### ISSUE TITLE
mlock in syslog as service - but not when I run at bash

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1001]
I setup xmr-stak to run as systemd service.  It runs without flaw on my first machine, but for reasons unknown, my second machine throwing errors in /sys/var/syslog
```

Jan 27 07:27:50 r810d xmr-stak[4726]: [2018-01-27 07:27:49] : MEMORY ALLOC FAILED: mlock failed
Jan 27 07:27:50 r810d xmr-stak[4726]: message repeated 4 times: [ [2018-01-27 07:27:49] : MEMORY ALLOC FAILED: mlock failed]
```

When I run xmr-stak at command prompt, I do not get these memory lock errors.  Can someone advise what I have done wrong, and / or what I can do to help myself to correct this please?

**Comment by fireice-uk** [comment]
Systemd has its own ulimits, you need to increase the ulimit -l in the systemd script.
