### ISSUE TITLE
can it support Xeon Phi OpenCL Mode to mining?

### ISSUE THREAD

**Issue by SKlayer** [fireice-uk/xmr-stak#1002]
I try run native code on my KNC(Knight Corner) it runs 585H/S,275Watt。(Luk Miner) Phi 31s1p
but i think it if use opencl mode will be more faster. so can u make a verision to support xeon phi?

I want to improve my poor english...

**Comment by psychocrypt** [comment]
sry we do not own this type of hardware. You can compile the miner directly. KNL is only a normal CPU. 
Connect to the on board linux of the KNL with ssh and compile the miner direct on the KNL. You need to use the intel compiler.

**Comment by SKlayer** [comment]
i try to compile software on Xeon Phi. But too many assembly codes has error...
