### ISSUE TITLE
Freezes and crashes while mining

### ISSUE THREAD

**Issue by suchamoneypit** [fireice-uk/xmr-stak#1006]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

Using 2x e5-2670 Xeon CPUs. 16 cores total, hyperthreading disabled.
Using 1x MSI 970, 1x MSI 760

# Stability issue
  - Is the CPU or GPU overclocked?

No overclocking 

  - Is the Main memory of the CPU or GPU undervolted?

no memory overclock or undervolting

Im running Windows 10 Pro. Every time I run the miner, it mines for a bit (few minutes), while pretty much freezing up my entire computer and with frequent complete freezes lasting 10-40 seconds long. Let it run overnight, It crashed and my entire PC turned off and stopped mining altogether.

**Comment by hl68fx** [comment]
I seem to have the same problem. Mining works for a few seconds up to serveral minutes. And sometimes it works for several hours without any problems.

Basic information
Type of the CPU.
Type of the GPU (if you try to miner with the GPU).
i3-6100 but not mining anymore because I thought it is the problem
3x Vega 64
HDMI dummy connected to iGPU

Stability issue
Is the  GPU overclocked?
![config](https://user-images.githubusercontent.com/7905756/35542548-d0d76cb4-0560-11e8-979f-fd41289ea479.PNG)


AMD.txt
  ```
  { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
	{ "index" : 1, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 1, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
	{ "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
```

I hope my information helps! :)

**Comment by psychocrypt** [comment]
Please set all clocks and the power for the gpu core to default values and
repeat your tests.

**Comment by suchamoneypit** [comment]
My clocks have been the default values from the very start.

I did some playing around, It still crashes, however I did the following changes and got good improvements in stability.

Changed "Bsleep" value on my GPU which powers my displays to 100. In the notes it even states that recommended value on a GUI system is 100, yet it does not auto-set this to GPU 0? I don't code myself but I assume its easy enough to either have it auto-detect this, or to ask if if your using a GUI system in the initial setup?

I also changed "affine_to_cpu" to "False" for my first CPU core, hoping keeping one core free it would not lag my system as bad in combination with the change I made to me GPU 0 with Bsleep.


I found I was able to run the system for 6-7 hours before i crashed overnight, before it lasted only around 20-40 min before crashing. However my CPU was still always at 100% usage on all cores so I either don't understand how to disable one core correctly (do i just delete the entire line?) or it didn't work.

**Comment by suchamoneypit** [comment]
I'm mining through Minergate pool and its worth noting that on my phone i occasionally get spammed that my worker has stopped working, this either means my PC crashed or something is wrong, and several times now i've gotten 2-5 notifications in rapid succession telling me it has stopped mining but when i remote into my server XMR stack is still mining and updating.

**Comment by JerichoJones** [comment]
XMR-STAK --noCPU

---
Take a look below for more interesting information when you run xmr-stak.exe --help  
  
Usage: xmr-stak.exe [OPTION]...  
  
  -h, --help            show this help  
  -v, --version         show version number  
  -V, --version-long    show long version number  
  -c, --config FILE     common miner configuration file  
  --noUAC               disable the UAC dialog  
  --currency NAME       currency to mine: monero or aeon  
  --noCPU               disable the CPU miner backend  
  --cpu FILE            CPU backend miner config file  
  --noAMD               disable the AMD miner backend  
  --amd FILE            AMD backend miner config file  
  --noNVIDIA            disable the NVIDIA miner backend  
  --nvidia FILE         NVIDIA backend miner config file  
  
The following options can be used for automatic start without a guided config,  
If config exists then this pool will be top priority.  
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333  
  -O, --tls-url URL     TLS pool url and port, e.g. pool.usxmrpool.com:10443  
  -u, --user USERNAME   pool user name or wallet address  
  -p, --pass PASSWD     pool password, in the most cases x or empty ""  
  --use-nicehash        the pool should run in nicehash mode  
  
  
Environment variables:  
  
  XMRSTAK_NOWAIT        disable the dialog `Press any key to exit.  
                               for non UAC execution  
  
  ---
