### ISSUE TITLE
*MINOR* Version prints hash with 8 characters but GitHub only shows 7 characters

### ISSUE THREAD

**Issue by jacobgc** [fireice-uk/xmr-stak#1007]
Very minor bug but the --version command outputs the first 8 characters of the git commit hash, however GitHub shows 7 characters

**Comment by fireice-uk** [comment]
Git (not to be confused with GitHub) will accept any prefix that is unique to the repo, so if you don't have a lot of commits even 4 characters will do. Actual commit hash is 32 characters long.

**Comment by thumbcore** [comment]
> Actual commit hash is 32 characters long.

Nitpicky stranger here... If you count the long commit hash, you'll see there are 40 characters. :)
