### ISSUE TITLE
Uninstalling/Re-Installing

### ISSUE THREAD

**Issue by George33** [fireice-uk/xmr-stak#1008]
I'm on Windows 10.  I'm not compiling but using the current executable.  

Amidst trying to get drivers to work and doing other configurations, I intentionally deleted the folder containing the xmr-stak.exe and the config files.  Now, when I attempt to re-extract xmr-stak-win64.zip once again in order to replace the deleted files, the new folder only shows the libeay32.dll and ssleay32.dll files but not the .exe file or any config files.  Is there a simple way to uninstall or delete all the files and start again fresh?  I'm afraid that I've already screwed up the environment variables trying to unpack it to different folders.

P.S.  I've been paying my 2%

Cheers

**Comment by psychocrypt** [comment]
Your anti virus software is removing the binary files. Please check the quarantine folder of your protection software and add an exaption for xmr-stak and the shipped dll files.
