### ISSUE TITLE
xmr-stak.exe has stopped working

### ISSUE THREAD

**Issue by SuperOP535** [fireice-uk/xmr-stak#1012]
OS: Windows 10 64-bit
RAM: 8 GB
Currency: monero
Nicehash: no
TLS: no

The miner instantly freezes and the classic "xmr-stack.exe has stopped working" popup appears.

I run xmr-stak with xmr-stak.exe --noNVIDIA --noCPU

If I replace --noCPU with --noAMD it works fine so I don't know why it doesn't want to work with the GPU

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. AMD A6 6400K APU with Radeon(tm) HD Graphics 3.90 GHz
  - Type of the GPU (if you try to miner with the GPU). AMD Radeon R7 240

# Issue with the execution
  - Do you compiled the miner by our own? no
  ```
  run `./xmr-stak --version-long` and add the output here. xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here. clinfo.exe has stopped working popup
  ```

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? ?????

**Comment by psychocrypt** [comment]
This is an driver issue. Please reinstall you driver.
