### ISSUE TITLE
hwloc: memory pinned

### ISSUE THREAD

**Issue by EnricoSx** [fireice-uk/xmr-stak#1019]
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1680934/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1680935/nvidia.txt)

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. xeon E3-1240 v5 
 - 16 gb ram
  - Type of the GPU (if you try to miner with the GPU). Quadro P2000 Memory 5 GB GDDR5
 - edit gpedit for large page
 - run xmrstak as administrator
 - no antivirus
- nvidia driver 23.21.13.8816
- same issue in many other windows pc with different gpu, cpu, memory...

# Compile issues
  - Which OS do you use? windows 10 64 bit 1709

# Issue with the execution
  - Do you compiled the miner by our own? NO
  ```
  run `./xmr-stak --version-long` and add the output here
Version: xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20
  ```

# Stability issue
  - Is the CPU or GPU overclocked? NO
  - Is the Main memory of the CPU or GPU undervolted? NO

**Comment by nsummy** [comment]
What is the issue you having exactly?  hwloc: memory pinned  is not an error message.
