### ISSUE TITLE
Card #12 having very low hashrate on 12GPU Rig

### ISSUE THREAD

**Issue by hoyanf** [fireice-uk/xmr-stak#102]
Hi, having issue on card #12 when using 12 GPU rig.

HASHRATE REPORT
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 412.6 | 412.1 | 412.3 |  1 | 412.8 | 412.8 | 412.7 |
|  2 | 413.1 | 413.1 | 413.0 |  3 | 412.8 | 412.8 | 412.6 |
|  4 | 412.8 | 412.8 | 412.6 |  5 | 412.5 | 412.6 | 412.5 |
|  6 | 412.8 | 412.8 | 412.2 |  7 | 413.2 | 413.2 | 412.5 |
|  8 | 412.9 | 412.8 | 412.5 |  9 | 412.9 | 412.9 | 412.7 |
| 10 | 417.6 | 417.6 | 417.5 | 11 | 417.4 | 416.5 | 417.3 |
| 12 | 57.3 | 57.1 | 57.1 |
-----------------------------------------------------
Totals:   5020.6 5018.8 5017.6 H/s
Highest:  5021.7 H/s

Using Ubuntu 16.04 with current release xmr-stak. Have no issues on xmr-stak-amd current release.

`uname -a
Linux mm-miner01 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Thanks

**Comment by psychocrypt** [comment]
NVIDIA or AMD gpus? Which OS?

**Comment by psychocrypt** [comment]
Could it be that this is the cpu. Because we begin to count with zero. This
means gpu 0-11 are gpus and than the cpus are countet.

To run without cpu usage start: xmr-stak --noCPU or emty the thread config
in cpu.txt

**Comment by psychocrypt** [comment]
With #104 the hash report will be split the different backends.

**Comment by hoyanf** [comment]
Sorry my bad... sleepy eyes, diff timezone... anyway thanks for the reply...

Only 1 request if possible to add ver no on webui.

Thanks again
