### ISSUE TITLE
miningpoolhub: CONNECT error: GetAddrInfo: Name or service not known

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1020]
XMR-STAK has worked very well for me testing to connect to various pools SO FAR.  Except this ONE has me stuck over a day of my troubleshooting.  I feel like my efforts are getting exhausted with google & bitcoin forum searches.

I went over the site setup instructions thoroughly.  XMR-STAK is listed on their site as well.
```
"pool_list" :
[
{	"pool_address" : "us-east.cryptonight-hub.miningpoolhub.com:20580",	"wallet_address" : "myusername.myworker", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],
```
I was hoping anyone had some advice on what I a could be doing wrong or where to proceed with troubleshooting.

**Comment by williampmills** [comment]
Try with the address specified to use ssl:

ssl://us-east.cryptonight-hub.miningpoolhub.com:20580

It may need the ssl:// at the start to work with their daemons...

Just a guess though.

**Comment by pruivo** [comment]
it works fine for me. here is my configuration
```
"pool_list" :
[
        {"pool_address" : "stratum+tcp://europe.cryptonight-hub.miningpoolhub.com:20596", "wallet_address" : "username.worker", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],
```

**Comment by DrStein99** [comment]
williampmills:
I did not try the stratum+ssl//___________ I tried stratum+tls//__________ 

pruivo:
This looks like the default setup.  I am certain I tried this many times.  I could have been frustrated and made a mistake.  I will try again.

**Comment by DrStein99** [comment]
I tested, and it worked.  I do not know what I was doing wrong, thank you for help.  I know for certain, I did not put the "stratum+tls//" in front of the pool address.  Thank you.
