### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JerichoJones** [fireice-uk/xmr-stak#1021]
---

Intel x5650 x2
AMD RADEON RX 64
AMD RADEON Vega Frontier Edition
Version: xmr_stak/2.2.0/dded06a3/unknown/win/nvidia_amd_cpu/aeon_monero/20
HASHRATE REPORT _ CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   34.7 |   37.5 |   38.0 |  1 |   35.3 |   37.8 |   38.2 |
|  2 |   35.0 |   37.7 |   38.1 |  3 |   34.7 |   37.6 |   38.1 |
|  4 |   36.5 |   39.3 |   39.7 |  5 |   36.6 |   39.3 |   39.7 |
|  6 |   35.2 |   37.6 |   38.0 |  7 |   35.5 |   37.7 |   38.1 |
|  8 |   35.4 |   37.7 |   38.1 |  9 |   35.2 |   37.6 |   38.0 |
| 10 |   36.9 |   39.3 |   39.7 | 11 |   36.7 |   39.2 |   39.6 |
Totals (CPU):   427.9  458.2  463.3 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  945.7 | 1057.7 | 1073.0 |  1 |  912.2 |  991.5 | 1001.7 |
|  2 |  826.7 |  922.3 |  932.0 |  3 |  963.3 | 1049.5 | 1060.1 |
Totals (AMD):  3647.9 4021.0 4066.8 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Totals (ALL):   4075.8 4479.2 4530.1 H/s
Highest:  4694.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Version: xmr_stak/2.2.0/0a142471/unknown/win/nvidia_amd_cpu/aeon_monero/20
HASHRATE REPORT _ CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   38.1 |   38.1 |   38.0 |  1 |   38.1 |   38.1 |   38.1 |
|  2 |   38.2 |   38.2 |   38.2 |  3 |   38.2 |   38.2 |   38.2 |
|  4 |   39.8 |   39.8 |   39.8 |  5 |   39.8 |   39.8 |   39.8 |
|  6 |   38.1 |   38.1 |   38.0 |  7 |   38.1 |   38.1 |   38.1 |
|  8 |   37.9 |   37.8 |   37.8 |  9 |   38.1 |   38.1 |   38.1 |
| 10 |   39.6 |   39.5 |   39.5 | 11 |   39.4 |   39.4 |   39.4 |
Totals (CPU):   463.4  463.3  462.9 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1072.9 | 1076.3 | 1074.7 |  1 | 1001.8 | 1003.0 | 1003.1 |
|  2 |  958.2 |  954.9 |  949.7 |  3 | 1090.5 | 1087.2 | 1080.3 |
Totals (AMD):  4123.5 4121.4 4107.7 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Totals (ALL):   4586.9 4584.6 4570.6 H/s
Highest:  4687.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

---

Intel 5820k
AMD Vega 64
NVIDIA 980SC

Version: xmr-stak/2.2.0/dded06a3/unknown/win/nvidia-amd-cpu/aeon-monero/20
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   60.1 |   62.7 |   64.3 |  1 |   61.7 |   64.4 |   66.1 |
|  2 |   61.2 |   63.3 |   64.7 |  3 |   58.4 |   61.4 |   63.1 |
|  4 |   60.7 |   63.3 |   64.5 |  5 |   61.0 |   63.8 |   65.7 |
Totals (CPU):   363.1  378.9  388.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1091.0 | 1091.9 | 1091.8 |  1 | 1092.9 | 1092.0 | 1091.8 |
Totals (AMD):  2183.9 2183.8 2183.6 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  520.9 |  521.3 |  521.1 |
Totals (NVIDIA):   520.9  521.3  521.1 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
Totals (ALL):   3068.0 3084.0 3093.1 H/s
Highest:  3156.1 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--

Version: xmr-stak/2.2.0/0a142471/unknown/win/nvidia-amd-cpu/aeon-monero/20
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   51.9 |   52.8 |   52.3 |  1 |   51.6 |   52.4 |   51.8 |
|  2 |   51.3 |   51.8 |   51.2 |  3 |   52.9 |   53.8 |   53.1 |
|  4 |   52.2 |   52.8 |   52.2 |  5 |   52.5 |   53.6 |   53.0 |
Totals (CPU):   312.4  317.3  313.6 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1073.3 | 1073.0 | 1072.8 |  1 | 1073.6 | 1072.6 | 1072.8 |
Totals (AMD):  2147.0 2145.6 2145.6 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  521.7 |  521.3 |  520.3 |
Totals (NVIDIA):   521.7  521.3  520.3 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--
Totals (ALL):   2981.0 2984.1 2979.5 H/s
Highest:  3003.1 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_--

---

Ryzen 1700x
NVIDIA 1050ti
AMD RADEON RX 64 Liquid

Version: xmr_stak/2.2.0/dded06a3/unknown/win/nvidia_amd_cpu/aeon_monero/20
HASHRATE REPORT _ CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   65.7 |   60.7 |   70.9 |  1 |   66.7 |   63.5 |   71.4 |
|  2 |   66.7 |   63.7 |   71.4 |  3 |   67.2 |   64.3 |   71.4 |
|  4 |   68.4 |   65.7 |   71.5 |  5 |   68.5 |   66.5 |   71.5 |
|  6 |   68.8 |   66.4 |   71.5 |  7 |   69.1 |   66.9 |   71.5 |
Totals (CPU):   541.1  517.9  571.1 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1026.9 | 1027.3 | 1027.5 |  1 | 1098.9 | 1100.5 | 1100.9 |
Totals (AMD):  2125.8 2127.8 2128.4 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  311.1 |  312.3 |  315.3 |
Totals (NVIDIA):   311.1  312.3  315.3 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Totals (ALL):   2978.1 2958.0 3014.8 H/s
Highest:  3031.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Version: xmr_stak/2.2.0/0a142471/unknown/win/nvidia_amd_cpu/aeon_monero/20
HASHRATE REPORT _ CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   71.6 |   71.8 |   71.5 |  1 |   71.9 |   72.1 |   71.9 |
|  2 |   72.0 |   72.1 |   71.9 |  3 |   72.0 |   72.1 |   71.9 |
|  4 |   71.9 |   72.0 |   71.9 |  5 |   72.0 |   72.0 |   71.9 |
|  6 |   71.8 |   71.9 |   71.8 |  7 |   71.9 |   72.0 |   71.8 |
Totals (CPU):   575.0  575.8  574.6 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1026.3 | 1026.2 | 1026.1 |  1 | 1101.4 | 1099.3 | 1099.4 |
Totals (AMD):  2127.7 2125.5 2125.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
HASHRATE REPORT _ NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  315.6 |  315.6 |  315.5 |
Totals (NVIDIA):   315.6  315.6  315.5 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
Totals (ALL):   3018.3 3016.9 3015.6 H/s
Highest:  3026.3 H/s
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

---

**Comment by DrStein99** [comment]
I run (1) Intel x5650.  Absolute top I get is 232.2 H/s.  Your benchmark for (2) x5650 is spot on.  Been trying to learn how to improve the efficiency and develop some more hashes, but it seems I'm at the top of the level when I compare my stats of same hardware to other known rigs.
