### ISSUE TITLE
Autorun and silent mode

### ISSUE THREAD

**Issue by YaWazowski** [fireice-uk/xmr-stak#1022]
Hello,

How would I add the autorun and silent mode (hide window) features like in XMR-Stack-CPU version?

Thanks,
Mike

**Comment by Omgthehorror** [comment]
It's a shady topic but if you're on Windows, you can use Task Scheduler.

**Comment by ChaosMarc** [comment]
Or you could create a service with a tool like [nssm](https://nssm.cc/)
