### ISSUE TITLE
The way to Optimization cpu hashrate

### ISSUE THREAD

**Issue by sx5486510** [fireice-uk/xmr-stak#1025]
CPU: I5 3470, L3 is 6M.
OS: Windows 7

The exe is download form https://github.com/fireice-uk/xmr-stak/releases
version: v2.1.0

if i set CPU with three thread, i got 125H /s, cpu usage 75%
`
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],
`

if i set CPU with two thread, i got 120H /s, cpu usage 50%
`
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],
`
The optimal number of threads should be 6/2=3.  I don`t know why two threads looks better.

The number of threads is greater than the number of cores is a waste?

**Comment by JayWalker512** [comment]
Well, 125 H/s > 120 H/s, so 3 threads is clearly faster for your CPU. Nobody said it would be MUCH faster ;)

**Comment by sx5486510** [comment]
I thank 125≈120,  I do not think it's faster.
Reference L3(6MB) of the CPU, i can create 3 thread, but I can't get the ideal result and the CPU haven't reached 100%

Where is the bottleneck?

**Comment by DrStein99** [comment]
5 H/s is something that can actually be affected by any other process on that machine.  For example: I lose around 10% of my hash rate just by opening a web browser to monitor stats.

**Comment by JerichoJones** [comment]
If you have Hyper-threading enabled the best you will see is 50% and that is normal.
