### ISSUE TITLE
May i could mining with GPU only?(don't use CPU)

### ISSUE THREAD

**Issue by PKingHot** [fireice-uk/xmr-stak#1027]
I konw this version combine cpu and gpu mining, but i only wish to use gpu only. How to do that?
cpu mining will slow down the computer, i wish to close it.
thank you all.

**Comment by psychocrypt** [comment]
add --noCPU as command line parameter to the miner.

**Comment by SR2k** [comment]
use `--noCPU` parameter, or simply edit `config.txt` and remove all threads.
