### ISSUE TITLE
Bfactor & Bsleep

### ISSUE THREAD

**Issue by kenshin6353** [fireice-uk/xmr-stak#1029]
these days im doing tuning for my 1060 6gb 
bfactor is 6...abit laggy but im ok with it....very stable for mining
i wonder if i reduce blseep.... to 10.... will it kill my gpu? though it's running stable...

**Comment by psychocrypt** [comment]
bsleep means only that there are small breaks between the tasks for the
gpu. The unit of bsleep is millisecond.
lower bsleep can increase the hash rate but maybe will ceeate a laggy
system where youtube and co will not run smooth during you are mining.

**Comment by kenshin6353** [comment]
ok... tqvm :)  btw...
