### ISSUE TITLE
buffer not being flushed

### ISSUE THREAD

**Issue by jacobgc** [fireice-uk/xmr-stak#1034]
I'm trying to create a GUI for this program and when trying to get the stdout from the program and I believe I'm having some difficulties due to the program not flushing the standard output. If I knew how and where this should be done in C++ I would create a fork and a merge request. 

> Also keep in mind that the callback will not be called, whenever the program outputs a newline. If you want to receive "events" from the child process, this process must flush the buffer (flush(stdout); in C) in order to fire events in Node.js

**Comment by psychocrypt** [comment]
Activate fluschin in config.txt

**Comment by jacobgc** [comment]
Oh wow that’s in there, I swear I’ve looked through the config like 3 times
🤔 thanks a bunch though!
