### ISSUE TITLE
dual pool mining

### ISSUE THREAD

**Issue by STk3000** [fireice-uk/xmr-stak#1038]
hello,

Can we have a 90% and 10% dual pool mining?

Saw in github that there was a weighting system but in the new unified stak miner it's just failover (mining priority, kicks into effect only when main pool is down).

I want to use the same miner to mine 80% ETN in an electroneum pool and then 20% XMR (or another custom combination) in supportxmr pool (just because XMR is a much older coin and cannot dissapear while ETN can always go belly up).

Does current version support this?

**Comment by psychocrypt** [comment]
This feature is currently not implemented. IMO it will come but not in the
near time.

**Comment by bobbieltd** [comment]
xmr-node-proxy can help you to mine 90% 10% on two coins. But with only one miner, it’s not recommended to use proxy (better 50+ miners ).

**Comment by rwebb0418** [comment]
@bobbieltd how can you do two coins on xmr-node-proxy?  I'm trying to figure it out, but the best I can do is split between pools, but just one coin.

**Comment by bobbieltd** [comment]
For XMR and ETN, it’s not a big deal. Just putting both pools the same coin (“xmr” or “etn”). I think it’s not your case. For ITNS, I need to modify the code to switch cnUtil. I don’t have free time yet to play and test it with my xmr-node-proxy fork. I’ll keep you in touch later.

**Comment by azirmaozao** [comment]
I'm setting up a mining rig for a friend who agrees to pay me 10% is there a way to set this up so it's the same coin ETN for example and have 90% go to one coin and 10% to another?

**Comment by bobbieltd** [comment]
@azirmaozao Everything is possible. However, I’m curious why you don’t ask him to give you back 10% every month ( by coins tranfer ). If you do shady thing (yeah, bad behaviour), it’s better that you setup a proxy, 90% ETN to him, 10% ETN to you.

**Comment by azirmaozao** [comment]
@bobbieltd nothing shady. shady does not encourage longevity.  simply looking to automate.  I'm hosting the rig. setting up a biz, building, hosting rigs.

**Comment by bobbieltd** [comment]
@rwebb0418 not big deal, I tweaked abit my fork to mine XMR/ETN/ITNS .... at the same time. Can you test it with ITNS ( one my server, it works for sharing between ITNS and other coins) and report back to me ? To share proxy to multiple coin, put “auto” as coin (see config_example.json). Github : https://github.com/bobbieltd/xmr-node-proxy

**Comment by rwebb0418** [comment]
@bobbieltd Awesome, I'll get it built right away and let you know

**Comment by rwebb0418** [comment]
@bobbieltd Yep I can confirm that it does work.  It's a little sketchy on the split when you're below 10 miners, but when you hit 10 miners it breaks pretty close to the settings in config.json file.  Thanks muchly for the hard work!

**Comment by bobbieltd** [comment]
@rwebb0418 You’re welcome. It’s only small tweak.
