### ISSUE TITLE
Centralized STATS

### ISSUE THREAD

**Issue by mlnishiya** [fireice-uk/xmr-stak#1039]
I haver 5 computers working 4 me..

Can i centralize stats on one of that computers?

4 example:
worker 1: 500h/s
worker 2: 500h/s
worker 3: 500h/s
host centralized shows 1500h/s
10s 60s 15m

? 

i think can we use a AJAX in WEBSERVICE to collect all data n show it all in a single webview

just adding worker IP:port

worker 1: 192.168.0.1:16000
worker 2: 192.168.0.2:16000
worker 3: 192.168.0.3:16000
host: 192.168.0.4:16000 (collection of all workers)

note:
"httpd_port" : 0,
it should be up
"httpd_port" : 16000,

i'm doing it with my own web server, n some php code... using javascript to calc infos i want... i think it can be native...

**Comment by JerichoJones** [comment]
Leverage the JSON API of STAK.

http://localhost:<port>/api.json

**Comment by mlnishiya** [comment]
well.. its should me nice Jericho
but native web service deny access from crossdomain requests... so if i want to show many workers stats on a single page, its not possible...

`Warning: file_get_contents(http://localhost:16000/api.json): failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized in C:\myxamppath\StatusWebView\json.php on line 3
NULL `

**Comment by JerichoJones** [comment]
There are workarounds... but...

https://www.red-gate.com/simple-talk/dotnet/asp-net/calling-cross-domain-web-services-in-ajax/

**Comment by hobbsh** [comment]
I wrote a script that pairs with a graphite/grafana installation where the aggregation would be done in grafana: 

[Imgur](https://i.imgur.com/iFUzzjG.png)

**Comment by mlnishiya** [comment]
@hobbsh that is awesome... do have a standalone .zip version just to test?

And... it monitoring just one Worker... is it possible to add many of it? For exemple a

array(array("host"=>"192.168.1.2:16000", "desc" => "personal pc"), array("host" => "192.168.1.3:16000", "desc" => "server"), array("host" => "200.0.75.1", "remote 01"))

So that will centralize all hashcounts in a same webview
