### ISSUE TITLE
Miner stops working even though the gpus still work full speed 6x Vega 64

### ISSUE THREAD

**Issue by eternitybtc** [fireice-uk/xmr-stak#1041]
I have an issue where the miner stops getting new shares , the hashrate goes to 0h/s even though the gpus are keep working on full speed.

I changed the miner and used cast xmr , the problem was the same even though there i could see that gpu 5 goes 0 h/s .

After playing on overdrivenTools and applying those settings :  http://prntscr.com/iacgg7
The miner kept going good for 5 days but then it stops working again. 

There is no specific pattern on how it stops it could be 2 hours - 24 hours .

I am desperate in need of help atm . Thank you.

**Comment by hchan123** [comment]
I had the same issue when the OC and/or undervolt was too aggressive.  Try
backing down memory to 1075.
