### ISSUE TITLE
VIRTUAL 4010384, 32gb of RAM.  Why ?

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1045]
System summary:
  Ubuntu 16.04 (server, no GUI)
  xmr-stak compiled from git clone
  (4) XEON E7 4850, 10 cores + hyperthreading
  32 gb DDR3 ram
----

If I am correct, VIRTUAL is swap memory - which is the slowest type that needs to cache to disk.  Am I wrong?  My system reporting a suspiciously large file to disk.  Is something configured wrong by me?  I prefer to use the 32gb of ram which is idling with nothing to do, while the hard disk gets a big exercise.
Please advise.

TOP reports:
```
top - 23:35:11 up 4 min,  1 user,  load average: 47.21, 26.29, 10.82
Tasks: 629 total,   1 running, 628 sleeping,   0 stopped,   0 zombie
%Cpu(s): 60.0 us,  0.0 sy,  0.0 ni, 40.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32916308 total, 31288004 free,  1353096 used,   275208 buff/cache
KiB Swap:   732156 total,   732156 free,        0 used. 31125516 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2327 drstein+  20   0 4010384 107344   8172 S  4798  0.3 191:13.21 xmr-stak
 2603 drstein+  20   0   41032   4212   3072 R   1.0  0.0   0:00.34 top
 2395 root      20   0   19692   2176   1776 S   0.3  0.0   0:00.08 irqbalance
    1 root      20   0   38124   6088   4004 S   0.0  0.0   0:06.52 systemd
```

**Comment by psychocrypt** [comment]
No virtual memory is no swapped memory on disk: https://serverfault.com/questions/138427/top-what-does-virtual-memory-size-mean-linux-ubuntu
