### ISSUE TITLE
Windows Admin Rights

### ISSUE THREAD

**Issue by BobbyGR** [fireice-uk/xmr-stak#1047]
Hey guys - I am trying to implement xmr-stak to AIOMiner (more fees collections for you! yay!) But during my testing I am unable to use xmr-stak for the simple reason that the user will need to hit Yes to run the application.  I have made a template config that I review the video cards they have and can fill out the config file and the pool setup file etc, but I can't find a way around it asking for admin rights.  I'm sure it's simple.  I was really hoping --noCPU would have done the trick as maybe that was the part making the call to need admin rights....so far no good.  Let me know if anything can be done!  Most likely i'm looking at pounding sand and telling Nvidia users it's just not possible :(

**Comment by JerichoJones** [comment]
xmr-stak --noUAC

---
Take a look below for more interesting information when you run xmr-stak.exe --help  
  
Usage: xmr-stak.exe [OPTION]...  
  
  -h, --help            show this help  
  -v, --version         show version number  
  -V, --version-long    show long version number  
  -c, --config FILE     common miner configuration file  
  --noUAC               disable the UAC dialog  
  --currency NAME       currency to mine: monero or aeon  
  --noCPU               disable the CPU miner backend  
  --cpu FILE            CPU backend miner config file  
  --noAMD               disable the AMD miner backend  
  --amd FILE            AMD backend miner config file  
  --noNVIDIA            disable the NVIDIA miner backend  
  --nvidia FILE         NVIDIA backend miner config file  
  
The following options can be used for automatic start without a guided config,  
If config exists then this pool will be top priority.  
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333  
  -O, --tls-url URL     TLS pool url and port, e.g. pool.usxmrpool.com:10443  
  -u, --user USERNAME   pool user name or wallet address  
  -p, --pass PASSWD     pool password, in the most cases x or empty ""  
  --use-nicehash        the pool should run in nicehash mode  
  
  
Environment variables:  
  
  XMRSTAK_NOWAIT        disable the dialog `Press any key to exit.  
                               for non UAC execution  
  
---

**Comment by BobbyGR** [comment]
I don't know how I missed this, any idea what the users will be missing out on if they don't have this running in UAC?

**Comment by JerichoJones** [comment]
I don't think they miss anything after the first run. I think you may need admin rights to enable Large Pages (I could be wrong). So aftet taht is done I don't think they are needed.
