### ISSUE TITLE
Install guide for xmr-stak-cpu for Ubuntu Server 17.*

### ISSUE THREAD

**Issue by cat007mine** [fireice-uk/xmr-stak#1050]
Hi.
Sorry if this is not the right place - but I'm trying to find a step by step install guide for ubuntu server 17.
I've got a Windows miner running but would like to use a linux server that doesn't consume so many resources for a desktop environment etc.

Please and thank you
Hunt

**Comment by elproducto** [comment]
http://www.cryptobadger.com/2017/04/build-ethereum-mining-rig-linux/ only thing you will need to change is the miner or Linux distribution being used.
