### ISSUE TITLE
How to setup encrypted connection to a pool?

### ISSUE THREAD

**Issue by alextrezvy** [fireice-uk/xmr-stak#1053]
OS Windows 7. Tried to connect, but get socket errors:

> [2018-02-08 20:26:10] : Pool pool.supportxmr.com:443 connected. Logging in...
> [2018-02-08 20:26:10] : SOCKET ERROR - [pool.supportxmr.com:443] RECEIVE error:
> socket closed

Have read about 'tls', but don't know where to get 'fingerprint'.

**Comment by bobbieltd** [comment]
It’s SSL , not TLS
