### ISSUE TITLE
I've modified this to mine QRL, would this be something you'd merge upstream?

### ISSUE THREAD

**Issue by randomshinichi** [fireice-uk/xmr-stak#1054]
I've gotten this to mine QRL on the testnet. The relevant changes are:
* roll the nonce at offset 0 (instead of 39)

and that's it.
Since you have if/elses for Cryptonight-lite, I was wondering if this would be something you'd merge upstream?

**Comment by globsch** [comment]
yes

**Comment by dko** [comment]
@randomshinichi I cloned your qrl branch forthe qrl testnet and am running into .lson error:
```Pool 139.59.135.167:9000 connected. Logging in...
[2018-02-15 19:53:10] : SOCKET ERROR - [139.59.135.167:9000] PARSE error: Invalid JSON

**Comment by psychocrypt** [comment]
which algorithm is used by  QRL and whats the current global hash rate.
