### ISSUE TITLE
"tls_secure_algo" in main config -VS "use_tls" in pool config

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1056]
Does anyone here know what the difference between
"tls_secure_algo" (in the main config)

and

"use_tls" (also in the config file, under each pool definition in "pool_list" ?

I tried to test this on my own.  I can not tell if the servers I am test attach are temporarily banning me at this point due to so many of my repeat failed attempts. 

----
There also appears to be a duplicate setting in the main config:
"nicehash_nonce" 	(true/false) 
-AND/OR !?!? in "pool _list" definition:
"use_nicehash"

----

This is confusing for anyone who wants to attach to nicehash as first priority, then use TLS secure pool as fail-over.  I can not tell if I am to set the nicehash and TLS in both the main and the pool setting or just the pool setting.  Please advise.

**Comment by fireice-uk** [comment]
tls_secure_algo set to true means the miner will configure openssl to reject insecure TLS settings, this is a global setting.

use_tls is per-pool and simply means to use TLS.

If you have multiple pools with TLS and one of them doesn't support secure algorithms then you need to set tls_secure_algo to false.
