### ISSUE TITLE
High Pool ping time 

### ISSUE THREAD

**Issue by elproducto** [fireice-uk/xmr-stak#1057]
I am running XMR-Stak on an Ubuntu 16.0.4.  I have noticed high pool ping time numbers within the miner.  I also noticed I am getting pool rejecting shares submitted with ping time being high. When I ping the pool server via terminal, ping numbers shown are significantly less.   I am using wireless connection, but also got the same result with a wired connection.  What could cause this discrepancy?

CONNECTION REPORT
Pool address    : gulf.moneroocean.stream:10032
Connected since : 2018-02-09 03:43:53
Pool ping time  : 220 ms

Network error log:
Yay! No errors.

**Terminal Ping**
`elproducto@MINE1:~$ ping gulf.moneroocean.stream
PING monerooceans.stream (142.44.240.132) 56(84) bytes of data.
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=1 ttl=50 time=20.6 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=2 ttl=50 time=19.3 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=4 ttl=50 time=20.5 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=5 ttl=50 time=20.7 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=6 ttl=50 time=21.5 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=7 ttl=50 time=20.6 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=8 ttl=50 time=19.5 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=10 ttl=50 time=24.2 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=11 ttl=50 time=25.8 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=12 ttl=50 time=21.7 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=13 ttl=50 time=20.9 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=14 ttl=50 time=29.8 ms
64 bytes from 132.ip-142-44-240.net (142.44.240.132): icmp_seq=15 ttl=50 time=20.0 ms
^C
--- monerooceans.stream ping statistics ---
15 packets transmitted, 13 received, 13% packet loss, time 14035ms
rtt min/avg/max/mdev = 19.376/21.984/29.851/2.872 ms`

**Comment by MoneroOcean** [comment]
What is your ping time to us.moneroocean.stream? 142.44.240.132 is just pool gateway server that proxy your connection to real pool leaf node server (in US).

**Comment by elproducto** [comment]
MonoeroOcean,

I did not mean to single you out, but your pool is what I am using.  You provide a great service.  Ping information below.

Connection Report
Pool address	gulf.moneroocean.stream:10032
Connected since	2018-02-09 11:39:35
Pool ping time	140 ms

`us.moneroocean.stream (45.32.81.217) 56(84) bytes of data.
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=1 ttl=51 time=97.5 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=2 ttl=51 time=94.1 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=3 ttl=51 time=93.2 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=4 ttl=51 time=95.6 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=5 ttl=51 time=94.0 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=6 ttl=51 time=95.1 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=7 ttl=51 time=97.6 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=8 ttl=51 time=94.6 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=9 ttl=51 time=93.2 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=10 ttl=51 time=94.2 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=11 ttl=51 time=93.9 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=12 ttl=51 time=95.2 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=13 ttl=51 time=132 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=14 ttl=51 time=93.1 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=15 ttl=51 time=94.6 ms
64 bytes from 45.32.81.217.vultr.com (45.32.81.217): icmp_seq=16 ttl=51 time=93.5 ms`

**Comment by psychocrypt** [comment]
I need to check but I think the time in xmr-stack is the pool response time
if a share is sendet. This includes the data transfere and the pool
validation time.

**Comment by bobbieltd** [comment]
In my opinion, MoneroOcean is the best pool. I’m interested in this issue. I’ll test it later ( I often don’t look at ping ). But if xmr-stak cause high ping with MoneroOcean.stream by some how, it can cause huge bad effect on his pool’s growth.

**Comment by MoneroOcean** [comment]
No worries)

142.44.240.132 is OVH US East cost (actually in Canada) gateway that basically proxies connection to real leaf node on US west coast (near us.moneroocean.stream), so compared to ping xmr-stak shows you more correct response time because it also take into account actual leaf server response time.

**Comment by elproducto** [comment]
OK cool can I get the address for real leaf node to compare ping times.

**Comment by MoneroOcean** [comment]
You can try us.moneroocean.stream.
