### ISSUE TITLE
Failed to open config file after creating one (docker)

### ISSUE THREAD

**Issue by adekbadek** [fireice-uk/xmr-stak#1059]
I'm on macOS (10.13.2) and tried to run the cli miner with docker (17.04.0-ce) using [these instructions](https://github.com/fireice-uk/xmr-stak/blob/master/doc/usage.md#docker-image-usage).
The config creation prompts go fine, and then I hit this wall:
```
Configuration stored in file 'config.txt'
[2018-02-09 10:25:00] : Failed to open config file config.txt.
```
I then entered re-ran the container with `--entrypoint=/bin/bash` and executed `/usr/local/bin/xmr-stak` from there, but to the same effect

**Comment by psychocrypt** [comment]
By default the config files will be written ro the folder of the xmr-stak
binary. I think you have no rights to create files in this directory.
Please run xmr-stak -h and check the options to define the config file
places and names

**Comment by adekbadek** [comment]
Changing permissions on the directory helped, thanks!

**Comment by Eddie2312** [comment]
how do you "run xmr-stak -h"?
