### ISSUE TITLE
WIN_UAC

### ISSUE THREAD

**Issue by true-datura** [fireice-uk/xmr-stak#106]
Compiling with options:
`cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DXMR-STAK_CURRENCY=monero -DMICROHTTPD_ENABLE=OFF -WIN_UAC=OFF ..`
But binary still triggers UAC.

**Comment by fireice-uk** [comment]
It needs to be `-DWIN_UAC=OFF` like every cmake option.

**Comment by true-datura** [comment]
Oh, sorry. Will try soon.

**Comment by psychocrypt** [comment]
Solved missing `-D`
