### ISSUE TITLE
Rig freeze and restart after 5 minutes.

### ISSUE THREAD

**Issue by Deno028** [fireice-uk/xmr-stak#1060]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
Core i7 Haswell
  - Type of the GPU (if you try to miner with the GPU).
Nitro+ Rx580

# Compile issues
  - Which OS do you use?
Windows
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
Yes Overclocked/flash bios mod 1100-2100
  - Is the Main memory of the CPU or GPU undervolted?
Yes 

I've mined months with ETH. I test on Cryptonight after couple of hours mining good it get restart rig after 5 minutes running.
I used the 2.2.0 version of xmr-stak
Change back to Claymore(ETH) it working normally.

I try disable overclock/undervolted/dual thread. But its still getting error.

**Comment by psychocrypt** [comment]
please try to mine with intensity 512. But it looks like a powet or heating
issue.

**Comment by Deno028** [comment]
Yes its seem ok now. After I set intensity to 820 and descrease cclock/mclock to : 1100-2000. It running ok for a day. 

Heating is not the cause I reckon because it just around 50C. 

Why ETH mining setting good at 1150-2150.
