### ISSUE TITLE
Sequentially decreasing hash rates per GPU (6)

### ISSUE THREAD

**Issue by nuglas** [fireice-uk/xmr-stak#1061]
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   43.3 |   42.2 |   40.5 |
---------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  490.8 |  491.8 |  491.8 |  1 |  492.3 |  491.9 |  491.8 |
|  2 |  479.2 |  479.1 |  479.1 |  3 |  479.3 |  479.2 |  479.1 |
|  4 |  460.8 |  461.1 |  461.0 |  5 |  461.5 |  461.2 |  461.0 |
|  6 |  457.1 |  457.2 |  457.1 |  7 |  457.3 |  457.2 |  457.1 |
|  8 |  447.7 |  447.6 |  447.5 |  9 |  447.8 |  447.5 |  447.5 |
| 10 |  373.3 |  376.2 |  376.7 | 11 |  378.9 |  377.0 |  376.8 |
-----------------------------------------------------
Totals:   5469.5 5469.3 5466.9 H/s
Highest:  5499.6 H/s

Part of me is not sure I want to mess with things, because I've finally got 6 GPU stable at ~5400 H/S.
Part of me thinks I should be closer to 6000 H/S  :)

The Part that really drives me crazy is seeing this sequential drop in hash rate. Running other miners I always had the varying hash rates per card, but not in a sequential order like this!

Any ideas if there is an issue I can work on or if this is just the way xmr-stak reports hash rates?

Thanks!

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
Intel Celeron 2.0
  - Type of the GPU (if you try to miner with the GPU).
(6) RX 580

# Stability issue
  - Is the CPU or GPU overclocked?
GPU are all overclocked slightly
  - Is the Main memory of the CPU or GPU undervolted?
No

I did modify my AMD config as well, was able to get higher hash rates with below:
"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 0,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 0,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 1,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 1,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 2,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 2,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 3,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 3,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 4,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 4,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 5,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 5,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

**Comment by totallyG82** [comment]
What is the CPU load?

**Comment by hchan123** [comment]
Can you try turning off CPU mining?

**Comment by JerichoJones** [comment]
Turn off CPU mining.
