### ISSUE TITLE
different hashrates each restart

### ISSUE THREAD

**Issue by STk3000** [fireice-uk/xmr-stak#1063]
I am running a 5 x rx 560 2gb sapphire rig 

Tested every driver, win 7 and win 10 each. remained on win 10 blockchain

Mem OC 1950 mhz 850 v samsung
GPU UV UC 1100 860 Mhz 
16 cu version
modded bios with polaris bios editor one click memory timings

Running two threads on each 16 cu samsung card, 430 intensity each. This should generate 470h/s (235 h/s each thread) - this is my target and what claymore has to offer with extra fan noise, heat and power consumption. Picked stak because it's waaay better in every single option except that you have to tweak it allot to get the same hashrate. 

When i start it up most of the times 2 or 3 cards will run at 230 even 235h/s per thread which is awesome. Other cards will run 210 and even 200 h/s per thread which is very annoying. The problem is that i have to restart/reboot it several times to get 230 h/s on each thread for all of my gpus.

This does happen after 5-10 reboots (i reboot because i also do CPU mining with my fx8300 and memloc doesn't work if I just restart the miner and not the OS).

intensity higher than 430 will freeze stak and windows
lower intensity gives the same results until 415 when per thread hashrate drops to 225 maximum.

It's not always the same gpu with issues, stak randomly "picks" 2-3 cards and fux their hashrate 

Got a secondary rig with modded 14cu elpida 560s (from sapphire too), issue happens there aswell.

is there a fix?
Thanks,
C

**Comment by STk3000** [comment]
![screen shot 2018-02-13 at 00 47 25](https://user-images.githubusercontent.com/36141404/36124135-9deb7596-1057-11e8-9c57-4d840fdcad64.jpg)

**Comment by STk3000** [comment]
it's always random, sometimes just one sometimes two sometimes three and some very good times none...

**Comment by JerichoJones** [comment]
Disable CPU mining and see if it makes a difference.
