### ISSUE TITLE
FreeBSD 11.1 - hwloc: set_thisthread_membind not supported - how to fix?

### ISSUE THREAD

**Issue by agentpatience** [fireice-uk/xmr-stak#1064]
>Please provide as much as possible information to reproduce the issue.

Greetings from Canada!

I compiled your excellent software on my dual AMD 6376 system without error.
I do not use graphics cards on this system so I removed cuda and opencl requirements per your switches.

My question is, when I run xmr-stak bin on FreeBSD 11.1 I get error output:
hwloc: set_thisthread_membind not supported

Can you tell me what the work around is in basic terms? I don't understand what it is complaining about?

This error seems to manifest itself in a different way on ubuntu; where an entry is made to systemctl to increase huge pages: sysctl -w vm.nr_hugepages=128 and thus that entry to the system gets rid of it.

is there something to set like this in FreeBSD 11.1, this being the latest production release? 

I am not a expert programmer and I hope I gave you enough information. 

I appreciate your time to take a look at my ticket and I will donate to this project because XMR-STAK seems to produce the best hashes for me out of all the software I have tried so far. Top notch job guys - keep on going!

Warm regards,
Jeff
hi-tronics.ca

**Comment by agentpatience** [comment]
with this error my xmr-stak hashrate is as follows:
Totals:    335.7  335.8  335.7 H/s
Highest:   336.3 H/s

Where windows 10 gives me a steady 1040 h/s? what gives?

**Comment by agentpatience** [comment]
I found that FreeBSD 11.0 does the same thing aswell? Is there a workaround?

**Comment by JerichoJones** [comment]
[Search](https://duckduckgo.com/?q=freebsd+hugepages)
