### ISSUE TITLE
Issue running second GPU

### ISSUE THREAD

**Issue by matt1634** [fireice-uk/xmr-stak#1065]
Hello,

I'm running system noted below, but I get the following message when trying to use my second GPU, the 950 GTX. I have also gone into the nvidia file and manually added

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 950M architecture: 50
  //      memory: 2000/2022 MiB
  { "index" : 1,
    "threads" : 68, "blocks" : 15,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },

],

 which is a setting I got from the support pages, however, this doesnt seem to do anything. The miner continues with GPU 0 (1070ti) and CPU mining whilst the 950 is idle.

If you can offer any help it would be appreciated, total newbie here be gentle!

Thanks Matt

 message [2018-02-11 11:30:55] : Start mining: MONERO
WARNING: NVIDIA GPU 1: context cannot be created.
[2018-02-11 11:30:55] : WARNING: NVIDIA setup failed for GPU 1.

[2018-02-11 11:30:55] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2018-02-11 11:30:55] : Starting NVIDIA GPU thread 0, no affinity.
[2018-02-11 11:30:55] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-02-11 11:30:55] : WARNING: backend AMD disabled.

# Basic information
  - i5 6600k oc 4.5 ghz
  - ASUS Strix 1070ti  and EVGA 950 2gb s/c

# Compile issues
  - Windows 10
 
  add **all** commands you used and the **full** compile output here
  
/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1070 Ti architecture: 61
  //      memory: 6763/8192 MiB
  //      smx: 19
  { "index" : 0,
    "threads" : 22, "blocks" : 57,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

# Issue with the execution
  - Used Auto config
  ```

**Comment by totallyG82** [comment]
I think your second GPU is too old and does'nt support CUDA 6

**Comment by matt1634** [comment]
Ah I see that's is shame. Thanks for your help. 

Matt
