### ISSUE TITLE
driver recommendation

### ISSUE THREAD

**Issue by STk3000** [fireice-uk/xmr-stak#1067]
Hello,

Stak does not provide driver recommendations for their miner, unfortunately.

What driver would you recommend for AMD RX 560 2GB cards? Been using oct2017 (17.9.3) and august blockchain drivers and they get roughly the same hashrates, are the any better drivers than these? I'm also interested of them working with afterburner for fan curve, but that is mosly optional.

Thanks,
Catalin

**Comment by totallyG82** [comment]
Blockchain drivers are recommended as they perform the best. The only reason for other drivers if the computer is used for gaming and other things.

**Comment by STk3000** [comment]
i am running rx 560 2gb card that is not affected by the eth dag fix, since the dag itself is more than 2gb and thus eth cannot be mined on 2gb cards.

getting the same hashrate on blockchain and on 17.9.3 (best drivers for claymore for my card).
Nevermind i will just system restore and test each one.


C

**Comment by SHREDDED-WHEAT** [comment]
Arn't blockchain drivers irrelevant now given the compute setting in the Radeon Settings?

**Comment by JerichoJones** [comment]
> Arn't blockchain drivers irrelevant now given the compute setting in the Radeon Settings?

That's the theory (except Vega)
