### ISSUE TITLE
New AMD Ryzen 5 2400G and Ryzen 3 2200G with Vega IGP

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [fireice-uk/xmr-stak#1073]
# Basic information
  - Type of the CPU: AMD Ryzen 2400G or Ryzen 3 2200G
  - Type of the GPU: Vega IGP built into the above CPU's

Can the current XMR-Stak version use the integrated Vega IGP of these processors?

**Comment by KL0nLutiy** [comment]
http://www.legitreviews.com/amd-ryzen-5-2400g-mining-performance-nicehash-xmr-stak_202662

**Comment by kio3i0j9024vkoenio** [comment]
Thanks
