### ISSUE TITLE
Amd Invalid Results

### ISSUE THREAD

**Issue by ikze** [fireice-uk/xmr-stak#1076]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
**Intel G3930**
  - Type of the GPU (if you try to miner with the GPU).
**Gigabyte Vega 56 OC Gaming ( ones with 2 fans ) i have 6 pcs.**
# Compile issues
  - Which OS do you use?
  ```
**Windows 10 , 64 bits** 
  add **all** commands you used and the **full** compile output here
  ```
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 0, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 1, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 1, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 2, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 2, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 3, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 3, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 4, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 4, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 5, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 5, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
 ],

  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
**I use the .bat file to run xmr-stak**
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? 
**Yes**
  - Is the Main memory of the CPU or GPU undervolted?
**Yes**

Hello everyone !

Something weird is happening !
I started this rig with 2 Vega 56 , worked like a jolly with intensity 1932 , 950 clock mhz , 900 mv 
After i added 4 more cards i can keep it stable only at 1900 intensity with 900/900 .
Or else i get Amd invalid result . I have 2x PSU from EVGA both at 750W , normally rig stays around 1.1kw .

Am i missing something here ? I'm pretty much out of ideas .

Motherboard is Asus Z270-P , 8 gigs of Ram and an ssd .

Every suggestion is welcome as i'm out of ideas .

**Comment by psychocrypt** [comment]
Set you clock and voltage to the default.

**Comment by bruslie** [comment]
lower your card temp to 40-50 °C   i dont get any errors after temp is so low
