### ISSUE TITLE
Forward Ports for HTML Report Help

### ISSUE THREAD

**Issue by garnier77** [fireice-uk/xmr-stak#1079]
Hello I am trying to see the HTML hashrate reports from a different computer. I have changed the port number in the config.txt  and it works on my computer at home but I cannot access the IP + port number on another pc. I tried to forward the ports on my router but it is still not working. I tried putting the external computer IP in the forward port rule and still not working.

**Comment by DavidBruchmann** [comment]
I might mistake but as far as I see xmr-stak is a client application without in-built server.
Therefore I think it's just not accessible without further steps from network.

**Comment by garnier77** [comment]
It says in the config to forward the port if you want to gain access OUTSIDE of your home network so it can be done

**Comment by DavidBruchmann** [comment]
Ahh, now when you mention about it I remember.
Sorry for confusion, you're right.

**Comment by DavidBruchmann** [comment]
I got it running by only setting the right port:

![image](https://user-images.githubusercontent.com/999146/36227620-3736c932-1204-11e8-8b9f-f9f8442685be.png)

**Comment by garnier77** [comment]
Thank you David for the help. I can do this as well if I'm on the computer that's mining in trying to access my home computer hashreport from an out side computer. It states in the config.txt that I need to forward ports which I have done but still not working

**Comment by DavidBruchmann** [comment]
Don't know what is the issue in detail, but you mentioned about the IP.
I never set any IP for accessing the site from outside - at least not in xmr-stak configuration.
I just checked my site from mobile, that's working too.
You have a running web-server you can access from outside?

**Comment by garnier77** [comment]
No I am trying to access my home computer hash rate report from the outside still not working I want to know of I did something wrong when I forwarded my port as instructed by the config.txt

**Comment by garnier77** [comment]
Built-in web server 

 * I like checking my hashrate on my phone. Don't you? 

 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from 

 * outside of your home network. Ports lower than 1024 on Linux systems will require root. 

 *

**Comment by DavidBruchmann** [comment]
@garnier77 maybe post your operating system, I think it's not about the config file.

**Comment by garnier77** [comment]
Windows 10 Home OS

**Comment by DavidBruchmann** [comment]
did you allow that application to communicate with outside in the windows-firewall?
Also windows defender might block it partially or complete from working / communicating.

**Comment by garnier77** [comment]
That part might be where I missed so  when I allow applications I see xmr stak checked under private do I check public?

**Comment by DavidBruchmann** [comment]
yeah try it. In general you should be able to restrict to your network, but try it first with that setting.

**Comment by garnier77** [comment]
Ok great I'll try that hope it works been trying all day lol. Thank you for the help

**Comment by DavidBruchmann** [comment]
Glad I could help ;-)

**Comment by garnier77** [comment]
Hey David I got it to work finally after following your directions I also needed to adjust the port forwarding on my router I had some infor missing excellent thank you again I will close this now.

**Comment by DavidBruchmann** [comment]
Great! Have a good mining ;-)
