### ISSUE TITLE
About the fee

### ISSUE THREAD

**Issue by oicitrapdraz** [fireice-uk/xmr-stak#1085]
There should be a simple way to edit the fee by means of parameters and not compile the entire project (although this is explained), not everyone knows how to compile codes, keep in mind that here there may be people who have never programmed in their life and just download the binaries to get things done.

**Comment by bobbieltd** [comment]
Donation is for the project development.

**Comment by hchan123** [comment]
I disagree. The donation config is fine the way it is.  This ensures the devs are paid and development for the project continues.

**Comment by bobbieltd** [comment]
Do you guys know how hard to write this software ? 
Go ask your friends or your teachers to compile for you. 
Compilation is the easiest part of making this program. If it is made simple, I guess 99.9999% won’t donate and this project would be dead long long time ago and you even don’t have a chance to complain here my friends.

**Comment by JokerGermany** [comment]
@oicitrapdraz:
This people should then donate to the project.

Plumber should work without payment because there are people who haven't done it?

**Comment by oicitrapdraz** [comment]
> Plumber should work without payment because there are people who haven't done it?

I said there should be a easy way to edit the fee with parameteres, where did I say that people should work for free according to you?

**Comment by bobbieltd** [comment]
One thing that I agree that some people are in difficulty because of cryptocurrency downward and they live in poor countries (like me). Then even 0.1% is problem with them. But if you are in difficulty with donation then you should learn to compile. Try to ask someone to help.

**Comment by bobbieltd** [comment]
For your concern about commits, it’s stable branch. For development branch, there are commits recently. They need time to test for bugs.

**Comment by oicitrapdraz** [comment]
Ok, I still believe that a mandatory 2% donation (if you don't compile the code) is a lot (most mining software and pools of any shitcoin is 1%), but I won't get anywhere where you all believe otherwise, so I'll close the issue.

**Comment by bobbieltd** [comment]
2% is alot, correct. But alot of people recompile and disable it. Can you disable pool’s fee 😂 ?

**Comment by bobbieltd** [comment]
Anyway, thanks for closing issue. Good luck and I hope you can disable it by yourself !
