### ISSUE TITLE
AMD tester needed

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#1088]
I worked on a new improvement for AMD GPUs. I need some test results for the pull request #1087.

**The most important hardware is VEGA but tests with older hardware are also welcome.**

- if you don't know how to compile the pull request please **do not** test it!
- please report the hash rate directly in the pull request #1087
  - report the type of the GPU
  - report the OS used
  - report the hash rate of the `dev` branch
  - report the hash rate of #1087
  - report the config used

**Comment by Sugaroverdose** [comment]
Vega 56
Windows 10
Can't compare, it crashes with such amd.txt:
```"gpu_threads_conf" : [
  { "index" : 2,
    "intensity" : 1928, "worksize" : 8,
    "affine_to_cpu" : 1, "strided_index" : 2, "mem_chunk" : 4
  },
  { "index" : 2,
    "intensity" : 1928, "worksize" : 8,
    "affine_to_cpu" : 1, "strided_index" : 2, "mem_chunk" : 4
  },
 
],```
 mem_chunk: 0/2/4/8 = crash after working for a minute with N/A h/s

**Comment by slysov** [comment]
i think strided_index should be 3 for this feature to work

**Comment by psychocrypt** [comment]
No two is the right one. Three is not supported. Mhh strange I tested it
very long on my amd rx570 without issues.

**Comment by JerichoJones** [comment]
In the config...
>2 = chunked memory, chunk size is controlled by 'mem_chunk'

then later...  

>range 0 to 18: set the number of elements per chunk if 'strided_index' == 3

thus the confusion

**Comment by psychocrypt** [comment]
Thanks for your very nice tests. The strided_index must be 2 two allow the
usage of mem_chunk. The documentaion is wrong. I wrote it late in the night
:-)

**Comment by Sugaroverdose** [comment]
i've checked sources before applying settings to be sure that 2 is right :)

**Comment by psychocrypt** [comment]
thanks for all the test!
