### ISSUE TITLE
old TLS snipped?

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#109]
@fireice-uk Can we remove https://github.com/fireice-uk/xmr-stak/blob/22039b2a8755e73fb812e6fa34b75d5665ab10de/xmrstak/config.tpl#L118-L125 tls setting?
I checked the code an this is still used on some places but I thought each pool can now define if TLS is needed.

**Comment by fireice-uk** [comment]
It is still needed. This is a global setting, and does what described  - reject pools with insecure TLS settings.

**Comment by psychocrypt** [comment]
Thx for the clarification.
