### ISSUE TITLE
GeForce 1050 ti config issues

### ISSUE THREAD

**Issue by amrap1** [fireice-uk/xmr-stak#1092]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by psychocrypt** [comment]
I forgot to add a description of your issue. The headline is not enough.

**Comment by amrap1** [comment]
I know...not sure what to add. I want to sound like a complete noobie, but I have some experience. Low hashrate and let xmr-stak set up config, cpu and nvidia file.  Where to start???

**Comment by psychocrypt** [comment]
Anwere as much as possible questions from the initial template. Describe
you problem and add the logs.
