### ISSUE TITLE
Starts using 1050ti even tho --noNVIDIA is in use

### ISSUE THREAD

**Issue by Osku9** [fireice-uk/xmr-stak#1094]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - I5 2500K non-overclocked
  - AMD Radeon HD 6850 Stock clocks

# Compile issues
  - Windows 10 64bit
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

it says something like WARNING: using non-amd gpu.
I made a text file and pasted this to it and made it a .bat file.

F:\___BLOCKCHAIN___\xmr-stak-win64\xmr-stak.exe --noNVIDIA

if errorlevel 255 goto finish
if errorlevel 1 goto error
goto finish

:error
echo.
echo xmr-stak.exe konnte nicht gestartet werden
echo xmr-stak.exe could not be started
pause

(from https://github.com/fireice-uk/xmr-stak/issues/470)
I have 2 1050ti:s, 1 HD 6850 and a 2500K in my rig. I want to mine Ethereum with the 1050ti:s
and Electroneum with the CPU & AMD GPU. WHEN i start it the Claymore miner says that one of the 1050ti:s does only 1mh/s. Any way to fix this?

**Comment by psychocrypt** [comment]
please provide the full log and the hash rate report (press key h)

**Comment by Osku9** [comment]
[2018-02-18 23:23:20] : Start mining: MONERO
[2018-02-18 23:23:20] : Compiling code and initializing GPUs. This will take a while...
[2018-02-18 23:23:20] : WARNING: using non AMD device: NVIDIA Corporation
[2018-02-18 23:23:20] : Device 0 work size 8 / 128.
[2018-02-18 23:23:21] : Starting AMD GPU thread 0, no affinity.
[2018-02-18 23:23:21] : Starting 1x thread, affinity: 0.
[2018-02-18 23:23:21] : hwloc: memory pinned
[2018-02-18 23:23:21] : Starting 1x thread, affinity: 1.
[2018-02-18 23:23:21] : hwloc: memory pinned
[2018-02-18 23:23:21] : Starting 1x thread, affinity: 2.
[2018-02-18 23:23:21] : hwloc: memory pinned
[2018-02-18 23:23:21] : Fast-connecting to etn-eu1.nanopool.org:13333 pool ...
[2018-02-18 23:23:22] : Pool etn-eu1.nanopool.org:13333 connected. Logging in...
[2018-02-18 23:23:22] : Difficulty changed. Now: 120001.
[2018-02-18 23:23:22] : Pool logged in.
[2018-02-18 23:23:35] : Difficulty changed. Now: 120001.
[2018-02-18 23:23:35] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   52.6 |   (na) |   (na) |  1 |   56.5 |   (na) |   (na) |
|  2 |   58.8 |   (na) |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m |
|  0 |  165.0 |   (na) |   (na) |
---------------------------
Totals:    332.9   (na)   (na) H/s
Highest:   332.0 H

**Comment by psychocrypt** [comment]
Your amd.txt file points to the nvidia gpu. Please post the file amd.txt. It could be that you must change the platform index to use the amd gpus.

**Comment by Osku9** [comment]
/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 false = use a contiguous block of memory per thread
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Barts memory:384
  // compute units: 12
  { "index" : 0,
    "intensity" : 96, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

**Comment by JerichoJones** [comment]
Did you change the platform index?

**Comment by Osku9** [comment]
No.

**Comment by JerichoJones** [comment]
OK. I guess we're done then.

**Comment by JerichoJones** [comment]
Try changing it.
