### ISSUE TITLE
Large Page is not working

### ISSUE THREAD

**Issue by anhphan** [fireice-uk/xmr-stak#11]
The large page currently not working, it always show "MEMORY ALLOC FAILED: VirtualAlloc falled.", the older version work fine.

Normally with old version I can get about 90H/s each double thread (lower_power_mode = true - 2 x CPU E5-2670v2),
![image](https://user-images.githubusercontent.com/1614690/31191854-b60b40ca-a969-11e7-8572-6c9b6b1f6b86.png)

but for universal version it only get about 50H/s, and it's say: `MEMORY ALLOC FAILED: VirtualAlloc falled.`
![image](https://user-images.githubusercontent.com/1614690/31193097-53afac64-a96d-11e7-8121-75c1d045a93b.png)

**Comment by fireice-uk** [comment]
Can you verify that fix from #12 is working?

**Comment by anhphan** [comment]
Confirmed the pull #12 is working well.

![image](https://user-images.githubusercontent.com/1614690/31196439-f7c497d8-a977-11e7-97f9-39819fa49d5d.png)

**Comment by fireice-uk** [comment]
Fixed in #12
