### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by JFHY** [fireice-uk/xmr-stak#1103]
Trying to install XMR STAK but unable. Sorry but i am new to all this. just trying out mining on the system. not quite knowing whats the problem. below are the logs.

Would you be able to help? Thanks

# Basic information
  - Type of the CPU. Dual Xeon E5 2620 0

# Compile issues
  - Which OS do you use? Ubuntu 12.04

:~/xmr-stak/build$ sudo make install
Scanning dependencies of target xmr-stak-c
[  4%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 12%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 20%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 24%] Linking C static library bin/libxmr-stak-c.a
[ 24%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 60%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
In file included from /home/brc/xmr-stak/xmrstak/http/httpd.cpp:39:0:
/usr/include/microhttpd.h:717:32: error: ‘socklen_t’ has not been declared
                                socklen_t addrlen);
                                ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp: In static member function ‘static int httpd::req_handler(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)’:
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:70:53: error: ‘MHD_digest_auth_get_username’ was not declared in this scope
   username = MHD_digest_auth_get_username(connection);
                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:73:91: error: ‘MHD_RESPMEM_PERSISTENT’ was not declared in this scope
 sponse_from_buffer(sHtmlAccessDeniedSize, (void*)sHtmlAccessDenied, MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:73:113: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 uffer(sHtmlAccessDeniedSize, (void*)sHtmlAccessDenied, MHD_RESPMEM_PERSISTENT);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:74:95: error: ‘MHD_queue_auth_fail_response’ was not declared in this scope
 e_auth_fail_response(connection, sHttpAuthRelam, sHttpAuthOpaque, rsp, MHD_NO);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:80:130: error: ‘MHD_digest_auth_check’ was not declared in this scope
 elam, jconf::inst()->GetHttpUsername(), jconf::inst()->GetHttpPassword(), 300);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:81:14: error: ‘MHD_INVALID_NONCE’ was not declared in this scope
   if (ret == MHD_INVALID_NONCE || ret == MHD_NO)
              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:83:91: error: ‘MHD_RESPMEM_PERSISTENT’ was not declared in this scope
 sponse_from_buffer(sHtmlAccessDeniedSize, (void*)sHtmlAccessDenied, MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:83:113: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 uffer(sHtmlAccessDeniedSize, (void*)sHtmlAccessDenied, MHD_RESPMEM_PERSISTENT);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:84:134: error: ‘MHD_queue_auth_fail_response’ was not declared in this scope
 uthRelam, sHttpAuthOpaque, rsp, (ret == MHD_INVALID_NONCE) ? MHD_YES : MHD_NO);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:98:54: error: ‘MHD_RESPMEM_PERSISTENT’ was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                      ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:98:76: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                                            ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:105:76: error: ‘MHD_RESPMEM_PERSISTENT’ was not declared in this scope
  MHD_create_response_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:105:98: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 esponse_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM_PERSISTENT);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:113:73: error: ‘MHD_RESPMEM_MUST_COPY’ was not declared in this scope
 p = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:113:94: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 te_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:120:73: error: ‘MHD_RESPMEM_MUST_COPY’ was not declared in this scope
 p = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:120:94: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 te_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:127:73: error: ‘MHD_RESPMEM_MUST_COPY’ was not declared in this scope
 p = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:127:94: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 te_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:134:73: error: ‘MHD_RESPMEM_MUST_COPY’ was not declared in this scope
 p = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM
                                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:134:94: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
 te_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                              ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:148:53: error: ‘MHD_RESPMEM_PERSISTENT’ was not declared in this scope
   rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                     ^
/home/brc/xmr-stak/xmrstak/http/httpd.cpp:148:75: error: ‘MHD_create_response_from_buffer’ was not declared in this scope
   rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                                           ^
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
make: *** [all] Error 2

  run `cmake -LA .` in the build folder and add the output here
:~/xmr-stak/build$ cmake -LA
CMake Error: The source directory "/home/brc/xmr-stak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/brc/xmr-stak/build
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
OpenCL_ENABLE:BOOL=OFF
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

**Comment by JerichoJones** [comment]
Use a newer version of Ubuntu
