### ISSUE TITLE
Can't even use the miner!!

### ISSUE THREAD

**Issue by annern55** [fireice-uk/xmr-stak#1105]
I have 2x 1060 and 2x 1070 and I can't even run the miner... WIndows kills it right saying "display driver nvidia windows kernel mode 390.77 has stopped responding and been sucsessfully restored." and then the miner gets terminated by windows. It also says device 0: worksize 8/32, what does this mean? On my other computer I have 1x 1070 and it does not say anything like this...  What is wrong? I had an old driver before but now I installed the newest verison (390.77), but error still persists.. Please help.

**Comment by JerichoJones** [comment]
Fill out the template properly.

**Comment by JerichoJones** [comment]
Closing due to lack of response

**Comment by psychocrypt** [comment]
For other users with the same issue. Reduce (test half) the threads in
nvidia.txt
