### ISSUE TITLE
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll WARNING: AMD Backend

### ISSUE THREAD

**Issue by annern55** [fireice-uk/xmr-stak#1106]
So I am trying to mine with my 2x gtx 1060 and 1x 1070 and 2x rx 570's, but I am facing error after error after error... I set up my rig 2 days ago and have been using legacy nicehash miner since then, but today I decided to try and setup XMRstak and mine some altcoins, but that's not happening appearently. First I was faced with the memoryalloc problem despite of setting virtual memory to 16gb, but this fixed itself all of the sudden after a bunch of testing and restarts. Now once I start the program it is saying: WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll WARNING: AMD Backend, despite of having 2 RX 570's ready to mine.. the XMRstak won't generate an AMD config file because of this and it's almost as if it doesn't recognize the cards. I have tried making an exclusion in windows defender incase that's corrupting the xmrstak_opencl_backend.dll file, tried turning off windows firewall, tried re-adding the .dll into my xmrstak folder from my .zip archive, and obviously I've tried deleting the configs and files and setting up xmr stak way too many times.. I've been troubleshooting for many hours and I feel no closer to finding a solution. And that's not all there is to it. xmr stak actually detects and creates a folder for my nvidia cards, but with it's recommended config settings I am getting the error: "Display driver has stopped responding and has been recovered." As seen here: https://i.gyazo.com/thumb/1200/80e518286d82203e7890fbeb95bb5cfa-png.jpg In the cmd it reports this: https://i.gyazo.com/thumb/1200/2ff90ec51a924a9887c22f736a1b5ca8-png.jpg Now I have tried for hours playing around with the settings changing bfactor, threads and blocks, and there are some settings which doesn't directly crash the program, but will give me absolutely worthless hashrates. The absolute best config settings I could get working with my gtx 1070 gave me a whopping 300 h/s.. Now I have another computer with a 1070 too, my gaming pc, and if I move the 1070 to that one, it will give me 720 no problems, and that is with the recommended settings: thread 28, bfactor 6 and blocks 45. If i try those same settings on my rig it crashes the drivers and windows terminates the miner.. Note that the first time I ran XMR-stak it actually created an AMD folder, but I deleted this to reconfigure the miner, and once I re-opened it, it only generated a folder for NVIDIA..

I am getting fed up and I can't exactly say this has been a fun first time experience, but hey, it's not supposed to go flawlessly right? Really appreciate any help I can get!

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

**Comment by drak01** [comment]
I had this same issue too, but in linux.  I copied the binary xmr-stak to /usr/bin, but I believe I needed to add the library to /usr/lib.  Otherwise, it worked when I ran the binary from the build directory I built it from because it was able to locate the library in the same directory.  

Maybe you can try running the binary from the terminal after cd'ing into the directory and seeing if the message is the same.
