### ISSUE TITLE
open cl 2.0

### ISSUE THREAD

**Issue by Sleinous** [fireice-uk/xmr-stak#111]
![image](https://user-images.githubusercontent.com/33639239/32767153-6e469ab4-c912-11e7-8033-96af79a39df8.png)

Hello all,
Anyone able to explain to me why opencl 2.0 wasn't found when running `cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. `   command? Is it important and will it impact hashrate at all?

**Comment by psychocrypt** [comment]
This is tge detection loop from the find module of CMake. This is normal.
It shows that CMake tries to detect OpenCL 2.0 and do fallbacks until a
known version is found.

**Comment by Sleinous** [comment]
Thanks for the explanation, I don't need to bother going about finding opencl 2 then I take it? Makes no different to xmr-stak's performance?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by psychocrypt** [comment]
OpenCL is only used for amd gpus. If you have only nvidia gpus you can also
compile with the cmake flag `-DOpenCL_ENABLE=OFF`
