### ISSUE TITLE
GPU working discontinously

### ISSUE THREAD

**Issue by michelegentili93** [fireice-uk/xmr-stak#1110]
It seems like the same issue where the GPU usage stays really low and then spikes to 100 before going back to 0 again. It's only running 89.4 H/s... so I'm not sure what the issue is.

"gpu_threads_conf" :
[
  // gpu: GeForce 940M architecture: 50
  //      memory: 1697/2048 MiB
  //      smx: 3
  { "index" : 0,
    "threads" : 86, "blocks" : 9,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : true, "sync_mode" : 3,
  },

],

**Comment by psychocrypt** [comment]
Reduce bsleep to 10 can reduce the effect. But the reason is that your card
is rendering your screen or an other app is also using the gpu.
You can also try to half the threads. It can also be that it takes to long
to calculate a bunch of hashes.

**Comment by dfg3hz5zqtwz46hw6** [comment]
I'm having the same problem. Tried a lot of different settings but nothing helped.

>But the reason is that your card is rendering your screen or an other app is also using the gpu.

is not the case for me because I am using my CPUs internal GPU and running the miner solely on my real GPU (GTX 750 TI) https://i.imgur.com/AT5p3Gs.png

**Comment by psychocrypt** [comment]
reduce the threads to a quarter

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
