### ISSUE TITLE
Socket Error - only shows up after first run

### ISSUE THREAD

**Issue by candre23** [fireice-uk/xmr-stak#1113]
I'm finally upgrading my 3 machines from the old wolf miner to your xmr-stak miner.  All three are experiencing the same issue.  The first time I run xmr-stak and enter in the address/config info, it connects to the pool and hashes away without any problem.  If I stop and try to restart the miner, I get the following error:

`SOCKET ERROR - [stratum+tcp://xmr-us-east1.nanopool.org:14444] 9432:error:2006A066:BIO routines:BIO_get_host_ip:bad hostname lookup:.\crypto\bio\b_sock.c:146:host=stratum+tcp`

This error occurs on every subsequent run on all three machines.  The wolf miner still works fine.  Claymore works as well, so it can't be an issue with the pool, my networking setup, or my hardware.

Stak config:

`{"pool_address" : "stratum+tcp://xmr-us-east1.nanopool.org:14444", "wallet_address" : "address.name/email", "pool_password" : "x", "use_nicehash" : false, "use_tls" : true, "tls_fingerprint" : "", "pool_weight" : 1 },`

Wolf config:

```
"url": "stratum+tcp://xmr-us-east1.nanopool.org:14444",
"user": "address.name/email",
"pass": "x"
```

I'm running your latest compiled release in win10 (machines 1 & 2) and windows server 2012R2 (machine 3).  

Machine 1: i7 2600 + RX480
Machine 2: i5 4590T
Machine 3: dual xeon x5660 + RX550

**Comment by JerichoJones** [comment]
When you have the issue make sure you can ping the pool.

**Comment by IronicMeme** [comment]
I'm having this exact same issue right now oddly enough.
