### ISSUE TITLE
xmr-stak crashes PC when terminated

### ISSUE THREAD

**Issue by Sleinous** [fireice-uk/xmr-stak#112]
Seem to have stumbled on an issue when terminating xmr-stak : 

![image](https://user-images.githubusercontent.com/33639239/32772604-a6b8b3be-c926-11e7-8d47-277f20b61ea0.png)

PC crashes and reboots, I have managed to repeat this behaviour.
MEMORY.DMP file is vlarge, over 2GB, let me know if there's anything in there you need!

**Comment by Sleinous** [comment]
Just tried to kill xmr-stak again, crashed entire PC immediately afterwards, anyone have any ideas on this one? This is a tri GTX 970 setup with dual Xeon E5-2630
Cheers

**Comment by fireice-uk** [comment]
@Sleinous That's a diver / card problem unfortunately (only a diver can crash the whole OS).

**Comment by Sleinous** [comment]
Hmm thanks for the heads up, I may have to revert to the xmr-stak-nvidia for this rig in that case because it doesn't behave that way on that build 👍

**Comment by Sleinous** [comment]
BSOD Stop code is : BAD_POOL_CALLER, only happens on xmr-stak, not on xmr-stak-nvidia

**Comment by Sleinous** [comment]
BSOD Stop code is : BAD_POOL_CALLER, only happens on xmr-stak, not on xmr-stak-nvidia
Additional BSOD stop code : PAGE_FAULT_IN_NON_PAGED_AREA

![image](https://user-images.githubusercontent.com/33639239/32822931-235d858e-c9db-11e7-8689-cedd54cdaa66.png)

@fireice-uk @psychocrypt  Any ideas at all why it's only crashing on this version and not on xmr-stak-nvidia, i've just run all 3 GTX 970's through rigourous stress tests, no BSOD, no nvidia driver has stopped working messages and no artifacting. Am puzzled as to what else this could be.

**Comment by fireice-uk** [comment]
Are you running them with the same settings?

**Comment by Sleinous** [comment]
@fireice-uk Yes, when you launch xmr-stak-nvidia for the first time you get the following suggested config :  
![image](https://user-images.githubusercontent.com/33639239/32912160-78d10c3c-cb0e-11e7-819b-bb7e958416a0.png)
You get the exact same suggested config on xmr-stak except when I close cmd out on xmr-stak it crashes, and it doesn't on xmr-stak-nvidia

**Comment by Sleinous** [comment]
@psychocrypt any ideas?

**Comment by Sleinous** [comment]
@fireice-uk 
Some addition information regarding this one : 

![image](https://user-images.githubusercontent.com/33639239/32991876-e6c5d43e-cd43-11e7-88d1-41bb9e5a324b.png)

![image](https://user-images.githubusercontent.com/33639239/32991873-d4ae0e1a-cd43-11e7-810a-b39a356bbe1d.png)

**Comment by 010themaster010** [comment]
Same problem here. FX 6300, RX 480 (1), RX 570(1), RX560(2), on this rig. Also my 570 won't hash any faster than my 560s but I got my 480 to 870 hashes. Any ideas for either? Happens worse with combined miner, less often/harsh with GPU only, doesn't happen with CPU miner.

**Comment by psychocrypt** [comment]
increase bfactor to 8 in nvidia.txt

**Comment by Sleinous** [comment]
Issue still persists fyi - switched to nvidia xmr until this is solved

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by cjokrap** [comment]
This happens to me as well.  I've already increased my bfactor to 8 in nvidia.txt, but every time I close the miner I get BSOD.

**Comment by valiant1x** [comment]
Issue persists for me as well, only when using the NVIDIA miner. CPU miner exits fine. Using dual 980TI cards.

**Comment by r3lik** [comment]
same issue with dual 980TI cards

**Comment by valiant1x** [comment]
@fireice-uk can this issue be reopened?
