### ISSUE TITLE
HTML report violates XML rules: quotes expected

### ISSUE THREAD

**Issue by alextrezvy** [fireice-uk/xmr-stak#1122]
Failed on parsing with DOM parser:

`<h4>Hashrate Report</h4><div class=data>`

xmrstak v.2.2.0

**Comment by alextrezvy** [comment]
I have worked this around this bug by parsing the response with RegExp instead of DOM. But you still may correct it.

**Comment by fireice-uk** [comment]
Thanks! Marked it for looking into.

**Comment by fireice-uk** [comment]
Fixed by @jimmielin
