### ISSUE TITLE
Compil CUDA 9.1 error  VS2017 Community ver 141

### ISSUE THREAD

**Issue by Fungraphic** [fireice-uk/xmr-stak#1123]
![2018-03-01_171919](https://user-images.githubusercontent.com/26345101/36855861-e4bae356-1d74-11e8-87eb-60da94d1be31.jpg)

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
mkdir build
cd build

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
![2018-03-01_173310](https://user-images.githubusercontent.com/26345101/36856603-b1816300-1d76-11e8-938e-653935436054.jpg)

cmake --build . --config Release --target install

**Comment by JerichoJones** [comment]
[Search](https://github.com/fireice-uk/xmr-stak/search?q=CUDA+9.1+error+VS2017&type=Issues&utf8=✓)

**Comment by Fungraphic** [comment]
Thank you very much! @JerichoJones
![2018-03-03_170314](https://user-images.githubusercontent.com/26345101/36936374-00d9444c-1f05-11e8-9c8e-b9cca98bbbea.jpg)
# **Fix for compiling with Cuda 9.1 on VS 2017 version >= 15.5**
https://github.com/fireice-uk/xmr-stak/pull/896/files

**http://pool-b2b.info**
