### ISSUE TITLE
how to change the number of cpu using in the xmr stak?

### ISSUE THREAD

**Issue by gjc12g** [fireice-uk/xmr-stak#1124]
trying to mine on my spare alienware laptop, it's a i7 but when I look up the hashrate seems it's only activating 0,1,2. how can I configure it to mine with more than 3 ? thx guys

**Comment by JerichoJones** [comment]
Read the cpu.txt for more info. Else...  

**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
