### ISSUE TITLE
win10 crashing when mining starts

### ISSUE THREAD

**Issue by hedelmasalaatti** [fireice-uk/xmr-stak#1125]
- CPU: AMD A8 7100 apu w/4 cpu cores+ 4 gpu cores.
  - GPU: AMD Radeon R5 (APU)+ Radeon R6 M255DX
When mining starts, my screen goes black and 5 min later the system reboots.

[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1775323/amd.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1775325/cpu.txt)

**Comment by JerichoJones** [comment]
Lower Intensity. Else...  

**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
