### ISSUE TITLE
Implement support for the CryptoNight-Dark hashing algorithm from Bitnote.

### ISSUE THREAD

**Issue by AnythingTechPro** [fireice-uk/xmr-stak#1129]
https://github.com/xbn-project/bitnote/commit/04cdf674c0a852cb13c0c7922447c13388899158

**Comment by AnythingTechPro** [comment]
https://github.com/xmrig/xmrig/issues/427

**Comment by psychocrypt** [comment]
Could you please provide the paper or specifications for the pow changes.

**Comment by AnythingTechPro** [comment]
@krruzic That has been fixed. https://github.com/xbn-project/bitnote/commit/4f21fdd75dc4ee50a47b0a903717b303e1b76218

**Comment by psychocrypt** [comment]
If nobody provide a describtion how cryptonight dark works I think we will
not suppory this coin for the moment.

**Comment by extrimexxx** [comment]
if change aeon settings to  
AEON_MEMORY 524288llu
AEON_MASK 0x7FFF0
AEON_ITER 0x80000
cryptonight dark work good, but only on cpu, on my gpu nvidia gtx1070 miner > crash
amd gpu no tested, no have amd gpu.
