### ISSUE TITLE
bTlsMode is undefined + executor threading vio

### ISSUE THREAD

**Issue by kyrre** [fireice-uk/xmr-stak#113]
https://github.com/fireice-uk/xmr-stak/blob/288363814fb091ccfc452f0408bfa53727fc30c0/xmrstak/jconf.cpp#L488

**Comment by fireice-uk** [comment]
Ty for reporting that! I will take over this ticket to make a note of another fix that needs to be done too =)

**Comment by fireice-uk** [comment]
`executor::inst()->log_result_error("NVIDIA Invalid Result");` is not correct, as it doesn't include thread safety. Replace it with a new event. Make sure similar call patterns are not anywhere else in the code.

**Comment by fireice-uk** [comment]
Another thing - make the threads yield after pinning but before allocation

**Comment by fireice-uk** [comment]
Implemented in #117
