### ISSUE TITLE
How to start/stop XMR-Stak at a specific time?

### ISSUE THREAD

**Issue by MrFlashGame** [fireice-uk/xmr-stak#1130]
Hey, sorry to ask this here but I didn't know where else I could ask. My question is: How can I start and stop XMR automatically at a specific time (e.g. I want XMR-Sak to start every afternoon at 5pm and to stop at 3am) on a Linux system. Thanks for every answer, sorry for the OT

**Comment by szogun1987** [comment]
You can create service and run systemctl start/stop via cron to start/stop process

**Comment by tinsami1** [comment]
You can create a cron entry to run the following line:
cd <folder/containing/xmr-stak> && timeout 10h ./xmr-stak
