### ISSUE TITLE
Mining other coin (2% fee)

### ISSUE THREAD

**Issue by gvia66** [fireice-uk/xmr-stak#1132]
Hello,
I'm using you software to mine Croat, so, i think, you cannot use your 2% fee.
Can you use it ? (mining Monero for you, and Croat for me, in the same sesson)
If not, how to edit it ?

guillem

**Comment by psychocrypt** [comment]
Even if you mine other coints you will support our development if you keep
the development fee enabled.
Please see the documentation how to disable the fee.
