### ISSUE TITLE
4th VEGA64 add to any PCI-e 1X, then issue happens

### ISSUE THREAD

**Issue by CUIRUIOHIO** [fireice-uk/xmr-stak#1139]
Please provide as much as possible information to reproduce the issue.

# Basic information
4770K
4 vega64 blockchain driver

# Compile issues
  - Which OS do you use?
win10 64
 
continous report as:
Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel  for kernel 0.

**Comment by CUIRUIOHIO** [comment]
remove the 4th vega64, goes well

**Comment by caius72** [comment]
What is your virtual memory size? It should be over 32 GB for 4 Vega cards.

**Comment by JerichoJones** [comment]
Are you still seeing the issue after increasing your virtual memory?

**Comment by CUIRUIOHIO** [comment]
Thank you! this issue resolved after increase virtiual mem to 33000M
