### ISSUE TITLE
Effectively using 24 cores of Intel(R) Xeon(R) CPU X5650 @ 2.67GHz

### ISSUE THREAD

**Issue by loco41211** [fireice-uk/xmr-stak#1142]
Please provide as much as possible information to reproduce the issue.

# Basic information
I have 24 of these in my machine, `cat /proc/cpuinfo` confirms it
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping	: 2
microcode	: 0x1a
cpu MHz		: 2659.848
cache size	: 12288 KB
physical id	: 1
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 32
initial apicid	: 32
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
bogomips	: 5319.69
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

# Issue with the execution
  - Do you compiled the miner by our own? 
Yes
  ```
  run `./xmr-stak --version-long` and add the output here

Version: xmr-stak/2.2.0/2ae7260/master/lin/cpu/aeon-monero/0

  ```
I'm trying to run xmr-stak on my 24 core machine but it seems only 50% is utilised, giving a hashrate of roughly 450Hz/s. HTop and other tools confirm this:
<img width="1547" alt="screen shot 2018-03-07 at 12 56 03" src="https://user-images.githubusercontent.com/5751080/37093347-f36f120a-2206-11e8-872d-f41e1cf3d03a.png">

<img width="630" alt="screen shot 2018-03-07 at 12 56 38" src="https://user-images.githubusercontent.com/5751080/37093369-017ba160-2207-11e8-86e1-dd32c2d9b821.png">

This is with this cpu.txt setting:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
],
```

I've tried adding the other 12 cores to the cpu.txt, but then my hashrate is horrible. CPU usage is at 100% but look at that hashrate:
<img width="617" alt="screen shot 2018-03-07 at 12 58 37" src="https://user-images.githubusercontent.com/5751080/37093460-4d234488-2207-11e8-87e7-8391f31d58da.png">

cpu.txt:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
    

    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 13 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 15 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 16 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 17 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 18 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 19 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 20 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 21 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 22 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 23 },
],

```

Can I not use the 24 cores to double my hashrate from the 450hz/s? I'm guessing I've misconfigured somehow.

**Comment by loco41211** [comment]
This site suggests I should be getting 400 per core or cpu, I think? Not 400 overall, or did I misunderstand?
https://cryptomining24.net/cpu-for-monero/

**Comment by JerichoJones** [comment]
I get ~480h/s TOTAL on Windows. There is no way each core is going to get you 400. My Ryzen can hit 75h/s per core and that is NEW.

**Comment by grafptitsyn** [comment]
@loco41211 give a careful look at these lines:
```
cpu cores	: 6
cache size	: 12288 KB
```

Your each CPU has only 6 cores, not 12, and 12MB L3 cache. Each mining thread needs 2MB of cache. So count your total possible threads.

**Comment by loco41211** [comment]
@grafptitsyn but I have 24 of these? I only pasted one of them since I didn't want to fill the screen, but here's the full output of `cat /proc/cpuinfo`
https://pastebin.com/LXE8hczg

Or have I misunderstood the output from cpuinfo?

**Comment by fireice-uk** [comment]
@loco41211 
`Can I not use the 24 cores to double my hashrate from the 450hz/s?`

You can't. Mining is limited by the CPU cache, not the number of cores. As you have noticed, if you overload the cache you will just slow things down.

**Comment by pulsarcmc** [comment]
@loco41211 
As fireice-uk said:
> You can't. Cryptonote mining is limited by the CPU cache, not the number of cores. As you have noticed, if you overload the cache you will just slow things down.

Not only that, but on certain systems you will run into cache collisions due to the noisy neighbor problem when utilizing LLC. Just because you have enough LLC doesn't mean it's being used in the manner you expect it.

**Comment by bizlevel** [comment]
Hm.

If i have E5-2660 where 8core and 20MB Cashe - my threads must be 10, but i got best result on 12 threads. How this explain? Not just thread=20MB/2MB...
