### ISSUE TITLE
How can I connect xmr-stak directly to the daemon for solo mining? (No pool)

### ISSUE THREAD

**Issue by s4m0k** [fireice-uk/xmr-stak#1145]

**Comment by JerichoJones** [comment]
STAK does not directly support solo mining. You would have to find a pool that provides a solo mining port. They do exist but I don't remember which ones do.

**Comment by fireice-uk** [comment]
You can use something like this -> https://github.com/sammy007/monero-stratum

**Comment by s4m0k** [comment]
Thank you for the replies!

@JerichoJones I have created actually a pool and I thought since i'm the only one mining in my pool (as of the moment) I could directly connect to daemon instead of going through pool to daemon.

@fireice-uk I'll try this one. Thanks!
