### ISSUE TITLE
--fastjobswitch support request (a MUST for AMD Vega + nicehash combo)

### ISSUE THREAD

**Issue by nikl11** [fireice-uk/xmr-stak#1148]
Hello, a few months ago when nicehash restarted its operations, we discussed compatibility problems with xmr-stak (issue #835 ). To be exact, a lot of (up to 5-6%) invalid shares probably due to a combination of problems on nicehash's side and a high difficulty. This issue still persists and it is the only reason I am forced to use a different mining software, which supports `--fastjobswitch`, solving this issue. 

I am kindly asking you again to implement this option into xmr-stak, as it not only makes nicehash cooperative again, but also prevents rare occurrences of unaccepted shares due to being slower than someone with that argument enabled. Thanks guys @psychocrypt @fireice-uk .

**Comment by fireice-uk** [comment]
My thoughts on the matter are here : https://github.com/fireice-uk/xmr-stak/issues/835#issuecomment-370795734

and here : https://github.com/fireice-uk/xmr-stak/issues/835#issuecomment-371159794
