### ISSUE TITLE
Unable to load backend library

### ISSUE THREAD

**Issue by lockpace** [fireice-uk/xmr-stak#1149]
I have been trying to set up the miner, but it seems that I have hit a dead end. When starting the miner, the following appears:
[2018-03-11 22:09:13] : Start mining: MONERO 
[2018-03-11 22:09:14] : Starting NVIDIA GPU thread 0, no affinity.
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
WARNING: AMD Backend disabled
My GPU:  (NVIDIA GeForce GT 540M)
OS: Windows 10

**Comment by psychocrypt** [comment]
this opencl lib is not needed for nvidia but should normally located in the
folder of xmr-stak. I think your virus protection software removed the lib.

**Comment by lockpace** [comment]
The backend lib is located in my xmr-stak folder, and my virus protection software didn´t issue a malware warning when I was downloading the file. 
If I don´t need the lib anyway, I would just download the zip file once more and delete the backend lib during the installation process, does that sound reasonable to you?:)
Thanks a lot for your help, I appreciate it!

**Comment by psychocrypt** [comment]
There is no need to remove the library the miner will ignore it if the
corresponding gpus are not available.

**Comment by lockpace** [comment]
Ok, thank you for helping me out ;-)
