### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by Cavien** [fireice-uk/xmr-stak#1150]
-- Set miner currency to 'monero' and 'aeon'
You have called ADD_LIBRARY for library xmr-stak-c without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmr-stak-backend without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmrstak_cuda_backend without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmrstak_opencl_backend without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:525 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:531 (target_link_libraries):
  Cannot specify link libraries for target "xmr-stak" which is not built by
  this project.

-- Configuring incomplete, errors occurred!
See also "C:/xmr-stak-dep/build/CMakeFiles/CMakeOutput.log".

**Comment by Cavien** [comment]
**Complete information**
`
c:\xmr-stak-dep\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
-- The C compiler identification is MSVC 19.12.25835.0
-- The CXX compiler identification is MSVC 19.12.25835.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found suitable version "9.1", minimum required is "7.5")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib (found version "2.0")
-- Found OpenSSL: C:/xmr-stak-dep/openssl/lib/libeay32.lib (found version "1.0.2m")
You have called ADD_LIBRARY for library xmr-stak-c without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmr-stak-backend without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmrstak_cuda_backend without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library xmrstak_opencl_backend without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:525 (add_executable):
  add_executable called with incorrect number of arguments


CMake Error at CMakeLists.txt:532 (target_link_libraries):
  Cannot specify link libraries for target "xmr-stak" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
See also "C:/xmr-stak-dep/build/CMakeFiles/CMakeOutput.log".`

**Comment by psychocrypt** [comment]
please goto the source code folder and not into xmr-stak-dep to compile the
code
