### ISSUE TITLE
Download file size of xmr-stak-2.2.0.tar.gz

### ISSUE THREAD

**Issue by inq1** [fireice-uk/xmr-stak#1153]
I imported xmr-stak-2.2.0.tar.gz and the 
xmr-stak-2.2.0.tar.gz file size is 308.9Kib (316,309),
compressed checksums are:
SHA1 checksum = c59c4ad7ef85bd2b6c1010d4719dc64589398db3.
SHA256 = a44c1315be4e3cf4ba8a01550a244408b27318b40ebbc0c9f0164d3ffdfe259d
MD5 = 320c7ce60c4c5eb3b77e6e0e3c6a55c8

The sha1 doesn't match this site's checksum.
Is this OK.
inq1

**Comment by psychocrypt** [comment]
The checksums are for the content of the zip file. This file contains the
windows binaries. You downloaded the source code packed and compressed as
tar.gz file.
