### ISSUE TITLE
Feature Request: Automatically switch from Aeon to XMR etc without miner restart

### ISSUE THREAD

**Issue by nutsnax** [fireice-uk/xmr-stak#1154]
I'd like it if xmr-stak were able to automatically switch between aeon/xmr/new XMR without a restart based on the work they receive.

I searched to see if this was already a FR but couldn't find it. Thanks and sorry if this is already out there!

**Comment by psychocrypt** [comment]
The work package the miner receive not contains the name of the currency and the used algorithm. Therefore it is not possible to switch the currency.

**Comment by psychocrypt** [comment]
An other point is that you need different settings per currency to utilize the miner device. The easiest way is to restart the miner with different settings to mine against an other pool.
