### ISSUE TITLE
Monero v7 PoW, scheduled on March 28.

### ISSUE THREAD

**Issue by coolhty** [fireice-uk/xmr-stak#1158]
Monero v7 PoW, scheduled on March 28.
is XMR-STAK ready to be updated?

**Comment by tecbeast42** [comment]
+1

**Comment by JerichoJones** [comment]
Per Fireice-uk: "We wrote our own algorithms, we are waiting for an official binary to test against."
From [this](https://www.reddit.com/r/MoneroMining/comments/8465r9/is_xmrstak_going_to_be_updated_to_accommodate_the/) REDDIT thread.  
  
It will be announced here (on the Github) when it is available.

**Comment by netmebtc** [comment]
http://killallasics.moneroworld.com/#

KILL ALL ASICS MONERO TESTNET POOL
Please use this pool to test if your mining software works with the new POW. Banning is disabled, so don't be a dick!
You need a testnet address to mine to this pool. Other than that, it should be same as any other pool
No blocks are found unless there are miners attached, so don't worry if it says last network block found forever ago
If you don't want to create a testnet address, use: 9v4vTVwqZzfjCFyPi7b9Uv1hHntJxycC4XvRyEscqwtq8aycw5xGpTxFyasurgf2KRBfbdAJY4AVcemL1JCegXU4EZfMtaz
This is on a private testnet to make sure the hash is low for easy testing... though I guess that doesn't matter for work submission. Maybe I'll change it to the real testnet

**Comment by fireice-uk** [comment]
The last line says it all.
