### ISSUE TITLE
Any plan to support monero V1 PoW?

### ISSUE THREAD

**Issue by sx5486510** [fireice-uk/xmr-stak#1160]
It looks like there is no patch.

**Comment by netmebtc** [comment]
you mean V1 or V7?

**Comment by sx5486510** [comment]
monero v7

**Comment by netmebtc** [comment]
waiting,I know xmrig and cast-xmr have new version support V7. so I guess stak will be update soon.

**Comment by coolhty** [comment]
v7's hashrate is reduced by half, temporarily not recommend updating

**Comment by netmebtc** [comment]
if  xmr-stak no update , miner will change to another minersfotware

**Comment by psychocrypt** [comment]
We have already all available and do internal tests. As soon as the
official monero minaries are relesed we will provide our changes. we need
to do tests against the new version of monero first.
Do not worry we will support the monero hardfork v7.

**Comment by stempelo** [comment]
Can you write the result for "This is a test"?
Thanks

**Comment by DrStein99** [comment]
reduced by HALF !?!?!  Does this mean ALL miners will have 1/2 speed (when the protocol becomes mandarory) ?

**Comment by sx5486510** [comment]
I tested xmring-nvidia, the speed is same as v6

**Comment by sx5486510** [comment]
xmring cpu is alse same

**Comment by jtgrassie** [comment]
@psychocrypt 
> As soon as the official monero minaries are relesed we will provide our changes

The PoW changes are already merged in Monero's master branch. You can simply pull and build if you want to test.

**Comment by psychocrypt** [comment]
We see no changes in speed. We will provide the changes soon. We have to do
some more changes and try to test as much as possible to avaoid that users
update to a pre release and later on have trubble.
Do not worry you will have our precompiled binaries and the full source
code a few days before the fork.

**Comment by netmebtc** [comment]
Why are you slow to release it? If we wait until a few days before the fork is released, the miners will not have enough time to test your software. If your software can't run with bug, the miners will not be able to resist ASIC. Are you an associate of ASIC mine?

**Comment by netmebtc** [comment]
On behalf of thousands and thousands of poor CPU and GPU miners, I beg you again for Xmr-stack CryptonightV7 version, please!

**Comment by fireice-uk** [comment]
@netmebtc 
Please go to the Monero project and ask them to tag a release.

**Comment by netmebtc** [comment]
I have beg them for that shit release.    What you can't do, I do it for you

**Comment by xmrig** [comment]
@fireice-uk maybe you just found critical bug in new PoW and wait for the time to show it. Sorry anyway. I prepare my popcorn :-)

**Comment by yyfong0918** [comment]
I GUESS they want to stop botnet using xmr-stak... Oh yes?  Oh No...

**Comment by yyfong0918** [comment]
Why so serious?
