### ISSUE TITLE
Is there a way to benchmark test hash rate without connecting to a pool?

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1162]
Please excuse me if I overlooked, but I can not find how to benchmark test xmr-stak without connecting to a live pool.  Should I just be doing that instead of benchmarking locally ?

**Comment by pulsarcmc** [comment]
Yes, I've been thinking about adding this as a command line option. In the meantime, to do a benchmark test edit the following file --
` xmr-stak/xmrstak/cli/cli-miner.cpp`

Look for the line:
`executor::inst()->ex_start(jconf::inst()->DaemonMode());`

Comment it out, or add this before that line:
```
do_benchmark();
return 0;
```

This will run a default 60 second benchmark. Hope this helps.

**Comment by fireice-uk** [comment]
@pulsarcmc That would be more than welcome as a pr! This used to be a feature but unfortunately has rotten away.

**Comment by pulsarcmc** [comment]
@fireice-uk Sure, looks like @jimmielin took care of it 👍
