### ISSUE TITLE
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu

### ISSUE THREAD

**Issue by FCU4ever** [fireice-uk/xmr-stak#1164]
Hello,

I've got this error sometimes within 12 hours and sometimes after 1 day:
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265

XMR-Stak version used:
Latest release (v2.2.0)

My PC is:
Asus G73SW (custom Bios with AES-NI enable)

My CPU is:
Intel Core i7-2630QM

My GPU is:
Nvidia Geforce 460M

With this configuration:

"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
],

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 460M architecture: 21
  //      memory: 1391/1536 MiB
  //      smx: 4
  { "index" : 0,
    "threads" : 54, "blocks" : 8,
    "bfactor" : 12, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],

**Comment by pulsarcmc** [comment]
Play around with the settings:
Reduce bfactor
Reduce threads

**Comment by FCU4ever** [comment]
Reduce bfactor results in a laggy system.

Can I reduce threads in steps of 2? What do you recommend?

**Comment by pulsarcmc** [comment]
Try reducing threads by half and see what happens.

**Comment by FCU4ever** [comment]
Reducing the threads by half decrease my hashrate from 270 H/s to 235 H/s

**Comment by pulsarcmc** [comment]
How stable was it with the reduced hashrate, e.g. how many hours have you been running it for w/o the error?

**Comment by FCU4ever** [comment]
I'm now running with this configuration for 24 hours and 267 H/s with no error.

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 460M architecture: 21
  //      memory: 1391/1536 MiB
  //      smx: 4
  { "index" : 0,
    "threads" : 48, "blocks" : 8,
    "bfactor" : 12, "bsleep" : 25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],

**Comment by FCU4ever** [comment]
After 1,5 day I've got the same error:
![xmr-stak error](https://user-images.githubusercontent.com/37446406/37564048-465fa792-2a8e-11e8-90ca-18b7ad5a62e5.PNG)

**Comment by psychocrypt** [comment]
This means in the most cases that you run out of gpu memory. The reason is
in the most cases that your system allocated more and more memory for
rendering or an other applicaten (e.g. browser) is also using the gpu.

**Comment by FCU4ever** [comment]
Is there a solution for this problem? 

My webbrowser was also running in the background. Is that the reason for the error?

**Comment by JerichoJones** [comment]
Did you try closing it to see if the problem was resolved?

**Comment by FCU4ever** [comment]
When I closed XMR-Stak I've got a display driver error. A few seconds later my screen changed into a spacing image....... and the pc reboot automatically.

Now i'll try to mine with no background programs and see what happens.

**Comment by FCU4ever** [comment]
After 36 hours the same error appear.

Someone a solution? Or do I have te close te Miner after 24 hours, reboot te pc and restart the Miner?

**Comment by psychocrypt** [comment]
Could you please check if the memory consumtion of xmr-stak is growing over
the time.
Never the less it sounds more than a driver issue. Do you use the latest
cuda 8 driver?

**Comment by FCU4ever** [comment]
How can I check if the (GPU) memory consumption of xmr-stak is growing over the time?

First I installed Cuda 8. After installing Cuda 8 my driver was downgraded so I installed the latest nVidia driver.

**Comment by FCU4ever** [comment]
Do you recommend to re-install Cuda 8 and try with the downgraded driver 
(Cuda 8 driver = 376.54 and latest nVidia driver = 391,01)?

**Comment by FCU4ever** [comment]
Good morning,

This morning the same error appeared. This time in less then a day. I monitored my graphics card with MSI Afterburner and this are the results:
CPU (1,3,5) usage: 100%
GPU max temp: 66 degree
GPU usage: 100%
GPU max mem usage: 1011 mb
GPU Core Clock: 675 MHz
GPU Memory clock 1247 MHz

Someone a solution?

**Comment by JerichoJones** [comment]
>When I closed XMR-Stak I've got a display driver error.
  
Probably the thread count is too high or as Psychocrypt pointed out something is using your GPU memory.

**Comment by FCU4ever** [comment]
After xmr stak chrased the max GPU memory usage is 1011 mb. My graphics card has 1536 mb. So I don't think the max GPU memory reached.

First I'll try the new version of xmr-stak with the same settings:

"gpu_threads_conf" :
[
// gpu: GeForce GTX 460M architecture: 21
// memory: 1391/1536 MiB
// smx: 4
{ "index" : 0,
"threads" : 48, "blocks" : 8,
"bfactor" : 12, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
],

If that won't work I reduce the threads in steps of 2 and post back the results.

**Comment by psychocrypt** [comment]
If you not disable your window manger fully also other programms are using
the gpu. Therefore also 300mb free memory can sometimes to low.
btw: I think it is not possible to disable the window manager in windows :-)
If you have an internal gpu use this for the desktop and than you have more
space on the nvidia gpu.

FCU4ever <notifications@github.com> schrieb am Di., 27. März 2018, 14:13:

**Comment by psychocrypt** [comment]
yes lower the threads or increase bfactor. Test where you get the better
hashrate

**Comment by JerichoJones** [comment]
@FCU4ever Did implementing @psychocrypt 's suggestions help?

**Comment by epb5119** [comment]
I have the same error: CUDA ....:365
using win 10
6xGTX1080TI only no cpu
Miner stops with this error and then Windows show Application has been blocked access to graphics card.

**Comment by epb5119** [comment]
changing threads or bfactor not solution. CPU and GPU memory usage spikes to 100% before miner stops and shows cuda error listed above

**Comment by FCU4ever** [comment]
Trying with threads 50, 48, 46, 44 won't work. Same error. Sometimes after a few hours sometimes after two days. Increase bfactor will decrease my hashrate with 25%.....

Now I'm also getting this message: 'Elevating due to Windows 7 or 8. You need Windows 10 to use fast memory without UAC elevation.

I'm running Windows 7.

**Comment by booblofobia** [comment]
CUDA] Error gpu 3: <C:/xmr-stak/buy_ryo/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:422

what is, problem program !?

**Comment by booblofobia** [comment]
[CUDA] Error gpu 3: <C:/xmr-stak/buy_ryo/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:422
**suggestion: Try to increase the attribute 'bfactor' in the NVIDIA config file.**

> what is, problem program !?
