### ISSUE TITLE
portbin download gone - n/a?

### ISSUE THREAD

**Issue by nerdoc** [fireice-uk/xmr-stak#1166]
I tried to download the Linux portable binary, like described [here](https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md), with a link to the "[latest releases](https://github.com/fireice-uk/xmr-stak/releases/latest)".
Neither is there a link to a portable binary `xmr-stak-portbin-linux.tar.gz`, nor did I find it anywhere else.
Is that gone? Please update the documentation.

**Comment by psychocrypt** [comment]
There is a note in the docu that this feature is maybe not available. Yes
maybe we should remove this section in the next release

Christian González <notifications@github.com> schrieb am Sa., 17. März
2018, 22:28:

**Comment by psychocrypt** [comment]
There was to much issues with the portable bin binaries. Therefore we removed it.
