### ISSUE TITLE
how to compile and run it on RHEL/CentOS 5

### ISSUE THREAD

**Issue by moralrebuild** [fireice-uk/xmr-stak#1167]
Here is my tough situation: a number of decent servers are running very old Enterprise flavor Linux of RHEL/CentOS 5 but in near future will not be possible to upgrade to new mining friendly version, like either 6 or 7. 

How can I get the xmr-stak compiled and run on them? Any of your helps are highly appreciated.

**Comment by psychocrypt** [comment]
You can compile everything by hand. I know that this is a lot of work.

Wei Brand <notifications@github.com> schrieb am So., 18. März 2018, 07:01:

**Comment by moralrebuild** [comment]
@psychocrypt Thanks. In fact, the latest gcc/g++ version I can upgrade to is 4.8  by using developer toolset 2.0 from Scientific Linux (http://linux.web.cern.ch/linux/devtoolset/). But g++ 5.1 is the minimal requirement. So your theory is just theory.

**Comment by bizlevel** [comment]
Yes. I love CentOS, but if need some package with high version - it is impossible to do! (
You can try compile in static generic mode under Fedora (it is too rpm-based) and after this run on CentOS.
Maybe also need to build some GLIBC library for run binary file.

**Comment by moralrebuild** [comment]
Just a heads-up. I managed to compile the xmrig on RHEL/CentOS 5 with some source codes hacking, the hash rate is acceptable. Saying 1200KH/S on a 4 (3 generations older Xeon) CPU sockets  If anyone want to know details, just ping me in this post.

**Comment by psychocrypt** [comment]
Compile clang instead of gnu is also possible and very easy.

**Comment by moralrebuild** [comment]
@bizlevel My 10 years passion for Enterprise Linux was gone when I started to use Debian 4 years before. For personal needs, I would never go back to RHEL/CentOS. But for business projects for large companies, redhat has already locked-in.

**Comment by Endt4sk** [comment]
@moralrebuild would you pleased share your steps on RHEL/CentOS 5? Tun of thaks for you.

**Comment by moralrebuild** [comment]
@Endt4sk No problem, here are the basic steps:

wget -O /etc/yum.repos.d/slc5-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc5-devtoolset.repo
yum install devtoolset-2 

wget https://archive.fedoraproject.org/pub/archive/epel/5/x86_64/epel-release-5-4.noarch.rpm
rpm -ivh epel-release-5-4.noarch.rpm
yum install hwloc-devel libmicrohttpd-devel openssl-devel make

wget https://copr-be.cloud.fedoraproject.org/results/ngompa/cmake3-el5/epel-5-x86_64/00169014-jsoncpp/jsoncpp-0.6.0-0.0.9.rc2.noarch.rpm
wget https://copr-be.cloud.fedoraproject.org/results/ngompa/cmake3-el5/epel-5-x86_64/00429458-cmake3/cmake3-data-3.5.0-0.2.1.el5.centos.x86_64.rpm 
wget https://copr-be.cloud.fedoraproject.org/results/ngompa/cmake3-el5/epel-5-x86_64/00429458-cmake3/cmake3-3.5.0-0.2.1.el5.centos.x86_64.rpm

rpm -ivh jsoncpp-0.6.0-0.0.9.rc2.noarch.rpm
yum install lzo -y && rpm -ivh libarchive3-3.1.2-0.1.x86_64.rpm
rpm -ivh --nodeps --force cmake3-data-3.5.0-0.2.1.el5.centos.x86_64.rpm 
rpm -ivh --nodeps --force cmake3-3.5.0-0.2.1.el5.centos.x86_64.rpm

# compiling XMRIG
git clone https://github.com/xmrig/xmrig.git
// make modification for following two files as workaround
 1. remove (in Mem_unix.cpp)
		MAP_HUGETLB |
 2. remove (in Platform_unix.cpp)
		if (sched_setscheduler(0, SCHED_IDLE, &param) != 0) {
		sched_setscheduler(0, SCHED_BATCH, &param);
		}

scl enable devtoolset-2 bash

rpm -q libuv  # "libuv-0.10.34-1.el6.x86_64" too old to support the compiling. 
sudo yum install make automake libtool curl -y
wget https://github.com/libuv/libuv/archive/v1.8.0.tar.gz
sudo tar zxfv v1.8.0.tar.gz -C /usr/local/src && rm -f v1.8.0.tar.gz
cd /usr/local/src/libuv-1.8.0
sudo sh autogen.sh
./configure && make && sudo make install
sudo rm -rf /usr/local/src/libuv-1.8.0 && cd ~/
sudo ldconfig
		
cd ~/xmrig/build
rm -rf ~/xmrig/build/*
cmake3 -DWITH_HTTPD=OFF -DUV_LIBRARY=/usr/local/lib/libuv.so ..

**Comment by bizlevel** [comment]
I will try make modification in code and use new libuv.so. All will be make under CentOS 6.9

**Comment by moralrebuild** [comment]
@Endt4sk  Sorry I am not a professional developer to take a deep look at your issue.  My successful effort only proves you can mine XMR on such unusual old OS but YMMV.

**Comment by bizlevel** [comment]
@moralrebuild  Hello.
What i get:
I was made changes in code, delete some string as you write.
Update libuv, cmake, gcc to latest.
And no profit! ( Except small size of miner )

Old version:
```
root@node:/opt/xmrig250# ./xmrig
 * VERSIONS:     XMRig/2.5.0 libuv/1.9.1 gcc/6.3.0
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (3) x64 AES-NI
 * CPU L2/L3:    2.2 MB/18.0 MB
 * THREADS:      3, cryptonight, av=1, donate=1%
 * POOL #1:      pool.supportxmr.com:3333
 * API PORT:     8080
 * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[2018-03-21 17:42:18] use pool pool.supportxmr.com:3333 212.232.25.156
[2018-03-21 17:42:18] new job from pool.supportxmr.com:3333 diff 5000
[2018-03-21 17:42:31] speed 2.5s/60s/15m 95.0 n/a n/a H/s max: 94.8 H/s
[2018-03-21 17:42:34] speed 2.5s/60s/15m 95.5 n/a n/a H/s max: 94.8 H/s
[2018-03-21 17:42:39] speed 2.5s/60s/15m 95.3 n/a n/a H/s max: 94.8 H/s
```
New version:

```
root@node:/opt/xmrig250# ./xmrig3
 * VERSIONS:     XMRig/2.5.0 libuv/1.19.2 gcc/7.3.0
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (3) x64 AES-NI
 * CPU L2/L3:    2.2 MB/18.0 MB
 * THREADS:      3, cryptonight, av=1, donate=1%
 * POOL #1:      pool.supportxmr.com:3333
 * API PORT:     8080
 * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[2018-03-21 17:29:12] use pool pool.supportxmr.com:3333 212.232.25.155
[2018-03-21 17:29:12] new job from pool.supportxmr.com:3333 diff 5000
[2018-03-21 17:29:28] new job from pool.supportxmr.com:3333 diff 6383
[2018-03-21 17:29:34] accepted (1/0) diff 6383 (78 ms)
[2018-03-21 17:30:13] accepted (2/0) diff 6383 (86 ms)
[2018-03-21 17:30:16] speed 2.5s/60s/15m 76.2 74.1 n/a H/s max: 76.5 H/s
[2018-03-21 17:30:28] new job from pool.supportxmr.com:3333 diff 5010
[2018-03-21 17:30:29] accepted (3/0) diff 5010 (80 ms)
[2018-03-21 17:30:33] speed 2.5s/60s/15m 76.5 74.0 n/a H/s max: 76.5 H/s
[2018-03-21 17:30:37] new job from pool.supportxmr.com:3333 diff 5010
[2018-03-21 17:30:50] speed 2.5s/60s/15m 79.0 74.2 n/a H/s max: 78.0 H/s
[2018-03-21 17:31:06] speed 2.5s/60s/15m 79.2 76.4 n/a H/s max: 79.9 H/s
[2018-03-21 17:31:16] speed 2.5s/60s/15m 79.6 77.0 n/a H/s max: 79.9 H/s
[2018-03-21 17:31:28] new job from pool.supportxmr.com:3333 diff 5010
[2018-03-21 17:31:28] new job from pool.supportxmr.com:3333 diff 5000
[2018-03-21 17:32:05] new job from pool.supportxmr.com:3333 diff 5000
[2018-03-21 17:32:16] speed 2.5s/60s/15m 78.7 77.1 n/a H/s max: 80.2 H/s
[2018-03-21 17:32:28] new job from pool.supportxmr.com:3333 diff 5000
[2018-03-21 17:32:30] new job from pool.supportxmr.com:3333 diff 5000
```

**Comment by bizlevel** [comment]
@moralrebuild  Hm, but after some time i got - 175 H/s ! )
Maybe all is work!
Thanks.

**Comment by Zenitur** [comment]
You can compile any version of GCC compiler [using this manual](https://www.linux.org.ru/forum/development/14513059?cid=14514412).

**Comment by Spudz76** [comment]
Clang as old as 3.5 works also.
Clang 3.8 generally has given me the best speeds anyway, unless gcc6+.
