### ISSUE TITLE
performance difference under different windows system

### ISSUE THREAD

**Issue by lowprofileusername** [fireice-uk/xmr-stak#1168]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
E7-4809 V3 @2.00GHz
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  `Windows 2008 R2/Windows 2016
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
no
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

I execute xmr-stak on 2 different system with same spec hardware. results are different

for E7-4809 V3 under windows 2008 R2 I got highest 601H/s average 590H/s but for windows 2016 I can get only average 500H to 520H /s 

is the hashrate I post here normal for this CPU? 
Thanks.
"cpu_threads_conf" :   for windows 2008 R2
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 64 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 66 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 68 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 70 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 72 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 74 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 76 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 78 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 65 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 67 },

],

"cpu_threads_conf" :   Windows 2016
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 64 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 66 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 68 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 70 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 72 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 74 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 76 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 78 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 65 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 67 },

],

**Comment by JerichoJones** [comment]
We can't test every OS.  
  
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
