### ISSUE TITLE
-- Could NOT find CUDA: Found unsuitable version "6.5", but required is at least "7.5" (found /usr/local/cuda-6.5)

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#1169]
Hello.

I have NVIDIA QUADRO FX1800, that works with CUDA6.5.
It is possible to use/compile with 6.5 not 7.5 CUDA version?
How many functions depend from it?
Thanks.

**Comment by psychocrypt** [comment]
You must have compute capability 2.0 (fermi) and this is supported with
cuda 7.5. I think your gpu is to old.

**Comment by bizlevel** [comment]
Supported any CUDA card begins from fermi microarchitecture (https://en.wikipedia.org/wiki/Fermi_(microarchitecture)

2.0 | GF100, GF110
2.1 | GF108, GF106, GF104, GF114, GF116
3.0 | GK107, GK106, GK104
3.5 | GK110, GK208
5.0 | GM108, GM107
5.2 | GM200, GM204, GM206

I think GF118, GF119, GF117 - also 2.1 no more.
Thanks.
