### ISSUE TITLE
GPUs Issues

### ISSUE THREAD

**Issue by nightsuspect** [fireice-uk/xmr-stak#1173]
Please provide as much as possible information to reproduce the issue..

# AMD OpenCl issue laptop GPUs completly turn off display ASUS x555y and doesnt mine anything and laptop is out of control and must hold power button to power off it

# NVIDIA CUDA issue LAPTOP ASUS GTX 920mx ERROR

**Comment by JerichoJones** [comment]
Please complete the template.
  
---

# Issue with the execution of STAK
- Which OS do you use?

- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
 
- Did you compile the miner yourself or are you running the release?  
   
   
 - Run  
 
```
    xmr-stak --version-long
```
and add the output here  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---

**Comment by nightsuspect** [comment]
-both laptop was win 10 x64 updated 
-and there was not any overclock
-and release version was used 2.2.0

**Comment by nightsuspect** [comment]
at this picture if i connect internet system goes down as i said: asus x555y 0-Mullins 1-Hainan
![screenshot 3](https://user-images.githubusercontent.com/5768533/37948788-fd3a44da-31a6-11e8-97da-46c537c0aa0b.png)
these pictures are claymore 9.7 that works correctly
![screenshot 4](https://user-images.githubusercontent.com/5768533/37948800-13ecaff6-31a7-11e8-83ce-1808a4789d03.png)
![screenshot 8](https://user-images.githubusercontent.com/5768533/37948802-15840170-31a7-11e8-9752-55b1520143a3.png)

**Comment by nightsuspect** [comment]
at this picture if i connect internet system goes down as i said: asus x555y 0-Mullins 1-Hainan
![screenshot 3](https://user-images.githubusercontent.com/5768533/37948788-fd3a44da-31a6-11e8-97da-46c537c0aa0b.png)
this picture is claymore 9.7 that works correctly
![screenshot 8](https://user-images.githubusercontent.com/5768533/37948802-15840170-31a7-11e8-9752-55b1520143a3.png)
