### ISSUE TITLE
CPU & GPU shell report 

### ISSUE THREAD

**Issue by MarcelusCH** [fireice-uk/xmr-stak#1175]
The reported hash rate in the linux shell don't seems correct. 
1) It display me that I have 3 CPU, probably for using 3 cores of 4.
2) It display me only 1 Nvidia GPU, and I have also 2 GPU.
The total hash rate seems ok.

See attached print screen:
![2018-03-20 15_50_47-miner00](https://user-images.githubusercontent.com/37587839/37663612-e048f56c-2c59-11e8-8921-354a420f9521.png)

.

**Comment by MarcelusCH** [comment]
Sorry, I see it now that its correct... :-)

**Comment by psychocrypt** [comment]
never the less  half the threads for your gtx1070

**Comment by MarcelusCH** [comment]
what do you mean by that? Could my capacity be higher for the GTX 1070?
