### ISSUE TITLE
better support for packaging

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#118]
Help the distribution package maintainer to simplify the shipping of an package.  

- add environment variable to control where the configs should be written to (e.g. $HOME/.config/xmr-stak) independent of the path to the miner
- add CMake option to separate the xmr-stak binary and the backend libs
- add option to use a external *rapidjson* version

- related to #96

**Comment by fireice-uk** [comment]
Rapidjson is a header-only library. It has no external versions.

**Comment by psychocrypt** [comment]
But the version from the distribution can be used instead of the internal.
Ubuntu: apt-get install rapidjson-dev
