### ISSUE TITLE
Can miner workaround driver issue?

### ISSUE THREAD

**Issue by szogun1987** [fireice-uk/xmr-stak#1183]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Ryzen 7 1700
  - Vega 56

# Issue with the execution
  - Do you compiled the miner by our own?
I have build it by myself. Currently it is up-to-date with dev branch 

xmr-stak requires some kind of GPU reset before execution to fully utilize RX Vega GPUs.
[This Reddit thread](https://www.reddit.com/r/MoneroMining/comments/7fh8eq/monero_mining_tutorial_for_vega_56_2000_hs/) propose to enable / disable HBCC to achieve it. On linux there is no simple solution.
Is there something that can be done on miner level to enforce it? 
There is related discussion in [this thread](https://github.com/RadeonOpenCompute/ROCm/issues/325).

**Comment by JerichoJones** [comment]
No. The miner cannot reset the driver.

**Comment by szogun1987** [comment]
OK. I though so. Closing issue
