### ISSUE TITLE
build xmrstak_cuda_backend statically

### ISSUE THREAD

**Issue by developernew123** [fireice-uk/xmr-stak#1184]
I managed to build xmr-stak with cpu and amd support in static runtime mt including openssl , microhttpd and hwloc , the problem is in build xmrstak_cuda_backend project which gives me errors such : 

unresolved external symbol __imp_asinhf
unresolved external symbol __imp_erff
unresolved external symbol __imp_truncf

"void __cdecl std::_Xout_of_range(char const *)" (?_Xout_of_range@std@@YAXPEBD@Z) already defined in libcpmt.lib(xthrow.obj)
"void __cdecl std::_Xbad_alloc(void)" (?_Xbad_alloc@std@@YAXXZ) already defined in libcpmt.lib(xthrow.obj)

is there any method to build it statically

**Comment by psychocrypt** [comment]
do you have enabled the cmake variable for static build?
I never tried to build it full static.

**Comment by developernew123** [comment]
@psychocrypt 
what is this variable

**Comment by bmatthewshea** [comment]
I'm curious, too. I tried:
`cmake -DBUILD_SHARED_LIBS=OFF -DITK_DYNAMIC_LOADING=OFF -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCMAKE_BUILD_TYPE=Release .. && CFLAGS=-static make`

GCC libs are static already by the look of the CMakeList.
Cuda libs (and AMD apparently) are not.
Still just moves 3 'static' libs to the bin/ output so the lib is found in current working dir when binary executes. This isn't a true static build - it's still file dependent. These libs need to be linked as static inside the single binary. Not left as separate files. What flags are needed / unneeded and/or cmakelist adjusts? Thanks much.

````
[ 19%] Linking C static library bin/libxmr-stak-c.a
...
[ 77%] Linking CXX static library bin/libxmr-stak-backend.a
...
[ 93%] Linking CXX shared library bin/libxmrstak_cuda_backend.so
````

**Comment by psychocrypt** [comment]
the cuda backend and amd backend will be created always as dynamic
libraries this can not disabled.

**Comment by bmatthewshea** [comment]
Understood. Was poking around Cmakelist again and seems so. thanks for quick reply, though.
