### ISSUE TITLE
How Start application ?

### ISSUE THREAD

**Issue by jeduarz** [fireice-uk/xmr-stak#1185]
Hi!
I clone the git repository to mi CENTOS 6.9
Now somebody could tell how start the application and maybe how I can set to start and stop via cron job

I use CENTOS on VMWARE

**Comment by myxuchangbin** [comment]
You need to compile the program before you can start it. Specific operation, please see the following document:
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md
https://github.com/fireice-uk/xmr-stak/blob/master/doc/usage.md#usage-on-linux--macos
