### ISSUE TITLE
[resloved]can not find the xmr-stak.sh script for the Linux deployment.

### ISSUE THREAD

**Issue by WayneWZ** [fireice-uk/xmr-stak#1186]
# Basic information
  - Type of the CPU.

# Compile issues
  - Ubuntu 17.04
  ```
i can not find the xmr-stak.sh file, which Linux_deployment.md mentioned.
* [Linux Portable Binary](doc/Linux_deployment.md)

```
tar xzf xmr-stak-portbin-linux.tar.gz
./xmr-stak.sh
```

Configuration and tuning files will be generated automatically from your answers.
  ```

# Issue with the execution
can not to deploy on Linux
  ```

**Comment by WayneWZ** [comment]
i found the answer at #524 , but there is another issue, no matter 2.1.0 or 2.2.0

/software/xmr-stak-2.1.0$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF
CMake Error: The source directory "/home/ute/software/xmr-stak-2.1.0/DOpenCL_ENABLE=OFF" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ute@ute572-2:~/software/xmr-stak-2.1.0$

**Comment by djfinch** [comment]
-DOpenCL_ENABLE=OFF not DOpenCL_ENABLE=OFF... notice leading dash. missing on your cmake args...

**Comment by WayneWZ** [comment]
@djfinch   thanks for your feedback!

after the cmake command corrtetion and ' libmicrohttpd-dev' 'libhwloc-dev' libarary installtion, i could moving forward more now. 

do you konw which libs should be installed for the OpenSSL?

  OpenSSL NOT found: use `-DOpenSSL_ENABLE=OFF` to build without SSL support


ute@ute572-2:~/software/xmr-stak-2.2.0$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:339 (message):
  OpenSSL NOT found: use `-DOpenSSL_ENABLE=OFF` to build without SSL support


-- Configuring incomplete, errors occurred!

**Comment by WayneWZ** [comment]
after the libssl1.0.0 and libssl-dev installtion for OpenSSL, the cmake is ok, then could execute the xmr-stak now, thanks for your sharing!

make install
cd bin
chmod +x xmr-stak
./xmr-stak
