### ISSUE TITLE
XMR-STAK_COMPILE question

### ISSUE THREAD

**Issue by tinsami1** [fireice-uk/xmr-stak#1187]
How much faster/better is "native" vs "generic"?

Currently I'm running several rigs with different CPUs (Xeons, Ryzens, i5's, etc.) and using the same generic build I made.  Is it worthwhile to build a native one for each machine?

**Comment by Omar-Elrefaei** [comment]
In theory, using the same "generic" would be like using the lowest common denominator between the systems. Of course your mileage SHOULD vary, but there is a big probability that you are losing on some optimizations.

I would still like to hear something from the developers. @fireice-uk @psychocrypt

**Comment by fireice-uk** [comment]
I can't speak for GPUs but for CPUs 90% of the run-time is in two dozen instructions. So optimisations elsewhere are not really significant.

**Comment by tinsami1** [comment]
So, if I understand it correctly, I should not see any marked improvements.  I'll stick to the generic build then.  Did you make any CPU-specfic optimisations we should be aware of?  Something that would warrant a native build for a certain CPU model?

**Comment by psychocrypt** [comment]
If you compile in native mode the compiler sometimes autotune a few parts
directly for your cpu. If you see any difference depends strongly from the
cpu generation.
