### ISSUE TITLE
xmr-stak-win64 in nicehash

### ISSUE THREAD

**Issue by professor-jonny** [fireice-uk/xmr-stak#1188]
is it possible to make the backend and config file compatible with xmr-stack-cpu so we could drop over the top of the executable  in nicehash?

**Comment by fireice-uk** [comment]
Short answer is no, sorry, they are using a very old version. Unless they overwrite the file, you can try dropping a new exe + config file.

**Comment by professor-jonny** [comment]
what happens when I do is say config_0.txt unknown command or something, im running it manually alongside nicehash at the moment , as nicehash legacy is hard coded to the old exe is it possible to have a config file inside xmr-stack-win64 to ignore the command line options sent from nicehash?

**Comment by JerichoJones** [comment]
Command-line options take precedence.

**Comment by professor-jonny** [comment]
yes but could there be an option in the config file that ignores the command line options ?
