### ISSUE TITLE
-std=c++11 is not supported

### ISSUE THREAD

**Issue by velicumugur** [fireice-uk/xmr-stak#120]
i get a lot of : 
the -std=c++11 is not supported with the configured host compiler
os : win10-64
cuda 8.0
opencl
visual studio 2017
everithing work ok when build is done, but i get less hashrate then old software xmr-stak-nvidia
or amd downloaded from git release.
i think this error afect somehow memory.

**Comment by psychocrypt** [comment]
This warning can be ignored. The msvc host compilet which can be used with
cuda8 is not supporting c++11. Ther is not disadvantage.

Which setup has less hashrate. Please post the type of the gpu, the auto
suggested config and if used the hand tuned config. For the old miner and
new (if different)
