### ISSUE TITLE
"monero2" is not good name

### ISSUE THREAD

**Issue by zensurette** [fireice-uk/xmr-stak#1202]
The suggested name for XMR is dangerously imprecise and may lead people to believe that there is new version of Monero (technically true, practically false).

A much better alternative would be `monero-v7`, `monero-fork7` (the name of the future fork) or `monero-201803` (the date of the fork).

Future updates will then have very predictable numbers.

**Comment by psychocrypt** [comment]
You are absolutely right the name is not nice but we need to avoid conflicts with older configs. I will discuss with with @fireice-uk if we should add also an other alternative name.

**Comment by fireice-uk** [comment]
We considered `Monero-v7` however rejected it since `MoneroV` *is* a fork, `monero7` would have my approval.

**Comment by zensurette** [comment]
I strongly suggest `monero-201803`. Factual, precise, boring and will never be mistaken for a fork.

**Comment by psychocrypt** [comment]
solved with #1206

**Comment by psychocrypt** [comment]
`monero-201803` is to complicated for a user who do not know enough about monero

**Comment by fireice-uk** [comment]
Also, the fork is likely to happen in April =)
