### ISSUE TITLE
Trojan reported (Trojan.Cridex) by Symantec

### ISSUE THREAD

**Issue by orbex** [fireice-uk/xmr-stak#1211]
On Windows 7 with Symantec Endpoint protection this exe gets reported as having trojan Cridex...

**Comment by psychocrypt** [comment]
please compare the checksums. If the checksum is equal to our reported sums
than add the miner to the ignore list of your virus protection list. You
can also compile the miner by your own but even than symantec will block
the binary

**Comment by enerdevelop** [comment]
Try edit binary file in some Hexaeditor. 
Change string values like "nicehash", "mining", "cryptonight" to some other chars and save. 
For example "nicehash" to "nicxxash"
It may be help :-)
