### ISSUE TITLE
Disable some but not all GPU's

### ISSUE THREAD

**Issue by NotTheFloor** [fireice-uk/xmr-stak#1212]
Is it possible to disable GPU0 while leaving the rest enabled?

  - Type of the GPU (if you try to miner with the GPU).
1x RX 570
2x Vega 56

I'd like to leave the 570 disabled completely, so I can mine a dif coin with it. Obviously --noAMD is not the answer here, and from what I understand commenting out the config for that single GPU will still cause xmr-stak to still #"probe" it. 

What is this "probe"? If it is only during initialization I'm fine with that. My guess would be it happens regularly though.

Any work around? Thanks!

**Comment by psychocrypt** [comment]
Let the miner generate a config and edit the config. If you remove the line
for your gpu than this gpu will be ignored.

**Comment by NotTheFloor** [comment]
Thanks! I was under the impression xmr-stak would still probe that gpu, which could interfere with other mining software, but since that's not the case, easy fix!

I appreciate the quick response.
