### ISSUE TITLE
Does not create ./xmr-stak in bin

### ISSUE THREAD

**Issue by Ulvarin** [fireice-uk/xmr-stak#1213]
After compiling everything goes perfect ending up in 
[100%] Built target xmr-stak
Install the project...
-- Install configuration: "Release"
xmr-stak installed to folder 'bin'

but there is no place where ./xmr-stak is  (/bin)
can not be runned or used in any way.
I compiled by admin, tried on root -> nothing helps.
How to fix it?

Linux Mint 18.3 x64

**Comment by psychocrypt** [comment]
lease post the comoiler outpur fully and an `ls -la` of your bin folder
Also please run `cmake -LA .` in the build folder

**Comment by Ulvarin** [comment]
compiler:
ryzenvm build # make install
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[  7%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 15%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 23%] Linking C static library bin/libxmr-stak-c.a
[ 23%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 30%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 42%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 46%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 53%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 57%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 65%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 69%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 73%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 80%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/uac.cpp.o
[ 84%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 88%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 92%] Linking CXX static library bin/libxmr-stak-backend.a
[ 92%] Built target xmr-stak-backend
Scanning dependencies of target xmr-stak
[ 96%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[100%] Linking CXX executable bin/xmr-stak
[100%] Built target xmr-stak

> 

ls -la

> ryzenvm bin # ls -la
razem 16288
drwxr-xr-x  2 root root    4096 mar 22 08:27 .
drwxr-xr-x 25 root root    4096 mar 26 09:42 ..
-rwxr-xr-x  1 root root    6456 lut 21 18:41 archdetect
-rwxr-xr-x  1 root root 1037440 maj 26  2017 bash
-rwxr-xr-x  1 root root  520992 cze 16  2017 btrfs
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-calc-size
lrwxrwxrwx  1 root root       5 sty 25 14:27 btrfsck -> btrfs
-rwxr-xr-x  1 root root  278376 cze 16  2017 btrfs-convert
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-debug-tree
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-find-root
-rwxr-xr-x  1 root root  270136 cze 16  2017 btrfs-image
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-map-logical
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-select-super
-rwxr-xr-x  1 root root  253816 cze 16  2017 btrfs-show-super
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfstune
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-zero-log
-rwxr-xr-x  1 root root   31288 maj 20  2015 bunzip2
-rwxr-xr-x  1 root root 1964536 sie 19  2015 busybox
-rwxr-xr-x  1 root root   31288 maj 20  2015 bzcat
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzcmp -> bzdiff
-rwxr-xr-x  1 root root    2140 maj 20  2015 bzdiff
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzegrep -> bzgrep
-rwxr-xr-x  1 root root    4877 maj 20  2015 bzexe
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzfgrep -> bzgrep
-rwxr-xr-x  1 root root    3642 maj 20  2015 bzgrep
-rwxr-xr-x  1 root root   31288 maj 20  2015 bzip2
-rwxr-xr-x  1 root root   14616 maj 20  2015 bzip2recover
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzless -> bzmore
-rwxr-xr-x  1 root root    1297 maj 20  2015 bzmore
-rwxr-xr-x  1 root root   52080 mar  2  2017 cat
-rwxr-xr-x  1 root root   14752 lut  7  2016 chacl
-rwxr-xr-x  1 root root   60272 mar  2  2017 chgrp
-rwxr-xr-x  1 root root   56112 mar  2  2017 chmod
-rwxr-xr-x  1 root root   64368 mar  2  2017 chown
-rwxr-xr-x  1 root root   10536 wrz 22  2016 chvt
-rwxr-xr-x  1 root root  151024 mar  2  2017 cp
-rwxr-xr-x  1 root root  141472 lut 18  2016 cpio
-rwxr-xr-x  1 root root  154072 lut 17  2016 dash
-rwxr-xr-x  1 root root   68464 mar  2  2017 date
-rwxr-xr-x  1 root root   72632 mar  2  2017 dd
-rwxr-xr-x  1 root root   97912 mar  2  2017 df
-rwxr-xr-x  1 root root  126584 mar  2  2017 dir
-rwxr-xr-x  1 root root   60680 lis 30 21:04 dmesg
lrwxrwxrwx  1 root root       8 sty 25 14:27 dnsdomainname -> hostname
lrwxrwxrwx  1 root root       8 sty 25 14:27 domainname -> hostname
-rwxr-xr-x  1 root root   82328 wrz 22  2016 dumpkeys
-rwxr-xr-x  1 root root   31376 mar  2  2017 echo
-rwxr-xr-x  1 root root   51512 kwi 26  2014 ed
-rwxr-xr-x  1 root root   36504 lip 14  2015 efibootmgr
-rwxr-xr-x  1 root root      28 kwi 29  2016 egrep
-rwxr-xr-x  1 root root   27280 mar  2  2017 false
-rwxr-xr-x  1 root root   10544 wrz 22  2016 fgconsole
-rwxr-xr-x  1 root root      28 kwi 29  2016 fgrep
-rwxr-xr-x  1 root root   49576 lis 30 21:04 findmnt
-rwxr-xr-x  1 root root    1185 cze 16  2017 fsck.btrfs
-rwxr-xr-x  1 root root   36024 lut  7  2016 fuser
-rwsr-xr-x  1 root root   30800 lip 12  2016 fusermount
-rwxr-xr-x  1 root root   23752 lut  7  2016 getfacl
-rwxr-xr-x  1 root root  211224 kwi 29  2016 grep
-rwxr-xr-x  1 root root    2301 paź 27  2014 gunzip
-rwxr-xr-x  1 root root    5927 paź 27  2014 gzexe
-rwxr-xr-x  1 root root   98240 paź 27  2014 gzip
-rwxr-xr-x  1 root root  192760 wrz 12  2017 hciconfig
-rwxr-xr-x  1 root root   14800 lis 24  2015 hostname
-rwxr-xr-x  1 root root  376192 gru  7 01:00 ip
-rwxr-xr-x  1 root root  498936 mar  8 18:51 journalctl
-rwxr-xr-x  1 root root   10536 wrz 22  2016 kbd_mode
-rwxr-xr-x  1 root root   30792 gru 10  2015 keyctl
-rwxr-xr-x  1 root root   23152 lis 21  2016 kill
-rwxr-xr-x  1 root root  150600 lip 25  2017 kmod
-rwxr-xr-x  1 root root  170728 kwi  5  2017 less
-rwxr-xr-x  1 root root   10256 kwi  5  2017 lessecho
lrwxrwxrwx  1 root root       8 sty 25 14:27 lessfile -> lesspipe
-rwxr-xr-x  1 root root   19824 kwi  5  2017 lesskey
-rwxr-xr-x  1 root root    7764 kwi  5  2017 lesspipe
-rwxr-xr-x  1 root root   56152 mar  2  2017 ln
-rwxr-xr-x  1 root root  111496 wrz 22  2016 loadkeys
-rwxr-xr-x  1 root root   48128 maj 17  2017 login
-rwxr-xr-x  1 root root  453848 mar  8 18:51 loginctl
-rwxr-xr-x  1 root root  105136 sty 28  2017 lowntfs-3g
-rwxr-xr-x  1 root root  126584 mar  2  2017 ls
-rwxr-xr-x  1 root root   77280 lis 30 21:04 lsblk
lrwxrwxrwx  1 root root       4 sty 25 14:27 lsmod -> kmod
-rwxr-xr-x  1 root root   76848 mar  2  2017 mkdir
-rwxr-xr-x  1 root root  265928 cze 16  2017 mkfs.btrfs
-rwxr-xr-x  1 root root   64496 mar  2  2017 mknod
-rwxr-xr-x  1 root root   39728 mar  2  2017 mktemp
-rwxr-xr-x  1 root root   39768 lis 30 21:04 more
-rwsr-xr-x  1 root root   40152 lis 30 21:04 mount
-rwxr-xr-x  1 root root   14768 lis 30 21:04 mountpoint
lrwxrwxrwx  1 root root      20 sty 25 14:27 mt -> /etc/alternatives/mt
-rwxr-xr-x  1 root root   68824 lut 18  2016 mt-gnu
-rwxr-xr-x  1 root root  130488 mar  2  2017 mv
-rwxr-xr-x  1 root root  208480 lut 15  2017 nano
lrwxrwxrwx  1 root root      20 sty 25 14:27 nc -> /etc/alternatives/nc
-rwxr-xr-x  1 root root   31248 gru  4  2012 nc.openbsd
lrwxrwxrwx  1 root root      24 sty 25 14:27 netcat -> /etc/alternatives/netcat
-rwxr-xr-x  1 root root  119624 cze 30  2014 netstat
-rwxr-xr-x  1 root root  678496 mar  8 18:51 networkctl
lrwxrwxrwx  1 root root       8 sty 25 14:27 nisdomainname -> hostname
-rwsr-xr-x  1 root root  142032 sty 28  2017 ntfs-3g
-rwxr-xr-x  1 root root   10312 sty 28  2017 ntfs-3g.probe
-rwxr-xr-x  1 root root   67608 sty 28  2017 ntfs-3g.secaudit
-rwxr-xr-x  1 root root   18424 sty 28  2017 ntfs-3g.usermap
-rwxr-xr-x  1 root root   26728 sty 28  2017 ntfscat
-rwxr-xr-x  1 root root   30824 sty 28  2017 ntfscluster
-rwxr-xr-x  1 root root   34920 sty 28  2017 ntfscmp
-rwxr-xr-x  1 root root   34928 sty 28  2017 ntfsfallocate
-rwxr-xr-x  1 root root   39024 sty 28  2017 ntfsfix
-rwxr-xr-x  1 root root   55416 sty 28  2017 ntfsinfo
-rwxr-xr-x  1 root root   31928 sty 28  2017 ntfsls
-rwxr-xr-x  1 root root   30824 sty 28  2017 ntfsmove
-rwxr-xr-x  1 root root   38944 sty 28  2017 ntfstruncate
-rwxr-xr-x  1 root root   47752 sty 28  2017 ntfswipe
lrwxrwxrwx  1 root root       6 sty 25 14:27 open -> openvt
-rwxr-xr-x  1 root root   18968 wrz 22  2016 openvt
lrwxrwxrwx  1 root root      14 sty 25 14:27 pidof -> /sbin/killall5
-rwsr-xr-x  1 root root   44168 maj  7  2014 ping
-rwsr-xr-x  1 root root   44680 maj  7  2014 ping6
-rwxr-xr-x  1 root root   35504 wrz  4  2016 plymouth
-rwxr-xr-x  1 root root   97408 lis 21  2016 ps
-rwxr-xr-x  1 root root   31472 mar  2  2017 pwd
lrwxrwxrwx  1 root root       4 sty 25 14:27 rbash -> bash
-rwxr-xr-x  1 root root   39632 mar  2  2017 readlink
-rwxr-xr-x  1 root root      89 kwi 26  2014 red
-rwxr-xr-x  1 root root   60272 mar  2  2017 rm
-rwxr-xr-x  1 root root   39632 mar  2  2017 rmdir
lrwxrwxrwx  1 root root       4 sty 25 14:27 rnano -> nano
-rwxr-xr-x  1 root root   19320 sty 26  2016 run-parts
-rwxr-xr-x  1 root root   73424 lut 12  2016 sed
-rwxr-xr-x  1 root root   36296 lut  7  2016 setfacl
-rwxr-xr-x  1 root root   39952 wrz 22  2016 setfont
-rwxr-xr-x  1 root root   30875 lut  1  2017 setupcon
lrwxrwxrwx  1 root root       4 sty 25 14:27 sh -> dash
lrwxrwxrwx  1 root root       4 sty 25 14:27 sh.distrib -> dash
-rwxr-xr-x  1 root root   31408 mar  2  2017 sleep
-rwxr-xr-x  1 root root  115816 gru  7 01:00 ss
lrwxrwxrwx  1 root root       7 sty 25 14:27 static-sh -> busybox
-rwxr-xr-x  1 root root   72496 mar  2  2017 stty
-rwsr-xr-x  1 root root   40128 maj 17  2017 su
-rwxr-xr-x  1 root root   31408 mar  2  2017 sync
-rwxr-xr-x  1 root root  659848 mar  8 18:51 systemctl
lrwxrwxrwx  1 root root      20 mar  8 18:51 systemd -> /lib/systemd/systemd
-rwxr-xr-x  1 root root   51656 mar  8 18:51 systemd-ask-password
-rwxr-xr-x  1 root root   39344 mar  8 18:51 systemd-escape
-rwxr-xr-x  1 root root   64080 mar  8 18:51 systemd-hwdb
-rwxr-xr-x  1 root root  281840 mar  8 18:51 systemd-inhibit
-rwxr-xr-x  1 root root   47544 mar  8 18:51 systemd-machine-id-setup
-rwxr-xr-x  1 root root   35248 mar  8 18:51 systemd-notify
-rwxr-xr-x  1 root root  133704 mar  8 18:51 systemd-tmpfiles
-rwxr-xr-x  1 root root   68032 mar  8 18:51 systemd-tty-ask-password-agent
-rwxr-xr-x  1 root root   23144 lis 30 21:04 tailf
-rwxr-xr-x  1 root root  383632 lis 17  2016 tar
-rwxr-xr-x  1 root root   10416 sty 26  2016 tempfile
-rwxr-xr-x  1 root root   64432 mar  2  2017 touch
-rwxr-xr-x  1 root root   27280 mar  2  2017 true
-rwxr-xr-x  1 root root  449136 mar  8 18:51 udevadm
-rwxr-xr-x  1 root root   14328 lip 12  2016 ulockmgr_server
-rwsr-xr-x  1 root root   27608 lis 30 21:04 umount
-rwxr-xr-x  1 root root   31440 mar  2  2017 uname
-rwxr-xr-x  1 root root    2301 paź 27  2014 uncompress
-rwxr-xr-x  1 root root    2762 wrz 22  2016 unicode_start
-rwxr-xr-x  1 root root  126584 mar  2  2017 vdir
-rwxr-xr-x  1 root root   10552 mar  3  2016 vmmouse_detect
-rwxr-xr-x  1 root root   31376 lis 30 21:04 wdctl
-rwxr-xr-x  1 root root     946 sty 26  2016 which
-rwxr-xr-x  1 root root   27432 sty 18  2016 whiptail
lrwxrwxrwx  1 root root       8 sty 25 14:27 ypdomainname -> hostname
-rwxr-xr-x  1 root root    1937 paź 27  2014 zcat
-rwxr-xr-x  1 root root    1777 paź 27  2014 zcmp
-rwxr-xr-x  1 root root    5764 paź 27  2014 zdiff
-rwxr-xr-x  1 root root     140 paź 27  2014 zegrep
-rwxr-xr-x  1 root root     140 paź 27  2014 zfgrep
-rwxr-xr-x  1 root root    2131 paź 27  2014 zforce
-rwxr-xr-x  1 root root    5938 paź 27  2014 zgrep
-rwxr-xr-x  1 root root    2037 paź 27  2014 zless
-rwxr-xr-x  1 root root    1910 paź 27  2014 zmore
-rwxr-xr-x  1 root root    5047 paź 27  2014 znew


> 
ryzenvm bin # ls -la
razem 16288
drwxr-xr-x  2 root root    4096 mar 22 08:27 .
drwxr-xr-x 25 root root    4096 mar 26 09:42 ..
-rwxr-xr-x  1 root root    6456 lut 21 18:41 archdetect
-rwxr-xr-x  1 root root 1037440 maj 26  2017 bash
-rwxr-xr-x  1 root root  520992 cze 16  2017 btrfs
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-calc-size
lrwxrwxrwx  1 root root       5 sty 25 14:27 btrfsck -> btrfs
-rwxr-xr-x  1 root root  278376 cze 16  2017 btrfs-convert
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-debug-tree
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-find-root
-rwxr-xr-x  1 root root  270136 cze 16  2017 btrfs-image
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfs-map-logical
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-select-super
-rwxr-xr-x  1 root root  253816 cze 16  2017 btrfs-show-super
-rwxr-xr-x  1 root root  249464 cze 16  2017 btrfstune
-rwxr-xr-x  1 root root  245368 cze 16  2017 btrfs-zero-log
-rwxr-xr-x  1 root root   31288 maj 20  2015 bunzip2
-rwxr-xr-x  1 root root 1964536 sie 19  2015 busybox
-rwxr-xr-x  1 root root   31288 maj 20  2015 bzcat
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzcmp -> bzdiff
-rwxr-xr-x  1 root root    2140 maj 20  2015 bzdiff
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzegrep -> bzgrep
-rwxr-xr-x  1 root root    4877 maj 20  2015 bzexe
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzfgrep -> bzgrep
-rwxr-xr-x  1 root root    3642 maj 20  2015 bzgrep
-rwxr-xr-x  1 root root   31288 maj 20  2015 bzip2
-rwxr-xr-x  1 root root   14616 maj 20  2015 bzip2recover
lrwxrwxrwx  1 root root       6 sty 25 14:27 bzless -> bzmore
-rwxr-xr-x  1 root root    1297 maj 20  2015 bzmore
-rwxr-xr-x  1 root root   52080 mar  2  2017 cat
-rwxr-xr-x  1 root root   14752 lut  7  2016 chacl
-rwxr-xr-x  1 root root   60272 mar  2  2017 chgrp
-rwxr-xr-x  1 root root   56112 mar  2  2017 chmod
-rwxr-xr-x  1 root root   64368 mar  2  2017 chown
-rwxr-xr-x  1 root root   10536 wrz 22  2016 chvt
-rwxr-xr-x  1 root root  151024 mar  2  2017 cp
-rwxr-xr-x  1 root root  141472 lut 18  2016 cpio
-rwxr-xr-x  1 root root  154072 lut 17  2016 dash
-rwxr-xr-x  1 root root   68464 mar  2  2017 date
-rwxr-xr-x  1 root root   72632 mar  2  2017 dd
-rwxr-xr-x  1 root root   97912 mar  2  2017 df
-rwxr-xr-x  1 root root  126584 mar  2  2017 dir
-rwxr-xr-x  1 root root   60680 lis 30 21:04 dmesg
lrwxrwxrwx  1 root root       8 sty 25 14:27 dnsdomainname -> hostname
lrwxrwxrwx  1 root root       8 sty 25 14:27 domainname -> hostname
-rwxr-xr-x  1 root root   82328 wrz 22  2016 dumpkeys
-rwxr-xr-x  1 root root   31376 mar  2  2017 echo
-rwxr-xr-x  1 root root   51512 kwi 26  2014 ed
-rwxr-xr-x  1 root root   36504 lip 14  2015 efibootmgr
-rwxr-xr-x  1 root root      28 kwi 29  2016 egrep
-rwxr-xr-x  1 root root   27280 mar  2  2017 false
-rwxr-xr-x  1 root root   10544 wrz 22  2016 fgconsole
-rwxr-xr-x  1 root root      28 kwi 29  2016 fgrep
-rwxr-xr-x  1 root root   49576 lis 30 21:04 findmnt
-rwxr-xr-x  1 root root    1185 cze 16  2017 fsck.btrfs
-rwxr-xr-x  1 root root   36024 lut  7  2016 fuser
-rwsr-xr-x  1 root root   30800 lip 12  2016 fusermount
-rwxr-xr-x  1 root root   23752 lut  7  2016 getfacl
-rwxr-xr-x  1 root root  211224 kwi 29  2016 grep
-rwxr-xr-x  1 root root    2301 paź 27  2014 gunzip
-rwxr-xr-x  1 root root    5927 paź 27  2014 gzexe
-rwxr-xr-x  1 root root   98240 paź 27  2014 gzip
-rwxr-xr-x  1 root root  192760 wrz 12  2017 hciconfig
-rwxr-xr-x  1 root root   14800 lis 24  2015 hostname
-rwxr-xr-x  1 root root  376192 gru  7 01:00 ip
-rwxr-xr-x  1 root root  498936 mar  8 18:51 journalctl
-rwxr-xr-x  1 root root   10536 wrz 22  2016 kbd_mode
-rwxr-xr-x  1 root root   30792 gru 10  2015 keyctl
-rwxr-xr-x  1 root root   23152 lis 21  2016 kill
-rwxr-xr-x  1 root root  150600 lip 25  2017 kmod
-rwxr-xr-x  1 root root  170728 kwi  5  2017 less
-rwxr-xr-x  1 root root   10256 kwi  5  2017 lessecho
lrwxrwxrwx  1 root root       8 sty 25 14:27 lessfile -> lesspipe
-rwxr-xr-x  1 root root   19824 kwi  5  2017 lesskey
-rwxr-xr-x  1 root root    7764 kwi  5  2017 lesspipe
-rwxr-xr-x  1 root root   56152 mar  2  2017 ln
-rwxr-xr-x  1 root root  111496 wrz 22  2016 loadkeys
-rwxr-xr-x  1 root root   48128 maj 17  2017 login
-rwxr-xr-x  1 root root  453848 mar  8 18:51 loginctl
-rwxr-xr-x  1 root root  105136 sty 28  2017 lowntfs-3g
-rwxr-xr-x  1 root root  126584 mar  2  2017 ls
-rwxr-xr-x  1 root root   77280 lis 30 21:04 lsblk
lrwxrwxrwx  1 root root       4 sty 25 14:27 lsmod -> kmod
-rwxr-xr-x  1 root root   76848 mar  2  2017 mkdir
-rwxr-xr-x  1 root root  265928 cze 16  2017 mkfs.btrfs
-rwxr-xr-x  1 root root   64496 mar  2  2017 mknod
-rwxr-xr-x  1 root root   39728 mar  2  2017 mktemp
-rwxr-xr-x  1 root root   39768 lis 30 21:04 more
-rwsr-xr-x  1 root root   40152 lis 30 21:04 mount
-rwxr-xr-x  1 root root   14768 lis 30 21:04 mountpoint
lrwxrwxrwx  1 root root      20 sty 25 14:27 mt -> /etc/alternatives/mt
-rwxr-xr-x  1 root root   68824 lut 18  2016 mt-gnu
-rwxr-xr-x  1 root root  130488 mar  2  2017 mv
-rwxr-xr-x  1 root root  208480 lut 15  2017 nano
lrwxrwxrwx  1 root root      20 sty 25 14:27 nc -> /etc/alternatives/nc
-rwxr-xr-x  1 root root   31248 gru  4  2012 nc.openbsd
lrwxrwxrwx  1 root root      24 sty 25 14:27 netcat -> /etc/alternatives/netcat
-rwxr-xr-x  1 root root  119624 cze 30  2014 netstat
-rwxr-xr-x  1 root root  678496 mar  8 18:51 networkctl
lrwxrwxrwx  1 root root       8 sty 25 14:27 nisdomainname -> hostname
-rwsr-xr-x  1 root root  142032 sty 28  2017 ntfs-3g
-rwxr-xr-x  1 root root   10312 sty 28  2017 ntfs-3g.probe
-rwxr-xr-x  1 root root   67608 sty 28  2017 ntfs-3g.secaudit
-rwxr-xr-x  1 root root   18424 sty 28  2017 ntfs-3g.usermap
-rwxr-xr-x  1 root root   26728 sty 28  2017 ntfscat
-rwxr-xr-x  1 root root   30824 sty 28  2017 ntfscluster
-rwxr-xr-x  1 root root   34920 sty 28  2017 ntfscmp
-rwxr-xr-x  1 root root   34928 sty 28  2017 ntfsfallocate
-rwxr-xr-x  1 root root   39024 sty 28  2017 ntfsfix
-rwxr-xr-x  1 root root   55416 sty 28  2017 ntfsinfo
-rwxr-xr-x  1 root root   31928 sty 28  2017 ntfsls
-rwxr-xr-x  1 root root   30824 sty 28  2017 ntfsmove
-rwxr-xr-x  1 root root   38944 sty 28  2017 ntfstruncate
-rwxr-xr-x  1 root root   47752 sty 28  2017 ntfswipe
lrwxrwxrwx  1 root root       6 sty 25 14:27 open -> openvt
-rwxr-xr-x  1 root root   18968 wrz 22  2016 openvt
lrwxrwxrwx  1 root root      14 sty 25 14:27 pidof -> /sbin/killall5
-rwsr-xr-x  1 root root   44168 maj  7  2014 ping
-rwsr-xr-x  1 root root   44680 maj  7  2014 ping6
-rwxr-xr-x  1 root root   35504 wrz  4  2016 plymouth
-rwxr-xr-x  1 root root   97408 lis 21  2016 ps
-rwxr-xr-x  1 root root   31472 mar  2  2017 pwd
lrwxrwxrwx  1 root root       4 sty 25 14:27 rbash -> bash
-rwxr-xr-x  1 root root   39632 mar  2  2017 readlink
-rwxr-xr-x  1 root root      89 kwi 26  2014 red
-rwxr-xr-x  1 root root   60272 mar  2  2017 rm
-rwxr-xr-x  1 root root   39632 mar  2  2017 rmdir
lrwxrwxrwx  1 root root       4 sty 25 14:27 rnano -> nano
-rwxr-xr-x  1 root root   19320 sty 26  2016 run-parts
-rwxr-xr-x  1 root root   73424 lut 12  2016 sed
-rwxr-xr-x  1 root root   36296 lut  7  2016 setfacl
-rwxr-xr-x  1 root root   39952 wrz 22  2016 setfont
-rwxr-xr-x  1 root root   30875 lut  1  2017 setupcon
lrwxrwxrwx  1 root root       4 sty 25 14:27 sh -> dash
lrwxrwxrwx  1 root root       4 sty 25 14:27 sh.distrib -> dash
-rwxr-xr-x  1 root root   31408 mar  2  2017 sleep
-rwxr-xr-x  1 root root  115816 gru  7 01:00 ss
lrwxrwxrwx  1 root root       7 sty 25 14:27 static-sh -> busybox
-rwxr-xr-x  1 root root   72496 mar  2  2017 stty
-rwsr-xr-x  1 root root   40128 maj 17  2017 su
-rwxr-xr-x  1 root root   31408 mar  2  2017 sync
-rwxr-xr-x  1 root root  659848 mar  8 18:51 systemctl
lrwxrwxrwx  1 root root      20 mar  8 18:51 systemd -> /lib/systemd/systemd
-rwxr-xr-x  1 root root   51656 mar  8 18:51 systemd-ask-password
-rwxr-xr-x  1 root root   39344 mar  8 18:51 systemd-escape
-rwxr-xr-x  1 root root   64080 mar  8 18:51 systemd-hwdb
-rwxr-xr-x  1 root root  281840 mar  8 18:51 systemd-inhibit
-rwxr-xr-x  1 root root   47544 mar  8 18:51 systemd-machine-id-setup
-rwxr-xr-x  1 root root   35248 mar  8 18:51 systemd-notify
-rwxr-xr-x  1 root root  133704 mar  8 18:51 systemd-tmpfiles
-rwxr-xr-x  1 root root   68032 mar  8 18:51 systemd-tty-ask-password-agent
-rwxr-xr-x  1 root root   23144 lis 30 21:04 tailf
-rwxr-xr-x  1 root root  383632 lis 17  2016 tar
-rwxr-xr-x  1 root root   10416 sty 26  2016 tempfile
-rwxr-xr-x  1 root root   64432 mar  2  2017 touch
-rwxr-xr-x  1 root root   27280 mar  2  2017 true
-rwxr-xr-x  1 root root  449136 mar  8 18:51 udevadm
-rwxr-xr-x  1 root root   14328 lip 12  2016 ulockmgr_server
-rwsr-xr-x  1 root root   27608 lis 30 21:04 umount
-rwxr-xr-x  1 root root   31440 mar  2  2017 uname
-rwxr-xr-x  1 root root    2301 paź 27  2014 uncompress
-rwxr-xr-x  1 root root    2762 wrz 22  2016 unicode_start
-rwxr-xr-x  1 root root  126584 mar  2  2017 vdir
-rwxr-xr-x  1 root root   10552 mar  3  2016 vmmouse_detect
-rwxr-xr-x  1 root root   31376 lis 30 21:04 wdctl
-rwxr-xr-x  1 root root     946 sty 26  2016 which
-rwxr-xr-x  1 root root   27432 sty 18  2016 whiptail
lrwxrwxrwx  1 root root       8 sty 25 14:27 ypdomainname -> hostname
-rwxr-xr-x  1 root root    1937 paź 27  2014 zcat
-rwxr-xr-x  1 root root    1777 paź 27  2014 zcmp
-rwxr-xr-x  1 root root    5764 paź 27  2014 zdiff
-rwxr-xr-x  1 root root     140 paź 27  2014 zegrep
-rwxr-xr-x  1 root root     140 paź 27  2014 zfgrep
-rwxr-xr-x  1 root root    2131 paź 27  2014 zforce
-rwxr-xr-x  1 root root    5938 paź 27  2014 zgrep
-rwxr-xr-x  1 root root    2037 paź 27  2014 zless
-rwxr-xr-x  1 root root    1910 paź 27  2014 zmore
-rwxr-xr-x  1 root root    5047 paź 27  2014 znew

>

**Comment by bizlevel** [comment]
usually build/bin/xmr-stak

```
git clone ....
mkdir ./xmr-stack/build
cd xmr-stack/build
cmake ..
make
ls -la bin/xmr-stak
```
