### ISSUE TITLE
MONERO_MEMORY undefined

### ISSUE THREAD

**Issue by aperets** [fireice-uk/xmr-stak#1214]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'MONERO_MEMORY': undeclared identifier	xmr-stak-backend autoAdjust.hpp	43

**Comment by psychocrypt** [comment]
This is in bug (we have a second issue open). I will fix it. Please use as
workaround hwloc to compile the miner.

**Comment by Keksov** [comment]
Looks like this bug has nothing to do with HWLOC_ENABLE. To my mind, if I have -DCPU_ENABLE=OFF then compiler shouldn't compile CPU backend related stuff at all...

Correct me if I'm wrong, but the fix is trivial:
Put two lines:
```
        hashMemSizeKB = cn_select_memory(::jconf::inst()->GetMiningAlgo()) / 1024u;
        halfHashMemSizeKB = hashMemSizeKB / 2u;
```
        
instead of the old code:
```
		if(::jconf::inst()->IsCurrencyMonero())
		{
			hashMemSizeKB = MONERO_MEMORY / 1024u;
			halfHashMemSizeKB = hashMemSizeKB / 2u;
		}
		else
		{
			hashMemSizeKB = AEON_MEMORY / 1024u;
			halfHashMemSizeKB = hashMemSizeKB / 2u;
		}
```

**Comment by fireice-uk** [comment]
@Keksov CPU back-end is needed for checking the GPU results.

**Comment by Keksov** [comment]
Oh, I see... Does it also mean that I need HWLOC_ENABLE=ON for better performance even if I don't use CPU for mining?
