### ISSUE TITLE
Segmentation fault (ver 2.3.0)

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#1217]
Ubuntu 16.04 LTS
Driver 390.12
CUDA 9.1
6x GTX 780 3Gb (Kepler)
xmr-stak v 2.3.0

`./xmr-stak --currency electroneum -o support.ipbc.io:7777 -u b********FN4 -p x`

Tried to upgrade from 2.1.0 to 2.3.0, compiled myself, no errors during compilation. Version 2.1.0 ran fine. Removed cpu.txt, nvidia.txt, config.txt to allow miner to create new ones. On start I get "Segmenataion fault (core dumped)".  Tried using monero, cryptonight, electroneum as coin type.
```
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-26 18:18:40] : Mining coin: electroneum
Segmentation fault (core dumped)
```
What should I do, what shoud I check? Coin is IPBC (just general Cryptonight).

Thanks!

**Comment by JerichoJones** [comment]
Please complete the template

**Comment by JerichoJones** [comment]
Closing due to lack of response.
