### ISSUE TITLE
Error when compiling C1189: You are trying to do a 32-bit build

### ISSUE THREAD

**Issue by Grimm2017** [fireice-uk/xmr-stak#122]
Any idea how I can fix this?

  c:\xmr-stak-dev\xmrstak\backend\cpu\crypto/cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to do
a 32-bit build. This will all end in tears. I know it. [C:\xmr-stak-dev\xmr-stak-backend.vcxproj]
  c:\xmr-stak-dev\xmrstak\backend\cpu\crypto\cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to do
a 32-bit build. This will all end in tears. I know it. [C:\xmr-stak-dev\xmr-stak-backend.vcxproj]

**Comment by psychocrypt** [comment]
Do you trying to compile it on a 32bit machine? Is you windows a 64bit
version?
We are not supporting 32bit systems.

**Comment by fireice-uk** [comment]
The default in MSVC gui is to build for 32-bits. Please follow our guide.
