### ISSUE TITLE
Invalid port number. Please enter a number between 0 and 65535.

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#1221]
when i try to run xmr-stak via cron @reboot root /xmr-stak/xmr-stak

I got huge not ending log file with:
```
- Do you want to use the HTTP interface?
Unlike the screen display, browser interface is not affected by the GPU lag.
If you don't want to use it, please enter 0, otherwise enter port number that the miner should listen on
Invalid port number. Please enter a number between 0 and 65535.
Invalid port number. Please enter a number between 0 and 65535.
Invalid port number. Please enter a number between 0 and 65535.
....

```
but xmr-stak not work, its stuck in memory and always logging last sentence...

But if just run in terminal - all is fine.

I find why all is it.
Because in this version need always set config file, it no reads file from work directory, also it try create new file in ~ directory.

**Comment by hieixu** [comment]
You can use a script to start xmr-stak.
```
#!/bin/sh
cd /xmr-stak/
./xmr-stak

```
save it as /root/xmr.sh , make it excutable

**Comment by psychocrypt** [comment]
The miner is searching for the default config files not near to the binary
instead the current work directory is used. If you prefere a other location
for the config file please provide the file via the option -c PATh-AND-FILE

**Comment by bizlevel** [comment]
Yes, there need add 3 config files for new version , it is no like in old version.

**Comment by Prasanth619** [comment]
Please advise how to fix this error message. Even i'm also getting the same error

**Comment by psychocrypt** [comment]
do you removed all old config files and started the miner ones interactive?

**Comment by Prasanth619** [comment]
Please advise how to remove the old config files

**Comment by psychocrypt** [comment]
delete all txt files in the same folder than the binary of xmr-stak

**Comment by Prasanth619** [comment]
yes I did now only xmr.stak and 4 files with .dll nly available

**Comment by psychocrypt** [comment]
and is it now working? If not remove all config diles again and post all
output! Please change our xmr addr. in the output.

**Comment by Prasanth619** [comment]
Rig identifier for pool-side statistics (needs pool support). Can be empty:

It is asking like this

**Comment by psychocrypt** [comment]
please copy all text from the terminal I need to see exactly all output.

**Comment by Prasanth619** [comment]
Please enter:
- Do you want to use the HTTP interface?
Unlike the screen display, browser interface is not affected by the GPU lag.
If you don't want to use it, please enter 0, otherwise enter port number that the miner should listen on
0
Configuration stored in file 'config.txt'
Please enter:
- Please enter the currency that you want to mine:
        - aeon
        - cryptonight
        - cryptonight_lite
        - edollar
        - electroneum
        - graft
        - intense
        - karbo
        - monero7
        - sumokoin

monero7
- Pool address: e.g. pool.usxmrpool.com:3333
trtl.mine2gether.com
- Username (wallet address or pool login):
TRTLuyVrodW437843BoAwf1KfSHgFKHMJ8u7oqiA9MQRjkG5BaG4cGh3Nm8fycG4vfBtad9GNFbe1auF22n4qP8Jh2A12nW7qhF
- Password (mostly empty or x):
x
- Rig identifier for pool-side statistics (needs pool support). Can be empty:

**Comment by psychocrypt** [comment]
again please post all output and **NOT** only the first lines. The issue of
this pr is that the some message is shown multiple times. You never postet
any output where I can see that this message is repeated

**Comment by Prasanth619** [comment]
there are the actual lines.. no other included there

**Comment by psychocrypt** [comment]
than please open a new issue. This issue handles the error that the port
number questions is shown multiple times. we handle over 20 issues per day
if you mix different problems than we can not solve it.
