### ISSUE TITLE
2.3.0 loses 100h/s rather than 2.2.0

### ISSUE THREAD

**Issue by nightsuspect** [fireice-uk/xmr-stak#1226]
2.3.0 loses 100h/s rather than 2.2.0
amd ryzen 7 1700 + 1050 ti O4G ASUS
2.2.0: 770h/s
2.3.0: 678 h/s
commands that i use in batch file:
del config.txt
del cpu.txt
del amd.txt
del nvidia.txt
del pool.txt
xmr-stak.exe --currency cryptonight -o xmr.pool.minergate.com:45560 -u email@gmail.com -p x -i 0 -r 0

**Comment by psychocrypt** [comment]
please provide the cpu tye too. do you lose the hash rate on gpu or cpu.

**Comment by nightsuspect** [comment]
loses hashrate on GPU and i said cpu is "AMD RYZEN 7 1700"
on cpu each core has about 58h/s in both 2.2.0 and 2.3.0
but GPU in 2.2.0 has 300-320h/s but in 2.3.0 has 200-220h/s

**Comment by psychocrypt** [comment]
please post the config you used for both tests (nvidia.txt)

**Comment by nightsuspect** [comment]
del config.txt
del cpu.txt
del amd.txt
del nvidia.txt
xmr-stak.exe --currency monero -o xmr.pool.minergate.com:45560 -u email@gmail.com -p x

**Comment by psychocrypt** [comment]
please post the config for both tests. It could be that the default
settings differ.

**Comment by nightsuspect** [comment]
i was guessing this ofcourse but i thought maybe you know it yourself

2.2.0

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3372/4096 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 36, "blocks" : 18,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],


2.3.0
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3372/4096 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 8, "blocks" : 18,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by Simaex** [comment]
@nightsuspect just change threads to the same count for starter.

**Comment by nightsuspect** [comment]
no no i want it work correctly as first time i want it config it automaticly TRUELY

**Comment by psychocrypt** [comment]
I change the auto adjust because there where a lot issues with that,
therefore we switch to some more conservative. Please update nvidia.txt to
the old settings and than start the miner with --nvidia configFileName if
you need different configurations.

**Comment by psychocrypt** [comment]
If editing the cfg is not possible for you please describe your workflow
which prevent you from changing the cfg once.

**Comment by nightsuspect** [comment]
yes i cant change config file and each start can need a different config file so i use old version

**Comment by psychocrypt** [comment]
but could you please describe your workflows. We can only improve our miner
if we know the workflows of different users.

**Comment by nightsuspect** [comment]
your software is one of softwares that i use under control of my controller program and if a graphic card failed to work some1 will change it and im not there so they cant config it auto-config is for that situation

**Comment by rhlug** [comment]
refer Issue #1216 

xmrig might be a better solution for you, since its CPU only instead of xmr-stak which bundled cpu+gpu together.

**Comment by psychocrypt** [comment]
do you change the gpus so often? I will think about this issue.

**Comment by nightsuspect** [comment]
thank you and why there is not 32bit version ? its performance is excellent but there is not 32bit version why ?

**Comment by psychocrypt** [comment]
There are no 32bit cpus (with attractive performance) available since ~10
years. Which 33bit cpu is giving more than 100H/s?

**Comment by nightsuspect** [comment]
hahaha CPU is not important OS is important a 64bit cpu can handle a 32bit OS

**Comment by psychocrypt** [comment]
Why would you run a 32bit OS?

**Comment by nightsuspect** [comment]
sometimes for lowprofile systems we dont buy more than 2gb ram and for 64bit os you need more than 2gb i know that we can run 64bit os on it but its not optimal

**Comment by petrvecera** [comment]
You don't need more than 2GB of ram for 64bit OS
https://www.microsoft.com/en-us/windows/windows-10-specifications

There is no reason to build or distribute 32bit binaries anymore. All modern CPUs are 64bit...

I don't understand why you can't use the same config. 

Remove 
```
del amd.txt
del nvidia.txt
```
from your script and edit the configs, problem solved ...

**Comment by nightsuspect** [comment]
ofcourse there is a lot of reasons and a 32bit version is not useless its a separate version why its problem for you ? and need just small changes in source code and ofcourse windows 10 has some fantasy advantages rather than xp but base kernel is xp yet dont lure yourself

**Comment by nightsuspect** [comment]
i have not neufilia and when i compile my programs i use 32bit version and compiled for win xp for compatibilty with all OSes

**Comment by nightsuspect** [comment]
even windows 10 has duel start menu for holding all users open mind and learn something there is a lot of experience behind their jobs you want experience them again ?

**Comment by nightsuspect** [comment]
Centos version is dead 0-7 h/s
yam has 16-20h/s atleast

**Comment by petrvecera** [comment]
Here are compile instructions https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md , you can try to do a 32bit build. When you do, you can put the PR with the improved instructions.

**Comment by nightsuspect** [comment]
please test before saying it i was tested this:
cmake -G "Visual Studio 15 2017 " -T v141,host=x86 ..
cmake -G "Visual Studio 15 2017 " -T v141 ..
cmake -G "Visual Studio 15 2017 " ..
CMake Error: Could not create named generator Visual Studio 15 2017

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Deprecated.  Generates Visual Studio 2005
                                 project files.  Optional [arch] can be
                                 "Win64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Comment by daiaji** [comment]
In fact, I also really need xmr-stak to work under 32bit OS.
32bit OS actually saves memory

**Comment by nightsuspect** [comment]
please GETBACK autoconfig for NVIDIA GPUs

**Comment by nightsuspect** [comment]
@psychocrypt  psychocrypt please GETBACK autoconfig for NVIDIA GPUs

**Comment by nightsuspect** [comment]
its not silly its necessary when you are not there anymore and you will not be there

**Comment by Spudz76** [comment]
If the xmr-stak.exe never changes then the config files do not need regenerated.   ?

**Comment by psychocrypt** [comment]
Yes co fig files must be only recreated if you change to a version which
has incompatible changes. If you stay whith one version there is no need to
recreate te co fig if all works fine.

**Comment by nightsuspect** [comment]
@psychocrypt  how i can getback autoconfig myself which files should be edited and compile them again ?
and if i compile it for cuda 9.1 its faster with 1050 ti or is same with cuda 8 as i saw precompiled binaries all compiled for cuda 8.0
