### ISSUE TITLE
1080ti hashes constant but hashrate output (na) most of the time

### ISSUE THREAD

**Issue by kth5** [fireice-uk/xmr-stak#1228]
The hashrate of the 1080ti card (NVIDIA ID 0) most of the time displays as **(na)** yet it hashes at around 770H/s. It does recover from time to time and does not to actually seem to impact number of shares submitted loosely compared to ccminer-cryptonight by KlausT.

The same issue existed within the dev branch leading to the 2.3.0 release.

Example:
![image](https://user-images.githubusercontent.com/1784992/37956545-3a5b7ece-31de-11e8-82cf-cff5e7f0493a.png)

# Basic information
  - Intel Celeron G3930
  - 1x Zotac 1080Ti Founders Edition 11GB
  - 2x Zotac 1060 Mini 3GB
  - 1x Gigabyte RX580 8GB

# Issue with the execution
  - Do you compiled the miner by our own? - Yes
  ```
  Version: xmr-stak/2.3.0/a036cd8/makepkg/lin/nvidia-amd-cpu/aeon-cryptonight-monero/0
  ```

# Compilation:
  ```
cmake . -DXMR-STAK_COMPILE=generic -DOpenCL_ENABLE=ON -DCUDA_ENABLE=ON
make -j2
  ```

# Compiled with:
- Archlinux x86_64
- Cuda 9.1.85.2
- GCC 6.4.1
- hwloc 1.11.9
- OpenSSL 1.1.0g

# AMD OpenCl issue

No issue there but check attached [clinfo.txt](https://github.com/fireice-uk/xmr-stak/files/1851143/clinfo.txt).

# Stability issue
  - Is the CPU or GPU overclocked? - No
  - Is the Main memory of the CPU or GPU undervolted? - No

**Comment by psychocrypt** [comment]
reduce the treads for this gpu! The gpu is to slow to calculate a bunch of
hashes within 10sec.

**Comment by JerichoJones** [comment]
---
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---
