### ISSUE TITLE
How to run xmr-stak in the background(windows)?

### ISSUE THREAD

**Issue by sailei00** [fireice-uk/xmr-stak#1229]
Is there any option can make xmr-stak run in the background?Like the option in xmrig's config file:
`      "background": false,    // true to run the miner in the background `

**Comment by djfinch** [comment]
```
start /B xmr-stak.exe
```

**Comment by psychocrypt** [comment]
yes use start but goto config.txt and change 'daemon_mode' to true to avoid
that the miner stops in the background.

**Comment by zifootball** [comment]
same here i need to run xmr-stake without admin

**Comment by psychocrypt** [comment]
with `xmr-stak --help` you can see all available option. one is `--noUAC` disable the UAC dialog
