### ISSUE TITLE
Make it easier to enable/disable GPU and CPU mining.

### ISSUE THREAD

**Issue by phxn** [fireice-uk/xmr-stak#1232]
Hello,

I'd like to request a feature. Would you consider adding a "enable" and "disable" switch in the configs to enable/disable CPU/GPU mining easily?

Sometimes I like to disable my GPU miner so that I can do more GPU intensive tasks, but since you merged both miners into one, it's become more of a chore to disable it.

Many thanks

**Comment by psychocrypt** [comment]
This is already possible if you create two bat files which calling the
miner. To disable amd gpu add the command line option --noAMD and to
disable Nvidia gpus add --noNVIDIA

**Comment by phxn** [comment]
Aha! Thank you, I'll give it a go.
