### ISSUE TITLE
how to run xmr-stake without admin privileges

### ISSUE THREAD

**Issue by zifootball** [fireice-uk/xmr-stak#1233]
hello, how to run xmr-stake without admin privileges??

**Comment by djfinch** [comment]
?
```
--noUAC
```
...read the docs...

**Comment by zifootball** [comment]
where to find that i'am really sorry if the question was too stupid :/

**Comment by djfinch** [comment]
sorry, it is not there... :/
you have to test it. i'm not sue if -noUAC just suppress UAC dialog or disable admin priv completely.
anyway, admin rights are needed to enable hugepages though.

**Comment by psychocrypt** [comment]
please run xmr-stak -h    to see all options
