### ISSUE TITLE
Typo in text output when mining begins

### ISSUE THREAD

**Issue by qwertycian** [fireice-uk/xmr-stak#1235]
When mining begins, and the miner loads precompiled **code** from a certain location, the following message is displayed:

"OpenCL device 0 - Load precompiled cod from file "

I don't think the fish has anything to do with mining...

**Comment by djfinch** [comment]
Done... https://github.com/fireice-uk/xmr-stak/pull/1237

**Comment by qwertycian** [comment]
Excellent, thank you!
