### ISSUE TITLE
Feature Request - Support Stellite's algorithm change from Cryptonight to Cryptonight V1

### ISSUE THREAD

**Issue by stellitecoin** [fireice-uk/xmr-stak#1241]
# Summary 

Due to the introduction of ASIC's into the cryptonight community Stellite (XTL) has decided to fork to Monero's variant of cryptonight. The changes are already being well tested and we're requesting to have the Variant 1 algo adjusted for Stellite's block version(3)

# Details

Stellite at V3 hardfork will use the same algorithm as monero V7 hardfork so not much changes will be required to xmr-stak, Our major block version will be 3.

# Testing V3

A community member @sebseb7 has set up a test pool at https://cryptoknight.cc/v3/, It is now in the forked state so it will accept the new variant hashes

# Further References 

Stellite's Testnet branch on github with the latest PoW activating at height 20 :- [V3 Private Testnet](https://github.com/stellitecoin/stellite/tree/V3PrivateNet)

**Comment by fireice-uk** [comment]
Hi. Our minimum standards for coin inclusion are 1MH/s hashrate and a website. Do you have those?

**Comment by xmrig** [comment]
Why not just bump block version to 7? like AEON do. Please don't start versioning hell.
Thank you.

**Comment by stellitecoin** [comment]
@fireice-uk, yes we do have a website, https://stellite.cash and our net hash on average is 6MH/s

**Comment by sebseb7** [comment]
"Why not just bump block version to 7? like AEON do. Please don't start versioning hell.
Thank you."

There is no way out of the "versioning hell" anyway. Like graft ist at version 7 already but with still on algo variant 0.
castxmr solves this by having "--algo 0 , 1 , auto " (auto means detection at v7)

**Comment by xmrig** [comment]
I know about GRAFT, It's GRAFT issue, when decision about v7 happen no one know about some other coin already bump version to 7. It happen, nothing can do.

Stellite position is different, instead of smooth update, manual action will required for all miners, instead of automatic variant choice in others miners and this with `monero7`.

**Comment by sebseb7** [comment]
"instead of automatic variant choice "

this was intentional. Coins are not designed around mining software, it's the other way.

The question is not wether graft and stellite will consult xmrstack for coin development, the question is: can we use xmr-stack to mine it? yes/no?

xmrig works, and so does castxmr, will stack follow or do we need to use the custom builds that fix the problem?

**Comment by fireice-uk** [comment]
@sebseb7 @xmrig 

Miners are for mining, not blockchain verification. We plan to remove all version checking code in the next release, so I'm not sure what the fuss is about.

**Comment by fireice-uk** [comment]
@sebseb7 

> ". It happen, nothing can do."
> xmrig works, and so does castxmr, will stack follow or do we need to use the custom builds that fix the problem?

I think you got confused here, you were talking to xmrig dev there.

**Comment by sebseb7** [comment]
I know who I am talked to. It's the irony that xmrig actually works.

**Comment by psychocrypt** [comment]
Can someone provide me please with a test address for the test pool?

**Comment by psychocrypt** [comment]
A test was not possible because of the missing test net address 
https://github.com/fireice-uk/xmr-stak/pull/1273

**Comment by stellitecoin** [comment]
@psychocrypt sorry for the late reply, 
Se321oJNkfaGrN89Vmq6qGZb8587L53u2NVZbCrhhJujemaGMVNmr952oEsQAKGFojevSWDNcJK8GS8Sy4manyrG2okoPyvfa, this address can be used to mine on the testpool.

Thank you

**Comment by MoNTE48** [comment]
Hi. I get this error
```
[2018-04-10 02:12:06] : Fast-connecting to pool.xtl.cryptopool.space:5555 pool ...
[2018-04-10 02:12:06] : Pool pool.xtl.cryptopool.space:5555 connected. Logging in...
[2018-04-10 02:12:08] : Pool logged in.
[2018-04-10 02:12:12] : Result rejected by the pool.
[2018-04-10 02:12:12] : Result rejected by the pool.
[2018-04-10 02:12:13] : Result rejected by the pool.
[2018-04-10 02:12:13] : New block detected.
```

**Comment by psychocrypt** [comment]
please open a new issue and provide all configs. This is an feature request
