### ISSUE TITLE
I'd like the version for the xeon phi also. 

### ISSUE THREAD

**Issue by ardatious** [fireice-uk/xmr-stak#1242]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by komawoyo** [comment]
with a bit of googling you can find a software for xeon phi specific, I would rather have this project focus on the current backend

**Comment by psychocrypt** [comment]
Which xeon phi do you mean. KNL or older?

**Comment by ardatious** [comment]
The KNL 7210 in my case. I am using the SuperMicro 2u4n server with four
phi nodes. I am using it with lukminer which is a great piece of software.
However someone on another thread here (closed now) said he used the stak
software on it with 7250 and got 22kh/s with 7250s. This is fast. I'd like
to find out how he got it working, but I don't have his email and the
thread is closed. I haven't run stak on it, but cpuminer-multi only sees 16
processors and runs at 373h/s.

I'm wondering if he used opencl or did something else. The 7210s are slower
than the 7250s, but not by 2 to 1.

In response to the other comment, I think the idea of open source
development is that we can use all the past contributions to it and
contribute our own, as long as we are willing to use future users to do the
same. I would not mind starting a new fork if I can get this running with
the phi.

After I looked at the cpuminer-multi code, I saw several things that would
benefit from optimization. Then I found stak, which has many optimizations
in place.

I have 26 more 4n2u servers on order and would like to get the best
profitability out of each one. If the stak software will help me do that, I
would like to use it.

I am also mining on old Dell servers and I will be testing xmr-stak there
very soon.

The newest intel servers we sell in our other business have up to 18 cores
per CPU, but they are too expensive for mining, I think.

on the SuperMicro server, we are booting ubuntu 16.04.4 on the xeon phi
cpu. it is not a coprocessor. There is no other cpu chip in the system.

with lukminer mining to xmr on nicehash, we generated $14.50 gross revenue
in one 24 hour period, at a cost of about $3.50 in electricity at 11 cents
a kwh. We are planning to put in our own natural-gas generator which should
get the electric cost below 5 cent per kwh.

Since the electric cost is basically fixed, even a small increase in
revenue makes a big difference in the profit.

**Comment by psychocrypt** [comment]
Do you tried xmr-stak. KNL is also x86 therefore the miner supports the
system without changes.

**Comment by ardatious** [comment]
ha ha first error message is 'you are trying to do a 32 bit build, i know
this will all end in tears'

and it did

here is my cpu info for intel  es5620

lscpu
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
Stepping:              2
CPU MHz:               2393.797
BogoMIPS:              4787.59
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K

**Comment by ardatious** [comment]
architecture i686 means I have 32 bit ubuntu installed. i don't know why it
installed that instead of 64 bit. ill go try to figure that out. i did the
install on this same machine

**Comment by ardatious** [comment]
i installed ubuntu 16.04.4 64 bit

i had to use the -f on apt commands to install cmake and git

did cmake and make and everything seemed to have worked.

where do I go to run the binary? i browsed thru several directories and cant find it

**Comment by hieixu** [comment]
binary is under your build/bin directory. 
you can copy it to somewhere like /usr/bin/

**Comment by ardatious** [comment]
I forgot you cannot execute xmr-stak, you have to execute ./xmr-stak

im an old unix guy. i don't know if all of linux is this stupid (like not
allowing root login, but you have to type sudo a billion times to do the
same thing)

meanwhile back at the ranch, i compiled everything up and ran xmr-stak. 272
hashes per second on a dell r410, versus lukminer's 372.  have'nt actually
tested xmr-stak on nicehash for 24 hour timed trial yet.

did the same setup again and ran it on one node of the supermicro phi 7210
system.

for some reason it only ran on the even numbered cores, 32 out of 64, at 8
hashes per second on a core.

i manually edited cpu.txt and added the odd numbered cores, that gave me 64
cores running at 6.7 hashes per second.

total was about 480 hashes per second. for reference, lukminer on a dual
5620 8-core dell r410 runs at 372 hashes per second.

lukminer on the 7210 phi machine node runs on the 4 virtual threads per
core, using 254 threads and a total hash rate of 2570 hashes per second
(cryptonight).

multiply that by 4 for all nodes.

however he is writing the code to take full advantage of the phi. his
numbers check out with the predictions from whattomine. a 4 7210 node
system generates a smidgen more than 24 nvidia gtf 1060s. the 4 node system
pulls 1350 watts while crunching.

the person who reported getting 22khs on a 7210 node or coprocessor, may
have been using opencl.

**Comment by psychocrypt** [comment]
If you like you can also use 4 threads per core in xmr-stak. Set low power
mode to 4.

**Comment by ardatious** [comment]
could you reopen the thread where j Daniel says he got 22k on the phi, so I
can ask him how he did it?
