### ISSUE TITLE
hwloc: can't bind memory

### ISSUE THREAD

**Issue by agentpatience** [fireice-uk/xmr-stak#1243]
I am getting this error on AMD 6234. DO you know what it is caused by?
* hwloc 1.11.5 has encountered what looks like an error from the operating system.
*
* L3 (cpuset 0x000fc000) intersects with NUMANode (P#4 cpuset 0x0003f000) without inclusion!
* Error occurred in topology.c line 1074

Lubuntu 17

**Comment by JerichoJones** [comment]
I believe this is a known bug that should be resolved in the next release.

**Comment by agentpatience** [comment]
I filed another issue, relating to CentOS, the thing with CentOS is that is is performing very well despite the errors and the NUMA error is not present.
