### ISSUE TITLE
AES-NI on XEON E5606 not work

### ISSUE THREAD

**Issue by remark23** [fireice-uk/xmr-stak#1245]
My processor Xeon E5606 in IBM x3400 M3 server support AES-NI:
https://ark.intel.com/products/52583/Intel-Xeon-Processor-E5606-8M-Cache-2_13-GHz-4_80-GTs-Intel-QPI

XMR-Stak_Win64 says: "Your CPU doesn't support hardware AES."

Why?

**Comment by marki555** [comment]
Does for example `CPU-Z` report your CPU as having AES-NI supported/enabled?

**Comment by remark23** [comment]
For me NO.
But: http://valid.x86.fr/5654ew

I'll do the UEFI update first..

**Comment by remark23** [comment]
I can not activate AES-NI on my IBM x3400 M3 server. In uEFI settings there is no option for AES-NI Enable/Disable. I updated uEFI firmware but again the same problem occurs.

**Comment by psychocrypt** [comment]
please look to config.txt there is an option to force enable aes-ni. Try if
this helps. If the miner crash than there is no aes-ni available

**Comment by remark23** [comment]
I already tried that and miner crash!
I think, processor support AES-NI but it is not enabled on motherboard. Probably there is no solution.

**Comment by changpeng75** [comment]
Use CPU-Z to confirm your cpu is 5606.

**Comment by remark23** [comment]
![cpu-z e5606](https://user-images.githubusercontent.com/37160304/38093016-032708be-336a-11e8-897c-3f82f5fe7488.jpg)

**Comment by changpeng75** [comment]
AES-NI support is option for IBM M3 Server? Need to crack it?
https://www.bios-mods.com/forum/Thread-REQUEST-REWARD-Add-AES-NI-support-to-IBM-x3500-M3-firmware

**Comment by remark23** [comment]
It's very complicated and risky..

**Comment by jkelly99** [comment]
I have a few x3650 m3 servers with L5430 CPU's and some of them came with AES-NI disabled. Someone was kind enough to share this link with me. I have used this process 2 times so far and it has worked for me.

[http://www.cievo.sk/2013/04/23/problems-with-cpu-in-incompatible-error-during-vmware-vmotion/]

Hopefully it it will be of some use to you as well.

**Comment by remark23** [comment]
Thanks. I already tried it but failed. On my uEFI flag uEFI.AesEnable does not exist. (uEFI firmware is latest)
It seems that the motherboard at x3400 M3 does not support it. :(

**Comment by DrStein99** [comment]
I am glad I read this.  Marking down "IBM X3650" on my list of servers to avoid buying.  Nothing like a booby-trap from manufacturer to prevent me from using the hardware they sell me.

**Comment by remark23** [comment]
IBM Advanced Settings Utility version 9.63.86D
Licensed Materials - Property of IBM
(C) Copyright IBM Corp. 2007-2014 All Rights Reserved
Successfully discovered the IMM via SLP.
Discovered IMM at IP address 169.254.95.118
Connected to IMM at IP address 169.254.95.118
**Could not find setting UEFI.AesEnable**

**Comment by changpeng75** [comment]
Xeon 54xx not support AES-NI.

**Comment by changpeng75** [comment]
remark23, can you use native BIOS setup?

**Comment by remark23** [comment]
My processor is Xeon E5606 (56xx, not 54xx) and support AES-NI:
https://ark.intel.com/products/52583/Intel-Xeon-Processor-E5606-8M-Cache-2_13-GHz-4_80-GTs-Intel-QPI

Native BIOS setup? What is this? Direct entry into BIOS setup, not with ASU?
I tried it, but no settings for AES.

**Comment by changpeng75** [comment]
Are you use VMs (exp Esxi)?

**Comment by remark23** [comment]
No, this is standalone Windows Server 2008 R2.

**Comment by changpeng75** [comment]
So,I think your system's original CPU is 5506,IBM disable the AES-NI support to prevent end user upgrade CPU.

**Comment by remark23** [comment]
It's possible.

**Comment by JerichoJones** [comment]
Closing as this is not a STAK issue.

**Comment by yyfong0918** [comment]
have you tried to reset the BIOS settings?  my x3550m2 + 2xX5650 need to reset BIOS and AES-NI appear.
