### ISSUE TITLE
clBuildProgramm error

### ISSUE THREAD

**Issue by rio-redstone** [fireice-uk/xmr-stak#1246]
I complied xmr-stak with OpenCL enabled on macOS 10.12, and ran it.
but in initialization, I had the error like below.

  ```
<program source>:1337:46: error: parameter may not be qualified with an address space
inline uint4 mix_and_propagate(__local uint4 xin[8][WORKSIZE])
  ```

it seems that xin in cryptonight.cl causes this error.

how can I fix this??

I can compile and run the 2.2.0 with OpenCL enabled on macOS 10.12.

**Comment by djfinch** [comment]
@rio-redstone Seems it's OSX-specific cause I have similar problem but even worse. What version of OpenCL is used? Mine is 1.2 (pretty old MacPro). IMHO it's something with Xcode's OpenCL Framework... https://github.com/fireice-uk/xmr-stak/issues/1218

**Comment by creaktive** [comment]
Same here, unfortunately... Except 2.2.0 doesn't run either

**Comment by fireice-uk** [comment]
#1265
