### ISSUE TITLE
CL_INVALID_BUFFER_SIZE Error

### ISSUE THREAD

**Issue by bodcat** [fireice-uk/xmr-stak#1249]
Have been running prior version of xmr-stak for a good while and am trying to upgrade to the new version prior to the fork.

I am running 2 x RX570 and 2 x Vega 56 cards on an Intel CPU.
Operating System is Windows 10.

I have tried the following executables:
master source code compiled locally
release 2.3.0 source code compiled locally
release 2.3.0 windows executables

All 3 show the same issue.

Having allowed the app to generate the new config files, produces the following amd.txt
"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 1,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],

When I run xmr-stak with this config, it runs fine but at a low hash rate.

My prior amd.txt had the following:
"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 0,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 0,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 1,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 1,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
   { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },

When I attempt to tune the new amd.txt by adding a second entry for one of the Vega 56 cards, i get the following error:

Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer

The config in question is as follows:

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 1,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 3,
    "intensity" : 1832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],

What am I doing wrong?

Thanks

**Comment by bodcat** [comment]
So the first config I included above is the one that is generated by the new version of xmr-stak. I was trying to adjust only one card at a time to check that I had it correct. I had an intensity of 1932 with the prior version.

**Comment by bodcat** [comment]
So I have now got a config that does not crash:

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3712
  // compute units: 32
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  
  // gpu: Ellesmere memory:3712
  // compute units: 32
  { "index" : 1,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
   { "index" : 3,
    "intensity" : 512, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

However, as soon as I increase the intensity on the Vega 56's (indexes 2 & 3), I get the CL_INVALID_BUFFER_SIZE error.

**Comment by bodcat** [comment]
The hash rate for the Vega56 cards (with this config) is 900H/s - way lower than the 1900H/s I was getting on the previous version.

**Comment by bodcat** [comment]
Just for clarity, here is my old working config on the prior version:


/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 false = use a contiguous block of memory per thread
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 0,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 0,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: Ellesmere memory:3673
  // compute units: 32
  { "index" : 1,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 1,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
   { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,


And here is my modified new version to replicate the hashrate that now causes issues:


/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 * index         - GPU index number usually starts from 0
 * intensity     - Number of parallel GPU threads (nothing to do with CPU threads)
 * worksize      - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 2 = chunked memory, chunk size is controlled by 'mem_chunk'
 *                     required: intensity must be a multiple of worksize
 *                 1 or true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 0 or false = use a contiguous block of memory per thread
 * mem_chunk     - range 0 to 18: set the number of elements (16byte) per chunk
 *                 this value is only used if 'strided_index' == 2
 *                 element count is computed with the equation: 2 to the power of 'mem_chunk' e.g. 4 means a chunk of 16 elements(256byte)
 * comp_mode     - Compatibility enable/disable the automatic guard around compute kernel which allows
 *                 to use a intensity which is not the multiple of the worksize.
 *                 If you set false and the intensity is not multiple of the worksize the miner can crash:
 *                 in this case set the intensity to a multiple of the worksize or activate comp_mode.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3712
  // compute units: 32
  { "index" : 0,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3712
  // compute units: 32
  { "index" : 1,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 832, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
   { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

Any idea what is wrong?

**Comment by keepotalize** [comment]
Try seeing what gpu is the problem instead of trying all of them all out at once.

**Comment by bodcat** [comment]
Turned out I was using the wrong "coin" parameter - Doh! SHould have been using cryptonight to mine sumokoin, not the new sumokoin algo.
