### ISSUE TITLE
Best settings for GTX 1060 3GB

### ISSUE THREAD

**Issue by GrannyCryptomaster** [fireice-uk/xmr-stak#1251]
You said:
"The optimal parameter for the threads and blocks option in config.txt depend on your GPU. For all GPU's with a compute capability >=2.0 and <6.0 there is a restriction of the amount of RAM that can be used for the mining algorithm. The maximum RAM that can be used must be less than 2GB (e.g. GTX TITAN) or 1GB (e.g. GTX 750-TI). The amount of RAM used for mining can be changed with "threads" : T, "blocks : B".
    T = threads used per block
    B = CUDA blocks started (should be a multiple of the multiprocessors M on the GPU)
For the 2GB limit the equations must be full filled: T * B * 2 <= 1900 and B mod M == 0. The value 1900 is used because there is a little data overhead for administration. The GTX Titan X has 24 multiprocessors M, this means a valid and good starting configuration is "threads" : 16, "blocks : 48" and full fill all restrictions 16 * 48 * 2 = 1536 and 48 mod 24 = 0.
The memory limit for NVIDIA Pascal GPUs is 16 GiB if the newest CUDA driver is used."
I don't realy undestand from where is 2 and 1900 in that formula.

**Please, explain to me, because I'm a newbie, what is the exact formula for T and B, for this card:
nVidia GTX 1060 3GB, compute cap. 6.1, SMX 9, for Windows 10 x64bit, 8GB RAM, CUDA 9.
My rig has 6 of them.**
Thanks!

**Comment by psychocrypt** [comment]
Use the autogenerated settings and try to increase threads until the hash
rate goes down.

**Comment by JerichoJones** [comment]
---
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---

**Comment by Spudz76** [comment]
1900 is 2048 with a little bit of padding removed.  So you would use 3072 with a little padding removed.  Every cryptonight block uses 2MB which is where the 2 vs 1900 comes from (how many times does 2MB fit into total VRAM while leaving some scratch room for housekeeping).  The 2 part doesn't change.

You may run out of CUDA Cores before you fill memory, I definitely only use less than half on the 6GB 1060's...

**Comment by GrannyCryptomaster** [comment]
@Spudz76 - Thanks! It's been enlightning! :))
@JerichoJones - if you don't have something usefull to say, better shut up. I was refering to xmr-stak's first post in this thread. So here it's the proper place to ask.

Best settings for my card so far, in Windows, are 32x36 8x100.
See? That's a usefull info.

**Comment by scryptkyddy** [comment]
@GrannyCryptomaster on my 1060 3gb EVGAs i found 36Blocks 8 threads to work Ok, and my 2gb 1030 I use 24blocks 8 threads. No idea why... haha

@Spudz76 I appreciate your comments around here also, thanks.

**Comment by GrannyCryptomaster** [comment]
For cryptonight, use TxB 32x36... and bfxbs 8x100 if you use Windows. 
For cn-heavy use 16x32 with 3GB cards.
These are the best settings for xmr-stak and xmrig
