### ISSUE TITLE
Ubuntu 16.04/GTX 750Ti, compile error

### ISSUE THREAD

**Issue by AHBennett** [fireice-uk/xmr-stak#1254]
Attempting to compile xmr-stak after running the commands listed on https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md
I have followed all of the Ubuntu directions, as well as installing Cuda 9.
Here is my compile information after adding in the suggested command:

GhostFerret:~/xmr-stak/build$ make install -Wno-deprecated-gpu-targets
[ 80%] Built target xmr-stak-c
[ 80%] Built target xmr-stak-backend
[ 80%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : Could not open output file /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.NVCC-depend
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake:207 (message):
  Error generating
  /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

CMakeFiles/xmrstak_cuda_backend.dir/build.make:373: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
GhostFerret:~/xmr-stak/build$ 

  run `cmake -LA .` in the build folder and add the output here
GhostFerret:~/xmr-stak/build$ cmake -LA
CMake Error: The source directory "/home/ferret/xmr-stak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/ferret/xmr-stak/build
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;20;60;61;62
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart.so
CUDA_CUDA_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcuda.so
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=/usr/local/cuda/bin/nvcc
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TARGET_CPU_ARCH:STRING=
CUDA_TOOLKIT_INCLUDE:PATH=/usr/local/cuda/include
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_TOOLKIT_TARGET_DIR:PATH=/usr/local/cuda
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=8.0
CUDA_cublas_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcublas.so
CUDA_cudart_static_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart_static.a
CUDA_cufft_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcufft.so
CUDA_cupti_LIBRARY:FILEPATH=/usr/local/cuda/extras/CUPTI/lib64/libcupti.so
CUDA_curand_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcurand.so
CUDA_cusolver_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusolver.so
CUDA_cusparse_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusparse.so
CUDA_nppc_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnppc.so
CUDA_nppi_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnppi.so
CUDA_npps_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnpps.so
CUDA_rt_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/librt.so
HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
OpenCL_ENABLE:BOOL=OFF
OpenCL_INCLUDE_DIR:PATH=OpenCL_INCLUDE_DIR-NOTFOUND
OpenCL_LIBRARY:FILEPATH=OpenCL_LIBRARY-NOTFOUND
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

I have tried multiple times to bypass this issue, but nothing is working. Do I need to install Cuda 8 in order for GTX 750Ti to work?

Thanks in advance,
GhostFerret

**Comment by psychocrypt** [comment]
Could you please try coda 9.1. If you still have issues please compile until the error is shown and than run again `make VERBOSE=1` and post **all** output from the second run to this issue.

**Comment by AHBennett** [comment]
Ok, but I'm a novice. How do I install 9.1? Get it from NVidia?

**Comment by AHBennett** [comment]
`GhostFerret:~/xmr-stak/build$ make VERBOSE=1
/usr/bin/cmake -H/home/ferret/xmr-stak -B/home/ferret/xmr-stak/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/ferret/xmr-stak/build/CMakeFiles /home/ferret/xmr-stak/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/ferret/xmr-stak/build'
make -f CMakeFiles/xmr-stak-c.dir/build.make CMakeFiles/xmr-stak-c.dir/depend
make[2]: Entering directory '/home/ferret/xmr-stak/build'
cd /home/ferret/xmr-stak/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ferret/xmr-stak /home/ferret/xmr-stak /home/ferret/xmr-stak/build /home/ferret/xmr-stak/build /home/ferret/xmr-stak/build/CMakeFiles/xmr-stak-c.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/ferret/xmr-stak/build'
make -f CMakeFiles/xmr-stak-c.dir/build.make CMakeFiles/xmr-stak-c.dir/build
make[2]: Entering directory '/home/ferret/xmr-stak/build'
make[2]: Nothing to be done for 'CMakeFiles/xmr-stak-c.dir/build'.
make[2]: Leaving directory '/home/ferret/xmr-stak/build'
[ 80%] Built target xmr-stak-c
make -f CMakeFiles/xmr-stak-backend.dir/build.make CMakeFiles/xmr-stak-backend.dir/depend
make[2]: Entering directory '/home/ferret/xmr-stak/build'
cd /home/ferret/xmr-stak/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ferret/xmr-stak /home/ferret/xmr-stak /home/ferret/xmr-stak/build /home/ferret/xmr-stak/build /home/ferret/xmr-stak/build/CMakeFiles/xmr-stak-backend.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/ferret/xmr-stak/build'
make -f CMakeFiles/xmr-stak-backend.dir/build.make CMakeFiles/xmr-stak-backend.dir/build
make[2]: Entering directory '/home/ferret/xmr-stak/build'
make[2]: Nothing to be done for 'CMakeFiles/xmr-stak-backend.dir/build'.
make[2]: Leaving directory '/home/ferret/xmr-stak/build'
[ 80%] Built target xmr-stak-backend
make -f CMakeFiles/xmrstak_cuda_backend.dir/build.make CMakeFiles/xmrstak_cuda_backend.dir/depend
make[2]: Entering directory '/home/ferret/xmr-stak/build'
[ 80%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
cd /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code && /usr/bin/cmake -E make_directory /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/.
cd /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code && /usr/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=Release -D generated_file:STRING=/home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o -D generated_cubin_file:STRING=/home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o.cubin.txt -P /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake
-- Removing /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o
/usr/bin/cmake -E remove /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o
-- Generating dependency file: /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.NVCC-depend
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /home/ferret/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu -o /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DXMR_STAK_LARGEGRID=ON -DXMRSTAK_CUDA_ARCH_LIST=30+35+37+50+52+20+60+61+62 -DCONF_NO_OPENCL -DGIT_COMMIT_HASH=a036cd8 -DGIT_BRANCH=master -DBACKEND_TYPE=nvidia-cpu -Dxmrstak_cuda_backend_EXPORTS -Xcompiler ,\"-march=native\",\"-mtune=native\",\"-msse2\",\"-maes\",\"-fPIC\",\"-O3\",\"-DNDEBUG\" -std=c++11 --generate-code arch=compute_30,code=sm_30 --generate-code arch=compute_30,code=compute_30 --generate-code arch=compute_35,code=sm_35 --generate-code arch=compute_35,code=compute_35 --generate-code arch=compute_37,code=sm_37 --generate-code arch=compute_37,code=compute_37 --generate-code arch=compute_50,code=sm_50 --generate-code arch=compute_50,code=compute_50 --generate-code arch=compute_52,code=sm_52 --generate-code arch=compute_52,code=compute_52 --generate-code arch=compute_20,code=sm_20 --generate-code arch=compute_20,code=compute_20 --generate-code arch=compute_60,code=sm_60 --generate-code arch=compute_60,code=compute_60 --generate-code arch=compute_61,code=sm_61 --generate-code arch=compute_61,code=compute_61 --generate-code arch=compute_62,code=sm_62 --generate-code arch=compute_62,code=compute_62 --default-stream per-thread -DNVCC -I/usr/local/cuda/include -I/home/ferret/xmr-stak/. -I/usr/include -I/usr/local/cuda/include
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : Could not open output file /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.NVCC-depend
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake:207 (message):
  Error generating
  /home/ferret/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


CMakeFiles/xmrstak_cuda_backend.dir/build.make:373: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[2]: Leaving directory '/home/ferret/xmr-stak/build'
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make[1]: Leaving directory '/home/ferret/xmr-stak/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`
This is what I get for the > make VERBOSE=1

**Comment by AHBennett** [comment]
Any ideas what I can do to get the program to compile? Would really like to start using Linux, but cannot do it without a miner. Having to run Windows to keep the miner running right now.

**Comment by Spudz76** [comment]
Your build environment is locating CUDA 8 (you must have both versions installed?) otherwise nvcc would not know about the 20-series and CMake would not be including those.  It also says 8.0 in the CMakeCache you posted...

The actual error appears to be permissions related, try `sudo chown -R ferret. ~/xmr-stak` and then run the build again (CUDA 8 works fine, perhaps even better for the 30-level cards, IMO).

To get a build that uses CUDA 9 when some other version is installed as default, you can use defines on the CMake command line, such as this example:
``
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \
      -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0/bin/nvcc \
      -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0/include \
      -DCUDA_CUDART_LIBRARY=/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so \
      -DCUDA_SHOW_REGISTER=ON \
   ..
``
However you would use whatever location (possibly but not always `/usr/local/cuda-9.0` or 9.1) instead of the above which would do CUDA 8.

If you have a `/usr/local/cuda` which is a symbolic link to `/usr/local/cuda-8.0` you can also replace that link with one to the other version and re-run CMake again from a fresh build directory (CMake loves to cache so the foolproof way to force fresh is destroy with fire the previous build dir/attempt)

**Comment by AHBennett** [comment]
Thanks for the tips, I'll give this a shot. I've installed Cuda 9.1, and still get bogus errors, but have not run cmake -LA since then.

**Comment by AHBennett** [comment]
Ok, finally got a build, and it is running, but I am getting errors... MEMORY ALLOC FAILED: mmap failed from CPU threads...
Something to do with me not having access to huge pages or something?

**Comment by AHBennett** [comment]
Ok, no more memory error, but now I'm not able to get to console either. Running in CLI mode.

**Comment by Spudz76** [comment]
I am completely inexperienced with actually using GPUs as outputs, every miner is headless.

You may need to investigate the `nvidia-xconfig` utility to either repair or generate a new `/etc/X11/xorg.conf`

You will want `--cool-bits 28` or clocking doesn't work.  Then your clock tool is `nvidia-settings` but you must have nvidia driver working in Xorg first (no low-gfx mode and no errors in `/var/log/Xorg*`)

**Comment by Spudz76** [comment]
You also should use `nvidia-smi` to validate the kernel parts of the driver are working.  It can change some other settings without Xorg running as well, but only the powerlimit (if applicable on that card / may not be) and a few CUDA options.

If anything is trying to use `nouveau` light it on fire and make sure it isn't ever again.  Usually the install of nvidia driver packages will automatically blacklist the other one, but Xorg may not follow along (without regenerating xorg.conf)

**Comment by Spudz76** [comment]
For example (and yes there is no powerlimit on this series of GPU)
```
root@gm05:~# nvidia-smi
Thu Apr  5 16:05:38 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 770     On   | 00000000:01:00.0 N/A |                  N/A |
|100%   62C    P0    N/A /  N/A |   1788MiB /  1999MiB |     N/A   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```
My clocking script (must have Xorg running already) the pointless loop is for when there are more than one of the same card / to blast the settings across them all but this one just has single.
```
#!/bin/bash
echo $(nvidia-smi -L | wc -l)
DISPLAY=:0
for N in 0; do
  nvidia-smi -i $N -pm 1
  nvidia-smi -i $N -c 1
  nvidia-settings -c :0 -a [gpu:$N]/GPUFanControlState=1
  nvidia-settings -c :0 -a [fan:$N]/GPUTargetFanSpeed=100
  nvidia-settings -c :0 -a [gpu:$N]/GPUPowerMizerMode=1
  nvidia-settings -c :0 -a [gpu:$N]/GPUGraphicsClockOffset[3]=112
  nvidia-settings -c :0 -a [gpu:$N]/GPUMemoryTransferRateOffset[3]=624
done
```

And my xorg.conf in case it helps (this is headless / fakes a 640x480 minimal waste of VRAM screen)
Also ignore the references to fglrx this also has some AMD trash in it and if it tries to load that at the same time it chokes hard.
```
root@gm05:~# cat /etc/X11/xorg.conf
Section "ServerLayout"
        Identifier     "Layout0"
        Screen      0  "Screen0" 0 0
        Option      "AutoAddDevices" "False"
        Option      "AutoEnableDevices" "False"
        Option      "AutoAddGPU" "False"
EndSection

Section "Files"
        ModulePath "/usr/lib/xorg/modules"
        ModulePath "/usr/lib/x86_64-linux-gnu/xorg"
EndSection

Section "Module"
        Disable "fglrx"
EndSection

Section "Monitor"
        Identifier   "Monitor0"
        VendorName   "Unknown"
        ModelName    "Unknown"
        HorizSync    28.0 - 33.0
        VertRefresh  43.0 - 72.0
        Option      "DPMS" "false"
EndSection

Section "Device"
        Identifier  "GTX770"
        Driver      "nvidia"
        VendorName  "NVIDIA Corporation"
        BoardName   "GeForce GTX 770"
        BusID       "PCI:1:0:0"
EndSection

Section "Screen"
        Identifier "Screen0"
        Device     "GTX770"
        Monitor    "Monitor0"
        DefaultDepth     24
        Option      "AllowEmptyInitialConfiguration" "True"
        Option      "Coolbits" "28"
        SubSection "Display"
                Depth     24
                Modes    "640x480"
        EndSubSection
EndSection
```

**Comment by Spudz76** [comment]
This is also Ubuntu 14 (Trusty) but everything is the same with nvidia even on ancient Ubuntu's

I had this miner on the antique versions so I could use fglrx with a card that doesn't work well with any newer drivers.  Fun!

**Comment by AHBennett** [comment]
Thanks Spudz76, will check on this mess in the morning, see what I can do. For now, my internet is going F'n nuts, ping times through the roof to everything, and all my troubleshooting says it's my cable company. Which means I'm screwed until someone comes in tomorrow morning.

**Comment by AHBennett** [comment]
Seems I just don't know enough to get it running again. Guess I'll have to start from scratch later today, maybe xmr-stak will compile properly when I do it on a fresh install, but I doubt it.
