### ISSUE TITLE
TorSocks not supported anymore

### ISSUE THREAD

**Issue by asterismo** [fireice-uk/xmr-stak#1256]
Ubuntu 16.04 amd64
2x AMD RX460 running old XMR-STAK-AMD over Tor
Compiled new XMR-STAK and i got these error

[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)
[Mar 30 16:21:51] WARNING torsocks[5198]: [syscall] Unsupported syscall number 204. Denying the call (in tsocks_syscall() at syscall.c:465)

Is this normal?

**Comment by psychocrypt** [comment]
I have never used torSocks @fireice-uk do you ever used it?

**Comment by asterismo** [comment]
xmr-stak-amd used to run fine. i executed it as "torify ./xmr-stak-amd"

**Comment by asterismo** [comment]
I mean, pool connections are visible for anyone inspecting the network. Use of tor is a very valuable feature, and kinda mandatory for many of us.

**Comment by fireice-uk** [comment]
What OS are you running on? Try disabling the affinities.

**Comment by asterismo** [comment]
I cannot disable affinities since newer xmr-stak does not ships with config.txt and it does not run to do initial config. I'm running Ubuntu 16.04 amd64 and 2xRX460.

**Comment by Piraty** [comment]
`Version: xmr-stak 2.4.3 26a5d65f`
i'm trying to use torsocks too, like this: `torsocks xmr-stak`. It doesn't give any output whatsoever.
Running it from a `torsocks /bin/sh` shell gives again no output.
Any idea?
