### ISSUE TITLE
Socket Error - Unknown TLS error

### ISSUE THREAD

**Issue by lockpace** [fireice-uk/xmr-stak#1257]
When starting the miner after rebooting my laptop, the miner returns a socket error ("Unknown TLS error. Secure TLS may be unsupported, try setting tls_secure_algo to false.") 
My GPU: NVIDIA GeForce GT 540M
OS: Windows 10 (64 bit)

**Comment by psychocrypt** [comment]
please post all your config files.

**Comment by lockpace** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1865299/config.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1865301/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1865302/nvidia.txt)

**Comment by psychocrypt** [comment]
do you used the latest release? If not use the latest release 2.3. Please
do not reuse old configa for the new release. If you already use the new
release please post the file 'pools.txt'

**Comment by lockpace** [comment]
I still used the old version, it works now
