### ISSUE TITLE
JSON config parse error(offset 2027): Invalid value

### ISSUE THREAD

**Issue by JiKv** [fireice-uk/xmr-stak#1258]
Please provide as much as possible information to reproduce the issue.

# Basic information
  Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Nvidia 970 and 750

# Compile issues
Ubuntu 16.04

Previous version worked fine. Compiled new version removed configs and created pool.txt and with start getting 

JSON config parse error(offset 2027): Invalid value

Mining sumokoin at sumo.sumominer.com

**Comment by psychocrypt** [comment]
Please post the full miner output and all configs.

**Comment by JiKv** [comment]
"pool_list" :
[
        {"pool_address" : "sumo.sumominer.com:4444", "wallet_address" : "SumooXXXXyyyZZZZ", "rig_id" : "", "pool_password" : "x", "use_nicehash" : false , "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],
"currency" : "sumokoin",


bunka@blink:~/xmr-stak-current$ ./xmr-stak
[2018-03-31 10:04:00] : MEMORY ALLOC FAILED: mlock failed
[2018-03-31 10:04:00] : MEMORY ALLOC FAILED: mlock failed
[2018-03-31 10:04:00] : MEMORY ALLOC FAILED: mlock failed
[2018-03-31 10:04:00] : MEMORY ALLOC FAILED: mlock failed
[2018-03-31 10:04:00] : MEMORY ALLOC FAILED: mlock failed
-------------------------------------------------------------------
xmr-stak 2.3.0 a036cd8

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-03-31 10:04:00] : Mining coin: sumokoin
[2018-03-31 10:04:00] : JSON config parse error(offset 2027): Invalid value.

**Comment by marki555** [comment]
Offset 2027 seems to be too big for pool.txt file. I guess the error is in config.txt at byte 2027. You can for example run `vi config.txt` and then type `:go 2027` and it should point you to the correct line.

@psychocrypt It would be nice if the error message would contain the filename where error was detected.

**Comment by JiKv** [comment]
Hello,

I had problem in nvidia.txt config. I resolved it and it is running. I just wonder this new version is slower from old one. I ma running it at 750/1G and I had with previous version 245 hash rate and new one is only 205.

Old config was

  // gpu: GeForce GTX 750 architecture: 50
  //      memory: 935/979 MiB
  //      smx: 4
  { "index" : 1,
    "threads" : 32, "blocks" : 12,
    "bfactor" : 2, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

New one was threads 16 but I increased it to 18 but not able to go over 18 (old one was 32)
  // gpu: GeForce GTX 750 architecture: 50
  //      memory: 935/981 MiB
  //      smx: 4
  { "index" : 1,
    "threads" : 18, "blocks" : 12,
    "bfactor" : 2, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

**Comment by psychocrypt** [comment]
what is the error if you set threads to 32. Please restart your system and
than set threads to 32. Sometimes you have more free memory directly after
the restart.

**Comment by Sigura** [comment]
Got replay:

> Hello!
> 
> We are aware of the problem and we already found a solution. Everything will be fixed today evening or tomorrow early in the morning.
> 
> Thank you for understanding.
> 
> Kind regards,
> NiceHash Team

![screen shot 2018-04-06 at 15 05 13](https://user-images.githubusercontent.com/428500/38420328-04ee62a8-39ac-11e8-9245-a62381450710.png)

**Comment by JerichoJones** [comment]
Closing due to lack of response
