### ISSUE TITLE
Portable Linux instructions seem out of date

### ISSUE THREAD

**Issue by anthonydotnet** [fireice-uk/xmr-stak#1264]
The relevant files noted in this doc are not available. I guess Linux_deployment.md should be deleted?

https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md

**Comment by fireice-uk** [comment]
Yes, added it onto todo list. for 2.3.1

**Comment by BigslimVdub** [comment]
I cant get this to compile on ubuntu 14.4 EthOS. Seems to be missing some dependencies or something I am unaware of.

**Comment by anthonydotnet** [comment]
I needed to update apt get
