### ISSUE TITLE
XMR-STAK crashing after execution.

### ISSUE THREAD

**Issue by skiddi3** [fireice-uk/xmr-stak#1269]
XMR-STAK crashing after execution on Windows 10.
(Was working fine on Windows 7)

# Error:
```
[CUDA] Error gpu 0: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:365
```

# Basic information
  - CPU: Intel Core i7-4770K
  - GPU: Nvidia GeForce GTX770
CPU and GPU are not overclocked and not undervolted

# Issue with the execution
  - Using the precompiled version of the miner.
  ```
  Version: xmr-stak/2.3.0/a036cd81/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20
  ```

**Comment by psychocrypt** [comment]
please decrease the number of threads for the gpu

**Comment by skiddi3** [comment]
Thanks, it's not crashing now but h/s are down from 600 (Windows7) to only 300 (Windows 10) now.
