### ISSUE TITLE
Windows Large Page Support & Pre-GCN (older) AMD GPUs

### ISSUE THREAD

**Issue by BSuperfly** [fireice-uk/xmr-stak#1274]
I don't have an issue. Rather, I thought I'd provide dev some useful insights that I've learned that might help deal with issues pertaining to pre-GCN AMD hardware, as well as a tip regarding Large Page support in Windows. Since you have been super cool in developing this, and as I am using it- I thought I'd offer this as a means of contribution (beyond my 2%). :o)

Large Page Support in Windows 7/8/8.1: If the user doesn't have Professional / Ultimate version, they will not have access to Group Policy editor (gpedit.msc) to add the user account for SeLockMemoryPrivilege. However, there is a useful tool within the [Windows Server 2003 Resource Kit](https://www.microsoft.com/en-us/download/details.aspx?id=17657) called ntrights.exe. It's CLI, and allows the user to Large Page Support. IMHO, easier to use than gpedit.msc. 

Command: ntrights.exe -u {USER ACCOUNT} +r SeLockMemoryPrivilege

Also, for older AMD GPU's... it seems that many users are experiencing compatibility issues getting up and mining, due to the lack of a decent OpenCL driver by AMD on pre-GCN hardware. AMD began to remove OpenCL from their latest Catalyst drivers due to a difference in branching in Stream / APP 2.0. 

I wanted to recommend this [custom modded driver](https://forums.guru3d.com/threads/16-101-2901-1001.409002/), which delivers OpenCL 2.0 support (versus 1.2, which exists within the v14.11 driver). It's unsigned, so Windows 10 users would have to do some work to get it to install... but for Win 7/8/8.1 on pre-GCN, this is the best driver out there. I've tested them all and on multiple different GPUs. 

I simply wanted to share this feedback, in the hopes that it might help you to deal with some of the issues that I've seen posted. And, to thank you for your code!

Be well, 
Bryan

**Comment by Simaex** [comment]
Hi!
How much memory is detected for HD6xxx GPU when the driver is installed?
I try 16.xx drivers but they often fail to report GPU temperature after a while so I have to reboot too often.
Do you experience any problems with sensors?

**Comment by BSuperfly** [comment]
You'll simply want to try the driver to see if it works better for your config. 

It only reports 384 MB memory, which I realize is an issue... but the sensors work just fine... no issues at all. FYI, this driver uses the 15.201.3001 OpenCL Libraries.

**Comment by Simaex** [comment]
Thank you for the info. The 384M memory detection issue is the one that hugely impact performance. No workaround was found up by XMR-STAK team. For 2G cards it results in 70-80% performance penalty. For 1G it may be less but I'd suggest it will be 40-50% penalty also. Only 14.4 driver do not have the issue as for now. It's a pity but old Claymore miner is closed source so we do not know what workaround was found and can't reproduce it.

**Comment by BSuperfly** [comment]
Unfortunately, device support in the v14.40 drivers is lacking. For example, I have a HD 8490 part (based on the Caico Terrascale GPU) that is unsupported in the v14.4 drivers. It should hash at ~120-130 H/s, but the best I can get is around 50.

Several others have reported compatibility issues with that driver. I may try to hack together a 16.10 Catalyst driver with only the OpenCL library being pulled from 14.10.

**Comment by JerichoJones** [comment]
@BSuperfly ntrights is already in the FAQ.  
I don't think we can recommend an unsigned driver but thanks for the info should people choose to use it.

**Comment by Spudz76** [comment]
Trip report, fglrx 13 from ubuntu 14 normal repos, HD5570 lightly clocked 60H/s

So, yes you should be getting more out of better cards than that.
