### ISSUE TITLE
benchmark BLOCKVERSION

### ISSUE THREAD

**Issue by Raboo** [fireice-uk/xmr-stak#1275]
Hi
I want to run a benchmark for monero. But it requires a BOCKVERSION argument for option `--benchmark`.
How do I know what the current block version is?

**Comment by psychocrypt** [comment]
Current monero block version is 6 and after the hardfork 7

**Comment by Raboo** [comment]
Ok, thanks.
Perhaps a default setting of 6  or 7 would be suggested when executing without argument?

**Comment by psychocrypt** [comment]
Our command line parsing is so basic that we are not supporting default
parameter
This avoid that we introduce a new dependency.
The default would alse be not stable over different versions.

**Comment by Raboo** [comment]
ok

**Comment by kim0** [comment]
Folks, what about all the new changes to PoW for coins like sumo and others. What parameter is suitable to pass to be able to benchmark that ?

**Comment by psychocrypt** [comment]
use your normal configs the currency is selected in poos.txt and will be
used for the benchmark. Therefore you have the option to set the block
version to have the option to benchmark the effect of the fork

**Comment by kim0** [comment]
Thanks @psychocrypt .. so I can set the currency in pools.txt (and I suppose using `--currency` as well). But how do I know the correct value of the block version per coins? 

I'm generally interested in benchmarking the new (after fork) blockchain, is there some magical block version value that means after-fork ? Thanks

**Comment by Rakly3** [comment]
How to find out blockversion of a algo/ceurrency?
