### ISSUE TITLE
Is 2.3 ready for the new PoW, or do I need to upgrade to 2.4 BEFORE the fork?

### ISSUE THREAD

**Issue by pstimpel** [fireice-uk/xmr-stak#1280]
Sorry for the maybe dumb question, but found no information - just the commit

**Comment by psychocrypt** [comment]
It depends on the currency. 2.4.0 will add aeon and stellite and sumokoin
POW.
Currently we preparing the new release wait 2h. Than update.

**Comment by pstimpel** [comment]
Ok, guess I was too fast then :)
