### ISSUE TITLE
config failed, pools.txt is empty

### ISSUE THREAD

**Issue by cp542524698** [fireice-uk/xmr-stak#1287]
Please provide as much as possible information to reproduce the issue.

# Basic information
processor	: 23
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
stepping	: 2
microcode	: 0x15
cpu MHz		: 3059.022
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 10
cpu cores	: 6
apicid		: 21
initial apicid	: 21
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes

# Compile issues
[root@node175 xstack]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
  ```
 
  ```
  ```
[root@node175 build]# cmake .. -DXMR-STAK_COMPILE=generic
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: /root/chengpeng/xmr-stak-2.3.0/build
  ```

# Issue with the execution
[root@node175 bin]# ./xmr-stak 
Please enter:
- Do you want to use the HTTP interface?
Unlike the screen display, browser interface is not affected by the GPU lag.
If you don't want to use it, please enter 0, otherwise enter port number that the miner should listen on
0
Configuration stored in file 'config.txt'
Please enter:
- Please enter the currency that you want to mine: 
        - aeon
        - cryptonight
        - cryptonight_lite
        - edollar
        - electroneum
        - graft
        - intense
        - karbo
        - monero7
        - sumokoin

monero7
- Pool address: e.g. pool.usxmrpool.com:3333
pool.usxmrpool.com:3333
- Username (wallet address or pool login):
aaaa
- Password (mostly empty or x):
bbb
- Rig identifier for pool-side statistics (needs pool support). Can be empty:
0.^H^H
- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
N
- Do you want to use nicehash on this pool? (y/n)
y
- Do you want to use multiple pools? (y/n)
n
Pool configuration stored in file 'pools.txt'
[2018-04-03 16:24:44] : File is empty or too short - config.txt.
[root@node175 bin]# cat pools.txt 
[root@node175 bin]# cat pools.txt
        - karbo
[root@node175 bin]# cat config.txt 
[root@node175 bin]# cat config.txt 
[root@node175 bin]# 

pools.txt and config.txt are empty

**Comment by jcrypp** [comment]
I am having the same issue as @skear 

It also fails to generate a pools.txt file.
