### ISSUE TITLE
One user's problem

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak#129]
One guy on IRC managed to get 12 (!) gpus working with xmr-stak-amd, but they aren't detected by xmr-stak - some pastebins:

https://thepasteb.in/p/3lhJcDkOW4D18hN (needs sudo to actually see the gpus)

https://thepasteb.in/p/P1hrcj5mx7l3vcX (with a working config from stak-amd)

https://thepasteb.in/p/vghjcAxwqkKxxhx (I guided him into adding the line dumping number of devices and platform)

@psychocrypt -  can you think of anything?

**Comment by psychocrypt** [comment]
Is the user using the AMD blockchain driver?
If so is it the latest beta version.
There are a lot of issues with the blockchain driver in the past. The
issues are equal to this one. The OpenCL call `clGetDeviceIDs` is not
giving the correct number of devices or fails.

Is it possible to update to the newest or to an older driver?
