### ISSUE TITLE
2.4.1 - CL_INVALID_BUFFER_SIZE when calling clCreateBuffer

### ISSUE THREAD

**Issue by pershoot** [fireice-uk/xmr-stak#1290]
Hi.

Windows:
Receiving this (same configs from 2.3.0 and also let it re-create amd).
Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.

Also windows defender seems to not be happy with the .exe (i had to manually allow it).

Please look in to this.

Thank you.

**Comment by pershoot** [comment]
This is for Aeon.

**Comment by psychocrypt** [comment]
reduce the intensity until the error is gone.
You must add a exeption for windows defender, someone is using the open
source code for bad things, thats the reason for the detection

**Comment by pershoot** [comment]
I've tried multiple intensity reductions, thread/worksize reduction, etc.;  same issue.  Configs confirmed working on 2.3.0.

**Comment by psychocrypt** [comment]
Please fill out the issue template. Add your config files and a full log of the miner output. The output of `clinfo`, system hardware and OS.

**Comment by pershoot** [comment]
[2018-04-03 16:30:28] : Mining coin: aeon
[2018-04-03 16:30:28] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2018-04-03 16:30:28] : Found OpenCL GPU Baffin.
[2018-04-03 16:30:28] : AMD: GPU configuration stored in file 'amd.txt'
[2018-04-03 16:30:28] : Compiling code and initializing GPUs. This will take a while...
[2018-04-03 16:30:28] : Device 0 work size 8 / 32.
[2018-04-03 16:30:28] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2018-04-03 16:30:28] : WARNING: AMD device not found
[2018-04-03 16:30:28] : WARNING: backend AMD disabled.
[2018-04-03 16:30:28] : Starting 2x thread, affinity: 0.
[2018-04-03 16:30:28] : hwloc: memory pinned
[2018-04-03 16:30:28] : Starting 2x thread, affinity: 2.
[2018-04-03 16:30:28] : hwloc: memory pinned
[2018-04-03 16:30:28] : Starting 2x thread, affinity: 4.
[2018-04-03 16:30:28] : hwloc: memory pinned
[2018-04-03 16:30:28] : Starting 2x thread, affinity: 6.
[2018-04-03 16:30:28] : hwloc: memory pinned
[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1873245/amd.txt)

**Comment by psychocrypt** [comment]
could you please update youramd app sdk to 3.0
I tested aeon mining on my rx570 again and all works fine.

**Comment by pershoot** [comment]
I have re-installed AMD-APP-SDK-3.0 and have purged .openclcache; same issue.

**Comment by psychocrypt** [comment]
please run `xmr-stak -V`
Also please try ro reduce the intensity to 32

**Comment by danez** [comment]
I have the same issue here with my rig

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. **Intel Celeron G3930**
  - Type of the GPU (if you try to miner with the GPU). **6x AMD Radeon RX550**

# Issue with the execution
  - Do you compiled the miner by our own? Yes

Version: xmr-stak/2.4.1/737383a5/unknown/win/amd-cpu/aeon-cryptonight-monero/20
[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1873695/amd.txt)

**Comment by pershoot** [comment]
Version: xmr-stak/2.4.1/737383a5/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20

32 intensity (2 threads):
[2018-04-03 19:15:43] : Mining coin: aeon
[2018-04-03 19:15:43] : Compiling code and initializing GPUs. This will take a while...
[2018-04-03 19:15:43] : Device 0 work size 8 / 32.
[2018-04-03 19:15:44] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2018-04-03 19:15:44] : WARNING: AMD device not found
[2018-04-03 19:15:44] : WARNING: backend AMD disabled.
[2018-04-03 19:15:44] : Starting 2x thread, affinity: 0.
[2018-04-03 19:15:44] : hwloc: memory pinned
[2018-04-03 19:15:44] : Starting 2x thread, affinity: 2.
[2018-04-03 19:15:44] : hwloc: memory pinned
[2018-04-03 19:15:44] : Starting 2x thread, affinity: 4.
[2018-04-03 19:15:44] : hwloc: memory pinned
[2018-04-03 19:15:44] : Starting 2x thread, affinity: 6.
[2018-04-03 19:15:44] : hwloc: memory pinned

**Comment by Spudz76** [comment]
I have gotten this error when forgetting to set the environment var `GPU_FORCE_64BIT_PTR=1`

**Comment by danez** [comment]
I tired doing `SET GPU_FORCE_64BIT_PTR 1` on windows before launching the miner, but it did not change anything.

**Comment by danez** [comment]
I tried all combinations of set and setx but it didn't change anything, it seems that 2.4 is just broken with some cards.

**Comment by danez** [comment]
Okay seems I figured it out the algo was renamed from `aeon` to `aeon7`. So the config from 2.3 is NOT compatible.
After changing it in `pools.txt` it works.

Here is the diff that a pools.txt has when generated with aeon from 2.3 and 2.4
```diff
...
 /*
  * Currency to mine. Supported values:
  *
- *    aeon
+ *    aeon7 (use this for Aeon's new PoW)
  *    cryptonight (try this if your coin is not listed)
  *    cryptonight_lite
  *    edollar
  *    electroneum
  *    graft
  *    intense
  *    karbo
  *    monero7 (use this for Monero's new PoW)
  *    sumokoin
  *
  */
 
-"currency" : "aeon",
+"currency" : "aeon7",
 
...
```

I guess xmr-stak should warn about this similar to monero vs monero7 or reject `aeon`.

**Comment by postalman** [comment]
Same problem with Vega64 and CN Heavy algo. I asume heavy algo means twice less hashrate? Cause it dont work with old intensity.

**Comment by BKdilse** [comment]
I saw this today, and I cut my intensity by half to get it working, for sumokoin.

**Comment by postalman** [comment]
I cut it too for Vega, interesting facts RX480 with two threads got same hashrate as was but Vega not, blockchain drivers dont fix it.

**Comment by randelsr** [comment]
I know that Sumokoin team has acknowledged that GPUs (in general) are getting 30% less hashrate on Sumokoin. 

I'm getting the same issues with mining Sumo on xmr-stak 2.4.2, CL_INVALID_BUFFER_SIZE. I have 8 GB of physical RAM with over 80GB of virtual, with 8 Vega 64s running. Lowering the intensity does resolve this issue, but obviously drastically reduces the hashrate. I wonder if lowering my intensity by ~30% will find a sweet spot.

To add constructive feedback to this thread, is anybody with "unlimited" memory running into these issues? I'm limited by memory & HD space for testing

**Comment by 1337c0d3d00d** [comment]
I get this error too when switching to 'sumokoin' on my VEGA56/64 cards which have 8GB of DDR.   However when I switch to the Frontier edition cards which have 16GB it gets past this error.  At that point there is another issue as the hash rates are all over the place and much lower than usual.

**Comment by psychocrypt** [comment]
remive your amd.txt and let the miner create a config. Sumokoin uses now
4MB scratchpad therefore it is in the most cases not possible to use the
old intensity.

**Comment by vegaman64** [comment]
I see others mining sumo with higher intensity however max I can get is 944 with single or 2 threads getting CL_INVALID_BUFFER_SIZE with higher settings. Is it realy max we can get from Vega cards ~ 1400hs?

**Comment by vegaman64** [comment]
I have 8x Vega 64 rig with poor celeron and 4 gb of ram (80Gb virtual memory). Maybe RAM or CPU is the case?

**Comment by TurkishPower92** [comment]
yeah admin why giving 944 for sumo i before mining 2010 h :S

**Comment by nuigru** [comment]
Why with Vega FE xmr sees only // gpu: gfx900 memory:3920 and not 16GB ?
