### ISSUE TITLE
Can't run as Windows scheduled task 

### ISSUE THREAD

**Issue by rwebb0418** [fireice-uk/xmr-stak#1292]
So I have a few computers that I'm attempting to run the precompiled Windows release XMR-Stak 2.2 and 2.4.1 on as a scheduled task.  The program will run but the miner does not connect to a pool.  

- When running the program as my user (as in I can see the output window) the miner connects to the pool without issue.  

- Since I am running it as a scheduled task I can't actually see any of the output screen to determine an error. 

- Setting an output file in config.txt doesn't help as no log file is created.

- Program runs about 60% CPU utilization when run as user, 0% utilization when run as a task

- The previous version I am running on the systems (2.0) works just fine.  

Basic information one of 5 miners... others are similar
  - i7-4600U
  - AMD Radeon HD8750M
  - Windows 10

**Comment by lzc-China** [comment]
Right Attribute Settings Run as Administrator

**Comment by AMDfreak** [comment]
In the security options for the scheduled task make sure "Run with highest privileges" is checked.

**Comment by rwebb0418** [comment]
That did it.  The 2.0 version ran fine without the "start in" field being filled in.  Thanks!
