### ISSUE TITLE
Move Currency/algo to Pool definition, define GPU settings by algo

### ISSUE THREAD

**Issue by joshuajrrc** [fireice-uk/xmr-stak#1293]
- in pool.txt, define pool and pool algo
- in amd.txt, define mutiple sections, one for each algorithm.
- would the same idea apply to the nvidia.txt?

Is it possible to detect algo by block header?

**Comment by marki555** [comment]
Or maybe just add commandline option similar to `--cpu`. Until then you can either symlink the config files or just have a script to copy them from `amd_coin1.txt` to `amd.txt`...

**Comment by AMDfreak** [comment]
This already exists.  For example create amdSUMO.txt for your Sumokoin settings and you can use the option --amd amdSUMO.txt.

**Comment by joshuajrrc** [comment]
Maybe it would be more like this
- define pool and pool algo
- in amd.txt, define mutiple sections, one for each algorithm.
- would the same idea apply to the nvidia.txt?

Seems like it would be handy to autodetect the algo from the pool if supported.  Is that in the block header info generally?

**Comment by Spudz76** [comment]
I agree, because the coin algo should be inside the pool entries within the pools.txt as well, so that you can have every possibility defined for runtime (and fail over to other coins).

**Comment by psychocrypt** [comment]
Why do you want to switch between coins? If you think about mine the most
provitable coin than this will also not work if you can add the currency
per coin. Why do you not start a new instance of the miner if like to
switch the currency.

**Comment by marki555** [comment]
@AMDfreak Good to know. `xmr-stak -h` 2.4.1 displays only the `--cpu` option, not the `--amd`.

**Comment by joshuajrrc** [comment]
You've built the architecture to support fail over to another pool in case of pool failure, which has generally worked good while there were only two main algos - You either mined the xmr variant or aeon variant.  Most are mining the xmr variant from what I can tell.  Now, you've added support for a number of new variations of the forked algorithms, which is also good, but can lead to a desire to fail to a pool and coin with a different algo.  Some of these algorithms require different GPU configs. sumo v3 vs. monero v7 for instance

**Comment by travis1234** [comment]
Auto-detect for currency would be awesome, failing that moving currency to the pool_list would be next best option.

**Comment by psychocrypt** [comment]
Autodetection is not possible because the solutions are ambiguous.
Also it can be a problem for the miner if he think he is mining monero but
the auto detection is switching to useless cryptonight coin. Also a message
in the logs will not help, because the most users not look to the logs.
I think the right way is to show that shares are rejected and than the user
wondering and check his configuration.

**Comment by psychocrypt** [comment]
I am not sure because somw coins are not compatible to each other. This
mean you need a different config.
Most users already saied that our configuration is to hard. If the user
needs now also a backend (cpu,amd,nvidia) cfg per pool it will be much more
complicated.

**Comment by travis1234** [comment]
No problem, it should be less of an issue in a few months when more coins switch to v7.
In the mean time, is it possible to have an option to select pool config via command-line arguments?

e.g: --pool monero7.txt OR --pool cryptonight.txt etc..? 

Then at least I can have separate batch files to start the problem instead of a whole new instance.

**Comment by JerichoJones** [comment]
xmr-stak --help  
  
There is no "OR" if that is what you are asking. I don't think it is worth adding that feature for a few months use. Maybe the devs will disagree (I doubt it).

**Comment by travis1234** [comment]
oh no, I just meant a single pool via cmd line switch

**Comment by JerichoJones** [comment]
![image](https://user-images.githubusercontent.com/13205729/38633007-5a43e2b2-3d8c-11e8-949f-16e19a852a06.png)

**Comment by travis1234** [comment]
awesome --poolconf thanks!
