### ISSUE TITLE
Nvidia Invalid Result

### ISSUE THREAD

**Issue by ThatGuy867** [fireice-uk/xmr-stak#1295]
Ran the setup, disabled cpu mining, started mining on the test network have got all NVIDIA Invalid Result GPU ID 0 errors for every result. When mining Sumokoin

# Basic information
  - Type of the CPU. R7 1700
  - Type of the GPU (if you try to miner with the GPU). Nvidia GTX 1070

# Compile issues
  - Which OS do you use? Windows 10

# Issue with the execution
  - Do you compiled the miner by our own? No

# Stability issue
  - Is the CPU or GPU overclocked? CPU is, GPU has been tested both stock and overclocked, same result
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by psychocrypt** [comment]
lease post the configs pool.txt nvidia.txt and the log until the first
rejected shares.
Which currency

**Comment by felipe-vvoosh** [comment]
It is rejecting all shares, at least for me...
The nvidia file was created by xmr-stak, automatically...

**Comment by ThatGuy867** [comment]
Nvidia.txt

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 * If you do not wish to mine with your nVidia GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" :
[
  { "index" : 0,
    "threads" : 14, "blocks" : 45,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by ThatGuy867** [comment]
/*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * rig_id          - Rig identifier for pool-side statistics (needs pool support).
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool 
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */
 
"pool_list" :
[
	{"pool_address" : "92.53.67.18:3333", "wallet_address" : "Sutoe6DuhQJVR2RWKDWtC3YWGaTVeemBZVUYizBirBzK6ecaock4LNyZD6QUYy9Fwvb5MSD6VLFGiHijRhU4AdbzCc2j355X8Yv", "rig_id" : "", "pool_password" : "GPU:Robertspag@gmail.com", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    cryptonight (try this if your coin is not listed)
 *    cryptonight_lite
 *    edollar
 *    electroneum
 *    graft
 *    intense
 *    karbo
 *    monero7 (use this for Monero's new PoW)
 *    sumokoin
 *
 */

"currency" : "sumokoin",

**Comment by ThatGuy867** [comment]
/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 * If you do not wish to mine with your nVidia GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" :
[
  { "index" : 0,
    "threads" : 14, "blocks" : 45,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by ThatGuy867** [comment]
-------------------------------------------------------------------
xmr-stak 2.4.1 737383a5

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-04-04 14:29:01] : Mining coin: sumokoin
[2018-04-04 14:29:01] : Starting NVIDIA GPU thread 0, no affinity.
[2018-04-04 14:29:04] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-04-04 14:29:04] : WARNING: backend AMD disabled.
[2018-04-04 14:29:04] : WARNING: backend CPU disabled.
[2018-04-04 14:29:04] : Fast-connecting to 92.53.67.18:3333 pool ...
[2018-04-04 14:29:04] : Pool 92.53.67.18:3333 connected. Logging in...
[2018-04-04 14:29:04] : Difficulty changed. Now: 1000.
[2018-04-04 14:29:04] : Pool logged in.
RESULT REPORT
Difficulty       : 1000
Good results     : 0 / 2 (0.0 %)
Pool-side hashes : 0

Top 10 best results found:
|  0 |                0 |  1 |                0 |
|  2 |                0 |  3 |                0 |
|  4 |                0 |  5 |                0 |
|  6 |                0 |  7 |                0 |
|  8 |                0 |  9 |                0 |

Error details:
| Count | Error text                       | Last seen           |
|     2 | NVIDIA Invalid Result GPU ID 0   | 2018-04-04 14:29:08 |
[2018-04-04 14:29:12] : Difficulty changed. Now: 5000.
[2018-04-04 14:29:12] : New block detected.
RESULT REPORT
Difficulty       : 5000
Good results     : 0 / 4 (0.0 %)
Pool-side hashes : 0

Top 10 best results found:
|  0 |                0 |  1 |                0 |
|  2 |                0 |  3 |                0 |
|  4 |                0 |  5 |                0 |
|  6 |                0 |  7 |                0 |
|  8 |                0 |  9 |                0 |

Error details:
| Count | Error text                       | Last seen           |
|     4 | NVIDIA Invalid Result GPU ID 0   | 2018-04-04 14:29:12 |

**Comment by psychocrypt** [comment]
the config files are different on each system please provide all information

**Comment by ThatGuy867** [comment]
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1877102/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1877103/pools.txt)
[log.txt](https://github.com/fireice-uk/xmr-stak/files/1877104/log.txt)

**Comment by psychocrypt** [comment]
Which GPU do you used and which OS. I tested the pool and everything work.

**Comment by ThatGuy867** [comment]
GTX 1070 and Windows 10, Using the current pool, with the mainnet blockchain it works fine, but when running the testnet everything is invalid

**Comment by ThatGuy867** [comment]
Redownloaded and did a fresh config, the CPU results are valid, but still getting the Nvidia errors.

**Comment by felipe-vvoosh** [comment]
This is also happening with 1080 TI...

**Comment by psychocrypt** [comment]
It is a bug with bfactor, the bug is always visible if bfactor is not zero. I am currently searching the reason.

**Comment by ThatGuy867** [comment]
Ah, glad you were able to find the root cause, Im going to test it at 0 for now to see how it runs.

**Comment by felipe-vvoosh** [comment]
0 doesn’t work.

**Comment by silentj408** [comment]
having same issue on my nvidia cards mining haven, bfactor 0 just crashes

**Comment by AnonJunkie** [comment]
same issue mining haven on lucky pool all invalid from nvidia.

**Comment by psychocrypt** [comment]
sry forgot to say bfactor zero is not working in windows. Switch to linux
for bfactor 0 ;-)

I am working on a bugfix

**Comment by psychocrypt** [comment]
fixed with #1300
