### ISSUE TITLE
[Feature Request] Option to compile into a single file (without having all the dll's)

### ISSUE THREAD

**Issue by ThaumicMekanism** [fireice-uk/xmr-stak#1296]
I could not tell if there was a way in which you could have xmr-stak compile so that it does not have any dependencies on the cuda or opencl files (as in they are statically linked instead of dynamically linked). I saw that you can do static linking for the other two but not for the backend files. I was wondering if it was possible so that it would be easier to just move a single file around instead of worrying about multiple dll files. I understand having dll's can make it so it can be easier to update but as it is, it seems this project has all of the files get updated so it seems like it would make no difference to have the ability to compile it into one file.

I'm sorry if this is a stupid question, just not as familiar with CMake to make this possible. And also thanks for all the support of this program! :D

P.S. If this is already implemented, could you tell me how since I could not find it in the doc's

**Comment by psychocrypt** [comment]
The usage of dlls is the only way to have all backends (cuda,cpu and amd)
within one miner without issues if e.g opencl or cuda is not available.
Please describe the workflow why you need one file instead 3.

**Comment by messi06** [comment]
+1 on the same idea, 
even though compiling all necessary DLL files into the EXE will make the exe file size bigger , in my opinion it's worth it , a standalone file like xmrig is way more convenient and cleaner..
+ the DLL files might not get detected by the antivirus and get deleted automatically....
I wish if xmr-stak can be a 1 standalone exe package yet unified .....
anyhow respect man ! you have done well...
