### ISSUE TITLE
monero7 w/ (Dev branch) - nicehash, poor results

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1298]
I set 2 machines run for 8+ hours last night on monero7 w/ Nicehash.  The "workaround" code performed just as expected, reporting to my log files and maintained the connection.  I suffered a significant loss in hash performance during this time, in comparison to running with Nicehash with standard cryptonight.

I switch my larger machine back to cryptonight for production reasons.  I have my smaller machine still running with monero7 just for analysis purposes.  The GOOD part of the test, is seeing the monero7 difficulty switched to 100001.  Historically that pool w/ cryptonight forces difficulty 200007 - which is too high for machines with less than 1,400h/s rate.  

There appears to be no issues with monero7 on an actual monero/xmr pool.  Logs are not reporting errors on both my xmrig proxy connection, and 1kh/s rig.  I can not confirm or deny the consistancy of production on xmr/monero pools cryptonight -vs-monero7 since I have been shifting rigs around and can not compare specific baseline results.

Just a f-y-i.

**Comment by Simaex** [comment]
Just for comparison I fired my rig to NH v7 pool and do not notice any decrease in hash rate compared to NH v6 pool. But I am receiving massive "share above target" errors, so long only one (!!!) good share against 60 found. BTW difficilty is 200 007. Are you getting good shares just now?

**Comment by DrStein99** [comment]
I am getting the same hash rate reported by xmr-stak.  I can't say with Nicehash, since their web reporting is so inconsistant.  I can say for CERTAIN the PROFIT was affected.

It is the "share above target" or in my case (nicehash work-around) that affects the profit.  Not being paid for these errored submits - which drags down the profit over the course of an hour, and flatlines when it becomes every 3-5 submits.  They do not tally up in xmr-stak web reporting.  Errors do show up in the log files.  I can clearly see the errored blocks in monero7 on the Nicehash graph.

**Comment by Sigura** [comment]
Looks like the same problem on 2.4.1, Win10x64

Works few minutes, then all result rejected by the pool.

nicehash picture:

<img width="221" alt="screen shot 2018-04-05 at 00 53 50" src="https://user-images.githubusercontent.com/428500/38336854-e94c7210-386b-11e8-903a-14149bbf14d4.png">

R:

```
Error details:
| Count | Error text                       | Last seen           |
|     4 | Job not found.                   | 2018-04-05 00:49:36 |
|    18 | Share above target.              | 2018-04-05 00:49:41 |
[2018-04-05 00:50:29] : Result rejected by the pool.
[2018-04-05 00:50:30] : New block detected.
[2018-04-05 00:50:34] : Result rejected by the pool.
```

do not see any errors

**Comment by joshgrob** [comment]
Yes I am seeing similar errors to @Sigura and @DrStein99.  It's definitely weird since it will work fine for an hour or so.  Also, when I have 2 pools setup (main NH and backup coin pool), "Network Error" results pile up, and constant pool switching occurs.  The progression is:
1.  Main pool sockets out
2. Backup successfully logs in
3. miner submits share
4. Pool closes connection
5. Network Error result increase by 1

The process repeats as the main pool attempts to login again.

**Comment by psychocrypt** [comment]
please post a full log to pastbin.com and link it here

**Comment by Sigura** [comment]
Got replay:

> Hello!
> 
> We are aware of the problem and we already found a solution. Everything will be fixed today evening or tomorrow early in the morning.
> 
> Thank you for understanding.
> 
> Kind regards,
> NiceHash Team

![screen shot 2018-04-06 at 15 05 13](https://user-images.githubusercontent.com/428500/38420328-04ee62a8-39ac-11e8-9245-a62381450710.png)

**Comment by psychocrypt** [comment]
Do I said to you you should not use nicehash? If not: **Don't use nicehash**

**Comment by madscientist159** [comment]
Seeing exactly this again....probably need to reopen this
