### ISSUE TITLE
pool reject shares.

### ISSUE THREAD

**Issue by newskytt** [fireice-uk/xmr-stak#1302]
i use xmr stak 2.4.1 mining at communitypool.stellite.cash for XTL coin ,but most share are reject by the pool:Valid Shares  85,839  Invalid Shares  16,800.pools.txt is changed: "currency" : "stellite",  so many reject ,and the pool bannd my ip . i cant mine ,please help me! Thanks.
# Basic information
  - Type of the CPU.
  -e5 2660 v2 *2

# Compile issues
  - Which OS do you use?
  ```windows 7 
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by newskytt** [comment]
and my OS is  windows7

**Comment by psychocrypt** [comment]
post pools.txt and cpu.txt andbest the log. also please fill out the
template. the long version is not included

**Comment by YuriiTonkov** [comment]
Which coin do you configure in the settings? Do u keep "monero7" like before the fork?

**Comment by JerichoJones** [comment]
@YuriiTonkov monero7

**Comment by JerichoJones** [comment]
Closing due to lack of response.
