### ISSUE TITLE
NVIDIA Invalid Result GPU ID 1

### ISSUE THREAD

**Issue by sergneo** [fireice-uk/xmr-stak#1303]
6xNvidia 1060 3Gb
xmr-stak 2.4.1
Windows 7 x64
Sumokoin

Error text
--

NVIDIA Invalid Result GPU ID 1
2 | 2018-04-05 02:58:40
NVIDIA Invalid Result GPU ID 5
5 | 2018-04-05 02:59:02
NVIDIA Invalid Result GPU ID 0
2 | 2018-04-05 02:57:55
NVIDIA Invalid Result GPU ID 3
3 | 2018-04-05 02:58:47
NVIDIA Invalid Result GPU ID 4
1 | 2018-04-05 02:57:40
NVIDIA Invalid Result GPU ID 2
1 | 2018-04-05 02:58:54

**Comment by psychocrypt** [comment]
run `xmr-stak -V` which currency. Sumo was broken in 2.4.1 again for nvidia
and is fixed in 2.4.2
