### ISSUE TITLE
Miner only reports even number IDs.

### ISSUE THREAD

**Issue by myvidster** [fireice-uk/xmr-stak#1304]
# Basic information
  - 1950X Treadripper
  - Ti1080 and Ti1070
  - Ubuntu 17
  
Miner only reports even number IDs.

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   75.1 |   75.1 |   74.4 |  1 |   75.4 |   75.4 |   74.7 |
|  2 |   75.4 |   75.4 |   74.6 |  3 |   75.4 |   75.4 |   74.6 |
|  4 |   75.4 |   75.5 |   75.2 |  5 |   75.5 |   75.6 |   75.3 |
|  6 |   75.3 |   75.4 |   75.2 |  7 |   75.4 |   75.5 |   75.2 |
|  8 |   75.7 |   75.6 |   75.5 |  9 |   75.7 |   75.6 |   75.5 |
| 10 |   75.7 |   75.6 |   75.5 | 11 |   75.7 |   75.6 |   75.5 |
| 12 |   70.6 |   70.7 |   71.6 | 13 |   70.5 |   70.6 |   71.6 |
| 14 |   70.6 |   70.7 |   71.6 | 15 |   69.5 |   69.6 |   70.6 |
Totals (CPU):  1186.9 1187.1 1186.6 H/s
-----------------------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  562.8 |  562.8 |  562.8 |  1 |  669.5 |  669.6 |  669.3 |
|  2 |  669.8 |  669.8 |  669.7 |  3 |  669.7 |  669.7 |  669.6 |
|  4 |  562.6 |  562.6 |  562.5 |  5 |  562.9 |  562.9 |  562.7 |
Totals (NVIDIA):  3697.3 3697.4 3696.5 H/s

**Comment by Spudz76** [comment]
```
0                        1
2                        3
4                        5
```

... do you see it now?

**Comment by myvidster** [comment]
Sneaky :), thanks!
