### ISSUE TITLE
[Feature Request] When exit xmr-stak, release the GPUs smoothly

### ISSUE THREAD

**Issue by Moskitopr** [fireice-uk/xmr-stak#1306]
Sometimes when I close xmr-stak I have problem with some GPU. Problem I solved by turning off my internet and then closing xmr-stak. It would be interesting some command to smoothly release the GPUs so that we can close xmr-stak without problems.

**Comment by Spudz76** [comment]
Works fine here / Linux?  Windows?

**Comment by psychocrypt** [comment]
I have a branch where I start3d to implement a clean shutdown but currently
I have no time ro finish it :-(

**Comment by Moskitopr** [comment]
Windows.
No problem psychocrypt. 
I'll wait for this feature ;)

**Comment by Moskitopr** [comment]
BAT to solve the problem :)

@echo on
netsh interface set interface "Ethernet" DISABLED
timeout /t 10
TASKKILL /IM xmr-stak.exe
timeout /t 20
netsh interface set interface "Ethernet" ENABLED
