### ISSUE TITLE
No change log for 2.4.2 - What changed?

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [fireice-uk/xmr-stak#1307]
No change log for 2.4.2

https://github.com/fireice-uk/xmr-stak/releases

last entry was for 2.4.1

**Comment by Spudz76** [comment]
pull #1301 is basically the changelog

Fixed problem(s) with sumocoin algo only (if you don't use sumocoin / it is no different)

**Comment by psychocrypt** [comment]
The change log in the release is always to the previous version.
