### ISSUE TITLE
Is v2.3.0-a036cd8 ready for the NEW Monero POW?

### ISSUE THREAD

**Issue by the-babaji** [fireice-uk/xmr-stak#1308]
Any reason to get the latest version before the change? Anything big I missed since v2.3.0-a036cd8 ?
I looked at the changelog, but i'm not sure. Got quite a few rigs to maintain, so if it ain't urgent, i'd rather wait a while.

Thx

**Comment by Spudz76** [comment]
If your version has a pools.txt and the 'monero7' algo available therein...

Then it's ready.

If all it knows about is config.txt and 'monero' or 'aeon' then it's the old POW.  AKA generic 'cryptonight' in the new algos.

**Comment by psychocrypt** [comment]
The release 2.3.0 is ready for monero v7. Only if you ise sumokoin or aeon
you must update.

**Comment by the-babaji** [comment]
Thanks, that's what i needed to know.
