### ISSUE TITLE
Configurator adds all CPUs in 2.4.X

### ISSUE THREAD

**Issue by oHu812** [fireice-uk/xmr-stak#1309]
On all my servers with various CPUs, all intel, the configurator builds the CPU.txt with all CPUs in 2.4.X. On an I7 it puts them even then odd. On an old XEON it puts them in order 0-8. I was previously at 2.3 and it would always add only the even cores before startup. Again this is happening on all 4 of my servers.

**Comment by psychocrypt** [comment]
Which OS do you use. Do you compiled the miner by your own? Do you have the
dependency hwloc? Please do not ignore the issue template we have not the
time to ask each user for more information.

**Comment by cporichie** [comment]
Sorry for skipping the template. The boxes are windows 10, 7, and server 16. I didn't compile these myself, but when I do the same thing happens. hwloc is active on all.  @Spudz76 I run the autoconfig after updates to see if the devs added any new tweaks than what I know to use. Just reporting here that I found a change in how things operated, probably low priority. It makes me curious now though if I am picking the wrong cores (not hardware but hyper) on my xeon...

**Comment by cporichie** [comment]
Here is some more info on the config that is built. XEON E5-2680. Fresh install of windows 10 pro.  Is this what is intended?

    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 13 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 15 },

**Comment by JerichoJones** [comment]
Still no template...

**Comment by oHu812** [comment]
Wow tough crowd. You need the template headers too? Maybe the top of the template should say don't remove the template. @JerichoJones here it is. Hope it's everything you ever wanted it to be....

# Basic information
  - Type of the CPU. **XEON E5-2680**
  - Type of the GPU (if you try to miner with the GPU). **NA**

# Compile issues
  - Which OS do you use? **Windows 10 pro**
  ```
  add **all** commands you used and the **full** compile output here  **-NA**
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here **NA**
  ```

# Issue with the execution
  - Do you compiled the miner by our own? **NO**
  ```
  run `./xmr-stak --version-long` and add the output here
**Version: xmr-stak/2.4.2/e10e8e67/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20**

  # AMD OpenCl issue
  ```
  run `clinfo` and add the output here **NA**
  ```

# Stability issue
  - Is the CPU or GPU overclocked? **NO**
  - Is the Main memory of the CPU or GPU undervolted? **NO**
