### ISSUE TITLE
Windows Compile error VS 15.6.4

### ISSUE THREAD

**Issue by joaquinabenza** [fireice-uk/xmr-stak#1310]
Error when i try to build xmr-stak for windows

# Basic information
c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/host_config.h(135): fatal error C1189: #error:  --
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [C:\Git\xmrstak
\build\xmrstak_cuda_backend.vcxproj]

# Compile issues
windows 10 x64
visual studio enterprise 2017 version 15.6.4
Commands:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11
"C:\Program Files (x86)\Microsoft Visual Studio\2017\enterprise\Common7\Tools\VsMSBuildCmd.bat"
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake --build . --config Release --target install

C:\Git\xmrstak\build>cmake --build . --config Release --target install
``
`
Microsoft (R) Build Engine versión 15.6.82.30579 para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Compilación iniciada a las 05/04/2018 16:09:37.
Proyecto "C:\Git\xmrstak\build\install.vcxproj" en nodo 1 (destinos predeterminados).
El proyecto "C:\Git\xmrstak\build\install.vcxproj" (1) está compilando "C:\Git\xmrstak\build\ZERO_CHECK.vcxproj" (2) en
 el nodo 1 (destinos predeterminados).
InitializeBuildStatus:
  Se creará "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
CustomBuild:
  Todas las salidas están actualizadas.
FinalizeBuildStatus:
  Se eliminará el archivo "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Aplicando tarea Touch a "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Compilación del proyecto terminada "C:\Git\xmrstak\build\ZERO_CHECK.vcxproj" (destinos predeterminados).

El proyecto "C:\Git\xmrstak\build\install.vcxproj" (1) está compilando "C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (3) en
el nodo 1 (destinos predeterminados).
El proyecto "C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (3) está compilando "C:\Git\xmrstak\build\xmr-stak.vcxproj" (4) en
 el nodo 1 (destinos predeterminados).
El proyecto "C:\Git\xmrstak\build\xmr-stak.vcxproj" (4) está compilando "C:\Git\xmrstak\build\xmr-stak-backend.vcxproj"
 (5) en el nodo 1 (destinos predeterminados).
El proyecto "C:\Git\xmrstak\build\xmr-stak-backend.vcxproj" (5) está compilando "C:\Git\xmrstak\build\xmr-stak-c.vcxpro
j" (6) en el nodo 1 (destinos predeterminados).
InitializeBuildStatus:
  Se creará "xmr-stak-c.dir\Release\xmr-stak-c.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
CustomBuild:
  Todas las salidas están actualizadas.
ClCompile:
  Todas las salidas están actualizadas.
Lib:
  Todas las salidas están actualizadas.
  xmr-stak-c.vcxproj -> C:\Git\xmrstak\build\bin\Release\xmr-stak-c.lib
FinalizeBuildStatus:
  Se eliminará el archivo "xmr-stak-c.dir\Release\xmr-stak-c.tlog\unsuccessfulbuild".
  Aplicando tarea Touch a "xmr-stak-c.dir\Release\xmr-stak-c.tlog\xmr-stak-c.lastbuildstate".
Compilación del proyecto terminada "C:\Git\xmrstak\build\xmr-stak-c.vcxproj" (destinos predeterminados).

InitializeBuildStatus:
  Se creará "xmr-stak-backend.dir\Release\xmr-stak-backend.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
CustomBuild:
  Todas las salidas están actualizadas.
ClCompile:
  Todas las salidas están actualizadas.
  Todas las salidas están actualizadas.
  Todas las salidas están actualizadas.
Lib:
  Todas las salidas están actualizadas.
  xmr-stak-backend.vcxproj -> C:\Git\xmrstak\build\bin\Release\xmr-stak-backend.lib
FinalizeBuildStatus:
  Se eliminará el archivo "xmr-stak-backend.dir\Release\xmr-stak-backend.tlog\unsuccessfulbuild".
  Aplicando tarea Touch a "xmr-stak-backend.dir\Release\xmr-stak-backend.tlog\xmr-stak-backend.lastbuildstate".
Compilación del proyecto terminada "C:\Git\xmrstak\build\xmr-stak-backend.vcxproj" (destinos predeterminados).

InitializeBuildStatus:
  Se creará "xmr-stak.dir\Release\xmr-stak.tlog\unsuccessfulbuild" porque se especificó "AlwaysCreate".
CustomBuild:
  Todas las salidas están actualizadas.
ClCompile:
  Todas las salidas están actualizadas.
Link:
  Todas las salidas están actualizadas.
  xmr-stak.vcxproj -> C:\Git\xmrstak\build\bin\Release\xmr-stak.exe
FinalizeBuildStatus:
  Se eliminará el archivo "xmr-stak.dir\Release\xmr-stak.tlog\unsuccessfulbuild".
  Aplicando tarea Touch a "xmr-stak.dir\Release\xmr-stak.tlog\xmr-stak.lastbuildstate".
Compilación del proyecto terminada "C:\Git\xmrstak\build\xmr-stak.vcxproj" (destinos predeterminados).

El proyecto "C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (3) está compilando "C:\Git\xmrstak\build\xmrstak_cuda_backend.vcx
proj" (7) en el nodo 1 (destinos predeterminados).
InitializeBuildStatus:
  Aplicando tarea Touch a "xmrstak_cuda_backend.dir\Release\xmrstak_.87068CFF.tlog\unsuccessfulbuild".
CustomBuild:
  Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cu
  da_backend_generated_cuda_core.cu.obj
  cuda_core.cu
c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/host_config.h(135): fatal error C1189: #error:  --
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [C:\Git\xmrstak
\build\xmrstak_cuda_backend.vcxproj]
CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignor
ed. [C:\Git\xmrstak\build\xmrstak_cuda_backend.vcxproj]
  CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Git/xmrstak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cuda_back
  end_generated_cuda_core.cu.obj

Compilación del proyecto terminada "C:\Git\xmrstak\build\xmrstak_cuda_backend.vcxproj" (destinos predeterminados) -- ER
ROR.

El proyecto "C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (3) está compilando "C:\Git\xmrstak\build\xmrstak_opencl_backend.v
cxproj" (8) en el nodo 1 (destinos predeterminados).
InitializeBuildStatus:
  Se creará "xmrstak_opencl_backend.dir\Release\xmrstak_.2A951498.tlog\unsuccessfulbuild" porque se especificó "AlwaysC
  reate".
CustomBuild:
  Todas las salidas están actualizadas.
ClCompile:
  Todas las salidas están actualizadas.
Link:
  Todas las salidas están actualizadas.
  xmrstak_opencl_backend.vcxproj -> C:\Git\xmrstak\build\bin\Release\xmrstak_opencl_backend.dll
FinalizeBuildStatus:
  Se eliminará el archivo "xmrstak_opencl_backend.dir\Release\xmrstak_.2A951498.tlog\unsuccessfulbuild".
  Aplicando tarea Touch a "xmrstak_opencl_backend.dir\Release\xmrstak_.2A951498.tlog\xmrstak_opencl_backend.lastbuildst
  ate".
Compilación del proyecto terminada "C:\Git\xmrstak\build\xmrstak_opencl_backend.vcxproj" (destinos predeterminados).

Compilación del proyecto terminada "C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (destinos predeterminados) -- ERROR.

Compilación del proyecto terminada "C:\Git\xmrstak\build\install.vcxproj" (destinos predeterminados) -- ERROR.

ERROR al compilar.

"C:\Git\xmrstak\build\install.vcxproj" (destino predeterminado) (1) ->
"C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (destino predeterminado) (3) ->
"C:\Git\xmrstak\build\xmrstak_cuda_backend.vcxproj" (destino predeterminado) (7) ->
(CustomBuild destino) ->
  CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ign
ored. [C:\Git\xmrstak\build\xmrstak_cuda_backend.vcxproj]

"C:\Git\xmrstak\build\install.vcxproj" (destino predeterminado) (1) ->
"C:\Git\xmrstak\build\ALL_BUILD.vcxproj" (destino predeterminado) (3) ->
"C:\Git\xmrstak\build\xmrstak_cuda_backend.vcxproj" (destino predeterminado) (7) ->
(CustomBuild destino) ->
  c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/host_config.h(135): fatal error C1189: #error:  -
- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [C:\Git\xmrst
ak\build\xmrstak_cuda_backend.vcxproj]

    1 Advertencia(s)
    1 Errores

Tiempo transcurrido 00:00:04.15
`

CMake Error: The source directory "C:/Git/xmrstak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_INSTALL_PREFIX:PATH=C:/Git/xmrstak/build
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/link.exe
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_RC_COMPILER:FILEPATH=C:/Program Files (x86)/Windows Kits/10/bin/10.0.16299.0/x86/rc.exe
CMAKE_RC_FLAGS:STRING=/DWIN32
CMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG
CMAKE_RC_FLAGS_MINSIZEREL:STRING=
CMAKE_RC_FLAGS_RELEASE:STRING=
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;60;61;62;70
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart.lib
CUDA_CUDA_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cuda.lib
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/bin/nvcc.exe
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include
CUDA_TOOLKIT_ROOT_DIR:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=9.1
CUDA_cublas_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cublas.lib
CUDA_cublas_device_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cublas_device.lib
CUDA_cudadevrt_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudadevrt.lib
CUDA_cudart_static_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart_static.lib
CUDA_cufft_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cufft.lib
CUDA_cupti_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/extras/CUPTI/libx64/cupti.lib
CUDA_curand_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/curand.lib
CUDA_cusolver_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cusolver.lib
CUDA_cusparse_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cusparse.lib
CUDA_nppc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppc.lib
CUDA_nppial_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppial.lib
CUDA_nppicc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppicc.lib
CUDA_nppicom_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppicom.lib
CUDA_nppidei_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppidei.lib
CUDA_nppif_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppif.lib
CUDA_nppig_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppig.lib
CUDA_nppim_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppim.lib
CUDA_nppist_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppist.lib
CUDA_nppisu_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppisu.lib
CUDA_nppitc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nppitc.lib
CUDA_npps_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/npps.lib
CUDA_nvcuvenc_LIBRARY:FILEPATH=CUDA_nvcuvenc_LIBRARY-NOTFOUND
CUDA_nvcuvid_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/nvcuvid.lib
HWLOC:FILEPATH=C:/xmr-stak-dep/hwloc/lib/libhwloc.lib
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=C:/xmr-stak-dep/hwloc/include
LIB_EAY_DEBUG:FILEPATH=LIB_EAY_DEBUG-NOTFOUND
LIB_EAY_LIBRARY_DEBUG:FILEPATH=LIB_EAY_LIBRARY_DEBUG-NOTFOUND
LIB_EAY_RELEASE:FILEPATH=C:/xmr-stak-dep/openssl/lib/libeay32.lib
MHTD:FILEPATH=C:/xmr-stak-dep/libmicrohttpd/lib/libmicrohttpd.lib
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=C:/xmr-stak-dep/libmicrohttpd/include
OPENSSL_INCLUDE_DIR:PATH=C:/xmr-stak-dep/openssl/include
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=C:/Program Files (x86)/AMD APP SDK/3.0/include
OpenCL_LIBRARY:FILEPATH=C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib
OpenSSL_ENABLE:BOOL=ON
SSL_EAY_DEBUG:FILEPATH=SSL_EAY_DEBUG-NOTFOUND
SSL_EAY_LIBRARY_DEBUG:FILEPATH=SSL_EAY_LIBRARY_DEBUG-NOTFOUND
SSL_EAY_RELEASE:FILEPATH=C:/xmr-stak-dep/openssl/lib/ssleay32.lib
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

**Comment by psychocrypt** [comment]
Your visyal studio ia not aupoorted by your cuda

```
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013,
2015 and 2017 are supported! [C:\Git\xmrst
ak\build\xmrstak_cuda_backend.vcxproj]
```

**Comment by nightsuspect** [comment]
his visual studio is updated 15.6.x so why is not supported it seems some misprogramming happend there

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\crt\host_config.h   line:133:

#if _MSC_VER < 1600 || _MSC_VER > 1911

#error -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

**Comment by psychocrypt** [comment]
I do not know how VS versioning works but his comiler is blocked by CUDA.
You can try remove the guard in the cuda header, sometimes this helps.

**Comment by Spudz76** [comment]
You can also use `-DCUDA_HOST_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/*good-version*/bin/Hostx64/x64/cl.exe`

You don't seem to have 14.11.25503 installed or it would have used it?

First, remove the check in CUDA and see if it results in something working.  Nvidia enjoys blocking things they just didn't bother to test, versus just letting it try.  So, let it try.

**Comment by joaquinabenza** [comment]
You was right spudz76, 14.11 wasnt installed, maybe the vs update uninstalled it, after several times trying to compile with the MSVC 14.13.26128 it didnt work, incompatible....

I checked MSVC 14.11 in the Visual Studio Installer and now xmr-stak success to compile, the standrad way.

THX everyone

**Comment by knoxcard** [comment]
Close ticket?
