### ISSUE TITLE
not working in nvidia 960 4GB but work in 1050ti, 1060, 1070...

### ISSUE THREAD

**Issue by javifly** [fireice-uk/xmr-stak#1314]
i have tested XMR-stack 2.4.1 and 2.4.2. Works fine in gtx1050ti, gtx1060, gtx1070... but not work in gtx960 4GB. isn´t compatible with nvidia 9 series?

[2018-04-05 19:07:31] : Mining coin: monero7
[2018-04-05 19:07:31] : Starting NVIDIA GPU thread 0, no affinity.
[2018-04-05 19:07:31] : Starting NVIDIA GPU thread 1, no affinity.
[2018-04-05 19:07:31] : Starting NVIDIA GPU thread 2, no affinity.
Invalid device ID!
[2018-04-05 19:07:31] : Setup failed for GPU 2. Exitting.

# Basic information
  - Type of the CPU. i3
  - Type of the GPU (if you try to miner with the GPU). gtx 960 4gb

# Issue with the execution
  - Do you compiled the miner by our own? no, use a exe file.
  ```
  run `./xmr-stak --version-long` and add the output here
Version: xmr-stak/2.4.2/e10e8e67/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20
  ```

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

**Comment by psychocrypt** [comment]
Yes this gpu works with cuda9. please post your logs and describe what is
not working. I the gpu not detected....
Please remove nvidia.txt and start the miner. Post **all** output.

**Comment by Spudz76** [comment]
Works perfectly on my GTX970, shows up as CUDA arch 52, gets ~444H/s
Though I run the dev branch always.

**Comment by javifly** [comment]
thanks psychocrypt 
I have removed the nvidia.txt file and started the program and worked me fine. The fail was in the nvidia.txt file.
