### ISSUE TITLE
Building under macOS failed

### ISSUE THREAD

**Issue by Teimoon** [fireice-uk/xmr-stak#1329]
Hey, 
I use MacOSx 10.11.6 and xmr-stak 2.4.2 

When I want to compile with
    "make install"
I get a lot of warnings like
    "null character ignored [-Wnull-character]"
and Errors like
    "source file is not valid UTF-8 ... <FF><FF>"

I converted it in TextEdit to UTF-8. But it did not work.
I compiled the previous version of xmr-stak without any Problems under macOS.

Thank you.

**Comment by Teimoon** [comment]
xmr-stak-2.4.2 admin$ make install
Scanning dependencies of target xmr-stak-c
[  2%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/._c_blake256.c.o
/Volumes/miner/xmr/xmr-stak-2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:1: warning: 
      null character ignored [-Wnull-character]
^
/Volumes/miner/xmr/xmr-stak-2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:2: error: 
      expected identifier or '('
<U+0000><U+0005><U+0016><U+0007>
        ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:5: warning: 
      null character ignored [-Wnull-character]
<U+0000><U+0005><U+0016><U+0007>
                                ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:7: warning: 
      null character ignored [-Wnull-character]
<U+0000><U+0005><U+0016><U+0007><U+0000><U+0002>
                                                ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:8: warning: 
      null character ignored [-Wnull-character]
<U+0000><U+0005><U+0016><U+0007><U+0000><U+0002><U+0000>
                                                        ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:25: warning: 
      null character ignored [-Wnull-character]
  ...OS X        
                 ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:27: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002>
                                 ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:28: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002><U+0000>
                                         ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:29: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002><U+0000><U+0000>
                                                 ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:31: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002><U+0000><U+0000><U+0000>  
                                                            ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:32: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002><U+0000><U+0000><U+0000>  <U+0000>
                                                                    ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:33: warning: 
      null character ignored [-Wnull-character]
  ...OS X        <U+0000><U+0002><U+0000><U+0000><U+0000>  <U+0000><U+0000>
                                                                            ^
/Volumes/miner/xmr/xmr-stak-


2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:35: warning: 
      null character ignored [-Wnull-character]
  ...<U+0000><U+0002><U+0000><U+0000><U+0000>      <U+0000><U+0000><U+0000>2
                                                                         ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:36: warning: 
      null character ignored [-Wnull-character]
  ...<U+0000><U+0000><U+0000>2<U+0000>
                                      ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:38: error: 
      source file is not valid UTF-8
  ...<U+0000><U+0000><U+0000>2<U+0000><U+0000><U+000E><B0>
                                                      ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:39: warning: 
      null character ignored [-Wnull-character]
  ...<U+0000><U+0000><U+0000>2<U+0000><U+0000><U+000E><B0>
                                                          ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:40: warning: 
      null character ignored [-Wnull-character]
  ...<U+0000><U+0000><U+0000>2<U+0000><U+0000><U+000E><B0><U+0000>
                                                                  ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:41: warning: 
      null character ignored [-Wnull-character]
  ...<U+0000><U+0000><U+0000>2<U+0000><U+0000><U+000E><B0><U+0000><U+0000>
                                                                          ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:43: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:44: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:46: error: 
      source file is not valid UTF-8
  ...<E2>
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:47: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:48: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:51: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:52: warning: 
      null character ignored [-Wnull-character]
  ...
     ^


/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:53: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:54: warning: 
      null character ignored [-Wnull-character]
  ...
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:4095: error: 
      source file is not valid UTF-8
  ...<FF><FF>
     ^
/Volumes/miner/xmr/xmr-stak-
2.4.2/xmrstak/backend/cpu/crypto/._c_blake256.c:1:4096: error: 
      source file is not valid UTF-8
  ...<FF>
     ^
3957 warnings and 13 errors generated.
make[2]: *** [CMakeFiles/xmr-stak-
c.dir/xmrstak/backend/cpu/crypto/._c_blake256.c.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-c.dir/all] Error 2
make: *** [all] Error 2

**Comment by Teutone** [comment]
builds fine here for AMD GPUs following build instructions under macOS 10.13.4. what other commands did you execute before `make install`?

**Comment by Teimoon** [comment]
Hello. Thank you for help. 
I executed...
cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
...before installing.

I solved my Problem now.
I used the tar.gz Archive instead of the zip.
Everything works fine here.

**Comment by jcrawford** [comment]
I am having a similar issue with MacOS 10.14, I tried the tar.gz as well as the zip both provide the same errors.

cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=ON
```
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework (found version "1.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.0.2q")
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- The ASM compiler identification is Clang
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jcrawford/Downloads/xmr-stak-2.10.0
```

make install
```
Scanning dependencies of target xmr-stak-asm
[  2%] Building ASM object CMakeFiles/xmr-stak-asm.dir/xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S.o
[  5%] Building ASM object CMakeFiles/xmr-stak-asm.dir/xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S.o
[  7%] Linking C static library bin/libxmr-stak-asm.a
[  7%] Built target xmr-stak-asm
Scanning dependencies of target xmr-stak-c
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
In file included from /Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:14:
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.h:31:56: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void hmac_blake256_init(hmac_state *, const uint8_t *, uint64_t);
                                                       ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.h:32:56: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void hmac_blake224_init(hmac_state *, const uint8_t *, uint64_t);
                                                       ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.h:40:53: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void hmac_blake256_hash(uint8_t *, const uint8_t *, uint64_t, const uint8_t *, uint32_t);
                                                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.h:41:53: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void hmac_blake224_hash(uint8_t *, const uint8_t *, uint64_t, const uint8_t *, uint32_t);
                                                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:225:61: error: unknown type name 'uint64_t'
void hmac_blake256_init(hmac_state *S, const uint8_t *_key, uint64_t keylen) {
                                                            ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:229:10: error: expected ';' after expression
        uint64_t i;
                ^
                ;
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:229:2: error: use of undeclared identifier 'uint64_t'
        uint64_t i;
        ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:229:11: error: use of undeclared identifier 'i'
        uint64_t i;
                 ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:239:7: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
             ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:239:14: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:239:28: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
                                  ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:240:7: error: use of undeclared identifier 'i'
                pad[i] ^= key[i];
                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:240:17: error: use of undeclared identifier 'i'
                pad[i] ^= key[i];
                              ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:246:7: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
             ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:246:14: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:246:28: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
                                  ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:247:7: error: use of undeclared identifier 'i'
                pad[i] ^= key[i];
                    ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:247:17: error: use of undeclared identifier 'i'
                pad[i] ^= key[i];
                              ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:255:61: error: unknown type name 'uint64_t'
void hmac_blake224_init(hmac_state *S, const uint8_t *_key, uint64_t keylen) {
                                                            ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:259:10: error: expected ';' after expression
        uint64_t i;
                ^
                ;
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:259:2: error: use of undeclared identifier 'uint64_t'
        uint64_t i;
        ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:259:11: error: use of undeclared identifier 'i'
        uint64_t i;
                 ^
/Users/jcrawford/Downloads/xmr-stak-2.10.0/xmrstak/backend/cpu/crypto/c_blake256.c:269:7: error: use of undeclared identifier 'i'
        for (i = 0; i < keylen; ++i) {
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-c.dir/all] Error 2
make: *** [all] Error 2
```
