### ISSUE TITLE
Win10 hangs with 2.4.1 after few accepted shares-ETN mining

### ISSUE THREAD

**Issue by myeneroglu** [fireice-uk/xmr-stak#1330]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - AMD
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Win10 64
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  No
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? Yes
  - Is the Main memory of the CPU or GPU undervolted? GPU undervolted
RX VEGA64

**Comment by JerichoJones** [comment]
Set clocks to stock and try again.
