### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by nhnc** [fireice-uk/xmr-stak#1332]
I got error message when I compiling xmr-stak 2.4.2 at fedora 27.

It's is my steps at a new install fedora 27:

# dnf install tcsh ftp screen libmicrohttpd-devel lm_sensors cpupowerutils cmake gcc-c++ openssl-devel libmicrohttpd-devel hwloc-devel opencl-utils-devel

# dnf update
# reboot

# dnf install kernel-devel kernel-headers gcc dkms acpid
# wget http://tw.download.nvidia.com/XFree86/Linux-x86_64/390.25/NVIDIA-Linux-x86_64-390.25.run

Install nvidia driver is OK (sh NVIDIA-Linux-x86_64-390.25.run)

Install cuda 9.1 is also normal:
# dnf config-manager --add-repo=http://negativo17.org/repos/fedora-nvidia.repo
# dnf install cuda-devel cuda-cudnn-devel

then I download xmr-stak, do the cmake .
the error message is:

-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found suitable version "9.1", minimum required is "7.5")
CMake Error at CMakeLists.txt:195 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/CMakeFiles/CMakeOutput.log".
See also "/root/xmr-stak/CMakeFiles/CMakeError.log".

 BUT

the same command I  used at another computer one month ago is fine.

The difference is:
kernel version: 4.15.6-300.fc27.x86_64 (before) and 4.15.14-300.fc27.x86_64 (now)
cuda version: cuda-9.1.85-2.fc27.x86_64(before) and cuda-9.1.85.3-5.fc27.x86_64 (now)

Have any one know what's wrong in my procedure?

**Comment by Spudz76** [comment]
It probably does not check the (oddball) RedHat location of the includes `/usr/include/cuda` and rather expects them to be available where nVidia says they belong, `/usr/local/cuda/include`

I bet the second dir does not exist, it should work if you `ln -s /usr/include/cuda /usr/local/cuda/include` and try again.

And `/usr/local/cuda` should already be a symlink to `/usr/local/cuda-9.1` or I don't think CMake would have found what it did.

**Comment by nhnc** [comment]
Thanks for your kindly help.
/usr/local/cuda/include is not exist, I did a symlink "include -> /usr/include/cuda" in the /usr/local/cuda/ dir, and re-login, but it shows the same error message.

And I can't find any *cuda-9.1* dir.

 I checked my order computer that work normally for cuda-9.1, there  is also no /usr/local/cuda/include exist, so I still understand where had been changed from cuda-9.1.85-2 to cuda-9.1.85.3-5.

**Comment by Spudz76** [comment]
if you have mlocate see if `updatedb` and then `locate -i nvcc` shows

**Comment by nhnc** [comment]
This is the result:
# locate -i nvcc 
/usr/bin/nvcc
/usr/bin/nvcc.profile  (new file)
/usr/share/cmake/Modules/FindCUDA/run_nvcc.cmake
/usr/share/man/man1/nvcc.1.gz
/var/cuda-repo-9-1-local/cuda-nvcc-9-1-9.1.85-1.x86_64.rpm (new file)

there are two more new files than my old fedora 27 WS (kernel version: 4.15.6)

**Comment by dbunic** [comment]
I had the same error when trying to compile **xmr-stak** with nvidia support on Fedora 27. Nvidia driver was already installed from negativo17.org repository. CUDA drivers were installed with:

```
dnf install cuda
dnf install cuda-devel
dnf install cuda-cudnn-devel
dnf install nvidia-driver-NVML
dnf install nvidia-driver-cuda
```

I'm not sure for the last two packages (because of several "trial and error") so you can try without them. Anyway, RPM were installed in **/usr/include/cuda** directory and cmake should be pointed to look inside. Finally, my cmake command from inner "build" directory was:

`cmake .. -DCUDA_TOOLKIT_ROOT_DIR=/usr/include/cuda -DOpenCL_ENABLE=OFF`

I took a bit longer to compile (a couple of minutes) but was successfully completed. Hope this will be helpful.

Cheers :)

**Comment by nhnc** [comment]
Thank you!
I solved that according to your method.

**Comment by kloinka** [comment]
Great....forgot the Cuda location issue, Thanks, worked!
