### ISSUE TITLE
Nvidia graphics card share reject by the  XTL pool !!!!

### ISSUE THREAD

**Issue by 35405903** [fireice-uk/xmr-stak#1333]
i use xmr stak 2.4.2 mining at communitypool.stellite.cash for XTL coin ,but  lots of share are reject by the pool , pools.txt is changed: "currency" : "stellite", so many reject ,and the pool bannd my ip 
. but when i mining  without  graphics ,no  share are reject!
cpu 2680v2 +750ti 
os windows 2008
v2.42

**Comment by psychocrypt** [comment]
please provide me with a stellite wallet address which i can use for tests
(please crate a new address which is not banned)

**Comment by psychocrypt** [comment]
lease post also the error report of your miner after you pressed the key 'r'

**Comment by JerichoJones** [comment]
Closing due to lack of response.
