### ISSUE TITLE
Monero v7 works?

### ISSUE THREAD

**Issue by aperets** [fireice-uk/xmr-stak#1334]
All results rejected! Why?

Please provide as much as possible information to reproduce the issue.

# Basic information
 rx560

# Compile issues
Windwos
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
Sumo bugfix version

# Stability issue
  - Is the CPU or GPU overclocked? yes
  - Is the Main memory of the CPU or GPU undervolted? yes

**Comment by Spudz76** [comment]
You did not include output of `xmr-stak --version-long`
You must have version 2.4.x and update your pools.txt algorithm to "monero7" not "cryptonight".
Older versions did not know anything but "cryptonight" but called it "monero" which will certainly no longer work after the fork happened about 7 hours ago.

**Comment by aperets** [comment]
monero7 works fine, thanks a lot!
