### ISSUE TITLE
CUDA_TOOLKIT_ROOT_DIR not found or specified

### ISSUE THREAD

**Issue by CEASar37** [fireice-uk/xmr-stak#1341]
I'm having some difficulty compiling the latest release (v2.4.2) of xmr-stak.
I'm attempting this on a Win10 machine with CUDA 9.1.85.3 and Visual Studio 15.6.5 with the required toolsets (as per this [guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md)).

I want to compile for cpu and nvidia support.
cmake doesn't seem to know where cuda is installed and I can't figure out how to tell it where to look.

Heres the output:
```
C:\Users\users\Downloads\xmr-stak-2.4.2\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:195 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support


-- Configuring incomplete, errors occurred!
See also "C:/Users/users/Downloads/xmr-stak-2.4.2/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Spudz76** [comment]
Try:
```
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
```
And then cmake again...

**Comment by CEASar37** [comment]
hm that didn't seem to work. I did however get it to partially behave by adding the path to CMakeCache.txt. 
However I'm still seeing 
```
-- Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
```

Is that just a matter of manually editing the .txt some more?

**Comment by psychocrypt** [comment]
set CUDA_TOOLKIT_ROOT_DIR to the cuda installation or install cuda again.
The cuda installerer ask if global environment variables should be set, say
yes. Restart your system

**Comment by CEASar37** [comment]
Still no dice. Just to make sure, is it `set CUDA_TOOLKIT_ROOT_DIR=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1`

The cuda installer doesn't ask about setting any global vars in either the express or custom installation. Its a very basic installer so im sure im not over looking it

**Comment by Spudz76** [comment]
Here is my entire CUDA-related environment from a Windows7 box that builds fine.  I have all three CUDAs installed and can build for any of them at any time by switching `v9.1` for the other target.

I'm sure there is plenty of garbage in my path that is not important / unrelated.

I don't think I manually added all of them to my System Environment but they are there somehow, must have been the installer.  Are you running as Administrator or is it skipping System level things because you are installing it as a peon / 'this account only'?
```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH_V7_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
CUDA_PATH_V8_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH_V9_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
NVCUDASAMPLES7_5_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
NVCUDASAMPLES8_0_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v8.0
NVCUDASAMPLES9_1_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v8.0
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
__VSCMD_PREINIT_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86_64;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\Redis\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Nodist\bin;C:\Program Files\dotnet\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\Wbem;C:\Windows\system32;C:\Windows
```
![image](https://user-images.githubusercontent.com/2391234/38457666-23d03c50-3a51-11e8-9e62-29bc1f2f359b.png)

**Comment by Spudz76** [comment]
And my build BAT for v9.1, which I believe works regardless of my System Environment (I have clones of this script with `v9.1` replaced for the others and they work perfectly)
```
set Path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86_64;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\Redis\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Nodist\bin;C:\Program Files\dotnet\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\Wbem;C:\Windows\system32;C:\Windows
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
set NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
set CMAKE_PREFIX_PATH=..\xmr-stak-dep_v2\hwloc;..\xmr-stak-dep_v2\libmicrohttpd;..\xmr-stak-dep_v2\openssl
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" x64 -vcvars_ver=14.11
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DCMAKE_BUILD_TYPE=Release -DXMR-STAK_CURRENCY=all -DDEFAULT_CUDA_ARCH="20;30;50;60" -DCUDA_SHOW_REGISTER=ON -DXMR-STAK_LARGEGRID=ON ..
cmake --build . --config Release --target clean
cmake --build . --config Release --target install
```

**Comment by JerichoJones** [comment]
@CEASar37 Is this resolved?

**Comment by CEASar37** [comment]
no it is not. Environment variables are in fact set correctly in windows but at compilation cmake says they are not

**Comment by JerichoJones** [comment]
I can't reproduce your issue.

**Comment by JarrodFairs** [comment]
i am having this same issue on linux mint 18.3 (ubuntu based distribution).
