### ISSUE TITLE
CN <--> CN7 auto-switch broke between 2.3.0 and 2.4.x

### ISSUE THREAD

**Issue by serisman** [fireice-uk/xmr-stak#1343]
I have two different machines running xmr-stak for CPU mining on the https://moneroocean.stream pool which auto switches between XMR and ETN depending on profitability.

Both machines are using the "monero7" currency config setting.

One machine is running 2.3.0 and appears to be able to auto-switch without a problem.

The other machine is running 2.4.2 and doesn't auto-switch properly.  Instead, it starts generating invalid shares that get rejected by the pool until the pool puts a temporary ban on the IP.

Restarting the miner fixes the problem until the pool switches coins again.

There are reports of other users with the same problem in the discord channel.

Also, for what its worth, xmrig 2.5+ is able to auto-switch without a problem as well.

**Comment by psychocrypt** [comment]
Switching between currencies is not supported by xmr-stak. Do not assume
that this works. The reason is also that we remove the monero hardfork
switch with the next release because the network forked already.
