### ISSUE TITLE
Downloading a release via google chrome is blocked because of virus detection

### ISSUE THREAD

**Issue by marcofranssen** [fireice-uk/xmr-stak#1345]
Downloading the latest release x64 zip failes in chrome because of detected virus.

**Comment by Spudz76** [comment]
Oversensitive, use a different browser or something that isn't paranoid (wget/curl).

**Comment by CircusDad** [comment]
Here is how you do it with chrome (from vega.miningguides.com):
"Chrome will call any miner malware and prevent the download.  The xmr_stak code is not bad but so many people are using miners as malware so the browser assumes you are not aware of what your doing.  Here are instructions on how to do this if you need them...
- Click the link and let Chrome prevent the download.
- Hit "Ctrl-J" to open the chrome download manager
- XMR-Stak will be the top file: Select, "Keep Dangerous File""

**Comment by Spudz76** [comment]
Or, that.  I am only familiar with how to get around the download block on Google Drive (claymore releases) which is clone it to your own Drive, and then you can force-download that clone of the file by clicking YES I LIKE BEING INFECTED THANKS.

**Comment by marcofranssen** [comment]
I have downloaded other miners in the past without any issues. I figure after running virusscanner the opcl backend is recognized as a trojan. I guess there is something which can be done about this to resolve this. This is the first miner I download from github having this issue.

**Comment by loveacat** [comment]
the same issue, windows release version seems has a Trojan, please resolve this

**Comment by JerichoJones** [comment]
@loveacat Complain to your AV vendor.
