### ISSUE TITLE
Results rejected. New update wont work with my miners but xmrig does?

### ISSUE THREAD

**Issue by agentpatience** [fireice-uk/xmr-stak#1346]
There seems to be a problem with latest xmr-stak build. Supportxmr.com and coinfoundry.org hashrates are half of what they are supposed to be. I can only get xmrig working on my miners. xmr-stak stopped working somehow with Monero during the update.

Can someone look into it?

**Comment by psychocrypt** [comment]
You missed to fill out the issue template. Withou logs and the config files
we can not reproduce the issue. Keep in mind that the pool calculated hash
eate is not exact and can variate very strong

**Comment by agentpatience** [comment]
Yea, but if you just build xmr-stak and test on these two pools you will see the errors. Someone else just posted socket error related messages, i get these on supportxmr pool. I have 10 miners not working on xmr-stak but xm-rig works. I am using centos and ubuntu linux, latest git pull, amd 6234, same setup worked before this update.

**Comment by agentpatience** [comment]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
AMD 6234
  - Type of the GPU (if you try to miner with the GPU).
NONE
# Compile issues
  - Which OS do you use?
  CENTOS/UBUNTU 16 SERVER
  add **all** commands you used and the **full** compile output here
  
  4  git clone https://github.com/fireice-uk/xmr-stak.git
    5  mkdir xmr-stak/build
    6  cd xmr-stak/build
    7  cmake3 -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..
    8  make install
    9  cd bin
   10  ls
   11   sysctl -w vm.nr_hugepages=128
   12  ./xmr-stak
   13  ./xmr-stak -v
   14  sudo apt-get --assume-yes update
   15  sudo yum install centos-release-scl epel-release
   16  sudo yum install cmake3 devtoolset-7-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make git
   17  sudo scl enable devtoolset-7 bash
   18  ip address show
   19  poweroff
   20  sudo yum install -y epel-release
   21  sudo yum install -y git make cmake gcc gcc-c++ libstdc++-static libmicrohttpd-devel libuv-static
   22  git clone https://github.com/xmrig/xmrig.git
   23  mkdir build
   24  cd build
   25  cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a


  run `cmake -LA .` in the build folder and add the output here
 root@mine8-poweredge build]# cmake -LA
CMake Error: The source directory "/root/xmr-stak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O2 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/root/xmr-stak/build
CMAKE_LINKER:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=ON
CMAKE_MAKE_PROGRAM:FILEPATH=/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/opt/rh/devtoolset-7/root/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC:FILEPATH=/usr/lib64/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib64/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib64/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib64/libssl.so
OpenCL_ENABLE:BOOL=OFF
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/bin/pkg-config
XMR-STAK_COMPILE:STRING=generic

# Issue with the execution
  - Do you compiled the miner by our own?
 Yes.
  run `./xmr-stak --version-long` and add the output here
 [root@mine8-poweredge bin]# ./xmr-stak --version-long
Version: xmr-stak/2.4.2/e10e8e6/master/lin/cpu/aeon-cryptonight-monero/20

# AMD OpenCl issue
NO
  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?
NO

**Comment by psychocrypt** [comment]
the reason why I ask is that I have not the time to reproduce all issues.
The most issues are wrong configurations. I do not know how expirence a
user is therefore it speedup the solution finding process if we get all
information from the beginnen.
never the less ich will try to reproduce this issue.

**Comment by psychocrypt** [comment]
How long does it takes until you see rejected shares. Could you please post the log with the rejected shares. Please also press the key `r` to show the error log. 
Do you mining only with cpu? 
I tried o reproduce the issue but I got only valid shares.

**Comment by Spudz76** [comment]
Working perfect on nanopool
Are you sure your pool operators are not idiots? :)

**Comment by agentpatience** [comment]
The problem is coinfoundry poolrate is half of what it should be and I cannot get any accepted shares with xmr-stak. I can't even get one decent share in from a fresh build since the update. I talked to oliver and since xmrig is still working well we feel it is xmr stak but I expect others will see the  issues, it should be quite evident if you try to mine to coinfoundry or  @supportxmr.com. I will fart around with other pools but I spent a lot of time trying to isolate where the problem is already... my girlfriend is pissed now that I have to setup my 10 boxes again LOL

**Comment by psychocrypt** [comment]
@agentpatience  As I wrote I need all the logs and configs from above. I can not reproduce the issue.

**Comment by agentpatience** [comment]
Ok, let me get you more details. Sorry for my drivel Psycho. I understand your concerns on the setup but I have kept everything the same.

**Comment by psychocrypt** [comment]
If you keeped everything the same please remove cpu.txt amd.txt and nvidia.txt and try the defaults

**Comment by agentpatience** [comment]
My email is: agentpatience@mail.com if you want to get in via root to take a look. I am setting up a new blade with a base install of CentOS7.

**Comment by agentpatience** [comment]
XMRIG output on same blade:
[root@mine8-poweredge xmrig]# ./xmrig 
 * VERSIONS:     XMRig/2.5.2 libuv/1.10.2 gcc/4.8.5
 * HUGE PAGES:   available, enabled
 * CPU:          AMD Opteron(TM) Processor 6234                  (4) x64 AES-NI
 * CPU L2/L3:    192.0 MB/64.0 MB
 * THREADS:      48, cryptonight, av=1, donate=1%
 * POOL #1:      xmr.coinfoundry.org:3032
 * COMMANDS:     hashrate, pause, resume
[2018-04-07 15:42:57] use pool xmr.coinfoundry.org:3032 97.107.139.34
[2018-04-07 15:42:57] new job from xmr.coinfoundry.org:3032 diff 7500
[2018-04-07 15:43:10] accepted (1/0) diff 7500 (2968 ms)
[2018-04-07 15:43:17] accepted (2/0) diff 7500 (3809 ms)
[2018-04-07 15:43:22] new job from xmr.coinfoundry.org:3032 diff 7500
[2018-04-07 15:43:22] accepted (3/0) diff 7500 (4598 ms)
[2018-04-07 15:43:25] accepted (4/0) diff 7500 (2028 ms)
[2018-04-07 15:43:25] accepted (5/0) diff 7500 (1142 ms)
[2018-04-07 15:43:35] speed 2.5s/60s/15m 1131.2 n/a n/a H/s max: 1347.0 H/s
[2018-04-07 15:43:36] new job from xmr.coinfoundry.org:3032 diff 14415

**Comment by agentpatience** [comment]
I loose over 350H/S with xmrig but it is working... so I can isolate it to the software.

**Comment by agentpatience** [comment]
What I can't figure out is why you can't reproduce the errors, can you try mining to: stratum+tcp://xmr.coinfoundry.org:3032

This pool worked flawless for me till the software change. I don't mean to sound like an ass. If it is a pool problem I will let Oliver know.

**Comment by psychocrypt** [comment]
you must set currency in pools.txt to `"currency" : "monero7",`
You tried to mine the wrong currency. Cryptonight is not longer used by `Monero`

**Comment by agentpatience** [comment]
Oh shit. You are right. You might want to add a condition to change this for the user if he is not keen to it. There are probably a whole bunch of miners where this directive never got changed. [2018-04-07 16:04:57] : Pool stratum+tcp://xmr.coinfoundry.org:3032 connected. Logging in...
[2018-04-07 16:05:07] : SOCKET ERROR - [stratum+tcp://xmr.coinfoundry.org:3032] CALL error: Timeout while waiting for a reply
[2018-04-07 16:05:36] : Fast-connecting to stratum+tcp://xmr.coinfoundry.org:3032 pool ...
[2018-04-07 16:05:36] : Pool stratum+tcp://xmr.coinfoundry.org:3032 connected. Logging in...
[2018-04-07 16:05:46] : SOCKET ERROR - [stratum+tcp://xmr.coinfoundry.org:3032] CALL error: Timeout while waiting for a reply
[2018-04-07 16:06:16] : Fast-connecting to stratum+tcp://xmr.coinfoundry.org:3032 pool ...
[2018-04-07 16:06:21] : Pool stratum+tcp://xmr.coinfoundry.org:3032 connected. Logging in...
[2018-04-07 16:06:31] : SOCKET ERROR - [stratum+tcp://xmr.coinfoundry.org:3032] CALL error: Timeout while waiting for a reply
[2018-04-07 16:07:00] : Fast-connecting to stratum+tcp://xmr.coinfoundry.org:3032 pool ...
[2018-04-07 16:07:00] : Pool stratum+tcp://xmr.coinfoundry.org:3032 connected. Logging in...
[2018-04-07 16:07:10] : SOCKET ERROR - [stratum+tcp://xmr.coinfoundry.org:3032] CALL error: Timeout while waiting for a reply
[2018-04-07 16:07:40] : Fast-connecting to stratum+tcp://xmr.coinfoundry.org:3032 pool ...
[2018-04-07 16:07:40] : Pool stratum+tcp://xmr.coinfoundry.org:3032 connected. Logging in...
[2018-04-07 16:07:47] : Difficulty changed. Now: 7500.
[2018-04-07 16:07:47] : Pool logged in.
[2018-04-07 16:07:47] : New block detected.
[2018-04-07 16:07:51] : Result accepted by the pool.
[2018-04-07 16:07:51] : Result accepted by the pool.
[2018-04-07 16:07:53] : Result accepted by the pool.
[2018-04-07 16:07:55] : Result accepted by the pool.
[2018-04-07 16:07:59] : Result accepted by the pool.
[2018-04-07 16:08:00] : Result accepted by the pool.
[2018-04-07 16:08:01] : Result accepted by the pool.
[2018-04-07 16:08:13] : Result accepted by the pool.
[2018-04-07 16:08:16] : Result accepted by the pool.
[2018-04-07 16:08:21] : Result accepted by the pool.
-----------------------------------------------------------------
Totals (ALL):      0.0 1334.9    0.0 H/s
Highest:  1418.6 H/s

**Comment by agentpatience** [comment]
there are still socket errors on startup of the process however it maybe pool related. I will post it to coinfoundrys work bench. Thanks for your understanding and assistance!

**Comment by psychocrypt** [comment]
@agentpatience  We are supporting now a bunch of currencies. If the user like to miner a cryptonight coin he can do it. Do not forget that Monero is not using `cryptonight` anymore.

btw: This is why I always ask for the configs. 90% of the issues can be solved by locking to it.

**Comment by fireice-uk** [comment]
> Not sure but usually documentation should be nearly as good as hand-holding?

The configuration assumes that that the user is not retarded enough to actively work against getting it right (enter `cryptonight` when asked to name the coin he is going to mine).

**Comment by agentpatience** [comment]
Tony, the problem with you is you are too logical and thinking from a biased view being a software developer.

 

When you have multiple miners of all different trades, groups, sects and god knows what else its hard to say everyone will run through all the docs. It is the engineers that need to make something that is a drop in dummy proof way of traversing through hardware and software changes. I am an electronics engineer and I totally respect your stance on this. I respect your patience and your interest in the thread. We learned some important details here, being that if one tried to upgrade xm-stak without consideration to "cryptonight" --> monero7 change that they would no longer be able to mine.

For some reason, xmr-stak was not able to scale without error like xmrig did during the migration. There are lessons here, 1 for me (read the docs) and 1 for the software engineers... make it easier to deploy xmr-stak by not letting old switches run. eg. "cryptonight". > pass a great sounding error message.


 

Thanks for your help.


Sent: Saturday, April 07, 2018 at 4:18 PM

**Comment by fireice-uk** [comment]
`cryptonight` is not an old switch, we added it together with everything else.

**Comment by psychocrypt** [comment]
The old switch is 'monero' try to add this in pools.txt and you will see
that the miner is exactly doing what you said.
