### ISSUE TITLE
File is empty or too short - config.txt.

### ISSUE THREAD

**Issue by avalyn2** [fireice-uk/xmr-stak#1351]
## My system specs

![image](https://user-images.githubusercontent.com/32930476/38459461-3e90d88e-3aaa-11e8-8b2b-67243ef538d0.png)

## The commands I entered

```
Please enter:
- Please enter the currency that you want to mine:
        - aeon7
        - cryptonight
        - cryptonight_lite
        - edollar
        - electroneum
        - graft
        - intense
        - karbo
        - monero7
        - stellite
        - sumokoin

sumokoin
- Pool address: e.g. pool.example.com:3333
sumo.bohemianpool.com:7777
- Username (wallet address or pool login):
Sumoo3yEnptVuGB9aa9utb38pH7sCjKFiDRjfpg3ngZgVaW3HQd32GB7FJ3iDzxKx6LYHdRJwHZePVX6EAVMrD6aZDoK7pzwntv
- Password (mostly empty or x):
x
- Rig identifier for pool-side statistics (needs pool support). Can be empty:

- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
N
- Do you want to use nicehash on this pool? (y/n)
n
- Do you want to use multiple pools? (y/n)
n
Pool configuration stored in file 'pools.txt'
[2018-04-07 21:24:14] : File is empty or too short - config.txt.
Press any key to exit.
```

# Compile issues
  - Which OS do you use? **Windows 10**
  - add **all** commands you used and the **full** compile output here **see above**
  run `cmake -LA .` in the build folder and add the output here `` **does not apply to my OS**
  ```

# Stability issue
  - Is the CPU or GPU overclocked? **no**
  - Is the Main memory of the CPU or GPU undervolted? **no**

**Comment by Spudz76** [comment]
Have not tried empty rig-id even though it claims to allow it, try entering something there and it may generate the file properly.  Then go make the rig-id empty (but I still think it doesn't enjoy that).

**Comment by Spudz76** [comment]
I do know the current version, given `-r ""` chokes and doesn't like empty "`rigid`"... which seems counter to what is claimed

**Comment by avalyn2** [comment]
I just put "x" to the question "- Rig identifier for pool-side statistics (needs pool support). Can be empty:"

still the same outcome:

```Pool configuration stored in file 'pools.txt'
[2018-04-08 00:47:07] : File is empty or too short - config.txt.
Press any key to exit.```

**Comment by ycsunjane** [comment]
I have same problem:
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"

**Comment by psychocrypt** [comment]
Do you have write access in the working directory (the folder from where you start the miner)

**Comment by psychocrypt** [comment]
Please remove the pool.txt in your folder. It could be you created a pools.txt with admin rights and now with the second start the miner starts without admin rights

**Comment by fireice-uk** [comment]
Delete config.txt and start again.

**Comment by avalyn2** [comment]
Hi, removing config.txt solved the problem.

**Comment by 54V4NT** [comment]
Removing config.txt on HiveOS and rebooting did not solve the problem.

**Comment by psychocrypt** [comment]
Do you compiled the miner by your own in HiveOS?
