### ISSUE TITLE
Increasing bfactor and bsleep gives 0 hashrate on GPU

### ISSUE THREAD

**Issue by phxn** [fireice-uk/xmr-stak#1353]
I'm using a GTX970 with the following settings, this enables me to use my PC normally.

`  { "index" : 0,
    "threads" : 13, "blocks" : 39,
    "bfactor" : 12, "bsleep" : 25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },`

When I want to watch more intensive video (madVR) I try to increase the bfactor and bsleep to 25 and 100 respectively. This used to reduce the load enough for me to watch 1080p videos in MPC-HC without issue, but in this latest version my GPU is giving a 0 hashrate with these settings.

Any idea what I could be doing wrong here?

Cheers

**Comment by Spudz76** [comment]
I usually have nicer luck with `sync_mode:0` and sometimes locking affinity helps.  Are you running `--noCPU` so it's just the one GPU thread?

I have noticed some users launching with `start /low` which sets the priority of the processes so they should wait for more important MPC-HC activity to happen before getting in the way.

**Comment by Spudz76** [comment]
My Win7 machine will shut off (bad PSU) if I run xmr-stak on the only GTX970/Windows combo I have available right now... or I would test some things

**Comment by phxn** [comment]
Thank you for the reply @Spudz76.

No I always run the CPU miner as my processor is more than powerful enough to mine and carry out regular desktop tasks.

I will try the sync_mode setting and the low priority mode and see how it goes. In the past when increasing bsleep and bfactor I'd see only a slightly lower hashrate but it wouldn't affect video playback.

**Comment by JerichoJones** [comment]
@phxn Is this resolved?

**Comment by psychocrypt** [comment]
please set bfactor to 12 and post the log of the minet from the first 3min.
Please press also the key `h` to show the hash rate report

**Comment by psychocrypt** [comment]
Does this mean the issue is solved?

phxn <notifications@github.com> schrieb am Mo., 23. Apr. 2018, 21:09:

**Comment by phxn** [comment]
No? I need to be able to lessen the load on my GPU sometimes, for that I need to raise bsleep and bfactor. When I raise bsleep and bfactor I get 0H/s from my GPU and then it appears to stop doing anything.

-------------------------------------------------------------------
xmr-stak 2.4.3 26a5d65f

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-04-23 20:19:26] : Mining coin: monero7
[2018-04-23 20:19:26] : Starting NVIDIA GPU thread 0, no affinity.
[2018-04-23 20:19:26] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-04-23 20:19:26] : WARNING: backend AMD (OpenCL) disabled.
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 0.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 2.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 4.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 6.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 8.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 10.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 1.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Starting 1x thread, affinity: 3.
[2018-04-23 20:19:26] : hwloc: memory pinned
[2018-04-23 20:19:26] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2018-04-23 20:19:26] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2018-04-23 20:19:27] : Difficulty changed. Now: 25000.
[2018-04-23 20:19:27] : Pool logged in.
[2018-04-23 20:20:12] : Difficulty changed. Now: 20000.
[2018-04-23 20:20:12] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   29.4 |   (na) |   (na) |  1 |   34.9 |   (na) |   (na) |
|  2 |   40.9 |   (na) |   (na) |  3 |   38.6 |   (na) |   (na) |
|  4 |   38.7 |   (na) |   (na) |  5 |   38.8 |   (na) |   (na) |
|  6 |   34.3 |   (na) |   (na) |  7 |   38.6 |   (na) |   (na) |
Totals (CPU):   294.2    0.0    0.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |   (na) |   (na) |   (na) |
Totals (NVIDIA):     0.0    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    294.2    0.0    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------

**Comment by psychocrypt** [comment]
please run the miner longer than 1 min. It could be that your gpu is now so
slow that the 10sec hash rate can not be calculated.
please post your nvidia.txt files. I am not sure if bfactor 15 is possible.

**Comment by phxn** [comment]
I ran it for 3 minutes, it stops posting hash rates, pressing H does nothing to show hashrates.

So, is there any bfactor/bsleep number I can use on a GTX970 that will slightly lessen the load? I use 12/25 for "max performance".

**Comment by phxn** [comment]
nvidia.txt

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 * If you do not wish to mine with your nVidia GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3373/4096 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 13, "blocks" : 39,
    "bfactor" : 12, "bsleep" : 25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by Spudz76** [comment]
I tune for lowest bfactor possible, and turn up the bsleep (125+ms) to give windows time to do things in between hashkernel execs.  Large bfactor (over 6) has never worked properly for me, I don't think that's possible.  Essentially if you already have a low diff from the pool plus you chop that up into divide-by-bfactor chunks, you end up doing like 100 nonces per kernel run, which probably returns faster than expected (too small) and ends up in race condition territory.

Also you are introducing bfactor*bsleep of doing nothing for every work round.  So eventually the duty cycle is doing mostly no work and a bunch of waiting.
