### ISSUE TITLE
Stellite is not in the list of supported currencies in the pool template file.

### ISSUE THREAD

**Issue by nexion21** [fireice-uk/xmr-stak#1356]
A very basic thing that can be fixed with a 8 letters, to prevent some headache for people after me

"currency" : "stellite" works to start mining the new fork, but there was no indication that it was an option. I tried mining on cryptonight, monero7 and several others with no luck. It would be nice if we didn't need to change the currency at all, but that would require communicating with the pool's server.

**Comment by sam08016** [comment]
Thanks man. That saved my day.

**Comment by MoNTE48** [comment]
+1

**Comment by Spudz76** [comment]
Pretty weird, it's right THERE...
```
- Please enter the currency that you want to mine:
        - aeon7
        - cryptonight
        - cryptonight_lite
        - edollar
        - electroneum
        - graft
        - intense
        - karbo
        - monero7
        - stellite
        - sumokoin
```

**Comment by mrosset** [comment]
@Spudz76 It's not documented in the configuration. not sure why your suggesting running the wizard is the obvious solution here. Since it quite plausible for someone to edit an existing configuration.
