### ISSUE TITLE
"result rejected by the pool"

### ISSUE THREAD

**Issue by weiyi5019** [fireice-uk/xmr-stak#1357]
please help me!
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
    i7-4790@3.6GHz
  - Type of the GPU (if you try to miner with the GPU).
    GTX 745

# Compile issues
  - Which OS do you use?
  win 7
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1887015/config.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1887016/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1887017/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1887018/pools.txt)

**Comment by weiyi5019** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1887022/config.txt)

**Comment by psychocrypt** [comment]
you must set currency in pools.txt to `monero7`
Monero is no longer using cryptonight. Monero extent the mining algorithm
for the hardfork. The hardfork was on 6th April 2018.

**Comment by weiyi5019** [comment]
thank you very much,i have fixed it:)

**Comment by feliceee** [comment]
Hello weiyi5019. I have the same problem. Can you please help me how to fix it ? 
Thank you.

**Comment by toyspace** [comment]
Hello weiyi5019. I have the same problem. Could you please help me how to fix it ?
Thank you.

**Comment by toyspace** [comment]
Hello @weiyi5019 . I have the same problem. Could you please help me how to fix it ?
Thank you.
