### ISSUE TITLE
Not working at all with GTX 1060: Lots of [CUDA] Errors 

### ISSUE THREAD

**Issue by stna1981** [fireice-uk/xmr-stak#1359]
Hi devs,

I'm coming from XMR-Stak-NVIDIA which worked like a charm and performed pretty god, ~460 H/s per default and up to 550 H/s with OC. Tested on different GTX 1060 3GB.

However, due to the hard fork of monero, I can't use it any longer and had to switch to XMR-Stak. Before I only had the issue that the hashrates were very poor, see #748 
But now, this thing is not even working any more at all. I start the xmr-stak.exe, select monero7, pool, login, pw and no for the rest. But I cannot mine. All I get is a list of errors:

[CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu 34: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu7: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:1365[CUDA] Error gpu 02: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu[CUDA] Error gpu 5: <

Windows Pro x64, nVidia 391.35 driver, different GTX 1060 3GB with default settings. Using the precompiled binaries from this site, latest release.

Can you please help?

Best regards

Stefan

**Comment by psychocrypt** [comment]
lease try to half the threads in nvidia.txt for all gpus.

**Comment by stna1981** [comment]
I found a working config now:
    _"threads" : 8, "blocks" : 144,
    "bfactor" : 7, "bsleep" :  25,_

Default was 12 threads / 27 blocks which did not work. However, I have another problem now.
When I run the miner for a single card, I get about 530 H/s which is really good. I can start 8 miners and each of them gets me ~530 H/s. But if I run one instance for more than 1 card, the performance drops the more cards are used, some cards go down to 500 H/s:

**1 card:**
| ID |    10s |    60s |    15m |
|  0 |  529.2 |   (na) |   (na) |

**2 cards:**
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  527.8 |   (na) |   (na) |  1 |  526.9 |   (na) |   (na) |

**4 cards:**
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  526.5 |   (na) |   (na) |  1 |  521.6 |   (na) |   (na) |
|  2 |  527.1 |   (na) |   (na) |  3 |  526.3 |   (na) |   (na) |

**8 cards:**
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  529.1 |   (na) |   (na) |  1 |  522.0 |   (na) |   (na) |
|  2 |  522.1 |   (na) |   (na) |  3 |  505.2 |   (na) |   (na) |
|  4 |  498.6 |   (na) |   (na) |  5 |  501.3 |   (na) |   (na) |
|  6 |  501.4 |   (na) |   (na) |  7 |  520.7 |   (na) |   (na) |

This was no issue in XMR-Stak-NVIDIA. Do I have to configure sth. special for more than 1 card in XMR-Stak? Is it a bug? Or something else?

**Comment by psychocrypt** [comment]
This is because you are using bfactor in combination with a high number of
gpus. The driver can not good handle the high number of context switches.
Try to start two instances of xmr-stak and use the half nvidia.txt config
within the first and the othwr half in the second instance.
You can path a nother config to the miner with the command line option
`--nvidia CFGNAME`

**Comment by stna1981** [comment]
But if it was be a driver issue, then it would also have occured in the oder XMR-Stak-NVIDIA, but threre the 8 cards performed all identical with 530 H/s. Moreover, with any bfactor lower than 6, XMR-Stak crashes and with bfactor 6, performance is way slower, only 460 H/s. I'm confused...

**Comment by Spudz76** [comment]
Difference could be CUDA 8 vs 9, both support the 10xx cards
The driver will support whichever version of CUDA the client software uses, and could act differently on the older one versus newer.

nVidia has been tuning their CUDA garbage to be more for Computer Vision / AI / Neural Nets and that kind of stupid useless stuff, and that is exactly not what makes mining fast.

**Comment by stna1981** [comment]
I think @psychocrypt should be able to tell which CUDA version is used and whether there is a difference in XMRStak and the older XMRStak-NVIDIA regarding the CUDA version. If this is the case, maybe there can be a switch for selecting the CUDA version or a build for CUDA9 and CUDA8?

**Comment by stna1981** [comment]
The issue is resolved imho as there is a working config. Maybe the auto-setup for GTX1060 should be adjusted to not use more than 8 threads and 144 blocks (which is also the fastest option).
