### ISSUE TITLE
after upgrade from 2.2.0 to 2.4.2, the xmr-stak can not be exectued successfully 

### ISSUE THREAD

**Issue by WayneWZ** [fireice-uk/xmr-stak#1360]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
Intel

# Compile issues
  - Which OS do you use?
Ubuntu
  add **all** commands you used and the **full** compile output here
  ```


  ```

# Issue with the execution

after upgrade from 2.2.0 to 2.4.2, the xmr-stak can not be exectued successfully now.

@ubuntu:~/software/tmp/xmr-stak-2.4.2/bin$ ./xmr-stak
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed
@ubuntu:~/software/tmp/xmr-stak-2.4.2/bin$

**Comment by WayneWZ** [comment]
[2018-04-08 00:08:20] : MEMORY ALLOC FAILED: mmap failed

**Comment by psychocrypt** [comment]
This means only that you have no large page support activated.

**Comment by CraniumDad** [comment]
This was helpful for me...  [https://kerneltalks.com/services/what-is-huge-pages-in-linux/](https://kerneltalks.com/services/what-is-huge-pages-in-linux/)

**Comment by Spudz76** [comment]
As is reading the config.txt comments and doing what it says you must...
