### ISSUE TITLE
Miner can no longer be triggered non-interactively

### ISSUE THREAD

**Issue by GSam** [fireice-uk/xmr-stak#1362]
Before the update to 2.4, specifying all the command line arguments led to the creation of all the correct config files and no interaction was required to launch the miner. This was useful for launching from an arbitrary file location e.g. within cron, without needing to change directories or setup the config files.

While there are some obvious workarounds, they don't interact very nicely with screen for instance.

**Comment by GSam** [comment]
~/xmr-stak/build/bin/xmr-stak -u "XXXXX" -p "x" --url "XXXX:80" --currency monero7 -i 0

Still asks to hit enter twice. Not sure how to avoid it.

**Comment by psychocrypt** [comment]
you missed a lot of options please add the cli option --help and check
there are also options like -r and --use-nicehash and tls you need to set.

**Comment by GSam** [comment]
Sorry, must have glazed over it. Closing.
