### ISSUE TITLE
lots of "socket error"

### ISSUE THREAD

**Issue by weiyi5019** [fireice-uk/xmr-stak#1364]
there is a new question,also it works,but it appears lots of "socket error"
![rtx 12](https://user-images.githubusercontent.com/38162229/38465867-836ccd2e-3b53-11e8-8daa-91b7b7d13464.png)
![rtx 444](https://user-images.githubusercontent.com/38162229/38465874-99390afa-3b53-11e8-8b69-266cfa248e7c.png)

# Basic information
  - Type of the CPU.
    i7-4790@3.6GHz
  - Type of the GPU (if you try to miner with the GPU).
    GTX 745

# Compile issues
  - Which OS do you use?
  win 7
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1887223/config.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1887224/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1887225/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1887226/pools.txt)

**Comment by weiyi5019** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1887228/config.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1887229/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1887230/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1887231/pools.txt)

**Comment by JerichoJones** [comment]
Have you tested another pool?

**Comment by warriordog** [comment]
A couple days ago I experienced this on MiningPoolHub.  The problem persisted for a full day until I rebooted, and the pool was working fine on my other PCs.  It's been fine since then, so I chalked it up to a windows bug of some kind.
