### ISSUE TITLE
cpu hash rate with 4 cores lower than with 3 cores

### ISSUE THREAD

**Issue by automag** [fireice-uk/xmr-stak#1366]
CPU. i5-3470 3.3 ghz
Windows 2012 server
xmr.stak 2.4.2 your compilation
no overclock or undervolt, all standard

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   38.7 |   52.6 |   41.3 |  1 |   66.2 |   38.0 |   45.0 |
|  2 |   50.6 |   55.6 |   57.3 |  3 |   21.1 |   23.2 |   29.0 |
Totals (CPU):   176.6  169.4  172.6 H/s

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   67.0 |   67.1 |   (na) |  1 |   69.2 |   69.4 |   (na) |
|  2 |   69.2 |   69.4 |   (na) |
Totals (CPU):   205.4  205.9    0.0 H/s

I have monitored these results over 2 days and the reports come out the same.

Can you explain the differences and advice how to fix and improve this.

**Comment by Dremor** [comment]
The INTEL I5-3470 got 6mB of cache, and Xmr-Stak needs 2mB per core in order to works at it's best capabilities.
Adding a forth core mean that some of your RAM will be used instead of the CPU cache, meaning lower bandwidth, and lower performances.
