### ISSUE TITLE
Performance Issue When Binary Compiled From CentOS6

### ISSUE THREAD

**Issue by LuvLetter** [fireice-uk/xmr-stak#1369]
`Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`
I want to use glibc 2.12 by compiling from CentOS 6. But the CryptonightV7 hash rate only reaches about 50% of latest openSUSE.

**Comment by loveacat** [comment]
the same issue, 2.4 xmr-stak only get 50% hashrate when compare to 2.2

**Comment by WhyTea78** [comment]
same here with centos 7
Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Spudz76** [comment]
CentOS is nearly the worst Linux possible.  however...

Some reports of the Meltdown/Spectre bug patch making CPU stuff (especially mining) slow down terribly, try disabling it (add `nopti` to kernel args in grub).

There is no actual reason to bother with running the PTI patch if you are not sharing your mining rig with 30 other (hostile) people or running virtual machines (with hostile users in them).  This patch is for Cloud hosts not home users.

https://medium.com/implodinggradients/meltdown-c24a9d5e254e

**Comment by WhyTea78** [comment]
the kernel-flag nopti didn't help :-(

[monero@monero ~]$ hwloc-ls
Machine (991MB)
  Package L#0 + L3 L#0 (16MB) + L2 L#0 (4096KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  Package L#1 + L3 L#1 (16MB) + L2 L#1 (4096KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  Package L#2 + L3 L#2 (16MB) + L2 L#2 (4096KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  Package L#3 + L3 L#3 (16MB) + L2 L#3 (4096KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  Package L#4 + L3 L#4 (16MB) + L2 L#4 (4096KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
  Package L#5 + L3 L#5 (16MB) + L2 L#5 (4096KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
  Package L#6 + L3 L#6 (16MB) + L2 L#6 (4096KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
  Package L#7 + L3 L#7 (16MB) + L2 L#7 (4096KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
  HostBridge L#0
    PCI 8086:7010
      Block(Removable Media Device) L#0 "sr0"
    PCI 1b36:0100
      GPU L#1 "card0"
      GPU L#2 "controlD64"
    PCI 1af4:1000
    PCI 1af4:1001

[monero@monero ~]$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel Xeon E3-12xx v2 (Ivy Bridge)
stepping	: 9
microcode	: 0x1
cpu MHz		: 3392.292
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase tsc_adjust smep erms xsaveopt arat
bogomips	: 6784.58
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:


"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
],

Every core make only about 30 h/s.
With xmr-stak 2.2 about 55h/s per core.

**Comment by Spudz76** [comment]
With that CPU it should work better with low_power_mode: 2 on all four lines.  It has 4096K L2 per physical core and thus two 2048K cryptonight blocks can be chewed by each core (low_power_mode is essentially number of threads per core, default is false/1 because very few CPUs have enough cache to fit more than 1)

I have several E5-2620 Xeons which have "15360MB" of "smartcache" and I get exactly 40 per core (280 total) running 7 lines (yes, it's a 6 core though).
```
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
```
That extra one running on whatever HT core it wants added another core worth, 40 or so, even though it "shouldn't" and running on the HT/fake cores is allegedly bad too.

Also on an i3-4160 (3072KB cache total, HA!) I get best results from a similar trick:
```
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
```
The 'roaming' thread gets kicked around and speed goes up and down all the time, but the average of the two is always stable around 80 (again, 40 per active core).  But I did this because there should only be enough room for one block, and is why the second thread is running 20H/s most of the time, but without it the whole CPU only does like 55 with the one thread / low_power_mode didn't help on this model due to being a cheezy desktop low TDP and low cache model.

**Comment by Spudz76** [comment]
Also the reason for the block having to fit inside cache is the AES-NI operations only work on data in cache and not on things out in regular memory.  So the amount of system RAM is pointless for CPU mining.  Or, if you blast outside of cache the AES boost is lessened by quite a bit (thus my second thread on a 3072 having only half the space it needs, runs half as slow).

**Comment by Spudz76** [comment]
There are further tunings you can try having to do with shutting down cores so that you get Turbo activated on the ones that are left.  Intel does weird things with Turbo and it's generally disabled if "too many" cores are running hard.  So if you limit the cores to whatever still engages Turbo sometimes you end up gaining rate, but I still think 4 threads at 40 will be faster than say 2 cores getting Turbo and 60 (160H/s versus 120H/s, even though CPU is hitting much much higher GHz, not enough to make up for strength in numbers)

**Comment by Spudz76** [comment]
And judging from your cpuinfo output, that kernel does not have the meltdown junk in it anyway.  It would have the `bugs` line after `flags`:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 4000.16
```

**Comment by WhyTea78** [comment]
Thank you for your time and ideas! But all these things didn't help. Of course I tried to find out the best settings for this cpu and these settings do the best job here. The CPU is an i7-3770 with 8192kb cache. I think the mismatch is because it is an vm. The point is that I didn't changed a thing but xmr-stak. And the issue only occurs with centos and not with ubuntu or debian or fedora.

**Comment by psychocrypt** [comment]
Do you recompiled also the 2.2 miner again and tested if the miner is today
still as fast as before. Maybe you changed your software. please compile
2.2 from scratch and run it

**Comment by WhyTea78** [comment]
here it is ;-) Same machine!

"cpu_threads_conf" :
[
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
],

-------------------------------------------------------------------
xmr-stak 2.2.0 c4400d19

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 0.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-04-11 09:10:36] : Start mining: MONERO
[2018-04-11 09:10:36] : Starting 1x thread, affinity: 0.
[2018-04-11 09:10:36] : hwloc: memory pinned
[2018-04-11 09:10:36] : Starting 1x thread, affinity: 1.
[2018-04-11 09:10:36] : hwloc: memory pinned
[2018-04-11 09:10:36] : Starting 1x thread, affinity: 2.
[2018-04-11 09:10:36] : hwloc: memory pinned
[2018-04-11 09:10:36] : Starting 1x thread, affinity: 3.
[2018-04-11 09:10:36] : hwloc: memory pinned
[2018-04-11 09:10:36] : Fast-connecting to xmrpool.eu:3333 pool ...
[2018-04-11 09:10:36] : Pool xmrpool.eu:3333 connected. Logging in...
[2018-04-11 09:10:36] : Difficulty changed. Now: 10000.
[2018-04-11 09:10:36] : Pool logged in.
[2018-04-11 09:10:49] : Difficulty changed. Now: 10000.
[2018-04-11 09:10:49] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   65.9 |   (na) |   (na) |  1 |   65.9 |   (na) |   (na) |
|  2 |   64.0 |   (na) |   (na) |  3 |   64.0 |   (na) |   (na) |
-----------------------------------------------------
Totals:    259.8   (na)   (na) H/s
Highest:   264.3 H/s

-------------------------------------------------------------------
xmr-stak 2.4.2 e10e8e6

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 0.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-04-11 09:12:40] : Mining coin: monero7
[2018-04-11 09:12:40] : Starting 1x thread, affinity: 0.
[2018-04-11 09:12:40] : hwloc: memory pinned
[2018-04-11 09:12:40] : Starting 1x thread, affinity: 1.
[2018-04-11 09:12:40] : hwloc: memory pinned
[2018-04-11 09:12:40] : Starting 1x thread, affinity: 2.
[2018-04-11 09:12:40] : hwloc: memory pinned
[2018-04-11 09:12:40] : Starting 1x thread, affinity: 3.
[2018-04-11 09:12:40] : hwloc: memory pinned
[2018-04-11 09:12:40] : Fast-connecting to pool.xmrpool.de:5555 pool ...
[2018-04-11 09:12:40] : Pool pool.xmrpool.de:5555 connected. Logging in...
[2018-04-11 09:12:41] : Difficulty changed. Now: 5000.
[2018-04-11 09:12:41] : Pool logged in.
[2018-04-11 09:12:53] : Difficulty changed. Now: 6818.
[2018-04-11 09:12:53] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   31.1 |   (na) |   (na) |  1 |   30.6 |   (na) |   (na) |
|  2 |   31.1 |   (na) |   (na) |  3 |   30.6 |   (na) |   (na) |
Totals (CPU):   123.4    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    123.4    0.0    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------

**Comment by WhyTea78** [comment]
sorry don't know why this pasted text is so huge!

**Comment by Spudz76** [comment]
You can put monospace blocks between triple backticks (markdown formatting)
Backticks being the apostrophe up in the top left corner on ~ button

**Comment by WhyTea78** [comment]
ahhh much better! thx

**Comment by WhyTea78** [comment]
Problem still persist! Any ideas?
