### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by iZakaroN** [fireice-uk/xmr-stak#1377]
After half day playing to setup the miner managed to run GPU's up to "threads" : 64, "blocks" : 32 with only 3.4kh/s, which is far from optimal as 64x56 runs fine at 4.3kh/s in xmrig without any problem and same GPU clocks settings (see below)
error: [CUDA] Error gpu 4: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:309
At line:1 char:150

CPU mining also do not runs very well as it gives 180h/s at its max compared to 240-320 in xmrig.

# Basic information
  - i7-8700k.
  - 5x1080ti.
  - 16g ram, 32g vmem

# Issue with the execution: no
  - Do you compiled the miner by our own?
No,   Pre-build 2.4.2 release:
  ```
  Version: xmr-stak/2.4.2/e10e8e67/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20
  ```
  - CPU: Stock,  GPU: TDP:85%, Core+80, Mem+80

**Comment by LuvLetter** [comment]
I notice a similar problem when I using the CentOS 6.5(GBLIC 2.12) to compile. I notice that it only reach only 50% compared to the binary which is compiled from latest openSUSE

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---
