### ISSUE TITLE
How to use just 1 gpu not both?

### ISSUE THREAD

**Issue by aceadamuk** [fireice-uk/xmr-stak#1379]
So i have an RX 480 8GB and a RX 580 4GB and i want to mine only on the rx480 how do i add this to a config? I have them both mining when im in bed but when i play on games i use the rx480 mining away while i play games.

**Comment by uvtzxpm** [comment]
Your question will be easier to answer if you post your current config files.

**Comment by the-babaji** [comment]
You need to modify your amd.txt and remove the references to the card you do not want to mine with.

delete this from the file
====================================
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 0,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
==========================================

then restart the miner

before you do that, you can make a copy of your current amd.txt and rename it to amd.txt.double   so you can have a backup or just delete your amd.txt and rerun xmr-stak to re-create the 2 card version.  You can also make a copy of the 1 card file and rename it to amd.txt.single  and then delete your amd.txt and rename amd.txt.single to amd.txt when you want to game.

**Comment by Spudz76** [comment]
Why bother deleting
add `//` before each of the lines in that section just like the header (which is also ignored)
