### ISSUE TITLE
xmr-stak.exe has stopped working

### ISSUE THREAD

**Issue by gavm11** [fireice-uk/xmr-stak#1383]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - i3-7100
  - GTX1060 6MB

# Compile issues
  - Windows10 64
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  No, downloaded compiled binary from GitHub
  run `./xmr-stak --version-long` and add the output here
  Version: xmr-stak/2.4.2/e10e8e67/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20

I have to run xmr-stak --noAMD on my system otherwise I get the Windows popup error "xmr-stak.exe has stopped working".

So I can run xmr-stak from a command window. However I'm not sure how to change the config file (or nvidia file or pools file) to run the program just using the xmr-stak.exe file?

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

**Comment by Spudz76** [comment]
If you have no AMD cards, erase the `xmrstak_opencl_backend.dll` it is not needed / should solve your crash.

Alternative is to put in amd.txt (create if not there)
```
"gpu_threads_conf" : null,
```
But I doubt just disabling threads will work.

Personally, I compile a CPU+nVidia (CUDA 9) version myself, so it doesn't even know about OpenCL.  But using the release pack and deleting the opencl backend is easier and similar effect (though there may be a complaint box to click OK on though, when it fails to load up the dll, it will continue fine).

**Comment by Spudz76** [comment]
Has it worked?  Also if so, which one of the solutions worked best for you?
