### ISSUE TITLE
Compile issues 

### ISSUE THREAD

**Issue by maxbest** [fireice-uk/xmr-stak#1384]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the GPU (if you try to miner with the GPU).
NVIDIA GTX750 1GB

# Compile issues
  - Which OS do you use?
  Ubuntu 16.04
  add **all** commands you used and the **full** compile output here
xmr@node-62:~/xmr-stak/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:758 (find_package)
  CMakeLists.txt:63 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/xmr/xmr-stak/build/CMakeFiles/CMakeOutput.log".
See also "/home/xmr/xmr-stak/build/CMakeFiles/CMakeError.log".
xmr@node-62:~/xmr-stak/build$ cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 ..
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:758 (find_package)
  CMakeLists.txt:63 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/xmr/xmr-stak/build/CMakeFiles/CMakeOutput.log".
See also "/home/xmr/xmr-stak/build/CMakeFiles/CMakeError.log".

**Comment by nightsuspect** [comment]
The test that CMake is using to check the include file uses an old-style C function definition. If -Wold-style-definition -Werror is in effect, gcc will barf on this.

find the file Modules/CheckIncludeFiles.cmake in your CMake installation (possibly in /usr/share/cmake or similar), find the line

  "${CMAKE_CONFIGURABLE_FILE_CONTENT}\n\nint main(){return 0;}\n")

and change int main() to int main(void).

**Comment by Spudz76** [comment]
I compile on Ubuntu 16 all the damn time and have NEVER seen this error.

Pretty sure if you compile this project with `-Werror` it will never ever make it out alive anyway.  Plenty of warnings but everyone is supposed to ignore them (including GCC!) haha
