### ISSUE TITLE
Add fonero

### ISSUE THREAD

**Issue by fonero-project** [fireice-uk/xmr-stak#1385]
Add fonero

+	{ "fonero", cryptonight_monero, cryptonight, 3u, nullptr },

**Comment by fonero-project** [comment]
If you do not want to add fonero we do it ourselves by fork your miner. Give your answer.

**Comment by fonero-project** [comment]
Hardfork on the 112,000 block

**Comment by Spudz76** [comment]
Would probably be better for promotion (and acceptance?) if your fonero.org site worked at all.

**Comment by fonero-project** [comment]
http://joxi.ru/DrlEkJWhvaw43m

**Comment by Spudz76** [comment]
Nope.

https://media.trillian.im/media/?m=aW1hZ2UvcG5nLDk2MCw1NDIsHveoMx0TAoBxNHqMkmzBAvdDlxsM07gtVC40j7Wh4l8%3D

**Comment by fonero-project** [comment]
The problem is on your side, use Google DNS

**Comment by Spudz76** [comment]
Charter/Spectrum is 32 Million users.  Their DNS returns 127.0.53.53 to every one of those people.

Sure, everyone should use Google DNS but only 3 Million of those users might bother.  I am a user that would usually bother but didn't, last time I reconfigured my router...

**Comment by fonero-project** [comment]
dev add fonero your miner

**Comment by psychocrypt** [comment]
ry I missed this feature request. Could you please point to a pool that we
can see the flobal hash rate. A pool list would also be good

**Comment by fonero-project** [comment]
Official pool (fee 0%):
    http://pool.fonero.org
    Unofficial pool (fee 0%):
    https://fno.cryptopool.space
    Unofficial pool (fee 0.1%):
    https://easyhash.io/fno
    Unofficial pool (fee 0%):
    http://fonero-moscow.ru


People can not mine after moving to v7

**Comment by psychocrypt** [comment]
why can they not mine? The can choose `cryptonigh_v7` directly since
version 2.4.3

**Comment by fonero-project** [comment]
psychocrypt, люди жалуются, не видят желаемой монеты в майнере и начинается ступор у них.
Просто добавь пожалуйста Fonero в списко выбора монет.

**Comment by psychocrypt** [comment]
please switch to english.

**Comment by fonero-project** [comment]
psychocrypt, people complain, they do not see the desired coin in the miner and the stupor begins with them.
Just add Fonero to the list of coins.
Similar to the coin stellite

**Comment by psychocrypt** [comment]
sry we had a lot of work and therefore we have higher response times.
I looked to your hash rate and we have currently a minimum requirement of
5MH/s (foneto has <400KH/s) before we add the coin as native coin.
Please choose cryptonight_v7 as algorithm after the fork.

Sry, but the list of coins get's to long and to fast outdated if we add
each small fork.

**Comment by fonero-project** [comment]
Well thank you
