### ISSUE TITLE
xmr-stack stalled after some hours

### ISSUE THREAD

**Issue by tripolino** [fireice-uk/xmr-stak#1386]
Please provide as much as possible information to reproduce the issue.

# Basic information
  
  - Type of the GPU ASUS STRIX VEGA 56 

# Compile issues
  - Which OS do you use? Windows 10 64 bit with beta blochain driver august 2017
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here

    2.4.2
    e10e8e6

  ```

# Stability issue
  - Is the CPU or GPU overclocked? No , all original value
  - Is the Main memory of the CPU or GPU undervolted? No , all original value

**Comment by tripolino** [comment]
I try latest asus strix vega 56 , after two hours , xmr-stack stalled , no block found and not error on screen , I can close the program pressing x, restart and working for two hours then stalled again.
I try to lower intensity but same result.
I try to use other miner for other crypto like ethereum and it is working well.

**Comment by Spudz76** [comment]
v2.4.2-945524b on Windows 7 mining CPU only, absolutely never hangs.
Same version on Linux (several distros and ages) mining everything (various blends of CPU+AMD+nVidia, some with all three), absolutely never hangs.

So it's not a general problem / could be OpenCL+Windows is the only place with the issue.

**Comment by tripolino** [comment]
I have this issue on windows 10 64bit (not windows 7)
The issue is with the new "Asus vega 56 strix" Sapphire vega 56 working ok.

**Comment by Spudz76** [comment]
So you can run the Asus Strix on Windows 7 with the same version of xmr-stak successfully?

I pointed out Windows 7 because then it's not a every-Windows issue and may be ONLY W10, which could narrow down the cause.  Very strange another Vega56 works fine too.

**Comment by tripolino** [comment]
I will try windows 7

**Comment by tripolino** [comment]
I use default setting ...no undervoltage no overclock, buy the card and use the xmr stack no overdriventool or other tweak.

**Comment by Spudz76** [comment]
Strix are 'factory OC' therefore even if you didn't do it, it is over spec and draw more watts.
The fact your Sapphire doesn't freeze supports this.
I would blame PSU, or thin wiring (lack of watts on PCIe whips).
This causes same as too much clock / undervolting (the lack of watts essentially force-undervolts the card)

**Comment by tripolino** [comment]
I have  no problem with xmr-stack-amd...and the new vega from ASUS. but I d' like to use monero and I need to use latest version of xmr-stack 2.4.2 on windows 10 64bit beta Blockchain 23 aug.

**Comment by Spudz76** [comment]
I have a 750w which is way more than needed for GTX970 and i7-2600

Still powers off unexpectedly if I run BF4 at anything over lowest details.  Or I'm sure xmr-stak would nuke it too, it did with the GTX770 I had a couple weeks ago (same PSU).  Actually the mining for a couple weeks on the GTX770 is what sucked the last life out of this PSU (it acted nicer before then).  Because it's old, it's more like a 350w now days.  Also, makes a nice hummmm into my speakers (inches from PSU) so it obviously has problems (dead cooked caps).

Just saying, you don't always know the PSU is what it says it is, could be sick or old or just a lemon.  Although EVGA PSU are generally pretty good from what I hear, I do not know if they burn up in 1y or 5y (my PSU is around 5y old, and failing for sure, the fan failed at 2y and I replaced it once I noticed, probably got cooked back then the first time and has been slowly getting worse since).

**Comment by Spudz76** [comment]
When windows doesn't see the GPU come back for more abuse within a default-short amount of time, it tosses a driver restart and that dumb message.  Lower threads, raise bsleep, or hack registry to raise the timeout to like 20-30 seconds so it doesn't prematurely spaz.

https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys

**Comment by mischief** [comment]
@Spudz76 i assume that won't help the BSODs - which occur in the video driver itself (IIRC ati<something>.sys).

**Comment by JerichoJones** [comment]
If the video driver is crashing it is likely that your Intensity is set too high.

**Comment by mischief** [comment]
raising the TDR registry keys to twice their default value (namely `TdrDelay` and `TdrDdiDelay`) seems to have completely stopped my gpu hang/TDR 0x116 BSOD problem.

@tripolino have you tried this?
