### ISSUE TITLE
xmr-stack hanging

### ISSUE THREAD

**Issue by guntire** [fireice-uk/xmr-stak#1388]
In fact, I started to having simillar hanning problems using version 2.2.0.  Then, I returned to version 2.0.0 which was quite stable for me. Now, I have no choice (because of PoW) to run version 2.3.0 or above. I tried all of them, 2.3.0, 2.4.1, and 2.4.2 ... and I experiencing the same problem: it hang, freezed or stalled ramdomly, sometime after 1 hour, othetime after 20 minutes! there are no real patterns I could see.

# Basic information
  - Type of the CPU : Intel Core i3570, AMD Phenom II 910, 
  - Type of the GPU : AMD R9 200x

# Compile issues
  - OS :  Windows 10 Pro 1709
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own? Yes, using the command lines within the doc directory.
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? CPU arer not overclocked, some GPU are overclocked on some machines but not on some other machines that hang also, I can't see any patterns here. 
  - Is the Main memory of the CPU or GPU undervolted? memory CPU et GPU voltages are at the standard values.

**Comment by JerichoJones** [comment]
Please post your amd.txt

**Comment by guntire** [comment]
Hi, that for answering. 
  
Here is what I found this morning. 

It appears that my problems were caused by GPU overclocking (that works fine with the previous XMR-Stack version 2.0.0). I also updated on all my machine to the latest GPU driver from AMD (AMD Radeon Adrenaline 18.3.4) to help diagnose by eliminating some variables. Then, I put back the default factory values (core and memory clock) for all my GPU and use the XMR-Stack version 2.4.2. All my rigs and stations appear to be very stable until now, I mean after some hours running it, I'm holding tight! However without overclock, Without overclocking, I lost somewhere between 5% to 10% of hashing rate. I suspect that version 2.0.0 was more tolerant to overclocking. For now, I prefer to have some stability, so I leave GPU at default factory settings. 

In any case, here is my amd.txt (auto-generated by xmr-stark itself), I have not changed any parameters in here on one of my AMD rig (1xAMD r9 290, 2xAMD 280x). 
/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 * index         - GPU index number usually starts from 0
 * intensity     - Number of parallel GPU threads (nothing to do with CPU threads)
 * worksize      - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 2 = chunked memory, chunk size is controlled by 'mem_chunk'
 *                     required: intensity must be a multiple of worksize
 *                 1 or true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 0 or false = use a contiguous block of memory per thread
 * mem_chunk     - range 0 to 18: set the number of elements (16byte) per chunk
 *                 this value is only used if 'strided_index' == 2
 *                 element count is computed with the equation: 2 to the power of 'mem_chunk' e.g. 4 means a chunk of 16 elements(256byte)
 * comp_mode     - Compatibility enable/disable the automatic guard around compute kernel which allows
 *                 to use a intensity which is not the multiple of the worksize.
 *                 If you set false and the intensity is not multiple of the worksize the miner can crash:
 *                 in this case set the intensity to a multiple of the worksize or activate comp_mode.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
  // gpu: Tahiti memory:2265
  // compute units: 32
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Tahiti memory:2265
  // compute units: 32
  { "index" : 1,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Hawaii memory:3136
  // compute units: 40
  { "index" : 2,
    "intensity" : 960, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,
