### ISSUE TITLE
no config file generated in docker container

### ISSUE THREAD

**Issue by marcokh** [fireice-uk/xmr-stak#1389]
Hello,

I tried to build the Dockerfile from the repo, the container build and start as expected, but I cannot see any config file generated. The docs seems to say that latest config file formats should be created but not sure where to expect them ? 

Also, a detail but since the binary isn't configured, it's looping very fast and filing the log file with thousands of this line fast enough to fill the hard drive to 100% within a few hours 

> Invalid port number. Please enter a number between 0 and 65535.

**Comment by Spudz76** [comment]
You have to run it interactive the first time, it asks questions that need input.  The very first one is which port number you want the Web Interface on (or 0 for off) which is exactly that message.

It does not create any files at all until those questions have been answered once.

**Comment by marcokh** [comment]
Thanks for your help. After I logged in my container and executed interactively the xmr-stak bin it did generate the files and I am up and mining again!

**Comment by xq0404** [comment]
> 
> 
> Thanks for your help. After I logged in my container and executed interactively the xmr-stak bin it did generate the files and I am up and mining again!

Would you upload your container image to Docker or share your docker image here in this post as a file attachment? Thanks a lot.

**Comment by marcokh** [comment]
sure, happy to help and thanks for your work
