### ISSUE TITLE
Xmr-stak cmd terminated after 48hrs stress test

### ISSUE THREAD

**Issue by Sleinous** [fireice-uk/xmr-stak#139]
![screenshot_20171119-104709](https://user-images.githubusercontent.com/33639239/32989485-4c24ddac-cd17-11e7-9902-417030fcb403.jpg)

Please note this is not the PC with the driver crash, this is a 100% fermi build mining for 48hrs then crashed

**Comment by fireice-uk** [comment]
@Sleinous can you please include output of xmr-stak.exe -V (you might need to run it from a privileged console)

**Comment by Sleinous** [comment]
@fireice-uk 
Here's what that command returns for me : 

![image](https://user-images.githubusercontent.com/33639239/32991694-b61275ac-cd40-11e7-8c7b-21123c291c81.png)
Thanks
