### ISSUE TITLE
Windows 10 performance drop by 17% from version 2.2.0 to 2.4.2

### ISSUE THREAD

**Issue by asdecopes** [fireice-uk/xmr-stak#1392]
Please provide as much as possible information to reproduce the issue.

I was using xmr-stak 2.2.0 under Windows 7.
Hashrates were: 
     **CPU: 375 h/s**
     GPU: 470 h/s

I did a clean install to Windows 10 and installed AMD drivers with compute workload and xmr-stak 2.4.2
Hashrates now:
      **CPU: 310 h/s**
      GPU: 470 h/s

GPU mining seems to be ok but my CPU mining performance has been reduced by 17%

Any idea?

# Basic information
  - Type of the CPU. Intel Xeon E5-2650L V2
  - Type of the GPU (if you try to miner with the GPU). Radeon RX 550 4Gb
  -OS: Windows 10
  -Windows 10 energy option set to max performance.
  -Miner does say anything about virtual memory problems (pagination file).
  -Currency: Monero
  -Same config files (adapted to new version)

[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1895282/cpu.txt)

# Issue with the execution
  - Do you compiled the miner by our own?
  No. Downloaded the compiled release from Github

# Stability issue
  - Is the CPU or GPU overclocked? CPU not overclocked, GPU bios mod
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by Spudz76** [comment]
I think I would use this:
```
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : 2, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : 2, "no_prefetch" : true, "affine_to_cpu" : false },
```

**Comment by asdecopes** [comment]
I'm trying it.
However, I have 25Mb of L3 cache. Should not be 12 threads?

**Comment by Spudz76** [comment]
https://ark.intel.com/products/64585/Intel-Xeon-Processor-E5-2650L-20M-Cache-1_80-GHz-8_00-GTs-Intel-QPI

That said 20MB which is what I based my ideas on...

**Comment by psychocrypt** [comment]
lease post the config from 2.2.0 and from the new version

**Comment by Captmario** [comment]
Hello,
I don't know if i should post here but i have same issue as OP.
My Xeon E5620 X2 seem to perform 5-10% lower on newer xmr stak's beyond 2.2.

**On Xmr Stak 2.2 : 390 H/s
On Xmr Stak 2.4 : 350 H/s**

I have same config cpu.txt file on both versions. Tried different combinations but seems to be an issue with newer xmr stak. Combining multiple rigs i am losing lots of hashes

Windows 10 user aswell and tried both compiled and self-compiled versions.

**Comment by asdecopes** [comment]
CPU config file of V2.2
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1900125/cpu.txt)
Xeon E5-2650L V2: 375h/s

CPU config file of V2.4.2
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1900128/cpu.txt)
Xeon E5-2650L V2: 330h/s

**Comment by psychocrypt** [comment]
which cpu, os, currency

asdecopes <notifications@github.com> schrieb am Mi., 11. Apr. 2018, 21:06:

**Comment by asdecopes** [comment]
Hi psychocrypt,

The requested information is in the first post. Anyway:

OS: Windows 10 clean install
CPU: Xeon E5-2650L V2 (no overclock)
Currency: Monero

Thanks!

**Comment by Captmario** [comment]
Same issue here, I noticed that this difference is on monero7 types of algos (cryptonight v7).
Switching to older algo cryptonight might resolve this issue, i'll test it later.

psychocrypt can you optimize it to atleast perform same as before? my CPU workers lost bunch of hashes for no reason

**Comment by psychocrypt** [comment]
The algorithm has changes. Therefore it is not possible to get the same old
performance on all systems. It depends on the system.
