### ISSUE TITLE
Please allow httpd_port to be specified with a CLI flag

### ISSUE THREAD

**Issue by starlilyth** [fireice-uk/xmr-stak#1395]
Thank you for providing an API in your miner, this makes a world of difference for status reporting. 

I would like to integrate your miner into PIMP OS and miner.farm, as there has been some requests for it. We dynamically assign the port used to communicate with the miners API on the command line in our tools, as most miners allow for (or require) this, and it provides maximum flexibility to our users. 

All other flags we need seem available on the command line, if it were possible to specify the httpd_port with a flag we could incorporate your miner immediately. Thank you for your consideration of this request. 

Lily
https://getpimp.org

**Comment by JerichoJones** [comment]
It's already supported.  
  
xmr-stak --help

**Comment by starlilyth** [comment]
Beg your pardon, but I do not see it listed. Your assistance is gratefully appreciated. 

xmr-stak --version
Version: xmr-stak 2.2.0 2ae7260

./xmr-stak --help
Usage: xmr-stak [OPTION]...

  -h, --help            show this help
  -v, --version         show version number
  -V, --version-long    show long version number
  -c, --config FILE     common miner configuration file
  --currency NAME       currency to mine: monero or aeon
  --noCPU               disable the CPU miner backend
  --cpu FILE            CPU backend miner config file
  --noAMD               disable the AMD miner backend
  --amd FILE            AMD backend miner config file
  --noNVIDIA            disable the NVIDIA miner backend
  --nvidia FILE         NVIDIA backend miner config file

The following options can be used for automatic start without a guided config,
If config exists then this pool will be top priority.
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333
  -O, --tls-url URL     TLS pool url and port, e.g. pool.usxmrpool.com:10443
  -u, --user USERNAME   pool user name or wallet address
  -p, --pass PASSWD     pool password, in the most cases x or empty ""
  --use-nicehash        the pool should run in nicehash mode

**Comment by JerichoJones** [comment]
That version is old. Download the latest.

**Comment by starlilyth** [comment]
Will do! Thank you for your help.
