### ISSUE TITLE
Results rejected by pool after a while - Low difficulty share

### ISSUE THREAD

**Issue by ragman666** [fireice-uk/xmr-stak#1396]
When running the miner it appears to run fine for a while, usually returns about 50 to 60 valid results. After this I start getting the error "Low difficulty share" and this never recovers.

I have 3 Ubuntu machines on the same pool with 0 issues.

# Basic information
  - Type of the CPU. - Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 3201 Mhz, 4 Core(s), 4 Logical Processor(s)
  - Type of the GPU (if you try to miner with the GPU). - NVIDIA GeForce GT 640

# Compile issues
  - Which OS do you use? Windows 10 version 1709

  add **all** commands you used and the **full** compile output here
NA, run from latest windows version

  run `cmake -LA .` in the build folder and add the output here
NA, run from latest windows version

# Issue with the execution
  - Do you compiled the miner by our own? No

  run `./xmr-stak --version-long` and add the output here
Version: xmr-stak/2.4.2/e10e8e67/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20

# AMD OpenCl issue
NA, 
  run `clinfo` and add the output here
NA

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1896158/config.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1896159/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1896160/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1896161/pools.txt)
[xmrlog.txt](https://github.com/fireice-uk/xmr-stak/files/1896186/xmrlog.txt)

**Comment by Spudz76** [comment]
I would be switching pools because that autodiff is ridiculous.
You need to be running around 25200 and it was all over the place / oversensitive.
Suspect once it sent you on a wild diff chase and rejected a block for being expired, it drops the diff too low and then you submit too often and then it sent it sky high again.  Seems like the pool is getting confused.

Do the other rigs that work OK have a different hashrate (higher probably)?

**Comment by ragman666** [comment]
no, other rigs that are fine have lower hash. Also they have only CPU and no GPU and they are ubuntu. Running the latest version though

**Comment by Spudz76** [comment]
I await knowledge from others, but there was some issue with bfactor but I thought it was only on arch-20 cards.  However if it's a DDR3 version of GT640 then it *is* arch 2.1 / GDDR5 version is 3.5 and the Mobile version is 3.0 (what a mess for the same "model").

So try running with bfactor 0 and whatever you have to do to threads and blocks (probably way lower) to make it run low bfactors.  On my "CUDA Arch 2.x Infirmary Rig":
```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 465 architecture: 20
  //      memory: 924/964 MiB
  //      smx: 11
  { "index" : 0,
    "threads" : 50, "blocks" : 8,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 0,
  },
  // gpu: GeForce GTX 550 Ti architecture: 21
  //      memory: 946/964 MiB
  //      smx: 4
  { "index" : 1,
    "threads" : 50, "blocks" : 8,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 0,
  },
  // gpu: GeForce GTX 550 Ti architecture: 21
  //      memory: 946/964 MiB
  //      smx: 4
  { "index" : 2,
    "threads" : 50, "blocks" : 8,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 0,
  },

],
```

I generally just do smx*2 for blocks and then move threads around until best is found, or it crashes.  But definitely no bfactor on 2.x cards.

**Comment by Spudz76** [comment]
I forgot you posted nvidia.txt oooops / yours is the arch 30 version (which is weird, should be 35? not GT640M... hmm)

https://developer.nvidia.com/cuda-gpus

**Comment by ragman666** [comment]
testing with bfactor at 0 and various threads and blocks, will update with results

**Comment by ragman666** [comment]
tested with bfactor 0 and many different combinations of threads and blocks, same issue no matter what.

Tested with CPU mining only, same issue
Tested with GPU mining only same issue

tested on another pool for another coin, same issue

**Comment by psychocrypt** [comment]
@ragman666  I think I found the problem, it should be fixed with #1437. This PR will be merged into the dev branch as soon as it is reviewed.

**Comment by DrStein99** [comment]
Hi.  I get "low difficulty share" on my CPU rigs.  It comes and goes.   I get this error sometimes on ALL my rigs at the same hour/minute.  Sometimes I get the error for a bunch of shares in a row on only 1 rig.

I do not know how to troubleshoot.  I sure wish I knew more about what specifically causes this error and how I can setup my tools to trap more details. 

I have been re-arranging my data room, upgrading cables, switches and power.  For reasons unknown, these changes have increased my hash share reports on the pool-side.  I am not certain I am getting lucky 2 days in a row or that I may have had a bottle-neck in my infrastructure.

**Comment by ragman666** [comment]
issues fixed with latest version
