### ISSUE TITLE
My GPU goes to 0 MH/s after seconds

### ISSUE THREAD

**Issue by karkyn** [fireice-uk/xmr-stak#1400]
Hello, I have three Sapphire Radeon RX 580 Nitro + Special Edition, and when I start Claymore 1 of them first show 25MH/s and after a seconds goes to 0MH/s and Temperature and Fan also goes to 0

thanks

**Comment by Spudz76** [comment]
Claymore?

**Comment by karkyn** [comment]
yes with claymore

**Comment by JerichoJones** [comment]
Ask Claymore.

**Comment by karkyn** [comment]
no I'm not Claymore
