### ISSUE TITLE
OLD DUMB AND NEEDING HELP TO INSTALL

### ISSUE THREAD

**Issue by joe1950** [fireice-uk/xmr-stak#1405]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU   Intel i7 - 3770K CPU @ 3.50GHz
  - Type of the GPU  AMD Radeon HD 7700

# Compile issues
  - Which OS do you use?  Windows 7 Ultimate
  ```
  add **all** commands you used and the **full** compile output here  ???
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here  ???
  ```

# Issue with the execution
  - Do you compiled the miner by our own?  ???
  ```
  run `./xmr-stak --version-long` and add the output here  How do I do this?
  ```

# AMD OpenCl issue  ??

  ```
  run `clinfo` and add the output here How do I do this?
  ```

# Stability issue
  - Is the CPU or GPU overclocked?   Have not changed it.
  - Is the Main memory of the CPU or GPU undervolted? Don't know??

**Comment by borzaka** [comment]
Than compiling is not your thing. Download the precompiled version from the [releases](https://github.com/fireice-uk/xmr-stak/releases): xmr-stak-win64.zip

**Comment by tinsami1** [comment]
Just run xmr-stak.exe  ... when it can't find the needed files (config.txt and pools.txt) it will ask you questions like what coin are you mining, which pool, and what is your wallet address.

**Comment by scryptkyddy** [comment]
Joe, the thing to do is run the exe, enter whatever, it will generate the pools, config, etc. files you can edit.

Is your 7??? card a 2gb? if so...

I'm mining with 2gb HD 6950, and found I get a performance boost by editing amd.txt as follows:

  { "index" : 0,
    "intensity" : 234, "worksize" : 6,
    "affine_to_cpu" : 7, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

that will tie your gpu to the 4th core,
and since you have an i7, suggest this for cpu.txt (using the first 3 cores)

    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },


depending on what coin you're mining, you might lose a line and get a bit of a better overall rate.

cheers,

Dave in Edmonton, Alberta

**Comment by scryptkyddy** [comment]
Joe, apparently we both have an issue where xmrstak only recognizes the first 384mb of video ram, 

I found this thread which suggests a driver that may be useful with your card from the Guru3d forum.
https://github.com/fireice-uk/xmr-stak/issues/1274

**Comment by joe1950** [comment]
FYI – I am still unable to get this to work!

**Comment by borzaka** [comment]
Just start the EXE, and it will ask questions like wallet, pool, etc.

**Comment by Simaex** [comment]
@joe1950 Please give all details of your system. What OS are you using, what drivers, please download what config files are generated (config.txt, pools.txt, cpu.txt, amd.txt). If no config files are generated please post all output that you miner generates during startup and give more details about what fail to work. At the moment it seem that you are trying to use the miner with 32 bit OS (it is NOT compatible) or your antivirus software block the miner.
