### ISSUE TITLE
Huge hashrate drop for Vega 64 after few hours of running (Cryptonight-Heavy)

### ISSUE THREAD

**Issue by s4m0k** [fireice-uk/xmr-stak#1406]
Hi, 

I got 1 Vega 64, with the following configuration:

- 2 threads with `intensity : 992, worksize: 8` each config.
- AMD Driver: Adrenaline 18.3.4

**Core GPU Clock**
- Frequency (Manual) : +5% -> 1617+ MHz
- Voltage Control (Manual) : 1000mV

**Memory Clock**
- Frequency (Manual): 1100 MHz
- Voltage Control(Manual): 1000mV

**Fan**
- Speed (Manual) : Range is from 2500 to 3500, Normally fan is spinning around 2100RPM

**Temperature**
- Average: 55degress
- Max: 60degrees
Power Limit
- +50%

This is hashing for `770+ HS` for each thread in sumokoin (cryptonight-heavy) as shown below:
<img width="606" alt="screen shot 2018-04-12 at 7 27 46 am" src="https://user-images.githubusercontent.com/3829536/38648301-12bb58c0-3e23-11e8-9633-8000e3a7bfa6.png">
However, at around 7 to 8 hours mark of running, it is consistently dropping to a huge -90%.  Each thread is only hashing to around `77 HS` screenshot shown below.  and as you can see the 10s average is empty and sometimes it takes longer than usual for this column to display a value. And the highest total value is `1555.8` which was recorded before the huge drop occured.

<img width="603" alt="screen shot 2018-04-12 at 7 11 42 am" src="https://user-images.githubusercontent.com/3829536/38647845-e66ea95e-3e20-11e8-8368-2f47feb14c55.png">

When this happen, what i needed to do is just to restart the miner and it will be back to normal again, then same thing will happen at around `7 to 8 hours` mark.  

I am running xmr-stak in windows 10.

**Comment by Spudz76** [comment]
Check windows event log for video driver crashes, acting as if the driver chokes and gets reloaded (which won't work well on existing OpenCL sessions / drops to powersave clocks or something)

**Comment by s4m0k** [comment]
I got some similar Events `Warning: Display driver amdkmdap stopped responding and has successfully recovered.` but the timing of these events doesn't match with the timing when the hasrate dropped.

**Comment by borzaka** [comment]
Are you using Blockchain driver? If so, this is a known bug. Try enable-disable your card, and rerun your overclock settings.

**Comment by s4m0k** [comment]
I'm not using Blockchain driver, I am using `Adrenaline 18.3.4`

**Comment by Spudz76** [comment]
I would run far, far away from anything AMD released that isn't 5 years old.  Basically that driver sucks, downgrade or await their next stab at it (which won't work either).
https://bitcointalk.org/index.php?topic=3207439.0

**Comment by besjamin** [comment]
What are your overdrive settings?

**Comment by s4m0k** [comment]
Thank you @Spudz76, I will try to downgrade and will update here the results.

**Comment by s4m0k** [comment]
Update!
- Miner has been running for over 9 hours now without hashrate drop

What I did was lower down the intensity to **972**
Each thread is hashing 759 +- less 20 HS than my previous config.
