### ISSUE TITLE
Why are Vega cards producing less h/s than RX5xxx and Nvidia cards?

### ISSUE THREAD

**Issue by besjamin** [fireice-uk/xmr-stak#1407]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Intel Celeron G3950
  - x6 AMD Vega 64 - Reference Cards

# Compile issues
  - Which OS do you use?
 Windows 10 Creators Update 1709 x64

# Issue with the execution
  - Do you compiled the miner by our own?
No

# Stability issue
  - Is the CPU or GPU overclocked? Yes

Hi there,

I am curious to find out why the AMD Vega cards perform poorly mining the cryptoheavy algorithm? I am struggling to get close to 1400 h/s on a single AMD Vega 64 whereas the AMD RX580 8GB perform nearly the same amount. I can confirm that a single RX580 8gb is hashing at 1120 h/s.

Also, the AMD 570-580 series are producing similar hash rates mining CN7 as they're with heavy. Why isn't the Vega like this?

If it helps, here are my configs.

Overdrive Overclocking Settings:
[General]
MainWindowLeft=658
MainWindowTop=292

[Profile_0]
Name=Vega64
GPU_P0=852;900;0
GPU_P1=991;900;0
GPU_P2=1084;900;0
GPU_P3=1138;900;0
GPU_P4=1150;900;0
GPU_P5=1202;900;0
GPU_P6=1212;905;0
GPU_P7=1408;925
Mem_P0=167;900;0
Mem_P1=500;900;0
Mem_P2=800;900;0
Mem_P3=1100;905
Fan_Min=3000
Fan_Max=4900
Fan_Target=5
Fan_Acoustic=2400
Power_Temp=85
Power_Target=0

Using the latest XMR-STAK 2.4.0, each Vega has this setting:

"gpu_threads_conf" : [

  { "index" : 0,
    "intensity" : 992, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 10,
    "comp_mode" : true
  },

Hashrate: 
I will be lucky to get 1400 h/s

**Comment by borzaka** [comment]
Because VEGA cards can handle 2 threads/card, and you are only using one. Try double your thread by duplicate the whole `{}` inside the `gpu_threads_conf`.

I'am not familiar with the new `strided_index` and `mem_chunk` options, but this was my default VEGA 64 config:
```
"gpu_threads_conf" : [
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1536, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],
```

But for VEGA-s, you can use more intensity. My VEGA 64 config after tweaking with a monitor attached to it;
```
"gpu_threads_conf" : [
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1800, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 1800, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],

```
I could use intensity 1932, but this card has a monitor on it and it would artifact with 1932.

**Comment by besjamin** [comment]
Sorry, forgot to mention I am using 2 threads...

I thought you would've known as a single thread it wouldn't be possible to achieve the hashrate that I mentioned above at 1400 h/s.

So the existing config I am using is:

> "gpu_threads_conf" : [
>   // gpu: gfx901 memory:3920
>   // compute units: 64
>   { "index" : 0,
>     "intensity" : 992, "worksize" : 8,
>     "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
>     "comp_mode" : true
>   },
>   { "index" : 0,
>     "intensity" : 992, "worksize" : 8,
>     "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
>     "comp_mode" : true
>   },
> ],

This is per card ^

**Comment by besjamin** [comment]
By the way, we should be achieving the relatively same h/s as the normal cryptonight algorithm, which was around 2000 h/s. Why is cnheavy different?

**Comment by hchan123** [comment]
Have you tried bumping up the intensity of both threads?

**Comment by borzaka** [comment]
You don't red my comment fully :(
992 intensity is very low for VEGA, try 1800 (monitor attached card), or 1932 no monitor attached card.

**Comment by besjamin** [comment]
Cryptoheavy won't mine with such high intensity though. Are you mining with 1800 double threads mining cryptoheavy algorithm? If so, what is your hash rate per Vega card?

**Comment by JerichoJones** [comment]
Cryptonight heavy uses a 4mb scratchpad which is double the 2mb scratchpad that cryptonight uses. It will be slower. You will not be able to use the same Intensity between the two.

**Comment by besjamin** [comment]
Thanks JerichoJones, love your work. 

So there is no way to achieve ~1900-2000 h/s on a single Vega mining Cryptoheavy?

**Comment by SigiSinatra** [comment]
@borzaka 
It's not possible to set intensity to 1800 if you are intending to mine Cryptonight Heavy.
I hope you know that there is a difference between v7 and heavy right ?
@JerichoJones why there is no hashdrop on rx 5xx, all those cards give the same hashrate on both v7 and heavy (with two threads)

**Comment by borzaka** [comment]
Sorry, I don't know the technical differences between CryptoNight and CryptoNight Heavy. I only know that CryptoNight and CryptoNightV7 existed, and they are different. Never heard of Heavy.
Sorry for misleading.
