### ISSUE TITLE
Compiling on Ubuntu 12.04

### ISSUE THREAD

**Issue by tinsami1** [fireice-uk/xmr-stak#1409]
Will I be able to compile the latest release using GCC 4?

One of my miners is still on Ubuntu 12.04, and that only has gcc 4.  I am not able to do an os upgrade at this time.

**Comment by Spudz76** [comment]
Very very hard requirement on GCC5 (or almost any compiler at C++ 11 level) maybe Clang-3.8 as I believe I've gotten that to work also.
Anything less just doesn't work, period.
Try backports?  Not sure, I've only tried antiquing back to 14 which worked once I got a better compiler on it.  May be impossible for 12.

**Comment by Spudz76** [comment]
Generally a dist-upgrade is about as much work as trying to massage a good compiler into ancient OS.

**Comment by tinsami1** [comment]
There's a backport available, not official though, and it will also upgrade the libstd library which I'd rather not do.

I'll take a good look at Clang.

Thanks!
