### ISSUE TITLE
How to run in background on Linux Server?

### ISSUE THREAD

**Issue by penguin806** [fireice-uk/xmr-stak#1411]
I set
"daemon_mode" = true
"output_file" = "/tmp/xmr-stak.log" 
in config.txt
and then input nohup ./xmr-stak & in the terminal, that works normally.
Are there any ways better  to run program in the background? I'm not familiar with Linux os.
Thank you.

**Comment by Spudz76** [comment]
Screen is probably the best.  You don't need `daemon_mode` on... all that does is shut off keyboard input (which you can still use with `screen`) and if you set the `output_file` it logs regardless of any other setting.

https://linode.com/docs/networking/ssh/using-gnu-screen-to-manage-persistent-terminal-sessions/

**Comment by lacivert** [comment]
you may try to make it as a service and run it as well

**Comment by ck-alpha** [comment]
you can also use tmux

**Comment by penguin806** [comment]
got it, thanks everyone.

**Comment by goldigger** [comment]
As the question asker said:

in **config.txt**, set:

**"daemon_mode" = true
"output_file" = "/tmp/xmr-stak.log"**

Then create this bash shell **xmr-launch.sh** script in your installation directory (I assume **/opt/xmr**)
Use the option --daemon or -d to launch in background. (Remember to **chmod +x xmr-launch.sh**)

**./xmr-launch.sh --daemon**

```
#!/bin/bash
case "$1" in
   -d|--daemon)
       /opt/xmr/xmr-stak < /dev/null &> /dev/null & disown
       exit 0
       ;;
   *)
       /opt/xmr/xmr-stak
       ;;
esac
```
