### ISSUE TITLE
Unable to use NVIDIA 350.12 driver

### ISSUE THREAD

**Issue by bymaximus** [fireice-uk/xmr-stak#1413]
I run this driver because it normally mines at speed of 400-450 GTX970, I compiled with both versions v141 v140 toolset, no errors but the miner cant find driver, its unsupported?

-------------------------------------------------------------------
[2018-04-12 19:03:04] : Mining coin: monero7
WARNING: NVIDIA Insufficient driver!
[2018-04-12 19:03:04] : WARNING: backend NVIDIA disabled.
[2018-04-12 19:03:05] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-04-12 19:03:05] : WARNING: backend AMD disabled.

**Comment by psychocrypt** [comment]
your environment is not correct configured. During the compile you used a
newer cuda library. Than during the execution an older driver is used or an
older runtime library. You need to set youur environment pathes correct.
Nornally this is done during the cuda installation.

**Comment by Spudz76** [comment]
Install CUDA 8...  The version of the compilation CUDA toolkit must not be newer than what the DRIVER version had included, which before 390-ish was not CUDA9 for sure.
I rip 486H/s on a GTX970 with CUDA8+390.30 on Ubuntu...
You *CAN* run Older CUDA Apps on newer CUDA equipped drivers... but not the other way around.

**Comment by Spudz76** [comment]
Whoops, that won't work either, the release notes for that driver say it includes CUDA 7
That driver won't work at all?  What did you get those rates from?  Must be something that supported CUDA 6.5 or 7 (this only supports minimum 7.5)

**Comment by bymaximus** [comment]
I currently run the old xmr-stak-nvidia, any newer driver drops speed hard

**Comment by bymaximus** [comment]
Ops, my bad, it was not the xmr-stak-nvidia but other miner (ccminer), I guess I got confusion after many build tries sorry. Im going to install cuda 8 and 390.30 driver to test build.

**Comment by bymaximus** [comment]
@Spudz76 sadly cant get more than 440H/s, even using 390.65 driver (I didnt found 390.30), using threads 8, blocks 52, do you have any tip to help me? Did you overclocked your gtx970?
