### ISSUE TITLE
CUDA illegal instruction

### ISSUE THREAD

**Issue by wlara** [fireice-uk/xmr-stak#1414]
Seeing this error with version 2.4.0. Happen evrytime after running for ~2-3 mins. Previously, used version 2.2.0 for months and never saw this issue:

ERROR:
-------
[CUDA] Error gpu 0: </Users/wl/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:365
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: [CUDA] Error: an illegal instruction was encountered
bash: line 1:   488 Abort trap: 6           ./bin/xmr-stak
-------------------------------------------------------------------
xmr-stak 2.4.2 e10e8e6

CONFIGURATION (using default values)
------------------
"gpu_threads_conf" :
[
  // gpu: GeForce GT 650M architecture: 30
  //      memory: 816/1023 MiB
  //      smx: 2
  { "index" : 0,
    "threads" : 56, "blocks" : 6,
    "bfactor" : 2, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by psychocrypt** [comment]
please compile into a clean build folder and post all cammandes used and
all output.

**Comment by wlara** [comment]
@psychocrypt Thanks for your quick response. Here is the complete build log:
[build-log.txt](https://github.com/fireice-uk/xmr-stak/files/1908087/build-log.txt)

And here the complete run log:
[run-log.txt](https://github.com/fireice-uk/xmr-stak/files/1908088/run-log.txt)

Let me know if you need any other details.

**Comment by wlara** [comment]
@psychocrypt It turns out that it was a power settings issue. Disabling the power saver did the trick. So far looking good after 2+ hrs without seeing the error. I'll come back here if I ever see the error again. Thanks for tour help.
