### ISSUE TITLE
Nvidia GPU Intensity control

### ISSUE THREAD

**Issue by YaWazowski** [fireice-uk/xmr-stak#1416]
Hi,

How can I control the intensity of an Nvidia GPU?

Changing threads and blocks does not give any results.

**Comment by psychocrypt** [comment]
intensity = Threads x Blocks. It must have an effect.

**Comment by psychocrypt** [comment]
It is no problem that the gpu is using 100% a gpu works a little bit
different than the cpu. Reduce the threads and maybe increase bfactor to 10
to get a better interactivity of your system.
