### ISSUE TITLE
monerohash.com pool - socket timeout and/or server not responding ...

### ISSUE THREAD

**Issue by guntire** [fireice-uk/xmr-stak#1421]
Hi, 

I have plenty of socket timeout, and/or server not responding ...  while mining the pool monerohash.com since it implementation of PoW and updating XMR-stak from v2.0.0 to 2.4.2 (same issue with all versions above 2.3.0) two days ago. No such issue with some other pools I tried.

pool: stratum+tcp://monerohash.com:3333

Do you thing it is the pool itself, I mean the server side only (monerohash pool), or it is the client xmr-stak version 2.3.0 and above or a combination of both?

Thanks for replying.

Sample # 1
2018-04-13 10:30:26] : Result accepted by the pool.
[2018-04-13 10:30:26] : Difficulty changed. Now: 15313.
[2018-04-13 10:30:26] : New block detected.
[2018-04-13 10:30:26] : Result accepted by the pool.
[2018-04-13 10:30:27] : Result accepted by the pool.
[2018-04-13 10:30:27] : Result accepted by the pool.
[2018-04-13 10:31:02] : Difficulty changed. Now: 26798.
[2018-04-13 10:31:02] : New block detected.
[2018-04-13 10:31:02] : All pools are dead. Idling...
[2018-04-13 10:31:03] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] CALL error: Timeout while waiting for a reply
 
Sample # 2
[2018-04-13 10:26:32] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] CALL error: Timeout while waiting for a reply
[2018-04-13 10:26:35] : Fast-connecting to stratum+tcp://monerohash.com:3333 pool ...
[2018-04-13 10:26:35] : Pool stratum+tcp://monerohash.com:3333 connected. Logging in...
[2018-04-13 10:26:40] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] Login error: your IP is banned
[2018-04-13 10:26:40] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] RECEIVE error: Une opÚration de blocage a ÚtÚ interrompue par un appel Ó WSACancelBlockingCall.
[2018-04-13 10:26:43] : Fast-connecting to stratum+tcp://monerohash.com:3333 pool ...
[2018-04-13 10:26:43] : Pool stratum+tcp://monerohash.com:3333 connected. Logging in...
[2018-04-13 10:26:43] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] Login error: your IP is banned
[2018-04-13 10:26:43] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] RECEIVE error: Une opÚration de blocage a ÚtÚ interrompue par un appel Ó WSACancelBlockingCall.
[2018-04-13 10:26:47] : Fast-connecting to stratum+tcp://monerohash.com:3333 pool ...
[2018-04-13 10:26:47] : Pool stratum+tcp://monerohash.com:3333 connected. Logging in...
[2018-04-13 10:26:49] : Pool logged in.
[2018-04-13 10:27:09] : All pools are dead. Idling...

Sample # 3

[2018-04-13 10:43:43] : Difficulty changed. Now: 8750.
[2018-04-13 10:43:43] : Pool logged in.
[2018-04-13 10:43:43] : New block detected.
[2018-04-13 10:43:43] : All pools are dead. Idling...
[2018-04-13 10:43:45] : SOCKET ERROR - [stratum+tcp://monerohash.com:3333] CALL error: Timeout while waiting for a reply
[2018-04-13 10:43:55] : Fast-connecting to stratum+tcp://monerohash.com:3333 pool ...
[2018-04-13 10:43:55] : Pool stratum+tcp://monerohash.com:3333 connected. Logging in...
[2018-04-13 10:44:05] : Difficulty changed. Now: 5000.
[2018-04-13 10:44:05] : Pool logged in.
[2018-04-13 10:44:05] : New block detected.
[2018-04-13 10:44:07] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID | 10s | 60s | 15m | ID | 10s | 60s | 15m |
| 0 | 52.1 | 14.4 | 35.2 | 1 | 43.7 | 11.8 | 29.5 |
| 2 | 45.6 | 12.7 | 30.8 | 3 | 32.2 | 9.0 | 21.8 |
| 4 | 37.5 | 10.2 | 25.4 | 5 | 40.8 | 11.1 | 27.7 |
| 6 | 44.5 | 12.7 | 30.0 |
Totals (CPU): 296.5 81.8 200.5 H/s
HASHRATE REPORT - AMD
| ID | 10s | 60s | 15m |
| 0 | 496.4 | 151.6 | 346.0 |
Totals (AMD): 496.4 151.6 346.0 H/s
Totals (ALL): 792.9 233.4 546.5 H/s
Highest: 817.3 H/s
.
.
.

# Basic information
  - Type of the CPU. AMD FX 8350
  - Type of the GPU (if you try to miner with the GPU). AMD HD 7950

# Compile issues
  - Which OS do you use? Windows 10 1709 16299.371
  ```
  add **all** commands you used and the **full** compile output here
  ```
mkdir build
cd build
set CMAKE_PREFIX_PATH=O:\CoinMining\Dev-v242\xmr-stak-dev\hwloc;O:\CoinMining\Dev-v242\xmr-stak-dev\libmicrohttpd;O:\CoinMining\Dev-v242\xmr-stak-dev\openssl
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake --build . --config Release --target install

  ```
  run `cmake -LA .` in the build folder and add the output here
  ```
cmake -LA
CMake Error: The current CMakeCache.txt directory O:/CoinMining/Dev-v242/xmr-stak-master/build/CMakeCache.txt is different than the directory o:/CoinMining/Dev4/xmr-stak-master/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source directory "O:/CoinMining/Dev-v242/xmr-stak-master/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_INSTALL_PREFIX:PATH=O:/CoinMining/Dev4/xmr-stak-master/build
CMAKE_LINKER:FILEPATH=S:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/link.exe
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_RC_COMPILER:FILEPATH=rc
CMAKE_RC_FLAGS:STRING=/DWIN32
CMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG
CMAKE_RC_FLAGS_MINSIZEREL:STRING=
CMAKE_RC_FLAGS_RELEASE:STRING=
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;60;61;62;70
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudart.lib
CUDA_CUDA_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cuda.lib
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=S:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin/nvcc.exe
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
CUDA_TOOLKIT_ROOT_DIR:PATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=9.0
CUDA_cublas_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cublas.lib
CUDA_cublas_device_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cublas_device.lib
CUDA_cudadevrt_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudadevrt.lib
CUDA_cudart_static_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudart_static.lib
CUDA_cufft_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cufft.lib
CUDA_cupti_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/extras/CUPTI/libx64/cupti.lib
CUDA_curand_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/curand.lib
CUDA_cusolver_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cusolver.lib
CUDA_cusparse_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cusparse.lib
CUDA_nppc_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppc.lib
CUDA_nppial_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppial.lib
CUDA_nppicc_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppicc.lib
CUDA_nppicom_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppicom.lib
CUDA_nppidei_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppidei.lib
CUDA_nppif_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppif.lib
CUDA_nppig_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppig.lib
CUDA_nppim_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppim.lib
CUDA_nppist_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppist.lib
CUDA_nppisu_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppisu.lib
CUDA_nppitc_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nppitc.lib
CUDA_npps_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/npps.lib
CUDA_nvcuvenc_LIBRARY:FILEPATH=CUDA_nvcuvenc_LIBRARY-NOTFOUND
CUDA_nvcuvid_LIBRARY:FILEPATH=S:/Program files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nvcuvid.lib
HWLOC:FILEPATH=O:/CoinMining/Dev4/xmr-stak-dev/hwloc/lib/libhwloc.lib
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=O:/CoinMining/Dev4/xmr-stak-dev/hwloc/include
LIB_EAY_DEBUG:FILEPATH=LIB_EAY_DEBUG-NOTFOUND
LIB_EAY_LIBRARY_DEBUG:FILEPATH=LIB_EAY_LIBRARY_DEBUG-NOTFOUND
LIB_EAY_RELEASE:FILEPATH=O:/CoinMining/Dev4/xmr-stak-dev/openssl/lib/libeay32.lib
MHTD:FILEPATH=O:/CoinMining/Dev4/xmr-stak-dev/libmicrohttpd/lib/libmicrohttpd.lib
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=O:/CoinMining/Dev4/xmr-stak-dev/libmicrohttpd/include
OPENSSL_INCLUDE_DIR:PATH=O:/CoinMining/Dev4/xmr-stak-dev/openssl/include
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=C:/Program Files (x86)/AMD APP SDK/3.0/include
OpenCL_LIBRARY:FILEPATH=C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib
OpenSSL_ENABLE:BOOL=ON
SSL_EAY_DEBUG:FILEPATH=SSL_EAY_DEBUG-NOTFOUND
SSL_EAY_LIBRARY_DEBUG:FILEPATH=SSL_EAY_LIBRARY_DEBUG-NOTFOUND
SSL_EAY_RELEASE:FILEPATH=O:/CoinMining/Dev4/xmr-stak-dev/openssl/lib/ssleay32.lib
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```
Version: xmr-stak/2.4.2/e10e8e67/unknown/win/nvidia-amd-cpu/aeon-cryptonight-monero/0

# AMD OpenCl issue
  ```
  run `clinfo` and add the output here
  ```
clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (2527.10)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices

  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon HD 7900 Series
  Device Topology:                               PCI[ B#1, D#0, F#0 ]
  Max compute units:                             28
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           900Mhz
  Address bits:                                  32
  Max memory allocation:                         2509871513
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            3221225472
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   00007FF9B7D94AB0
  Name:                                          Tahiti
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2527.10
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2527.10)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event cl_amd_liquid_flash

  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     1002h
  Board name:
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           1024
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   2
  Preferred vector width float:                  8
  Preferred vector width double:                 4
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           4335Mhz
  Address bits:                                  64
  Max memory allocation:                         4280635392
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            8192
  Max image 2D height:                           8192
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   4096
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            17122541568
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Global
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          4280635392
  Max global variable size:                      1879048192
  Max global variable preferred total size:      1879048192
  Max read/write image args:                     64
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     1
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    236
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   00007FF9B7D94AB0
  Name:                                          AMD FX(tm)-8350 Eight-Core Processor
  Vendor:                                        AuthenticAMD
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2527.10 (sse2,avx,fma4)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2527.10)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event

# Stability issue
  - Is the CPU or GPU overclocked? No for both
  - Is the Main memory of the CPU or GPU undervolted? No for both

**Comment by Simaex** [comment]
I have something similar with nanopool. After the algo change I use to have 95-98% of good shares, before I rarely have less then 100% good. It seems that it is something to be looked into. I did not report it myself cause I was not sure it is not some random network error and I do not know how to address the issue.

**Comment by sew3521** [comment]
Inside of Pools.txt do you have the currency set to monero7?  I know there have been a few issues where people left the currency as cryptonight and it caused issues with how the program communicated with the servers.

**Comment by guntire** [comment]
Thanks for answering.

Yes I did; "currency" : "monero7"
I using the same pools.txt file and pointing to at supportXMR.com works just fine.

Here me pool.txt fconfig file :

/*
* pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
* wallet_address  - Your wallet, or pool login.
* rig_id          - Rig identifier for pool-side statistics (needs pool support).
* pool_password   - Can be empty in most cases or "x".
* use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
* use_tls         - This option will make us connect using Transport Layer Security.
* tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
* pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
*
* We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
*/

"pool_list" :
[
                {"pool_address" : "stratum+tcp://monerohash.com:3333", "wallet_address" : "49YNYt2PtXG2p5gqvL4gppegLvX4kjUse99mxxymUpnqF7JGjTnVUChnjvilfMBGXEtJ6FHX1C17NuuWzoKxFwKKZ3BZt","rig_id" : "", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
* Currency to mine. Supported values:
*
*    aeon7 (use this for Aeon's new PoW)
*    cryptonight (try this if your coin is not listed)
*    cryptonight_lite
*    edollar
*    electroneum
*    graft
*    intense
*    karbo
*    monero7 (use this for Monero's new PoW)
*    sumokoin
*
*/

"currency" : "monero7",


________________________________
De : sew3521 <notifications@github.com>
Envoyé : Tuesday, April 17, 2018 5:50:35 PM
À : fireice-uk/xmr-stak
Cc : Gilles Gonthier; Author
Objet : Re: [fireice-uk/xmr-stak] monerohash.com pool - socket timeout and/or server not responding ... (#1421)


Inside of Pools.txt do you have the currency set to monero7? I know there have been a few issues where people left the currency as cryptonight and it caused issues with how the program communicated with the servers.

**Comment by guntire** [comment]
Yes, I did try it, v2.4.3 I still have problems on a machine running AMD GPU and AMD processor when mining again monerohash.com. However, no problems at all minng at supportXMR.com. I have to run more tests, then, I will provide feedback...
