### ISSUE TITLE
html report not accessible on windows 10 

### ISSUE THREAD

**Issue by gitmanfa** [fireice-uk/xmr-stak#1423]
Dear ,
              when i try to access html reports i can't access ? :( 
i have set the "httpd_port" : 3333, 

when i acess 192.168.1.2:3333/h ,chrome show not accesible :(

please help anyone

**Comment by psychocrypt** [comment]
why `/h` remove it and it will work

**Comment by gitmanfa** [comment]
already tried without .h same error not accessible

**Comment by psychocrypt** [comment]
you have a comma in your IP but it must be a dot. Is your IP correct?

**Comment by gitmanfa** [comment]
sorry but it was typo mistake , problem still there..

**Comment by psychocrypt** [comment]
maybe your firewall. Try to connect from the miner PC itself. use 127.0.0.1
:3333

**Comment by gitmanfa** [comment]
same problem on miner pc

This site can’t be reached
127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED


also restart the PC :(

**Comment by psychocrypt** [comment]
Do you compiled the miner by our own?

**Comment by gitmanfa** [comment]
nope downloaded from https://github.com/fireice-uk/xmr-stak/releases

**Comment by landergate** [comment]
Can't reproduce.
Fetching html-reports on the same OS version.

You're sure `httpd_port` param in config.txt is not 0?

**Comment by gitmanfa** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1910347/config.txt)

here is config file

**Comment by gitmanfa** [comment]
when i start on my laptop it work fines , but not working on my Miner PC ? please help

**Comment by psychocrypt** [comment]
That is an issue with your firewall. Check that the port is open.

**Comment by gitmanfa** [comment]
i have allow the port still same error , chrome showing ERR Connection refused

**Comment by gitmanfa** [comment]
ok found a solution i start via shell .bat it does load html report , without .bat it run fine please fix this issuse Thanks for wonderfull software

**Comment by psychocrypt** [comment]
Where do you downloaded the miner we have not `*.bat` file in our shiped
precompiled banaries. If you like to keep the miner from someone else
please open an issue where you downloaded the miner.
You can find the original miner
https://github.com/fireice-uk/xmr-stak/releases
Only because users use the original wth 2% dev fee we are able to help you.

**Comment by gitmanfa** [comment]
you'r correct there is not .bat file in originally shipped version , i have manually created start.bat 

like this added on shell:startup of windows 10

xmr-stak.exe -O xmr-eu1somepolol.org:4433 -u YOUR_XMR_ADDRESS.YOUR_WORKER/YOUR_EMAIL --currency monero7 -i 0 -p "" -r ""

**Comment by landergate** [comment]
@gitmanfa
Any reason for using `-i 0`?

**Comment by gitmanfa** [comment]
just copy paste from internet , i don't even know what this function do ..... 🗡

**Comment by landergate** [comment]
@gitmanfa
Try to run `xmr-stak.exe --help`. It's explains that `-i` defining reporting http port.

**Comment by gitmanfa** [comment]
oh my lord , so this was causing problem 👍

**Comment by Spudz76** [comment]
LOL documentation.

Who has time?
