### ISSUE TITLE
 NVIDIA Invalid Result GPU ID 1 (Version 2.4.2 with Stellite or Monero )

### ISSUE THREAD

**Issue by TerpFan** [fireice-uk/xmr-stak#1424]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. Intel Celeron
  - Type of the GPU (if you try to miner with the GPU). NVIDIA 1060 (6 GPU Rig)

# Compile issues
  - Which OS do you use? Windows 10
  ```

Getting this error "NVIDIA Invalid Result GPU ID 1" with the new version. 
Searched the error and found this was a problem you fixed with Sumokin. 
Typically averages 81% good results on GPU 1. No errors on any other cards. 
I'm kind of new to mining and thought I might have had a bad card, riser, etc.
But it is just the GPU 1 slot. Is this the same issue as was with Sumo? 
Thanks in advance for any help you may provide!

**Comment by perestoronin** [comment]
Have same errors with all AMD Vega RX 56 cards on system with Ryzen 7 1800x:

> RESULT REPORT
> Difficulty       : 120001
> Good results     : 40 / 49 (81.6 %)
> Avg result time  : 53.6 sec
> Pool-side hashes : 4800040
> 
> Top 10 best results found:
> |  0 |         11770105 |  1 |          1659742 |
> |  2 |          1444604 |  3 |          1333809 |
> |  4 |          1101328 |  5 |           981691 |
> |  6 |           626344 |  7 |           583111 |
> |  8 |           437336 |  9 |           400346 |
> 
> Error details:
> | Count | Error text                       | Last seen           |
> |     5 | AMD Invalid Result GPU ID 1      | 2018-04-15 00:50:27 |
> |     3 | AMD Invalid Result GPU ID 0      | 2018-04-15 00:50:11 |
> |     1 | Block expired                    | 2018-04-15 00:36:52 |

**Comment by JerichoJones** [comment]
@TerpFan Are you running stock closks? If not, try setting the problematic card to stock clocks to see if the issue is resolved. Then you can try increasing clocks.
