### ISSUE TITLE
Install error on Centos

### ISSUE THREAD

**Issue by ahmedmurad** [fireice-uk/xmr-stak#1429]
I compiled/installed xmr-stak-cpu on a number of CentOS machines without issue, the setup guide is somewhat similar to the newer xmr-stak guide.

I am now trying to compile/install xmr-stak using the guide here: https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md as a replacement, but after 'cmake3 ..' I get the below error:

----------------------
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:195 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/build/CMakeFiles/CMakeOutput.log".
[root@localhost build]# cmake3 ..
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:195 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/build/CMakeFiles/CMakeOutput.log".
----------------------

I am mining Monero with CPU miners and have no need for GPU, does anyone know where I am going wrong?

Many thanks.

**Comment by psychocrypt** [comment]
As the error message said add the option `-DCUDA_ENABLE=OFF` to the cmake
command as option.
Please read the documentation
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md#build-system

**Comment by ahmedmurad** [comment]
@psychocrypt Thanks a lot, I misunderstood at the time but after your comment I understand and have corrected the problem, thank again!
