### ISSUE TITLE
AMD GPU some cards low hashrate CentOS 7.3

### ISSUE THREAD

**Issue by SveguS80** [fireice-uk/xmr-stak#1431]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Motherboard ASUS B250 mining expert
  - Centos 7.3 64 bit
  - CPU Skylake 
  - 4GB RAM
  - AMDGPUPro driver 17.40
  - AMD-APP-SDKInstaller-v3.0.130.136
  - Card 0-4 AMD RX 570 4GB
  - Card 5 AMD RX 570 8GB
  
  - ./xmr-stak --version-long
	Version: xmr-stak/2.4.2/e10e8e6/master/lin/amd-cpu/aeon-cryptonight-monero/20
	
# Background and Question
  Started out mining on this rig using Windows 10. After the latest windows update (early April) something happened and I have not managed to get the system to work in a stable state. So decided to give Centos another shot. So far I am VERY happy with stability. Just performance that is not up to scratch. The fact that some cards are not being "worked" to the max would that be something i can alter in XMR-STAK?, or is it more likely to be a driver issue?
  
  I know there are no "offically known" Linux drivers for the Asus B250 MB.

# AMD OpenCl infornation

  ```
  run `clinfo` and add the output here
  See attached clinfo.txt
[clinfo.txt](https://github.com/fireice-uk/xmr-stak/files/1912740/clinfo.txt)
  ```  

# Performace issue

  - Card 0 and Card 5 display similar kind of issues. They are not performing at full potential. I have run the same cards in the same setup in Windows 10 with latest AMD drivers and they (Card 0 and 5) performed the same as the other cards.
  
  - Hashreport
  
	  HASHRATE REPORT - CPU
	| ID |    10s |    60s |    15m |
	|  0 |   53.5 |   (na) |   (na) |
	Totals (CPU):    53.5    0.0    0.0 H/s
	-----------------------------------------------------------------
	HASHRATE REPORT - AMD
	| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
	|  0 |  376.5 |   (na) |   (na) |  1 |  364.3 |   (na) |   (na) |
	|  2 |  576.0 |   (na) |   (na) |  3 |  577.5 |   (na) |   (na) |
	|  4 |  578.2 |   (na) |   (na) |  5 |  578.7 |   (na) |   (na) |
	Totals (AMD):  3051.2    0.0    0.0 H/s
	-----------------------------------------------------------------
	Totals (ALL):   3104.8    0.0    0.0 H/s
	Highest:  3107.0 H/s

  
  - Startup Log
  
	-------------------------------------------------------------------
	[2018-04-15 15:11:49] : Mining coin: monero7
	[2018-04-15 15:11:49] : Compiling code and initializing GPUs. This will take a while...
	[2018-04-15 15:11:49] : Device 0 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 0 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Device 1 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 1 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Device 2 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 2 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Device 3 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 3 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Device 4 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 4 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Device 5 work size 8 / 32.
	[2018-04-15 15:11:49] : OpenCL device 5 - Load precompiled cod from file /root/.openclcache/b811c23eba25a910992cf0fd730e0427a581b63fe7a05ad40faab24a19e4bf22.openclbin
	[2018-04-15 15:11:49] : Starting AMD GPU thread 0, no affinity.
	[2018-04-15 15:11:49] : Starting AMD GPU thread 1, no affinity.
	[2018-04-15 15:11:49] : Starting AMD GPU thread 2, no affinity.
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : Starting AMD GPU thread 3, no affinity.
	[2018-04-15 15:11:49] : Starting AMD GPU thread 4, no affinity.
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : Starting AMD GPU thread 5, no affinity.
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed
	[2018-04-15 15:11:49] : Starting 1x thread, affinity: 0.
	[2018-04-15 15:11:49] : hwloc: memory pinned
	[2018-04-15 15:11:49] : Fast-connecting to xmrpool.eu:5555 pool ...
	[2018-04-15 15:11:49] : MEMORY ALLOC FAILED: mmap failed

**Comment by psychocrypt** [comment]
Do you ise any riser extender? It could also be that you have a pci-e
switch on your mainboard which is not fully supported by centos. Do you
tried a debian based distribution?

**Comment by SveguS80** [comment]
I do use riser extenders, they worked fine for me in Windows though. I have not tested with Debian based yet. Interesting that pci-e switch might not be supported there. Which debian dist would you recommend for easy of use and stability with xmr-stak, and AMD drivers :) they are not exactly known for working well together :)

**Comment by psychocrypt** [comment]
I think ubuntu is supported best.

**Comment by SveguS80** [comment]
Thank you! Will have to give that a go, will report back with findings.

**Comment by Spudz76** [comment]
Ubuntu 16 !!!
Not the latest, it's pretty unworkable also.

**Comment by Spudz76** [comment]
I have not tried it and got the opposite impression from reading.
I did try Debian Stretch (same basis) and none of the AMDGPU-Pro stuff would work properly
Nvidia works on anything/everything.
You do have to adjust kernel revision (backports) manually on most of them to get amd+nvidia working together, maybe the latest just has a working kernel by default.  I run 4.13 on all of mine it seems to work best, 4.10 had worse CPU mining speeds but about equal on GPUs.
They never work together as far as having both accessible via Xorg for tweak apps (nvidia-settings, overdrive control) as their drm/dri/glx libs fight each other.

**Comment by SveguS80** [comment]
Latest 16.04.03 Ubuntu server with HWE runs on the 4.13 kernel so should be ok

**Comment by Spudz76** [comment]
Yes, that is exactly the distro and kernel I use for best results.

**Comment by Spudz76** [comment]
Also with riser extensions most of mine won't even pass POST tests unless I manually drop the PCIe speed maximums.  I use gen1 unless that doesn't work and then I go gen2 if necessary to make a specific card work (Fiji / Fury Nano don't like gen1) but gen3 is right out.
Linux will kick the gen-lock from BIOS/CMOS setup back up to gen3 as it boots unless you use driver module options to disable it from "helping you out".
Windows probably doesn't even bother trying to override what BIOS had setup for PCIe.

**Comment by SveguS80** [comment]
Spudz76:

I have not had any issues with the cards working at all so far.

May I ask what combination of driver versions you have used when managing to get AMD and NVIDIA cards to coexist? Using debian with kernel 4.13?

**Comment by SveguS80** [comment]
With only 1 card attached to the 1st PCIE slot. Still getting the same low Hashrate on card 0.

With all cards attached: I have various output.

  - UBUNTU 16.04.04, AMDGPUPRO 17.30
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  124.2 |   (na) |   (na) |  1 |  562.6 |   (na) |   (na) |
|  2 |  578.3 |   (na) |   (na) |  3 |  578.3 |   (na) |   (na) |
|  4 |  577.5 |   (na) |   (na) |  5 |  577.9 |   (na) |   (na) |
Totals (AMD):  2998.8    0.0    0.0 H/s
Totals (ALL):   3046.2    0.0    0.0 H/s
Highest:  3048.5 H/s
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   (na) |  124.3 |   (na) |  1 |  563.0 |  561.9 |   (na) |
|  2 |  578.6 |  577.5 |   (na) |  3 |  578.4 |  577.1 |   (na) |
|  4 |  573.1 |  575.3 |   (na) |  5 |  578.5 |  578.2 |   (na) |
Totals (AMD):  2871.6 2994.3    0.0 H/s

Sometimes card 0 is working sometimes not.

I Stopped the Ubuntu experiment and plugged in the Centos HDD again.

  - CentOS 7.3  AMDGPUPRO 17.40
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  374.9 |   (na) |   (na) |  1 |  563.0 |   (na) |   (na) |
|  2 |  573.1 |   (na) |   (na) |  3 |  578.0 |   (na) |   (na) |
|  4 |  577.7 |   (na) |   (na) |  5 |  579.0 |   (na) |   (na) |
Totals (AMD):  3245.7    0.0    0.0 H/s

And the hasrates are better on card one although not working at "normal" speed.

Result so far:

Centos seems to have an issue with the motherboard not able to switch between discreet graphics and pcie as the screen goes dead as soon as CentOS boots up. But the hashrates are better. Likely because of using AMD 17.40 drivers.

Ubuntu does produce the screen output on the monitor so the PCIE switching does not seem to be a problem. But the hashrates on several cards are unexpected.

Any ideas on where to troubleshoot this next?

**Comment by SveguS80** [comment]
Im going to put this on ice for a while, my Centos rig is running stable without overheating.

I've managed to put my nvidia cards in my desktop and run them  there instead of trying to make the coexists. Thanks for all the help. I will put this as fixed for now.

@ryan-ronnander 
Your suggestion sounds very promising, i have not setup any Fedora builds yet and have no spare time to educate myself at the moment :) but that will be my next step!

@psychocrypt 
A big thanks to XMR-STAK team for a smooth build process for both amd and nvidia! And responding on the forum, the dev fee stays :)
