### ISSUE TITLE
CALL error : Time out while waiting for a reply

### ISSUE THREAD

**Issue by LeGqston** [fireice-uk/xmr-stak#1433]
Hello,
i'm mining with xmr-stak-v2.4.2-cuda8 for 3 or 4 days now on SMOS and i can't get it to run stable, it crashed every 90 to 120mnts for like 30 to 90mnts, i have to reboot the miner manually if i don't want to loose 30 to 90mnts of mining ...

here is what it shows when it craches : 

![sans titre](https://user-images.githubusercontent.com/38410074/38784877-c5462824-4118-11e8-9f3d-5711b5a8d2df.png)

can you tell me what's wrong ?
thank you

# Basic information
  - Type of the GPU : 1060 6Gb ( Overclock +100 Core, + 600 Memory )
  - SMOS xmr-stak-v2.4.2-cuda8
  - --currency stellite -o communitypool.stellite.cash:6699 -u wallet -p x

**Comment by psychocrypt** [comment]
Where do you downloaded the miner. Do you compiled the miner by your own?
Please run `xmr-stak -V`

**Comment by LeGqston** [comment]
no i didn't do any of this, simplemining.net does it, it's so i don't think i can run *xmr-stak -V*
i can run *h* *r* for hrate and the result

**Comment by psychocrypt** [comment]
run xmr-stak-v2.4.2-cuda8 -V   (attention capital letter V)

**Comment by psychocrypt** [comment]
could you please post all output from the miner after the start. The output
of the first minute. Please do not remove any output each line counts.

**Comment by hassanhash** [comment]
psychocrypt, thanks for all the great work. I have a question, just started mining on smos with 11x 1080's. Linked my monero wallet and synced it (remote node-to speed up sync). Im using xmr-stak-v2.4.2-cuda8 -V, but after 14 hours dont see any indication of payout (zero balance in wallet).
So how often should I expect payout? how do you monitor how much your earnning etc? Right now it feels like I should just have faith lol, can you help, sorry to be so long....thanks

**Comment by hassanhash** [comment]
![image](https://user-images.githubusercontent.com/38433307/38817908-505100ba-4191-11e8-8bb7-9ddc75619419.png)

**Comment by psychocrypt** [comment]
You do not use our miner you can find our miner on
https://github.com/fireice-uk/xmr-stak/releases

Please open an ticket with your questions on the website simplemining.

If you downloaded our miner and have questions feel free to open an issue.

**Comment by psychocrypt** [comment]
This is an issue with a forked miner.

**Comment by LeGqston** [comment]
xmr-stak-v2.4.2-cuda8 is not your miner ?

**Comment by psychocrypt** [comment]
No if you not downloaded the miner from the link I posted it is a fork
and/or compiled from someone else. This mean we do not know which changes
are included and it is a blackbox for us. Therefore it is impossible to
help you.
You should use our miner or if you like to stay with the other miner you
should open a ticket where you downloaded the miner.
