### ISSUE TITLE
Simple miner os payout question

### ISSUE THREAD

**Issue by hassanhash** [fireice-uk/xmr-stak#1436]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by hassanhash** [comment]
psychocrypt, thanks for all the great work. I have a question, just started mining on smos with 11x 1080's. Linked my monero wallet (downloaded it from getmonero.com) and synced it (remote node-to speed up sync). Im using xmr-stak-v2.4.2-cuda8 -V, but after 14 hours dont see any indication of payout (zero balance in wallet).
So how often should I expect payout? how do you monitor how much your earnning etc? Right now it feels like I should just have faith lol, can you help, sorry to be so long....will post pic of my miner settings I have 3 rigs running all on the same 'miner options' (pool-wallet is all the same on all 3 rigs)...sorry for long question, and thanks if you get time.

**Comment by hassanhash** [comment]
![image](https://user-images.githubusercontent.com/38433307/38819703-02cce522-4194-11e8-9379-12bad09dfaf7.png)

**Comment by hassanhash** [comment]
![image](https://user-images.githubusercontent.com/38433307/38819756-29f0b836-4194-11e8-8170-8ef4bff8af61.png)

**Comment by hassanhash** [comment]
![image](https://user-images.githubusercontent.com/38433307/38819779-3b1cb79a-4194-11e8-8f56-2645af5ceef7.png)

**Comment by psychocrypt** [comment]
You do not use our miner you can find our miner on https://github.com/fireice-uk/xmr-stak/releases Please open an ticket with your questions on the website simplemining. If you downloaded our miner and have questions feel free to open an issue.
