### ISSUE TITLE
SOCKET ERROR

### ISSUE THREAD

**Issue by Simaex** [fireice-uk/xmr-stak#1439]
During execution I am repeatedly receiving the next errors that results in unsteady performance.

[2018-04-14 23:33:20] : Background-connect to xmr.nanopool.org:14433 pool ...
[2018-04-14 23:33:41] : SOCKET ERROR - [xmr.nanopool.org:14433] 4024:error:02002
74C:system library:connect:reason(1868):.\crypto\bio\bss_conn.c:246:host=xmr.nan
opool.org:14433
4024:error:20073067:BIO routines:CONN_STATE:connect error:.\crypto\bio\bss_conn.
c:249:

Please advise how to troubleshoot.

CPU Celeron G3930
GPU HD6990 - 4x
Windows 10 Pro (1709) with updates disabled
AMD 14.4 driver
I am using 2.4.1 737383a5 miner downloaded from github
CPU and GPU are not downvolted or overclocked

**Comment by Simaex** [comment]
I downloaded 2.4.2 and give it a run. Will update tomorrow.

**Comment by sew3521** [comment]
I am having socket issues with 2.4.2 and 2.4.1.  I keep getting RECEIVE error: socket closed and RECEIVE error: An existing connection was forcibly closed by the remote host.
I have tried on two different computers on two different networks.
I am able to use XMRig without issue.

**Comment by turtlepile** [comment]
same problem here. 
what's the solution? 

thanks.

**Comment by Simaex** [comment]
2.4.2 did not cure the problem for me.

**Comment by turtlepile** [comment]
@fireice-uk  can you help please?

**Comment by sew3521** [comment]
What currency do you have listed in the pools.txt file?

**Comment by psychocrypt** [comment]
please check if #1449 os solving the issue

**Comment by fireice-uk** [comment]
This is unlikely to be solved  by #1449 symptom of that bug would be an intermittent crash. @Simaex Can you please post pools.txt

**Comment by Simaex** [comment]
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1923297/pools.txt)

This is my pools.txt
The last running period I get a different error - socket closed but no additional info.

**Comment by turtlepile** [comment]
SOCKET ERROR - [45.32.171.89:4444] CONNECT error: No connection could be made because the target machine actively refused it.

**Comment by Simaex** [comment]
Upgraded to the latest version 2.4.3. The issue is not completely gone but stability and resulting pool-side hash rate is much better. Average +10% gain 
`[2018-04-20 04:37:38] : Fast-connecting to cryptonightv7.eu.nicehash.com:33355 pool ...
[2018-04-20 04:37:38] : Fast-connecting to cryptonightv7.usa.nicehash.com:33355 pool ...
[2018-04-20 04:37:39] : SOCKET ERROR - [xmr-eu1.nanopool.org:14433] CALL error: Timeout while waiting for a reply
[2018-04-20 04:37:51] : SOCKET ERROR - [cryptonightv7.usa.nicehash.com:33355] 3984:error:2006A066:BIO routines:BIO_get_host_ip:bad hostname
 lookup:.\crypto\bio\b_sock.c:146:host=cryptonightv7.usa.nicehash.com

[2018-04-20 04:37:51] : SOCKET ERROR - [cryptonightv7.eu.nicehash.com:33355] 1948:error:2006A066:BIO routines:BIO_get_host_ip:bad hostname
lookup:.\crypto\bio\b_sock.c:146:host=cryptonightv7.eu.nicehash.com

[2018-04-20 04:37:51] : All pools are dead. Idling...
[2018-04-20 04:38:07] : Fast-connecting to xmr-eu1.nanopool.org:14433 pool ...`

**Comment by turtlepile** [comment]
should i change my pool?

**Comment by JerichoJones** [comment]
@Simaex That looks like a DNS lookup failure.

**Comment by KnoAll** [comment]
I"m seeing a similar error connectiong to nanopool.
`[xmr-us-west1.nanopool.org:14433] 123145377673288:error:02002033:system library:connect:Network is unreachable:bss_conn.c:246:host=xmr-us-west1.nanopool.org:14433 123145377673288:error:20073067:BIO routines:CONN_STATE:connect error:bss_conn.c:249:`

whereas the xmr-us-east1.nanopool.org works better but with greater latency (for me on the west coast)
