### ISSUE TITLE
UAC notification

### ISSUE THREAD

**Issue by servelat1** [fireice-uk/xmr-stak#1441]
Is any option to disable UAC notification, and manually add rights for lock page in memory how it been with older version of xmr-stak?

**Comment by Spudz76** [comment]
You have never tried `xmr-stak --help`
Please do.

**Comment by Spudz76** [comment]
https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/cli/cli-miner.cpp#L73

**Comment by servelat1** [comment]
--noUAC disable notification and force to use slow memory, although user have rights for this
