### ISSUE TITLE
Is there no XMR-STAK-CPU anymore?

### ISSUE THREAD

**Issue by cat007mine** [fireice-uk/xmr-stak#1443]
Hi all,
There is no XMR-STAK-CPU anymore? Only xmr-stak for GPU?

**Comment by psychocrypt** [comment]
xmr-stak can be used as cpu only miner. Please run xmr-stak --help and
check our documentation

**Comment by phubbard91** [comment]
What arguments need to be passed to the main function in cli-miner.cpp in order to run as cpu-only?

**Comment by psychocrypt** [comment]
If you compile the miner you can disable gpus with `-DCUDA_ENABLE=OFF
-DOpenCL_ENABLE=OFF`
If you use a precompiled build or compiled with gpu please run `xmr-stak
--help` to see all options

**Comment by Spudz76** [comment]
@phubbard91 Everything comes from the configuration struct you would inject the settings you want and then call functions.  They read from the config struct in global memory rather than having all the options passed as arguments.

I think that's what you were asking?

**Comment by Spudz76** [comment]
@cat007mine `xmr-stak --noAMD --noNVIDIA` which only leaves CPU enabled?

**Comment by phubbard91** [comment]
Is there any way to bypass the initial configuration? Could I do this by just filling in all of the necessary fields in params.hpp?

**Comment by phubbard91** [comment]
Essentially, what I want to know is would there be any way to run the miner with no user input?

**Comment by Spudz76** [comment]
@phubbard91 I see, you would just edit the defaults here
https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/params.hpp#L59

**Comment by psychocrypt** [comment]
Start the miner once and fill out all fields. The next time the configs
will be used and there is no interaction needed anymore.
An other way is to use the command line paramater to set the pool and all
other options asked at the beginning if the configs are not available.

**Comment by phubbard91** [comment]
@psychocrypt excuse my ignorance, but what would the input for the second option look like? I am calling the main function from an external C call. what should I give it for the integer argc and the string argv? I know my use case is super specific so I appreciate your time. It's probably not really within the scope of this forum.

**Comment by phubbard91** [comment]
@Spudz76 is it possible to manually add the config.txt and other config files before running? I have tried this, but the miner still wants to run the initial configuration setup (do_guided_config())

**Comment by cat007mine** [comment]
Forgive my ignorance - but I'm pretty novice with linux :)
Running Ubuntu server 17.10
I'm following steps for Ubuntu as per here:

https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md

Here's the cmake output log:

[CMakeOutput.log](https://github.com/fireice-uk/xmr-stak/files/1921930/CMakeOutput.log)

I'm then not sure how I would actually run xmr-stak. The build folder only has a CMakeCache.txt file and a CMakeFiles directory (where the output log was retrieved from). When I type "make install" I get this:
make: *** No rule to make target 'install'.  Stop.
I was previously using this guide which worked a treat:

https://www.cryptocurrencyfreak.com/2017/08/22/monero-mining-xmr-stak-cpu-ubuntu-16-04/

If anyone can help me out that would be great!

Thanks in advance.

**Comment by phubbard91** [comment]
@Spudz76 Thanks for all your help. Are the config files written to the same directory as the template files?

**Comment by Spudz76** [comment]
@phubbard yes placing appropriate named files (`config.txt` / `cpu.txt` / `pools.txt`) in the current directory before running `xmr-stak` should result in no configuration wizard.  Unless they are old-format configs they do change now and then for features or improvement and that may trigger "invalid" and therefore wizard asking questions.

**Comment by Spudz76** [comment]
@cat007mine there should be a `bin` subdir in your build dir and you need the `*.so` and `xmr-stak` files from there.  I usually keep my running copy in `/opt/xmr-stak/` so to "install":
```
mkdir /opt/xmr-stak/
cp bin/*.so bin/xmr-stak /opt/xmr-stak/
cd /opt/xmr-stak/
./xmr-stak
```
