### ISSUE TITLE
Miner changes to cryptonight v7 automatically even when setting currency to to "cryptonight"

### ISSUE THREAD

**Issue by randing89** [fireice-uk/xmr-stak#1453]
The currency is set to "cryptonight". But after few hours mining, it will switch to cryptonight v7 automatically.
Here is the log from the pool.
![image](https://user-images.githubusercontent.com/640557/38917767-8de7937a-42a0-11e8-8959-3ab8ac8257a2.png)

The algorithm will go back to "cryptonight" after restarting the miner.

**Comment by psychocrypt** [comment]
Sry thats a bug in our code where we handle the forks. It is fixed in the
current dev branch.
Please recompile with the dev branch code. We will try to release a fixed
version today or tomorrow.

**Comment by randing89** [comment]
@psychocrypt Can you please have a review of my PR here: https://github.com/fireice-uk/xmr-stak/pull/1426
I hope we can get included in the next release. We are forking next week.
Thanks!
