### ISSUE TITLE
CUDA ERROR <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>366

### ISSUE THREAD

**Issue by klove007** [fireice-uk/xmr-stak#1455]
windows 10, stock settings on GPU's, cryptonight v7 - tried reducing threads, running a mix of 1060 3gb, 1060 6gb, and one 1080ti

"gpu_threads_conf" :
[
// gpu: GeForce GTX 1080 Ti architecture: 61
// memory: 9309/11264 MiB
// smx: 28
{ "index" : 0,
"threads" : 54, "blocks" : 84,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 1,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 2,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 3,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 4,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 6GB architecture: 61
// memory: 5082/6144 MiB
// smx: 10
{ "index" : 5,
"threads" : 16, "blocks" : 30,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 6,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 6GB architecture: 61
// memory: 5082/6144 MiB
// smx: 10
{ "index" : 7,
"threads" : 16, "blocks" : 30,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 6GB architecture: 61
// memory: 5082/6144 MiB
// smx: 10
{ "index" : 8,
"threads" : 16, "blocks" : 30,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 9,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,
},
// gpu: GeForce GTX 1060 3GB architecture: 61
// memory: 2482/3072 MiB
// smx: 9
{ "index" : 10,
"threads" : 16, "blocks" : 27,
"bfactor" : 6, "bsleep" : 25,
"affine_to_cpu" : false, "sync_mode" : 3,

**Comment by chrisewalsh** [comment]
I'm getting a very similar error with a 1060 3GB card too. 
[CUDA] Error gpu 1: <X:/xmr-stak-2.4.3/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:368

Mine seems to have started after the most recent big Windows 10 update.  I even tried compiling everything from scratch with the latest libraries and code to see if that would help. It did not.
It's a weird one, in that it runs fine for a while (sometimes 10-12 hours), but then randomly dies on this.  
I've tried playing with the settings (threads, bfactor,bsleep), nothing helps
It would be nice if xmr-stak would simply restart it itself when it gets an error, rather than just sitting there.

**Comment by fly19940923** [comment]
change the "threads" and "blocks"  maybe fiexed the issue

**Comment by Salingo** [comment]
@chrisewalsh  I met the same problem with you. It work well before I update Windows 10 from 1709 to 1803 yesterday. Have you fixed this issue?
