### ISSUE TITLE
Cryptonight V7 - CPU low_power_mode

### ISSUE THREAD

**Issue by Zozor54** [fireice-uk/xmr-stak#1456]
Hi,

When I run XMR the automatic configuration always puts the CPU "slow_power_mode"  to true.
My global hashrate is therefore diminished. Is it an obligation with V7 cryptonight?

Thanks.

Hav a nice day

**Comment by JayWalker512** [comment]
Can you provide more information? Ie. what is your CPU, OS, etc. Please follow the template. It's hard for anyone to help you if they don't know what you're working with.

**Comment by JerichoJones** [comment]
@Zozor54 low power mode is not required.
