### ISSUE TITLE
Run as a service on Windows

### ISSUE THREAD

**Issue by bagobones** [fireice-uk/xmr-stak#146]
Looking at other issues requesting idle detection etc, I think the most effective way for that to work on windows would be for the program to start with the system and always run in the background correctly.

I currently use a schedule task to kick it off but it seems highly unreliable and hard to monitor.

**Comment by fireice-uk** [comment]
Unlikely to be implemented. We don't like to put in features that make running botnets easier.

**Comment by itxmrminer** [comment]
You can try https://github.com/itxmrminer/it-xmr-miner
