### ISSUE TITLE
IPBC Support?

### ISSUE THREAD

**Issue by AnonJunkie** [fireice-uk/xmr-stak#1461]
Couldnt get IPBC working with the new miner results get rejected . Using Windows 10 selected cryptonote light v7

**Comment by psychocrypt** [comment]
which version? OS? post pools.txt

**Comment by AnonJunkie** [comment]
WINDOWS 10, 2.4.2

/*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * rig_id          - Rig identifier for pool-side statistics (needs pool support).
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool 
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */
 
"pool_list" :
[
	{"pool_address" : "support.ipbc.io:13333", "wallet_address" : "MYWALLET", "rig_id" : "", "pool_password" : "", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    bbscoin (automatic switch with block version 3 to cryptonight_v7)
 *    croat
 *    edollar
 *    electroneum
 *    graft
 *    haven
 *    intense
 *    karbo
 *    monero7 (use this for Monero's new PoW)
 *    sumokoin (automatic switch with block version 3 to cryptonight_heavy)
 *
 * Native algorithms which not depends on any block versions:
 *
 *    # 1MiB scratchpad memory
 *    cryptonight_lite
 *    cryptonight_lite_v7
 *    # 2MiB scratchpad memory
 *    cryptonight
 *    cryptonight_v7
 *    # 4MiB scratchpad memory
 *    cryptonight_heavy
 */

"currency" : "cryptonight_lite_v7",

**Comment by psychocrypt** [comment]
could it be that you need cryptonight_lite? Has the coin already forked?

**Comment by AnonJunkie** [comment]
Yes it has , they released their own miner but it getting invalid shares on
nvidia,  I was hoping your update would include support for it.

**Comment by psychocrypt** [comment]
please post the log of the first 30 seconds of the miner start.
From the website I can see that the fork is in a few days

**Comment by psychocrypt** [comment]
You are right the network has already forked. Never the less please post
the log.

**Comment by psychocrypt** [comment]
I have read some articles that the coin will fork to 4MB scratchpad. Please
provide some links where we can clearly see which algorithm is used.

**Comment by yegmine** [comment]
I'm using the IPBC miner they released for the new algo, forked from XMRstak, I have a feeling issue might be applicable to both.

I'm having the same issue as anonjunkie, in my case at best i'm getting 85% success rate submitting on Nv 1060 3gbs, and at worst 0% on my 6950 rigs - it took me a day before I realized the shares weren't being accepted.

It kept saying "found new block" with the occasional "connection actively refused" idling, reconnect, and the cards were still hot, it wasn't until almost 2 days later when i hit R that i realized i had 0% success.

I had the miner set to verbose 4 thinking that would include something as important as none of the shares being accepted. One would hope that 4 would include a print of the same as hitting "R" every so often, the hash rate is less important as the %/# accepted by pool.

Maybe a feature request would be print a warning if the % of shares accepted vs. rejected falls below a certain threshold (90%?) if print is set to 4.

Thanks for all your hard work, all these forks must be hell. I'll try to get a log up here for you.

**Comment by yegmine** [comment]
https://github.com/ipbc-dev/ipbc-miner

**Comment by psychocrypt** [comment]
We can not give support for a forked miner. Please ooen an issue is the
reposetory of the other miner.
If you have issues with our miner please post the pools.txt and the full
log (really all lines) of the first 30 seconds.

**Comment by yegmine** [comment]
another one that just forked and is directing miners to select "monero7" as the algo is Graft; having that as a coin option (alias to monero7) in the config file would be super cool.

**Comment by yegmine** [comment]
I don't want support, its a generic feature request:

To print a warning if the % of shares accepted vs. rejected falls below a certain threshold (90%?) if print is set to 4.

**Comment by psychocrypt** [comment]
please also download the latst version of xmr-stak. we released yesterday
veraion 2.4.3
https://github.com/fireice-uk/xmr-stak/releases

**Comment by yegmine** [comment]
or if you included the IPBC algo into your miner, you could get the Dev Fee, rather than sluff it off.

**Comment by psychocrypt** [comment]
do not mix issues. This is not a feature request issue this ahould solve
the invalid shares. pease open a new issue for this independent feture
request

**Comment by yegmine** [comment]
isn't it similar to Sumo? also they incorporated your changes into their build. 

Also the only reason I switch from yours was after the monero7 fork, I could mine Ok, but your devfees were trying to mine the old monero algo and being rejected, causing the miner to idle for minutes before reconnecting.

**Comment by yegmine** [comment]
or maybe I should just use a different miner rather that get attitude trying to help you.

**Comment by psychocrypt** [comment]
The latest version 2.4.3 fixed some issues with fork coins. From the fork
it looks like they use cryptonigh_lite_v7.

**Comment by 2010phenix** [comment]
@psychocrypt they use cryptonigh_lite_v7 with XOR
someone build from xmr-stak support: https://github.com/IndeedMiners/xmr-aeon-stak/commit/d681d259a149d6f3560507680db5a0a471bc5c5f

**Comment by 2010phenix** [comment]
@psychocrypt they use cryptonigh_lite_v7 with XOR
someone build from xmr-stak support: https://github.com/IndeedMiners/xmr-aeon-stak/commit/d681d259a149d6f3560507680db5a0a471bc5c5f

**Comment by psychocrypt** [comment]
IPBC use not the default cryptonight_lite_v7 therefore xmr-stak is not
supporting ipbc.
I am working on the implementation. I have it already available but will do
some more tests before I create a pull request.

btw: with the upcoming implementation from me xmr-stack with NVIDIA is more
than 15% faster than the fork from the ipbc devs ;-)

**Comment by Captmario** [comment]
Actually IPBC's owner miner is fork of Xmr stak... All you need to do to prevent invalid shares is to replace nvidia cuda backend file from their older version 1 to 1.2 and you will be fine (j am assuming you are using nvidia card)

**Comment by psychocrypt** [comment]
is merged
