### ISSUE TITLE
Shares mined is rejected

### ISSUE THREAD

**Issue by Ottobroeker** [fireice-uk/xmr-stak#1462]
Hi, everytime the miner have been doing the dev mining something goes wrong. 

After doing dev mining it switch back to the Bytecoin pool like it should but all my shares are now getting rejected. 

I have to close the program and start it again and shares are now being accepted until it once again have been doing the dev mining and switch back to mining Bytecoins. 

This means that I have to restart several times every day.

**Comment by psychocrypt** [comment]
We fixed this bug in the release 2.4.3 today. Please update your miner.
