### ISSUE TITLE
can it run without any configuration files for CPU mining?

### ISSUE THREAD

**Issue by moralrebuild** [fireice-uk/xmr-stak#1463]
For deployment and security reasons, I want to control the xmr-stak instances completely from the command line interface and make it independent from any configuration files (not just the 'pools.txt', but also 'config.txt' and 'cpu.txt'). I know xmrig can meet my requirement in this respect but I'd like to try xmr-stak since it provides valuable TLS encryption.

**Comment by Omar-Elrefaei** [comment]
I don't think so. When you run it the first time, it asks for some options, and saves the answers automatically in the config files.

**Comment by moralrebuild** [comment]
Now I understand the command line interface is only half baked.

**Comment by Omar-Elrefaei** [comment]
"half baked" I don't particularly agree on this, since this is the expected
outcome from a normal user. You have a specific edge case.

**Comment by psychocrypt** [comment]
the cli interface is not designed to avoid the config files. It is not
possible to map the complex functionallity we have in the config files to
an cli interface. And if so the interface will be unusable.

**Comment by psychocrypt** [comment]
Why do you need all at cli? Could you please describe the workflow and why
is it not possible to use the config files.

**Comment by moralrebuild** [comment]
@psychocrypt I already stated in the OP. It is understandable this is not a high priority request and only applicable for niche scenarios

**Comment by psychocrypt** [comment]
The negative side will be that than xmr-stak is used more often from script
kiddies as trojan miner because it is much easier to wrap the miner into
scipts. This is e.g. the case with xmrig's miner.
