### ISSUE TITLE
xmr-stak crash when it start to compile GPU

### ISSUE THREAD

**Issue by MalMen** [fireice-uk/xmr-stak#1471]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Celeron G3930
  - RX 550
  - RX 570
  - RX 580

# Issue with the execution
On windows when I execute xmr-stak it freezes and stop in this part:
[2018-04-19 23:10:40] : Compiling code and initializing GPUs. This will take a while...

It was working before, but it was giving some CL errors (didnt save the logs), and I had to remove some GPUs from the amd.txt to have it running ( I removed all the rx550 GPUs from it), I searched and based on what I found I figured out it could have low virtual memory so I updated windows virtual memory to 50GBytes, after the reboot the program couldnt run anymore

**Comment by JerichoJones** [comment]
It sounds like you have issues unrelated to STAK.... Did you exclude the STAK folder from your anti-virus?

**Comment by billyboy337** [comment]
Hello,
Are you running Windows 10? Can you check if and when KB4093112 has been installed on your system?

I am facing the same kind of issues. After hours wasted on it (including full reinstall), I end up believing it is an issue tied to Amd GPU and KB4093112 (Windows update patch from april). I bet that patch got installed on your system at reboot. I did not find solution yet (planning a reinstall and blocking this update for now)
