### ISSUE TITLE
2.4.3 version fail to respond to keyboard commands

### ISSUE THREAD

**Issue by Simaex** [fireice-uk/xmr-stak#1475]
Upgraded to the last 2.4.3 version downloaded from github. Running W10Pro (1709), 4xHD6990 GPU, AMD 14.4 drivers. I have verbose level 3 set before upgrade.
After the upgrade I did not receive any answer to r, h or c keyboard commands but mining is running normally. I am using TeamViewer to access the rig.
I have the same issues once in a while before but never this long, usually miner resume responding in a few minutes. This time it was not responding for hours. Resumed just when I check it last time before submitting the issue.

**Comment by psychocrypt** [comment]
please remove the file  config.txt and start the miner.

**Comment by ikon0000** [comment]
@Simaex hi~i have 1 HD6990 GPU,W10Pro (1709), AMD 14.4 drivers , but i have no good results update 
 help me please~

**Comment by Simaex** [comment]
I removed config.txt and started miner. It worked properly. After several hours I check it and get the same problem - no reaction to r, h or c keyboard commands.

**Comment by psychocrypt** [comment]
I get the same issue today directly after the startup. I am not surre why.
Currently I can not reproduce it. If you found any way to reproduce the
issue it would be help.

**Comment by fireice-uk** [comment]
@Simaex This can be caused by a proxy setting ridiculously low difficulty (below 1000) and your CPU not being able to check the shares in time.

**Comment by Simaex** [comment]
The system is using 8 GPU and CPU, total hashrate about 3000 H/s
Difficulty is 120000, average share time less ther 60 s.
I do not seem like too low difficulty.
I'll try to figure how to reproduce the issue. As for now it usually work for me after starting the miner but if I let it run for extended period (ex. overnight) I use to get the issue.
