### ISSUE TITLE
v2.4.2 Windows support only affinity up to 63? 

### ISSUE THREAD

**Issue by blew888** [fireice-uk/xmr-stak#1478]
I have an 80 CPU core server and the warning says Windows supports only affinity up to 63.  Before the fork, now I am only getting half the hash rate.  

Windows Server 2016
Xeon 2870 (8 processors)

![1](https://user-images.githubusercontent.com/9167126/39067659-5aa4b048-448e-11e8-9371-7a35961a38f5.JPG)

**Comment by Spudz76** [comment]
According to [this](https://technet.microsoft.com/en-us/library/ms187104(v=sql.110).aspx) the affinity mask in Windows is 8 bytes which is only enough single bit flags for 64 cpus, and that's that.
Would bet the older versions just didn't bother to mention failure...

**Comment by blew888** [comment]
I assume linux is the best way to utilize 80 cpus?

**Comment by psychocrypt** [comment]
yes
