### ISSUE TITLE
Can't Paste with ctrl V  into miner

### ISSUE THREAD

**Issue by KamikazeD** [fireice-uk/xmr-stak#1480]
Trying to set up the miner but it won't me Ctrl v the paste into the command window? What am i doing wrong? I can hand type in everything, but I really rather not especially when it comes to addresses :P

# Basic information
  - Type of the CPU. i7 4700
  - Type of the GPU (if you try to miner with the GPU). 770 gtx

# Compile issues
  - Which OS do you use? win 10
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by psychocrypt** [comment]
right klick on the mouse and than past

**Comment by KamikazeD** [comment]
Well I tried that first, and when that didn't work , I tried crtl v.  and only thing that comes up is a V.

**Comment by psychocrypt** [comment]
Please open an issue in a windows forum if you use windows else in a linux
forum. This is no miner issue.

**Comment by Simaex** [comment]
I will not argue that it is miner issue but no copy-paste to cmd window I have only in the xmr-stak miner.
@KamikazeD I am using a workaround. I put few first digits when generating config file, then stop miner and use copy-paste for complete address while editing config files. Another option is to use command-line starting parameters to pass all the needed values to miner but I never bothered to check the method myself.

**Comment by bokorben** [comment]
Shift + Insert is also an option to paste to windows cmd
