### ISSUE TITLE
unable to get two threads per GPU

### ISSUE THREAD

**Issue by matdez** [fireice-uk/xmr-stak#1481]
Hi guys, complete noob here trying to tune my GPU mining rigs (which were mining ETN but now probably going to do Monero given the current ASIC situation)

All GPUS are AMD RX580 8gb (various brands - but all have Hynix memory)

When I look at examples of other peoples intensity, work size etc it looks to me like they are running 2 threads per GPU, yet I can not for the life of me work out how.

Of a single thread i can get 730h/s per card (Sapphire brand), ~700h/s (Asus brand) and 670h/s (Gigabyte)

Three rigs, each with 7 identical cards of each brand in them.

On the website https://www.xmrstak.com/2018/02/13/gigabyte-rx-580-gaming-8g-865-h-s I see examples with - "gpu_thread_num" : 1, - but where exactly does this go? I have tried inserting it in just about every logical spot in the AMD config file, tried it in both version 2.1.0 and 2.4.2

Config file looks like this (for version 2.1.0 i followed the same structure in 2.4.2) :

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 0,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 0,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 1,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 1,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 2,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 2,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 3,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 3,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 4,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 4,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 5,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 5,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  // gpu: Ellesmere memory:3920
  // compute units: 36
  { "index" : 6,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
  { "index" : 6,
    "intensity" : 1024, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

Any and all help is very much appreciated!
[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1934466/amd.txt)

**Comment by Spudz76** [comment]
Config looks good to me you list the same index however many threads times

**Comment by matdez** [comment]
I am trying to achieve two individual mining operations per GPU (not sure on the correct terminology) but basically off the 7 GPU's I want 14 lots of mining calculations happening - two per GPU.

If i number the index's 0-13, it doesn't load any, saying device index 7 does not exist.

As it stands, it produces another error over and over (don't have remote access from my work computer to tell you what that is)

**Comment by Spudz76** [comment]
Well actually your amd.txt is invalid in newer than 2.2.0 when the configs changed.
Re-run with no amd.txt to see what a new one looks like
Then do exactly as done there, clone out each index.  If you have 8 cards they will always be index 0-7.  Index is card number.  Simply listing the card twice achieves two threads across the bus, and yes they show up separately.

**Comment by matdez** [comment]
tried it several times... then it finally worked! not sure what was different the last one but happy now. Thanks Spuds76!
