### ISSUE TITLE
v2.4.3 crashes/freezes system on compile or when closing

### ISSUE THREAD

**Issue by tavenger5** [fireice-uk/xmr-stak#1482]
After upgrading to v2.4.3, downloaded from here, I'm facing some crashing issues. It seems to only happen when trying to get the cached compile file or when closing the miner. In this case, this is the last line:
```
[2018-04-21 06:20:19] : Mining coin: monero7
[2018-04-21 06:20:19] : Compiling code and initializing GPUs. This will take a while...
[2018-04-21 06:20:20] : Device 0 work size 8 / 32.
```

If it does get past the compile, it freezes and doesn't respond to keyboard commands. When trying to close it, the whole system freezes.

I was not having this issue at at with 2.3. After reverting back, everything seems fine. I'm running Adrenalin 18.3.4 drivers.

# Basic information
  - Type of the CPU: Core i7 920 @2.67gHz
  - Type of the GPU: 2x Vega FE

# Stability issue
  - Is the CPU or GPU overclocked: GPUs memory is overclocked
  - Is the Main memory of the CPU or GPU undervolted: GPUs undervolted

**Comment by psychocrypt** [comment]
please post the full output. The output not looks like version 2.4.3.

Please post also the commamd how you started the miener

**Comment by tavenger5** [comment]
Unfortunately I was unable to get the exact output before crashing, but that is where it would hang on startup. There were no other error messages.

The miner was started with a bat file that contains --noNVIDIA --noCPU. I also tried just starting the miner, but it would still crash.

The amd.txt looks like this: 
`"gpu_threads_conf" : [
  // gpu: gfx901 memory:15984
  // compute units: 64
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx901 memory:15984
  // compute units: 64
  { "index" : 1,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
`

and the config.txt:
`
  "call_timeout": 10,
  "retry_time": 30,
  "giveup_limit": 0,
  "verbose_level": 4,
  "print_motd": true,
  "h_print_time": 60,
  "aes_override": null,
  "use_slow_memory": "warn",
  "tls_secure_algo": true,
  "daemon_mode": false,
  "flush_stdout": false,
  "output_file": "",
  "httpd_port": 4000,
  "http_login": "",
  "http_pass": "",
  "prefer_ipv4": true
`

**Comment by psychocrypt** [comment]
please start a cmd in windows and than goto the folder with xmr-stak. Start
the miner by hand we can not help if er have not the logs and the output of
`xmr-stak -V`

**Comment by tavenger5** [comment]
This is what I get most of the time
![xmr-stak-freeze](https://user-images.githubusercontent.com/34163498/39095581-daa76ab4-4610-11e8-8f14-438606da68d6.PNG)

At that point the system is not frozen, but if I try to close the miner, it will freeze.

When I do get it to run, I noticed my hashrate has dropped about 60-200h/s per card, and after a couple min, GPU 0 (which is the main, since I don't have graphics on the MB), fails and reverts to default powerplay table settings. When trying to close the miner, the system sometimes freezes.
![xmr-stak-compile](https://user-images.githubusercontent.com/34163498/39095678-4c678872-4612-11e8-8212-8da7bca43492.PNG)
 freezes.

**Comment by tavenger5** [comment]
@JerichoJones - why 1920?

**Comment by tavenger5** [comment]
Setting things to 1920 doesn't seem to make a difference. I can't find any correlation.

**Comment by JerichoJones** [comment]
Keep reducing by 32 until the problem is resolved (or not).

**Comment by tavenger5** [comment]
The strange thing is the version compiled by Nicehash 1.9.0.1 seems to run fine, and has been stable for days with the exact same settings. The only difference I can see is the dev fee being 0.

**Comment by psychocrypt** [comment]
could you please provide a link to the nicehash xmr-stak version you used.

**Comment by tavenger5** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/releases

**Comment by myeneroglu** [comment]
and also I tried to run 2.4.4 release in diffirent folder to what happens. Same result :(

**Comment by myeneroglu** [comment]
Hi all , Solved with resetting MotherBoard bios.
Model MSI H270a-PRO.
thnx
Murat

**Comment by JerichoJones** [comment]
Unfortunately no. :(
