### ISSUE TITLE
line for start xmr-stack for mining in miningpoolhub

### ISSUE THREAD

**Issue by javifly** [fireice-uk/xmr-stak#1487]
Hello,

I am trying to start xmr-stack for mining in miningpoolhub but i can´t it.

I am using this bat file for start, where is the problem?

xmr-stak.exe -O europe.cryptonight-hub.miningpoolhub.com:20580 -u xxxxxx.yyyyyy --currency monero7 -i 0 -p "" -r ""

i see the message in the log:
SOCKET ERROR - [europe.cryptonight-hub.miningpoolhub.com:20580] RECEIVE error: socket closed

thanks

**Comment by psychocrypt** [comment]
Please fill out the issue template. You did not show the error message.

**Comment by javifly** [comment]
the problem was in the start line, i change it several times i get fix the fail, the good start line is:

xmr-stak.exe -o ssl://europe.cryptonight-hub.miningpoolhub.com:20580 -u xxxxxxx.yyyyy --currency monero7 -i 0 -p "x" -r ""

thanks
