### ISSUE TITLE
NO static build

### ISSUE THREAD

**Issue by wsm3** [fireice-uk/xmr-stak#1493]
Hello

`cmake .. -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DMICROHTTPD_ENABLE=OFF -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF`

`Version: xmr-stak/2.4.3/26a5d65/master/lin/cpu/aeon-cryptonight-monero/20`

but

```
root@server:~/xmproxy/xmr-stak/build/bin# objdump -p xmr-stak | grep NEEDED
  NEEDED               libpthread.so.0
  NEEDED               libssl.so.1.0.0
  NEEDED               libcrypto.so.1.0.0
  NEEDED               libhwloc.so.5
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

How build static ?

**Comment by Spudz76** [comment]
There is no support for fully static, the "static" mode includes only a couple core libs (if gcc, it adds `-static-libgcc -static-libstdc++`)

**Comment by xiaoyuge16** [comment]
hello 
I compile with "cmake .. -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DMICROHTTPD_ENABLE=OFF -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF"
when I run ./xmr-stak
it report
 error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

what should  I do ?

**Comment by psychocrypt** [comment]
statuc build will only remove glibc dependencies. All other dependencies
are dynamic. In linux many libs are build as dynamic lib. Therrfore it is
not easy to create a fully static build.
