### ISSUE TITLE
Feature Request - Support Stellite's algorithm change from CryptonightV1 to a slightly modified variant

### ISSUE THREAD

**Issue by stellitedev** [fireice-uk/xmr-stak#1494]
# Summary

After forking to V7 without the presence of nicehash our network was stable, now since that V7 works for all block versions on it we're making a small change to the V7 variant.

# Details
You can see the simple modification we've done in [this](https://github.com/stellitecoin/Stellite/tree/V4) branch on our main repo 

# Testing the new variant

For convenience we have already set up a testnet pool [here](https://testxtl.anypool.net/#), you can use the following address for testing purposes.

```
Se3EkZfYDpXhaVqyBnAkkjfM1D3RWKeEECMJtAMjCuDE1qaQyEVUqcpXg6b49fCFSeKUD7Xvtzp5nFNPrFrFBVCG1C91AmN8d
```
Hope you take our request into consideration soon as we plan to implement this onto our mainnet as soon as possible and a good amount of our miners are fond of your miner.

Thank you.

**Comment by stellitedev** [comment]
https://github.com/stellitecoin/Stellite/commit/d4984cce1a4f6647db506c08e1980a9e5e297d08,
That is the commit for the changes in V4, [this line in src/crypto/slow-hash.c](https://github.com/stellitecoin/Stellite/blob/d4984cce1a4f6647db506c08e1980a9e5e297d08/src/crypto/slow-hash.c#L56), is the exact place we made our changes for the next variant. The block version used for the next fork is 4, we're currently helping pool operators with testing their pools but if the miner software is ready we could fork this week.

**Comment by psychocrypt** [comment]
I have seen in the code that you will fork one block aftet the next fork
again. Is it correct?
Is stellite currentl using cryptonight_v7 (the minero pow)?

Only a note even if we add the changes in the next half week there will be
no windows binaries available. We can not realease each week.

**Comment by stellitedev** [comment]
We're already using cryptonight_v7, we're forking to the above given changes again, and about the binaries yes we understand, we will fork stak master and build the binaries for our miners to use currently until you guys make the next release 👍

**Comment by psychocrypt** [comment]
I will work today on this issue

**Comment by psychocrypt** [comment]
@stellitedev The test pool is not available. If I try e.g. `telnet xtl.anypool.net 3333` I can not connect

**Comment by psychocrypt** [comment]
@xmrig  THX it looks like the pool was offline for a few hours

@stellitedev #1512 is implementing the new algorithm
