### ISSUE TITLE
GUI lag with GPU miner

### ISSUE THREAD

**Issue by bokorben** [fireice-uk/xmr-stak#1496]
Hi guys,

I've searched the web but I couldn't find any solution about this. 

When I am mining with CPU+GPU, my gui starts to lag _very_ badly (1 click needs ~2 sec to be seen). Mining is running fine, but I cannot use my machine during this time.

I tried to lower the intensity and worksize values, de HR dropped significally but the gui lag remained ~the same.  

# Basic information

"gpu_threads_conf" : [
  // gpu: AMD Radeon Pro 580 Compute Engine memory:1920
  // compute units: 36
  { "index" : 0,
    "intensity" : 864, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

Do you have any suggestions/tips that I can apply? 

(I am using the iMac all day, and want to run the miner in the background.)

iMac 2017 5K, i7-7700K, 16G RAM, Radeon Pro 580 8G (please leave the 'why are you mining on an iMac' questions, I am aware that this is not the best option, I also have a 2 x Vega56 rig just to mine, but I'd like to add the extra ~500-700 HR from the iMac, too)

Thanks,
Ben

**Comment by JayWalker512** [comment]
This happens with every OpenCL platform I've tried, Intel and Nvidia included. Not sure there's much that can be done about it short of using a second card dedicated to graphics.

**Comment by shagath** [comment]
XMR-Stak is one of the few miners I can't use desktop with while mining on GPU. Please add intensity parameters for NVIDIA. 👍

**Comment by psychocrypt** [comment]
reduce the threads it is equal to change the intensity.
Intensity = threads × blocks
