### ISSUE TITLE
I'm getting a pop-up on start that says "xmr-stak.exe has stopped working" and it closes the program

### ISSUE THREAD

**Issue by aceboyjake** [fireice-uk/xmr-stak#1498]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

Running a g4400 with 2x msi rx580 cards. I have a 3rd but my h270 won't allow the 3rd to register. I've tried scrolling through similar issues and haven't seen any fixes that work for me. Already ran through gpedit and regedit.
![capture17](https://user-images.githubusercontent.com/38672302/39154989-5b6392aa-471e-11e8-964e-f27fe3b0ca0f.JPG)

**Comment by aceboyjake** [comment]
Also when I run a fresh version of xmr-stak it's not building the cpu.txt amd.txt files like my vega rig did only getting a config file, although I'm not sure if that's part of the latest build

**Comment by TrueOsiris** [comment]
I'm having the exact same issue where these files are not created automatically.
I'm using 2 vega 64s with AMD Crimson drivers (in an unraid vm, with GPU's passed through)

In the w10 event viewer:

Faulting application name: xmr-stak.exe, version: 0.0.0.0, time stamp: 0x5ad792c8
Faulting module name: igdrclneo64.dll, version: 0.0.0.0, time stamp: 0x5aa189d8
Exception code: 0xc0000005
Fault offset: 0x0000000000150638
Faulting process id: 0x1ba8
Faulting application start time: 0x01d3dbb237123ad1
Faulting application path: C:\mining\xmr-stak-win64\xmr-stak.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fe73d2ebaa05fb95\igdrclneo64.dll
Report Id: 7b18cc80-ba9c-45f2-9374-b0f89d6f9d39
Faulting package full name: 
Faulting package-relative application ID:

**Comment by billyboy337** [comment]
Same issue as : https://github.com/fireice-uk/xmr-stak/issues/1471

I believe this is tied to KB4093112 and AMD RX cards.
(you'll get the same behavior with other miner - Trying to reinstall AMD Drivers (Crimson or the current (18.3.4) Adrenaline  might also get you some reboot in the process or bluescreen)

If you have a Restore points, you might try and restore to before KB4093112 and launch xmr-stak again. Should work.

**Comment by tavenger5** [comment]
@billyboy337, I'm facing a similar issue, but KB4093112 is not installed. I have 18.3.4 running with 2 Vega FE's

**Comment by psychocrypt** [comment]
PLease check if you use old `dLL` files from the previous release.  Please download the newest version into a new  empty directory
