### ISSUE TITLE
Amd.txt not cretaed

### ISSUE THREAD

**Issue by opensourcepj** [fireice-uk/xmr-stak#1503]
amd.txt not created despite the fact that it compiles with cmake as follows

cmake -DOpenCL_ENABLE=ON  -DCUDA_ENABLE=OFF -DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/CL -DOpenCL_LIBRARY=/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so ..

**Comment by JayWalker512** [comment]
Please fill out the template. This is not enough information to help you.
