### ISSUE TITLE
GPU ID 5

### ISSUE THREAD

**Issue by STRATZ-Ken** [fireice-uk/xmr-stak#1504]
Just a question.  

When it says : 

2 | 2018-04-25 10:41:10
-- | --
AMD Invalid Result GPU ID 5

Does that mean when you press `H` you get GPU ID 5 there.  Or does that mean the OS GPU ID 5 (Index Id in amd.txt). I double thread cards, so not sure which one is over clocked.

**Comment by psychocrypt** [comment]
Yes ID 5 is the in `amd.txt` with the index 5
