### ISSUE TITLE
Xmr-Stak2.4.3 continues mining "rejected shares" for hours after reconnecting to pool

### ISSUE THREAD

**Issue by lost-bro** [fireice-uk/xmr-stak#1505]
Please provide as much as possible information to reproduce the issue.

# Basic information
V2.4.3 will run for a decent amount of time (days)  w/o any issues..... 100% accepted share rate... then immediately following an internet caused loss of connection to pool the v2.4.3 will attempt to reconnect to pool.  The reconnection appears in the log.txt as normal except ALL following shares are now "rejected shares".  The miner is NOT banned and there were NO duplicate shares nor bad shares submitted prior to the disconnection from pool (actually up to 100% accepted prior to disconnection).  It seems the reconnect is not complete as the pool shows NO shares submitted during this time.  Unfortunately, the miner continues mining the "rejected shares" for hours...... until time that it is manually turned off and restarted.
![connection rejection](https://user-images.githubusercontent.com/37913805/39262705-c588f9d2-4885-11e8-8fbd-4472b69a8d19.png)

Intel Pentium G3250 3.2GHz   - Type of the CPU.  
Sapphire Nitro rx580 x6  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use? Windows 10 1079
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```yes...................
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"

cd /

cd xmr-stak-2.4.3

mkdir build

cd build

set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl;

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

cmake --build . --config Release --target install


    85 Warning(s)
    0 Error(s)
   Time Elapsed 00:13:00.89

cd bin\Release

copy C:\xmr-stak-dep\openssl\bin\* .


 


 run `./xmr-stak --version-long` and add the output here
  ```C:\xmr-stak-2.4.3_\build\bin\Release_x64>xmr-stak --version-long
Version: xmr-stak/2.4.3/26a5d65f/unknown/win/nvidia-amd-cpu/aeon-cryptonight-monero/0
Press any key to exit.

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by lost-bro** [comment]
![poolsideshares](https://user-images.githubusercontent.com/37913805/39265755-ae97174c-488d-11e8-9215-0241abe85bec.png)
Just wanted to upload a pic of the poolside shares from this advent.   Can be seen the 'clean' turn off and then about 3 hours later I manually restarted the miner.

**Comment by psychocrypt** [comment]
please post the file pools.txt

**Comment by lost-bro** [comment]
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/1948511/pools.txt)
Ok,  here is the pool.txt that was active in this rig when the issues have occured
thanks

**Comment by lost-bro** [comment]
OK, just a quick update:  here is a screen shot from 12hrs after last incident:  Rig is getting 100% accepted shares.  
![12hrs later](https://user-images.githubusercontent.com/37913805/39280299-2836b022-48c4-11e8-9753-5edd7cc8da78.png)

**Comment by aij** [comment]
I'm seeing something similar if not the same. 

```
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:29:50] : Result accepted by the pool.
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:29:59] : Result accepted by the pool.
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:30:15] : Result accepted by the pool.
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:30:25] : Fast-connecting to m0:3333 pool ...
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:30:25] : SOCKET ERROR - [m1:3333] CALL error: Timeout while waiting for a reply
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:32:37] : SOCKET ERROR - [m0:3333] CONNECT error: Connection timed out
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:32:37] : Fast-connecting to m1:3333 pool ...
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:32:37] : Pool m1:3333 connected. Logging in...
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:32:38] : Result rejected by the pool.
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:32:58] : Result rejected by the pool.
Apr 23 03:44:35 m1 xmr-stak-start[7402]: [2018-04-23 03:33:06] : Result rejected by the pool.
```

Unfortunately, I didn't notice until this morning, by which time I was down to 8% good shares from that rig. :disappointed: 

From a quick tcpdump, it seems all the shares are being submitted with the same `job_id`, resulting in rejection message `"Invalid job id"`, code `-1`.

Attached is a tcpdump from a different machine, which is where I first noticed the issue.
[stak-invalid_job_id.tcpdump.gz](https://github.com/fireice-uk/xmr-stak/files/1956478/stak-invalid_job_id.tcpdump.gz) (Note job_id is always `503755494998768000`.)

This is connecting to `xmrig-proxy`, so the issue might be there.

From the tcpdump, it seems no new jobs were received during that 5 minute window. I don't yet know this protocol well enough to know how that is supposed to work, but either way it doesn't seem to make sense to burn CPU cycles (and electricity) doing work for a known-invalid `job_id`.

**Comment by psychocrypt** [comment]
thx for the tcp dump. @fireice-uk maybe we can see from the dump whats
going on.

**Comment by fireice-uk** [comment]
@aij The dump is *way* too short, I would need to have the connection loss in it to make a proper judgement, but the fact that a new job is never sent makes me strongly suspect that this is xmrig problem.

**Comment by psychocrypt** [comment]
@lost-bro do you also used xmrig-proxy?

**Comment by lost-bro** [comment]
@ psychocrypt
No, this rig is connected thru a "double-natted" ISP service....... local router (house) >>(internal IP) >> ISP router (server)>> external IP (internet).
I have used various anterior versions of Xmr-stak on this same ISP system w/o seeing this issue.  The rig in question has now been running for a couple days w/o this problem recurring.  The last time it happened the rig only ran for about two days when it happened for the second time, which was when I posted the information above.  I have not changed any configurations so as to see if the problem would occur again.  I am writing a powershell script now to restart Xmr-stak when / if the " result rejected by pool " happens in the future, know it's just a bandaid for whatever the real issue is........ but seems to be a really sporadic problem.

**Comment by Amdpowered** [comment]
This also happened to my yesterday. There was some connectivity issue and then xmr-stak 2.4.3 started submitting invalid shares. I caught it an hour later. The other two instances (same version) I was running on the same internet connection did not have problems.

**Comment by cryptify** [comment]
"pool_list" :
[
	{"pool_address" : "POOL.IP.ADDRESS.HERE:PORT", "wallet_address" : "full-wallet-address", "rig_id" : "", "pool_password" : "x (I have also left this blank to no avail", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],



"currency" : "monero7",

**Comment by cryptify** [comment]
pool is a machine I run locally, no TLS in case that matters

I have also tried routing it through the external IP using another IP, but it still rejects shares

**Comment by psychocrypt** [comment]
The issue should be fixed with #1526

**Comment by cryptify** [comment]
Still rejecting shares but it doesn't seem you've updated the binaries yet :) 


![untitled](https://user-images.githubusercontent.com/37587102/39661074-f1bbc804-5019-11e8-8958-9dd508118aec.png)

**Comment by mountaineerbr** [comment]
Hello. I am getting a lot of 

`SOCKET ERROR - [address:port] RECEIVE error: Connection reset by peer`

And they started after update to 2.4.3, 2.4.2 was giving me no connection errors. Interestingly enough, I took my mining laptop to university and alas, it stayed for hours mining without any connection problems!

Now at home, I am using the 2.4.2 version on Linux (and in Windows, too, the same problems) and I am having no network problems. i hope this gets fixed by next update. Thanks,
