### ISSUE TITLE
CMakeFiles errors on Make Install

### ISSUE THREAD

**Issue by shaneg92** [fireice-uk/xmr-stak#1506]
Please provide as much as possible information to reproduce the issue.

# Basic information
  Intel i7
 Radeon RX 750

# Compile issues
  Ubuntu 14.04
  
following the instructions from https://www.monero.how/how-to-mine-monero-with-gpu

when I run make install inside the build file I receive two errors listed below

/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1061:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, cx3, bx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1061:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, cx3, bx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1062:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, cx4, bx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1062:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, cx4, bx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h: In instantiation of ‘void cryptonight_penta_hash(const void*, size_t, void*, cryptonight_ctx**) [with xmrstak_algo ALGO = (xmrstak_algo)5u; bool SOFT_AES = true; bool PREFETCH = true; size_t = unsigned int]’:
/home/chris/xmr-stak/xmrstak/backend/cpu/minethd.cpp:627:2:   required from here
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: error: ‘_mm_cvtsi128_si64’ was not declared in this scope
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1004:26: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx1 = _mm_cvtsi128_si64(ax1);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1005:26: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx2 = _mm_cvtsi128_si64(ax2);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1006:26: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx3 = _mm_cvtsi128_si64(ax3);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1007:26: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx4 = _mm_cvtsi128_si64(ax4);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1027:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1028:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax1, bx1, cx1, l1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1029:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax2, bx2, cx2, l2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1030:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax3, bx3, cx3, l3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1031:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax4, bx4, cx4, l4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1033:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax0, bx0, cx0, l0, mc0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1033:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax0, bx0, cx0, l0, mc0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1034:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax1, bx1, cx1, l1, mc1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1034:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax1, bx1, cx1, l1, mc1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1035:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax2, bx2, cx2, l2, mc2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1035:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax2, bx2, cx2, l2, mc2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1036:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, bx3, cx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1036:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, bx3, cx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1037:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, bx4, cx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1037:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, bx4, cx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1052:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax0, cx0, bx0, l0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1053:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax1, cx1, bx1, l1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1054:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax2, cx2, bx2, l2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1055:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax3, cx3, bx3, l3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:718:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1056:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax4, cx4, bx4, l4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1058:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax0, cx0, bx0, l0, mc0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1058:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax0, cx0, bx0, l0, mc0, ptr0, idx0);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1059:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax1, cx1, bx1, l1, mc1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1059:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax1, cx1, bx1, l1, mc1, ptr1, idx1);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1060:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax2, cx2, bx2, l2, mc2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1060:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax2, cx2, bx2, l2, mc2, ptr2, idx2);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1061:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, cx3, bx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1061:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, cx3, bx3, l3, mc3, ptr3, idx3);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:725:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1062:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, cx4, bx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:732:25: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  idx = _mm_cvtsi128_si64(a); \
                         ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1062:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, cx4, bx4, l4, mc4, ptr4, idx4);
   ^
/home/chris/xmr-stak/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:1003:26: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx0 = _mm_cvtsi128_si64(ax0);
                          ^
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
make: *** [all] Error 2
  
 

# Stability issue
  - Is the CPU or GPU overclocked? --No
  - Is the Main memory of the CPU or GPU undervolted? --No

**Comment by Spudz76** [comment]
Did you install the good 14.04 gcc-5 from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test ??
Or are you using clang < 3.8 ??
Looks like a bad compiler issue or something with the toolchain.
Post the CMakeCache.txt it tells us most of what decisions CMake made.

**Comment by Spudz76** [comment]
Also when the gcc-5 or good clang is not the system default compiler you should specify the proper alternative like:
`CC=/usr/wherever-gcc-5/bin/gcc CXX=/usr/wherever-gcc-5/bin/g++ cmake ..`
You also will likely need to witch kernels around depending which AMD driver you want (fglrx needs 4.2.0 or older)...
