### ISSUE TITLE
Is AMD APP SDK 3.0 no longer available on AMD website?

### ISSUE THREAD

**Issue by cialu** [fireice-uk/xmr-stak#1511]
The instructions on the page [Compile xmr-stak for Linux](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md) show:

AMD APP SDK 3.0 (only needed to use AMD GPUs)

download and install the latest version from [http://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/](http://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/)

The link results in a 404 page and it seems that the AMD APP SDK 3.0 is no longer available on AMD website. 

Did I miss something? What can I use as alternative?

Regards.

**Comment by Spudz76** [comment]
Seems down, their webmaster/content system sucks this week apparently.
[here is a mirror for now / link to google cached amd checksums page](http://files.esited.net/AMD/)

**Comment by cialu** [comment]
@Spudz76 Thanks for the file. I think they completely removed the APP SDK from the website because also found no mention on the [Tools & SDKs page](https://developer.amd.com/tools-and-sdks/).

**Comment by neptune-klm** [comment]
I don't see any download for the AMD APP SDK 3.0 for windows

**Comment by Spudz76** [comment]
Moved/added windows...

**Comment by cialu** [comment]
From AMD DEVGURUS forum:

> It might be a temporary server problem. As a workaround, please download the installers from here:
> 
> Full Installers:
> 
> 32-bit: http://amd-dev.wpengine.netdna-cdn.com/app-sdk/installers/APPSDKInstaller/3.0.130.135-GA/full/AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x86.exe
> 
> 64-bit: http://amd-dev.wpengine.netdna-cdn.com/app-sdk/installers/APPSDKInstaller/3.0.130.135-GA/full/AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe

**Comment by cialu** [comment]
Also, on hold of the Linux download links.
[https://community.amd.com/message/2859384](https://community.amd.com/message/2859384)

**Comment by Spudz76** [comment]
Thanks for curating some more mirrors

**Comment by Orsontrius** [comment]
Hello, it seems the mirrors provided for linux no longer exist. Is there another alternative?

**Comment by KOLANICH** [comment]
https://github.com/Microsoft/LightGBM/releases/download/v2.0.12/AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2

**Comment by Orsontrius** [comment]
@KOLANICH Works great, thank you!

**Comment by KOLANICH** [comment]
@Orsontrius, thank LightGBM maintainers for their archived copy :)

**Comment by mountassir** [comment]
> 
> 
> Seems down, their webmaster/content system sucks this week apparently.
> here is a mirror for now
> [AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2](http://debian.nullivex.com/amd/AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2)
> [AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe](http://debian.nullivex.com/amd/AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe)
> 
> [link to google cached amd checksums page](https://webcache.googleusercontent.com/search?q=cache:UxGKO0L94SkJ:https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/system-requirements-driver-compatibility/+&cd=2&hl=en&ct=clnk&gl=us)

Both Linux and Windows links give error "File not found".

**Comment by KOLANICH** [comment]
>Both Linux and Windows links give error "File not found".

For Windows versions use links to, they are  http://amd-dev.wpengine.netdna-cdn.com still alive, though the connection is insecure. If you don't want to install the stuff (for example you wanna crosscompile), you can unpack the installer with https://github.com/lifenjoiner/ISx and then https://github.com/activescott/lessmsi or other msi unpacker.

**Comment by xakepp35** [comment]
Just take a look at this pretty [OCL light SDK ](https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases) from AMD! It just installs couple of nesesary headers and lib files to compile openCL-related on Windows, and sets `%OCL_ROOT%` variable to use in.. wherever!  Houraaa, I dont need to download AMD APP with heavyweight payloads of _super-duper-mega-examples_ anymore!!!

**Comment by KOLANICH** [comment]
>DLLs now lives with drivers, where they should be

the dll shipped with the AMD driver to the card on one of my PCs was broken, the one from APP SDK had solved the issue.

**Comment by catcoin-project** [comment]
At the Internet Archive:

[https://archive.org/download/AMDAPPSDK](https://archive.org/download/AMDAPPSDK)
