### ISSUE TITLE
Linux Binary

### ISSUE THREAD

**Issue by shadixs** [fireice-uk/xmr-stak#1516]
Hi, just wondering if you can release a full built linux binary like you did several months ago? I found this binary really helpful for me and others due to difference on linux distros I have..

Or can you show me how to do so?

Thanks

**Comment by cialu** [comment]
At [https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md) you can find instructions to compile xmr-stak on Linux and at #1511 you can find the AMD APP SDK that is no longer available on AMD website.

**Comment by Zenitur** [comment]
[Try this](https://yadi.sk/d/XiAWdL2_3VVwD3). It requires Glibc 2.11+. Optionally I'd make OpenCL backend that was built with FreeOCL. Look that in freeocl directory.
