### ISSUE TITLE
Invalid shares with dwarf pool

### ISSUE THREAD

**Issue by kaeptnb** [fireice-uk/xmr-stak#1519]
Hello!

getting about 5% inalid shares when connected to dwarf pool (mining xmr), i googled and found this:
https://github.com/xmrig/xmrig/issues/153
yes, this is for xmrig, but i wonder if the same workaround (i.e. reconnecting when getting an invalid share?!) could be implemented in xmr-stak also - if that makes sense at all? :)

Greetings, and thanks for this great miner!

**Comment by Spudz76** [comment]
I think something like this approximates the xmrig patch... give it a try?
```
--- a/xmrstak/misc/executor.cpp
+++ b/xmrstak/misc/executor.cpp
@@ -365,6 +365,14 @@ void executor::on_pool_have_job(size_t pool_id, pool_job& oPoolJob)

        jpsock* pool = pick_pool_by_id(pool_id);

+       pool_job oCurrPoolJob;
+       if(pool->get_current_job(oCurrPoolJob) && oCurrPoolJob.sJobID == oPoolJob.sJobID)
+       {
+               printer::inst()->print_msg(L3, "Duplicate job detected!");
+               pool->disconnect();
+               return;
+       }
+
        xmrstak::miner_work oWork(oPoolJob.sJobID, oPoolJob.bWorkBlob, oPoolJob.iWorkLen, oPoolJob.iTarget, pool->is_nicehash(), pool_id);

        xmrstak::pool_data dat;
```

**Comment by kaeptnb** [comment]
Thanks! i tried that,  but still about 2% invalid shares - maybe it helped only a little

**Comment by psychocrypt** [comment]
invalid shares comming from overclocking and ram issues

**Comment by kaeptnb** [comment]
i thought so too, but a) its only with dwarf pool and b) i tried already with less aggressive settings - still the same; but i will re-test b) with this new patch...

**Comment by TheBulitt** [comment]
this happens because dwarfpool always messes up and sends double-jobs so your miner starts working on the first job but the pool is expecting results from the second job and returns "low difficulty share"

**Comment by Spudz76** [comment]
So then the proper action would be to dump the first job version and replace it with the new one?
Slightly less aggressive than reconnecting... but still losing work / why aren't they fixing it?

**Comment by psychocrypt** [comment]
If this is a po issue please contact the pool admin. He/she should be fix
the double sending very easy.

**Comment by kaeptnb** [comment]
Hi, 
after running xmrstak with above patch a little longer than just a few hours, it seems the error rate is still at about 4-5%, so no real improvment; 

i re-compiled everything, customizing the Errormessage a bit, so i might recognize it better in the output; thing is - it seems, the codepath above is never really traversed in my case:


[2018-05-02 14:33:24] : Result accepted by the pool.
[2018-05-02 14:33:25] : New block detected.
[2018-05-02 14:33:26] : New block detected.
[2018-05-02 14:33:27] : Result accepted by the pool.
[2018-05-02 14:33:29] : Result rejected by the pool.
[2018-05-02 14:33:37] : Result accepted by the pool.

at 14:33 "it" happened again, but the errormessage i customized didn't appear, just the normal "Result rejected by the pool";

I always suspected that the patch doesnt really disconnect me to the pool in my case, simply because under "connection" the time of the connect always stays the same....

maybe we need to adapt the patch, to mimic xmrig's workaround for this problem?

Greetings!

**Comment by Spudz76** [comment]
That was sort of a hack-stab at the problem based completely on the xmrig patch but the executor/job-loop is a bit different here so that may not work the same / at all.

Try #1527 as that is the patch for this issue from the 'real' devs.  I'm just a groupie trying to help out.

**Comment by kaeptnb** [comment]
awesome - that version is working now for hours and not a single invalid hash yet... very promising!

**Comment by kaeptnb** [comment]
after nearly 24h it seems to have settled at 2% invalid shares with the new version, definitly better compared to the non-#1527 version.

**Comment by Spudz76** [comment]
Cool, please report in the #1527 thread so psychocrypt has related reports in one place.  Also can work more closely with the patch over there (I'm just facilitating now).

**Comment by K2** [comment]
Similar issues, latest code working slightly better... 
@Atrides do you know what's up?
