### ISSUE TITLE
Compiling with mingw64 error

### ISSUE THREAD

**Issue by UnclWish** [fireice-uk/xmr-stak#152]
[ 24%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.obj
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/autoAdjustHwloc.hpp:9,
                 from D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/minethd.cpp:41:
D:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:1585:13: error: conflicting declaration of 'DWORD64 _umul128(DWORD64, DWORD64, DWORD64*)' with 'C' linkage
     DWORD64 UnsignedMultiply128(DWORD64 Multiplier,DWORD64 Multiplicand,DWORD64 *HighProduct);
             ^
In file included from D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/minethd.cpp:24:0:
D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:24:24: note: previous declaration with 'C++' linkage
 static inline uint64_t _umul128(uint64_t a, uint64_t b, uint64_t* hi)
                        ^~~~~~~~
D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/minethd.cpp: In static member function 'static bool xmrstak::cpu::minethd::thd_setaffinity(std::thread::native_handle_type, uint64_t)':
D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/minethd.cpp:76:48: error: invalid conversion from 'std::thread::native_handle_type {aka long long unsigned int}' to 'HANDLE {aka void*}' [-fpermissive]
  return SetThreadAffinityMask(h, 1ULL << cpu_id) != 0;
                                                ^
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:70:0,
                 from D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/autoAdjustHwloc.hpp:9,
                 from D:/Compiling/xmr-stak-2.0.0/xmrstak/backend/cpu/minethd.cpp:41:
D:/msys64/mingw64/x86_64-w64-mingw32/include/winbase.h:1162:31: note:   initializing argument 1 of 'DWORD_PTR SetThreadAffinityMask(HANDLE, DWORD_PTR)'
   WINBASEAPI DWORD_PTR WINAPI SetThreadAffinityMask (HANDLE hThread, DWORD_PTR dwThreadAffinityMask);
                               ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/build.make:164: CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/xmr-stak-backend.dir/all] Ошибка 2
make: *** [Makefile:130: all] Ошибка 2

**Comment by fireice-uk** [comment]
We don't support mingw64, please use msvc on Windows.

**Comment by UnclWish** [comment]
Hmmm, it's strange. XMR-Stak-CPU normally compiling via mingw64...
It would be nice if you're add support for mingw compiling.
