### ISSUE TITLE
2 identical GPU with different result

### ISSUE THREAD

**Issue by bucah** [fireice-uk/xmr-stak#1521]
Hi,
I have 2 Gigabyte Vega 56 Gaming which are identical with the same setting on amd.txt and the same OC setting according to vegamininguide.com.

When I use to mine sumokoin, these 2 GPU makes different hash result. However when I use to mine Monero there are not much different on hash result.

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   34.3 |   35.1 |   30.7 |
Totals (CPU):    34.3   35.1   30.7 H/s
-----------------------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  160.7 |  159.3 |  157.1 |  1 |  160.8 |  159.4 |  157.1 |
|  2 |  737.5 |  736.5 |  732.8 |  3 |  736.8 |  737.2 |  732.8 |
|  4 |  668.2 |  667.7 |  666.9 |  5 |  667.7 |  667.2 |  666.9 |
Totals (AMD):  3131.8 3127.2 3113.7 H/s
-----------------------------------------------------------------
Totals (ALL):   3166.1 3162.3 3144.4 H/s
Highest:  3167.6 H/s

ID 0 and 1 : Gigabyte RX550
ID 2,3,4,5 are Gigabyte Vega 56 Gaming

What could possibly wrong with this ?

**Comment by Spudz76** [comment]
Is it also different hashrates on gpus when cpu is not mining? (`--noCPU`)
If so, maybe affinity could help.  Otherwise I would test by swapping cards and if the hashrate doesn't move then it's a slot-based issue (one is 16x cpu-local and one is 4x on some bridge?)
If they are not the exact same cards one may have different memory brand?

**Comment by bucah** [comment]
I have got the same result on both GPUs with new setting on mem_chunk to 12 instead of 8.

Here are the results: 

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   35.5 |   36.4 |   (na) |
Totals (CPU):    35.5   36.4    0.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  150.6 |  147.2 |   (na) |  1 |  149.4 |  146.2 |   (na) |
|  2 |  731.0 |  730.6 |   (na) |  3 |  731.4 |  730.8 |   (na) |
|  4 |  728.4 |  728.9 |   (na) |  5 |  731.5 |  732.1 |   (na) |
Totals (AMD):  3222.3 3215.8    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   3257.7 3252.2    0.0 H/s
Highest:  3283.6 H/s
-----------------------------------------------------------------

As you can see they are now have the same hash rate.
I have check the memory brand with GPUZ and both are made by Hynix. And both GPU are using PCIe riser on small slot from the first time.

**Comment by mountaineerbr** [comment]
Hello! I cannot really see any problem. I would say that oscillation is expected as cores try to work together, some sort of resonance is expected as there are many identical components working together, but in average they should do the just work sum of separate entities combined or maybe a bit higher than expected , in overall analysis... If you could, really, check and take note of the hashrate of each core of each card running separately - leave the others out for each run, and then compare results *afterwards*, you should have some better material to draw further conclusions. There you should be able to see that, on average, they work the same.

But, I am also thinking there is oscillation in the code that is being worked on in our computer that is not translated into the *difficulty* parametre. That code may seem to generate instantaneous hashrate oscillation
 even though the diff is the same for the block.
