### ISSUE TITLE
Vega 56/64 hashing too low on cryptonight-heavy(SUMO)

### ISSUE THREAD

**Issue by alejandrocfg** [fireice-uk/xmr-stak#1522]
I have two AMD cards, an AMD RX 580 and AMD RX Vega 56. Both perform great on cryptonight and cryptonightv7(~850h/s and ~1850h/s). The issue is the with Vega when mining cryptonight-heavy SUMO. First I noticed I had to change(lower) the intensity considerably on the Vega to get the miner to work but then the hash rate wont go over ~1200h/s on the other hand the 580 works perfectly having same hash rate than the other 2 algorithms without changing settings. I double checked this issue with a friend having a Vega 64 rig and he had the same issue than my Vega 56 one.

I tried the latest version and also tried compiling the latest source code having the same issue.

**Comment by Spudz76** [comment]
Vega is slower with Heavy, that's just how they are.

**Comment by Hsys7272** [comment]
might be the amd drivers arent updated yet for cn-heavy

**Comment by psychocrypt** [comment]
cryptonight_heavy is using 4 MIB per thread. VEGA was able to use the full GPU memory for mining with cryptonight_v7 (2MB/H), now with 4MB/H the parallelism is reduced and therefore the hash rate is lower.
