### ISSUE TITLE
instructions to compile on windows do not work

### ISSUE THREAD

**Issue by khuffmanjr** [fireice-uk/xmr-stak#153]
Greetings!

I have followed instructions to compile on windows 10.  I did not perform steps for CUDA 8.0+ nor did I download and create the directory structure for the dependency folder - again, no CUDA needed; I have a Vega.  When I create the build directory and cd to it and then run the cmake command, I get `Error: could not load cache`

Why am I changing to an empty directory and running cmake without specifying the location of make files or whatnot?  Anyway, I would like this to work, please.  :)  Please look at your instructions and let me know how I screwed up.  Thanks!

**Comment by khuffmanjr** [comment]
So I went through it again.  This time I grabbed the cuda stuff, assuming cuda 9, despite not having nvidia.  Got down to the last cmake command in windows compile instructions and then this:
`C:\xmr-stak-amd-final\build>cmake --build . --config Release --target install
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj

C:\xmr-stak-amd-final\build>`

**Comment by Clintoxen** [comment]
Why not turn off cuda in the cmakelist file?

**Comment by khuffmanjr** [comment]
Ok, I'm game.  How would I do that?

**Comment by AMDfreak** [comment]
I'm getting the same thing. Doesn't matter whether CUDA is on or off in the cmakelist file.

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> cmd
Microsoft Windows [Version 10.0.16299.64]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd \

C:\>cd xmr-stak-master

C:\xmr-stak-master>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
C:\Users\user\source>cd \

C:\>cd xmr-stak-master

C:\xmr-stak-master>set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

C:\xmr-stak-master>cd build

C:\xmr-stak-master\build>cmake --build . --config Release --target install
Error: could not load cache

C:\xmr-stak-master\build>cmake --build . --config Release --target install
Error: could not load cache

C:\xmr-stak-master\build>`

**Comment by Clintoxen** [comment]
@khuffmanjr according to the error at the beginning this is your problem https://blogs.msdn.microsoft.com/ericparvin/2016/12/16/msb1009-project-file-does-not-exist-for-tfs-visual-studio-build-task/

**Comment by psychocrypt** [comment]
@AMDfreak please follow exactly the steps from the howto. You forget to
create the build files with cmake. Even if you have no cuda you need to run
the cmake command. Use the command which is within the cuda9 section.

**Comment by AMDfreak** [comment]
Thanks, that got things moving for me but I have now run into a different problem.  When running the resultant exe, I get 2 error popups, "The code execution cannot proceed because LIBEAY32.dll was not found".  The same message comes up for SSLEAY32.dll.

I started over to try to follow the guide to a T, so I'm not sure where I went wrong this time.

**Comment by psychocrypt** [comment]
I updated the documentation in #181

**Comment by derchirurg** [comment]
I added the two Parameters: -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF

So the command looks like:
cmake -G "Visual Studio 15 2017 Win64" -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -T v141,host=x64 ..

**Comment by darcshadow** [comment]
I'm not having any luck getting this to compile. It has to be something simple that I'm missing I'm sure.
I get all the way through the process per the instructions but the last cmake step doesn't work for me
cmake --build . --config Release --target install
I get an error message stating that the director install does not exist.
