### ISSUE TITLE
Compilation fails on arm based RPI3b+

### ISSUE THREAD

**Issue by lhirlimann** [fireice-uk/xmr-stak#1534]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU : Quad Core 1.2GHz Broadcom BCM2837 64bit CPU

# Compile issues
  - Which OS do you use?
  Fedora Server 28 armv7

  add **all** commands you used and the **full** compile output here
 cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF -DHWLOC_ENABLE=OFF -DCPU_ENABLE=YES
  [ludovic@localhost build]$ make
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
cc: error: unrecognized command line option ‘-msse2’
cc: error: unrecognized command line option ‘-maes’; did you mean ‘-mapcs’?
make[2]: *** [CMakeFiles/xmr-stak-c.dir/build.make:63: CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/xmr-stak-c.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

  run `cmake -LA .` in the build folder and add the output here
ludovic@localhost build]$ cmake -LA
CMake Error: The source directory "/home/ludovic/src/xmr-stak-2.4.3/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=
CMAKE_CXX_FLAGS_RELEASE:STRING=
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O2 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=YES
CUDA_64_BIT_DEVICE_CODE:BOOL=OFF
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
CUDA_ENABLE:BOOL=OFF
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
EXECUTABLE_OUTPUT_PATH:STRING=bin
HWLOC:FILEPATH=HWLOC-NOTFOUND
HWLOC_ENABLE:BOOL=OFF
HWLOC_INCLUDE_DIR:PATH=HWLOC_INCLUDE_DIR-NOTFOUND
LIBRARY_OUTPUT_PATH:STRING=bin
MHTD:FILEPATH=MHTD-NOTFOUND
MICROHTTPD_ENABLE:BOOL=OFF
MTHD_INCLUDE_DIR:PATH=MTHD_INCLUDE_DIR-NOTFOUND
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/libssl.so
OpenCL_ENABLE:BOOL=OFF
OpenCL_INCLUDE_DIR:PATH=OpenCL_INCLUDE_DIR-NOTFOUND
OpenCL_LIBRARY:FILEPATH=OpenCL_LIBRARY-NOTFOUND
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
[ludovic@localhost build]$

**Comment by Spudz76** [comment]
`-msse2` and `-maes` are always added to the compiler line, you'd have to find and remove them from `CMakeLists.txt` and try again.

**Comment by lhirlimann** [comment]
That did the trick - now I'm stuck with : 
/home/ludovic/src/xmrig/algo/cryptonight/cryptonight.c:28:10: fatal error: mm_malloc.h: No such file or directory
 #include <mm_malloc.h>
          ^~~~~~~~~~~~~
Any idea where that file comes from ?

**Comment by psychocrypt** [comment]
xmr-stak is only supporting x86 based cpu systems.

**Comment by Zenitur** [comment]
Will developers add ARM processors support? IMHO the main reason to add it is the official OpenCL support in VideoCore V, the new GPU of the Broadcom. I think they'll release Raspberry Pi 4 with the new GPU in few months. Also there is unofficial OpenCL support for the VideoCore IV, GPU of a Raspberry Pi 1 - 3. [The install script](https://github.com/doe300/VC4CL/wiki/How-to-get) will download nightly builds made in Debian 9 Stretch (Raspbian 9). Then you need to install DEB packages:
```
sudo apt-get install clinfo
sudo dpkg -i /tmp/vc4cl-stdlib.deb
sudo apt-get -f install
sudo dpkg -i /tmp/vc4c.deb
sudo apt-get -f install
sudo dpkg -i /tmp/vc4cl.deb
```
There is [clinfo output on RPi 3](https://pastebin.com/aQtG1UcT).

Also I'd collect some ARMv8 processors info. Cortex A53 processor used in RPi 3 has [an official specification](https://developer.arm.com/docs/ddi0501/latest/introduction/about-the-cortex-a53-processor-cryptography-extension). It declares that "The optional Cryptography Extension is not included in the base product". Some vendors are adding AES ARM64 CE on it's ARMv8 CPUs, some not. The question is did Broadcom it on their's Cortex A53 processors?

No. I'd found some RPi miner on a github (I'd failed to found it twice) with the tests. Author says that the only software AES is supported in RPi, it give some boost, but it's small.

Also I'd found these ARMv8 miner: https://github.com/hyc/wolf-xmr-miner/tree/armv8 It cannot run on Raspbian because there is no 64-bit Raspbian variant (but there are unofficial 64-bit kernels for it).
