### ISSUE TITLE
Config option to set maximum system load

### ISSUE THREAD

**Issue by WyseNynja** [fireice-uk/xmr-stak#154]
I run xmr-stak on a system with several other processes and sometimes I have to stop mining (or limit to 1 thread) while my server does some heavy lifting. I can nice xmr-stak, but I think it could be really neat if xmr-stak could automatically add or remove mining threads based on system load.  For example, on my system I don't want it to ever have more than 4 threads and if my server is busy transcoding, I want it to drop down to 1 thread so that the transcode can go faster.  I can build something that watches system load, updates the config, and restarts the miner, but having this built into xmr-stak would be easier and save on needing to restart which costs downtime.

**Comment by JayWalker512** [comment]
I [wrote a script](https://github.com/jaywalker512/moneroman) that does what you described: restarts the miner with a light config when it detects certain processes are running. I'm sure it could be adapted to watch for load easily. 

The overhead of restarting the miner is probably minimal, but one of the devs could speak more to that point.

**Comment by fireice-uk** [comment]
There is no way to add/remove mining threads without rebooting the miner, even in the code.  Closing as this is unlikely to be implemented.
