### ISSUE TITLE
Compilation error " ‘to_string’ is not a member of ‘std’"

### ISSUE THREAD

**Issue by rkinkopf** [fireice-uk/xmr-stak#1540]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Intel i5-520M 2.5ghz
  - Type of the GPU -none

# Compile issues
  - Which OS do you use? Ubuntu 16.04
  
  add **all** commands you used and the **full** compile output here
 

*** Compile output start ****
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/jonathonf/gcc-7.1/ubuntu artful Release' does not have a Release
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc-5 is already the newest version (5.5.0-1ubuntu2).
g++-5 is already the newest version (5.5.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
 Backport of GCC 7.1 from Artful
 More info: https://launchpad.net/~jonathonf/+archive/ubuntu/gcc-7.1
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmpc78lmj9g/pubring.gpg' created
gpg: /tmp/tmpc78lmj9g/trustdb.gpg: trustdb created
gpg: key 8CF63AD3F06FC659: public key "Launchpad PPA for J Fernyhough" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
cmake is already the newest version (3.9.1-1).
libhwloc-dev is already the newest version (1.11.5-1).
libmicrohttpd-dev is already the newest version (0.9.55-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu13.5).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Cloning into 'xmr-stak'...
remote: Counting objects: 4689, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 4689 (delta 0), reused 21 (delta 0), pack-reused 4667
Receiving objects: 100% (4689/4689), 1.39 MiB | 5.92 MiB/s, done.
Resolving deltas: 100% (3335/3335), done.
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rick2/xmr-stak/build
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  7%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 15%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 19%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 23%] Linking C static library bin/libxmr-stak-c.a
[ 23%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 30%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from /home/rick2/xmr-stak/xmrstak/version.cpp:1:0:
/home/rick2/xmr-stak/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
/home/rick2/xmr-stak/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 1000)) ;
                                 ^
CMakeFiles/xmr-stak-backend.dir/build.make:86: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/ve
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
**** Compile output end ****

**** Compile commands Start ****
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-5 g++-5
sudo add-apt-repository ppa:jonathonf/gcc-7.1

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
# cmake -DOpenCL_ENABLE=OFF  -DCUDA_ENABLE=OFF  -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 ..
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF  ..
make install
*** Compile commands End ****

# Issue with the execution
  - Do you compiled the miner by our own?
  yes

  run `./xmr-stak --version-long` and add the output here
didn't compile, so can't run, but build script clones from "git clone https://github.com/fireice-uk/xmr-stak.git"

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  Number of platforms         0

# Stability issue
  - Is the CPU or GPU overclocked? no 
  - Is the Main memory of the CPU or GPU undervolted? no

**Comment by Spudz76** [comment]
CMake is still picking up GCC 5.4.1 which might be most of the problem
