### ISSUE TITLE
bad json

### ISSUE THREAD

**Issue by rain534** [fireice-uk/xmr-stak#1541]
Hi. I'm using the lates 2.4.3 version.
When using a web server for get statistics from the program and if there are connection errors in the log (Network error log) with newline characters (i think). Request for json from http://hostname:8080/api.json
return "SyntaxError: JSON.parse: bad control character in string..." 
See attached  files with http and json requests.

![default](https://user-images.githubusercontent.com/36900336/39643198-a48e05ac-4fdc-11e8-94f0-8e5bbc74a6da.png)

![default](https://user-images.githubusercontent.com/36900336/39643228-c0b06b30-4fdc-11e8-817a-548e877f173a.png)

**Comment by h0h0h0** [comment]
post your json

**Comment by rain534** [comment]
My json is very simple, i fetch all.
request:
$ curl http://localhost:8080/api.json
reply:
{"version":"xmr-stak/2.4.3/26a5d65/master/lin/cpu/aeon-cryptonight-monero/10","hashrate":{"threads":[[103.4,101.5,108.6],[62.6,61.4,64.9]],"total":[166.0,162.9,173.5],"highest":184.7},"results":{"diff_current":120001,"shares_good":5,"shares_total":5,"avg_time":778.8,"hashes_total":600005,"best":[251293,210698,162972,122252,121639,0,0,0,0,0],"error_log":[]},"connection":{"pool": "xmr-eu2.nanopool.org:14444","uptime":3894,"ping":72,"error_log":[]}}

Everything is good here.

When we have an errors in "Network error log"
request:
$ curl http://localhost:8080/api.json
reply:
{"version":"xmr-stak/2.4.3/26a5d65/master/lin/cpu/aeon-cryptonight-monero/10","hashrate":{"threads":[[103.8,101.5,null],[62.6,61.3,null]],"total":[166.4,162.8,null],"highest":179.3},"results":{"diff_current":120001,"shares_good":0,"shares_total":1,"avg_time":0.0,"hashes_total":0,"best":[0,0,0,0,0,0,0,0,0,0],"error_log":[{"count":1,"last_seen":1525588861,"text":"[NETWORK ERROR]"}]},"connection":{"pool": "not connected","uptime":0,"ping":0,"error_log":[{"last_seen":1525588687,"text":"[xmr-eu2.nanopool.org:14444] CONNECT error: Connection timed out"},{"last_seen":1525588861,"text":"[xmr-eu1.nanopool.org:14433] CALL error: Timeout while waiting for a reply"},{"last_seen":139645,"text":"[xmr-eu2.nanopool.org:14444] CONNECT error: Connection timed out"},{"last_seen":0,"text":"[xmr-eu1.nanopool.org:14433] 139645616535160:error:0200206E:system library:connect:Connection timed out:bss_conn.c:246:host=xmr-eu1.nanopool.org:14433
139645616535160:error:20073067:BIO routines:CONN_STATE:connect error:bss_conn.c:249:
"},{"last_seen":0,"text":"[xmr-eu2.nanopool.org:14444] CONNECT error: Connection timed out"}]}}

Json parser raise an error "bad control character in string literal..."
I think, it's because reply has a newline characters before "139645616535160:error..." and after "bss_conn.c:249:".
So, this is a bug in xmr-stak.

I don't know how to get selective response, please, tell me how I can request only hashrate.total[1], for example.

Thanks.

**Comment by rain534** [comment]
patch from the issue #1111 fixed the problem.
Under linux i didn't use caret return in regex.
