### ISSUE TITLE
Always MEMORY ALLOC FAILED: mmap failed on macOS

### ISSUE THREAD

**Issue by nozombieWK** [fireice-uk/xmr-stak#1542]
I always get "MEMORY ALLOC FAILED: mmap failed” which usually doesn’t appear on Windows10 when I start xmr-stak on macOS 10.13. And I won't get a hash rate as high as that on Windows10. I think running on macOS should be better than running on Windows10.

So what should I do, to get a higher hash rate on macOS 10.13 ?
Thx a lot.

# Issue with the execution
  - Do you compiled the miner by our own?
  Yes.
  - run `./xmr-stak --version-long` and add the output here
  Version: xmr-stak/2.4.3/26a5d65f/unknown/mac/cpu/aeon-cryptonight-monero/0

**Comment by Spudz76** [comment]
There is no setting apparently, but the best chance of obtaining the contiguous free memory allocation is at fresh reboot.
