### ISSUE TITLE
Add "currency" option inline with "pool_list" - Enhancement

### ISSUE THREAD

**Issue by Bathmat** [fireice-uk/xmr-stak#1548]
I was just wondering if it would be possible to move the `"currency"` selection to be in the same line with each pool under the `"pool_list"` section. E.g., be able to specify `monero7` pools and `cryptonight_heavy` in the same `pools.txt` config. This would allow for more robust failover options.

I realize this would require the miner to switch algos without shutting down/restarting the program, and I'm not sure how feasible that is, but I thought I'd ask.

Also, sorry if this has already been brought up/discussed.

**Comment by psychocrypt** [comment]
This also require cpu, nvidia and amd config per pool. This would be
complicated to configure.
