### ISSUE TITLE
Add more flags so xmr-stak can run without any interactive questions

### ISSUE THREAD

**Issue by WyseNynja** [fireice-uk/xmr-stak#155]
I run xmr-stak-cpu on a few systems and with the old release I had a script that would sed some environment variables into the default config and then start the miner.  The new release doesn't have that config file anymore. Rather than build something to write it, it would be a lot easier for me if everything that could be set in the text configs could also be set as flags.

Right now if you do `xmr-stak --url "$POOL" --user "$LOGIN" --pass "$PASS"` it prompts `Does this pool port support TLS/SSL? Use no if unknown. (y/N)`.  A flag for this and any other options would make it easy to script this. Interactive prompts are user friendly, but not very friendly to scripts.

A flag for maximum threads (or better yet, maximum load with some auto-scaling-- https://github.com/fireice-uk/xmr-stak/issues/154) would be very helpful, too.

**Comment by fireice-uk** [comment]
Thanks for spotting it! We will add it to dev in a couple of days.

**Comment by Clintoxen** [comment]
I agree with you, but for now you can copy the config you made with the exe and it will skip all of the questions and go straight to mining when you start it

**Comment by sergneo** [comment]
Why do I like this miner who immediately throws the error? My PC Core2Duo E8400 and a Nvidia 8600GT.
![xmr-stak-error](https://user-images.githubusercontent.com/27492679/33005351-7a1e3248-cdd6-11e7-8588-68fdf17f346b.jpg)

**Comment by psychocrypt** [comment]
After the first start all co fig files will be created. If the config files
are available than the miner will not ask any questions. You can use the
miner in your scriped environment.

**Comment by sergneo** [comment]
miner does not work with nvidia driver 378.78
![xmr-stak-error2](https://user-images.githubusercontent.com/27492679/33007063-046ae836-cdde-11e7-848f-6052ccbbd61c.jpg)

**Comment by sergneo** [comment]
Default miner is not true determines the parameters of the GPU. For example the optimal settings for GT730:
"threads" : 24, "blocks" : 16,
"bfactor" : 8, "bsleep" : 100,
![xmr-stak-error3](https://user-images.githubusercontent.com/27492679/33008212-460204b4-cde3-11e7-9a6b-8e70684da570.jpg)

**Comment by psychocrypt** [comment]
@sergneo please open a new issue for your problem. This issue is a feature request!

**Comment by lh1008** [comment]
@sergneo yesterday I had the same issue. Your windows doesn´t have installed the OpenCL.dll, or there is an error in the OpenCL.dll file. I downloaded the OpenCL.dll and installed and it worked. Got it from this site [dll4free](https://www.dll4free.com/opencl.dll.html). Use it at your own risk, follow instructions.

**Comment by fireice-uk** [comment]
@lh1008 and others. Please DO NOT use "missing dll" sites. You wouldn't use a "missing exe" site, would you? DLL is an EXE file.

**Comment by lh1008** [comment]
Ok @fireice-uk....I'm new on this, what can we do with the error showing up?

**Comment by lh1008** [comment]
@fireice-uk ..... I removed the dll exe file.  I´m new on this and what I did was clicked ok to the error, and the miner started by itself. Is this ok?
![capture](https://user-images.githubusercontent.com/7443480/33156391-4d61f2a6-cfc7-11e7-8268-010237c1fd21.PNG)
Thank you :)

**Comment by lh1008** [comment]
Thank you.. :), I removed the dll files. Started the miner and its working correctly. The error showed up, but then I clicked ok, and the miner continued without any issues. When I first got the message I was in a rush and just closed it and went to find the files. I´m new in this, so I have to be more careful. Thank you for support. If I get any issues I´ll be back for help. Great day.
