### ISSUE TITLE
Hellp for a Noob please

### ISSUE THREAD

**Issue by MrMyerss** [fireice-uk/xmr-stak#1550]
hey guys have been ruining xmr stak since today and have got me a nice config boosted h/s by 200 but how can i only mine with the gpu not my cpus i did change the 

set_cpu_affinty 0 
set_cpu_affinty 1

to 

set_cpu_affinty false , but it seems like the cpu is still active?

**Comment by Simaex** [comment]
You have to start xmr-stak with --noCPU option
You can get list of all available options using --help option
[https://github.com/fireice-uk/xmr-stak/blob/master/doc/usage.md#command-line-options](url)

**Comment by borzaka** [comment]
If you do not wish to mine with your CPU(s) then use:
`"cpu_threads_conf" : null,`

In cpu.txt.
