### ISSUE TITLE
AMD accelerated parallel processing app sdk (bad link) 

### ISSUE THREAD

**Issue by rivierer1** [fireice-uk/xmr-stak#1556]
There is a bad link under the "compile for Linux" section 
Compile xmr-stak for Linux
Install Dependencies
AMD APP SDK 3.0 (only needed to use AMD GPUs)
download and install the latest version from **http://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/**

**Comment by BonitaTerror** [comment]
@rivierer1 hello. I am wondering why this issue was closed. The link is still bad for me as well

**Comment by rivierer1** [comment]
I found a mirror on a different ticket...
https://github.com/fireice-uk/xmr-stak/issues/1511
