### ISSUE TITLE
NEED help

### ISSUE THREAD

**Issue by den4ik66** [fireice-uk/xmr-stak#1558]
hi everybody... cant start xmr-stak as service .. debian 9
get error
xmr-stak service

[Unit]
Description=her
After=network.target

[Service]
ExecStart=/home/her/her -c /home/her/config.txt -c /home/her/cpu.txt -c /home/her/pools.txt
User=root

[Install]
WantedBy=multi-user.target

May 10 00:16:38 vm01 her[410]:         - monero7
May 10 00:16:38 vm01 her[410]:         - stellite
May 10 00:16:38 vm01 her[410]:         - sumokoin
May 10 00:16:38 vm01 her[410]: - Please enter the currency that you want to mine:
May 10 00:16:38 vm01 her[410]:         - aeon7
May 10 00:16:38 vm01 her[410]:         - bbscoin
May 10 00:16:38 vm01 her[410]:         - croat
May 10 00:16:38 vm01 her[410]:         - cryptonight
May 10 00:16:38 vm01 her[410]:         - cryptonight_heavy
May 10 00:16:38 vm01 her[410]:         - cryptonight_lite

**Comment by fireice-uk** [comment]
WorkingDirectory=/home/her/xmr-stak
ExecStart=/home/her/xmr-stak/xmr-stak

put configs with their default names in /home/her/xmr-stak

**Comment by den4ik66** [comment]
doesn`t work

**Comment by psychocrypt** [comment]
You used three times -c and increased the numbet of - before c. Please run
xmr-stak -h to see the correct options.
