### ISSUE TITLE
GPU mining not working on iMac Pro with Windows 10

### ISSUE THREAD

**Issue by sholladay** [fireice-uk/xmr-stak#1559]
Hi and thanks for making this. In general, it works very well. 👏 

I'm experiencing a problem where `xmr-stak` seems to not be utilizing the GPU on an iMac Pro running Windows 10.

![no-gpu-use](https://user-images.githubusercontent.com/3674950/39852372-31117d40-53ea-11e8-88cb-d37f0ec02b07.PNG)

I tried downloading the latest driver from AMD, it is up to date.

I see these relevant lines when starting `xmr-stak`:
```
WARNING: NVIDIA Insufficient driver!
[2018-05-10 00:16:03] : WARNING: backend NVIDIA disabled.
[2018-05-10 00:16:03] : Compiling code and initializing GPUs. This will take a while...
[2018-05-10 00:16:04] : Device 0 work size 8 / 32.
[2018-05-10 00:16:04] : OpenCL device 0 - Load precompiled cod from file C:\Users\Seth Holladay\AppData\Local/.openclcache/bc1e950d628eb86db04a4ba3d262d1eaa567660e1bf29b22a7be6409ab54c466.openclbin
[2018-05-10 00:16:04] : Starting AMD GPU thread 0, no affinity.
```

If I understand correctly, the NVIDIA warnings are expected, since there is no NVIDIA hardware in here. And since it doesn't have any complaints about AMD, it seems to be detecting the Vega and its driver.

The `amd.txt` file was created, here are its contents (minus only the header comment), in case it is relevant:
```
"gpu_threads_conf" : [
  // gpu: gfx901 memory:13567
  // compute units: 64
  { "index" : 0,
    "intensity" : 1536, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,
```

# Basic information
  - Type of the CPU.
    ```
    Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz, 3201 Mhz, 8 Core(s), 16 Logical Processor(s)
     ```
  - Type of the GPU (if you try to miner with the GPU).
    ```
    Radeon Pro Vega 64
    ```

# Compile issues
  - Which OS do you use?
    Windows 10 Pro 64-bit

I am not compiling from source, but rather using the executable asset from GitHub

# Issue with the execution
  - Do you compiled the miner by our own?
    No.  
  - run `./xmr-stak --version-long` and add the output here
    ```
    Version: xmr-stak/2.4.2/e10e8e67/unknown/win/nvidia-amd-cpu/aeon-cryptonight-monero/0
    ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```
<details>
    <summary><b>`clinfo` output</b></summary>
    <pre><code>
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2442.9)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices

  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon Pro Vega 64
  Device Topology:                               PCI[ B#243, D#0, F#0 ]
  Max compute units:                             64
  Max work items dimensions:                     3
    Max work items[0]:                           256
    Max work items[1]:                           256
    Max work items[2]:                           256
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1350Mhz
  Address bits:                                  64
  Max memory allocation:                         14360458035
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            17163091968
  Constant buffer size:                          14360458035
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          1475556147
  Max global variable size:                      12924412160
  Max global variable preferred total size:      17163091968
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00007FFCB2ED4168
  Name:                                          gfx901
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                2442.9 (PAL,HSAIL)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (2442.9)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash

  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     1002h
  Board name:
  Max compute units:                             16
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           1024
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   2
  Preferred vector width float:                  8
  Preferred vector width double:                 4
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3192Mhz
  Address bits:                                  64
  Max memory allocation:                         8514335744
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            8192
  Max image 2D height:                           8192
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   4096
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    32768
  Global memory size:                            34057342976
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Global
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          4219368448
  Max global variable size:                      1879048192
  Max global variable preferred total size:      1879048192
  Max read/write image args:                     64
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     1
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    320
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   00007FFCB2ED4168
  Name:                                          Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  Vendor:                                        GenuineIntel
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2442.9 (sse2,avx)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2442.9)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event
    </code></pre>
</details>

# Stability issue
  - Is the CPU or GPU overclocked?
    No
  - Is the Main memory of the CPU or GPU undervolted?
    No

**Comment by psychocrypt** [comment]
is the miner crashing? Press the key h after 1min in the terminal. Than you
will see the hashrate.

**Comment by psychocrypt** [comment]
Do not thrust windows ;-) The percentage are only showing gpu grafic
utilization not computing. If the miner shows that you are hashing and the
pool also does it than you are mining.

**Comment by sholladay** [comment]
I'm not so certain. The Task Manager on a different machine (a MacBook Pro, same version of Windows) showed the same thing and had a lower hashrate than I was expecting. So I downloaded the latest NVIDIA drivers for it and when I restarted, the hashrate had tripled and Task Manager started showing full GPU utilization. I suppose it could be a difference between NVIDIA and AMD, but overall I feel pretty convinced that the Task Manager is accurately displaying GPU usage. The 1 kh/s I'm seeing also doesn't make sense for the iMac Pro's specs. It's a very fast machine. 1 kh/s seems right for only the CPU, though.

Is there anything I can do to further prove or debug what is going on?

**Comment by psychocrypt** [comment]
1KH/S for monero is a lot. A fast cpu will not reach 1kh/s. Please post a
the output which is shown if you press the key h

**Comment by sholladay** [comment]
For some reason, pressing the <kbd>h</kbd> key while `xmr-stak.exe` is running did not do anything. I tried both Command Prompt and PowerShell.

Perhaps you are right, though... here is the HTTP dashboard.

![hashrate-report](https://user-images.githubusercontent.com/3674950/39888268-50f1a2de-5462-11e8-8ed1-3ff7ead81d4a.PNG)

According to the terminal output, thread 0 is the GPU, and the HTTP dashboard does show it having a much higher hashrate. So case closed, I guess. Still seems odd that it isn't being reported correctly to Windows. Maybe something to do with OpenCL?

I was using a GUI before that didn't show the per-thread hashrate. So thanks for the pointer!

**Comment by xq0404** [comment]
I have a MacBook Pro with 64-bit Windows 7 installed through Bootcamp. The GPU is recognized after the xmr-stak is launched, but the reported hashrate is zero when I type H.

**Comment by xq0404** [comment]
My Macbook Pro uses Intel (R) Core(TM) i7-2675QM CPU @ 2.20GHz 2.20 GHz
My GPU is AMD Radeon HD 6750M 
Bootcamp has Windows 7 Service Pack 1 installed.
