### ISSUE TITLE
XMR not reporting Hash rate since Windows 10 1803 update

### ISSUE THREAD

**Issue by chc-pr** [fireice-uk/xmr-stak#1560]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
AMD A8
  - Type of the GPU (if you try to miner with the GPU).
Vega 56

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
No
  ```
  run `./xmr-stak --version-long` and add the output here
Version: xmr-stak/2.4.3/26a5d65f/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20
  ```

# AMD OpenCl issue
  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

Odd behaviour. Worked fine until Windows 10 update this AM - then it stopped working. Apparently hashing, but reporting hashes as '0'. CPU is disabled - but pool is reporting accepting some hashes

**Comment by JerichoJones** [comment]
I had to remove and re-install the driver after the update.
