### ISSUE TITLE
after I use the linux portable binary, I can no longer ssh into the machine

### ISSUE THREAD

**Issue by varung** [fireice-uk/xmr-stak#157]
I ran the commands in /root for using linux portable binary
After this I get permission denied when ssh'ing (and ssh worked right before)
Is this malware?

**Comment by psychocrypt** [comment]
No that is no malware. After you get your access back could you please
provide use with the logs. I think it has nothing to du with xmr-stak.
Maybe we have a bug and do an illegal memory access which can crash the
system if you running the miner as root.
btw: please do not run software aus root use always user accounts with
reduced access rights!!

**Comment by varung** [comment]
running it not out of the /root folder works. I'm really confused by what happens when I run it as root.
