### ISSUE TITLE
2.4.3 randomly stucks sometime

### ISSUE THREAD

**Issue by Retia-Adolf** [fireice-uk/xmr-stak#1571]
CPU and GPUs are working and heating, but hashrates reports 0 in mining pool, and no responding when access 127.0.0.1 with httpd_port, no responding when press h, r, or c in xmr-stak console.

CPU: Threadripper 1950X @4.01 GHz, 1.3 V
	(using 8 physical cores of Node 1)

RAM: 1x Micron DDR4 3000 8GB

GPU: 
- 2x Vega FE
- 1x RX Vega 64
- 1x R9 290

OS: Windows 10 64bit Version 1709, Build 16299.431

Driver: [Radeon Software Adrenalin Edition 18.3.4](https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-18.3.4-Release-Notes.aspx)

xmr-stak release: 2.4.3 26a5d65f

GPU OverdriveNTool Config:
```
[Profile_0]
Name=Vega64
GPU_P0=852;800
GPU_P1=1138;900
GPU_P2=1302;950
GPU_P3=1348;1000
GPU_P4=1408;1050
GPU_P5=1560;1100
GPU_P6=1668;1150
GPU_P7=1407;900
Mem_P0=167;800
Mem_P1=500;800
Mem_P2=800;900
Mem_P3=1105;900
Fan_Min=3300
Fan_Max=3300
Fan_Target=65
Fan_Acoustic=1500
Power_Temp=70
Power_Target=-15

[Profile_1]
Name=R9_290
GPU_P0=300;993;0
GPU_P1=483;1250
GPU_P2=662;1250
GPU_P3=841;1243
GPU_P4=881;1250
GPU_P5=914;1250
GPU_P6=939;1250
GPU_P7=947;1250
Mem_P0=150;993;0
Mem_P1=1275;1250
Fan_Min=3000
Fan_Max=3000
Fan_Target=0
Fan_Acoustic=0
Power_Temp=95
Power_Target=-15

[Profile_2]
Name=Vega64FE
GPU_P0=852;800
GPU_P1=991;900
GPU_P2=1084;900
GPU_P3=1138;900
GPU_P4=1150;900
GPU_P5=1415;890
GPU_P6=1425;900
GPU_P7=1435;910
Mem_P0=167;800;0
Mem_P1=500;900;0
Mem_P2=800;950;0
Mem_P3=1100;870
Fan_Min=4900
Fan_Max=4900
Fan_Target=60
Fan_Acoustic=0
Power_Temp=70
Power_Target=-15
```

**Comment by Simaex** [comment]
Try to follow issue reporting guidelines. The only thing that can be recommended with the given data is to pull out R9-290 that usually do not play well along with VEGA's due to driver limitations.
