### ISSUE TITLE
Dev Pool Socket Error, see #919, #853

### ISSUE THREAD

**Issue by gigacorn** [fireice-uk/xmr-stak#1576]
Dev Pool Socket error since at least 18/05 at 06:00 GMT. @fireice-uk, you asked me to report these here, I'm guessing TLS is down again.

I know that you don't agree that the Dev Pool Socket error can cause Stak to crash, but I am positive it does. I have 5 total rigs, all have been running without interruption for 1+ week, now 3 of 5 have gone down since the Dev Pool Socket error began.

**Comment by psychocrypt** [comment]
The dev pool is down since yesterday. Mining without fees for everyone :-)
Could you please send us the log from the crashed miner.

**Comment by Spudz76** [comment]
What do you have your retry timeouts set at?

**Comment by gigacorn** [comment]
Log below. The consistent pattern is after a failed Dev pool connection attempt (not every time, maybe twice a day per rig) it will spit out a Connection, Results, and Hashrate report then crash. Verbose logging is set to 1. "call_timeout" : 20, "retry_time" : 30, "giveup_limit" : 0,

[2018-05-21 00:09:14] : Fast-connecting to dev pool ...
[2018-05-21 00:09:35] : Dev pool socket error - mining on user pool...
[2018-05-21 00:10:05] : Fast-connecting to dev pool ...
[2018-05-21 00:10:05] : Dev pool connected. Logging in...
[2018-05-21 01:49:14] : Fast-connecting to dev pool ...
[2018-05-21 01:49:35] : Dev pool socket error - mining on user pool...
[2018-05-21 01:50:05] : Fast-connecting to dev pool ...
[2018-05-21 01:50:26] : Dev pool socket error - mining on user pool...
[2018-05-21 01:50:55] : Fast-connecting to dev pool ...
[2018-05-21 01:51:16] : Dev pool socket error - mining on user pool...
[2018-05-21 03:29:14] : Fast-connecting to dev pool ...
[2018-05-21 03:29:14] : Dev pool connected. Logging in...
[2018-05-21 05:09:14] : Fast-connecting to dev pool ...
[2018-05-21 05:09:17] : Dev pool connected. Logging in...
CONNECTION REPORT
Pool address    : xmr-us-east1.nanopool.org:14444
Connected since : 2018-05-20 20:51:15
Pool ping time  : 192 ms

Network error log:
Yay! No errors.
RESULT REPORT
Difficulty       : 120001
Good results     : 1834 / 1879 (97.6 %)
Avg result time  : 15.9 sec
Pool-side hashes : 220081834

Top 10 best results found:
|  0 |        405112462 |  1 |        141723439 |
|  2 |         74428143 |  3 |         65148784 |
|  4 |         33211875 |  5 |         29133108 |
|  6 |         23029607 |  7 |         19102218 |
|  8 |         18009702 |  9 |         17215654 |

Error details:
| Count | Error text                       | Last seen           |
|    45 | Block expired                    | 2018-05-21 05:07:09 |
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   52.1 |   61.1 |   37.3 |  1 |   18.8 |   19.9 |   45.7 |
Totals (CPU):    70.9   81.1   83.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  896.1 |  889.7 |  889.1 |  1 |  881.9 |  892.1 |  889.1 |
|  2 |  967.3 |  965.9 |  966.8 |  3 |  969.6 |  967.9 |  966.7 |
|  4 |  924.7 |  925.9 |  924.7 |  5 |  925.3 |  924.8 |  924.8 |
|  6 |  912.8 |  921.9 |  922.6 |  7 |  931.2 |  922.5 |  922.7 |
Totals (AMD):  7409.1 7410.8 7406.4 H/s
-----------------------------------------------------------------
Totals (ALL):   7480.0 7491.9 7489.4 H/s
Highest:  7507.7 H/s

**Comment by psychocrypt** [comment]
Thx for the log. We will release tomorrow a nee version with a lot
fixes/improvements in the job consumption part of the miner.

**Comment by gigacorn** [comment]
Great news. Any thoughts on when the socket error will be resolved? Is that fix part of the new release?

**Comment by psychocrypt** [comment]
The dev pool socket error should be gone if you restart the miner. The dev
pool is back in action since yesterday

**Comment by gigacorn** [comment]
Thanks, no socket errors for 9 days, closing.
