### ISSUE TITLE
404 on link from compile_Linux.md

### ISSUE THREAD

**Issue by BonitaTerror** [fireice-uk/xmr-stak#1577]
I am following the compile instructions found in compile_Linux.md and everything is going well so far except that the link to the page for the AMD APP SDK is giving me a 404. I am running the XFCE spin of Fedora 28 and I cannot seem to find a way to install this sdk in order to compile xmr stak for use with my AMD GPUs

Obviously since I cannot install this SDK I am getting the error "Could NOT find OpenCL". All I need is some more info on this SDK and hopefully find out how to install it.

**Comment by xpat07** [comment]
Unbuntu
sudo apt-get install opencl-headers
apt install ocl-icd-opencl-dev
