### ISSUE TITLE
Dual Instance mining

### ISSUE THREAD

**Issue by neptune-klm** [fireice-uk/xmr-stak#1578]
Please provide as much as possible information to reproduce the issue.

# Basic information
6 x Vega 64-2 threads each
# Compile issues
Windows 10 Pro
# Issue with the execution
Stak 2.4.3

I am trying to dual mine splitting my GPU's according to the coin.  I open the first instance and hashrate is appropriate.  When I open the 2nd instance, the hashrate on the 1st opened instances drops off but the 2nd opened instance is fine.  Is this a simple fix or is version 2.4.3 not set up for running more than 1 instance?

Instance 1 amd config (Monero)...
"gpu_threads_conf" : [
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 3, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 4, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true},
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 4, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true}
],

Instance 2 amd config (Sumo)...

"gpu_threads_conf" : [
 
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 5, "intensity" : 963, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 2, "mem_chunk" : 10, "comp_mode" : false},  
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 5, "intensity" : 963, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : 2, "mem_chunk" : 10, "comp_mode" : false},  
],

Also, not using cpu...

"cpu_threads_conf" :
null

**Comment by Spudz76** [comment]
I have run dual process in the past to overcome CUDA not wanting to mix old and new cards, and it worked fine.  Could be an OpenCL thing.  Granted it was probably not 2.4.3 but it was after the fork patches.  I eventually physically split those cards into separate rigs it was clunky even though OK.

Agree your configuration seems correct and should work that way.  Perhaps AMD driver is doing something dumb when a second OpenCL session is opened (autoswitch away from Exclusive Compute mode or such?)
