### ISSUE TITLE
Nvidia 750 TI problems.

### ISSUE THREAD

**Issue by CaseyGramz** [fireice-uk/xmr-stak#1582]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - AMD FX 6300.
  - Nvidia EVGA 750 TI.
  - Gigabyte 970 G motherboard

# Compile issues
  - Windows 7 Professional Home Edition

# Issue with the execution
 Running 2.4.3 XMR STAK

# AMD OpenCl issue

CL closes when running clinfo

# Stability issue
 GPU OC, CPU at base levels. GPU not undervolted.

Basically, my GPU won't cooperate with my CPU in stak, and I'm not getting anything over like 39 h/s, when usually I get 254+ h/s for this specific card. I just installed this card, and my old HD into this motherboard/CPU build with a new PSU and water cooler. There really shouldn't be much different going on here. Reinstalled all drivers as best I could. Cuda updated, VS installed, everything I can think of and for some reason I'm not finding a answer to my problems anywhere. I've been all over the forums, google, discord, and I can't get the help I need.

**Comment by psychocrypt** [comment]
remove all configs,start theminer and post the generated configs and the
log of the first start
