### ISSUE TITLE
Don’t compile correctly with amdgpu-pro

### ISSUE THREAD

**Issue by yoburtu** [fireice-uk/xmr-stak#1583]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. Core i3
  - Type of the GPU (if you try to miner with the GPU).AMD Rx550

# Compile issues
  - Which OS do you use?
  Ubuntu 16.04.3

  add **all** commands you used and the **full** compile output 

I have problems with cmake command:

WARNING: Target "xmrstak_opencl_backend" requests linking to directory "/opt/amdgpu-pro/lib/x86_64-linux-gnu". Targets may link only to libraries. CMake is dropping the item.

The result of previous warning is that xmrstak_opencl_backend don’t links with opencl lib and then, the xmr-stak binary file compiled don’t supports opencl and don’t works with my amd Rx550 gpus.

Best regards.

**Comment by psychocrypt** [comment]
empty the build folder compile again and post al used commands and the
output.

**Comment by yoburtu** [comment]
I have solved including directly the opencl library in OpenCL_LIBRARY argument:

$ cmake -DOpenCL_LIBRARY=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so -DCUDA_ENABLE=OFF ..

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/xmr-stak/build
$ make install
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 30%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 33%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 43%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 46%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 53%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 60%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/uac.cpp.o
[ 63%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 70%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 73%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 80%] Linking CXX static library bin/libxmr-stak-backend.a
[ 80%] Built target xmr-stak-backend
Scanning dependencies of target xmrstak_opencl_backend
[ 83%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o
[ 86%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/jconf.cpp.o
[ 90%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/minethd.cpp.o
[ 93%] Linking CXX shared library bin/libxmrstak_opencl_backend.so
[ 93%] Built target xmrstak_opencl_backend
Scanning dependencies of target xmr-stak
[ 96%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[100%] Linking CXX executable bin/xmr-stak
[100%] Built target xmr-stak
Install the project...
-- Install configuration: "Release"
xmr-stak installed to folder 'bin'

But now, don’t works xmr-stak executable compiled:

$ ./xmr-stak 
-------------------------------------------------------------------
xmr-stak 2.4.3 26a5d65

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-05-20 10:52:20] : Mining coin: stellite
[2018-05-20 10:52:20] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-05-20 10:52:20] : WARNING: No OpenCL platform found.
[2018-05-20 10:52:20] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-05-20 10:52:20] : WARNING: backend AMD (OpenCL) disabled.
[2018-05-20 10:52:20] : Starting 1x thread, affinity: 0.
[2018-05-20 10:52:20] : hwloc: memory pinned
[2018-05-20 10:52:20] : Starting 1x thread, affinity: 1.
[2018-05-20 10:52:20] : hwloc: memory pinned
[2018-05-20 10:52:20] : Fast-connecting to Pool.XTL.CryptoPool.Space:5555 pool ...
[2018-05-20 10:52:20] : Pool Pool.XTL.CryptoPool.Space:5555 connected. Logging in...
[2018-05-20 10:52:20] : Difficulty changed. Now: 50000.
[2018-05-20 10:52:20] : Pool logged in.

**Comment by Spudz76** [comment]
Run as root or add user to `video` group
That is an access error.  You should be able to get output from `clinfo` and then things will begin working.

**Comment by yoburtu** [comment]
As root is the same. My user is in video group. But the clinfo command don’t work. Core dump!.

$ uname -a
Linux galadriel 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ id
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),44(video),46(plugdev),113(lpadmin),129(sambashare)

$ /opt/amdgpu-pro/bin/clinfo 
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

**Comment by Spudz76** [comment]
Well nothing will work until / unless the clinfo works.  Looks like a library issue, check content in `/etc/ld.so.conf.d/`

What is output of `ldd /opt/amdgpu-pro/bin/clinfo` as far as the libOpenCL.so references...

**Comment by yoburtu** [comment]
user@galadriel:~$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

user@galadriel:~$ ls /etc/ld.so.conf.d
amdgpu-pro-i386.conf            i386-linux-gnu.conf  x86_64-linux-gnu.conf
amdgpu-pro-x86_64.conf          libc.conf            x86_64-linux-gnu_EGL.conf
fakeroot-x86_64-linux-gnu.conf  rocm-x86_64.conf     x86_64-linux-gnu_GL.conf

user@galadriel:~$ cat /etc/ld.so.conf.d/amdgpu-pro-x86_64.conf 
/opt/amdgpu-pro/lib/x86_64-linux-gnu

user@galadriel:~$ ldd /opt/amdgpu-pro/bin/clinfo 
        linux-vdso.so.1 =>  (0x00007fff031b9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb5918ee000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb5915e5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb5913e1000)
        libOpenCL.so.1 => /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007fb5911da000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb590fc4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb590da7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb5909dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb591af6000)

**Comment by Spudz76** [comment]
That all looks fine, is the driver loading OK in dmesg?

4.13 is working for me on multiple rigs so it's not the kernel.  Which amdgpu version?

**Comment by yoburtu** [comment]
I have solved!.

I installed amdgpu-pro-18.10-NNNNNN.tar.xz driver and now works fine!.

How can I install rocm for adjust overclock of graphic cards?.

**Comment by zjhxmjl** [comment]
@yoburtu hi,guy!what's hashrate with vega 56 on ubuntu 16.04？thx

**Comment by yoburtu** [comment]
I do not have a vega 56. I'm sorry. Regards.
