### ISSUE TITLE
Single rx Vega 56 - Hash Drop compared to xmr-stak-amd

### ISSUE THREAD

**Issue by amdvega** [fireice-uk/xmr-stak#159]
With the default generated amd.txt I get ~1350 H/s.  Copy/pasted gpu config from xmr-stak-amd's config.txt and now getting ~1835 H/s.  However, in xmr-stak-amd I get ~1865 H/s.  Config below:

"gpu_thread_num" : 2,
/*
 */
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 0, "intensity" : 1600, "worksize" : 8, "affine_to_cpu" : false },
],
/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

**Comment by psychocrypt** [comment]
we added a few bug fixes. Maybe this is the reason for the 1.3% drop.

**Comment by gizmocruncher** [comment]
I saw the same drop when setting the intensity of the first thread to 2016 and the second to 1600. After setting them both to 1932, the performance seems comparable.

**Comment by amdvega** [comment]
Unfortunately my card crashes when setting both to 1932.  I get snowy static on the screen and then can't see anything and have to hard power cycle the box.  I'm using circusdad's blogspot guide, but that 1932 intensity setting definitely crashes me out.  After going through that guide I was able to squeeze out a few more H/s on xmr-stak-amd.  Now stable at 1876 at .875v on GPU core.  1900+ is elusive for me.  On xmrstak2 still pulling around 1835.  Not sure what "bug fixes" went in but looks like I'm on xmr-stak-amd for now.
