### ISSUE TITLE
Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by tleunen** [fireice-uk/xmr-stak#1597]
Having this error when trying to run cmake on macos. Any idea how to resolve it?
```
❯ cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=ON
CMake Error at /usr/local/Cellar/cmake/3.11.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.11.2/share/cmake/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:280 (find_package)
```

**Comment by psychocrypt** [comment]
It looks like pthread dev package is not installed. Which os do you use.

**Comment by Spudz76** [comment]
I could only find [this](https://stackoverflow.com/questions/14171740/cmake-with-ios-toolchain-cant-find-threads) which has a few possible clues on solutions but is about cross-compiling for iOS although I think the proposed solutions there may work regardless of cross or host compiling (pthreads might be in a "bundle" now not discrete files? weird...)
