### ISSUE TITLE
Sapphire RX VEGA 64 Nitro+ Thread 0 Has Invalid Config issue

### ISSUE THREAD

**Issue by arabooo2** [fireice-uk/xmr-stak#1600]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Intel Core i5 7500 3.4GHz 6MB 1151P Processor
  - Sapphire RX VEGA 64 Nitro+

# Compile issues
  - Windows 10 Pro RS3 v.1709.16299.19 x64
  ```
  add **all** commands you used and the **full** compile output here
  ```
"gpu_threads_conf" : [
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 0,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 0,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 1,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 1,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 2,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 2,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 3,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 3,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 4,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 4,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 5,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 5,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 6,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 6,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
Yes
  ```
  run `./xmr-stak --version-long` and add the output here
  ```
xmr-stak 2.4.3 26a5d65f
# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Describe issue
-------------------------------------------------------------------
xmr-stak 2.4.3 26a5d65f

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-05-27 12:44:58] : Mining coin: monero7
WARNING: NVIDIA Insufficient driver!
[2018-05-27 12:44:58] : WARNING: backend NVIDIA disabled.
[2018-05-27 12:44:58] : Thread 0 has invalid config.
Press any key to exit.

I have used Sapphire Vega 64 – 2100 h/s from (https://www.xmrstak.com/2017/12/26/sapphire-vega-64-2100-h-s/#more-432)

Am I wrong?

Thnks

**Comment by arabooo2** [comment]
I have 7 x Sapphire RX VEGA 64 Nitro+ GPU. I'm trying to xmr-stak version 2.4.3 (latest version)

And I have used for My Sapphire Nitro+ Vega 64s "Sapphire Vega 64 – 2100 h/s"  from (https://www.xmrstak.com/2017/12/26/sapphire-vega-64-2100-h-s/#more-432)

But I'm getting this Error while starting XMR-Stak  program. Where am I making mistakes?

Thanks a lot of Dudes.

**Comment by Spudz76** [comment]
Also you probably want to use command line option `--noNVIDIA` so it stops bothering with CUDA detections.

**Comment by arabooo2** [comment]
Spudz76 says: Also you probably want to use command line option --noNVIDIA so it stops bothering with CUDA detections.

Where can I add this configuration? amd.txt or config.txt ?

Could you please share this section here?

**Comment by arabooo2** [comment]
My Full amd.txt output here.

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 * index         - GPU index number usually starts from 0
 * intensity     - Number of parallel GPU threads (nothing to do with CPU threads)
 * worksize      - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 2 = chunked memory, chunk size is controlled by 'mem_chunk'
 *                     required: intensity must be a multiple of worksize
 *                 1 or true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 0 or false = use a contiguous block of memory per thread
 * mem_chunk     - range 0 to 18: set the number of elements (16byte) per chunk
 *                 this value is only used if 'strided_index' == 2
 *                 element count is computed with the equation: 2 to the power of 'mem_chunk' e.g. 4 means a chunk of 16 elements(256byte)
 * comp_mode     - Compatibility enable/disable the automatic guard around compute kernel which allows
 *                 to use a intensity which is not the multiple of the worksize.
 *                 If you set false and the intensity is not multiple of the worksize the miner can crash:
 *                 in this case set the intensity to a multiple of the worksize or activate comp_mode.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 0,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 0,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 1,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 1,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 2,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 2,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 3,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 3,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 4,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 4,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 5,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 5,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 6,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 5, "strided_index" : true
 },
 // gpu: gfx900 memory:3920
 // compute units: 64
 { "index" : 6,
 "intensity" : 1932, "worksize" : 8,
 "affine_to_cpu" : 3, "strided_index" : true
 },

],

/*
•Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
 "platform_index" : 0,

**Comment by arabooo2** [comment]
I have change all the affine_to_cpu to false but I'm getting same error

-------------------------------------------------------------------
[2018-05-27 13:42:59] : Mining coin: monero7
WARNING: NVIDIA Insufficient driver!
[2018-05-27 13:42:59] : WARNING: backend NVIDIA disabled.
[2018-05-27 13:42:59] : Thread 0 has invalid config.
Press any key to exit.

**Comment by Spudz76** [comment]
triple backticks around pasted file content makes it actually usable/readable
backtick is the one on the ~ button

google command line argument and then you'll know where `--noNVIDIA` goes.  hint: make a shortcut to the exe if you run it by double clicking not from Command Prompt

Here is your amd.txt repaired like I instructed you.  Assuming you have 7 total identical AMD cards (you didn't bother to include the clinfo output, and didn't say you have 7 of them in your report either)

```

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 * index         - GPU index number usually starts from 0
 * intensity     - Number of parallel GPU threads (nothing to do with CPU threads)
 * worksize      - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 2 = chunked memory, chunk size is controlled by 'mem_chunk'
 *                     required: intensity must be a multiple of worksize
 *                 1 or true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 0 or false = use a contiguous block of memory per thread
 * mem_chunk     - range 0 to 18: set the number of elements (16byte) per chunk
 *                 this value is only used if 'strided_index' == 2
 *                 element count is computed with the equation: 2 to the power of 'mem_chunk' e.g. 4 means a chunk of 16 elements(256byte)
 * comp_mode     - Compatibility enable/disable the automatic guard around compute kernel which allows
 *                 to use a intensity which is not the multiple of the worksize.
 *                 If you set false and the intensity is not multiple of the worksize the miner can crash:
 *                 in this case set the intensity to a multiple of the worksize or activate comp_mode.
 * "gpu_threads_conf" :
 * [
 *   { "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 1,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 1,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 2,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 3,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 4,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 4,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 5,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 5,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 6,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },
  // gpu: gfx900 memory:3920
  // compute units: 64
  { "index" : 6,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : false
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

```
```

**Comment by Spudz76** [comment]
that source site is not ours as far as I know, just a "paste bucket" someone else made up

most/all the examples there can no longer be straight pasted in, you have to hand-copy over just the intensity/worksize and other things that remain the same meanings, and add the new stuff (and decide which way those should be, they didn't exist when whomever came up with those settings, but usually one of the selections is same-as-old-ways)

**Comment by arabooo2** [comment]
Thank you Spudz76! You're the King! :)
Config is running :) 1 Sapphire Nitro+ Vega 64 giving 1800 H/S is it OK?

and Finally Question If I don't want to CPU for mining , Which parameter do I need to change?

Should I make this 0? "affine_to_cpu" : 0,

I don't want use CPU, I want use only GPUs. 
I apologize for my poor English :)

**Comment by Spudz76** [comment]
To disable CPU with config files, make `cpu.txt` containing:
```
"cpu_threads_conf" : null,
```
and to disable CUDA with config files, make `nvidia.txt` containing:
```
"gpu_threads_conf" : null,
```

However it is more complete to set launch ('command line') options on a shortcut (if clicking to start) or on the command line in Command Prompt (if launch by typing).  `--noCPU` and `--noNVIDIA` which then won't even read the related cpu/nvidia config files (they don't have to exist then, and it won't try to recreate them new).

**Comment by Spudz76** [comment]
I do not know if 1800 is best/top score for that GPU setup, you may try adjusting the intensity up or down in worksize increments (plus or minus 8 each time) and see if it gets better or worse.

These settings/tunings are very very dependent on motherboard and cpu not just the GPU.  For instance if your i5 is not as good at PCIe communication as a Xeon someone else (on paste site) had used, the result can be different.

Think eating with different spoons, if you are using a smaller spoon (cpu/PCI wiring/resultant bandwidth) you would not get the same eating-rate as someone with a larger or more optimized spoon even if you are eating the same cereal (same coin/work) with the same size mouth (same GPU).

Also sometimes algorithm in miner changes so comparing results from earlier versions is not always meaningful on exact numbers.  Vega tends to change more as it is newest.  But an older claim of 2100 makes sense as 1800 on new versions, based only on issue reports here over time.  Many complaints of lost hashrate versus old versions (but can't use due to blockchain forks) but it is normal, more likely was display/measurement/calculation difference not an actual work speed difference.

Also everything can change per AMD driver release, who knows what they change, settings may be different if they do something in driver we don't know about (they don't always announce all changes with detail).
