### ISSUE TITLE
Old card support request

### ISSUE THREAD

**Issue by kulipasar** [fireice-uk/xmr-stak#1601]
I have 2 old AMD cards (HD 5830 & HD 5870)..
xmr-stak works nicelly on HD 5830  i got around  120 h/s..
but it was strange when it came to HD 5870 it was only 50 h/s..

i am using AMD 15.7.1 version for both cards...
i am not sure wether it is caused by the driver or not, suppose it is please suggest me for the right driver version as i believe HD 5870 has more power than its succesor...

**Comment by Simaex** [comment]
You should try 14.4 drivers for Terascale cards assuming you are running Windows 10. Also you have to play with intensity and worksize. Ex for HD6990 best worksize is usually 19, but range from 17 to 21 is worth trying. Check how much memory is detected by clinfo. If it do not meet actual card characteristics it is the source of low performance. Too high intensity may actually degrade performance also. In case you need more help please take care to fill issue template properly.
