### ISSUE TITLE
Electroneum (ETN) Network Upgrade

### ISSUE THREAD

**Issue by borzaka** [fireice-uk/xmr-stak#1603]
> First-Just a reminder that ETN’s Network Upgrade will be taking place tomorrow, 30th May at block height 307,500. We suggest that any exchanges or mining pools that have not updated their nodes should do so as a matter of urgency. If your exchange and mining pool nodes are not updated before block 307,500 your ETN will not be recognised by anyone who has completed the upgrade.
> 
> After block 307,500 it could take some time for the difficulty to normalise to the new hashing power so the first few hours’ worth of blocks is likely to take longer than normal to mine.
> 
> GPU/CPU miners also need to switch to Cryptonight Variant 1 software in preparation.

source: [Electroneum Facebook](https://www.facebook.com/electroneum/)

So;
- XMR-Stak is ready for the network upgrade?
- What is Cryptonight Variant 1?
- What settings should I use to mine Electroneum after the network upgrade?
- Can I start mining now and will it work auto after the upgrade, or it needs miner restarting/changing settings?
- Or this network upgrade is not affecting miners?

This is the [release note](https://github.com/electroneum/electroneum/releases/tag/v2.0.0.0) for the network upgrade:

> This release of the software presents several major improvements to Electroneum. Some highlights of this release are:
> 
> - Implementation of ASIC resistance
> - Increased of transaction base fee from 0.01 ETN to 0.1 ETN
> - Disabled RingCT
> - Disabled Mixin
> - Mempool life increased to 3 days
> - Move to 2 minute blocks
> - Reduced difficulty window to check every 360 blocks to adjust the difficulty every 12 hours

**Comment by randelsr** [comment]
Cryptonight variant 1 is the "asic resistant" version of the Cryptonight algorithm. This was the update done when Monero moved to Monero 7 and is the new algo for ETN.

So this said, once the fork has occurred,  you SHOULD be able to set xmr-stak to mine "monero7" and then point it at your etn pool of choice. 

I don't believe you'll be able to mine the new algo ahead of time unless xmr-stak implements a specific update. IIRC xmr-stak had it hardcoded for the Monero fork so it automatically changed to monero7 at the correct block height... but it was a few months ago, so.... not entirely sure. 

If anybody else has any advice please drop some knowledge!

**Comment by terrak** [comment]
In my pools.txt I changed the currency to : 

**"currency" : "cryptonight_v7",**

and I run this new pool when bloc 307500 is ready to mine.

This one do not depend of a specific bloc as monero7.

**Comment by borzaka** [comment]
I don't think this was the same update as Monero's one. Monero hard forked, and changed the mining algorithm.

According to the [official Electroneum wiki](https://wiki.electroneum.com/display/ESD/Electroneum+Fork+Update+-+30th+May+2018):

> **ASICs:** 
> We will be making our system ASIC resistant. You can still use ASICs to mine Electroneum but they won’t be as powerful as they were before the fork.

So, they can still mine Electroneum, but with a lower speed as before. It's not entirely ASIC resistant.

Changing `currency` to `cryptonight_v7` and mining Electroneum with XMR-Stak is not working now;
`Result rejected by the pool.`

**Comment by haidertech** [comment]
so what the best coin for x3

**Comment by njwyatt** [comment]
using ccminer2.3, what algo to use in ETN? algo=cryptonight cannot mine.

**Comment by psychocrypt** [comment]
you are asking the ccminer question in an xmr-stak issue. You should switch
over to mine with xmr-stak or ask this question again within an issue in
the ccminer github repo.
