### ISSUE TITLE
P106 xmr-stak issue

### ISSUE THREAD

**Issue by gguner** [fireice-uk/xmr-stak#1605]
I've 4x p106(8card) rig.
I've recently updated all my miner rigs driver version to 391.35. My previous version is 382.45

in 382.45 each p106  card performs 530-540 hash with 8 cards together working in 1 miner instance   .
After the 391.35 update strange things happens :) 

All cards have ;

   "threads" : 8, "blocks" : 144,
    "bfactor" : 7, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
 
and all cards have the same overclock settings.

If i run 8 cards together in 1 miner instance ;

HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  533.5 |   (na) |   (na) |  1 |  434.0 |   (na) |   (na) |
|  2 |  433.7 |   (na) |   (na) |  3 |  430.1 |   (na) |   (na) |
|  4 |  433.4 |   (na) |   (na) |  5 |  431.8 |   (na) |   (na) |
|  6 |  438.1 |   (na) |   (na) |  7 |  437.8 |   (na) |   (na) |
Totals (NVIDIA):  3572.5    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   3572.5    0.0    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------
Only the first card runs normally.All the other cards have low hash rates.

Then i try to split the instances.
Run 4 card in 1 instance and other 4 card in another instance 

HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  529.9 |   (na) |   (na) |  1 |  367.5 |   (na) |   (na) |
|  2 |  368.8 |   (na) |   (na) |  3 |  365.8 |   (na) |   (na) |
Totals (NVIDIA):  1632.1    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   1632.1    0.0    0.0 H/s
Highest:  1659.3 H/s
-----------------------------------------------------------------
Now  again only the first card runs normally, other 3 card have even more low hashes then 8 card rig instance.

I dont want to lower the driver version of my rigs because i want to use cuda9 . I've tried  391.35 - 388.71 - 388.43 - 388.13  driver versions and all of them have same same hash problem .

Any advice for my problem ?

Thanks.

**Comment by Spudz76** [comment]
Why not 397.xx
Windows? 7? 10? Linux?

**Comment by gguner** [comment]
I'm using Windows 10 .I upgraded my rigs drivers  for to  use  the latest ccminer releases (2.2.5-enemy etc.) 
I'll try the 397.xx drivers.... This slowdown issue only occurs with xmr stak miner. All other miners works perfectly.

**Comment by Spudz76** [comment]
What does your `nvidia-smi` output look like when idle, and while running?

Make sure all GPUs are in P0 state when running, if not then that is the issue.
There are windows utils to disable the "P2 lock" on 10xx series based cards, which are the only ones affected.  They disabled application clocks in the 10xx series, so the P0 unlock is the only thing you can do.

**Comment by gguner** [comment]
All cards are at the p0 state and %100 utilized mode. This issue is related directly to the driver.

382.xx drivers  are ok. But all of the 384 to 397 drivers are buggy with p106 miner cards.It must be fixed .!
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  539.2 |  538.2 |  534.6 |  1 |  426.5 |  426.7 |  436.6 |
|  2 |  427.7 |  426.5 |  455.2 |  3 |  424.8 |  423.2 |  439.9 |
|  4 |  423.6 |  425.6 |  436.2 |  5 |  425.6 |  422.9 |  434.1 |
|  6 |  420.8 |  422.4 |  434.2 |  7 |  427.6 |  425.7 |  458.3 |
Totals (NVIDIA):  3515.9 3511.3 3629.1 H/s
-----------------------------------------------------------------
Totals (ALL):   3515.9 3511.3 3629.1 H/s
Highest:  3865.0 H/s
