### ISSUE TITLE
--noNVIDIA

### ISSUE THREAD

**Issue by CircusDad** [fireice-uk/xmr-stak#161]
The https://github.com/fireice-uk/xmr-stak/blob/master/doc/usage.md guide give a --noCPU and --noAMD tag but not description for Nvidia.

**Comment by sergneo** [comment]
And how to run the miner without the Nvidia GPU ?

**Comment by psychocrypt** [comment]
@sergneo use `--noNVIDIA` to disable the nvidia GPUs.

**Comment by sergneo** [comment]
please correct the usage.md
------------------------------------
Usage: stak.exe [OPTION]...

  -h, --help            show this help
  -v, --version         show version number
  -V, --version-long    show long version number
  -c, --config FILE     common miner configuration file
  --currency NAME       currency to mine: monero or aeon
  --noCPU               disable the CPU miner backend
  --cpu FILE            CPU backend miner config file
  --noAMD               disable the AMD miner backend
  --amd FILE            AMD backend miner config file
  --noNVIDIA            disable the NVIDIA miner backend
  --nvidia FILE         NVIDIA backend miner config file

The Following options temporary overwrites the config file settings:
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333
  -u, --user USERNAME   pool user name or wallet address
  -p, --pass PASSWD     pool password, in the most cases x or empty ""

**Comment by psychocrypt** [comment]
solved with #196
