### ISSUE TITLE
Monero7 "Share Above Target" Ver. 2.4.4

### ISSUE THREAD

**Issue by SlamminS85** [fireice-uk/xmr-stak#1612]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Threadripper 1950
  - Asus X399 Strix
  - 32 GB RAM (samsung Bdie, but running at 2166 MHz, the MB default)

I am using the pre-compiled version of this software on a fresh install of Windows 10. No overclocking. Connecting with Nisehash.

100% of my results are rejected because "share above target"
![capture](https://user-images.githubusercontent.com/39672311/40791657-a6624a6e-64bd-11e8-8bb1-7b7ad916b1bb.JPG)

[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/2058866/cpu.txt)

**Comment by psychocrypt** [comment]
Rhis are expired blocks. Nicehash is setting the difficulty to high that
you can use it with cpu.
Please try a native pool. If you search in the issue list there are otehr
with the same issue
