### ISSUE TITLE
Multi-AMD-GPU thread crash error on random thread (usually thread 1 of 0-3)

### ISSUE THREAD

**Issue by Inkertus** [fireice-uk/xmr-stak#1613]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Running most recent Windows 10 build, GPU driver version 18.3.4
  - R7 1700 CPU
  - Vega 56 GPU x2.
  - Running two different models of PowerColor Vega 56 cards, Red Devil and Red Dragon, will have 3rd Stock air cooler type soon.

# AMD OpenCl issue

  ```
  unknown as to what "clinfo" is and how to run, please advise.
  ```

# Stability issue
  - Is the CPU or GPU overclocked? - GPUs are run at or near 1400Mhz, memory at 900Mhz
  - Is the Main memory of the CPU or GPU undervolted? - GPUs are at stock voltage.  
XMR Stak start
![xmr stak start](https://user-images.githubusercontent.com/39816686/40818231-cc389528-651b-11e8-9fb7-d71da89a30e6.png)
Initial run rate
![initial start rate](https://user-images.githubusercontent.com/39816686/40818230-cc2763fc-651b-11e8-89c8-ea68a2578303.png)
About 60 seconds later, thread crashed
![about 60 seconds later thread crashed](https://user-images.githubusercontent.com/39816686/40818228-cc13525e-651b-11e8-9941-f82d1f12aad2.png)

**Comment by psychocrypt** [comment]
I cannot see that a thread is crashing . If you mean the 'na' for one
thread in the last image in the 5sec column than your intensity is to high
to produce results within 5 sec. The reason is that this gpu is used by
windows for your desktop and is therefore a little bit slower than other.

**Comment by Inkertus** [comment]
Ah OK.  This software is an enigma to me for the most part so that didn't occur to me.  Interestingly I also turned down the memory overclock from a "modest" 900 to 800 back up to 875 over a few minutes and the thread registered normally.  So I'll try the lowered intensity (1792 by default) and try the memory back at 900.
