### ISSUE TITLE
Low difficulty share on the new ETN network at Mining Pool Hub

### ISSUE THREAD

**Issue by borzaka** [fireice-uk/xmr-stak#1619]
MiningPoolHub just updated:
> - Updated Electroneum wallet to bug patched version and opened ETN pool now. You should use Cryptonight7 supported miner to mine
>   Pool will mine empty blocks as ETN wallet bug is not fixed completely yet. ETN network difficulty is still high, blocks would not be generated frequently.
>   ETN payouts will be enabled when network is stable.

# Basic information
  - AMD Ryzen 7 1700X overclocked to 3,8 GHz
  - 1x SAPPHIRE Radeon RX Vega 64, no undervolting, just Global Wattman settings (-8% GPU, 1100 MHz mem, volts are auto)
  - Windows 10 Pro 64 bit, Version 1803
  - `xmr-stak/2.4.4/c0ab1734/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20`
  it's the same with prev versions which supports cryptonight_v7
  - [Mining Pool Hub Electroneum(ETN) Pool](https://electroneum.miningpoolhub.com/)
  - It's working without problem on MPH's Monero Pool.
  - I haven't tried another pool.
  - For some day MPH redirected ETN hashrate to mine Monero, since they stopped the redirection, I'am seeing this low difficulty shares:

```
RESULT REPORT
Difficulty       : 40000
Good results     : 0 / 159 (0.0 %)
Avg result time  : 17.4 sec
Pool-side hashes : 0

Top 10 best results found:
|  0 |                0 |  1 |                0 |
|  2 |                0 |  3 |                0 |
|  4 |                0 |  5 |                0 |
|  6 |                0 |  7 |                0 |
|  8 |                0 |  9 |                0 |

Error details:
| Count | Error text                       | Last seen           |
|   159 | Low difficulty share             | 2018-06-02 00:04:40 |
```

My pool.txt:

```

"pool_list" :
[
	{"pool_address" : "europe.cryptonight-hub.miningpoolhub.com:20596", "wallet_address" : "user.worker", "rig_id" : "", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

"currency" : "cryptonight_v7",
```

**Comment by psychocrypt** [comment]
please fill out the issue template. we need the miner version ... Do you
tried an alternative pool?

**Comment by borzaka** [comment]
Sorry, I wrote it fast to let you guys know :)
It's true for the latest version, as on some prev versions that support cryptonight_v7

I haven't tried another pool. It's a new patch, I don't know which pool is updated.

**Comment by psychocrypt** [comment]
As I know etn changed back to cryptonight because of some issue during the
fork. please try cryptonight as currency

**Comment by borzaka** [comment]
Changing currency `cryptonight_v7` to `cryptonight` on the new ETN network at Mining Pool Hub solved the problem. 
`Result accepted by the pool.`

Don't tell the ASICs, that they can come back... I haven't heard about that they changed back the algorithm.
