### ISSUE TITLE
Thread 0 has invalid config. (RX 560x2)

### ISSUE THREAD

**Issue by AHBennett** [fireice-uk/xmr-stak#1620]
Please provide as much as possible information to reproduce the issue.

# Basic information
AMD FX 6200 (6 core)
AMD RX 560 x2

# Compile issues
Win10 X64

# Issue with the execution
Thread 0 invalid config.
I have tried changing the affine to false and strided to false. Nothing working.

OC disabled.

**Comment by AHBennett** [comment]
UG, solved by creating deleting old AMD.TXT. (New config parameters...)

**Comment by Spudz76** [comment]
Yep, happens, I just move all my configs to `.old` and then run total fresh, then diff those.

Also pools moved out of config.txt into pools.txt a while back
