### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by baldoarturo** [fireice-uk/xmr-stak#1631]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU - Xeon E5-1620 v3
  - Type of the GPU - nVidia quadro m4000

# Issue with the execution
  - Do you compiled the miner by our own?
  No

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

I cannot get the miner to work, I built the config file using the prompt
`
Arturo@ARTURO-PC C:\Users\Arturo\Desktop\xmr-stak-win64
$ xmr-stak.exe -V
Version: xmr-stak/2.4.4/c0ab1734/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20
Press any key to exit.
Arturo@ARTURO-PC C:\Users\Arturo\Desktop\xmr-stak-win64
$ xmr-stak.exe
-------------------------------------------------------------------
xmr-stak 2.4.4 c0ab1734

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-06-04 15:53:17] : Mining coin: monero7
[2018-06-04 15:53:17] : Starting NVIDIA GPU thread 0, no affinity.

"gpu_threads_conf" :
[
  // gpu: Quadro M4000 architecture: 52
  //      memory: 6860/8192 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 8, "blocks" : 39,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

`

**Comment by psychocrypt** [comment]
is thetr no error message. If not please start the miner from a terminal

**Comment by Spudz76** [comment]
I use this on my arch:52 GPU:
```
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3968/4043 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 26, "blocks" : 39,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
```
However, I'm using Linux, you probably have to add back in some bfactor or bsleep to get Windows to play along.  I would use bfactor:4 and bsleep:125

Driver probably crashing, check Windows Event Viewer for things occurring at the time.

**Comment by baldoarturo** [comment]
Thanks, tried it without luck
It even crashes with the nvidia backend disabled
Any way to get logs from it?

```
Arturo@ARTURO-PC C:\Users\Arturo\Desktop\xmr-stak-win64
> xmr-stak.exe
-------------------------------------------------------------------
xmr-stak 2.4.4 c0ab1734

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-06-04 18:15:37] : Mining coin: monero7
[2018-06-04 18:15:37] : WARNING: backend NVIDIA disabled.

```
And then dies without further info

**Comment by Spudz76** [comment]
OK, you've got Intel iGPU drivers installed and their OpenCL stub crashes the AMD backend.
Disable OpenCL by using `--noAMD` and it should stop dying.
There will be messages in Event Viewer regarding the `igdocl` DLL or such causing a crash (no dialog box and no popup notify at all).
