### ISSUE TITLE
xmr-stak Ubuntu 16 AMD Radeo RX550 fails to launch

### ISSUE THREAD

**Issue by wolfgangrumpf** [fireice-uk/xmr-stak#1634]
I compiled xmr-stak and when I execute it I get this:

wolfgang@CULTURE3:~/xmr-stak/build/bin$ ./xmr-stak 
[2018-06-04 21:37:43] : MEMORY ALLOC FAILED: mlock failed
[2018-06-04 21:37:43] : MEMORY ALLOC FAILED: mlock failed
[2018-06-04 21:37:43] : MEMORY ALLOC FAILED: mlock failed
[2018-06-04 21:37:43] : MEMORY ALLOC FAILED: mlock failed
[2018-06-04 21:37:43] : MEMORY ALLOC FAILED: mlock failed
-------------------------------------------------------------------
xmr-stak 2.4.4 c0ab173

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-06-04 21:37:43] : Mining coin: monero7
[2018-06-04 21:37:43] : Compiling code and initializing GPUs. This will take a while...
[2018-06-04 21:37:43] : WARNING: using non AMD device: Mesa
[2018-06-04 21:37:43] : Device 0 work size 8 / 32.
Segmentation fault (core dumped)

Any ideas?  Here is what CLINFO reports:

wolfgang@CULTURE3:~/xmr-stak/build/bin$ clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.2.8
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     Radeon RX 550 Series (AMD POLARIS12 / DRM 3.20.0 / 4.4.0-127-generic, LLVM 5.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 17.2.8
  Driver Version                                  17.2.8
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               8
  Max clock frequency                             1183MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              7704767692 (7.176GiB)
  Error Correction support                        No
  Max memory allocation                           1926191923 (1.794GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        1926191923 (1.794GiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   Radeon RX 550 Series (AMD POLARIS12 / DRM 3.20.0 / 4.4.0-127-generic, LLVM 5.0.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   Radeon RX 550 Series (AMD POLARIS12 / DRM 3.20.0 / 4.4.0-127-generic, LLVM 5.0.0)

**Comment by Spudz76** [comment]
"Clover" === open source garbage OpenCL that doesn't work -- You need AMDGPU-PRO drivers not the ones Ubuntu comes with.

AMD driver downloads site has what you need just navigate to Linux->Ubuntu 16 get one of the deb options and then `sudo dpkg -i whatever.deb`

**Comment by Spudz76** [comment]
Also, to fix the mlock issues run as root or follow the instructions in [config.txt](https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/config.tpl#L79)

**Comment by wolfgangrumpf** [comment]
I do have the AMDGPU-Pro drivers....not sure how to convince it to use those.

**Comment by wolfgangrumpf** [comment]
Tried running as root, and sure enough the mlock went away - thanks!  Do I uninstall openCL and recompile to get xmr-stak to use the AMDGPU drivers?

**Comment by Spudz76** [comment]
I think `apt purge mesa-opencl-icd` fixes it, and bonus deletes the broken OpenCL which should bring AMDGPU-PRO into forefront.

The compile should be good just have to get Clover out of the stack.

**Comment by Spudz76** [comment]
But clinfo should be showing 2 platforms, Clover and AMDGPU
So something else is probably wrong.
Check output of `dpkg-query -l | grep opencl-amdgpu`:
```
ii  opencl-amdgpu-pro                     18.10-572953                                     amd64        AMD OpenCL
ii  opencl-amdgpu-pro-icd                 18.10-572953                                     amd64        non-free AMD OpenCL ICD Loaders
```

**Comment by wolfgangrumpf** [comment]
The results of that query are:

```
wolfgang@CULTURE3:~$ dpkg-query -l | grep opencl-amdgpu
ii  opencl-amdgpu-pro                           17.50-511655                                 amd64        Meta package to install OpenCL components
ii  opencl-amdgpu-pro-icd:amd64                 17.50-511655                                 amd64        non-free AMD OpenCL ICD Loaders
```

**Comment by wolfgangrumpf** [comment]
Thanks for all the help, btw!

**Comment by wolfgangrumpf** [comment]
After uninstalling EVERYTHING OpenCL and reinstalling the AMDGPU-Pro drivers (v18) everything is working - thanks again!

**Comment by Spudz76** [comment]
It is quite the touchy thing, since OpenCL is a 'stack' when too many players join in it gets weird.  Best to not even have the benched players in the stack, and the AMD installer is not the best at working around other OpenCL ICDs.

Good job on the last hurdles, I would have suggested exactly what you did.  Actually whenever I have any issue I've gotten in the reflex of just purging everything related like that, and reinstalling.  AMD installer script is not capable of figuring out every situation.

17.50 works about the same as 18.10 in my testing but I have mostly R9 and only one RX.  Also that rig is doing ETH but still OpenCL even if not xmr-stak.  I am using 18.10 on some Tahiti for xmr-stak and it works same as 17.xx.  So not much reason to change yours now that it works, but the process would be similar to that last winning step.

There is a directory `/etc/OpenCL/vendors/` which holds pointers/config for all the current ICDs in the stack.  If the vendor file is missing the stack won't go find the driver.  Also a quickfix may have been to delete the Clover ICD file out of here and the main OpenCL stack would stop 'seeing' it even though technically still installed.  But the way you've fixed it is more 'correct' and clean.
```
# ls /etc/OpenCL/vendors/
amdocl64.icd  amdocl-orca64.icd  nvidia.icd
```
