### ISSUE TITLE
Vega FE 16GB Memory Allocation

### ISSUE THREAD

**Issue by JeuTheIdit** [fireice-uk/xmr-stak#1636]
**Basic Info:**
* Windows 1803, with 90gb virtual memory and large page size enabled (gpedit).
* xmr-stak 2.4.4 (complied version on github) with the following environment variables in a batch file before starting:
  * set GPU_FORCE_64BIT_PTR=1
  * set GPU_MAX_HEAP_SIZE=100
  * set GPU_MAX_ALLOC_PERCENT=100
  * set GPU_SINGLE_ALLOC_PERCENT=100
* 3x Vega FE GPUs.

**Issue:**

*tldr: Xmr-stak only allocates ~3.5GB of memory instead of the full 16GB on gaming drivers (but allocates the full 16GB on pro drivers).  Cast-xmr allocated the full 16GB on gaming drivers.*

Using the 18.4.1 Pro drivers xmr-stak fully allocates 16GB of memory for each GPU, so hashrate is as expected.  However, since I cannot use overdriventool my power consumption is through the roof (PPT voltages don't correctly apply either).

Now, changing to the 18.4.1 gaming driver I can use overdriventool and PPT voltages correctly apply.  However, xmr-stak only allocates ~3.5GB of memory per GPU, instead of the full 16GB like it should.  Because of this I have to lower the intensity and hashrate is not good.  Cast-xmr allocates the full 16GB though (I haven't tested any other software yet).

Is there a reason that xmr-stak only allocates 3.5GB of memory? Is there a way to fully allocate it on the gaming drivers for Vega FE?  I know this have been an issue for other Vega FE owners with gaming drivers.  I would prefer to use xmr-stak so if there is any insight it would be greatly appreciated!

**Comment by Spudz76** [comment]
Interesting, perhaps the other miners allocate multiple regions @ 3.5 to work around the apparent lack of 64bit (capping at 4GB like a 32bit OS would the system ram).  But then handling all the memory regions in one thread rather than opening multiple OpenCL pipes (host threads).

Maybe the gaming driver doesn't honor the 64BIT_PTR env option?  If you make that 0 with the Pro does it also do the 3.5GB thing (I think it would)?

**Comment by Spudz76** [comment]
The multiple allocation and mapping I suspect gaming-driver-working miner apps use would be similar to PAE in a 32bit OS.  You can still "get to" all the memory it just has to be "banked" into 32-bit chunks and handled as such by the client app.

**Comment by JeuTheIdit** [comment]
Changing 64BIT_PTR to 0 does lower the memory allocation (not to 3.5 though). So maybe opening more threads would do the trick?

**Comment by Spudz76** [comment]
The issue with multiple host threads is it opens as many OpenCL sessions to the card.  You could try 4-5 host threads with max "3.5g" intensity in as many as possible and then whatever remainder in the last one.  But I doubt the performance will get as high as the single host thread with proper 16GB and high intensity, it should gain, and work around the chunk-allocation limit.

I believe xmr-stak would need a more complex internal memory manager to be able to workaround allocation issues while still using single host/CL session.  Perhaps the others were designed with a more complex memory manager already, so they didn't even need to deal with this issue.  Could also be why they tend to still work better on Terascale (opposite end of the spectrum), those seem to need multiple allocation to get all the memory, but more at a 350MB chunk size, and do not like multiple CL sessions.  Currently have to run ancient antique drivers to make them work with single allocation, similar to you having to run the Pro.  I still haven't gotten the old aticonfig to work so no OverDrive tweaks, same boat there.

I do wonder if there is some manual combination of components from the two drivers that would be Pro (full alloc) but add back the ability to tune power.  Main driver from Gaming, then copy over the Pro OpenCL pieces by hand to make a hybrid driver combo that might do all of the things.

**Comment by JeuTheIdit** [comment]
That makes sense, thanks for the information (I am not much of a programmer but all of it makes sense, so learned something new)!  Yes multiple threads don't improve performance at all.

I actually found a way to limit the power consumption so I am using xmr-stak on pro drivers for now.  Kind of a bummer that you have to work around it.  I believe if xmr-stak fixed the allocation issue on gaming drivers, a lot more Vega FE owners would start using it.

**Comment by JanCernyCZ** [comment]
Have you "Above 4G Decoding" option in BIOS?

**Comment by JanCernyCZ** [comment]
Manual, page 51: Above 4GB MMIO BIOS assignment
PCIe Link Speed: with GPU to Gen 2, unused set to Gen 1
Disable: PCIE ASPM Support, PCH PCIE ASPM Support, DMI ASPM Support, PCH DMI ASPM Support

**Comment by JeuTheIdit** [comment]
Thanks!  I missed 4GB MMIO BIOS assignment, but was already enabled.  PCIE Link Speeds were already set to Gen 2 and PCIE ASPM Support, PCH PCIE ASPM Support, DMI ASPM Support, and PCH DMI ASPM Support were all already disabled.  I tried disabling/enabling IOAPIC 24-119 Entries but did not work.

I am at a loss here.  Wonder what cast does that xmr-stak and srb miner does not to allocate full memory.  Bummer it is closed source.

**Comment by JanCernyCZ** [comment]
Download old blockchain driver for Vega: https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx

Download DDU:
https://www.wagnardsoft.com/forums/viewtopic.php?f=5&t=1095

Disconect from internet. Boot to safe mode and use DDU to uninstall all AMD graphics drivers. Reboot. Install AMD blockchain driver, uncheck all boxes except the box for the AMD Display Driver.

Disable automatic driver update (you can also do more tweaks): https://www.oo-software.com/en/shutup10

Switch driver to compute mode:
https://support.amd.com/en-us/kb-articles/Pages/DH-024.aspx
or via this tool: https://bitcointalk.org/index.php?topic=2815803.0

Connect to the internet.

Try mine with two threads per card with intensity 2048. For example:
https://www.xmrstak.com/2018/05/07/amd-vega-frontier-edition-2205-h-s/

```
"gpu_threads_conf" : [
  // Vega 0 if iGPU as primary adapter, you can increase both threads to 2048 
  { "index" : 0, "intensity" : 2048, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 0, "intensity" : 1664, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
  // Vega 1
  { "index" : 1, "intensity" : 2048, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 1, "intensity" : 2048, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
  // Vega 2
  { "index" : 1, "intensity" : 2048, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
  { "index" : 1, "intensity" : 2048, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "comp_mode" : true },
],
```

**Comment by JeuTheIdit** [comment]
Thanks for the write up! I guess I should have mentioned that I have already mined with blockchain drivers with good success, xmr-stak allocates the full memory on those drivers.  I would rather not go back since they are extremely buggy with FEs (more so that 56/64s, you have to reinstall drivers if your computer crashes with FEs).  Plus I have cast working anyways so it is not that big of a deal if I keep using new gaming drivers.

I will close this thread for now and continue testing.  It seems like a mixed bag online for people that are able to use xmr-stak or not with FEs on gaming drivers, so there has got to be something we are missing that I am assuming is related to drivers.
