### ISSUE TITLE
motherboard GPU heating up with NVIDIA cards

### ISSUE THREAD

**Issue by tinsami1** [fireice-uk/xmr-stak#1642]
One of my rigs is a Supermicro with dual Xeon E5620 with a Matrox MGA G200eE WPCM450 video chipset in the motherboard.  It was mining with a Radeon HD7870 card (Ubuntu 16.04 + AMDGPU v17.50) and the temps (CPU, G200, and HD7870) are not that high (all are below 70C) to rev up the noisy-as-hell high-speed intake fan.

I replaced the HD7870 with two nVidia GTX 1050 2GB cards.  I upgraded Ubuntu to 18.04 and installed from the Ubuntu repo the nvidia-headless-390 driver package.  Unfortunately, now the temp of the built-in VGA rises so fast to 83C that the noisy intake fan is almost always running at full speed to keep it fluctuating between 78C and 80C.

I'm assuming here that for some reason, some computation load of sort is somehow placed on the MGA chipset as to cause it to heat up.  But this shouldn't be happening, right?  How do I prevent this from happening?

I'm using an xmr-stak binary I compiled myself with SSL and HTTP features turned off.  Same binary is  used then wthen it was with an HD7870 and now (with the two GTX 1050's).

The machine is now mining with the case's side panel opened up and a small electric fan is being used to blow air into the MGA's heat sink -- it is a passively cooled heatsink, no dedicated heatsink fan.

**Comment by Spudz76** [comment]
I have at least 3 of the same thing, never noticed the IPMI Video getting hot, but may not have bothered checking either.
They also are not in cases and don't have the Supermicro Jet Engine Fans so even if it was on fire it wouldn't be making hair dryer noise.

**Comment by Spudz76** [comment]
Also, no there is no possible way the MGA is doing anything cool, especially computation.
At best Linux has initialized it up to whatever the default VESA framebuffer does (1024x768?) which may raise the MGA clocks.  I lock all mine to 800x600 in `/etc/default/grub` along with a couple kernel args for fun:
```
GRUB_CMDLINE_LINUX_DEFAULT="spectre_v2=off nopti noibpb noibrs"
GRUB_CMDLINE_LINUX="panic=5 consoleblank=0 net.ifnames=0"
GRUB_GFXMODE=800x600x32
GRUB_GFXPAYLOAD=800x600
GRUB_GFXPAYLOAD_LINUX=keep
```
Are you running Xorg?  Make sure the MGA is not involved, only the nVidia.  I put all this in my `/etc/X11/xorg.conf` to ensure Xorg is only handling the nVidia via the proprietary driver.
```
Section "Module"
    Disable "evdev"
    Disable "vesa"
    Disable "fbdev"
    Disable "modesetting"
    Disable "ati"
    Disable "amdgpu"
    Disable "fglrx"
    Disable "mga"
    Disable "nouveau"
EndSection
```

**Comment by tinsami1** [comment]
The unit doesn't have Xorg installed.  It is basically and minimal server install plus the nvidia-headless-390 package.  I tried running just the CPU miners (i.e --noAMD --noNVIDIA) and still the igpu heats up.  So that rules out something in the nvidia code.  And if xmr-stak is not running, then the igpu temps go down as well, so that means something in xmr-stak is triggering the igpu in some way.  And the igpu doesn't heats up when the radeon gpu is installed and the xmr-stak is running.

I will try the GRUB parameters above tomorrow when I get to where the rig is.

**Comment by tinsami1** [comment]
I tried the GRUB parameters, but the igpu temps still goes up fast when I turn off the fan.  I even tried blacklisting the mgag200 module, but still no luck.  I guess I'll have to find a fan I can put directly on top of the heatsink to manage the temp.
