### ISSUE TITLE
how to compile a miner for android apk ?

### ISSUE THREAD

**Issue by mike2001** [fireice-uk/xmr-stak#1643]
hi, i want mine on android pohone, how to compile a miner for android apk ?

**Comment by Mogster** [comment]
The devs have stated before that xmr-stak will not be supported on ARM CPUs. [(https://github.com/fireice-uk/xmr-stak/issues/897)] Maybe it would work on Android-x86, I don't know.

If you want a miner that works on ARM, try xmrig. [https://github.com/xmrig/xmrig]
