### ISSUE TITLE
Reduced computing power

### ISSUE THREAD

**Issue by m1911** [fireice-uk/xmr-stak#165]
Double X5650 use 100%, only 240h/s

**Comment by psychocrypt** [comment]
do you compiled it by hand? Do you compiled the dependency hwloc?
To get a auto suggestion for two sockets you must comoile with hwloc.

**Comment by m1911** [comment]
Yes, I use manual compilation.
My compile Parameters -Dhwloc_enable=on

**Comment by psychocrypt** [comment]
please post the auto suggested config and the output of `hwloc-ls`

**Comment by m1911** [comment]
hwloc-ls
root@c2241:~# hwloc-ls
Machine (7967MB total)
  NUMANode L#0 (P#0 4029MB) + Package L#0 + L3 L#0 (12MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#12)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#2)
      PU L#3 (P#14)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#4)
      PU L#5 (P#16)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#6)
      PU L#7 (P#18)
    L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
      PU L#8 (P#8)
      PU L#9 (P#20)
    L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
      PU L#10 (P#10)
      PU L#11 (P#22)
  NUMANode L#1 (P#1 3938MB) + Package L#1 + L3 L#1 (12MB)
    L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
      PU L#12 (P#1)
      PU L#13 (P#13)
    L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
      PU L#14 (P#3)
      PU L#15 (P#15)
    L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
      PU L#16 (P#5)
      PU L#17 (P#17)
    L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
      PU L#18 (P#7)
      PU L#19 (P#19)
    L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
      PU L#20 (P#9)
      PU L#21 (P#21)
    L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
      PU L#22 (P#11)
      PU L#23 (P#23)
  HostBridge L#0
    PCIBridge
      PCI 14e4:163b
        Net L#0 "eno1"
      PCI 14e4:163b
        Net L#1 "eno2"
    PCIBridge
      PCI 102b:0532
    PCI 8086:3a22
      Block(Disk) L#2 "sda"
@psychocrypt

**Comment by m1911** [comment]
Automatic configuration
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 16 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 18 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 20 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 22 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 13 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 15 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 17 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 19 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 21 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 23 },
],
@psychocrypt

**Comment by psychocrypt** [comment]
Do you mining aeon or xmr?

Am 20.11.2017 1:00 Nachm. schrieb "m1911" <notifications@github.com>:

**Comment by m1911** [comment]
@psychocrypt 
Aeon or XMR are the same CPU 100% computing power drops a lot.

**Comment by psychocrypt** [comment]
You must generate a new config(cpu.txt,amd.txt and nvidia.txt) if you
switched from monero to aeon or the oter way around.
The auto suggestion differ for both currencies.
Please to not use the some settings.

**Comment by m1911** [comment]
I tested the new Monero no more than 12 threads. 
or
AEON CPU use 100%, the computational power is very low.

**Comment by mfaiola** [comment]
Run on even cores with dual x5650 (0,2,4,6,8,10,12) dont use the odd ones they are hyperthreading. I'm getting 455-465 h/s on both nodes of a supermicro server than also runs xmr-stak-nvidia as well. running the dual x5650's at 2.66Ghz and 1333Mhz ddr3 ram with 2 channels. Updating to the new version today will post if there is a decrease.
