### ISSUE TITLE
CN mining guide and miner manual!

### ISSUE THREAD

**Issue by GrannyCryptomaster** [fireice-uk/xmr-stak#1651]
Hey guys,
I made a guide about CN mining as a manual for XMRig, but contains usefull info that can be applied to XMR-Stak also. I use it as a memo for all my findings in OC and miner settings, for CN mining.
You can check it out here:
https://github.com/xmrig/xmrig-nvidia/issues/100

**Comment by Spudz76** [comment]
Matches more or less what xmr-stak autoconfig does.
I have a pile of MSI 1060 6GB single fan / short format with junk bios and junk Hynix GDDR5 that require the "P2 lock disable" or they run like 1030s.  CUDA-in-use forces P2 mode on 10xx, stops stable overclocking as you're setting P2clock+P2offset to max out memory but then when the CUDA app logs out of CUDA the card visits P0 for a moment while stuff settles and the P2 lock is released, sending the memory rate up to P0clock+P2offset which is likely waaaaay too high and crashes if not just the driver the whole rig.

Also have some PNY full length dual fan but their bios is better, they clock identical in P0 and P2 so the driver issue is rendered ineffective even if it's on (P0clock and P2clock are the same so the offset won't go crazy even if it cycles P2-P0-P8 on the way out of a CUDA app).  So not all 10xx users would need the P2-lock-disable but there is also no reason not to undo the nVidia sabotage anyway just for the counter-troll of it.
