### ISSUE TITLE
Failed to build on Windows with VS2017 and CUDA9

### ISSUE THREAD

**Issue by Ghosthree3** [fireice-uk/xmr-stak#166]
Following the compile instructions for CUDA9 I end up getting this output.

> EXEC : CMake error : Error processing file: cmake_install.cmake [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1. [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> Done Building Project "F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj" (default targets) -- FAILED.
> 
> 
> Build FAILED.
> 
> "F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj" (default target) (1) ->
> (PostBuildEvent target) ->
>   EXEC : CMake error : Error processing file: cmake_install.cmake [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd\r [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1. [F:\src\xmr-stak\xmr-stak-2.0.0\build\install.vcxproj]
> 
>     0 Warning(s)
>     2 Error(s)

**Comment by psychocrypt** [comment]
please provide all commands you have used to compile xmr-stak

**Comment by psychocrypt** [comment]
and all cmake output from a clean build folder.

**Comment by Ghosthree3** [comment]
Commands:

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
> set CMAKE_PREFIX_PATH=F:\src\xmr-stak\xmr-stak-dep-v2\hwloc;F:\src\xmr-stak\xmr-stak-dep-v2\libmicrohttpd;F:\src\xmr-stak\xmr-stak-dep-v2\openssl
> mkdir build\test
> cd build\test
> cmake ..\.. -G "Visual Studio 15 2017 Win64" -T v141,host=x64 > cmake.log 2>&1
> cmake --build . --config Release --target install > cmakebuild.log 2>&1

cmake.log https://0bin.net/paste/t7JGyK6M7E8YC+GO#TK1eP8x3idyFX3tv6Rvc4tS0CRRJwAfq7k8NKRUrlmH
cmakebuild.log https://0bin.net/paste/pWS-yh3XYmRICAdQ#EJBHK96rf50hhOiTOKpa8TUI5c+onZb16i29UY1OhD3

**Comment by psychocrypt** [comment]
It looks like the miner is correct compiled but the install procedure is crashing.
IN your case `cmake --build . --config Release` should be enough to create the binaries.

**Comment by Ghosthree3** [comment]
Ok, that works fine. Could you quickly explain what --target install does if it's not needed to compile the binary? It's sounding like an option I wouldn't want to use anyway, I just want the binary, I don't want it moved somewhere on my system.

Any clue why it's not working anyway? Weird that this would be the thing to fail.

**Comment by psychocrypt** [comment]
The command is calling some post compile routines to copy the libraries and
executable to the install folder. Since you have not selected a extern
folder where all should be copied to it is not needed.
I am currently not sure why you get this error. It looks like your user has
not the rights to copy files but since the install routine is copy files
only to the subfolder it should work.
Our appVoyer CI is working that must be something special on your system.
I will keep this issue open and check this if I have more time.
