### ISSUE TITLE
Error gpu 5: <C:/xmr-stak/xmr-stak-2.4.5/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:312

### ISSUE THREAD

**Issue by dahifi** [fireice-uk/xmr-stak#1666]
Please provide as much as possible information to reproduce the issue.

# Basic information
  // gpu: GeForce GTX 1070 Ti architecture: 61
  //      memory: 6763/8192 MiB
  //      smx: 19
  { "index" : 5,
    "threads" : 10, "blocks" : 57,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

# Compile issues
Win10 with Visual Basic updates, Latest Nvidia drivers

xmr-stak/2.4.5/b3f79de3/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20

# Stability issue
Doesn't matter what settings I use. Miner doesn't run at all.

**Comment by Spudz76** [comment]
Releases are still built for CUDA 8 as far as I know, you will have better results either compiling yourself against CUDA 9.2 (matching driver you have, 'latest') or the other way around, downgrade driver to the newest one that supported CUDA 8 (but not yet 9).  CUDA 8 apps work ok on CUDA 9.1 driver but it seems like CUDA 8 apps on CUDA 9.2 drivers have problems.  So you could also try the latest CUDA 9.1 driver (not 9.2) but it is still best to match up.

Running "backward compatible" is allegedly supported and "works" but I can't ignore all the errors I saw trying CUDA8 junk against CUDA9.2 drivers, and errors with no reason behind them. (same as yours)

**Comment by dahifi** [comment]
I'm running CUDA 9.1 from the looks of it. That may explain a lot of the problems I'm having with other miner applications. I'll see what I need to do to downgrade and see if that clears things up.

**Comment by JerichoJones** [comment]
Is this a fresh download of stak?  
Does it run through the configuration questions on first run?

**Comment by Spudz76** [comment]
The revision of CUDA runtime is bundled with the driver.  So trash the entire 39x.xx or whatever and get a 384.xx or such (I don't know off the top of my head which driver had CUDA8 runtime, google it).

The CUDA stuff from the CUDA site is only for compiling and has nothing to do with runtime.  If you are running the exe from Releases and not compiling you do not even need the CUDA stuff, just the driver which includes whatever CUDA was the current thing at the time.

**Comment by dahifi** [comment]
@JerichoJones I copied the pool config over but not the GPU files. And yes, this was the latest release.

**Comment by JerichoJones** [comment]
@dahifi Did you try the pre-compiled version?
