### ISSUE TITLE
Configure donation interval

### ISSUE THREAD

**Issue by testitem** [fireice-uk/xmr-stak#1667]
Instead of donating 2 minutes every 100 minutes, I'd like to donate 6 seconds every 5 minutes.
This is donating the same amount, and it allows me to reconnect to my pool to reset the difficulty back to 100.
Is this possible?

Thank you very much.

**Comment by JerichoJones** [comment]
Not without modifying the source.

**Comment by Spudz76** [comment]
There has to be a chance of hitting a work result, which would literally never happen in 6 seconds.  The donate-pool would need to support ultra low difficulty.

So really what you're asking for is a reconnect option either on timeout or on difficulty events where it is not within your preferred range.

You should run a proxy and set your difficulty there, or choose a pool that allows fixed diff at 100 or what you like.  Are you sure they don't support it with added account string option (some pools do).

**Comment by testitem** [comment]
> There has to be a chance of hitting a work result, which would literally never happen in 6 seconds. The donate-pool would need to support ultra low difficulty.

If you did 6 seconds of work every 5 minutes, in 100 minutes you would've done 2 minutes of work. Mining selects a RANDOM nonce, not a nonce in order, so it would happen in 6 seconds.

> Not without modifying the source.

Yes, I'd like to modify the source.

**Comment by Spudz76** [comment]
You clearly have no idea how mining works.  You must complete ALL nonces in a work unit or you get zero credit for any of it.  It's not a time clock.

Go ahead and modify the source then?

**Comment by Spudz76** [comment]
Also same thing happens when you reconnect to your pool, even if just straight reconnecting, you get a new work unit so unless you found a result in that time all the work is lost.  Reconnecting that often should ruin your payouts completely but still chew the power.  But good luck?

Read about SegWit and you will find out why it's not a timeclock and you must find a result or get zero credit.

Yes you could find a result in 6 seconds but very rarely.  Not finding a result means no credit for anything.

**Comment by testitem** [comment]
> You clearly have no idea how mining works. You must complete ALL nonces in a work unit or you get zero credit for any of it. It's not a time clock.

From my understanding that's wrong. A CPU takes random nonces and then hashes it with the work. Finding a share does not mean completing all nonces. If finding a share does mean completing all nonces in a work unit, how would pools that run at ~100 MH/s (minexmr.com) verify every single hash? They don't. They only verify the shares. I think you are confusing this with pools that pay for each hash (like CoinHive)

**Comment by Spudz76** [comment]
Pools verify the PoW and PoW would never work if nonces were random.  You might as well CRC32 a file by random offsets, it's no longer a checksum that means anything then (aka no verifiable PoW).

There are literally four calls to `rand()` and they are in the socket port selection code.  Nothing in the backends contains any reference to random.

**Comment by testitem** [comment]
Well duh I know that! The miner computes random nonces for a block, then sends the block and the correct nonce back, **NOT THE HASH,** and the pool verifies that block. That's a "share". The pool of course doesn't need anything random.

**Comment by Spudz76** [comment]
The miner doesn't randomize the nonces.  End of.

I have pointed to the code multiple times and it clearly `nonce++`

**Comment by testitem** [comment]
It starts at a random nonce and does nonce++ for each time it doesn't meet the target!  
And doesn't your post prove my point?  
**_Furthermore, can someone JUST ANSWER MY ORIGINAL QUESTION?_**

**Comment by Spudz76** [comment]
OK then we're both right.  But the daemon hands the pool a random starting nonce, the miner has nothing random.  You kept saying miner and random too close together.

Change the `100` [here](https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/misc/executor.hpp#L62) into `5` and recompile.

**Comment by testitem** [comment]
Okay. Thank you!
