### ISSUE TITLE
Multiple configs for day and night mining

### ISSUE THREAD

**Issue by hanserasmus** [fireice-uk/xmr-stak#167]
Hi guys

During the day I want to mine with less CPU threads and no Nvidia, and at night I want to mine at full capacity.  How can I achieve this with the new setup? I cannot find the correlation between the config.txt files and the cpu.txt or nvidia.txt. In other words, I know I can change the settings inside the cpu- and nvidia.txt files, but I want to create two sets of config files. One set for during the day and one for during the night. Which I can then call with the -c flag. This possible?

**Comment by psychocrypt** [comment]
please run `xmr-stak --help` you can define which miner config (pool,
login, ...) and the configurations for the backends (cpu,nvidia and amd) is
used

**Comment by hanserasmus** [comment]
Thank you, this worked well.

For anyone coming upon this thread, my final command was something like:

`./xmr-stak --cpu cpu_day.txt --noNVIDIA`
