### ISSUE TITLE
Sirefef.gen!C  in xmrstak_opencl_backend.dll ??

### ISSUE THREAD

**Issue by krrkrr** [fireice-uk/xmr-stak#1686]
Please provide as much as possible information to reproduce the issue.

# Basic information
i5 with vega64 and 56.

on
Win10 Pro

I've re-install my Win10 little mining rig... with 2 Vegas. And downloaded the last xmr stak win64 release one hour ago.... then MalwareBytes and others went crazy because there's Sirefef.gen!C rootkit in the xmrstak_opencl_backend.dll  ??? what the hell ???

**Comment by krrkrr** [comment]
yeah, but I never had such reaction before... as I use xmr stak on this rig for months...

so, yeah, I set them to ignore xmr stak and stuff...

**Comment by Spudz76** [comment]
I see.  I run 6 1060 on Win7 and Win10 would just be silly.
Did not know there was a way to shut off updates, main reason I would never switch from Win7.
But this most recent update really broke everything, games too.

**Comment by psychocrypt** [comment]
Each miner is detected a bad software by AV software. YOu need to add an exception for the miner folder. If you not trust our binaries you can compile the miner by your own (please follow our documentation).
