### ISSUE TITLE
GT 740M and CUDA 9.0

### ISSUE THREAD

**Issue by agisubagio** [fireice-uk/xmr-stak#170]
I've managed to compile from the last version of the source code, but when it runs, an error occurs like this. And this problem does not appear in previous versions. I'm using Notebook with GT 740M onboard and Windows 7 64-bit.

https://imgur.com/a/zNtwr

**Comment by CollusionPool** [comment]
I think not only you)

**Comment by anhphan** [comment]
Try change `bfactor` to 8 and reduce `threads` in `nvidia.txt` file

**Comment by psychocrypt** [comment]
please increase bfactor in nvidia.txt and/or reduce the threads for the
device.

**Comment by agisubagio** [comment]
My current config:

{ "index" : 0, "threads" : 96, "blocks" : 8, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false },

**Comment by psychocrypt** [comment]
solved by increasing bfactor
