### ISSUE TITLE
Pls add xmr-stak-alloy

### ISSUE THREAD

**Issue by BenOZ** [fireice-uk/xmr-stak#1701]
https://github.com/alloyproject/xmr-stak-alloy/releases
Will be so great!
Wanna mine XAO on HiveOS easily...
Thank U!

**Comment by psychocrypt** [comment]
the alloy network is fare away from 1MH/s.

**Comment by psychocrypt** [comment]
Please open a issue if the coin has more than 5 MH/s hashrate.
