### ISSUE TITLE
Incorrect algorithm reported to pool/proxy

### ISSUE THREAD

**Issue by xmrig** [fireice-uk/xmr-stak#1708]
### Issue with the execution
Official Windows build `Version: xmr-stak/2.4.5/b3f79de3/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20`

If user select `currency` `turtlecoin` or `cryptonight_lite_v7` miner always report to pool algorithm `cryptonight_lite` it breaks algorithm verification in xmrig-proxy. For `monero7` and `cryptonight_v7` miner correctly send `cryptonight_v7`. So it looks like a bug, anyway if this bug exists from beginning of time and/or wont be fixed, I can add workaround for this case. https://github.com/xmrig/xmrig/issues/529#issuecomment-403567387
Thank you.

**Comment by psychocrypt** [comment]
thx for reporting. I will have a look into it.

**Comment by psychocrypt** [comment]
fixed with #1710
