### ISSUE TITLE
Errors when running XMR-Stak

### ISSUE THREAD

**Issue by sergneo** [fireice-uk/xmr-stak#171]
Why do I like this miner who immediately throws the error? My PC Core2Duo E8400 and a Nvidia 8600GT. Why would I OpenCL.dll if I don't have AMD card.
(**update: Is solved by installing the latest drivers Nvidia 388.31 or copying opencl.dll in the folder with the miner**)
![xmr-stak-error](https://user-images.githubusercontent.com/27492679/33016739-b81ac99c-ce00-11e7-8519-490ef4b5dcc7.jpg)

Miner does not work with nvidia driver 378.78
![xmr-stak-error2](https://user-images.githubusercontent.com/27492679/33016808-f56addaa-ce00-11e7-9c71-c3d109b64371.jpg)

Default miner is not true determines the parameters of the GPU. For example the optimal settings for GT730:
"threads" : 32, "blocks" : 6,
"bfactor" : 8, "bsleep" : 100,
![xmr-stak-error3](https://user-images.githubusercontent.com/27492679/33016847-13fe3f50-ce01-11e7-829e-6dfc543cddb5.jpg)

**Comment by lh1008** [comment]
@sergneo yesterday I had the same issue. Your windows doesn´t have installed the OpenCL.dll, or there is an error in the OpenCL.dll file. I downloaded the OpenCL.dll and installed and it worked. Got it from this site [dll4free](https://www.dll4free.com/opencl.dll.html) Use it at your own risk, follow instructions.

**Comment by psychocrypt** [comment]
@sergneo  please update you cuda driver to the latest version https://developer.nvidia.com/cuda-downloads.
Also increase bfactor. You GPU is very slow and therefore the miner gets killed by the OS.

**Comment by psychocrypt** [comment]
@sergneo  Please also increase bfactor in `nvidia.txt` to 8 and/or reduce `threads`. Your GPu is to slow and therefor ethe miner is killed by the OS

**Comment by sergneo** [comment]
I have long know about it and always put on all GPU "bfactor" : 8, "bsleep" : 100, hash is not reduced.
Can the miner to set the same parameters for all.

**Comment by psychocrypt** [comment]
I added a fix to the dev branch for low end gpus. The issue is the f...ing
OS (sry I am windows hater) and the liw end gpu.

Btw is the miner now running?

**Comment by sergneo** [comment]
Yes works successfully and produces about 64 hash.I just have a lot of these GPU on the chip GK208, let them work.
On GF108 Nvidia GT730 is not working. Architecture is not like him.
```
"gpu_threads_conf" :
[
  // gpu: GeForce GT 730 architecture: 35
  //      memory: 1973/2048 MiB
  //      smx: 2
  { "index" : 0,
    "threads" : 64, "blocks" : 6,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false,
  },

],
```
