### ISSUE TITLE
backend NVIDIA disabled

### ISSUE THREAD

**Issue by crazy4u2** [fireice-uk/xmr-stak#1715]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU : i7-7700
  - Type of the GPU (if you try to miner with the GPU) : AMD rx550

# Compile issues
  - Which OS do you use? : window10 pro
  ```
  add **all** commands you used and the **full** compile output here
  ```
-------------------------------------------------------------------
xmr-stak 2.4.2 e10e8e67

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-07-13 01:47:52] : Mining coin: monero7
WARNING: NVIDIA Insufficient driver!
[2018-07-13 01:47:52] : WARNING: backend NVIDIA disabled.
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? : No
  - Is the Main memory of the CPU or GPU undervolted? : No

#ETC 
  - sorry, my English is poor. I use AMD RX550 GPU. but xmr-stak make a error about NVIDIA. I can't understand

**Comment by Spudz76** [comment]
Mismatched CUDA version, program is compiled for newer CUDA than your old driver supports.

**Comment by psychocrypt** [comment]
There is no error visible in you posted output. This is only a WARNING. WARNING means something happened what reduce maybe the functionality of the miner but mining will be possible.
xmr-stak is a multi backend miner, the miner assumes that you have a cpu, AMD GPu and a NVIDIA GPU. If one if those backends are not available the miner will warn you that you no about it.

**Comment by psychocrypt** [comment]
@crazy4u2 has no NVIDIA GPU
