### ISSUE TITLE
Crash upon start, with amd and nvidia gpu

### ISSUE THREAD

**Issue by hoyanf** [fireice-uk/xmr-stak#172]
Crash on amd with nvidia gpu, attached is the error screen
![screen shot 2017-11-20 at 19 44 25](https://user-images.githubusercontent.com/15434685/33016970-81c883b8-ce2b-11e7-9317-cee756d5737a.png)

**Comment by Clintoxen** [comment]
I think the default setting the miner is picking for gpus is too high and causing the miner to freeze up and crash. I had the same problem until I raised the bsleep etc

**Comment by psychocrypt** [comment]
please set bfactor to 8. This should solve the issue. We have a few issues
like that, mostly with low end gpus :-(
