### ISSUE TITLE
CMakeFiles/xmr-stak-backend.dir/build.make:158: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o' failed

### ISSUE THREAD

**Issue by iskyd** [fireice-uk/xmr-stak#1742]
Hi, i'm trying to compile under Linux ubuntu 18.04

This is info about my cpu:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Virtual CPU 714389bda930
Stepping:            1
CPU MHz:             2399.996
BogoMIPS:            4799.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0
```

I run 
`cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF`
and everything works right but during make install I get the following error:

> CMakeFiles/xmr-stak-backend.dir/build.make:158: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o' failed
> make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o] Error 4
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
> make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by iskyd** [comment]
It was just a memory problem during compile. Not an xmr-stak problem.

**Comment by suuuch** [comment]
@iskyd I get this problem too,How do you fix this ?
