### ISSUE TITLE
Activity monitor 50% idle

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#1748]
On high sierra using the latest build just thought I would check activity monitor.

Users was 50% system about 2% but idle was 48%

Does this mean it’s not utilising the full capacity of the cpu?

Should I be tweaking settings or leave as is?

**Comment by Spudz76** [comment]
If you are mining a regular CryptoNight algo (monero or close relative) then the block size is 2MB
CPU only mines within cache memory, system memory is (electronically) far away and too slow.
So if you divide your CPU's L3 cache in MB by 2, that is the maximum threads you can run regardless of core count.  Any more cores working would have no "real estate" to use for farming... and slow everyone down as they have to wait/contend for space.

CN-Heavy is 4MB and is even worse (Xeon huge cache or not worth it)
CN-Lite is 1MB and you may do better on a coin based on that if you have low cache, and the old GPU would do better with it as well (assuming the OpenCL workaround makes it do anything at all)

**Comment by Spudz76** [comment]
^^^ so summarizing that, if your CPU has 2MB of cache and 2 cores, it will only mine on one core and you would see that 48% usage, totally normal.  It can't mine the other core without 4MB of cache.

**Comment by macminer** [comment]
Thanks.

I have 12mb L3 and 6 cores. Which is 2mb per core.

**Comment by Spudz76** [comment]
Hyperthreaded? That doubles your core count thus 50% load is full load (not counting the HT cores).  The OS doesn't know that half the processors are "virtual".

Your `cpu.txt` should have six entries then?

**Comment by psychocrypt** [comment]
closed - The reason for the  "low" compute utilization is that the cryptonight POW is cache limited and not compute limited.
