### ISSUE TITLE
Cuss high sierra.

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#1749]
I have a Quadro FX4880 that uses compute 1.3

For the life of me I can’t get it working.

The latest cuda driver does not support the gpu

The early cuda is not supported by xmr stak.

How can I get round this?

In fact I can’t even install the cuda version suggested for the gpu because it’s not supported by high sierra.

It’s a waste of hash power, I only cpu mine. This card although being old may almost double my output if enabled.

**Comment by Spudz76** [comment]
You are correct there is no way to use CUDA (for mining) on cards older than compute 2.0 - however the old drivers supported OpenCL before CUDA was even useful.

So, use `xmr-stak --noNVIDIA --openCLVendor NVIDIA` and it may work, that is what the openCLVender flag is actually for ('most' CUDA supported GPUs perform better via CUDA, other than those with bad old CUDA but usable OpenCL)

Although I've never gotten xmr-stak to compile successfully against CUDA 7.5 either, just 8/9.1/9.2

**Comment by macminer** [comment]
Great thanks.

Where do I put that?

When compiling using CMake

**Comment by Spudz76** [comment]
no when running on command line

**Comment by psychocrypt** [comment]
https://www.techwalla.com/articles/how-to-add-a-command-line-parameter-to-a-windows-shortcut

**Comment by macminer** [comment]
Thanks, I just tried that.

It’s not giving any NVidia errors when I first start the terminal sesison but I don’t believe it’s using the GPU just the cpu only.

When I press h it only refers to the cpu

**Comment by macminer** [comment]
I don’t believe I have a GPU.txt file, could this be why?
