### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by Gintasz** [fireice-uk/xmr-stak#1753]
deleted

**Comment by psychocrypt** [comment]
I think you have installed a cuda 8 driver and used a cuda 9.x library to
compile xmr-stak.
Install the latest cuda driver and the libraries together.

**Comment by Gintasz** [comment]
Could you show your cmake -LA that’s used for compiling bonaries for shipping? Your binary works, mine doesn’t so I think some compile setting might be different

**Comment by psychocrypt** [comment]
I used cuda 8. As I wrote it looks like a a driver and library issue.

**Comment by Spudz76** [comment]
Do not build within the source root, `mkdir build` and `cd build` and then use `cmake ..` never `cmake .`
You would have to adjust your hwloc path to `..` then also of course.  This is a CMake requirement not our rule, it may not work without following their intended methods.

The CUDA SDK is only for compiling and does not have any runtime included, at all, whatsoever.  That is how CUDA works without installing the SDK, if you have installed the driver you already have some version of CUDA.  If you have a new driver it will be CUDA 9.2 support, but next week when some other new driver comes out it could be CUDA 9.3 all of a sudden, watch the readmes.

If you have 381.xx or so (if I recall correctly) driver it will be CUDA 8 support
I think 394.xx or so (again hazy recall) was where it went to CUDA 9.1

You have check the PDF for the driver release (on nVidia driver pages) on about the 5th page usually, where it lists what APIs are bundled (OpenGL, CUDA, OpenCL... etc) and it will say what runtime version of CUDA that driver is.

CUDA 8 apps (release bins here) run best against CUDA 8 driver, but also work well with 9.1 containing drivers
CUDA 8 apps do not really seem to like CUDA 9.2 but it seems more like backward compatibility errors made by nVidia (not really fixable by source patch here)
Generally CUDA is supposed to be backward compatible but best results are of course where versions match exactly.  That driver the CUDA SDK offered would be ideal.

So compile against the CUDA SDK which your favorite driver is.  Or update to latest driver and continue with the 9.2 SDK.

**Comment by Spudz76** [comment]
@Gintasz one more thing to answer your Release building question, that gets built by Appveyor thus the config file [in tree here](https://github.com/fireice-uk/xmr-stak/blob/master/.appveyor.yml) contains the exact steps used to make releases.  I'm not sure if we can grab the `cmake -LA` equivalents from Appveyor artifacts or not...
