### ISSUE TITLE
Couldnt connect to a server

### ISSUE THREAD

**Issue by 1221328** [fireice-uk/xmr-stak#1761]
I am trying to install XMR Stak on VPS with Ubuntu 18.04. I got this error.

git clone https://github.com/fireice-uk/xmr-stak.git/
Cloning into "xmr-stak"...
fatal: unable to access "https://github.com/fireice-uk/xmr-stak.git": couldnt connect to server

Can using only IPv6 be the problem?

**Comment by Spudz76** [comment]
I have IPv6 and do not see any AAAA record for github.com
So I guess, no, not unless you get around whatever is blocking you at the ISP v6-to-v4 gateway.

I would expect something happening such as [described here](https://medium.com/@cookiengineer/using-github-when-your-isp-does-not-want-you-to-aka-nat-breaking-via-tor-ssh-and-ipv6-5fb9ac40a185)

**Comment by 1221328** [comment]
Okay, thanks.
