### ISSUE TITLE
How to restart one card in whore rig

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#1778]
Time to time we can see that videocard drop speed and out of mining (if card was not proper overclocked).
In report we see `(na)` , no hashrate, in GUI report we have just blank field.

Need to have way to restart only one on several card.
It is possible to add like this feature?

P.S. It is helps to resolve, tune cards for best maximum values, if i can reconfigure card and restart, after this get heshrate, and time work in this mode, if card drops - reconfigure and restart, etc.

![capture](https://user-images.githubusercontent.com/12154217/43994822-d2c90314-9dab-11e8-8b92-13a8b5da599d.PNG)

**Comment by bizlevel** [comment]
For example on HiveOS, some card can restart if drops. Intresting how is it work?

**Comment by Simaex** [comment]
@bizlevel I think you are wrong. Never experienced such behaviour in Hive OS. Feel free to ask Dmytro Shcherbyna, he is the Hive OS teamleader.

**Comment by bizlevel** [comment]
Hm, ok, i got wrong info..
Hm and how to make multi thread miner for each card.. And it is similar miner + proxy) Also need add little monitor to report. Need to think about this, how to wrap all it in one whole decision.

**Comment by Spudz76** [comment]
Only way around driver limitations would be to build rig with qemu and passthru each PCI slot to an ultralight VM, each VM runs an xmr-stak with one GPU that connects up to proxy running on hypervisor, which connects to real pool(s).

Pretty sure some people had PCIe passthru working.

**Comment by bizlevel** [comment]
@Spudz76 Thanks.
