### ISSUE TITLE
comp_mode : false => Only invalid results

### ISSUE THREAD

**Issue by golya87** [fireice-uk/xmr-stak#1849]
Hello

I have a Win10 rig with 6*Vega56 Strix overclocked (1400/900 + 900/900).
When I run the XMR-Stak 2.4.7 with "comp_mode : true", I've got ~10700h/s with valid shares. If I change the "comp_mode : false", I've got ~11000h/s but with invalid shares only.

Is it normal?

Here is my amd.txt, all 6 cards using the same config.

"gpu_threads_conf" : [
  // gpu: gfx901 memory:3920
  // compute units: 56
  { "index" : 0,
    "intensity" : 1920, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : true
  },
{ "index" : 0,
    "intensity" : 1920, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2,
    "comp_mode" : true
  },

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

**Comment by psychocrypt** [comment]
which currency

**Comment by golya87** [comment]
Ahh sry, I missed that. XMR on MiningPoolHub.
With 18.9.2 driver I've got only invalid shares with both comp mode, now I'll try it with 18.5.1.

**Comment by psychocrypt** [comment]
lease downgrade your driver ro 17.x or 18.1. the current driver have a
compielr bug.

**Comment by golya87** [comment]
If I use pre 18.5.1 driver I've got lower hashrates than the Blockchain driver. Before the Win10 1803 it worked well with 18.5.1.

**Comment by psychocrypt** [comment]
lower hashrate is better than no hash rate ;-)
I would like to hel you but this can only be solved by AMD. we informed
already the Rocm team and escalated the issue but I need to say that AMD is
not the best software provider :-(

András Frankovics <notifications@github.com> schrieb am Mo., 24. Sep. 2018,
18:41:

**Comment by golya87** [comment]
With 18.5.1 now it works good. (comp_mode:false, 11kh/s, all valid shares)
