### ISSUE TITLE
Result rejected By Pool

### ISSUE THREAD

**Issue by friedner** [fireice-uk/xmr-stak#1863]
Hi -
At first I got "Result Rejected From Pool"

Now I get that my IP is Banned

I've tried different pools, different drivers and miners,  but keep getting the same error.  Any suggestions?
I have three AMD Vega 64 Cards and I am currently using the Crimson Drivers from AMD and AMDXMRMINER  
TRYING TO MINE THE Safex Cash Coin using Cryptonight_v7, which I believe is Algo=1

Running on
  -Windows 10
  ```
Latest error message:

  
  - - -    AMD XMR Miner v0.65b    - - -

MINER HAVE SUCCESSFULLY STARTED ON PIDX 1

If you have questions, or would like more information about this miner go to http://www.amdxmrminer.com

Miner will now try to access your selected Pool.
To get updated on current report from the miner press 's' on your keyboard, to quit press 'q' on your keyboard, to restart press 'r' on your keyboard


13:26:21: Trying to Connect to eu.pool.safexnews.net:5555 ...
13:26:21: Connected.
13:26:21: SOCKET ERROR - Your IP is banned
13:26:21: SOCKET ERROR - RECEIVE error: A blocking operation was interrupted by a call to WSACancelBlockingCall.
13:26:21: Huston, we lost communications!. We will attempt regain communications in 10 s (we have tried 1 times).
13:26:31: Trying to Connect to eu.pool.safexnews.net:5555 ...
13:26:31: Connected.
13:26:32: SOCKET ERROR - Your IP is banned
13:26:32: SOCKET ERROR - RECEIVE error: A blocking operation was interrupted by a call to WSACancelBlockingCall.
13:26:32: Huston, we lost communications!. We will attempt regain communications in 10 s (we have tried 2 times).

**Comment by psychocrypt** [comment]
You selected the wrong currency. But what I can see is you have not used
xmr-stak on the terminal else you use some wrapper software. IMO the
wrappet software selected the wrong currency. Thats the reason for the
issue.

**Comment by psychocrypt** [comment]
pease download our miner xmr-stak
https://github.com/fireice-uk/xmr-stak/releasesor open an issue where your
current used miner provided an bug tracker.

**Comment by psychocrypt** [comment]
wrong miner, it is not xmr-stak
