### ISSUE TITLE
strided_index=1 not accepted for cryptonight or cryptonight_v7

### ISSUE THREAD

**Issue by jagerman** [fireice-uk/xmr-stak#1869]
This may just be a documentation issue, but the generated `amd.txt` for the current `dev` branch refuses to accept `strided_index=1`, saying `ERROR AMD: gpu 0 stridedIndex is not allowed to be `true` or `1` for the selected currency`.

The documentation inside the generated `amd.txt` seems to imply that it should work for `cryptonight_v7` or `cryptonight` or coins like `graft`, but it does not.  (It does, however, work for the light and heavy variants).

**Comment by srwx666** [comment]
> 
> 
> This may just be a documentation issue, but the generated `amd.txt` for the current `dev` branch refuses to accept `strided_index=1`, saying `ERROR AMD: gpu 0 stridedIndex is not allowed to be`true`or`1`for the selected currency`.
> 
> The documentation inside the generated `amd.txt` seems to imply that it should work for `cryptonight_v7` or `cryptonight` or coins like `graft`, but it does not. (It does, however, work for the light and heavy variants).

set strided_index=0 and it will work correctly

**Comment by psychocrypt** [comment]
fixed in #1874
