### ISSUE TITLE
Setting XMR-STAK as startup service in Ubuntu 16.04

### ISSUE THREAD

**Issue by AniketBhadane** [fireice-uk/xmr-stak#187]
I'm running Ubuntu 16.04 as VMWare Virtual Machine. Downloaded xmr-stak-portbin-linux.tar.gz.

I created a xmr.service file in /lib/systemd/system/

```
[Unit]
Description=xmr
After=network.target

[Service]
ExecStart=/home/aniket/xmr-stak.sh
User=root

[Install]
WantedBy=multi-user.target
```

Ran following commands in terminal:
sudo systemctl daemon-reload
sudo systemctl enable xmr.service
sudo systemctl start xmr.service
sudo systemctl stop xmr.service
sudo systemctl restart xmr.service

Restarted computer.

After Ubuntu restarted, I did systemctl status xmr, and could see status as active.

But in supportxmr dashboard, I cannot see the worker. On manually running the .sh file, I can see the worker in the dashboard. What might be going wrong?

**Comment by AniketBhadane** [comment]
It seems that xmr-stak.sh only reads the config file if you start it manually. If I add the -c option with the path of config file, it works.

ExecStart=/home/aniket/xmr-stak.sh -c /home/aniket/config.txt

**Comment by hoyanf** [comment]
Hi, you can view my current usage and change to fit your's.
cat /etc/systemd/system/xmrstak.service
```
[Unit]
Description=XMR AMD GPU Miner
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/xmr-stak
ExecStart=/opt/xmr-stak/xmr-stak -c /opt/xmr-stak/config.txt --amd /opt/xmr-stak/amd.txt --noCPU
ExecReload=/sbin/start-stop-daemon

[Install]
WantedBy=multi-user.target

```

**Comment by psychocrypt** [comment]
please do not forget to activate daemon mode in the file config.txt, else
the miner will not miner as background service.

**Comment by AniketBhadane** [comment]
The miner is working on startup in background without setting daemon mode in config.txt
