### ISSUE TITLE
`unroll` help text shouldn't include 0 as a valid option

### ISSUE THREAD

**Issue by jagerman** [fireice-uk/xmr-stak#1870]
The help text generated in `amd.txt` with the current `dev` branch says that the valid range for `unroll` is `[0;128)`, but 0 isn't isn't actually allowed (1 already means "don't unroll").  Trying 0 causes a compilation failure with:

```
/tmp/OCL112351T3.cl:1692:18: error: invalid value '0'; must be positive
                #pragma unroll CN_UNROLL
                               ^
<built-in>:9:19: note: expanded from here
#define CN_UNROLL 0
                  ^
1 error generated.
```

Perhaps the text here should be changed to read `[1,128)` instead?

**Comment by psychocrypt** [comment]
solved with #1871
