### ISSUE TITLE
nvidia Invalid Results

### ISSUE THREAD

**Issue by Bathmat** [fireice-uk/xmr-stak#1873]
I'm getting all `Invalid Result` when using the latest dev branch for CNv8. Prior to the last optimizations, results were being submitted. With the latest optimizations, hashrate is faster, but no results.
Tested on 2 systems compiled using MSVC and CUDA 9.1
First system: Win10 GTX-1050
Second: Win7 GTX970 and 1050

[GTX-1050 working](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-425780998)
[Win7 working](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-425945856)

[Improved hashrate](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-427541061) with latest dev branch/CUDA optimizations, but then realized all [invalid results](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-427586516)

**Comment by Bathmat** [comment]
Version: xmr-stak 2.4.7 b0ccccf3

**Comment by Bathmat** [comment]
This is the version that is working: Version: xmr-stak 2.4.7 010cbd98

Perhaps something in this commit? d1e02a70c0eaeb729260c3c2cb1c7e5bf2e4318e

**Comment by psychocrypt** [comment]
Could you please download https://github.com/psychocrypt/xmr-stak/archive/topic-testCUDAAlwaysSync.zip and test if this solves your issue.

**Comment by Bathmat** [comment]
Nope. Still all Invalid with GTX-1050 on Win10. Tried multiple Threads/Blocks combos: 4/40 (auto config), 12/40, 32/15.

**Comment by psychocrypt** [comment]
Could you please test https://github.com/psychocrypt/xmr-stak/archive/fix-cudaMemoryRace.zip
I think I know what is the reason and hoped it will never happened :-(

**Comment by Bathmat** [comment]
Nope. Still Invalid ☹️ 
Version: xmr-stak 2.4.7 86f4da51

And just to make sure nothing is broken on my end, I went back and compiled this version: Version: xmr-stak 2.4.7 5df80757
Shares are being submitted with that version (but with slower hashrate).

**Comment by psychocrypt** [comment]
mhh I will insert an option to switch between the old and new method. It is
strange that it is only broken on your system. But it could be that CUDA
9.1 has some issues. I know that 9.1 has a fee bugs. Could you upgrade to
9.2?

**Comment by Bathmat** [comment]
Still Invalid with CUDA 9.2. I was able to get the latest drivers (411.70) working with my Win7 rig; however, v7 hashrate is slowed down a little with them.
I'll try CUDA 10, but 🤷‍♂️ . 
Am I the only one seeing Invalid with the latest dev branch?

**Comment by Bathmat** [comment]
Is there another MSVC version I should try? I'm using this command from the compiling guide:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11
```

**Comment by Bathmat** [comment]
CUDA 10: Still Invalid 😞

**Comment by SChernykh** [comment]
I tried different versions from this list: https://github.com/fireice-uk/xmr-stak/commits/dev/xmrstak/backend/nvidia/nvcc_code

They all produce invalid results, starting from ~30% invalid results with the first version and 99% with the latest version.

**Comment by psychocrypt** [comment]
I try to reproduce this issue under linux but I never get invalid results. I tried CUDA 10, CUDA 9.2 and CUDA 8 and with and without bfactor.

**Comment by Bathmat** [comment]
> I try to reproduce this issue under linux but I never get invalid results. I tried CUDA 10, CUDA 9.2 and CUDA 8 and with and without bfactor.
> 
> Are you changing the cmake variable `CUDA_ARCH`?

No. The only extra flag I'm using is `-DXMR-STAK_COMPILE=generic` so I can use it on different CPUs.

**Comment by psychocrypt** [comment]
@SChernykh If you get low difficulty shares than you are using the wrong currency. The CPU code should be correct and in that case each share is checked before it is send to the pool. This means, the miner must be totally broken or must produce invalid shares if only CUDA code hash bugs.

**Comment by SChernykh** [comment]
@psychocrypt Low diff shares were for the old code without the final tweak - 30% invalid results (not sent to pool), 70% sent to pool but low diff. With the latest code I don't get low diff shares, but 99% results are invalid.

**Comment by psychocrypt** [comment]
@Bathmat  @SChernykh Could you please test https://github.com/psychocrypt/xmr-stak/archive/topic-cudaFunction.zip this is #1878 and added a new option to the NVIDIA config (therefore please do not reuse the old config) By default the old memory load operation will be used.
Is this solving the issues?

**Comment by SChernykh** [comment]
> https://github.com/psychocrypt/xmr-stak/archive/topic-cudaFunction.zip

This one doesn't produce invalid results, which is good, but GPU driver crashes after a minute or two. Maybe driver crash is unrelated though.

**Comment by SChernykh** [comment]
This is the best I got, crashed after ~2 minutes:
```
RESULT REPORT
Difficulty       : 200
Good results     : 25 / 25 (100.0 %)
Avg result time  : 2.0 sec
Pool-side hashes : 3600

Top 10 best results found:
|  0 |             2444 |  1 |             2375 |
|  2 |             1990 |  3 |             1275 |
|  4 |             1232 |  5 |              953 |
|  6 |              693 |  7 |              359 |
|  8 |              327 |  9 |              321 |

Error details:
Yay! No errors.
[2018-10-08 22:03:24] : Result accepted by the pool.
[2018-10-08 22:03:26] : Difficulty changed. Now: 400.
[2018-10-08 22:03:26] : New block detected.
[2018-10-08 22:03:28] : Result accepted by the pool.
[2018-10-08 22:03:28] : Result accepted by the pool.
[2018-10-08 22:03:29] : Result accepted by the pool.
[CUDA] Error gpu 0: <C:/Temp/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:418
```

**Comment by psychocrypt** [comment]
@SChernykh maybe you must increase bfactor. IN windows a kernel is not allowed to run to long.

**Comment by SChernykh** [comment]
@psychocrypt Increased bfactor from 6 to 7. It doesn't crash now and all results are accepted. Hashrate is only 121 H/s however (CNv7 is 270 H/s).

**Comment by psychocrypt** [comment]
What is if you change `comp_mode` to false?

**Comment by Bathmat** [comment]
I'm also getting Results accepted, but hashrate is at the slower pre-optimized speed since this obviously by-passes the optimizations with `COMP_MODE` (288 h/s instead of 318 h/s on GTX1050).

**Comment by SChernykh** [comment]
> What is if you change comp_mode to false?

All results are invalid again, but hashrate is better. 200 H/s vs 140 H/s with comp_mode=true (I managed to get it a bit better).

**Comment by Bathmat** [comment]
`comp_mode : false` Invalid results

**Comment by Bathmat** [comment]
@SChernykh try `threads` from 4 to 12 and `blocks` : smx times 8
Those have been giving me the best results on v8. Threads depends on the GPU

**Comment by psychocrypt** [comment]
Mhh I think we need to release the miner with `comp_mode` : false and I hope that I can find the reason why it is not working soon. It looks like a WINDOWS issue. I tried the miner on 5 different GPUs and never got invalid results. But I tested all under LINUX.

**Comment by SChernykh** [comment]
@Bathmat The best I could get was 143.2 H/s with threads=16, blocks=56 (GTX 660 Ti has 7 smx).

**Comment by Bathmat** [comment]
Ran stak for 15 minutes+ with `comp_mode : true`. No issues, no invalids, hashrate: 289 h/s (GTX-1050)

**Comment by xmrig** [comment]
@psychocrypt I figure out what wrong, `sizeof(ulong4)` is `16` on Windows and `32` on Linux, so solution is simple, use `ulonglong4` on both platform, it fixes invalid shares.
Thank you.

**Comment by psychocrypt** [comment]
Ohh cool big thx @xmrig
I hate the fucking C/C++ standard. The definition of int is that it must
have at least 16bit and also long is defined to have at least 16bit.
We discussed it yesterday at work together with a other open source
library.
It come never in my mind that this is the issue in xmr-stak.

**Comment by SChernykh** [comment]
This is why I prefer stdint.h and fixed size types (int32_t, int64_t, etc).

**Comment by psychocrypt** [comment]
Yes but tyoes than ulong4 are shipped by nvidia. But also the stdint types
make trouble if you overlad templates. Because uint64_t can collide with
long or lon long. All in all this dynamic platform dependent sizes make
only trouble.

**Comment by psychocrypt** [comment]
could someone please test #1887 in windows. Please remove your current `nvidia.txt` the new auto adjust will set `comp_mode` by default to `false` and use 256bit reads

**Comment by SChernykh** [comment]
https://github.com/psychocrypt/xmr-stak/commit/ed2168b48d16a9870cbef067d38a5ad16b26c9f9 works for me, all results are accepted (more than 100 results so far).

**Comment by SChernykh** [comment]
Ran it for ~35 minutes, everything worked fine:
```
RESULT REPORT
Difficulty       : 10000
Good results     : 122 / 122 (100.0 %)
Avg result time  : 17.1 sec
Pool-side hashes : 453100

Top 10 best results found:
|  0 |         58453026 |  1 |           566806 |
|  2 |           227480 |  3 |           125472 |
|  4 |           101744 |  5 |            55207 |
|  6 |            42759 |  7 |            40295 |
|  8 |            36457 |  9 |            32603 |

Error details:
Yay! No errors.
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  202.2 |  202.0 |  202.1 |
Totals (NVIDIA):   202.2  202.0  202.1 H/s
-----------------------------------------------------------------
Totals (ALL):    202.2  202.0  202.1 H/s
Highest:   202.3 H/s
-----------------------------------------------------------------
```

**Comment by Bathmat** [comment]
I will test later today after I have some time to recompile.

**Comment by SChernykh** [comment]
@psychocrypt I've optimized integer math for CUDA: https://github.com/SChernykh/fast_int_math_v2_cuda/commit/2ac043c097449f29ed0cec4a9100b68c1e4cf636

It works faster on NVIDIA cards. I'll test optimized OpenCL version this evening.

**Comment by Bathmat** [comment]
Tested on my GTX-1050 on Win10. Working, Results accepted 👍 
Speed with `comp_mode: false` is slower than before (310 h/s) with threads/blocks: 12/40 (this was previously the fastest setting). However, with T/B: 32/20 (same config for v7) speed is 318 h/s 🥇 

I can test again once @SChernykh's optimizations are incorporated.

**Comment by psychocrypt** [comment]
Good to know that comp_mode is sometimes slower. Than I will leave the
option for the user to set comp_mode to true.

**Comment by Bathmat** [comment]
> Good to know that comp_mode is sometimes slower. Than I will leave the option for the user to set comp_mode to true.

With `comp_mode: true`, speed is much slower: 290h/s

**Comment by Bathmat** [comment]
Tested with my Win7 rig: working 👍 
Best config (from a very brief test) was using the same settings as cnv7.
GTX-970: 450 h/s (93.75% of V7), T/B: 16/39

P.S. I compiled using CUDA 9.1

**Comment by SChernykh** [comment]
@psychocrypt 
Huh, even though my optimized math code was ~10% faster on GTX 1060 when tested alone, real mining hashrate didn't change at all on GTX 660 Ti with new code. Maybe it will be faster on Pascal cards. At least this code doesn't eat 1 KB of shared memory.

**Comment by SChernykh** [comment]
@Bathmat You can test the new math code in xmrig: https://github.com/xmrig/xmrig-nvidia/commits/dev

**Comment by psychocrypt** [comment]
note the option comp_mode will not be available in the next release. I
renamed it to mem_mode to reflect what the option is doing.

**Comment by SChernykh** [comment]
@psychocrypt I've tried to port this new CUDA math code to OpenCL for AMD cards, but it wasn't faster, even a bit slower in some tests.

**Comment by psychocrypt** [comment]
I tried it also but ended up with invalid shares. Due to the full time
table I looked only short into it.
