### ISSUE TITLE
Low hash rate 580/8gb,570/4gb (bit.tube)

### ISSUE THREAD

**Issue by sandrodz** [fireice-uk/xmr-stak#1875]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Sapphire Pulse RX 580 8GB / MSI ARMOR RX 580 8GB 
  - RX 570 4gb Asus ROG / XFX 570 4gb

# Stability issue
  - Is the CPU or GPU overclocked? - YES
  - Is the Main memory of the CPU or GPU undervolted? - NO

I cannot set intensity to anything over 1000 for any of these cards. In previous versions of XMR-Stak I believe I had 1600 for 8gb cards.

<img width="1207" alt="screen shot 2018-10-08 at 3 17 02 am" src="https://user-images.githubusercontent.com/8479569/46588245-f6945480-caa9-11e8-8dbb-f7cfbdac9ff2.png">

hash rate is also 2800 for all 4 cards, seems low compared to what I see on the net.

Anything I can do?

**Comment by Spudz76** [comment]
When did you last mine IPBC / Bittube coins?  Before April?

They changed from 2MB (normal CN) to 4MB (Heavy) [in April](https://twitter.com/BitTubeApp/status/979397283757379584)

Thus also, pay attention to benchmark results you compare yourself to, if they are not from after the fork, they are invalid (2MB is faster but perhaps not quite double, depends on the GPU) - it's not as easy as cutting the old hashrate in half to know what to expect.

However it does work for intensity, whatever your best setting for 2MB scratchpad was, cut it in half (your 1000 now is like 2000 before... no wonder it won't work)  800 is like the old 1600

**Comment by psychocrypt** [comment]
as @Spudz76 said the algorithm has changed and therefore you can not compare very old hash rates with the current.

**Comment by sandrodz** [comment]
So what hash rate can I expect from these cards? I'd like to have some baseline for comparison.
