### ISSUE TITLE
One Card out of 4 is hardly hashing

### ISSUE THREAD

**Issue by sschall947** [fireice-uk/xmr-stak#1879]
Running 4 Asus Rx 580 4gb cards 3 are hashing normally 1 is hardly breaking 400.

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  503.1 |   (na) |   (na) |  1 |  510.5 |   (na) |   (na) |
|  2 |  512.7 |   (na) |   (na) |  3 |  501.7 |   (na) |   (na) |
|  4 |  502.7 |   (na) |   (na) |  5 |  511.3 |   (na) |   (na) |
|  6 |  214.7 |   (na) |   (na) |  7 |  214.6 |   (na) |   (na) |
Totals (AMD):  3471.2    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   3471.2    0.0    0.0 H/s
Highest:  3471.9 H/s

AMD config is:
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true, "mem_chunk" : 2, "comp_mode" : true },
 * ],
 * If you do not wish to mine with your AMD GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3136
  // compute units: 36
  { "index" : 0,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
 },
  { "index" : 0,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3136
  // compute units: 36
  { "index" : 1,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3136
  // compute units: 36
  { "index" : 2,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: Ellesmere memory:3136
  // compute units: 36
  { "index" : 3,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 3,
    "intensity" : 896, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,
 Any Ideas? Running on windows 10

**Comment by psychocrypt** [comment]
could it be that your windows is using this card for rendering tasks? You
can check if it is an card issue by switching the last card with another
card.

**Comment by Simaex** [comment]
Try different intencities for the card hashing low. Lower intencity may be better for the card. It is a known issue that Windows use one GPU for some tasks, you have to switch to different OS for complete solution. In case you do not intend to use more GPU you may try Win7 but I'll better opt to some Linux version.

**Comment by psychocrypt** [comment]
no I mean switching the cards in the hardware slot on the mainboard

**Comment by Simaex** [comment]
@psychocrypt You suggestion will prove that the issue is not hardware dependent. I try to suggest how to maximize hashrate in current system. I have similar issue in Win10 system when exactly the same cards need lower intencities in one PCIe slot.

**Comment by sschall947** [comment]
I have switched out the last card 3 times with the same results. None of the cards should be rendering anything, the unit has onboard graphics.  It seems as if the hardware is not the issue.

**Comment by QoOdrink3r** [comment]
So the same card always hashes low? Welcome to the  Silicon Lottery. 🗡

**Comment by sschall947** [comment]
No was one of my pcie slots is being weird, moved cards all around until issue resolved itself. All cards are not hashing closer to each other.
