### ISSUE TITLE
Windows SOCKET ERROR 4428:error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match:.\ssl\ssl_lib.c:1305:

### ISSUE THREAD

**Issue by simonlui** [fireice-uk/xmr-stak#189]
I compiled using the instructions given on WIndows 10 FCU, Visual Studio 2017, using an Intel and Nvidia system. I am getting the following when connecting to pools that have TLS/SSL support.

> xmr-stak 2.0.0 0000000
> 
> Brought to you by fireice_uk and psychocrypt under GPLv3.
> Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
> Based on NVIDIA mining code by KlausT and psychocrypt.
> 
> Configurable dev donation level is set to 2.0%
> 
> You can use following keys to display reports:
> 'h' - hashrate
> 'r' - results
> 'c' - connection
> -------------------------------------------------------------------
> [2017-11-21 00:15:23] : Start mining: MONERO
> [2017-11-21 00:15:23] : Starting NVIDIA GPU thread 0, no affinity.
> [2017-11-21 00:15:23] : Starting single thread, affinity: 0.
> [2017-11-21 00:15:23] : hwloc: memory pinned
> [2017-11-21 00:15:23] : Starting single thread, affinity: 2.
> [2017-11-21 00:15:23] : hwloc: memory pinned
> [2017-11-21 00:15:23] : Starting single thread, affinity: 4.
> [2017-11-21 00:15:23] : hwloc: memory pinned
> [2017-11-21 00:15:23] : Fast-connecting to xmr-us-west1.nanopool.org:14433 pool ...
> [2017-11-21 00:15:24] : SOCKET ERROR - [xmr-us-west1.nanopool.org:14433] 4428:error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match:.\ssl\ssl_lib.c:1305:
> 
> [2017-11-21 00:15:24] : Fast-connecting to pool.supportxmr.com:443 pool ...
> [2017-11-21 00:15:24] : SOCKET ERROR - [pool.supportxmr.com:443] 4428:error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match:.\ssl\ssl_lib.c:1305:

I have another all AMD system that I compiled using Linux which doesn't have this issue and is connecting using the same TLS/SSL ports as the output listed.

Is there something up with the xmr-stak-dep openssl.dll that was provided or is there something else possibly? I also don't know what version of OpenSSL you compiled but if it is the latest, the line referenced seems to be calling a function inside SSL_set_wfd

`SSL_set0_wbio(s, rbio);`

Not quite sure what's up with that, I haven't worked with the library to know what it is exactly doing there.

**Comment by psychocrypt** [comment]
please provide all commands you have used to build the miner.

**Comment by simonlui** [comment]
So using non-SSL works for now temporarily as a workaround. I still have work today before the Thanksgiving holiday in the US and will be busy for half a day Wednesday so it might be a while until I can reproduce the issue here.

I used a mix of command line and GUI to compile the application and the process worked perfectly up to the point of opening up my application, but I'll try and keep it command line based when reproducing.

**Comment by psychocrypt** [comment]
@fireice-uk could you please check this TSL issue

**Comment by simonlui** [comment]
Sorry, stuff came up and I was only able to do a reproduction just a moment ago. The issue for this is because of not doing the last two steps, apparently. I was missing the following commands:

`cd bin\Release
copy C:\xmr-stak-dep\openssl\bin\* .`

Missing either libeay32.dll, which I assume is probably what the error is complaining about, or ssleay32.dll will cause this. I will be closing the issue.
