### ISSUE TITLE
Build on Windows 10 and CUDA 9: 66warning 0 error. 

### ISSUE THREAD

**Issue by at-bachhuynh** [fireice-uk/xmr-stak#190]
Edited!
Hi there,
I built it with 66 warning and 0 error.
In bin\Release folder have one exe file and it can not run.
I follow the guide: https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md

Please help me!

**Comment by at-bachhuynh** [comment]
I found that it can run now,
But get some error:
[2017-11-21 17:29:56] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-11-21 17:29:56] : WARNING: backend NVIDIA disabled.
[2017-11-21 17:29:56] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-11-21 17:29:56] : WARNING: backend AMD disabled.
[2017-11-21 17:29:57] : CPU configuration stored in file 'cpu.txt'
[2017-11-21 17:29:57] : Starting single thread, affinity: 0.

I don't want use CPU to mine, I have 7 cards 1060 on the PC, but it does not work!

Where I can fix it?

**Comment by at-bachhuynh** [comment]
Hi all,
I try to test your release again, and have the same error?
Please hardly check! Thank you!

**Comment by sergneo** [comment]
Downloads drivers Nvidia 388.31  WHQL and everything will be fine.

**Comment by at-bachhuynh** [comment]
@sergneo Not fine :(.
The hash rate very low with the same config.
And it not stable.

**Comment by saylor68** [comment]
not to threadjack, but only comment, I hope to add to this desc also - when I compiled I had '60' warnings '0' errors , but i did not study the output warnings. it compiled the EXE, which did execute. when I get home from work tonight I will recompile and study/post here the warnings. Win10x64 - followed the windoze compile guide (which is great BTW).

thanks!
- saylor

**Comment by psychocrypt** [comment]
Only a few warnings are interesting the post are f...ing windows stuff. Do
not worry the warnings are no problem.

**Comment by at-bachhuynh** [comment]
> Please describe which error do you have. From you posts I can see that the
miner is runnninf. Please keep in mind a warning is no error.
In the first post you wrote you followed the linux compile guide but build
a windows binary.

Hi @psychocrypt P
Thank you for your reply.
I edited the first post, my mistake about the link to the guide.
I this the driver is the new problem for us.
I tested as follow:
- I use Driver 382.53 for my P106-100 Nvidia Card (1060 6G without output port): the hashrate very stable:
(xmr-stak-nvidia)
```
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 579.3 | 579.9 | 579.7 |  1 | 578.3 | 579.0 | 579.1 |
|  2 | 579.0 | 578.9 | 578.9 |  3 | 578.9 | 579.4 | 579.6 |
|  4 | 580.1 | 579.9 | 579.7 |  5 | 580.2 | 580.6 | 580.6 |
|  6 | 580.6 | 580.0 | 580.2 |  7 | 579.7 | 580.1 | 579.9 |
-----------------------------------------------------
```

- I install the latest version of driver 388.31 to can use with your xmr-stak (not my build).
The hash rate very low, and not the same with each card.
```
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 550.1 | 550 | 555 |  1 | 545.1 | 546 | 546.5 |
|  2 | 540 | 540.2 | 540.5 |  3 | 535 | 535.5 | 535.8 |
|  4 | 500 | 500.5 | 500.5 |  5 | 505 | 505.5 | 505.8 |
|  6 | 480 | 480.5 | 480.7 |  7 | 480 | 480.5 | 480.6 |
-----------------------------------------------------
```
- Keep driver version 388.31 and use the xmr-stak-nvidia. It the same report.

So, the version 388.31 is not good for me right now.

Sadly, the xmr-stak cannot work on 382.53 :(

I really want to use xmr-stak to run nicehash. Please make a compatible version xmr-stak to comfort 382.53. 
Thank you!

**Comment by saylor68** [comment]
@at-bachhuynh  forgive me for jumping onto your post - and if needed I will move to some other post, but these are sample warnings I have that I thought may be interesting. see if you have some of the same errors when compiling:
D:\xmr-stak\xmr-stak\crypto\c_blake256.c(151): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss o
f data [D:\xmr-stak\xmr-stak\build\xmr-stak-c.vcxproj]

D:\xmr-stak-dep\hwloc\include\hwloc/helper.h(1238): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\xmr-stak\xmr-stak\build\xmr-stak-cpu.vcxproj]

d:\xmr-stak\xmr-stak\crypto/cryptonight_aesni.h(359): warning C4267: 'argument': conversion from 'size_t' to 'int', p
ossible loss of data [D:\xmr-stak\xmr-stak\build\xmr-stak-cpu.vcxproj]

I only had 30 warnings this time, and I do not know the significance of these. if they are worthy, I can post all 30.

thanks!
- saylor

**Comment by psychocrypt** [comment]
Please open an new issues for the warning. Else we mix two issues and
nobody can follow the process to solve it.

Am 22.11.2017 3:51 Vorm. schrieb "saylor68" <notifications@github.com>:

**Comment by psychocrypt** [comment]
You can install cuda 8 and build the miner for fermi and for pascal.
A programm build with an old cuda is also ru ning on a new driver but not
the other way around.

**Comment by at-bachhuynh** [comment]
Hi @psychocrypt,
I build it with CUDA8,
I stay the driver 382.53, and this is result:
```
HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 530.5 | (na) | (na) |  1 | 505.0 | (na) | (na) |
|  2 | 545.1 | (na) | (na) |  3 | 545.6 | (na) | (na) |
|  4 | 544.2 | (na) | (na) |  5 | 501.3 | (na) | (na) |
|  6 | 393.8 | (na) | (na) |
```
-----------------------------------------------------

What the problem we got? :(

**Comment by psychocrypt** [comment]
Sry I don not get it, is there still an issue? The hash rates looks good or
not?

**Comment by at-bachhuynh** [comment]
as you see:
HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 530.5 | (na) | (na) |  1 | 505.0 | (na) | (na) |
|  2 | 545.1 | (na) | (na) |  3 | 545.6 | (na) | (na) |
|  4 | 544.2 | (na) | (na) |  5 | 501.3 | (na) | (na) |
|  6 | 393.8 | (na) | (na) |
The hashrate is very very bad :|

**Comment by psychocrypt** [comment]
Is this the hash rate with cuda9 or cuda8?
It could be that cuda8 is faster if so please switch ro cuda8.

If you use the word bad please give exact numbers what you expect. I follow
around 30 issues thus I can not remember each hashrate.

**Comment by at-bachhuynh** [comment]
Goodmorning,
That is hashrate on CUDA8, and CUDA9 is the same.
I expect it can work normally like XMR-STAK-NVDIA:
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 579.3 | 579.9 | 579.7 |  1 | 578.3 | 579.0 | 579.1 |
|  2 | 579.0 | 578.9 | 578.9 |  3 | 578.9 | 579.4 | 579.6 |
|  4 | 580.1 | 579.9 | 579.7 |  5 | 580.2 | 580.6 | 580.6 |
|  6 | 580.6 | 580.0 | 580.2 |  7 | 579.7 | 580.1 | 579.9 |

**Comment by psychocrypt** [comment]
What was the hashrate with xmr-sak-nvidia?

**Comment by at-bachhuynh** [comment]
This is:
HASHRATE REPORT
| ID | 10s | 60s | 15m | ID | 10s | 60s | 15m |
| 0 | 579.3 | 579.9 | 579.7 | 1 | 578.3 | 579.0 | 579.1 |
| 2 | 579.0 | 578.9 | 578.9 | 3 | 578.9 | 579.4 | 579.6 |
| 4 | 580.1 | 579.9 | 579.7 | 5 | 580.2 | 580.6 | 580.6 |
| 6 | 580.6 | 580.0 | 580.2 | 7 | 579.7 | 580.1 | 579.9 |

**Comment by psychocrypt** [comment]
Do you use the same config for both miner?
Please post the nvidia.txt of the new miner and the threadconf of the old
miner.

**Comment by at-bachhuynh** [comment]
Yes,
The same config!

**Comment by psychocrypt** [comment]
please post the config. If you changed the config by hand please post also
the auto suggested config (remove nvidia.txt to generate a new config)

**Comment by hishikishi** [comment]
how to Disable CPU mining ? & my PC is Running slow hang after i start the mining ? what to do ?
& how to reduce speed of GPU
