### ISSUE TITLE
Build 2.5 on Windows fails using VC2017 community and cmake

### ISSUE THREAD

**Issue by pstimpel** [fireice-uk/xmr-stak#1901]
with 2.2(?) I set up a build environment using VS 2017 community and cmake. It worked well, with all the updates followed.

But, after pulling the last changes from the repo it tells about missing external symbols

xmr-stak-backend.lib(minethd.obj) : error LNK2001: Nicht aufgel÷stes externes Symbol "cryptonight_v8_mainloop_ivybridge_asm". [C:\xmr-stak\build\xmr-stak.vcxproj]

xmr-stak-backend.lib(minethd.obj) : error LNK2001: Nicht aufgel÷stes externes Symbol "cryptonight_v8_mainloop_ryzen_asm". [C:\xmr-stak\build\xmr-stak.vcxproj]

xmr-stak-backend.lib(minethd.obj) : error LNK2001: Nicht aufgel÷stes externes Symbol "cryptonight_v8_double_mainloop_sandybridge_asm". [C:\xmr-stak\build\xmr-stak.vcxproj]

C:\xmr-stak\build\bin\Release\xmr-stak.exe : fatal error LNK1120: 3 nicht aufgel÷ste Externe [C:\xmr-stak\build\xmr-stak.vcxproj]

Options:
cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..

cmake --build . --config Release --target install

What I am missing? Thanks in advance

**Comment by psychocrypt** [comment]
please empty the build folder and start all from the beginning. Than post
all output from cmake and the build process to pastbin and link ot here.
Please do not foget to post each environment variable you set by hand in
the terminal. We can only help if we see all output even if it not looks
important.
The ci is passing fine and also my Visual Studio (but I never updated it
since 8 mounth).

**Comment by Spudz76** [comment]
If not using CUDA/OpenCL you may use v141 (and the v2 xmr-stak-dep package)

CPU backend builds with 14.15 runtime (latest patches) only reason to hold back to v140 is for CUDA.

**Comment by pstimpel** [comment]
OK, I did as you told, psychocrypt.

https://pastebin.com/iB39U47T

@Spudz76 I read about this, but dislike to change 2 things ata given time. Thanks for pointing this out

**Comment by pstimpel** [comment]
@Spudz76 :

Changed to 

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF 

and downloaded depsV2, killed the content of the build folder again...same failures.

**Comment by psychocrypt** [comment]
I have never tried to disable the cuda and opencl backend in windows. I can see from your log that somehow all the asm code is not created. I am wondering why.

**Comment by pstimpel** [comment]
If you disable it, can you reproduce this?

**Comment by Spudz76** [comment]
I compile win-cpuonly all the time, including recent dev branch, works.

What version of cmake?

**Comment by pstimpel** [comment]
@Spudz76 : Thanks a lot. I was trying your batch file, adapted only the paths, double-checked to have it all right...but it fails with the same error message. 

cmake is 3.9.6

**Comment by pstimpel** [comment]
I am an idiot and should be allowed to use cpus anymore...

Of course it works all well...but only of you pull the whole repo. I was pulling the xmrstak subfolder only, so I had the old CmakeLists.txt...

Again, sorry guys!

**Comment by Spudz76** [comment]
Or, that. :)
