### ISSUE TITLE
2.5.0 has issues connectins to some pool

### ISSUE THREAD

**Issue by lhirlimann** [fireice-uk/xmr-stak#1909]
Please provide as much as possible information to reproduce the issue.

# Issue with the execution
  ```
Windows 10/ latest release 2.5.0 - I get disconnected from both monerooocean and xmrpool.net so it can't really mine.

**Comment by psychocrypt** [comment]
please post all aoutput from the miner

**Comment by lhirlimann** [comment]
Kecpbac was using cryptonigt-v8 insated of menero
