### ISSUE TITLE
vega56 cnv2 test very low hash

### ISSUE THREAD

**Issue by onweer** [fireice-uk/xmr-stak#1910]
OS: Windows 10
Backend:
- RX Vega56
core: 1407 , mem: 900
speed:  
 - cryptonight_v7: 1800 H/s   100%
 - cryptonight_v8: 900 H/s     only 50%

Miner config: 
"gpu_threads_conf" : [
  { "index" : 0,
    "intensity" : 1696, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

**Comment by psychocrypt** [comment]
what was your solution?
