### ISSUE TITLE
miner hangs/freezes

### ISSUE THREAD

**Issue by ITwrx** [fireice-uk/xmr-stak#192]
this issue https://github.com/fireice-uk/xmr-stak-amd/issues/110 still seems to be present in xmr-stak-2.0.0. daemon mode seemed to help by a large margin with xmr-stak-amd but it would still eventually hang(3-4 days instead of hours/1-2 days). i'm trying daemon mode on xmr-stak-2.0.0 now. Regular mode hung up just like xmr-stak-amd did. 
i have one machine that is still running xmr-stak-amd which never hangs/freezes. it has stock 480s with one stock rx570. the machine that hangs up consistently has 6 (all stock) rx570s. Both are running arch linux with amdgpu and opencl-amd. the miner with rx570s was previously running ubuntu with amdgpu pro and exhibited the hanging/freezing behavior. I moved to arch linux hoping the problem was the proprietary driver. also, the hanging/freezing issue did not manifest itself until i added the 6th gpu. However, i disconnected card6 and xmr-stak-amd still hung up so it shouldn't be a hardware issue.
thanks

**Comment by psychocrypt** [comment]
Do you have overclocked and/or undervolted your equipment?
If so this can be the reason for the freezes. The memory error rate
increases very soon if it is overclocked.

**Comment by ITwrx** [comment]
no. all stock/factory.

**Comment by ITwrx** [comment]
btw, the miner that runs 24/7 without issue is using 
kernel: 4.12.8-2 
ocl-icd 2.2.11-1
opencl-amd 17.10.410326-1
opencl-headers 2:2.2.20170516-1

while the trouble maker is using 
kernel: 4.13.12-1
ocl-icd 2.2.11-1
opencl-amd 17.40.483984-1
opencl-headers 2:2.2.20170516-1
opencl-mesa 17.2.5-1

i don't know what you've tested with.

**Comment by psychocrypt** [comment]
Could you change the software of the rig which is freezing to the same than
the running system.
With the current information I would say it is an driver issue. Normally
the miner which runnning i  userspace ahould not be able to crash the gpu
or system.

**Comment by ITwrx** [comment]
i'll look into it. i don't like stopping the miners. :) i should clarify that xmr-stak nor xmr-stak-amd are able to crash the whole system for me. i just can't kill the xmr-stak/xmr-stak-amd process so i have to log into another terminal and reboot and restart xmr-stak.

**Comment by ITwrx** [comment]
i rolled back the kernel but i don't have a copy of opencl-amd 17.10.410326-1/amdgpu pro 17.10. i tried the latest version in aur since AMD fixed their broken download, but it just hung last night after running for 9 hours. i've increased the verbosity of the xmr-stak log so maybe it will show me hashrate dropping on one of the cards or something. any clue would be nice. the only other variable i can think of is the uefi. i updated that around the time the 6th card went in. there was a cpu related uefi bug. maybe the pci slots need to be set at 1x instead of auto or something like that. i'll check it the next time it hangs up. It would be nice if xmr-stak could just background any troublemaking gpu and keep working with the others and periodically test the backgrounded gpu and when it's working again bring it back into the fold. Or in some other way handle any misbehaving hardware.

**Comment by ITwrx** [comment]
it's only been running sucessfully for 19 hours in but i think i found the problem.  i forgot that i had added my user to the "video" group with the first miner and that i was **temporarily** running xmr-stak on the second miner as root because i didn't know why clinfo wouldn't show my devices as the normal user. I'm not in the habit of using these deprecated groups(at least for systemd distros) so i didn't think about it/remember (i had read the amd driver install instructions once before).  sorry for wasting your time. maybe my mistake would be a good candidate for the docs? either way, thanks for trying to help. 

i'll wait a little while to make sure that was the problem before i close this issue.

**Comment by ITwrx** [comment]
well it hung up again, but now it showed multiple lines of  "Dev pool socket error - mining on user pool...".

**Comment by psychocrypt** [comment]
please post the log.

Am 27.11.2017 01:17 schrieb "ITwrx" <notifications@github.com>:

**Comment by ITwrx** [comment]
i didn't have it logging at the time. i got the snippet i posted from the terminal output which had frozen when xmr-stak hung up. here's a snippet from the currently running instance(same miner) which seems to be having similar issues, though it's still mining so far.

`[2017-11-27 03:43:23] : Dev pool socket error - mining on user pool...
[2017-11-27 03:43:53] : Fast-connecting to dev pool ...
[2017-11-27 03:43:53] : Dev pool socket error - mining on user pool...
[2017-11-27 03:44:23] : Fast-connecting to dev pool ...
[2017-11-27 03:44:23] : Dev pool socket error - mining on user pool...
[2017-11-27 05:22:22] : Fast-connecting to dev pool ...
[2017-11-27 05:22:22] : Dev pool socket error - mining on user pool...
[2017-11-27 05:22:52] : Fast-connecting to dev pool ...
[2017-11-27 05:22:52] : Dev pool socket error - mining on user pool...
[2017-11-27 05:23:22] : Fast-connecting to dev pool ...
[2017-11-27 05:23:22] : Dev pool socket error - mining on user pool...
[2017-11-27 05:23:52] : Fast-connecting to dev pool ...
[2017-11-27 05:23:52] : Dev pool socket error - mining on user pool...
[2017-11-27 05:24:22] : Fast-connecting to dev pool ...
[2017-11-27 05:24:22] : Dev pool socket error - mining on user pool...
[2017-11-27 06:27:02] : SOCKET ERROR - [xmr-us-east1.nanopool.org:14433] RECEIVE error: socket closed
[2017-11-27 06:27:02] : All pools are dead. Idling...
[2017-11-27 06:27:31] : Fast-connecting to xmr-us-east1.nanopool.org:14433 pool ...
[2017-11-27 06:27:31] : SOCKET ERROR - [xmr-us-east1.nanopool.org:14433] Unknown TLS error. Secure TLS maybe unspported, try setting tls_secure_algo to false.
[2017-11-27 06:28:01] : Fast-connecting to xmr-us-east1.nanopool.org:14433 pool ...
[2017-11-27 06:28:01] : TLS fingerprint [xmr-us-east1.nanopool.org:14433] SHA256:longstringoftextwashere=
[2017-11-27 06:28:01] : Pool xmr-us-east1.nanopool.org:14433 connected. Logging in...
[2017-11-27 07:02:21] : Fast-connecting to dev pool ...
[2017-11-27 07:02:21] : Dev pool socket error - mining on user pool...
[2017-11-27 07:02:51] : Fast-connecting to dev pool ...
[2017-11-27 07:02:51] : Dev pool socket error - mining on user pool...
[2017-11-27 07:03:21] : Fast-connecting to dev pool ...
[2017-11-27 07:03:21] : Dev pool socket error - mining on user pool...
[2017-11-27 07:03:51] : Fast-connecting to dev pool ...
[2017-11-27 07:03:51] : Dev pool socket error - mining on user pool...
[2017-11-27 07:04:21] : Fast-connecting to dev pool ...
[2017-11-27 07:04:21] : Dev pool socket error - mining on user pool...
`
this is the first i've noticed mine having trouble with tls or connecting to nanopool. i had previously only seen it having trouble with connecting to dev pool.

**Comment by ITwrx** [comment]
i just found a copy of amdgpu pro 17.10 so i made a PKGBUILD for opencl-amd 17.10 and installed it. it's not the same exact version of 17.10 as i have on miner1 but at least it's 17.10. i notice that 17.10 shows 7 devices when running clinfo while 17.40 only showed 6 devices (same machine). i couldn't be bothered to look through the devices list, but my guess would be that one detects the i5 while the other doesn't. strange. running xmr-stak with 17.10 now. will let you know what happens.

**Comment by ITwrx** [comment]
hung up again. would compiling and running with debug tell us anything if it hangs up like this? is there any other info i can provide that will help you to know what the problem is?
here's the only things in my system log that are out of the ordinary and gpu related.

amdgpu: [powerplay] [AVFS] Something is broken. See log!
Nov 27 09:35:15 nombredecomputador kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!

amdgpu 0000:0f:00.0: VM size (-1) must be a power of 2

kernel: [drm] BIOS signature incorrect 0 0
Nov 27 09:35:05 nombredecomputador kernel: amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
Nov 27 09:35:05 nombredecomputador kernel: ATOM BIOS: MS-V34113-F4

**Comment by nikandco** [comment]
Hello,
it hangs up on my machine too. 
Windows 7 x64. I am running on the CPU i7 6700 miner since I have no GPUs on this system. 
It hangs so bad it even prevents the system from restarting properly. Just stays on the blue screen shutting down.

A strange thing I noticed is that when I first downloaded and played with it for several hours there was no problem. Today on a fresh bootup all the problems started immediately.

**Comment by nikandco** [comment]
Hi again,
its worth mentioning that I found out that my Kaspersky somehow conflicted with the xmr stak,
I tried a new tactic, disabled protection, reboot, xmr stak runs fine and then reenable the KIS (Kaspersky Internet Security) -- while I had it added to the exclusions list it did not help much.

**Comment by ITwrx** [comment]
i notice that in the xmr-stak log it just stops logging when xmr-stak hangs up. nothing at all in system log or in xmr-stak log at that time.

[2017-11-30 05:33:12] : Result accepted by the pool.
[2017-11-30 05:33:45] : Result accepted by the pool.
[2017-11-30 05:33:48] : New block detected.
[2017-11-30 05:33:58] : Result accepted by the pool.
[2017-11-30 05:34:48] : New block detected.
[2017-11-30 05:35:10] : Result accepted by the pool.

5:35am is when the hash drops off on nanopool's chart.

**Comment by ITwrx** [comment]
@psychocrypt please let me know when there's a fix/possible fix in the dev branch.

**Comment by ITwrx** [comment]
i also see that clinfo won't return anything when xmr-stak is hung up.

**Comment by ITwrx** [comment]
this appears to be a hardware issue after all. motherboard stability with 6 GPUs or bad number 6 pci-e slot. or, i guess it could be the driver, but only with more than 5 GPUs? Regardless, it's not xmr-stak, so sorry for the trouble.

**Comment by RJ-MacReady** [comment]
I've been experiencing the same issue. Was able to work though the initial MEMORY ALLOC FAILED: VirtualAlloc Failed issues (#355, thxs, very helpful) and thought it was going smoothly.

![xmr-stak-new block detected freeze up](https://user-images.githubusercontent.com/34753481/34275698-72ccf192-e66c-11e7-998f-3070010dd4cc.jpeg)

I though I had seen another issue open n this #46, we'll try and see what happens. New to this so just trying to work my way thought it and see how it work, great site

**Comment by RJ-MacReady** [comment]
Changed my PSU from 300W to 750W, and corrected my issue. I'm able to view hashrate, results & connection results
