### ISSUE TITLE
2.5.0 vega56 rig - hashrate halved compared to 2.4.7

### ISSUE THREAD

**Issue by xavierx66** [fireice-uk/xmr-stak#1920]
I am upgrading rigs previously all working on 2.4.7 to 2.5.0. 4 rigs so far successful out of 8

2nd problem rig :

MSI x170a M5, G3930 cpu, 4x Vega56
AMD driver : 18.9.1
Windows 10 64bit
Coin "monero" (previously "monero7" on 2.4.7)

Problem:

Getting aprox 50% of hashing speed compared with 2.4.7.
Have tried both single and dual threads.

 amd.txt from 2.4.7

"gpu_threads_conf" : [
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "comp_mode" : true
  },
],

Thread ID | 10s | 60s | 15m | H/s
-- | -- | -- | -- | --
998.8 | 995.7 | 995.4
977.9 | 992.8 | 995.2
987.7 | 991.8 | 992.8
973.1 | 990.4 | 992.7
977.5 | 988.8 | 990.7
983.5 | 989.9 | 990.7
982.3 | 992.8 | 994.1
979.8 | 991.6 | 994.0
7860.6 | 7933.8 | 7945.5

amd.txt from 2.5.0 (auto generated and then modified to 2 thread)

"gpu_threads_conf" : [
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },

Thread ID | 10s | 60s | 15m | H/s
-- | -- | -- | -- | --
588.2 | 572.8 |  
605.5 | 568.7 |  
535.7 | 593.1 |  
529.9 | 597.1 |  
595.7 | 596.8 |  
589.9 | 599.6 |  
503.6 | 560.8 |  
500.1 | 566.3 |  

amd.txt from 2.5.0 unmodified 

"gpu_threads_conf" : [
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:3920
  // compute units: 56
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },

Thread ID | 10s | 60s | 15m | H/s
-- | -- | -- | -- | --
632.1 | 645.9 |  
618.0 | 654.2 |  
597.0 | 655.7 |  
641.5 | 653.4

Thanks for any help

**Comment by psychocrypt** [comment]
please set strided index to 1 for version 2.5.0 this differ to the config
before.

**Comment by psychocrypt** [comment]
the v8 hash rate is it against the same pool?

**Comment by xavierx66** [comment]
Correct, I have only ever used Support-xmr pool

**Comment by psychocrypt** [comment]
If you have per miner stats could you validate if the hash rate on the pool
is higher than what the miner is showing. we fixed a bug in the hash rate
calculation of the miner. I will be sure that you get not shown lower hash
rates on the miner than on the pool.

**Comment by psychocrypt** [comment]
windows or linux. Invalid results point to a broken driver. The latest
adrenalin driver in windows is broken as I know you must switch to 18.6 or
older

xavierx66 <notifications@github.com> schrieb am Sa., 13. Okt. 2018, 16:20:

**Comment by psychocrypt** [comment]
I will try to change some thing and provide a beta test version soon.

**Comment by xavierx66** [comment]
It's in my first post, Windows 10 / Adrenalin 18.9.1
OK well that explains it then, I use recent drivers on Vega rigs as there are instabilities with previous versions (slowdown bug etc) 

I can try switching to 18.6 and report back

I don't think newer driver are broken, as they work fine in xmr-stak 2.4.7, the problem has only occurred when switching to 2.5.0

**Comment by xavierx66** [comment]
I installed AMD drivers 18.5.2 

Using xmr-stak 2.5.0 the hashrate was still only 50% and then I got banned for submitting invalid shares. 

The problem is definately with xmr-stak 2.5.0 not with the AMD drivers

**Comment by unsivilaudio** [comment]
Did you delete your opencl cache files? I know for a fact the 18.6.1/18.5.1 drivers work.  The invalid shares are a result of bad compilation of the cache, its an issue with newer AMD drivers.

**Comment by QoOdrink3r** [comment]
As I reported before I have the same issues with vega 56 & vega 64 on blockchain drivers...

**Comment by xavierx66** [comment]
> As I reported before I have the same issues with vega 56 & vega 64 on blockchain drivers...

I have another issue logged where I do have the same problem on blockchain drivers also (and cache has been cleared)

**Comment by xavierx66** [comment]
> WIN+R, enter "%LocalAppData%" in the box and hit enter, open ".openclcache" and delete all the files in there.

Issue resolved. Thankyou, I didn't think to do that as it was still working on 2.4.7. Much appreciated

**Comment by qwert95** [comment]
I didn't solve the issue that way... still reduced hashrate

**Comment by psychocrypt** [comment]
please have a look to #1930 and test these binaries
