### ISSUE TITLE
Miner reports lower hashrate then pool-side report

### ISSUE THREAD

**Issue by Simaex** [fireice-uk/xmr-stak#1939]
After runnung 2.5.0 version for a night I can definitely say that miner reported hash rate is lower then pool-side hashrate, in my case (i7-3770K + GTX970) miner maximum reported hashrate is 749,5 but pool-side 6-hour average is 810 (nanopool). It is not good cause for brief comparison few people will wait for pool-side average. Note that pool-side do not include miner fee, in my case standart 2%. Also good news - up to 1% lower results error rate. For the old version it was from 1 to 2% bad results, now only 0.4%. In my case miner reported hashrate is up to 10% lower then actual (client pool + miner fee pool). Please share you results. I have a feeling that miner hash rate report should be fine-tuned. 
Software configuration - Windows 8.1 64-bit Ent, using elevated rights for proper huge page initialisation, standart binary 2.5.0, driver 416.34, CUDA 10.0.132

**Comment by JPaulMora** [comment]
Hi, the pool has no idea about your hash rate. it estimates it with how many shares you send. The miner should be reporting the correct value because its the one actually producing the hashes. 

You should ignore pool speed, just make sure your shares are being accepted.

**Comment by Simaex** [comment]
Additional testing show that 12 hour pool-side hash rate is much more close to miner reported hash rate so the issue may be irrelevant.
