### ISSUE TITLE
Need a guide to install or update xmr-stak on Ubuntu?

### ISSUE THREAD

**Issue by cat007mine** [fireice-uk/xmr-stak#1946]
Hi all,
Simpleton user here - currently I have Ubuntu 16.04 running xmr-stak 2.4.3 and need to update to 2.5 but not sure what to do.
Can someone please provide a simple 'how to' guide to install/update xmr-stak on Ubuntu CLI?

thanks in advance.

**Comment by rumatadest** [comment]
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md
