### ISSUE TITLE
Invalid shares HD 7970 and HD 7850 (14.4 driver, Win 10 64)

### ISSUE THREAD

**Issue by xmronadaily** [fireice-uk/xmr-stak#1975]
# Basic information

About the system: 

It's the HD 6990 rig that @psychocrypt  worked on to fix https://github.com/fireice-uk/xmr-stak/pull/1945 and invalid shares on 6990s. 

The system also has HD 7970 and HD 7850 in it, they are hashing, but submitting invalid shares. 

Tested on default AMD config and default GPU core and memory settings. 

"gpu_threads_conf" : [
  // gpu: Cayman memory:1645
  // compute units: 24
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: Cayman memory:1645
  // compute units: 24
  { "index" : 1,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: Cayman memory:1645
  // compute units: 24
  { "index" : 2,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: Cayman memory:1645
  // compute units: 24
  { "index" : 3,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: Tahiti memory:2658
  // compute units: 32
  { "index" : 4,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: Pitcairn memory:1645
  // compute units: 16
  { "index" : 5,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  194.5 |  193.6 |   (na) |  1 |  194.8 |  194.2 |   (na) |
|  2 |  191.5 |  194.0 |   (na) |  3 |  194.6 |  194.3 |   (na) |
|  4 |  283.8 |  283.7 |   (na) |  5 |  124.2 |  126.1 |   (na) |
Totals (AMD):  1183.3 1185.9    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   1183.3 1185.9    0.0 H/s
Highest:  1189.5 H/s
-----------------------------------------------------------------
RESULT REPORT
Difficulty       : 28447
Good results     : 18 / 20 (90.0 %)
Avg result time  : 26.9 sec
Pool-side hashes : 417694

Top 10 best results found:
|  0 |         12982659 |  1 |          1262484 |
|  2 |           289346 |  3 |           189399 |
|  4 |           137353 |  5 |           114302 |
|  6 |           105498 |  7 |            79171 |
|  8 |            51821 |  9 |            51450 |

Error details:
| Count | Error text                       | Last seen           |
|     1 | AMD Invalid Result GPU ID 4      | 2018-10-19 11:35:50 |
|     1 | AMD Invalid Result GPU ID 5      | 2018-10-19 11:39:22 |

GPU ID 4 is HD 7970 and ID 5 is 7850. 

Appreciate any help on this issue if it's not too big of a hassle, I can provide Teamviewer access as before if needed :)

**Comment by Boynk** [comment]
Im having the same issue on my Tahiti and Pitcairn cards. Tried under clocking, lowering intensity etc but no luck.

**Comment by xmronadaily** [comment]
So it seems it's not only limited to 14.4 drivers, @psychocrypt any recommendations on what to try?

**Comment by Spudz76** [comment]
I can probably fire up my old Tahiti rig and do some hackery.

I recall having tons of issues before I downshifted that rig to Ubuntu 14 with some very particular kernel revision, and the 15.x driver.  What kernel(s) are you trying?

**Comment by xmronadaily** [comment]
@Spudz76 How can I see the kernel revision? Is it the thing when I do winver? It's Version 1511 OS build 10586.494

**Comment by Spudz76** [comment]
Oh my bad I forgot people still Windows.  haha

**Comment by xmronadaily** [comment]
I've got a monitor hooked to HD 7970, so they were working all right with v7 so far, didn't try it any other way tho...

**Comment by xmronadaily** [comment]
This is fixed by moving to 17.4.4 drivers for HD 7970 and 7850, they produce all valid shares now and hashrate is 500 for first gpu and 390 for second.
