### ISSUE TITLE
Not full report, if too quick refresh

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#1976]
If i refresh not too often - all is normal, but if too quick, some fields are missing.
It is not critical, but feel like drop cards.

![capture](https://user-images.githubusercontent.com/12154217/47211722-e8dea900-d39e-11e8-9895-f0c76dfe7791.PNG)

**Comment by Spudz76** [comment]
Every time you ask for that page, it recalculates all history.  While it is recalculating it can not update the data buckets with any incoming info.

Basically asking to see it too often blocks the mining threads from adding their hashrate measurement to the buckets.

Don't refresh more often than 10s or so (60s is better) and it won't be a problem.

Also because you have so many threads in one xmr-stak the recalc-per-pageload is probably taking quite a while (some hundreds of milliseconds) another reason to not refresh too often.

You may also have too low intensity (if OpenCL) or blocksize (if CUDA) which makes the miner threads push telemetry bucket more often.

If there are *any* holes in the per-thread data, such as your 10s column, the sum-total will be blank (mainly because blank != 0 so the summing just gives no result instead of just counting the blanks as zero)  The 10s column uses the smallest recent bucket inputs and will show the worst holes when telemetry is overloaded, the holes disappear with larger data set (even though it still has some holes, they get averaged over).

Your 15m column is all that really matters.  And of course what the pool says.

**Comment by bizlevel** [comment]
Yes, i understand it. And I think about external monitoring, and now InfluxDB is the best for storage time-series data and visualise in grafana. And need to find curent all forks for external monitoring, and in future this simple page can be deprecated.

**Comment by psychocrypt** [comment]
You get na on the terminal and blanks in the web frontend if your gpu is to
slow and you need to long to solve one bunch of hashes.
It helps to reduce the threads/intensity.
Each time the miner needs more than 10sec to solve a bunch the result for
short statistics will be 0 (na)

**Comment by Spudz76** [comment]
That helps me understand the timing of why this happens, and yes seems about right (gpu returns every 15s, sometimes it will line up with 0/30/60 window of 10s)

**Comment by bizlevel** [comment]
I not understand, why "0" - just not clear current/previous cell/value, just rewrite with new only when got new value.

**Comment by Spudz76** [comment]
Because that's not how it was designed to work.  Devices on backends should return work more often than 10s.  It could be changed but not easily...
Rewrite and submit PR if you know some other more complicated and successful method of telemetry or round-robin-databasing.

**Comment by bizlevel** [comment]
How about regularity ? 
Only same 2 card (row 4-7) can be with "spaces" ! 

If i correct - it is - 580SE 8GB Micron MT51J256M32

```
"gpu_threads_conf" : [
//570 8GB Micron MT51J256M32
  { "index" : 0,     "intensity" : 960, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 0,     "intensity" : 960, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 11,    "intensity" : 960, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 11,    "intensity" : 960, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
//580SE 8GB Micron MT51J256M32
  { "index" : 5,    "intensity" : 1896, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 5,    "intensity" : 1896, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 6,    "intensity" : 1896, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 6,    "intensity" : 1896, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
//580 4GB Samsung K4G41325FE
  { "index" : 1,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 1,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 2,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 2,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 3,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 3,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 4,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 4,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 7,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 7,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 8,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 8,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 9,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 9,    "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 10,   "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
  { "index" : 10,   "intensity" : 992, "worksize" : 8,    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,    "unroll" : 8, "comp_mode" : false  },
```

Also i have one other PC low-end NVIDIA 1050TI under Windows10LTSB
With same behaviour.
![capture](https://user-images.githubusercontent.com/12154217/48135473-b93c0600-e2a5-11e8-8068-9d281e13f32d.PNG)

It is mean that with driver and OS - all is fine?
Only in xmr-stak need something to do, and i can't test anything more for help?

But i'm not understand why only 580SE can be blank (
It is depend from tune cards - speed up or speed down ?

**Comment by Spudz76** [comment]
Miner makes job of `intensity * worksize` nonces
If device can not finish that number of nonces in 10s *and* store/calc the telemetry data then it will show blanks.  If you chew too hard on the CPU, there will be more chances that it takes too long to store telemetry for the 10s column, even if the actual device is mining at 9s per check-in.

Regardless, 15m is the authoritative hashrate no matter what sparks and smoke happen in the rest of the app.  You are fine, it is a mirage.

**Comment by bizlevel** [comment]
In 2.10, and since 2.9 all is fine at last! )
