### ISSUE TITLE
RX Vega Hashrates are low

### ISSUE THREAD

**Issue by redscream** [fireice-uk/xmr-stak#1981]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).
no cpu

# Issue with the execution
  - Do you compiled the miner by our own?
  ```no
  run `./xmr-stak --version-long` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked? yes
  - Is the Main memory of the CPU or GPU undervolted? yes

RX vega 64 hash rates under 1900 
RX vega 56 hash rates under 1700

my config is:

"gpu_threads_conf" : [
  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 5, "strided_index" : 1, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : false
  },

  // gpu: gfx901 memory:3920
  // compute units: 64
  { "index" : 0,
    "intensity" : 1932, "worksize" : 8,
    "affine_to_cpu" : 3, "strided_index" : 1, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : false
  },
.....

Driver is blockchain driver for amd. aug'17

thanks..

**Comment by Wacholek** [comment]
What are the clock?

**Comment by jenik1** [comment]
Same for me. I am running with lower clocks to save power. Before upgrade on v7 I had 2K h/s per vega. I was running on 17.3 mining beta drivers. After upgrade v8 does not mine on old drivers anymore. Switched to 18.5.1. Now I can mine, but with much less speed. I am using the same PP_PhmSoftPowerPlayTable I was using with 17.3 driver.

**Comment by redscream** [comment]
GPU_P0=852;800
GPU_P1=991;900
GPU_P2=1084;950
GPU_P3=1138;1000
GPU_P4=1202;1050
GPU_P5=1250;1100
GPU_P6=1260;1150
GPU_P7=1408;920
Mem_P0=167;800
Mem_P1=500;800
Mem_P2=800;950
Mem_P3=1100;900
Fan_Min=4850
Fan_Max=4900
Fan_Target=75
Fan_Acoustic=15
Power_Temp=85
Power_Target=0

**Comment by TheGoddessInari** [comment]
Try worksize 16. That seems to fix it for most people. At least you aren't getting the 50% hashing problem though.

**Comment by redscream** [comment]
@TheGoddessInari awesome sir... It is fixed my rx vega 56 issue...
all my rigs are stable and temperatures as well.
thanks a lot for your tip... I appreciate it :+1: 


2018-10-20 03:28:51 ec4 Hash Rate : 9477
2018-10-20 03:28:51    GPU 4, Temp= 63,0, Fan Speed= 4652
2018-10-20 03:28:51    GPU 3, Temp= 61,0, Fan Speed= 4619
2018-10-20 03:28:51    GPU 2, Temp= 57,0, Fan Speed= 4686
2018-10-20 03:28:51    GPU 1, Temp= 59,0, Fan Speed= 4592
2018-10-20 03:28:51    GPU 0, Temp= 56,0, Fan Speed= 4668
2018-10-20 03:28:51 ec3 Hash Rate : 9081
2018-10-20 03:28:51    GPU 4, Temp= 55,0, Fan Speed= 4683
2018-10-20 03:28:51    GPU 3, Temp= 54,0, Fan Speed= 4649
2018-10-20 03:28:51    GPU 2, Temp= 57,0, Fan Speed= 4728
2018-10-20 03:28:51    GPU 1, Temp= 59,0, Fan Speed= 4664
2018-10-20 03:28:51    GPU 0, Temp= 59,0, Fan Speed= 4702
2018-10-20 03:28:52 ec2 Hash Rate : 7333
2018-10-20 03:28:52    GPU 3, Temp= 53,0, Fan Speed= 4582
2018-10-20 03:28:52    GPU 2, Temp= 61,0, Fan Speed= 4587
2018-10-20 03:28:52    GPU 1, Temp= 58,0, Fan Speed= 4543
2018-10-20 03:28:52    GPU 0, Temp= 55,0, Fan Speed= 4594
2018-10-20 03:28:52 ec1 Hash Rate : 9294
2018-10-20 03:28:52    GPU 4, Temp= 55,0, Fan Speed= 4625
2018-10-20 03:28:52    GPU 3, Temp= 57,0, Fan Speed= 4614
2018-10-20 03:28:52    GPU 2, Temp= 55,0, Fan Speed= 4657
2018-10-20 03:28:52    GPU 1, Temp= 60,0, Fan Speed= 4593
2018-10-20 03:28:52    GPU 0, Temp= 57,0, Fan Speed= 4633

**Comment by jenik1** [comment]
> 
> 
> @TheGoddessInari awesome sir... It is fixed my rx vega 56 issue...
> all my rigs are stable and temperatures as well.
> thanks a lot for your tip... I appreciate it 👍
> 
> 2018-10-20 03:28:51 ec4 Hash Rate : 9477
> 2018-10-20 03:28:51 GPU 4, Temp= 63,0, Fan Speed= 4652
> 2018-10-20 03:28:51 GPU 3, Temp= 61,0, Fan Speed= 4619
> 2018-10-20 03:28:51 GPU 2, Temp= 57,0, Fan Speed= 4686
> 2018-10-20 03:28:51 GPU 1, Temp= 59,0, Fan Speed= 4592
> 2018-10-20 03:28:51 GPU 0, Temp= 56,0, Fan Speed= 4668
> 2018-10-20 03:28:51 ec3 Hash Rate : 9081
> 2018-10-20 03:28:51 GPU 4, Temp= 55,0, Fan Speed= 4683
> 2018-10-20 03:28:51 GPU 3, Temp= 54,0, Fan Speed= 4649
> 2018-10-20 03:28:51 GPU 2, Temp= 57,0, Fan Speed= 4728
> 2018-10-20 03:28:51 GPU 1, Temp= 59,0, Fan Speed= 4664
> 2018-10-20 03:28:51 GPU 0, Temp= 59,0, Fan Speed= 4702
> 2018-10-20 03:28:52 ec2 Hash Rate : 7333
> 2018-10-20 03:28:52 GPU 3, Temp= 53,0, Fan Speed= 4582
> 2018-10-20 03:28:52 GPU 2, Temp= 61,0, Fan Speed= 4587
> 2018-10-20 03:28:52 GPU 1, Temp= 58,0, Fan Speed= 4543
> 2018-10-20 03:28:52 GPU 0, Temp= 55,0, Fan Speed= 4594
> 2018-10-20 03:28:52 ec1 Hash Rate : 9294
> 2018-10-20 03:28:52 GPU 4, Temp= 55,0, Fan Speed= 4625
> 2018-10-20 03:28:52 GPU 3, Temp= 57,0, Fan Speed= 4614
> 2018-10-20 03:28:52 GPU 2, Temp= 55,0, Fan Speed= 4657
> 2018-10-20 03:28:52 GPU 1, Temp= 60,0, Fan Speed= 4593
> 2018-10-20 03:28:52 GPU 0, Temp= 57,0, Fan Speed= 4633

Which driver do you use?

**Comment by redscream** [comment]
@jenik1 blockchain driver which was the first one for the mining of rx vegas' :)
08.08.17

**Comment by redscream** [comment]
@TheGoddessInari awesome sir... It is fixed my rx vega 56 issue...
all my rigs are stable and temperatures as well.
thanks a lot for your tip... I appreciate it +1

**Comment by jenik1** [comment]
Just an update - I have found the source of my problem. It was in the compatibility of the 18.6.1 driver and my SoftPowerPlayTable. Had to rebuild the table and it solved the problem. Hashing speed had dropped from 2K to 1900 on single vega64 - but with block size 16 everything works.
Thanks everybody for the help.
