### ISSUE TITLE
gpu WARNING: NVIDIA Insufficient driver!

### ISSUE THREAD

**Issue by Sirqwit** [fireice-uk/xmr-stak#1986]
# Basic information
  ryzen 7 1700x
  1060 6gb palit

gentoo

  run `cmake -LA .` in the build folder and add the output here

 -- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "7.5") 
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "1.2") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2p") 
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sam/miner/xmr-stak/build
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_ASM_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_ASM_FLAGS:STRING=
CMAKE_ASM_FLAGS_DEBUG:STRING=-g
CMAKE_ASM_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_ASM_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_ASM_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/sam/miner/xmr-stak/build
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;60;61;62;70;75
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart.so
CUDA_CUDA_LIBRARY:FILEPATH=/usr/lib/libcuda.so
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=/usr/local/cuda/bin/nvcc
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=/usr/local/cuda/include
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=10.0
CUDA_cublas_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcublas.so
CUDA_cublas_device_LIBRARY:FILEPATH=CUDA_cublas_device_LIBRARY-NOTFOUND
CUDA_cudadevrt_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudadevrt.a
CUDA_cudart_static_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart_static.a
CUDA_cufft_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcufft.so
CUDA_cupti_LIBRARY:FILEPATH=/usr/local/cuda/extras/CUPTI/lib64/libcupti.so
CUDA_curand_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcurand.so
CUDA_cusolver_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusolver.so
CUDA_cusparse_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusparse.so
CUDA_nppc_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnppc.so
CUDA_nppi_LIBRARY:FILEPATH=CUDA_nppi_LIBRARY-NOTFOUND
CUDA_npps_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnpps.so
CUDA_rt_LIBRARY:FILEPATH=/usr/lib/librt.so
EXECUTABLE_OUTPUT_PATH:STRING=bin
HWLOC:FILEPATH=/usr/lib/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
LIBRARY_OUTPUT_PATH:STRING=bin
MHTD:FILEPATH=/usr/lib/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib64/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib64/libssl.so
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/usr/include
OpenCL_LIBRARY:FILEPATH=/usr/lib/libOpenCL.so
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

nvidia-smi
Sat Oct 20 16:19:13 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:0A:00.0  On |                  N/A |
| 25%   30C    P8     8W / 120W |    214MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4858      G   /usr/bin/X                                    90MiB |
|    0      5141      G   ...uest-channel-token=12944327325913080358   121MiB |
+-----------------------------------------------------------------------------+

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

I had install nvidia-drivers with emerge and setup that, i tried to install nvidia-cuda-toolkit, the version is 9.2, and nvidia-cuda-sdk with emerge but it gave the same problem that i have now. Now i had install nvidia toolkit from website the version 10. At the end of compilation of nvidia toolkit from web site it give me 
===========
= Summary =
===========
Driver:   Not Selected 

I dont know if is right. After i have set up this on .bashrc of user: 

export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH

# this is the error when run ./xmr-stak

Password (mostly empty or x):

- Rig identifier for pool-side statistics (needs pool support). Can be empty:

- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
n
- Do you want to use nicehash on this pool? (y/n)
n
- Do you want to use multiple pools? (y/n)
n
Pool configuration stored in file 'pools.txt'
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
-------------------------------------------------------------------
xmr-stak 2.5.0 9012512

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2018-10-20 16:32:31] : Mining coin: monero
[2018-10-20 16:32:31] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory
[2018-10-20 16:32:31] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda9_2.so: cannot open shared object file: No such file or directory
[2018-10-20 16:32:31] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Insufficient driver!
[2018-10-20 16:32:31] : WARNING: backend NVIDIA disabled.
[2018-10-20 16:32:31] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-10-20 16:32:31] : WARNING: No OpenCL platform found.
[2018-10-20 16:32:31] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-10-20 16:32:31] : WARNING: backend AMD (OpenCL) disabled.
[2018-10-20 16:32:31] : CPU configuration stored in file 'cpu.txt'
[2018-10-20 16:32:31] : Starting 1x thread, affinity: 0.
[2018-10-20 16:32:31] : hwloc: can't bind memory
[2018-10-20 16:32:31] : Starting 1x thread, affinity: 2.
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'
[2018-10-20 16:32:31] : hwloc: can't bind memory
[2018-10-20 16:32:31] : Starting 1x thread, affinity: 4.
[2018-10-20 16:32:31] : MEMORY ALLOC FAILED: mmap failed, check attribute 'use_slow_memory' in 'config.txt'

I have built it with my user, the cpu work fine.
I really don't know what i have to do

thank you and sorry for my eng.

**Comment by Spudz76** [comment]
Upgrade to 4xx.xx nVidia Driver

3xx.xx have CUDA 9.2 (or earlier) in them thus you have compiled CUDA10 trying to run it on a CUDA9.2 driver so of course it's insufficient.

Runtime for CUDA comes with driver, the SDK is simply for compiling.

**Comment by Sirqwit** [comment]
I have uninstall cuda10 and install cuda 9.2 with emerge because if I update the nvidia-drivers from website  is a problem for the system.

Now I have this:

Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2018-10-21 13:31:56] : Mining coin: monero
[2018-10-21 13:31:56] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory
[2018-10-21 13:31:56] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda9_2.so: cannot open shared object file: No such file or directory
[2018-10-21 13:31:56] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Unable to query number of CUDA devices!
[2018-10-21 13:31:56] : WARNING: backend NVIDIA disabled.
[2018-10-21 13:31:56] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-10-21 13:31:56] : WARNING: No OpenCL platform found.
[2018-10-21 13:31:56] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-10-21 13:31:56] : WARNING: backend AMD (OpenCL) disabled.
[2018-10-21 13:31:56] : CPU configuration stored in file 'cpu.txt'

**Comment by Sirqwit** [comment]
#nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.8


#nvidia-smi
Sun Oct 21 14:05:57 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:0A:00.0  On |                  N/A |
| 25%   33C    P8     7W / 120W |    140MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4538      G   /usr/bin/X                                    90MiB |
|    0      4610      G   ...uest-channel-token=16507877582116369872    47MiB |
+-----------------------------------------------------------------------------+

**Comment by psychocrypt** [comment]
please empty the build folder and compile the miner again. Please post all
commands you used and all output from the compile (best post it on pastbin
and link it here)

**Comment by Sirqwit** [comment]
https://pastebin.com/rfeLDVA0

**Comment by psychocrypt** [comment]
if you campare your old dumo with the new you can see that you solved
somehow the invalid driver issue and now cuda was not able to find your
devices. I think that it hash something to do with the libraries used
during the compile and the execution. This time you have set ld library
path. I think the driver of your system is not updated to 9.2 and also you
have two cuda versions on your system.

**Comment by Spudz76** [comment]
The CUDA runtime comes in the driver
SDK version does not magically bring CUDA10 to an old driver version

4xx or you won't have CUDA 10 regardless how many times you installed the CUDA 10 SDK.

**Comment by Sirqwit** [comment]
I have uninstall cuda 10
Now I have install xmr-stak from emerge and the error is:
WARNING: NVIDIA Unable to query number of CUDA devices!
[2018-10-21 23:06:19] : WARNING: backend NVIDIA disabled.
[2018-10-21 23:06:19] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-10-21 23:06:19] : WARNING: No OpenCL platform found.
[2018-10-21 23:06:19] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-10-21 23:06:19] : WARNING: backend AMD (OpenCL) disabled.
[2018-10-21 23:06:19] : CPU configuration stored in file 'cpu.txt'


the version is Version: xmr-stak 2.4.7 c5f0505d

**Comment by psychocrypt** [comment]
2.4.7 IS NOT able to mine monero anymore. I think you should install cuda
from the webside (including the driver)

**Comment by xartin** [comment]
15+ year gentoo user here that frequently uses xmr-stak.  
  
nvidia-cuda-sdk is not a required dependency to compile xmr-stak on gentoo using gentoo portage. only nvidia-cuda-toolkit is required and xmr-stak works with amd and nvida currently.  

noted amd with RX 4xx/5xx cards is producing invalid results but generally works.

https://bpaste.net/show/850eb90e907e

If cuda or nvidia drivers were manually installed not using gentoo portage there's a good chance the system environment is borked.  
  
as of 24/10/2018 cuda 10 is not yet available in gentoo's package tree and m,anually compiling xmr-stak is entirely unnecessary.

**Comment by Sirqwit** [comment]
Ok

**Comment by Sirqwit** [comment]
Ok thanks you

**Comment by xartin** [comment]
> Ok thanks you

Your welcome. if you need any more help getting xmr-stak running on gentoo post on reddit.com/r/gentoo  i'll gladly help out if it's a benefit

**Comment by rogersil** [comment]
hi friends!I had this error:

[2018-10-26 20:53:52] : Mining coin: monero
[2018-10-26 20:53:52] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA Insufficient driver!
[2018-10-26 20:53:53] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda9_2.dll
WARNING: NVIDIA Insufficient driver!
[2018-10-26 20:53:53] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Insufficient driver!
[2018-10-26 20:53:54] : WARNING: backend NVIDIA disabled.
[2018-10-26 20:53:55] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-10-26 20:53:55] : WARNING: backend AMD (OpenCL) disabled.

I have a laptop core i 7 plus geforce gt 630 2gb.I m just studying about mining before do something big how to buy powerfull machines or specific hardware.I just wanna know if is possible to use this mine hardware gpu onboard to mining, cause the xmr stark works but with these issues i said.Thanks and sorry for take your time!

**Comment by psychocrypt** [comment]
which cuda driver do you installed? I assume cuda 8 but need at last 9
(better 9.2)

**Comment by rogersil** [comment]
hello, i installed cuda 9.before install, the nvidia.txt was not created.Now, after install, it happends.and i have these messages:
2018-10-27 10:15:08] : Starting NVIDIA GPU thread 0, no affinity.
[2018-10-27 10:15:08] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-10-27 10:15:08] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-10-27 10:15:08] : WARNING: backend AMD (OpenCL) disabled.

**Comment by Spudz76** [comment]
You should run with `--noAMD` so it doesn't try to probe OpenCL

Other than that it seems the nvidia backend should be working as it made it to the starting NVIDIA thread message...

**Comment by rogersil** [comment]
but where exactly i must insert this code?

**Comment by Spudz76** [comment]
Also pending accept, new docs section [here](https://github.com/Spudz76/xmr-stak/blob/dev-cudaDocs/doc/compile.md#cuda-runtime-versus-cuda-sdk) summarizing the above

**Comment by kbuggenhout** [comment]
for the nvidia part, you did  install the cuda toolkit I hope,
linked /usr/local/cuda-[version] to /usr/local/cuda
then set the LD_LIBRARY_PATH or added /usr/local/cuda/lib64 to the library search path ( man ldconfig)
and set CUDA_HOME to /usr/local/cuda

and indeed if you dont have an AMD card, run with --noAMD

:)

**Comment by kbuggenhout** [comment]
oh and the gt630 hashrate is not worth the electricity you put in sorry mate... its peanuts.
