### ISSUE TITLE
Window spammed with Error CL_MEM_OBJECT_ALLOCATION_FAILURE 

### ISSUE THREAD

**Issue by twotwatsabroad** [fireice-uk/xmr-stak#199]
Windows 10.

6 x AMD RX 580 GPUS

Running spams the following message over and over at a rapid rate:
[2017-11-21 21:40:51] : Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for kernel 0.

It is mining and getting results, but this is obviously something wrong, any ideas?

**Comment by psychocrypt** [comment]
please post the file amd.txt. Do you changed any co figs within the file
amd.txt?

**Comment by twotwatsabroad** [comment]
It seems that this was related to my operating system, after updates this is no longer happening. I believe this issue is closed, thanks.
