### ISSUE TITLE
unsupported GNU version! gcc versions later than 5 are not supported!

### ISSUE THREAD

**Issue by trite2k3** [fireice-uk/xmr-stak#1990]
Slackware how to, this is not an issue, only what the fewk to do after you get this (if you made it this far):
```

[ 73%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
In file included from /usr/share/cuda/include/cuda_runtime.h:78,
                 from <command-line>:
/usr/share/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
  /build/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:72: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@bifrost:/build/xmr-stak# cmake -DCMAKE_LINK_STATIC=ON -DMICROHTTPD_ENABLE=OFF -DXMR-STAK_COMPILE=generic -DCMAKE_INSTALL_PREFIX:PATH=/opt/xmr-stak . 
-- Configuring done
-- Generating done
-- Build files have been written to: /build/xmr-stak
```

Ok, so cuda 8 is old and greasy and since we cannot install a newer one (at least not easy?) we should install gcc 5.3.0 from slack 14.2 and also gcc-g++5.3.0. This will mess with your symlinks so just in case, install gcc and g++ latest again after you've installed 5.3.0.

export this variable, I have no idea but just in case
export HOST_COMPILER=/usr/bin/g++-gcc-5.3.0

If you try to compile now youll get some bull about __float128 not defined
go edit /usr/include/bits/floatn.h (AT YOUR OWN RISK :D)
 **&&  !defined(__CUDACC__)**:
```
--- a/usr/include/bits/floatn.h	2017-09-13 16:00:37.079654880 +0200
+++ b/usr/include/bits/floatn.h	2017-09-13 16:00:00.999104815 +0200
@@ -28,7 +28,8 @@
    support, for x86_64 and x86.  */
 #if (defined __x86_64__							\
      ? __GNUC_PREREQ (4, 3)						\
-     : (defined __GNU__ ? __GNUC_PREREQ (4, 5) : __GNUC_PREREQ (4, 4)))
+     : (defined __GNU__ ? __GNUC_PREREQ (4, 5) : __GNUC_PREREQ (4, 4))) \
+  &&  !defined(__CUDACC__)
 # define __HAVE_FLOAT128 1
 #else
 # define __HAVE_FLOAT128 0
```

cmake build with this ultra long line, notice the gcc 5.3.0 pointers:
cmake -DCMAKE_LINK_STATIC=ON -DMICROHTTPD_ENABLE=OFF -DXMR-STAK_COMPILE=generic -DCUDA_HOST_COMPILER=/usr/bin/gcc-5.3.0 -DCMAKE_INSTALL_PREFIX:PATH=/opt/xmr-stak -DCMAKE_C_COMPILER=/usr/bin/gcc-5.3.0 -DCMAKE_CXX_COMPILER=/usr/bin/g++-gcc-5.3.0 .

make install

[100%] Built target xmr-stak

[2018-10-21 21:54:15] : Result accepted by the pool.

woopie \o/

**Comment by trite2k3** [comment]
please close this

**Comment by JayWalker512** [comment]
Thanks for posting this. I had a similar issue in Ubuntu 18.04 with CUDA 9 where the build was complaining that gcc versions later than 6 were not supported. Ran modified cmake command: 
```
cmake -DCMAKE_LINK_STATIC=ON -DMICROHTTPD_ENABLE=OFF -DXMR-STAK_COMPILE=generic -DCUDA_HOST_COMPILER=/usr/bin/gcc-6 -DCMAKE_INSTALL_PREFIX:PATH=/opt/xmr-stak -DCMAKE_C_COMPILER=/usr/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/bin/g++-6
```
And then make was able to complete the compilation successfully.

**Comment by Zenitur** [comment]
@trite2k3 @JayWalker512 you need to modify `/usr/local/cuda/include/host_config.h`, not the system file! Find this:

```
#if defined(__GNUC__)

#if __GNUC__ > 6

#error -- unsupported GNU version! gcc versions later than 6 are not supported!

#endif /* __GNUC__ > 6 */
```
When set any GCC version.
