### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by sartoricobra** [fireice-uk/xmr-stak#1996]
im getting this error, since i change my gpu... already tried removing nvidia drivers, installing new one, older one, clean install...

below im giving more information about my system.

# Basic information
  - Type of the CPU.: Ryzen 1800x
  - Type of the GPU (if you try to miner with the GPU).: GTX 970
  - Which OS do you use?: Windows 10 64bits
  - Do you compiled the miner by our own?: using the generic release

  ```
 Version: xmr-stak/2.5.1/4e72408ff/master/win/nvidia-amd-cpu/20
  ```

  - Is the CPU or GPU overclocked?: NO
  - Is the Main memory of the CPU or GPU undervolted?: NO

**Comment by sartoricobra** [comment]
forgot to paste the error: 
![sem titulo](https://user-images.githubusercontent.com/23238134/47311864-da93c580-d608-11e8-8210-44371d72806e.png)

**Comment by psychocrypt** [comment]
reduce the threads in nvidia.txt

**Comment by Spudz76** [comment]
The paths are to the source file, from the build environment where Releases come from (Appveyor), whereas `/xmr-stak-2.5.1/` is the git root folder.

**Comment by sartoricobra** [comment]
Sorry guys for returning late. Psychocrypt was right... Dunno why, using the same config on different processors made that... Looks like it got out of resource.

As he said, lowering thread solve it.

**Comment by psychocrypt** [comment]
solved by reducing the number of threads
