### ISSUE TITLE
How to use integrated address with xmr-stak

### ISSUE THREAD

**Issue by ksze** [fireice-uk/xmr-stak#1998]
I got xmr-stak compiled and running. However, I don't understand how to use xmr-stak with a monero integrated address.

I want to mine and deposit directly to an exchange wallet, specifically on Poloniex. Apparently, Poloniex supports monero's integrated address scheme (https://twitter.com/Poloniex/status/872008789586845696), which is a form of combining the usual standard public address and the payment ID into one string. However, the payment ID portion of such an integrated address is only 64-bit long instead of the 256-bit.

Does xmr-stak support such integrated addresses? Do I have to decode the integrated address into its separate public address and payment ID components? Does it depend on the pool? I'm mining with nanopool.

**Comment by plavirudar** [comment]
Yes, it depends on the pool. You should ask this question to the pool operator, xmr-stak doesn't control pool payments.

**Comment by ksze** [comment]
@Spudz76 nanopool happens to officially support mining to exchange. They even have instructions with using an exchange address, just not in the "integrated" format. Their support contact has already replied to my question: just use the integrated address without supplying a separate payment ID.
