### ISSUE TITLE
check nicehash pool support

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#2]
During the refactoring I have remove the nicehash pool support, I added it back with https://github.com/fireice-uk/xmr-stak/commit/1f40f88a0c031db1bb04fa39a51117263eb27155.

I have not tested if it runs without issues, therefore a runtime test is needed.

- [ ] do test against the nicehash pool.

**Comment by anhphan** [comment]
Nicehash is totally broken, I try with both cpu backend and amd backend, both receiver 100% reject with error on the web page:

`Invalid nonce; is miner not compatible with NiceHash?`

**Comment by psychocoderHPC** [comment]
Could you provide me with your config.txt thus I can try to mine against your nicehash account to fix the issue.

**Comment by psychocrypt** [comment]
Could you provide me with a config.txt which I can use for testing. I will spend my hash power to your account to fix it.

**Comment by anhphan** [comment]
The config file is attached.

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1356859/config.txt)

**Comment by psychocrypt** [comment]
@anhphan Thx for providing me with a account, the nice hash support is fixed in #14

**Comment by anhphan** [comment]
It's fixed somewhere but it's not completely fix.
Will try more with each backend (cpu, amd). This is my result when running both amd and cpu (5.5kh amd + 0.9kh cpu)

![image](https://user-images.githubusercontent.com/1614690/31198367-3b0afc8e-a97e-11e7-9f8c-aa03ba9f82c5.png)

**Comment by anhphan** [comment]
Seem good (with shift 8 bit as @fireice-uk indicated in review code).
45 min mining on nicehash (nh will push us very high diff if we have high speed, then maybe problem out of nonce will not happen):
![image](https://user-images.githubusercontent.com/1614690/31201525-2f2f72c2-a989-11e7-9980-1edffb76a35c.png)

**Comment by fireice-uk** [comment]
@anhphan thanks for testing this one! Closing as the fix was merged in #14
