### ISSUE TITLE
Rethink nonce allocation

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak#20]
We have a large mix of workers now with capabilities ranging in two orders of magnitude from 10H/s to 1000H/s 

If we are going to support nicehash then we are working in a very restricted space - we have 16.7 million nonces to split.

Moreover if we stop, and then resume at a pool without dropping connection we need to include that in the nonce budget, otherwise we will get collisions.

The maths just doesn't add up,  8 workers at 2500H/s and 1 resume is 3.6 million hashes. There is no way to that we can fit 64 cpu workers without making the nonce calculation differentiate between cpu and gpu workers

**Comment by psychocrypt** [comment]
I changed the original implementation a little bit which will be more effective than before. Never the less you are right.
The main issue is coming from the way how nicehash is cutting the 32bit index domain. 

suggestions:
 - show a WARNING message as soon as the start_nonce have possible collisions
 - add something like groups (backends) which get larger index ranges, the index domain can be re-ranged after ~2 minutes with the next new block.

IMO we can solve this issue after the release, this is only an issue with nicehash.

**Comment by fireice-uk** [comment]
Implemented in #45
