### ISSUE TITLE
Auto configuration not assigning the correct physical CPU cores on Windows 10, why not a benchmark option to test different configs and find the fastest?

### ISSUE THREAD

**Issue by mojimi** [fireice-uk/xmr-stak#200]
Hello, I tested this using an Intel i5 4200

4 threads, 2 cores

The auto config set 2 threads to core 0 and 2.

But after some benchmarking I found out that the actual physical cores are ID 0 and 1, which net a great increase in hashrate.

**Comment by psychocrypt** [comment]
Do you compiled the miner by your own? Can you run someyhing like hwloc
https://www.open-mpi.org/software/hwloc/v1.11/ and post the output.

**Comment by mojimi** [comment]
@psychocrypt Which one? the Istopo GUI?

And no I did not compile on my own
