### ISSUE TITLE
What algorithm should I use to mine monero?

### ISSUE THREAD

**Issue by Unlash** [fireice-uk/xmr-stak#2002]
![snipaste_2018-10-24_10-59-27](https://user-images.githubusercontent.com/32661990/47403421-1a2eee80-d77c-11e8-83ea-32b53f901987.png)

monero
cryptonight v7 
cryptonight v8

I should use that.

**Comment by Spudz76** [comment]
I'd use graft, obviously.

**Comment by psychocrypt** [comment]
He missed the irony tags. Please use monero to mine monero.

**Comment by Unlash** [comment]
> 
> He missed the irony tags. Please use monero to mine monero.
May I ask the next cryptonight v7 What kind of coin does cryptonight V8 dig?
