### ISSUE TITLE
Improve device initialization startup time

### ISSUE THREAD

**Issue by Grimm2017** [fireice-uk/xmr-stak#201]
It takes 12 seconds per card to initialize on my rig.  In a 12 card rig that adds up, especially if you're running an auto restart script to restart the miner when Vega hash rates drops.  By contrast Cast XMR starts mining almost immediately upon launch.  Not a huge problem but every little bit of performance helps.

**Comment by psychocrypt** [comment]
please post the output of the miner until all gpus are running.
Which cpu is i build in you rig.

**Comment by psychocrypt** [comment]
Please post
- the hardware used in the rig. GPUs, RAM, CPU, ...
- you config `amd.txt` (if you changed the config please also post the auto suggested config)
Normally the startup time should be small.

**Comment by randelsr** [comment]
@Grimm2017 Are you running 12 Vegas on Windows or Linux? Just curious as I can't get more than 8 Vegas running on Windows with correct hashrates (2k).

**Comment by krypknot** [comment]
Same issue when it comes to using any AMD card.  Have noticed this initialization time growing over the past few versions - now it almost requires a keystroke to 'kick' it on to the next index.
Version: xmr-stak 2.2.0 29bac549
RX480 and RX580
  { "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
  { "index" : 1, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },

It works very well once initialized

**Comment by psychocrypt** [comment]
The reason for the "long" compile time is that the miner is explicitly
compiled for your device. If all devices are equal than it is only compiled
once.
The time to compile the opencl part should be small compared to the miner
runtime.

**Comment by eliashdezr** [comment]
I have the exact 8 GPUs on each of my rigs and they took long to compile.
