### ISSUE TITLE
macOS Mojave NVIDIA hangs at "try to load library"

### ISSUE THREAD

**Issue by ABIPUP** [fireice-uk/xmr-stak#2014]
I updated to macOS Mojave, and the build config that I was running prior to the upgrade started to hang at:
NVIDIA: try to load library 'xmrstak_cuda_backend'

I've tried to make a new xmr-stak install, and reinstalling cuda drivers, no success.  2.5.1 install also hangs at loading cuda library.

# Basic information
  - Core i5 Macbook Air
  - Stock GTX 1070
  - macOS Mojave

# Compiling
  - Fresh make and install of xmr-stak 2.5.0:
brew tap caskroom/drivers
brew cask **re**install nvidia-cuda
brew **re**install hwloc libmicrohttpd gcc openssl cmake
cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOpenCL_ENABLE=OFF
make install

Version: xmr-stak/2.5.0/9012512/master/mac/nvidia-cpu/0

  - cmake -LA command returns:
CMAKE_AR:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/ar
CMAKE_ASM_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/cc
CMAKE_ASM_COMPILER_AR:FILEPATH=CMAKE_ASM_COMPILER_AR-NOTFOUND
CMAKE_ASM_COMPILER_RANLIB:FILEPATH=CMAKE_ASM_COMPILER_RANLIB-NOTFOUND
CMAKE_ASM_FLAGS:STRING=
CMAKE_ASM_FLAGS_DEBUG:STRING=-g
CMAKE_ASM_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_ASM_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_ASM_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_NAME_TOOL:FILEPATH=/usr/bin/install_name_tool
CMAKE_INSTALL_PREFIX:PATH=/Users/danyal/xmr-stak
CMAKE_LINKER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_OSX_ARCHITECTURES:STRING=
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
CMAKE_OSX_SYSROOT:STRING=
CMAKE_RANLIB:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;60;61;62
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcudart.dylib
CUDA_CUDA_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcuda.dylib
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/clang
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=/usr/local/cuda/bin/nvcc
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=/usr/local/cuda/include
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=9.2
CUDA_cublas_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcublas.dylib
CUDA_cudadevrt_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcudadevrt.a
CUDA_cudart_static_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcudart_static.a
CUDA_cufft_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcufft.dylib
CUDA_cupti_LIBRARY:FILEPATH=/usr/local/cuda/extras/CUPTI/lib/libcupti.dylib
CUDA_curand_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcurand.dylib
CUDA_cusolver_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcusolver.dylib
CUDA_cusparse_LIBRARY:FILEPATH=/usr/local/cuda/lib/libcusparse.dylib
CUDA_nppc_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppc.dylib
CUDA_nppial_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppial.dylib
CUDA_nppicc_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppicc.dylib
CUDA_nppicom_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppicom.dylib
CUDA_nppidei_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppidei.dylib
CUDA_nppif_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppif.dylib
CUDA_nppig_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppig.dylib
CUDA_nppim_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppim.dylib
CUDA_nppist_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppist.dylib
CUDA_nppisu_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppisu.dylib
CUDA_nppitc_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnppitc.dylib
CUDA_npps_LIBRARY:FILEPATH=/usr/local/cuda/lib/libnpps.dylib
EXECUTABLE_OUTPUT_PATH:STRING=bin
HWLOC:FILEPATH=/usr/local/lib/libhwloc.dylib
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/local/include
LIBRARY_OUTPUT_PATH:STRING=bin
MHTD:FILEPATH=/usr/local/lib/libmicrohttpd.dylib
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/local/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/local/opt/openssl/lib/libcrypto.dylib
OPENSSL_INCLUDE_DIR:PATH=/usr/local/opt/openssl/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/local/opt/openssl/lib/libssl.dylib
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/System/Library/Frameworks/OpenCL.framework
OpenCL_LIBRARY:FILEPATH=/System/Library/Frameworks/OpenCL.framework
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=PKG_CONFIG_EXECUTABLE-NOTFOUND
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

Thanks for your hard work on xmr-stak as always.

**Comment by psychocrypt** [comment]
wait longer. if you not set by hand a architecture the miner will create
binaries for all gpu types. depending on your cpu this can take 30 minutes.

**Comment by Spudz76** [comment]
[Look before you leap](https://devtalk.nvidia.com/default/topic/1042279/cuda-10-and-macos-10-14/?offset=1)...

Unsupported, revert or await repairs.

**Comment by ABIPUP** [comment]
Thanks for pointing me in the right direction.  I consider myself to be a cautious updater, considering the legacy status of my laptop.  But I never thought to check to see if CUDA itself would be an issue.

Since it's a global issue for all Mojave users, I'll wait for Apple and NVIDIA to work out their differences, and close this topic in the meantime.

**Comment by Spudz76** [comment]
Look out for OpenCL disappearing in the near future too.

Apple wants everyone to switch to their Metal whatever thing (Vulkan competitor? idk why they compete instead of support standards...)  OpenCL will be removed in 10.15

Guess what I'm saying is they may have intentionally left it broken with no plans to fix, you'd be better off reverting.
