### ISSUE TITLE
Some questions about Build

### ISSUE THREAD

**Issue by rocke** [fireice-uk/xmr-stak#2036]
I use Ubuntu 16.04.1

I statically compiled the -dxmr-stak_compile =generic and -dcmake_link_static =ON parameters

What should I do to address the lack of libuv.a when Centos runs

**Comment by psychocrypt** [comment]
Static build is only linking g++ dependencies hard into the binary. To have
a full static build you must compile dependencies by hand. This is not easy.

**Comment by rocke** [comment]
Is there any way to package libuv.a into the xmrig binary?

So no matter what kind of operating system it runs, it only calls the packaged libuv.a.

**Comment by psychocrypt** [comment]
xmrig is an other miner you should ask in there issue tracker for a
solution.

**Comment by psychocrypt** [comment]
> Is there any way to package libuv.a into the xmrig binary?

I am confused by this question. xmr-stak is not using libuv.a

**Comment by Spudz76** [comment]
Many `-devel` packages do not have static libraries only the shared, if you want true serious full static, you must compile all dependencies with static enabled.
xmr-stak dependencies are:
hwloc (for navigating memory/cache layouts, somewhat optional but the non-hwloc code is lesser tested)
openssl (for pool TLS, optional)
microhttpd (for the API and Web Interface, optional)

...and any of their sub-deps, however microhttpd does not need any SSL options (no SSL API /web interface support) and distro development packs usually have gnutls turned on which gets in the way somewhat with openssl in the other part

we and none of our deps or their sub deps use libuv whatsoever.

**Comment by rocke** [comment]
It's too complicated. I'll think about it.
I have a compiled xmr-stak that runs on any platform. Can you help me analyze how it works?

@psychocrypt

**Comment by lotus1313** [comment]
> 
> Static build is only linking g++ dependencies hard into the binary. To have a full static build you must compile dependencies by hand. This is not easy.

But for [XMRig](https://github.com/lotus1313/xmrig)

**Comment by Spudz76** [comment]
"But without http server and SSL/TLS"
this makes static xmr-stak also simple to do
remove all the deps, mission complete

**Comment by rocke** [comment]
@Spudz76 

According to what you said, how should I fill in cmake I used the following:

Cmake .. -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DMICROHTTPD_ENABLE=OFF -DOpenSSL_ENABLE=OFF
-DHWLOC_ENABLE=OFF

**Comment by rocke** [comment]
@Spudz76 Have a video of the compilation process let me learn
