### ISSUE TITLE
Inconsistent CPU and GPU Hashrate when compiling with Cuda 10 and vs 17 15.8.7

### ISSUE THREAD

**Issue by Theflyer737** [fireice-uk/xmr-stak#2040]
Please provide as much as possible information to reproduce the issue.

# Basic information
Threadripper 1850x
Nvidia 1060 6gb + 1070ti 8Gb

# Compile issues
  - Which OS do you use? Windows 10 pro

  add **all** commands you used:
As refered on github site https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.11
mkdir build
cd build
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake --build . --config Release --target install
cd bin\Release
copy C:\xmr-stak-dep\openssl\bin\* .

Compilation:
  run `cmake -LA .` in the build folder and add the output here
  CMake Error: The source directory "C:/Users/Calypso/xmr-stak-2.5.2/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_ASM_MASM_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/ml64.exe
CMAKE_ASM_MASM_FLAGS:STRING=
CMAKE_ASM_MASM_FLAGS_DEBUG:STRING=
CMAKE_ASM_MASM_FLAGS_MINSIZEREL:STRING=
CMAKE_ASM_MASM_FLAGS_RELEASE:STRING=
CMAKE_ASM_MASM_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_INSTALL_PREFIX:PATH=C:/Users/Calypso/xmr-stak-2.5.2/build
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/link.exe
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_RC_COMPILER:FILEPATH=C:/Program Files (x86)/Windows Kits/10/bin/10.0.17134.0/x64/rc.exe
CMAKE_RC_FLAGS:STRING=/DWIN32
CMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG
CMAKE_RC_FLAGS_MINSIZEREL:STRING=
CMAKE_RC_FLAGS_RELEASE:STRING=
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;60;61;62;70;75
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart.lib
CUDA_CUDA_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cuda.lib
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin/nvcc.exe
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
CUDA_TOOLKIT_ROOT_DIR:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=10.0
CUDA_cublas_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cublas.lib
CUDA_cublas_device_LIBRARY:FILEPATH=CUDA_cublas_device_LIBRARY-NOTFOUND
CUDA_cudadevrt_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudadevrt.lib
CUDA_cudart_static_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart_static.lib
CUDA_cufft_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cufft.lib
CUDA_cupti_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/extras/CUPTI/libx64/cupti.lib
CUDA_curand_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/curand.lib
CUDA_cusolver_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cusolver.lib
CUDA_cusparse_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cusparse.lib
CUDA_nppc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppc.lib
CUDA_nppial_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppial.lib
CUDA_nppicc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppicc.lib
CUDA_nppicom_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppicom.lib
CUDA_nppidei_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppidei.lib
CUDA_nppif_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppif.lib
CUDA_nppig_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppig.lib
CUDA_nppim_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppim.lib
CUDA_nppist_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppist.lib
CUDA_nppisu_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppisu.lib
CUDA_nppitc_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/nppitc.lib
CUDA_npps_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/npps.lib
CUDA_nvcuvenc_LIBRARY:FILEPATH=CUDA_nvcuvenc_LIBRARY-NOTFOUND
CUDA_nvcuvid_LIBRARY:FILEPATH=CUDA_nvcuvid_LIBRARY-NOTFOUND
EXECUTABLE_OUTPUT_PATH:STRING=bin
HWLOC:FILEPATH=C:/xmr-stak-dep/hwloc/lib/libhwloc.lib
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=C:/xmr-stak-dep/hwloc/include
LIBRARY_OUTPUT_PATH:STRING=bin
LIB_EAY_DEBUG:FILEPATH=LIB_EAY_DEBUG-NOTFOUND
LIB_EAY_LIBRARY_DEBUG:FILEPATH=LIB_EAY_LIBRARY_DEBUG-NOTFOUND
LIB_EAY_RELEASE:FILEPATH=C:/xmr-stak-dep/openssl/lib/libeay32.lib
MHTD:FILEPATH=C:/xmr-stak-dep/libmicrohttpd/lib/libmicrohttpd.lib
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=C:/xmr-stak-dep/libmicrohttpd/include
OPENSSL_INCLUDE_DIR:PATH=C:/xmr-stak-dep/openssl/include
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
OpenCL_LIBRARY:FILEPATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/OpenCL.lib
OpenSSL_ENABLE:BOOL=ON
SSL_EAY_DEBUG:FILEPATH=SSL_EAY_DEBUG-NOTFOUND
SSL_EAY_LIBRARY_DEBUG:FILEPATH=SSL_EAY_LIBRARY_DEBUG-NOTFOUND
SSL_EAY_RELEASE:FILEPATH=C:/xmr-stak-dep/openssl/lib/ssleay32.lib
XMR-STAK_COMPILE:STRING=native
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

# Issue with the execution
  - Do you compiled the miner by our own? YES via command line cited above
  Results when launching xmr-stak:
Inconsistent hashrate for CPU and no hashrate for GPU. No blocks treated.
 
-------------------------------------------------------------------
xmr-stak 2.5.2 752fd1e7e

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 0.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2018-11-04 22:22:36] : Mining coin: monero
[2018-11-04 22:22:36] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda10_0.dll
[2018-11-04 22:22:36] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda9_2.dll
[2018-11-04 22:22:36] : NVIDIA: try to load library 'xmrstak_cuda_backend'
NVIDIA: found 2 potential device's
[2018-11-04 22:22:37] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [10.0/10.0] GPU#0, device architecture 61: "GeForce GTX 1070 Ti"... device init succeeded
[2018-11-04 22:22:37] : Starting NVIDIA GPU thread 1, no affinity.
CUDA [10.0/10.0] GPU#1, device architecture 61: "GeForce GTX 1060 6GB"... device init succeeded
[2018-11-04 22:22:37] : NVIDIA: use library 'xmrstak_cuda_backend'
[2018-11-04 22:22:38] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-11-04 22:22:38] : WARNING: backend AMD (OpenCL) disabled.
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 0.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 2.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 4.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 6.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 8.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 10.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 12.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 14.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 16.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 18.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 20.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 22.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 24.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 26.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 28.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Starting 1x thread, affinity: 30.
[2018-11-04 22:22:38] : hwloc: memory pinned
[2018-11-04 22:22:38] : Fast-connecting to stratum+tcp://xmr-eu2.nanopool.org:14444 pool ...

[2018-11-04 22:22:38] : stratum+tcp://xmr-eu2.nanopool.org:14444 connected. Logging in...

[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Difficulty changed. Now: 120001.
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Pool logged in.
[2018-11-04 22:22:38] : New block detected (1)

[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
[2018-11-04 22:22:38] : Switch to assembler version for 'amd_avx' cpu's
print_report
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 39837.2 |   (na) |   (na) |  1 | 41454.8 |   (na) |   (na) |
|  2 | 43373.1 |   (na) |   (na) |  3 | 43555.5 |   (na) |   (na) |
|  4 | 38936.6 |   (na) |   (na) |  5 | 41740.8 |   (na) |   (na) |
|  6 | 40753.7 |   (na) |   (na) |  7 | 40620.2 |   (na) |   (na) |
|  8 | 43772.7 |   (na) |   (na) |  9 | 44887.6 |   (na) |   (na) |
| 10 | 43153.5 |   (na) |   (na) | 11 | 36817.4 |   (na) |   (na) |
| 12 | 48294.3 |   (na) |   (na) | 13 | 50733.4 |   (na) |   (na) |
| 14 | 50470.2 |   (na) |   (na) | 15 | 50634.8 |   (na) |   (na) |
Totals (CPU):  699035.9    0.0    0.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   (na) |   (na) |   (na) |  1 |   (na) |   (na) |   (na) |
Totals (NVIDIA):     0.0    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   699035.9    0.0    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------

# Stability issue
  - Is the CPU or GPU overclocked? lightly: 3800
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by Spudz76** [comment]
I have not necessarily tried holding CUDA 10 back to 14.11.25503 compilers

Let it use the default 14.15 or whatever is current.  Downgrade only when CUDA complains about the compiler being too new.  Docs were written about CUDA 9.0 which did require 14.11 and then never updated.

**Comment by Theflyer737** [comment]
Ok, thanks for your answer. Meanwhile, I downgraded from VS 17 15.8.7 to VS 17 15.8.1 with CUDA 10 and it works now.
