### ISSUE TITLE
JSON API without MicroHTTPD?

### ISSUE THREAD

**Issue by OhGodADog** [fireice-uk/xmr-stak#2042]
I am trying to find information, but the docs do not hold much>

I got the basic JSON format from IP:PORT/api.json and it looks good.

I need to know, if i compile XMR-Stak without MicroHTTPD support, will the JSON API still work? 
Or if its compiled with MicroHTTPD, but no port is set (thus HTTPD is disabled), will the JSON API still work (being accessible to retrieve remotely data).

Also, does the JSON API support any command inputs?

**Comment by psychocrypt** [comment]
No json api requires that you compile with microhttpd

**Comment by Spudz76** [comment]
As it is JSON over HTTP, of course you still need the httpd.  It is simply a different web page.

There is also no support for HTTPS with the httpd, only for pool connections (outward).

**Comment by OhGodADog** [comment]
Thanks, this answered my question.
