### ISSUE TITLE
Quadro 4000 compatibility with version 2.5.2

### ISSUE THREAD

**Issue by warz0mbie** [fireice-uk/xmr-stak#2059]
I am no longer able to mine using NVidia Quadro 4000 GPU's after the update to version 2.5.2 for cryptonight V8.

In version 2.4.2 I could mine using GPU and CPU without any problems.

Now I'm getting the following errors:

[2018-11-12 17:28:26] : Mining coin: cryptonight_v8
[2018-11-12 17:28:26] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2018-11-12 17:28:26] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda9_2.dll
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2018-11-12 17:28:26] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2018-11-12 17:28:26] : WARNING: backend NVIDIA disabled.

I did not compile it myself, nor do I have the knowledge for it.
The GPU drivers installed are in the latest version.

I'm hoping someone can enlighten me about possible issues.

**Comment by Moreno-Borsalino** [comment]
>           I am no longer able to mine using NVidia Quadro 4000 GPU's after the update to version 2.5.2 for cryptonight V8.

Hi warz0mbie, we are on the same boat; i have the same problem and I didn't find any solution with xmr-stai. I can't mine with Quadro 4000 too. It is really a pity because I got good hash rate in the past although the card is very old. In any case now I am using [xmrig-nvidia](https://github.com/xmrig/xmrig-nvidia) to mine with Quadro 4000. With some tuning I can get again about 90 - 95 H/s.

**Comment by warz0mbie** [comment]
Hi Moreno,

Thanks for your reply.
I tried using xmrig-nvidia, but only made it work when settling the number of threads to 1, which gave me a really poor hash rate (about 35 H/s).

Could you please share your configuration and what you did to improve it?

Cheers

**Comment by warz0mbie** [comment]
This actually improve my hash rate, I'm getting about 90 H/s now.
Not what I expected but surely better than before.

Thanks a lot!

I'll keep trying some other configs and miners. If I find anything better I'll share!

Cheers m8

**Comment by psychocrypt** [comment]
I do not know if you are using windows or linux. But if you use my
precompiled windows binaries you must update your nvidia driver to 9.X or 10

**Comment by warz0mbie** [comment]
Hi psychocrypt,

Thanks for your reply.

I'm using Windows 8.1 Pro.

The drivers are updated and use CUDA 9.

Like our friend Moreno also stated above, it was working fine in the previous version (2.4.2).

I'll much appreciate any help you can give us.

Cheers

**Comment by psychocrypt** [comment]
Than please update to cuda 9.2. If you ise my precompiled binary I upgraded
my environment and therefore cuda 9.0 is required if you not compile it by
your own. If your cuda 9 is older than the version I used than it make
trubble.

**Comment by Spudz76** [comment]
Quadro 4000 is a Fermi

You MUST use CUDA 8.0 and that is the only version that will work.  You must compile yourself, release is no longer based on CUDA 8.0 SDK.  See the [new section in the Compile docs](https://github.com/fireice-uk/xmr-stak/blob/dev/doc/compile.md#cuda-runtime-versus-cuda-sdk)

**Comment by Moreno-Borsalino** [comment]
That's the point. I suspect that many miners have again old cards based on CUDA 8. Would be nice if a xmr-stak CUDA 8 version is also make available to download.

**Comment by Spudz76** [comment]
Would be nice if nVidia didn't abandon their hardware in the drivers/CUDA over time.

**Comment by Moreno-Borsalino** [comment]
Yes, it is true, that would be the best solution but Nvidia follows market policies that lead to the rapid obsolescence of products. Fortunately, with the strength of this community you can overcome the lack of driver updates with greater flexibility of the applications offered in the new releases.

**Comment by Spudz76** [comment]
Also as builds occur on Appveyor, once they drop the old MSVC there will be no way to compile CUDA 8.0 (requires old MSVC due to silly nVidia headers blocking newer compilers then those that existed)

So they both force obsolescence and block future compilers (even though they would probably work fine)
