### ISSUE TITLE
XMR-stak feature request for Zelerius Network

### ISSUE THREAD

**Issue by anartz** [fireice-uk/xmr-stak#2076]
**XMR-stak feature request for Zelerius Network**

Zelerius Network is switching from CN variant 1 to CN variant 2 in order to fight inequity and centralized mining caused by ASIC devices. The issue has been addressed before in the following article written by the Zelerius Network team and published in Medium: https://medium.com/@zelerius/crytonight-variant-2-v8-for-zelerius-network-7ba97489e08e/

The algorithm change is proposed for block 26 5000, which with an average of 1 block per 30 seconds thrown into the net, and will be accomplished by mid December.

We would like to ask to the team of mining software XMR-STAK to apply this functionality for Zelerius Network after ZLS carries out the switch to CN variant 2 in the block mentioned beforehand.

**Technical details**

Zelerius Network has algorithm CN variant 1 integrated. ZLS will switch to algorithm CN variant 2 through a Hardfork in the block mentioned previously.

**Block Major Version**

1a Block Major Version 5. Block Minor Version 2. Cn_v1
2a Block Major Version 6. Block Minor Version2. CN_v2

**Test pool**

Zelerius Core Team has built a testing pool in order to observe and study beforehand how the currency will respond to this new integration and modification of the algorithm. It is configured in the Block Major Version 6, which accepts CN_V8 hashes and it’s address is: https://xyztest.zelerius.org/. We propose two different difficulties to test in this pool: SSL, 15000 and 1000. Also to be noted at this time, all miners that have tried it have been warned about the pool’s testnet nature. It is noteworthy that this change of algorithm has been agreed and accepted by the community.

After an initial testing for 92 hours by the Zelerius Team with a rig of 6 GPU AMD 580 8 g, the testnet pool has been publicly announced so that the ZLS community miner members can connect to the above and express their own thoughts and impressions. It has been demonstrated as a brilliant way to obtain
accurate and trustworthy information, by receiving feedback directly from miners. The more sources of information the Zelerius Team has access to, the more accurate conclusion it will be able to make.

A correct functioning has been tested and verified supported by Ubuntu 18.04.1 with V2.4.7 dev Cuda 9.1. from mining software XMR-stak. It’s mining software configuration corresponds to this:

--currency cryptonight_v8 -o http://xyztest.zelerius.org:9292 -u ZL4qXYbGtGm1FMCZKsr6m4jBLin7jLu4EHL6ZBd7b3rLUQqZQ6dVYjXBWKPqTq8QxvGRjHiULgjEJ2aogvwNWHS91vi98L7HR -p x

**Conclusions**

We appreciate so much the attention given to this requirement by the XMR-STAK development team.

Links
https://github.com/monero-p

**Comment by zelerius** [comment]
We open a pull request in order to add Zelerius as a config option and automatic switch with block version 6 to CN variant 2 (V8). [Add zelerius as a config option](https://github.com/fireice-uk/xmr-stak/pull/2090)
