### ISSUE TITLE
Is issue #11 fixed in the pre-compiled Windows version?

### ISSUE THREAD

**Issue by chiwalfrm** [fireice-uk/xmr-stak#208]
Downloaded xmr-stak-win64.zip today from https://github.com/fireice-uk/xmr-stak/releases/tag/v2.0.0
it is latest version (post says it was released 3 days ago).

I get the error : "MEMORY ALLOC FAILED: VirtualAlloc failed." twice.  Have 2 physical cores with hyperthreading turned on = 4 logical cores.

I searched github issues and found this: https://github.com/fireice-uk/xmr-stak/issues/11
which says it was fixed in pull #12.  Is this pull merged into the precompiled Windows version?

**Comment by chiwalfrm** [comment]
> -------------------------------------------------------------------
> [2017-11-22 12:02:52] : Start mining: MONERO
> [2017-11-22 12:02:52] : Starting single thread, affinity: 0.
> [2017-11-22 12:02:52] : hwloc: memory pinned
> [2017-11-22 12:02:52] : Starting single thread, affinity: 2.
> [2017-11-22 12:02:52] : MEMORY ALLOC FAILED: VirtualAlloc failed.
> [2017-11-22 12:02:52] : hwloc: memory pinned
> [2017-11-22 12:02:52] : MEMORY ALLOC FAILED: VirtualAlloc failed.
> [2017-11-22 12:02:52] : Fast-connecting to xmr-us-west1.nanopool.org:14433 pool ...
> [2017-11-22 12:02:52] : TLS fingerprint [xmr-us-west1.nanopool.org:14433] SHA256:w4iG797lQuvZmAG3XHXTSY2Xl4u83sB8cnHLGXKeAU8=
> [2017-11-22 12:02:52] : Pool xmr-us-west1.nanopool.org:14433 connected. Logging in...
> [2017-11-22 12:02:53] : Difficulty changed. Now: 120001.
> [2017-11-22 12:02:53] : Pool logged in.
> [2017-11-22 12:03:01] : Result accepted by the pool.
> [2017-11-22 12:03:03] : Difficulty changed. Now: 120001.
> [2017-11-22 12:03:03] : New block detected.
> [2017-11-22 12:03:59] : New block detected.
> [2017-11-22 12:04:59] : New block detected.

**Comment by saylor68** [comment]
helpful questions - did you set your local policy to lock memory? that did it for me. also have lots of virtual space above 16384 I'd say.

**Comment by sergneo** [comment]
Best 32768

**Comment by chiwalfrm** [comment]
@saylor68 Windows 10: i checked local policy and it is by default already set to lock memory for my user ID.  I also had 16384 set for swap min/max.  I increased it to 32768 but I still get this error "MEMORY ALLOC FAILED: VirtualAlloc failed."

**Comment by sergneo** [comment]
So little RAM, increase the memory. A Minimum Of 8 GB

**Comment by chiwalfrm** [comment]
actually my bad.  i rebooted after the change to 32767 and it seems to be ok now.  Thanks all!

**Comment by chiwalfrm** [comment]
@saylor68 @sergneo Specifically the increase of virtual memory from 16384 to 32768 eliminated the error.  Will close this issue now thank you!
