### ISSUE TITLE
SOCKET ERROR any pool

### ISSUE THREAD

**Issue by TheCHIM** [fireice-uk/xmr-stak#209]
I'm using xmr-stak-portbin-linux.tar.gz. OS CentOS 6.9 and here such error appears at start xmr-stak:

./xmr-stak.sh
-------------------------------------------------------------------
xmr-stak 2.0.0 0005e4a

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-11-22 22:39:11] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-11-22 22:39:11] : WARNING: backend NVIDIA disabled.
[2017-11-22 22:39:11] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2017-11-22 22:39:11] : WARNING: No OpenCL platform found.
[2017-11-22 22:39:11] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-11-22 22:39:11] : WARNING: backend AMD disabled.
[2017-11-22 22:39:11] : Starting single thread, affinity: 0.
[2017-11-22 22:39:11] : hwloc: memory pinned
[2017-11-22 22:39:11] : Starting single thread, affinity: 1.
[2017-11-22 22:39:11] : hwloc: memory pinned
[2017-11-22 22:39:11] : Fast-connecting to pool.minemonero.pro:5555 pool ...
[2017-11-22 22:39:11] : SOCKET ERROR - [pool.minemonero.pro:5555] CONNECT error: GetAddrInfo: Name or service not known

**Comment by psychocrypt** [comment]
Please compile it by your own we see this issue a few times inthe last
days. :(

**Comment by TheCHIM** [comment]
I would be happy, but ..:

`cmake3 ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
`
`cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic .
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.0.1 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!`

And all of this list is installed and enabled:

> # CentOS
    sudo yum install centos-release-scl epel-release
    sudo yum install cmake3 devtoolset-4-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make
    sudo scl enable devtoolset-4 bash
    git clone https://github.com/fireice-uk/xmr-stak.git
    mkdir xmr-stak/build
    cd xmr-stak/build

**Comment by fireice-uk** [comment]
@TheCHIM we are working on making the binary actually portable :)
