### ISSUE TITLE
can not dual thread gpu.

### ISSUE THREAD

**Issue by thewalrusking** [fireice-uk/xmr-stak#2091]
# Basic information
  - intel celeron
  - 4 rx vega.
  - windows

I am attempting to follow the vega mining guide and i am setting two threads for each gpu by editing the amd.txt file in the xmr-stak directory . But everytime i change the .txt file to anything other that its original contents i get a "thread 0 has invalid config"  and no mining commences. Any suggestions? The miner works fine with the original text but when i try to dual thread gpu i get nothing.

**Comment by psychocrypt** [comment]
how should we help if you not post the cfg. You make a mistake during copz
past therefore we need to see the cfg.
