### ISSUE TITLE
Dev branch - performances tests

### ISSUE THREAD

**Issue by Q-Sharp** [fireice-uk/xmr-stak#2092]
I compiled the newest dev branch and started some tests (amd opengl) wanna share my results:

### 2.5.2
Vega 64: 2013.7 h/s
Vega 56: 1880.1 h/s
RX550: 486,6 h/s

### dev
Vega 64: 2020.3 h/s
Vega 56: 1814.2 h/s
RX550: 506.3 h/s

### dev (memchunk 3)
Vega 64: 2000.9 h/s
Vega 56: 1800.2 h/s
RX550: 468.2 h/s

Result for now seems to be:
big increase for 550, small increaser for vega 64 and significant loss on vega 56.
All in all a loss in total hashrate for me. 

How to explain the hashrate wins on the one hand and the losses on the other?

**Comment by psychocrypt** [comment]
thanks for the information. Coyld you please add the checksum of the
current used dev. There are around 10 new commits in the dev and it is not
clear which state you are using.
Please also add a note if you tested with the old config(post this cfg) or
if you searched for a new optima.

**Comment by QoOdrink3r** [comment]
#2088
commit ff204b22944ee342dbecc53d84eb228fc38ea7bf

Checksum of downloaded src zip
MD5: 830f50b8c2a14220ed7d92d1d1101470                           
SHA-1: 3b91b298d26aaa8b64a686da43e9bd9c547c5713

(I one of the checksums is the correct one 🔢 
---

First I used same config from 2.5.2.
The results of vega 64 + 550er were already nice. 
For my vega 56 I tested some more values and changed something to get some more hashes.
I already posted final results.

---

Vega 56 config 2.5.2:

{ 
    "index" : 2,
    "intensity" : 1984, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
  },
  { "index" : 2,
    "intensity" : 1968, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
  },

config for dev version:
{ 
    "index" : 2,
    "intensity" : 1984, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
  },
  { "index" : 2,
    "intensity" : 1984, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
  },


Also tryed 2 x 1968 and 2 x 1952 as intensity.

**Comment by QoOdrink3r** [comment]
My config for vega 56:

```
{ "index" : 2,
    "intensity" : 1984, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 3, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
  },
  { "index" : 2,
    "intensity" : 1984, "worksize" : 16,
    "affine_to_cpu": false, "strided_index" : 3, "mem_chunk" : 2,
    "unroll" : 4, "comp_mode" : false
}
```

resulting in:
![grafik](https://user-images.githubusercontent.com/8755388/48920051-d8868600-ee96-11e8-82f2-5085be8b463b.png)

**Comment by trasherdk** [comment]
It would be helpful to know which algorithm and config used to obtain those rates.

**Comment by psychocrypt** [comment]
config is in the post above but currency information is missing.

**Comment by trasherdk** [comment]
Yes, for Vega 56, but that's not the one I was looking for.
I have RX 550 2GB, but I have a feeling he's got 4GB.
