### ISSUE TITLE
10s Statistic for GPU threads random show/hide 

### ISSUE THREAD

**Issue by anhphan** [fireice-uk/xmr-stak#21]
As you see in the picture:
![image](https://user-images.githubusercontent.com/1614690/31273591-8cfd7c92-aab9-11e7-84f5-1c903de9e0ea.png)

Statistic for gpu threads is randomly show/hide for each threads, it's will change with each refresh (this threads hide, other threads show).

Beside that, when having gpu, total hashrate of 10s is always hide. Highest hastrate alway 0.

On CLI only having zero highest hashrate problem.

**Comment by psychocrypt** [comment]
Thx for reporting  I think I missed to set the timer to 10sec and xhanged
only the lables. Gpus needs more than 2 or 3 sec to calculate one bunch of
hashes.

Am 06.10.2017 12:13 Nachm. schrieb "Anh Phan Tuan" <notifications@github.com

**Comment by fireice-uk** [comment]
This is because 10s is too short of a sample time for a gpu, the result comes back as NaN and sum is fuxored. Sample time needs to be increased to 30s or so.

**Comment by psychocrypt** [comment]
@fireice-uk 10sec is fine and is now also used for the terminal output. It
was 2.5 sec before and I changed it during the refactoring. I think I
missed to update a timer somewhere which builds the statistics.

Am 06.10.2017 3:18 Nachm. schrieb "fireice-uk" <notifications@github.com>:

**Comment by psychocrypt** [comment]
Should be fixed with #26
