### ISSUE TITLE
CMAKE error when compiling, PU_ENABLE=ON

### ISSUE THREAD

**Issue by steamingtracks** [fireice-uk/xmr-stak#2108]
Please provide as much as possible information to reproduce the issue.
It compiled just fine before I added the flag CPU_ENABLE=ON, I'm trying to mine off of my CPU. If you need anymore details please let me know.

# Basic information
  - Type of the CPU?
Intel Celeron
# Compile issues
  - Which OS do you use?
  GalliumOS(Ubuntu 14.04)
  add **all** commands you used and the **full** compile output here
 `chrx@chrx:~$ git clone https://github.com/fireice-uk/xmr-stak/
Cloning into 'xmr-stak'...
remote: Enumerating objects: 6291, done.
remote: Total 6291 (delta 0), reused 0 (delta 0), pack-reused 6291
Receiving objects: 100% (6291/6291), 1.93 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (4507/4507), done.
Checking connectivity... done.
chrx@chrx:~$ cd xmr-stak
chrx@chrx:~/xmr-stak$ cmake . -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -CPU_ENABLE=ON -DCPU_ENABLE=ON
loading initial cache file PU_ENABLE=ON
CMake Error: Error processing file: PU_ENABLE=ON
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring incomplete, errors occurred!
See also "/home/chrx/xmr-stak/CMakeFiles/CMakeOutput.log".
See also "/home/chrx/xmr-stak/CMakeFiles/CMakeError.log".
chrx@chrx:~/xmr-stak$ cmake . -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -CPU_ENABLE=ON -DCPU_ENABLE=ON
loading initial cache file PU_ENABLE=ON
CMake Error: Error processing file: PU_ENABLE=ON
-- Configuring incomplete, errors occurred!
See also "/home/chrx/xmr-stak/CMakeFiles/CMakeOutput.log".
See also "/home/chrx/xmr-stak/CMakeFiles/CMakeError.log".
chrx@chrx:~/xmr-stak$ 
`
  run `cmake -LA .` in the build folder and add the output here
`
Number of platforms                               0
`

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

**Comment by psychocrypt** [comment]
it is not PU_ENABLE is is CPU_ENABLE

**Comment by Spudz76** [comment]
You missed the `-D` and `-CPU` means `-C` ...whatever that does... `PU_ENABLE`

Also CPU is always on unless you override with `OFF` so adding that is pointless anyway
