### ISSUE TITLE
Need to remove Autotune line from AMD.txt to run w/o AMD gpus

### ISSUE THREAD

**Issue by Nostradamus411** [fireice-uk/xmr-stak#2120]
I was helping a miner who only wanted to use his CPU to mine, he had updated the GPU array to be null as is noted in the opening comments.  But after doing so was running into a parse error.

![image](https://user-images.githubusercontent.com/38844339/49463807-f620ed00-f7be-11e8-97da-c6983143ab2d.png)

We found that to get around the parsing error the new line for the autotune feature also needed to be removed/commented out.

"auto_tune" : 0,   <== remove / comment out

Tactical solution could be to just add this info the AMD.txt comment section 👍

**Comment by Spudz76** [comment]
Post non-working version of the file that won't parse.  Note `null` is not a member of the array but in place of the array, it should work fine when done correctly (JSON is JSON)

**Comment by Spudz76** [comment]
Also the correct method is really to use `--noAMD` on the command line.  No reason to half-fire-up the whole backend just to parse a file that ends up giving it nothing to do.

**Comment by psychocrypt** [comment]
even if the program paramter is the correct way I will have a look into the
issue because many users do not know how to use program parameter

**Comment by Spudz76** [comment]
I suspect the resulting nulled file was missing a comma or such (user error) or it would parse.

**Comment by psychocrypt** [comment]
Could you please post the broken pools.txt file. I tried to reproduce the
issue but it was not possible. I think there is a typo in the file.

**Comment by xq0404** [comment]
> 
> 
> Also the correct method is really to use `--noAMD` on the command line. No reason to half-fire-up the whole backend just to parse a file that ends up giving it nothing to do.

I also hope to disable AMD or nvidia sometimes if the GPU is too weak and only serves to slow down the whole system. So do I need to create a batch file with `--noAMD` on the command line?
