### ISSUE TITLE
xmr-stak crashes above 14 GPU threads

### ISSUE THREAD

**Issue by yellovest** [fireice-uk/xmr-stak#2126]
Please provide as much as possible information to reproduce the issue.

# Basic information
Using octominer board with [8] RX580 GPUS
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Stability issue
  - Is the CPU or GPU overclocked?  GPUs are overclocked
  - Is the Main memory of the CPU or GPU undervolted?  GPUs are undervolted

If I use the following configuration the miner runs stable:

`gpu_threads_conf" : [ { "index" : 0, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 0, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 1, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 1, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 2, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 2, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 3, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 3, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 4, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 5, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 6, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 6, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 7, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, { "index" : 7, "intensity" : 1004, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2, "unroll" : 8, "comp_mode" : true }, ], "platform_index" : 0,`

If I try and have any other GPU run two threads the miner crashes.  It doesn't seem to matter which ones I choose.  14 GPU threads or below is stable.  15 or 16 GPU threads crashes.

**Comment by psychocrypt** [comment]
post the full log. which Os? What kind of GPUs? Did you increased the
virtual memory? It sounds like it is ro small for 15 GPUs

**Comment by yellovest** [comment]
You're right, turned out to be a memory issue.  put in larger RAM and it works now.  Thank you!
