### ISSUE TITLE
32 bit release for Windows 10

### ISSUE THREAD

**Issue by Russellx2000** [fireice-uk/xmr-stak#213]
Can you please compile a version for 32 bit systems. (or can someone tell me the steps to do so)

**Comment by psychocrypt** [comment]
This is not possible our code ia not support 32bit architectures. The
expected hash rate will be extrem low.

**Comment by sergneo** [comment]
But there is a PC with a 32 bit OS, where it is impossible to change the system.
And no matter what would be the hash, it will still be above 0. It's better than nothing.

**Comment by psychocrypt** [comment]
The effort to support 32bit systems is large. We need to focus our small
amount of time to other improvements.
Feel free to open a pull request to add 32bit support.
