### ISSUE TITLE
compiling on Windows 

### ISSUE THREAD

**Issue by dormancygrace** [fireice-uk/xmr-stak#2139]
Compiling with CUDA 10 work well with lastest toolset of VS 2017. You need to change documentation

**Comment by dormancygrace** [comment]
![default](https://user-images.githubusercontent.com/20384748/50052815-265f7880-013b-11e9-963b-8c0d7dc003e5.PNG)
For AMD&CPU last toolset works too, so you can add this info to your documentation

**Comment by psychocrypt** [comment]
But is will not work togethet with our precompied binaries since toolchains
are not compatible and we compiled the latest dependencies with v141

**Comment by dormancygrace** [comment]
forgot about it =)
