### ISSUE TITLE
freebsd xmr-stak 2 Program running problem

### ISSUE THREAD

**Issue by zhiapp-com** [fireice-uk/xmr-stak#214]
freebsd11 xmr-stak 2 Program running problem

pkg install git libmicrohttpd hwloc cmake 

git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DHWLOC_ENABLE=OFF ..
make install

info:
xmr-stak 2.0.0 79154f7

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-11-23 20:55:13] : Start mining: MONERO
[2017-11-23 20:55:13] : Starting double thread, no affinity.
Bus error (core dumped)

**Comment by psychocrypt** [comment]
please compile with `cmake -DCMAKE_BUILD_TYPE=Debug ..` and run with with the debugger `gdb`

```
gdb -ex r -ex tb --args ./xmr-stak
```

and post all output

**Comment by zhiapp-com** [comment]
root@freebsd:/xmr-stak/build/bin # gdb -ex r -ex tb --args ./xmr-stak
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) 

Is this information?



 ./xmr-stak
...
[2017-11-24 09:54:52] : Start mining: MONERO
[2017-11-24 09:54:52] : Starting single thread, no affinity.
Illegal instruction (core dumped)

**Comment by psychocrypt** [comment]
Mhh I hoped to see more error messages.
Please post you hardware configuration.
Please run `cat /proc/cpuinfo` or similar to show all features of your cpu.
I am not sure if the command is correct I never used a bsd system.

**Comment by lisergey** [comment]
to see BSD features would be good to issue
`cat /var/run/dmesg.boot | head -n 20`

**Comment by Skayver** [comment]
Is not from hardware, i have same problem on diferent FreeBSD servers.
But on the same servers xmr-stak-cpu work normaly.

cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DHWLOC_ENABLE=OFF -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/xmr-stak/build
root@[14:03]/usr/local/src/xmr-stak/build> make
Scanning dependencies of target xmr-stak-c
[  4%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 12%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 20%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 24%] Linking C static library bin/libxmr-stak-c.a
[ 24%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
/usr/local/src/xmr-stak/xmrstak/jconf.cpp:161:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 60%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 72%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 76%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 80%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 84%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 88%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 92%] Linking CXX static library bin/libxmr-stak-backend.a
[ 92%] Built target xmr-stak-backend
Scanning dependencies of target xmr-stak
[ 96%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[100%] Linking CXX executable bin/xmr-stak
[100%] Built target xmr-stak
root@[14:03]/usr/local/src/xmr-stak/build> cd bin/
root@[14:03]/usr/local/src/xmr-stak/build/bin> ./xmr-stak
Please enter:
- Currency: 'monero' or 'aeon'
monero
- Pool address: e.g. pool.usxmrpool.com:3333
pool.usxmrpool.com:3333
- Username (wallet address or pool login):
wallet
- Password (mostly empty or x):
x
- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
n
- Do you want to use nicehash on this pool? (y/n)
n
- Do you want to use multiple pools? (y/n)
n
Configuration stored in file 'config.txt'
[2017-11-24 14:04:20] : MEMORY ALLOC FAILED: mlock failed
[2017-11-24 14:04:20] : MEMORY ALLOC FAILED: mlock failed
-------------------------------------------------------------------
xmr-stak 2.0.0 79154f7

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-11-24 14:04:20] : Start mining: MONERO
[2017-11-24 14:04:20] : Autoconf failed: L3 size sanity check failed - 8 KB.
[2017-11-24 14:04:20] : Autoconf FAILED. Create config for a single thread. Please try to add new ones until the hashrate slows down.
[2017-11-24 14:04:20] : CPU configuration stored in file 'cpu.txt'
[2017-11-24 14:04:20] : Starting single thread, no affinity.
Illegal instruction (core dumped)

Invalid shared object handle 0x800b43d58

if need more info ...

**Comment by blacklion** [comment]
Is it dup of #177?

**Comment by zhiapp-com** [comment]
xmrstak/jconf.cpp
 @@ -158,6 +158,7 @@ bool jconf::GetPoolConfig(size_t id, pool_cfg& cfg)
  	}
  	else /* Special case - user selected same weights for everything */
  		cfg.weight = 0.0;
 +	return true;
  }

Recompile and solve it. TKS
