### ISSUE TITLE
Duplicate equal job detected

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#2145]
I have latest xmr and **Pool ping time | 27 ms**

And for last week i got several messages like this:
**[pool.supportxmr.com:7777] Duplicate equal job detected! Please contact your pool admin.
[pool.supportxmr.com:7777] CALL error: Timeout while waiting for a reply
[pool.supportxmr.com:7777] CONNECT error: GetAddrInfo: Temporary failure in name resolution**

How to eliminate this messages?
What to tune for best way?

Thanks.

**Comment by Spudz76** [comment]
the last error means your DNS sucks
Fix ISP, use some other DNS, reduce packet loss and timeouts on your link to the Internet.
Don't use Wifi on miners.  Also feels like it could be Wifi drops.

**Comment by bizlevel** [comment]
No WIFI, only cabels.
Can i Use IP instead DNS name?

Duplicate equal job - it is as result of bad latency?

**Comment by pinpins** [comment]
just faced the same issue with one of users 
**"Duplicate equal job detected! Please contact your pool admin."**

Not sure what exactly is wrong, as I have tested the same on stable local network, and got this issue only on xmr-stak miner.
