### ISSUE TITLE
In report Avg result time is below zero, digits with minus in sec

### ISSUE THREAD

**Issue by bizlevel** [fireice-uk/xmr-stak#2146]
I have latest xmr, and i in first time see result lower than zero.
How it can be?
Just reboot rig and i see that:
![1](https://user-images.githubusercontent.com/12154217/50454180-7665e880-094e-11e9-944c-e3427a3ac85f.PNG)

After some time - little lower:
![2](https://user-images.githubusercontent.com/12154217/50454181-7665e880-094e-11e9-86fc-e39e43eed5bd.PNG)

And after some time again lower:
![3](https://user-images.githubusercontent.com/12154217/50454182-76fe7f00-094e-11e9-82db-2528f812cf1b.PNG)

Hm, how long wait for good result. )

P.S. It is not critical !

**Comment by bizlevel** [comment]
Yes. with ntp.
After some tome - all is fine:
![capture](https://user-images.githubusercontent.com/12154217/50455823-2f312500-0959-11e9-8789-9d9a5733bd9a.PNG)

**Comment by psychocrypt** [comment]
If you have linux and windows in dual mode this can be happen each time
when you seitch the os
