### ISSUE TITLE
libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fbmoose48** [fireice-uk/xmr-stak#2156]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. - Intel Core 2 Duo E8400
  - Type of the GPU (if you try to miner with the GPU). - Nvidia GeForce GT 620

Ubuntu 18.04

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```
Version: xmr-stak/2.7.1/7d6cd31/master/lin/nvidia-amd-cpu/20

Installed latest CUDA, compiled with gcc-6

cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-6

make install

cd /xmr-stak/build/bin/

sudo ./xmr-stak

results in "Setup failed for GPU 0. Exiting."

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?
No.

$ nvidia-smi
Tue Jan  1 12:42:04 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 620      Off  | 00000000:01:00.0 N/A |                  N/A |
| 26%   39C    P8    N/A /  N/A |    334MiB /   957MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

When I try to run xmr-stak:
[2019-01-01 12:40:55] : Mining coin: monero
[2019-01-01 12:40:55] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2019-01-01 12:40:55] : WARNING: backend AMD (OpenCL) disabled.
[2019-01-01 12:40:55] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory
[2019-01-01 12:40:55] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda9_2.so: cannot open shared object file: No such file or directory
[2019-01-01 12:40:55] : NVIDIA: try to load library 'xmrstak_cuda_backend'
NVIDIA: found 1 potential device's
[2019-01-01 12:40:55] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [9.1/9.1] GPU#0, device architecture 21: "GeForce GT 620"... WARNING: skip device - binary does not contain required device architecture
[2019-01-01 12:40:55] : Setup failed for GPU 0. Exiting.

Any thoughts? thanks

**Comment by fbmoose48** [comment]
I'm thinking somehow I missed getting those cuda_backend files into the right directory, any suggestions on how to correct this are appreciated.

**Comment by Spudz76** [comment]
Normal, it is for being able to load an intentional CUDA10 / CUDA9 / CUDA8 backend.
However to make those files you would compile on CUDA10 then rename the `xmrstak_cuda_backend` to `xmrstak_cuda_backend_cuda10_0`, then switch CUDA SDK target and build again, etc.
There is no automated CMake targeting (yet?) to build the actual files it searches for.  Eventually though it loads the old/normal/usual default of `xmrstak_cuda_backend` which can be of whatever CUDA version the compiling SDK had activated.

Thus that is completely normal, the files aren't forced to exist it is for being able to package releases that work across more driver versions.

You can `mv xmrstak_cuda_backend.so xmrstak_cuda_backend_cuda10_0.so` to get rid of the messages (regardless if the .so is actually CUDA10, it is *just* a name)

**Comment by Spudz76** [comment]
Furthermore, your GPU is a Fermi and as such you must compile with CUDA8 or it will not work
Also possibly downgrade driver to one that contained CUDA8 as sometimes running CUDA8-Apps on CUDA9.2-Driver (I think is what 390.xx had inside) had random problems.  There is info in the CUDA Compilation docs.

**Comment by fbmoose48** [comment]
Do I need to run

apt-get purge nvidia-cuda*
apt-get purge nvidia-*

Prior to installing CUDA 8.0, or can I just install 8.0 and proceed to re-compile?

Is there anything I need to be mindful of removing prior to the re-compile? Do I need to scrub xmr-stak from the system before re-compiling? any quick tips on how to do that if it is needed?

thanks

**Comment by fbmoose48** [comment]
I have 2 very similar setups, both running Ubuntu 18.04.

On the second, which had a freshly formatted and reinstalled OS I compiled with CUDA 8.0, and got the gpu running no problem.

On this one however, which already had xmr-stak compiled, I removed all nvidia component I could think of with

sudo rm etc/apt/sources.d/cuda
sudo apt remove nvidia-cuda-toolkit
sudo apt-get purge nvidia-cuda*
sudo apt-get purge nvidia-*

then downloaded and installed CUDA 8.0 and proceeded to re-compile with CUDA 8.0. But this issue persists.

**Comment by Spudz76** [comment]
cmake caches (and does not recheck) many things, destroy old build dir and make empty one, try cmake command again and it will force rechecks with new environment

or so I suspect

**Comment by fbmoose48** [comment]
I tried that, output on run:

[2019-01-03 21:31:18] : Mining coin: monero
[2019-01-03 21:31:18] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2019-01-03 21:31:18] : WARNING: backend AMD (OpenCL) disabled.
[2019-01-03 21:31:18] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory
[2019-01-03 21:31:18] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda9_2.so: cannot open shared object file: No such file or directory
[2019-01-03 21:31:18] : NVIDIA: try to load library 'xmrstak_cuda_backend'
NVIDIA: found 1 potential device's
[2019-01-03 21:31:18] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [9.1/9.1] GPU#0, device architecture 21: "GeForce GT 620"... WARNING: skip device - binary does not contain required device architecture
[2019-01-03 21:31:18] : Setup failed for GPU 0. Exiting.

Any thoughts? I believe I compiled with CUDA 8.0 this time, is there some way to verify?

I have noticed the Nvidia GT 720 in the other rig that works fine is running driver 390.77, whereas the Nvidia GT 620 that is yielding the above failed results runs driver 390.87...could this be the issue? should I revert to 390.77? This is perplexing , as I must have setup up properly at least once, so what's going on with the second instance?

**Comment by fbmoose48** [comment]
Swapped the GT 620 for a GT 730... still can't get it working. The GT 720 is a GK208 Kepler card and the GT 730 is a GF108 Fermi card, that explains why I can run the 720 but not the 730. That being said, I believe I have CUDA 8.0 installed with Nvidia driver 390.87 installed running the GT 720. Is that driver too advanced for a the GF108 Fermi build card?

What does "binary does not contain required device architecture" mean? is this a build error or a driver error?

**Comment by Spudz76** [comment]
Build error, but when CUDA8.0 is detected the "20" series gets added the the `CUDA_ARCH` list so it should be included if you truly got CUDA8.0 SDK working properly.
You can specify `-DCUDA_ARCH=20` to only build for Fermi.

I would install the last CUDA8 driver, you have to dig into the PDF release notes to find out what CUDA is in each driver.  I never got CUDA8 programs to run perfect on any other CUDA driver, the backward compatibility is pretty bad although it was intended to work.

**Comment by Spudz76** [comment]
Your detection line has to say `CUDA [8.0/8.0]` for it to work properly.

**Comment by fabianboesiger** [comment]
@fbmoose48 how did you get rid of the error? I currently have the exact same error message.
