### ISSUE TITLE
feature request: dividing hashing-power over multiple pools

### ISSUE THREAD

**Issue by HydraGene** [fireice-uk/xmr-stak#216]
We can add multiple pools in our configuration. Several as a fallback in case pool#1 can't be reached, so it hops to pool#2.

But I would like to be able to divide my hashing-power over multiple pools. For example:
moneropool#1: 25% hashing-power
moneropool#2: 75% hashing-power

Would be nice for this to even work with different coins which basically have the same algorithm. (I'm not sure if this differs from the above example.) For example: 
moneropool#1: 70% hashing-power
aeonpool#2: 20% hashing-power
intensecoinpool#2: 10% hashing-power

I'm not sure if this is possible. But if it is, I'd like to get this feature.
Low priority though.

**Comment by psychocrypt** [comment]
This feature was planned but skiped. Maybe it will in in one of the next
releases.
