### ISSUE TITLE
Stak crashes, unable to fix

### ISSUE THREAD

**Issue by rickbb** [fireice-uk/xmr-stak#2160]
have one rig that stak keeps crashing on me, I've searched but can't find a similar issue post. It does this with an older version and the latest download as well. Wondering if anyone has seen this or can point me in a direction to look at.

I have other rigs running fine, but this is my only MSI mobo setup.

Here is the error from the log file:

Faulting application name: xmr-stak.exe, version: 0.0.0.0, time stamp: 0x5c0ec342
 Faulting module name: ucrtbase.dll, version: 10.0.17763.1, time stamp: 0x309241e0
 Exception code: 0xc0000409
 Fault offset: 0x000000000006f08e
 Faulting process id: 0x3e8

MSI mobo, Intel 100 series chip set, Core I3 cpu, 4 gb ram, 500 gb hdd, 16 GB vram, 5x Asus Nvidia 1060 3gb cards. Windows 10 ENT, LTSB 2019 version 64bit.

Nvidi.txt file is set for 8 threads, 144 blocks each card. Cards are slightly over clocked with Asus software, about 10%.

At the same time that stak crashes the system log shows a low virtual mem condition, but with 16GB paging file not sure why or if that is the cause of the crash. There are other times it shows a low Vram and stak does not crash.

**Comment by rickbb** [comment]
OK, I've tried changing so many setting in windows it's now locked up, won't boot. 

Will wipe hard drive and rebuild from scratch. 

Mark this one closed.

**Comment by rickbb** [comment]
See above

**Comment by psychocrypt** [comment]
could you please post if it work after you have a clean system without any
changes.

**Comment by rickbb** [comment]
Continues to crash after formatting hard drive and clean install of Windows Ent LTSB 2019 64bit version and Stak with default settings. GPU cards are NOT overclocked this time.

After it continued crashing, I upped the RAM to 16GB, no change still crashes. 

Then changed paging file to 32GB, continues to crash.

Last change was setting GPU threads to 30 and blocks to 40 in the nivida.txt file. Boosted hash rate by 50 each card. but did not change the random crashing.

**Comment by psychocrypt** [comment]
could you increase the virtual memory in windows. You can increase it to a
value higher than the available main memory

**Comment by rickbb** [comment]
It's currently at 32GB, I will up it to 64GB.

**Comment by rickbb** [comment]
Didn't help, still shuts down. Did not get a low VRAM error though.

**Comment by psychocrypt** [comment]
do you tried to remove the overclocking.
 Please post the cpu.txt and nvidia.txt file.
Please also post all output from the terminal (really all output, every
line even if it looks not important)

**Comment by rickbb** [comment]
Overclocking was removed on clean system build. Has not been reinstalled.

Nvida.txt file
// generated by xmr-stak/2.7.1/7d6cd31b1/master/win/nvidia-amd-cpu/20

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 * mem_mode      - select the memory access pattern (this option has only a meaning for cryptonight_v8 and monero)
 *                 0 = 64bit memory loads
 *                 1 = 256bit memory loads   
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0,
 *       "affine_to_cpu" : false, "sync_mode" : 3, "mem_mode" : 1
 *     },
 * ],
 * If you do not wish to mine with your nVidia GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 0,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 1,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 2,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 3,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 4,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },

],

CPU.txt
/ generated by xmr-stak/2.7.1/7d6cd31b1/master/win/nvidia-amd-cpu/20

/*
 * Thread configuration for each thread. Make sure it matches the number above.
 * low_power_mode - This can either be a boolean (true or false), or a number between 1 to 5. When set to true,
 *                  this mode will double the cache usage, and double the single thread performance. It will
 *                  consume much less power (as less cores are working), but will max out at around 80-85% of
 *                  the maximum performance. When set to a number N greater than 1, this mode will increase the
 *                  cache usage and single thread performance by N times.
 *
 * no_prefetch    - Some systems can gain up to extra 5% here, but sometimes it will have no difference or make
 *                  things slower.
 *
 * asm            - Allow to switch to a assembler version of cryptonight_v8; allowed value [auto, off, intel_avx, amd_avx]
 *                    - auto: xmr-stak will automatically detect the asm type (default)
 *                    - off: disable the usage of optimized assembler
 *                    - intel_avx: supports Intel cpus with avx instructions e.g. Xeon v2, Core i7/i5/i3 3xxx, Pentium G2xxx, Celeron G1xxx
 *                    - amd_avx: supports AMD cpus with avx instructions e.g. AMD Ryzen 1xxx and 2xxx series
 *
 * affine_to_cpu  - This can be either false (no affinity), or the CPU core number. Note that on hyperthreading
 *                  systems it is better to assign threads to physical cores. On Windows this usually means selecting
 *                  even or odd numbered cpu numbers. For Linux it will be usually the lower CPU numbers, so for a 4
 *                  physical core CPU you should select cpu numbers 0-3.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "cpu_threads_conf" :
 * [
 *      { "low_power_mode" : false, "no_prefetch" : true, "asm" : "auto", "affine_to_cpu" : 0 },
 *      { "low_power_mode" : false, "no_prefetch" : true, "asm" : "auto", "affine_to_cpu" : 1 },
 * ],
 * If you do not wish to mine with your CPU(s) then use:
 * "cpu_threads_conf" :
 * null,
 */

"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "asm" : "auto", "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "asm" : "auto", "affine_to_cpu" : 1 },

],

console output file.

xmr-stak 2.7.1 7d6cd31b1

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-01-13 11:24:23] : Mining coin: monero
[2019-01-13 11:24:23] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2019-01-13 11:24:23] : WARNING: backend AMD (OpenCL) disabled.
[2019-01-13 11:24:23] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
NVIDIA: found 5 potential device's
[2019-01-13 11:24:23] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [10.0/10.0] GPU#0, device architecture 61: "GeForce GTX 1060 3GB"... device init succeeded
[2019-01-13 11:24:23] : Starting NVIDIA GPU thread 1, no affinity.
CUDA [10.0/10.0] GPU#1, device architecture 61: "GeForce GTX 1060 3GB"... device init succeeded
[2019-01-13 11:24:23] : Starting NVIDIA GPU thread 2, no affinity.
CUDA [10.0/10.0] GPU#2, device architecture 61: "GeForce GTX 1060 3GB"... device init succeeded
[2019-01-13 11:24:24] : Starting NVIDIA GPU thread 3, no affinity.
CUDA [10.0/10.0] GPU#3, device architecture 61: "GeForce GTX 1060 3GB"... device init succeeded
[2019-01-13 11:24:24] : Starting NVIDIA GPU thread 4, no affinity.
CUDA [10.0/10.0] GPU#4, device architecture 61: "GeForce GTX 1060 3GB"... device init succeeded
[2019-01-13 11:24:24] : NVIDIA: use library 'xmrstak_cuda_backend_cuda10_0'
[2019-01-13 11:24:24] : Starting 1x thread, affinity: 0.
[2019-01-13 11:24:24] : hwloc: memory pinned
[2019-01-13 11:24:24] : Starting 1x thread, affinity: 1.
[2019-01-13 11:24:24] : hwloc: memory pinned
[2019-01-13 11:24:24] : Fast-connecting to monerohash.com:2222 pool ...
[2019-01-13 11:24:24] : Pool monerohash.com:2222 connected. Logging in...
[2019-01-13 11:24:24] : Difficulty changed. Now: 5000.
[2019-01-13 11:24:24] : Pool logged in.
[2019-01-13 11:24:30] : Result accepted by the pool.
[2019-01-13 11:24:30] : Result accepted by the pool.
[2019-01-13 11:24:34] : Result accepted by the pool.
[2019-01-13 11:24:34] : Result accepted by the pool.
[2019-01-13 11:24:34] : Result accepted by the pool.
[2019-01-13 11:24:35] : Result accepted by the pool.
[2019-01-13 11:24:36] : Result accepted by the pool.
[2019-01-13 11:24:37] : Difficulty changed. Now: 8750.
[2019-01-13 11:24:37] : New block detected.
[2019-01-13 11:24:45] : Result accepted by the pool.
[2019-01-13 11:24:47] : Result accepted by the pool.
[2019-01-13 11:24:50] : Result accepted by the pool.
[2019-01-13 11:24:50] : Result accepted by the pool.
[2019-01-13 11:24:54] : Result accepted by the pool.
[2019-01-13 11:25:07] : Difficulty changed. Now: 15313.
[2019-01-13 11:25:07] : New block detected.
[2019-01-13 11:25:07] : Result accepted by the pool.
[2019-01-13 11:25:16] : Result accepted by the pool.
[2019-01-13 11:25:33] : Result accepted by the pool.
[2019-01-13 11:25:37] : Difficulty changed. Now: 26798.
[2019-01-13 11:25:37] : New block detected.
[2019-01-13 11:25:59] : Result accepted by the pool.
[2019-01-13 11:26:07] : Difficulty changed. Now: 46897.
[2019-01-13 11:26:07] : New block detected.
[2019-01-13 11:26:11] : Result accepted by the pool.
[2019-01-13 11:26:12] : Result accepted by the pool.


event log entries.txt
Windows App log entry

Faulting application name: xmr-stak.exe, version: 0.0.0.0, time stamp: 0x5c0ec342
Faulting module name: ucrtbase.dll, version: 10.0.17763.1, time stamp: 0x309241e0
Exception code: 0xc0000409
Fault offset: 0x000000000006f08e
Faulting process id: 0xbbc
Faulting application start time: 0x01d4aadc5fec3a45
Faulting application path: C:\Users\user1060\Downloads\xmr-stak-win64 (1)\xmr-stak-win64-2.7.1\xmr-stak.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 5e15edb3-d9ff-4d34-95ed-63cab4657be8
Faulting package full name: 
Faulting package-relative application ID: 




Windows system log entry at same timestamp as App log entry

Display driver nvlddmkm stopped responding and has successfully recovered.

This error only shows sometimes at same time as stak crash, sometimes it shows and stak does not crash.

**Comment by rickbb** [comment]
OK, GPU blocks now at 30. This cut the hash rate almost 100Hs on each card. 

I will let it run for a few hours and see what happens.

**Comment by psychocrypt** [comment]
yes this is for testing. if it eorks than you need only to reduce the
blocks for the first gpu. ehat you also can try is to increase bfactor by
one.
The rrason for the crash can be a gpu which runs out of memory because the
window manager uses to much resources or the kernel is running to long and
windows is killing the miner.

**Comment by rickbb** [comment]
Crashed again, ran for 4 hours.

**Comment by rickbb** [comment]
I set the bfactor to 7 on the first gpu and left it at 30 blocks.

Moved all the others to 40 blocks.

**Comment by rickbb** [comment]
Continues to crash, worse now. crashed 4 times in 3 hours.

I've put the blocks back to 40 and bfactor back to 6. I have installed a program that will monitor and restart the exe when it detects a crash. At least it will keep it mining until we can figure out what is going on with this rig.

**Comment by rickbb** [comment]
Timing of the crash ranges anywhere from 1 hour to 12 hours.

**Comment by CryptoBroke550** [comment]
rickbb, this sounds much like the issue I had, I disabled TdrDelay on all my rigs and have been able to increase my hash rate. I had the issue with both Nvidia and AMD rigs. Worth a Try.
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys

**Comment by rickbb** [comment]
Thanks, I've just implemented this on this rig. I'll see how it goes.
All my other rigs don't have this issue, but the others are either single GPU PC's or have older AMD cards.

**Comment by rickbb** [comment]
Well that didn't fix it, back to square one.

**Comment by CryptoBroke550** [comment]
Just in case I should add some more info.
I was not able to find settings that allowed we to keep it enabled so I disabled TdrDelay.
I created a Qword first (64bit OS) but that did not correct the issue.
I then used a Dword set to 0 and the problem was corrected.

KeyPath   : HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
KeyValue  : TdrLevel
ValueType : REG_DWORD
ValueData : 0 - Detection disabled

I also read people did a clean removal of the video drivers and clean install, but mine was a clean install.

**Comment by rickbb** [comment]
My system had a TDR_Watch and I had set that to zero, but it seems to automaticly reset back to 1.
I've deleted that reg key and created the TDRLevel key and set it to 0.

I've also read several posts on MS and Nvida forums about this problem. Looks it's been going on for years. Some people have fixed it by swapping out power supplies, some by reinstalling the drivers, some by the TDR fix and so on. Some have never been able to fix it. Hope I'm not one of those.

**Comment by rickbb** [comment]
Just an FYI, I have not found a solution after trying all the recommendations I've see online. Even a new and larger power supply. I do have a batch file that loops and will restart stak within 5 seconds of closing, but that's just a band aid. I guess the only real solution is to start over and build a Linux rig instead.
