### ISSUE TITLE
amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x

### ISSUE THREAD

**Issue by fbmoose48** [fireice-uk/xmr-stak#2162]
Explicit instruction on how to identify and install the appropriate AMD driver compatible with DRM version is 2.50.0 would be greatly appreciated.

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. - Intel Core 2 Duo E8400
  - Type of the GPU (if you try to miner with the GPU). - AMD RadeonR7 240

Ubuntu 18.04

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
Version: xmr-stak/2.7.1/7d6cd31/master/lin/nvidia-amd-cpu/20

Installed Radeon 18.20

cmake .. 

make install

cd /xmr-stak/build/bin/

sudo ./xmr-stak

results in "amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.
Segmentation fault"

# AMD OpenCl issue

  ```
 amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.
Segmentation fault (core dumped)
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?
No.

**Comment by fbmoose48** [comment]
restarted and clinfo yields:

clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (2639.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Oland
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2639.3)
  Driver Version                                  2639.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Board Name (AMD)                         AMD Radeon Graphics
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               5
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             600MHz
  Graphics IP (AMD)                               6.0
  Device Partition                                (core)
    Max number of sub-devices                     5
    Supported partition types                     none specified
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    32, Little-Endian
  Global memory size                              1712984064 (1.595GiB)
  Global free memory (AMD)                        <printDeviceInfo:75: get number of CL_DEVICE_GLOBAL_FREE_MEMORY_AMD : error -33>
  Global memory channels (AMD)                    2
  Global memory banks per channel (AMD)           8
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           1270428876 (1.183GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1546958597397314167ns (Tue Jan  8 09:43:17 2019)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    Number of async queues (AMD)                  2
    Max real-time compute queues (AMD)            0
    Max real-time compute units (AMD)             0
    SPIR versions                                 1.2
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Oland
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Oland
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Oland

**Comment by fbmoose48** [comment]
I've got the radeon driver blacklisted in favor of the amdgpu and the amdgpu is running, but on start of mining I get:

Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.
[2019-01-08 09:57:26] : WARNING: AMD device not found
[2019-01-08 09:57:26] : WARNING: backend AMD (OpenCL) disabled.

and it only runs the cpu, any suggestions?

**Comment by Spudz76** [comment]
Oland is pretty old, probably needs the 15.x crimson driver not anything newer (they broke most of the older GPUs, pre R9)

**Comment by zefkerr** [comment]
> Oland is pretty old, probably needs the fglrx 15.x crimson driver, not anything newer like amdgpu-pro (they broke most of the pre-R9 older GPUs, then abandoned them so there will be no fixes). What mostly happens is they return the wrong memory amount, so nothing can allocate any memory (as you see in the error).
> 
> You will need to downgrade the whole system to Ubuntu 14 level (Trusty) in order to have the antique kernel needed for the antique driver. I forget the exact version of things but there are several (closed) posts here about it. Also [this post](https://askubuntu.com/questions/864195/what-is-the-latest-version-of-ubuntu-14-04-on-which-fglrx-for-amd-can-be-install), note the "latest 14" is poisoned with Xenial kernel and Xorg you need the old ISO to lock yourself into the old kernel/xorg versions needed by fglrx.
> 
> Currently your kernel is slightly too old for the newest driver, which works on Ubuntu 18 best. You must have Ubuntu 16 currently? But even if you got DRM3 going it would choke on Oland, without the old driver.
> 
> There is no reasonable way to get the newer Ubuntus to run the older kernel series (too many deps).

![Screenshot from 2020-06-26 17-56-28](https://user-images.githubusercontent.com/36989404/85859293-65fa2c80-b7d6-11ea-96da-04a3dfc3e2e9.png)
