### ISSUE TITLE
Mac OS X No AMD OpenCL platform found

### ISSUE THREAD

**Issue by fromcouch** [fireice-uk/xmr-stak#219]
After clone i've modified next file:

    nano xmrstak/backend/amd/amd_gpu/gpu.hpp

And add:
     `#include <string> `

for compile. I read in other issue.

Then execute And says:

> [2017-11-23 19:52:51] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
> [2017-11-23 19:52:51] : WARNING: backend AMD disabled.
> [2017-11-23 19:52:51] : WARNING on MacOS thread affinity is only advisory.

Then begins to work with CPU.
Anyone knows what i need to do to mine with GPU?

Thanks

P.D.: I Have AMD Radeon R9 M370X 2048 MB

**Comment by psychocrypt** [comment]
already fixed in the dev branch #194

**Comment by fromcouch** [comment]
@psychocrypt I've just applied #194 and is compiling fine. I'm not asking about problems compilation. I'm asking about WARNING telling that AMD platform isn't found.

If you read carefully the first post I'm saying that I did #194 to compile, and then I have this three warning: 

> [2017-11-23 19:52:51] : Start mining: MONERO
> [2017-11-23 19:52:51] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
> [2017-11-23 19:52:51] : WARNING: backend AMD disabled.
> [2017-11-23 19:52:51] : WARNING on MacOS thread affinity is only advisory.
> [2017-11-23 19:52:51] : Starting single thread, affinity: 0.

And then, xmr-stak begin work with CPU and not with GPU that is I want.
How can I begin mine with AMD?

**Comment by psychocrypt** [comment]
Sry for the fast close. The second issue should be fixed with #197

**Comment by fromcouch** [comment]
Thanks @psychocrypt  , was #197 
Works like a charm :)
