### ISSUE TITLE
affinity randomly wrong

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#22]
I tested the thread pinning under linux. Something went sometimes wrong.
Normally I use thread 0 and 1 on my laptop. To get a higher chance to trigger the bug I configuread it to 0, 3. 
Than I started the miner and looked to `htop`. In 20 -50% the second thread is going to core 1 instead of core 3.

**It looks like a race condition somewhere.**

I checked if hwloc is a problem but also without hwloc I get this behavior. 
~~I also tried to pin the thread with hwloc but with the same result.~~

**Comment by psychocrypt** [comment]
If I disable hwloc, I can't reproduce it anymore.

**Comment by fireice-uk** [comment]
What's the kernel? I have a sneaking suspicion that hwloc does not play nice with older kernels.

**Comment by psychocrypt** [comment]
`Linux fwk321 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I am not sure, it could be that there is something wrong with the guard during the initialization which should avoid that we use the wrong `oWorkThd`.
If I added a sleep of e.g. 1sec before hwloc and set affinity is called I get no wrong pinning.

Never the less I need to reproduce it somewhere else because currently I have a reproduce rate <5% because my internet stacks.
I will investigate next week a little bit time into it.

**Comment by psychocrypt** [comment]
fixed with #33

**Comment by psychocrypt** [comment]
fixed with #43 and #69
