### ISSUE TITLE
Plenteum rejected shares

### ISSUE THREAD

**Issue by gibsb** [fireice-uk/xmr-stak#2203]
stak_2.8.0. shows rejected shares when mining Plenteum, regardless of whether I use pools.txt from plenteum_stak or stak_2.8.0.

**Comment by gibsb** [comment]
rejected shares still showing. plenteum_stak shows valid shares with same configs.

**Comment by psychocrypt** [comment]
please also test to set currency in pools.txt to cryptonight_turtle

**Comment by gibsb** [comment]
Thank you for your attention. Windows OS. Mining with celeron cpu only. Using cryptonight_turtle fixed this issue. Now seeing 100% accepted shares.
