### ISSUE TITLE
Cannot compile on Visual Studio 2015

### ISSUE THREAD

**Issue by testingMonero** [fireice-uk/xmr-stak#224]
Hello, we are try for build your miner for mining laboratory using VS2015.

Latester version 2 -

Having problems compiling libwloc.lib on VS2015. On the libhwloc.dll link stage following error - 

libhwloc.lib(topology.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'
LINK : fatal error LNK1257: code generation failed

When we try link code with libhwloc.lib from version 1 -

error LNK2001: unresolved external symbol __imp_strcspn
error LNK2001: unresolved external symbol __imp__stricmp
error LNK2001: unresolved external symbol __imp_strspn
error LNK2001: unresolved external symbol __imp__stat64i32
release\xmr-stak-cpu.exe : fatal error LNK1120: 4 unresolved externals

We only have proper lisence for VS2015, please provide source code for libhwloc.lib or make compatible with VS2015. Already we try build libhwloc.lib from scratch but appears you have changed code from original libhwloc-master. Thanks you.

**Comment by psychocrypt** [comment]
please post the link where you downloaded hwlink from.
Which cuda do you use?

**Comment by testingMonero** [comment]
We download hwloc.lib from this github website - https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip for 1 version and this weblink for 2 version - https://github.com/fireice-uk/xmr-stak-dep/releases/download/v2/xmr-stak-dep.zip

Problem appear be that libhwloc.lib comiled with setting that conflict with visual studio 2015. can you please post source code to libhwloc.lib or recompile in visual studio 2015? We see you make modification from original libhwloc-5.dll source code. thanks you.

**Comment by testingMonero** [comment]
we no use cuda this for mining cpu verison only

**Comment by psychocrypt** [comment]
please compile with visual studio 2017 this will solve the issue.

**Comment by testingMonero** [comment]
our lisence no have visual studio. can you provide source code for libhwloc.lib or this close source project? you make modification to original libhwloc-5.dll.

**Comment by psychocrypt** [comment]
bisual studio 2017 is free.
You found all source linked under https://github.com/fireice-uk/xmr-stak-dep

**Comment by testingMonero** [comment]
you have make modification to original libhwloc-5.dll which can find here - https://github.com/open-mpi/hwloc

You are exporting different function 

there is no source for libhwloc only header file and static library

can you please publish this modification or link for source code? or this is close sourced project? thanks you.

**Comment by psychocrypt** [comment]
As I know @fireice_uk did no changes to the code else he would puplish it.
@fireice_uk could you please confirm it.

**Comment by testingMonero** [comment]
there have changes because original libhwloc-5.dll is not static and libhwloc.lib from xmr-stak and libhwloc-5.dll/lib have different function export. can makes donation if solve. thanks you.

**Comment by psychocrypt** [comment]
It could be that the dependencies contain hwloc 2.X.

**Comment by bmatthewshea** [comment]
Same problem.

```
LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\xmr-stak\build\xmr-stak.vcxproj]
LINK : fatal error LNK1257: code generation failed [C:\xmr-stak\build\xmr-stak.vcxproj]
```
I am also using VS2015.

As a matter of fact the `appveyor.yml` build file **also uses VS2015**.
The docs also mention to use VS2015. They also mention using VS2017.
Cleaning up your compile and docs would go a long way to resolving all your compile 'issues'.

1. Is there some reason the docs switched to VS2017? VS2015 is fine and should be more than adequate if you simply fix your linking.

2. Why are you putting up a zip of dependencies? You need to give links to official source/binaries not pre-compiled binaries from who knows where.

3. You also need to have appveyor compile this and give us the build link. I have a feeling it will not pass.
https://github.com/fireice-uk/xmr-stak/blob/master/.appveyor.yml

thank you.

**Comment by JollyMort** [comment]
@bmatthewshea another user seems to have resolved the same problem - maybe it can be of use to you: https://github.com/fireice-uk/xmr-stak/issues/211

**Comment by bmatthewshea** [comment]
Just saw - but I got it built - thanks for link tho @JollyMort
