### ISSUE TITLE
Dev Question: New Algo Implementation

### ISSUE THREAD

**Issue by davehlong** [fireice-uk/xmr-stak#2252]
Hi Guys, hoping someone can point me in the right direction. 

I am attempting to implement a new algo, described here: https://medium.com/@turtlecoin/introducing-cryptonight-soft-shell-2c2d4c497efd

The premise of this algo is that the scratchpad and iterations will change for each new block based on set parameters, within a defined window of blocks. So, this is a "derived" algo as per some of the other implementations, but it will change the scratchpad, iterations and mask for each new miner job (new height).
The issue I'm facing is that I cannot seem to get xmr-stak to produce the correct hashes consistently. It seems to only work for every 64 hashes (from what I've been able to gather to date)

My self test implementation can be seen here:
https://github.com/plenteum/ple-stak/commit/96533208824b4a227eea12e5c2ed5258e992d7e1#diff-dcb588b7465f85cba435cdcd930ed1e3R430

Test 1 (for height 0) works and produces the correct hash, Test 2 (height 65476) however fails.

I'm sure I'm missing something somewhere, but would really appreciate if someone could give me a nudge in the correct direction?

Many thanks, 
Dave

**Comment by davehlong** [comment]
Just some additional information related to this from testing.. 

As a first step, I tried to loop through a huge range of masks, to see if there was a specific mask that would produce the correct hash, but, this did not work. 

So, based on that, I am now thinking that something in the actual hashing function is not consistent with the standard implementation. Ultimately, I "think" this is likely to be related to a division result of one of the paramters (scratchpad, iterations or mask) or a derivative thereof, that is not divisible by 64 and ultimately is causing a different value to be propagated through the rest of the hash funtion. 

I am trying to step through this to see if I can identify where this difference might be occuring, but, as you probably know there's alot to check, so if anyone has any pointers of the "likely" or even "possible" candidates I'd be most grateful.

(ps. I could also be barkling up the wrong tree entirely as I still have alot to learn about the intricacies of the hash function itself)

**Comment by davehlong** [comment]
Ok, so, some additional findings on this... 

I've worked out that if I make the MEMORY for each height divisible by 64 AND ensure that the MEMORY % 2 == 0 (ie: the result of a divisiion by 64 is an even number) then xmr-stak produces the same hashes as the core algo.

I have not changed anything in the actual hash function implementation as I did not want to mess around and potentially break optimisations. 

Doing this this way `(static_cast<unint64_t>(mem/64)*64) AND ((mem % 2 != 0 ? mem -= 64 : mem)` allows for a steady progression and regression of the memory and iterations on each new height, whilst producing the correct hashes.

**Comment by Spudz76** [comment]
You may have hit some alignment limitation with how work is tiled in memory for parallelism or easier math.

**Comment by davehlong** [comment]
> You may have hit some alignment limitation with how work is tiled in memory for parallelism or easier math.

Yes, I figured it was likely something to do with optimisations in the actual hash function. I don't know enough yet about the actual hash function implementation to fiddle around to much in that, and I didn't want to break it, or slow it down so, for me anyway, this is a good balance as I still get the steady progression/regression of the algo itself, without breaking anything that much smarter people than me have done :-)
