### ISSUE TITLE
Invalid Shares with AMD 19.2.2

### ISSUE THREAD

**Issue by MohitYadavGitHub** [fireice-uk/xmr-stak#2257]
Same settings for xmr-stak gives invalid shares with Vega 64 on 19.2.2 and works completely fine with 18.5.2 . Cant really say its a xmr-stak issue, but maybe useful for people.

Also got a vega vii which has invalid shares with 19.2.2 (about 80% valid). I guess with vega vii dont have the option to go back to 18.5.2

**Comment by psychocrypt** [comment]
please run `xmr-stak -V` and post the version here

**Comment by MohitYadavGitHub** [comment]
![image](https://user-images.githubusercontent.com/31392206/53285935-8db32d80-3767-11e9-9d20-6eae363c0612.png)

**Comment by MohitYadavGitHub** [comment]
sorry had closed by mistake.

**Comment by psychocrypt** [comment]
mhh other user reported that 19.X and 2.8.3 is working together. if not you
must downgrade the driver :-(

MohitYadavGitHub <notifications@github.com> schrieb am Sa., 23. Feb. 2019,
12:36:

**Comment by MohitYadavGitHub** [comment]
downgrade works yep for vega 64 (18.5.2 is absolutely fine). Not sure its an option for vega vii since its just launched. maybe will give it a try in the next days. Will post the results here.

**Comment by MohitYadavGitHub** [comment]
just tried 19.2.3 . same issue. Didnt get time to try 18.x.x

**Comment by Spudz76** [comment]
Generally once a mining-specific function stops working, future drivers never fix it again. Client code must follow whatever AMD Software Departments latest idea is, without them really telling anyone.

After 19.2.1 they changed out the PCI driver maybe that broke things.
Nearly impossible to figure out which driver is the oldest one with Vega20 chip support.

AMD is also horrible at any sort of historical documentation, it's like earlier software was an embarrassment to be forgotten (probably, because it is haha)

**Comment by heavyarms2112** [comment]
v8 was working fine on Vegas and Adrenalin 19.2.x and above drivers with xmr-stak 2.8.2 and #2241 fix.   It broke again with 2.8.3+ versin.

**Comment by Spudz76** [comment]
Try the 2.10.0 release please

**Comment by heavyarms2112** [comment]
@Spudz76  i mentioned 2.8.3+ version.  so it's broken for above versions.  I already tried 2.10

**Comment by MohitYadavGitHub** [comment]
couldnt make the old drivers work with vega vii...  With the latest 19.3.1 drivers ,still get a lot of invalid shares
 
![image](https://user-images.githubusercontent.com/31392206/54053197-d0a0e680-41e6-11e9-8a29-4bf4bb0d0853.png)

**Comment by MohitYadavGitHub** [comment]
One Side question , Does any one know how to use more than 8 gb of memory on Vega VIi while mining?

**Comment by psychocrypt** [comment]
which pool do you use? The strange thing is that other user report that all
works fine. Could you please test tomorrow after the fork if maybe
cryptonight_r is solving the issue.

**Comment by MohitYadavGitHub** [comment]
Supportxmr . Will try and let you know

**Comment by heavyarms2112** [comment]
@psychocrypt i haven't had success mining with 2.8.3+ version for any of the Vegas.  Personally I know at least 5 folks who haven't had success.  Which users are reporting it's working for them?
Many switched back to 18.6.1 drivers or so.  Vega VII works only on Adrenalin and above so that option is not available.

**Comment by psychocrypt** [comment]
Chris in the Ryo channel reported numbers for vii and vega and tested my
fixes.

**Comment by MohitYadavGitHub** [comment]
> @MohitYadavGitHub FYR 2.8.2 with #2241 fix works fine for v8 on VII

Thanks :) . But i guess its not going to be useful after tomorrows fork.

**Comment by heavyarms2112** [comment]
> Chris in the Ryo channel reported numbers for vii and vega and tested my fixes.

one user?  What about the feedback from multiple here that it's producing invalids.

**Comment by Spudz76** [comment]
You can't possibly use all that memory, but to use more of it choose the largest scratchpad coins you can (CN-Heavy based, 4MB per block)

You will always run out of processor and memory bandwidth well before you fill more than ~3GB with cryptonights

If you need to use memory then go Ethereum, it's designed to waste memory instead of processor and width.

**Comment by psychocrypt** [comment]
Yes one user. It is not that I not thrust you that it is not working the
problem is that I have not access to a windoes system and with chris I had
a fast channel to communicate and we did many iterations until wie solved
the issue.

Could you try if you get valid shares with xmrig-amd. If so we can start to
spott differences.
Are you able to compile the code by our own?

**Comment by MohitYadavGitHub** [comment]
![image](https://user-images.githubusercontent.com/31392206/54071722-202bf480-4271-11e9-99d2-493041efdffc.png)


All accepted ! so problem is unfortunately with xmr-stak :(

**Comment by psychocrypt** [comment]
ok thanks for the test I will provide a few test changes to you soon. Do
you have also the issue with cryptonight_r?

**Comment by heavyarms2112** [comment]
@psychocrypt yes i can compile stak.  I have tried xmrig and it works fine.

**Comment by psychocrypt** [comment]
Hi could you please test https://github.com/psychocrypt/xmr-stak/archive/windowsBug1.zip if it solves the invalid shares.

**Comment by heavyarms2112** [comment]
@psychocrypt will test and report.

**Comment by MohitYadavGitHub** [comment]
Yes confirm that the issue seems to be fixed. Great !

**Comment by psychocrypt** [comment]
I will send you a second test because I removed something which should not be removed for linux. So I need you for a second test

**Comment by psychocrypt** [comment]
please test https://github.com/psychocrypt/xmr-stak/archive/fix-vegaWindowsAMDInvalid.zip for a last test

**Comment by heavyarms2112** [comment]
tested the above pvt build.  works fine.

**Comment by WhiskeyBlocks** [comment]
I'm having the same issue with my Vega 56's. Any idea when the fix will be added to the full release?

**Comment by psychocrypt** [comment]
I think in 2 to 3 days. I like also to fix a few other issues. Maybe I will
provide a beta version before.
