### ISSUE TITLE
Incorrectly identified as not having AES support, likely effecting performance

### ISSUE THREAD

**Issue by Eddie2312** [fireice-uk/xmr-stak#2259]
i5 8400 cpu mining on windows 10 64

I'm getting a notification that it doesn't support hardware AES when it certainly does.

Using xmrstak 2.8.2

**Comment by psychocrypt** [comment]
there is an option in config.txt to force enable aes.

**Comment by Eddie2312** [comment]
> there is an option in config.txt to force enable aes.

When I force aes it crashes the miner

**Comment by psychocrypt** [comment]
do you run it on a native system or in a VM (virtual environment)?

**Comment by Spudz76** [comment]
What does CPU-Z say about it?  Please either save report as txt, C&P here, or screenshot the main tab (showing features, steppings, etc)

Does it show AES (like mine)?
![image](https://user-images.githubusercontent.com/2391234/53292140-6bc3a600-377b-11e9-8715-0d3ac61b8c52.png)

**Comment by Eddie2312** [comment]
> do you run it on a native system or in a VM (virtual environment)?

Native system

**Comment by Spudz76** [comment]
It can be disabled in software (such as by the BIOS or other bootloader step) so I would check for BIOS updates and then hunt the CPU Options in there for anything that might tweak the CPU features.

Similar to how HT can be disabled in BIOS, its the same configuration register.  If BIOS is buggy/stupid it might nuke the AES feature before OS even boots.

What motherboard (or post Mainboard tab of CPU-Z)

**Comment by Eddie2312** [comment]
> What does CPU-Z say about it? Please either save report as txt, C&P here, or screenshot the main tab (showing features, steppings, etc)
> 
> Does it show AES (like mine)?
> ![image](https://user-images.githubusercontent.com/2391234/53292140-6bc3a600-377b-11e9-8715-0d3ac61b8c52.png)

![sdokifsdoikj](https://user-images.githubusercontent.com/25727760/53292386-42a91280-3787-11e9-9299-8e46e1a80bec.PNG)

I have no idea why it doesn't show AES. Ark says it should

**Comment by psychocrypt** [comment]
please check if there is an option in bios available.

**Comment by Eddie2312** [comment]
![dgdrfgsedffse](https://user-images.githubusercontent.com/25727760/53292408-ccf17680-3787-11e9-837d-2355145f77f5.PNG)

**Comment by Eddie2312** [comment]
I was able to fix in the bios. Thanks guys and thanks Spudz.

I recently had to reset bios settings because of a network issue which might have caused it.

Went from 140 to 170 h/s
