### ISSUE TITLE
Please add new custom algorithm CryptoNight Heavy X 

### ISSUE THREAD

**Issue by AnimusXCASH** [fireice-uk/xmr-stak#2263]
Greetings,
I am from X-Cash team. I would like to kindly ask you if you can add our new custom algorithm to your mining software.
Proof Of Work algorithm was changed from Cryptonight V8 to modified Cryptonight HeavyX, to try to prevent ASICs and or FPGAs from mining on the network. This means as well that we are now nicehash resistant.

Daemon: https://github.com/X-CASH-official/X-CASH/releases/tag/1.5.0

You can reach us through the Discord community if any further information required:
https://discord.gg/sr5G3ch

Thank you for your time.
brg

Lovro
Marketing and Community Manager
X-Cash Team

**Comment by Spudz76** [comment]
Would suggest not using keyword "Heavy" unless also 4MB scratchpad size (that is what most would consider what "Heavy" means with CN algos) it would only lead to more confusion.

2MB scratchpads are not Lite (1MB) nor Heavy (4MB)

If you double the work maybe try "Hard2X" or something

**Comment by AnimusXCASH** [comment]
thank you for suggestion

**Comment by psychocrypt** [comment]
What are the changes of x-cash pow against v8 or native cryptonight.
Please provide a pool address and a wallet address which I can use for testing.

**Comment by psychocrypt** [comment]
added in #2316
