### ISSUE TITLE
Update your Mining Software before 2019-03-09 to get ready for the upcoming protocol upgrade. If you neglect to update to a CNv4 (aka CryptonightR) capable mining software and/or proxy, you will no longer be able to mine after block 1788000.

### ISSUE THREAD

**Issue by xl-tech** [fireice-uk/xmr-stak#2265]
Update your Mining Software before 2019-03-09 to get ready for the upcoming protocol upgrade. If you neglect to update to a CNv4 (aka CryptonightR) capable mining software and/or proxy, you will no longer be able to mine after block 1788000. - Got this message from pool, do xmr-stak updated protocols already? Or we need to wait for new release?

**Comment by psychocrypt** [comment]
rhe release should be ready on sunday
