### ISSUE TITLE
./xmr-stak.sh: line 3: /stak/ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by botoxparty** [fireice-uk/xmr-stak#227]
hey,

trying to run the xmr-stak combined on an os X system and this is what i'm getting when i try and execute the miner...

```
Adams-iMac-3:xmr-stak-portbin-linux Adam$ ./xmr-stak.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./xmr-stak.sh: line 3: /stak/ld-linux-x86-64.so.2: No such file or directory
```

of course i have checked that the file is there and it does exist :S

**Comment by psychocrypt** [comment]
The poetable bin is for linux only. MacOSX is not supported.
Please compile the miner by hand. Please use the dev branch because there
are a few fixes for macOSX included.

**Comment by botoxparty** [comment]
Where's the dev branch?
I'm trying to compile the miner by hand however it's not detecting that I have CUDA installed.

`Adams-iMac-3:xmr-stak-master Adam$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:203 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support


-- Configuring incomplete, errors occurred!
See also "/Users/Adam/Downloads/xmr-stak-master/CMakeFiles/CMakeOutput.log".
`

**Comment by psychocrypt** [comment]
Dev branch: https://github.com/fireice-uk/xmr-stak/tree/dev
download dev branch: https://github.com/fireice-uk/xmr-stak/archive/dev.zip
