### ISSUE TITLE
Bug in 2.9.0

### ISSUE THREAD

**Issue by jagerman** [fireice-uk/xmr-stak#2276]
The `!=` on this line is definitely wrong (should probably be `==`?):

https://github.com/fireice-uk/xmr-stak/blob/61e997c3474734590e3f3788de9e8c125eebdeeb/xmrstak/backend/cpu/crypto/cryptonight_aesni.h#L801

**Comment by psychocrypt** [comment]
Well spotted! I will fix it today!

**Comment by psychocrypt** [comment]
fixed with #2280
