### ISSUE TITLE
XMR-stak compiled under FreeBSD 11.1 throws "hwloc: set_thisthread_membind not supported"

### ISSUE THREAD

**Issue by kulmosen** [fireice-uk/xmr-stak#228]
Compiled the xmr-stak with the following commands

cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF

make install gives me this result:

`

> Scanning dependencies of target xmr-stak-c
> [  4%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
> [  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
> [ 12%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
> [ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
> [ 20%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
> [ 24%] Linking C static library bin/libxmr-stak-c.a
> [ 24%] Built target xmr-stak-c
> Scanning dependencies of target xmr-stak-backend
> [ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
> /root/xmr-stak/xmrstak/jconf.cpp:161:1: warning: control may reach end of non-void function [-Wreturn-type]
> }
> ^
> 1 warning generated.
> [ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
> [ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
> [ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
> [ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
> [ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
> [ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
> [ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
> [ 60%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
> [ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
> [ 68%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
> [ 72%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
> [ 76%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
> [ 80%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
> [ 84%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
> [ 88%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
> [ 92%] Linking CXX static library bin/libxmr-stak-backend.a
> [ 92%] Built target xmr-stak-backend
> Scanning dependencies of target xmr-stak
> [ 96%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
> [100%] Linking CXX executable bin/xmr-stak
> [100%] Built target xmr-stak
> Install the project...
> -- Install configuration: "Release"

`

When running the binary it goes through the setup and then tries to run giving me this error message:

`

> xmr-stak 2.0.0 79154f7
> 
> Brought to you by fireice_uk and psychocrypt under GPLv3.
> Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
> 
> Configurable dev donation level is set to 2.0%
> 
> You can use following keys to display reports:
> 'h' - hashrate
> 'r' - results
> 'c' - connection
> -------------------------------------------------------------------
> [2017-11-24 13:25:33] : Start mining: MONERO
> [2017-11-24 13:25:33] : Starting single thread, affinity: 0.
> [2017-11-24 13:25:33] : hwloc: set_thisthread_membind not supported
> [2017-11-24 13:25:33] : Starting single thread, affinity: 2.
> [2017-11-24 13:25:33] : hwloc: set_thisthread_membind not supported
> [2017-11-24 13:25:33] : Starting single thread, affinity: 4.
> [2017-11-24 13:25:33] : hwloc: set_thisthread_membind not supported
> Bus error (core dumped)

`

The system is:

FreeBSD KulmosenBSD 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by lisergey** [comment]
same on my 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

after launch and questions to make config.file

[2017-11-24 16:17:45] : Start mining: MONERO
[2017-11-24 16:17:45] : CPU configuration stored in file 'cpu.txt'
[2017-11-24 16:17:45] : Starting double thread, affinity: 0.
[2017-11-24 16:17:45] : hwloc: set_thisthread_membind not supported
[2017-11-24 16:17:45] : Starting single thread, affinity: 1.
[2017-11-24 16:17:45] : MEMORY ALLOC FAILED: mlock failed
and core dumped

**Comment by lisergey** [comment]
but on the same machine works
xmr-stak-cpu 1.3.0-1.5.0 mining software, CPU Version.

**Comment by blacklion** [comment]
This is not a problem of absent `set_thisthread_membind` — which is really not supported bu FreeBSD — problem is here (fixed on dev): #177

**Comment by agentpatience** [comment]
Hello, can you please clarify on the fix for this?
[2018-02-10 19:18:19] : hwloc: set_thisthread_membind not supported

**Comment by blacklion** [comment]
@agentpatience It can not be fixed because FreeBSD 11 doesn't support memory binding.

**Comment by agentpatience** [comment]
Hi Lev!

Is there any version that does? What is the best OS to use?

 

Sent: Saturday, February 10, 2018 at 7:24 PM

**Comment by blacklion** [comment]
@agentpatience FreeBSD 12 WILL support it in month or two. But it is almost irrelevant, according to my measurements difference in speed is negligible.

**Comment by agentpatience** [comment]
Thanks guys, I see that there is a development release for version 12, is there any harm in trying to download it and installing xmr-stak or will there be dependency issues?

**Comment by lisergey** [comment]
@agentpatience, you'll most probably succeed in compile it, but then launch and get complaint about unable to bind memory.
I've had several versions to run with option 

"use_slow_memory" : "no_mlck",

my FreeBSD 11.1-RELEASE-p4, root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

until xmr-stak is FreeBSD friendly you might find it useful /usr/ports/net-p2p/xmrig

**Comment by lisergey** [comment]
@agentpatience, I have a binary compiled with 5x factor (xmr-stak 2.0.0 359e732), running well.
I can upload it if you'd interested.

**Comment by blacklion** [comment]
@lisergey: mlock is not a problem if you have root. You should enable it for users (sysctl security.bsd.unprivileged_mlock=1) and increase limit (sysctl vm.max_wired=67108864) and mlock will work after that.

@agentpatience: It is not committed to FreeBSD yet, patches are under review now. And API will be different to Linux one, so AFTER it will be committed to FreeBSD hwloc library must be updated to support new API too.

**Comment by lisergey** [comment]
@blacklion I've run it under non-root.
mine are security.bsd.unprivileged_mlock: 1 and vm.max_wired: 486172[2018-02-15 15:48:59] : 

it just complained:
hwloc: set_thisthread_membind not supported

and continued to run after.

Pls, update us when release would be fully FreeBSD-friendly :)

**Comment by blacklion** [comment]
@lisergey: yes, binding memory to threads is not (yet) supported on FreeBSD side. But I repeat: binding memory to threads gives almost non-noticeable speedup, you could mine without.

**Comment by agentpatience** [comment]
I get such crappy rates with FreeBSD 12 and xmr-stak:
[2018-03-31 02:47:57] : Starting 1x thread, affinity: 47.
[2018-03-31 02:47:57] : hwloc: set_thisthread_membind not supported

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |    3.0 |    3.0 |   (na) |  1 |   38.9 |   38.9 |   (na) |
|  2 |   29.5 |   29.5 |   (na) |  3 |   29.8 |   29.8 |   (na) |
|  4 |   38.7 |   38.8 |   (na) |  5 |    3.2 |    3.2 |   (na) |
|  6 |   39.8 |   39.8 |   (na) |  7 |   (na) |    2.0 |   (na) |
|  8 |    2.1 |    2.1 |   (na) |  9 |    2.1 |    2.1 |   (na) |
| 10 |   (na) |    2.0 |   (na) | 11 |    2.1 |    2.2 |   (na) |
| 12 |    2.8 |    2.8 |   (na) | 13 |    2.8 |    2.8 |   (na) |
| 14 |    2.8 |    2.8 |   (na) | 15 |    2.9 |    2.9 |   (na) |
| 16 |    2.8 |    2.8 |   (na) | 17 |    2.8 |    2.8 |   (na) |
| 18 |   (na) |    2.0 |   (na) | 19 |   (na) |    2.0 |   (na) |
| 20 |   (na) |    2.0 |   (na) | 21 |   (na) |    2.0 |   (na) |
| 22 |   (na) |    2.1 |   (na) | 23 |   (na) |    2.1 |   (na) |
| 24 |    4.1 |    4.1 |   (na) | 25 |    3.8 |    3.8 |   (na) |
| 26 |    3.8 |    3.8 |   (na) | 27 |    3.9 |    3.9 |   (na) |
| 28 |    4.0 |    4.0 |   (na) | 29 |    4.1 |    4.0 |   (na) |
| 30 |    2.4 |    2.4 |   (na) | 31 |   (na) |    2.4 |   (na) |
| 32 |   (na) |    2.4 |   (na) | 33 |    2.4 |    2.4 |   (na) |
| 34 |   (na) |    2.4 |   (na) | 35 |    2.3 |    2.3 |   (na) |
| 36 |   (na) |    1.7 |   (na) | 37 |   (na) |    1.7 |   (na) |
| 38 |   (na) |    1.7 |   (na) | 39 |   (na) |    1.7 |   (na) |
| 40 |   (na) |    1.7 |   (na) | 41 |   (na) |    1.7 |   (na) |
| 42 |   (na) |    1.5 |   (na) | 43 |   (na) |    1.5 |   (na) |
| 44 |   (na) |    1.6 |   (na) | 45 |   (na) |    1.6 |   (na) |
| 46 |   (na) |    1.6 |   (na) | 47 |   (na) |    1.6 |   (na) |
Totals (CPU):   237.0  280.2    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    237.0  280.2    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------
