### ISSUE TITLE
Not Generating a xmr-stak.exe file

### ISSUE THREAD

**Issue by nikrox2** [fireice-uk/xmr-stak#229]
I have tried (repeatedly) to build xmr-stak on windows. (I have an Intel cpu and an Nvidia GTX 1060)
Instead of making the xmr-stak.exe file, it just makes the xmr-stak-cpu file, every time.
I don't know what to do. Can someone help?
Thanks
Nikila

**Comment by MilosMosovsky** [comment]
Please post you steps, I successfully compiled yesterday. Are you looking to good dir? its in ` build/Release/bin` dir

**Comment by psychocrypt** [comment]
please also check you anti virus software. even if you compile it the virus
protection is removing the miner

**Comment by nikrox2** [comment]
I followed the steps on compile_Windows.md , and I did disable my antivirus. I created a new folder for this, which is why I find it weird that the cpu.exe is generated.

**Comment by psychocrypt** [comment]
cpu.exe? there should be a xmr-stak.exe

**Comment by nikrox2** [comment]
Sorry, by cpu.exe I meant xmr-stak-cpu.exe .

**Comment by psychocrypt** [comment]
Please tey it again in an empty foldet and post all commands and the full
output.

**Comment by tmairegasnighto** [comment]
I get from both the dev branch and the latest release branch...

LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20130802' [C:\xmr-stak-dev\buil
d\xmr-stak.vcxproj]
LINK : fatal error LNK1257: code generation failed [C:\xmr-stak-dev\build\xmr-stak.vcxproj]

**Comment by nikrox2** [comment]
Can you post the link for the releases page? When I click the releases link on front page, it only allows me to download files from the 20th of July and earlier.

**Comment by nikrox2** [comment]
Ok, I found the error. When I click releases on the start page, it sends me to the xmr-stak-cpu file download, whereas if I use the reddit announcement link, I get the unified miner.
