### ISSUE TITLE
Issue while compiling on manjaro linux, -DCUDA_HOST_COMPILER flag not working.

### ISSUE THREAD

**Issue by Fitzerrick** [fireice-uk/xmr-stak#2302]
So my Cuda version is 10
My video drivers version is 415.27 although I don't think that matters for this issue.
My gnu compiler is version 8.2.1
I have gcc-5 installed as it was required to compile past versions of this miner.

However when I follow instructions and use the -DCUDA_HOST_COMPILER flag the program complains that my gcc version is not supported. In the past this worked just fine, I have no idea what could be different now. Full terminal output follows:

[michael@rexxy-the-sexxy-2point0 ~]$ git clone https://github.com/fireice-uk/xmr-stak.git
Cloning into 'xmr-stak'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 7319 (delta 18), reused 40 (delta 18), pack-reused 7279
Receiving objects: 100% (7319/7319), 2.31 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (5283/5283), done.
[michael@rexxy-the-sexxy-2point0 ~]$ mkdir xmr-stak/build
[michael@rexxy-the-sexxy-2point0 ~]$ cd xmr-stak/build
[michael@rexxy-the-sexxy-2point0 build]$ cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 ..
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "10.0", minimum required is "7.5") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "2.2") 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1a")  
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/michael/xmr-stak/build
[michael@rexxy-the-sexxy-2point0 build]$ make install
Scanning dependencies of target xmr-stak-asm
[  2%] Building ASM object CMakeFiles/xmr-stak-asm.dir/xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S.o
[  4%] Building ASM object CMakeFiles/xmr-stak-asm.dir/xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S.o
[  6%] Linking C static library bin/libxmr-stak-asm.a
[  6%] Built target xmr-stak-asm
Scanning dependencies of target xmr-stak-c
[  9%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 15%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 18%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 22%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 25%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/cpuType.cpp.o
[ 27%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp.o
[ 29%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cn_gpu_avx.cpp.o
[ 31%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cn_gpu_ssse3.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 36%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 40%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 43%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 45%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 47%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 54%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 59%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/uac.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 63%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 65%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 70%] Linking CXX static library bin/libxmr-stak-backend.a
[ 70%] Built target xmr-stak-backend
[ 72%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
In file included from /opt/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/opt/cuda/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
 #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  ^~~~~
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
  /home/michael/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:72: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[michael@rexxy-the-sexxy-2point0 build]$

Any hint how to get this to pay attention to the compiler flag would be appreciated...I've tried looking through the build files to see if I could manually change it but it didn't seem to help, plus there's a lot of them so I don't really know which file is the key one to look through, kinda just gave up on that, also tried changing it using ccmake .. but that didn't seem to work either. /sigh sorry, my understanding of how the build files and compilers work is pretty limited. Any help would be amazing. Please and thanks.

**Comment by psychocrypt** [comment]
I changed that always the compier which is used for the rest of the code is
used for nvidia.
- remove the build folder
- export CC=gcc-5
- export CXX=g++-5
- cmake ..

if the name gcc-5 is wrong change it to the name of the gcc compiler.
By setting CC and CXX you say cmake which compiler you like to use.

**Comment by Fitzerrick** [comment]
Haha, yes this worked perfectly. I figured there was some simple solution I was just too ignorant to know about. Many thanks, psychocrypt. Your tip will be incoming once I get my node and everything updated ;). Thanks again.

**Comment by Spudz76** [comment]
Should also work natively with gcc-8 system compiler if you upgrade to CUDA 10.1 Toolkit, then you can dump gcc-5 completely and all the workarounds.  Also will achieve ideal `[10.1/10.1]` detection vs you probably have `[10.1/10.0]` now... not sure which CUDA the 415.27 driver comes with.
