### ISSUE TITLE
Cryptonight_r raising Illegal instructions

### ISSUE THREAD

**Issue by Garito** [fireice-uk/xmr-stak#2303]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU: Intel i3 @ 2.93GHz
  - Type of the GPU (if you try to miner with the GPU): GeForce GTX 1060 6GB

# Compile issues
  - Which OS do you use? Ubuntu 18.04
  NO

# Issue with the execution
  - Do you compiled the miner by our own?
  YES
  run `./xmr-stak --version-long` and add the output here
  xmr-stak/2.10.0/56d2770/master/lin/nvidia-cpu/0

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

When trying to use cryptonight_r it raises Illegal instruction core dumped after "enable cryptonight_r asm 'off' cpu's"
I've try specifing cryptonight_r instead of monero with the same result and if I try cryptonight_v8 it works but raises the timeout with the pool that was happening before the fork

Any help, please?
Thanks

**Comment by psychocrypt** [comment]
please change in config.txt the option aes to off.

**Comment by psychocrypt** [comment]
see #2297 for more details

**Comment by Garito** [comment]
Thanks, it worked
