### ISSUE TITLE
CPU low power mode has no effect on Cryptonight R

### ISSUE THREAD

**Issue by cotinco** [fireice-uk/xmr-stak#2305]
Seems that Cryptonight R CPU low power mode does not increase performance at all (for V8 it still works as before). Is it the nature of the algorithm or it's just not implemented yet?
Version 2.10.

**Comment by psychocrypt** [comment]
It is implemented but I need to activate another optimization I skipped due
to the short time for development.

**Comment by psychocrypt** [comment]
solved with https://github.com/fireice-uk/xmr-stak/pull/2309
