### ISSUE TITLE
Cuda error at startup and aplication close.

### ISSUE THREAD

**Issue by noebranco** [fireice-uk/xmr-stak#2320]
Hello,
After upgrading to version 2.10 I get this error on two PC's:
![XMR-STAK](https://user-images.githubusercontent.com/48280825/54115126-6ac98000-43db-11e9-8073-aa282457eb8e.jpg)
After I click "OK" 2 times, XMR-STAK closes.
With version 2.9 no problems. Any ideia?
Thanks in advance.
Regards.

**Comment by Spudz76** [comment]
Check antivirus?  Probably blocking.

**Comment by noebranco** [comment]
Thanks for the input, but not AV.
The folder and files are excluded in AV and firewall.
Even if I turn all of them off, still get the error.

**Comment by Spudz76** [comment]
Then, it may not be finding the sub-dependency DLLs - You need:
`cudart64_100.dll`
`nvrtc64_100_0.dll`
`nvrtc-builtins64_100.dll`

Either installed to system (CUDA 10.0 Toolkit -> Runtime section only) or copied into run folder with exe.

**Comment by noebranco** [comment]
On one of the PC's after installing the Runtime, I didn't get the error but XMR-STAK stopped and the window closed after a few seconds. On the other PC's all the same.
Created a simples batch file and tried to start XMR-STAK with "--noNVIDIA" and "--noAMD" and I get no errors on both machines but XMR_STAK still closes after a fez seconds.
I'm going to format both os them and reinstall W10 and try from scratch, might be some probem in Windows.
Will let you know.
👍

**Comment by noebranco** [comment]
With version 2.10.1 and using "--noAMD" and "--noNVIDIA" all is working fine now and XMR-STAK doesn't close anymore.
👍
