### ISSUE TITLE
old nvidia GTX 550ti stops working

### ISSUE THREAD

**Issue by rassware** [fireice-uk/xmr-stak#2322]
The miner works with this setup fine until 2.9.
Compilation works fine. I have CUDA version 8 installed.

# Basic information
  - Type of the CPU: AMD AthlonX2 (old one)
  - Type of the GPU: nvidia GTX 550ti 4GB

# Issue with the execution
  - Do you compiled the miner by our own? Yes
  ```
  export CXX=/usr/bin/g++-5
  cmake .. -DOpenCL_ENABLE=OFF
  make install
  ```
 After launch the miner gets errors and shutdown:
  ```
 [2019-03-11 13:15:52] : Mining coin: cryptonight_r
[2019-03-11 13:15:52] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda10_0.so: cannot open shared object file: No such file or directory
[2019-03-11 13:15:52] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend_cuda9_2.so: cannot open shared object file: No such file or directory
[2019-03-11 13:15:52] : NVIDIA: try to load library 'xmrstak_cuda_backend'
NVIDIA: found 1 potential device's
[2019-03-11 13:15:53] : Starting NVIDIA GPU thread 0, no affinity.
CUDA [9.1/8.0] GPU#0, device architecture 21: "GeForce GTX 550 Ti"... device init succeeded
[2019-03-11 13:15:53] : NVIDIA: use library 'xmrstak_cuda_backend'
[2019-03-11 13:15:53] : WARNING: backend CPU disabled.
[2019-03-11 13:15:53] : Fast-connecting to XXXXXXXXXXXXX pool ...
[2019-03-11 13:15:53] : Pool XXXXXXXXXXXXX  connected. Logging in...
[2019-03-11 13:15:53] : Difficulty changed. Now: 5000.
[2019-03-11 13:15:53] : Pool logged in.
[2019-03-11 13:15:53] : nvrtcCompileProgram failed: NVRTC_ERROR unknown
[2019-03-11 13:15:53] : Program compile log: nvrtc: error: failed to load builtins
[CUDA] Error gpu 0: <cryptonight_core_cpu_hash>:1040 "device kernel image is invalid"
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: device kernel image is invalid
Abgebrochen (Speicherabzug geschrieben)
  ```

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by bycarloz** [comment]
I'm using cuda 8 and I compiled the miner 2.10.0 to cuda 8 and I'm extracting, monero in graphics gtx 460 ti, gtx 570 ti, gtx 750 ti Driver: 391.35. although I am going to degrade the controllers to 372.70 or 388.71 to see if the hashrate goes up a bit more, since in the miner xmr-stak 2.6.0 I had more hashrate and I used the drivers 391.35 but the recommended thing is to have to cuda 8 one of this two driver installed 372.70 or 388.71

**Comment by Spudz76** [comment]
Go to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\`
Copy `cudart64_80.dll` and `nvrtc64_80.dll` and `nvrtc-builtins64_80.dll` into wherever `xmr-stak.exe` is located.

Or install CUDA 8 Toolkit on the mining rig just the runtime section (more specifically the CUDART and NVRTC parts) but it's way easier to just copy the DLLs around.

**Comment by rassware** [comment]
Thanks @Spudz76 for your help. My system is an Ubuntu 18.04 by the way. I had a wrong path to the cuda library in my `.profile` in my home dir.

Correct path in my `.profile` (`/usr/local/cuda` is a symlink to `/usr/local/cuda-8.0`):
`LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"`

Thanks!

**Comment by Spudz76** [comment]
Ah, yes.  I have not used the new version on CUDA-Linux yet but same issue different fixes.
