### ISSUE TITLE
2% Hash Donation Option

### ISSUE THREAD

**Issue by Larceniii** [fireice-uk/xmr-stak#233]
I'm leaving the hashrate donation at the default, just wanted to say thank you for the full disclosure and being up front about it.

An option to adjust it would be nice, but I understand why you left that out ;)

Thank you for your hard work!!!!

**Comment by MilosMosovsky** [comment]
It`s adjustable here 
https://github.com/fireice-uk/xmr-stak/blob/79154f76defa627255891888f4dd62453194fc2c/xmrstak/donate-level.hpp#L18

You can increase/decrease amount and re-compile binary

**Comment by saylor68** [comment]
+1 I have to agree, and also left the 2%, and say thanks for the great app!
- saylor
