### ISSUE TITLE
Random CUDA Error during mining

### ISSUE THREAD

**Issue by IceFloe** [fireice-uk/xmr-stak#2343]
Please provide as much as possible information to reproduce the issue.

# Basic information
- Type of the GPU.
Asus Rog Strix 2070

I am using WIndows 10. Installed Cuda version from How to compile guide. I have compiled xmr-stak by guide at my PC. I am mining cn-gpu algo.

# Stability issue
  - Is the CPU or GPU overclocked?
Yes it is 
+125 on Core GPU Boost Clock
+15 Power Target

Average temperature 65C
Fans at 60%

During the mining I am getting an error in random time, it could happen in 2 hours or in 24 hours, or happen after restart and some mining.

The error is 
[CUDA] ERROR gpu 0: ./xmr-stak-2.10.1/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu: 487

If you need more information just write, I will provide everything what you need.

**Comment by Spudz76** [comment]
kernel crashed on GPU, reduce clocking or powerlimit

boost memory clock it's more important (and crashes less hard than clocking the core clock)
if you overclock core slightly too much it crashes the whole train
if you overclock memory slightly too much it just throws invalid results now and then

I run powerlimit 66% (110w) anything over that just chews exponential watts for not much hashrate gain (on GTX970)

You didn't say what GPU but the ideal powerlimit varies per family and somewhat per algo too.  I would never run over 75% limit as the added 50W only buys half the hash it should after a point and profit goes down.

Highest possible hashrate feels good but it is a waste, like driving everywhere at 110MPH.  Somewhere around 65MPH the air resistance actually eats more fuel and makes going 110MPH ridiculous just from a stress and energy waste angle.

**Comment by psychocrypt** [comment]
please take care since monero uses a random part within the pow it could be
that some blocks require more power from your gpu and overclocking can be
the reason for random crashes.

**Comment by IceFloe** [comment]
I am using CN-GPU algo only, memory is not important for me at all, overclocking does not matter in all other applications and this is not connected with It I think, temperature is near 60-65 so  all is ok with video card.

And I did say what GPU, Asus Rog Strix 2070.

@psychocrypt Does CN-GPU do the same?

**Comment by psychocrypt** [comment]
sry read to much issues per day and missed that you inserted the fpu type.
No gn-gpu is not using random commands.

**Comment by psychocrypt** [comment]
Is there maybe a line before or after the error message. Normally the miner
will give a little bit kore details about the reason of the crash

**Comment by IceFloe** [comment]
No problem, Yes I wrote it also :)

> The error is
> [CUDA] ERROR gpu 0: ./xmr-stak-2.10.1/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu: 487

**Comment by psychocrypt** [comment]
This I already saw. Is there not more? This is only the line I miss the
reason.

**Comment by IceFloe** [comment]
Nothing else, just line and than crash application, could I run it somehow in the debug mode to get more info?

**Comment by psychocrypt** [comment]
in config.txt you can set the debug level to 10 but for cn-gpu you will not
get more information.

**Comment by IceFloe** [comment]
Should I try?

**Comment by psychocrypt** [comment]
I think we will not information out of it. I am still thinking about how we
can solve this issue.
It is like fishing in the dark :-(

**Comment by IceFloe** [comment]
I am a programmer and know what you are talking about. Like some one said
"If you wanna find a bug, you should think like a bug" :)

Maybe you can add more debug messages to the cn-gpu algo in the future release, so I can test it with it. Or just do this in the separate branch, and I will compile version from it and see how it is going on.

**Comment by IceFloe** [comment]
@psychocrypt Do you have any ideas? I am asking because it continues to happen

**Comment by IceFloe** [comment]
@psychocrypt I am 100% sure that this is connected with overclocking. I have reduced it slightly and put xmr-stak in a loop in case of crash. It is still crashing one time per 24 hours but I can mining with it.  You can close an issue if you want to. And if you need anything from me, I am. ready to answer.

**Comment by psychocrypt** [comment]
i have currently no idea. If you think it is solved for now than close it
pelase. If you still need help feel free to open a new ticket later and
point to the old if the issues is somehow related
