### ISSUE TITLE
What if I dont want the CPU mining? Just GPU

### ISSUE THREAD

**Issue by dden4012** [fireice-uk/xmr-stak#235]
How do I disable that function from the prebuilt binaries?

**Comment by saylor68** [comment]
theres nocuda option in config

- saylor

**Comment by psychocrypt** [comment]
`xmr-stak.exe --help` or
https://github.com/fireice-uk/xmr-stak/blob/dev/doc/usage.md#command-line-options

**Comment by dden4012** [comment]
Thanks for the help. Made a bat file with the settings and works great. Steady 1800h/s no crashes or weirdness. Was having issues with xmrig for some reason.
