### ISSUE TITLE
Question about setting best intensity

### ISSUE THREAD

**Issue by Eddie2312** [fireice-uk/xmr-stak#2350]
I'm trying to understand the intensity setting.
Using 2.10.0 to mine Bittube
I'm trying to find the best intensity setting for the RX 580 8GB. How do I interpret the numbers output by the miner? The default intensity is 1000 on each of the two threads.
![asdfsgaraw](https://user-images.githubusercontent.com/25727760/54460880-dc396380-4738-11e9-93b6-833cf03e7441.png)
![gmfdrgfqhg](https://user-images.githubusercontent.com/25727760/54460901-ed827000-4738-11e9-8fb6-a7bc7b5e899f.PNG)

![dtfhgkfrdtdr](https://user-images.githubusercontent.com/25727760/54461004-43efae80-4739-11e9-8b0f-1e960318cf7d.PNG)

**Comment by BKdilse** [comment]
Leave miner running with autotune, and look out for the text, something in the lines of "locked intensity" on the miner console, which will be the highest stable one.

**Comment by rickbb** [comment]
I have some old AMD HD 7870 cards and let auto tune run. Cards went from 65Hs to 180Hs overnight.

**Comment by Eddie2312** [comment]
> Leave miner running with autotune, and look out for the text, something in the lines of "locked intensity" on the miner console, which will be the highest stable one.

Thanks, found it. It said 704 for each thread
