### ISSUE TITLE
Nvida GTX 1060 very low hash rate

### ISSUE THREAD

**Issue by rickbb** [fireice-uk/xmr-stak#2356]
Win 10 Ent, Intel Pentium G4400, (not using CPU for mining).
5 Nvida GTX 160 3 GB GPU cards.
Using stak cards reports 100Hs max on each, using XMRRIG-Nivdia reports 425 on each.

I have threads and blocks at max, any increase will crash mining, any decrease will lower hash rate even more.

Contents of nvida.txt 

// generated by xmr-stak/2.10.0/56d2770ff/master/win/nvidia-amd-cpu/20

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 * mem_mode      - select the memory access pattern (this option has only a meaning for cryptonight_v8 and monero)
 *                 0 = 64bit memory loads
 *                 1 = 256bit memory loads   
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0,
 *       "affine_to_cpu" : false, "sync_mode" : 3, "mem_mode" : 1
 *     },
 * ],
 * If you do not wish to mine with your nVidia GPU(s) then use:
 * "gpu_threads_conf" :
 * null,
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 0,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 1,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 2,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 3,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2481/3072 MiB
  //      smx: 9
  { "index" : 4,
    "threads" : 30, "blocks" : 40,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },

],

**Comment by psychocrypt** [comment]
which config do you use with xmrig? Please try the same block thread
config. since both miner using the same code on device there ahould be no
difference in the hashrate if you use the same config.

**Comment by Spudz76** [comment]
What coin, also.

**Comment by Spudz76** [comment]
I have been using 39X26 blockXthread on GTX970 which scores 390H/s (at 66% power limit + mild overclock) on algo CN-R

**Comment by rickbb** [comment]
Used 2.14.1 xmrig-nvidia-cuda10-win64,  threads 26 blocks 27, let everything setup as default other than pool and donation level.
Pools is xmr.coinfoundry.org, using port 3033

**Comment by rickbb** [comment]
sorry, coin is monero, only one I mine at the moment.

**Comment by Spudz76** [comment]
You may be close with that, try 18 threads 27 blocks
My best settings were based on 3*SMX and 2*SMX I have 13 you have 9

**Comment by rickbb** [comment]
Matched the config from xmrig and now getting the same hash rate. Using 26/27 threads/blocks.

**Comment by rickbb** [comment]
We can close this one as well. Rig as run all night no crashes, seems stable. It did seem to help disabling CPU mining.
