### ISSUE TITLE
Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram

### ISSUE THREAD

**Issue by rickbb** [fireice-uk/xmr-stak#2359]
noticed these errors just before the hash rate goes to zero. I have deleted the .clcache and rebuilt the amd.txt file several times. error keeps happening. 

win 10 ent, intel processer, (not used in mining), 16 gig ram, 5 x AMD HD7870 2 gig cards.

When it reports hash rate, it's decent, 185 appx per card. but after a few of these errors, and screen blanking for a few seconds, zero hash rate. 

[2019-03-18 22:04:15] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
Internal error: Link failed.
Make sure the system setup is correct.
[2019-03-18 22:04:23] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
Internal error: Link failed.
Make sure the system setup is correct.

**Comment by psychocrypt** [comment]
ehich version of xmr-stak do you use and which amd driver.

**Comment by rickbb** [comment]
Using 2.10.2 and latest driver 25.xx dated March 3 2019

Rick Bragg

**Comment by rickbb** [comment]
Just did a complete re-do of the setup. Fresh download of 2.10.2, drivers are 25.20, still getting the cl build errors. I don't think there is a power issue, rig starts mining good, after many hours hash rate will fall off to nothing. Rig has a 1200W PSU, each riser and card has it's own power cable. Was very stable under previous versions, I know that the fork made lots of changes, but still. 

The rig starts mining and is running and hash rate is what I'd expect, but every so often it throws that cl build error, and after several hours will report zero hash rate.

**Comment by rickbb** [comment]
Hash dropped to zero again. Started the miner at 5:30PM yesterday, looking through the output file hash rate stopped around 5:00 this morning. I stopped and restarted it again just now, 5:40PM and it's mining back to normal hash rate.

**Comment by rickbb** [comment]
Same result again today, I'm going to setup a scheduled task to reboot the PC every 6 hours. At least it will keep this rig mining until a fix can be found or I can come up with newer cards.

**Comment by rickbb** [comment]
I'm going to close this, I may have stumbled on a fix, at least for this rig.

I rolled the AMD driver back to 19.1.1, increased my virtual ram to a max of 32gig, and decreased intensity by half. It was set at 480, it's now at 240.

Systems has run stable and continuous for 17 hrs., steady hash rate around 1230.

So fingers crossed, I'm going to let it run and not touch it.

**Comment by psychocrypt** [comment]
A fix is already open as pr.
