### ISSUE TITLE
Logic error thrown during make install on Ubuntu 16.04

### ISSUE THREAD

**Issue by Ambrotos** [fireice-uk/xmr-stak#236]
During make install, I see the following error

andrew@xmr-host:~/xmr-stak/build$ make install
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
/home/andrew/xmr-stak/xmrstak/jconf.cpp:161:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 30%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
.......
.......

The install then completes with no further errors or warnings, and the bin directory is created. If I execute the built xmr-stak binary, it runs through the first-time configuration setup, then quits with the error:

-------------------------------------------------------------------
[2017-11-24 16:28:32] : Start mining: MONERO
[2017-11-24 16:28:33] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2017-11-24 16:28:33] : Starting NVIDIA GPU thread 0, no affinity.
[2017-11-24 16:28:33] : CPU configuration stored in file 'cpu.txt'
[2017-11-24 16:28:33] : Starting single thread, affinity: 0.
[2017-11-24 16:28:33] : hwloc: memory pinned
[2017-11-24 16:28:33] : Starting single thread, affinity: 1.
[2017-11-24 16:28:33] : hwloc: memory pinned
[2017-11-24 16:28:33] : Starting single thread, affinity: 2.
[2017-11-24 16:28:33] : hwloc: memory pinned
[2017-11-24 16:28:33] : Starting single thread, affinity: 3.
[2017-11-24 16:28:33] : hwloc: memory pinned
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

I am using Ubuntu Server 16.04.3, and CUDA 8.0 GA2 (the one from Feb 2017). I followed the Linux Compilation instructions provided on this repo, basically copy/pasting the commands from the Ubuntu/Debian section. I've tried completely deleting the ~/xmr-stak directory and re-cloning from github, but always get the same result.

Any thoughts on what might be causing this? Can I provide any additional information that might be helpful?

-A

**Comment by psychocrypt** [comment]
thx, already fixed i the dev branch

**Comment by Ambrotos** [comment]
Rebuilt from dev branch. Everything works fine now. Thanks!
