### ISSUE TITLE
Error GPU 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:242

### ISSUE THREAD

**Issue by mitkodinev** [fireice-uk/xmr-stak#237]
System HP Z820 - Win Server 2012R Latest update on everything
2x 16core Xeon,
128 GB Ram
Nvidia Quadro K5000
and Nvidia Tesla K10 (this card has some problem in OS giving me Code 10: The device cannot start). I disabled it and tried again with K5000 only it produces the same error. 

I also receive a system notification right after xmr-stack crashes that display driver stop working and it's been restarted.

---------- Error Message ------------------------------
Problem signature:
  Problem Event Name:	BEX64
  Application Name:	xmr-stak.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a18c098
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10586.1171
  Fault Module Timestamp:	59ae5010
  Exception Offset:	00000000000699ce
  Exception Code:	c0000409
  Exception Data:	0000000000000007
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	f98d
  Additional Information 2:	f98d4243b9c303727e670624941bd033
  Additional Information 3:	b665
  Additional Information 4:	b665d043de02b0fc13fc39983418972b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

------------------ Error Message End -----------------------------------------------

**Comment by saylor68** [comment]
if you have an O/S code 10 error u probably need to fix that first, but bsleep and threads and blocksizes changes will probably let it run.
in NVidia.txt:

 // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3369/4096 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 32, "blocks" : 16,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false,


- saylor

**Comment by mitkodinev** [comment]
I've disabled the two Tesla devices and run this again but unfortunately no luck for me. I will try to solve all hardware issues. The other strange thing that I've noticed is the start it accurately discover all cpu threads and login into the mining pool. Right after the first block is discovered it show this error.

**Comment by saylor68** [comment]
mine did exactly same until I set my NVidia file as above ^^. good luck!

- saylor

**Comment by mitkodinev** [comment]
Thank you very much.

**Comment by mitkodinev** [comment]
Confirmed. It works with those settings.

**Comment by Clintoxen** [comment]
Is it possible to lower the default bfactor/bsleep settings the miner autogenerates ? @fireice-uk  

I have tried the dev build and it still sets the settings too low for the average gpu. I have an 1070 and it still sets it to 6 which is too low. I dont have a problem changing the setting just trying to improve the autogenerate

**Comment by psychocrypt** [comment]
Is the default bfactor to low or high?
Do you changed it to 8 for you gpu?

**Comment by Clintoxen** [comment]
Yea I had to raise it from 6 to 8 so it wouldn't crash after logging in. Its not a problem for me to change it but the default bfactor it gave my 1070 was definitely causing this gpu 0 error

**Comment by Clintoxen** [comment]
I meant to say raise the bfactor my bad

**Comment by psychocrypt** [comment]
Do you miner aeon or xmr. Bfactor 6 should work fine on a 1070. Maybe it is
only an issue combined with server 2012.

**Comment by Clintoxen** [comment]
I'm on Windows 10 pro, xmr is what I mine, didn't notice any other issue with the default nvidia config besides the bfactor being too low
