### ISSUE TITLE
Disable Nvidia mining keeping CPU

### ISSUE THREAD

**Issue by DaniloJacques** [fireice-uk/xmr-stak#238]
There is a command-link to disable the NVIDIA mining? In the Readme there is an argument to disable AMD mining, but no NVIDIA.
It's very common AMD and CPU have the same most profitable coin (because AMD cards is strong in Cryptonight), but Nvidia have other algos (Equihash, Neoscrypt, etc) that is commonly greater profitability than cryptonight. 

I couldn't find any way to disable nvidia, and the new XMR STAK all-in-one is faster using CPU than all miners. The is an option to disable the NVIDIA mining?

**Comment by hoyanf** [comment]
Command option can get from running xmr-stak.exe --help. These are the options :-
`Usage: xmr-stak.exe [OPTION]...

  -h, --help            show this help
  -v, --version         show version number
  -V, --version-long    show long version number
  -c, --config FILE     common miner configuration file
  --currency NAME       currency to mine: monero or aeon
  --noCPU               disable the CPU miner backend
  --cpu FILE            CPU backend miner config file
  --noAMD               disable the AMD miner backend
  --amd FILE            AMD backend miner config file
  --noNVIDIA            disable the NVIDIA miner backend
  --nvidia FILE         NVIDIA backend miner config file

The Following options temporary overwrites the config file settings:
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333
  -u, --user USERNAME   pool user name or wallet address
  -p, --pass PASSWD     pool password, in the most cases x or empty ""


Version: xmr-stak 2.0.0 0005e4a
Brought to by fireice_uk and psychocrypt under GPLv3.`

**Comment by DaniloJacques** [comment]
Thank you so much

I think the https://github.com/fireice-uk/xmr-stak/blob/master/doc/usage.md#command-line-options is outdated

**Comment by sergneo** [comment]
developers have long known, correct.

**Comment by psychocrypt** [comment]
Is fixed in the dev branch. I missed to update the documentation.
