### ISSUE TITLE
Clarifying Windows build instructions

### ISSUE THREAD

**Issue by Cleeez** [fireice-uk/xmr-stak#239]
I know most of us know this by now, but after you run the command for VsMSBUILDCmd.bat, it will redirect your cmd to the users/sources directory instead of the one you started in. 

Would you want me to clarify that and how to get back to the working source code directory in the windows compile guide?

Might help prevent some of these errors people report

**Comment by SlaytanicPB** [comment]
cd [hard drive source code is on]:\[sub-directory or directories source is in]\xmr-stak-2.0.0
for example -  cd c:\xmr-stak-2.0.0  or  cd d:\downloads\xmr-stak-2.0.0
If you're using windows and are using file-explorer, you should see the full path of where the code is and just copy that after   cd

Do you mean something like that?  I think that a note saying after running that command, that you'll need to change the current directory to the source directory should be good enough.  If it isn't, I don't think that person should be trying to compile code.

**Comment by Clintoxen** [comment]
Yeah, I think some people are getting confused after the .bat file is changing the directory

**Comment by saylor68** [comment]
+1 I had to ditch the user\source folder a few times and it would return back to my expected path \xmr-stak\xmrstak on next iteration.

I didn't go chasing the cause of it - whats doin it ?

- saylor

**Comment by Clintoxen** [comment]
Its the bat file changing the directory after you run it

**Comment by psychocrypt** [comment]
I nevwr saw that loading the VS environment changed the working directory.
Could you please post your OS and the VS version. And a log of the terminal
where you load the environment and the working directory is changed.

**Comment by SlaytanicPB** [comment]
I'm using Win10 Pro, latest update.  VS 2017

After I run VsMSBuildCmd.bat the current working directory switches to C:\Users\UserName\source
It's not a big problem for me, I know how to deal with it.  It did catch me off guard for a sec when I tried to follow the build directions and then noticed I'm not in the directory I want to be in.

**Comment by saylor68** [comment]
just confirming  / +1 to all of this - same same over here. win10x64, fresh component installs, etc. only just downloaded the build components/compilers this week/just to run this app. see my GitHub join date is only last week :)

+1 agreed I didn't expect it to change working paths - I don't think its overwriting the SYSTEM-DEFINED paths - but I spent more time getting back to correct vs. trying to understand why the path changed.

next time it happens to me ill try to note more detail/

thanks!

 -saylor

**Comment by Clintoxen** [comment]
Yea iits not necessarily breaking anything, just an heads up in the build instructions would help people

**Comment by JerichoJones** [comment]
I use the below batch file to compile without issue with CUDA 8 or 9 (Separate compile machine per CUDA version). Change:

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

to suit your CUDA version per the compile guide.

@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSSL DLLs
xcopy C:\xmr-stak-dep\openssl\bin*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD
