### ISSUE TITLE
AMD Invalid Result GPU ID x

### ISSUE THREAD

**Issue by WoK-E** [fireice-uk/xmr-stak#2394]
OS: Ubuntu 16.04
Kernel: 4.15.0
amdgpu-pro: 18.40

I have a few rigs with R9-380, R9-380X, RX470, RX480, and RX580. No overclocking, or undervolting. All have the original BIOS.

Everything was working fine with xmr-stak 2.8.3, amdgpu-pro 16.40 and kernel 4.04. As soon as I upgraded to the version shown above, the RX480 cards "stopped" working, i.e. xmr-stak shows AMD Invalid Result GPU ID xx for all the RX480 cards (both 4GB and 8GB). All other rigs (with the other cards) have no rejected or invalid results.

Any help is greatly appreciated

Below are the results from a rig with all but one cards removed, and after enabled auto-tuning
RESULT REPORT
Currency         : bittube
Difficulty       : 5000
Good results     : 11 / 165 (6.7 %)
Avg result time  : 132.7 sec
Pool-side hashes : 55000

Top 10 best results found:
|  0 |            13809 |  1 |             9813 |
|  2 |             8634 |  3 |             8500 |
|  4 |             7968 |  5 |             7837 |
|  6 |             7731 |  7 |             6902 |
|  8 |             6677 |  9 |             5588 |

Error details:
| Count | Error text                       | Last seen           |
|   154 | AMD Invalid Result GPU ID 0      | 2019-04-03 14:38:44 |

And this is part of the amd.txt file
  { "index" : 0,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 1, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true, "interleave" : 40
  },

**Comment by WoK-E** [comment]
I have the same problem with xmr-stak 2.10.1

**Comment by psychocrypt** [comment]
please post your pools.txt file.
I think you are mining the wrong currency.


agis <notifications@github.com> schrieb am Mi., 3. Apr. 2019, 14:02:

**Comment by Spudz76** [comment]
Isn't driver 18.40 one of the ones that will never work?

**Comment by psychocrypt** [comment]
never heard that this driver not work. But good point. Please update your
driver to one of the latest.

**Comment by WoK-E** [comment]
18.40 works fine for all my other rigs, and it is the latest one that is available for ubuntu 16.04. The current version (18.50) is only available for ubuntu 18.04.

Here's my pools.txt

"pool_list" :
[
        {"pool_address" : "bittube.miner.rocks:5555", "wallet_address" : "xxx.yyy", "rig_id" : "miner-02", "pool_password" : "w=miner-02", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 100 },
        {"pool_address" : "bittube.miner.rocks:7777", "wallet_address" : xxx.yyy", "rig_id" : "miner-02", "pool_password" : "w=miner-02", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 10 },
],

"currency" : "bittube",

**Comment by WoK-E** [comment]
I put the RX480 cards in a rig that was working with RX470 cards, and had the same results, i.e. I was getting "AMD Invalid Result GPU ID ...". I think it is not an installation issue, but rather an Ubuntu/AMD 18.40 driver/RX470 card interoperability issue.

Finally I upgraded the rigs with the RX480 cards to Ubuntu 18.04 and install the AMD 18.50 drivers and they started working.

If anybody else has the same problem, please note that **do-release-upgrade** (that I used to update the rigs) is a process that will most probably need some (or more) additional manual work in order to get the system ready to run xmr-stak again. A fresh installation is a lot faster.

**Comment by Spudz76** [comment]
Also the latest OS is never a good idea when it comes to GPUs and mining and not having tons of manual issues to fix by yourself (or bugs to report).

What were you going to get by updating? Definitely not double the hashrate so it's never worth messing up a working setup.

**Comment by WoK-E** [comment]
What kind of comment is this? Did you even read what I wrote before? It was **not** a working setup...
Now I have 15 RX480 cards that actually work

**Comment by Spudz76** [comment]
Definitely can read:
> Everything was working fine with xmr-stak 2.8.3, amdgpu-pro 16.40 and kernel 4.04. As soon as I upgraded to the version shown above, 

"the version shown above" is

> OS: Ubuntu 16.04
Kernel: 4.15.0
amdgpu-pro: 18.40

Therefore everything worked with kernel 4.04 and driver 16.40 and had you not touched the system upgrade and only pulled the new xmr-stak it would still be working flawlessly, correct?

18.04 + 18.50 combo saved you only by pure luck.  That path was also only fixed recently and used to be invalid results minefield too.  There is no reason to run newer than 17.50 unless you have Vega or enjoy new problems to solve.

Did the new xmr-stak not work with the old ubuntu setup? that was the only unclear part, it seemed like you just upgraded to be upgrading without even trying the new code on the old setup.

**Comment by WoK-E** [comment]
Man, you're reading sideways, or skipping things on purpose. Reading and comprehending, or asking if something is not clear, is far more important than answering.

The setup above was working fine with xmr-stak **2.8.3**. I upgraded to the latest xmr-stak release and decided to install amdgpu-pro 18.40. The process was automated, and everything went smoothly for all rigs, except the ones the the 480 cards. I actually spent no more than 10 minutes. All the systems were initially installed by the same script, all were updated by the same (different than the installation one) script, and all the 480 ones failed. All the other systems (i.e. the ones that do not have 480 cards) now hash a lot faster than before. Clear enough?

The problem could be because of faulty memory on the cards, the cards themselves, the software, the kernel, or strange solar activity. I don't care. I only regret the time it took me to manually upgrade the 480 systems to 18.04. My closing posting was intended to help anyone that could be facing the same problem.  If nobody else find themselves in the same situation, great! More happy people on this planet.

You'll have to forgive me for not reading anything else you're going to write. I can't waste any more with you.

**Comment by Spudz76** [comment]
>  I upgraded to the latest xmr-stak release and decided to install amdgpu-pro 18.40.
There is exactly where you went wrong as far as giving anyone good info about what to fix.

Trying the new xmr-stak without changing the driver for kicks at the same time would have told everyone that it was the drivers fault (or not).

Instead you went and changed more than one thing at a time and so nobody really knows.

My only point this whole time is don't change so many things at once, and furthermore if it works why change it.  xmr-stak may have stopped working but then change JUST THAT not the driver, and OS, and kernel, and ... then wonder why broke.
