### ISSUE TITLE
Failure Xmr-stak 2.10.2 NVIDIA

### ISSUE THREAD

**Issue by bycarloz** [fireice-uk/xmr-stak#2407]
how do I solve this problem?

I spent 12 hours extracting monero and after 12 hours the gpu of nvidia is paralyzed and begins a consumption of RAM and virtual memory begins increases too.

![help 3](https://user-images.githubusercontent.com/31080791/55994656-4da8fb00-5c80-11e9-9ea7-ec867ab328f6.png)
![help](https://user-images.githubusercontent.com/31080791/55994667-53064580-5c80-11e9-97d2-17807d80db0e.png)
![help 2](https://user-images.githubusercontent.com/31080791/55994683-58639000-5c80-11e9-9065-6167004f6670.png)

**Comment by Spudz76** [comment]
Already been fixed you're running old version.

**Comment by psychocrypt** [comment]
please update to the latest version
