### ISSUE TITLE
Precompiled Windows Binary

### ISSUE THREAD

**Issue by chesketh** [fireice-uk/xmr-stak#241]
Hi the current release directory only leads to the source for xmr-stak-cpu. Could a link be included to the precompiled Windows binaries for those of us who don't regularly compile source code on Windows. Thanks.

**Comment by Clintoxen** [comment]
![image](https://user-images.githubusercontent.com/20504430/33236793-79086c0c-d22c-11e7-8b9f-0e7e424f5d33.png)

**Comment by aaronsace** [comment]
https://github.com/fireice-uk/xmr-stak/releases/download/v2.0.0/xmr-stak-win64.zip

**Comment by chesketh** [comment]
Ah perfect, thanks very much.
