### ISSUE TITLE
Wrong algo for lethean

### ISSUE THREAD

**Issue by MJMoonbow** [fireice-uk/xmr-stak#2418]
Lethean has the same algo as monero.
If i choose lethean, the results get rejected by the pool. Ive to choose monero to mine.
This is very confusing, especially, when you just start mining....
It would be cool if you could change it...

**Comment by psychocrypt** [comment]
Thanks for the notification. We was not aware that the coin forked. Please
chosse 'cryptonight_r' as coin until we release the bugfix.

**Comment by MJMoonbow** [comment]
Yeah lethean is following Monero on the upgrades, so if they do lethean will do, sooner or later

**Comment by psychocrypt** [comment]
updated in #2419
