### ISSUE TITLE
SOCKET ERROR - [vwxy.supportxmr.com:zzzz] CONNECT error: GetAddrInfo: Name or service not known

### ISSUE THREAD

**Issue by kalanga6** [fireice-uk/xmr-stak#242]
I broke the network code somehow. I was able to connect to a supportxmr server with xmr-stak under debian stretch.  Unfortunately I couldn't get opencl drivers for several radeon 7970s under the 4.9 kernel in stretch.  I tried again using debian jessie (3.16 kernel). I could get non x-server open cl drivers for the 3.16 kernel in jessie.  However, I now receive this vexing error message with the only difference being a vanilla stretch install  vs a vanilla jessie install.  A duck duck of the error message found an example where a leading space in the config.txt file caused the "CONNECT error: GetAddrInfo: Name or service not known error".  I confirmed that my config.txt file did not have the leading space which leads me to believe there is either PEBCAK or unstated dependency of which I'm unaware.  Any syggestions?

**Comment by psychocrypt** [comment]
please compile the miner from the sources it is an issue with our
precompiled linux binaries.

**Comment by psychocrypt** [comment]
I removed the portable bin from the release.
