### ISSUE TITLE
xmr-stak.exe??

### ISSUE THREAD

**Issue by Calveeen** [fireice-uk/xmr-stak#243]
There's no xmr-stak.exe, how do i open the files?

**Comment by aaronsace** [comment]
It's right here: https://github.com/fireice-uk/xmr-stak/releases/download/v2.0.0/xmr-stak-win64.zip

**Comment by psychocrypt** [comment]
Pleas download the zip with the exe lined by @aaronsace and disable the virus protection (the software is sometimes removing the exe).

**Comment by Drocephus** [comment]
I'm having this issue now and haven't been able to troubleshoot it with anything I've found online. Please halp.
