### ISSUE TITLE
How to compile xmrstak_cuda_backend_cuda10_0.dll?

### ISSUE THREAD

**Issue by o2genum** [fireice-uk/xmr-stak#2433]
In `xmr-stak.zip` from the releases page, there are two versions of the CUDA backend:
- `xmrstak_opencl_backend.dll`
- `xmrstak_cuda_backend_cuda10_0.dll`

How do I build the second one? Is this automated to some extent, or should I install a different CUDA SDK, then build the DLL, then rename it?

**Comment by psychocrypt** [comment]
This feature is needed for windows releases to provide binaries for
different architectures. If you compile with cuda 10 or 9 the build system
will always use xmrstak_cuda_backend.dll
I will remove the feature to have multiple cuda backends for the user and
activate it only during I build the release binaries.

Andrey Moiseev <notifications@github.com> schrieb am Di., 7. Mai 2019,
17:00:
