### ISSUE TITLE
Miner sticks to dev. pool

### ISSUE THREAD

**Issue by AndreyTomsk** [fireice-uk/xmr-stak#245]
Hello author!

tried version from first release. Once miner connects to dev. pool, it doesn't return back. Shows donate messages for 40+ minutes:
Message from donate.xmr-stak.net:3333:
Thanks for donating!
Please checkout our community fund-raisers!
GUI Miner - http://goo.gl/vmuiLE
Faster pool software - https://goo.gl/hZ1djk

Log file attached.
[xmr-stak.log](https://github.com/fireice-uk/xmr-stak/files/1503917/xmr-stak.log)

**Comment by fireice-uk** [comment]
@AndreyTomsk This is a message-of-the-day from a pool meant for notifications about downtimes, pool parties etc. It is one of the protocol extensions that we implemented in 2.0

It is not an indicator of where the miner is mining, message will be displayed even if the pool is offline. 

You can set `"print_motd"` to `false` to disable it.

**Comment by AndreyTomsk** [comment]
@fireice-uk thanks for helping. I see in code that message-of-the-day is composed from all pools. Maybe displaying message only from a current pool would be more clear. Also previous versions had message pair "Connecting to dev pool ... Switching back to user pool". Now it have only the left one, and together with dev pool's message-of-the-day gives a sense of things being out of control.

**Comment by fireice-uk** [comment]
Yes, we totally re-wrote the pool selection code for the fail-over pool. I will mark this issue as an enhancement for the "fix release"

`[2017-11-26 19:12:56] : Dev pool connected. Logging in...`
`[2017-11-26 19:14:59] : Pool switched.`

Second message should be clarified with a custom message for dev -> user switch.
