### ISSUE TITLE
Extra DLL's in the Windows Releases

### ISSUE THREAD

**Issue by BKdilse** [fireice-uk/xmr-stak#2451]
Hi,

What are the additional DLL files for, because the miner functions without them fine?

```
nvrtc64_90.dll
nvrtc64_100_0.dll
nvrtc-builtins64_90.dll
nvrtc-builtins64_100.dll

```

**Comment by psychocrypt** [comment]
If you have not installed nvvp than this files provides the needed dlls.
Most users do not have those files installed.

**Comment by trasherdk** [comment]
Google tell's me that they are part of `NVIDIA CUDA Development 9.0 version 9.0 by NVIDIA Corporation`

**Comment by BKdilse** [comment]
thanks @psychocrypt I'll keep that in mind when using NVIDIA.  I use AMD, so don't need them for now.

thanks @trasherdk I did check that, but was querying why they are being distributed with the zip.
