### ISSUE TITLE
Xmr stak 2.10.5 crashes after assiginig CPU

### ISSUE THREAD

**Issue by Theflyer737** [fireice-uk/xmr-stak#2455]
Hello, 

I receive '[CUDA] Error gpu 0: <C:/Users/Calypso/xmr-stak-2.10.5/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:909' after the setting of CPU's when starting xmr-stak 2.10.5
I compiled it exactely the same way as I did for 2.10.4 (copy paste compile statement from github site).
I tried to recompile it a second time and I receive the same message.
I run the old version 2.10.4.
Any idea?

**Comment by psychocrypt** [comment]
should be solved by #2468
