### ISSUE TITLE
Addition of Aeon K12 to XMR-STAK 

### ISSUE THREAD

**Issue by BigslimVdub** [fireice-uk/xmr-stak#2456]
Aeon is planning a POW change to K12 (sha3 variant) in the near future. Will Stak miner be supporting this POW change as AeonV8? Modifications have been made to a few other miners, some officially and some in personal repositories forked from xmrig. 

Inquiring on CPU, AMD, and Nvidia miners. 

Nvidia GPU have proven the most efficient currently over AMD gpu with k12 with testnet testing.

**Comment by psychocrypt** [comment]
k12 will be mine able by fpga so a port for GPU is not usefull
