### ISSUE TITLE
XMR-Stak not working anymore with bbscoin pool.bbscoin.xyz

### ISSUE THREAD

**Issue by zer0c0d3** [fireice-uk/xmr-stak#2459]
**Most execution issues are caused by driver problems. Please use the [xmr-stak sub-reddit](https://www.reddit.com/r/XmrStak/) to ask for help instead of opening an issue here.**
At 21/06/19 08:00 xmr-stak not working anymore with bbscoin pool.bbscoin.xyz ...
Why ???

**Comment by psychocrypt** [comment]
what is the error? what means is not working? Is it crashing? Invalid
shares. Which OS. Post the file pools.txt

**Comment by zer0c0d3** [comment]
Yeah, i have wrong in pools.txt in my address , it's ok ...

**Comment by psychocrypt** [comment]
solved
