### ISSUE TITLE
Unable to compile on windows using latest AMD SDK v3.0 

### ISSUE THREAD

**Issue by NmxMilk** [fireice-uk/xmr-stak#246]
Cmake fails to detect AMD SDK v3.0 just installed.
Had to revert to version 2.9 to compile.
Cmake version 3.10 (on windows 10 64bits)

Another problem i'm having with the project dependencies (downloaded CUDA 9 version and followed instructions to no avail):
set CMAKE_PREFIX_PATH=c:\xmr-stak-dep\hwloc;c:\xmr-stak-dep\libmicrohttpd;c:\xmr-stak-dep\openssl
cmake -DCUDA_ENABLE=OFF -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
fails to find the three dependencies 

Cheers

**Comment by Clintoxen** [comment]
Do you have the dependencies unpacked in the correct place c:\xmr-stak-dep

**Comment by jch9678** [comment]
I had the same problem not finding the 3 dependencies.  I had to use the visual studio prompt as cmd wouldn't work.  See my issue #248

**Comment by JerichoJones** [comment]
I use the below batch file to compile without issue with CUDA 8 or 9 (Separate compile machine per CUDA version):

@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSLL DLLs
xcopy C:\xmr-stak-dep\openssl\bin\*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD

**Comment by NmxMilk** [comment]
Today I had some more time to investigate my problem.

I was using the command:
set AMDAPPSDKROOT="C:\Program Files (x86)\AMD APP SDK\3.0"
I used double quotes since the default install path uses windows long file names.
If I remove the quotes as in:
set AMDAPPSDKROOT=C:\Program Files (x86)\AMD APP SDK\3.0
cmake find the OpenCL lib correctly.

One question though:
Why is the CmakeLists.txt not relying entirely on cmake to find the OpenCL libs ?
Shouldn't something like:
# Handle OpenCL
find_package(OpenCL REQUIRED)
include_directories(${OpenCL_INCLUDE_DIRS})
link_directories(${OpenCL_LIBRARY})

be enough. 
I see lots of redundant lines with the FindOpenCL.cmake provided by cmake.
Thanks again

**Comment by psychocrypt** [comment]
A I remembe there was an issue somewhere that the cmake module always
perfere the nvidia opencl.
To the environment variable. Yes you need to remove the double quotes. I
will add this to the documentation. I got the same issue today during the
compile for the release :-)
