### ISSUE TITLE
Reward 0.05 bitcoins. Welcome to help solve the following problems. My mailbox is 979477675@qq.com

### ISSUE THREAD

**Issue by caojioayue** [fireice-uk/xmr-stak#2470]
My machine needs to dig Monroe coins. I need you to help me process several functions.
Integrating Monroe Excavation Procedures

Hidden digging process

Hidden excavation CPU

Boot-up automatic loading

Start the binary file

Close the binary file

No logs required

**Comment by trasherdk** [comment]
You forgot: Hide from anti-virus defense.

**Comment by caojioayue** [comment]
I don't know, but my program runs only on my machine.

**Comment by caojioayue** [comment]
> 你忘了：隐藏反病毒防御。

I don't know, but my program runs only on my machine.

**Comment by psychocrypt** [comment]
we do not support virus creation. we are aginst hidden mining.
