### ISSUE TITLE
Developer, what is this? can i remove it?

### ISSUE THREAD

**Issue by baboda52525** [fireice-uk/xmr-stak#2472]
![K-002](https://user-images.githubusercontent.com/51094395/60792603-f47a3600-a1a0-11e9-9e72-370d532e803e.jpg)
![K-003](https://user-images.githubusercontent.com/51094395/60792729-36a37780-a1a1-11e9-852e-9a1500180078.jpg)

Even if I remove the func_table[] , Mining working normally and compile file size reduced. Can I remove it? I don't know really what is this......

**Comment by Spudz76** [comment]
Used for `low_power_mode > 1`
If you never use anything but `1` then yeah, rip it out of there.

But, I recall you from xmrig, asking trojan questions, so you should probably delete all of the code instead? :/
