### ISSUE TITLE
Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by Sueoka-ppc** [fireice-uk/xmr-stak#2476]
I compile this code Fedora 28 (arch is ppc64)
Following error happend, But I don't know what should I do?

pthreads is required?? but there are no packages in "rpm package list"

I do command before compile 
# Fedora
    sudo dnf install gcc gcc-c++ hwloc-devel libmicrohttpd-devel libstdc++-static make openssl-devel cmake
    git clone https://github.com/fireice-uk/xmr-stak.git
    mkdir xmr-stak/build
    cd xmr-stak/build
    cmake ..
    make install

**Describe the bug**
cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF 
-- The CXX compiler identification is GNU 8.3.1
-- The C compiler identification is GNU 8.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindThreads.cmake:191 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:335 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/build/CMakeFiles/CMakeOutput.log".
See also "/root/xmr-stak/build/CMakeFiles/CMakeError.log".
**Which operating system do you use? **

```
...
```

**Additional information.**
##when I run compile in x86_fedora it is clearly enable to compile.

**Comment by psychocrypt** [comment]
we do not support power pc's. We require sse2.

**Comment by Sueoka-ppc** [comment]
Ok thank you...
