### ISSUE TITLE
Open CL device 0 - Precompiled code not found

### ISSUE THREAD

**Issue by Kawamintai** [fireice-uk/xmr-stak#2478]
`[2019-07-18 04:10:12] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

[2019-07-18 04:10:12] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

[2019-07-18 04:10:12] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

[2019-07-18 04:10:12] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

-------------------------------------------------------------------
xmr-stak 2.10.5 b846a6f7c

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ____               __
 ##     ## | _ \             /  _ \
#    _    #| |_/ /_   _   _  | / \/ _   _  _ _  _ _  _  _ _    __  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '|| '_|/ _ \| ' \  / __|| | | |
#         #| |\ \| |_| || () || \_/\| |_| || |  | | |  __/| | | || (_ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-07-18 04:10:12] : Mining coin: cryptonight_r
!!!! Doing only a benchmark and exiting. To mine, remove the '--benchmark' option. !!!!
[2019-07-18 04:10:12] : Prepare benchmark for block version 8

[2019-07-18 04:10:12] : Compiling code and initializing GPUs. This will take a while...

[2019-07-18 04:10:12] : Device 0 work size 8 / 32.

[2019-07-18 04:10:13] : OpenCL device 0 - Precompiled code C:\Users\kawam\AppData\Local/.openclcache/0f2682eba1f2d55fbfb69dddac69181bcb8f81007f06c8797207199c0d6ce545.openclbin not found. Compiling ...`

**Most execution issues are caused by driver problems. Please use the [xmr-stak sub-reddit](https://www.reddit.com/r/XmrStak/) to ask for help instead of opening an issue here.**

**Comment by psychocrypt** [comment]
This is not a problem. The code does not exists and will be created.
Depending on your cpu speed and number of gpus you must wait a few seconds
up to a minute.

**Comment by Kawamintai** [comment]
@psychocrypt I waited 2 hours. The xmr-stak process doesn't exist. 

Intel Core i7-8550U
AMD Radeon 530

NVIDIA works.

**Comment by psychocrypt** [comment]
than try an driver up or downgrade. which driver do you use?

**Comment by Kawamintai** [comment]
@psychocrypt Radeon 19.7.2 Adrenalin 2019.
OpenGL Version 26.20.11000.13570
2D Driver: 8.1.1.1634
I've updated before and it didn't help

**Comment by psychocrypt** [comment]
other users also reported issues with 19.7.x
Could you go back to 19.6.X

**Comment by Kawamintai** [comment]
@psychocrypt precompiled code fixed but now
Error CL_INVALID_KERNEL_ARGS when calling clEnqueueNDRangeKernel for kernel 0

**Comment by Kawamintai** [comment]
Xmr-stak restart helped.
