### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by Kawamintai** [fireice-uk/xmr-stak#2479]
Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:

Error: AMD HSA Code Object loading failed.

xmr-stak version: 2.10.5

**Comment by psychocrypt** [comment]
please remove the opencl cache. the path is shown during the start

Szymon Radoliński <notifications@github.com> schrieb am Do., 18. Juli 2019,
13:43:
