### ISSUE TITLE
Compiling for AMD-only Problems on Windows

### ISSUE THREAD

**Issue by jch9678** [fireice-uk/xmr-stak#248]
I don't have much experience compiling programs let alone in windows so I'm stuck.  I could not get the instructions to work when I followed them word for word but I think I've made some progress with workarounds.  Here is what I have so far:

1) Unzip xmr-stak into C:\xmr-stak

2) Unzip xmr-stak-dep into C:\xmr-stak-dep (This is confusing for AMD users as the instructions only reference CUDA users for v8 and v9.  Nevertheless I just used v9.)

3) go here  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools and run LaunchDevCmd as Admin (not sure if Admin is needed)  I had to use the Visual Studio prompt because regular cmd was not setting the cmake prefix path correctly.  When I did use the cmd prompt, it would not find xmr-stak-dep. 

4) set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

5) mkdir build

6) cd build

7) cmake .. C:\xmr-stak -DCPU_ENABLE=OFF -DCUDA_ENABLE=OFF -DHWLOC_ENABLE=OFF

8) cmake --build . --config Release --target install

I'm not sure if I do steps 7 and 8 correctly.  7 appears to work just fine though and I get this output:

-- Build files have been written to: C:/xmr-stak/build

Step 8 gives me 34 warnings and 2 errors.  Here is the output for the 2 errors:

"C:\xmr-stak\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak\build\xmr-stak.vcxproj" (default target) (4) ->
"C:\xmr-stak\build\xmr-stak-backend.vcxproj" (default target) (5) ->
(ClCompile target) ->
  c:\xmr-stak\xmrstak\backend\cpu\crypto/cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to do a 32
-bit build. This will all end in tears. I know it. [C:\xmr-stak\build\xmr-stak-backend.vcxproj]
  c:\xmr-stak\xmrstak\backend\cpu\crypto\cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to do a 32
-bit build. This will all end in tears. I know it. [C:\xmr-stak\build\xmr-stak-backend.vcxproj]

So far it has not ended in tears but it is frustrating.  I disabled cpu but it looks like it's trying to do something with the cpu and I don't know how to addess the 32-bit build problem.  Any ideas?

Thanks

**Comment by Clintoxen** [comment]
You need to run the cmd from the folder you unzipped  xmr-stak to. You also need to run the Cuda 9 command like it says in the instructions

**Comment by jch9678** [comment]
I did run the cmd from the folder I unzipped xmr-stak to, just wouldn't work.  This was a problem referenced here https://github.com/fireice-uk/xmr-stak-cpu/issues/298 and I got the hint to use the visual studio prompt from there.  

I see what you mean about the Cuda 9 instructions.  I just assumed that was for nvidia only as it doesn't reference AMD.  Thanks for the help, I'll give it a shot.

**Comment by psychocrypt** [comment]
The missing reference to amd and cpu is currently added in the dev and will
be part of the next relese.

**Comment by Clintoxen** [comment]
yea its not worded correctly imo, allows you to think that its not required. But as long as you are putting the dependencies in the correct folder and using the correct command in cmd it shouldnt have a problem finding it. Make sure you are using the updated dependency folder and not the one from xmr-cpu

**Comment by psychocrypt** [comment]
Please check the documentaion the line how 64bit is activated is there
available.

https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md#compile

**Comment by jch9678** [comment]
I think I got it to work.  Here are my steps

1) Unzip xmr-stak into C:\xmr-stak

2) Unzip xmr-stak-dep into C:\xmr-stak-dep

3) go here  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools and run LaunchDevCmd as admin 

4) cd c:\xmr-stak

5) set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

6) mkdir build

7) cd build

8) cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. C:\xmr-stak -DCPU_ENABLE=OFF -DCUDA_ENABLE=OFF -DHWLOC_ENABLE=OFF

9) cmake --build . --config Release --target install

39 warnings but it compiled.  Now to test....

**Comment by SharnamK** [comment]
Thanks for the instructions, jch9678
Since the C:\xmr-stak -DCPU_ENABLE=OFF option disables CPU, is there a way to restart it? Did you figure out how to do that without any errors?

**Comment by jch9678** [comment]
just leave out the cpu and hwloc.  

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. C:\xmr-stak -DCUDA_ENABLE=OFF 

or use on instead of off...I guess.  

I didn't have any errors when I compiled, just warnings, which I think are ok.

**Comment by JerichoJones** [comment]
I use the below batch file to compile without issue with CUDA 8 or 9 (Separate compile machine per CUDA version):

@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSSL DLLs
xcopy C:\xmr-stak-dep\openssl\bin*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD

**Comment by jch9678** [comment]
Cool @JerichoJones I just tested it and the only hang up was the OpenSSL dlls didn't get copied.

**Comment by TrueStanos** [comment]
I was having the same problem and tried these instructions instead but got a lot of errors as suggested above.  I tried the originial Windows build instructions but used the VS  LaunchDevCmd as admin from jch9678's instructions and everything worked out just fine.  

Seems the Windows cmd prompt just doesn't have the juice.
