### ISSUE TITLE
"pool_list" : [ {"pool_address": "168.235.86.33: 3368", "wallet_address": "SK_MB2alcAPslZOo5sDPnXnH.vova1978", "rig_id":"", "pool_password": "x", "use_nicehash": false, "use_tls": false, "tls_fingerprint":"", "pool_weight": 1 }, ], "currency": "cryptonight_r",

### ISSUE THREAD

**Issue by zverwinda** [fireice-uk/xmr-stak#2489]
**Please explain the feature as good as possible.**
"pool_list" : [ {"pool_address": "168.235.86.33: 3368", "wallet_address": "SK_MB2alcAPslZOo5sDPnXnH.vova1978", "rig_id":"", "pool_password": "x", "use_nicehash": false, "use_tls": false, "tls_fingerprint":"", "pool_weight": 1 }, ], "currency": "cryptonight_r",

**Comment by psychocrypt** [comment]
I will close thenissue. There is no error explained.
