### ISSUE TITLE
SSLEAY32.dll not found

### ISSUE THREAD

**Issue by risaWY** [fireice-uk/xmr-stak#249]
Build it in Windows and when I ran it, I get:

_The code execution cannot proceed because SSLEAY32.dll was not found. Reinstalling the program may fix this problem._

Ideas? Download the file and place it somewhere?

**Comment by aaronsace** [comment]
Right here: https://github.com/fireice-uk/xmr-stak/releases/download/v2.0.0/xmr-stak-win64.zip

**Comment by RustyHoff** [comment]
I belive they are actually in  https://github.com/fireice-uk/xmr-stak-dep/releases/download/v2/xmr-stak-dep.zip
```
xmr-stak-dep>openssl>libeay32.ddl
                    >ssleay32.ddl
```

**Comment by saylor68** [comment]
put it in the working directory where the app lives and it should see it.

- saylor

**Comment by psychocrypt** [comment]
You need to copy the ssl files from the dependencies.
https://github.com/fireice-uk/xmr-stak/blob/dev/doc/compile_Windows.md
I missed to add the las tstep into the master branch. The dev is already fixed and with the next release the changes will go into the master branch.

**Comment by risaWY** [comment]
Thanks guys. That worked.
