### ISSUE TITLE
2.10.6 CN-GPU Nvidia 1060 invalid results

### ISSUE THREAD

**Issue by Ryo-RU** [fireice-uk/xmr-stak#2490]
OS: W10
Drivers: 19.4.3
Gpu: Vega56
Version: 2.10.6 (precompiled)
System: Vega56 + Gtx1060
Ram: 4Gb
Config: custom (worksize set to 16)
After several hours GTX1060 submits 12-18% invalid shares mining cn-gpu.
[[Log link]](https://pastebin.com/B4wmyecr)

2.10.5 was working on same settings without issues

**Comment by psychocrypt** [comment]
error is on NVIDIA side: `|   108 | NVIDIA Invalid Result GPU ID 0   | 2019-07-24 22:16:42 |`

**Comment by Ryo-RU** [comment]
sry, fixed

**Comment by Ryo-RU** [comment]
update:
- autogenerated config works well. I had custom config that was working well in previos version. With .6 update i had to reduce "blocks" to get rid of invalid shares.

**Comment by Ryo-RU** [comment]
fixed in 2.10.7 release
