### ISSUE TITLE
new version speed problem

### ISSUE THREAD

**Issue by Ogy** [fireice-uk/xmr-stak#250]
hello,
at first, thanks for your work !

the new xmr-stak is a very little bit slower than "old" xmr-stak-cpu
i have dedicated amd 1700X machine running from ram where all code has been compiled
the old version runs **constantly** at:
  Totals:   555.9 555.8 555.7 H/s
  Highest:  556.0 H/s
but the new
  Totals:   552.4 552.4 552.4 H/s
  Highest:  552.5 H/s
I've run a lot of long tests, different cmake settings, tried different kernels and so on

**Comment by Sandown** [comment]
I have the same issue but with AMD GPUs, each GPU runs around 30H/s slower on XMR -STAK 2.0 than on 1.4 AMD NOTLS. Did you ever find a solution?

**Comment by Forage** [comment]
The new version automatically generates a different 'intensity' value for the config setting then what I found ideal with the previous version. Try changing that value manually in 'amd.txt' to the value you had before in your 'config.txt' and see if that makes a difference for you.

**Comment by Sandown** [comment]
@Forage Thanks for the reply. I've tried tweaking the intensity values and still can't get those extra 30H/s back compared to v1.4. If i try going higher with the intensity i start getting artifacts on the screen and the miner becomes unstable :(

**Comment by Forage** [comment]
Higher is not necessarily better. It all depends on your setup. The default in the previous version was 1000. Where the new version suggested to go for 864, a value of 1024 gave me the best results in the previous version. When I started using the new version I had a rate drop with the suggested value. Resorting to the old value gave me the higher rate of the previous version again.

This is for me with an AMD RX480.

There is, oddly enough, not a reliable way to calculate the intensity. At least not that I know of. So you are left with trial and error. Start with 1000 and increase and decrease with step of (multiples of) 8. Go back again (in a smaller step when possible) when a change gives you a rate drop. Usually you'll have a pretty good impression of the rate after a minute or two with each attempt.

It could all be related to something else as well, of course. I don't know how much has changed between the two versions and if some of those changes could also explain a rate drop.

**Comment by psychocrypt** [comment]
If you use a newer version keep always in mind that we fixing bugs in each
version. sometimes a bugfix can decrease the performance. But even if the
performance goes down by a few percent it is always better to use the bug
fixed version.
There is no advantage id you see a higher number bit the number is only
coming from a bug.
@Age Bosma wrote try to hand tune the config. The auto suggestion tries to
find a good and valid config but to avoid crashes we need to be
conservative with our suggestion.
