### ISSUE TITLE
WARNING: No AMD device found

### ISSUE THREAD

**Issue by cirolaferrara** [fireice-uk/xmr-stak#2500]
I'm on Linux ubuntu 4.15.0-55-generic 64 bit
I have xmr-stak-linux-2.10.7-cpu_opencl-amd
I have [ROCm driver](https://rocm.github.io/install.html)
I have Gigabyte VEGA 56

The log says:

> [2019-08-01 23:34:01] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2019-08-01 23:34:01] : WARNING: CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for of devices.
[2019-08-01 23:34:01] : WARNING: No AMD device found.
[2019-08-01 23:34:01] : WARNING: backend AMD (OpenCL) disabled.

xmrig-amd-2.14.5 works
hashcat works
so I think that drivers are installed. ideas?

**Comment by psychocrypt** [comment]
could you try to compile the miner. I compiled the binaries with the
original amd driver. Normally opencl is designed to allow it but maybe it
is not the case.

**Comment by cirolaferrara** [comment]
Thank you. Now it works

**Comment by psychocrypt** [comment]
do you solved it by compiling it?

**Comment by cirolaferrara** [comment]
Yes. With rocm AMDAPPSDKROOT and disabling cuda.

I have a Gigabyte vega 56 and hashrate for monero is around 1300H/s.

I dont know if it is a good performance. I read that people with Windows
and same video card are around 1900.

**Comment by psychocrypt** [comment]
Not sure which coin you are mining but for cryptonigh-gpu you can find
configs
https://www.reddit.com/r/XmrStak/comments/ckugbx/ryo_cryptonightgpu_hashrates_configs_amd/?utm_medium=android_app&utm_source=share

cirolaferrara <notifications@github.com> schrieb am Fr., 2. Aug. 2019,
10:01:
