### ISSUE TITLE
hashrate drop since 2.10.0

### ISSUE THREAD

**Issue by dkwan8888** [fireice-uk/xmr-stak#2503]
I am using Quadro P4000 and intel i7 for mining XMR.

I have 2.10.0 having 800+ H/s while I only got 650 H/s while using 2.10.7
they are all auto config.

**Comment by psychocrypt** [comment]
please post both configs. Maybe the auto config has changed

**Comment by dkwan8888** [comment]
Resolved. Used old nvidia.txt. Works perfectly.
