### ISSUE TITLE
How to compile CUDA 8 with Fermi Nvidia Card (GT 430)

### ISSUE THREAD

**Issue by OMGitsMohaYT** [fireice-uk/xmr-stak#2505]
I already have the Visual Studio 2019, and the VC++ 2015 build tools and all that stuff, I also have both CUDA 9 and 8, (idk if i should remove cuda 9, i just have them both installed) and a nvidia driver version of 375.70, I got i3 2100 and GT 430 GPU (fermi) and 8gb ram if those specs are needed, I'm honestly stuck and confused and I don't wanna ruin everything and stuff so I came here and made a new issue, Please help me with this situation or give me a video that I should follow

**Comment by psychocrypt** [comment]
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile/compile_Windows.md

follow excatly this. If something went wring please copy all comamnds and
all output to pastbin and link it here or you can get also help in our
reddit forum
https://www.reddit.com/r/XmrStak?utm_medium=android_app&utm_source=share

**Comment by OMGitsMohaYT** [comment]
Oh thanks, I'll let you know when I'm done!

**Comment by OMGitsMohaYT** [comment]
https://pastebin.com/8MrpAT05

An error occured at the end when I did everything right and everything was fine, Hope you help me figure out what's the problem :)

**Comment by psychocrypt** [comment]
please remove the build folder and do all steps again. Than please past all
output from the screen.
I must see the command you used and the response of the system.

**Comment by OMGitsMohaYT** [comment]
You mean a screenshot, right?

**Comment by psychocrypt** [comment]
no mark it in the terminal and copy past it.
You will get many pages of output.

**Comment by OMGitsMohaYT** [comment]
I actually messed some stuffs and I got it working which means it's done and should work but instead nope, I went to the xmr stak miner and it still says backend disabled, cuda error, cuda etc...
Here's it:
`[2019-08-11 15:05:36] Mining coin: cryptonight_r

[2019-08-11 15:05:36] WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.

[2019-08-11 15:05:36] WARNING: backend AMD (OpenCL) disabled.

[2019-08-11 15:05:36] NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'

[2019-08-11 15:05:37] WARNING: NVIDIA Insufficient driver!

[2019-08-11 15:05:37] NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'

[2019-08-11 15:05:37] WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda9_2.dll

[2019-08-11 15:05:37] WARNING: NVIDIA Insufficient driver!

[2019-08-11 15:05:37] NVIDIA: try to load library 'xmrstak_cuda_backend'

[2019-08-11 15:05:37] WARNING: NVIDIA Insufficient driver!

[2019-08-11 15:05:37] WARNING: backend NVIDIA disabled.

[2019-08-11 15:05:37] Starting 1x thread, affinity: 0.

[2019-08-11 15:05:37] hwloc: memory pinned

[2019-08-11 15:05:37] Starting 1x thread, affinity: 2.

[2019-08-11 15:05:37] hwloc: memory pinned

[2019-08-11 15:05:37] Fast-connecting to hk01.supportxmr.com:8080 pool ...

[2019-08-11 15:05:37] MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

[2019-08-11 15:05:37] MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

[2019-08-11 15:05:38] Fast-connecting to pool.supportxmr.com:5555 pool ...

[2019-08-11 15:05:38] Pool pool.supportxmr.com:5555 connected. Logging in...

[2019-08-11 15:05:38] Difficulty changed. Now: 20000.

[2019-08-11 15:05:38] Pool logged in.

[2019-08-11 15:05:40] SOCKET ERROR - [hk01.supportxmr.com:8080] CONNECT error: No connection could be made because the target machine actively refused it. 

[2019-08-11 15:06:29] Difficulty changed. Now: 14815.

[2019-08-11 15:06:29] New block detected.

[2019-08-11 15:06:34] New block detected.

[2019-08-11 15:07:29] Difficulty changed. Now: 10000.

[2019-08-11 15:07:29] New block detected.`

**Comment by psychocrypt** [comment]
are you sure you are using the latest version. please post always all
output. you removed the version line.
Maybe you installed also two different driver and forget to let the driver
set the environment variables.
You must also restart windows after the driver install

**Comment by psychocrypt** [comment]
I still think you are on an old version of stak but missed that you must
copy all nvrtc dll files into the miner folder or set the environment
variable 'PATH' to the folder with the libs

**Comment by OMGitsMohaYT** [comment]
I'm not using the latest nvidia driver version but I'm using the latest xmr stak version, I posted all the outputs I have so I don't think there's more, The messages errors with timestamps I showed you above was from a miner that uses xmr stak (that miner has the latest version) even If I go to xmr stak, it still says the same, Yeah I installed 2 nvidia drivers, first one was 36x.xx and the second one was 375.70 which replaced the first one, I didn't restart my PC after the driver install, and wdym by copying all nvrtc.dll files into the miner folder or setting the environment variable 'PATH' to the folder with the libs?

**Comment by psychocrypt** [comment]
is the driver 375 also cuda 8? I think you compiled against the newer
driver and than during the start you use the older. This will result in a
similar issue.

**Comment by psychocrypt** [comment]
remove both driver versions. restart the system. Install cuda 8 again.
restart the system.

Now compile all again.

**Comment by OMGitsMohaYT** [comment]
so i remove both driver versions, restart the system, install the driver 375.70 or i shouldn't install drivers at all, then install cuda 8, restart, then compile, then restart the system and done?

**Comment by OMGitsMohaYT** [comment]
should i also remove cuda 8 and 9 because they're installed now

**Comment by psychocrypt** [comment]
yes remove both. I think you environment is configured wrong. by using only
one driver the risk of a dirty environment is lower.

**Comment by OMGitsMohaYT** [comment]
alright then, i'll do this later on, after i'm done, i'll just comeback with the results, i might take longer to do those steps cuz im lazy rn :v

**Comment by OMGitsMohaYT** [comment]
Do I have to download cuda 8 network or local since local has a total of 1gb or smth

**Comment by psychocrypt** [comment]
if you download the network version they will in the end also download the
1.5gib. so you are free to choose.

**Comment by OMGitsMohaYT** [comment]
It still doesn't work, I did everything, removed everything then installed nvidia drvier 375.70 and cuda 8, compiled but it still says 
NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'

WARNING: NVIDIA Insufficient driver!

NVIDIA: try to load library 'xmrstak_cuda_backend_cuda9_2'

WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend_cuda9_2.dll

Idk what should I do

**Comment by psychocrypt** [comment]
please run `xmr-stak -V`

**Comment by OMGitsMohaYT** [comment]
Where do I put that or find that?

**Comment by psychocrypt** [comment]
open the terminal goto the build folder where the binary xmr-stak is and
execute the command I posted

**Comment by OMGitsMohaYT** [comment]
I did it but it didn't work and now I get only one error or 2 idk

[2019-08-13 00:47:10] : Mining coin: cryptonight_r
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
[2019-08-13 00:47:10] : WARNING: backend AMD (OpenCL) disabled.
[2019-08-13 00:47:10] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
[2019-08-13 00:47:10] : WARNING: backend NVIDIA disabled.
[2019-08-13 00:47:10] : Starting 1x thread, affinity: 0.
[2019-08-13 00:47:10] : hwloc: memory pinned
[2019-08-13 00:47:10] : Starting 1x thread, affinity: 2.
[2019-08-13 00:47:10] : hwloc: memory pinned
[2019-08-13 00:47:10] : Fast-connecting to pool.supportxmr.com:5555 pool ...
[2019-08-13 00:47:10] : Pool pool.supportxmr.com:5555 connected. Logging in...
[2019-08-13 00:47:10] : Difficulty changed. Now: 20000.
[2019-08-13 00:47:10] : Pool logged in.

**Comment by psychocrypt** [comment]
please post all output of the miner. you remove every time you post
something the importent lines.

**Comment by OMGitsMohaYT** [comment]
[2019-08-13 12:43:43] : Your CPU doesn't support hardware AES. Don't expect
high hashrates.
-------------------------------------------------------------------
xmr-stak 2.10.7 fd19a5d03

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _
  _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| |
| |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ |
|_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___|
\__, |
   #####           __/ |
 __/ |
                  |___/   https://ryo-currency.com
|___/

This currency is a way for us to implement the ideas that we were unable to
in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for
details.
-------------------------------------------------------------------
[2019-08-13 12:43:43] : Mining coin: cryptonight_r
[2019-08-13 12:43:44] : WARNING: No AMD OpenCL platform found. Possible
driver issues or wrong vendor driver.
[2019-08-13 12:43:44] : WARNING: backend AMD (OpenCL) disabled.
[2019-08-13 12:43:44] : NVIDIA: try to load library
'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2019-08-13 12:43:45] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2019-08-13 12:43:46] : WARNING: backend NVIDIA disabled.
[2019-08-13 12:43:46] : Starting 1x thread, affinity: 0.
[2019-08-13 12:43:46] : hwloc: memory pinned
[2019-08-13 12:43:46] : Starting 1x thread, affinity: 2.
[2019-08-13 12:43:46] : hwloc: memory pinned
[2019-08-13 12:43:46] : Fast-connecting to pool.supportxmr.com:5555 pool ...
[2019-08-13 12:43:46] : Pool pool.supportxmr.com:5555 connected. Logging
in...
[2019-08-13 12:43:46] : Difficulty changed. Now: 20000.
[2019-08-13 12:43:46] : Pool logged in.
[2019-08-13 12:43:54] : New block detected.
[2019-08-13 12:44:31] : Difficulty changed. Now: 16000.
[2019-08-13 12:44:31] : New block detected.

**Comment by psychocrypt** [comment]
do you copied the nvrtc dell files to the xmr-stak binary? If not do this
or set the environment variable to the folder where th3 cudua nvrtc dll
files are located.

**Comment by OMGitsMohaYT** [comment]
I didn't do any of the above, Could you show me how because I don't know
how to do that. Thanks for taking your time to help me, I really appreciate
it.

**Comment by OMGitsMohaYT** [comment]
So?

**Comment by psychocrypt** [comment]
download a precompiled version and check which files are in. I am currently
only via phone online so i can not check the names.

**Comment by OMGitsMohaYT** [comment]
Yeah, I already downloaded the precompiled version, Now it only gives me
one error or 2, idk, Lemme give you the output:

>

Use simple setup method? (Y/n)
n
Please enter:
- Do you want to use the HTTP interface?
Unlike the screen display, browser interface is not affected by the GPU lag.
If you don't want to use it, please enter 0, otherwise enter port number that the miner should listen on
y
Invalid port number. Please enter a number between 0 and 65535.
5555
Configuration stored in file 'config.txt'
Please enter:
- Please enter the currency that you want to mine:
        - aeon7
        - bbscoin
        - bittube
        - cryptonight
        - cryptonight_bittube2
        - cryptonight_masari
        - cryptonight_haven
        - cryptonight_heavy
        - cryptonight_lite
        - cryptonight_lite_v7
        - cryptonight_lite_v7_xor
        - cryptonight_r
        - cryptonight_superfast
        - cryptonight_turtle
        - cryptonight_v7
        - cryptonight_v8
        - cryptonight_v8_double
        - cryptonight_v8_half
        - cryptonight_v8_reversewaltz
        - cryptonight_v8_zelerius
        - cryptonight_v7_stellite
        - cryptonight_gpu
        - cryptonight_conceal
        - graft
        - haven
        - lethean
        - masari
        - monero
        - qrl
        - ryo
        - torque
        - plenteum
        - zelerius

cryptonight_r
- Pool address: e.g. pool.example.com:3333
pool.supportxmr.com:5555
- Username (wallet address or pool login):
4Ar6MjjCFUHj3HCgdQSTgLhmmzKfHZ2mZautPrqJ9z6J9s72KaMMtX9QgESPBJN8vF3tTvmoKAEeFSXLD1qHunAqHg2pAi5
- Password (mostly empty or x):
23518_1
- Rig identifier for pool-side statistics (needs pool support). Can be empty:

- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
n
- Do you want to use nicehash on this pool? (y/N)
n
- Do you want to use multiple pools? (y/N)
n
Pool configuration stored in file 'pools.txt'
[2019-08-15 10:38:44] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
-------------------------------------------------------------------
xmr-stak-JK 2.10.7 fd19a5d03

Brought to you by fireice_uk and psychocrypt under GPLv3.
Compiled with no devfee by JaredKaragen.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 0.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2019-08-15 10:38:44] : Mining coin: cryptonight_r
[2019-08-15 10:38:44] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2019-08-15 10:38:44] : WARNING: backend AMD (OpenCL) disabled.
[2019-08-15 10:38:44] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA Insufficient driver!
[2019-08-15 10:38:44] : WARNING: backend NVIDIA disabled.
[2019-08-15 10:38:44] : CPU configuration stored in file 'cpu.txt'
[2019-08-15 10:38:44] : Starting 1x thread, affinity: 0.
[2019-08-15 10:38:44] : hwloc: memory pinned
[2019-08-15 10:38:44] : Starting 1x thread, affinity: 2.
[2019-08-15 10:38:44] : hwloc: memory pinned
[2019-08-15 10:38:44] : Fast-connecting to pool.supportxmr.com:5555 pool ...
[2019-08-15 10:38:44] : Pool pool.supportxmr.com:5555 connected. Logging in...
[2019-08-15 10:38:45] : Difficulty changed. Now: 20000.
[2019-08-15 10:38:45] : Pool logged in.
[2019-08-15 10:39:31] : New block detected.

**Comment by OMGitsMohaYT** [comment]
So?

**Comment by psychocrypt** [comment]
could it be that you use not our source code? Your version shows xmr-stak-JK
2.10.7 fd19a5d03

**Comment by OMGitsMohaYT** [comment]
then what should i do?

**Comment by psychocrypt** [comment]
please use always https://github.com/fireice-uk/xmr-stak because we can not
debug versions from someone else. We do not know what other changed on the
code.

**Comment by OMGitsMohaYT** [comment]
So after compiling and stuff, and running the miner from that folder, I get this: https://pastebin.com/NpDGnDaz

**Comment by OMGitsMohaYT** [comment]
After installing the latest nvidia driver version which is 391.35 for GT 430, I get this: https://pastebin.com/vLSEbahu

**Comment by OMGitsMohaYT** [comment]
I made a batch file to mine with GPU only but I get this:


C:\xmr-stak-dep\xmr-stak-2.10.7\build\bin\Release>xmr-stak.exe --noCPU
[2019-08-21 16:53:58] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
-------------------------------------------------------------------
xmr-stak 2.10.7 fd19a5d03

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-08-21 16:53:58] : Mining coin: cryptonight_r
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
[2019-08-21 16:53:58] : WARNING: backend AMD (OpenCL) disabled.
[2019-08-21 16:53:58] : NVIDIA: try to load library 'xmrstak_cuda_backend'
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
[2019-08-21 16:53:58] : WARNING: backend NVIDIA disabled.
[2019-08-21 16:53:58] : ERROR: No miner backend enabled.
Press any key to exit.

**Comment by OMGitsMohaYT** [comment]
After downloading the precompiled version from the one you made, It worked
https://pastebin.com/s5RuSDmF
But the thing is im not getting result accepted by the pool

**Comment by psychocrypt** [comment]
you are using a too old miner version. monero switched the pow algorithm so
please use the latest xmr-stak version

**Comment by jaredkaragen** [comment]
It was my build.  Simply set devfee to zero and donation addresses to 127.0.0.1:port...  no major code changes.

To the OP:
I noticed cryptonight_r was your selection....  and not "monero"

Might be your rejected share issues.

**Comment by OMGitsMohaYT** [comment]
> you are using a too old miner version. monero switched the pow algorithm so please use the latest xmr-stak version
I tried using it actually, but I was using the new miner version all the time but no luck, Here's the output: https://pastebin.com/vpx8C7C4




> It was my build. Simply set devfee to zero and donation addresses to 127.0.0.1:port... no major code changes.
> 
> To the OP:
> I noticed cryptonight_r was your selection.... and not "monero"
> 
> Might be your rejected share issues.
Thanks for ur reply, but where do I set them? (devfee and donation addresses).

**Comment by OMGitsMohaYT** [comment]
Alright, so I compiled the miner by myself all over again and everything was done, so it seems like I got the miner to use my GPU which is something dope but there's only 1 error that's ruining the entire thing which is at the end of the line over here: https://pastebin.com/GT2vWHDL

**Comment by OMGitsMohaYT** [comment]
Good news, I fixed the problem by following some issues in github and it worked but there's 1 more last problem, The GPU hashrate goes to 10-11 then drops, so basically something is wrong

**Comment by psychocrypt** [comment]
please post the log. please do not remove any lines from the log.

**Comment by OMGitsMohaYT** [comment]
https://pastebin.com/WfnRg5ji

**Comment by psychocrypt** [comment]
you must wait a few minutes. the code for the gpu must be compiled just in
time. since it lookes like the cpu is also very slow you must wait at least
5 min.

**Comment by OMGitsMohaYT** [comment]
Alright, everything is working fine now, It's just the GPU needs some work
from my side, Thank you for your help, much appreciated mate! Have a good
day, Topic can be Closed now

**Comment by psychocrypt** [comment]
nice that it is now working. it was a long debug session
