### ISSUE TITLE
Clear Linux and XMR-Stack - does it work?

### ISSUE THREAD

**Issue by agentpatience** [fireice-uk/xmr-stak#2506]
I'd like to try Clear Linux and XMR stak, but I can't find any details about if they run together?

**Comment by psychocrypt** [comment]
never tried it. please try and report back if there any benefits compared
to other linux distributions.

**Comment by agentpatience** [comment]
I am trying it based on benchmark results Phoronix did however I am having issues with it detecting hwloc install it says hwloc not found but I installed the hwloc bundle here: 
https://clearlinux.org/software/bundle/hwloc

When I get home I will have more time to install it. I am just running it off a live USB stick could that be why?

**Comment by psychocrypt** [comment]
do you use the procompiled linux binaries?

**Comment by agentpatience** [comment]
I think so, I think the bundles are precompiled. See my link above.

**Comment by psychocrypt** [comment]
I will close this issue in general the precompiled xmr-stak binaries https://github.com/fireice-uk/xmr-stak/releases should also work on clear linux.
