### ISSUE TITLE
Radeon R9 Nano and FuryX CN-GPU auto config optimisation

### ISSUE THREAD

**Issue by Ryo-RU** [fireice-uk/xmr-stak#2510]
**Since R9 Nano and R9 FuryX are the same chips I'm sure that info about Nano applies to FuryX too.**
Binary: **2.10.7 precompiled**
GPU: **R9 Nano**
OS: **W10**
Driver: **19.7.5**
Algo: **CN-GPU**
Core: **Fiji** 64 Compute Units
OC: **None**

**Auto config:**
Intensity: 1536
Worksize: 8
Hash: **633H/s** [[Link]](https://imgur.com/a/xRuwuCf)

**Auto config with WS16:**
Intensity: 1536
Worksize: 16
Hash: **767H/s** [[Link]](https://imgur.com/a/Qrd2lxx)

**RX 588 config:**
Intensity: 1728
Worksize: 16
Hash: **835H/s** [[Link]](https://imgur.com/a/z9sWP4r)

**taken from Vega64 config:**
Intensity: 1864
Worksize: 16
Hash: **890H/s** [[Link]](https://imgur.com/a/PaADA9t)

**Comment by psychocrypt** [comment]
solved with #2520
