### ISSUE TITLE
Monero mining with mixed nVidia architecture

### ISSUE THREAD

**Issue by dkwan8888** [fireice-uk/xmr-stak#2511]
Hi all,
Windows 10 - 64 bit, mining Monero, 2 GPUs, Quadro P4000 (architecture 61), geForece GTX1060 (architetcutre 21).

GeForce driver version: 23.21.13.9077
Quadrio driver version: 23.21.13.9077
I understand pre-compiled binaries don't support anymore.

What should I do next to make it work?

**Comment by Ryo-RU** [comment]
Does it throw error? can you give miner output or screenshot?

**Comment by dkwan8888** [comment]
-------------------------------------------------------------------
xmr-stak 2.10.7 fd19a5d03

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
Upcoming xmr-stak-gui is sponsored by:
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-08-21 12:25:40] : Mining coin: cryptonight_r
[2019-08-21 12:25:41] : Compiling code and initializing GPUs. This will take a while...
[2019-08-21 12:25:42] : Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.
[2019-08-21 12:25:42] : WARNING: AMD device not found
[2019-08-21 12:25:42] : WARNING: backend AMD (OpenCL) disabled.
[2019-08-21 12:25:42] : NVIDIA: try to load library 'xmrstak_cuda_backend_cuda10_0'
WARNING: NVIDIA Insufficient driver!
[2019-08-21 12:25:45] : NVIDIA: try to load library 'xmrstak_cuda_backend'
CUDA [9.1/9.0] GPU#0, device architecture 61: "Quadro P4000"...
device init succeeded
CUDA [9.1/9.0] GPU#1, device architecture 21: "GeForce GTX 1060 6GB"...
WARNING: skip device - binary does not contain required device architecture
[2019-08-21 12:25:49] : WARNING: NVIDIA setup failed for GPU 1.

[2019-08-21 12:25:49] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
NVIDIA: found 2 potential device's

**Comment by psychocrypt** [comment]
where do you get your gtx 1060 from? A gtx1060 is compute 61 and not 21.
Something is wrong, could it be someone sold a fake card to you?

Can you please run 'nvidia-smi -q'

**Comment by dkwan8888** [comment]
==============NVSMI LOG==============

Timestamp                           : Wed Aug 21 16:25:20 2019
Driver Version                      : 390.77

Attached GPUs                       : 2
GPU 00000000:02:00.0
    Product Name                    : GeForce GTX 1060 6GB
    Product Brand                   : GeForce
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : N/A
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : WDDM
        Pending                     : WDDM
    Serial Number                   : N/A
    GPU UUID                        : GPU-aba6e8fd-e0f8-fd99-7a1b-9bbcdd7d204f
    Minor Number                    : N/A
    VBIOS Version                   : 70.26.23.00.01
    MultiGPU Board                  : N/A
    Board ID                        : N/A
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : N/A
    PCI
        Bus                         : 0x02
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1C0310DE
        Bus Id                      : 00000000:02:00.0
        Sub System Id               : 0x000010DE
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : N/A
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : 22 %
    Performance State               : P12
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 6144 MiB
        Used                        : 4167 MiB
        Free                        : 1977 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
        Encoder                     : N/A
        Decoder                     : N/A
    Encoder Stats
        Active Sessions             : N/A
        Average FPS                 : N/A
        Average Latency             : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 41 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : N/A

------------------------
Also wondering why the memory is used 4Gb ALL THE TIME?

**Comment by Ryo-RU** [comment]
> Also wondering why the memory is used 4Gb ALL THE TIME? 
Seems like fake GPU or bios error..

**Comment by dkwan8888** [comment]
I return them all. Fake GPU, not minable
