### ISSUE TITLE
TurtleCoin new ALGO: argon2/chukwa...https://turtlecoin.lol/ still showing xmr-stak support for mining it.

### ISSUE THREAD

**Issue by sohosynergy** [fireice-uk/xmr-stak#2525]
Hello,

I've been using your miner as the primary miner for my altcoin mining, specifically for Turtlecoin.

They changed their algorithm at block 1,800,000 to **argon2/chukwa** and no other miner I can find is supporting the algo for AMD card mining, only xmrig for cpu mining.

Can you please incorporate this into your builds?  I prefer to use your miner and will gratefully compile with full 5 percent donation if you do!

**Comment by Ryo-RU** [comment]
https://github.com/fireice-uk/xmr-stak/issues/2493
no chukwa in observable future

**Comment by psychocrypt** [comment]
currently wo do not plane to support this POW
