### ISSUE TITLE
GPU temperature increases when mining on dev pool

### ISSUE THREAD

**Issue by old777max** [fireice-uk/xmr-stak#2526]
Hi there, I use 5 of Sapphire AMD RX 580 Nitro Plus Special Edition GPU on WIN 10 PRO for mining Haven (XHV). When XMR-STAK-WIN64-2.10.7 is swiching to dev pool the temperature increases by 6-7 degrees. Thanks, Max

**Comment by Ryo-RU** [comment]
it is mining cn-gpu during this short period. Cn-gpu produces more heat compared to haven on same oc settings.

**Comment by old777max** [comment]
Do we have any options to get rid of uncontrolled overheating? Thanks

**Comment by Ryo-RU** [comment]
it mines it 2 minutes out of 100 (1h 40) and cant overheat that much it. (after dev session is finished cooler should cool it down).
What OC are your GPUs running at?
I have 588 Nitro too and they are the most cool and silent (fan is literally 50% max) gpus I've see so far

**Comment by old777max** [comment]
Thanks for sharing your setup!
RX 580 Nitro Plus Special Edition has GPU Clock 1430 and Mem Clock 2100 out of the box and I'm not paying for hydro, so I have different OC:
GPU Clock 1225
Memory Clock 2145
-138 mV
Fan 31%
Temp 54C
It shows 946 h/s
I use Sapphire Trixx instead of Afterburner.

**Comment by Ryo-RU** [comment]
54C is not something that I would call overheating =]
I welcome you to our [forum](https://www.reddit.com/r/XmrStak/), to discuss various settings, share experience or just check some guides and info there

**Comment by old777max** [comment]
I have 54 on Haven pool. When it switches to dev pool it is 60-61. Thanks for the invitation.

**Comment by Ryo-RU** [comment]
set fan to static rpm and increase to 35-40 and you will have 55C max or so. And from my experience it is still barely noticeable sound.

**Comment by old777max** [comment]
That's what I did. But I have 55C for only 2 minutes and for another 98 minutes I have 48C. Just killing fans with no reason. I switched to Xmrig and temperature is always the same. Thanks for your help!
