### ISSUE TITLE
Can not find a portable XMR-Stak for Linux in releases

### ISSUE THREAD

**Issue by ToolB0xx** [fireice-uk/xmr-stak#253]
As stated, I am trying to deploy this on a few Linux systems using the much wanted portable XMR-Stak, however, I can not find the file addressed in https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md . Is there any info on when this might be added or how to compile it on my own? Thanks.

**Comment by ToolB0xx** [comment]
My apologies, just looked at the strikethrough.

~~- Easy precompiled and portable Linux binary~~ currently not available

**Comment by psychocrypt** [comment]
We had to much isses with that therefore we removed it for now.

**Comment by ToolB0xx** [comment]
I see, any word on when it will be fixed and released again? Thanks.

**Comment by psychocrypt** [comment]
We can not say a date because it is currently not fully clear how we can
avoid the compatibilit issues.
Please compile it by hand. It is very simple and we provide a guide wich
can copy pasted.
