### ISSUE TITLE
Link to releases is broken

### ISSUE THREAD

**Issue by pdewilde** [fireice-uk/xmr-stak#254]
I get a 404 error when I try to select releases from the Readme.

**Comment by psychocrypt** [comment]
https://github.com/fireice-uk/xmr-stak/releases
The link was pointing to the wrong reposetory,will be fixed soon.

**Comment by GuiPinto** [comment]
@psychocrypt I noticed xmr-stak-portbin-linux.tar.gz is also missing from Downloads in v2.0.0, is that tar.gz still active/valid?

**Comment by psychocrypt** [comment]
i remived it because of to many issues. It is market as currently not
avalable in the release nodes.
