### ISSUE TITLE
Is it possible to add a new algorithm to the miner?

### ISSUE THREAD

**Issue by Camellia73** [fireice-uk/xmr-stak#2541]
I am the developer of "BlackRoseCoin", my coin runs on the Cryptonight Dark algorithm. This algorithm was previously used in the Cryonote coin, but is currently only used in my project. Is it possible to add support for this algorithm to your miner? If so, what does it take on my part?

**Comment by psychocrypt** [comment]
We add only support for coins with more yhan 5MH/s if you need 2MiB
Scratchpad. If you use less scratchpad than it requires more hashrate.
Could you send  us a pool where we see the global hashrate and some details
about the POW

**Comment by Camellia73** [comment]
In this case, unfortunately, my project is not suitable for adding to your miner. However, I will still write data about POW.
Cryptonight Dark has a scratchpad of 0.5 megabytes. A distinctive feature of the algorithm is the reduction of additional hash functions included in Cryptonight from 4 to 1. That is, initially, almost all versions of Cryptonight have additional hash functions Groestl, Jh, Skein, Blake. In Cryptonight Dark, only Blake is present. This algorithm is not my author, it was originally created and implemented by the Cryonote project. But later the project was closed, after that there was a modification of one of the old versions of XMRStak, however it does not work as it should, so now I am working on fixing this. More details about the implementation of the algorithm can be found in this commit from their project.
https://github.com/cryonote/cryonote/commit/016584c89297a880c947ecc88d3f3913a2951af7
