### ISSUE TITLE
AMD GPU not mining but is reconigzed

### ISSUE THREAD

**Issue by OMGitsMohaYT** [fireice-uk/xmr-stak#2543]
I got a laptop that has a AMD GPU, Intensity is at 100, worksize: 8, I can't get the miner to use the GPU and idk whats the problem so thats why I came here to ask, At first when I started the miner in the first time, it generated a amd.txt file and it had 2 threads but the GPU wasn't mining so I removed the 2nd thread and kept the first one and it still doesn't mine, so I'd like you to help me and thanks!

**Comment by psychocrypt** [comment]
please post the amd.txt, your OS, the type of the gpu, the log from the
startup of the miner and pools.txt

**Comment by psychocrypt** [comment]
please also post the output of the tool 'cl_info'

**Comment by OMGitsMohaYT** [comment]
AMD.txt: https://pastebin.com/yjGTZrT4
OS: Windows 10 64-bit
GPU: AMD HD Radeon 7400M (I know it's old and bad but it still mines with some good hashrates)
Log from the startup of the miner: https://pastebin.com/5yZBTY3r
Pools.txt: https://pastebin.com/yKK68BBF
cl_info: https://pastebin.com/jKsuqFct

**Comment by psychocrypt** [comment]
do you waited after starting the miner for 10min and than checked for the
hash rate. depending of the cpu it could take minutes until all amd kernel
will be compiled. disable cpu mining to have more power fr the compile
process. Monero requires just in time compiles of code for each block due
to amd driver issues we must compile 50 kernel within one bunch.

So try to disable cpu mining, start the miner and wait 10min and check the
hashrate again.

**Comment by OMGitsMohaYT** [comment]
I don't think that's the solution to the problem but thanks for trying to help mate, I just figured it out and solved the problem by disabling the antivirus because it was the problem.

**Comment by OMGitsMohaYT** [comment]
Well I guess it still persits, Now after I disabled the antivirus, it's mining without problems but when I wake up on the morning and check if it's mining, I find it like this: (na) which means it's not mining, and it happens everytime, keep in mind I disabled the antivirus from the group policy so any help is appreciated!

**Comment by psychocrypt** [comment]
could you please enable the log file in config.txt and send us the full log.

**Comment by OMGitsMohaYT** [comment]
// generated by xmr-stak/2.10.7/fd19a5d03/unknown/win/amd-cpu/20

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 30,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0  - Don't print anything.
 *                 1  - Print intro, connection event, disconnect event
 *                 2  - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3  - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4  - All of level 3, and automatic hashrate report printing
 *                 10 - Debug level for developer
 *
 * print_motd    - Display messages from your pool operator in the hashrate result.
 */
"verbose_level" : 4,
"print_motd" : true,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 300,

/*
 * Manual hardware AES override
 *
 * Some VMs don't report AES capability correctly. You can set this value to true to enforce hardware AES or
 * to false to force disable AES or null to let the miner decide if AES is used.
 *
 * WARNING: setting this to true on a CPU that doesn't support hardware AES will crash the miner.
 */
"aes_override" : null,

/*
 * LARGE PAGE SUPPORT
 * Large pages need a properly set up OS. It can be difficult if you are not used to systems administration,
 * but the performance results are worth the trouble - you will get around 20% boost. Slow memory mode is
 * meant as a backup, you won't get stellar results there. If you are running into trouble, especially
 * on Windows, please read the common issues in the README and FAQ.
 *
 * By default we will try to allocate large pages. This means you need to "Run As Administrator" on Windows.
 * You need to edit your system's group policies to enable locking large pages. Here are the steps from MSDN
 *
 * 1. On the Start menu, click Run. In the Open box, type gpedit.msc.
 * 2. On the Local Group Policy Editor console, expand Computer Configuration, and then expand Windows Settings.
 * 3. Expand Security Settings, and then expand Local Policies.
 * 4. Select the User Rights Assignment folder.
 * 5. The policies will be displayed in the details pane.
 * 6. In the pane, double-click Lock pages in memory.
 * 7. In the Local Security Setting – Lock pages in memory dialog box, click Add User or Group.
 * 8. In the Select Users, Service Accounts, or Groups dialog box, add an account that you will run the miner on
 * 9. Reboot for change to take effect.
 *
 * Windows also tends to fragment memory a lot. If you are running on a system with 4-8GB of RAM you might need
 * to switch off all the auto-start applications and reboot to have a large enough chunk of contiguous memory.
 *
 *
 * use_slow_memory defines our behaviour with regards to large pages. There are three possible options here:
 * always  - Don't even try to use large pages. Always use slow memory.
 * warn    - We will try to use large pages, but fall back to slow memory if that fails.
 * never   - If we fail to allocate large pages we will print an error and exit.
 */
"use_slow_memory" : "warn",

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel.
 *
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 */
"tls_secure_algo" : true,

/*
 * Daemon mode
 *
 * If you are running the process in the background and you don't need the keyboard reports, set this to true.
 * This should solve the hashrate problems on some emulated terminals.
 */
"daemon_mode" : false,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * HTTP Authentication
 *
 * This allows you to set a password to keep people on the Internet from snooping on your hashrate.
 * Keep in mind that this is based on HTTP Digest, which is based on MD5. To a determined attacker
 * who is able to read your traffic it is as easy to break a bog door latch.
 *
 * http_login - Login. Empty login disables authentication.
 * http_pass  - Password.
 */
"http_login" : "",
"http_pass" : "",

/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,



Idk if this is what u mean

**Comment by OMGitsMohaYT** [comment]
Any help?

**Comment by psychocrypt** [comment]
I need still the log of the run not the config.txt.

**Comment by psychocrypt** [comment]
in config.txt set `"output_file" : "",` to `"output_file" : "log.txt",` and
post the log.txt file

**Comment by OMGitsMohaYT** [comment]
https://pastebin.com/yUMuD1ws

**Comment by psychocrypt** [comment]
I thought you solved the problem with the start by disabling the av
software. Could you please disable cpu mining and check if after 5 min the
gpu starts with mining. I wrote before that the cpu must compile a bunch of
gpu code  Deping on you cpu it can take very long when you are mine with
the cpu.

**Comment by OMGitsMohaYT** [comment]
https://pastebin.com/Pv3MUHQS, I even have the AMD intensity set to 20 which is really low but still nothing, doesn't mine for some reason

**Comment by psychocrypt** [comment]
Could you please run the miner 10min I like to be sure that it is not the
amd comoiler. the compining time is not depending on the intensity. The amd
compiler is really slow. If 10min wait not help it could be that you need
to search an other driver.
I do not remember, do you tested xmrig too?

**Comment by OMGitsMohaYT** [comment]
> Could you please run the miner 10min I like to be sure that it is not the amd comoiler. the compining time is not depending on the intensity. The amd compiler is really slow. If 10min wait not help it could be that you need to search an other driver. I do not remember, do you tested xmrig too?
AMD doesn't support Radeon HD 7400M anymore, I tried searching drivers for this GPU last time but didn't find any on their site, But I guess there's because I found some drivers from some sites, I didn't test xmrig actually but I'll run the miner for 10 min and let you know

**Comment by OMGitsMohaYT** [comment]
Here: https://pastebin.com/bWJbEiKb

**Comment by psychocrypt** [comment]
thx for the log. It looks like there was for a short time some hashing (se
the highest 6H/s)
I think it is a driver issue. The card is really old and we had a lot of
truble even with newer driver. The just in time stuff needed for monero is
not working good with amd driver

**Comment by psychocrypt** [comment]
I woild not invest too much time since monero forkes in 3 weeks to a cpu
POW.
Do you tried to mine ryo? Ryo is made for gpus and should run okisch on
your old gpu.

**Comment by OMGitsMohaYT** [comment]
What do you mean by "monero forkes in 3 weeks to a cpu POW"? and can I mine ryo with my GPU and monero with my CPU at the same time?

**Comment by realityworks** [comment]
@OMGitsMohaYT Monero will fork to using RandomX, which runs well on certain AMD processors but not so well on GPU processors or ASIC miners. What this means is that the income will shift to non-ASIC mining farms to democratise the income. Though, someone will just build a processor stack using custom circuit boards. :)

**Comment by realityworks** [comment]
The latest version of Monero 0.15.0.0 was released just a couple of hours ago. :)

**Comment by psychocrypt** [comment]
Yes you will be able to start one miner for randomx (next POW of monero)
and mine ryo on your gpu.
If you need help to miner ryo please have a look on reddit and for
questions please open a new post there https://www.reddit.com/r/XmrStak

**Comment by psychocrypt** [comment]
btw we will release a version for randomx this week

**Comment by OMGitsMohaYT** [comment]
Thanks psychocrypt for the help as well as realityworks, I appreciate it a lot, Have a good wekeend!
