### ISSUE TITLE
xmr-stak-linux-2.10.7-cpu_cuda-nvidia very low CPU H/s Ryzen 5 1600X

### ISSUE THREAD

**Issue by meem6** [fireice-uk/xmr-stak#2548]
I downloaded complied version of xmr-stak for linux, xmr-stak-linux-2.10.7-cpu_cuda-nvidia
GPU is working ok, I have 280H/s on GTX750ti, but on CPU even when I enable just 2 cores, I have less then 10H/s on each.

-----------------------------------------------------
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |    9.8 |   (na) |   (na) |  1 |    9.8 |   (na) |   (na) |
Totals (CPU):    19.5    0.0    0.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  279.8 |   (na) |   (na) |
Totals (NVIDIA):   279.8    0.0    0.0 H/s

$:~xmr-stak-linux-2.10.7-cpu_cuda-nvidia> tail -4 cpu.txt 
[
    { "low_power_mode" : false, "no_prefetch" : true, "asm" : "amd_avx", "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "asm" : "amd_avx", "affine_to_cpu" : 2 },
],

**Comment by psychocrypt** [comment]
please post your pools.txt file

**Comment by meem6** [comment]
in pools.txt I got: "currency" : "ryo",

**Comment by psychocrypt** [comment]
ryo is using cryptonight-gpu. this algo is made for gpus and is very slow
on cpus. you should not mine ryo with your cpu. This will only waist energy.

**Comment by meem6** [comment]
I see, wasn't mining for some time, didn't know that ryo switched to new cryptonight algo...

thank you

**Comment by OMGitsMohaYT** [comment]
You can close this thread @meem6
