### ISSUE TITLE
Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.

### ISSUE THREAD

**Issue by OMGitsMohaYT** [fireice-uk/xmr-stak#2549]
I got the 2.10.7 version and this only started happening when mining RYO currency, Now idk what to do,
Here are some informations that might help you see what causes the problem:
**The log when the miner starts:**
https://pastebin.com/2cR61BNp
**amd.txt:**
https://pastebin.com/iub0XYkz
**config.txt:**
https://pastebin.com/kFtHFGeV
**pools.txt:**
https://pastebin.com/UA5Mi7gZ
**clinfo:**
https://pastebin.com/ih6mqsTX

**Comment by psychocrypt** [comment]
sry to say your gou is to old and do not support the correct 32bit floating
point operations.
cl-fp32-correctly-rounded-divide-sqrt is not supported

**Comment by OMGitsMohaYT** [comment]
I guess it doesn't work then, thanks for stating
