### ISSUE TITLE
hello.i complies code with vs2017,some questions

### ISSUE THREAD

**Issue by jackkite** [fireice-uk/xmr-stak#255]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		CMake Error at C:/Program Files/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files/Microsoft Visual
  Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe" is
  not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/2323/CMakeBuilds/937c166e-043a-1e39-9a40-0225b6d31cb5/build/x86-Debug/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"C:/PROGRA~1/MICROS~2/2017/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe"
  "cmTC_42584"

  ninja: error: build.ninja:30: loading 'rules.ninja':
  系统找不到指定的文件。

  

  include rules.ninja

                     ^ near here

  

  

  CMake will not be able to correctly generate this project.		C:/Program Files/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake	51

**Comment by psychocrypt** [comment]
please post all commands you have used.

**Comment by jackkite** [comment]
I want to compile the code to vs2017, but an error occurred, my cmake version is 3.10.0


![qq 20171127155955](https://user-images.githubusercontent.com/33998508/33256248-3fa42b52-d38c-11e7-8bb2-03437e9159b4.png)
![qq 20171127160004](https://user-images.githubusercontent.com/33998508/33256251-438e98ec-d38c-11e7-867a-ed2336da979f.png)

**Comment by jackkite** [comment]
please give me a vs2017 project? thank you

**Comment by fireice-uk** [comment]
You are welcome to try `xmr-stak` if xmrig doesn't work compile for you. You can get it here - https://github.com/fireice-uk/xmr-stak/releases/tag/v2.1.0
