### ISSUE TITLE
randomx shared rejected

### ISSUE THREAD

**Issue by baboda52525** [fireice-uk/xmr-stak#2550]
Since I heard about Monero switched to the Random X algorithm, I tried mining with what you just released but failed due to shared rejected.

**Comment by psychocrypt** [comment]
yes you need to test randomx against a testnet pool wher randomx is already
used. (you will not earn anything because it is for testing only)

Here is a post with a testnet pool address:
https://www.reddit.com/r/MoneroMining/comments/dfxpjy/minexmr_randomx_testnet_pool
