### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ImBoredAsf** [fireice-uk/xmr-stak#2565]
I'm getting segmentation fault when I run xmr-stak-rx on ubuntu or centos. I tried the release binary and compiled from source and neither would work. I'm not sure what info I should provide so I'll do my best. The following results are from the centos 6 box using a binary I compiled.

this is where it fails with just ./xmr-stak-rx
[2019-11-23 05:29:35] : start self test for 'randomx'
Segmentation fault

this is where it fails when ran with --noTest
[2019-11-23 05:31:31] : Difficulty changed. Now: 75000.
[2019-11-23 05:31:31] : Pool logged in.
Segmentation fault

I found the following message in /var/log/messages not really sure what it means or if it is relevant but here you go.
kernel: xmr-stak-rx[8922]: segfault at 0 ip 000000000045519c sp 00007f776e7496a8 error 4 in xmr-stak-rx[400000+85000]

I can provide more info if needed just let me know what info that would be

**Comment by psychocrypt** [comment]
please post your param files. I will have a look if I can see something

**Comment by ImBoredAsf** [comment]
what exactly do you mean by param files if you don't mind explaining?

**Comment by psychocrypt** [comment]
amd.txt nvidia.txt cpu.txt and pools.txt

I like to have a look there first. After it I would provide you with
information how to compile with devug symbols and run it with gdb so that I
get a backtrace to detect the issue

**Comment by ImBoredAsf** [comment]
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/3882548/cpu.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/3882549/pools.txt)
These were the ones generated on first run

**Comment by psychocrypt** [comment]
could you please run 'cat /proc/cpuinfo' and post the data

**Comment by ImBoredAsf** [comment]
[root@hpnf0 build]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
stepping        : 4
microcode       : 1070
cpu MHz         : 3000.014
cache size      : 25600 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc up rep_good unfair_spinlock eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt ssbd pti retpoline ibrs ibpb stibp fsgsbase smep erms flush_l1d
bogomips        : 6000.02
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by psychocrypt** [comment]
I assume you running within a vm this is maybe the reason. You config is
not fitting with the possible config for the system.
Please try to set `"asm" : "auto",` to `"asm" : false` to disable asm.
You can also try to disable aes in config.txt. One of this option could be
the reason.

**Comment by ImBoredAsf** [comment]
it's a spare vps that I use for vpn have just been running the miner on it for a while. The current monero algo works fine with it
[2019-11-23 10:23:58] : enable cryptonight_r asm 'intel_avx' cpu's
[2019-11-23 10:24:14] : Difficulty changed. Now: 25532.
[2019-11-23 10:24:14] : New block detected.

is it just something with the new algo that breaks functionality for some vps?

**Comment by bav73** [comment]
xmr-stak-rx 1.0.1 CentOs7 - Segmentation fault

**Comment by psychocrypt** [comment]
please open an new issue with all the information like OS, Hardware and the
log of the crash.
