### ISSUE TITLE
 CMake Error at xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj.Release.cmake

### ISSUE THREAD

**Issue by flaneque** [fireice-uk/xmr-stak#257]
Hello

I can't compile xmr-stak for my GTX 1080 using CUDA9.
Please help to find the solution.

Here is how it end :
Here is how it end :
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj.Release.cmake:2
22 (message):
Error generating
C:/xmr-stak-gpu/build/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/Release/
xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VC
Targets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\xmr-stak-gpu\build\xmr-stak-nvidiaCuda.vcxproj]

And full logs :
[cmd logs.txt](https://github.com/fireice-uk/xmr-stak/files/1506874/cmd.logs.txt)

**Comment by flaneque** [comment]
Please some help

**Comment by diablodude** [comment]
Having a non-french error-message would help maybe, there should be a way to do that in your environment?

I did not compile xmr-stak myself yet, but "Arrêt de "cmd.exe" a
vec le code 1. [C:\xmr-stak-gpu\build\xmr-stak-nvidiaCuda.vcxproj]" was the thing I would try to understand first.

**Comment by flaneque** [comment]
I edited my post with logs in english
