### ISSUE TITLE
xmr-stak-rx and xmr-stak both install libxmrstak_opencl_backend.so and libxmrstak_cuda_backend.so

### ISSUE THREAD

**Issue by candrews** [fireice-uk/xmr-stak#2571]
xmr-stak 2.10.7 and xmr-stak-rx 1.0.1-rx both install /usr/lib64/libxmrstak_opencl_backend.so which means that both xmr-stak and xmr-stak-rx cannot be installed at the same time.

Perhaps you could change rx's library name to include rx, from libxmrstak_opencl_backend.so to libxmrstakrx_opencl_backend.so ?

This issue also applies to the cuda library (libxmrstak_cuda_backend.so)

**Comment by psychocrypt** [comment]
Do not put both miner into the same directory. Please use a new directory
for xmr-stak-rx and copy your pools.txt and config.txt into the xmr-stak-rx
folder. Please have a look to the release nodes
https://github.com/fireice-uk/xmr-stak/releases i to the section pre-fork
notes.

**Comment by candrews** [comment]
It's https://github.com/fireice-uk/xmr-stak/blob/1.0.1-rx/CMakeLists.txt#L564 which is installing the libraries - it puts them (correctly) in `/usr/lib{,64}`. CMakeLists.txt needs to be changed to use different names for those libraries.

**Comment by psychocrypt** [comment]
Ohh I never thought about that someone is installing the miner to the root
filesystem.
You can simple set the install path `cmake
-DCMAKE_INSTALL_PREFIX:PATH=$HOME/stak-rx`

**Comment by candrews** [comment]
That isn't a workable solution for Linux distributions :)

Distros package to install globally, not in a user's home directory.

**Comment by psychocrypt** [comment]
I will fix it. As you wrote initial I forgot to rename the libraries.

**Comment by psychocrypt** [comment]
#2573 will fix the issue.
