### ISSUE TITLE
compile switcher?

### ISSUE THREAD

**Issue by the-babaji** [fireice-uk/xmr-stak#2576]
Is the source available for the switcher?

**Comment by psychocrypt** [comment]
for shure it is linked in the release notes.
https://github.com/psychocrypt/rx_switcher

**Comment by the-babaji** [comment]
thx

**Comment by the-babaji** [comment]
would the switcher work, even if xmr-stak is running inside of a 'screen' ?

**Comment by psychocrypt** [comment]
If you have the rights to kill the task, yes.
The switcher is killing all programs called xmr-stak

**Comment by the-babaji** [comment]
is it supposed to just sit there?

./rx-switcher 
[2019-11-30 12:35:10] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2019-11-30 12:35:11] : Pool pool.supportxmr.com:7777 connected. Logging in...

**Comment by psychocrypt** [comment]
yes it is only whatching the blockheight
