### ISSUE TITLE
nvidia cards wont load

### ISSUE THREAD

**Issue by the-babaji** [fireice-uk/xmr-stak#2577]
Yes i know it's a waste of time. Just want to see for myself how bad it is (at least for a few moments)

[2019-11-30 14:58:40] : NVIDIA: try to load library 'xmrstak_cuda_backend'
NVIDIA: found 2 potential device's

any idea how i can load the cuda backend?

**Comment by psychocrypt** [comment]
please remove nvidia.txt and start the miner again. please post the full
output from the terminal

**Comment by the-babaji** [comment]
./xmr-stak-rx --noAMD
[2019-11-30 15:51:41] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:51:41] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:51:41] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:51:41] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:51:41] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:51:41] : start self test for 'randomx' (can be disabled with the command line option '--noTest')
-------------------------------------------------------------------
xmr-stak-rx 1.0.1-rx 7a9361b22

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by tevador and SChernykh.
Based on NVIDIA mining code by SChernykh.
-------------------------------------------------------------------
You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
   #####   ______               ____
 ##     ## | ___ \             /  _ \
#    _    #| |_/ /_   _   ___  | / \/ _   _  _ _  _ _  ___  _ __    ___  _   _
#   |_|   #|    /| | | | / _ \ | |   | | | || '_|| '_|/ _ \| '_ \  / __|| | | |
#         #| |\ \| |_| || (_) || \_/\| |_| || |  | | |  __/| | | || (__ | |_| |
 ##     ## \_| \_|\__, | \___/ \____/ \__,_||_|  |_|  \___||_| |_| \___| \__, |
   #####           __/ |                                                  __/ |
                  |___/   https://ryo-currency.com                       |___/

This currency is a way for us to implement the ideas that we were unable to in
Monero. See https://github.com/fireice-uk/cryptonote-speedup-demo for details.
-------------------------------------------------------------------
[2019-11-30 15:52:09] : Mining coin: randomx
[2019-11-30 15:52:09] : NVIDIA: try to load library 'xmrstak_cuda_backend'
CUDA [10.1/10.1] GPU#0, device architecture 61: "GeForce GTX 1060 3GB"...
WARNING: skip device - cudaMalloc failed
[2019-11-30 15:52:09] : WARNING: NVIDIA setup failed for GPU 0.

CUDA [10.1/10.1] GPU#1, device architecture 61: "GeForce GTX 1060 3GB"...
WARNING: skip device - cudaMalloc failed
[2019-11-30 15:52:09] : WARNING: NVIDIA setup failed for GPU 1.

[2019-11-30 15:52:09] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
NVIDIA: found 2 potential device's
[2019-11-30 15:52:09] : WARNING: backend NVIDIA disabled.
[2019-11-30 15:52:09] : Starting 1x thread, affinity: 0.
[2019-11-30 15:52:09] : hwloc: memory pinned
[2019-11-30 15:52:09] : Fast-connecting to pool.supportxmr.com:9000 pool ...
[2019-11-30 15:52:09] : MEMORY ALLOC FAILED: mmap with HUGETLB failed, attempting without it (you should fix your kernel)
[2019-11-30 15:52:10] : TLS fingerprint [pool.supportxmr.com:9000] SHA256:QaAyAEbGZnH2Bqc9tn/+sTqaxc0o6cQDct36mO7wouw=
[2019-11-30 15:52:10] : Pool pool.supportxmr.com:9000 connected. Logging in...
[2019-11-30 15:52:10] : Difficulty changed. Now: 100001.
[2019-11-30 15:52:10] : Pool logged in.
Monero is forking to randomX.

https://www.getmonero.org

press key 'v' to open the url

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   (na) |   (na) |   (na) |
Totals (CPU):     0.0    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):      0.0    0.0    0.0 H/s
Highest:     0.0 H/s
-----------------------------------------------------------------

**Comment by psychocrypt** [comment]
please post the file nvidia.txt the error message is `WARNING: skip device
- cudaMalloc failed` for sone reason you run out of memory. 3GiB for mining
randomX is not much. If you have additional software lke the windows
manager using the gpu you can not mine randomX.

**Comment by psychocrypt** [comment]
please run also nvidia-smi and post the output.
I assume you run under linux.

**Comment by the-babaji** [comment]
yes linux but this machine happens to run a desktop, i bet if i rebooted it to run level 3, it would work. 

nvidia-smi 
Sat Nov 30 16:21:28 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| 48%   18C    P8     3W / 120W |    193MiB /  3019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:03:00.0 Off |                  N/A |
| 47%   19C    P8     3W / 120W |      2MiB /  3019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1620      G   /usr/lib/xorg/Xorg                            95MiB |
|    0      1749      G   /usr/bin/gnome-shell                          95MiB |
+-----------------------------------------------------------------------------+

**Comment by the-babaji** [comment]
working now, I should go check power consumption at the wall

| ID |    10s |    60s |    15m |
|  0 |  319.9 |  319.9 |   (na) |
Totals (CPU):   319.9  319.9    0.0 H/s
-----------------------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  288.5 |  288.6 |   (na) |  1 |  289.0 |  288.9 |   (na) |
Totals (NVIDIA):   577.5  577.5    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    897.4  897.4    0.0 H/s
Highest:   898.2 H/s
-----------------------------------------------------------------
