### ISSUE TITLE
Miner not compiled for the gpu architecture 21.

### ISSUE THREAD

**Issue by Prev-I** [fireice-uk/xmr-stak#258]
I was trying out xmr-stak and I noticed that on launch it returned this warning:

`WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 21.`

Then it proceed to mine only on CPU.

The attached card is a  NVIDIA GeForce GT 705, which probably isn't best suited for mining, but I was curious why not all CUDA capable card are supported

**Comment by psychocrypt** [comment]
The precompiled binary is not running on fermi gpus because it depends on
cuda9. Cuda9 droped fermi.

**Comment by Prev-I** [comment]
Thank you for the clarification.
