### ISSUE TITLE
low_power_mode not relevant or bug?

### ISSUE THREAD

**Issue by Omnividente** [fireice-uk/xmr-stak#2589]
Hello.
I'm testing on the i7 processor. 1 stream, the speed without low_power_mode ~730 h/s  and Low_power_mode = true ~730 h/s . Is this option no longer relevant?

**Comment by psychocrypt** [comment]
thx for opening the issue

yes i forgot to remove this from the auto config. will do it today.

**Comment by psychocrypt** [comment]
Ohh sry I miss read you issue. Low power mode should work but has no positive effect on the hashrate.

**Comment by entak** [comment]
So low power mode was removed in general? Meaning in randomx, extra CPU L3 cache is not usable for extra mining?

**Comment by psychocrypt** [comment]
no sry. low power mode is still available but have not seen any advantage.
You can set low power to any number between 1 to 5

**Comment by psychocrypt** [comment]
I found the bug, should be fixed with #2621

**Comment by psychocrypt** [comment]
There was a bug in low power but I assume that you will not get any performance out of the low power mode.
