### ISSUE TITLE
GTX 750Ti can't mining randomX??

### ISSUE THREAD

**Issue by zjhxmjl** [fireice-uk/xmr-stak#2595]
2GiB memory for mining randomX is not much in ubuntu 18.04?thx for advance.

zjhxmjl@80ti:~$ nvidia-smi
Sun Dec  1 21:42:31 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 43%   65C    P2   219W / 250W |  10959MiB / 11176MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 44%   66C    P2   206W / 250W |  10959MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 750 Ti  Off  | 00000000:04:00.0 Off |                  N/A |
| 40%   21C    P0     1W /  58W |     11MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 33%   59C    P2   178W / 250W |  10959MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 46%   67C    P2   212W / 250W |  10959MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 39%   65C    P2   204W / 250W |  10959MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1237      C   ./bin/xmr-stak-rx                          10949MiB |
|    1      1237      C   ./bin/xmr-stak-rx                          10949MiB |
|    3      1237      C   ./bin/xmr-stak-rx                          10949MiB |
|    4      1237      C   ./bin/xmr-stak-rx                          10949MiB |
|    5      1237      C   ./bin/xmr-stak-rx                          10949MiB |

**Comment by psychocrypt** [comment]
Yes 2GiB is not enough to mine randomX. You need 2GiB for the dataset + 2MiB per thread.
btw: mining randomX with gpus is not efficent, I suggest you to switch to another coin for you GPUs and  use the CPU only to mine Monero.

**Comment by psychocrypt** [comment]
You can remove the GTX750 in nvidia.txt than you can test to mine with the other gpus.

**Comment by zjhxmjl** [comment]
thx,which another coin for GPU more efficent?

**Comment by psychocrypt** [comment]
we are developing Ryo (cryptonight_gpu) https://ryo-currency.com/

**Comment by zjhxmjl** [comment]
Good,i hope it can secure, private, untraceable,fight Off ASICs

**Comment by zjhxmjl** [comment]
@psychocrypt BTW, what's the hashrate with GTX 1080TI?

**Comment by psychocrypt** [comment]
https://monerobenchmarks.info/

**Comment by Ryo-RU** [comment]
> BTW, what's the hashrate with GTX 1080TI?

[Disappointed with your GPU hashrate on RandomX? Here is the CN-GPU hashrate reference for you](https://www.reddit.com/r/XmrStak/comments/dyisy3/disappointed_with_your_gpu_hashrate_on_randomx/)
