### ISSUE TITLE
Windows MEMORY ALLOC FAILED: VirtualAlloc failed if running with noTest

### ISSUE THREAD

**Issue by Tualua** [fireice-uk/xmr-stak#2598]
I built windows binary with affinity fix from https://github.com/fireice-uk/xmr-stak/pull/2590
But if I run miner with --noTest I got many of MEMORY ALLOC FAILED: VirtualAlloc failed

It affects hashrate, 2500 with error and 2900 without error

Rig: 2xE5-2660v2, 2x4GB RAM, Windows 10 1803 build 17134.1069

**Comment by 7evenmikser** [comment]
possibly this is duplicate of https://github.com/fireice-uk/xmr-stak/issues/2582

**Comment by psychocrypt** [comment]
fixed with #2624
