### ISSUE TITLE
crashes with unsupported for mining nvidia card

### ISSUE THREAD

**Issue by Ivarss1970** [fireice-uk/xmr-stak#260]
Hello!
Is there any way how to disable mining with GPU?
Miner start mining, detects GeForce GT 710  and crashes 
![xmr-stak](https://user-images.githubusercontent.com/34022170/33256694-d85f779c-d35b-11e7-8ad7-a9fecfbfb937.PNG)

**Comment by diablodude** [comment]
monero@monero:~$ ./xmr-stak.sh --help
Usage: xmr-stak [OPTION]...

  -h, --help            show this help
  -v, --version         show version number
  -V, --version-long    show long version number
  -c, --config FILE     common miner configuration file
  --currency NAME       currency to mine: monero or aeon
  --noCPU               disable the CPU miner backend
  --cpu FILE            CPU backend miner config file
  --noAMD               disable the AMD miner backend
  --amd FILE            AMD backend miner config file
  --noNVIDIA            disable the NVIDIA miner backend
  --nvidia FILE         NVIDIA backend miner config file


--> So adding "--noNVIDIA" or "--noAMD" to the shortcuts properties disables the named gpu-backend.
You could also remove everything inside the "gpu_threads_conf" inner dictonary so it looks like the following in nvidia.txt or amd.txt:
"gpu_threads_conf":
[
{
},
],

I know that error from having an wrong amount of "threads x blocks" -- Try with real low values (16 threads, and blocks 16 for starters) and then increase them until you get reasonable performance.

**Comment by Clintoxen** [comment]
This is because the auto config sets the bfactor and bsleep  too low, try raising the bfactor to 8 or 10 and bleep to 100

**Comment by Ivarss1970** [comment]
+38h/s :)
