### ISSUE TITLE
computer crash cpu mining

### ISSUE THREAD

**Issue by christgelinas** [fireice-uk/xmr-stak#2602]
computer crash mining for 10 minutes to 20 minutes Cpu only 
loose the display and computer is unreachable , had to reset 

cpu fx-8300 
cpu temp below 40 celcius and motherbpoar below 50 celcius. 
never had problem with minine before moving to randomx miner 

same problem with my second computer with fx-6300

**Comment by psychocrypt** [comment]
Which OS, which coin do you mine

**Comment by christgelinas** [comment]
windows 10 , mining monero randomx , problem start moving to randomx algo

**Comment by christgelinas** [comment]
fix with revising overclocking setting
