### ISSUE TITLE
Linux Binary missing

### ISSUE THREAD

**Issue by izznogooood** [fireice-uk/xmr-stak#264]
"you can simply download xmr-stak-portbin-linux.tar.gz from our latest releases."

Nope, not there.

**Comment by psychocrypt** [comment]
I removed the portable ins for now. We had to many issues with the precompiled linux binaries.We are working on it.

**Comment by dawidtelepski** [comment]
so it is better to use old xmr-stak-cpu until portable will be fixed?

**Comment by psychocrypt** [comment]
Best is to compile xmr-stak from source. It is extrem simple under linux.

**Comment by psychocrypt** [comment]
follow our guide.
