### ISSUE TITLE
Docs out of date on CPU optimization

### ISSUE THREAD

**Issue by nuke-web3** [fireice-uk/xmr-stak#2641]
https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md#cpu-backend

I believe this is now outdated, please advise as to the state of the recommendations here, as this is for the CN algo, right? 

Please update this / point me to the randomX CPU optimization strategies. :pray: 

Thanks!

**Comment by psychocrypt** [comment]
You can still use this option even with randomx. I have not seen any cpu
where this has advantage. what it does is performaing N hashes in a row
where each hash gets his own scratchpad. Therefore it is only usefull if
you have more +2x cache than cpu cores.

**Comment by nuke-web3** [comment]
got it. I was under the impression that L4 cache would cover this. My system specs in #2642 show 20MB and 16 cores here... so cache > 2x cores does _not_ apply in my case for using this feature.
