### ISSUE TITLE
AMD RX 5500XT CN-GPU config optimisation

### ISSUE THREAD

**Issue by Ryo-RU** [fireice-uk/xmr-stak#2643]
Xmr-Stak generates by default 1threaded config. While in most cases CN-GPU works better and more stable on 1t config, new architecture RDNA GPUs from AMD perform better while 2-threaded.
Tested newest 5500XT and it proven to be also benefiting from 2t config on CN-GPU

**Default config:**
```{ "index" : 0,"intensity" : 528, "worksize" : 8,"affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,"unroll" : 1, "comp_mode" : true, "interleave" : 40},```
Core: 1710/950mV
Result: **810**H/s [[screenshot](https://preview.redd.it/9nwt0ji0md741.jpg?width=1280&format=pjpg&auto=webp&s=99e1b2f273a89c73d66d84de38f9b9ddd374182d)]

**Optimized config:**
```
{ "index" : 0,"intensity" : 348, "worksize" : 8,"affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,"unroll" : 1, "comp_mode" : true, "interleave" : 45},
{ "index" : 0,"intensity" : 348, "worksize" : 8,"affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,"unroll" : 1, "comp_mode" : true, "interleave" : 45}, 
```
Core: 1750/950mV
Result: **980**H/s [[screenshot](https://preview.redd.it/m71yu7uqld741.jpg?width=1280&format=pjpg&auto=webp&s=0b3dc25ef815f4e165646737ca34735c205df70c)]

**Comment by psychocrypt** [comment]
fixed with #2648
