### ISSUE TITLE
Issue with openssl

### ISSUE THREAD

**Issue by yinkiu602** [fireice-uk/xmr-stak#265]
When i tried to compile the file with openssl,the program will failed to start,having some problem like missing sothing....etc
But when i compile it WITHOUT ssl, it works normally.
So....what lead to the problem.
Using the ssl provided here: https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md
ERROR I GOT:
The code execution cannot proceed because LIBEAY32.dll was not found.Reinstalling the program may fix this problem
The code execution cannot proceed because SSLEAY32.dll was not found.Reinstalling the program may fix this problem

But when i copy the 2 files from openssl/lib to the release folder. It works. So...dev...add this to the guide?
SSL folder path is like this:J:\ssd download\xmr-stak-2.0.0\openssl
Program saved path is     :J:\ssd download\xmr-stak-2.0.0\build\bin\Release

**Comment by psychocrypt** [comment]
please use the guide from https://github.com/fireice-uk/xmr-stak/blob/dev/doc/compile_Windows.md.
I missed to add the copy to the guide. This is fixed in the dev branch and will be merged to master with the next release.
