### ISSUE TITLE
Errors compiling xmr-stak-rx on Lubuntu

### ISSUE THREAD

**Issue by prettygoodprogrammer** [fireice-uk/xmr-stak#2652]
Hello everyone,
so I wanted to run xmr-stak on my pc, on which I have installed Lubuntu (18.04 LTS) [32 bit OS]

I followed every step of [this](https://github.com/fireice-uk/xmr-stak/blob/xmr-stak-rx/doc/compile/compile_Linux.md) guide, but at the last command of the shell all I get are these errors:

> bru@bru-1025C:~/xmr-stak/build$ make install
[ 41%] Built target xmr-stak-randomx
[ 87%] Built target xmr-stak-rx-backend
[ 95%] Built target xmrstakrx_opencl_backend
[ 97%] Linking CXX executable bin/xmr-stak-rx
bin/libxmr-stak-randomx.a(virtual_memory.cpp.o): nella funzione "allocExecutableMemory(unsigned int)":
virtual_memory.cpp:(.text+0x1a): riferimento non definito a "xmrstak::VirtualMemory::allocateExecutableMemory(unsigned int)"
bin/libxmr-stak-randomx.a(virtual_memory.cpp.o): nella funzione "freePagedMemory(void*, unsigned int)":
virtual_memory.cpp:(.text+0x98): riferimento non definito a "xmrstak::VirtualMemory::freeLargePagesMemory(void*, unsigned int)"
bin/libxmr-stak-randomx.a(virtual_memory.cpp.o): nella funzione "allocLargePagesMemory(unsigned int, unsigned int)":
virtual_memory.cpp:(.text+0xd8): riferimento non definito a "xmrstak::VirtualMemory::allocateLargePagesMemory(unsigned int, unsigned int)"
collect2: error: ld returned 1 exit status
CMakeFiles/xmr-stak-rx.dir/build.make:106: recipe for target 'bin/xmr-stak-rx' failed
make[2]: *** [bin/xmr-stak-rx] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/xmr-stak-rx.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-rx.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone help me? I'm not so experienced so I do not know how to solve the problem.
Thank you.

**Comment by psychocrypt** [comment]
32bit OS is not supported. You need a 64bit OS.

**Comment by prettygoodprogrammer** [comment]
Thank you very much,
is there a way I could mine Xmr with a 32bit CPU? (I know it is highly inefficient, i just want to try for curiosity).

And, this is a little off topic, sorry for asking, i am very green with Linux OS and still learning.
How should I uninstall all the files i downloaded?

`sudo apt-get autoremove ~/xmr-stak` could do the job?

Thanks a lot for your time
