### ISSUE TITLE
Electroneum not working?

### ISSUE THREAD

**Issue by robmoggach** [fireice-uk/xmr-stak#266]
I used to be able to mine ETN as well as XMR with your miner but that sadly has stopped working. Any ideas?

**Comment by mt025** [comment]
It's working for me. I just selected monero when running the xmr-stak 2.2.0 for the first time.

**Comment by robmoggach** [comment]
must be the pool - close the issue

--
Robert Moggach
http://moggach.com
Mobile (647) 544-1793
