### ISSUE TITLE
Big difference in hashrate with Claymore.

### ISSUE THREAD

**Issue by cbesot** [fireice-uk/xmr-stak#267]
I used to use Claymore for CPu & GPU because I had problems with xmr-stak-amd and xmr-stak-cpu.

Today, I decided to compile the new xmr-stak2. Compilation was ok but with the number of CPU cores and different intensity and worksize for GPU, I lost 10% with GPU (310 -> 290) and CPU (200 -> 180) compared to Claymore.

It's it usual?

**Comment by psychocrypt** [comment]
Please post the hash rate table of the old xmr-stak and the new. And you configs used.

**Comment by carboneer** [comment]
Hi , i'm trying to use your new xmr-stak software for my amd card but i have some probleme :/
i don't know why but on xmr-stak i can't upgrade the intensity for some card .
Currently i'm using Claymore 9.7 and i get 2200 h/s and the lowest intensity at 480 
With xmr stak i can't go up to 1800 h/s and 360 intensity
