### ISSUE TITLE
Batch file for compiling under Windows

### ISSUE THREAD

**Issue by JerichoJones** [fireice-uk/xmr-stak#273]
This works for me every time.
VS 2017 Community
CMAKE 3.9.4
AMD SDK 3.0
CUDA 8 or 9 (Seperate VMs)

Modify 140/141 depending on CUDA version per the docs.

[CompileIt.cmd.txt](https://github.com/fireice-uk/xmr-stak/files/1508182/CompileIt.cmd.txt)

'@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual 
Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSLL DLLs
xcopy C:\xmr-stak-dep\openssl\bin\*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD'

**Comment by fireice-uk** [comment]
@JerichoJones Feel free to open a PR with it
