### ISSUE TITLE
unable to compile on windows 10 with VS 2017 community.

### ISSUE THREAD

**Issue by hotaru2k3** [fireice-uk/xmr-stak#275]
following the instructions from https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md, I get errors when running cmake:
`-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/hotar/OneDrive/Documents/GitHub/xmr-stak/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hotar/OneDrive/Documents/GitHub/xmr-stak/build/CMakeFiles/CMakeError.log".`

**Comment by psychocrypt** [comment]
please post all commands you used and the output

**Comment by hotaru2k3** [comment]
`C:\Users\hotar>cd c:\xmr-stak-dep

c:\xmr-stak-dep>tree .
Folder PATH listing
Volume serial number is 000001CA D653:75AF
C:\XMR-STAK-DEP
├───hwloc
│   ├───include
│   │   ├───hwloc
│   │   │   └───autogen
│   │   └───private
│   │       └───autogen
│   └───lib
├───libmicrohttpd
│   ├───include
│   └───lib
└───openssl
    ├───bin
    ├───include
    │   └───openssl
    └───lib

c:\xmr-stak-dep>cd c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak

c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
C:\Users\hotar\source>cd c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak

c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak>set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak>mkdir build

c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak>cd build

c:\Users\hotar\OneDrive\Documents\GitHub\xmr-stak\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/hotar/OneDrive/Documents/GitHub/xmr-stak/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hotar/OneDrive/Documents/GitHub/xmr-stak/build/CMakeFiles/CMakeError.log".`

**Comment by psychocrypt** [comment]
It looks like you have not installed the C++ compiler for visual studio. Please check you installation.

**Comment by hotaru2k3** [comment]
I installed visual studio and all the components that have anything to do with C++. regular visual studio projects using C++ compile fine.

**Comment by psychocrypt** [comment]
than please try to remove all files in the build folder. And start the
compile process again.
If that is not working try to start the visual studio command line from the
vs gui instead of using the bat file.

**Comment by hotaru2k3** [comment]
that's what I did to get the output I posted.

**Comment by hotaru2k3** [comment]
I removed the build folder completely before trying to build again, and output is the same whether I use visual studio command line or regular windows command prompt.

**Comment by Libbzter** [comment]
Ever figure this out?

**Comment by hotaru2k3** [comment]
no, never figured it out.

**Comment by lantama70** [comment]
You have to install the Toolkit for CMAKE as well in Visual Studio 2017. It is in the right side in the Installer. When it is marked it shows a subset for V141 which is needed.
