### ISSUE TITLE
Post full default/needed config

### ISSUE THREAD

**Issue by olstenlarck** [fireice-uk/xmr-stak#276]
Seems like there are tons of things that we should guess. I got the basic config from the `config.tpl` file and added single pool. But now it errors with some random things like `use_nicehash`, `use_tls` that are missing from the "Pool 0" config. When added it continues with another things like `tls_fingerprint`..

**Comment by psychocrypt** [comment]
Please do not copy the config.tpl and manipulate it. Remove your hand
created config and only start thr miner. The miner will create the config
which can be hand tuned after the first start.

**Comment by olstenlarck** [comment]
Nice. Worked perfectly. Good to point it out :)

**Comment by olstenlarck** [comment]
One more prompt question for how many cores to use would be great too :)
