### ISSUE TITLE
Can't build on Linux with CUDA (Debian Stretch)

### ISSUE THREAD

**Issue by elBradford** [fireice-uk/xmr-stak#278]
I have tried every combination of clang3.8, 3.9, 4.0, as well as cuda 8 and 9.

The errors are different each time, but limited to either a `cannot find libdevice for sm_xx` series of errors during compile time, or a segfault during runtime. 

The static linux binary is not listed on releases, plus I would like to build it myself anyway. Is there any hope for a better build process in the near future, or at least some specific environmental requirements? Thanks

**Comment by AndyLavr** [comment]
Use clang 5:

cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCUDA_COMPILER=clang -DCUDA_ARCH=52 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DXMR-STAK_CURRENCY=monero -DXMR-STAK_COMPILE=native -DCPU_ENABLE=ON -DCMAKE_BUILD_TYPE=Release -DOpenSSL_ENABLE=ON -DHWLOC_ENABLE=ON

Build fine.

**Comment by AndyLavr** [comment]
#!/bin/bash
#
cd xmr-stak
git pull
git clean -fdx
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCUDA_COMPILER=clang -DCUDA_ARCH=52 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DXMR-STAK_CURRENCY=monero -DXMR-STAK_COMPILE=native -DCPU_ENABLE=ON -DCMAKE_BUILD_TYPE=Release -DOpenSSL_ENABLE=ON -DHWLOC_ENABLE=ON
make install VERBOSE=1
exit 0

**Comment by psychocrypt** [comment]
@elBradford  The best is to use gcc 5.x. Clang is e.g. not compatible with CUDA9. If you prefer clang than you should use clang 4.X

**Comment by elBradford** [comment]
@AndyLavr 
Thanks for the tip - I installed clang 5, cuda 9, and tried your instructions. If I specify my cuda architecture (35) it says 

`clang: error: cannot find libdevice for sm_35. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.`

If I remove the DCUDA_ARCH flag entirely, it fails the same except it is for sm_70

@psychocrypt Thanks for the suggestion - I am having a hard time installing gcc5 on Debian stretch, apparently they moved gcc5 to unstable (??) and installing it will mess up a bunch of other dependencies.

**Comment by psychocrypt** [comment]
If you use clang than also use clang as device compiler. There is a flag
where you can change nvcc to clang. Best use `ccmake .` to change the flag

**Comment by elBradford** [comment]
@psychocrypt I have tried with and without the -DCUDA_COMPILER=clang flag. I essentially used @AndyLavr 's suggestion for mine:

`-DCMAKE_C_COMPILER=clang
-DCMAKE_CXX_COMPILER=clang++
-DCUDA_COMPILER=clang 
-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda 
-DOpenCL_ENABLE=OFF 
-DMICROHTTPD_ENABLE=ON 
-DXMR-STAK_CURRENCY=monero 
-DXMR-STAK_COMPILE=native 
-DCPU_ENABLE=ON 
-DCMAKE_BUILD_TYPE=Release 
-DOpenSSL_ENABLE=ON 
-DHWLOC_ENABLE=ON 
-DCMAKE_C_COMPILER=/usr/bin/clang-5.0 
-DCMAKE_CXX_COMPILER=/usr/bin/clang++-5.0`

**Comment by psychocrypt** [comment]
Forgot: the reason for the error
```
clang: error: cannot find libdevice for sm_35. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
```
is that debian has split CUDA in to includes and libs, this is not supported by clang. Debian will fix it in the next release. 
To fix this issue please compile CUDA8 by hand and not from the debian sources. Please use CUDA8 because I am not sure if clang is now supporting CUDA9.
Best use the run file: `wget https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda_8.0.44_linux-run` to install the driver and toolkit

**Comment by elBradford** [comment]
@psychocrypt 

I switched to CUDA 8 (leaving Clang=5.0) and the build succeeded. When I try to mine, however, it crashes after connecting to the pool with the following error:

`[CUDA] Error gpu 0: </root/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:322
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: invalid configuration argument
Aborted`

Any idea of what it means? I don't see any verbosity flags in `xmr-stak -h`

**Comment by elBradford** [comment]
If I make with gcc6  and CUDA 9 (flags below), it has the same error:

`cmake .. -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.0 -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DXMR-STAK_CURRENCY=monero -DXMR-STAK_COMPILE=native -DCPU_ENABLE=ON -DCMAKE_BUILD_TYPE=Release -DOpenSSL_ENABLE=ON -DHWLOC_ENABLE=ON -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++`

**Comment by fireice-uk** [comment]
LEt us know if you still have problems with the new versio

**Comment by propcoder** [comment]
Still no success..
I am following AndyLavr suggestion on Debian Stretch with Cuda installed as per these instructions: https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_9_.22Stretch.22-1

When I use commands: cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCUDA_COMPILER=clang -DCUDA_ARCH=61 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DXMR-STAK_CURRENCY=monero -DXMR-STAK_COMPILE=native -DCPU_ENABLE=ON -DCMAKE_BUILD_TYPE=Release -DOpenSSL_ENABLE=ON -DHWLOC_ENABLE=ON

-- Set miner currency to 'monero'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mes/dev/tmp/xmr-stak/build

make install VERBOSE=1

I get errors:
Scanning dependencies of target xmrstak_cuda_backend
make[2]: Leaving directory '/home/usr/dev/tmp/xmr-stak/build'
make -f CMakeFiles/xmrstak_cuda_backend.dir/build.make CMakeFiles/xmrstak_cuda_backend.dir/build
make[2]: Entering directory '/home/usr/dev/tmp/xmr-stak/build'
[ 80%] Building CXX object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu.o
/usr/bin/clang++   -DBACKEND_TYPE=nvidia-cpu -DCONF_NO_AEON=1 -DCONF_NO_OPENCL -DGIT_BRANCH=dev -DGIT_COMMIT_HASH=9fbe76c -DXMRSTAK_CUDA_ARCH_LIST=61 -DXMR_STAK_LARGEGRID=ON -Dxmrstak_cuda_backend_EXPORTS -I/home/usr/dev/tmp/xmr-stak/.  -march=native -mtune=native  -msse2 -maes -O3 -DNDEBUG -fPIC   -O3 -x cuda --cuda-path=/usr/local/cuda -ffp-contract=fast --cuda-gpu-arch=sm_61 -std=c++11 -o CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu.o -c /home/usr/dev/tmp/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
clang: error: Unsupported CUDA gpu architecture: sm_61
CMakeFiles/xmrstak_cuda_backend.dir/build.make:62: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu.o] Error 1
make[2]: Leaving directory '/home/usr/dev/tmp/xmr-stak/build'
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make[1]: Leaving directory '/home/usr/dev/tmp/xmr-stak/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
