### ISSUE TITLE
can't use AMD RX480 on debian

### ISSUE THREAD

**Issue by Kryschuuu** [fireice-uk/xmr-stak#280]
Hi, 
mining with cpu works well!

I'm rying to use my RX480 on debian stretch, but everytime I got a 

> JSON config parse error(offset 25): Missing a name for object member

issue. And terminal crashes. 

![xmr-stack](https://user-images.githubusercontent.com/5438686/33332043-7ecbd5d2-d463-11e7-813e-d733afc97d07.png)

What's wrong with my config
[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1510762/amd.txt)

[configamd.txt](https://github.com/fireice-uk/xmr-stak/files/1510771/configamd.txt)

ethminer works well with my GPU. 

Any suggestion?

**Comment by psychocrypt** [comment]
Please remove both files. Than start the miner. The miner will create the
files for you.

Am 28.11.2017 5:43 Nachm. schrieb "Kryschuuu" <notifications@github.com>:

**Comment by Kryschuuu** [comment]
Okay, thanks.  that works.
