### ISSUE TITLE
How can i compiling x32 version for windows?

### ISSUE THREAD

**Issue by Omnividente** [fireice-uk/xmr-stak#282]
i try 
`cmake .. -DXMR-STAK_CURRENCY=monero -DOpenCL_ENABLE=OFF  -DCUDA_ENABLE=OFF -DWIN_UAC=OFF -DXMR-STAK_COMPILE=generic`
but i get error 

"C:\xmr-stak-master\build\install.vcxproj" (целевой объект по умолчанию) (1) ->
"C:\xmr-stak-master\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) ->
"C:\xmr-stak-master\build\xmr-stak.vcxproj" (целевой объект по умолчанию) (4) ->
"C:\xmr-stak-master\build\xmr-stak-backend.vcxproj" (целевой объект по умолчанию) (5) ->
(ClCompile конечный объект) ->
  c:\xmr-stak-master\xmrstak\backend\cpu\crypto/cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to
do a 32-bit build. This will all end in tears. I know it. [C:\xmr-stak-master\build\xmr-stak-backend.vcxproj]
  c:\xmr-stak-master\xmrstak\backend\cpu\crypto\cryptonight_aesni.h(36): fatal error C1189: #error:  You are trying to
do a 32-bit build. This will all end in tears. I know it. [C:\xmr-stak-master\build\xmr-stak-backend.vcxproj]

**Comment by JerichoJones** [comment]
XMR-STAK does not support compilation for 32-bit.

**Comment by rsimenok** [comment]
Add this info in ```Readme.md``` please, because I end compilation in tears :)
