### ISSUE TITLE
GPU 0 problems

### ISSUE THREAD

**Issue by Punknoodles** [fireice-uk/xmr-stak#283]
I keep getting:
`[CUDA] Error gpu 0:
<C:/Users/MAIN/github/xmrstak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:244`

Updated CUDA, Visual Studio 2015 Community installed. Do I need to compile it myself? If so, how do I do that?

**Comment by Clintoxen** [comment]
You get this error when running the miner or trying to build it? @Punknoodles 

If you get it while running the miner change your bfactor a couple numbers higher inside the nvidia.txt file

**Comment by gtwy** [comment]
I had this same problem. Increasing bfactor to 8 on both my cards solved it. Thanks.
