### ISSUE TITLE
Error Make Install

### ISSUE THREAD

**Issue by ndalexnov** [fireice-uk/xmr-stak#284]
x21211@xxx:~/xmr-stak/build$ make install
[  4%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
/tmp/cc5VJBwy.s: Assembler messages:
/tmp/cc5VJBwy.s:91: Error: no such instruction: `kmovq %rsi,%k1'
/tmp/cc5VJBwy.s:92: Error: no such instruction: `kmovq -72(%rsp),%k2'
/tmp/cc5VJBwy.s:93: Error: no such instruction: `kxorq %k2,%k1,%k0'
/tmp/cc5VJBwy.s:94: Error: no such instruction: `kmovq -64(%rsp),%k4'
/tmp/cc5VJBwy.s:95: Error: no such instruction: `kmovq -104(%rsp),%k3'
/tmp/cc5VJBwy.s:96: Error: no such instruction: `kmovq %k0,%r8'
/tmp/cc5VJBwy.s:97: Error: no such instruction: `kxorq %k4,%k3,%k0'
/tmp/cc5VJBwy.s:98: Error: no such instruction: `kmovq -96(%rsp),%k5'
/tmp/cc5VJBwy.s:99: Error: no such instruction: `kmovq -56(%rsp),%k6'
/tmp/cc5VJBwy.s:100: Error: no such instruction: `kmovq %k0,%rbx'
/tmp/cc5VJBwy.s:102: Error: no such instruction: `kxorq %k6,%k5,%k0'
/tmp/cc5VJBwy.s:103: Error: no such instruction: `kmovq -88(%rsp),%k7'
/tmp/cc5VJBwy.s:104: Error: no such instruction: `kmovq -48(%rsp),%k1'
/tmp/cc5VJBwy.s:105: Error: no such instruction: `kmovq %k0,%r11'
/tmp/cc5VJBwy.s:106: Error: no such instruction: `kxorq %k1,%k7,%k0'
/tmp/cc5VJBwy.s:111: Error: no such instruction: `kmovq -80(%rsp),%k2'
/tmp/cc5VJBwy.s:114: Error: no such instruction: `kmovq %k0,%rbx'
/tmp/cc5VJBwy.s:117: Error: no such instruction: `kmovq -40(%rsp),%k3'
/tmp/cc5VJBwy.s:119: Error: no such instruction: `kxorq %k3,%k2,%k0'
/tmp/cc5VJBwy.s:120: Error: no such instruction: `kmovq %k0,%r13'
/tmp/cc5VJBwy.s:140: Error: no such instruction: `kmovq %k4,%r8'
/tmp/cc5VJBwy.s:147: Error: no such instruction: `kmovq %k3,%r13'
/tmp/cc5VJBwy.s:151: Error: no such instruction: `kmovq %k5,%r9'
/tmp/cc5VJBwy.s:174: Error: no such instruction: `kmovq %k2,%r9'
/tmp/cc5VJBwy.s:178: Error: no such instruction: `kmovq %k1,%r14'
/tmp/cc5VJBwy.s:199: Error: no such instruction: `kmovq %k7,%r9'
make[2]: *** [CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-c.dir/all] Error 2
make: *** [all] Error 2

Please help me. I dont know how to fix this

**Comment by JollyMort** [comment]
Did you follow the instructions [here](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md) and installed all dependencies?

**Comment by ndalexnov** [comment]
Yes, i follow the instructions there. Anyway, i now mining xmr-stak-cpu for
all my vps now its working fine, i

Vào 05-12-2017 3:00, "Jolly Mort" <notifications@github.com> đã viết:
