### ISSUE TITLE
4x Vega 56 Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for kernel 0.

### ISSUE THREAD

**Issue by oxzhor** [fireice-uk/xmr-stak#286]
I use the last version of xmr-stak and get the follow error:
`Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for kernel 0.`

Setup:
`0000 Internal gpu
0001 Radeon RX Vega
0002 Radeon RX Vega
0003 Radeon RX Vega
0004-Radeon RX Vega`

amd.txt
`/* 
 * Number of GPUs that you have in your system. Each GPU will get its own CPU thread.
 */
"gpu_thread_num" : 8,

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 */
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 0, "intensity" : 1600, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 1, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 1, "intensity" : 1600, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 2, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 2, "intensity" : 1600, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 3, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 3, "intensity" : 1600, "worksize" : 8, "affine_to_cpu" : false },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,`

If i change the index to 1,2,3,4 i get
` Selected OpenCL device index 4 doesn't exist.`

How i can solved this issue?

**Comment by psychocrypt** [comment]
Is the suggested config running?
You can try to increase the memory which canbe used by the miner.
https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md#increase-memory-pool

You can also set the values to 100 instead of 99.
Decrease the intensity if the miner is still crashing.

**Comment by oxzhor** [comment]
In which file do i add that parameters ?

**Comment by gurupras** [comment]
I'm facing a similar issue. I have set the environment variables, but despite that the default configuration does not run.
```
"gpu_threads_conf" : [
  // gpu: gfx900 memory:8048
  // compute units: 56
  { "index" : 0,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:8048
  // compute units: 56
  { "index" : 1,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:8048
  // compute units: 56
  { "index" : 2,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:8048
  // compute units: 56
  { "index" : 3,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },
  // gpu: gfx900 memory:8048
  // compute units: 56
  { "index" : 4,
    "intensity" : 1792, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 2, "mem_chunk" : 2,
    "unroll" : 8, "comp_mode" : true
  },

],
```

**Comment by Spudz76** [comment]
This thread is from almost a year ago and was closed, please open a new issue instead of gravedigging.
Code has changed quite a bit since a year ago.
dev branch currently contains giant pile of AMD fixes you probably need, may have been fixed already
checkout dev and build and try that, or await next release
