### ISSUE TITLE
NVIDIA Invalid Result - occurs regularly with unified miner but not with xmr-stak-nvidia

### ISSUE THREAD

**Issue by ElectroMW** [fireice-uk/xmr-stak#289]
Hi guys,
First off, Thank you!  Great software package.
Now on to the bug :)

It's really as the title describes. 
Using the combined miner I get frequent "Nvidia invalid result" errors  (approx 5-15% of total hashes running combined cpu/gpu mining).
There seems to be a slight correlation between hash rate and these results but it is largely the same rate even after dropping max hash rate by 30%.

On the most recent release of the xmr-stak-nvida tool with the same settings I get none of these errors.
C is not my strongpoint so I don't feel brave enough to start hypothesising :)

Setup:
Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz - 3 cores running at approx 70H/s
GPU 1 - GTX 1050 Ti - 220 H/s (30% down on max I have previously achieved [315H/s])
GPU 2 - GT730          - 75 H/s (managed a max of about 100 H/s)

Config: nvidia.txt (note with xmr-stak-nvidia I have the same same settings in config.txt)
 // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3554/4035 MiB
  //      smx: 6
 { "index" : 0,
    "threads" : 4, "blocks" : 36, 
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : 3,
  },
  // gpu: GeForce GT 730 architecture: 35
  //      memory: 1973/2001 MiB
  //      smx: 2
  { "index" : 1,
   "threads" : 60, "blocks" : 2,
   "bfactor" : 0, "bsleep" :  0,
   "affine_to_cpu" : 3,
  },

Please let me know if you need any more info.

**Comment by psychocrypt** [comment]
Please post the commands which do you used to compile the miner.
Try also to reduce the number of threads a little bit.

**Comment by ElectroMW** [comment]
to compile it would have been ;

cmake -DOpenCL_Enable=OFF 

I have tested the cards individually with both settings. 
The GT730 was very rarely reporting the issue with the above config.
The 1050 was with all combinations of low and high thread and block count

**Comment by psychocrypt** [comment]
Which of both gpus creates the errors?

**Comment by ElectroMW** [comment]
Both, but the main cause is the 1050.
With the 730 in that config it very rarely does.

**Comment by mdcosh** [comment]
I also experience this with a 1060. CUDA 7.5.17

**Comment by fireice-uk** [comment]
Unfortunately the cause here is usually a bad card. Different code will use it slightly differently, so if the old version works better, use that one. This is the reason why I'm keeping the old repositories up.

**Comment by drbuckingham** [comment]
I disagree with that determination.  Perhaps sometimes it is a faulty card, but specifically in my case the card throws no such errors using ccminer performing aeon mining.  I even see significantly different results when mining to different pools:  aeonpool.dreamitsystems.com yields good results 95+%, yet pool.aeonhash.com yields good results 72-84%.  Those numbers are over hours of testing each pool.  There is something beyond "a bad card" at play.
[CMakeCache.txt](https://github.com/fireice-uk/xmr-stak/files/1584955/CMakeCache.txt)

**Comment by drbuckingham** [comment]
I tried an alternate setup by running xmr-stak with the --noCPU flag, with the configuration remaining the same otherwise.  The result is enlightening:  0% good results after 15 minutes (meaning that the above success rates were solely due to the CPU).  Bear in mind that the card works perfectly fine with ccminer, so I fail to understand how it is "a bad card".

**Comment by psychocrypt** [comment]
please try to lower the threads in nvidia.txt. It could be that your card
is to slow and this is the reason for the wrong results. Could it be that
you have also a bad internet connection?

**Comment by drbuckingham** [comment]
While my internet connection is not great, it has caused no issues for any of my other miners.  Lowering the threads did not yield a better percentage, but it did drop my hashrate.  The original configuration of threads * blocks * 2 is less than my GPU memory as per the configuration guideline.  Higher threads or blocks and it fails to run and lower threads or blocks yields a lower hashrate.

**Comment by Znuff** [comment]
I've stumbled upon this issue by accident, and thank fuck that I did.

I did my own test on 10 identical rigs.

`xmr-stak` always results in only 65-70% success rate, while running `xmr-stak-nvidia` is at 92-95% (I've got some network issues with a rebooting switch, but nothing too important right now).

I'm using the same settings (threads/blocks) on all the rigs, I'm using the same overclocking settings etc., I simply can't get `xmr-stak` to play nicely.

I'm getting a stable 4500H/s with 8 x nVidia P106-100 @ +1300Mhz memory and base core clock.

**Comment by jrodrigog** [comment]
It does not seem to be a card issue (GTX 970 here)...
I'm having the "NVIDIA errorz" of the death... And diving always to ~77% success.
I does not matter the memory settings nor the threads settings nor the fixed diff.

**Comment by markdjones82** [comment]
I will also say that this appears to be more frequent with my GTX 1060.

**Comment by ElectroMW** [comment]
Now with the monero7 changes, using the nvidia miner is no longer an option. Is it possible for this ticket to be re-examined or can/has someone updaate the nvidia miner to use monero7?
