### ISSUE TITLE
Cannot find CUDA

### ISSUE THREAD

**Issue by Kuhitacop** [fireice-uk/xmr-stak#290]
Hello, I have the following errors:
https://gyazo.com/14c17678ae260bbd89231d0cc3490485
https://gyazo.com/525303a9f7bef041b410272084818604
https://gyazo.com/a37c28cf9ca42531d4ae2e0a2514326a
Please help me :(
Maybe something is in Spanish but I didn't translate because I don't see anything important.

**Comment by InFerYes** [comment]
Do you have an AMD GPU?

**Comment by Kuhitacop** [comment]
Nvidia GTX 970 and Intel Core i5

**Comment by JerichoJones** [comment]
I use the below batch file to compile without issue with CUDA 8 or 9 (Separate compile machine per CUDA version). Change:

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

to suit your CUDA version per the compile guide.

@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSSL DLLs
xcopy C:\xmr-stak-dep\openssl\bin*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD
