### ISSUE TITLE
Pools of same weight - sends results to both. 

### ISSUE THREAD

**Issue by se5a** [fireice-uk/xmr-stak#292]
with multiple pools, if they have the same weight, it appears to send a result to both pools, causing a rejection.

**Comment by fireice-uk** [comment]
Can you please include full logs?

**Comment by se5a** [comment]
I've not been able to reproduce this now, possibly I misinterpreted the data it was outputting. What I saw the first time I ran it was something like this:

New block detected.
Result accepted by the pool.
Result Rejected by the pool.
New block detected.
New block detected.
New block detected.
Result accepted by the pool.
Result Rejected by the pool.

a rejection after an acception happening multiple times seemed an unlikely coincidence, and I must have jumped to a conclusion.
