### ISSUE TITLE
Problems loading Nvidia backend

### ISSUE THREAD

**Issue by almijal** [fireice-uk/xmr-stak#294]
Hey everyone,

First off, thanks for taking the time to write this library, and thanks in advance for your help!

I am having the following error when running the program after compiling. I am on Ubuntu 17.10 with Nvidia CUDA 9. During compiling, I set both the CUDA_SDK_ROOT_DIR and CUDA_TOOLKIT_ROOT_DIR to /usr/local/cuda... is this correct, or are there two separate directories here?
 

[2017-11-29 16:34:43] : MEMORY ALLOC FAILED: mmap failed
[2017-11-29 16:34:43] : MEMORY ALLOC FAILED: mmap failed
{ splash screen }
[2017-11-29 16:34:43] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: libxmrstak_cuda_backend.so: cannot open shared object file: No such file or directory
WARNING: NVIDIA Backend disabled
[2017-11-29 16:34:43] : WARNING: backend NVIDIA disabled.

**Comment by psychocrypt** [comment]
Is the file libxmrstak_cuda_backend.so in the same directory than the
xmr-stak binary?

**Comment by almijal** [comment]
During building I got this message, but the file doesn't appear to have been generated.


[ 82%] Linking CXX shared library bin/libxmrstak_cuda_backend.so
[ 82%] Built target xmrstak_cuda_backend

**Comment by psychocrypt** [comment]
please type the full log of the build process and a ls from the bin folder.

**Comment by almijal** [comment]
I rebuilt xmr-stak and it now appears all of the files are in place. I can successfully run it now, but still get  this error message, and the program hangs my whole OS. If this isnormal, then case closed.

[2017-11-29 17:09:38] : MEMORY ALLOC FAILED: mmap failed
