### ISSUE TITLE
NVIDIA Backend/Architecture Error

### ISSUE THREAD

**Issue by slomeleon** [fireice-uk/xmr-stak#295]
Hey there. Brand new to mining so if I am doing something completely wrong, yell at me.

With no NVIDIA file I get 

ERROR
`WARNING: backend NVIDIA disabled.`

If I add my code to the file I get

CODE
```
"gpu_threads_conf" :
[
	{ "index" : 0, "threads" : 16, "blocks" : 32, "bfactor" :0, "bsleep" :  0, "affine_to_cpu" : false},
],
```

ERROR
```
WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 20.
[2017-11-29 18:48:46] : Setup failed for GPU 0. Exitting.
```

Let me know what information you need. Everyday PC just mining on the side and when I go into the office even if it's nothing.
i7 6700k
GTX 570
Version: xmr-stak 2.0.0 0005e4a

CPU mining works fine.

**Comment by briard51** [comment]
`rm CMakeCahe.txt`
`cmake .. -DCUDA_ARCH=20 `
`make`

Enjoy

**Comment by sergneo** [comment]
the same situation, how to compile ?
WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 21.
[2017-11-30 12:37:13] : WARNING: NVIDIA setup failed for GPU 0.

**Comment by briard51** [comment]
cmake .. -DCUDA_ARCH=21

**Comment by slomeleon** [comment]
Sorry where do I do this? Just in a command prompt? Do I have to be in a specific directory?

**Comment by briard51** [comment]
In your terminal
```
make clean
rm CMakeCahe.txt
cmake .. -DCUDA_ARCH=21
make
```
All these things are explain here: [https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md)

**Comment by slomeleon** [comment]
@briard51 Sorry did not see any of this before. Not a developer really so github is pretty foreign to me. So from what I'm reading...
1. Read https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md for understanding
2.

**Comment by sergneo** [comment]
Compiling with-DCUDA_ARCH=21 fails. Tired of these problems.
I didn't like it, went back to the old version of the xmr-stak-nvidia and cpu.

**Comment by slomeleon** [comment]
@briard51 I feel really dumb now. I work in IT and am having trouble figuring this out. Following this link https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md at one point do you enter what you've given me into the terminal?

**Comment by briard51** [comment]
Sorry, you have a windows version.
I can't help you...

**Comment by sergneo** [comment]
the solution here -> https://github.com/fireice-uk/xmr-stak/issues/330

**Comment by fireice-uk** [comment]
@sergneo I would appreciate if you plugged xmrig on their own repo and not here.
