### ISSUE TITLE
complie with 2017

### ISSUE THREAD

**Issue by jackkite** [fireice-uk/xmr-stak#296]
hi,i have succeed code with vs2017,But a problem, I can compile normally, but at run time (in debug mode) error, I intercept the exception, please help me see
![qq 20171130151428](https://user-images.githubusercontent.com/33998508/33418532-442f8926-d5e1-11e7-911d-c93d745574b8.png)
![qq 20171130151436](https://user-images.githubusercontent.com/33998508/33418533-446896d0-d5e1-11e7-8fb4-8575a0aef330.png)
![qq 20171130151456](https://user-images.githubusercontent.com/33998508/33418534-449dd9d0-d5e1-11e7-9855-bffab6719c52.png)

**Comment by psychocrypt** [comment]
Please follow exactly [this guide](https://github.com/fireice-uk/xmr-stak/blob/38fadae0b666bbaf45208cb1eae17763a286f3a0/doc/compile_Windows.md) to compile the miner.

btw: the last gui windows says that you compile `xmrig` bu this reposetory is for `xmr-stak`.

**Comment by fireice-uk** [comment]
Try using our miner, you can find it here -> https://github.com/fireice-uk/xmr-stak/releases
