### ISSUE TITLE
Error while compiling on Ubuntu 17.10

### ISSUE THREAD

**Issue by MattMattV** [fireice-uk/xmr-stak#297]
gcc version : `gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)`

Using the dev version @ bd8d84a, I followed Linux compile instructions :

- Downloaded Cuda 9 toolkit in `.run` used `--silent --toolkit --override` options (otherwise it would not have installed)
- Applied "patch" mentioned here : https://github.com/xmrMiner/xmrMiner/blob/master/INSTALL.md#software
- Installed dependencies from Linux compile instructions and then executed :
```
mkdir xmr-stak/build
cd xmr-stak/build
cmake ..
make install
```
I put you the error log in a gist : https://gist.github.com/MattMattV/3cf49181474961cdaa8d4c3aff70a94c

Let me know if you need more information ! (:

**Comment by AndyLavr** [comment]
Use clang 5:

#!/bin/bash
#git clone -b dev https://github.com/fireice-uk/xmr-stak.git
cd xmr-stak
git pull
git clean -fdx
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCUDA_COMPILER=clang -DCUDA_ARCH=52 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=ON -DXMR-STAK_CURRENCY=monero -DXMR-STAK_COMPILE=native -DCPU_ENABLE=ON -DCMAKE_BUILD_TYPE=Release -DOpenSSL_ENABLE=ON -DHWLOC_ENABLE=ON
make install VERBOSE=1
exit 0

Build fine. https://gist.github.com/AndyLavr/d3fc2f02eab896e40ece1f2046a2cf71

**Comment by MattMattV** [comment]
Thank you for your quick answer ! I also combined this : https://github.com/fireice-uk/xmr-stak-nvidia/issues/155#issuecomment-344530118 and now I have a new issue :disappointed:
