### ISSUE TITLE
Issue with compiling in Arch Linux

### ISSUE THREAD

**Issue by wsaenot** [fireice-uk/xmr-stak#299]
Hi I am trying to compile this in archlinux.  I am getting the following error:

/home/miner/xmr-stak/xmrstak/backend/NVidia/nvcc_code/cuda_core.cu(171): error: attributes are not allowed here.

Anyone can help me?

**Comment by psychocrypt** [comment]
lease do not set XMR-STAK_THREADS there is an bug whixh is fixed in the dev
branch.

**Comment by wsaenot** [comment]
Thanks guys managed to compile fine but now I cannot run the miner. I get this following error:

`[CUDA] Error gpu 1: </home/miner/xmr-stak/xmrstak/backend/NVidia/nvcc_code/cuda_core.cu>:341
terminate called after throwing an instance of 'std::runtime_error'
    what():    [CUDA]  Error:  invalid argument
[CUDA] Error gpu Aborted (core dumped)`

I am running GTX780, GTX680, GTX670, GTX950.
OS: Arch Linux

**Comment by briard51** [comment]
You need to reduce the value of Threads and Blocks for each card and it should work.

**Comment by wsaenot** [comment]
Thank you it works now!
