### ISSUE TITLE
Feature Request: Enable test run

### ISSUE THREAD

**Issue by xpat07** [fireice-uk/xmr-stak#301]
If possible would be nice to make 1-5 minutes long test run without connecting to pool and print kind of reference performance Hashrate for given configuration.

XMR-STAK.EXE --testRun

**Comment by psychocrypt** [comment]
why not mining against a real pool? The results will be equal

**Comment by xpat07** [comment]
I am just new here. I have few systems with different Hardware, different OS. My hash rate in real pools jumps +- 30%. With –testRun option users can measure performance, automate testing different configurations and releases. (Threads, intensity, low_power_mode, etc). Is there some other way to do this?

**Comment by psychocrypt** [comment]
The hashbrate shown in the miner should not jump 30% if you are connected
to a real pool. If so than something is wrong with your setup. Do you have
network isses?

**Comment by xpat07** [comment]
Yes network, I will check ASAP.

08:39
Hash Rate	       	1 Hour Avg. 	       24 Hour Avg. 
567 H/s    <21%>	717 H/s	    <11%>   644 H/s	

08:46
658 H/s     <4%>	686 H/s	     <6%>    643 H/s	

This is from supportxmr.com, which of these HashRates should I use for tuning?

**Comment by xpat07** [comment]
I will try report API. Thanks
