### ISSUE TITLE
Mediocre hashrates w/ Vegas

### ISSUE THREAD

**Issue by joeyblow** [fireice-uk/xmr-stak#303]
Hi,
Total noob question here. Since the release of this new cpu/gpu miner, I’ve been unable to figure out how to run 2 threads for each Vega as in previous versions (assuming that’s the reason for poor results), since the config file is different. What am I doing wrong?

![3d3d2f4e-23b8-4b1c-ae13-74f3573ccaca](https://user-images.githubusercontent.com/33847396/33452565-e3648be8-d5cf-11e7-841b-aaf47bb78e85.jpeg)
![d9948e6e-62ae-4cf3-b4fa-440e7d74beb2](https://user-images.githubusercontent.com/33847396/33452588-f43f6eec-d5cf-11e7-8564-23d6283f4a2d.jpeg)

**Comment by ledbg** [comment]
https://github.com/fireice-uk/xmr-stak/issues/300

**Comment by joeyblow** [comment]
Nice! Thank you. That did the trick.

**Comment by psychocrypt** [comment]
I will close this issue because it looks like it is solved.
