### ISSUE TITLE
cmake --build . --config Release --target install

### ISSUE THREAD

**Issue by Tekmekanik** [fireice-uk/xmr-stak#307]
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-11-30 5:06:31 PM.
Project "C:\Users\Profound\source\build\install.vcxproj" on node 1 (default targets).
Project "C:\Users\Profound\source\build\install.vcxproj" (1) is building "C:\Users\Profound\source\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\Profound\source\build\ZERO_CHECK.vcxproj" (default targets).

Project "C:\Users\Profound\source\build\install.vcxproj" (1) is building "C:\Users\Profound\source\build\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
Project "C:\Users\Profound\source\build\ALL_BUILD.vcxproj" (3) is building "C:\Users\Profound\source\build\xmr-stak-nvidia.vcxproj" (4) on node 1 (default targets).
Project "C:\Users\Profound\source\build\xmr-stak-nvidia.vcxproj" (4) is building "C:\Users\Profound\source\build\xmr-stak-nvidiaCrypto.vcxproj" (5) on node 1 (default targets).
InitializeBuildStatus:
  Creating "xmr-stak-nvidiaCrypto.dir\Release\xmr-stak.F3E05E06.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  xmr-stak-nvidiaCrypto.vcxproj -> C:\Users\Profound\source\build\Release\xmr-stak-nvidiaCrypto.lib
FinalizeBuildStatus:
  Deleting file "xmr-stak-nvidiaCrypto.dir\Release\xmr-stak.F3E05E06.tlog\unsuccessfulbuild".
  Touching "xmr-stak-nvidiaCrypto.dir\Release\xmr-stak.F3E05E06.tlog\xmr-stak-nvidiaCrypto.lastbuildstate".
Done Building Project "C:\Users\Profound\source\build\xmr-stak-nvidiaCrypto.vcxproj" (default targets).

Project "C:\Users\Profound\source\build\xmr-stak-nvidia.vcxproj" (4) is building "C:\Users\Profound\source\build\xmr-stak-nvidiaCuda.vcxproj" (6) on node 1 (default targets).
InitializeBuildStatus:
  Touching "xmr-stak-nvidiaCuda.dir\Release\xmr-stak.C07AF97B.tlog\unsuccessfulbuild".
CustomBuild:
  Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/Release/xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj
  nvcc fatal   : Unsupported gpu architecture 'compute_20'
  CMake Error at xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Users/Profound/source/build/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/Release/xmr-stak-nvidiaCuda_generated_cuda_core.cu.obj

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Profound\source\build\xmr-stak-nvidiaCuda.vcxproj]
Done Building Project "C:\Users\Profound\source\build\xmr-stak-nvidiaCuda.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Profound\source\build\xmr-stak-nvidia.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Profound\source\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\Profound\source\build\install.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Profound\source\build\install.vcxproj" (default target) (1) ->
"C:\Users\Profound\source\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\Profound\source\build\xmr-stak-nvidia.vcxproj" (default target) (4) ->
"C:\Users\Profound\source\build\xmr-stak-nvidiaCuda.vcxproj" (default target) (6) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Profound\source\build\xmr-stak-nvidiaCuda.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.57

I have no idea where to start, I'm a hardware guy. I guessing it's a cuda problem, I have cuda toolkit 9 installed as per the compile guide.

**Comment by SlaytanicPB** [comment]
try downloading the code base from the main page by clicking the green button that says "Clone or Download.  Find cuda_core.cu and copy/paste that file into the same directory that is in your build directory.  That's what worked for me...

**Comment by JerichoJones** [comment]
I use the below batch file to compile without issue with CUDA 8 or 9 (Separate compile machine per CUDA version). Change:

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..

to suit your CUDA version per the compile guide.

@echo off
PUSHD %~DP0
echo ########## Running VsMSBuildCmd.bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
echo ########## Setting CMAKE_PREFIX_PATH
set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
echo ########## Making build directory
mkdir build
echo ########## Changing to build directory
cd build
echo ########## Running cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
echo ########## Running cmake --build . --config Release --target install
cmake --build . --config Release --target install
echo ########## Changing to bin\Release directory
cd bin\Release
echo ########## Copy OpenSSL DLLs
xcopy C:\xmr-stak-dep\openssl\bin*.dll . /v
echo ########## Running Explorer
explorer.exe .
echo ########## Done... Exiting
POPD
