### ISSUE TITLE
Unable to locate Win64 files for download

### ISSUE THREAD

**Issue by hashaway** [fireice-uk/xmr-stak#310]
Hello,

Thank you for the new miner :o)

The following files are not listed for download with the latest 19 November 2017 update:

 "xmr-stak-cpu-notls-win64.zip" and "xmr-stak-cpu-win64.zip" 

Are you going to make those files available for download with this latest release? (they are available for all the older releases).

Please see:
https://github.com/fireice-uk/xmr-stak-cpu/releases
AND
https://github.com/fireice-uk/xmr-stak-cpu/releases/tag/final

Visual Studio is too big for many of us to download and compile the source. (Most of us just want to install, configure and hit the road running :o)

Looking forward to your response :o)

Thank you.

**Comment by aaronsace** [comment]
https://github.com/fireice-uk/xmr-stak/releases

**Comment by slash333hp** [comment]
Thank you.  the link on the main page brings us to "https://github.com/xmr-stak/xmr-stak/releases" which doesn't exist instead of this page.

**Comment by JerichoJones** [comment]
Link has been fixed. Thanks!
