### ISSUE TITLE
Compilation fails on ubuntu server 16.04.5

### ISSUE THREAD

**Issue by 941design** [fireice-uk/xmr-stak#312]
+ fresh install of ubuntu server 16.04
+ cuda 9.0
+ gcc 5.4.0
+ cmake 3.5.1
+ make 4.1

make install fails with:

...
[ 70%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(184): error: identifier "__builtin_ia32_pf2iw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(190): error: identifier "__builtin_ia32_pfnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(196): error: identifier "__builtin_ia32_pfpnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(202): error: identifier "__builtin_ia32_pi2fw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(208): error: identifier "__builtin_ia32_pswapdsf" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_00000634_00000000-14_cuda_extra.compute_70.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake:266 (message):
  Error generating file
  /home/user/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

CMakeFiles/xmrstak_cuda_backend.dir/build.make:70: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psychocrypt** [comment]
please post all commands used and the full output

**Comment by 941design** [comment]
I might have duplicated: https://github.com/fireice-uk/xmr-stak/issues/202
I'll check there first.
Sorry.

**Comment by 941design** [comment]
~/xmr-stak/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "7.5") 
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/xmr-stak/build

~/xmr-stak/build$ make install
Scanning dependencies of target xmr-stak-c
[  2%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 17%] Linking C static library bin/libxmr-stak-c.a
[ 17%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 20%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 29%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 35%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 47%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 58%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 67%] Linking CXX static library bin/libxmr-stak-backend.a
[ 67%] Built target xmr-stak-backend
[ 70%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(184): error: identifier "__builtin_ia32_pf2iw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(190): error: identifier "__builtin_ia32_pfnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(196): error: identifier "__builtin_ia32_pfpnacc" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(202): error: identifier "__builtin_ia32_pi2fw" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mm3dnow.h(208): error: identifier "__builtin_ia32_pswapdsf" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_000008da_00000000-14_cuda_extra.compute_70.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.cmake:266 (message):
  Error generating file
  /home/user/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


CMakeFiles/xmrstak_cuda_backend.dir/build.make:70: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psychocrypt** [comment]
It looks like something is wrong with you compiler. Could you test a nother
version of gcc or try to downgrade your cudua to cuda8

**Comment by psychocrypt** [comment]
wait thats something with the cuda architecture 70. Please run `ccmake .`
within the build folder and remove 70 from the list of the variable
CUDA_ARCH

**Comment by 941design** [comment]
Failed to downgrade gcc on ubuntu. Ended up using arch-linux, because I know that system better, and got it working there. Some of the other things I had to do:
* downgrade to gcc-5
* downgrade to cuda-8, because my old nvidia card used the 'Fermi' instruction set
Issue can be closed. Thanks for your help. And keep up the good work.

**Comment by 941design** [comment]
Failed to downgrade gcc on ubuntu. Ended up using arch-linux, because I know that system better, and got it working there. Some of the other things I had to do:
* downgrade to gcc-5
* downgrade to cuda-8, because my old nvidia card used the 'Fermi' instruction set
Issue can be closed. Thanks for your help. And keep up the good work.
