### ISSUE TITLE
Cannot run miner on Fedora 27

### ISSUE THREAD

**Issue by fascineroso** [fireice-uk/xmr-stak#316]
I have a i7-6700HQ CPU and NVIDIA 960M GPU. I have been running xmr-stak-cpu and xmr-stak-nvidia, with no problems, but trying to run the new xmr-stak fails (even though, it doesn't show any errors)

$ sudo optirun ./xmr-stak 
-------------------------------------------------------------------
xmr-stak 2.0.0 79154f7

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-01 22:22:39] : Start mining: MONERO
[2017-12-01 22:22:39] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-01 22:22:39] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-01 22:22:39] : WARNING: backend AMD disabled.
[2017-12-01 22:22:39] : Starting single thread, affinity: 0.
[2017-12-01 22:22:39] : hwloc: memory pinned
[2017-12-01 22:22:39] : Starting single thread, affinity: 1.
[2017-12-01 22:22:39] : hwloc: memory pinned
[2017-12-01 22:22:39] : Starting single thread, affinity: 2.
[2017-12-01 22:22:39] : hwloc: memory pinned

**Comment by psychocrypt** [comment]
what do you mean with it fails? Is the miner freezing,...

**Comment by psychocrypt** [comment]
It could be that you need to enable the option daemon_mode in confi.txt.
This can be a side effect of optirun.

**Comment by fascineroso** [comment]
Thanks for the reply!
I have tried that mode, but no luck, still doesn't really start up.
I have look at dmesg and I have seen this:

**Comment by fascineroso** [comment]
So it looks like CPU mining could work, but the GPU is causing the failure, which is strange, because running xmr-stak-nvidia works (I use optirun, but I don't need to use "sudo", however, if I don't use sudo with xmr-stak, I see memory pinning failures)

**Comment by fireice-uk** [comment]
Different code will use the card slightly differently. If it is close to failing this is what makes the difference between it running or not. I will keep the old repos up, so you are welcome to use an older version.
