### ISSUE TITLE
Error while starting xmr-stak.exe on Windows 10 with AMD R7 M270

### ISSUE THREAD

**Issue by SharnamK** [fireice-uk/xmr-stak#317]
I used the following steps:
1) Unzip xmr-stak into C:\xmr-stak
2) Unzip xmr-stak-dep into C:\xmr-stak-dep

3) go here C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools and run LaunchDevCmd as admin

4) cd c:\xmr-stak

5) set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

6) mkdir build

7) cd build

8) cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. C:\xmr-stak -DCPU_ENABLE=OFF -DCUDA_ENABLE=OFF -DHWLOC_ENABLE=OFF

9) cmake --build . --config Release --target install

The following are the files in the /xmr-stak-master/build/bin/release after my successful build (although the build gave a few warnings which i ignored)

![files](https://user-images.githubusercontent.com/23208029/33507246-b684962c-d719-11e7-933b-5f042d7d69e1.png)

I get the following errors on double clicking xmr-stak.exe
namely
1) The program can't  start because LIBEAY32.dll is missing from your computer.  Try reinstalling the program to fix this problem.
2)The program can't  start because SSLEAY32.dll is missing from your computer.  Try reinstalling the program to fix this problem.

![error1](https://user-images.githubusercontent.com/23208029/33507278-eddd06f4-d719-11e7-9404-d77e9f407b6a.png)

and 
![error2](https://user-images.githubusercontent.com/23208029/33507290-f84931ee-d719-11e7-9b57-83216a10cf99.png)

Which is weird because i already have LIBEAY32.dll and SSLEAT32.dll in the xmr-stak-dep folder in C:\
![lib](https://user-images.githubusercontent.com/23208029/33507465-e2f0bdde-d71a-11e7-9806-583a2471d391.png)

Can anyone help me find where i'm going wrong?
**EDIT** - FIXED.

**Comment by SharnamK** [comment]
As suggested in a closed issue, i tried copying both of the files from /xmr-stak-dep/openssl/lib to the working directory where xmr-stak.exe lives, but still getting the same error

**Comment by SharnamK** [comment]
I apologise for not going through the closed issues before making my own. Copying the files from xmr-stak-dep/openssl to the directory where the xmr-stak.exe lived worked for me.

**Comment by SharnamK** [comment]
Reopened because I am facing 2 problems as of now
1) my GPU is mining but my CPU isn't. Is it because i added the C:\xmr-stak -DCPU_ENABLE=OFF during cmake?
How do i fix this? I want my CPU to be mining as well. 

2) I see this on my pool's dashboard. 
![shares](https://user-images.githubusercontent.com/23208029/33516091-cfdf08fe-d792-11e7-984d-c124622a0640.png)

6 invalid shares. Should i be worried? Is there a way to prevent this? 
Any sort of help is appreciated

**Comment by psychocrypt** [comment]
please post the terminal output after you pressed the key 'r' for the
report. I need exactly the error name. please press also 'h'.
Ru  `xmr-stak -V` and post the output too.

**Comment by SharnamK** [comment]
Here are the outputs
1) Result 
![result](https://user-images.githubusercontent.com/23208029/33516343-6ffa8580-d797-11e7-97ea-81a04cdd919d.png)

2) Hash 
![hash](https://user-images.githubusercontent.com/23208029/33516352-824c22f2-d797-11e7-93c1-e0fe00d87dcc.png)

3) xmr-stak -V
![v](https://user-images.githubusercontent.com/23208029/33516355-8abf0b3e-d797-11e7-9a74-663d8a3cd81a.png)

4) connection
![connnection](https://user-images.githubusercontent.com/23208029/33516363-9eb43132-d797-11e7-83ba-aaeb689534dd.png)

**Comment by psychocrypt** [comment]
You have network issues this is the reason for the issues. You found one
duplicated share which can be a bug but due to the network issues I would
say yhat you should first fix it.

**Comment by SharnamK** [comment]
thank you. I will disable autostarting apps and see if that helps.
Could you pls tell how i can restart CPU mining? Will i have to build again?

**Comment by JerichoJones** [comment]
Grab the bin from Releases or re-compile without -DCPU_ENABLE=OFF

**Comment by Montigomo** [comment]
Hello 
after 5 step 
i get - fatal: not a git repository (or any of the parent directories): .git
![untitled-1](https://user-images.githubusercontent.com/1889961/43994386-da9c7b72-9da4-11e8-83c0-cc109e8995f9.jpg)
i don't understand...
I've tried remove all .git folders from the xmr-stak directory, but it appears still....
help please.

**Comment by Montigomo** [comment]
Resolved, seemsly.
If you want cuda support use dep files from here -> https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md 
for CUDA8 and use on step 8 next command
cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 .. C:\xmr-stak -DCPU_ENABLE=OFF -DCUDA_ENABLE=ON -DHWLOC_ENABLE=OFF
