### ISSUE TITLE
Remove gpu_thread_num for AMD backend

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak#32]
@psychocrypt can you confirm that the autosuggestion on this backend is good enough to remove the gpu_thread_num safety?

**Comment by psychocrypt** [comment]
Yes the number can be removed. Even if it is nedded the number of entries
in gpu_thread_conf can be counted.
I keeped it only to avoid more bugs during the refactoring.
The auto suggestion is working fine for my gpu and also in #5. Better
suggestion for vega coming soon.

**Comment by psychocrypt** [comment]
done.
