### ISSUE TITLE
Bus error (core dumped) on FreeBSD 11.1 

### ISSUE THREAD

**Issue by klikfroggi** [fireice-uk/xmr-stak#320]
Hi

I have successfully compiled xmr-stak. When I tried to run. It crashed. 

root@artemis:~/xmr-stak/bin # ./xmr-stak
[2017-12-02 15:42:04] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
-------------------------------------------------------------------
xmr-stak 2.0.0 79154f7

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-02 15:42:04] : Start mining: MONERO
[2017-12-02 15:42:04] : Starting double thread, affinity: 0.
[2017-12-02 15:42:04] : hwloc: set_thisthread_membind not supported
[2017-12-02 15:42:04] : Starting single thread, affinity: 1.
[2017-12-02 15:42:04] : hwloc: set_thisthread_membind not supported
Bus error (core dumped)

root@artemis:~/xmr-stak/bin # sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu'
hw.machine: amd64
hw.model: Intel(R) Xeon(R) CPU           E3110  @ 3.00GHz
hw.ncpu: 2
hw.machine_arch: amd64

Thank you.

**Comment by psychocrypt** [comment]
please compile the dev branch. This error ahould be fixed there.

**Comment by lisergey** [comment]
also try in config.txt set

"use_slow_memory" : "no_mlck",

**Comment by klikfroggi** [comment]
psychocrypt. Fixed. Thanks.

**Comment by psychocrypt** [comment]
Is it fixed in the dev or was this the option suggest from @lisergey

**Comment by klikfroggi** [comment]
It is fixed in the dev. I tried the option suggest from @lisergey first but still crash.
