### ISSUE TITLE
Runtime type error

### ISSUE THREAD

**Issue by imrecsoka** [fireice-uk/xmr-stak#321]
I have windows 7 installed with service pack 1 , clean.
I have just installed the Visual C++ 2013 64 bit runtimes.

Is this all i need, because XMR-CPU-STAK still fails with a runtime error.
There used to be a page for the requirement  for XMR-SATK-CPU but i cant find it.

**Comment by psychocrypt** [comment]
please post the full error and ran `xmr-stak -V`

**Comment by imrecsoka** [comment]
I had to download some update and then Visual C++ runtimes for 2015 , now it works.
Thanks...
