### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by nicolasu** [fireice-uk/xmr-stak#322]
In the home page, the relase link to the page https://github.com/xmr-stak/xmr-stak/releases

Who is 404 not found.

The right address is https://github.com/fireice-uk/xmr-stak/releases i think

**Comment by psychocrypt** [comment]
the link is fixed in the dev branch
https://github.com/fireice-uk/xmr-stak/releases

**Comment by JerichoJones** [comment]
Fixed in Release
