### ISSUE TITLE
Error in make install - version.cpp

### ISSUE THREAD

**Issue by Joe-Lapetoire** [fireice-uk/xmr-stak#325]
Linux 17.10 

Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from [...]/xmr-stak-master/xmrstak/version.cpp:1:0:
[...]/xmr-stak-master/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
[...]/xmr-stak-master/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100

Can you help me ?

**Comment by ITwrx** [comment]
maybe you borked your donate-level.hpp?

**Comment by psychocrypt** [comment]
what is the exact error?

**Comment by Joe-Lapetoire** [comment]
No modification in donate-level file.

`[ 20%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from .../xmr-stak-master/xmrstak/version.cpp:1:0:
.../xmr-stak-master/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
.../xmr-stak-master/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100
                                 ^
CMakeFiles/xmr-stak-backend.dir/build.make:62 : la recette pour la cible « CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o » a échouée
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Erreur 1
CMakeFiles/Makefile2:105 : la recette pour la cible « CMakeFiles/xmr-stak-backend.dir/all » a échouée
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

thanks

**Comment by psychocrypt** [comment]
Please post the output of cmake from a clean directory. Which OS do you
use?

**Comment by Joe-Lapetoire** [comment]
I'm on Ubuntu 17.10

xmr-stak-master/build$ cmake .. -DCUDA_ENABLE=OFF
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: [...]/xmr-stak-master/build

**Comment by Joe-Lapetoire** [comment]
(same error with : cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=ON -DCPU_ENABLE=ON -DHWLOC_ENABLE=ON )

**Comment by psychocrypt** [comment]
could you please remove `#include <inttypes.h>` and add `#include
<cstdint>` iin the file version.hpp and recompile.

**Comment by Joe-Lapetoire** [comment]
No change, same error : 
```
Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from [...]/xmr-stak-master/xmrstak/version.cpp:1:0:
[...]/xmr-stak-master/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
[...]/xmr-stak-master/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100
                                 ^
CMakeFiles/xmr-stak-backend.dir/build.make:62 : la recette pour la cible « CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o » a échouée
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Erreur 1
CMakeFiles/Makefile2:105 : la recette pour la cible « CMakeFiles/xmr-stak-backend.dir/all » a échouée
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by A-Manning** [comment]
I also get this error on ubuntu 17.10, gcc/g++ 5.4.1.

**Comment by NmxMilk** [comment]
This seems to be compiler version or option problem:
[https://stackoverflow.com/questions/12975341/to-string-is-not-a-member-of-std-says-g-mingw](url)
and
[https://stackoverflow.com/questions/19122574/to-string-isnt-a-member-of-std](url)
enforcing -std=c++11 or -std=c++14 option may help

**Comment by fireice-uk** [comment]
@Joe-Lapetoire @A-Manning you have broken tool-chains - gcc 5.4.1 is very old for 17.10, you should have gcc 7.

**Comment by goeland86** [comment]
@fireice-uk I had gcc 7 on Ubuntu 17.10 and had to downgrade to using gcc 6 because Cuda won't work with GCC 7 yet. Using gcc 6 I have the same error still.

**Comment by franklinam1** [comment]
If you've run into the issue, try uninstalling gcc and reinstalling it along with the other pre-reqs in the build guide

**Comment by akosmaroy** [comment]
I'm getting the same error - can you please elaborate on what the fix is.

details:

```
⟫ make -j2
Scanning dependencies of target xmr-stak-c
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 17%] Linking C static library bin/libxmr-stak-c.a
[ 17%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 20%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 22%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
In file included from /home/miner/src/xmr-stak/xmrstak/version.cpp:1:0:
/home/miner/src/xmr-stak/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’
:
/home/miner/src/xmr-stak/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 1000)) ;
                                 ^
CMakeFiles/xmr-stak-backend.dir/build.make:86: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

```
⟫ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
⟫ gcc-5 --version
gcc-5 (Ubuntu 5.5.0-1ubuntu1) 5.4.1 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by akosmaroy** [comment]
no, I haven't. I'm expecting the code to compile from the repository as it is.

the code did compile with using gcc-7 for the main code and gcc-5 for the CUDA code, using the following cmake command line:

`cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 ..`
