### ISSUE TITLE
NVIDIA cannot load backend library: xmr_cuda_backend.dll

### ISSUE THREAD

**Issue by BMA-Corgea** [fireice-uk/xmr-stak#328]
Hello,

It looks like this is a new issue. Not to say that it is a new glitch, but nobody has seemed to ask this yet. Please excuse my inexperience.

To my understanding, my NVIDIA GeForce 840M is being called to mine by the XMR Stak code, but when it tries to understand what is being asked, it is unable to make use of the library, thus rendering the GPU inert for the sake of mining.

Is there any advice that you can give me about this issue?

**Comment by psychocrypt** [comment]
please post more information.
- do you compiled the miner by your own
- post `xmr-stak -V`
- list all files within the folder with the binary

**Comment by BMA-Corgea** [comment]
1) I do not compile the miner.
2) It is xmr-stak 2.0.0
3) 
a) libeay32.dll
b) ssleay32.dll
c) xmrstak_cuda_backend.dll
d) xmrstak_opencl_backend.dll

Based on your questions, my guess is that compiling the miner is what I should do to get the library working. Is this proper and adequate information?

**Comment by psychocrypt** [comment]
please post first all cammds used to start the miner and all output from
the terminal

**Comment by BMA-Corgea** [comment]
To start the miner I disable my antivirus and select the xmr-stak.exe file.

Full output:


-------------------------------------------------------------------
xmr-stak 2.0.0 0005e4a

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-03 01:39:17] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled
[2017-12-03 01:39:17] : WARNING: backend NVIDIA disabled.
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
WARNING: AMD Backend disabled
[2017-12-03 01:39:17] : WARNING: backend AMD disabled.
[2017-12-03 01:39:17] : Starting single thread, affinity: 0.
[2017-12-03 01:39:17] : hwloc: memory pinned
[2017-12-03 01:39:17] : Starting single thread, affinity: 2.
[2017-12-03 01:39:17] : hwloc: memory pinned
[2017-12-03 01:39:17] : Fast-connecting to pool.minexmr.com:4444 pool ...
[2017-12-03 01:39:17] : Pool pool.minexmr.com:4444 connected. Logging in...
[2017-12-03 01:39:17] : Difficulty changed. Now: 15000.
[2017-12-03 01:39:17] : Pool logged in.

**Comment by psychocrypt** [comment]
please check the sizes of the dll files. Maybe the virus protection removed
thw content. The dll files must be located in the directory of the binary.

**Comment by BMA-Corgea** [comment]
Don't laugh at me.

Putting the .exe file in the same folder as the binary resolved the issue. That being said, it's now telling me:

WARNING: NVIDIA Insufficient driver!
WARNING: backend NVIDIA disabled.

This seems to be an unrelated issue that I have not researched yet. Thank you so much for your help. Please tell me if you know a quick solution or whether I should just close the issue now.

**Comment by psychocrypt** [comment]
Please update your cuda driver to the latest cuda9. this schould solve the
last issue

**Comment by BMA-Corgea** [comment]
Cool, I'll do that. Thank you for all the work you've put into this miner and for helping me!
