### ISSUE TITLE
Fermi GPU

### ISSUE THREAD

**Issue by shadixs** [fireice-uk/xmr-stak#330]
Does anybody has tried to compile windows xmr-stak with fermi support? Or anybody willing to share xmrstak_cuda_backend.dll with fermi support?

THanks

**Comment by psychocrypt** [comment]
You need cuda8 to compile for fermi. the next release comming soon will
have again a precompiled fermi support

**Comment by sergneo** [comment]
Remove CUDA 9, install only CUDA 8 http://developer2.download.nvidia.com/compute/cuda/8.0/secure/Prod2/local_installers/cuda_8.0.61_windows.exe
Patch: http://developer2.download.nvidia.com/compute/cuda/8.0/secure/Prod2/patches/2/cuda_8.0.61.2_windows.exe
Compiling and everything works for Fermi

**Comment by JayWalker512** [comment]
Is it possible to run the miner using OpenCL 1.2 for older Nvidia architectures (Tesla, Geforce 2xx, etc)? I ask because I'm using Ubuntu and newer version of CUDA are not readily available for older archs, but maybe OpenCL would be easier to get working.

**Comment by psychocrypt** [comment]
please use cuda 8 to compile for fermi.

**Comment by JayWalker512** [comment]
With respect, my question was in reference to GPUs that predate Fermi and are not supported by CUDA 8.

**Comment by psychocrypt** [comment]
No older cards than fermi are not supported also not with opencl.

**Comment by psychocrypt** [comment]
pre-compiled windows binaries with fermi support are now available in the new release https://github.com/fireice-uk/xmr-stak/releases/tag/v2.1.0
