### ISSUE TITLE
New version same old issue.

### ISSUE THREAD

**Issue by GoldPT** [fireice-uk/xmr-stak#331]
Hello,

Thanks for the new version although there's still the same issue with the miner freezing if a particular GPU stops hashing. Is it possible to flag that same card and keep it going?

**Comment by psychocrypt** [comment]
No the system do not know if the gpu is hashing slow or is broken. In the
most cases this means you overclocked the gpu to much, you have driver
issues or the gpu is broken.

**Comment by GoldPT** [comment]
I do struggle to understand how that's not possible. 

Please bare in mind that if the miner crashes how can we find out which card has the issue? Plus, there's other miners around that do use that methodology (stops the card if there's an issue).

**Comment by psychocrypt** [comment]
If the driver is crashing we can do nothing. You can find the broken gpu if
you start a miner per gpu and rename the binary for each gpu miner.

**Comment by fireice-uk** [comment]
Trying a card one by one is the only way currently.
