### ISSUE TITLE
error gpu 0 : cuda 244

### ISSUE THREAD

**Issue by Zediona** [fireice-uk/xmr-stak#333]
I've tried everything , increasing b factor reducing blocks and threads gives the same  error nonstop.
Looked at some issues before submitting this
i have an msi gtx 750 ti,
i've followed all the instructions on compiling (i guess)
![help1](https://user-images.githubusercontent.com/34218502/33529160-a9c4ce10-d87d-11e7-8539-720e81c48222.png)
i've seen someone drop this on an other issue so i guess it might help?
![help2](https://user-images.githubusercontent.com/34218502/33529180-0295dad4-d87e-11e7-9840-62ff494264bf.png)
like i said after this  cmd crashes

**Comment by psychocrypt** [comment]
Set bfactor to 8

**Comment by Zediona** [comment]
Tried that too, i tried 6 8 10 12 same error

**Comment by CheapHoarder** [comment]
I also have the same error. I downloaded the miner 3/12 and was mining just fine with Ryzen and RX580. I picked up a GTX1060 and installed it today and tried running the miner and got the same error as OP. Latest drivers from Nvidia, latest CUDA package and latest release of xmr-stak. Is this a common issue with the new release?

**Comment by TimothyShimmin** [comment]
@psychocrypt 's solution worked for me when I ran into this error. The error name and GPU brand are the only similarities though.

**Comment by erikwithaknotac** [comment]
Same issue. Have a GTX 1070 Ti.

**Comment by fireice-uk** [comment]
@Zediona try the new version - it has more conservative nvidia settings
