### ISSUE TITLE
Unable to connect to xmr.suprnova.cc

### ISSUE THREAD

**Issue by aegroto** [fireice-uk/xmr-stak#334]
I'm unable to connect to the Suprnova.cc XMR pool from about 2 weeks.

I tried with this unified version (master branch), the original xmr-stak-amd and my fork xmr-stak-amd-clover, and even if it slowly connects to the pool the software suddendly fails to login, returning a timeout.

I don't know if it is related to the miner or to the pool, but i'm able to connect to the latter with other miners. I already wrote an e-mail to pool admins but still had no response. May this be related to a recent protocol modification?

**Comment by psychocrypt** [comment]
I think this is an pool issue.

**Comment by fireice-uk** [comment]
It is most likely trying to do something clever with the version string.
