### ISSUE TITLE
How to compile for Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#337]
Hello.

I can't seem to find a way (or understand how to) compile xmr-stak v2.00 for Ubuntu.
Looks like pre-compiled binaries have been removed from Releases.

There's the docker script, however, it seems it's trying to get older versions from git hub, which are marked as outdated.

How?
Please.

**Comment by ibexes** [comment]
```   
sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake ..
make install
```

https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md

**Comment by Angel996** [comment]
Oh, thanks... It worked. Me lame. ;)
It's just that usually compile instructions are in the main README.MD file. :) 

p.s. Maybe it would be a good idea to remove all references to Linux precompiled binaries if a decision was made to withdraw them?

**Comment by fireice-uk** [comment]
`p.s. Maybe it would be a good idea to remove all references to Linux precompiled binaries if a decision was made to withdraw them?`

They were withdawn because "it-doesnt-work-too-well-let's-not-annoy-users" not "we-don't-want-to-do-this-anymore"
