### ISSUE TITLE
Feature: Mining pool cycle option

### ISSUE THREAD

**Issue by ve6a** [fireice-uk/xmr-stak#338]
Hi,

Is it possible to add a command to XMR-stak so the user could cycle trough mining pool's ?
I know that there is an option to setup fail-over pool, but in resent events regarding fluctuation of hash power  between pools it would be quite handy for admin to change pool without stoping the miner and editing config.txt. For example to use a P letter just to cycle trough all pools in conifg file.

**Comment by fireice-uk** [comment]
We are planning to do a round-robin feature where you can split your hashes between pools.
