### ISSUE TITLE
Config file override by command line possible?

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#340]
Hello.

Running under Ubuntu 16.04 LTS. This miner is the first one I've come across that cannot run w/o a config.txt file.  Other miners use config files too, but they are not mandatory. I usually add rig name after wallet address like $WALLET.$RIG with RIG set to (hostname). This parameter is passed via command line and it works with other miners.

But XMRSTAK picks up parameters from the config.txt once it has been created and it **ignores** newer params passed via command line (contrary to what -h command claims). I could erase the config.txt on every run, however, XMRSTAK enters a kind of interactive state when it asks questions about coin name and pool parameters. 

So, if I had, say, 100 rigs, I would have to run XMRSTAK a 100 times to create an individual config file for every rig.

p.s. I just realized your group name is FIRE ICE-UK. If written as one word, it reads "fierce-uk".

**Comment by patraanjan23** [comment]
You can have multiple `.txt` config files. Rename them like `minexmr.txt` then use them like this `./xmr-stak -c minexmr.txt`

Peace.

**Comment by Angel996** [comment]
I know I can use custom config files. However, it does not solve portability problem to 100 rigs. If I want every rig to have its hostname (like RIG14, RIG77) appended to wallet number, I would have to create 100 config files, instead of simply putting a hostname variable in a command line.

**Comment by psychocrypt** [comment]
It is planed to add environment variables for this. Currently there was no
time for that.
It is on my todo list.

**Comment by patraanjan23** [comment]
@psychocrypt I think it's something I could do. I know how cli arguments in c work. Can you tell me the source file that contains the CLI arguments handling and configuration generation? Just want to try.

**Comment by psychocrypt** [comment]
I forgot that I already added thisnoptions. Sry.
It looks like there is an bug that the options will not have a higher
priority than the config file.
I will check which pull request broke this feature and will fix it.

**Comment by Angel996** [comment]
psychocrypt, can you please update this branch with this fix? the fireice-uk/xmr-stak ?

**Comment by psychocrypt** [comment]
The firat version is already pushed to the dev branch  But there will be a
change how it is handled in an open pull request.

**Comment by Angel996** [comment]
Sorry, I don't understand how to utilize this fix then. I did the "git pull" on the master branch and I get "Already up to date"

**Comment by rowanruseler** [comment]
@Angel996 `git checkout dev && git pull`

As stated by @psychocrypt : The firat version is already pushed to the **dev** branch

**Comment by Angel996** [comment]
Just one more question, please. :)

Is there a way to specify SSL connection on the command line?
