### ISSUE TITLE
Config & Nvidia Settings Resetting 

### ISSUE THREAD

**Issue by themoneromines** [fireice-uk/xmr-stak#343]
So, when  I run xmr-stak from the .exe it runs the custom config and Nvidia settings I have setup. However, when I run the program though program called "Watch4Idle" which runs a batch-file called C:\xmr-stak.exe it then asks me to put in all of the configuration settings again rather than just pulling from the all ready edited  config/nvidia text documents. After I have put in the settings I cannot seem to find were it has saved them to, is there any temporary files that XMR-Stack as I think it has just made a new config in a file I cannot find.

Thanks in advance.

**Comment by JerichoJones** [comment]
It sounds like you have not set the working directory. By default the command prompt starts from %windir%\system32. You could also modify your batch file:
PUSHD %~DP0
XMR-STAK.EXE
POPD

More info can be found [here](https://github.com/fireice-uk/xmr-stak/issues/377).
