### ISSUE TITLE
Can someone please point me in the direction of a sample config file?

### ISSUE THREAD

**Issue by chc-pr** [fireice-uk/xmr-stak#346]
As per the subject really. I have downloaded windows 64 the binary but cannot find any semblance of a config file in the zip file. I have managed to find a config file (or at least a partial one, I have no idea of it is complete - it certainly has no GPU section in what I understand is a new unified version). As a result, I have no real idea how to try to configure this for a test run. I am particularly keen to try the AMD GPU.

Any help much apprciated.

**Comment by psychocrypt** [comment]
Simply start the miner. The miner will ask some questions and create the
config files for you.

**Comment by chc-pr** [comment]
Thanks
On Mon, Dec 4, 2017 at 22:23, psychocrypt  wrote: Simply start the miner. The miner will ask some questions and create the
 config files for you.
