### ISSUE TITLE
WARNING: AMD cannot load backend library: libxmrstak_opencl_backend.so

### ISSUE THREAD

**Issue by bowerstech** [fireice-uk/xmr-stak#347]
Hello,

I am setting up my first system so pardon any ignorance on my part.  I am on Arch Linux with a AMD RX 550 card.  I followed the instructions here:  https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md

I was able to get through the instructions, install the AMD SDK, and run through the cmake (turning off nvidia support) and install process.  When I run ./xmr-stak from the bin folder I receive the following error:

WARNING: AMD cannot load backend library: libxmrstak_opencl_backend.so: cannot open shared object file: No such file or directory

When in look in the bin folder I see that file listed there.

Not sure what I am doing wrong

TIA, Bryan

**Comment by psychocrypt** [comment]
please goto the bin folder and post `ls -la`

**Comment by bowerstech** [comment]
Here are the results:

total 2252
drwxr-xr-x 2 bryan users   4096 Dec  4 14:17 .
drwxr-xr-x 4 bryan users   4096 Dec  4 14:02 ..
-rw-r--r-- 1 bryan users   8825 Dec  4 14:04 config.txt
-rw-r--r-- 1 bryan users   1388 Dec  4 14:04 cpu.txt
-rw-r--r-- 1 bryan users 856670 Dec  4 14:02 libxmr-stak-backend.a
-rw-r--r-- 1 bryan users  72678 Dec  4 14:01 libxmr-stak-c.a
-rwxr-xr-x 1 bryan users 727440 Dec  4 14:02 libxmrstak_opencl_backend.so
-rwxr-xr-x 1 bryan users 616032 Dec  4 14:02 xmr-stak

**Comment by bowerstech** [comment]
Son came home and loaded the AMD GPU driver.  Problem solved.
