### ISSUE TITLE
Archlinux nvidia gtx 1070 core dump

### ISSUE THREAD

**Issue by marcosdsanchez** [fireice-uk/xmr-stak#348]
Error:

```
xmr-stak 2.0.0 79154f7

[2017-12-04 19:32:45] : Start mining: MONERO                                                                
[2017-12-04 19:32:45] : Starting NVIDIA GPU thread 0, affinity: 0.                    
[2017-12-04 19:32:45] : hwloc: memory pinned                                                                                   
[2017-12-04 19:32:45] : Starting single thread, no affinity.                                                 
[2017-12-04 19:32:45] : Starting single thread, no affinity.                                                         
[2017-12-04 19:32:45] : Starting single thread, no affinity.                                                               
[2017-12-04 19:32:45] : Fast-connecting to pool.supportxmr.com:7777 pool ...                                               
[CUDA] Error gpu 0: </home/marcos/.cache/pacaur/xmr-stak-git/src/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:206
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: out of memory

```

Core dump details:
<details>
 #5  0x00007f430646c47f __clone (libc.so.6)                                                                                      

                                                     Stack trace of thread 20047:
                                                     #0  0x00007f4307a24230 __nanosleep (libpthread.so.0)
                                                     #1  0x000055fc900e195f _ZN7xmrstak3cpu7minethd9work_mainEv (xmr-stak)
                                                     #2  0x00007f43069fea6f execute_native_thread_routine (libstdc++.so.6)
                                                     #3  0x00007f4307a1a08a start_thread (libpthread.so.0)
                                                     #4  0x00007f430646c47f __clone (libc.so.6)

                                                     Stack trace of thread 20049:
                                                     #0  0x00007f4307a24230 __nanosleep (libpthread.so.0)
                                                     #1  0x000055fc900d0cba _ZN8executor12ex_clock_thdEv (xmr-stak)
                                                     #2  0x00007f43069fea6f execute_native_thread_routine (libstdc++.so.6)
                                                     #3  0x00007f4307a1a08a start_thread (libpthread.so.0)
                                                     #4  0x00007f430646c47f __clone (libc.so.6)

                                                     Stack trace of thread 20050:
                                                     #0  0x00007f4307a20756 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                     #1  0x00007f43021dcd07 n/a (libcuda.so.1)
                                                     #2  0x00007f4302192307 n/a (libcuda.so.1)
                                                     #3  0x00007f43021dc058 n/a (libcuda.so.1)
                                                     #4  0x00007f4307a1a08a start_thread (libpthread.so.0)
                                                     #5  0x00007f430646c47f __clone (libc.so.6)

                                                     Stack trace of thread 20040:
                                                     #0  0x00007f4306462076 ppoll (libc.so.6)
                                                     #1  0x00007f42f2f969b3 n/a (libnss_resolve.so.2)
                                                     #2  0x00007f42f2f98dbb n/a (libnss_resolve.so.2)
                                                     #3  0x00007f42f2f9242d _nss_resolve_gethostbyname4_r (libnss_resolve.so.2)
                                                     #4  0x00007f4306456679 gaih_inet.constprop.7 (libc.so.6)
                                                     #5  0x00007f43064575a4 getaddrinfo (libc.so.6)
                                                     #6  0x000055fc900e007a _ZN12plain_socket12set_hostnameEPKc (xmr-stak)
                                                     #7  0x000055fc900d7c79 _ZN6jpsock7connectERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (xmr-stak)
                                                     #8  0x000055fc900d0046 _ZN8executor16eval_pool_choiceEv (xmr-stak)
                                                     #9  0x000055fc900d4996 _ZN8executor7ex_mainEv (xmr-stak)
                                                     #10 0x00007f43069fea6f execute_native_thread_routine (libstdc++.so.6)
                                                     #11 0x00007f4307a1a08a start_thread (libpthread.so.0)
                                                     #12 0x00007f430646c47f __clone (libc.so.6)

                                                     Stack trace of thread 20045:
                                                     #0  0x00007f4307a24230 __nanosleep (libpthread.so.0)
                                                     #1  0x000055fc900e195f _ZN7xmrstak3cpu7minethd9work_mainEv (xmr-stak)
                                                     #2  0x00007f43069fea6f execute_native_thread_routine (libstdc++.so.6)
                                                     #3  0x00007f4307a1a08a start_thread (libpthread.so.0)
                                                     #4  0x00007f430646c47f __clone (libc.so.6)

</details>

Cuda Version: 9.0.176-4

`➜  ~ uname -a
Linux marcos-arch 4.14.3-1-ARCH #1 SMP PREEMPT Thu Nov 30 18:33:13 UTC 2017 x86_64 GNU/Linux`

Nvidia gtx 1070

**Comment by psychocrypt** [comment]
reduce the threads in nvidia.txt

**Comment by marcosdsanchez** [comment]
I guess it's worth mentioning that I was running the first configuration I pasted in the comment above and that re-running the command with the same configuration didn't throw that error.

**Comment by LSChyi** [comment]
use nvidia-smi, it lists the state of your gpu. I think other processes are using your GPU memory when ran first time.  That’s why you didn’t error this time.
