### ISSUE TITLE
xmr-stak crashing instantly on windows 7 with blockchain driver

### ISSUE THREAD

**Issue by tejaykodali** [fireice-uk/xmr-stak#349]
Hello, I'm currently trying ton mine on Windows 7. For the sake of testing, I'm only using a single RX 570. I was able to mine perfectly fine with the normal driver the past 72 hours with 0 issues. I just installed the blockchain driver ([downloaded from here](https://support.amd.com/en-us/download)), and xmr-stak is crashing instantly without any error messages. I tried using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) to make sure I uninstalled everything correctly, and then reinstalled the blockchain driver, and I'm still getting the same issue. This is what happens as soon as I open xmr-stak:
![capture](https://user-images.githubusercontent.com/10409442/33582924-60db72e4-d91d-11e7-93c7-8d1dce19d6ca.JPG)

**Comment by JerichoJones** [comment]
This problem is not limited to STAK and effects other miners (Claymore). There are many [complaints](https://duckduckgo.com/?q=blockchain+driver+windows+7) with the Windows 7 blockchain drivers. 

Keep in mind these drivers are BETA. Have you tried the current release drivers?

**Comment by tejaykodali** [comment]
If by release drivers, you mean the ones available [here](https://support.amd.com/en-us/download), then yes, as I mentioned in my post, I have been able to mine with those without any issue whatsoever.

**Comment by JerichoJones** [comment]
I never claimed to be able to read. ;)
I don't think there is much that can be done on the dev side. It seems to be a AMD issue.
