### ISSUE TITLE
How to set CPU affinity manually?

### ISSUE THREAD

**Issue by NoleA1** [fireice-uk/xmr-stak#354]
How do I set the CPU affinity manually as in the xmr-stak-cpu? The current automated suggestion works pretty well, but it's off a little bit on my CPUs. I'd like to set the affinity manually as I know which logical cores works better than the other.

Previously it could set it by;

"cpu_threads_conf" :
[
  { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
  { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
]

**Comment by cbesot** [comment]
Same now but there is a dedicated cpu conf file: cpu.txt
