### ISSUE TITLE
Error CL_DEVICE_NOT_FOUND, xmr-stak-amd works fine

### ISSUE THREAD

**Issue by ArthurJS** [fireice-uk/xmr-stak#356]
My system has Nvidia 1070 and AMD Vega 56.

xmr-stak-cpu works, xmr-stak-amd works, xmr-stak-nvidia works

xmr-stak combined throws error "CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices", I isolated with --noCPU and --noNVIDIA that it is the AMD card causing the error

amd.txt config is same as on xmr-stak-amd, the platform index is(should be) correct.

Any idea why it might happen ? thank you

**Comment by JerichoJones** [comment]
Can you post the miner output up to the point of pool connection?

**Comment by JerichoJones** [comment]
Might be easier to enable logging in the config.txt

**Comment by szogun1987** [comment]
There is additional field (strided_index) in config in 2-nd release. App has problem with de-serializing it. try to rename amd.txt to something else and allow app to re-generate it, then apply your changes manually.
