### ISSUE TITLE
Slow program termination NVIDIA GPU mode

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#358]
Hello.

Ubuntu 16.04 LTS. 

I have noticed miner takes very long to terminate: be it CTRL-C in terminal, or killall command. Terminal appears frozen, not reacting up to 30 seconds. In a scenario where we do multi-algo mining, switching miners etc this poses a bit of a problem.

Problem is only Nvidia GPU related. If I run CPU only mining or AMD GPU mining, miner terminates fast, although also appears frozen for 1-2 secs.

thanks. ))

**Comment by mecrip** [comment]
In my case the entire rig freeze when I close xmr-stak, and I have to reset the machine

**Comment by JerichoJones** [comment]
Try the new release and let us know if it's resolved.

**Comment by mecrip** [comment]
i've trouble building it on ubuntu 17.4 with cuda8. VArious issues with both Gcc 5 6 or 7.. 
`/home/mirko/miner/xmr-stak/xmr-stak/xmrstak/version.hpp:13:33: error: 'to_strin' is not a member of 'std'
` 

still have to find a solution..

**Comment by Angel996** [comment]
JerichoJones, just tried the new release, and couldn't get it working at all. Also, there is a weird thing going on with pool logon, miner only logs in after several attempts: I specifically rechecked: older version does not have this problem.

```
[2017-12-10 00:46:59] : Start mining: MONERO
[2017-12-10 00:47:00] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-10 00:47:00] : Starting NVIDIA GPU thread 1, no affinity.
[2017-12-10 00:47:00] : Starting NVIDIA GPU thread 2, no affinity.
[2017-12-10 00:47:00] : Starting NVIDIA GPU thread 3, no affinity.
[2017-12-10 00:47:00] : Starting 1x thread, affinity: 0.
[2017-12-10 00:47:00] : hwloc: memory pinned
[2017-12-10 00:47:00] : Fast-connecting to etn-eu2.nanopool.org:13433 pool ...
[2017-12-10 00:47:00] : Fast-connecting to stratum+ssl://etn-eu2.nanopool.org:13433 pool ...
[2017-12-10 00:47:00] : Pool stratum+ssl://etn-eu2.nanopool.org:13433 connected. Logging in...
[2017-12-10 00:47:00] : SOCKET ERROR - [stratum+ssl://etn-eu2.nanopool.org:13433] RECEIVE error: socket closed
[2017-12-10 00:47:00] : TLS fingerprint [etn-eu2.nanopool.org:13433] SHA256:w4iG797lQuvZmAG3XHXTSY2Xl4u83sB8cnHLGXKeAU8=
[2017-12-10 00:47:00] : Pool etn-eu2.nanopool.org:13433 connected. Logging in...
[2017-12-10 00:47:00] : Difficulty changed. Now: 120001.
[2017-12-10 00:47:00] : Pool logged in.
[CUDA] Error gpu 0: </home/user/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:246
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: invalid configuration argument
./exec_miner.sh: line 173: 11796 Aborted                 (core dumped) $cmd

```
Here is the log from the older version:

> 
> [2017-12-10 00:53:14] : Start mining: MONERO
> [2017-12-10 00:53:14] : Starting NVIDIA GPU thread 0, no affinity.
> [2017-12-10 00:53:14] : Starting NVIDIA GPU thread 1, no affinity.
> [2017-12-10 00:53:14] : Starting NVIDIA GPU thread 2, no affinity.
> [2017-12-10 00:53:14] : Starting NVIDIA GPU thread 3, no affinity.
> [2017-12-10 00:53:14] : Starting single thread, affinity: 0.
> [2017-12-10 00:53:14] : hwloc: memory pinned
> [2017-12-10 00:53:14] : Fast-connecting to etn-eu2.nanopool.org:13433 pool ...
> [2017-12-10 00:53:14] : TLS fingerprint [etn-eu2.nanopool.org:13433] SHA256:w4iG797lQuvZmAG3XHXTSY2Xl4u83sB8cnHLGXKeAU8=
> [2017-12-10 00:53:14] : Pool etn-eu2.nanopool.org:13433 connected. Logging in...
> [2017-12-10 00:53:14] : Difficulty changed. Now: 120001.
> [2017-12-10 00:53:14] : Pool logged in.
> Using high_cryptonight.sh for high.sh
> 
> ++HIGHEST TEMP IN RIG10: 49, running in HI power mode
> FANS: fan0=47% fan1=47% fan2=48% fan3=49%
> [2017-12-10 00:53:30] : Difficulty changed. Now: 120001.° PWR HI 110:112:95:114 TP 431 W
> [2017-12-10 00:53:30] : New block detected.
>

**Comment by Angel996** [comment]
Little update. Deleted the old nvidia.txt and cpu.txt files. Now it runs for some time, but terminates again with this error:

```
[CUDA] Error gpu 0: </home/user/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: the launch timed out and was terminated
Aborted (core dumped)

```

**Comment by Angel996** [comment]
Deleted old config.txt file and let miner recreate it. Now, it's running.

Seriously, guys, you are making it SO HARD with all those config files... I already opened another issue concerning running the miner w/o the config file.

**Comment by psychocrypt** [comment]
reduce the thraeds in nvidia.txt

**Comment by fireice-uk** [comment]
@Angel996 that's why it will create one for users that find them confusing.

**Comment by Angel996** [comment]
I don't find them confusing, they add *much confusion* to usability of the miner. If every new miner release requires all new config files, maybe it would be a good idea to re-create them or warn user. Instead of terminating with segmentation fault messages.
