### ISSUE TITLE
Offtopic: Will this support Electroneum mining?

### ISSUE THREAD

**Issue by eliashdezr** [fireice-uk/xmr-stak#360]
Since both coins are based on CryptoNote I'm wondering if I change the pool and wallet to a Electroneum one, would I be able to mine it.

**Comment by jeromemorignot** [comment]
It is supported...I'm mining some right now.

**Comment by eliashdezr** [comment]
Nice to hear that!

**Comment by seiferflo** [comment]
Ok I see you have to put currency=monero in the config file and change the wallet/pool. Cool.
