### ISSUE TITLE
Windows console default mode on Windows 10

### ISSUE THREAD

**Issue by NmxMilk** [fireice-uk/xmr-stak#362]
Hi,
While checking on my hashrate, it happens that I click the mouse in the console window.
This seems to have the side effect of stalling the miner until I press the return key !
I have already lost hours of mining time due to this.
When I press enter the output in the console resumes, and gives a lot of  "rejected by the pool" ...

I think this behaviour is due to the default "Quick edit mode" of the console.

It can be disabled by the following code:
```C++
#ifdef WIN32
   HANDLE stdIn = GetStdHandle(STD_INPUT_HANDLE);
   if (stdIn != INVALID_HANDLE_VALUE) {
      DWORD dwMode = 0;
      if (GetConsoleMode(stdIn, &dwMode)) {
         dwMode &= ~ENABLE_QUICK_EDIT_MODE;
         SetConsoleMode(stdIn, dwMode | ENABLE_EXTENDED_FLAGS);
      }
   }
#endif
```
Can you please patch to avoid this behaviour ?
Happy mining

**Comment by NmxMilk** [comment]
Another enhancement would be to enable mouse wheel scrolling:
```C++
#ifdef _WIN32
void win_init_stdin()
{
   HANDLE stdIn = GetStdHandle(STD_INPUT_HANDLE);
   if(stdIn != INVALID_HANDLE_VALUE) {
      DWORD dwMode = 0;
      if(GetConsoleMode(stdIn, &dwMode)) {
         dwMode &= (~ENABLE_QUICK_EDIT_MODE) | ENABLE_EXTENDED_FLAGS;  // disable quick edit mode
         dwMode &= ENABLE_PROCESSED_INPUT | ~ENABLE_MOUSE_INPUT; // allow mouse wheel scrolling
        SetConsoleMode(stdIn, dwMode);
      }
   }
}
#endif
```

**Comment by fireice-uk** [comment]
I would much rather keep it this way as it enables users to copy logs.

**Comment by DavidBruchmann** [comment]
@NmxMilk you can tell me where the file data.mdb resides in Windows 7?
In Windows 10 it seems being different but I have to know it about win 7.

**Comment by NmxMilk** [comment]
@DavidBruchmann I guess your talking about the blockchain database ?
You can do a file search to find it.
Usually goes into %homepath%\App Data\Roaming\Monero or something like that.

But, that has nothing to do with xmr-stak !!!

**Comment by DavidBruchmann** [comment]
@NmxMilk  yeah thanks.
wasn't sure about the usage, but I remarked when I packed the database xmr-stak lost connection with an error. Doesn't matter, helps that you could give me the location.
