### ISSUE TITLE
Wrong release Link in Readme

### ISSUE THREAD

**Issue by Setup007** [fireice-uk/xmr-stak#366]
The Readme currently links Releases to https://github.com/xmr-stak/xmr-stak/releases
instead it should be https://github.com/fireice-uk/xmr-stak/releases I believe.

Kind regards
Setup

**Comment by fireice-uk** [comment]
Hi! We are aware of that and we will fix it with the next release this weekend. Unfortunately we can't just update docs on the master branch without messing up the release schedule.
