### ISSUE TITLE
Huge amounts of lag and hanging with AMD Radeon HD8790M

### ISSUE THREAD

**Issue by bupthebroker** [fireice-uk/xmr-stak#367]
Hi,
i pulled and compiled the latest xmr-stak today. I have an AMD Radeon HD8790M video card. The problem is that when i start the miner the PC hangs a lot and picture goes black from time to time.

"gpu_threads_conf" :
[
    { "index" : 0, "intensity" : 12, "worksize" : 8, "affine_to_cpu" : false},
],

Previously i used to mine with the MineGate app, it allows me to set 4 levels of intensity for the GPU. If i set it to 1 (lowest) then everything works well and i get a hashrate of about 110.

Is there a similar concept of intensity in the xmr-stak? No matter what i set for the intensity in the gpu_threads_conf my PC hangs a lot and i cannot use it for other things.

![miner](https://user-images.githubusercontent.com/9417629/33661094-0b2646e4-da8f-11e7-9b66-ac5116291cd2.jpg)

Thanks

**Comment by JerichoJones** [comment]
Did you look at the [tuning guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md)?
