### ISSUE TITLE
Cuda memory limitation

### ISSUE THREAD

**Issue by dgiero** [fireice-uk/xmr-stak#369]
Hi, can you tell me more about the below quote?

> For all GPU's with a compute capability >=2.0 and <6.0 there is a restriction of the amount of RAM that can be used for the mining algorithm. The maximum RAM that can be used must be less than 2GB (e.g. GTX TITAN) or 1GB (e.g. GTX 750-TI). 

Thanks

**Comment by psychocrypt** [comment]
The reason is that NVIDIA GPUS older than Pascal can not handle random memory accesses to a memory range lager than 2GiB. Im the case we allocate more than 2GiB and randomly access the memory (that is what monero is doing) than the performance will decrease because of the TLB misses.
