### ISSUE TITLE
Run xmr-stak on 32 bits Windows with x64 CPU?

### ISSUE THREAD

**Issue by zdimension** [fireice-uk/xmr-stak#370]
I need to install xmr-stak on a computer that is currently running Windows 7 Pro (32 bits). The computer has got an Intel i5-3470 CPU, which supports amd64 and AES instructions. Is it possible? I'm aware that xmr-stak makes extensive use of amd64 features which would make mining slower, but since the CPU has AES encryption, would a 32-bit build work?

**Comment by dgiero** [comment]
Read this 
[https://github.com/fireice-uk/xmr-stak-cpu/issues/360](url)

**Comment by JerichoJones** [comment]
XMR-STAK does not support 32-bit operating systems.

**Comment by zdimension** [comment]
solution for mining on a 32-bit OS on a 64-bit CPU with acceptable hashrate: use xmrig

(for 64-bit though, xmr-stak gives a much better hashrate than xmrig)
