### ISSUE TITLE
Feature Request: Add GPU intensity option

### ISSUE THREAD

**Issue by artivity** [fireice-uk/xmr-stak#371]
Hi Fireice. What are the chances of being able to implement a GPU intensity flag similar to that of Claymore's miner? For anyone only just getting into mining and only has the one graphics card, this would be somewhat of a game changer I think, especially on macOS. Happy to test in all OS's if you feel like implementing this?

**Comment by tejaykodali** [comment]
You can change this in the config file.

**Comment by artivity** [comment]
What? **No, you can't.** I am referring to GPU usage intensity. Move along.

**Comment by gerbilOFdoom** [comment]
You can adjust the intensity by using the tuning options in the documentation.

On nVidia, reduce the number of threads/blocks in use. On AMD reduce the intensity variable.

**Comment by artivity** [comment]
I should probably have been more specific; this is for AMD cards... It seems as though you have this option for Nvidia cards known as "bsleep" in the nvidia config. I'm not particularly well versed with OpenCL so I'm having a hard time trying to figure out how to add a delay the same way you would with Cuda. What I have noticed is that in Windows, reducing the intensity level a little below the optimal value helps tremendously for browsing and watching videos but brings down the hash rate substantially in comparison to the -li flag in Claymore which only drops ~20H/s. In macOS, it's completely unusable while mining.

Any chance of just pointing me in the right direction so I could create a custom build to test?

**Comment by psychocrypt** [comment]
the intensity for any amd card can be changed in the config file `amd.txt`

**Comment by artivity** [comment]
Never mind then ;)

**Comment by gerbilOFdoom** [comment]
What about Nvidia, though? I've tried working with the options and haven't
found a configuration that leaves my system usable.

**Comment by JerichoJones** [comment]
Increase bsleep may help.

* bsleep        - Insert a delay of X microseconds between kernel launches.

**Comment by seiferflo** [comment]
Same problem, increasing bsleep doesn't change anything on nvidia (25/50/75/100/300...) I can only mine using CPU when using the computer.
 // gpu: GeForce GTX 760 architecture: 30

**Comment by JerichoJones** [comment]
Apparently so. As they say, "There is no free lunch".
