### ISSUE TITLE
Issues launching from a batch file using windows task scheduler

### ISSUE THREAD

**Issue by Sandwich247** [fireice-uk/xmr-stak#377]
When Windows Task Scheduler launches a bat file, that is configured to launch XMR-Stak.exe for Aeon, it does not do so. Instead, it uses a different set of configuration settings that I set previously (a few days ago). This issue also occurs when setting Task Scheduler to run the .exe file, and adding any configuration options in the arguments box. Issue also occurs when launching a shortcut to the batch file. Issue also occurs when launching a shortcut to XMR-Stak.exe with the parameters inside the shortcut target. Issue also occurs regardless of whether or not the batch file has the program path in quotation marks.

Launching the batch file manually works fine. Launching shortcut to batch file works fine. Launching shortcut with parameters inside the shortcut target manually works fine.

Please see attached screenshots.

Thanks.

Image 1: launching batch file manually. Notice it is pointing to an Aeon pool.
![1](https://user-images.githubusercontent.com/8767826/33686697-a8e02092-dacd-11e7-863d-b55ce386026c.png)

Image 2: Launching same batch file from Task Scheduler. Notice how it is now pointing to an XMR pool.
![2](https://user-images.githubusercontent.com/8767826/33686703-aba390ca-dacd-11e7-94f9-fc06f7e9cc02.png)

**Comment by JerichoJones** [comment]
Can you post your batch file?

**Comment by Sandwich247** [comment]
> Can you post your batch file?

Thank you for your response. The contents of the batch file are below:

"C:\Users\Sandwich247\Desktop\Aeon\xmr-stak\xmr-stak.exe" --currency aeon --noCPU --url aeon.poolto.be:11015 --user WmtSmMp3sCFFfrHNcDvJFXP6x57UqdqJEZ9jy9TjAAQtWAymY9WLAik8RwguakPfgLgj7QcJCz9dtHBcAx5HgzQo178cFcHZm

**Comment by JerichoJones** [comment]
Are you setting a working directory?
I would suggest the following changes:
PUSHD %~DP0
"C:\Users\Sandwich247\Desktop\Aeon\xmr-stak\xmr-stak.exe" --currency aeon --noCPU --url aeon.poolto.be:11015 --user WmtSmMp3sCFFfrHNcDvJFXP6x57UqdqJEZ9jy9TjAAQtWAymY9WLAik8RwguakPfgLgj7QcJCz9dtHBcAx5HgzQo178cFcHZm
POPD

If you have not set a working directory PUSHD will basically change directory to where the script was invoked. If it is a UNC path it will map a drive "on the fly". POPD returns you to the starting folder (probably c:\windows\system32) and unmap the drive (if UNC).

Maybe you have already gone down this road?

**Comment by Sandwich247** [comment]
> I would suggest the following changes:
>PUSHD %~DP0
>...
>POPD

This has resolved the issue. Thank you for your assistance, it is much appreciated.
