### ISSUE TITLE
Default nvidia.txt crashes GTX 1060 6GB

### ISSUE THREAD

**Issue by gerbilOFdoom** [fireice-uk/xmr-stak#379]
Default configuration has bfactor at 6 for my GPU. I had to increase that number to 8 in order to mine without crashing.

**Comment by JerichoJones** [comment]
On my laptop with the NVIDIA 3000M no settings that I have tried work. It always crashes. No problems with XMR-STAK-NVIDIA.

**Comment by thexenoncodex** [comment]
thanks gerbilOFdoom  could not keep mixed rig amd 570's and gtx1060's stable seems fine now with bfactor 6, i should have figured that out but was skipping that in my troubleshooting. your comment helped me.

**Comment by psychocrypt** [comment]
Is bfactor 7 also solving the issue?

**Comment by Cleeez** [comment]
@psychocrypt 8 seems to be the stable number
