### ISSUE TITLE
Windows Defender deletes exe file (Win32/Tilken.B!cl)

### ISSUE THREAD

**Issue by williampmills** [fireice-uk/xmr-stak#381]
Today (07 December 2017), Windows Defender has deleted the exe file twice, and flagged it as a Trojan by the name of:
Win32/Tilken.B!cl

**Comment by Fengyao115** [comment]
Same issue with me

**Comment by Morisf** [comment]
+1

**Comment by Svyatk0** [comment]
very suspiciously coincides with nicehash hack

**Comment by ernestp** [comment]
+1

**Comment by Sugarfloodwave** [comment]
on all my Pcs it will be deleted .. everytime .. sigh

**Comment by aaronsace** [comment]
Add the folder to your exceptions list. All miners get this problem because they get integrated into botnets. This is how MultiPoolMiner miner manages to download it successfully without issue.

**Comment by Sugarfloodwave** [comment]
cant do that .. reasons! So no way to get a clean install without adding it to exception list

**Comment by aaronsace** [comment]
@Sugarfloodwave The only other option is to compile it yourself.
