### ISSUE TITLE
Link to download AMD APP SDK 3.0 directly

### ISSUE THREAD

**Issue by iRickyJ** [fireice-uk/xmr-stak#385]
I need to install AMD App sdk 3.0 on linux via command line. Issue is that I can only download it via browser after seeing their terms.

Is there way to download from this page via cmd directly for linux (using wget or curl ?)
https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/

Thanks

**Comment by JerichoJones** [comment]
Obviously you would need a direct link which they obfuscate as they want you to accept the license agreement.

Try developer mode on your browser. You might be able to determine it from there.

**Comment by iRickyJ** [comment]
Nevermind, downloaded through browser then scp'ed to linux  box.
