### ISSUE TITLE
Cant get XMR stalk to work

### ISSUE THREAD

**Issue by Newguy123456** [fireice-uk/xmr-stak#387]
XMR stalk just stops dead after I answer the configuration questions (currency, pool address, wallet address etc).
Its says configuration stored in file "config.txt". Then nothing happens. I cant give it a command and I cant even close it down without restarting the computer.

(Before running the program - I've created a firewall rule for XMR stak; Ive updated windows, Ive installed the latest version of Visual++)

**Comment by JerichoJones** [comment]
Have you created an exception for it in your anti-virus program?

**Comment by Mkorny** [comment]
I have a very similar behavior, except the miner just drops to the command prompt again.

So far, tried fully stopping all security software, rebooting switching HDD, confirmed virtual mem is @ 16gb, tested different pools, confirmed Cuda 8.0 + patch 2 is installed (tried different combinations of cuda dev kit versions)

**Comment by JerichoJones** [comment]
Edit the config.txt and enable logging.

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

Post the results here.

**Comment by fvini113** [comment]
This is happening to me too. It was after I installed the CUDA 9.1 driver and Visual Studio.

![image](https://user-images.githubusercontent.com/34553154/34010829-d26a8e14-e0ec-11e7-905b-fd0ca57ed969.png)

**Comment by PFFyodor** [comment]
Newguy123456 
similar problem and not ideas

**Comment by psychocrypt** [comment]
please activate the log file to have all output in the files.
Also be shure that you not update to cuda 9 if you own a fermi gpu. Fermi
is no longer supported by cuda 9.

**Comment by JerichoJones** [comment]
@fvini113 You are in select mode and have scrolled down so that is not going to work. Select mode will cause unexpected results. Scrolling down past any messages makes the screen shot not particularly useful.

**Comment by fireice-uk** [comment]
@Newguy123456 If the problem still persists in 2.2 please open a new issue while using the template.
