### ISSUE TITLE
Error CL_INVALID_WORK_GROUP_SIZE when calling clEnqueueNDRangeKernel for kernel 0.

### ISSUE THREAD

**Issue by griztown** [fireice-uk/xmr-stak#393]
Just downloaded xmr-stak last night and kicked it off but got the following error right away. Was using an intensity of 1932. I dropped the intensity down to 1000, then 700, finally at 500 I was able to stably run the miner. Is this a bug or did I screw something up in my setup?

**Comment by griztown** [comment]
I figured this out. I hadn't appropriately adjusted my virtual memory. As soon as I did that the error went away and I was able to mine at the intensities advertised. I can close this but I wonder if we could give a more instructive error message?

**Comment by JerichoJones** [comment]
How much RAM do you have and what size did you set your pagefile?

**Comment by griztown** [comment]
I have 4 GB of RAM. For pagefile, what are you referring to? As I mentioned, I was able to fix this by changing the virtual memory. I set that to 30 GB. I assume that the amount of disk space you have to the cap for virtual memory. I only have a 60 GB SSD so after intalling Windows I had less than 40 GB left over. So thus I only use 30 GB.

**Comment by fireice-uk** [comment]
If you still have this problem with version 2.1 then please reopen using the new template for the responses.
