### ISSUE TITLE
Is there an already compiled version of this?

### ISSUE THREAD

**Issue by swcrusade** [fireice-uk/xmr-stak#40]
Hello,

I was wondering if someone had an already compiled version for download available?

**Comment by psychocrypt** [comment]
No there is currently no precompiled binary avaialable.
Everything is work in progress and the binaries will be shipped with the
release.

**Comment by fireice-uk** [comment]
@swcrusade You are welcome to test but keep in mind that this is not a finished software product - there will be a lot of bugs and rough edges.

**Comment by gboddin** [comment]
Here's a CUDA friendly Dockerfile to build it just in case : https://gist.github.com/gboddin/ede88ed2beb43cd44e8205b8f4de6ce3

You'll have to adapt for your target distro after dropping the file in the root of this repo.

```sh
docker build . -t xmr-stak && docker run -ti xmr-stak tar cz /xmr-stak > xmr-stak.tar.gz 
```

@psychocrypt if you need any CI and/or delivery help I can give a hand on travis or an hosted drone instance

**Comment by Grimm2017** [comment]
Is there a target date for release?

**Comment by fireice-uk** [comment]
This weekend. We have already frozen the feature set and are only doing debugging PRs.
