### ISSUE TITLE
WARNING: NVIDIA Insufficient driver!

### ISSUE THREAD

**Issue by jsbranco** [fireice-uk/xmr-stak#401]
Hi,

I recently built the v2.0 version and although I am able to run it on CPU, I can't seem to have it running on my GTX 1080.

It shows "Nvidia Insufficient Driver", and switches to CPU. Although, I have CUDA 9.0 installed and my GTX is recognised. Has anyone seen this?
**./xmr-stak**
```
[2017-12-08 08:31:27] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-12-08 08:31:27] : WARNING: backend NVIDIA disabled.
[2017-12-08 08:31:27] : Starting single thread, no affinity.
[2017-12-08 08:31:27] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-08 08:31:27] : MEMORY ALLOC FAILED: mlock failed
[2017-12-08 08:31:27] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-08 08:31:27] : Difficulty changed. Now: 25000.
[2017-12-08 08:31:27] : Pool logged in.
```

**nvidia-smi**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.12                 Driver Version: 387.12                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:0E:00.0  On |                  N/A |
|  0%   41C    P8    13W / 210W |    701MiB /  8105MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1165      G   /usr/lib/xorg/Xorg                           404MiB |
|    0      7023      G   compiz                                       173MiB |
|    0      7503      G   ...-token=A4DF6F97357101C23AE30692EEAD51E2   120MiB |
+-----------------------------------------------------------------------------+

```
**nvcc --version**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

**Comment by psychocrypt** [comment]
Could you please restall the newest cuda version and restart the system. It
looks like the driver is not updated only the toolkit.

**Comment by renownedd** [comment]
I am having this same issue when trying to run nvidia and amd gpu at the same time, I have the most recent drivers. Will this miner work with both cards at once?

**Comment by JerichoJones** [comment]
@renownedd - You don't specify the OS. I run AMD/CPU/NVIDIA at the same time on Windows.

**Comment by renownedd** [comment]
It was something I had messed up. I figured it out thanks!

**Comment by chichicuervo** [comment]
Can you share what you did? I'm having this same problem. 

My crazy setup:  FreeBSD 11.1-RELEASE chrooted into a linux (debian jessie) jail.  nvidia-driver: 384.90, cuda: 9.0.176-384.81-linux

I'm seriously hoping it's a config thing and not minor version number.

**Comment by JerichoJones** [comment]
@chichicuervo What do you get back when you run:

nvcc --version

**Comment by axpatito** [comment]
+1 on this ticket. @renownedd pls share how you fixed.

**Comment by renownedd** [comment]
I had my nvidia on a pcie riser and forgot to connect the pcie power cord from the psu to the gpu.... After plugging it in it worked. I have had a lot of issues with it tho. I have had a lot of luck doing it as follows: use ddu to uninstall drivers. only connect one card at a time. So amd or nvidia first then install drivers. then disconnect that gpu and connect the other one install the drivers. then plug both gpus in and it works for me. I have also sometimes had to have a display connected to both gpus at the same time to get them to work properly. Otherwise programs like radeon settings wattman or geforce experience may not open because they dont detect a display connected to the gpu.

**Comment by JerichoJones** [comment]
@renownedd Thanks for this! 
>I have also sometimes had to have a display connected to both gpus at the same time to get them to work properly.
Dongles might help here.
