### ISSUE TITLE
Nvidia GPU mining error 206

### ISSUE THREAD

**Issue by TacticOwl** [fireice-uk/xmr-stak#404]
I keep getting an error at start up: 

[CUDA] Error gpu X: <Directory stuff .../nvcc_code/cuda_extra.cu>: 206
and then it crashes.

I've downloaded and installed NVIDIA Nsight HUD. I don't know what is causing this error. I have 6 1070's. Here is a copy of my nvidia config if that helps.

In geforce it says my installed driver is 385.54.

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 0,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 1,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 2,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 3,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 4,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6782/8192 MiB
  //      smx: 15
  { "index" : 5,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },

],

**Comment by psychocrypt** [comment]
Reduce the value of threads should solve the issue.

**Comment by cybercrypto** [comment]
I had the same issue with the new xmr-stak. I had to increase the bfactor  6 to avoid instant crash.
Funny thing is on xmr-stak-nvidia my config below works flawlessly and has a higher hashrate (~748h/)s compared to the new xmr-stak (~720h/s) because of bfactor 6.
 { "index" : 0, "threads" : 96, "blocks" : 15, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : 3}, <-- gtx 1070

Any idea why ?

**Comment by TacticOwl** [comment]
I reduced my threads to like 23. Overall getting a lower performance than
ccminer. By like 200 h/s.

**Comment by JerichoJones** [comment]
It sounds like your configuration is not optimal. Have you checked the [tuning guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md)?
