### ISSUE TITLE
compilation failure: cuda_core.cu(171): error: attributes are not allowed here

### ISSUE THREAD

**Issue by kroupouk666** [fireice-uk/xmr-stak#407]
While compiling with gcc-5, I've encountered the following error:

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/root/stuffs/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(171): error: attributes are not allowed here

1 error detected in the compilation of "/tmp/tmpxft_0001037e_00000000-23_cuda_core.compute_62.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.o.Release.cmake:282 (message):
  Error generating file
  /root/stuffs/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_core.cu.o

`
CMakeFiles/xmrstak_cuda_backend.dir/build.make:296: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmrstak_cuda_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/root/stuffs/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(171): error: attributes are not allowed here

1 error detected in the compilation of "/tmp/tmpxft_0001037e_00000000-23_cuda_core.compute_62.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.o.Release.cmake:282 (message):
  Error generating file
  /root/stuffs/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_core.cu.o

Tried on Debian unstable fully updated

**Comment by fireice-uk** [comment]
This looks like a broken cuda install

**Comment by kroupouk666** [comment]
reloaded the box - with all the updates that have been going on and forced to re-install all the nvidia and cuda drivers - error message remains.

**Comment by fireice-uk** [comment]
Try ubuntu, it seems to be more compatible.

**Comment by kroupouk666** [comment]
To close on that one.
 
I can successfully compile latest greatest code with
 
cmake .. -DMICROHTTPD_ENABLE=OFF -DCPU_ENABLE=ON -DHWLOC_ENABLE=ON -DCUDA_ENABLE=ON -DCUDA_ARCH=61
