### ISSUE TITLE
Devpool socket error in xmr-stak logs

### ISSUE THREAD

**Issue by szogun1987** [fireice-uk/xmr-stak#408]
Mine app cannot connect to devpool and switches back to users one (I don't know which wallet it uses on it). I appreciate you work, and I have nothing against mining for you a little bit.

**Comment by JerichoJones** [comment]
Is this still occurring? If so, post logs.

**Comment by szogun1987** [comment]
It seems that issue didn't occurred today. I see that one of mine machines produces some invalid shares. Some of them are marked as Duplicate share some Network problem. Please close this issue I will reopen it if I ensure that everything  is fine with mine mining equipment.

**Comment by szogun1987** [comment]
I have just figured out that I had connected miner to use nicehash with no-nicehash support pool-port
