### ISSUE TITLE
Poor performance i5-2500K

### ISSUE THREAD

**Issue by crazydoc72** [fireice-uk/xmr-stak#410]
Hi!
For testing purposes, I (also) try to mine with two of my CPUs. First one is a 2-core/4-threads AMD A10-7800K, second one a 4-core/4-threads Intel i5-2500K, both at standard clocks.  The AMD CPU looses each and every benchmark against the i7 (7zip, sysbench, HandBrakeCLI, ...), but can easily outperform the i7 at xmr-stak-cpu. A10 gives about 170 H/s with 2 threads whereas the i5 gives only 145 H/s with 4 threads. OS is the same, xubuntu 16.04.3 with Kernel 4.10, both machines have a SSD and 12 Gig of RAM. On both systems, hugepages is enabled. Why is the hashrate of the i5 so poor?

**Comment by sunk818** [comment]
what's the L3 cache on both CPUs? I get about 145 H/s on 3 cores on my i5. There's only 6MB of L3 so three threads is optimal.

**Comment by crazydoc72** [comment]
A10 has no L3 cache, i5 has 6MB. So I will try 3 threads.

**Comment by JayWalker512** [comment]
Looks like the A10 has 4mb L2 cache. I'm assuming that's shared between the cores, in which case you might get better performance on it by running only 2 threads with low_power_mode = false on each.

**Comment by crazydoc72** [comment]
Yeah, the A10 performs well with 2 threads. The problem is not the performance of the A10, but the i5 ;-). It doesn´t matter if I try to run it wit 3 or 4 threads, the hashrate stucks at about 145 H/s.

**Comment by sunk818** [comment]
Why do you expect it to be higher on an i5? That is the correct hash rate

**Comment by crazydoc72** [comment]
With 3 threads and setting hugepages to a value of 512 instead of 128, it works with about 205 H/s now :-)

**Comment by sunk818** [comment]
Oh. My bad. Where do you set to 512. I will need to try.

**Comment by NmxMilk** [comment]
On linux you have to follow theses steps:
1- sudo sysctl -w vm.nr_hugepages=128 
2- modify /etc/security/limits.conf to add hard and soft memory limits as stated in the config file
Usually you set the memlock value to 2048 times the huge page number
In this case 2048*128 = 262144 since huge page size is usaually 2Megs.
3- restart your shell, so that the new limits take effect
You can check the new limits with the command "ulimit -a" or only the memlock limit with "ulimit -l"

You should check also that no other program is already using the hugepages.

**Comment by JayWalker512** [comment]
@NmxMilk @crazydoc72 What distribution are you guys using? Every time I have tried configuring hugepages with Ubuntu I get problems on reboot.

**Comment by NmxMilk** [comment]
I'm on centos 7.
What problems do you get on reboot ?

**Comment by crazydoc72** [comment]
Ubuntu 16.04.3. No problems so far.

**Comment by JayWalker512** [comment]
@NmxMilk X fails to start, blinking cursor/error messages at boot, same as some of the issues reported here: [https://github.com/fireice-uk/xmr-stak-cpu/issues/54](https://github.com/fireice-uk/xmr-stak-cpu/issues/54)

I'll try again in a week when I have more time and report back.

**Comment by fireice-uk** [comment]
@crazydoc72 It is poor because you are using 4 threads. Please let the miner generate the config and work from there. It will generate a config with 3 treads for you.

@JayWalker512 Pleas open another issue.

**Comment by sunk818** [comment]
> With 3 threads and setting hugepages to a value of 512 instead of 128, it works with about 205 H/s now :-)

I tried on xmrig last night av=1 w/ 3 threads. Was able to get 190 H/s on i5 (Win 10 64-bit), so I believe you. :)
