### ISSUE TITLE
Where to get the freaking binary for windows? Do I really need to build it from scratch?

### ISSUE THREAD

**Issue by haalcala** [fireice-uk/xmr-stak#411]

**Comment by aaronsace** [comment]
https://github.com/fireice-uk/xmr-stak/releases

**Comment by akudlacek** [comment]
If you go to Download and to Releases it takes you to "https://github.com/xmr-stak/xmr-stak/releases" which is incorrect.

I ran into the same problem so i compiled it then later realized where they are at. This link needs to be changed. To the one aaronsace stated.

![capture](https://user-images.githubusercontent.com/7029639/33784802-cfd73996-dc27-11e7-9026-eb5843f9b694.PNG)

**Comment by psychocrypt** [comment]
already fixed in the dev branch
