### ISSUE TITLE
Miner not starting...

### ISSUE THREAD

**Issue by Mkorny** [fireice-uk/xmr-stak#412]
Hi guys, I just can't seem to get the miner to start up... after I fire it up it just drops back to the prompt, back on the path.

I'm running a GTX 1060 GB on an i5-4670.

So far, tried fully stopping all security software, rebooting switching HDD, confirmed virtual mem is @ 16gb, tested different pools, confirmed Cuda 8.0 + patch 2 is installed (tried different combinations of cuda dev kit versions), updated to the most current Nvidia drivers

Sample output:
```
...
...
...
    [2017-12-08 01:07:20] : Start mining: MONERO 
    [2017-12-08 01:07:20] : Starting NVIDIA GPU thread 0, no affinity.
    
    F:\Min\XMR>
```

note: before i was having 1 additional line with memory errors, confirmed the pagefile was at 16Gb & rebooted, sorted it.

**Comment by fireice-uk** [comment]
@Mkorny does 2.1 work for you?

**Comment by Mkorny** [comment]
@fireice-uk hey, thanks for the reply. I ended up testing on a new Windows User profile and it worked... 

Just formatted the damn thing and it got sorted ;)

Thanks for helping the community with this m8! :)
