### ISSUE TITLE
Error - C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:244

### ISSUE THREAD

**Issue by badincite** [fireice-uk/xmr-stak#413]
Cant seem to get this running
C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:244

This directory doesn't even exist on my pc what its about? Running windows 10 1709 getting the same error on my mining rig which runs Windows 10 1703

**Comment by fuomag9** [comment]
I get the same error

**Comment by sifotes** [comment]
Getting the same error when running a second copy of xmr-stak with `xmr-stak.exe --noAMD --noCPU.` 
`xmr-stak.exe`  Runs without error, AMD, Nvidia and CPU mining.

Windows 10 FCU, gtx 1070.

**Comment by sifotes** [comment]
Setting bfactor to 8 in nvidia.txt as suggest [here](https://github.com/fireice-uk/xmr-stak/issues/333) solved the issue.

**Comment by badincite** [comment]
I have a mixed rig 3 1060s and 1 rx 580 Ill try the bfactor but I think it was set to 8 already

**Comment by fuomag9** [comment]
putting it to 8 doesn't change anything, while putting it to 6 makes it last a bit and then I get the same error again

**Comment by psychocrypt** [comment]
reduce the number of threads used in nvidia.txt

**Comment by fuomag9** [comment]
for me it's solved! thank you :D

**Comment by badincite** [comment]
Yeah looks like bfactor to 8 solved my issue threads weren't the issue
