### ISSUE TITLE
xmr-stak stops reporting hashrate when time changes

### ISSUE THREAD

**Issue by KHouse75** [fireice-uk/xmr-stak#416]
I noticed that if the pc time changes xmr-stak stops reporting hashrate.

I haven't done extensive testing but when I run Linux with UTC time then switch to windows with EST and forget to fix the time, when windows time service catches it and drops it back 5 hours, xmr-stak stops reporting hashrate.

I tested by manually changing the time back 1 minute and it stopped reporting hashrate with (na) for 1 minute then started reporting again.  I suspect that if I let xmr-stak run for 5 hours after a UTC to EST change, it would start reporting again.

**Comment by fireice-uk** [comment]
@KHouse75 What is your OS + kernel version?

**Comment by fireice-uk** [comment]
Note to self: high_resolution_clock -> is_steady

**Comment by KHouse75** [comment]
Windows 10 Pro is where I've noticed this.  I haven't tried reproducing it in Linux yet..

**Comment by DavidBruchmann** [comment]
Don't change the time when it's running.
Time can be always critical when changed unexpected.

**Comment by KHouse75** [comment]
@DavidBruchmann Time change occurred automatically by NTP.  Linux typically sets the hardware clock as UTC and windows sets the hardware clock as local time.  When dual booting Linux/Windows or manually switching disks like I happen to do, the hardware clock ends up being off by several hours.  It's when NTP catches it and makes the change that the hashrates stop being reported.

The primary timea I could see this occurring for many people is starting and ending daylight savings time.

**Comment by DavidBruchmann** [comment]
Right I know that.
But changes by several hours are not in any limits.
A change within a few seconds or minutes makes often no problems, but depending on the software even 10 seconds are not accepted.

**Comment by marqueis301** [comment]
[electroneum-pool-master.zip](https://github.com/fireice-uk/xmr-stak/files/1565946/electroneum-pool-master.zip)

**Comment by fireice-uk** [comment]
Fixed in #664
