### ISSUE TITLE
"cpu_threads_conf" isn't working

### ISSUE THREAD

**Issue by katedutch** [fireice-uk/xmr-stak#418]
My CPU with 2 physical cores has a hyper-threading (4 virtual cores), but miner uses only 2.

configuration
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
], 
```
is ignored.

```
[2017-12-08 19:17:18] : Starting single thread, affinity: 0.
[2017-12-08 19:17:18] : hwloc: memory pinned
[2017-12-08 19:17:18] : Starting single thread, affinity: 1.
[2017-12-08 19:17:18] : hwloc: memory pinned
```
![screenshot at 2017-12-08 19-29-38](https://user-images.githubusercontent.com/8805308/33779700-39c5acfe-dc4e-11e7-9537-3e9f52c35b46.png)

**Comment by gerbilOFdoom** [comment]
Per the documentation in cpu.txt:

"Note that on hyperthreading 
 *                  systems it is better to assign threads to physical cores. On Windows this usually means selecting 
 *                  even or odd numbered cpu numbers. For Linux it will be usually the lower CPU numbers, so for a 4 
 *                  physical core CPU you should select cpu numbers 0-3."
