### ISSUE TITLE
Only 16 of 32-64 available cores appear when pressing 'h'

### ISSUE THREAD

**Issue by nueverest** [fireice-uk/xmr-stak#426]
I have over 16 cores available, but when I press 'h' I only see the stats for cores 0-15.  I am concerned that the miner is under utilizing the resources available by 50-75%.

Is there a config setting to fix this?

Mining is the only purpose of this machine.

**Comment by crazydoc72** [comment]
What CPU do you use? The miner works best if it uses only the number of "real" CPU cores, not the number of hyperthreaded cores.

**Comment by psychocrypt** [comment]
the miner is only using as much cpu cores needed to fully utilize the
cache. If you can see 16 miner threads than you cpu has 32MByte L3 Cache

**Comment by JerichoJones** [comment]
"Is there a config setting to fix this?" - Modify cpu.txt if you must.

**Comment by nueverest** [comment]
The statement by @psychocrypt is correct.  I did not realize how heavily the algorithm relied on L3 Cache.  I just assumed that having more cores was the key, but it seems that 2MB / core is required. So 64 cores requires 128MB or more of L3.  

I am discovering that 2MB seems like an optimistic number as my machine will lock up around 3-4MB per core.
