### ISSUE TITLE
AMD and NVIDIA GPUs wont work same time

### ISSUE THREAD

**Issue by renownedd** [fireice-uk/xmr-stak#427]
I have an msi radeon rx 570 4gb and an nvidia geforce gtx 750ti 4gb windforce oc edition, I am trying to use both at the same time. I have the most up to date drivers for both and they are the standard drivers, not blockchain. The 570 has a modded bios and oc and works fine as well as my CPU works fine, the issue is now that I am trying to add the 750ti with a riser xmr-stak is not able to identify a CUDA device. But before I had just the 750ti without a riser straight to the motherboard and before I got the 570 it worked fine. Any ideas?

**Comment by crazydoc72** [comment]
Is your 750Ti recognized by your OS when connected via riser? Some Mainboard <--> Riser <--> GPU combinations just dont´t work.

Which OS do you use?

**Comment by renownedd** [comment]
You know what man I am a fucking idiot and am to embarrassed to say what
was the issue. IT IS RUNNING GREAT!

**Comment by JerichoJones** [comment]
It happens to the best of us. ;)
