### ISSUE TITLE
mining with Nvidia and AMD, result rejected by the pool

### ISSUE THREAD

**Issue by acratia** [fireice-uk/xmr-stak#430]
i have 3x 1070 and 1 470

last night i use 3x 1070 and all accepted by pool. but when i installed 470 this afternoon, its automaticaly changed to rejected after a few minutes of accepted by the pools.

i tried to run xmr stak nvidia only, it works and accepted by pool.
i tried to run xmr stak amd only, it works and accepted by pool too.

but when i tried to use new xmr stak, using both nvidia and amd, it somehow changed into rejected by pool after a few minutes of accepted.

i've tried to uninstall the driver with ddu, change the config files and below is my last config files for nvidia and amd.

```
**NVIDIA**

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, "affine_to_cpu" : false},
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6795/8192 MiB
  //      smx: 15
  { "index" : 0,
    "threads" : 16, "blocks" : 120,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6795/8192 MiB
  //      smx: 15
  { "index" : 1,
    "threads" : 16, "blocks" : 120,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 6795/8192 MiB
  //      smx: 15
  { "index" : 2,
    "threads" : 16, "blocks" : 120,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },

],

**AMD**

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:3136
  // compute units: 32
  { "index" : 0,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

```

(i've been changed platform_index from 1 to 0 and 0 to 1.. still the same..

ive tried to overclock and return to default several times and no luck.

is there something that i missed?

thanks :)

**Comment by psychocrypt** [comment]
Could you please post the output if you press the key `r` to get the
result. I need the correct error message.
Which OS do you use.

**Comment by acratia** [comment]
i use win 10 pro 64, core i 7 7700 ram 8gb

![capture](https://user-images.githubusercontent.com/13401797/33794450-0c4caa78-dcff-11e7-88eb-95f07ce222b1.PNG)

**Comment by NmxMilk** [comment]
Hi,
When I see the white carret on your screen it makes me think this might be due to windows console default edit mode (see #362 ).

Clicking the mouse in the window's console puts it in edit mode (the title will change to select) and has the side effect of stalling sending results to the pool.

**Comment by psychocrypt** [comment]
@fireice-uk could you please check this. I am not familiar with the windows
cmd or is this a powershell issue.

**Comment by JerichoJones** [comment]
I think that NmxMilk is correct. Disable Quick Edit mode or stop clicking in the window.

**Comment by acratia** [comment]
@psychocrypt @NmxMilk @JerichoJones thanks for your responses..
i figured something out and it's work now. I guess its because of the pool itself. Now i've change my pool and all accepted by pool. idk if there is still a problem in xmr stak, but changing pools fixed this problem.
deepest thanks from the bottom of my heart :*
