### ISSUE TITLE
Error: cannot load backend library: xmrstak_cuda_backend.dll

### ISSUE THREAD

**Issue by shih1** [fireice-uk/xmr-stak#432]
cannot load backend library: xmrstak_cuda_backend.dll

# Basic information
Intel Core i7 6700HQ @ 2.60GHz
2047MB NVIDIA GeForce GTX 960M
Windows 10

# Issue with the execution
[2017-12-09 02:37:17] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled
[2017-12-09 02:37:17] : WARNING: backend NVIDIA disabled.
[2017-12-09 02:37:17] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-09 02:37:17] : WARNING: backend AMD disabled.
[2017-12-09 02:37:17] : Starting single thread, affinity: 0.
[2017-12-09 02:37:17] : hwloc: memory pinned

#issue with compile
c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  --
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

**Comment by psychocrypt** [comment]
which files are located in the folder with the binary xmr-stak

**Comment by shih1** [comment]
12/09/2017  02:22 AM             9,000 config.txt
12/09/2017  02:22 AM             1,653 cpu.txt
12/04/2017  09:13 PM         2,122,752 libeay32.dll
12/04/2017  09:13 PM           359,936 ssleay32.dll
12/09/2017  03:09 AM         1,618,104 xmr-stak-backend.lib
12/09/2017  02:19 AM            77,018 xmr-stak-c.lib
12/09/2017  02:20 AM           588,800 xmr-stak.exe
12/09/2017  02:20 AM           452,608 xmrstak_opencl_backend.dll
12/09/2017  02:20 AM               835 xmrstak_opencl_backend.exp
12/09/2017  02:20 AM             2,036 xmrstak_opencl_backend.lib

**Comment by psychocrypt** [comment]
ou compiled the mi er without the nvidia backend or you got an error during
the compile.

**Comment by shih1** [comment]
I switched over to CUDA 8 and I'm getting this error

LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812' [C:\Users\chris\Docum
ents\Monero\xmr-stak-master\build\xmr-stak.vcxproj]
LINK : fatal error LNK1257: code generation failed [C:\Users\chris\Documents\Monero\xmr-stak-master\build\xmr-stak.vcxp
roj]

With CUDA 9  I get this error. 

c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error: --
unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

These have been discussed before in previous issues and I've tried the fixes but they didn't work

**Comment by steeno** [comment]
shih, can you try to use the as [CUDA 8 declared dependencies](https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip)
and afterwards change the `-T v141,host=x64` part in your cmake cmd to `-T v140,host=x64`
it is important that you installed the VS2015 toolchain with **VC++ 2015.3 v140 toolset for desktop**, like mentioned in the windows compile guide
i didn't saw your issue earlier, so i stated the problem [here](https://github.com/fireice-uk/xmr-stak/issues/433)
does this solve your issue too?

**Comment by shih1** [comment]
hey this didn't solve my issues. I've tried both using CUDA 8 and CUDA 9 for install.

**Comment by JerichoJones** [comment]
"unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!"

I must have missed it. What are you using?
