### ISSUE TITLE
Windows compilation is broken after VS2017 update, possible workaround attached

### ISSUE THREAD

**Issue by steeno** [fireice-uk/xmr-stak#433]
When you try to compile xmr-stak on windows with cuda support and CUDA 9.0 after you updated your VS2017 version you will run in an error like **unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!**.
This is an issue based on the **_MSC_VER** check in **CUDAROOTDIR/include/crt/host_config.h:133**.
The version of VS got bumped to **1912** but cuda has only support up to version **1911**. Changing the check does not help.

Luckily you mentioned to also install the **VC++ 2015.3 v140 toolset for desktop** in your [compile on windows](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md) guide.

In this case you could still use the VS2015 toolchain to successfully be able to compile xmr-stak on windows. You just need to use the [v1 dependencies](https://github.com/fireice-uk/xmr-stak-dep/releases/download/v1/xmr-stak-dep.zip), even if you are using CUDA 9.0, you need to use the **v140,host=x64** target.

So download CUDA 9.0, install it somewhere, start your cmdline, load the VS environment varibales with
`"H:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\"vcvarsall.bat x86_amd64`
Set the path to the xmr-stak build dependencies with
`set CMAKE_PREFIX_PATH=H:\xmr-stak\deps\hwloc;H:\xmr-stak\deps\libmicrohttpd\;H:\xmr-stak\deps\openssl`
Generate the vs project files with
`cmake -G "Visual Studio 14 2015 Win64" -T v140,host=x64 -DCMAKE_BUILD_TYPE=Release -DCPU_ENABLE=ON -DCUDA_ENABLE=ON -DHWLOC_ENABLE=ON -DOpenCL_ENABLE=OFF -DOpenSSL_ENABLE=ON ..`
And finally start the build with
`cmake --build . --config Release --target install`

**Comment by steeno** [comment]
In this case you haven't set the CMAKE_PREFIX_PATH. If you download the xmr-stak-dep file and extract it somewhere, lets assume directly to c: for simplicity, you will find the following structure:
`c:/xmr-stak-dep/hwloc
c:/xmr-stak-dep/libmicrohttpd
c:/xmr-stak-dep/openssl`
So your CMAKE_PREFIX_PATH variable would look like
`CMAKE_PREFIX_PATH=c:\xmr-stak-dep\hwloc;c:\xmr-stak-dep\libmicrohttpd;c:\xmr-stak-dep\openssl`
And you can set this environment variable with
`set CMAKE_PREFIX_PATH=c:\xmr-stak-dep\hwloc;c:\xmr-stak-dep\libmicrohttpd;c:\xmr-stak-dep\openssl`
This has to be done in the same cmdline you use before you are calling cmake

Furthermore you can just use CUDA 9.0, you don't need to upgrade.

If this still doesn't work you could also disable the support of all third party dependencies with
`-DMICROHTTPD_ENABLE=OFF -DHWLOC_ENABLE=OFF -DOpenSSL_ENABLE=OFF`
So the first cmake command would look like
`cmake -G "Visual Studio 14 2015 Win64" -T v140,host=x64 -DCMAKE_BUILD_TYPE=Release -DCPU_ENABLE=ON -DCUDA_ENABLE=ON -DHWLOC_ENABLE=OFF -DOpenCL_ENABLE=OFF -DOpenSSL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF -DWIN_UAC=ON ..`

**Comment by shih1** [comment]
hm. Didn't know there was a binary release! It would have been easier. 

I got it to compile and and run without errors. I downgraded from CUDA 8.0 and repaired VS. Thanks for your help. I'm mining now!!

**Comment by Ossii** [comment]
I tried to follow this, but I end up With the following error:
```
"
"C:\xmr-stak-master\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak-master\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak-master\build\xmrstak_cuda_backend.vcxproj" (default target) (7) ->
(CustomBuild target) ->
  C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu(9): fatal error C1083: Cannot open include file: 'd
evice_functions.hpp': No such file or directory [C:\xmr-stak-master\build\xmrstak_cuda_backend.vcxproj]

    52 Warning(s)
    1 Error(s)
"
```

**Comment by steeno** [comment]
This is a cuda include file, have you restarted your cmdline after installing cuda? Can you open the CMakeCache.txt file in your build directory and check the variable CUDA_TOOLKIT_INCLUDE:PATH=, is it pointing to your cuda installation/include dir?
