### ISSUE TITLE
New version detection

### ISSUE THREAD

**Issue by Faaa97** [fireice-uk/xmr-stak#435]
A nice function to the miner would be, before anything else, to check for updates and drop a warning notifying that there is a new version available, if there is a new version.

This should be shut-down with --no-updates option or similar.

**Comment by lisergey** [comment]
That would add another 'wait-and-check-and-wait' burden load. What for?!!!
Cron, and other scheduler software do their job much better, than integrated 'version checkers'.
Please, do not.

**Comment by Faaa97** [comment]
> That would add another 'wait-and-check-and-wait' burden load. What for?!!!

That's why there should be an option to disable it.

This aims for general public. When GUI is done and non-tenchie people uses it, it'll be useful as they probably aren't hardcore/experienced miners.

> Cron, and other scheduler software do their job much better, than integrated 'version checkers'.
I didn't knew about the existence of that, I'll check how that works.

**Comment by lisergey** [comment]
> That's why there should be an option to disable it.
definitely yes.

Guess in GUI that would be appropriated.
Information about possible version upgrade, if it is not automated by means of external helper-app, requires human attention to decide is it really necessary, and how and when to do.

On the other hand, with farms, with multiple instances of this really productive software, that would be a headache if version checker would be active by default.

**Comment by fireice-uk** [comment]
@Faaa97 With the next version I will probably broadcast it via pool message.
