### ISSUE TITLE
Hashrate report readability

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#436]
This is just an opinion, but... When I first ran XMR-STAK (Ubuntu 16.04) I could not understand why it would only detect GPU0, GPU2 and GPU4. Only after a few hours I realized I was not reading the hashrate report table correctly. 

Maybe we should have just a standard table with each GPU in a separate line, like this:

**HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m 
|  0 | 492.0 | 496.1 | 496.9 
|  1 | 508.8 | 508.5 | 508.2 |
|  2 | 471.7 | 468.2 | 467.5
|  3 | 474.0 | 472.2 | 470.4 |**

Instead of:

**HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 492.0 | 496.1 | 496.9 |  1 | 508.8 | 508.5 | 508.2 |
|  2 | 471.7 | 468.2 | 467.5 |  3 | 474.0 | 472.2 | 470.4 |
-----------------------------------------------------**

Or, if the idea is to save terminal text space, all GPUs in a single line.

Because the one we have now is really very hard to read. ))

thanks.

**Comment by fireice-uk** [comment]
The first one would be very hard to read for people who have 64 cores worth of CPU. Try using the web ui for a nicer display.
