### ISSUE TITLE
2.1.0 isn't able to setup nvidia gpu

### ISSUE THREAD

**Issue by roberth1990** [fireice-uk/xmr-stak#441]
Using an nvidia gpu

Issue with the execution
  - Do you compiled the miner by our own? No

 Version: xmr-stak/2.1.0/30888a3/master/win/nvidia-amd-cpu/aeon-monero/20

```
-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-09 17:16:12] : Start mining: MONERO
[2017-12-09 17:16:12] : Starting NVIDIA GPU thread 0, no affinity.

GPU -1664092736: invalid device ordinal
C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu line 341
[2017-12-09 17:16:12] : Setup failed for GPU 0. Exitting.

```

After upgrading from 2.0.0, I am getting this error message.

**Comment by psychocrypt** [comment]
Could you please post the content of `nvidia.txt`

**Comment by roberth1990** [comment]
Oops forgot that.

```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1060 6GB architecture: 61
  //      memory: 5089/6144 MiB
  //      smx: 10
  { "index" : 0,
    "threads" : 82, "blocks" : 30,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : false,
  },

],
```

**Comment by psychocrypt** [comment]
mhh I checked the code and can not find why this can happen. Could you
please remove the dile nvidia.txt and start the miner again.

**Comment by roberth1990** [comment]
With the default nvidia.txt:

```
-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-09 20:55:09] : Start mining: MONERO
[2017-12-09 20:55:09] : Starting NVIDIA GPU thread 0, no affinity.

GPU -251660832: invalid device ordinal
C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu line 341
[2017-12-09 20:55:09] : Setup failed for GPU 0. Exitting.
```

**Comment by psychocrypt** [comment]
could you please install cuda 9 or 8 again. It could be a driver issue.

Am 09.12.2017 20:56 schrieb "Roberth Sjonøy" <notifications@github.com>:

**Comment by roberth1990** [comment]
I removed the driver with ddu and reinstalled, didn't help.

**Comment by CmdrKeen** [comment]
I'm also seeing this. I was using an earlier version (xmMiner_0.2.1) and it was working happily, but it blows up with the same error message that @roberth1990 is getting.

My nvidia.txt has:

> "gpu_threads_conf" :
> [
>   // gpu: GeForce GTX 1080 Ti architecture: 61
>   //      memory: 9312/11264 MiB
>   //      smx: 28
>   { "index" : 0,
>     "threads" : 54, "blocks" : 84,
>     "bfactor" : 6, "bsleep" :  25,
>     "affine_to_cpu" : false, "sync_mode" : 3,
>   },
> ]

I have cuda 8 installed (side q: is there any benefit in moving to 9?)

**Comment by psychocrypt** [comment]
please remove the config file `nvidia.txt` and start the miner. Please post the full output.

**Comment by CmdrKeen** [comment]
_after_ removing the nvidia.txt file and re-running:

-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-09 13:42:31] : Start mining: MONERO
[2017-12-09 13:42:32] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2017-12-09 13:42:32] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-09 13:42:33] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-09 13:42:33] : WARNING: backend AMD disabled.
[2017-12-09 13:42:33] : Starting 1x thread, affinity: 0.
[2017-12-09 13:42:33] : hwloc: memory pinned
[2017-12-09 13:42:33] : Starting 1x thread, affinity: 2.
[2017-12-09 13:42:33] : hwloc: memory pinned
[2017-12-09 13:42:33] : Starting 1x thread, affinity: 4.
[2017-12-09 13:42:33] : hwloc: memory pinned
[2017-12-09 13:42:33] : Starting 1x thread, affinity: 6.
[2017-12-09 13:42:33] : hwloc: memory pinned
[2017-12-09 13:42:33] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2017-12-09 13:42:33] : Pool pool.supportxmr.com:7777 connected. Logging in...
[2017-12-09 13:42:33] : Difficulty changed. Now: 25000.
[2017-12-09 13:42:33] : Pool logged in.
[CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

**Comment by psychocrypt** [comment]
This look like thre number of threads are to high. Could you please half the attribute `threads` in `nvidia.txt`

**Comment by CmdrKeen** [comment]
Indeed that resolved it. I set the thread count to 27. 

Hash rate seems relatively unaffected. I could also make it not crash by changing my bFactor to 8, and my bSleep to 100 (those were settings I'd used previously). While I'm a technical guy, I'm pretty n00bish with what these values really do (aside from improve or degrade interactivity with the system).

**Comment by roberth1990** [comment]
Sorry I missunderstood you @psychocrypt I removed the whole nvidia.txt and it's working now, but I have about ~15 H/S worse performance.
