### ISSUE TITLE
2.1 stak issue with JJ monitor

### ISSUE THREAD

**Issue by gregv64** [fireice-uk/xmr-stak#444]
just doanloaded the new 2.1 stak, let it run through. I started JJs hash monitor, it gets hung up here, right after enabling nvidia
JSON config parse error(offset 1540): Missing a name for object member.
Press any key to exit.

**Comment by psychocrypt** [comment]
The config for the backend AMD and NVIDIA gets a new attribute. Please open an issue in JJ's repository.
