### ISSUE TITLE
ubuntu compile error 2.1 without gpu

### ISSUE THREAD

**Issue by urza** [fireice-uk/xmr-stak#447]
Trying to compile 2.1 from git on ubuntu:

**sudo cmake .**
```
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5") CMake Error at CMakeLists.txt:203 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support
```

**even with -DCUDA_ENABLE=OFF parameter like this:**
`sudo cmake --DCUDA_ENABLE=OFF .`
got the same error

**even when I edit the CMakeLists.txt:**
`option(CUDA_ENABLE "Enable or disable CUDA support (NVIDIA backend)" OFF)`
still the same error

**Comment by psychocrypt** [comment]
Please do not compile software with sudo rights. Remove all files in the
build directory and try it again
Btw: it is `-D` not `--D`

**Comment by psychocrypt** [comment]
should be solved.
