### ISSUE TITLE
question: does the docker support require lines

### ISSUE THREAD

**Issue by logicminds** [fireice-uk/xmr-stak#450]
Docker runs natively on windows and linux.  Can I run xmr-stak in a container on windows with GPU support?

**Comment by JerichoJones** [comment]
This is not something we have tested. You will have to test it and see.  

It looks like pass-through may require a server OS.

**Comment by psychocrypt** [comment]
As I know nvidia is only shipping a linux docker file. I am also not sure
if a AMD gpu can be forwarded to be used in a container.
