### ISSUE TITLE
Fully turn off UAC prompt

### ISSUE THREAD

**Issue by Cleeez** [fireice-uk/xmr-stak#453]
Please provide as much as possible information to reproduce the issue.

With the new build there is no longer a way to fully turn off the UAC prompt. Why is this required? Is it for the large pagefiles ? 

Is there an compile option im missing to avoid it asking for admin privs on the first run since id rather avoid giving it any admin privileges. 

The old option I used to use in the previous build is gone

**Comment by psychocrypt** [comment]
You can start the miner with the option `--noUAC` this will turn of the UAC dialog.

**Comment by Cleeez** [comment]
@psychocrypt 
So it has moved into a command line options vs a cmake build option? No way to compile it like that?

**Comment by Cleeez** [comment]
I spoke to fierce on reddit and got info i needed thanks, closing
