### ISSUE TITLE
sorry, silly beginner question

### ISSUE THREAD

**Issue by DavidBruchmann** [fireice-uk/xmr-stak#455]
I created a wallet with the GUI and in the configuration for xmr-stak I'm asked for the wallet-address.
Have I to enter there the Public view key?
The pool I want to join never has a user-login, so the wallet-address is requested.

**Comment by psychocrypt** [comment]
You need to use you public address.

**Comment by DavidBruchmann** [comment]
Is address the same like key?

This is what is listed for the wallet:
Secret view key, Public view key, Secret spend key, Public spend key

So if I understand you right, I have to use the Public view key, is that correct?
