### ISSUE TITLE
Made a config for less GPU usage, but if not watching youtube/twitch hashrate drops to 0(na)

### ISSUE THREAD

**Issue by AskDrax** [fireice-uk/xmr-stak#456]
CPU = Ryzen 1800X @ 4.0GHz (running on 1,3,5,7,9,11,13,15 for ~640H/s)

GPU = GTX1080 FTW (stock config but bfactor 8, bsleep 100 for ~520H/s)

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 architecture: 61
  //      memory: 6762/8192 MiB
  //      smx: 20
  { "index" : 0,
    "threads" : 22, "blocks" : 60,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

runs fine but just basic web browsing is pretty laggy, watching youtube or twitch streams is totally lagged / slow motion hitching... 

so I tried making an alternate nvidia.txt (nvidialow.txt) which I made a shortcut to run --nvidia nvidialow.txt

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 architecture: 61
  //      memory: 6762/8192 MiB
  //      smx: 20
  { "index" : 0,
    "threads" : 17, "blocks" : 60,
    "bfactor" : 12, "bsleep" :  200,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

This works great, ~450H/s and can watch 1080p60fps youtube or twitch stream totally smooth...

However if I stop watching video... the GPU hashrate immediately drops to 0.0 (NA)

I think the cause is the bsleep value but not 100% sure. It seems like anything higher than 100 will drop to NA unless some streaming video is playing.

Is there a problem with using bsleep higher than 100?

Thanks for any info :)

**Comment by fireice-uk** [comment]
> Is there a problem with using bsleep higher than 100?

No, as long as you are happy with the performance.

**Comment by AskDrax** [comment]
Performance is good but only if I'm watching video, as soon as I stop watching video, GPU hashrate drops to 0 (says NA in console). This seems to happen only with bsleep > 100?

**Comment by psychocrypt** [comment]
Please look to the one minute average after you stopped the vidio stream.
It could be that your gpu is not finishing the hashing tasks within 10sec
with this high bfactor and sleep. If you use a high sleep and bfactor of 12
than the gpu reduce the clock speed because of the long idle. Try bfactor
10 and bsleep 25. That should be ok to whatch videos.
