### ISSUE TITLE
CUDA crash on 2.1 at line 266

### ISSUE THREAD

**Issue by dprestegard** [fireice-uk/xmr-stak#458]
When I start the new miner it immediately crashes referencing the following error:

[CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

# Basic information
GeForce GTX 770
Windows Server 2016
Driver 385.41
Intel P35 chipset w/ i7 2600k
No overclocking, totally stable on older builds

# GPU config generated by 2.1:
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 770 architecture: 30
  //      memory: 1677/2048 MiB
  //      smx: 8
  { "index" : 0,
    "threads" : 62, "blocks" : 24,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],

# GPU config I'm using in the old build:
"gpu_threads_conf" : 
  [
      { "index" : 0, 
"threads" : 16, "blocks" : 24, 
"bfactor" : 8, "bsleep" :  100, 
"affine_to_cpu" : false},
  ],

Switching to these old settings seems to work fine, but makes a very low hash rate, about 160, vs approx 580 on the old build.

**Comment by zr26060** [comment]
Same thing for me , I was finally totally stable on older build , I passed the last 3 weeks to play with threads , blocks , bfactor , bsleep , drivers , win10 with XMR-STAK nvidia and now again with 2.1  threads , blocks , bfactor , bsleep... I stopped playing with my kids just to try to make this thing run stable....

**Comment by sergneo** [comment]
For all Nvidia GPU's always need to install
"bfactor" : 8, "bsleep" : 100 and manual to choose "threads" and "blocks"

**Comment by awhittle3** [comment]
I was experiencing this issue on Windows 10 before I made pull request #445, which fixes the sleep function in Windows builds.

**Comment by psychocrypt** [comment]
it should also help to start with the auto suggested config and than reduce
the threads value by 2 up to the issue is aolved.

**Comment by ZUBRS** [comment]
I have that problem too. 
My conf

> > "gpu_threads_conf" :
> [
>   // gpu: GeForce GTX 1080 Ti architecture: 61
>   //      memory: 9312/11264 MiB
>   //      smx: 28
>   { "index" : 0,
>     "threads" : 20, "blocks" : 45,
>     "bfactor" : 6, "bsleep" :  25,
>     "affine_to_cpu" : false, "sync_mode" : 3,
>   },
> 

> 
As default was bfactor-0 bsleep-0. 
I try many type of Threads and block value - but nothing help.
Please help.
I try threads value 20, 26 - nothing help.

**Comment by ZUBRS** [comment]
update.
setup  "bsleep" : 100 - all OK

**Comment by zr26060** [comment]
Finally replaced my MSI Z270-a pro ( random code 43 with 2 gpu of 6 )  and xmr-stak stability issues whatever threads , blocks , bsleep , bfactor....

Now I've got the Asus B250 mining expert , this MOBO runs stable right off the box , no drivers and no xmr-stak issues....

6 GTX1070 SC  threads : 32  blocks : 45 bfactor : 8 bsleep : 100

615 H/s X 6 = 3690 H/s  without OC
