### ISSUE TITLE
UAC handle side effect when create new process

### ISSUE THREAD

**Issue by anhphan** [fireice-uk/xmr-stak#46]
When xmr-stak prompt  UAC dialog to ask you, if you select yes, new process will be created and **it will ignore all command line parameter**.

Beside that, UAC handle is very annoying with who having correct setting about large page (you can even use large page when answer no), it's should have a switch or config option to enable or disable it. If it cannot turn on/off by switch/option please leave it as xmr-stak-cpu

**Comment by fireice-uk** [comment]
>  (you can even use large page when answer no)

Are you sure about that part? If yes please post the system and policy rights for the account

**Comment by anhphan** [comment]
I running windows 10 x64 with the account belong Administrators group (not the Administrator) and that account linked to Microsoft account. 

The local policy (edit in gpedit.msc): `Local Computer Policy/Computer Configuration/Windows Settings/Security Settings/Local Policies/User Rights Assignment/Lock pages in memory` content my account and Administrator account.

As I remember after change local policy, I must restart computer, the command `gpupdate -Force` is not help.

**Comment by fireice-uk** [comment]
Ok, this might be a change from Windows 7 where I do my testing then. I want to do UAC support to make the miner easier to use, but you are correct about the parameter problem. 

I think the only way is to have the windows build to include UAC manifest (you will need to click yes to start the program), with an optional flag to build without it.

**Comment by anhphan** [comment]
Ok, build option is also good choice.

I don't have windows 7 anymore, then not sure about it. But I remember windows 7 have 4 level of UAC. Do you testing `xmr-stak-cpu` (which not having uac manifest) with level: `Only notify me when programs try to make changes to my computer`.
