### ISSUE TITLE
this happens when i am trying to mine electroneum with a 1060 is anyone able to help 

### ISSUE THREAD

**Issue by HackerDanny** [fireice-uk/xmr-stak#460]
[2017-12-10 21:59:58] : Pool us-etn-pool.hashparty.io:5555 connected. Logging in...
[2017-12-10 21:59:58] : SOCKET ERROR - [us-etn-pool.hashparty.io:5555] invalid address used for login
[2017-12-10 21:59:58] : SOCKET ERROR - [us-etn-pool.hashparty.io:5555] RECEIVE error: A blocking operation was interrupted by a call to WSACancelBlockingCall.

**Comment by txtasosxt** [comment]
Hello, not an expert here but the "SOCKET ERROR" points to a problem with your connection to the pool as far as I know. The "invalid address used for login" that follows it makes me think that you've got your wallet or your password wrong. Check the pool's guide again. I'm 99% sure your problem has nothing to do with the miner.

**Comment by NmxMilk** [comment]
Out of curiosity just pointed my miner to electroneum pool, and it works fine !

![image](https://user-images.githubusercontent.com/30717667/33807097-08edc064-ddd2-11e7-8f12-ddd6902bddbc.png)

The message your getting seems to indicate the wallet address your using is not valid.
Check you config which should look like this:
```Json
"pool_address" : "us-etn-pool.hashparty.io:5555",
"wallet_address" : "etnkQAXLc2D2xNFtKJcZ9nCFF26xSLrFh6BwRQGR6vnZRfLLBZVzgBXKvxdFhSwU1GiEfPqFpHJG8WT9BnSF6XoR8DdE8CGcHH",
```
Happy mining

**Comment by fireice-uk** [comment]
@HackerDanny This is caused by a network-enabled antivirus or firewall.
