### ISSUE TITLE
Optimal GPU configuration for the GeForce 930MX

### ISSUE THREAD

**Issue by borzaka** [fireice-uk/xmr-stak#462]
This is my default nvidia.txt for my [GeForce 930MX](http://gpuboss.com/graphics-card/GeForce-930MX)
```
"gpu_threads_conf" :
[
  // gpu: GeForce 930MX architecture: 50
  //      memory: 1697/2048 MiB
  //      smx: 3
  { "index" : 0,
    "threads" : 86, "blocks" : 9,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],
```

I have changed `bsleep` to 100, because it's a GUI system.
With this, I got a ~34 H/s in the 60s and 15m hashrate report, but no 10s report.
I should get around [65 H/s](https://coinad.info/gpu-benchmarks/).

I don't understand the [Tuning Guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md) :(
Can you tell me what `threads`/`blocks` should I use with this GPU? I think it has 16 multiprocessors (Render output processors: 16), but I'am not sure. It has 24 texture mapping units.

- Windows 10 64 bit
- xmr-stak 2.1.0 30888a3
- NVIDIA 388.59 driver
- no overclocks

**Comment by psychocrypt** [comment]
the gpu is to slow to generate a bunch of hashes within 10s. But do not
worry thats no problem. You can try to reduce threads in nvidia.txt maybe
you will get a few hashes more.

**Comment by borzaka** [comment]
I tried many combinations, and I successfully made 77.5 H/s even within 10s with this config:
```
"gpu_threads_conf" :
[
  // gpu: GeForce 930MX architecture: 50
  //      memory: 1697/2048 MiB
  //      smx: 3
  { "index" : 0,
    "threads" : 8, "blocks" : 32,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : 1, "sync_mode" : 3,
  },
],
```
The next closest was 8 `threads`/ 24 `blocks ` with 77 H/s.
I hope my config will help someone.

Note: `affine_to_cpu` is set to 1 because that number was not listed in the cpu.txt's `cpu_threads_conf`, and I'am mining with my CPU as well.

**Comment by sergneo** [comment]
Model GeForce 930M — this is the Maxwell architecture 1.0. This video card uses the chip GM108 with 384 CUDA cores in the **three** SMM-multiprocessors. ( **//      smx: 3** )
Thus, the number of blocks must be a multiple of the number of smx. You have "blocks" : 32, not divisible by 3. Therefore, it is not the optimal configuration.

**Comment by borzaka** [comment]
Thank you for the information! I tried again many combination, and these are the best with the same hashrates: 76.4 H/s
- 8 `threads` / 18 `blocks`
- 8 `threads` / 27 `blocks`
- 8 `threads` / 36 `blocks`

I'am using the 8 / 36 right now.
