### ISSUE TITLE
SOCKET ERROR - [xmr.pool.minergate.com:45560] CALL error: Timeout while waiting for a reply

### ISSUE THREAD

**Issue by ArthurPinhas** [fireice-uk/xmr-stak#463]
Hello everyone,

When i use the xmr-eu1.nanopool.org:14444 for example,i dont have any issues at all.
Only when i use the minergate pool.
Here is my config:
"pool_list" :
[
	{"pool_address" : "xmr.pool.minergate.com:45560", "wallet_address" : "username", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },

Is there something im doing wrong or missing?

**Comment by glendale789** [comment]
I also get the same error with Suprnova pool using xmr-stak 2.1.0

SOCKET ERROR - [xmr-us.suprnova.cc:5221] CALL error: Timeout while waiting for a reply

**Comment by psychocrypt** [comment]
please open a ticket somewhere by minergate. This is an minergate issue.

btw: do not use minergate.

**Comment by ArthurPinhas** [comment]
Why shouldn't i use minergate?
I mainly use it because i am new to mining,and it just simplifies the whole process.

**Comment by psychocrypt** [comment]
please search for minergate in reddit monero and moneromining

**Comment by Killswitch1982** [comment]
Claymore miner connects fine to minergate. So it is problem of xmr-stak.

**Comment by Renkyz** [comment]
After what happened to Nicehash, I wouldn't trust using a service like that or Minergate again. Luckily I only lost about $80 when Nicehash got hacked. I promptly went back to mining on Nanopool and storing my funds in a cold wallet.

**Comment by ArthurPinhas** [comment]
Yeah,i think i should try and make a cold wallet.(it just seems more complicated than using a hot wallet)
And it seems like the issue is with the xmr stak. xmrig doesnt give me the same issue with the minergate pool.
First i had an issue with the xmrig just closing right when i try and open it.
Then i looked at the config file and figured out it was the settings for my gpu that caused it to shutdown right away.
