### ISSUE TITLE
Consistently lower hashrate for 2nd, 3rd cards?

### ISSUE THREAD

**Issue by hhalim** [fireice-uk/xmr-stak#466]
Thank you for working on this miner, absolutely fantastic for monero/electroneum mining. Not sure if this is a setting issue or something else and I've been running xmr-stak for the past 2 days.

# Basic information
MSI Nvidia GTX 1070 8GB Armor
Ubuntu 16.04
Intel Celeron 3930

# Stability issue
The 2nd and 3rd cards are consistently reporting lower hashrate avg of 640-650 ish. The first card is averaging in 718. All 3 cards are the same make, model, and OC settings.
GPU set to 100 watt max.
GPU clock +100, Memory +1260
The machine is running stable, no crashing or stopping issue, but the hashrate is not consistent.
The xmr-stak was successfully compiled with CUDA 9.

```
HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 720.7 | 718.3 | 718.4 |  1 | 708.1 | 646.9 | 640.6 |
|  2 | 715.9 | 646.9 | 639.0 |
-----------------------------------------------------
Totals:   2144.7 2012.1 1998.0 H/s
Highest:  2165.1 H/s
```

Nvidia.txt setting, as configured, no changes:
 ```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 7953/8112 MiB
  //      smx: 15
  { "index" : 0,
    "threads" : 86, "blocks" : 45,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 8003/8114 MiB
  //      smx: 15
  { "index" : 1,
    "threads" : 86, "blocks" : 45,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 8003/8114 MiB
  //      smx: 15
  { "index" : 2,
    "threads" : 86, "blocks" : 45,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },

],
```

**Comment by psychocrypt** [comment]
The reason is a bottleneck in the driver. You could try to start three
miner instances and check if this is running better.
I am aware of this issue but have currently no solution.

**Comment by Renkyz** [comment]
I don't get this on Windows 10. Have a rig with 2 1070's that get near identical performance. Maybe if it's an option for you, you could try it with Windows?

**Comment by psychocrypt** [comment]
The windows and linux driver differ. But if you can not see this behaviour
on windows than it is a strong sign that xmr-stak is doing all correct and
the driver is the bottleneck.

**Comment by dgiero** [comment]
I have the same issue with 2 Tesla card, the second reports lower hashrate then the first. I'm using linux and nvidia driver 384.81.

**Comment by hhalim** [comment]
Thank you for the replies, much appreciated. It's currently running 384.98 driver. I'll try windows 10 and a different driver version in Linux too.

**Comment by hhalim** [comment]
Tried it with nvidia 387.34 driver got a consistent hashrate:
```
HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 722.3 | 721.4 | 721.7 |  1 | 722.6 | 721.9 | 722.4 |
|  2 | 722.8 | 723.0 | 722.9 |
-----------------------------------------------------
Totals:   2167.7 2166.4 2167.1 H/s
Highest:  2171.2 H/s
```
