### ISSUE TITLE
Different cards, almost same hashrate

### ISSUE THREAD

**Issue by dgiero** [fireice-uk/xmr-stak#467]
Hi, I'm mining with 4 cards, as listed below. They are very different cards with different GPUs and performances, nevertheless they have pretty much the same hashrate, around 400H/s.
They are all in different pc, with linux (centos or ubuntu)

  - GTX480 1.5GB (1.35TFlops)
  - GTX680 4GB (3.1TFlops)
  - 4x TESLA K20c 5GB  (3.95TFlops)
  - TESLA K40m 12GB  (4.29TFlops)

I tuned all of them by nvidia.txt to get the maximum performances. 
How can a gtx480 performing as a tesla k40? The latter has 3 times the calculation power of the former.
Is it related to the cuda limitation of using at most 2GB of VRAM?
Can you tell me more about this limitation? I couldn't find any information about it.

PS: I also have 2 GTX470 1.2GB, they make 280H/s.

**Comment by JerichoJones** [comment]
This is a question more suited to a NVIDIA forum. Like this one https://devtalk.nvidia.com/

**Comment by dgiero** [comment]
Which of the two questions is more suited to NVIDIA forum? 
The first one is related to xmr-stak miner, the second one to the xmr-stak code.
Video cards can use all the GDDR, otherwise it will be senseless put so much memory, All the programs that use CUDA can allocate more than 2GB. I couldn't find any post regarding the cudamalloc limitation. in the NVIDIA forum. so I was wondering why the miner has such a limitation.
