### ISSUE TITLE
XMR keeps crashing, can't mine

### ISSUE THREAD

**Issue by neptune-klm** [fireice-uk/xmr-stak#468]
Running the below laptop
Asus i7
Nvidia GEForce GTX 660M, 2.0GB
Windows 10
64 bit

My driver says it has the latest driver, I downloaded the prereq microsoft ++, but I keep getting the error that XMR stak stopped working.  I am a complete noob, so I have no idea what the issue is.  See pic
![error](https://user-images.githubusercontent.com/34425869/33809716-31a6c856-ddc9-11e7-945d-0b469660e51a.jpg)

When I opened nvidia.txt, here is what is there...

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 660M architecture: 30
  //      memory: 1702/2048 MiB
  //      smx: 2
  { "index" : 0,
    "threads" : 130, "blocks" : 6,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,

**Comment by ernestp** [comment]
+1

**Comment by psychocrypt** [comment]
increase bfactor in nvidia.txt to 8

**Comment by DavidBruchmann** [comment]
Offtopic you still could skip scanning for AMD like described here: #470

**Comment by ernestp** [comment]
>increase bfactor in nvidia.txt to 8

Does not help. still crashing on 6 Nvidia rig

**Comment by psychocrypt** [comment]
please provide mere information else we can not help.
we need all output and comamnds used. And the nvidia.txt

**Comment by ernestp** [comment]
This crash for first release
output:

```
[2017-12-16 15:37:58] : New block detected.
[CUDA] Error gpu [CUDA] Error gpu 1[CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu 3[CUDA] Error gpu 520: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu: <: <: <4: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cuC:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:341: <>:341
C

```

No command line options was used.

[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1564890/nvidia.txt)

**Comment by psychocrypt** [comment]
please update to the latest release

**Comment by ernestp** [comment]
Latest release showing me this:

![screenshot at dec 17 00-11-19](https://user-images.githubusercontent.com/7553589/34072712-f1639256-e2be-11e7-8a50-71386ec742dc.png)

I tried to add exception, but this window still showing.

Miner still starting anyway, but not sure if it in good way.

**Comment by psychocrypt** [comment]
I can not help you with that because I do not know your system. Please fix
first you protection software issue.

**Comment by ernestp** [comment]
latest miner crashed after 2 min, will paste output when it finish log

**Comment by ernestp** [comment]
Disabled antivirus, reduced threads to 20, run with --noCPU
will see how it goes.

**Comment by ernestp** [comment]
Crashed again

```
[CUDA] Error gpu 0[CUDA] Error gpu : <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:[CUDA] Error gpu 2444
[CUDA] Error gpu 12: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvi
```

text not truncated by copying, it all that was in console 20 min after crash

**Comment by psychocrypt** [comment]
set bfactor to 8 or/and reduce the threads

**Comment by ernestp** [comment]
bfactor already 8
threads 20

**Comment by Shinjuku1** [comment]
I'm also getting random crashes. I will continue to diagnose the situation, currently running an AMD and Nvidia in the same system ;)
