### ISSUE TITLE
Can't seem to get the miner to use CPU only

### ISSUE THREAD

**Issue by hi4rahul** [fireice-uk/xmr-stak#470]
I have not been able to configure the miner to use CPU only. It detects my GPUs and starts using them too, which I do not want as I am using them for other mining.

Please guide.

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by DavidBruchmann** [comment]
if you open commandline and xmr-stak from there like this:
xmr-stak.exe --help
you'll discover that there are parameters to disable the cards when you open.xmr-stak.
You've to create a batch-file to open it always with the parameters.
Did you try this?

Here is my batchfile for this:
```
F:\___BLOCKCHAIN___\xmr-stak-win64\xmr-stak.exe --noAMD --noNVIDIA

if errorlevel 255 goto finish
if errorlevel 1 goto error
goto finish

:error
echo.
echo xmr-stak.exe konnte nicht gestartet werden
echo xmr-stak.exe could not be started
pause

:finish
```
Just adjust the path, save it as xmr-stak.bat (or something else but with extension bat) and you can start it by click on that file then.

**Comment by carlo0000** [comment]
thanks i was looking for this too

**Comment by DavidBruchmann** [comment]
You can be creative too by creating several batch-files with different parameters in each ;-)

**Comment by ernestp** [comment]
CLI for devices is good, but having this in config will be great

**Comment by DavidBruchmann** [comment]
if you use batch-files you enter it once and use it only by clicking.
Never studied the amd and nvidia config-files if they could be skipped there but in the general config file I at least never found the words amd or nvidia, never searched more.
Agree that the params in the config-file would be good, but I never know if the params can be set there too.

**Comment by DavidBruchmann** [comment]
The batch files have the advantage that you can have a config for work (where the resources for xmr-stak are limited) and one for night with full power.
Just two examples of many options and requirements ...

**Comment by izacs** [comment]
You missing the point im talking about cpu not gpu 
second no config file will not work becuase every vps have it own cpu so the system should detetvt that and chose best permfomance if you bot config file u will end up runninmg 16 threads in 4 threads vps or 4 threads in 16 threads vpss

Thes is for alot of machines man for 1 mahcine yes not problem set these manully buy if you cloud mining and make like 20 vps per day is itsa easy jop to set 20 daily - so i will simply add script to the boot which do all the job without me doing any thing which why i need the commands for that !

**Comment by hi4rahul** [comment]
hey, Thanks for the help with CPU... I am having another issue I believe... I have a intel i7-7700K CPU but am getting a max of 90 h/s. 50 % cpu and 22% mem utilisation.. .any suggestions on improving it?

**Comment by DavidBruchmann** [comment]
strange I get 260-300 H/s with that CPU (raised somehow, in the beginning it was 230-260).
Don't have a graphics-card, so its really the CPU only.
Everything I have in CPU.txt is this:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },

],
```

**Comment by DavidBruchmann** [comment]
BTW: I have i7-7700 CPU (without K)
Don't know the difference, but probably there is one.

**Comment by hi4rahul** [comment]
I will chk what the K is for... 
MY file looks like this:
"cpu_threads_conf" :
[
    { "low_power_mode" : 5, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : 5, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : 5, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : 5, "no_prefetch" : true, "affine_to_cpu" : 6 },

],

**Comment by hi4rahul** [comment]
I changed the false to 5, to see if I could raise it any higher.

Will revert back yo false and check again.

Have you tried running multiple instances of the miner  on the same CPU? I did not notice much - the net seemed to be the same

**Comment by hi4rahul** [comment]
K - The k means the processor has an unlocked multiplier, meaning you can overclock the CPU in the bios by simply increasing the CPU multiplier.
but you need a supporting MOBO

**Comment by DavidBruchmann** [comment]
Hehe, no I didn't.
But as long as you never get 300 or more I don't see a reason ;-)

**Comment by DavidBruchmann** [comment]
With overclocking I wait till I can increase something about cooling.
Else I can forget about my CPU.

**Comment by hi4rahul** [comment]
> 

Hehe, no I didn't.But as long as you never get 300 or more I don't see a reason ;-)
--

I did that for this reason... am going back to false and trying again... Not interested in overclocking at the mo, am prepared with a liquid cooling system

**Comment by DavidBruchmann** [comment]
Yeah, liquid cooling is nice, don't know yet when I can realize that.
Several instances are useful if you mine different currencies or if you have different configs for have if the cores or something like that. But using the same instance on the same core is useless I guess.

**Comment by hi4rahul** [comment]
YaY.. jumped to 300!! Thank you!!

**Comment by DavidBruchmann** [comment]
Welcome ;-)

**Comment by hi4rahul** [comment]
Have you tried with multiple currencies? Does it impact the hash rates among them?

**Comment by DavidBruchmann** [comment]
No I didn't yet, but I read a post here somewhere where a guy used CPU for Monero and GPUs for something else.

**Comment by hi4rahul** [comment]
I am also doing that - 1 GPU for Eth and the CPU for Monero now. Sharing GPU slows down the ETH mining on the GPU

**Comment by hi4rahul** [comment]
Since the CPU is only 54% used, am interested in exploring another one...

**Comment by DavidBruchmann** [comment]
54% is because it's advised not to use the virtual but only the real cores.

**Comment by DavidBruchmann** [comment]
You could try to use all cores 0-7, but it's not advised and can have a bad impact on the results of your mining.

**Comment by hi4rahul** [comment]
i7-7700K has 4 cores and 8 logical processors - so I think if we are not to use virtual, the miner correctly discovers 0-3. Which proves your earlier point.

**Comment by DavidBruchmann** [comment]
yeah, was already curious if you'd try that :D

**Comment by hi4rahul** [comment]
I am tempted to try... Resource monitor shows CPU 0/2/4/6 at 100 % utilisation while 1/3/5/7 have random spikes - mostly 10%, so maybe add a few . I wil try to morrow and see how it goes

**Comment by DavidBruchmann** [comment]
Lol, I knew it.
Ok, let me see the result of your experiment then.
Maybe then it's useful to use the 5 in the settings again ... don't know ...

**Comment by hi4rahul** [comment]
Ha Ha... Let me do it... adding 1 should not be bad - Else I won't get sleep

**Comment by hi4rahul** [comment]
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   38.2 |   32.7 |   (na) |  1 |   68.4 |   67.3 |   (na) |
|  2 |   58.3 |   60.5 |   (na) |  3 |   26.5 |   25.9 |   (na) |
|  4 |   26.3 |   25.5 |   (na) |
-----------------------------------------------------
Totals:    217.7  212.0   (na) H/s
Highest:   220.9 H/s

CPU6/7 are working at 100% but the hash rate has taken a hit as there seems to be no output/ unstable?

**Comment by DavidBruchmann** [comment]
mhm only No.1 is normal, the others are to low

**Comment by DavidBruchmann** [comment]
at least without some special tweaks perhaps it's better to switch back

**Comment by hi4rahul** [comment]
yep... GN for now... will try another currency on CPU tomorrow and see if that is feasible. Do let me know if you try somethng ;)

**Comment by DavidBruchmann** [comment]
all right, will lay down too again. See you ;-)

**Comment by DavidBruchmann** [comment]
btw: longest thread of open issues, lol

**Comment by JerichoJones** [comment]
A general rule that I use for CPUs:

"low_power_mode" : false,
L3 / 2 = # of threads

"low_power_mode" : true, - I have never had much luck with this setting but others claim that they have
L3 / 5 = # of threads

If you get creative you can mix modes but I have never gone that far down the rabbit hole.

**Comment by DavidBruchmann** [comment]
mhm, having problems to understand the notation `L3 / 2 = # of threads`

**Comment by DavidBruchmann** [comment]
I know its L1-L3 cache, I just mean the whole notation.

**Comment by JerichoJones** [comment]
L3 cache divided by 2 equals Number of Threads

**Comment by KAOS191** [comment]
Using i7 8700k on stock. --noNVIDIA -noAMD

| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   27.9 |   (na) |   (na) |  1 |   29.8 |   (na) |   (na) |
|  2 |   30.2 |   (na) |   (na) |  3 |   29.7 |   (na) |   (na) |
|  4 |   28.4 |   (na) |   (na) |  5 |   27.6 |   (na) |   (na) |
Totals (CPU):   173.6    0.0    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):    173.6    0.0    0.0 H/s
Highest:   174.0 H/s
---------------------
I tried 10x times to start it. Pagefile usage didn't move (MSI Afterburner for monitoring) and few times ONE of  the cores changed speed to 60

config:
"cpu_threads_conf" :
[   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 } ]

Then I used CPU and my 6x 1050ti

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   57.8 |   (na) |   (na) |  1 |   66.1 |   (na) |   (na) |
|  2 |   69.6 |   (na) |   (na) |  3 |   69.1 |   (na) |   (na) |
|  4 |   67.3 |   (na) |   (na) |  5 |   61.4 |   (na) |   (na) |
Totals (CPU):   391.3    0.0    0.0 H/s
-----------------------------------------------------------------

Please someone explain what am I doing wrong. Why I have only randomly this hashrate on solo CPU?
