### ISSUE TITLE
trouble compiling the source code?

### ISSUE THREAD

**Issue by Lowbudgetgamer04** [fireice-uk/xmr-stak#471]
Hi,
I have am having problems compiling the source code. I got all the way to the last step where you have to compile it.
![xmr](https://user-images.githubusercontent.com/34432109/33815792-df3dd1b4-ddf9-11e7-8674-440a04fa8faf.jpg)
The i get this error:
![xmr_command](https://user-images.githubusercontent.com/34432109/33815802-ee275768-ddf9-11e7-93b3-fafc7dbaeb4d.jpg)
What did i do wrong are you supposed to change that part in the second line CMAKE_PREFIX_PATH.
any help would be greatly appreciated.

**Comment by maxcr** [comment]
You don't have cmake installed. Make sure you have all of the C/C++ dev libraries installed.

**Comment by Lowbudgetgamer04** [comment]
@maxcr I do have cmake installed i even checked the box to add cmake to the system path for all users. I installed the cuda thing and i downloaded the other library zip and unziped to xmr-stak-dep.

**Comment by Lowbudgetgamer04** [comment]
Nvm i got it figured out. It was either i didnt have all of the visual studio toolkits installed or that when wasnt back in the source code file when i tried that cmake command.
