### ISSUE TITLE
Cannot find xmr-stak-portbin-linux.tar.gz

### ISSUE THREAD

**Issue by hume12** [fireice-uk/xmr-stak#474]
Hi, I'm trying to follow the docs and install the miner on Ubuntu for the first time, but can not find xmr-stak-portbin-linux.tar.gz as described [here](https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md).

So I downloaded and extracted https://github.com/fireice-uk/xmr-stak/archive/v2.1.0.tar.gz instead, but could not find `xmr-stak.sh` anywhere but on the `/doc/Linux_deployment.md:`. 

So I guess the documentation needs to be updated.

**Comment by psychocrypt** [comment]
There is a mark in the docs that if we have trubble with the portable bin
that we remove it. Currently the bins make to much trubble, we work on a
solution.

**Comment by fhlfibh** [comment]
It would be great if you only added more info about how to compile the miner on Linux, with configuration options.

**Comment by Kabouik** [comment]
I hope a solution can be found so that the portable binary can return, I wanted to use it for my first step into cryptocurrencies.

**Comment by efazati** [comment]
I think update document and tell users this module dont exists until we fix problem is better than now

**Comment by psychocrypt** [comment]
Yes we have still issues with that we will definitively release the linux
binaries but at the current state they are not stable enough

**Comment by fireice-uk** [comment]
We are still working on making portable miner work flawlessly.
