### ISSUE TITLE
avast is flagging the windows binary for malware

### ISSUE THREAD

**Issue by telstarone** [fireice-uk/xmr-stak#475]
![image](https://user-images.githubusercontent.com/34438413/33823669-f8d9cbdc-de6c-11e7-8ceb-542be387dcae.png)

**Comment by JerichoJones** [comment]
You can thank Bot herders for that. They wrap miners in their packages so now mining software is getting flagged by AV.

Create an exception in your AV for XMR-STAK.EXE or the folder in which you drop it.

**Comment by telstarone** [comment]
Thanks JerichoJones.

**Comment by DavidBruchmann** [comment]
I propose to put that info in the README.md and close any items just with hint about that file.
Coming up always again and people never look in closed items.
