### ISSUE TITLE
Cuda runtime error

### ISSUE THREAD

**Issue by dgiero** [fireice-uk/xmr-stak#476]
# Basic information
  - GTX680 4GB
  - GTX480 1.5GB
  - I compiled the miner on ubuntu 16.04.3
  - `Version: xmr-stak/2.1.0/31a0784/master/lin/nvidia-cpu/aeon-monero/20`
  - I use `--noCPU` option

# Stability issue
  - No overclock nor undervolt, stock cards

# Issue with the execution
I had the above cards on two different pcs, they worked flawlessly. I had to put both of them on one of the two pcs.
If I run the miner with only one card, commenting in the nvidia.txt the card settings I don't want to use, the miner run perfectly. 

Here the nvidia.txt: 
```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 680 architecture: 30
  //      memory: 3987/4032 MiB
  //      smx: 8
  { "index" : 0,
    "threads" : 42, "blocks" : 24,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 470 architecture: 20
  //      memory: 1169/1218 MiB
  //      smx: 14
  { "index" : 1,
    "threads" : 18, "blocks" : 28,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],
```

 ### When I enable both the cards on the nvidia.txt I get this error:
```
------------------------------------------------------------------
xmr-stak 2.1.0 31a0784

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.

Configurable dev donation level is set to 2.0%
-------------------------------------------------------------------
[2017-12-11 10:49:48] : Start mining: MONERO
[2017-12-11 10:49:48] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2017-12-11 10:49:48] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-11 10:49:48] : Starting NVIDIA GPU thread 1, no affinity.
[2017-12-11 10:49:48] : Fast-connecting to 192.168.85.240:15000 pool ...
[2017-12-11 10:49:48] : Pool 192.168.85.240:15000 connected. Logging in...
[CUDA] Error gpu 0: </xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:221
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: all CUDA-capable devices are busy or unavailable
Aborted (core dumped)
```

If I run two different miner, one per card, they work perfectly, but this is not an ideal situation.

On the other pc I put a GTX470 and a GTX480, same OS, same miner build, they work flawlessy with a single miner.

**Comment by psychocrypt** [comment]
It is not possible to mix fermi gpus with non fermi. There are a few other
issues where we found out that this is not possible. This is a limitation
of the nvidia driver.
As you wrote the only workaround is to start two instances with a seperated
nvidia.txt.
Run --help to see how you can change the name for the nvidia config.
