### ISSUE TITLE
defrent hash rate between windows and ununtub

### ISSUE THREAD

**Issue by izacs** [fireice-uk/xmr-stak#477]
SO these is the problem defrent hash rate for the same cpu in same machine between windows and untub
windows 950 hash 
untub16 600 hash 

its 16 cores machine and in both it uses 16 threads by auto 

i use these before i run the miner 
sudo sysctl -w vm.nr_hugepages=128
ulimit -l

any idea guys ?

**Comment by JerichoJones** [comment]
The Untub drivers are not as good for this purpose as the Windows version.
