### ISSUE TITLE
Hi , I'm getting error with CPU mining "Illegal Instruction"

### ISSUE THREAD

**Issue by lumstery** [fireice-uk/xmr-stak#479]
Only CPU, alpine linux 
8x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz CPUs
[cpu_info.txt](https://github.com/fireice-uk/xmr-stak/files/1547665/cpu_info.txt)
[cmake.log](https://github.com/fireice-uk/xmr-stak/files/1547921/cmake.log)

**Comment by NmxMilk** [comment]
You should give more info about your platform, issue:
$ uname -va
and paste the result.
If you can run it under gdb and backtrace to where it hangs that will help a lot.
