### ISSUE TITLE
double hash calculation broken

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#48]
The low power mode (or double hash) calculation is broken since #19. If I enable it the miner will hang at the beginning. The commit 9c3a71ef090ea783a1124bd981dc1ce6e79b3309 is working.

CC-ing: @fireice-uk

**Comment by fireice-uk** [comment]
@psychocrypt Cannot reproduce it on dcd176ad  - can you confirm that it still exists?

**Comment by psychocrypt** [comment]
issue is solved with #44
