### ISSUE TITLE
How to avoid the manual start config in lunix 

### ISSUE THREAD

**Issue by izacs** [fireice-uk/xmr-stak#480]
hello so im planing to use boot script for my vps creat os is untub 
i know in alot of miners you need put like these 

./xmr-stak -o stratum+tcp://pool.supportxmr.com:80 -u user

can some one give me the full command to avoid any manual input 

menoro + pool + user + pass + how to answer the 3 qustion they ask regard use nhash and another pools

**Comment by DavidBruchmann** [comment]
mhm, wallet-address is probably needed as input or you want others to mine for your own wallet?
Apart from that I'd have a look how it's done in pool-frameworks like this (you can search several pools to get a list of frameworks):
http://cryptonotemining.org/
A very simple approach is to deliver batch files like in #470 
Another approach is to deliver the config-file too, you had to check what is there individual.

**Comment by izacs** [comment]
Dude i have no idea what u are talking about - i want to know how to make start order to avoid the first run manuall input - i want o know what the format will be for xmr stak is it like these for examle 

./xmr-stak a- algo -o pool adress u- user - p pass -- but have the no idea how to avoid the last 3 qustions

**Comment by DavidBruchmann** [comment]
same here, no clue how it should be related to start order

**Comment by JerichoJones** [comment]
xmr-stak --help
