### ISSUE TITLE
Building to SINGLE exe only 

### ISSUE THREAD

**Issue by promotion** [fireice-uk/xmr-stak#481]
This is more a question rather than an issue or a bug . However this is quite and important feature i think.

Is there a way of building it to one exe file :
1. including dll files into the exe
2. hardcoding main settings to code and autodect video settings on runtime without using txt files 

So that at the end i would have one single exe file , which , upon execution would not create any TXT files. ?

If author or anyone had this done already or could do this - please contact me (i'm really ready to pay for a proper solution :) ) 

You can email me on info at kodomafija.lt

**Comment by fireice-uk** [comment]
Sorry, we don't support features that would be primarily useful to bot herders. Having the miner flagged by AV is annoying as it it.
