### ISSUE TITLE
NVIDIA GeForce GTX 680MX

### ISSUE THREAD

**Issue by rickerd** [fireice-uk/xmr-stak#482]
Sadly my GPU isn't supported as well NVIDIA GeForce GTX 680MX.

[ 86%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_70'
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
  /Users/rick/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [all] Error 2

**Comment by psychocrypt** [comment]
It looks like you are using cuda8. cuda 8 is not supporting vega. please
clean your build directory. it looks like you tried to compile with cuda 9
before.
Or use the cmake flag CUDA_ARCH to set your architecture. or run `ccmake .`
and remove 70 from CUDA_ARCH

**Comment by rickerd** [comment]
Yes i removed 70 and it worked

**Comment by rickerd** [comment]
I have compiled with cuda 9 yes, what to do now?
Should i remove cuda 9 and install 8 of install cuda 7?

**Comment by JerichoJones** [comment]
Determine which CUDA version is required for the NVIDIA GeForce GTX 680MX and use that. If it is prior to CUDA 7.5 it is unsupported.

**Comment by sergneo** [comment]
Completely remove CUDA 9 . Install only CUDA 8, after compiling it will work.
