### ISSUE TITLE
More attractive output

### ISSUE THREAD

**Issue by crazydoc72** [fireice-uk/xmr-stak#484]
I like to use your unified miner. But I don´t like the colorless, unstructured output. So it should be easy to list the devices/cores in a clearer form. Now it´s like that:

```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   65.3 |   65.4 |   (na) |  1 |   66.4 |   67.7 |   (na) |
|  2 |   66.5 |   67.7 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  367.9 |  367.9 |   (na) | 1 |  262.9 |  263.1 |   (na) |
```

But it would be more attractive and better readable like that:

```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | 
|  0 |   65.3 |   65.4 |   (na) | 
|  1 |   66.4 |   67.7 |   (na) |
|  2 |   66.5 |   67.7 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  367.9 |  367.9 |   (na) |
|  1 |  262.9 |  263.1 |   (na) |
```
It would be even cooler if the different devices would have different colors, e.g. blue for CPU, green for NVIDIA and red for AMD.

Giving the same hashrates, xmrig(-nvidia/-amd/-cpu) has a prettier output, so some users are using it instead your great unified miner. Just think about the donations.... ;-)

**Comment by psychocrypt** [comment]
Thanks for your feedback. I know this is a nice feature but we are
currently focus our manpower to core features.
Currently there is not time for colored output. Another way to get colored
output is ro querry the json webdata and use a powerfull tool for coloring.
