### ISSUE TITLE
Laggy computer when GPU mining but not CPU mining

### ISSUE THREAD

**Issue by naymikm** [fireice-uk/xmr-stak#485]
Is this a tweaking issue? I would have guessed it would be the other way around. Ive tried adjusting the intensity and the hashrate goes down but not the lag. Here is my amd.config

"gpu_threads_conf" : [
  // gpu: AMD Radeon R9 M370X Compute Engine memory:384
  // compute units: 10
  { "index" : 1,
    "intensity" : 160, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

]

**Comment by AdamBunn** [comment]
I have the same issue with my AMD card. I assume it's because the GPU is having a hard time mining and re-drawing the display at the same time.

Anyone else fixed this issue?

**Comment by psychocrypt** [comment]
reduce the intensity than the gpu will have not such a hard live.

**Comment by AdamBunn** [comment]
I took the intensity down to 256 from ~960, it did't make any difference
```
  { "index" : 0,
    "intensity" : 256, "worksize" : 8,
    "affine_to_cpu" : true, "strided_index" : true
  },
'''

**Comment by JerichoJones** [comment]
It looks like you have dome all that can be done.
