### ISSUE TITLE
miner runs but but only finds new blocks and difficulty

### ISSUE THREAD

**Issue by syncacide** [fireice-uk/xmr-stak#486]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the intel 4400
  - Type of the GPU 3x MSI vega 64 1x MSI Vega 56 flashed to 64

# Compile issues
  - Which OS? Windows 10 
 
  add **all** commands you used and the **full** compile output here
 /*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool 
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */
"pool_list" :
[
	{"pool_address" : "pool.supportxmr.com:5555", "wallet_address" : "4BHg3KsmxZkWJTKpG53huM4eSutiuoZMXBigxEDwNeD7KuC6UiW6UJDQMYLMQXSWpgK3Ew3MQ4gW8UbskwubecNaDMDuySu", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * currency to mine
 * allowed values: 'monero' or 'aeon'
 */
"currency" : "monero",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make 
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for 
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 30,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0 - Don't print anything.
 *                 1 - Print intro, connection event, disconnect event
 *                 2 - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3 - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4 - All of level 3, and automatic hashrate report printing
 *
 * print_motd    - Display messages from your pool operator in the hashrate result.
 */
"verbose_level" : 4,
"print_motd" : true,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 60,

/*
 * Manual hardware AES override
 *
 * Some VMs don't report AES capability correctly. You can set this value to true to enforce hardware AES or
 * to false to force disable AES or null to let the miner decide if AES is used.
 *
 * WARNING: setting this to true on a CPU that doesn't support hardware AES will crash the miner.
 */
"aes_override" : null,

/*
 * LARGE PAGE SUPPORT
 * Large pages need a properly set up OS. It can be difficult if you are not used to systems administration,
 * but the performance results are worth the trouble - you will get around 20% boost. Slow memory mode is
 * meant as a backup, you won't get stellar results there. If you are running into trouble, especially
 * on Windows, please read the common issues in the README.
 *
 * By default we will try to allocate large pages. This means you need to "Run As Administrator" on Windows.
 * You need to edit your system's group policies to enable locking large pages. Here are the steps from MSDN
 *
 * 1. On the Start menu, click Run. In the Open box, type gpedit.msc.
 * 2. On the Local Group Policy Editor console, expand Computer Configuration, and then expand Windows Settings.
 * 3. Expand Security Settings, and then expand Local Policies.
 * 4. Select the User Rights Assignment folder.
 * 5. The policies will be displayed in the details pane.
 * 6. In the pane, double-click Lock pages in memory.
 * 7. In the Local Security Setting – Lock pages in memory dialog box, click Add User or Group.
 * 8. In the Select Users, Service Accounts, or Groups dialog box, add an account that you will run the miner on
 * 9. Reboot for change to take effect.
 *
 * Windows also tends to fragment memory a lot. If you are running on a system with 4-8GB of RAM you might need
 * to switch off all the auto-start applications and reboot to have a large enough chunk of contiguous memory.
 *
 * On Linux you will need to configure large page support "sudo sysctl -w vm.nr_hugepages=128" and increase your
 * ulimit -l. To do do this you need to add following lines to /etc/security/limits.conf - "* soft memlock 262144"
 * and "* hard memlock 262144". You can also do it Windows-style and simply run-as-root, but this is NOT
 * recommended for security reasons.
 *
 * Memory locking means that the kernel can't swap out the page to disk - something that is unlikely to happen on a
 * command line system that isn't starved of memory. I haven't observed any difference on a CLI Linux system between
 * locked and unlocked memory. If that is your setup see option "no_mlck".
 */

/*
 * use_slow_memory defines our behaviour with regards to large pages. There are three possible options here:
 * always  - Don't even try to use large pages. Always use slow memory.
 * warn    - We will try to use large pages, but fall back to slow memory if that fails.
 * no_mlck - This option is only relevant on Linux, where we can use large pages without locking memory.
 *           It will never use slow memory, but it won't attempt to mlock
 * never   - If we fail to allocate large pages we will print an error and exit.
 */
"use_slow_memory" : "never",

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel.
 *
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 */
"tls_secure_algo" : true,

/*
 * Daemon mode
 *
 * If you are running the process in the background and you don't need the keyboard reports, set this to true.
 * This should solve the hashrate problems on some emulated terminals.
 */
"daemon_mode" : false,

/*
 * Buffered output control.
 * When running the miner through a pipe, standard output is buffered. This means that the pipe won't read
 * each output line immediately. This can cause delays when running in background.
 * Set this option to true to flush stdout after each line, so it can be read immediately.
 */
"flush_stdout" : false,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * HTTP Authentication
 *
 * This allows you to set a password to keep people on the Internet from snooping on your hashrate.
 * Keep in mind that this is based on HTTP Digest, which is based on MD5. To a determined attacker
 * who is able to read your traffic it is as easy to break a bog door latch.
 *
 * http_login - Login. Empty login disables authentication.
 * http_pass  - Password.
 */ 
"http_login" : "",
"http_pass" : "",
 
/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,

  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  no
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
------------------------------------------------------------------
[2017-12-11 14:01:24] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-12-11 14:01:24] : WARNING: backend NVIDIA disabled.
[2017-12-11 14:01:24] : Compiling code and initializing GPUs. This will take a while...
[2017-12-11 14:01:24] : Device 0 work size 8 / 32.
[2017-12-11 14:01:29] : Device 1 work size 8 / 32.
[2017-12-11 14:01:34] : Device 2 work size 8 / 32.
[2017-12-11 14:01:40] : Device 3 work size 8 / 32.
[2017-12-11 14:01:45] : Starting AMD GPU thread 0, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 1, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 2, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 3, no affinity.
[2017-12-11 14:01:45] : Starting 1x thread, affinity: 0.
[2017-12-11 14:01:45] : hwloc: memory pinned
[2017-12-11 14:01:45] : Starting 1x thread, affinity: 1.
[2017-12-11 14:01:45] : hwloc: memory pinned
[2017-12-11 14:01:45] : Fast-connecting to pool.supportxmr.com:5555 pool ...
[2017-12-11 14:01:45] : Pool pool.supportxmr.com:5555 connected. Logging in...
[2017-12-11 14:01:45] : Difficulty changed. Now: 5000.
[2017-12-11 14:01:45] : Pool logged in.
[2017-12-11 14:01:49] : Result accepted by the pool.
[2017-12-11 14:01:49] : Result accepted by the pool.
[2017-12-11 14:01:50] : Result accepted by the pool.
[2017-12-11 14:01:50] : Result accepted by the pool.
[2017-12-11 14:01:50] : Result accepted by the pool.
[2017-12-11 14:01:51] : Result accepted by the pool.
[2017-12-11 14:01:53] : Result accepted by the pool.
[2017-12-11 14:01:56] : Result accepted by the pool.
[2017-12-11 14:01:57] : Result accepted by the pool.
[2017-12-11 14:01:57] : Result accepted by the pool.
[2017-12-11 14:01:57] : Result accepted by the pool.
[2017-12-11 14:02:00] : Result accepted by the pool.
[2017-12-11 14:02:02] : Result accepted by the pool.
[2017-12-11 14:02:02] : Result accepted by the pool.
[2017-12-11 14:02:04] : Result accepted by the pool.
[2017-12-11 14:02:06] : Result accepted by the pool.
[2017-12-11 14:02:09] : Result accepted by the pool.
[2017-12-11 14:02:13] : Result accepted by the pool.
[2017-12-11 14:02:14] : Result accepted by the pool.
[2017-12-11 14:02:14] : Result accepted by the pool.
[2017-12-11 14:02:15] : Result accepted by the pool.
[2017-12-11 14:02:17] : Result accepted by the pool.
[2017-12-11 14:02:22] : Result accepted by the pool.
[2017-12-11 14:02:22] : Result accepted by the pool.
[2017-12-11 14:02:24] : Result accepted by the pool.
[2017-12-11 14:02:26] : Result accepted by the pool.
[2017-12-11 14:02:26] : Result accepted by the pool.
[2017-12-11 14:02:29] : Result accepted by the pool.
[2017-12-11 14:02:32] : Result accepted by the pool.
[2017-12-11 14:02:33] : Result accepted by the pool.
[2017-12-11 14:02:33] : Result accepted by the pool.
[2017-12-11 14:02:33] : Result accepted by the pool.
[2017-12-11 14:02:36] : Result accepted by the pool.
[2017-12-11 14:02:36] : Result accepted by the pool.
[2017-12-11 14:02:37] : Result accepted by the pool.
[2017-12-11 14:02:39] : Result accepted by the pool.
[2017-12-11 14:02:40] : Result accepted by the pool.
[2017-12-11 14:02:41] : Result accepted by the pool.
[2017-12-11 14:02:43] : Result accepted by the pool.
[2017-12-11 14:02:43] : Result accepted by the pool.
[2017-12-11 14:02:45] : Difficulty changed. Now: 101670.
[2017-12-11 14:02:45] : New block detected.
[2017-12-11 14:02:46] : Result accepted by the pool.
[2017-12-11 14:02:46] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   25.5 |   25.4 |   (na) |  1 |   25.7 |   25.7 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1016.8 |  996.4 |   (na) |  1 |  779.4 |  819.0 |   (na) |
|  2 |  800.3 |  818.3 |   (na) |  3 |  880.7 |  877.8 |   (na) |
-----------------------------------------------------
Totals:   3528.5 3562.5   (na) H/s
Highest:  4054.2 H/s
[2017-12-11 14:03:33] : Result accepted by the pool.
[2017-12-11 14:03:45] : Difficulty changed. Now: 78570.
[2017-12-11 14:03:45] : New block detected.
[2017-12-11 14:03:47] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   28.3 |   26.3 |   (na) |  1 |   27.8 |   26.3 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1110.4 | 1059.0 |   (na) |  1 |  799.7 |  791.9 |   (na) |
|  2 |  785.4 |  789.8 |   (na) |  3 |  885.2 |  854.5 |   (na) |
-----------------------------------------------------
Totals:   3636.8 3547.8   (na) H/s
Highest:  4054.2 H/s
[2017-12-11 14:04:27] : New block detected.
[2017-12-11 14:04:45] : Difficulty changed. Now: 65400.
[2017-12-11 14:04:45] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   28.9 |   28.8 |   (na) |  1 |   27.9 |   28.0 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1075.1 | 1105.9 |   (na) |  1 |  767.0 |  772.1 |   (na) |
|  2 |  766.4 |  770.5 |   (na) |  3 |  853.3 |  868.2 |   (na) |
-----------------------------------------------------
Totals:   3518.7 3573.6   (na) H/s
Highest:  4054.2 H/s
[2017-12-11 14:05:10] : Result accepted by the pool.
[2017-12-11 14:05:34] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   26.1 |   28.4 |   (na) |  1 |   26.3 |   27.7 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 | 1018.6 | 1091.4 |   (na) |  1 |  723.3 |  781.8 |   (na) |
|  2 |  740.7 |  761.6 |   (na) |  3 |  843.7 |  870.7 |   (na) |
-----------------------------------------------------
Totals:   3378.6 3561.7   (na) H/s
Highest:  4054.2 H/s
[2017-12-11 14:05:56] : Result accepted by the pool.
[2017-12-11 14:06:06] : Result accepted by the pool.
[2017-12-11 14:06:08] : Result accepted by the pool.
[2017-12-11 14:06:14] : Result accepted by the pool.
[2017-12-11 14:06:29] : Result accepted by the pool.
[2017-12-11 14:06:33] : Result accepted by the pool.
[2017-12-11 14:06:45] : Difficulty changed. Now: 91320.
[2017-12-11 14:06:45] : New block detected.
# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted?
no

**Comment by syncacide** [comment]
So, everything looks to be configured right? and the miner is running?  The clock rates bounce between 852 and 1536Mhz. and wont stay steady. any idea why? would you be able to explain whats happening here? thanks again
[2017-12-11 14:01:45] : Starting AMD GPU thread 0, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 1, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 2, no affinity.
[2017-12-11 14:01:45] : Starting AMD GPU thread 3, no affinity.
[2017-12-11 14:01:45] : Starting 1x thread, affinity: 0.
[2017-12-11 14:01:45] : hwloc: memory pinned
[2017-12-11 14:01:45] : Starting 1x thread, affinity: 1.
[2017-12-11 14:01:45] : hwloc: memory pinned

**Comment by delone70** [comment]
I have 4 x Sapphire Vega 64 cards and this is my AMD.txt for reference. I'm assuming you have made the registry changes available elsewhere. The important setting in my AMD.txt for you is probably the "threads" setting.


/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 * { "index" : 3, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : false },
 * { "index" : 3, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : false },
 * { "index" : 0, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : false },
 * { "index" : 0, "intensity" : 1900, "worksize" : 8, "affine_to_cpu" : false },
 */

"gpu_thread_number" : 8,

"gpu_threads_conf" : [
    { "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 0, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 1, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 1, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 2, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 2, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 3, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
    { "index" : 3, "intensity" : 1800, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

**Comment by JerichoJones** [comment]
The clock rates bounce because it is not constantly calculating. The clock rate will drop when calculations are not being performed. Such as when a share is being submitted or requested.

This is normal.

**Comment by ubbe1** [comment]
Hi. thats i way to low hashrate for thoose GPUs.
You have to do som configthings to get better values.
Read this --> http://vega.miningguides.com/ Follow that.
set intensity 1935 1935 strided Index true.
Report here after that...

**Comment by fireice-uk** [comment]
Closing as OP's issue seems to be resolved.

**Comment by syncacide** [comment]
Well i went through the guides and got my hash rate up to about 50000 h/s. I did notice 2 things. went i would try and run cast xmr. It would tell me that the drivers I was using were not the amd blockchain compute drivers, even though thats what im using. I also notice in regedit that under the file for my cards the Device Description is no longer there. 
Thanks again

**Comment by fireice-uk** [comment]
This is highly indicative of driver problems, when working with a dedicated mining system like that (and unstable drivers), I would recommend using a disk imager to switch between complete OS installs.
