### ISSUE TITLE
VBS Problem whit the new 2.1 Update

### ISSUE THREAD

**Issue by gigi2006** [fireice-uk/xmr-stak#489]
hi,

I have a problem with the new version 2.1
I had a vbs file that started the whole thing in the background, so that no cmd window is always visible. I honestly mind working with you.

anyway, now with the 2.1 a second cmd window starts, this disappears but the second one does not.

does anyone have an idea what I need to change to make both of them invisible?

set wshShell = CreateObject("WScript.Shell")
wshShell.run "C:\xmr-stak-cpu\xmr-stak-cpu.exe",0,true

**Comment by neosho** [comment]
Hi, same problem, that second/double window for launch breaks my launch app :(

**Comment by JerichoJones** [comment]
xmr-stak --noUAC

**Comment by neosho** [comment]
thanks!

**Comment by sergneo** [comment]
Can be compiled immediately remove UAC , double window I don't like

**Comment by gigi2006** [comment]
@JerichoJones 

sorry i am a newby
can you help.

set wshShell = CreateObject("WScript.Shell")
wshShell.run "C:\xmrxmr-stak.exe",0,true

but where do I put this? --noUAC

**Comment by sergneo** [comment]
here 
wshShell.run "C:\xmrxmr-stak.exe --noUAC",0,true

**Comment by gigi2006** [comment]
@sergneo 
totally funny, had already tried that and it didn't work, so I asked.
but now I've copied and pasted it again and here we go.

thank you
