### ISSUE TITLE
CryptoNight-Lite support?

### ISSUE THREAD

**Issue by huserbg** [fireice-uk/xmr-stak#49]
Is there a plan to add CryptoNight-Lite support in this miner so it can be used for AEON mining?

Another useful feature for CryptoNight-Lite will be quad thread support (4 hashes per thread) in low power mode (but also keep double thread mode for maximum flexibility).

**Comment by Mattthev** [comment]
Would be great. I tried to make changes like AEON-STAK-AMD and CPU have, but it fails self test always.

**Comment by psychocrypt** [comment]
@huserbg  @Mattthev Support is added in #67, could you please test the new miner feature and post in the PR if everything works fine or if you detect issues.

**Comment by CircusDad** [comment]
I know this is "closed" so I don't know if this helps or not (or will even be seen).  I ran a 10-26-2017 compile of xmr-stak on windows 10 with nicehash at the pool for 24hrs.  I was happy with results: 1596 / 1639 (97.4 %) shares accepted.  Providing details if that helps...  

![image](https://user-images.githubusercontent.com/33241250/32411490-ccb82f26-c1b1-11e7-91af-17fb44c9a03c.png)

**Comment by psychocrypt** [comment]
Thx for reporting.

**Comment by huserbg** [comment]
@psychocrypt xmr-stak 2.0.0 works great with CryptoNight-Lite. Thanks a lot for adding this!

Any chance to also add a new **low power** mode which does **4 hashes per thread** and uses **4 MB** of cache?
This branch of **aeon-stak-cpu** supports this, but is otherwise very outdated:
https://github.com/shyba/aeon-stak-cpu/tree/4_per_thread
Also I never managed to compile the 4_per_thread branch for Windows.
