### ISSUE TITLE
GPU position/model hashrate inconsistency

### ISSUE THREAD

**Issue by Angel996** [fireice-uk/xmr-stak#493]
Hi.

Ubuntu 16.04, Nvidia.

I noticed, that GPU0 is always faster with xmr-stak. Sample output:

4 x GTX 980:

HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  607.9 |  606.3 |   (na) |  1 |  479.3 |  480.8 |   (na) |
|  2 |  513.4 |  499.3 |   (na) |  3 |  434.7 |  437.8 |   (na) |

4 x 1060 3GB:

HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  508.2 |  508.5 |  508.2 |  1 |  513.5 |  419.2 |  420.3 |
|  2 |  427.6 |  419.5 |  419.9 |  3 |  448.0 |  423.1 |  419.6 |

There is also another strange thing. I have an older GTX 780 GHz videocard. Tried it out alone in a separate rig. And it produces 650 h/s! How is that possible? Why is it faster than GTX 980?!

**Comment by fireice-uk** [comment]
It is a hardware issue (motherboard or northbridge).
