### ISSUE TITLE
Crash Help 341 3413 

### ISSUE THREAD

**Issue by tff1elyk** [fireice-uk/xmr-stak#495]
Basically I run the miner could take 3 hours or 18 hours but eventually it will crash and give be either a long error like there prior or a shorter one like the latter. I've tried not overclocking and adjusting threads and blocks setting virtual memory and whatever that gpedit.msc thing is in the config. I'm not all to educated when it comes to all this so I didn't add some of the info requested cause I had no idea what it meant. 

[CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu [CUDA] Error gpu [CUDA] Error
 gpu 4: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_cor
e.cu>:3413: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda
_core.cu1: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_
core.cu
0: <C:/Users/

[CUDA] Error gpu [CUDA] Error gpu 2: <C:/Users/MAIN/github/xmr-stak/xmrstak/back
end/nvidia/nvcc_code/cuda_core.cu>:341

# Basic information
  - i7 7700k
  - 2x gtx 1070 gtx 980 gtx 970 gtx 1050ti

# Compile issues
  - windows 8.1 pro

# Issue with the execution
  - I did not compile myself used precompiled

# Stability issue
  - GPUs overclocked
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by JerichoJones** [comment]
Probably overheating. Unfortunately you don't provide your settings so it's hard to tell.

Please post your nvidia.txt
Maybe that will shed some light.

**Comment by tff1elyk** [comment]
My cards don't ever get hot. The hottest knee get is 57c and the hottest my cpu gets is 54c.

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 7947/8192 MiB
  //      smx: 15
  { "index" : 0,
    "threads" : 72, "blocks" : 45,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : 1,
  },
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3911/4096 MiB
  //      smx: 13
  { "index" : 1,
    "threads" : 20, "blocks" : 39,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : 1,
  },
  // gpu: GeForce GTX 1070 architecture: 61
  //      memory: 7947/8192 MiB
  //      smx: 15
  { "index" : 2,
    "threads" : 74, "blocks" : 45,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : 1,
  },
  // gpu: GeForce GTX 980 architecture: 52
  //      memory: 3901/4096 MiB
  //      smx: 16
  { "index" : 3,
    "threads" : 14, "blocks" : 48,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : 1,
  },
  // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3914/4096 MiB
  //      smx: 6
  { "index" : 4,
    "threads" : 80, "blocks" : 18,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : 1,
  },

],

**Comment by psychocrypt** [comment]
try to reduce the threads for all gpus maybe by 4

**Comment by tff1elyk** [comment]
Just crashed again

[CUDA] Error gpu 3: <C:/Users/MAIN/github/xmr-stak/xmrstak/backend/nvidia/nvccvcc_code/cuda_core.cu>:341

**Comment by JerichoJones** [comment]
@tff1elyk Reduce it until it stops crashing

**Comment by tff1elyk** [comment]
That seems to have fixed it although I'm having another issue as well. I'm running two gtx 1070s that are exactly the same and they get very different h/s. One sits at 700 all day the other fluctuates from 350 to 450. Any ideas on that?

**Comment by psychocrypt** [comment]
this is coming from the nvidia driver. I still searching how I can avoid it.

Am 22.12.2017 5:36 Vorm. schrieb "tff1elyk" <notifications@github.com>:

**Comment by tff1elyk** [comment]
Thank you
