### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by bossmos** [fireice-uk/xmr-stak#496]
What is hacktool:win64/coinminer? Is this part of xmr stack? My computer believes it is a virus. It specifically targeted the xmr-stak files. pls let me know, thanks.

**Comment by DavidBruchmann** [comment]
That's a wellknown problem because xmr-stak is implemented in some virus'.
You've to set it on the white-list, it won't harm your system if it's here from the original repository.

**Comment by JerichoJones** [comment]
@DavidBruchmann is correct.

You can thank Bot herders for that. They wrap miners in their packages so now mining software is getting flagged by AV.

Create an exception in your AV for XMR-STAK.EXE or the folder in which you drop it.
