### ISSUE TITLE
how to desable GPU to mine only with CPU

### ISSUE THREAD

**Issue by giozera** [fireice-uk/xmr-stak#497]
up until now I was mining separately with CPU and GPU by xmr-stak (first combined version) and xmr-stak-nvidia (latest) and I was getting way more h/s than this last 2.1.0 together combined. like 200h/s less. 
for some reason first combined version was not able to detect my GPUs (gtx 780m) on my alienware x18r 2
and I was forced to mine separately by xmr-stak-nvidia. so xmr-stak (first combined version) was mining just by 4 cores and was getting in average 100h/s or more per core (400h/s average in total). now with latest version of 2.1.0 it started to detect my cpu and gpu's and mines together but with average of 45h/s per cpu core. what happened? why is my cpu loosing hashes here? GPU doesn't suffers with hashes on latest 2.1.0 just cpu.
my hardware: alienware m18x r2 CPU-i7-3940xm, GPU 2xGTX 780M. OS-windows 7.
thanks

**Comment by DavidBruchmann** [comment]
See #470

**Comment by JerichoJones** [comment]
xmr-stak --help

**Comment by giozera** [comment]
thanks!
