### ISSUE TITLE
xmr-stak undefined symbol: clGetPlatformIDs

### ISSUE THREAD

**Issue by airbladesi** [fireice-uk/xmr-stak#498]
Hello, I have that problem:
**./xmr-stak: symbol lookup error: ./libxmrstak_opencl_backend.so: undefined symbol: clGetPlatformIDs**

here is the whole output:
root@-System-Product-Name:~/xmr-stak/build/bin# ./xmr-stak
[2017-12-12 01:59:26] : MEMORY ALLOC FAILED: mmap failed
[2017-12-12 01:59:26] : MEMORY ALLOC FAILED: mmap failed
[2017-12-12 01:59:26] : MEMORY ALLOC FAILED: mmap failed
[2017-12-12 01:59:26] : MEMORY ALLOC FAILED: mmap failed
[2017-12-12 01:59:26] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.1.0 31a0784

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-12 01:59:27] : Start mining: MONERO
./xmr-stak: symbol lookup error: ./libxmrstak_opencl_backend.so: undefined symbol: clGetPlatformIDs

How to fix that?
Thanx,
Andrej

**Comment by JerichoJones** [comment]
Did you try changing the platform id in amd.txt?

**Comment by szogun1987** [comment]
Similar error occurred to me if I used 17.50 version of AMDGPU-PRO. I think I installed it wrong so I switched back to 17.40.
Please paste clinfo output in here.
