### ISSUE TITLE
OpenCL name of a VEGA GPU

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#5]
The auto suggestion for the AMD backend will add the name of the GPU as comment into the config.
What is the name of the VEGA gpu provided by OpenCL?

**Could someone from the communityplease  provide us with the config created by the auto suggestion!**

This information is needed to improve the auto suggestion for VEGA gpus.

**Comment by anhphan** [comment]
I use self build on windows with only one custom offtion `-DCUDA_ARCH=50;61` because cuda 9 drop computed 2.0

Just tested on server with RX Vega 56 (blockchain driver) and GTX 1050Ti (only install cuda 8 runtime - no cuda 9)

xmr-stak auto disable AMD backend so cannot give you the name it generated.

Don't know how to force it enable.
```
-------------------------------------------------------------------
WARNING: NVIDIA Insufficient driver!
[2017-10-05 00:05:57] : WARNING: backend NVIDIA disabled.
[2017-10-05 00:05:57] : Found AMD platform index id = 1, name = Advanced Micro Devices, Inc.
[2017-10-05 00:05:57] : WARNING: backend AMD disabled.
[2017-10-05 00:05:57] : CPU configuration stored in file 'cpu.txt'
```

**Comment by psychocrypt** [comment]
The opencl library from the installed cuda is selected instead your amd
opencl lib.
Set the path to the amd libopencl.so

`LD_LIBRARY_PATH=PATHTOOPENCL:$LD_LIBRARY_PATH ./xmr-stak`

you can find the path to amd opencl with `find /usr | grep -i libopencl`

Am 04.10.2017 7:13 Nachm. schrieb "Anh Phan Tuan" <notifications@github.com

**Comment by anhphan** [comment]
It's windows server 2016, not linux, and platform index 1 is correct index for AMD (NVIDIA is 0)

**Comment by psychocrypt** [comment]
ignore what I am wrote before. It could be a bug that the autosuggestion stops of a non amd gpu is found. I need to check it today.

Please compile with the cmake option `-DCUDA_ENABLE=OFF` mabe this helps to activate the amd gpu.

**Comment by anhphan** [comment]
AMD can be active if i manual created amd.txt file with thread and platform info copy from old amd version, it's just autosuggestion not work, (and large page not work too)

**Comment by psychocrypt** [comment]
Could you please open an issue for the large page support and descriibe if
you mean the option within config.txt or how you see that is not working.

Am 04.10.2017 7:45 Nachm. schrieb "Anh Phan Tuan" <notifications@github.com

**Comment by psychocrypt** [comment]
@anhphan Your AMD detection bug should be fixed with #13

**Comment by anhphan** [comment]
It's work.
Here is autosuggestion for my RX Vega (2xVega56 + 1xVega64) and the name is `gfx901`, as I remember I already see this name somewhere, maybe claymore

```
/* 
 * Number of GPUs that you have in your system. Each GPU will get its own CPU thread.
 */
"gpu_thread_num" : 3,

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: gfx901
  { "index" : 0,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, 
  },
  // gpu: gfx901
  { "index" : 1,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, 
  },
  // gpu: gfx901
  { "index" : 2,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

```

**Comment by psychocrypt** [comment]
thx for testing: What is the best intensity and worksize for both gpu types?

**Comment by anhphan** [comment]
Internet say that will be run two theards per gpu, one with 2016, and one with 1600, but for me, on blockchain driver best is run both two thread with intensity 1920 (gpu memory consume will be ~7721). 

It's not difference between RX Vega 56 and 64. When have enough high intensity, best hashrate not effect much from change it's value, most problem is how to keep gpu running cool without throttling, hashrate will drop if it become hot.

```
"platform_index" : 1,

"gpu_thread_num": 6,
"gpu_threads_conf" : [
	{ "index" : 0, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
	{ "index" : 0, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
	{ "index" : 1, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
	{ "index" : 1, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
	{ "index" : 2, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
	{ "index" : 2, "intensity" : 1920, "worksize" : 8, "affine_to_cpu" : false},
],
```

**Comment by anhphan** [comment]
Ah, forgot to mention, it's seem intensity will belong driver very much, haven't test RX Vega on normal driver, but tested Vega FE (16GB) on normal driver and blockchain driver.

On blockchain driver i can even put 4 threads per gpu with intensity 1920, It's can run without error (only just cannot computed because stak cannot communication with mining threads).

But on normal driver, with 2 thread 1920, it's will throw some error about cl buffer (cannot remember exactly name), and I can only rut it with 2 thread 1024 (higher value will make stak cannot communicate with mining threads too).

**Comment by psychocrypt** [comment]
Thanks for the information I need to think about your points and why 2 or 4
threads fits best. What is if you run e.g. with on thread but intensity
3800?

Am 04.10.2017 10:06 Nachm. schrieb "Anh Phan Tuan" <notifications@github.com

**Comment by psychocrypt** [comment]
The limitation looks like a RAM limitation. To avoid that some environment
variables must be set to allow OpenCL to use the full memory with one
process.
I will add the variables tomorrow or so to this thread.

Am 04.10.2017 10:57 Nachm. schrieb "Anh Phan Tuan" <notifications@github.com

**Comment by psychocrypt** [comment]
@anhphan Could you please test if you can use one thread instead of two per gpu if you set a few environment variables before the miner starts.

```
export GPU_FORCE_64BIT_PTR 0
export GPU_MAX_HEAP_SIZE 98 
export GPU_MAX_ALLOC_PERCENT 100 
export GPU_SINGLE_ALLOC_PERCENT 100 
```
Than it should be possible to use one thread with intensity 3840. Ehat is the hash rate compared to two threads per fpu.

**Comment by anhphan** [comment]
Have a testing today on windows server 2016 + blockchain driver.
Startup script:
```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 98 
setx GPU_MAX_ALLOC_PERCENT 100 
setx GPU_SINGLE_ALLOC_PERCENT 100 
xmr-stak.exe -c config2.txt --noCPU --noNVIDIA --amd amd2.txt
```

With one thread `intensity=2024` the hashrate is about 1500 on vega 56. With `intensity=2032` or greater i receiver this error:
`Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.`

> other info: claymore cryptonight have a parameter -h having limit value 2023, every setting value > 2023 will be automatic set to that value.

**Comment by psychocrypt** [comment]
I added a VEGA patch to create better auto suggestion for VEGA GPUS in #74

**Comment by basselkhaddour** [comment]
backend AMD (OpenCL) disabled. plz help
