### ISSUE TITLE
Suggestion - Run or stop the miner depending on the weather outside.

### ISSUE THREAD

**Issue by zombiqc** [fireice-uk/xmr-stak#501]
Hi,

This is just a suggestion. Would it be possible to implement a function that checks the weather and stop or start the miner based on certain thresholds ?

I have a bi-energy system to warm my house. When it's warmer thant -14c I pay 0.04$ per kw/h. But then it gets colder than -14c, I pay 0.26 per kw/h. The system switch to kerosene instead of electricity during the cold nights so I'd like to turn off the mine aswell. 

Thanks for all the great work, your application works great and I love it.

Have a good day.

**Comment by DavidBruchmann** [comment]
In general I support a pause switch without closing the app (maybe it even exists and I never discovered it yet),
Concerning your temperature problem I think it's too special for integrating but you could create a wrapper-program that is doing the desired logic.

**Comment by zombiqc** [comment]
Thanks for the quick response. I'm not a programmer myself but I'll see
what I can do with off the shelf stuff (IFTTT and whatnot) to at least get
emails when I could stop and start manualy my miner.

If ever make a pause founction that'd be great !



2017-12-11 23:17 GMT-05:00 David Bruchmann <notifications@github.com>:

**Comment by DavidBruchmann** [comment]
you never read all, because I added some text to my post ;-)
That's not delivered by mail I suppose.

**Comment by zombiqc** [comment]
Yeah sorry the email didnt show the whole text. Actualy my heating system takes the reading outside my home and change from electric to fuel from that reading. Your right though that the energy compagny is probably making a generalisation of the weather in my area. Anyway, I'll try the IFTTT route with and go from there. Thanks for your time :)
