### ISSUE TITLE
AMD OpenCL

### ISSUE THREAD

**Issue by shih1** [fireice-uk/xmr-stak#503]
Please provide as much as possible information to reproduce the issue.

# Basic information
Windows10 
GTX 960M

# Compile issues
compile passed with warnings and 0 errors

# AMD OpenCl issue
```
Configurable dev donation level is set to 3.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-11 21:31:44] : Start mining: MONERO
[2017-12-11 21:31:45] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-11 21:31:46] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
```
What does this warning mean and how important is the AMD OpenCL platform? 
Using CUDA 8.0

**Comment by scarf** [comment]
The AMD OpenCL platform is for ATI/AMD GPU's, not needed if you only have NVIDIA

**Comment by JerichoJones** [comment]
The --noAMD will get rid of the message. It just indicates , in this instance, that no AMD GPU was found.

XMR-STAK --noAMD
