### ISSUE TITLE
Why download CUDA if there is only a CPU on the PC?

### ISSUE THREAD

**Issue by TheCHIM** [fireice-uk/xmr-stak#505]
CPU Xeon E5630
OS CentOS 6.9
Kernel Linux 2.6.32-696.16.1.el6.centos.plus.x86_64 on x86_64

```
Saving to: “cuda_9.0.176_384.81_linux-run”

100%[====================================>] 1,643,293,725 1.36M/s in 20m 4s

2017-12-12 10:36:39 (1.30 MB/s) - “cuda_9.0.176_384.81_linux-run” saved [1643293725/1643293725]

chmod a+x cuda_9.0.176_384.81_linux-run
docker run --rm -it -v /Bitcoin/12.12.2017/xmr/scripts/build_xmr-stak_docker:/mnt fedora:27 /bin/bash -c '
set -x ;
dnf install -y -q cmake gcc-c++ hwloc-devel libmicrohttpd-devel libstdc++-static make openssl-devel;
cd /mnt/xmr-stak ;
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF . ;
make ;
'
./build_xmr-stak_docker.sh: line 22: docker: command not found

```
Why download CUDA if there is only a CPU on the PC?

**Comment by TheCHIM** [comment]
Saving to: “cuda_9.0.176_384.81_linux-run”

100%[====================================>] 1,643,293,725 1.36M/s   in 20m 4s

2017-12-12 10:36:39 (1.30 MB/s) - “cuda_9.0.176_384.81_linux-run” saved [1643293725/1643293725]

+ chmod a+x cuda_9.0.176_384.81_linux-run
+ docker run --rm -it -v /Bitcoin/12.12.2017/xmr/scripts/build_xmr-stak_docker:/mnt fedora:27 /bin/bash -c '
set -x ;
dnf install -y -q cmake gcc-c++ hwloc-devel libmicrohttpd-devel libstdc++-static make openssl-devel;
cd /mnt/xmr-stak ;
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF . ;
make ;
'
./build_xmr-stak_docker.sh: line 22: docker: command not found

**Comment by nueverest** [comment]
It strikes me as strange as well.  The code already knows that no CUDA or OpenCL libraries are present.  It should just observe this configure the installation as CPU only.  No need for these ENABLE flags.

**Comment by TheCHIM** [comment]
In fact of the matter. For some reason he himself defined it:
1. That he suddenly needs CUDA
2. What is Fedora (actually CentOS)
So the installer is not finalized.
