### ISSUE TITLE
Mac AMD detection issue

### ISSUE THREAD

**Issue by sputn1k** [fireice-uk/xmr-stak#506]
When running **xmr-stak** on MacOS it does not detect my AMD GPU? 

I tried adding the `amd.txt` file manually from a previous `xmr-stak-amd` config but does nothing. 

Is there specific compile instructions for AMD GPU's there wasn't anything on the guide?

**Comment by drewwiley** [comment]
Use the dev branch: https://codeload.github.com/fireice-uk/xmr-stak/zip/dev

**Comment by drewwiley** [comment]
(for some reason I was having the same issues with xmr-stak finding my AMD card on my mac as well and the dev branch fixed it)

**Comment by drewwiley** [comment]
If that works and you are able to get it up and running, I would very much appreciate it if you would report back with how your performance is and what config setup you use. Are you using an iMac or a MacBook?

**Comment by psychocrypt** [comment]
If the gpu is not found please post all output and the version number. The
full list of information needed is shown id you open the issue.

**Comment by sputn1k** [comment]
@drewwiley Thanks, but I have actually already tried that already, I compiled from the dev branch and no difference couldn't detect the GPU. 

@psychocrypt Should I post here my GPU hardware or pass a parameter into the xmr-stak? 

I did try compiling with -dOpenCL_ENABLE=ON 

Mac Pro (2013) + AMD Crossfire GPU's

Mac System Report: 
```
AMD FirePro D300:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Total):	2 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  VBIOS Version:	113-C4012PA-012
  EFI Driver Version:	01.0D.687
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.11 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

AMD FirePro D300:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-2
  PCIe Lane Width:	x16
  VRAM (Total):	2 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  VBIOS Version:	113-C4012PB-012
  EFI Driver Version:	01.0D.687
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.11 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3
```

**Comment by psychocrypt** [comment]
Please post the output of the miner during the firs start. Remove amd.txt if a file is already created.

**Comment by sputn1k** [comment]
@psychocrypt Ok thanks will do - I added the `amd.txt` never got generated.

**Comment by sputn1k** [comment]
Recompiled the dev branch and it all works cheers guys...👍 @drewwiley @psychocrypt 

Flying now... 🔥🔥🔥🔥 
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   84.0 |   83.4 |   (na) |  1 |   81.9 |   80.5 |   (na) |
|  2 |   74.8 |   73.5 |   (na) |  3 |   75.8 |   74.7 |   (na) |
|  4 |   72.7 |   72.0 |   (na) |  5 |   75.8 |   74.9 |   (na) |
|  6 |   73.7 |   72.5 |   (na) |  7 |   75.4 |   74.3 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  819.9 |  807.6 |   (na) |  1 |  845.7 |  844.6 |   (na) |
-----------------------------------------------------
Totals:   2279.6 2258.1   (na) H/s
Highest:  2339.5 H/s
```

**Comment by drewwiley** [comment]
@sputn1k What kind of mac are you using!? Specs? 

My iMac barely gets 300 H/s from the AMD card and about 150 H/s from the CPU :-/ .

 Could you share your config files by chance? Thanks so much!

**Comment by sputn1k** [comment]
@drewwiley Mac Pro 2013 (desktop) + AMD Crossfire GPU's (specs above), basically 2 GPUs with 2GB of memory each. my CPU is only getting 850 max.

**Comment by drewwiley** [comment]
ahhhh I didn't notice those two AMDs, makes sense now. Yeah I can only handle about 640, maybe 768 max as far as intensity goes.
