### ISSUE TITLE
Config is read from current directory instead of binary location

### ISSUE THREAD

**Issue by bin4ryio** [fireice-uk/xmr-stak#508]
Like title, I'm running Linux compiled from source. Even if argument supplied, it is creating config file in current directory instead of using the existing config.

**Comment by psychocrypt** [comment]
By default the miner will generate the configs in the working directory (current directory). If you explicitly add the path and name of an file than the config will be created there.

```
~/xmr-stak/xmr-stak -c /tmp/config.txt --amd /tmp/amd.txt --nvidia /tmp/nvidia.txt
```

**Comment by bin4ryio** [comment]
It seems to prompt SSL Y/N and NiceHash Y/N regardless the key value is in `config.txt`.
