### ISSUE TITLE
potential race condition

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#51]
One of my test produced a race  condition. The nvidia config was written to `cpu.txt` instead to `nvidia.txt`
I used #55 rebased to the dev 6701b0c2025987674708c9984c1d76461428c09e.

I can't reproduce it (but this is the nature of a race condition), it could be that #44 is introducing this race condition.

I will investigate some time to this soon.

```
[2017-10-17 21:46:14] : NVIDIA: GPU configuration stored in file 'cpu.txt'
[2017-10-17 21:46:14] : Starting GPU thread, no affinity.
[2017-10-17 21:46:14] : Starting GPU thread, no affinity.
...
[2017-10-17 21:46:14] : MEMORY ALLOC FAILED: mmap failed
[2017-10-17 21:46:15] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-10-17 21:46:15] : WARNING: backend AMD disabled.
[2017-10-17 21:46:15] : Invalid config file. Missing value "cpu_threads_conf".
[CUDA] Error gpu [CUDA] Error gpu 2: </xmr-stak-nvidia/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:1920: </xmr-stak-nvidia/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:192[CUDA] Error gpu 4: <xmr-stak-nvidia/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:192

```

cc-ing: @fireice-uk

**Comment by fireice-uk** [comment]
I will have a look, it is possible that duplicated singletons were hiding bugs.

**Comment by fireice-uk** [comment]
@psychocrypt unless you can find a way to replicate this, this is not a race condition since you used two different variables. In whichever order the code gets executed configFileNVIDIA is not going to be set to `cpu.txt`

**Comment by psychocrypt** [comment]
It can also be a wrong read within the stak or heap. I also can not see how this can be happened.

**Comment by psychocrypt** [comment]
Maybe https://github.com/fireice-uk/xmr-stak/pull/44/files#r145259888 is the reason

**Comment by fireice-uk** [comment]
Made you a test harness to put this one to bed, feel free to play around -> https://github.com/fireice-uk/env-test-harness

**Comment by psychocrypt** [comment]
@fireice-uk I tested you test case and the class is not handled ass POD. Never the less we should use `new CLASS()` to avoid side effects.

**Comment by psychocrypt** [comment]
I can't reproduce the issue, therefore I will close this issue.
