### ISSUE TITLE
Ubuntu Mate 16.04 64 Bit - compiled Version don't work on another pc

### ISSUE THREAD

**Issue by JokerGermany** [fireice-uk/xmr-stak#511]
Please provide as much as possible information to reproduce the issue.

# Basic information
Intel(R) Core(TM)2 Duo CPU     P7350
HD Radeon 4670M

# Issue with the execution
  - Do you compiled the miner by our own?
  Yeah
  run `./xmr-stak --version-long` and add the output here
  Version: xmr-stak/2.0.0/79154f7/master/lin/amd-cpu/aeon-monero/0

# AMD OpenCl issue
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Abgebrochen (Speicherabzug geschrieben)

I get the following error:
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)

Looks like OpenCL is the error, but why?

Can I try xmr-stak without opencl without recompiling it?

**Comment by dgiero** [comment]
use `xmr-stak --noAMD `

**Comment by JokerGermany** [comment]
ok, same error...

**Comment by psychocrypt** [comment]
Pleas read https://github.com/fireice-uk/xmr-stak/blob/31a078416042d5492540f4bdb1466a84b690430e/doc/compile.md#generic-build-options

You need `-DCMAKE_LINK_STATIC=ON` and `-DXMR-STAK_COMPILE=generic`. But this will mostly only work if the OS is equal between the systems.

**Comment by JokerGermany** [comment]
Thanks, then i will compile it on every computer, when i get then a better hashrate.

This only effects Linux?

**Comment by psychocrypt** [comment]
You get the best cpu performance if you compile it directly on the system.
This is not needed on windows because binaries are compatible never the
less all systems must have all dependencies installed or shipped with the
binary.
This is also possible for linux but cross compile for another distribution
is not easy.
