### ISSUE TITLE
Aeon-pool being default pool with Aeon mining is causing network problems. User should have to pick pools by themselves to even the hashes out between pools. 

### ISSUE THREAD

**Issue by CheapHoarder** [fireice-uk/xmr-stak#512]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by psychocrypt** [comment]
There is no default pool but an example. Is there a pool list available
with all aeon pools?

**Comment by fireice-uk** [comment]
That's a hard no on forcing users to pick (no default). Our primary responsibility is to the user, not the coin at large. We will look into having a smaller pool as a default.

**Comment by CheapHoarder** [comment]
There's http://aeonpools.net/

Thank's for looking in to using a smaller pool by default. Maybe even changing it up between releases?
