### ISSUE TITLE
amd.txt with one r9 nano and one vega rx cards

### ISSUE THREAD

**Issue by fsck0ff** [fireice-uk/xmr-stak#513]
When using two different generations of AMD GPUs, the automatic configuration generates amd.txt with only one of the cards (in my case the legacy r9 nano).  

# Basic information

  - Type of the GPU (if you try to miner with the GPU).
1x AMD R9 nano
1x AMD Vega RX 56

# Compile issues
  - Which OS do you use?
No issues - Ubuntu 16.04.3

# Issue with the execution
./xmr-stak --version-long
Version: xmr-stak/2.1.0/30888a3/unknown/lin/amd-cpu/aeon-monero/0

I can use this amd.txt for the r9 nano:

"gpu_threads_conf" : [
  { "index" : 0,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false, 
    "strided_index" : true
  },
  { "index" : 0,
    "intensity" : 1000, "worksize" : 8,
    "affine_to_cpu" : false,
    "strided_index" : true
  },
],
"platform_index" : 0,

or I can use this amd.txt for the rx vega:

"gpu_threads_conf" : [
  { "index" : 0,
    "intensity" : 1762, "worksize" : 8,
    "affine_to_cpu" : false, 
    "strided_index" : true
  },
  { "index" : 0,
    "intensity" : 1762, "worksize" : 8,
    "affine_to_cpu" : false,
    "strided_index" : true
  },
],
"platform_index" : 1,

but if I put both in the same amd.txt only the r9 nano (platform_index 0) is working. Is it even possible to have configuration for both cards/platform_indices in the same file? I tried adding multiple --amd options with the different config files but that doesn't seem to work (only the last one is taken into account). Currently I am working around this by using the old xmr-stak-amd with the r9 nano and xmr-stak with cpu/rx vega which works fine, but I'd love to have everything in one place if possible.

Thanks for the great work!

**Comment by psychocrypt** [comment]
please remove your amd.txt than start the mi er and post all terminal
output and the generated amd.txt. Also please run clinfo and post the output

**Comment by fsck0ff** [comment]
Hello,

here is the output of clinfo:
[clinfo.txt](https://github.com/fireice-uk/xmr-stak/files/1552933/clinfo.txt)
The miner output:
[miner.txt](https://github.com/fireice-uk/xmr-stak/files/1552934/miner.txt)
and the generated amd.txt:
[amd.txt](https://github.com/fireice-uk/xmr-stak/files/1552935/amd.txt)

The overlay stuff in the miner output is because everything is running in a docker container, but it doesn't seem to cause any issues. Please let me know if you need something else... Thanks!

**Comment by psychocrypt** [comment]
You can start two instances of xmr-stak one with gpu 0 and one with gpu 1. You need to write to amd.txt and start the miner two times.

```
./xmr-stak --amd amd.txt
./xmr-stak --amd vega.txt
```

btw: I see that you are running the miner from a docker file. As I know docker is not fully supporting native amds. Please retry to use the miner on an native system, maybe this solves your issue.

**Comment by fsck0ff** [comment]
Two instances with different configs work fine (in the same docker container or in two separate ones), this is what I am currently doing. I thought that there might be a way to specify two platform_index sections in the same config file, but it seems that's not currently possible. I guess this is pretty rare use case and probably not worth spending time so I am going to close this issue...

As for docker and AMDs I haven't had any issues with it once amdgpu-pro is properly installed in both the docker host and the container and you pass --device /dev/dri:/dev/dri --privileged to the container...
