### ISSUE TITLE
Getting a maximum of 104-107 hashrate on Titan X's.

### ISSUE THREAD

**Issue by DuquetteRoxx** [fireice-uk/xmr-stak#515]
Specs:
i7 5930K
128GB DDR4 @ 4200MHZ
(2) GTX Titan X (SLI off)
Windows 10
No overclocks on CPU, or GPU.
Standard XMP overclock on the RAM.

Have tried every combination of threads and blocks, all of which produce 104 to 107 rate.

Have tried many values of bfactor. (nothing lower than 7 works, and 12 makes my system usable)
All bsleep values between 5-100 seem to work.

![nvidia txt](https://user-images.githubusercontent.com/34487958/33902304-94737d92-df42-11e7-95bf-a6e5d0dd8b31.png)
![wtf](https://user-images.githubusercontent.com/34487958/33902309-9aa9b884-df42-11e7-8020-deb9fab594a0.png)

**Comment by DuquetteRoxx** [comment]
I have also tried setting affinity to CPU and all sync modes.

**Comment by psychocrypt** [comment]
please delete the file nvidia.txt start the miner and post the file. Please
copy&past the text instead of posting screenshots

**Comment by DuquetteRoxx** [comment]
If I delete the file and start the miner, it disables back-end nvidia.

There is nothing in nvidia.txt now, just the template.


/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 */

"gpu_threads_conf" :
[

],

**Comment by DuquetteRoxx** [comment]
It also looks like they will only hash for a second or two, and then stop.

**Comment by psychocrypt** [comment]
In that case please remove the file `nvidia.txt` gain start the miner and post all output from the terminal.

**Comment by DuquetteRoxx** [comment]
-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-12 15:49:26] : Start mining: MONERO
[2017-12-12 15:49:27] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2017-12-12 15:49:27] : WARNING: backend NVIDIA disabled.
[2017-12-12 15:49:27] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-12 15:49:27] : WARNING: backend AMD disabled.
[2017-12-12 15:49:27] : Starting 1x thread, affinity: 0.
[2017-12-12 15:49:27] : hwloc: memory pinned
[2017-12-12 15:49:27] : Starting 1x thread, affinity: 2.
[2017-12-12 15:49:27] : hwloc: memory pinned
[2017-12-12 15:49:27] : Starting 1x thread, affinity: 4.
[2017-12-12 15:49:27] : hwloc: memory pinned
[2017-12-12 15:49:27] : Starting 1x thread, affinity: 6.
[2017-12-12 15:49:27] : hwloc: memory pinned
[2017-12-12 15:49:27] : Starting 1x thread, affinity: 8.
[2017-12-12 15:49:28] : hwloc: memory pinned
[2017-12-12 15:49:28] : Starting 1x thread, affinity: 10.
[2017-12-12 15:49:28] : hwloc: memory pinned
[2017-12-12 15:49:28] : Starting 1x thread, affinity: 1.
[2017-12-12 15:49:28] : hwloc: memory pinned
[2017-12-12 15:49:28] : Starting 1x thread, affinity: 3.
[2017-12-12 15:49:28] : hwloc: memory pinned
[2017-12-12 15:49:28] : Fast-connecting to nyc01.supportxmr.com:7777 pool ...
[2017-12-12 15:49:28] : Pool nyc01.supportxmr.com:7777 connected. Logging in...
[2017-12-12 15:49:28] : Difficulty changed. Now: 25000.
[2017-12-12 15:49:28] : Pool logged in.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   34.0 |   (na) |   (na) |  1 |   38.2 |   (na) |   (na) |
|  2 |   44.1 |   (na) |   (na) |  3 |   38.8 |   (na) |   (na) |
|  4 |   43.4 |   (na) |   (na) |  5 |   39.7 |   (na) |   (na) |
|  6 |   35.2 |   (na) |   (na) |  7 |   33.0 |   (na) |   (na) |
-----------------------------------------------------
Totals:    306.6   (na)   (na) H/s
Highest:   303.6 H/s
CONNECTION REPORT
Pool address    : nyc01.supportxmr.com:7777
Connected since : 2017-12-12 15:49:28
Pool ping time  : (n/a)

Network error log:
Yay! No errors.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   33.0 |   (na) |   (na) |  1 |   37.6 |   (na) |   (na) |
|  2 |   43.1 |   (na) |   (na) |  3 |   38.7 |   (na) |   (na) |
|  4 |   42.1 |   (na) |   (na) |  5 |   38.9 |   (na) |   (na) |
|  6 |   34.7 |   (na) |   (na) |  7 |   32.5 |   (na) |   (na) |
-----------------------------------------------------
Totals:    300.4   (na)   (na) H/s
Highest:   304.6 H/s
[2017-12-12 15:50:09] : Difficulty changed. Now: 25000.
[2017-12-12 15:50:09] : New block detected.
[2017-12-12 15:50:26] : Difficulty changed. Now: 16854.
[2017-12-12 15:50:26] : New block detected.

**Comment by m03e5** [comment]
Whats your CFG file content for nvidia after you have deleted empty CFG and restarted miner - did it create a new CFG file? if it did whats in it?

**Comment by DuquetteRoxx** [comment]
Yes when I run it after deleting the nvidia config, it creates a new nvidia.txt but it just has the “template” inside it, no actual values set.

**Comment by m03e5** [comment]
It has 2 gpu's on board right? Perhaps in this case it will be necessary to manually play with CFG. Maybe someone has any other titans CFG to compare with... have you tried any other miners with it, were they successful? if yes, then its possible to look in to configs generated by those miners and try applying it

**Comment by DuquetteRoxx** [comment]
I'll bet this is the problem..
![hmmm](https://user-images.githubusercontent.com/34487958/33927311-c60af73c-dfaf-11e7-9c26-89114cd213c1.png)

**Comment by sergneo** [comment]
The NVIDIA driver is the latest? 388.59 WHQL

**Comment by DuquetteRoxx** [comment]
Yup. Tried deleting all previous versions/clean install and all that.

**Comment by sergneo** [comment]
Looks like XMR-stak is unable to determine your GPU, this is a bug

**Comment by DuquetteRoxx** [comment]
Are there any values I can enter to force it to acknowledge the cards?

**Comment by sergneo** [comment]
Leave only one GPU in the system and repeat all over again.

**Comment by luncht1me** [comment]
My friend is having a similar issue with his Titan X. Gave him your advice sergneo, will let you know what happens.

**Comment by alexnode** [comment]
I have the same problem ... Titan X the old one (maxwell) and it is not being detected automatically ...
