### ISSUE TITLE
Change that triggers Virus Alert? 

### ISSUE THREAD

**Issue by purplerane** [fireice-uk/xmr-stak#517]
Just curious why the new version (2.1) is getting flagged when 2.0 did not. I'm not trying to beat a dead horse here on this problem since I've seen others mention it, and I know the "fix" is to whitelist the folder, which I can do.  However, I'm running it on over 100 machines so that's going to be very time consuming and just trying to figure out what changed to trigger this.

**Comment by JerichoJones** [comment]
You can thank Bot herders for that. They wrap miners in their packages so now mining software is getting flagged by AV.

All you can do is create an exception in your AV for XMR-STAK.EXE or the folder in which you drop it.

**Comment by purplerane** [comment]
Thanks and I've seen your similar response elsewhere, but it still doesn't really answer my question. As I said the 2.0 version launched and still launches on all my machines without a problem, so I am curious what specifically changed in 2.1 to cause the change.

**Comment by psychocrypt** [comment]
than we had luck with our last release but it depends on the av companie.
The av protection uses heuristics to detect bad software this can be the
reason that the last version was not flagged as virus.

**Comment by purplerane** [comment]
ok, thanks. most of my systems are running Windows 10, just using the built-in tools.  Part of the reason I started using xmr-stak over the others was even the old versions never were flagged as malicious on my system so it's just going to take a bit more work on my part if I want to use the newest version.

**Comment by fireice-uk** [comment]
@purplerane It is a pure luck of the draw from our side. I suspect that herders prefer more tested software so they waited until 2.1 to start dropping it.
