### ISSUE TITLE
CMAKE_LINK_STATIC does only link libgcc and libstdc++

### ISSUE THREAD

**Issue by yjeanrenaud** [fireice-uk/xmr-stak#518]
I would love to static link all the libraries, thus libltdl, libhwloc, libcrypto and libmicrohttpd as well as libssl to the binary for easy deployment on embedded machines

**Comment by psychocrypt** [comment]
This is not possible if you using your distribution provided libraries.
Most ofnthe shipped libraries are not as static version available.
Therefore only a few gcc dependencies can be included.

**Comment by yjeanrenaud** [comment]
thanks for making this clear. I will try to get nonstatics
