### ISSUE TITLE
cuda error gpu0: 

### ISSUE THREAD

**Issue by firestart57** [fireice-uk/xmr-stak#519]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. intel 4400 
  - Type of the GPU  geforce gtx 1080 ti 
# Compile issues
  - Which OS do you use? windows 
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

i downloaded the miner followed the comands and got  this error 
cuda error gpu 0:  <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

can any one help?

**Comment by psychocrypt** [comment]
set befactor in nvidia.txt to 8 or reduce the threads in this file.
