### ISSUE TITLE
Autosuggest issues and fine tuning

### ISSUE THREAD

**Issue by gboddin** [fireice-uk/xmr-stak#52]
Hi !

First, uber nice work on this all-in-one refactoring, thanks

I gave it a shot yesterday on debian sid + cuda 9.0 and hashrates seems more stable than 5 separate miners !

Machine A : 
- Intel(R) Core(TM) i3-7100T CPU @ 3.40GHz ( 2x30H/s, but expected, who cares :) )
- rx580 4GB ( 770H/s )
- gtx 1060 3GB ( 520/H/s )

Machine B (laptop): 
- Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz ( 3x60H/s, that's always nice )
- gtx 950m 4GB ( 170H/s )

I had to adapt the autosuggest on the first machine for the 1060, first it gave : 
```
  { "index" : 0,
    "threads" : 52, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
```

but this was giving ~10% rejected shares ( at 520/Hs ), dividing by 2 

```
  { "index" : 0,
    "threads" : 26, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
```
made all the rejects go away and we're now at 100% accepted for 12h :)

Hope it helps !

**Comment by psychocrypt** [comment]
Thanks for opening the issue. Could you please repeat the test and post the
reason for the rejected shares. If the miner gets a new block and just
found e.g. 4 shares for the old block than it could be that you get 4
expired shares but this can not be avoided.
If you get compute errors than we need to look deeper to found the reason.

**Comment by fireice-uk** [comment]
@gboddin can you confirm that the testing was on topic-nonce-final branch?

**Comment by gboddin** [comment]
It was without the topic-nonce-final.

I'm merging, building and will report again

**Comment by gboddin** [comment]
Ok first report on 950m : 
Letting autoconfig gives : 

```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 950M architecture: 50
  //      memory: 4000/4044 MiB
  { "index" : 0,
    "threads" : 68, "blocks" : 15,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },

],
```
however, this ends up with : 

```
-------------------------------------------------------------------
xmr-stak 2.0.0-predev mining software.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
NVIDIA mining code was written by KlausT and psychocrypt.
AMD mining code was written by wolf9466.
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 2.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-18 18:53:38] : Starting GPU thread, no affinity.
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
[2017-10-18 18:53:39] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-10-18 18:53:39] : WARNING: backend AMD disabled.
[2017-10-18 18:53:39] : hwloc: memory pinned
[2017-10-18 18:53:39] : Starting single thread, affinity: 0.
[2017-10-18 18:53:39] : hwloc: memory pinned
[2017-10-18 18:53:39] : Starting single thread, affinity: 1.
[2017-10-18 18:53:39] : hwloc: memory pinned
[2017-10-18 18:53:39] : Starting single thread, affinity: 2.
[2017-10-18 18:53:39] : Connecting to pool xmr-eu1.nanopool.org:14444 ...
[2017-10-18 18:53:42] : Connected. Logging in...
[2017-10-18 18:53:42] : Difficulty changed. Now: 120001.
[2017-10-18 18:53:42] : New block detected.
HASHRATE REPORT
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | (na) | (na) | (na) |  1 | (na) | (na) | (na) |
|  2 | (na) | (na) | (na) |  3 | (na) | (na) | (na) |
-----------------------------------------------------
Totals:   (na) (na) (na) H/s
Highest:  0.0 H/s
[CUDA] Error gpu 0: </xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:230
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: the launch timed out and was terminated
```

Lowering threads to 34 fixes the issue.

**Comment by psychocrypt** [comment]
you can also keep the old config and increase bfactor. The timeout is
coming from the xserver. I missed the fact that many users keep the xserver
enabled :-). If to many threads are used the over all time for one bunch of
hashes increases and after a few seconds the xserver will kill the miner.
Thats equal than in windows but under linux there is more rime before a gpu
process will be killed.

**Comment by gboddin** [comment]
Increasing bfactor to 8 seems to make the miner not crash anymore, but the H/s report for the 950M is on N/A and doesn't seem to move. ( I get 50/s in the 60s column but nothing in the 15s anymore ).

Anyhow, this is a hybrid laptop graphic setup (the nvidia chip is used only for mining, I'm using intel for display), so I expected rough edges and at this point, only halving the threads to 34 works atm ( i'm on 384.90 ).

Afaik optirun probes the drivers and launches an X server. Only then we can run nvidia-settings to OC the memory.

I tried to kill everything once xmr-stak runs but the hashrate went down to 80.

I will look at nvidia-persistenced, maybe that can help, also I wouldn't concern too much about this, it's low hashrate and can kill laptop, if you still want some debug output let me know !

On the GTX 1060 side, I have left the 52 threads with the merge of topic-fix and topic-nonce-final branches, and no reject to report anymore. ( It was quickly noticeable before, I completely forgot to write down the messages that started with "NVIDIA:" though -_-' ).

I'll close this in 24h if nothing else to report. Thanks for the support !

**Comment by psychocrypt** [comment]
I am confused you jumped between different systems with different settings.
Could you please focus for which system the auto config is not working.

**Comment by gboddin** [comment]
My bad, ok so I have 2 systems : 


### Fixed computer running Debian sid ( Kernel 4.11 with default amdgpu driver and nvidia 384.90, no X except to bootstrap nvidia memory clock, killed afterwards )

1. AMD RX580 4GB ( bios timings modded, mem clock at 2100Mhz ) -> [generated-amd-rx580-4g.txt](https://github.com/fireice-uk/xmr-stak/files/1396053/generated-amd-rx580-4g.txt) : ~780H/s

2. nVidia 1060 3GB ( mem clock at + 900mhz ) -> [generated-nvidia-1060.txt](https://github.com/fireice-uk/xmr-stak/files/1396077/generated-nvidia-1060.txt) : ~510H/s

3. CPU i3 7100T (3.4GHZ no OC) -> [generated-cpu-i3-7100t.txt](https://github.com/fireice-uk/xmr-stak/files/1396090/generated-cpu-i3-7100t.txt) : ~30H/s x2

4. Intel HD graphics ( not used for mining, wish I could , beignet is crashing even clinfo, probably Debian sid )

### Laptop running Debian sid ( Kernel 4.9 with nvidia 384.90 )

1. Secondary nVidia 950M ( mem clock at +175mhz ) -> [generated-nvidia-950m.txt](https://github.com/fireice-uk/xmr-stak/files/1396113/generated-nvidia-950m.txt) : ~160H/s

2. CPU i7 i7-6700HQ ( 2.6Ghz no OC ) -> [generated-cpu-i7-6700HQ.txt](https://github.com/fireice-uk/xmr-stak/files/1396120/generated-cpu-i7-6700HQ.txt) : ~60H/s x3

3. Intel HD graphics ( not used for mining but as default display adapter, wish I could , beignet is crashing even clinfo, probably Debian sid )


#### Small issues
- The AMD RX580 seemed under-evaluated, probably because during the test the amount of memory detected (2815) is not what's really available in real conditions (4000) ? Changing intensity to 1000 instead of 864 gives +~25H/s  
- Yesterday, the nvidia 1060 seemed unstable and gave rejects. however after merge of the fix branches and  recompile today it's rock solid at ~510h/s -> so forget it problem solved

#### Blockers
- The nvidia 950M in the laptop won't start mining with the default suggested threads ( 68, see the previous log ). Setting the bfactor to 8 doesn't help, rather it makes the miner output 50H/s sporadically ( every minutes or so ). Resetting the bfactor to 0 and setting the threads to 34 on the other hand gives a solid 160H/s ( which is what I ended up with when using xmr-stak-nvidia anyway )

**Comment by gboddin** [comment]
After too much checking -_-'

Disabling the X server on the nVidia chip makes the PowerMizer run the card in the lowest perf possible (450Mhz), and depsite ```nvidia-smi -ac``` allowing the max frequency to be changed, doesn't prevent it to kick in.

```
# nvidia-smi --gom=0
GOM mode cannot be changed on GPU 00000000:01:00.0.
Treating as warning and moving on.
All done.
```

That happens on both the 1060 and the 950M.

If that's the output of your distro, there's not choice other choice to keep an headless X server enabled ...

Here's the final sh** I ended up with : 
```
optirun nvidia-smi -pm 1
optirun nvidia-settings -c :8 -a "GPUPowerMizerMode=1" -a "GPUMemoryTransferRateOffset[2]=400"
optirun ./bin/xmr-stak
```

There are counteless of X headless script arround on the internet to work arround this issue.

Probably this doesn't occur on more advanced cards made for computing only ( and therefore supporting nvidia-smi --gom=0 )


So remaining issue still : 
The 950M is getting twice the threads it should during xmr-stak autoconfig ( or something else is wrong ).

```
HASHRATE REPORT
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | (na) | (na) | (na) |  1 | (na) | (na) | (na) |
|  2 | (na) | (na) | (na) |  3 | (na) | (na) | (na) |
-----------------------------------------------------
Totals:   (na) (na) (na) H/s
Highest:  0.0 H/s
[CUDA] Error gpu 0: </xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:230
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: the launch timed out and was terminated
```

```
Timestamp                           : Thu Oct 19 01:53:24 2017
Driver Version                      : 384.90

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 950M
    Product Brand                   : GeForce
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Enabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-68882c87-5d7b-0a12-f29e-425382acb6db
    Minor Number                    : 0
    VBIOS Version                   : 82.07.86.00.20
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x139A10DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x1C9D1043
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 8x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 41000 KB/s
        Rx Throughput               : 148000 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 4044 MiB
        Used                        : 1067 MiB
        Free                        : 2977 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 1 MiB
        Free                        : 255 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 100 %
        Memory                      : 44 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 60 C
        GPU Shutdown Temp           : 101 C
        GPU Slowdown Temp           : 96 C
        GPU Max Operating Temp      : 92 C
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : 1124 MHz
        SM                          : 1124 MHz
        Memory                      : 1201 MHz
        Video                       : 1011 MHz
    Applications Clocks
        Graphics                    : 993 MHz
        Memory                      : 1201 MHz
    Default Applications Clocks
        Graphics                    : 993 MHz
        Memory                      : 1201 MHz
    Max Clocks
        Graphics                    : 1124 MHz
        SM                          : 1124 MHz
        Memory                      : 1201 MHz
        Video                       : 1011 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 32120
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 4 MiB
        Process ID                  : 32125
            Type                    : C
            Name                    : ./bin/xmr-stak
            Used GPU Memory         : 1052 MiB

````

**Comment by psychocrypt** [comment]
thanks for build the summery. I will think about the issue and where it
coming from

**Comment by gboddin** [comment]
I was trying to compile a debug version to give more output but : 

```
[ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:900:23: error: invalid operands to binary expression ('size_t *' (aka 'unsigned long *') and 'size_t' (aka 'unsigned long'))
                        assert(BranchNonces%w_size == 0);
                               ~~~~~~~~~~~~^~~~~~~
/usr/include/assert.h:89:5: note: expanded from macro 'assert'
  ((expr)                                                               \
    ^~~~
```
Doesn't happen on release.

Maybe I need some dbg packages ?

**Comment by psychocrypt** [comment]
Asserts are only active if you compile with in debug mode. Never the less I
saw that there is a bug in the expression. I will fix it tonight

**Comment by psychocrypt** [comment]
@gboddin your assert bug is fixed in #60

**Comment by psychocrypt** [comment]
@gboddin The nvidia timeout can be a result of an illegal memory access which is fixed in #57

**Comment by psychocrypt** [comment]
To allocate the full memory of your amd card you need to set some environment variables before you start the miner. The limitaion is coming from the opencl standard. The variables must be set before each start.

```
export GPU_FORCE_64BIT_PTR 0
export GPU_MAX_HEAP_SIZE 98
export GPU_MAX_ALLOC_PERCENT 100
export GPU_SINGLE_ALLOC_PERCENT 100
```

Never the less the autosuggestion will always only use max. 2GiB memory. 
This will be changes for VEGA gpus soon.

**Comment by gboddin** [comment]
Hi variables are set everywhere now :)

Still same results.

Ok I'm done testing with the various builds ( the debug builds works now , perfect ! ).

So yeah the 950M definitely won't start mining with the default suggested settings. I have to reduce either the threads or blocks by half.

It's a mobile gpu so it could be a bit exotic, let me know if you need any debug, strace or whatever ;)

A small sumary for hybrid laptop user  :
 
- Use your intel as main graphic
- Don't config Xorg for the nvidia ( except if you want overclocking with coolbits through nvidia-settings, but on a mobile, not recommended )
- Install the nvidia drivers probing them will enable compute

```sh
# enable the gpu, check the documentation depending on your situation ( switcheroo ,ect ) 
modprobe nvidia
# resets GPU 
nvidia-smi -r
# sets permanent mode to 0, otherwise clocks stay at the lowest :| < see me confused
nvidia-smi -pm 0 
``` 

I guess this bug can be closed since it's a corner case.

**Comment by psychocrypt** [comment]
If you lowered the thread count is this than working?

**Comment by gboddin** [comment]
Yes.

I also noticed that reducing the thread counts on 1060s ( I have 2 now ) gave a few H/s more.

Maybe the suggest just overshoot nvidia by default ? How is this computed ?

Here's a small table with numbers which should be easier to grasp : 

|Card|Bios timings modded|OC mem|Suggested threads|Hashrate|Changed threads|New hashrate|
|---|---|---|---|---|---|---|
|Gigabyte 1060 3GB|no|2350Mhz|52|510|26|525|
|KFA2 1060 3GB|no|2250Mhz|52|495|26|505|
|RX 580 4GB|no|2100Mhz|852|750|1000|770|

**Comment by Znuff** [comment]
I'll leave my expertise here, even if the ticket was closed.

I'm running 8 x nVidia P106-100, so cards that are made for mining, under Linux (ubuntu-16.04).

You still need to run Xorg. No way around it. I tried. Once you stop Xorg, the card puts itself into P8 state and you can't take it out with `nvidia-smi`.

Also, you can't enable GOM on these, either:

```
# nvidia-smi --gom=0
GOM mode cannot be changed on GPU 00000000:01:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:02:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:03:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:04:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:06:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:07:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:08:00.0.
Treating as warning and moving on.
GOM mode cannot be changed on GPU 00000000:09:00.0.
Treating as warning and moving on.
All done.
```

Currently getting around 490H/s per GPU with the default (auto) settings.

**Comment by gboddin** [comment]
@Znuff yes you always need Xorg with nVidia when gom is not available.

Here's a one shot command to config xorg : 

```nvidia-xconfig -a --allow-empty-initial-configuration --cool-bits 28```

This will config all your cards to run headless ( without monitor having to be connected ) and with overclocking and fan control enabled.

You can then create a small script with
1. nvidia-settings commands for overclocking
2. at the end of the script run you miner

```
#!/bin/bash
/usr/bin/nvidia-settings -c :0 -a "[gpu:0]/GPUFanControlState=1" 
/usr/bin/nvidia-settings -c :0 -a "[gpu:1]/GPUFanControlState=1" 
/usr/bin/nvidia-settings -c :0 -a "GPUTargetFanSpeed=100"
/usr/bin/nvidia-settings -c :0 -a "[gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=200"
/usr/bin/nvidia-settings -c :0 -a "[gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels=100" 
/usr/bin/nvidia-settings -c :0 -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=1600" 
/usr/bin/nvidia-settings -c :0 -a "[gpu:1]/GPUMemoryTransferRateOffset[3]=1200"
cd /opt/xmrstak
./bin/xmrstak
```

Then run it with :

```
xinit your-script.sh
```

Memory OC is the key with XMR ;)

**Comment by Znuff** [comment]
I am very well aware on how to run it, even wrote my own system, that's not a problem.

It would just be nice for other people to run into this message to figure out that you can't run the mining cards without Xorg when they Google for an answer.

I know, it's stupid.

**Comment by hishikishi** [comment]
how to Disable CPU mining ? & my PC is Running slow hang after i start the mining ? what to do ?
& how to reduce speed of GPU

**Comment by Znuff** [comment]
Read the help file, maybe?

Pass `--nocpu` for no CPU Usage. Edit the nvidia.txt file to change the threads/blocks count to lower usage.
