### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Parlax** [fireice-uk/xmr-stak#520]
When I try to compile the build fails with following error.

"C:\xmr-stak-2.1.0\build\install.vcxproj" (default target) (1) ->
"C:\xmr-stak-2.1.0\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\xmr-stak-2.1.0\build\xmrstak_cuda_backend.vcxproj" (default target) (7) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(17
1,5): error MSB6006: "cmd.exe" exited with code 1. [C:\xmr-stak-2.1.0\build\xmrstak_cuda_backend.vcxproj]

    40 Warning(s)
    1 Error(s)

**Comment by Makanar** [comment]
I am having the same problem. CUDA version 9.1.85, Visual Studio version 15.5.1. Please help!
