### ISSUE TITLE
iMac MacOS compiling experiences, issues and hashrate report

### ISSUE THREAD

**Issue by borzaka** [fireice-uk/xmr-stak#522]
I just want to share my compiling experience and issues on MacOS.

# Basic information
[iMac (Retina display 5K, 27 inch, late 2015)](https://support.apple.com/kb/SP731?locale=en_US)
macOS High Sierra - 10.13.1 (17B1003)
3,2 GHz Intel Core i5 ([i5-6500](https://ark.intel.com/products/88184/Intel-Core-i5-6500-Processor-6M-Cache-up-to-3_60-GHz))
16 GB 1867 MHz DDR3
AMD Radeon R9 M390 2 GB

# Compile
I followed the guide [here](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_MacOS.md), but skipped the NVIDIA-specific part.

Used commands (I'm in my `$HOME/Downloads` folder):
```
brew install hwloc libmicrohttpd gcc openssl cmake
git clone https://github.com/fireice-uk/xmr-stak.git
cd xmr-stak/
cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ENABLE=OFF -DCMAKE_INSTALL_PREFIX=$HOME/Downloads/xmr-stak
make install
```

- My full compile [output](https://pastebin.com/zAFthpA7).
- `cmake -LA .` [output](https://pastebin.com/0ENXm0Wj).
- `./xmr-stak --version-long` output:
`Version: xmr-stak/2.1.0/31a0784/master/mac/amd-cpu/aeon-monero/0`
- `clinfo: command not found`

# First start
```
[2017-12-12 21:33:23] : Start mining: MONERO
[2017-12-12 21:33:23] : Found AMD platform index id = 0, name = Apple
[2017-12-12 21:33:23] : Found OpenCL GPU .
[2017-12-12 21:33:23] : AMD: GPU configuration stored in file 'amd.txt'
[2017-12-12 21:33:23] : Compiling code and initializing GPUs. This will take a while...
[2017-12-12 21:33:23] : WARNING: using non AMD device: Apple
[2017-12-12 21:33:23] : Device 0 work size 8 / 32.
[2017-12-12 21:33:26] : Starting AMD GPU thread 0, no affinity.
[2017-12-12 21:33:26] : Autoconf FAILED: Failed to allocate a PU.. Create config for a single thread.
[2017-12-12 21:33:26] : CPU configuration stored in file 'cpu.txt'
[2017-12-12 21:33:26] : Starting 1x thread, no affinity.
[2017-12-12 21:33:26] : Fast-connecting to stratum+tcp://etn.nasf.eu:3333 pool ...
[2017-12-12 21:33:26] : Pool stratum+tcp://etn.nasf.eu:3333 connected. Logging in...
[2017-12-12 21:33:26] : Difficulty changed. Now: 512.
[2017-12-12 21:33:26] : Pool logged in.
[2017-12-12 21:33:31] : Result accepted by the pool.
```

# CPU
It did not recognize my CPU cores and threads, and saved a single thread config, so I started to optimize the cpu.txt;
This CPU has 4 cores and 4 threads, but using only 3 threads can make the most hash. XMRIG knew this from the beginning when I tried their CPU mining software.
My cpu.txt:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],
```

With this config, there is a hwlock error for each thread:
```
[2017-12-12 21:46:08] : Starting 1x thread, affinity: 0.
[2017-12-12 21:46:08] : hwloc: set_thisthread_membind not supported
[2017-12-12 21:46:08] : WARNING on MacOS thread affinity is only advisory.
[2017-12-12 21:46:08] : Starting 1x thread, affinity: 1.
[2017-12-12 21:46:08] : hwloc: set_thisthread_membind not supported
[2017-12-12 21:46:08] : WARNING on MacOS thread affinity is only advisory.
[2017-12-12 21:46:08] : Starting 1x thread, affinity: 2.
[2017-12-12 21:46:08] : hwloc: set_thisthread_membind not supported
```

Still the mining starts with good (?) CPU hashrate.

# GPU
Default, untouched amd.txt:
```
"gpu_threads_conf" : [
  // gpu: AMD Radeon R9 M390 Compute Engine memory:384
  // compute units: 16
  { "index" : 0,
    "intensity" : 128, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
],
```

# Hashrate report
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   59.9 |   61.2 |   63.6 |  1 |   59.9 |   61.2 |   63.6 |
|  2 |   60.1 |   61.3 |   63.6 |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m |
|  0 |   98.7 |   98.5 |   98.6 |
---------------------------
Totals:    278.6  282.1  289.6 H/s
Highest:   292.0 H/s
```

# Stability issues
- When using only CPU, everything is fine; I can use the computer, but when GPU joins the party, the whole system became very laggish and unusable. Lowering the intensity doesn't help much. I changed to 64, but it was as laggish as before but with a half hashrate.
- No overclocks/undervolts.

What could I do differently or try to optimize these settings?

I hope my macOS compiling experiences helps and gives additional infos for the developers. Keep up the good work!

**Comment by borzaka** [comment]
Update:

I haven't checked the results until now. And something is probably wrong with the GPU settings. After ~25 minutes it has 30 AMD Invalid Result.
No overclocks, no undervolts, it's a stock iMac.

```
RESULT REPORT
Difficulty       : 6012
Good results     : 233 / 263 (88.6 %)
Avg result time  : 5.8 sec
Pool-side hashes : 340432

Top 10 best results found:
|  0 |           140370 |  1 |           115746 |
|  2 |            88953 |  3 |            65601 |
|  4 |            62118 |  5 |            55448 |
|  6 |            55214 |  7 |            49062 |
|  8 |            42237 |  9 |            35448 |

Error details:
| Count | Error text                       | Last seen           |
|    30 | AMD Invalid Result               | 2017-12-15 11:43:08 |
```
amd.txt is unchanged:
```
"gpu_threads_conf" : [
  // gpu: AMD Radeon R9 M390 Compute Engine memory:384
  // compute units: 16
  { "index" : 0,
    "intensity" : 128, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },
],
```

**Comment by pwdrhash** [comment]
I just wanted to note that in the fourth line of your commands list something got cut off at the "=" sign which I figured out by looking at your log.

**Comment by borzaka** [comment]
That just a weird Pastebin.com line break issue I guess. If you copy that two line, and paste you will see one line.
The install prefix is right there I wanted.

Thank you for having time to look my logs.

**Comment by pwdrhash** [comment]
Have you had any success getting your miner to work better without getting laggy?

**Comment by JerichoJones** [comment]
@borzaka Lowering your Intensity should sole the failure issue.

**Comment by wichall** [comment]
Got the same stability issues here when using GPU - even with an intensity of 1 the machine becomes instantly laggy and unusable. Hashrate appears to reflect intensity level however, so it's working on that level.

Something else seems to be causing the sluggishness - some sort of a leak?
