### ISSUE TITLE
No Linux binary xmr-stak-portbin-linux.tar.gz in latest releases

### ISSUE THREAD

**Issue by vaibhavch** [fireice-uk/xmr-stak#524]
As mentioned in the docs which is updated 12 days ago , I couldn't find linux binary in releases section. Please update the link.

**Comment by Dimitri2g** [comment]
Same for me. I have not been able to locate the portabin file. Also is it possible to get some installation instruction on how to set this up on CentOS?

**Comment by vaibhavch** [comment]
Run these commands. It will work for any linux distro.

`wget https://github.com/fireice-uk/xmr-stak/archive/v2.1.0.tar.gz`
`tar xzf  v2.1.0.tar.gz`
`cd xmr-stak-2.1.0`
`cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF . `
`cd bin`
`chmod +x xmr-stak`
`./xmr-stak`

**Comment by vaibhavch** [comment]
If cmake command fails, You have to install these things first for centos.
`sudo yum install centos-release-scl epel-release`
`sudo yum install cmake3 devtoolset-4-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make`
`sudo scl enable devtoolset-4 bash`

**Comment by Dimitri2g** [comment]
the cmake keeps failing for me.

# cmake3 -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF .
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak-2.1.0/CMakeFiles/CMakeOutput.log".

**Comment by Dimitri2g** [comment]
i have centos 7, 8 cores, 4 gb ram, and 100 gb HDD for this VM. It was working with older xmr-stak-cpu but the build keeps failing trying to get this latest code to work

**Comment by vaibhavch** [comment]
once try
'yum install libmpc-devel mpfr-devel gmp-devel`

`./configure --with-system-zlib --disable-multilib --enable-languages=c,c++`

`make -j 8`

`make install`

Also tell me your `gcc --version`

**Comment by Dimitri2g** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Dimitri2g** [comment]
# ./configure --with-system-zlib --disable-multilib --enable-languages=c,c++
-bash: ./configure: No such file or directory

**Comment by vaibhavch** [comment]
My bad. I missed mentioning downloading the gnu package.

`wget https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.gz`
`./configure --with-system-zlib --disable-multilib --enable-languages=c,c++`
`make -j 8`
`make install`

**Comment by Dimitri2g** [comment]
wget https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.gz
--2017-12-13 00:13:04--  https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.gz
Resolving ftp.gnu.org (ftp.gnu.org)... 208.118.235.20, 2001:4830:134:3::b
Connecting to ftp.gnu.org (ftp.gnu.org)|208.118.235.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 111997123 (107M) [application/x-gzip]
Saving to: ‘gcc-7.2.0.tar.gz’

100%[==============================================================>] 111,997,123 1.39MB/s   in 79s    

2017-12-13 00:14:23 (1.35 MB/s) - ‘gcc-7.2.0.tar.gz’ saved [111997123/111997123]

[root@c999948359-cloudpro-863762068 ~]# ./configure --with-system-zlib --disable-multilib --enable-languages=c,c++
bash: ./configure: No such file or directory

**Comment by vaibhavch** [comment]
`tar -xvf gcc-7.20.tar`
`cd gcc-7.20`

I thought you will figure out the extracting and selecting the directory.

**Comment by Dimitri2g** [comment]
woops, i was not paying attention. hehe.

**Comment by Dimitri2g** [comment]
./configure --with-system-zlib --disable-multilib --enable-languages=c,c++
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for libatomic support... yes
checking for libcilkrts support... yes
checking for libitm support... yes
checking for libsanitizer support... yes
checking for libvtv support... yes
checking for libmpx support... yes
checking for libhsail-rt support... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ accepts -static-libstdc++ -static-libgcc... no
checking for gnatbind... no
checking for gnatmake... no
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for isl 0.15 or later... no
required isl version is 0.15 or later
*** This configuration is not supported in the following subdirectories:
     zlib gnattools gotools target-libada target-libhsail-rt target-libgfortran target-libbacktrace target-libgo target-libffi target-libobjc target-liboffloadmic
    (Any other directories should still work fine.)
checking for default BUILD_CONFIG... bootstrap-debug
checking for --enable-vtable-verify... no
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... no
/root/gcc-7.2.0/missing: line 81: makeinfo: command not found
checking for expect... expect
checking for runtest... no
checking for ar... ar
checking for as... as
checking for dlltool... no
checking for ld... ld
checking for lipo... no
checking for nm... nm
checking for ranlib... ranlib
checking for strip... strip
checking for windres... no
checking for windmc... no
checking for objcopy... objcopy
checking for objdump... objdump
checking for readelf... readelf
checking for cc... cc
checking for c++... c++
checking for gcc... gcc
checking for gfortran... gfortran
checking for gccgo... no
checking for ar... no
checking for ar... ar
checking for as... no
checking for as... as
checking for dlltool... no
checking for dlltool... no
checking for ld... no
checking for ld... ld
checking for lipo... no
checking for lipo... no
checking for nm... no
checking for nm... nm
checking for objcopy... no
checking for objcopy... objcopy
checking for objdump... no
checking for objdump... objdump
checking for ranlib... no
checking for ranlib... ranlib
checking for readelf... no
checking for readelf... readelf
checking for strip... no
checking for strip... strip
checking for windres... no
checking for windres... no
checking for windmc... no
checking for windmc... no
checking where to find the target ar... host tool
checking where to find the target as... host tool
checking where to find the target cc... just compiled
checking where to find the target c++... just compiled
checking where to find the target c++ for libstdc++... just compiled
checking where to find the target dlltool... host tool
checking where to find the target gcc... just compiled
checking where to find the target gfortran... host tool
checking where to find the target gccgo... host tool
checking where to find the target ld... host tool
checking where to find the target lipo... host tool
checking where to find the target nm... host tool
checking where to find the target objcopy... host tool
checking where to find the target objdump... host tool
checking where to find the target ranlib... host tool
checking where to find the target readelf... host tool
checking where to find the target strip... host tool
checking where to find the target windres... host tool
checking where to find the target windmc... host tool
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
config.status: creating Makefile

**Comment by Dimitri2g** [comment]
Getting gcc 7.20 worked but for some reason it still thinks i have the old version. Is there somewhere i can go to force the change to use the latest versions?

**Comment by Dimitri2g** [comment]
[xmr-stak-2.1.0]# cmake3 -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF .
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak-2.1.0/CMakeFiles/CMakeOutput.log".
xmr-stak-2.1.0]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Dimitri2g** [comment]
also thank you kindly for helping me out

**Comment by vaibhavch** [comment]
did u ran `make -j 8` and `make install` ?

**Comment by psychocrypt** [comment]
to the initial question. the portable binaries are currently not available.
there is a small section for that in the documentation. we had some trubble
with the portable binaries and removed it. I hope we can solve it soon.

**Comment by OldenGit** [comment]
@Dimitri2g delete your untar'd  xmr-stak-2.1.0 directory (easiest way to clear the cmake cache for such a small build) then:
    export CC=/usr/local/bin/gcc
    export CXX=/usr/local/bin/g++

That will force cmake3 to use the correct compilers.

I still have a problem trying to build, I get the following:

$ cmake3 -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF .
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k")
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jerry/xmr-stak-2.1.0

Any ideas? 

Thanks

**Comment by Dimitri2g** [comment]
Figured it out after deploying a new centos box thanks @vaibhavch and @OldenGit you both helped me figure this out. Cheers.

#574

**Comment by kowenzhang** [comment]
I compile it on Ubuntu. I met two errors below:

CMake Error at CMakeLists.txt:311 (message):
  microhttpd NOT found: use `-DMICROHTTPD_ENABLE=OFF` to build without http
  deamon support

CMake Error at CMakeLists.txt:365 (message):
  hwloc NOT found: use `-DHWLOC_ENABLE=OFF` to build without hwloc support

the solution is following:
sudo apt install libmicrohttpd-dev libhwloc-dev

**Comment by kowenzhang** [comment]
I compile it on Ubuntu. I met two errors below:

CMake Error at CMakeLists.txt:311 (message):
microhttpd NOT found: use -DMICROHTTPD_ENABLE=OFF to build without http
deamon support

CMake Error at CMakeLists.txt:365 (message):
hwloc NOT found: use -DHWLOC_ENABLE=OFF to build without hwloc support

the solution is :
sudo apt install libmicrohttpd-dev libhwloc-dev

**Comment by kowenzhang** [comment]
I got a problem at the cmake step and nothing is generated in bin 

		kowen@kowen-desktop:~/Downloads/xmr-stak-2.1.0$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF .
		-- Set miner currency to 'monero' and 'aeon'
		fatal: Not a git repository (or any parent up to mount point /home)
		Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
		fatal: Not a git repository (or any parent up to mount point /home)
		Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
		-- Configuring done
		-- Generating done
		-- Build files have been written to: /home/kowen/Downloads/xmr-stak-2.1.0

**Comment by dade22** [comment]
hi, i got this on make install

[ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from /home/dev/xmr-stak/xmrstak/version.cpp:1:0:
/home/dev/xmr-stak/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
/home/dev/xmr-stak/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
  return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100
                                 ^
CMakeFiles/xmr-stak-backend.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JerichoJones** [comment]
Please don't tack on unrelated issues. Open your own issue. Thanks!

**Comment by dade22** [comment]
oops my fault

**Comment by drknght** [comment]
"did u ran make -j 8 and make install ?"

Hello I Followed the instructions from your posts and made corrections ... going into dirs... downloading g==, etc... But when i got to this point it ran for 1 1/2 hours and i cancelled the job.

is that normal or should i have waited?

**Comment by drknght** [comment]
"did u ran make -j 8 and make install ?"

Hello I Followed the instructions from your posts and made corrections ... going into dirs... downloading g==, etc... But when i got to this point it ran for 1 1/2 hours and i cancelled the job.

is that normal or should i have waited?

**Comment by WayneWZ** [comment]
the cmake failure, did anyone konw this issue?

ute@ute572-2:~/software/xmr-stak-2.1.0$ 
ute@ute572-2:~/software/xmr-stak-2.1.0$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF
CMake Error: The source directory "/home/ute/software/xmr-stak-2.1.0/DOpenCL_ENABLE=OFF" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ute@ute572-2:~/software/xmr-stak-2.1.0$

**Comment by drknght** [comment]
Did this a while ago so do not recall exactly but ...

Compile with "-DCUDA_ENABLE=OFF" If you have AMD

Check Help file for exact syntax.

Worked for me after I paid attention to the Error Msg at the End... After doing a whole lot of debugging.

-----Original Message-----

**Comment by old-greywolf** [comment]
Hello.  I am the newest n00b in mining, but thought I'd try on an old linux box.  I've got Linux Mint 18.3 (forked from Ubuntu), and not an expert at all with the  command line, but certainly not afraid of it.
So I stumbled onto this page after finding out that there is only a latest version for Windows.
After following the first steps at the top of the page, cmake puked for me, also.
But the discussions that follow are not clear, so please help me understand.  I think the steps I should follow are:
wget https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.gz
tar -xvf gcc-7.20.tar
cd gcc-7.20
./configure --with-system-zlib --disable-multilib --enable-languages=c,c++
make -j 8
make install

then:
wget https://github.com/fireice-uk/xmr-stak/archive/v2.1.0.tar.gz
tar xzf v2.1.0.tar.gz
cd xmr-stak-2.1.0
cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF DOpenCL_ENABLE=OFF
cd bin
chmod +x xmr-stak
./xmr-stak

Or did I miss something inbetween?
Thanks.

**Comment by WayneWZ** [comment]
@drknght  thanks for your feedback!

after the cmake command corrtetion and ' libmicrohttpd-dev' 'libhwloc-dev' libarary installtion, i could moving forward more now. 

do you konw which libs should be installed for the OpenSSL?

  OpenSSL NOT found: use `-DOpenSSL_ENABLE=OFF` to build without SSL support


ute@ute572-2:~/software/xmr-stak-2.2.0$ cmake -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:339 (message):
  OpenSSL NOT found: use `-DOpenSSL_ENABLE=OFF` to build without SSL support


-- Configuring incomplete, errors occurred!

**Comment by WayneWZ** [comment]
after the libssl1.0.0 and libssl-dev installtion for OpenSSL, the cmake is ok, then could execute the xmr-stak now, thanks for your sharing!

make install
cd bin
chmod +x xmr-stak
./xmr-stak

**Comment by T81** [comment]
@vaibhavch you forgot a dash "-" after "-DCUDA_ENABLE=OFF". It should be "-DOpencl" else the command fails.

**Comment by asanchez500** [comment]
So I tried to compile on Red Ribbon Linux for my PS3 as you said it would compile one any distro and I am getting an error stating that i need CMake 3.1.0 and that I am running version 3.0.2. I was that close to getting it to run on my PS3. lol. I wonder if the portbin would of worked or not on the PS3? Please let me know if there is a work around. Thank you.

**Comment by psychocrypt** [comment]
For the PS3 you must compile it by hand. But it should not compile because
the Cell processor used in the PS3 is not an x86 CPU system. We support
currently only x86.
