### ISSUE TITLE
Memory Alloc Error - CentOS 7.2

### ISSUE THREAD

**Issue by nueverest** [fireice-uk/xmr-stak#525]
# Basic information
  - CentOS 7.2
  - CPU AMD Opteron 6274 x2 (dual CPU - 32 cores)  
  - Total of 16/12  L2/L3 Cache (Taken directly from the BIOS)

# Issue with the execution
  - Receiving MEMORY ALLOC FAILED : mmap failed
  - hwloc: memory pinned

# Steps taken

Followed the Large Page Size instructions here:
https://github.com/fireice-uk/xmr-stak/blob/master/doc/FAQ.md#error-memory-alloc-failed-mmap-failed

```
sudo sysctl -w vm.nr_hugepages=128
ulimit -l
64
sudo nano /etc/security/limits.conf
```

Added these lines:
```
* soft memlock 262144
* hard memlock 262144
```
Saved the file.

Even though it says you do not need to reboot I still did.
`reboot`    

Once everything was back up I ran.

```
ulimit -l
262144
cd /path/to/xmr-stak
./xmr-stak
```

 **Memory Alloc Failed : mmap failed persists.**

Hopefully I'm just missing something simple.

**Comment by JeffBarrowbank** [comment]
I also got the same issue but on Linux Ubuntu 16 LTS:

[2017-12-15 17:54:24] : Starting 1x thread, affinity: 22.
[2017-12-15 17:54:24] : hwloc: memory pinned
[2017-12-15 17:54:24] : Fast-connecting to pool.electroneum.space:3333 pool ...
[2017-12-15 17:56:34] : SOCKET ERROR - [pool.electroneum.space:3333] CONNECT error: Connection timed 
out

Followed the same steps above. Tried everything I can think of to change the settings etc. Cannot get the miner to work.

**Comment by nueverest** [comment]
Seems like you are getting a SOCKET ERROR.  Are you sure that your pool connection settings are correct.  I can still connect to my pool.

**Comment by NmxMilk** [comment]
On centos : sudo sysctl -w vm.nr_hugepages=128 
may not persist after boot.
You might have to explictly edit:
/etc/sysctl.conf and add the line:
vm.nr_hugepages=128.
After reboot check with:
grep Huge /proc/meminfo
if huge pages are used or not.

**Comment by nueverest** [comment]
After I edited /etc/sysctl.conf my computer crashed and I got kernel errors.  I also installed CUDA 9.1 right before this happened so now I'm nervous to try this again as I just had to re-install the OS.
