### ISSUE TITLE
AMD Driver: blockchain mandatory

### ISSUE THREAD

**Issue by qdel** [fireice-uk/xmr-stak#527]
Hi
# Basic information
  - i7 4790k
  - Vega 64 LC, downclocked gpu to 

# amd.txt
"gpu_threads_conf" : [
  { "index" : 0,
    "intensity" :1900, "worksize" : 8,
    "affine_to_cpu" : 3,
  },
  { "index" : 0,
    "intensity" : 1900, "worksize" : 8,
    "affine_to_cpu" : 3,
  },
],

# Mining overclock / downclock
GPU_P0=852;900
GPU_P1=991;900
GPU_P2=1084;900
GPU_P3=1138;900
GPU_P4=1150;900
GPU_P5=1202;900
GPU_P6=1212;905
GPU_P7=1408;925
Mem_P0=167;900
Mem_P1=500;900
Mem_P2=800;900
Mem_P3=1100;905
Fan_Min=30
Fan_Max=1800
Fan_Target=70
Fan_Acoustic=1500
Power_Temp=70
Power_Target=0

I have ~2000H/s using blockchain driver + this configuration.

Using latest 17.12.1, (or any driver different to the blockchain one), i can't mine using 2 threads. The card is never able to process both threads correctly.

Is this expected?

**Comment by psychocrypt** [comment]
It could be that the blockchain driver is optimized to have less context
memory reserved on the gpu and also that opencl allows to allocate more
memory with on call.
You can try
https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md#increase-memory-pool
on the non blockchain driver.

**Comment by qdel** [comment]
This doesn't seems to affect performance / behavior.

I managed to have a stable hashrate when taking care to disable / enable device before launching the miner, but i top at 1350 h/s on the same card.

**Comment by JerichoJones** [comment]
The release driver does not appear to enable compute on Vega unless you are mining ETH... at least this is the complaint on REDDIT.

**Comment by qdel** [comment]
The so-called automatic mode switching does not switch...

Any way to force it? The Reddit thread is kind of long.

**Comment by JerichoJones** [comment]
No

**Comment by qdel** [comment]
An update to this, i do not reopen as it is not an issue with xmr-stak:
using 18.1.1, the driver is able to mine with 2 thread and is stable.

But the hashrate is slower, using blockchain it is possible to reach 1020+960
Using 18.1.1 i manage to have 720+640

But at least it is stable, seems the driver is improving on this.
