### ISSUE TITLE
xmr-stack crashes at the start

### ISSUE THREAD

**Issue by zloniko** [fireice-uk/xmr-stak#529]
**System**:
Windows 8.1
**CPU:** 
i7-4770 3.4 GHz
RAM 32 GB
**GPU:**
GeForce GTX 770
**NVidia driver:**
388.59
**CUDA**
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:08:12_Central_Dayligh
Cuda compilation tools, release 9.1, V9.1.85

**Issue:**
After the launc xmr-tak crashes. In prompt I have:
Error gpu:0 <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

**Comment by psychocrypt** [comment]
increase bfactor to 8 or reduce threads in nvidia.txt

Am 13.12.2017 10:46 schrieb "zloniko" <notifications@github.com>:

**Comment by Joshelin** [comment]
Had same error as OP.
NB: Error comes up on my end only the 2nd time I start xmr-stak. Rebooting does solve the problem but it appears again if I close xmr-stak and open it again.

I increased bfactor to 8, lowered threads until error stopped appearing.
Threads are set at 9, but GPU is not working or that's what I think is happening.

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   24.9 |   26.3 |   (na) |  1 |   32.3 |   37.4 |   (na) |
|  2 |   38.8 |   35.9 |   (na) |  3 |   38.4 |   39.2 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |   (na) |   (na) |   (na) |
---------------------------
Totals:     (na)   (na)   (na) H/s
Highest:     0.0 H/s

Threads at 10 gives the error, lowering down threads stops the error but GPU isn't doing anything.

**Comment by diegonc** [comment]
I've found this problem to be related to the memory requirements of the miner. If you check the mallocs [here](https://github.com/fireice-uk/xmr-stak/blob/v2.1.0/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu#L220), you can calculate the usage in bytes:

* 680 * blocks * threads
* 128
* hashMemSize * blocks * threads

where hashMemSize is `2097152` (2M) for Monero and `1048576` (1M) for Aeon.

Thus,

```
                     GPUMemory - 128
blocks * threads < --------------------
                     hashMemSize + 680
```

also `threads` must be lower than the maximum threads per block the card supports. Use the `deviceQuery` tool to find your card parameters. My installation put it in the folder `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\demo_suite`.

Hope this helps 😃
