### ISSUE TITLE
Vega, xmr-stak-amd works, xmr-stak does not find AMD device

### ISSUE THREAD

**Issue by dwright1542** [fireice-uk/xmr-stak#535]
(3) Vega 64's, Windows 10 v 2.0.0/005e4a
Also Integrated Video

"gpu_threads_conf" : [
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0 },
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0 },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0 },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
    { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },
    { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1 },	

],

I get:

[2017-12-13 19:01:23] : Compiling code and initializing GPUs. This will take a while...
[2017-12-13 19:01:24] : WARNING: using non AMD device: Intel(R) Corporation
[2017-12-13 19:01:24] : Selected OpenCL device index 1 doesn't exist.

[2017-12-13 19:01:24] : WARNING: AMD device not found
[2017-12-13 19:01:24] : WARNING: backend AMD disabled.

**Comment by psychocrypt** [comment]
remove the file amd.txt and start the miner. The miner will search for your
gpu. You changed the file by hand and added an error.
Please update to the latest release, the new version is 2.1.

**Comment by dwright1542** [comment]
Sure did edit by hand.   Vega requires 2 workers per card.   Re did it this time and it worked ok.

**Comment by psychocrypt** [comment]
you changed the platform_index this was the reason for then issue but to
avoid  misunderstandings I let you generate the default ;-)

**Comment by sthanh** [comment]
Do you know if the "index" correspond to the index of the drive when looking at the device manager?
I have a mixed of Vega 56 and Vega 64 so I don't know which index intensity to set it, afraid I might set it to the wrong one.

Thanks!
