### ISSUE TITLE
cpu hash descent compare to old xmr-stak-cpu

### ISSUE THREAD

**Issue by loveacat** [fireice-uk/xmr-stak#536]
hi, thanks for your code, i'm now using my server to dig xmr. 
# Basic information
  - 2x  intel e5 2670v3

the program run about one day and the old xmr-stak-cpu hash rate  up to 500H /s
today i compile  the new version v2.1.0 use command  (https://github.com/fireice-uk/xmr-stak/archive/v2.1.0.zip)
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF .. 
make install
every thing is ok  but when i run the hash rate is only up to 348 h/s .
in your release note there is a huge performance improve on cpu mining 
what's wrong with my version ? or dose  my cpu use the old program is better?
thanks

**Comment by nadal28** [comment]
are you using same cpu settings?

**Comment by SeaDude** [comment]
My hashrate is also lower in v2.1. https://github.com/fireice-uk/xmr-stak/issues/588, though I am mining with CPU and GPU.

**Comment by JerichoJones** [comment]
@loveacat Did you reboot your machine before you tried to run v2.1?
