### ISSUE TITLE
Disable AMD and Nvidia GPU

### ISSUE THREAD

**Issue by fishbird3000** [fireice-uk/xmr-stak#537]
How do i disable both AMD and Nvidia GPU mining and just use CPU mining? I have looked and seen --noAMD but i have no idea where to input this and I haven't seen anything to disable Nvidia.

**Comment by veridicis** [comment]
Are you on Windows? Just remove the cuda and opencl .dll files from the folder :)

**Comment by fishbird3000** [comment]
Yes, THANK YOU!

**Comment by JerichoJones** [comment]
xmr-stak --help

**Comment by DavidBruchmann** [comment]
see #470

**Comment by hishikishi** [comment]
how to Disable CPU mining ? & my PC is Running slow hang after i start the mining ? what to do ?
