### ISSUE TITLE
Optimization needed for Xeon processors

### ISSUE THREAD

**Issue by vans163** [fireice-uk/xmr-stak#539]
Dual Socket, Xeon 8+ phys core cpus.
Ubuntu 16.04

So if I mine on 2 physical cores of a Xeon CPU, then run a 2 phys core miner instance to fill all the cores. I get about 10-15% more hashes.  Very strange but I think an optimization can be added.

Also running 1 miner per NUMA node gives about 20-30% more hashes then 1 miner for both NUMA nodes.

**Comment by JerichoJones** [comment]
"So if I mine on 2 physical cores of a Xeon CPU, then run a 2 phys core miner instance to fill all the cores. I get about 10-15% more hashes. "

I'm not sure what you mean here. Are you mixing terms (sockets and cores)?

Dual socket, Xeon x5650 6 core, 12 thread CPU
All 12 phys cores: 479H/s
6 phys cores, 2 instances: 486H/s

**Comment by vans163** [comment]
1 instance of the miner on 1 NUMA node (8 phys cores, SMT disabled)
55 hashes per core so 440 hashes total.

4 instances of the miner on the same NUMA node. 
Each miner has affinity set for 2 cores
miner1 -> 0,1
miner2 -> 2,3
miner3-> 4,5
miner4-> 6,7
67 hashes per core, 134 hashes per miner, 536 hashes total.

**Comment by psychocrypt** [comment]
it is an interesting opservation please provide the output of `cat
/proc/cpuinfo`

**Comment by vans163** [comment]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
stepping        : 4
microcode       : 0x416
cpu MHz         : 3099.906
cache size      : 25600 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 5600.17
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by JerichoJones** [comment]
Windows 10 x64
Dual Xeon x5650
64 GB RAM
NUMA Enabled
SMT Enabled

1 instance of STAK on node1 only (--noUAC --noNVIDIA --noAMD )
miner1 -> 0,2,4,6,8,10
~40H/s per thread on Node1

1 instance of STAK on per node (--noUAC --noNVIDIA --noAMD )
miner1 -> 0,2,4,6,8,10
miner1 -> 12,14,16,18,20,22

~40H/s per thread on Node1
~38H/s per thread on Node2

6 instances of STAK  across both nodes (--noUAC --noNVIDIA --noAMD )
12 threads
miner1 -> 0,2
miner2 -> 4,6
miner3-> 8,10
miner4-> 12,14
miner5 -> 16,18
miner6 -> 20,22

~40H/s per thread

Let me know if you want me to try something specific.

**Comment by vans163** [comment]
This seems to only happen if the processor is not fully loaded.  It seems I made a mistake testing.
