### ISSUE TITLE
Option to choose server ip/dns

### ISSUE THREAD

**Issue by mojimi** [fireice-uk/xmr-stak#542]
Please give us a option to change the server ip/dns from "localhost" to one of our choices.

This is usefull not only in high scale mining, but in your home intranet as you can access your pc by its domain name, instead of the dynamic ip address.

For example you could run your server on "http://MyPcName:80" and in your smartphone connected in the same network you could just acces it by "MyPcName/"

On a side note, I couldn't find where can I manually change this in the binaries, if someone could point to it that would be nice.

**Comment by JerichoJones** [comment]
I just tested using the http://hostname to connect and it works fine for me v2.1. Maybe I'm misunderstanding what you are trying to do. I certainly don't understand how you would connect using "MyPcName/".

![image](https://user-images.githubusercontent.com/13205729/34021724-564b529c-e109-11e7-964e-5d9d1102a87c.png)

**Comment by dcolley** [comment]
@mojimi I suspect you can solve this by running your own DNS server
I would, however, like the option to attach to a named ip address - e.g. where I have a machine with 2 cards

**Comment by mojimi** [comment]
@JerichoJones "MyPcName/" is the same as http://MyPcName, you use your machine name as your IP in your local network, so you can bypass dynamic IPs assigned by your modem

**Comment by JerichoJones** [comment]
@mojimi I think @dcolley is probably correct.
