### ISSUE TITLE
Constantly dropping at etn.nanopool

### ISSUE THREAD

**Issue by SirLouen** [fireice-uk/xmr-stak#546]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU: Xeon X5675

# Stability issue
  - Is the CPU overclocked/underclocked? No

I've tested with both 2.1 and 2.0 and the same issue: Constant drops in nanopool with this miner. I've been also testing SGMiner and no drops at all. So it's obviously a specific issue of XMR-Stak

I'm currently mining at etn.nanopool.org and receive an email every hour with a drop connection. 

Don't know how to debug this issue.

CONNECTION REPORT
Pool address    : etn-eu1.nanopool.org:13333
Connected since : 2017-12-13 21:22:33
Pool ping time  : 59 ms

Network error log:
Yay! No errors.

RESULT REPORT
Difficulty       : 120001
Good results     : 118 / 119 (99.2 %)
Avg result time  : 627.7 sec
Pool-side hashes : 14160118

Error details:
| Count | Error text                       | Last seen           |
|     1 | Block expired                    | 2017-12-14 15:16:25 |

Just 1 Block expired out of 119 in this last session. 

cpu.txt config:

"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },

],

config.txt:

"pool_order" : "failover",
"pool_list" :
[
	{"pool_address" : "etn-eu1.nanopool.org:13333", "wallet_address" : "public_key.cpu/my-email", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 2 },
	{"pool_address" : "etn-eu2.nanopool.org:13333", "wallet_address" : "public_key.cpu/my-email", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],
"currency" : "monero",
"call_timeout" : 10,
"retry_time" : 30,
"giveup_limit" : 0,
"verbose_level" : 3,
"print_motd" : true,
"h_print_time" : 60,
"aes_override" : null,
"use_slow_memory" : "warn",
"tls_secure_algo" : true,
"daemon_mode" : false,
"flush_stdout" : false,
"output_file" : "",
"httpd_port" : 0,
"http_login" : "",
"http_pass" : "",
"prefer_ipv4" : true,

**Comment by anhphan** [comment]
It's seem xmr-stak will drop connection if cannot find a share within 10 minutes, I also see that when mining with nanopool. Just reduce `retry_time` to make it quick connect back or find a proxy to reduce diff of nanopool.

**Comment by SirLouen** [comment]
@anhphan or maybe the solution is to configure that connection drop when not finding a share for X minutes. Then it will be easier to set it up let's say @ 30 minutes or 60 minutes and this problem will be solved automatically.
