### ISSUE TITLE
Allow Ajax requests to JSON API

### ISSUE THREAD

**Issue by mojimi** [fireice-uk/xmr-stak#547]
At the moment AJAX requests to the JSON API get the cross-origin policy error, which makes it difficult to develop web-based monitors on top of it.

Please add this feature as specified in this reddit post https://www.reddit.com/r/MoneroMining/comments/7js7qy/how_to_use_xmrstaks_json_api/dr8vu9i/

**Comment by HazCod** [comment]
Specifically, the following headers should be added:
```
Allow-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
```

**Comment by HazCod** [comment]
Errr .. @fireice-uk .. you could at least mention why this gets closed.
