### ISSUE TITLE
Bitdefender -  Xmr-stak Win64  Trojan virus

### ISSUE THREAD

**Issue by StiiCeva** [fireice-uk/xmr-stak#552]
I can't use it anymore Bitdefender and AMSI  on windows 10 blocks it. 

Does it have a virus? 

If not, any workaorunds?

**Comment by DavidBruchmann** [comment]
You've to add it to the virus-protection-programs' white-lists.
It won't harm your system if downloaded here from the original repository.

**Comment by StiiCeva** [comment]
Yes! Added it everywhere .... do not scan on execute, do not scan on access.... 

I think it's the F*****g Microsoft Update with the AMSI (something about advanced malware scan and inspect) up your ass.

**Comment by DavidBruchmann** [comment]
If you never recovered it it might be still in quarantine or deleted.
Check if the files still exist.

**Comment by StiiCeva** [comment]
I recovered it, but it get's blocked from running.

**Comment by DavidBruchmann** [comment]
https://support.microsoft.com/en-au/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus

https://thinksmartbox.com/answer/how-to-configure-exceptions-for-microsoft-security-essentialswindows-defender/

https://www.bitdefender.com/support/how-to-add-exclusions-(exceptions)-in-bitdefender-2016-1467.html

**Comment by DavidBruchmann** [comment]
https://stackoverflow.com/questions/40888849/windows-defender-antivirus-scan-from-c-sharp-accessviolation-exception

Despite the accepted answer (green check) on that page I never have the problem as I use another virus-scanner.

**Comment by JerichoJones** [comment]
Once a I added it as an exclusion in Windows Defender (STAK on multiple machines) I have not had a problem.

Not sure how we can help further.

**Comment by zr26060** [comment]
Bitdefender total 2018 :  1 - add exclusion xmr-stak.exe  in " advanced threat defense "
                                        2 - add exclusion xmr-stak.exe  in " safe files "

**Comment by StiiCeva** [comment]
Back, sorry for the delay. 

Did everything you mentioned - nothing worked. 

Had to disable realtime protection and from Settings > General > Antimalware Scan Service. 

AND add the folder to exceptions. 


Hope this helps other! Cheers!

**Comment by maxkaplan** [comment]
I'm getting a Vigorf.A warning from Windows Defender. 

![image](https://user-images.githubusercontent.com/200634/34507949-cc2c23d4-efef-11e7-8687-4fdda4d532f0.png)
