### ISSUE TITLE
Memory INIT ERROR:

### ISSUE THREAD

**Issue by sthanh** [fireice-uk/xmr-stak#553]
Hi there,
Anyone seen this error before? I tried to use the new version and the computer froze after 20 minutes of mining. Any help would be appreciated.

Thanks!!!

![capture](https://user-images.githubusercontent.com/3734322/34018240-d30cc878-e0dd-11e7-8157-dbc6c6f30a66.PNG)

**Comment by JaredRCooper** [comment]
I have this same error, but it doesn't seem to be effecting the miner.  But I can't edit my config file for my wallet address.  Any idea?

**Comment by JerichoJones** [comment]
Try running as Administrator once and reboot so Large Pages can be set.
This screenshot would leave me to believe that it froze right away. We would need a screenshot of the windows at the time of the error and or logs.

Enable logs in the config.txt
/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

**Comment by fireice-uk** [comment]
Memory init error is due to the miner not being able to set up large pages, see the config.txt for documentation on that. Hanging is a separate issue - usually caused by amd driver or the card overheating.
