### ISSUE TITLE
Linux Portbin for Releases

### ISSUE THREAD

**Issue by camisatx** [fireice-uk/xmr-stak#555]
Thanks @psychocrypt and @fireice-uk for a great piece of software! I really like what you are doing with xmr-stak.

I've noticed that neither the 2.1.0 nor the 2.0.0 release include the `xmr-stak-portbin-linux.tar.gz` file anymore.

Is it possible for you to add it back? This really makes it easier when adding the miner to a new system, especially since compiling the code is more error-prone.

Thanks for your time, and keep up the fantastic work!

**Comment by OldenGit** [comment]
See https://github.com/fireice-uk/xmr-stak/issues/524

Binary was removed due to issues. Not idea what issues though. :)

**Comment by camisatx** [comment]
Doh! I obviously didn't look down the open issues enough.

I'll close this issue so related discussions can remain in #524. :)
