### ISSUE TITLE
Suggestion "Idle mode"

### ISSUE THREAD

**Issue by Lowerman** [fireice-uk/xmr-stak#556]
it would be interesting an option for low cpu usage ..

**Comment by eeglitis** [comment]
Exactly. I was thinking today. How great it would be that mining starts when the computer is idle when there is no user input. When computer users go for a lunch/smoke breaks or leave computer on overnight. I could push miners to thousands of computers..

**Comment by fireice-uk** [comment]
> I could push miners to thousands of computers..

Sorry mate, but we are not really interested in making botnet tools.
