### ISSUE TITLE
Hwloc: Memory Pinned.

### ISSUE THREAD

**Issue by syncacide** [fireice-uk/xmr-stak#557]
Please provide as much as possible information to reproduce the issue.

Hwloc: Memory Pinned. miner will run for a short amount of time with 7700-7900 h/s eventurally is will freeze and windows crashes to blue screen and then restarts.

# Basic information
  - intel 4400
  - 1 vega 56 flashed to 64, 3x vega 64
   - 8g of DD4 2133 MHz (2x 4gb stick)
   -120g ssd

# Compile issues
  Windows 10
 
/*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool 
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */
"pool_list" :
[
	{"pool_address" : "pool.supportxmr.com:7777", "wallet_address" : "4BHg3KsmxZkWJTKpG53huM4eSutiuoZMXBigxEDwNeD7KuC6UiW6UJDQMYLMQXSWpgK3Ew3MQ4gW8UbskwubecNaDMDuySu", "pool_password" : "x", "use_nicehash" : false, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * currency to mine
 * allowed values: 'monero' or 'aeon'
 */
"currency" : "monero",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make 
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for 
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 30,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0 - Don't print anything.
 *                 1 - Print intro, connection event, disconnect event
 *                 2 - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3 - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4 - All of level 3, and automatic hashrate report printing
 *
 * print_motd    - Display messages from your pool operator in the hashrate result.
 */
"verbose_level" : 3,
"print_motd" : true,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 60,

/*
 * Manual hardware AES override
 *
 * Some VMs don't report AES capability correctly. You can set this value to true to enforce hardware AES or
 * to false to force disable AES or null to let the miner decide if AES is used.
 *
 * WARNING: setting this to true on a CPU that doesn't support hardware AES will crash the miner.
 */
"aes_override" : null,

/*
 * LARGE PAGE SUPPORT
 * Large pages need a properly set up OS. It can be difficult if you are not used to systems administration,
 * but the performance results are worth the trouble - you will get around 20% boost. Slow memory mode is
 * meant as a backup, you won't get stellar results there. If you are running into trouble, especially
 * on Windows, please read the common issues in the README.
 *
 * By default we will try to allocate large pages. This means you need to "Run As Administrator" on Windows.
 * You need to edit your system's group policies to enable locking large pages. Here are the steps from MSDN
 *
 * 1. On the Start menu, click Run. In the Open box, type gpedit.msc.
 * 2. On the Local Group Policy Editor console, expand Computer Configuration, and then expand Windows Settings.
 * 3. Expand Security Settings, and then expand Local Policies.
 * 4. Select the User Rights Assignment folder.
 * 5. The policies will be displayed in the details pane.
 * 6. In the pane, double-click Lock pages in memory.
 * 7. In the Local Security Setting – Lock pages in memory dialog box, click Add User or Group.
 * 8. In the Select Users, Service Accounts, or Groups dialog box, add an account that you will run the miner on
 * 9. Reboot for change to take effect.
 *
 * Windows also tends to fragment memory a lot. If you are running on a system with 4-8GB of RAM you might need
 * to switch off all the auto-start applications and reboot to have a large enough chunk of contiguous memory.
 *
 * On Linux you will need to configure large page support "sudo sysctl -w vm.nr_hugepages=128" and increase your
 * ulimit -l. To do do this you need to add following lines to /etc/security/limits.conf - "* soft memlock 262144"
 * and "* hard memlock 262144". You can also do it Windows-style and simply run-as-root, but this is NOT
 * recommended for security reasons.
 *
 * Memory locking means that the kernel can't swap out the page to disk - something that is unlikely to happen on a
 * command line system that isn't starved of memory. I haven't observed any difference on a CLI Linux system between
 * locked and unlocked memory. If that is your setup see option "no_mlck".
 */

/*
 * use_slow_memory defines our behaviour with regards to large pages. There are three possible options here:
 * always  - Don't even try to use large pages. Always use slow memory.
 * warn    - We will try to use large pages, but fall back to slow memory if that fails.
 * no_mlck - This option is only relevant on Linux, where we can use large pages without locking memory.
 *           It will never use slow memory, but it won't attempt to mlock
 * never   - If we fail to allocate large pages we will print an error and exit.
 */
"use_slow_memory" : "warn",

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel.
 *
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 */
"tls_secure_algo" : true,

/*
 * Daemon mode
 *
 * If you are running the process in the background and you don't need the keyboard reports, set this to true.
 * This should solve the hashrate problems on some emulated terminals.
 */
"daemon_mode" : false,

/*
 * Buffered output control.
 * When running the miner through a pipe, standard output is buffered. This means that the pipe won't read
 * each output line immediately. This can cause delays when running in background.
 * Set this option to true to flush stdout after each line, so it can be read immediately.
 */
"flush_stdout" : false,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * HTTP Authentication
 *
 * This allows you to set a password to keep people on the Internet from snooping on your hashrate.
 * Keep in mind that this is based on HTTP Digest, which is based on MD5. To a determined attacker
 * who is able to read your traffic it is as easy to break a bog door latch.
 *
 * http_login - Login. Empty login disables authentication.
 * http_pass  - Password.
 */ 
"http_login" : "",
"http_pass" : "",
 
/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,

  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 false = use a contiguous block of memory per thread
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
 * ],
 */

"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 0, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 1, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 1, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 2, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 2, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 3, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
    { "index" : 3, "intensity" : 1925, "worksize" : 8, "affine_to_cpu" : 0, "strided_index" : true },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

/*
 * Thread configuration for each thread. Make sure it matches the number above.
 * low_power_mode - This can either be a boolean (true or false), or a number between 1 to 5. When set to true,
                    this mode will double the cache usage, and double the single thread performance. It will 
 *                  consume much less power (as less cores are working), but will max out at around 80-85% of 
 *                  the maximum performance. When set to a number N greater than 1, this mode will increase the
 *                  cache usage and single thread performance by N times.
 *
 * no_prefetch -    Some sytems can gain up to extra 5% here, but sometimes it will have no difference or make
 *                  things slower.
 *
 * affine_to_cpu -  This can be either false (no affinity), or the CPU core number. Note that on hyperthreading 
 *                  systems it is better to assign threads to physical cores. On Windows this usually means selecting 
 *                  even or odd numbered cpu numbers. For Linux it will be usually the lower CPU numbers, so for a 4 
 *                  physical core CPU you should select cpu numbers 0-3.
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 * 
 * A filled out configuration should look like this:
 * "cpu_threads_conf" :
 * [ 
 *      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
 *      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
 * ],
 */

"cpu_threads_conf" :
[
//    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },

],

[2017-12-15 01:40:53] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-12-15 01:40:53] : WARNING: backend NVIDIA disabled.
[2017-12-15 01:40:53] : Compiling code and initializing GPUs. This will take a while...
[2017-12-15 01:40:53] : Device 0 work size 8 / 32.
[2017-12-15 01:40:58] : Device 0 work size 8 / 32.
[2017-12-15 01:41:03] : Device 1 work size 8 / 32.
[2017-12-15 01:41:08] : Device 1 work size 8 / 32.
[2017-12-15 01:41:13] : Device 2 work size 8 / 32.
[2017-12-15 01:41:18] : Device 2 work size 8 / 32.
[2017-12-15 01:41:23] : Device 3 work size 8 / 32.
[2017-12-15 01:41:28] : Device 3 work size 8 / 32.
[2017-12-15 01:41:33] : Starting AMD GPU thread 0, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 1, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 2, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 3, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 4, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 5, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 6, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting AMD GPU thread 7, affinity: 0.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:33] : Starting 1x thread, affinity: 1.
[2017-12-15 01:41:33] : hwloc: memory pinned
[2017-12-15 01:41:59] : Result accepted by the pool.
[2017-12-15 01:42:25] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   57.5 |   (na) |   (na) |
---------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  851.1 |   (na) |   (na) |  1 |  862.1 |   (na) |   (na) |
|  2 |  982.5 |   (na) |   (na) |  3 |  987.2 |   (na) |   (na) |
|  4 |  994.1 |   (na) |   (na) |  5 |  980.4 |   (na) |   (na) |
|  6 |  990.5 |   (na) |   (na) |  7 |  988.6 |   (na) |   (na) |
-----------------------------------------------------
Totals:   7694.0   (na)   (na) H/s
Highest:  7756.3 H/s
[2017-12-15 01:42:32] : Result accepted by the pool.

# Stability issue
  - GPU 1100hz power tables, cpu no overclocked
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by JeffBarrowbank** [comment]
I also got HWLOC:MEMORY PINNED issue

[2017-12-15 17:54:24] : Starting 1x thread, affinity: 22.
[2017-12-15 17:54:24] : hwloc: memory pinned
[2017-12-15 17:54:24] : Fast-connecting to pool.electroneum.space:3333 pool ...
[2017-12-15 17:56:34] : SOCKET ERROR - [pool.electroneum.space:3333] CONNECT error: Connection timed 
out

Followed the Large pages recommendations on Lubunto 16 LTS. Tried everything I can think of to change the settings etc. Cannot get the miner to work.

**Comment by JerichoJones** [comment]
**"hwloc: memory pinned" is not an error. It indicates that the memory was successfully reserved.**

@syncacide Not every card wins the silicon lottery. Lower clocks and/or Intensity until it stabilizes. You may have different settings per card.
