### ISSUE TITLE
OpenCL 2.0 not found when CUDA is installed

### ISSUE THREAD

**Issue by Mattthev** [fireice-uk/xmr-stak#56]
When I have only AMD SDK installed and disabled NVIDIA backend or compile XMR-STAK-AMD it has no problem detect OpenCL 2.0, but with CUDA 9 installed it only find 1.2 version.
```
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib (found version "1.2")
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
```

**Comment by psychocrypt** [comment]
There is no need to use OpenCL 2.0.

**Comment by fireice-uk** [comment]
@psychocrypt I get the same error. This is relevant because CMake goes after the NVIDIA's OpenCL lib and not AMD's even though `AMDAPPSDKROOT=C:\Program Files (x86)\AMD APP SDK\3.0\`  is set,

**Comment by psychocrypt** [comment]
Could you test to set CMAKE_PREFIX_PATH to amd app sdk.
Else we can try to change the order in cmake, that we first search for
opencl and than cuda.

**Comment by psychocrypt** [comment]
note to myself: https://stackoverflow.com/a/44955868 could be the solution.

**Comment by Mattthev** [comment]
I've tried change the order, same problem only before CUDA search.

**Comment by psychocrypt** [comment]
@Mattthev Could you please try #63, it could be that you need to set the environment variable `OpenCL_ROOT` or `AMDAPPSDKROOT` but hopefully it works without the hints.

**Comment by Mattthev** [comment]
It's working great, thanks. Should I close this issue now?

**Comment by psychocrypt** [comment]
We close it after the PR is merged. Thx for testing and opening the issue.
