### ISSUE TITLE
GPU AMD remain at 100%

### ISSUE THREAD

**Issue by Salvo52** [fireice-uk/xmr-stak#561]
Hello,
I have ryzen 1700x and rx580 which mining on both with original xmr stak v2.1 on win10 64bits.
Before i was on driver 17.11 and when i closed the miner the GPU and cpu turned at 0%. Since i installed the new driver 17.12, the GPU remain at 100%, the cpu is ok.

**Comment by JerichoJones** [comment]
To clarify: When you close XMR-STAK you GPU still show 100% utilization?
Can you verify if some other process has grabbed the GPU?

**Comment by Salvo52** [comment]
Yes, that's it. I think it's driver AMD adrenalin. I don't know how check which process use the GPU.

**Comment by Salvo52** [comment]
I am cheating to stop 100% use or gpu, in the driver AMD adrenalin, i switch graphics to calcul, that's stopped the driver and it relaunch them.
