### ISSUE TITLE
Windows miner crashing instantly after start

### ISSUE THREAD

**Issue by BlackGrimReaper** [fireice-uk/xmr-stak#563]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Ryzen 7 1700
  - windows 10

# Issue

Hello,
I"ve already downloaded the miner 3 times but every time i try to start the miner (double clicking the xmr-stak.exe not filling mining details and start) it instantly close down, just a pop-up of some border of window and boom gone. Every antivirus, windows defender, firewall is disabled. any help?

# Update 
Now that i noticed I'm having same problem with every xmr miner even wolf miner is closing down as soon as i start it.

**Comment by veridicis** [comment]
Remove the cuda and opencl .dll files from the directory and try again, what do you get?

**Comment by BlackGrimReaper** [comment]
still same problem. instantly closing...

**Comment by veridicis** [comment]
Are you running as admin user?

**Comment by BlackGrimReaper** [comment]
Ran as administrator.... Still same Problem
VS libraries are also installed (re-downloaded the program for confirmation) Still same  problem

**Comment by veridicis** [comment]
Output log to file and see the results

**Comment by BlackGrimReaper** [comment]
where is the log file?

**Comment by BlackGrimReaper** [comment]
or how to get one?

**Comment by KnoAll** [comment]
I had basically this same issue. after moving out the dlls mentioned it is running great in just CPU mode.

**Comment by psychocrypt** [comment]
use the terminal command line. goto the folder with the binary and run
`xmr-stak --noUAC` than the error will be shown in the terminal window.

**Comment by BlackGrimReaper** [comment]
This is what I'm getting...
![screenshot 8](https://user-images.githubusercontent.com/26975750/34078410-df7b386a-e33f-11e7-850a-19be7a68c86b.png)

**Comment by psychocrypt** [comment]
could it be that your anti virus software is blocking the miner somehow.
Your folder also not contains the miner dll files.

**Comment by BlackGrimReaper** [comment]
veridices told me to remove cuda and opencl dll files from the folder. and antivirus and windows defender are not running at all.

**Comment by BlackGrimReaper** [comment]
issue resolved... comodo firewall was causing the problem........
