### ISSUE TITLE
Are the .lib files needed/helpful after build?

### ISSUE THREAD

**Issue by Makanar** [fireice-uk/xmr-stak#564]
Google was not helpful with this question, probably because it is silly to anyone who understands it. Are the xmr-stak-backend.lib and xmr-stak-c.lib files helpful/needed once it is built? xmr-stak.exe appears to run without issue without those files.

Note: I built with -DMICROHTTPD_ENABLE=OFF -DXMR-STAK_CURRENCY=monero -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF

**Comment by JerichoJones** [comment]
They are not needed to run XMR-STAK
