### ISSUE TITLE
Compile error with cuda-9.1.85-1 : "device_functions.hpp not found"

### ISSUE THREAD

**Issue by Furinkazan33** [fireice-uk/xmr-stak#569]
On Archlinux, i got an error when compiling with the latest version of cuda (cuda-9.1.85-1).

Fixed by changing in cuda_extra.cu
#include <device_functions.hpp>
to
 #include <device_functions.h>

Here the trace :

xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu:9:32: erreur fatale: device_functions.hpp : Aucun fichier ou dossier de ce type
 #include <device_functions.hpp>
                                ^
compilation terminée.
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
  /home/xxx/xxx/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:72: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by psychocrypt** [comment]
fixed with #532
