### ISSUE TITLE
Can you use AMD and NVidia in same box?

### ISSUE THREAD

**Issue by markdjones82** [fireice-uk/xmr-stak#570]
Please provide as much as possible information to reproduce the issue.
I am looking to buy an additional card and see AMD seems to perform better.  Can I run NVidia and AMD?

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).
GTX 1060 
AMD RX 580

# Compile issues
  - Which OS do you use?
  Windows 10
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by psychocrypt** [comment]
Yes it is possible. On which OS.?

**Comment by markdjones82** [comment]
I will be using Windows 10 do I just need to have drivers for both installed?

On Dec 15, 2017 4:33 PM, psychocrypt <notifications@github.com> wrote:
Yes it is possible. On which OS.?

**Comment by JerichoJones** [comment]
I do it on Windows 10.
Yes, you need both drivers installed.
