### ISSUE TITLE
Hashrate reduced on one gpu after adding another

### ISSUE THREAD

**Issue by anarchonist** [fireice-uk/xmr-stak#572]
Hey guys just recently started mining, love what you guys are doing. I've spent the last two days reading everything on this project page and I'm amazed at how you two guys are supporting this application.

I'm using version 2.1.0 on Win 10. I used it all day yesterday with my GTX960 4gb and was getting average 300 H/s with lots of fluctuation. I thought that was cool so I added a GTX 1050ti 4gb to my system.

After install of the card I updated/verified all the drivers with Geforce Experience. Then I deleted the nvidia.txt and let it generate a new one. Now my 1050ti is getting a consistent 314 H/s, but my 960 dropped down to a consistent 101 H/s. One thing I thought was odd is that my 960 was index 0 when it was alone, but now its index 1, but its still in the same slot.

I messed around with the config for the 960 but any change in threads results in application crash. I have windows 10 home so I can't change the lock page GPO. I do have 32 GB Ram though and most available. Running as admin has no apparent affect on H/s, getting no errors either way.

Both GPU's are stock with no overclocking yet.

My i7-6700k seems to be performing wonderfully, I'm getting over 70 H/s per core (4) consistently.

Any idea how to maximize this output?

**Comment by JerichoJones** [comment]
Are you using the same setup for the 960 as prior when you were getting 300H/s?
The index order is determined by the driver. I don't know what magic it uses to pick an index.
I would think it would start indexing based on slot order (lower numbered slot = lower index) but I do not know.
Try the NVIDIA forums. If you get an answer I would be very interested to know as well!

**Comment by anarchonist** [comment]
Exact same setup, literally the only thing I changed was installing the 1050 in the next available slot.

**Comment by anarchonist** [comment]
Yep I did that before first run after installing card.

**Comment by JerichoJones** [comment]
[How to Install and Enable “Group Policy Editor” (gpedit.msc) in Home Edition](https://www.askvg.com/how-to-enable-group-policy-editor-gpedit-msc-in-windows-7-home-premium-home-basic-and-starter-editions/)
