### ISSUE TITLE
Unable to compile in CentOS 7

### ISSUE THREAD

**Issue by Dimitri2g** [fireice-uk/xmr-stak#574]
Trying to compile for CentOS 7 using CPU.

Has anyone had success with this and if you have can you provide the exact steps as the instructions at https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md do not work for me. 

If you have step by step instructions on what you did to get it to work successfully from start to finish that would be greatly appreciated.

**Comment by zagman76** [comment]
I am also facing this problem.  The error I keep getting is:
```
[root@mon-tester1 build]# cmake3 ..
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
See also "/home/xmr-stak/CMakeFiles/CMakeOutput.log".

[root@mon-tester1 build]# g++ --version
g++ (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by NmxMilk** [comment]
@zagman76 try this.
Do not overwrite CMAKE_C_COMPILER, but export CC (and CXX) before calling cmake as:
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++

adapt to reflect your real path

**Comment by NmxMilk** [comment]
@Dimitri2g I installed devtoolset-6 instead of devtoolset-4
Steps in the readme worked fine for me.
Maybe, you give more details on errors your having ?

**Comment by zagman76** [comment]
@NmxMilk 

I think I did this correctly:

```
[root@mon-tester1 build]# export CC=/usr/bin/gcc
[root@mon-tester1 build]# export CXX=/usr/bin/g++
[root@mon-tester1 build]# cmake3 ..
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
See also "/home/xmr-stak/CMakeFiles/CMakeOutput.log".
```

**Comment by Dimitri2g** [comment]
I got it to build. I ran the commands below:

sudo yum install centos-release-scl epel-release
sudo yum install cmake3 devtoolset-7-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make
sudo scl enable devtoolset-7 bash
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake3  -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..
make install

deploy a new centos box and did my updates and everything and issued the commands mentioned about and now i have xmr-stak compiled and working finally.

**Comment by Dimitri2g** [comment]
Before i close this does anything know how i can keep xmr-stak up and running in centos? After i end my terminal session it seems to die and if you can provide some instructional steps or a push in the right direction that would be appreciated. Cheers.

**Comment by psychocrypt** [comment]
please check
https://github.com/fireice-uk/xmr-stak/blob/master/scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
there is also an example for centos.

**Comment by NmxMilk** [comment]
@zagman76 Did you delete cmake cache before retrying ?
If not delete all in your build dir and retry.

**Comment by zagman76** [comment]
@NmxMilk -- I tried that, and it still didn't work.  

However, I wiped and re-installed CentOS from scratch, following the steps that @Dimitri2g used above:

```
sudo yum install centos-release-scl epel-release
sudo yum install cmake3 devtoolset-7-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make
sudo scl enable devtoolset-7 bash
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake3 -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..
make install
```

And that worked.  Strange, but the ends result is what I was looking for.

**Comment by Dimitri2g** [comment]
Before i close this does anything know how i can keep xmr-stak up and running in centos? After i end my terminal session it seems to die and if you can provide some instructional steps or a push in the right direction that would be appreciated. Cheers.

**Comment by nueverest** [comment]
I'm having this same issue after I install the CUDA driver from Nvidia.  Nvidia seems to change gcc to 4.8 even though I explicitly installed `devtoolset-7-gcc*`.

**Comment by Jany-M** [comment]
I still can't get it to build, it's driving me nuts.
```
CMake Error at CMakeLists.txt:36 (message):
  g++ version must be at least 5.1!
```

```
[root@yw28-5hhq build]# which cmake
/usr/local/bin/cmake
[root@yw28-5hhq build]# cmake --version
cmake version 3.6.2
[root@yw28-5hhq build]# which make
/opt/rh/devtoolset-7/root/usr/bin/make
[root@yw28-5hhq build]# make --version
GNU Make 4.2.1
[root@yw28-5hhq build]# which g++
/opt/rh/devtoolset-7/root/usr/bin/g++
[root@yw28-5hhq build]# g++ --version
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
```
Help? :(

**Comment by psychocrypt** [comment]
configure the environment before the compile

export CXX=/opt/rh/devtoolset-7/root/usr/bin/g++
export CC=/opt/rh/devtoolset-7/root/usr/bin/gcc

run now cmake

please remove all files in the build folder before else cmake will not
search for the compiler
