### ISSUE TITLE
Ubuntu Mate 16.04 64 Bit - OpenCL - WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms

### ISSUE THREAD

**Issue by JokerGermany** [fireice-uk/xmr-stak#576]
# Basic information
Intel(R) Core(TM) i3 CPU         550
AMD Radeon RX 580 8GB
Ubuntu Mate 16.04 64 Bit.

# AMD OpenCl issue
  ```
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Abgebrochen (Speicherabzug geschrieben)
  ```

```
[2017-12-16 09:36:29] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2017-12-16 09:36:29] : WARNING: No OpenCL platform found.
[2017-12-16 09:36:29] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-16 09:36:29] : WARNING: backend AMD disabled.
```

I Installed the AMD-APP-SDK 3 and amdgpu-pro-17.50-511655

**Comment by psychocrypt** [comment]
please try to run `clinfo` but I think that you have driver issues.

**Comment by JokerGermany** [comment]
```
terminate called after throwing an instance of 'cl::Error'
what():  clGetPlatformIDs
Abgebrochen (Speicherabzug geschrieben)
```
how can i solve the issue?

**Comment by psychocrypt** [comment]
please provide how you generate the error message. do you run clinfo?
Please do notnonly post the error message we need also what you did.

**Comment by JokerGermany** [comment]
Yeah, thats the output of clinfo

**Comment by unixworker** [comment]
Hi guys, i am having the exact same issue!
On 17.10 Ubuntu i cannot manage to get the AMD Driver working. So i switched to 16.04.03.

On 16.04.03 with newest updates and the latest AMD GPU PRO Driver (17.50) i am having the exact same output from clinfo. Xmr stak also does not recognize the gpu and says that opencl is not found.

Now, changing to 17.30 AMD GPU driver lets xmr stak start and recognize the gpu BUT Ubuntu is then crashing on bootup with a black screen (several entries on google for that issue). 

I am really tired of trying since i have installed ubuntu several times with different versions now.
Any suggestion for a better distribution to run xmr-stak with RX 560 and Ryzen 1700?

Fedora hat the same issue, since opencl would not work and the amd-gpu driver is only available for rhel/ubuntu.

**Comment by psychocrypt** [comment]
sry I can not help help with driver issues because this is very system
specific. As long as clinfo is not working the miner can not be used.
try to find help on ubuntuusers or other forum platforms for you
distribution

**Comment by JokerGermany** [comment]
@unixworker 
The 17.30 driver don't work with 16.04.**3**
Do you tried the 17.40?
If this work i will use it too XD

**Comment by unixworker** [comment]
@Joker: No i have not tried that.
Although AMD admits that there were several problems related to use with Ubuntu they claim that in 17.50 most issues should be resolved.

With 17.50 the system seems to be running and the black screen on bootup is fixed BUT opencl does not work properly.

**Comment by unixworker** [comment]
@psychocrypt : Do you have any suggestions for a Linux distro that is running properly with AMD gpu?
Or is everyone using windows here...?

**Comment by JokerGermany** [comment]
Ok i installed 17.40 and it can mine thats enough for me for the moment

**Comment by psychocrypt** [comment]
Amd driver are a pian but I hope with the future investigations of amd to
unify windows and linux driver more and more it will be easier to use the
gpus.

**Comment by unixworker** [comment]
@JokerGermany : Can you tell me exactly how you managed that?
I am getting a "System running in low-graphics mode" error on boot up.

So you have Ubuntu 16.04.04 installed. 
Then you do a full system update as mentioned in the amd manual.
Then you install the graphics driver.

Then you install AMD APPSKD 3.xx (newest version available) 
After this you install xmr?

**Comment by JokerGermany** [comment]
I compiled xmr-stak with an the intel graphics and the amd appskd 3.
Then i got the graphics card and installed 17.40.

BUT I use the intel graphics for the output!
The AMD card ist for mining.

**Comment by unixworker** [comment]
Ah, i see. 
Some say that running amdgpu pro together with appskd is nonsense since these packages do not work together and it is not supported by amd.
Instead one should use opencl from the amdgpu pro driver package.

It is a real pity so many people have problems with this setup...
