### ISSUE TITLE
Only CPU is mining. Nvidia GPU. No affinity error

### ISSUE THREAD

**Issue by iogres** [fireice-uk/xmr-stak#578]
I installed latest driver and latest CUDA. I added my results. Actually, according to hashrate report, my GPU is working, but hashrate is very small, I guess. Also, at the beginning, the program gives warning as you can see from text below.

Also, Highest is 0.0 H/s in hashrate report. I couldn't understand it. 

# Basic information
  - Type of the CPU. i7-4710MQ
  - Type of the GPU (if you try to miner with the GPU). NVIDIA GTX 950M

# Compile issues
  - Which OS do you use? Windows 10 x64

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

Results

> `[2017-12-16 16:15:02] : Start mining: MONERO
[2017-12-16 16:15:02] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-16 16:15:03] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-16 16:15:03] : WARNING: backend AMD disabled.
[2017-12-16 16:15:03] : Starting 1x thread, affinity: 0.
[2017-12-16 16:15:03] : hwloc: memory pinned
[2017-12-16 16:15:03] : Starting 1x thread, affinity: 2.
[2017-12-16 16:15:03] : hwloc: memory pinned
[2017-12-16 16:15:03] : Starting 1x thread, affinity: 4.
[2017-12-16 16:15:03] : hwloc: memory pinned
[2017-12-16 16:15:03] : Fast-connecting to xmrpool.eu:5555 pool ...
[2017-12-16 16:15:03] : Pool xmrpool.eu:5555 connected. Logging in...
[2017-12-16 16:15:03] : Difficulty changed. Now: 25000.
[2017-12-16 16:15:03] : Pool logged in.
[2017-12-16 16:15:03] : Difficulty changed. Now: 25000.
[2017-12-16 16:15:03] : New block detected.
[2017-12-16 16:15:41] : Difficulty changed. Now: 10000.
[2017-12-16 16:15:41] : New block detected.
[2017-12-16 16:17:03] : New block detected.
[2017-12-16 16:17:43] : Result accepted by the pool.
[2017-12-16 16:20:28] : New block detected.
[2017-12-16 16:20:58] : Result accepted by the pool.
[2017-12-16 16:21:46] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   34.6 |   34.5 |   (na) |  1 |   33.2 |   31.0 |   (na) |
|  2 |   35.8 |   35.4 |   (na) |

HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |   (na) |   38.3 |   (na) |

Totals:     (na)  139.3   (na) H/s
Highest:     0.0 H/s`
> 

Nvidia.txt
```

/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 8, "bsleep" :  25, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 950M architecture: 50
  //      memory: 1688/2048 MiB
  //      smx: 5
  { "index" : 0,
    "threads" : 50, "blocks" : 15,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],


```

**Comment by JerichoJones** [comment]
You need to adjust your threads until you hit the sweet spot.

**Comment by iogres** [comment]
I tried several different configuration for threads, but it does't change anything.

**Comment by psychocrypt** [comment]
half the attribute threads in nvidia.txt

**Comment by iogres** [comment]
I still get "Starting NVIDIA GPU thread 0, no affinity." message at the beginning, but I tried "threads" : 16, "blocks" : 20, and I get 309 H/s in total, 153 H/s in GPU. 

Thank you @psychocrypt and @JerichoJones for your help. 

`HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   40.5 |   37.5 |   (na) |  1 |   42.1 |   38.2 |   (na) |
|  2 |   42.0 |   38.3 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  153.4 |  153.2 |   (na) |
---------------------------
Totals:    278.0  267.2   (na) H/s
Highest:   309.5 H/s`

**Comment by JerichoJones** [comment]
>"Starting NVIDIA GPU thread 0, no affinity."

Is not an error. You have not set affinity which is OK.
I don't think there is anything more we can do. Try REDDIT/r/MoneroMining
