### ISSUE TITLE
identifier "__float128" is undefined

### ISSUE THREAD

**Issue by trite2k3** [fireice-uk/xmr-stak#579]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
i7 7700K
  - Type of the GPU (if you try to miner with the GPU).
gtx980
gtx750ti

# Compile issues
  - Which OS do you use?
slackware
  ```
  add **all** commands you used and the **full** compile output here
  ```
cmake -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF .

/opt/xmr-stak# make install
[ 20%] Built target xmr-stak-c
[ 76%] Built target xmr-stak-backend
[ 80%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000064a8_00000000-23_cuda_extra.compute_62.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:279 (message):
  Error generating file
  /opt/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o

make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:400: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

  ```
  run `cmake -LA .` in the build folder and add the output here
  ```
/opt/xmr-stak# cmake -LA .
-- Set miner currency to 'monero' and 'aeon'
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/xmr-stak
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/opt/xmr-stak
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ARCH:STRING=30;35;37;50;52;20;60;61;62
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_COMPILER:STRING=nvcc
CUDA_CUDART_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcudart.so
CUDA_CUDA_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcuda.so
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_KEEP_FILES:BOOL=OFF
CUDA_NVCC_EXECUTABLE:FILEPATH=/usr/share/cuda/bin/nvcc
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=/usr/share/cuda/include
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/share/cuda
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=8.0
CUDA_cublas_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcublas.so
CUDA_cublas_device_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcublas_device.a
CUDA_cudadevrt_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcudadevrt.a
CUDA_cudart_static_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcudart_static.a
CUDA_cufft_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcufft.so
CUDA_cupti_LIBRARY:FILEPATH=/usr/share/cuda/extras/CUPTI/lib64/libcupti.so
CUDA_curand_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcurand.so
CUDA_cusolver_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcusolver.so
CUDA_cusparse_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libcusparse.so
CUDA_nppc_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libnppc.so
CUDA_nppi_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libnppi.so
CUDA_npps_LIBRARY:FILEPATH=/usr/share/cuda/lib64/libnpps.so
CUDA_rt_LIBRARY:FILEPATH=/usr/lib64/librt.so
HWLOC:FILEPATH=/usr/lib64/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MICROHTTPD_ENABLE:BOOL=OFF
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib64/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib64/libssl.so
OpenCL_ENABLE:BOOL=OFF
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all
XMR-STAK_LARGEGRID:BOOL=ON
XMR-STAK_THREADS:STRING=0

# Issue with the execution
  - Do you compiled the miner by our own?
yes
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
no
  - Is the Main memory of the CPU or GPU undervolted?
no

**Comment by psychocrypt** [comment]
which compiler do you use. please compile the miner in an empty build
folder and provide all cmake output and all commands.

**Comment by trite2k3** [comment]
cmake -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF .
make install

Tried with gcc 5.3.0 and 7.2.0. Both give above error.

**Comment by trite2k3** [comment]
root@darkstar:/opt# git clone https://github.com/fireice-uk/xmr-stak.git
Cloning into 'xmr-stak'...
remote: Counting objects: 3365, done.
remote: Total 3365 (delta 0), reused 0 (delta 0), pack-reused 3365
Receiving objects: 100% (3365/3365), 1000.52 KiB | 2.15 MiB/s, done.
Resolving deltas: 100% (2348/2348), done.
root@darkstar:/opt# cd xmr-stak/
root@darkstar:/opt/xmr-stak# ls
CI/  CMakeLists.txt  CONTRIBUTING.md  Dockerfile  LICENSE  README.md  THIRD-PARTY-LICENSES  doc/  scripts/  xmrstak/
root@darkstar:/opt/xmr-stak# vi xmrstak/donate-level.hpp 
reading xmrstak/donate-level.hpp

wrote xmrstak/donate-level.hpp, 18 lines, 823 chars
root@darkstar:/opt/xmr-stak# cmake .
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/share/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "2.1") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2n") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/xmr-stak
root@darkstar:/opt/xmr-stak# make
Scanning dependencies of target xmr-stak-c
[  2%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[  8%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 14%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 17%] Linking C static library bin/libxmr-stak-c.a
[ 17%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 20%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 26%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 29%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 32%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 35%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 47%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 58%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 64%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 67%] Linking CXX static library bin/libxmr-stak-backend.a
[ 67%] Built target xmr-stak-backend
[ 70%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o                                                                                                                                     
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/share/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/share/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:219 (message):
  Error generating
  /opt/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:72: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@darkstar:/opt/xmr-stak# ls /usr/bin/gcc
/usr/bin/gcc@
root@darkstar:/opt/xmr-stak# ls -l /usr/bin/gcc
lrwxrwxrwx 1 root root 9 Dec 27 09:17 /usr/bin/gcc -> gcc-7.2.0*
root@darkstar:/opt/xmr-stak# ls -l /usr/bin/gcc
gcc         gcc-7.2.0   gcc-ar      gcc-nm      gcc-ranlib  gccbrig     gccgo       gccmakedep  
root@darkstar:/opt/xmr-stak# ls -l /usr/bin/gcc
gcc         gcc-7.2.0   gcc-ar      gcc-nm      gcc-ranlib  gccbrig     gccgo       gccmakedep  
root@darkstar:/opt/xmr-stak# ls -l /usr/bin/gcc^C
root@darkstar:/opt/xmr-stak# installpkg /home/trite/Downloads/gcc-
gcc-5.3.0-x86_64-3.txz       gcc-g++-5.3.0-x86_64-3.txz   gcc-objc-5.3.0-x86_64-3.txz  
root@darkstar:/opt/xmr-stak# installpkg /home/trite/Downloads/gcc-*
Verifying package gcc-5.3.0-x86_64-3.txz.
Installing package gcc-5.3.0-x86_64-3.txz:
PACKAGE DESCRIPTION:
# gcc (Base GCC package with C support)
#
# GCC is the GNU Compiler Collection.
#
# This package contains those parts of the compiler collection needed to
# compile C code.  Other packages add Ada, C++, Fortran, Go,
# Objective-C, and Java support to the compiler core.
#
Executing install script for gcc-5.3.0-x86_64-3.txz.
Package gcc-5.3.0-x86_64-3.txz installed.

Verifying package gcc-g++-5.3.0-x86_64-3.txz.
Installing package gcc-g++-5.3.0-x86_64-3.txz:
PACKAGE DESCRIPTION:
# gcc-g++ (C++ for GCC)
#
# C++ support for the GNU Compiler Collection.
#
# This package contains those parts of the compiler collection needed to
# compile C++ code.  The base gcc package is also required.
#
Executing install script for gcc-g++-5.3.0-x86_64-3.txz.
Package gcc-g++-5.3.0-x86_64-3.txz installed.

Verifying package gcc-objc-5.3.0-x86_64-3.txz.
Installing package gcc-objc-5.3.0-x86_64-3.txz:
PACKAGE DESCRIPTION:
# gcc-objc (Objective-C support for GCC)
#
# Objective-C support for the GNU Compiler Collection.
#
# This package contains those parts of the compiler collection needed to
# compile code written in Objective-C.  Objective-C was originally
# developed to add object-oriented extensions to the C language, and is
# best known as the native language of the NeXT computer.
#
# The base gcc package is also required.
#
Executing install script for gcc-objc-5.3.0-x86_64-3.txz.
Package gcc-objc-5.3.0-x86_64-3.txz installed.

root@darkstar:/opt/xmr-stak# make
[ 17%] Built target xmr-stak-c
[ 67%] Built target xmr-stak-backend
[ 70%] Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004848_00000000-23_cuda_extra.compute_62.cpp1.ii".
CMake Error at xmrstak_cuda_backend_generated_cuda_extra.cu.o.Release.cmake:279 (message):
  Error generating file
  /opt/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_extra.cu.o


make[2]: *** [CMakeFiles/xmrstak_cuda_backend.dir/build.make:72: CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/xmrstak_cuda_backend.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@darkstar:/opt/xmr-stak#

**Comment by trite2k3** [comment]
This was on another machine completely from scratch with all output, same error.

**Comment by candrews** [comment]
A gentoo user is reporting the same error: https://bugs.gentoo.org/646852
Here's the log: https://bugs.gentoo.org/attachment.cgi?id=518302
Key info is:
* Nvidia cuda toolkit 9.1
* GCC 6.4

```
/usr/bin/cmake -E remove /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o.depend.tmp /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_core.cu.o.NVCC-depend
-- Generating /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_core.cu.o
/opt/cuda/bin/nvcc /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu -c -o /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/./xmrstak_cuda_backend_generated_cuda_core.cu.o -ccbin /usr/bin/x86_64-pc-linux-gnu-gcc -m64 -Dxmrstak_cuda_backend_EXPORTS -DXMR_STAK_LARGEGRID=ON -DXMRSTAK_CUDA_ARCH_LIST=30+35+37+50+52+60+61+62+70 -DCONF_NO_OPENCL -DCONF_NO_HTTPD -DCONF_NO_HWLOC -DBACKEND_TYPE=nvidia-cpu -Xcompiler ,\"-march=native\",\"-mtune=native\",\"-march=bdver2\",\"-O2\",\"-pipe\",\"-msse2\",\"-maes\",\"-fPIC\" -std=c++11 --generate-code arch=compute_30,code=sm_30 --generate-code arch=compute_30,code=compute_30 --generate-code arch=compute_35,code=sm_35 --generate-code arch=compute_35,code=compute_35 --generate-code arch=compute_37,code=sm_37 --generate-code arch=compute_37,code=compute_37 --generate-code arch=compute_50,code=sm_50 --generate-code arch=compute_50,code=compute_50 --generate-code arch=compute_52,code=sm_52 --generate-code arch=compute_52,code=compute_52 --generate-code arch=compute_60,code=sm_60 --generate-code arch=compute_60,code=compute_60 --generate-code arch=compute_61,code=sm_61 --generate-code arch=compute_61,code=compute_61 --generate-code arch=compute_62,code=sm_62 --generate-code arch=compute_62,code=compute_62 --generate-code arch=compute_70,code=sm_70 --generate-code arch=compute_70,code=compute_70 --default-stream per-thread -DNVCC -I/opt/cuda/include -I/var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0/. -I/usr/include
-- Generating temporary cmake readable file: /var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.NVCC-depend -D output_file:FILEPATH=/var/tmp/portage/net-p2p/xmr-stak-2.2.0/work/xmr-stak-2.2.0_build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o.depend.tmp -D verbose=1 -P /usr/share/cmake/Modules/FindCUDA/make2cmake.cmake
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
```

**Comment by candrews** [comment]
This appears to be an issue with CUDA not being compatible with glibc 2.2.6:
https://devtalk.nvidia.com/default/topic/1023776/-request-add-nvcc-compatibility-with-glibc-2-26/

**Comment by trite2k3** [comment]
--- a/usr/include/bits/floatn.h	2017-09-13 16:00:37.079654880 +0200
+++ b/usr/include/bits/floatn.h	2017-09-13 16:00:00.999104815 +0200
@@ -28,7 +28,8 @@
    support, for x86_64 and x86.  */
 #if (defined __x86_64__							\
      ? __GNUC_PREREQ (4, 3)						\
-     : (defined __GNU__ ? __GNUC_PREREQ (4, 5) : __GNUC_PREREQ (4, 4)))
+     : (defined __GNU__ ? __GNUC_PREREQ (4, 5) : __GNUC_PREREQ (4, 4))) \
+  &&  !defined(__CUDACC__)
 # define __HAVE_FLOAT128 1
 #else
 # define __HAVE_FLOAT128 0

**Comment by psychocrypt** [comment]
you cuda and gcc are not compatible. update to cuda 10 and all should be
solved
