### ISSUE TITLE
"xmr-stak.exe is not a valid Win32 application" under XP x86-64

### ISSUE THREAD

**Issue by Behemot2077** [fireice-uk/xmr-stak#580]
I cannot seem to run xmr-stak under 64bit version of Win XP Pro (basically a Win server 2003 system). What is it that it's missing? It is 64bit system so the main requirement is there. .NET newer than 4.0 is no longer supported so I cannot install Visual studio to try to compile it myself.

**Comment by fireice-uk** [comment]
Sorry, the minimum supported windows version is 7. To get it to even build for xp you will need to tweak the code. Closing as this is not a target system for the miner.

**Comment by Behemot2077** [comment]
I noticed pretty much everybody pisses on XP, it seems that Vista too. That is one thing, but would be at least a bit decent from EVERYBODY to STATE the minimum requirements. Is that such a problem to write it somewhere? How does one know it won't work without wasting time trying? Not that the documentation is not so poor either, there are dozens of options for the app and NO information about that anywhere. But minimum requirements are kinda the first thing one would expect to see about every SW!

**Comment by psychocrypt** [comment]
Yes we can add a section with the minimum requirements. If a description of
compile time parametet is missing please open an issue for that.

**Comment by Behemot2077** [comment]
Appreciated!
