### ISSUE TITLE
CUDA mining crashes

### ISSUE THREAD

**Issue by xmrhamster** [fireice-uk/xmr-stak#581]
Please provide as much as possible information to reproduce the issue.

# Basic information
  Intel Core i7 3740QM (CPUID 6.A.9)
  NVIDIA Quadro K2000M (Revision A2)

# Compile issues
Microsoft Windows 7 (6.1) Enterprise Edition 64-bit  Service Pack 1 (Build 7601) 
Executable is from the https://github.com/fireice-uk/xmr-stak/releases/download/v2.1.0/xmr-stak-win64.zip
Full version is  xmr-stak/2.1.0/30888a3/master/win/nvidia-amd-cpu/aeon-monero/20

Everything works is at native clocks.
Start of xmr-stak.exe leads to quick application crash. 

Windows error report looks like that:
>Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	xmr-stak.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a2bc165
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10586.788
  Fault Module Timestamp:	5879ab76
  Exception Code:	40000015
  Exception Offset:	000000000006990f
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1049
  Additional Information 1:	3542
  Additional Information 2:	354277695d5996549de65424a30f567a
  Additional Information 3:	a15d
  Additional Information 4:	a15d7fea7755357421348c7718956f4a

Logfile does not show anything special:

>[2017-12-16 19:04:04] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-16 19:04:04] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-16 19:04:04] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-16 19:04:04] : WARNING: backend AMD disabled.
[2017-12-16 19:04:04] : Starting 1x thread, affinity: 0.
[2017-12-16 19:04:04] : hwloc: memory pinned
[2017-12-16 19:04:04] : Starting 1x thread, affinity: 2.
[2017-12-16 19:04:04] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-16 19:04:04] : hwloc: memory pinned
[2017-12-16 19:04:04] : Starting 1x thread, affinity: 4.
[2017-12-16 19:04:04] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-16 19:04:04] : hwloc: memory pinned
[2017-12-16 19:04:04] : Fast-connecting to frankfurt-1.xmrpool.net:443 pool ...
[2017-12-16 19:04:04] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-12-16 19:04:05] : Fast-connecting to vegas-backup.xmrpool.net:443 pool ...
[2017-12-16 19:04:05] : Pool frankfurt-1.xmrpool.net:443 connected. Logging in...
[2017-12-16 19:04:05] : Pool vegas-backup.xmrpool.net:443 connected. Logging in...
[2017-12-16 19:04:06] : Difficulty changed. Now: 30000.
[2017-12-16 19:04:06] : Pool logged in.
[2017-12-16 19:04:38] : Difficulty changed. Now: 30000.
[2017-12-16 19:04:38] : New block detected.`

Program's windows last line is a little bit more informative:

![image](https://user-images.githubusercontent.com/34606356/34073192-5dee97ac-e294-11e7-975e-fb013a0bc405.png)

Trying to bring this error into vstudio debugger (VS10) gives the following backtrace:

> 

>	ucrtbase.dll!__crt_debugger_hook() 	
 	ucrtbase.dll!__acrt_call_reportfault()  + 0x12c bytes	
 	ucrtbase.dll!abort()  + 0x5f bytes	
 	ucrtbase.dll!terminate()  + 0x26 bytes	
 	vcruntime140.dll!FindHandler(EHExceptionRecord * pExcept=0x0000000000000001, unsigned __int64 * pRN=0x000000000313dff8, _CONTEXT * pContext=0x000000000313eaa0, _xDISPATCHER_CONTEXT * pDC=0x000000000313e0b0, const _s_FuncInfo * pFuncInfo=0x000000000313f7c0, unsigned char recursive=0, int CatchDepth=97444816, unsigned __int64 * pMarkerRN=0x0000000005cee3d0)  Line 762 + 0x6 bytes	C++
 	vcruntime140.dll!__InternalCxxFrameHandler(EHExceptionRecord * pExcept=0x000000000313e0b0, unsigned __int64 * pRN=0x000000000313f7c0, _CONTEXT * pContext=0x000000000313eaa0, _xDISPATCHER_CONTEXT * pDC=0x000000000313f0d0, const _s_FuncInfo * pFuncInfo=0x000007fee02d6488, int CatchDepth=1, unsigned __int64 * pMarkerRN=0x0000000000000001, unsigned char recursive=0)  Line 449	C++
 	vcruntime140.dll!__CxxFrameHandler3(EHExceptionRecord * pExcept=0x0000000003140000, unsigned __int64 RN=51640256, _CONTEXT * pContext=0x000007fee02f8a90, _xDISPATCHER_CONTEXT * pDC=0x0000000003139000)  Line 215	C++
 	ntdll.dll!RtlpExecuteHandlerForException()  + 0xd bytes	
 	ntdll.dll!RtlDispatchException()  + 0x38f bytes	
 	ntdll.dll!RtlRaiseException()  + 0x248 bytes	
 	KernelBase.dll!RaiseException()  + 0x3d bytes	
 	vcruntime140.dll!_CxxThrowException(void * pExceptionObject=0x000007fee0280000, const _s__ThrowInfo * pThrowInfo=0x0000000000000000)  Line 136	C++
 	xmrstak_cuda_backend.dll!xmrstak_start_backend()  + 0xa3a bytes	
 	[Frames below may be incorrect and/or missing, no symbols loaded for xmrstak_cuda_backend.dll]	
 	xmrstak_cuda_backend.dll!000007fee02b9189() 	
 	xmrstak_cuda_backend.dll!000007fee02b3ff5() 	
 	xmrstak_cuda_backend.dll!000007fee02b01d9() 	
 	ucrtbase.dll!_crt_at_quick_exit()  + 0x7d bytes	
 	kernel32.dll!BaseThreadInitThunk()  + 0xd bytes	
 	ntdll.dll!RtlUserThreadStart()  + 0x21 bytes

P.S. begin started with --noNVIDIA option it works just fine

**Comment by psychocrypt** [comment]
reduce threads or increase bfactor in nvidia.txt

**Comment by xmrhamster** [comment]
Thanks a lot! That really helped.

P.S. Yet it would be nice if app writes this advice on a screen instead of crashing...

**Comment by psychocrypt** [comment]
The miner still write it to the screen on some errors but currently not at
this line. I will check if it is already added in the dev branch.
