### ISSUE TITLE
--noCPU doesn't work

### ISSUE THREAD

**Issue by whitemarvin** [fireice-uk/xmr-stak#582]
Starting the miner with --noCPU doesn't seem to have effect. I want to mine XMR on my GPU, but as soon as I start the miner, it uses 100% of my CPU instead, and the system becomes near unusable.

> [2017-12-16 21:17:35] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
> [2017-12-16 21:17:35] : MEMORY ALLOC FAILED: mmap failed
> [2017-12-16 21:17:35] : MEMORY ALLOC FAILED: mmap failed
> [2017-12-16 21:17:35] : MEMORY ALLOC FAILED: mmap failed
> [2017-12-16 21:17:35] : MEMORY ALLOC FAILED: mmap failed
> [2017-12-16 21:17:35] : MEMORY ALLOC FAILED: mmap failed
> -------------------------------------------------------------------
> xmr-stak 2.1.0 31a0784
> 
> Brought to you by fireice_uk and psychocrypt under GPLv3.
> Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
> Based on NVIDIA mining code by KlausT and psychocrypt.
> Based on OpenCL mining code by wolf9466.
> 
> Configurable dev donation level is set to 2.0%
> 
> You can use following keys to display reports:
> 'h' - hashrate
> 'r' - results
> 'c' - connection
> -------------------------------------------------------------------
> [2017-12-16 21:17:36] : Start mining: MONERO
> [2017-12-16 21:17:36] : Starting NVIDIA GPU thread 0, no affinity.
> [2017-12-16 21:17:36] : MEMORY ALLOC FAILED: mmap failed
> [2017-12-16 21:17:36] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
> [2017-12-16 21:17:36] : WARNING: backend AMD disabled.

I compiled the miner myself. Here's the output of xmr-stak --version-long:

> Version: xmr-stak/2.1.0/31a0784/master/lin/nvidia-amd-cpu/aeon-monero/0

**Comment by fireice-uk** [comment]
You still need to validate the GPU results on the CPU. My bet is that you are using a proxy that reduces the difficulty to something ridiculous like 1000

**Comment by whitemarvin** [comment]
I'm not using a proxy. I'm mining with a pool, and in my testing so far, the difficulty has been anywhere from 200000 to 1000000.

I expected that mining on GPU would use a bit of CPU, but I didn't expect it would use anywhere near this much. I've tested a bit more, and it looks like when mining, 100% of a core gets used for few seconds until it goes down, and then immediately another core goes up to 100%, and so on. Is this the expected behaviour?

**Comment by psychocrypt** [comment]
please post your nvidia.txt it could be that the syncing of the gpu cost
cpu power. please also post the output of htop during the mining.

**Comment by whitemarvin** [comment]
Here's nvidia.txt:

> /*
>  * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
>  * index         - GPU index number usually starts from 0.
>  * threads       - Number of GPU threads (nothing to do with CPU threads).
>  * blocks        - Number of GPU blocks (nothing to do with CPU threads).
>  * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
>  *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
>  * bsleep        - Insert a delay of X microseconds between kernel launches.
>  *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
>  * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
>  * sync_mode     - method used to synchronize the device
>  *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
>  *                 0 = cudaDeviceScheduleAuto
>  *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
>  *                 2 = cudaDeviceScheduleYield
>  *                 3 = cudaDeviceScheduleBlockingSync (default)
>  *
>  * On the first run the miner will look at your system and suggest a basic configuration that will work,
>  * you can try to tweak it from there to get the best performance.
>  *
>  * A filled out configuration should look like this:
>  * "gpu_threads_conf" :
>  * [
>  *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
>  *       "affine_to_cpu" : false, "sync_mode" : 3,
>  *     },
>  * ],
>  */
> 
> "gpu_threads_conf" :
> [
>   // gpu: GeForce GTX 750 architecture: 50
>   //      memory: 601/978 MiB
>   //      smx: 4
>   { "index" : 0,
>     "threads" : 18, "blocks" : 12,
>     "bfactor" : 2, "bsleep" :  0,
>     "affine_to_cpu" : false, "sync_mode" : 3,
>   },
> 
> ],
> 

As for htop, it shows that xorg is using 100% of the CPU whenever I try to mine.

**Comment by psychocrypt** [comment]
Than it is an xorg issue. Tru to mine when xorg is disabled. Press
crt+alt+F1 login and stop your x session. than starte the miner. Check the
cpu usage on tty2 (crt+alt+2)

**Comment by whitemarvin** [comment]
I tried it, and indeed, with xorg disabled, there's hardly any CPU usage at all while mining. Unfortunately, this isn't a dedicated machine for mining, and I need xorg running. Is there no other solution?

**Comment by psychocrypt** [comment]
try to set bfactor to 6 and bsleep to 10

**Comment by whitemarvin** [comment]
There's a slight improvement, but the system is still barely usable when mining with xorg running.

**Comment by JerichoJones** [comment]
Try bsleep 100

**Comment by whitemarvin** [comment]
There's no noticeable improvement, unfortunately.

**Comment by DavidBruchmann** [comment]
Whats about running in docker or VBox?

**Comment by whitemarvin** [comment]
@DavidBruchmann If my understanding is correct, creating a virtual machine with GPU passthrough requires a CPU that supports IOMMU, but I'm using an old i3 which doesn't have that. So I don't think I can run the miner in a virtual machine, unless there's some way around the IOMMU requirement.

As for running the miner in Docker, I'd love to try it, but I don't have a clue how Docker works. I'll have to take some time to look in that.

I'm curious if this issue occurs with Wayland as well. If anyone knows, please let me know.

**Comment by DavidBruchmann** [comment]
@whitemarvin yeah, honestly I don't have experience with any of the proposed solutions, so regrettable I can't give you any advise.

**Comment by psychocrypt** [comment]
If no cpu should not work empty all entries in cpu.txt between `[···]`

**Comment by whitemarvin** [comment]
@psychocrypt I don't have a cpu.txt. I think it might've deleted altogether.

In any case, it's obvious by now that I misinterpreted the issue. The parameter --noCPU works just fine, but mining on GPU makes X.org use a ton of CPU for some reason. I think it's the same issue referenced in #585.
