### ISSUE TITLE
CPU Hash Rate Wrong?

### ISSUE THREAD

**Issue by unformatt** [fireice-uk/xmr-stak#584]
Maybe report is not showing all CPUs?  46 + 49 != 185

`./xmr-stak-fix --noNVIDIA`

```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   46.0 |   (na) |   (na) |  1 |   44.3 |   (na) |   (na) |
|  2 |   49.2 |   (na) |   (na) |  3 |   45.7 |   (na) |   (na) |
-----------------------------------------------------
Totals:    185.3   (na)   (na) H/s
Highest:   187.1 H/s
```

# Basic information
  - 4.01 GHz Intel Core i7
  - NVidia GTX 950
  - macOS Sierra 10.12.6
![image](https://user-images.githubusercontent.com/157132/34058777-5ae0087e-e1aa-11e7-8961-73c24b8032b2.png)
![image](https://user-images.githubusercontent.com/157132/34058792-6339c37a-e1aa-11e7-922c-71992a86973a.png)

# Issue with the execution
  - Do you compile the miner by our own? Yes, from `dev` branch
  ```
 ./xmr-stak --version-long
Version: xmr-stak/2.1.0/14d7e52/dev/mac/nvidia-cpu/aeon-monero/20
  ```

# Stability issue (NO)
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by DavidBruchmann** [comment]
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   46.0 |   (na) |   (na) |  1 |   44.3 |   (na) |   (na) |
|  2 |   49.2 |   (na) |   (na) |  3 |   45.7 |   (na) |   (na) |
-----------------------------------------------------
Totals:    185.3   (na)   (na) H/s
Highest:   187.1 H/s
```
46 + 49.2 + 44.3 + 45.7 = 185.2

**Comment by unformatt** [comment]
oh bajeebus... I completely glazed over the second set of stats on the right. Thank you
