### ISSUE TITLE
GUI is unusably slow on Ubuntu 17.10 with Nvidia GPU mining

### ISSUE THREAD

**Issue by robs-pangolin** [fireice-uk/xmr-stak#585]
Please provide as much as possible information to reproduce the issue.

When running xmr-stack on Ubuntu 17.10 (+cuda 9.1) with the nvidia gpu, the gui becomes so slow it is unusable (if I, instead, just use the cpu mining, everything works fine).  Xmr-stak itself works fine, and I am able to mine at rates similar to those predicted on various websites, I'm just not able to do anything else (with the gui, the command line works fine).

I've tried tweaking the values in nvidia.txt, which do improve things slightly but not enough to be able to use the computer. If I boot into windows, I can use the windows version of xmr-stak fine and even play Age of Empires without it impacting the mining rate  (I have tried using the nvidia.txt settings from windows under linux, but it didn't improve things much.)

I have tried running the monitors off the integrated adapter rather than the nvidia one, no difference.

I have also tried switching from gnome to Xfce for the desktop environment, no difference.

Would downgrading to the LTS release of Ubuntu(16.04) help?  

This is so far the best I've been able to come up with as far as nvidia.txt goes:

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 960 architecture: 52
  //      memory: 3969/4096 MiB
  //      smx: 8
  { "index" : 0,
    "threads" : 38, "blocks" : 24,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],

The version that works pretty much perfectly on windows (but not on Linux) is:

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 960 architecture: 52
  //      memory: 3969/4096 MiB
  //      smx: 8
  { "index" : 0,
    "threads" : 38, "blocks" : 24,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

# Basic information
  - Type of the CPU. i7
  - Type of the GPU (if you try to miner with the GPU). GTX 960

# Issue with the execution
  - Do you compiled the miner by our own? Compiled from git dev branch using gcc 6
  ```
  run `./xmr-stak --version-long` and add the output here: Version: xmr-stak/2.1.0/ca2889d/dev/lin/nvidia-cpu/aeon-monero/1
  ```

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

**Comment by SeaDude** [comment]
My computer is basically unusable while GPU and CPU mining at the same time. I've tried to turn off CPU mining altogether, but still unusable. 

* Ubuntu 16.04
* NVIDIA 880M

**Comment by DavidBruchmann** [comment]
@robs-pangolin hope your name is only a silly joke.

**Comment by JerichoJones** [comment]
@robs-pangolin Are you CPU mining as well?

**Comment by robs-pangolin** [comment]
@SeaDude Thanks, saved me the bother of downgrading only to find it still wouldn't work

@JerichoJones  No, just GPU mining (but I can, and the computer is more responsive for day to day usage if I CPU mine rather than GPU)

After a couple of days of testing, I seem to have got things working, though I'm not exactly sure what made the difference. The problem seems to be with having certain applications running with certain combinations of monitors on the graphics cards. In some cases, some things cause Xorg to take up 100% of the processing power. I am suspicious that it may have been a panel app that was causing the main problem.

I was hoping that switching to Wayland might be a simple solution to this problem, but I have so far failed to get Wayland to run. 

For now, it is mostly usable, the only major annoyance is that I can no longer use LibreOffice (even with hardware acceleration turned off) as it causes Xorg to use 100% of the CPU if I'm GPU mining at the same time.

I currently have my monitors attached to the integrated adapter, and started with a new clean standard gnome-shell (i.e not the ubuntu one) with top running in a terminal (and xmr-stack running in another) opened each program I need to use and if it caused Xorg to go berserk, found an alternative that wouldn't.

I now have gpu mining at around 280H/s on my gtx 960 and my computer feels normal to use. After Christmas I might try and figure out why LibreOffice is such a problem.

**Comment by SeaDude** [comment]
@robs-pangolin , if there are any steps you can recommend for the rest of us Ubuntu users, that'd be awesome. I have a GTX 880M that i'd love to mine with while I use my i7 CPU to do actual work with my computer. 

I imagine there are some `xorg.conf` items to edit, but that .conf file is beyond me in the way it works. Spent quite a bit of time in `man xorg.conf` only to get wrapped around the wheel. `nvidia-settings` and `nvidia-smi` and `nvidia-xconfig` are no help to me either. Need outside expertise at this point. 

Thanks

**Comment by robs-pangolin** [comment]
Basically, the two things I didn't realise were that if you have your monitor plugged into a graphics card, it doesn't necessarily mean it's using that card for hardware acceleration, and that some fairly inoffensive looking apps use hardware acceleration in surprising ways. My solution was simply to get rid of everything I need that used hw acceleration and replace it with something that didn't and to give xmr-stak a bit of breathing space for the things that couldn't be lived without by setting "bfactor" : 8, "bsleep" : 100 in nvidia.txt.

A much better solution would be to run everything I use day to day off my onboard graphics card and then just use my nvidia card for xmr-stak (and the occasional other programs that need it), but I have so far failed to get this to work...

**Comment by robs-pangolin** [comment]
I have it working perfectly (fingers crossed).
The thing you need to do is to not install the opengl libraries from nvidia as these only allow you to use either your nvidia gpu or your onboard one but not both at the same time!

Here is what I did:
1) Plug monitors into onboard graphics
2) Completly purge your system of everything nvidia (depending on how you installed it, this step will vary, but you need to get rid of the drivers, cuda, apps and libs)
3) Reboot to make sure all kernel modules have been removed (and that you are now using the intel drivers for everything) 
4) Download cuda_9.1.85_387.26_linux.run from the https://developer.nvidia.com/cuda-downloads (currently there is no option for 7.10 but 7.04 works fine)
5) run the installer with "sudo sh cuda_9.1.85_387.26_linux.run --override" (override is needed else it will fail due to 17.10 having an unsupported compiler)
6) select the options required (at least driver and cuda) but **importantly** say no to opengl libraries
7) reboot and your done!

For more information about why this works see this thread https://askubuntu.com/questions/779530/how-to-configure-igpu-for-xserver-and-nvidia-gpu-for-cuda

Note: in the thread, it says that you need to install nvidia-modprobe separately, but it got installed when I installed the cuda stuff
