### ISSUE TITLE
xmr-stak force closes soon after startup

### ISSUE THREAD

**Issue by RokuHodo** [fireice-uk/xmr-stak#586]
# Hardware and Specs
- **PC Specs:** https://pcpartpicker.com/user/SixDegrees/saved/JM9j4D
- **OS:** Windows 10 Pro
- **Binary:** Precompiled binary v2.1.0

# Problem
After starting the miner through either a ``batch`` file or through the command prompt, the miner successfully connects to the pool with no errors, begins  to mine, and then force closes itself after a few blocks have been mined with no error.

I also used the following launch parameters: 
```
--noCPU --noUAC --noAMD
```

The minor ran beautifully over night for 10 hours without a hiccup, but now it only lasts a few minutes before closing. The behavior persisted even after reverting back to the default ``config.txt`` and ``nvidia.txt``, and after re-installing my graphics driver and cuda drivers.

**Comment by DavidBruchmann** [comment]
check your windows defender about blocked threads.

**Comment by RokuHodo** [comment]
Windows Defender and Webroot were both deactivated while this was happening.

**Comment by RokuHodo** [comment]
Wait, no, they were turned back on some how. Probably when my computer forced me to upgrade to the fall creators update. GG Microsoft.

**Comment by DavidBruchmann** [comment]
"Probably when my computer forced me to upgrade to the fall creators update."

No, on some events defender starts automatically even if deactivated.

**Comment by RokuHodo** [comment]
So you assuming that wasn't the cause of the issue, without knowing how I have my computer configured and what processes I ave running? Seems like an arrogant claim to say I'm straight up wrong without knowing the details. Which, by the way, even after making sure every last trace of defender is deactivated, the issue persists.

**Comment by JerichoJones** [comment]
@RokuHodo Is it fixed or not?

**Comment by RokuHodo** [comment]
For the first couple days it was stable with the third release, but now it's behaving the same way as the other two releases with the force closes.

**Comment by JerichoJones** [comment]
@RokuHodo Turn on logging in config.txt
