### ISSUE TITLE
in the cuda_extras.cu you have to change something

### ISSUE THREAD

**Issue by genewitch** [fireice-uk/xmr-stak#589]
cuda-9.1 
-#include <device_functions.hpp>
+#include <device_functions.h>

basically everywhere. i had to change this in another file but i forget which one. 

solution kinda tracked down https://github.com/xmrig/xmrig-nvidia/commit/97ebe8be0d6d6a2ed0e75d7def9ed811e26e1d4a

**Comment by psychocrypt** [comment]
it is already fixed in the dev branch and will be released soon.

**Comment by genewitch** [comment]
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b8f1eef..7fa6898 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -107,9 +107,14 @@ if(CUDA_ENABLE)
             list(APPEND DEFAULT_CUDA_ARCH "60" "61" "62")
         endif()
         # add Volta support for CUDA >= 9.0
-        if(NOT CUDA_VERSION VERSION_LESS 9.0)
-            list(APPEND DEFAULT_CUDA_ARCH "70")
+       if(NOT CUDA_VERSION VERSION_LESS 9.0)
+            # Volta GPUs are currently not supported on MACOSX
+            # https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-known-issues
+            if(NOT APPLE)
+                list(APPEND DEFAULT_CUDA_ARCH "70")
+            endif()
         endif()
+
         set(CUDA_ARCH "${DEFAULT_CUDA_ARCH}" CACHE STRING "Set GPU architecture (semicolon separated list, e.g. '-DCUDA_ARCH=20;35;60')")

         # generate comma separated list with architectures
diff --git a/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu b/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
index 734426c..e655f6b 100644
--- a/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
+++ b/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
@@ -6,7 +6,7 @@
 #include <vector>
 #include <cuda.h>
 #include <cuda_runtime.h>
-#include <device_functions.hpp>
+#include <device_functions.h>
 #include  <algorithm>
 #include "xmrstak/jconf.hpp"

**Comment by genewitch** [comment]
ETA on fix, then so i can reclone?

**Comment by genewitch** [comment]
also i fixed another issue, so i am not sure which one you said you fixed.

**Comment by genewitch** [comment]
also how do i stop it from CPU mining? it's not even using all the cores:
![image](https://user-images.githubusercontent.com/3182020/34077758-56926014-e2d1-11e7-80d0-fae45b8e17c2.png)

**Comment by genewitch** [comment]
also since i know it's going to come up, here's my config.txt 👍 
http://projectftm.com/#yh9s_KeCmpBGtgNeBPQkaQ

ping me privately and i'll upload it to my github page.

**Comment by genewitch** [comment]
http://projectftm.com/#Xg7QIqXWsj89GZbIRhjFtQ
my config.txt. i'll delete it soon, msg me and i'll upload it to github on my account (the config.txt format changed a bit, the pools are different)

**Comment by psychocrypt** [comment]
The include of the deleted function in cuda 9.1 (device_functions.hpp) is
fixed. I can not see what you changed in cmake but in cmake there is an fix
for windows cuda 9.1 and macosx included.
Cpu mining can be disabled with the option `--noCPU`
