### ISSUE TITLE
LD_LIBRARY_PATH= Ineffective in making OpenCL work on AMD Gpu

### ISSUE THREAD

**Issue by MatthewCroughan** [fireice-uk/xmr-stak#590]
[matthew@MatthewDesktop ~]$ clinfo
Number of platforms                               2
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 9.1.98
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
  Platform Extensions function suffix             NV

  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.3.0
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce GTX 960
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  387.34
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Available                                Yes
  Device Profile                                  FULL_PROFILE
  Device Topology (NV)                            PCI-E, 02:00.0
  Max compute units                               8
  Max clock frequency                             1202MHz
  Compute Capability (NV)                         5.2
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Compiler Available                              Yes
  Linker Available                                Yes
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2085093376 (1.942GiB)
  Error Correction support                        No
  Max memory allocation                           521273344 (497.1MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        131072 (128KiB)
  Global Memory cache line                        128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 256
    Max number of write image args                16
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     9
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer

  Platform Name                                   Clover
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContext(NULL, ...) [other]              <error: no devices in non-default plaforms>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

No matter where I plug in the binaries:
/opt/amdgpu-pro/lib/x86_64-linux-gnu
/opt/AMDAPP/SDK/lib/sdk/

or others that I have tried, I don't get any further. 

**BUT** I do actually get the Amd driver to load, although no gpu is detected

[2017-12-17 10:46:02] compiling code and initializing GPUs. This will take a while...
[2017-12-17 10:46:02] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2017-12-17 10:46:02] No AMD device found.
[2017-12-17 10:46:02] Failed to start threads

I have blacklisted the radeon kernel module.

[matthew@MatthewDesktop ~]$ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Curacao PRO [Radeon R7 370 / R9 270/370 OEM]
02:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

**Comment by psychocrypt** [comment]
set LD_LIBRARY_PATH to the opencl lib folder of the app sdk. As I remember
this is also described in the readme of the appsdk

**Comment by MatthewCroughan** [comment]
That's what I've done, and it loads the driver, but does not detect any GPUs when launching the application.

**Comment by MatthewCroughan** [comment]
[matthew@MatthewDesktop bin]$ LD_LIBRARY_PATH=/opt/AMDAPP/SDK/lib/ ./xmr-stak-amd 
[2017-12-17 10:56:06] : Compiling code and initializing GPUs. This will take a while...
[2017-12-17 10:56:06] : Device 0 work size 8 / 1024.
[2017-12-17 10:56:06] : Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
<kernel>:16:26: warning: unknown OpenCL extension 'cl_amd_media_ops2' - ignoring
#pragma OPENCL EXTENSION cl_amd_media_ops2 : enable
                         ^
In file included from <kernel>:18:
./opencl/wolf-aes.cl:79:14: warning: implicit declaration of function 'amd_bfe' is invalid in C99
        Y.s0 = AES0[BYTE(X.s0, 0)] ^ AES1[BYTE(X.s1, 1)] ^ AES2[BYTE(X.s2, 2)] ^ AES3[BYTE(X.s3, 3)];
                    ^
./opencl/wolf-aes.cl:74:21: note: expanded from macro 'BYTE'
#define BYTE(x, y)      (amd_bfe((x), (y) << 3U, 8U))
                         ^
In file included from <kernel>:19:
./opencl/wolf-skein.cl:33:29: warning: implicit declaration of function 'amd_bitalign' is invalid in C99
        if(y < 32) return(as_ulong(amd_bitalign(x, x.s10, 32 - y)));
                                   ^
./opencl/wolf-skein.cl:33:20: error: call to 'as_ulong' is ambiguous
        if(y < 32) return(as_ulong(amd_bitalign(x, x.s10, 32 - y)));
                          ^~~~~~~~
cl_kernel.h:14906:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (long);
                       ^
cl_kernel.h:14907:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ulong);
                       ^
cl_kernel.h:14908:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (double);
                       ^
cl_kernel.h:15584:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (char8);
                       ^
cl_kernel.h:15585:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uchar8);
                       ^
cl_kernel.h:15587:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short3);
                       ^
cl_kernel.h:15589:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short4);
                       ^
cl_kernel.h:15591:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort3);
                       ^
cl_kernel.h:15593:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort4);
                       ^
cl_kernel.h:15594:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (int2);
                       ^
cl_kernel.h:15595:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uint2);
                       ^
cl_kernel.h:15596:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (float2);
                       ^
In file included from <kernel>:19:
./opencl/wolf-skein.cl:34:14: error: call to 'as_ulong' is ambiguous
        else return(as_ulong(amd_bitalign(x.s10, x, 32 - (y - 32))));
                    ^~~~~~~~
cl_kernel.h:14906:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (long);
                       ^
cl_kernel.h:14907:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ulong);
                       ^
cl_kernel.h:14908:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (double);
                       ^
cl_kernel.h:15584:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (char8);
                       ^
cl_kernel.h:15585:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uchar8);
                       ^
cl_kernel.h:15587:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short3);
                       ^
cl_kernel.h:15589:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (short4);
                       ^
cl_kernel.h:15591:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort3);
                       ^
cl_kernel.h:15593:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (ushort4);
                       ^
cl_kernel.h:15594:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (int2);
                       ^
cl_kernel.h:15595:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (uint2);
                       ^
cl_kernel.h:15596:24: note: candidate function
ulong __OVERLOADABLE__ as_ulong (float2);
                       ^
<kernel>:328:26: warning: unknown OpenCL extension 'cl_amd_media_ops2' - ignoring
#pragma OPENCL EXTENSION cl_amd_media_ops2 : enable

**Comment by MatthewCroughan** [comment]
and on the unified build 

[2017-12-17 10:57:54] : WARNING: backend NVIDIA disabled.
[2017-12-17 10:57:54] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2017-12-17 10:57:54] : WARNING: CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for of devices.
[2017-12-17 10:57:54] : WARNING: No AMD device found.

**Comment by psychocrypt** [comment]
do you use the newest driver from the amd webside or the driver from the
distribution?

**Comment by MatthewCroughan** [comment]
Sorry, I should have mentioned, I'm using arch. I'm using every possible dependency, xf86-video-amdgpu clinfo opencl-headers ocl-icd amdgpu-pro-opencl amdapp-sdk. I'm not too familiar with environment variables, I just use Antergos and would love to be able to mine on a spare AMD GPU, and Vegas in the future, but fear this might be impossible to do outside of Ubuntu 16.04.

**Comment by JerichoJones** [comment]
@MatthewCroughan "do you use the newest driver from the amd webside or the driver from the
distribution?"
