### ISSUE TITLE
Windows / Nvidia: Detected default values don't work

### ISSUE THREAD

**Issue by UselessGuru** [fireice-uk/xmr-stak#592]
The default values created on first run are set too high:

System: Windows 10, Nvidia driver 23.21.13.8859
Screen res: 3820 x 2160

I need to set the following values
GTX1080ti --cuda-launch=64x72
GTX1070 --cuda-launch=53x64
GTX10603GB --cuda-launch=16x77

Anything higher results in an 'out of memory' error.

**Comment by psychocrypt** [comment]
please post the default settings suggested by the miner. Please copy past
it from nvidia.txt because the comments above the config gives me an
overview of the gpus.

**Comment by UselessGuru** [comment]
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1565745/nvidia.txt)

**Comment by fireice-uk** [comment]
Please reopen if the issue is still present in the latest version.
