### ISSUE TITLE
Support Debian 8 (compiling)

### ISSUE THREAD

**Issue by pSchaub** [fireice-uk/xmr-stak#594]
How can we compile XMR-Stak on Debian 8?

```
  CMake 3.1.0 or higher is required.  You are running version 3.0.2
```
I use the official debian repository.

This issue exists since https://github.com/fireice-uk/xmr-stak/pull/268

**Comment by roberth1990** [comment]
Why not upgrade to debian 9 which is now stable?

**Comment by pSchaub** [comment]
@roberth1990 We want to run XMR-Stak next to a Plesk environment which only supports Debian 8 until Q1/2018. Is there a way to run XMR-Stak on Debian 8?

**Comment by roberth1990** [comment]
Install cmake from backports: https://backports.debian.org/

**Comment by pSchaub** [comment]
I've installed G++ and Gcc to the latest versions:
```
g++ (Debian 7.2.0-17) 7.2.1 20171205
gcc (Debian 7.2.0-17) 7.2.1 20171205
```

But I still see this error message:
```
g++ version must be at least 5.1!
```

Did I miss to update a package?

**Comment by pSchaub** [comment]
Deleted the folder `build/CMakeFiles` and run `cmake ..` again - now it works!
