### ISSUE TITLE
Antivirus detects it as malware--don't have admin rights so cannot add as an exception

### ISSUE THREAD

**Issue by grzzyy** [fireice-uk/xmr-stak#597]
I'm using a computer that I don't have the admin login/password for (siblings computer, nothing sketchy) and unfortunately windows defender recognizes it as malware and immediately removes it. Is there a work around I can use?

**Comment by mrush842** [comment]
Unfortunately the easiest and safest way will be to get the admin password.

**Comment by mojimi** [comment]
Although you say is nothing sketchy, there are several other cases where it is very sketchy, many people would just install it on corporate/school computers (I'll admit I have tried it)

**Comment by JerichoJones** [comment]
@grzzyy No.
