### ISSUE TITLE
Slower hash rate after updating to v2.1.0

### ISSUE THREAD

**Issue by Ambrotos** [fireice-uk/xmr-stak#609]
I am doing CPU mining of Monero on several HP DL60Gen9 Xeon servers (2x Xeon E5-2609 v3s). This morning I upgraded one of them from xmr-stak v2.0.0-79154f7 to the latest (as of this writing) v2.1.0-31a0784. I am running CentOS 7, and I just did a git pull, deleted the ~/xmr-stak/build/* directory and  recompiled as described in your "How to compile in Linux" guide.

The problem I'm having is that when running v2.0.0 I was getting a total of around 380H/s, yet with v2.1.0 I'm seeing about 200H/s. As mentioned in your release announcement I deleted the previously-generated config.txt and cpu.txt and let v2.1.0 generate a new config on first startup. Both v2.0 and v2.1 seem to generate the same CPU configuration though; 2 of the cores in each CPU are configured as lowpower, and the remaining 4 are marked as "false" in that field. In v2.0 I was getting 45H/s for the lowpower cores, and 30H/s for the remainder. Now I'm seeing around 22H/s and 15H/s respectively. So, v2.1.0 has effectively cut my hashrate in half.

I've tried adjusting the lowpower configuration in cpu.txt (true, 1, 2, false, etc in various ratios) as well as enabling/disabling prefetch, and it seems like the auto-generated configuration is optimal... but still half of what it was.

Any thoughts on why I'm seeing such a huge degradation in performance? I've got 9 other machines still running v2.0.0 that I'm holding off on upgrading for the moment. They don't all have E5-2609s in them, but I'd like to understand what's going on here before I continue...

Thanks,

-A

**Comment by rodrigocalilo** [comment]
Same problem with GTX 1050, in v2.0 hashrate has 280, in v2.1 is 90H/s.

**Comment by coreburner** [comment]
i'm on 2.20 and gettin 346.8 h/s with this config
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1050 Ti architecture: 61
  //      memory: 3961/4096 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 72, "blocks" : 24,
    "bfactor" : 10, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,

afterburner settings 
223 cc 295 mc  fan on full

hope this helps
