### ISSUE TITLE
xmr-stak does not create cpu.txt and nvidia.txt and freeze everything

### ISSUE THREAD

**Issue by vlazy** [fireice-uk/xmr-stak#612]
I am trying to set up the new version to see if hashrate will be improved but xmr-stak does not create cpu.txt and nvidia.txt and freeze everything. 

I am running on Windows 7, with a bi-xeon cpu (24 cores) and 2x GTX 970.

Any idea why ? Thank you !

**Comment by DavidBruchmann** [comment]
virus scanner, Windows defender

**Comment by JerichoJones** [comment]
@DavidBruchmann <-- What he said. 👍

**Comment by vlazy** [comment]
Oh :o , so simple that I didn't thought about it. Kaspersky has an exclusion for the folder but seems it's not enough. Thank you guys for your answer !
