### ISSUE TITLE
Unable to get docker to work in CentOS 7

### ISSUE THREAD

**Issue by Dimitri2g** [fireice-uk/xmr-stak#617]
For some reason i cannot get docker to work. Please help as i am not sure what i need to do.

Did a yum install for docker and i verified it is running. Below is what i used and the result i get back.

Thanks in advance.

`#!/bin/bash

########################
# CentOS 7
########################
# CUDA is not going to work on CentOS/RHEL beacuse it's only support gcc-4 in these distributions: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
docker run --rm -it -v $PWD:/mnt centos:7 /bin/bash -c "
set -x ;
yum install -y -q centos-release-scl epel-release ;
yum install -y -q cmake3 devtoolset-7-gcc* hwloc-devel libmicrohttpd-devel make openssl-devel perl ;
scl enable devtoolset-7 - << EOF
mkdir /mnt/xmr-stak ;
cd /mnt/xmr-stak ;
cmake3 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF . ;
make ;
EOF
"

test -d centos_7 || mkdir centos_7
mv xmr-stak/bin/* centos_7
git -C xmr-stak clean -fd
`

Results

+ yum install -y -q centos-release-scl epel-release
warning: /var/cache/yum/x86_64/7/extras/packages/centos-release-scl-2-2.el7.centos.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for centos-release-scl-2-2.el7.centos.noarch.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
+ yum install -y -q cmake3 'devtoolset-7-gcc*' hwloc-devel libmicrohttpd-devel make openssl-devel perl
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/epel/packages/cmake3-data-3.6.3-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Public key for cmake3-data-3.6.3-1.el7.noarch.rpm is not installed
warning: /var/cache/yum/x86_64/7/centos-sclo-rh/packages/devtoolset-7-binutils-2.28-8.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f2ee9d55: NOKEY
Public key for devtoolset-7-binutils-2.28-8.el7.x86_64.rpm is not installed
Importing GPG key 0xF2EE9D55:
 Userid     : "CentOS SoftwareCollections SIG (https://wiki.centos.org/SpecialInterestGroup/SCLo) <security@centos.org>"
 Fingerprint: c4db d535 b1fb ba14 f8ba 64a8 4eb8 4e71 f2ee 9d55
 Package    : centos-release-scl-rh-2-2.el7.centos.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-9.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
install-info: No such file or directory for /usr/share/info/nettle.info
ValueError: SELinux policy is not managed or store cannot be accessed.
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/as.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/binutils.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/gprof.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/ld.info.gz
+ scl enable devtoolset-7 -
mkdir: cannot create directory '/mnt/xmr-stak': File exists
CMake Error: The source directory "/mnt/xmr-stak" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat ‘xmr-stak/bin/*’: No such file or directory
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

**Comment by rowanruseler** [comment]
https://gitlab.com/nvidia/cuda/blob/centos7/9.0/base/Dockerfile

Try that as a base, and see how it works.

**Comment by Dimitri2g** [comment]
so I am not sure if that is what i want. @rowanruseler is it possible for you to send me the syntax of the commands that i need to run. In the order that i need to run them? I am running a centos vm with 8 CPUs no GPU. I did a yum install docker so i know its installed i just don't know what to do from there.
Thanks in advance for you help.

**Comment by Dimitri2g** [comment]
docker run --rm -it -v $PWD:/mnt centos:7 /bin/bash -c "
> set -x ;
> yum install -y -q centos-release-scl epel-release ;
> yum install -y -q cmake3 devtoolset-7-gcc* hwloc-devel libmicrohttpd-devel make openssl-devel perl ;
> scl enable devtoolset-7 - << EOF
> cd /mnt/xmr-stak ;
> cmake3 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF . ;
> make ;
> EOF
> "
+ yum install -y -q centos-release-scl epel-release
warning: /var/cache/yum/x86_64/7/extras/packages/centos-release-scl-rh-2-2.el7.centos.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for centos-release-scl-rh-2-2.el7.centos.noarch.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
+ yum install -y -q cmake3 'devtoolset-7-gcc*' hwloc-devel libmicrohttpd-devel make openssl-devel perl
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/epel/packages/cmake3-3.6.3-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Public key for cmake3-3.6.3-1.el7.x86_64.rpm is not installed
warning: /var/cache/yum/x86_64/7/centos-sclo-rh/packages/devtoolset-7-gcc-7.2.1-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f2ee9d55: NOKEY
Public key for devtoolset-7-gcc-7.2.1-1.el7.x86_64.rpm is not installed
Importing GPG key 0xF2EE9D55:
 Userid     : "CentOS SoftwareCollections SIG (https://wiki.centos.org/SpecialInterestGroup/SCLo) <security@centos.org>"
 Fingerprint: c4db d535 b1fb ba14 f8ba 64a8 4eb8 4e71 f2ee 9d55
 Package    : centos-release-scl-rh-2-2.el7.centos.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-9.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
install-info: No such file or directory for /usr/share/info/nettle.info
ValueError: SELinux policy is not managed or store cannot be accessed.
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/as.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/binutils.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/gprof.info.gz
install-info: No such file or directory for /opt/rh/devtoolset-7/root/usr/share/info/ld.info.gz
+ scl enable devtoolset-7 -
CMake Error: The source directory "/mnt/xmr-stak" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
