### ISSUE TITLE
Segmentation fault (core dumped) on FreeBSD 11.1

### ISSUE THREAD

**Issue by klikfroggi** [fireice-uk/xmr-stak#619]
Hi I have successully compile xmr-stak on FreeBSD using dev. But when I try to run,, it crash.

hw.model: Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
hw.machine: amd64
hw.ncpu: 4

root@aphrodite:~/xmr-stak/build/bin # ./xmr-stak
[2017-12-20 00:46:14] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
[2017-12-20 00:46:14] : MEMORY ALLOC FAILED: mlock failed
[2017-12-20 00:46:14] : MEMORY ALLOC FAILED: mlock failed
[2017-12-20 00:46:14] : MEMORY ALLOC FAILED: mlock failed
[2017-12-20 00:46:14] : MEMORY ALLOC FAILED: mlock failed
[2017-12-20 00:46:14] : MEMORY ALLOC FAILED: mlock failed
-------------------------------------------------------------------
xmr-stak 2.1.0 8e38483

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-20 00:46:16] : Start mining: MONERO
Segmentation fault (core dumped)

**Comment by natorminer** [comment]
After compiling on FreeBSD 11.1, I also got the same error "Segmentation fault" when running.  I got past this by disabling one of the cpu build options.  I could be wrong, but I don't think this is related to FreeBSD 11.1, but the cpu.  Also, I haven't noticed a reduction in performance.  cpu: Intel Core i5 4210U.

cmake -DHWLOC_ENABLE=OFF

**Comment by rhavenn** [comment]
Yeah, does the same thing for me on a AWS instance. Adding the HWLOC_ENABLE=OFF fixes it as well. 

However, I think the problem is just like was mentioned in #509 . If I build it with the above flag it generates the cpu.txt file and then I can rebuild it without the above flag and use the previously generated cpu.txt and it works fine.

**Comment by klikfroggi** [comment]
Thank you guys. Now it is working fine after adding HWLOC_ENABLE=OFF. Sorry I didnt browse the threads before asking.
