### ISSUE TITLE
CL_DEVICE_NOT_FOUND Firepro V5800

### ISSUE THREAD

**Issue by msilvoli** [fireice-uk/xmr-stak#62]
First of all you guys are doing an awesome job, making possible for all of us to mine with different platforms.
I'm getting the following message:
Compiling code and initializing GPUs. This will take a while...
Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.
WARNING: AMD device not found

System: 2 x XEON L5630 12MB L3 24GB RAM HP server DL380 G6 Firepro V5800 installed as add on card with motherboard integrated graphics disabled on BIOS with OpenSUSE LEAP 42.1 running on metal.

I'm using FGLRX drivers since I couldn't install the AMDPRO in any opensuse version (42.1 is not compatible) and (42.2/ 42.3 the system freezes after install. First the Xorg and a few seconds after the entire system).
libOpenCL1 2.2.11-2.1 (from opensuse)
opencl-headers 2.2+git.20170617-1.2 (from opensuse)
fglrx64 15.302.3-1 (http://geeko.ioda.net/mirror/amd-fglrx/openSUSE_Leap_42.1/)
xmr-stak compiled with GCC 5.3.1, cmake 3.3.2-1.2 both from SUSE repo's

lspci -nnk | grep -A3 VGA report:
10:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Juniper XT [FirePro V5800] [1002:68a9]
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:2303]
	Kernel driver in use: fglrx_pci
	Kernel modules: radeon, fglrx

clinfo report attached: 
[clinfo-report.txt](https://github.com/fireice-uk/xmr-stak/files/1405762/clinfo-report.txt)

During the compiling process I can see:
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "2.0")

The thing is: I installed the opensuse normally and after I did the installation of libOpenCL1 and opencl-headers. Then I installed the fglrx driver that seems to overwrite the libOpenCL1, and maybe this is promoting the error.
If I remove the libOpenCL1 and headers and install only the fglrx drivers, the xmr-stak cannot compile because it needs the CL/cl.h file included in the package libOpenCL1 from opensuse....since I know, fglrx doesn't install CL/cl.h or am I missing something ?

PS: this is happing with xmr-stak-amd too !

Any ideas ? 
Thanks a lot !!!

**Comment by psychocrypt** [comment]
Please try to install only the opencl headers from your distribution and
than the fglx driver. Getting amd driver running is always a pain don't
give up. Maybe search also for howto's for equivalent desktop amd cards
from the same generation.
Sometimes the mesa driver and sametimes the fglx driver is needed,but I
think in your case fglx is fine.

**Comment by msilvoli** [comment]
Hi @psychocrypt 
Thanks for your response. I used this 2 days to try to put the things working but without success. 
I got your suggestions but it didn't work. Mesa drivers weren't installed before open this issue, only the fglrx so this is a real pain :- )
Both XMR-stak and the AMD version continued to not work. CPU miner is ok, getting 320H/s.
I upgraded Opensuse to 42.2 (but before I removed de fglrx drivers) then I installed the amdpro drivers to give another try - unsuccessful. Old video cards (Terascale2 cores) are completely incompatible with new amdpro drivers - specially the beta one release a few days ago. 
I installed ubuntu 16.04 and had the same problems and with 14.04 same thing. Today I decide to put Server 2012 R2 - OMG - to check if the video card has any problem (I believe it's not because on opensuse 42.1 it was working for other things, including the catalyst panel)
Linux is an amazing operating system (which I'm using for last 10 years) but without the correct drivers you can imagine.
Thanks a lot.

**Comment by psychocrypt** [comment]
Yes the vendors needs to do his homework driver installation can be a pain.
:-(
