### ISSUE TITLE
config.txt embedded inside the code

### ISSUE THREAD

**Issue by opala79** [fireice-uk/xmr-stak#621]
Congratulations to the people involved, it was great !!!

I would like to put the config.txt information already inside the source code, so when compiling would only result in an .exe file, how to do it?

Please provide as much as possible information to reproduce the issue.
# Basic information
  - Type of the CPU.
# Compile issues
 win 7 x64
# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

**Comment by oldschoola41** [comment]
I am also looking to do this.  I will post on here if i find something on how to do this.  I would like to then run it as a service.

**Comment by JayWalker512** [comment]
Since the miner just loads a text file, you can probably replace whatever function call loads the text file to a const char array hardcoded in a header file. I doubt the developers will do this for you.

I'm happy to do the work for a small fee though ;)

**Comment by oldschoola41** [comment]
Brandon,

I would be interested in your help for this.  What fee would you charge?
Also I have a junior developer that I would want you to just show him what
you do so we can then compile it in house on our own in case we want to
make changes to the hardcoded information later on.  Could you do this?

**Comment by opala79** [comment]
I really do not expect anyone to do it, but I'd like some help finding out where the text file is called, I've tried it but I find it confusing.

**Comment by JayWalker512** [comment]
Hi oldschoola41,

Yes, that all sounds fine. Could you email me directly at [my first name 
you used] @brandonfoltz.com so we may discuss fee and terms?

Thanks for your time.

**Comment by muyuxx** [comment]
hi guys 
how can i compile the configuration(pools ,wallet address) in  xmr-stak other than outside

**Comment by psychocrypt** [comment]
You can use command line options to configure the minimal required options.
The miner will always create configefiles out of this command line options.
