### ISSUE TITLE
Getting an error message:  "AMD CANNOT LOAD BACKEND LIBRARY: XMR-STAK_OPENCL_BACKEND.DLL"

### ISSUE THREAD

**Issue by skeelo58** [fireice-uk/xmr-stak#622]
I've been mining just fine the past few days, until one of my GPU's crashed earlier today for whatever reason.  I rebooted the machine, and now my XMR-STAK wont mine.  It's like XMR-STAK isn't detecting the GPU.

I ran clinfo, and I tried as best I could to capture it, as the window only stays open for like 5 seconds.  But here is what I got.

I did try to re-install the AMD blockchain drivers, but that didn't help at all.

Please help!

Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1
  Platform Name:                                 Intel(R) OpenCL
  Platform Vendor:                               Intel(R) Corporation
  Platform Extensions:                           cl_intel_dx9_media_sharing cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_fp64 cl_khr_gl_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2442.12)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices

  Platform Name:                                 Intel(R) OpenCL
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     8086h
  Max compute units:                             12
  Max work items dimensions:                     3
    Max work items[0]:                           256
    Max work items[1]:                           256
    Max work items[2]:                           256
  Max work group size:                           256
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1050Mhz
  Address bits:                                  64
  Max memory allocation:                         1662119117
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          128
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            16384
  Max image 3D height:                           16384
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    262144
  Global memory size:                            1662119117
  Constant buffer size:                          1662119117
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             65536
  Max pipe arguments:                            16
  Max pipe active reservations:                  1
  Max pipe packet size:                          1024
  Max global variable size:                      65536
  Max global variable preferred total size:      1662119117
  Max read/write image args:                     128
  Max on device events:                          1024
  Queue on device max size:                      67108864
  Max on device queues:                          1
  Queue on device preferred size:                131072
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     Yes
  Preferred platform atomic alignment:           64
  Preferred global atomic alignment:             64
  Preferred local atomic alignment:              64
  Kernel Preferred work group size multiple:     32
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    83
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   000001A0CDF04FD0
  Name:                                          Intel(R) HD Graphics 610
  Vendor:                                        Intel(R) Corporation
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                22.20.16.4836
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.1
  Extensions:                                    cl_intel_accelerator cl_intel_advanced_motion_estimation cl_intel_d3d11_nv12_media_sharing cl_intel_device_side_avc_motion_estimation cl_intel_driver_diagnostics cl_intel_dx9_media_sharing cl_intel_media_block_io cl_intel_motion_estimation cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_required_subgroup_size cl_intel_simultaneous_sharing cl_intel_subgroups cl_intel_subgroups_short cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_fp16 cl_khr_fp64 cl_khr_gl_depth_images cl_khr_gl_event cl_khr_gl_msaa_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_gl_sharing cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_khr_spir cl_khr_subgroups cl_khr_throttle_hints

  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     8086h
  Max compute units:                             2
  Max work items dimensions:                     3
    Max work items[0]:                           8192
    Max work items[1]:                           8192
    Max work items[2]:                           8192
  Max work group size:                           8192
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     4
  Native vector width double:                    2
  Max clock frequency:                           2900Mhz
  Address bits:                                  64
  Max memory allocation:                         1044067328
  Image support:                                 Yes
  Max number of images read arguments:           480
  Max number of images write arguments:          480
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    480
  Max size of kernel argument:                   3840
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               No
    Round to +ve and infinity:                   No
    IEEE754-2008 fused multiply-add:             No
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    262144
  Global memory size:                            4176269312
  Constant buffer size:                          131072
  Max number of constant args:                   480
  Local memory type:                             Global
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  131071
  Max pipe packet size:                          1024
  Max global variable size:                      65536
  Max global variable preferred total size:      65536
  Max read/write image args:                     480
  Max on device events:                          4294967295
  Queue on device max size:                      4294967295
  Max on device queues:                          4294967295
  Queue on device preferred size:                4294967295
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     Yes
  Preferred platform atomic alignment:           64
  Preferred global atomic alignment:             64
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     128

**Comment by psychocrypt** [comment]
is the dll file located in the xmr-stak folder

**Comment by skeelo58** [comment]
Here is what my XMR-STAK looks like

[2017-12-19 14:38:23] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled
[2017-12-19 14:38:23] : WARNING: backend NVIDIA disabled.
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
WARNING: AMD Backend disabled
[2017-12-19 14:38:23] : WARNING: backend AMD disabled.
[2017-12-19 14:38:23] : Starting 1x thread, affinity: 0.
[2017-12-19 14:38:23] : hwloc: memory pinned
[2017-12-19 14:38:23] : Fast-connecting to mine.sumo.fairpool.xyz:5555 pool ...
[2017-12-19 14:38:23] : Pool mine.sumo.fairpool.xyz:5555 connected. Logging in...
[2017-12-19 14:38:23] : Difficulty changed. Now: 2000.
[2017-12-19 14:38:23] : Pool logged in.

**Comment by skeelo58** [comment]
I checked, and the dll file was not in the XMR-STAK folder, so I went to the original downloaded zip file and copied/pasted the dll file into my XMR-STAK folder, and now XMR-STAK just crashes as soon as I open it.

**Comment by joelmusicman** [comment]
The DLL file is sometimes flagged by Windows Malware tools.

**Comment by skeelo58** [comment]
I figured it out. I'm not quite sure how it happened, but the dll files were deleted from the folder.

Strange that it would do it days after I started mining. 

I just found the original zip file I had downloaded and extracted the files again, and it was golden.

**Comment by iwipetillibleed** [comment]
I am having the same issue. one day my GPU just stopped mining :/ my dll file is missing from my folder now so im guessing thats the issue but everytime i try to extract it from the .zip windows quarantines it as a trojan. how do i get one that isnt infected?

**Comment by psychocrypt** [comment]
You can check the check sum of the files and trust us that we not do bad
things.
Or you compile the miner by your own, even than the will be flagged as
trojan.

**Comment by skeelo58** [comment]
Open your anti-virus program and find the part where you can add an exception or exclusion. Add the dll file itself and you should be good.

**Comment by iwipetillibleed** [comment]
awesome guys thanks. i hate windows :(

**Comment by psychocrypt** [comment]
me too :-)
