### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by toperx** [fireice-uk/xmr-stak#626]
**My english is bad, and cmd is russified.
Sorry.**

**If i compile soft with VS2015**

cd /d D:\xmr-stak-dep\140\
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsMSBuildCmd.bat"
set CMAKE_PREFIX_PATH=D:\xmr-stak-dep\140\hwloc;D:\xmr-stak-dep\140\libmicrohttpd;D:\xmr-stak-dep\140\openssl
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" -T v140,host=x64 ..
cmake --build . --config Release --target install

**i got error**

D:/xmr-stak-dep/140/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu(9): fatal error C1083: Cannot open include file: 'device_functions.hpp': No  such file or directory [D:\xmr-stak-dep\140\build\xmrstak_cuda_backend.vcxproj]

**If i compile soft in VS2017**

cd /d D:\xmr-stak-dep\141\
"D:\VS_comm_17\Common7\Tools\VsMSBuildCmd.bat"
set CMAKE_PREFIX_PATH=D:\xmr-stak-dep\141\hwloc;D:\xmr-stak-dep\141\libmicrohttpd;D:\xmr-stak-dep\141\openssl
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake --build . --config Release --target install

 **i got error**

D:\VS_comm_17\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" завершилась с кодом 1. [D:\xmr-stak-dep\141\build\xmrstak_cuda_backend.vcxproj]

**What am I doing wrong?**

**Comment by phreaker0** [comment]
I also hit this error with the current cuda9.1, i got compiling going by commenting out that missing include in "cuda_extra.cu", but I didn't tried to run it.

**Comment by fvini113** [comment]
Same here.
