### ISSUE TITLE
Programmatic Configuration

### ISSUE THREAD

**Issue by jgillich** [fireice-uk/xmr-stak#627]
I'm using xmr-stak as a library in my program. I imagine this issue could also be relevant for the upcoming xmr-stak UI that you guys are working on.

jconf is the primary method to configure xmd-stak, and it's used all over the place. My biggest issues with it are:

1. A actual file on disk is required for it to work, there's no way to set config values programmatically
2. Backends (e.g. cpu) write config files 

Both are mostly fine when xmr-stak is a cli program, but rather bad when it's a library.

Are there any plans to rework configuration to make it a bit more flexible? Ideally the cli would handle everything related to local files and executor would simply receive a config struct.

I could also tackle this, but I haven't touched C++ in years.

**Comment by DavidBruchmann** [comment]
Is there a problem to create a config-file by GUI if required and start xmr-stak only if that's found?

**Comment by jgillich** [comment]
The problem with it is that it's completely pointless to write out a file that you're going to throw away anyway. It's not a big deal, but I like clean code free of such workarounds.

**Comment by DavidBruchmann** [comment]
I felt some discomfort about improving those general usability-features among the devs as it would increase the option for misusage too and xmr-stak is already flagged as virus.

**Comment by DavidBruchmann** [comment]
BTW: check-out
```
.\xmr-stak.exe --help
```
on commandline (cmd / powershell) if you never did already.

**Comment by jgillich** [comment]
Not sure I follow. This is a matter of internal code organization and not user-facing at all.

**Comment by DavidBruchmann** [comment]
Yeah but usability is not only related to user-interface but also to you as programmer.
Don't mind, I just wrote an impression what I read in the topics here, perhaps you find some support.

**Comment by psychocrypt** [comment]
@jgillich I will refactor some parts for the gui. I am still thinking about which way is the best and how information will be passed from the GUI to the miner.

**Comment by jgillich** [comment]
Sounds good, let me know if there's anything I can help with.
