### ISSUE TITLE
Freezing, dont do anything

### ISSUE THREAD

**Issue by PFFyodor** [fireice-uk/xmr-stak#628]
latest version
--noCPU
freezing - dont do anything, dont closing or killing and pc not rebooting, needs hot shutdown PC 
try without --noCPU options - same result

config inside, was maked auto by .exe with my params of pool and etc

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1574391/config.txt)

**Comment by psychocrypt** [comment]
If your pc is freezing than it is an driver issue.

**Comment by PFFyodor** [comment]
not pc, software window, blank ms-dos window and nothing, not closing, process not killing

**Comment by rafik-z** [comment]
Got the same issue on 2 computers (both i5, one with 1x GTX960 + 1x GTX 1060 and the other with 1x Rx570). Can't reboot nor kill the process.

**Comment by fvini113** [comment]
Same ... =(

**Comment by RaHery** [comment]
Same thing for me ...
I have 5 vega ; when i run the miner with just only 3 vega, everything is fine. But with 4 vega and more, the miner just hangs and freezes, no feedback, nothing.
Frustrating ... :(

**Comment by psychocrypt** [comment]
increase the virtual memory

**Comment by RaHery** [comment]
i've set 60000 already (per vega.minningguides.com). ok, i'll try with more. 
Thansk for your reply.

**Comment by RaHery** [comment]
I mean 60000 Mo
