### ISSUE TITLE
Do not open another window when already elevated

### ISSUE THREAD

**Issue by huserbg** [fireice-uk/xmr-stak#629]
When you run the miner without `--noUAC`, it always opens a new window, even if it has been run as administrator.
I prefer to open elevated command prompt first and then run the miner, this way if I press Ctrl+C the window is not closed.
My request is to check whether the process is already elevated and if yes, behave like when it's executed with `--noUAC`.

**Comment by bomb-on** [comment]
This is bugging me too... I actually tried to modify [relevant lines](https://github.com/fireice-uk/xmr-stak/blob/30888a31368d6d1e2f459e611b634df39cbcc857/xmrstak/cli/cli-miner.cpp#L341) but I couldn't make it close the window automatically... It might me just me and my limited C++ knowledge.

**Comment by fireice-uk** [comment]
This will be addressed in #649 - we will roll a bugfix release before xmas

**Comment by bomb-on** [comment]
@fireice-uk Awesome! Thanks a lot!

**Comment by fireice-uk** [comment]
It is rolled out! Closing as the bug has been fixed.
