### ISSUE TITLE
SOCKET ERROR -  minergate.com

### ISSUE THREAD

**Issue by fadmax66** [fireice-uk/xmr-stak#631]
SOCKET ERROR - [xdn-xmr.pool.minergate.com:45790] CALL error: Timeout while waiting for a reply

"wallet_address" : "my_address_of_minergate@gmail.com" is error

when "wallet_address" : "any_without_@" is OK

xmr-stak cannot transfer the  wallet address in the form of the e-mail address for minergate.com

**Comment by DavidBruchmann** [comment]
You've to enter your wallet address, not the email.
In the monero-GUI it can be found at the Navi-Point "Receive"

**Comment by fadmax66** [comment]
minergate.com don't nave wallet address

**Comment by DavidBruchmann** [comment]
then you have to create one.
You can do it online on some pages or you can do it with the gui.
Probably the commandline-tools can do it too.

**Comment by DavidBruchmann** [comment]
You've to save it well, if it's lost any values stored in it are lost too.
And don't forget the password you're creating too.

**Comment by fadmax66** [comment]
It is necessary to make corrections to a program code

**Comment by fadmax66** [comment]
xmr-stak cannot transfer the  wallet address in the form of the e-mail address for minergate.com

**Comment by DavidBruchmann** [comment]
Wallet address and e-mail are different things, nobody needs your email to transfer to your wallet!
But apart from that minergate is suspicious of possible share skimming!
Better chose another pool here: http://moneropools.com/

**Comment by fadmax66** [comment]
I have the account on a minergate.com. Minergate.com don't have wallet address. e-mail address is wallet address

**Comment by fadmax66** [comment]
for example: -o stratum+tcp://bcn.pool.minergate.com:45550 -u my_e-mail_for_my_account  -p x

**Comment by DavidBruchmann** [comment]
If you're right then that's against the claim of monero to be anonymous and un-trace-able.
Like I said, if you've never yet any coins there use another pool.

**Comment by joelmusicman** [comment]
Minergate uses its own closed source program, probably so they can skim your hashes.  Can't use xmr-stak.

**Comment by lh1008** [comment]
@joelmusicman don´t use minergate :)

**Comment by psychocrypt** [comment]
This is an miner gate issue. Miner gate is closing the communication session very fast. Please open an issue on the miner gate website.
