### ISSUE TITLE
How to build the miner on PPC64 of centos?

### ISSUE THREAD

**Issue by xlhzly** [fireice-uk/xmr-stak#632]
# Basic information
  IBM Power7

# Compile issues
 Contos for PPC64 7.2
  
Dear 
I want to build xmr-stak on IBM power. 
But centos-release-scl epel-release , cmake3,devtoolset-4-gcc* hwloc-devel can not be found in yum mirror site.   Would you tell me which site provide these packages。Thanks。

**Comment by psychocrypt** [comment]
sry ppc is not supported.
