### ISSUE TITLE
Win10 Latest Release GTX750ti crash

### ISSUE THREAD

**Issue by vans163** [fireice-uk/xmr-stak#634]
On windows 10 64 bit I get a crash with a EVGA GTX 750 ti.

Nvidia-driver 388.71-desktop-win10-64bit-international-whql.exe

Latest release. Version: xmr-stak 2.1.0 30888a3
No overclocks.

It happens immediately once connected to the pool, once the GPU occupies its memory and starts the first hash.

As a sanity test dtsm miner works on equihash just fine with the same system.

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 750 Ti architecture: 50
  //      memory: 1686/2048 MiB
  //      smx: 5
  { "index" : 0,
    "threads" : 32, "blocks" : 15,
    "bfactor" : 0, "bsleep": 0,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],

[CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

**Comment by psychocrypt** [comment]
please reduce threads in `nvidia.txt`  or increase bfactor to 8

**Comment by vans163** [comment]
Its weird because the same card works fine on ubuntu 16.04 with these settings. But your correct I lowered the settings and it works now.
