### ISSUE TITLE
Adding donation percent to my wallet

### ISSUE THREAD

**Issue by BobiraS** [fireice-uk/xmr-stak#635]
Hello,

I compiled the CPU .exe file but I have a question. I want to add plus 1% donation to my wallet and 1% to another wallet. Can I do that?

Thank you in advance

**Comment by psychocrypt** [comment]
sry this is not possible without code changes.

**Comment by BobiraS** [comment]
Thank you for the answer. Are you aiming to do that? there are many cases I'm thinking that need for.

Thank you in advance

**Comment by psychocrypt** [comment]
It is planed that the user get the option to define multiple pools and use
the weight to split the hash power to different pools over time.
