### ISSUE TITLE
compile error linux oracle 6

### ISSUE THREAD

**Issue by solustore-h** [fireice-uk/xmr-stak#639]
[root@localhost build]# cmake3 ..
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!

-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/build/CMakeFiles/CMakeOutput.log".

**Comment by solustore-h** [comment]
[root@localhost ~]# gcc --version
gcc (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by NmxMilk** [comment]
what's output of:
$ g++  --version

**Comment by psychocrypt** [comment]
remove all files in the build folder and run cmake again and post the dull
output.

**Comment by solustore-h** [comment]
[root@mcahost ~]# g++ version
g++: error: version: Arquivo ou diretório não encontrado
g++: fatal error: no input files
compilation terminated.

**Comment by solustore-h** [comment]
psychocrypt removed from all the files in the build folder

[root@localhost build]# cmake3 ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (message):
  g++ version must be at least 5.1!


-- Configuring incomplete, errors occurred!
See also "/root/xmr-stak/build/CMakeFiles/CMakeOutput.log".

**Comment by solustore-h** [comment]
how to install the correct version of g ++ in oracle linux?

**Comment by solustore-h** [comment]
@psychocrypt 

before running cmake3 .. in build

[root@localhost ~]# g++ --version
g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

after running cmake3 .. in build

[root@locahost ~]# g++ version
g++: error: version: Arquivo ou diretório não encontrado
g++: fatal error: no input files
compilation terminated.

**Comment by NmxMilk** [comment]
cmake seems to find version 4.4.7 because it is in default cmake search path.
Try this:
$ CC=/opt/rh/devtoolset-6/root/usr/bin/gcc
$ CXX=/opt/rh/devtoolset-6/root/usr/bin/g++
$ cmake
adapt the path to reflect your real path (use which g++)

**Comment by solustore-h** [comment]
@NmxMilk @psychocrypt @rsanheim @scottmckenzie @fALKENdk 

/tmp/ccsifhKN.s: Assembler messages:
/tmp/ccsifhKN.s:238: Error: no such instruction: `rorx $16,%ecx,%ecx'
/tmp/ccsifhKN.s:244: Error: no such instruction: `rorx $12,%esi,%esi'
/tmp/ccsifhKN.s:250: Error: no such instruction: `rorx $8,%ecx,%ebx'
/tmp/ccsifhKN.s:257: Error: no such instruction: `rorx $7,%esi,%esi'
/tmp/ccsifhKN.s:258: Error: no such instruction: `rorx $16,%edx,%edx'
/tmp/ccsifhKN.s:263: Error: no such instruction: `rorx $12,%edi,%ecx'
/tmp/ccsifhKN.s:271: Error: no such instruction: `rorx $8,%edx,%r10d'
/tmp/ccsifhKN.s:277: Error: no such instruction: `rorx $7,%ecx,%ecx'
/tmp/ccsifhKN.s:283: Error: no such instruction: `rorx $16,%r12d,%r12d'
/tmp/ccsifhKN.s:288: Error: no such instruction: `rorx $12,%edi,%edi'
/tmp/ccsifhKN.s:291: Error: no such instruction: `rorx $8,%r12d,%r12d'
/tmp/ccsifhKN.s:296: Error: no such instruction: `rorx $7,%edi,%edi'
/tmp/ccsifhKN.s:300: Error: no such instruction: `rorx $16,%r9d,%r9d'
/tmp/ccsifhKN.s:303: Error: no such instruction: `rorx $12,%r14d,%ebx'
/tmp/ccsifhKN.s:313: Error: no such instruction: `rorx $8,%r9d,%r9d'
/tmp/ccsifhKN.s:318: Error: no such instruction: `rorx $7,%ebx,%ebx'
/tmp/ccsifhKN.s:322: Error: no such instruction: `rorx $16,%r12d,%r12d'
/tmp/ccsifhKN.s:326: Error: no such instruction: `rorx $12,%esi,%esi'
/tmp/ccsifhKN.s:331: Error: no such instruction: `rorx $8,%r12d,%edx'
/tmp/ccsifhKN.s:337: Error: no such instruction: `rorx $7,%esi,%r12d'
/tmp/ccsifhKN.s:344: Error: no such instruction: `rorx $16,%r10d,%edx'
/tmp/ccsifhKN.s:349: Error: no such instruction: `rorx $12,%ebx,%ebx'
/tmp/ccsifhKN.s:357: Error: no such instruction: `rorx $8,%edx,%edx'
/tmp/ccsifhKN.s:362: Error: no such instruction: `rorx $7,%ebx,%edx'
/tmp/ccsifhKN.s:371: Error: no such instruction: `rorx $16,%r9d,%r9d'
/tmp/ccsifhKN.s:375: Error: no such instruction: `rorx $12,%ecx,%ecx'
/tmp/ccsifhKN.s:378: Error: no such instruction: `rorx $8,%r9d,%eax'
/tmp/ccsifhKN.s:383: Error: no such instruction: `rorx $7,%ecx,%eax'
/tmp/ccsifhKN.s:395: Error: no such instruction: `rorx $16,%ecx,%ecx'
/tmp/ccsifhKN.s:399: Error: no such instruction: `rorx $12,%edi,%edi'
/tmp/ccsifhKN.s:403: Error: no such instruction: `rorx $8,%ecx,%ecx'
/tmp/ccsifhKN.s:408: Error: no such instruction: `rorx $7,%edi,%eax'
/tmp/ccsifhKN.s:847: Error: no such instruction: `shrx %eax,(%rbx),%eax'
/tmp/ccsifhKN.s:850: Error: no such instruction: `shrx %eax,(%rbx),%eax'
/tmp/ccsifhKN.s:853: Error: no such instruction: `shrx %eax,(%rbx),%eax'
/tmp/ccsifhKN.s:862: Error: no such instruction: `shrx %eax,4(%rbx),%eax'
/tmp/ccsifhKN.s:871: Error: no such instruction: `shrx %eax,8(%rbx),%eax'
/tmp/ccsifhKN.s:880: Error: no such instruction: `shrx %eax,12(%rbx),%eax'
/tmp/ccsifhKN.s:889: Error: no such instruction: `shrx %eax,16(%rbx),%eax'
/tmp/ccsifhKN.s:898: Error: no such instruction: `shrx %eax,20(%rbx),%eax'
/tmp/ccsifhKN.s:907: Error: no such instruction: `shrx %eax,24(%rbx),%eax'
/tmp/ccsifhKN.s:916: Error: no such instruction: `shrx %eax,28(%rbx),%eax'
make[2]: ** [CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o] Erro 1
make[1]: ** [CMakeFiles/xmr-stak-c.dir/all] Erro 2
make: ** [all] Erro 2

**Comment by Algeroth123** [comment]
scl enable devtoolset-6 bash
than cmake3 in fresh dir, and than make...

**Comment by solustore-h** [comment]
Veryyy GOOD! 
Server is OK. 
thak´s! 
thank you people
