### ISSUE TITLE
CPU threads massive hashrate differences

### ISSUE THREAD

**Issue by jimk98** [fireice-uk/xmr-stak#640]
Just curious as to why i have such a massive difference on my thread hashrates. Am i going wrong somewhere? 

Any help or input would be appreciated and if any other info is needed ill see what i can do.

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   70.4 |   70.1 |   72.2 |  1 |   15.0 |   15.0 |   14.6 |
|  2 |   15.1 |   15.1 |   14.7 |

-----------------------------------------
"cpu_threads_conf" :
[
    	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },

],

------------------------------------------

# Basic information
  AMD Athlon 860K
  GTX 645 & GT 640 (Until new GPUs arrive)

# Compile issues
  Windows 10 64 Bit

# Stability issue
  GPU both overclocked
  CPU Stock freq and voltages

**Comment by bomb-on** [comment]
How many threads are reported in your Task Manager/Performance tab?

**Comment by jimk98** [comment]
Task manager reports 4 cores and 8 logical processors

**Comment by psychocrypt** [comment]
Do you compiled the miner by your own?
Please remove cpu.txt and let the miner generate a config. You changed the
config by hand and used the weong core ids, Thats the reason for the hash
rate difference.

**Comment by jimk98** [comment]
I Don't.

The autoconfig only uses one thread. What is the proper way to go about manually setting it up?

**Comment by psychocrypt** [comment]
your cpu has only 4 mb cachse thetefore you can only use 2 threads at all.
Could you remive please the cpu.txt start the miner and post the terminal
output from the start.

**Comment by bomb-on** [comment]
@jimk98 Autogenerated `cpu.txt` has a nice explanation how to use this:

```
affine_to_cpu -  This can be either false (no affinity), or the CPU core number. Note that on hyperthreading 
                 systems it is better to assign threads to physical cores. On Windows this usually means selecting 
                 even or odd numbered cpu numbers. For Linux it will be usually the lower CPU numbers, so for a 4 
                 physical core CPU you should select cpu numbers 0-3.
```

In general, if you are using hyperthreading, you should use even or odd mubers:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
]
```
If you are not using hyperthreading, you will have ordered numbers, but keep in mind to leave at least 1 core free:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
]
```

**Comment by jimk98** [comment]
[2017-12-21 14:58:29] : Start mining: MONERO
[2017-12-21 14:58:29] : Starting NVIDIA GPU thread 0, no affinity.
[2017-12-21 14:58:29] : Starting NVIDIA GPU thread 1, no affinity.
[2017-12-21 14:58:29] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-12-21 14:58:29] : WARNING: backend AMD disabled.
[2017-12-21 14:58:29] : Autoconf FAILED: Failed to allocate a PU.. Create config for a single thread.
[2017-12-21 14:58:29] : CPU configuration stored in file 'cpu.txt'
[2017-12-21 14:58:29] : Starting 1x thread, no affinity.
[2017-12-21 14:58:29] : Fast-connecting to monerohash.com:3333 pool ...
[2017-12-21 14:58:29] : Pool monerohash.com:3333 connected. Logging in...
[2017-12-21 14:58:30] : Difficulty changed. Now: 5000.
[2017-12-21 14:58:30] : Pool logged in.

**Comment by PadaKwaak** [comment]
I'm also having the same issue where each time I start up _xmr-stak 2.1.0 30888a3_ it gives me a different total H/s with my i7 8700k @ 4.8GHz on all cores, 2x 8GB DDR4 @ 3200MHz CL16, Windows 10 x64 v1709.

Most of the time I can get 370H/s and if I'm lucky I can launch it and then get 460H/s. I'm not sure if it has to do with Windows 10's RAM random memory allocation or something of that sort.
So I often restart my PC using `shutdown.exe /r /t 0` and even after the restart I may have to try launching xmr-stak twice to get a decent hash rate.

I have not tried Linux yet to see if its more consistent.

My config looks like:
```
"cpu_threads_conf" :
[   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 }]
```

For instance here is how it would look for 370H/s:
```
HASHRATE REPORT - CPU
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 45.8 | (na) | (na) |  1 | 51.2 | (na) | (na) |
|  2 | 89.6 | (na) | (na) |  3 | 51.1 | (na) | (na) |
|  4 | 87.3 | (na) | (na) |  5 | 45.2 | (na) | (na) |
-----------------------------------------------------
Totals:   370.3 (na) (na) H/s
Highest:  371.1 H/s
```

And this is how it looks at 468.5H/s (via HTTP in daemon mode):
```
| ID |  10s |  60s |  15m |
|  0 | 75.0 | 73.9 | (na) |
|  1 | 79.8 | 79.2 | (na) |
|  2 | 82.6 | 82.0 | (na) |
|  3 | 80.6 | 79.9 | (na) |
|  4 | 77.4 | 76.4 | (na) |
|  5 | 73.0 | 72.6 | (na) |
-----------------------------------------------------
Totals:   468.5 464.0 (na) H/s
Highest:  468.4 H/s
```

**Comment by akostadinov** [comment]
Agreed with @PadaKwaak , I've setup 2 threads but when I hit `h` I only see statistics for one of the threads.

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

**Comment by greydaymine** [comment]
Try changing your low power setting from false to 5.
