### ISSUE TITLE
Disable some GPU (not all)

### ISSUE THREAD

**Issue by rwlf** [fireice-uk/xmr-stak#643]
I am using for speed reason a different miner with my two Vegas. 
But I also have a AMD A7-9600 as CPU in same system and want to use this CPU and iGPU for mining with XMR Stak. 
How can I exclude the two Vega cards in XMR Stak?

**Comment by rwlf** [comment]
Sry, it‘s an A8-9600 with a R7 iGPU. A bit confusing.
iGPU has index 0, Vegas have 1 and 2.

**Comment by bomb-on** [comment]
If you are using the latest xmr-stak version, you should edit your `cpu.txt` and `amd.txt` files accordingly... If you take a look at `amd.txt` you should see something similar to:

```
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
    { "index" : 2, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 1, "strided_index" : true },
],
```

Once you figure out for sure which `index` is used by Vega, just remove it from this file and re-run the program...

**Comment by rwlf** [comment]
Maybe I should just have tried.. Thought about deleting this lines, but wasn't sure about it. Could have been intensity value, too.
Thank u. It works.
