### ISSUE TITLE
Performance tracking and Hashrate output not working?

### ISSUE THREAD

**Issue by B-Hard** [fireice-uk/xmr-stak#644]
Please provide as much as possible information to reproduce the issue.

# Basic information
  Intel Xeon E5-2620 v4 @2.10GHz
  - 
# Issue with the execution
  - Do you compiled the miner by our own?
No
Version: xmr-stak/2.1.0/30888a3/master/win/nvidia-amd-cpu/aeon-monero/20

I don't know how I can check my current mining performance (ie Monero I mined already) ?
I read something about shares I get but didn't see that in the output.

I would too like to know my hashrate in the output file?

Here I post a short output of my log.

`[2017-12-21 07:05:13] : Difficulty changed. Now: 10830.
[2017-12-21 07:05:13] : New block detected.
[2017-12-21 07:05:15] : Result accepted by the pool.
[2017-12-21 07:05:47] : Fast-connecting to dev pool ...
[2017-12-21 07:05:47] : Dev pool connected. Logging in...
[2017-12-21 07:07:50] : Difficulty changed. Now: 10770.
[2017-12-21 07:07:50] : Switching back to user pool.
[2017-12-21 07:07:51] : New block detected.
[2017-12-21 07:08:13] : Difficulty changed. Now: 10710.
[2017-12-21 07:08:13] : New block detected.
[2017-12-21 07:08:32] : Result accepted by the pool.
[2017-12-21 07:09:32] : Result accepted by the pool.
[2017-12-21 07:09:55] : Result accepted by the pool.
[2017-12-21 07:10:14] : New block detected.
[2017-12-21 07:10:26] : New block detected.
[2017-12-21 07:10:58] : Result accepted by the pool.
[2017-12-21 07:11:13] : Difficulty changed. Now: 10680.`

I'm using the pool.xmrminer.de:7777

Thanks for your help!

**Comment by bomb-on** [comment]
You cannot see how much Monero you mined already in mining program. This is the information which is available in your pool.

Shares are related to mining rewards. When you are mining in a pool and the block is found, rewards are divided to miners based on how many shares they had in that block.

You can see info about your shares in xmr-stak by pressing `r` (shortcut for "results"). It will show you how many "good" or "bad results" you sent to pool.

You can also press `c` for "connection" details.

And about the hash rate, you can either press `h` in xmr-stak (shortcut for "hash rate") or if you defined `httpd_port` in your `config.txt` you can see it by visiting `127.0.0.1:PORT` in your browser (replacing `PORT` with the actual port number, of course). On that website, you will have access to all the information provided by those 3 shortcuts I mentioned.

**Comment by B-Hard** [comment]
Got it setup ;) Thanks! I used a path instead of a pure filename in  the config.txt at the output command.

Do you know how I can tweak the config to use 100% of my CPU's?

Here I attach a screenshot where you can see the usage is at 70%... 

THANKS!
![cpu usage](https://user-images.githubusercontent.com/16137558/34269241-db417c0e-e683-11e7-8eec-9b5731b4c23e.png)

**Comment by Elycin** [comment]
Modify your `cpu_threads_conf` JSON array to contain 16 entries, each entry starting with an affinity at 0 and ending in 15 (count by indicies).

Your mileage may vary with `low_power_mode` being enabled or disabled, but an ideal configuration for that array would look like this:
```json
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 13 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 15 },
],
```
 
(Your system might become sluggish with full CPU usage on all of your cores)

**Comment by B-Hard** [comment]
OH YESS! Thank you very much - 100% Power now ;)

**Comment by psychocrypt** [comment]
You will have less hash rate with 100% cpu usage instead of 70% for the
most systems. Remove the cpu.txt file and let te miner generate the config.
This is mostly the config with the highest hash rate.
If you tweak the config take care that the hash rate shown if you press the
key `h` is not goning down.

**Comment by B-Hard** [comment]
You're right , just wanted to reply again about that - Will use the default config. Thank you!
