### ISSUE TITLE
CPU Throttling?

### ISSUE THREAD

**Issue by runningwithbeer** [fireice-uk/xmr-stak#650]
I've been considering the cpu.txt file. Is there a way for 'throttling' or will xmr-stak simply use 100% of the CPUs selected? My CentOS VM has 8 vCPUs and I deleted 4 of them in the cpu.txt file. Below is what I have now. Ideally I'd like to see about 50% usage across all 8...

    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 3 },

Thanks

**Comment by crazymagicmushroom** [comment]
Hi, I am not an expert but as far as I know, its all about the cache of your cpus. I have got 72 threads but I get the highest speed with 44 threads only (%60 loaded)..  I really worked hard to increase the speed but I couldna

**Comment by runningwithbeer** [comment]
I'm actually trying to use less CPU

**Comment by seankibler** [comment]
There isn't a way to do that within this miner that I know of. You can easily do it with **cpulimit** which you might already have but if not is surely available. I installed it on my Mac via Homebrew. I had a config similar to yours mining CPU only on a 2.7Ghz Intel i7 getting ~300 H/s @ ~400% usage. I found the PID of xmr-stak and did **cpulimit -l 100 -p [pid]** and usage went from ~400% to ~100%. Now I'm getting ~85 H/s.

I reduced my config from 8 cores to 4 and turned on low power mode to reduce the strain on my laptop and be able to hash all day while I use it. CPU cores stay around 60C without any cpulimit.

Hope that helps.

**Comment by potholiday** [comment]
Any idea how to throttle CPU. I am also trying to mine from my laptop so I need a config with low cpu and thread usage. I use laptop for my work all day long so I want to keep the mining in the background with very small resource usage. Any idea how to do it. I am new here.

**Comment by seankibler** [comment]
I literally just explained a solution for unix based platforms. If you are using Windows you'll need to find another solution. Search the nets for cpulimit windows and maybe you'll find something useful.

**Comment by JerichoJones** [comment]
![image](https://user-images.githubusercontent.com/13205729/34651175-ac7b1d84-f39a-11e7-9710-8361c7ef5ee5.png)

**Comment by jonhassall** [comment]
To reduce the priority in Windows, try:
wmic process where name="xmr-stak.exe" CALL setpriority "below normal"
