### ISSUE TITLE
Please tell me how to disable GPU on XMR-STAK

### ISSUE THREAD

**Issue by crazymagicmushroom** [fireice-uk/xmr-stak#651]
Hi folks, I only wanna do mining with my cpus on xmr stak

" --noGPU " command is not working.

I have tried to delete the threads and make the values lower but it's still sucking it's power :(

Is it possible to disable it completely ?

Thank you

**Comment by psychocrypt** [comment]
--noAMD and --noNVIDIA

--help will show you all options.

**Comment by crazymagicmushroom** [comment]
Thank you so much man I really do appreciate it!

**Comment by rakicluca** [comment]
I don't know when to put this command... Please help me ;)
