### ISSUE TITLE
[Not an Issue] Do you have any other wallets

### ISSUE THREAD

**Issue by nischkar** [fireice-uk/xmr-stak#653]
I would like to support further development.
Do you have a bitcoin wallet?

**Comment by bomb-on** [comment]
I don't think they have, but I can share mine and hold for them ;)

**Comment by fireice-uk** [comment]
@nischkar You can use https://s hapeshift.io/ to send us XMR. If you want to support development, please have a look here - https://www.reddit.com/r/MoneroMining/comments/7e1n5j/independent_community_fundraiser_for_gui_miner/
