### ISSUE TITLE
Doesn't support the highest Hashrate on NVIDIA Tesla V100

### ISSUE THREAD

**Issue by heliumsoft** [fireice-uk/xmr-stak#654]
I am mining the XMR using NVIDIA Tesla V100(5300 cuda cores). I am using 4 x v100 Gpus and it has 6 ~ 8kh/s. 
I need the highest hashrate in Tesla V100. 
if you have any good solution, please let me know it. 

Thread info 

gpu : Tesla V100-SXM2-16GB architecture : 70

{
   "index" : 0,
"threads": 30,
"blocks": 240,
"bfactor": 6,
"bsleep" : 25,
"affine_to_cpu" : false,
"sync_mode" : 3
}

**Comment by bomb-on** [comment]
8 KH/s for 4 cards seems like a decent hash rate to me... Do you expect even more of it? If so, what hash rate do you expect from a single card?

**Comment by netxecute** [comment]
The only entry in http://monerobenchmarks.info/ for the tesla v100 shows 1677H/s for one card.  I think you are doing alright.

**Comment by JerichoJones** [comment]
Try
CUDA Cores / Streaming Multiprocessors = Threads

**Comment by andrewpsp** [comment]
I'm running one Tesla v100 @  1677H/s  and I firmly believe its absolutely ridiculous no use of tensor core library etc ( Dust's of C lang books)
