### ISSUE TITLE
XMR Miner not using my GPU resulting in extremely low hashrates

### ISSUE THREAD

**Issue by eduguy** [fireice-uk/xmr-stak#656]
# Basic information
Pentium G3258
GTX 760
Windows 10

![Miner](https://user-images.githubusercontent.com/34255728/34286531-16dc29b4-e696-11e7-9ce0-9581f79ec9af.png)

The miner does not seem to want to use my GPU properly. The usage spikes every once in awhile but otherwise stays at around idle.

**Comment by psychocrypt** [comment]
please post the file nvidia.tyt

**Comment by eduguy** [comment]
/*
 * GPU configuration. You should play around with threads and blocks as the fastest settings will vary.
 * index         - GPU index number usually starts from 0.
 * threads       - Number of GPU threads (nothing to do with CPU threads).
 * blocks        - Number of GPU blocks (nothing to do with CPU threads).
 * bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * sync_mode     - method used to synchronize the device
 *                 documentation: http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g69e73c7dda3fc05306ae7c811a690fac
 *                 0 = cudaDeviceScheduleAuto
 *                 1 = cudaDeviceScheduleSpin - create a high load on one cpu thread per gpu
 *                 2 = cudaDeviceScheduleYield
 *                 3 = cudaDeviceScheduleBlockingSync (default)
 *
 * On the first run the miner will look at your system and suggest a basic configuration that will work,
 * you can try to tweak it from there to get the best performance.
 *
 * A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 760 architecture: 30
  //      memory: 1685/2048 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 40, "blocks" : 18,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by bomb-on** [comment]
This works for my card, I'm getting around 300 H/s with this config... Replace your `nvidia.txt` with this and try it out:

```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 760 architecture: 30
  //      memory: 1685/2048 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 24, "blocks" : 18,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],
```

**Comment by eduguy** [comment]
I'm using those exact same settings but I'm only getting 70 h/s. It seems like the same issue where the GPU usage stays really low and then spikes to 100 before going back to 0 again. It's only running at 50C so I'm not sure what the issue is.

**Comment by bomb-on** [comment]
Hm, I forgot to say that my cards was never overclocked, modified or messed around with in any way at all... I don't even have installed Afterburner or anything similar... Not sure how much difference that makes in the whole setup...

**Comment by eduguy** [comment]
I overclocked for a bit probably 1 year back but I didn't end up running it because it wasn't worth the heat. I have MSI Afterburner though because it's really good for monitoring your computer. You get an on screen display with all your usages and temps and stuff.

**Comment by eduguy** [comment]
After playing around with the settings a bit, I ended up with around 150 H/S on these settings:

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 760 architecture: 30
  //      memory: 1685/2048 MiB
  //      smx: 6
  { "index" : 0,
    "threads" : 30, "blocks" : 18,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

Still not sure why the hash rate is so low though. It's like half what it should be.

**Comment by NutterzUK** [comment]
For my 970, I was getting around 150 before tweaking. After a bit of trial and error, I am getting around 425.

Here are my settings:
`"gpu_threads_conf" :
[
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3386/4096 MiB
  //      smx: 13
  // 8 gets 387
  // 10 gets 420
  // 12 gets 427
  // 16 is awful
  // 14 gets 427
  
  { "index" : 0,
    "threads" : 13, "blocks" : 39,
    "bfactor" : 8, "bsleep" :  100,
    "affine_to_cpu" : true, "sync_mode" : 3,
  },

],`
