### ISSUE TITLE
Miner mined for dev for 5 hours straight.

### ISSUE THREAD

**Issue by konstantinakis** [fireice-uk/xmr-stak#657]
Pretty much what the tittle says. Im using the miner's last version on windows 10. 
![miner](https://user-images.githubusercontent.com/15005634/34294360-d583337e-e710-11e7-81f1-3f578558e2db.png)

**Comment by bomb-on** [comment]
Just to be sure, did you compile the miner by yourself or not? What does the line about "developer fee" say when you start the miner? Is it: `Configurable dev donation level is set to 2.0%` or something else?

**Comment by konstantinakis** [comment]
No i didnt compile it by myself, im running the exe. The developer fee is set to 2.0%.

**Comment by bomb-on** [comment]
In that case, I think one of devs here might have a proper explanation for this...

**Comment by dan-and** [comment]
I have similar issues. I use the pre-compiled version for Windows

**Comment by d0cx** [comment]
Same here. It switched to the dev pool over 10 minutes ago, still in Dev pool. What's going on here?

**Comment by fireice-uk** [comment]
@konstantinakis @d0cx @dan-and  please use the issue template and provide full logs in this particular case. Without that we can't help you.

Please make another issue with those things.

**Comment by fireice-uk** [comment]
Just to further set your mind at ease, I just verified that no client was around for more than 16 blocks on the dev pool. 

I look forward to @konstantinakis  @d0cx @dan-and posting their logs and proper issue templates. so we can debug this.

**Comment by konstantinakis** [comment]
First of all i'd like to clear that i DON'T accuse the developers of stealing my power. I realise that this is a kind of a bug.

My miner connected to the developers pool at 06:37 (GMT +2) (~18 hours ago). What else would you like to know? @fireice-uk

**Comment by DavidBruchmann** [comment]
Blocked tasks in Windows defender?

**Comment by konstantinakis** [comment]
Windows defender is disabled.

**Comment by DavidBruchmann** [comment]
Might be, but that doesn't hinder Defender to get active :D
Just check the blocked threads there ...

**Comment by fireice-uk** [comment]
@konstantinakis I realise that :) - can you please re-create using the template though, and include a full log since the miner started? You can use `output_file` option for that. We can't debug stuff form a screenshot.

**Comment by fireice-uk** [comment]
@konstantinakis If you PM me on reddit your miners' ip address I will give you the logs. In general this may be a display issue - miner not displaying the dev switch correctly if some network stuff happens, but I really can't tell without full logs.

**Comment by fireice-uk** [comment]
One more thing - can you please use the new release to make sure it isn't related to #664 And thanks in advance for your help!

**Comment by konstantinakis** [comment]
I enabled the output file. I will post in case this happens again.
