### ISSUE TITLE
[Just a Question] How much hash rate on CPUs with L4 cache (i7 5775c and etctera)

### ISSUE THREAD

**Issue by Victoram** [fireice-uk/xmr-stak#661]
Dunno if its right to question this here, but the last update states a huge hash rate on CPUs with L4 cache, and I want to know how much of difference there is, as I do not have one of this cpus

sry for bad english.

**Comment by bomb-on** [comment]
This is a bit off-topic, maybe it's better to ask in https://www.reddit.com/r/MoneroMining/, https://bitcointalk.org/ or even https://thebitcoin.pub/
