### ISSUE TITLE
新版本怎么生成配置文件

### ISSUE THREAD

**Issue by lls5918** [fireice-uk/xmr-stak#663]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by lls5918** [comment]
W7上面使用的

**Comment by bomb-on** [comment]
English please? Also, you didn't explain what's your problem at all...

**Comment by lls5918** [comment]
![1](https://user-images.githubusercontent.com/34771211/34305515-66fe17e8-e779-11e7-91e1-777f3f979792.png)

What should I write here

**Comment by bomb-on** [comment]
What exactly you don't understand? :) It is really a simple question and you should know the answer to this ^^

**Comment by psychocrypt** [comment]
closed: please search first for a how to miner guide. If you than have question please add a useful title and add a question to your post.
