### ISSUE TITLE
First time using a miner, is there a command list that I should know?

### ISSUE THREAD

**Issue by alexDHAS** [fireice-uk/xmr-stak#665]
It's my first time running a command based program, and I'm quite baffled with all these texts are being showned. I'm coming from Minergate as people are suggesting to avoid it for monero.

Is there a way for me to limit the cpu threads/gpu intensity?
And how do I check my balance?
Do I need to enable nicehash pool/multi-pool?

**Comment by psychocrypt** [comment]
run `xmr-stak --help`

**Comment by alexDHAS** [comment]
Sorry, I accidently press enter without typing anything in comments.
