### ISSUE TITLE
[RELEASE] need help to test the Xmas release

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#669]
I need some help to test the Xmas windows binary with AMD and NVIDIA cards. If you own a AMD GPU and/or NVIDIA gpu please [download](https://github.com/fireice-uk/xmr-stak/releases/download/v2.2.0/xmr-stak-win64.zip) the release binary and run it for a short test.
**Please report back which GPU do you tested and if the miner is running.**

Everything should run but I will be absolutely sure.

https://github.com/fireice-uk/xmr-stak/releases/tag/v2.2.0

@JerichoJones @davidpesce @anhphan

**Comment by DavidBruchmann** [comment]
CPU only is working fine.
I Propose just like if you remark the same (= no further comment), especially as CPU-only wasn't asked.
Thanks for all the work!

**Comment by JerichoJones** [comment]
CPU/AMD/NVIDIA all working for me.

**Comment by psychocrypt** [comment]
thx @JerichoJones  and @DavidBruchmann  for testing

**Comment by hydrus777** [comment]
I am trying to use this to mine bytecoin, its not working. Is there a way to do this using this release?

**Comment by szogun1987** [comment]
On windows it is working fine with 2x RX570  + Ryzen 7. But Windows defender in Win 10 make it hard to start (I had to add exception).
I have download and build sources on Ubuntu yesterday and it works quite good. Should I git-pull again and rebuild it for test?

**Comment by psychocrypt** [comment]
@szogun1987 thanks for your tests, you can update you miner to the latest dev because today thete was a last minut bug fix. But there are no test anymore needed.

**Comment by psychocrypt** [comment]
@hydrus777 please open an issue for your question

**Comment by psychocrypt** [comment]
thanks to all for the fast test! 💓

**Comment by szogun1987** [comment]
I have rebuild and run. It works OK. Is there any formula to calculate optimal amount of memory?
On  my ubuntu machine I have only 4GB, and miner reports: " MEMORY ALLOC FAILED: mmap failed". It is server version so it shouldn't have this issue(but I have changed limits anyway).

**Comment by fireice-uk** [comment]
@szogun1987 "use_slow_mem" : "always" will silence that error if you don't mind the reduced speed.

**Comment by bomb-on** [comment]
CPU on Ubuntu 16.04, OS X 10.13.2 and Windows 10 works fine.
Nvidia on Windows 10 works fine.
AMD on Windows 10 occasionally "freezes", the miner just stops working, computer keeps running normally and I can easily close the window and re-run it. This happened multiple times, approximately 2-3 hours after I start the miner.

**Comment by 1RedOne** [comment]
Windows defender now categorizes as a Trojan, which is different from before. Any idea why?

I looked at the files changed in the pr and don't see anything malicious.

**Comment by fireice-uk** [comment]
Because the miner got dropped by a different trojan probably.

**Comment by szogun1987** [comment]
I have no problem with buying couple more gigs of RAM, but I don't wanna spend money if it doesn't affect performance. Currently I have 3+ GB unused. Maybe I should replace with other memory (This one has 2133)?

**Comment by LegolasGChief** [comment]
There are a few problems with auto config 

GTX 660m
