### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by JerryWang304** [fireice-uk/xmr-stak#677]
I am using Ubuntu 12.04 and meet this error when running cmake
![snip20171223_64](https://user-images.githubusercontent.com/11796555/34316978-c13490d8-e7de-11e7-9680-b1ff60cda70c.png)
How to fix this ?

**Comment by psychocrypt** [comment]
You can ignore that. Cmake tries to find git bit it is not installed. I
will check if I can hide this message to avoid confusion.
