### ISSUE TITLE
If one thread fails to hash STAK does not calculate 10 sec Total properly

### ISSUE THREAD

**Issue by JerichoJones** [fireice-uk/xmr-stak#679]
I cannot reproduce the issue. Whatever was causing the issue with my GPUs seems to have cleared up. Hashing is back to normal. Maybe there is something in the way that the 10 second total is calculated that is only seen in this edge case.

![image](https://user-images.githubusercontent.com/13205729/34319703-9e81d5be-e7b6-11e7-9735-5d59d55a850e.png)
![image](https://user-images.githubusercontent.com/13205729/34319709-b576cb6c-e7b6-11e7-8552-aa642cb7885d.png)

**Comment by psychocrypt** [comment]
This is the case if the gpu is not able to calculate a bunch hof hashes
within 10 sec.
It is no problem if this number is not correct this will not influence the
hash rate over all.

Never the less we need to check how we can avoid it.

**Comment by fireice-uk** [comment]
10 + invalid number = ? :)

**Comment by psychocrypt** [comment]
inf :-)

**Comment by fireice-uk** [comment]
Putting a zero instead of (na) would be more confusing I think. Closing unless someone has a better idea.
