### ISSUE TITLE
NOT AN ISSUE - Question about editing report html

### ISSUE THREAD

**Issue by maxxxxpower** [fireice-uk/xmr-stak#682]
I have a little HTML experience (no C++ experience), but I am looking for some help with something I think should be relatively easy - edit the text return of the html report url.

Basically, I'd like to be able to have the "Highest" return of the hashrate return in brackets instead of bare - ie. Highest: [506.3] instead of Highest 506.3. This is for HTTP monitoring with PRTG.

I've been messing around with the webdesign files but seem to be unable to make that change.

Any help would be appreciated!

**Comment by maxxxxpower** [comment]
Figured it out. I wasn't recompiling after editing the file.

**Comment by fireice-uk** [comment]
Did you have a look at `json.api` ?

**Comment by maxxxxpower** [comment]
Not yet. I need to learn some more before I start working with API...I'm lost!

**Comment by maxxxxpower** [comment]
Seems PRTG doesn't like the way the results are returned to it. I'll keep learning!
