### ISSUE TITLE
Compilation fails on ubutu server 16.04 (CPU only)

### ISSUE THREAD

**Issue by gamafranco** [fireice-uk/xmr-stak#683]
Hi,

I'm getting the following compilation error. Thanks!

/usr/bin/cmake -H/home/tfranco/xmr-stak -B/home/tfranco/xmr-stak/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/tfranco/xmr-stak/build/CMakeFiles /home/tfranco/xmr-stak/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/tfranco/xmr-stak/build'
make -f CMakeFiles/xmr-stak-c.dir/build.make CMakeFiles/xmr-stak-c.dir/depend
make[2]: Entering directory '/home/tfranco/xmr-stak/build'
cd /home/tfranco/xmr-stak/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tfranco/xmr-stak /home/tfranco/xmr-stak /home/tfranco/xmr-stak/build /home/tfranco/xmr-stak/build /home/tfranco/xmr-stak/build/CMakeFiles/xmr-stak-c.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tfranco/xmr-stak/build'
make -f CMakeFiles/xmr-stak-c.dir/build.make CMakeFiles/xmr-stak-c.dir/build
make[2]: Entering directory '/home/tfranco/xmr-stak/build'
make[2]: Nothing to be done for 'CMakeFiles/xmr-stak-c.dir/build'.
make[2]: Leaving directory '/home/tfranco/xmr-stak/build'
[ 24%] Built target xmr-stak-c
make -f CMakeFiles/xmr-stak-backend.dir/build.make CMakeFiles/xmr-stak-backend.dir/depend
make[2]: Entering directory '/home/tfranco/xmr-stak/build'
cd /home/tfranco/xmr-stak/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tfranco/xmr-stak /home/tfranco/xmr-stak /home/tfranco/xmr-stak/build /home/tfranco/xmr-stak/build /home/tfranco/xmr-stak/build/CMakeFiles/xmr-stak-backend.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tfranco/xmr-stak/build'
make -f CMakeFiles/xmr-stak-backend.dir/build.make CMakeFiles/xmr-stak-backend.dir/build
make[2]: Entering directory '/home/tfranco/xmr-stak/build'
[ 28%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
/usr/bin/c++   -DBACKEND_TYPE=cpu -DCONF_NO_AEON=1 -DCONF_NO_CUDA -DCONF_NO_OPENCL -DGIT_BRANCH=master -DGIT_COMMIT_HASH=2ae7260 -I/home/tfranco/xmr-stak/.  -march=native -mtune=native  -msse2 -maes -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o -c /home/tfranco/xmr-stak/xmrstak/backend/cpu/minethd.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/xmr-stak-backend.dir/build.make:158: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o] Error 4
make[2]: Leaving directory '/home/tfranco/xmr-stak/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
make[1]: Leaving directory '/home/tfranco/xmr-stak/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JerichoJones** [comment]
Please fill out the template properly.

---
# Issue Compiling STAK
 - Which OS do you use?
 
 - What software are you using to compile? Include versions (this can be very important).
 
 - Add **all** commands you used and the **full** compile output here
 
 - Run `cmake -LA .` in the build folder and add the output here
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---
