### ISSUE TITLE
i5-2520M	much slower on Linux then on Win

### ISSUE THREAD

**Issue by meem6** [fireice-uk/xmr-stak#685]
I got i5-2520M on WIN10 I got 73H/s on Fedora 57H/s
I am using current version for WIN, and for LINUX I tried 2.1 and 2.2 those I compiled on Fedora 27
same config (using 1core)

**Comment by meem6** [comment]
LINUX
./xmr-stak -v
Version: xmr-stak 2.2.0 2ae7260

cmake -LA
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:209 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support


-- Configuring incomplete, errors occurred!
See also "/root/monero/xmr-stak/CMakeFiles/CMakeOutput.log".
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/lib64/ccache/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/lib64/ccache/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O2 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/root/monero/xmr-stak
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/lib64/ccache/cc
CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

cpu.txt
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },

],

config.txt
"currency" : "monero",
"call_timeout" : 10,
"retry_time" : 30,
"giveup_limit" : 0,
"verbose_level" : 3,
"print_motd" : true,
"h_print_time" : 60,
"aes_override" : null,
"use_slow_memory" : "warn",
"tls_secure_algo" : true,
"daemon_mode" : false,
"flush_stdout" : false,
"output_file" : "",
"httpd_port" : 0,
"http_login" : "",
"http_pass" : "",
 
"prefer_ipv4" : true,

**Comment by psychocrypt** [comment]
you can not ise the same config on windows and linux. The core enumeration
on both OS is different. Please remoce cpu.txt on linux and let the minet
generate a config.

**Comment by meem6** [comment]
I recreated the configs, the default got 2cores, so the results are even worse (as the i5 got 3MB L3)
I changed to only using only core 0 now, I am at 62H/s now for unknown reason (maybe core 0 run better then core 3) :)
but still is some 10H/s lower then used to be last night at WIN.
The options in config.txt are same on WIN and LIN now too.

maybe I should use some options when compiling, dont know. (the cpu is running at 3000Mhz, same as at win)

**Comment by psychocrypt** [comment]
Try core 2 and be shure you have huge page support enabled under linux.

**Comment by psychocrypt** [comment]
do you compiled the miner with hwloc support?

**Comment by meem6** [comment]
I do not know, sorry. How can I check, or make sure I compiled with hwloc, and maybe something that make best use of INTEL i5, thx

I just ran "cmake -DCUDA_ENABLED=OFF -DOpenCL_ENABLED=OFF .. "

**Comment by psychocrypt** [comment]
ok hwloc is included could you olease post the output of the miner from the
start.

**Comment by meem6** [comment]
TE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   63.5 |   64.3 |   64.0 |
---------------------------
Totals:     63.5   64.3   64.0 H/s
Highest:    64.4 H/s
[2017-12-24 10:42:47] : Difficulty changed. Now: 2430.
[2017-12-24 10:42:47] : New block detected.

**Comment by meem6** [comment]
# ./xmr-stak 
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.2.0 2ae7260

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 0.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-24 10:49:54] : Start mining: MONERO
[2017-12-24 10:49:54] : Starting 1x thread, affinity: 0.
[2017-12-24 10:49:54] : hwloc: memory pinned
[2017-12-24 10:49:54] : Fast-connecting to xmr.bohemianpool.com:4444 pool ...
[2017-12-24 10:49:54] : MEMORY ALLOC FAILED: mmap failed
[2017-12-24 10:49:54] : Pool xmr.bohemianpool.com:4444 connected. Logging in...
[2017-12-24 10:49:55] : Difficulty changed. Now: 2000.
[2017-12-24 10:49:55] : Pool logged in.

**Comment by meem6** [comment]
this is what I got on WIN10 very similar setup (installed same day at different laptop, i5 3350M)
the other laptop doestne hae win10 nstalled anymore, but was just couple H/s slower

Message from donate.xmr-stak.net:3333:
Thanks for donating!
Please checkout our community fund-raiser!
GUI Miner - http://goo.gl/vmuiLE

PS This is just a thank you.
It doesn't mean you are mining to our pool right now.

-----------------------------------------------------
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   36.4 |   35.2 |   72.4 |
---------------------------
Totals:     36.4   35.2   72.4 H/s
Highest:    77.1 H/s

-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-24 12:10:29] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled
[2017-12-24 12:10:29] : WARNING: backend NVIDIA disabled.
WARNING: AMD cannot load backend library: xmrstak_opencl_backend.dll
WARNING: AMD Backend disabled
[2017-12-24 12:10:29] : WARNING: backend AMD disabled.
[2017-12-24 12:10:29] : Starting 1x thread, affinity: 3.
[2017-12-24 12:10:29] : hwloc: memory pinned
[2017-12-24 12:10:29] : Fast-connecting to xmr.bohemianpool.com:4444 pool ...
[2017-12-24 12:10:30] : Pool xmr.bohemianpool.com:4444 connected. Logging in...

**Comment by meem6** [comment]
so the issue was huge pages.
"sysctl -w vm.nr_hugepages=2048"
did the trick.
thank you!
I am at 70H/s now
