### ISSUE TITLE
NVIDIA Compute not working.

### ISSUE THREAD

**Issue by goose** [fireice-uk/xmr-stak#686]
Intel Core I5 6600
Windows 10 64-bit
Gigabyte GTX970 G1

I cannot start the miner with Compute mode enabled on my GTX970, I have tried both with Cuda 8 with patch and cuda 9 latest installer. 

I can however start either version of the miner if i switch the card back to normal mode. Please advise.

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3387/4096 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 16, "blocks" : 39,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-23 22:52:27] : Start mining: MONERO
[2017-12-23 22:52:28] : Starting NVIDIA GPU thread 0, no affinity.
[CUDA] Error gpu 0: <C:/Users/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:221

I have also tried the latest version and get the following:

-------------------------------------------------------------------
xmr-stak 2.2.0 c4400d19

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-23 22:54:32] : Start mining: MONERO
[2017-12-23 22:54:33] : Starting NVIDIA GPU thread 0, no affinity.
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:207

**Comment by psychocrypt** [comment]
please change bfactor to 8 or reduce the threads in the file nvidia.txt

**Comment by goose** [comment]
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3387/4096 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 4, "blocks" : 13,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

set to this and it still does the same error.

**Comment by demib84** [comment]
I got a similiar error ([CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:221) when I set the "optimize for compute performance" option in the nvidia control panel to on. Turning it off allows it to work once more.

Below are the settings I am using for my GTX 970. bfactor is set where it is because 8 does not smooth out the lagging between computing and rendering the screen when I am using the computer at the same time.

[
// gpu: GeForce GTX 970 architecture: 52
// memory: 3386/4096 MiB
// smx: 13
{ "index" : 0,
"threads" : 13, "blocks" : 39,
"bfactor" : 10, "bsleep" : 100,
"affine_to_cpu" : false, "sync_mode" : 3,
},

],

If I delete the nvidia config file and let the program auto-config, it comes in as blank.

**Comment by carlthome** [comment]
Same issue here.

**Comment by eruditej** [comment]
why are you tinkering with blocks and threads in config files? 

https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-write-flexible-kernels-grid-stride-loops/

Let grid stride launch the right threads/blocks of your nv kernels automatically.

Poor... quality... code...

**Comment by carlthome** [comment]
@eruditej, Hemi looks cool, but xmr-stak already warns when the number of blocks is not a multiple of the number of processors and it might not be worth a breaking change unless there is a clear performance improvement.

Also, off topic.

**Comment by goose** [comment]
@eruditej that link doesn't seem relevant? I already know the blocks and threads my GPU will support, however xmr-stak does not support NVIDIA compute and if it does it definitely doesn't on the Gigabyte G1 GTX970.

However any input on how to get past the CUDA issues would be useful? :-)

**Comment by psychocrypt** [comment]
Could you please post the full error. In the first post there is the last
line missing. Bfactor and co is not helping here the error is coming from
the l1 disbling call.

**Comment by goose** [comment]
-------------------------------------------------------------------
xmr-stak 2.2.0 c4400d19

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-28 17:57:55] : Start mining: MONERO
[2017-12-28 17:57:55] : Starting NVIDIA GPU thread 0, no affinity.
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:207

This is all of the console output that I get given, then the application crashes and closes

**Comment by psychocrypt** [comment]
I will create a bug fix for this which allows that this line fails. Could
you pease tru the release 2.1.0 as I remember this line was not guarded in
this release.

**Comment by goose** [comment]
Here you go:

-------------------------------------------------------------------
xmr-stak 2.1.0 30888a3

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-12-28 18:07:35] : Start mining: MONERO
[2017-12-28 18:07:35] : Starting NVIDIA GPU thread 0, no affinity.
[CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:221

**Comment by carlthome** [comment]
2.1.0 doesn't work either.

`[CUDA] Error gpu 0: <C:/Users/widera/Downloads/release/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:221`

That's a weird error by the way because my user name is not widera and I'm not running from that directory.

**Comment by goose** [comment]
@carlthome I assume this is just because there is a hard code directory location in the code.

**Comment by psychocrypt** [comment]
This is the path from the precompiled binary it is hard coded into the
binary.

**Comment by carlthome** [comment]
Interestingly, v2.2.0 works fine with "Optimise for Compute Performance: On" and I get a good improvement on my 980 Ti from 600 H/s to 660 H/s.

**Comment by carlthome** [comment]
I assume this error was related to CUDA 9.1 or something.

**Comment by goose** [comment]
@carlthome please may you describe a little more about your setup such as drivers?

**Comment by goose** [comment]
If it helps I am running the following driver: 388.71-desktop-win10-64bit-international-whql

**Comment by goose** [comment]
I got compute mining working :smiley:
[7:22 PM] Goose: "gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 12, "blocks" : 52,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],

This driver
388.71-desktop-win10-64bit-international-whql

and the following 2 settings in the manage 3D settings
DSR - Factors 1.20x
Optimize for compute performance on

Gigabyte GTX970 G1 mining electroneum @ 410 H/s

I'll probably get this to 450 H/s once I re-apply my card overclock

Thanks for all the help, I'd advise asking people to change their DSR- Factors in the future if they have this issue with NVIDIA cards.
