### ISSUE TITLE
Ubuntu 16.04 cuda9.1 clang-4.0 compile whit nvcc but is necesary remove clang3.8

### ISSUE THREAD

**Issue by reproteq** [fireice-uk/xmr-stak#687]
//desinstalar clang 3.8 
apt-get remove --purge clang*
//instalar clang-4.0

//editar fuentes 
/etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse

wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main"
sudo apt-get update
sudo apt-get install -y clang-4.0

update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-4.0 1000
update-alternatives --install /usr/bin/clang++ clang /usr/bin/clang-3.8 100
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 1000
update-alternatives --config clang
update-alternatives --config clang++
 
//instalar git

git clone https://github.com/fireice-uk/xmr-stak.git

cd xmr-stak
mkdir build
cd build

//compilar
xmr-stak
cmake .. -DCUDA_ENABLE=ON -DCUDA_COMPILER=nvcc -DOpenCL_ENABLE=OFF -DOpenSSL_ENABLE=OFF -DCUDA_ARCH=61 
make install

done ;)
run

cd bin
./xmr-stak

**Comment by psychocrypt** [comment]
-DCUDA_ENABLE=enble must be -DCUDA_ENABLE=ON

It helps to remove the old compiler but you can also set the environment
variable CC and CXX to force cmake to use the new clang version instead of
the old.
