### ISSUE TITLE
Backend Nvidia Disabled

### ISSUE THREAD

**Issue by flak153** [fireice-uk/xmr-stak#688]
I've been mining with this machine for about a week now, before that I used it once in a blue moon (literally once every few months) for gaming. I restarted the computer, and now I get an error saying that xmr-stak no longer recognizes my gpu. I've checked to see that the drivers are still installed and correct, and that the gpu is still fine. Restarted my pc, and redownloaded xmr stack. The issue still has not resolved itself

  - Type of the CPU: Intel 6700k
  - Type of the GPU: Nvidia 1070
  -OS : Windows

The cpu is overclocked but everything else is stock

**Comment by psychocrypt** [comment]
please ckeck if all dll files are in the folder. It could be that the anti
virus software removed the files.
