### ISSUE TITLE
Only one card hashes at a high rate, the rest do not

### ISSUE THREAD

**Issue by Mordecai0** [fireice-uk/xmr-stak#689]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
i3
  - Type of the GPU (if you try to miner with the GPU).
6 x 1070s

# Compile issues
  - Which OS do you use?
 Windows 10 Pro 64
 

https://pastebin.com/FZ08S7yu - auto generated config

https://i.imgur.com/B6NIHiD.png - the result is one gpu works well and the others dont

I have tried my old blocks/threads with the same result. 

More info here - https://www.reddit.com/r/MoneroMining/comments/7lsl4f/xmrstak_any_reason_why_only_one_card_has_a_high/

Thanks

**Comment by psychocrypt** [comment]
please run nvidia-smi to be sure that there are no other apps using the gpu.

**Comment by Mordecai0** [comment]
https://i.imgur.com/jhNp3Dc.png Results here.

**Comment by Mordecai0** [comment]
https://i.imgur.com/m3jT8sH.png More here.

**Comment by Mordecai0** [comment]
https://i.imgur.com/acuMNK6.png Results

**Comment by JerichoJones** [comment]
What does task manager look like when you are hashing?
