### ISSUE TITLE
getting cuda error 265

### ISSUE THREAD

**Issue by khel973** [fireice-uk/xmr-stak#694]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by khel973** [comment]
gpu is asus gtx 460 
win 10
i5 6600K

**Comment by psychocrypt** [comment]
please fill out as much as possible questions from the first post and add
the exact error shown in the terminal, else we can not help you.
