### ISSUE TITLE
backup pools

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#7]
It would be usefull to allow that a list of pools with there login data (username, pool passwd, address) can be configured.
A json array like for `cpu_thread_conf` would be the best.

If we add a `value` to each pool entry that can be set by the user for each pool and a additional flag ( a new variable those is not part of the pool array) what the value means we can allow two cases:
- fail over: This means the value defines a priority which pool is prioritized (higher is used first)
- weighted pool logins: This means the values from all pools is aggregated and than normalized to `100min - dev pool time`. Each pool is than used for mining depending of the time slice within e.g. 98min. This allows for example the user to provide other developer (e.g. monero devs) with a donation, or the user likes to split the hash power to different pools)

```
/* This defines in which order the pools are use:
 * "failover" - means the value defines the priority of the pool (higher is used first),
 *               if the connection get lost the pool is switched to the next 
 *               (after X min the miner tries to fall back to the original pool)
 * "weighted" - all pool values will be accumulated and the hash rate 
 *                is given to all pools (within 100 minutes) depending on the weight
 */
"pool_order" : "weighted",
"pool_list" :
[
    // if the dev donation is 2%, this pool is used 42 minute
    { "pool_address" : "pool1", "wallet_address" : "myXMRAddress",
      "pool_password" : "x", "value" : 60 },
    // this pool is used 56 minutes
    { "pool_address" : "pool2", "wallet_address" : "myXMRAddress",
      "pool_password" : "", "value" : 80 },
],
```
```

**Comment by fireice-uk** [comment]
I will do it, as you can probably see from the code I intended to do this a year ago. It has so much failure surface I don't even want to think about possible things that can go wrong...

**Comment by fireice-uk** [comment]
Closing  - #90
