### ISSUE TITLE
how to make it so it only uses my amd gpu

### ISSUE THREAD

**Issue by flobie** [fireice-uk/xmr-stak#704]
trying to have it so it is only mining on my amd card and not my nvidia or cpu

**Comment by psychocrypt** [comment]
goto the terminal and start the miner with xmr-stak --help

**Comment by Jalockin** [comment]
thank you psychoscrypt, I had the same problem, but now another question - if I set "xmr-stak.exe --noCPU" will it read the config.txt ?

**Comment by Jalockin** [comment]
-- It will ;)

**Comment by mehdox** [comment]
i am trying to disable the cpu because my computer is really slow i ve create a shortcut
 \xmr-stak.exe" --noCPU 
the cpu is still @50% ?
waths wrong?

![image](https://user-images.githubusercontent.com/3768736/34401749-6fafcc92-eb9d-11e7-9a0e-f6004d716ef9.png)

**Comment by JayWalker512** [comment]
@mehdox Could you post the terminal output when you start the miner? Some CPU time is still required to mine on the GPU so I would guess that's what you're seeing.

**Comment by mehdox** [comment]
![xmr stack](https://user-images.githubusercontent.com/3768736/34428629-346e29a0-ec4f-11e7-9cbd-d82847204837.png)

**Comment by JerichoJones** [comment]
Did you check Task Manager? It looksl ike you are also using two cores to manage the GPU. You might want to try setting affinity to false. YMMV

**Comment by mehdox** [comment]
thank you
wich setting do i have to put?

**Comment by JerichoJones** [comment]
@mehdox In your AMD.TXT
