### ISSUE TITLE
How to launch

### ISSUE THREAD

**Issue by hawkeagle123** [fireice-uk/xmr-stak#710]
Hello,

i have solved the issue in https://github.com/fireice-uk/xmr-stak-amd/issues/182
what should i do next to launch the program?

i tried

> vi /home/mining/xmr-stak/bin/start.sh

in http://www.easycryptomining.com/monero_ubuntu_16.html but nothing appear

i also see the /home/bin folder but there are no files for xmr-stack

Thank you.

**Comment by psychocrypt** [comment]
sry the portable bin is currently not available because of t muxh issues.
we work on a solution.

**Comment by kencrocken** [comment]
If you followed the [build instructions](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md), you would find the bin folder under `xmr-stak/build/bin`.

`$ cd ~/path/to/xmr-stak/build`
From there its just `bin/xmr-stak`.
