### ISSUE TITLE
RECEIVE error: blocking Operation interrupted by a call to WSACancelBlockingCall.

### ISSUE THREAD

**Issue by sergneo** [fireice-uk/xmr-stak#711]
In the logs frequently this error occurs, then the client reboots and starts over. For what reasons may even be a message about this error?

**Comment by laurx2** [comment]
I had the sames issue....the latest error is 
[pool.supportxmr.com:7777] RECEIVE error: A blocking operation was interrupted by a call to WSACancelBlockingCall

**Comment by sergneo** [comment]
I have pool.etn.spacepools.org it depends from the server?

**Comment by JerichoJones** [comment]
Network-enabled antivirus or firewall?
