### ISSUE TITLE
Using all CPU cores causes lower hashrate -- why?

### ISSUE THREAD

**Issue by mkowske** [fireice-uk/xmr-stak#712]
Hi,

Running xmr-stak on a Ubuntu 17.10 box, CPU only, 4 core Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz.

```
$ cat /proc/cpuinfo | grep 'core id' | sort | uniq
core id		: 0
core id		: 1
core id		: 2
core id		: 3
```

When I ran the program and it created a config I noticed that the cpu.txt was only assigned to 3 cores (0-2). This gives me a hash rate around 190 H/s. 

```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],
```

I went in to cpu.txt and added a line to assign the 4th core as well. I re-ran xmr-stak and the CPU usage went up but the hashing rate went down (to about 168 H/s). 

```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
],
```

Just wondering why using all 4 cores would cause lower hashing rate?

**Comment by seankibler** [comment]
I think efficiency is highly bound to CPU cache, so if that CPU doesn't have a cache that can handle that many threads it will bog down the hash rate. I'm not sure about this and haven't verified it by looking up specs on that CPU so consider it just a hunch.

**Comment by wheresmycode** [comment]
Your CPU has only 6MB cache. 1 thread needs 2MB.
https://ark.intel.com/de/products/78931/Intel-Core-i7-4710MQ-Processor-6M-Cache-up-to-3_50-GHz

**Comment by mkowske** [comment]
That makes sense.. thanks.
