### ISSUE TITLE
Error compiling xmr-stak with AMD GPU

### ISSUE THREAD

**Issue by acsegal** [fireice-uk/xmr-stak#714]
Sorry if this is a repeat, I cannot find a similar error report.

[CMakeError.log](https://github.com/fireice-uk/xmr-stak/files/1587652/CMakeError.log)
[CMakeOutput.log](https://github.com/fireice-uk/xmr-stak/files/1587653/CMakeOutput.log)

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
celeron G3900 on a ASUS Prime z270a motherboard
  - Type of the GPU (if you try to miner with the GPU).
radeon RX 580
# Compile issues
  - Which OS do you use?
Ubuntu 16.04

cmake -L -DCUDA_ENABLE=OFF  ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/i386-linux-gnu/libOpenCL.so (found version "2.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: /home/acs/Downloads/acs_try1/xmr-stak-master/build
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_INSTALL_PREFIX:PATH=/home/acs/Downloads/acs_try1/xmr-stak-master/build
CMAKE_LINK_STATIC:BOOL=OFF
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC:FILEPATH=/usr/lib/i386-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib/i386-linux-gnu/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OpenCL_ENABLE:BOOL=ON
OpenSSL_ENABLE:BOOL=ON
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

make
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 17%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 24%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 27%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 31%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
In file included from /home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/minethd.cpp:24:0:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:36:2: error: #error You are trying to do a 32-bit build. This will all end in tears. I know it.
 #error You are trying to do a 32-bit build. This will all end in tears. I know it.
  ^
In file included from /home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/minethd.cpp:24:0:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h: In function ‘uint64_t _umul128(uint64_t, uint64_t, uint64_t*)’:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:26:11: error: expected unqualified-id before ‘__int128’
  unsigned __int128 r = (unsigned __int128)a * (unsigned __int128)b;
           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:27:8: error: ‘r’ was not declared in this scope
  *hi = r >> 64;
        ^
In file included from /home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/minethd.cpp:24:0:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h: In function ‘void cryptonight_hash(const void*, size_t, void*, cryptonight_ctx*)’:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:319:30: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
   idx0 = _mm_cvtsi128_si64(cx);
                              ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:319:30: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h: In function ‘void cryptonight_double_hash(const void*, size_t, void*, cryptonight_ctx**)’:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:392:30: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
   idx0 = _mm_cvtsi128_si64(cx);
                              ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:406:30: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
   idx1 = _mm_cvtsi128_si64(cx);
                              ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h: In function ‘void cryptonight_triple_hash(const void*, size_t, void*, cryptonight_ctx**)’:
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(a);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:519:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(a);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:520:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax1, bx1, cx1, l1, ptr1, idx1);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(a);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:521:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax2, bx2, cx2, l2, ptr2, idx2);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:475:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:527:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:475:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:528:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax1, bx1, cx1, l1, ptr1, idx1);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:475:27: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  idx = _mm_cvtsi128_si64(c);    \
                           ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:529:3: note: in expansion of macro ‘CN_STEP3’
   CN_STEP3(ax2, bx2, cx2, l2, ptr2, idx2);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:482:40: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                        ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:531:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:482:40: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                        ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:532:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax1, bx1, cx1, l1, ptr1, idx1);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:482:40: error: there are no arguments to ‘_mm_cvtsi128_si64’ that depend on a template parameter, so a declaration of ‘_mm_cvtsi128_si64’ must be available [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                        ^
.
.
.
<snip>
<snip>
<snip>
.
.
.

/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:25: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx = _mm_cvtsi128_si64(a);    \
                         ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:692:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:482:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:738:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax3, cx3, bx3, l3, ptr3, idx3);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:25: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx = _mm_cvtsi128_si64(a);    \
                         ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:692:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:482:38: error: ‘_mm_cvtsi128_si64’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  lo = _umul128(idx, _mm_cvtsi128_si64(b), &hi);  \
                                      ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:739:3: note: in expansion of macro ‘CN_STEP4’
   CN_STEP4(ax4, cx4, bx4, l4, ptr4, idx4);
   ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:460:25: note: ‘_mm_cvtsi128_si64’ declared here, later in the translation unit
  idx = _mm_cvtsi128_si64(a);    \
                         ^
/home/acs/Downloads/acs_try1/xmr-stak-master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h:692:3: note: in expansion of macro ‘CN_STEP1’
   CN_STEP1(ax0, bx0, cx0, l0, ptr0, idx0);
   ^
CMakeFiles/xmr-stak-backend.dir/build.make:134: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any help would be appreciated.

**Comment by psychocrypt** [comment]
could it be that you are using a 32 bit OS.

**Comment by acsegal** [comment]
Yep, my error.
