### ISSUE TITLE
xmr-stak-win64.zip problm to configure all in one

### ISSUE THREAD

**Issue by Tefo85** [fireice-uk/xmr-stak#715]
Is my first time here sorry for my question. 

I'm try to mining monero but i have issue to create the perfect configuration file to use all potentiality of PC (2 processors and graphic card)

Details PC
Workstation hp z800
Intel(r) xeon(r) x5650 @267GHz 2.66GHz (2 processors)
RAM - 24GB
64-bit
windows 7.8
GeForce GTX 1050 Ti

My pool https://supportxmr.com
Configurations: i use "Port 5555 (Fast CPUs)" 
"pool_address": "pool.supportxmr.com:5555"

Last info: https://github.com/fireice-uk/xmr-stak/releases

Please any can help me to crate a perfect file config for all my pc
Thanks

**Comment by JerichoJones** [comment]
[Tuning Guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md)
