### ISSUE TITLE
Xubuntu 16.04.3 compile problem 91% [SOLVED]

### ISSUE THREAD

**Issue by Buklao** [fireice-uk/xmr-stak#717]
Hi I have problems compiling xmr-stak on clean Xubuntu 16.04.3 install with the necessary dependencies.

# Compile issues
  - Which OS do you use?
  Xubuntu 16.04.3
  add **all** commands you used and the **full** compile output here
  sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev gcc-6 g++-6
  git clone https://github.com/fireice-uk/xmr-stak.git
 mkdir xmr-stak/build
 cd xmr-stak/build
 cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
make install

 # The error during compile:

make[2]: *** No rule to make target '/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop.
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/xmrstak_opencl_backend.dir/all' failed
make[1]: *** [CMakeFiles/xmrstak_opencl_backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nbartels** [comment]
I think the opencl dev files are missing. If you don't need opencl you can simply deactivate it in your cmake call or install them.

**Comment by JerichoJones** [comment]
@Buklao Just to clarify, you followed all the instructions in the [compile guide](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md) ?

**Comment by Buklao** [comment]
@JerichoJones yes I followed the instructions 100%. @nbartels but dont I need opencl to use the GPU to mine? Do you have any idea where I can get the missing opencl files? I think it has something to do with AMD APP SDK 3.0 but I did install it

**Comment by joshgrobin** [comment]
First things first, are you even using a GPU to mine. If not try  

> cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF

If you are using a gpu from only one of these manufactures remove the part of the cmake command that applies to what you are using.
So if you are using only AMD GPUS use 

> cmake .. -DCUDA_ENABLE=OFF

If you are using AMD GPUs the answer I gave yesterday might work for you if you run into anymore trouble. https://github.com/fireice-uk/xmr-stak/issues/675 
It should be at the bottom of the page.

**Comment by Buklao** [comment]
@joshgrobin Thanks! This helped my problems! Now I can compile without problems :)
