### ISSUE TITLE
Youtube can't run while xmr-stak is

### ISSUE THREAD

**Issue by tff1elyk** [fireice-uk/xmr-stak#718]
Basically I used to play OSRS while mining and watching YouTube all at the same time. Ever since the unified miner was released, if I'm mining and run YouTube, YouTube will sit there loading forever and do nothing while my miner will only detect new blocks and never get a share. Sometimes after 5 to 10 mins a YouTube video will play but the miner will never get an accepted share, so I have to shut off the miner while I watch YouTube. OSRS seems to have no affect on the miner at all. I'm wondering if there is a setting I may be able to tweak to make this work or if its the program itself that is the issue and I should just go back to the older separate cpu and gpu version? 

# Basic information
  - i7 4790k
  - rx 570

# Compile issues
  - windows 10
 no idea how to do that

# Issue with the execution
  - Do you compiled the miner by our own? no
no idea how to do that

# AMD OpenCl issue
no idea how to do this

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

**Comment by gdiShun** [comment]
Had a similar problem with my 7950. Driver crashed whenever a video loaded. Try disabling Hardware Acceleration, and _restart your browser_. Spent half the day messing with drivers because I forgot to restart. lol.

**Comment by psychocrypt** [comment]
You need to lower the intensity that you get more free memory.
The nature of a miner is to utilize a system as good a spossible to
generate as much as possible hashes.
