### ISSUE TITLE
Quadro cards not detected.

### ISSUE THREAD

**Issue by 0Camus0** [fireice-uk/xmr-stak#719]
Hello,

I have a Quadro 1000M and it does not recognize it for CUDA, I have the latest drivers, the output:

[2017-12-26 23:52:14] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
WARNING: NVIDIA no device found
[2017-12-26 23:52:14] : WARNING: backend NVIDIA disabled.

I have seen this error on other miners like claymore, could you add support for it? should be an enum to add.

Thanks!!
Great work!

**Comment by alexweissman** [comment]
I got this error as well with my Radeon HD 7700.  When I removed `amd.txt` and restarted the miner, I got a "Found OpenCL GPU" message, after which it appears to have been able to initialize my GPU, generate a new `amd.txt`, and start GPU mining.

**Comment by psychocrypt** [comment]
which OS and which CUDA driver do you use?

**Comment by JerichoJones** [comment]
"Quadro 1000M"
Just curious... how old is that laptop?

**Comment by oviwankenobi** [comment]
hi all
I have windows 7 x64
NVIDIA Quadro FX 1800M latest driver installed
cuda_9.1.85_windows
VS 2017 redistributable package installed (link taken from github readme/doc)

and I get the same "WARNING: NVIDIA Insufficient driver!"
is there anything I can do to make it work? how can I troubleshoot farther?

thank you

**Comment by JerichoJones** [comment]
@oviwankenobi Please open your own Issue.

**Comment by oviwankenobi** [comment]
@JerichoJones 
done
https://github.com/fireice-uk/xmr-stak/issues/823
thank you

**Comment by oviwankenobi** [comment]
https://github.com/fireice-uk/xmr-stak/issues/823#issuecomment-355847971
