### ISSUE TITLE
Good Hashrate, slow xmr-stak msg's in terminal. Issue?

### ISSUE THREAD

**Issue by SeaDude** [fireice-uk/xmr-stak#720]
# Basic information
  - Type of the CPU. `i5`
  - Type of the GPU (if you try to miner with the GPU). `4x Vega 64`

# Compile issues
  - Which OS do you use? `Win 10 64bit`
  
# Issue with the execution
  - Did you compile the miner by yourself? `yes`
  
  run `./xmr-stak --version-long` and add the output here `Do I need to add xmr-stak.exe to my PATH var? I get an error when I try xmr-stak --help in Windows terminal`

My hash rate is great @ 8339 H/s on my 4 Vega 64's and the i5 processor. The problem is that xmr-stak only shows the messages in the terminal (such as `Results accepted by pool`, `New block detected` etc) every 15-45 seconds. 

I saw the issue regarding mouse activating terminal window. I am sure not to click in the terminal. Do I have an issue here? Should the messages be going along at a certain rate? 

Thanks

**Comment by JerichoJones** [comment]
That sounds normal. VARDIFF (Pool side) generally shoots for about 30 seconds.
