### ISSUE TITLE
Linux portable pre-compiled xmr-stak is not available in the download

### ISSUE THREAD

**Issue by ahtaha1** [fireice-uk/xmr-stak#721]
Hi, 
I followed the links to download the Linux pre-compiled portable xmr-stak (xmr-stak-portbin-linux.tar.gz) from the latest releases page (https://github.com/fireice-uk/xmr-stak/releases) but I can only see Windows build. Linux is not there at all; as described in the following page: 
https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md

**Comment by hi0x0** [comment]
作者似乎并未提供。

**Comment by fireice-uk** [comment]
We are still working on making portable miner work flawlessly.

**Comment by vangogh-ken** [comment]
Eager release liunx

**Comment by moralrebuild** [comment]
Keeping an eye on this. Hope it can support the grandpa linux like RHEL/CentOS 5.
