### ISSUE TITLE
proxy server support

### ISSUE THREAD

**Issue by robertvanommen** [fireice-uk/xmr-stak#724]
can you implement proxy support?
i'm behind a authenticated proxy server and cant use this awesome miner atm.

**Comment by epcdiy** [comment]
Proxifier may help you

**Comment by iNetMediaWorks** [comment]
Is there any plan for inbuilt support ? As Proxifier is not working for us.

**Comment by robertvanommen** [comment]
Proxifier or similar software is not working for us.
