### ISSUE TITLE
CL_INVALID_BUFFER_SIZE error on 2.2.0

### ISSUE THREAD

**Issue by KeysorSozer** [fireice-uk/xmr-stak#732]
Windows 10, clean driver install, fresh auto-conf. Runs great on my other machine. CPU hashing works fine.

# AMD OpenCl issue

clinfo dump

Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (1800.8)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices

  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon HD 6900 Series
  Device Topology:                               PCI[ B#1, D#0, F#0 ]
  Max compute units:                             24
  Max work items dimensions:                     3
    Max work items[0]:                           256
    Max work items[1]:                           256
    Max work items[2]:                           256
  Max work group size:                           256
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   2
  Preferred vector width float:                  4
  Preferred vector width double:                 2
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     4
  Native vector width double:                    2
  Max clock frequency:                           900Mhz
  Address bits:                                  32
  Max memory allocation:                         536870912
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    None
  Cache line size:                               0
  Cache size:                                    0
  Global memory size:                            2147483648
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   00007FFD126CF180
  Name:                                          Cayman
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                1800.8 (VM)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (1800.8)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_image2d_from_buffer_read_only cl_khr_spir cl_khr_gl_event

amd.txt config file

"gpu_threads_conf" : [
  // gpu: Cayman memory:384
  // compute units: 24
  { "index" : 0,
    "intensity" : 0, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

**Comment by psychocrypt** [comment]
please i crease the intensity. The problem is that an othwr app is
consuming ro much memory of your gpu and there are only 300MB free mem.
This is to less to generate a valid config. The miner therefore set the
intensity to zero which created the error.

**Comment by KeysorSozer** [comment]
Hmmm, increasing intensity seems to work to a point, but I still get quite poor hashrate. I'm not sure what would consume GPU memory given that there is nothing else running on the machine. I'll try to look into it more and play around. At least I have an idea of what I'm looking for now. Cheers!

**Comment by psychocrypt** [comment]
Than please update your driver. It could b3 an issue with the driver.

**Comment by KeysorSozer** [comment]
Updated to 16.2.1 beta drivers from 15.7.1 I now get "CL_DEVICE_NOT_FOUND when Calling clGetDeviceIDs". Double checking in clinfo and it only shows the processor, however the Catalyst Control Center still reports the GPU. CCC does report upgrade available, will try this and get back.

**Comment by JerichoJones** [comment]
@KeysorSozer Download & run DDU then re-install the driver.

**Comment by KeysorSozer** [comment]
@JerichoJones it's been a long time since AMD wrote such shit drivers as to require DDU, but I tried it for completeness maybe there was something lurking around. Unfortunately same problem occurs, the auto-generated conf sets intensity to 0 and breaks and the highest I can get manually is about half of what others have reported the card being capable of. Further I can only get out about ~40% Memory Usage (as indicated by GPU-Z). Increasing the intensity further gives the Buffer Size error again.
