### ISSUE TITLE
Linux build failure with cuda and gcc 7

### ISSUE THREAD

**Issue by Ghosthree3** [fireice-uk/xmr-stak#733]
Following the regular instructions in https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md for Arch Linux results in failure at
`Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/xmrstak_cuda_backend_generated_cuda_extra.cu.o`
with
`/opt/cuda/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!`

There's an easy work around by adding -DCUDA_HOST_COMPILER=/usr/bin/gcc-6 to the cmake args.

I'm not sure if this is something you can work around with CMakeLists or if the proper solution is to add what I mentioned above to the compile docs for anyone experiencing the error.

**Comment by psychocrypt** [comment]
GCC 7 is not supported by the nvidia compiler nvcc. Thats what the error
message is saying. Switch to gcc 6 or 5.

**Comment by Ghosthree3** [comment]
I have, I provided a solution I was just reporting the issue.

**Comment by psychocrypt** [comment]
Ahh sry I have not read well enough

**Comment by mirix** [comment]
Yes, you can:

https://carterturn.com/h/Guides/NVIDIA%20CUDA%209.1%20with%20GCC%207.2

**Comment by JerichoJones** [comment]
Yes but it's still unsupported. Thanks for the links though guys!

**Comment by aramgrigoryan** [comment]
@mirix tried your guide, first part works, but cannot deal with disabling float_128 
here is my floatn.h file. wherever i put the code it still complains about having not defined float_128
Description	Resource	Path	Location	Type
identifier "__float128" is undefined	testingyou		line 76, external location: /usr/include/bits/floatn.h	C/C++ Problem
Description	Resource	Path	Location	Type
invalid argument to attribute "__mode__"	testingyou		line 64, external location: /usr/include/bits/floatn.h	C/C++ Problem

https://paste.ofcode.org/34JBme9ZAemxascwZtrUreh
