### ISSUE TITLE
when download&installing wont accept cuda or cpu backend dll's..? help? trying to mine for first time..

### ISSUE THREAD

**Issue by unequivocally-me** [fireice-uk/xmr-stak#735]
I am on a HP with intel i7 and trying to CPU mine monero.. when i was trying to download the applications from github for the past 2 days, my computer wouldnt allow me, kept saying "virus detected" and wouldnt even leave it on my computer.

Using Windows 10 Home 

Finally able to open the downloaded file BUT when extracting, comp wouldnt let the backend files extract and install. I pressed "skip" so i could install the stak app still.. i also can not figure out how to configure my config file or get it to mine, keeps telling me to use the command i am already using ( "start_mining [2]" 

Also can not seem to keep my wallet synched to the network..?
Any assistance would be SUPER appreciated! thanks!

**Comment by JerichoJones** [comment]
Create an exception in your AV for XMR-STAK.EXE or the folder in which you drop it.
