### ISSUE TITLE
Cant stop the process

### ISSUE THREAD

**Issue by cynk0** [fireice-uk/xmr-stak#736]
Hy,

i have a win 10 OS, AMD maschine and want to use cpu mining.

I start the comand and forgot to put the port-number to the miningpool....

now the process is still runing with the output

[2017-12-29 17:27:12] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2017-12-29 17:27:12] : WARNING: backend NVIDIA disabled.
[2017-12-29 17:27:12] : Compiling code and initializing GPUs. This will take a while...
[2017-12-29 17:27:12] : Device 0 work size 8 / 32.
[2017-12-29 17:27:18] : Starting AMD GPU thread 0, no affinity.
[2017-12-29 17:27:18] : Starting 1x thread, no affinity.
[2017-12-29 17:27:18] : Fast-connecting to de03.supportxmr.com pool ...
[2017-12-29 17:27:18] : SOCKET ERROR - [de03.supportxmr.com] CONNECT error: Pool port number not specified, please use format <hostname>:<port>.

how can i format the portnumber or stop the process and start new?
i dont prepair the miner, just start it

best regards

**Comment by psychocrypt** [comment]
Please check get started guide of your pool. You need to add the port to
the adress separated by a :

e.g. hostname:3333

**Comment by cynk0** [comment]
Thanks...

but how can i stop the process? Its still running but im not able to change the pool adress...

i only got the same errors but no way to typ in somting in the commandshell

**Comment by psychocrypt** [comment]
ctrl+c or use the task manager

**Comment by cynk0** [comment]
thanks psychocrypt..

i try to do it with ctrl+c and also with the task manager.....it stops but when i open it again its in the same status.....

im not able to change the pool adress or do anything because i cant typ in any letter in the command shell...

can you help me :-P ?

**Comment by zxcj04** [comment]
you should edit the "config" file
change the pool and address there

**Comment by cynk0** [comment]
@zxcj04

where can i find the config file

in the download folder ther are just these files (see picture)

![2017-12-29 18_35_17-xmr-stak-win64](https://user-images.githubusercontent.com/17902016/34443096-152a02b2-ecc7-11e7-8a1f-0821e3406607.png)

thanks

**Comment by cynk0** [comment]
ok thanks...im an idiot....the config.txt is the config file......it works right now ;-)

Thanks for all
