### ISSUE TITLE
Edit xmr-stak

### ISSUE THREAD

**Issue by cynk0** [fireice-uk/xmr-stak#737]
Hy,

i have a win 10, AMD maschine

Is it possible to edit the .exe that it starts automaticly and in the background?

Im very new and my nowledge about programming is very low, is anybody there who can help me?

**Comment by yinkiu602** [comment]
create a .bat file
put this command in the bat file:
start /min "xmr-stak.exe" /high "YOUR PATH\xmr-stak.exe"
then press WIN+R,type taskschd.msc, press enter. Then create a simple task. Set the trigger to run it on user login. Select the .bat file you created in the action column. DONE

**Comment by JerichoJones** [comment]
^^This
