### ISSUE TITLE
Question and not issue

### ISSUE THREAD

**Issue by sherifomran** [fireice-uk/xmr-stak#739]
Can XMR-Stak check the underlying drivers and chose CPU or GPU automatically?
thank you

**Comment by psychocrypt** [comment]
Yes start the miner and if all driver are correct installed than all
possible devices will be stelected.

**Comment by JerichoJones** [comment]
@sherifomran Take a look below for more interesting information when you run xmr-stak.exe --help

Usage: xmr-stak.exe [OPTION]...  
  
  -h, --help            show this help  
  -v, --version         show version number  
  -V, --version-long    show long version number  
  -c, --config FILE     common miner configuration file  
  --noUAC               disable the UAC dialog  
  --currency NAME       currency to mine: monero or aeon  
  --noCPU               disable the CPU miner backend  
  --cpu FILE            CPU backend miner config file  
  --noAMD               disable the AMD miner backend  
  --amd FILE            AMD backend miner config file  
  --noNVIDIA            disable the NVIDIA miner backend  
  --nvidia FILE         NVIDIA backend miner config file  
  
The following options can be used for automatic start without a guided config,  
If config exists then this pool will be top priority.  
  -o, --url URL         pool url and port, e.g. pool.usxmrpool.com:3333  
  -O, --tls-url URL     TLS pool url and port, e.g. pool.usxmrpool.com:10443  
  -u, --user USERNAME   pool user name or wallet address  
  -p, --pass PASSWD     pool password, in the most cases x or empty ""  
  --use-nicehash        the pool should run in nicehash mode  
  
Environment variables:  
  
  XMRSTAK_NOWAIT        disable the dialog `Press any key to exit.  
                               for non UAC execution  
 
Version: xmr-stak 2.1.0 30888a3  
Brought to by fireice_uk and psychocrypt under GPLv3.

**Comment by sherifomran** [comment]
i tried to compile it under linux but it did not work. Could you please provide us with the binaries ? thank you
