### ISSUE TITLE
Configuration Ryzen 1700 + 1060 6gb - enough hashrate?

### ISSUE THREAD

**Issue by Riccardo101991** [fireice-uk/xmr-stak#742]
# Basic information
  - Ryzen 1700 3.9Ghz
  - 1060 6gb zotac mini +200Clock +600MemClock
  - xmr-stak 2.2.0

# Compile issues
 Win 10 Pro 64bit

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   78.0 |   (na) |   (na) |  1 |   79.3 |   (na) |   (na) |
|  2 |   79.3 |   (na) |   (na) |  3 |   79.2 |   (na) |   (na) |
|  4 |   78.4 |   (na) |   (na) |  5 |   78.6 |   (na) |   (na) |
|  6 |   78.5 |   (na) |   (na) |  7 |   78.2 |   (na) |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  535.4 |   (na) |   (na) |
---------------------------
Totals:   1164.8   (na)   (na) H/s
Highest:  1167.0 H/s

For the CPU
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },

For the GPU
{ "index" : 0, "threads" : 79, "blocks" : 30, "bfactor" : 8, "bsleep" :  100, "affine_to_cpu" : true, "sync_mode" : 3}

Is it a good hashrate for the configuration?

Thank you

**Comment by JerichoJones** [comment]
Yes. I have  a 1700x @3.9/1050ti and I get about 200H/s less than you.
