### ISSUE TITLE
Bad instructions for portable linux mining

### ISSUE THREAD

**Issue by jsirianni** [fireice-uk/xmr-stak#743]
The following page is not accurate. specifically, the releases page does not have a Linux release. Additionally, the automated script points to a bad URL. 

https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md

**Comment by b0n0** [comment]
Check the closed issues. And yes you are right. Latest releases there is no portable linux miner, you have to compile it first.

**Comment by fireice-uk** [comment]
We are still working on making portable miner work flawlessly.

**Comment by sa7mon** [comment]
I was also confused when reading the instructions and not finding the binary. Maybe take that part out of the readme until the releases are added back?
