### ISSUE TITLE
i can not run xmr-stak on my video card

### ISSUE THREAD

**Issue by smiletsuuhan** [fireice-uk/xmr-stak#745]
My video card can not run xmr-stak. CUDA error, and then automatically exit.
I use the old version of xmr-stak-nvidia to work properly.
What is the cause of this?

# Basic information
  - i5 4200m
  - gtx 750m

# Compile issues
  - windows 10 1709
  ```

# Issue with the execution
  - Do you compiled the miner by our own? No
Version: xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted?

Log:
[2017-12-30 19:25:25] : Difficulty changed. Now: 120001.
[2017-12-30 19:25:25] : Pool logged in.
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:322

**Comment by JerichoJones** [comment]
Did you let the miner configure your system?
Post your nvidia.txt

**Comment by smiletsuuhan** [comment]
"gpu_threads_conf" :
[
  // gpu: GeForce GT 750M architecture: 30
  //      memory: 1704/2048 MiB
  //      smx: 2
  { "index" : 0,
    "threads" : 130, "blocks" : 6,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],


nvidia.txt automatically generated, has not been modified

**Comment by JerichoJones** [comment]
Try bfactor 6
Also lowering threads.

**Comment by thomasp79** [comment]
I changed Thread to 90 and bfactor to 6 and my 322 error is gone.
