### ISSUE TITLE
Much different hashrate with same CPU

### ISSUE THREAD

**Issue by daisakute** [fireice-uk/xmr-stak#746]
Hello i have several computers with same CPU but some ones get 240H/s while others only get 110H/s
If i do speedtest on the computers all give the same CPU speed.

I think the issue can be related with some of this:
All the computers have Xeon x5650 with 24 GB DDR3 1066
The ones mining at 240H/s have Windows 10 pro installed and regular DDR3
The ones mining at 110H/s have Windows 2012 R2 with REG ECC memory.

I think the issue can be related with the OS or the REG ECC memory, something is slowing down the performence of xmr-stak

# Basic information
  - Type of the CPU: Xeon x5650

# Compile issues
I  downloaded executable 2.2.0 but the issue is in previous versions too.

# Stability issue
  - Is the CPU or GPU overclocked? NO
  - Is the Main memory of the CPU or GPU undervolted? NO

**Comment by psychocrypt** [comment]
It could be that the RAm speed is different or the cpu is not fully supported by the wold windows 2012

**Comment by joshgrobin** [comment]
Can we see the cpu.txt of both?

**Comment by daisakute** [comment]
I think i found the problem, AES is not activated in the slow PCs. Gonna close the issue.

**Comment by trecart** [comment]
Hi, now the hashrate is same with same CPU?
