### ISSUE TITLE
0 donation build for xmr-stack (In case you guys need it).

### ISSUE THREAD

**Issue by Dhruv420** [fireice-uk/xmr-stak#747]
Here's  a build of 0 dev donation for xmr-stack.

https://www.dropbox.com/s/i...

Have fun :)

[edited by psychocrypt] I removed the link to the zip file. Because the link was down due to the traffic limitation of Dropbox and you have not shipped the source code with your binaries. If you only change one line in the code you need to ship the source code else it is a license violation.

**Comment by DavidBruchmann** [comment]
Idiot. You know how much time the devs spend that you can mine on every system with best hashrates?
Apart from that anyone is free to configure the level anyway, no need to change any code.

**Comment by psychocrypt** [comment]
If someone downloaded the binary please keep care it can be that this code contains a virus or trojan.
