### ISSUE TITLE
Configuration EVGA 980 Ti + G4560

### ISSUE THREAD

**Issue by mikemike396** [fireice-uk/xmr-stak#749]
# Basic information

Intel G4560 3.5Ghz (stock)
EVGA 980 Ti Classified +155 Core Clock +500 Mem Clock
Core: 1547mhz
Memory: 4000mhz (8000mhz effective)
xmr-stak 2.2.0 c4400d19
# Compile issues

Win 10 Pro 64bit

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m |
|  0 |   69.6 |   67.2 |   (na) |
---------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  612.4 |  611.4 |   (na) |
---------------------------
Totals:    681.9  678.5   (na) H/s
Highest:   683.2 H/s

For the CPU
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false},

For the GPU
  { "index" : 0,
    "threads" : 6, "blocks" : 88,
    "bfactor" : 6, "bsleep" : 25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  }

Does this look about right?

Thank You

**Comment by JerichoJones** [comment]
Probably.
Try reddit/r/MoneroMining

**Comment by mikemike396** [comment]
Thanks for the suggestion.
