### ISSUE TITLE
New build failing to compile on Windows 10 x64 v1703 Build:16232.1000

### ISSUE THREAD

**Issue by JerichoJones** [fireice-uk/xmr-stak#75]
It seems to be failing building the back-end DLLs. I am using the same process as before without the AMD SDK. I have tried CUDA8 & 9. I can compile the previous build successfully.
Am I doing something incorrectly?

![image](https://user-images.githubusercontent.com/13205729/32135578-7051040c-bbcf-11e7-93c6-a39f68b68986.png)

[Compile_Log.zip](https://github.com/fireice-uk/xmr-stak/files/1424347/Compile_Log.zip)

**Comment by fireice-uk** [comment]
When building development code always `make clean` before you start a build. That should fix the symbols issue.

**Comment by psychocrypt** [comment]
Thx for the information. I can reproduce the broken build and will fix it
soon.

**Comment by fireice-uk** [comment]
@psychocrypt is it related to the mac symbols issue?

**Comment by psychocrypt** [comment]
Could be the bug was introduced with #69.
I will fix it in a few hours.
