### ISSUE TITLE
VEGA/RX5x0 tester needed

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#753]
Dear community,

I am working on a potential increase of the hashrate for AMD GPUs. I need some tester to verify if the new feature increases the hash rate and how much.

Windows and Linux must be tested.

**Please do not start testing if you are not familiar with the compile process.**

You can find the new pull request #752, please read the pull request description before you start.

thx in advanced

psychocrypt

**Comment by davidpesce** [comment]
I'm set back up to compile and test (Win10.64). I have (4x) XFX vega 56s and (1x) powercolor vega 56

**Comment by dfad44** [comment]
Hello psychoscrypt,

I have two options available for linux. 
A. Rzyen 7 1800x with 2x Vega FE Air with Liquid Cooling Mod running rocm 1.7
B. 1950x with 4 x Vega FE Air with Liquid Cooling Mod running rocm 1.7

I'm fairly new to linux, detailed instructions will help tremendously.

**Comment by GoZippy** [comment]
I have a couple test rigs I can use:
1) Gigabyte z370 SLI - i5 8600k - 1x16GB - 2 x XFX RX 560 (one Hynix, one Micron) - Windows 10 (I can dual boot to anything you want to test with though - happy to help if I can). I can try any combo of individual card, crossfire and radeon smart settings... just name it
2) Gigabyte GA-MA770-DS3 - AMD Phenom II X4-940 - 1x8GB - 1 x EVGA 1060 SSC (Hynix) stable at +103 power, 71C target, +125 clock, +1000 mem (2088MHz clock and 4799MHz mem)
3) a mess of other older PC's and cards... I have 6 RX560's sitting on my bench doing nothing.. I do not have any other brands - only XFX.. I have a couple RX 570's but I think they are fried a friend gave to me.

**Comment by sebseb7** [comment]
have most vega models:  56, 64, liquid 64, FE 16GB

have rigs with 5 and with 8 cards.

very familiar with compilation on windows (w10) and Linux (debian stable).

longtime stack user and pool operator. 

can dedicate two rigs for testing purposes.

**Comment by psychocrypt** [comment]
thanks you for all the offers. I got a few benchmark results and need to find out why the pull request crash on some system.
I will close this issue because I need to work on the PR first.

@sebseb7 maybe I come later to your offer.
