### ISSUE TITLE
Set "no_mlck" option in config.txt ,  xmr-stak prints: "MEMORY ALLOC FAILED: mmap failed" and exits

### ISSUE THREAD

**Issue by nicholasfeigen** [fireice-uk/xmr-stak#756]
I'm not sure why, but if I set the use slow memory to: "no_mlck" in config.txt, when I run the program it outputs just one line:

"[2017-12-30 20:45:46] : MEMORY ALLOC FAILED: mmap failed"

if I leave the variable set to "warn" and run xmr-stak it shows "MEMORY ALLOC FAILED: mmap failed" for each thread, but will run and I get hashrates around ~1175-1200

I'm hoping that using fast memory can help speed this up a bit

> Please  provide as much as possible information to reproduce the issue.
> # Basic information

  - Type of the CPU: Xeon e5-2448v2
  - Memory: 12GB DDR3
  - OS: Ubuntu 16.04.2 LTS

> # Issue with the execution
>   - Do you compiled the miner by our own?  Yes, compiled with this command:

"cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF"

>   run `./xmr-stak --version-long` and add the output here:

Version: xmr-stak/2.2.0/2ae7260/master/lin/cpu/aeon-monero/0

**Comment by joshgrobin** [comment]
Try the suggestions at the end of https://github.com/fireice-uk/xmr-stak-cpu/issues/383 or https://github.com/fireice-uk/xmr-stak/issues/525 or https://www.kevinhooke.com/2017/12/15/xmr-stak-memory-alloc-failed-mmap-failed/ To be honest I did not see that much of a difference in hashrate when I get ride of the error message.

**Comment by nicholasfeigen** [comment]
Just wanted to let you guys know, I ran through the suggestions again, and I noticed in the #525 thread that NmxMilk wrote:

> 'sudo sysctl -w vm.nr_hugepages=128'  may not persist after boot.

and that was the solution to my issue!  Btw @joshgrobin , got a very nice bump in hashrate (went from 1188±15 H/S to 1405±10H/S or ~18%) after I got large paging to function!
