### ISSUE TITLE
Add key shortcuts to add or remove cores dynamically or change core % use

### ISSUE THREAD

**Issue by eyanson** [fireice-uk/xmr-stak#759]
![20171231_122840](https://user-images.githubusercontent.com/32112569/34462603-2bb6d69e-ee26-11e7-81c1-8b454efe8876.png)

See sample image. 
Thanks

**Comment by JayWalker512** [comment]
You can change the % of CPU time alloted to the miner with *cpulimit* on Linux, though dynamically changing the number of threads in use would be a bit more involved.

**Comment by eyanson** [comment]
I need that works only in Windows.
Ideally, I need to be able to change the priority of the threads. That way I can give them low priority or stop thread (idle state).

The problem with what I saw is that std::thread does not support priority change.
I was trying to use pthread.h to change the priority but I can not make it work.

Do you have any idea?

thanks

**Comment by fireice-uk** [comment]
Dynamic changes are much more useful to bot herders than average miners. I don't think we will do that one. What we have on the todo is "idle detection" - switching off gpu mining if the mouse is moving.
