### ISSUE TITLE
Donation Connect Appears to Fail 

### ISSUE THREAD

**Issue by CAPeddle** [fireice-uk/xmr-stak#760]
Running after compiling with CUDA and OPENCL disabled

[donate.xmr-stak.net:3333] CONNECT error: GetAddrInfo: |

'uname -a':

> Linux desktop 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

'sudo lshw | grep -i cpu':

>      *-cpu
>           description: CPU
>           product: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
>           bus info: cpu@0
>           version: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

cmake -LA .

> -- Set miner currency to 'monero' and 'aeon'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/chris/xmr-stak
> -- Cache values
> CMAKE_AR:FILEPATH=/usr/bin/ar
> CMAKE_BUILD_TYPE:STRING=Release
> CMAKE_COLOR_MAKEFILE:BOOL=ON
> CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
> CMAKE_CXX_FLAGS:STRING=
> CMAKE_CXX_FLAGS_DEBUG:STRING=-g
> CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
> CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
> CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
> CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
> CMAKE_C_FLAGS:STRING=
> CMAKE_C_FLAGS_DEBUG:STRING=-g
> CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
> CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
> CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
> CMAKE_EXE_LINKER_FLAGS:STRING=
> CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
> CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
> CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
> CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
> CMAKE_INSTALL_PREFIX:PATH=/home/chris/xmr-stak
> CMAKE_LINKER:FILEPATH=/usr/bin/ld
> CMAKE_LINK_STATIC:BOOL=OFF
> CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
> CMAKE_MODULE_LINKER_FLAGS:STRING=
> CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
> CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
> CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
> CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> CMAKE_NM:FILEPATH=/usr/bin/nm
> CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
> CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
> CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
> CMAKE_SHARED_LINKER_FLAGS:STRING=
> CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
> CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
> CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
> CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
> CMAKE_SKIP_RPATH:BOOL=NO
> CMAKE_STATIC_LINKER_FLAGS:STRING=
> CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
> CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
> CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
> CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> CMAKE_STRIP:FILEPATH=/usr/bin/strip
> CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
> CPU_ENABLE:BOOL=ON
> CUDA_64_BIT_DEVICE_CODE:BOOL=ON
> CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
> CUDA_BUILD_CUBIN:BOOL=OFF
> CUDA_BUILD_EMULATION:BOOL=OFF
> CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
> CUDA_CUDA_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcuda.so
> CUDA_ENABLE:BOOL=OFF
> CUDA_GENERATED_OUTPUT_DIR:PATH=
> CUDA_HOST_COMPILATION_CPP:BOOL=ON
> CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
> CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
> CUDA_NVCC_FLAGS:STRING=
> CUDA_NVCC_FLAGS_DEBUG:STRING=
> CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
> CUDA_NVCC_FLAGS_RELEASE:STRING=
> CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
> CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
> CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
> CUDA_SEPARABLE_COMPILATION:BOOL=OFF
> CUDA_TARGET_CPU_ARCH:STRING=
> CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
> CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
> CUDA_TOOLKIT_TARGET_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
> CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=OFF
> CUDA_VERBOSE_BUILD:BOOL=OFF
> CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
> CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
> CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
> CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
> HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
> HWLOC_ENABLE:BOOL=ON
> HWLOC_INCLUDE_DIR:PATH=/usr/include
> MHTD:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so
> MICROHTTPD_ENABLE:BOOL=ON
> MTHD_INCLUDE_DIR:PATH=/usr/include
> OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
> OPENSSL_INCLUDE_DIR:PATH=/usr/include
> OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
> OpenCL_ENABLE:BOOL=OFF
> OpenCL_INCLUDE_DIR:PATH=OpenCL_INCLUDE_DIR-NOTFOUND
> OpenCL_LIBRARY:FILEPATH=OpenCL_LIBRARY-NOTFOUND
> OpenSSL_ENABLE:BOOL=ON
> PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
> XMR-STAK_COMPILE:STRING=native
> XMR-STAK_CURRENCY:STRING=all

'./xmr-stak --version-long'

> Version: xmr-stak/2.2.0/2ae7260/master/lin/cpu/aeon-monero/10

**Comment by goldyfruit** [comment]
`donate.xmr-stak.net` on port `3333` seems to be responding.
```$ telnet donate.xmr-stak.net 3333
Trying 94.176.237.97...
Connected to donate.xmr-stak.net.
Escape character is '^]'.
quit
Connection closed by foreign host.
```
Maybe the host was unreachable when you tried.

**Comment by fireice-uk** [comment]
`GetAddrInfo` suggests DNS error. Can you resolve `donate.xmr-stak.net` ?

**Comment by CAPeddle** [comment]
Mmmm. Must be as @goldyfruit  says. Must have been the time I was testing because now I can resolve. And there are no connectivity problems with the miner at the moment. False alarm. 
Thanks for the great miner/work
