### ISSUE TITLE
Multiple GPU threads for AMD cards

### ISSUE THREAD

**Issue by SimpleLogic** [fireice-uk/xmr-stak#761]
I'm running trying to edit the amd config file to match what is seen here:

https://www.xmrstak.com/2017/12/08/get-380-h-s-monero-rx-550-2gb/

I don't see an option for "gpu_thread_num" though in the config file template. Can I insert this myself? Or is this something that is not possible with the unified miner now?

**Comment by Scriptiee** [comment]
You just manually insert that yourself and works fine then.
