### ISSUE TITLE
this version of xmr-stak is ignoring more than 1 thread per GPU in config.txt

### ISSUE THREAD

**Issue by induktorCL** [fireice-uk/xmr-stak#762]
Setup:
3x RX VEGA 56, 8GB RAM, Mother MSI Z270-A, Celeron 3900, Windows 10 Pro fully cleaned.
Driver: Blockchain beta.
Compiled the source myself, works perfectly fine on NVIDIA and CPU.

**I run the bat file with the recommended set parameters:**
_set GPU_FORCE_64BIT_PTR=1
set GPU_MAX_HEAP_SIZE=99
set GPU_MAX_ALLOC_PERCENT=99
set GPU_SINGLE_ALLOC_PERCENT=99
C:\xmr-stak-master\build\bin\Release\xmr-stak.exe --noUAC_

**My configuration file (config.txt):**
_"gpu_thread_num" : 6,
"gpu_threads_conf" :
[ 
	{ "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 0, "intensity" : 1736, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 1, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 1, "intensity" : 1736, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 2, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 2, "intensity" : 1736, "worksize" : 8, "affine_to_cpu" : false },
],
"platform_index" : 0,_

This config works perfectly on the old AMD only version, but in newer version, only sets 1 Thread for each GPU, no matter what i enter in the config.txt, VEGA requires 2 threads to achieve full performance.

**Comment by Scriptiee** [comment]
I use that with VEGA and it initialises 2 threads without an issue.

**Comment by induktorCL** [comment]
Can you share your config.txt?, perhaps I am doing something wrong, how many cards you have? specs of the machine? perhaps i'm underpowered in CPU or memory.

**Comment by JerichoJones** [comment]
@induktorCL

**"gpu_thread_num" : 6,**

Is no longer valid in AMD.TXT
