### ISSUE TITLE
How to log average hash rate 

### ISSUE THREAD

**Issue by Simplecomputerblog** [fireice-uk/xmr-stak#763]
How can I log the average hash rate? CPU/GPU.

Currently I have a script that will log the output of the xmr-stak bash script, but it does now show average hash rate. Only way I know of is to press "h" 

Current cron job to output, but does not show avg hash rate
@reboot cd /usr/local/src/xmr-stak-cpu/bin/ && ./start.sh  > /usr/local/src/log$

**Comment by JerichoJones** [comment]
Use JSON and do math?

**Comment by Simplecomputerblog** [comment]
I was thinking more along the lines of outputting the hash rate to a log file. Not sure how I would do that?

**Comment by JerichoJones** [comment]
Turn on logging and set verbose_level to 4

**Comment by Simplecomputerblog** [comment]
Thanks
