### ISSUE TITLE
Mac OS anyone got AMD mining working?

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#764]
I have complied the new xmr-stak on a Sierra Mac Pro.

My Mac Pro is a mid 2010 with 2x cpu.

It has a AMD graphics card which there are currently no instructions for.

so following the instructions and disabling the card using cpu only I get around 330 h/s

Has anyone had any luck getting the latest miner to work with both cpu and AMD graphics card?

My cars is fairly old, not sure of specs but likely to be the 79xx series.

**Comment by macminer** [comment]
Thank you :)

**Comment by macminer** [comment]
Additionally, is there any advantages installing more ram or upgrading the HD to a SSD or even a hybrid?

Thanks

**Comment by Simaex** [comment]
@macminer no use to upgrade you Mac for mining if you get mining running. Few people experience problems with less then 2Gb RAM, but if you have 4+ do not expect any gains for mining. If you will be more specific with your hardware info you may expect more help. Start with actual CPU and GPU info :-)

**Comment by macminer** [comment]
Thanks, it is a 2x 2.4 Quad core Xeon

8gb ram and a Radeon HD5770 1gb

I understand the card is fairly old and it’s not going to be amazing at mining but if I can combine the cpu and graphics card even if I got a boost to 400 h/s every little helps.

There was a stack-amd so it must be possible to get the amd cards working in a mac, just wondering if anyone has got it working on the latest combined cpu/gpu build.

Thank you.

**Comment by macminer** [comment]
A very helpful guy helped with a compiled stak with amd and he advised it’s not really worth it on a mac due to the risk of overheating which macs are prone to with gpu mining, I only have a old gpu and tried the compiles miner and it wasn’t worth the risk.
