### ISSUE TITLE
Ubuntu - how to edit config after initial config wizard?

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#766]
I was having a complete moment, was experimenting on Linux to see how it peformed.

I set up Ubuntu 14.04.5 because it supported my hardware.

Got it installed, started running and got an error with the username in the config, yeap I typed my wallet address wrong.

In the older versions of xmr-stalk the config was manual and you could easily change the config file.

I can not find any reference to the wallet address anywhere.

I can’t find a config.txt file assuming the wizard creates one but I did find config. Something else.

It looked just like the orig config file but there was no settings and pool and wallet address was blank.

How do I reset a wizard config file? Or amend it?

Thank you.

**Comment by JayWalker512** [comment]
Once you go through the initial setup prompts completely, a *config.txt* and *cpu.txt* file are created for you (and possibly more if your GPU is supported). Edit the *config.txt* to change your address and pool information.

**Comment by macminer** [comment]
Thanks, I thought that must be the case but couldn’t find the config file location.

Where is it stored?

**Comment by JayWalker512** [comment]
If you compiled from source on Linux, it should be in the top level of the project folder. Ie. the folder which contains folders *bin*, *xmrstak*, and some others. 

If you're using the Windows pre-built binaries, I'm not sure as I haven't used them.

**Comment by DavidBruchmann** [comment]
In my compilation the files config.txt and cpu.txt are in xmr-stak/build/

**Comment by macminer** [comment]
I found it... :)

Was in the user home folder
