### ISSUE TITLE
AES cpu support.

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#767]
I get a message saying my cpu doesn’t support AES and the miner will not run as efficient, ok it didn’t exactly say that but that was the general gist from the warning.

Is there anything I can enable or disable to help?

I am running Ubuntu 14.04.5 so perhaps there is something I need to do in terminal to enable AES support on the cpu, if it supports it at all.

I think it’s a 2.4 Xeon but I will need to look up exact specs.

**Comment by joshgrobin** [comment]
Yep processor specs are important here. Many of the older xeons don't have hardware AES support so we need to know the model number of the Xeon to help you here.

**Comment by marki555** [comment]
`lscpu` will tell you the exact model string. `grep -c aes /proc/cpuinfo` will show if you have AES support (can be bogus in case of virtualized machine).

**Comment by macminer** [comment]
Everyone on here is so helpful.

Thanks I will report back the model.

**Comment by macminer** [comment]
The cpu famine is 6 and the model is 15 stepping 11

When I ran the aes Grep I get 0

**Comment by joshgrobin** [comment]
Try Sudo lshw -class processor instead and let us know what it says

**Comment by macminer** [comment]
Thanks, I will try that.

It currently has a hash rate of around 80 it’s a dual processor both with 4 cores.

I have a few errors relating to MEMORY ALLOC FAILED: mmap failed

**Comment by macminer** [comment]
That’s very interesting...

It is saying

Cpu:0

Xeon E7330 2.4

Cpu 1

Xeon E7330 2.4

Cpu:2 disabled
Cpu:3 disabled

I’ll take a look inside the machine to see how many sockets are installed.

**Comment by macminer** [comment]
It’s empty because it is actually empty only has 2 cpu’s Installed.

2x E7330 is surely capable of more than 80h/s? I think it peaks at around 100h/s

Buckets of ram installed.

On board graphics.

**Comment by marki555** [comment]
This CPU does not have AES support, so the computation will be quite slow. Also it has 6 MB cache, which means only 3 threads per socket.
https://ark.intel.com/products/30794/Intel-Xeon-Processor-E7330-6M-Cache-2_40-GHz-1066-MHz-FSB

**Comment by macminer** [comment]
Thanks, so in other words the low h/s are to be expected from that cpu?

Thanks for your help.

**Comment by crazydoc72** [comment]
Exactly.

**Comment by mvpel** [comment]
It went EOL roughly seven years ago, so the fact that you're getting 80H/s out of them is pretty good for a possibly10-year-old CPU. Probably not worth the electricity, though.
