### ISSUE TITLE
Benchmarking xmr-stak

### ISSUE THREAD

**Issue by mirix** [fireice-uk/xmr-stak#769]
This is and isn't an issue.

In case you are interested, I have benchmarked the performance of xmr-stak (the CPU code) in Linux with different kernels, compilers and compiler flags:

https://www.linkedin.com/pulse/miners-world-mind-your-kernel-edelmiro-moman

It is a pity that, because of the previously reported issues with multiply defined symbols on the Nvidia backend, one cannot compile with GCC and LTO. 

I managed to do it with Clang but Clang seems to be insensitive to those trifles. GCC clearly isn't.

**Comment by goldyfruit** [comment]
Hey @mirix 

Thanks for the benchmark. Could you please share a bit more about your tests, like:
- Tools used to get the results
- `.config` for the custom kernel
- `CFLAGS` and `CXXFLAGS` used
- GCC default flags

**Comment by mirix** [comment]
The benchmarking was done with xmr-stak. For it to report the hashrate you need to change the "verbose_level"  to 4 in your config.txt.

I compiled both a CPU+Nvidia version and a CPU-only version and benchmarked both.  The reported results are only for the CPU code. I also tried the Intel compilers. However, only the CPU-only code is usable and the performance of the binaries is poorer than that of CGG and Clang, so I did not bother to report those results.

I modified the following lines on the kernel makefile:

HOSTCC       = gcc
HOSTCXX      = g++
HOSTCFLAGS   = -Wall -Wmissing-prototypes -Wstrict-prototypes -fomit-frame-pointer -std=gnu89 \
               -m64 -Ofast -flto -fno-fat-lto-objects -march=native -funroll-loops
HOSTCXXFLAGS = -m64 -Ofast -flto -fno-fat-lto-objects -march=native -funroll-loops

But for the kernel itself is probably wiser to use -O3 rather than -Ofast and to remove -funroll-loops.

The default flags for the kernel are those of the first line. I added the second line.

Attached you should find the kernel configuration file. It was initially generated with "make localyesconfig". But then I built the Intel microcode and the wifi firmware into the kernel, chose Core2/Newer Xeon as a processor, changed the timer to 100 MHz, removed support for AMD, etc. In summary, I made it a bit more server-like and a bit leaner.

[config_ubuntu_44.txt](https://github.com/fireice-uk/xmr-stak/files/1601090/config_ubuntu_44.txt)

**Comment by goldyfruit** [comment]
@mirix 👍

**Comment by goldyfruit** [comment]
For Debian system, I guess `linux-image-rt-amd64` (`linux-image-lowlatency` in Ubuntu) could be something to try.

**Comment by mirix** [comment]
I am not sure. Low latency is good for desktop responsiveness, which is what people typically want, but I guess that for "HPC" a server-like configuration should be more advantageous.

**Comment by mirix** [comment]
I am starting to wonder whether or not the hashrate reported by xmr-stak is reliable.

With the default compile options and the stock kernel, xmr-stak was reporting 450 h/s, but the pool reported peaks of 850 h/s.

Now, with somehow optimised kernel and code, xmr-stak reports 485 h/s but the pool reports (averages?) of 1.3 MH/s...

**Comment by JayWalker512** [comment]
> I am starting to wonder whether or not the hashrate reported by xmr-stak is reliable.
I have been wondering this as well due to various weird behaviors but I haven't had time to investigate.

**Comment by JerichoJones** [comment]
@mirix 
  
***Why does the hashrate in my miner not match what I see on the dashboard???***

Your computer does the following while mining:
 
The pool gives you a search-job, then your miner starts calculating hashes until it finds one that matches the requirements (difficulty).  The miner sends the pool the result if it exceeds the difficulty.
 
The pool does not see how often you perform the hash calculations. It only knows when your miner submits a hash that exceeds the difficulty.
 
The pool then uses the law of probability to estimate the number of hashes it took to make the share result you found. This is ONLY AN ESTIMATE. That is why you see the fluctuating numbers.
 
You do not get paid based on your hashrate, but by a combination of the difficulty of AND the number of shares submitted to the pool. If your luck is bad then you will submit less shares in a given time period.
 
In very basic terms:
 
Shares*Difficulty=MuhMoneez

**Comment by mirix** [comment]
Thanks for the explanation.
