### ISSUE TITLE
What’s considered a average / decent hash rate?

### ISSUE THREAD

**Issue by macminer** [fireice-uk/xmr-stak#770]
More out of curiosity than anything.

I know everyone has different setups but what is considered as a average or fair h/s rate? 

Would be nice for people starting out to know how their rig stands up to others.

I’m getting a 24 hour average of 320 h/s

**Comment by Simaex** [comment]
@macminer There are several resourses that collect actual hashrate data for a variety of hardware. For example [http://monerobenchmarks.info/](url) Please feel free to check and submit your own results.

**Comment by mirix** [comment]
If it is a technical question, it depends on your hardware. If you are mining only with a single processor 320 h/s is fine for a mid-range quad-core or six-core. If you are using GPUs on top of your CPU or if you have more cores or a top-notch processor, then you should be getting more than that. 

On my 6-year-old notebook, I am getting 333 h/s out of the CPU (six-core Xeon) and 151 h/s out of the GPU (Nvidia Mobile). Combined 484 h/s. But it required some tweaking:

https://www.linkedin.com/pulse/miners-world-mind-your-kernel-edelmiro-moman/

If it is a "profitability" question. You can obtain an estimate of how many coins of a given cryptocurrency you are expected to mine at a given hashrate:

https://whattomine.com/coins/101-xmr-cryptonight

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
