### ISSUE TITLE
SOCKET ERROR

### ISSUE THREAD

**Issue by L2ne** [fireice-uk/xmr-stak#774]
Im running 5 Rx Vega 56 on Windows 10.
The miner works fine for a almost a day ... the problem is not caused by to much overclocking (the pc does NOT just turn off like when i set too high memory clock).
Basically what happens is that the server is not responding and the pc just restarts after one failed attemp. I already set the attemps from 0 (i kow it should try forever but it doesnt) to 50, but it doesnt help sometimes it failes after the first attemp or maybe up to 7 but then the pc just restarts.

One day sumokoin was on top on whatToMine and the pool was fucked due to so many people wanting to mine this... resulting in "no response from the server" also this caused my Rig to restard... even a fresh started one wich normaly runs 18h+ at least up to 2 days so far if not this error occures.

I just downloaded the compiled release.

also i noticed a hashrate difference when using 2.2 vs 1.4 ... in 1.4 i get MORE hashes with the same settings.
with 2.2 none of the vegas get to 1000 + ~850(they get like 960 + 700 or even less) but in 1.4 two of my cards get 1850 hashes
The problem is with both versions.

**Comment by JerichoJones** [comment]
If your PC is restarting you have some other problem to look into first. It seems very unlikely that STAK is causing (on its' own) the PC to restart.

**Comment by L2ne** [comment]
trust me it is! the incident with the pool pretty much proofed my suggestion.
it is very likely that STAK crashed when the server fails to respond(most of the time its crashing at the first retry attemp). last thing thats in the log is socket error and some "cant connect stuff". what i dont get is why its crashing when attemping to reconnect.

no other programms are running than STAK... i use overdriveNtool for settings ... but its not running at the same moment.
I disabled windows update restart stuff...

**Comment by JerichoJones** [comment]
Set your GPU back to defaults and test.
