### ISSUE TITLE
Feature req: JSON-formatted (or other machine-readable) data report, more report detail

### ISSUE THREAD

**Issue by mvpel** [fireice-uk/xmr-stak#776]
I'd like to be able to pull the runtime statistics for Cast-XMR in a machine-readable format. CastXMR, for example, puts out JSON on a network port, and this would be useful for XMR-STAK as well.

Having the hashrate report show what type of thread each one is - CPU, NVIDIA, or AMD - and perhaps some specifics about the device itself such as the model name, clock rates, PCI device path, etc, would allow more fine-grained monitoring and management of the run.

I'm working with the new Asus 19-slot board, and so scaling considerations are coming into play.

Also, perhaps include an indication of whether the reported difficulty in the results is fixed or dynamic. Thanks!

**Comment by JerichoJones** [comment]
>CastXMR, for example, puts out JSON on a network port, and this would be useful for XMR-STAK as well.

STAK has this. It is a bit limited but it is a start. Point your browser at:

http://YourMinerIP:port/api.json

**Comment by mvpel** [comment]
Splendid, thanks for the info!
