### ISSUE TITLE
CUDA 9.x doesnt work

### ISSUE THREAD

**Issue by abshkd** [fireice-uk/xmr-stak#777]
using latest tip from master.
`ccmake` cant detect `CUDA_SDK_ROOT_DIR` so I manually add `/usr/local/cuda-9.1` in ccmake
compiles fine but gives the error
`WARNING: NVIDIA Insufficient driver!`

nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

ldd libxmrstak_cuda_backend.so
```
        linux-vdso.so.1 =>  (0x00007ffe289fc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f90dfbe7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f90df9e3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f90df7da000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f90df571000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f90df12d000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f90deef2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f90deb70000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f90de95a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f90de58f000)
        /lib64/ld-linux-x86-64.so.2 (0x000055f1fb160000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f90de384000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f90de17a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f90dde70000)
```

System info
```
GTX 1060,  Ubuntu 16.04

compile options, only defined:
monero, opencl=off, and the cuda sdk root directory as above.
ARCH: 30;61
specified 30 for the other tx 660 card
````

please let me know if I have missed something and what other information can help.

Note: I have been able to compile other miners (not xmr) and run them off of this same system.

**Comment by mirix** [comment]
Did you install the developer driver 387.34 along with Cuda 9 or do you have a different version?

**Comment by abshkd** [comment]
I forget which one it was but this is what I have in my bash history
`sudo sh cuda_9.1.85_387.26_linux.run --override`

and output of SMI

` NVIDIA-SMI 384.90                 Driver Version: 384.90`

How do I know it is the `developer driver`?

**Comment by psychocrypt** [comment]
if nvidia-smi is showing the old version number than you have not updated
the driver correctly. Nvidia smi is the tool.to check the installed driver.

**Comment by abshkd** [comment]
Ok now I know what I did wrong. I will go hunt for a solution. Thanks.
Any clues on how I could fix this?

**Comment by abshkd** [comment]
It appears the latest driver is only 384.98 So does it still matter? versions still mismatch though.

**Comment by mirix** [comment]
1) Add the CUDA 9.1 repo:

$ wget -c http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb
$ sudo dpkg -i cuda-repo-ubuntu1604_9.1.85-1_amd64.deb
$ sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
$ sudo apt-get update

2) Search for the driver:

$ apt-cache search nvidia-387

3) If found, install it:

$ sudo apt-get install nvidia-387 nvidia-387-dev

4) If there are no error messages, reboot and run nvidia-smi to make sure you have the right version.

**Comment by abshkd** [comment]
Thank you. Let me try that today and post back the build results.

**Comment by DrLuke** [comment]
@abshkd Any progress?

**Comment by abshkd** [comment]
Sorry I have to take time to do this
 Injured right shoulder. It's still an issue. I upgraded the drivers and
just need to test again.
