### ISSUE TITLE
Unwanted CPU mining

### ISSUE THREAD

**Issue by CallumMcW** [fireice-uk/xmr-stak#779]
I only want to mine with my GPU however whenever I run the program it also mines with my CPU. How can I prevent this (its probably a simple command line/batch file fix)

**Comment by CallumMcW** [comment]
I think running it from the command line with --noCPU might work

**Comment by AzaZPPL** [comment]
Remove all cpu threads from cpu.txt. Your cpu threads should look like this:

`"cpu_threads_conf" : [],`

**Comment by JerichoJones** [comment]
@AzaZPPL NO.
@CallumMcW YES

**Comment by CallumMcW** [comment]
@JerichoJones Thanks
