### ISSUE TITLE
Config not created

### ISSUE THREAD

**Issue by cburghardt** [fireice-uk/xmr-stak#781]
I have compiled xmr-stak from sources on a SusE sytem (openSUSE Leap 42.3).
I have tried to install it to home directory as well as to /usr/local but I always run into the same issue:
the config files (in my case config.txt and cpu.txt) are created but empty. I have tried all variants of paths and so forth. 
In the end I copied the templates from sources and adjusted them but I wonder how the correct procedure should be.
Note that the binary works fine.

Version: v2.2.0-2ae7260

**Comment by psychocrypt** [comment]
remove all txt files and start the miner. Answere all questions.
If you still have issues post all output from the first start including
your answeres.

**Comment by cburghardt** [comment]
Please enter:
- Pool address: e.g. pool.usxmrpool.com:3333
xmr-eu1.nanopool.org:14433
- Username (wallet address or pool login):
47kPHy8wWJpbDySkyxKb92gxcKW7juwNxAwW7YbhaXmd3J4JPHRs581WbwaVe4vUMveKAzAiA4j8xgUi29TpKXpm3xqFSrG
- Password (mostly empty or x):
x
- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
y
- Do you want to use nicehash on this pool? (y/n)
n
- Do you want to use multiple pools? (y/n)
n
Configuration stored in file 'config.txt'
[2018-01-03 13:58:34] : File is empty or too short - config.txt.

**Comment by psychocrypt** [comment]
could you please run `ls -la` in the folder with the binary

**Comment by cburghardt** [comment]
It just contains the binary:
-rwxr-xr-x 1 root root 514776 Jan  3 11:02 xmr-stak

After the above step an empty config.txt is created (0 file size).

**Comment by cburghardt** [comment]
I just verified that the same works without problems on a Mac. So it is OS specific.

**Comment by JerichoJones** [comment]
Please fill out the template properly.

---
# Issue with the execution of STAK
- Which OS do you use?

- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
 
- Did you compile the miner yourself or are you running the release?  
   
   
 - Run  
 
```
    xmr-stak --version-long
```
and add the output here  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---
