### ISSUE TITLE
hardcoded settings for compiled xmr-stak

### ISSUE THREAD

**Issue by TuxMiner** [fireice-uk/xmr-stak#782]
Hi, yesterday I successfully compiled xmr-stak from source code for the first time, including cuda and amd support. Would it be possible to hardcode the miner settings (address, cpu settings, gpu, pretty much everything) into the compiled binary? Would I have to go through all the code and change a lot of things or is there an easier way? 

Thanks a lot for any insights..

**Comment by psychocrypt** [comment]
This is not supported but is an easy task for an programmer.
