### ISSUE TITLE
compile failed on windows7

### ISSUE THREAD

**Issue by s-mason** [fireice-uk/xmr-stak#783]
Please provide as much as possible information to reproduce the issue.

# Basic information
 CPU is AMD A8-3520

# Compile issues
  - Which OS do you use?
  ```WINDOWS 7 32-bit
  add **all** commands you used and the **full** compile output here
  ```<intrin.h> can not be found,<mutex> can not support.(i use cmake+mingw).i think these errors are not all,solve this ,there will be more.the code use too much  characters in c++ that windows don't support.
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```Yes.
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by JerichoJones** [comment]
#### What you should be doing to make this go as smoothly as possible

1. Choose a simple, clear title for your Issue Subject
2. Stick to one problem per issue report.
3. Describe the issue clearly.

    a. A short synopsis of what is happening.
    
    b. What you expect should be happening.
    
    c. Exact error message(s), if any.

	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
    
4. Describe what steps you have performed in an attempt to resolve the issue.

**Comment by JerichoJones** [comment]
I have no idea. Try it and see but I think that compiling under cygwin is out of scope for support.

**Comment by s-mason** [comment]
i reinstall my OS.Now ,i'm on win7 64-bit .i download the compiled file to run .but i has error ,too.
---------------------------------------------
D:\ProgramData\monero-gui-v0.11.1.0\xmr-stak-amd>xmr-stak-amd.exe
[2018-01-08 11:49:57] : Compiling code and initializing GPUs. This will take a w
hile...
[2018-01-08 11:49:58] : Device 0 work size 8 / 256.
[2018-01-08 11:49:58] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer
 to create hash scratchpads buffer.
Press any key to exit.
