### ISSUE TITLE
HD 4890 mining ?

### ISSUE THREAD

**Issue by why35** [fireice-uk/xmr-stak#785]
Hello ,

I have HD7700 series card and started to cpu+gpu mining , also want to add HD4890 in to the another pci16x slot but when i put and started to xmr (first i have deleted amd setting file) could not find another card.
I have W10 , W10 doesnt support the 4890 ? if yes and turn the W7 is that work ? 

Thank you very much

Barış

**Comment by joshgrobin** [comment]
http://support.amd.com/en-us/kb-articles/Pages/Driver-Support-for-AMD-Radeon%e2%84%a2-HD-4000%2c-HD-3000%2c-HD-2000-and-older-Series.aspx

There is the slight possibility that the driver that comes with Windows 10 lacks the OpenCL drivers.

**Comment by bovcan** [comment]
will not work. I could not run hd6870 and hd4770 in the same pc. Driver do not support such different models. 7700 and 6xxx might work...

**Comment by why35** [comment]
Thank you very much , so i will not try anymore and find one more 7700 or 7850 series for multi gpu
