### ISSUE TITLE
SOCKET ERROR

### ISSUE THREAD

**Issue by manuelale222** [fireice-uk/xmr-stak#786]
I'm using a core i7 with a amd r9 m265x video card, I´ve change de tls to false and change the pools but nothing works, even disable the firewall but the problem its still there, my config log is this:

"pool_list" :
[
	{"pool_address" : "pool.supportxmr.com:3333", "wallet_address" : "42zxsgDpvnMKtHPMnqkzW1JgMYM6DSjrX6VEuke3CVquALzCtUfmsoqYSuHmipBdFBJf7CcPrpX8T8Vk38QnvXFM33egznq", "pool_password" : "", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

thanks for your help

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by joshgrobin** [comment]
Have you been able to successfully mine with other software in the past from the same machine in the same location?

**Comment by manuelale222** [comment]
i´ve solved the problem, in password i had to put the "X" and then it worked
