### ISSUE TITLE
HD 7850 max hashrate ?

### ISSUE THREAD

**Issue by why35** [fireice-uk/xmr-stak#787]
Hello Guys ,

I have three computers 7/24 hour open , it is about monero mining

One of them have 1050ti - with OC around 350 h/s , checked benchmarks , it seems normal
Second HD7700 - with OC around 312 h/s , seems normal too
But my last one have HD7850 (Saphhire 1GB) seems max 195 h/s , checked benchmarks it should be around 300-400 isnt it ?

my amd config is..

----

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Pitcairn memory:524
  // compute units: 16
  { "index" : 0,
    "intensity" : 256, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

----------

whats the wrong with these settings ?

Thank you very much

Baris

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

**Comment by one-quaker** [comment]
Try to Increase intensity from 1000 to 2000, it helps on rx580
Also you can experiment with another values

**Comment by ptdev** [comment]
Hi, I have an hd7850 2gb and I get around 415H/s using claymore's miner for windows. HashCnt is set at 512 since it gives the best performance.
Last time I tried this miner I got a few hash's less (about 350..380) than using claymore's miner.
So, 195H/s definitely seems too low.
