### ISSUE TITLE
NO GPU mining and no GPU config file created

### ISSUE THREAD

**Issue by feugen** [fireice-uk/xmr-stak#789]
Hello,

I just compiled xmr-stak and I dont see any GPU config file, bit there is one for CPU. I try to launch xmr-stak and its working fine but it just using CPU and no GPU. Hashrate is just about 300h/s as it used to be with xmr-stack-cpu. I got Vega 56 and its the only one gpu in my computer, and its not working.

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU: E5-2670
  - Type of the GPU: AMD Vega 56

# Compile issues
  - Which OS do you use? Debian 9, 3.15 kernel
  ```
  add **all** commands you used and the **full** compile output here:

  ```
efischer@Server:~$ git clone https://github.com/fireice-uk/xmr-stak.git
Klone nach 'xmr-stak' ...
remote: Counting objects: 3365, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 3365 (delta 9), reused 14 (delta 6), pack-reused 3342
Empfange Objekte: 100% (3365/3365), 1003.25 KiB | 96.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (2342/2342), Fertig.
efischer@Server:~$ mkdir xmr-stak/build
efischer@Server:~$ cd xmr-stak/build
efischer@Server:~/xmr-stak/build$ cmake ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:209 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

-- Configuring incomplete, errors occurred!
See also "/home/efischer/xmr-stak/build/CMakeFiles/CMakeOutput.log".
efischer@Server:~/xmr-stak/build$ cmake .. -DCUDA_ENABLE=OFF
-- Set miner currency to 'monero' and 'aeon'
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/efischer/xmr-stak/build
efischer@Server:~/xmr-stak/build$ make install
Scanning dependencies of target xmr-stak-c
[  3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[  6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 17%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 24%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/jconf.cpp.o
[ 27%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
[ 31%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/hwlocMemory.cpp.o
[ 34%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/jconf.cpp.o
[ 37%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
[ 41%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/backendConnector.cpp.o
[ 44%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/globalStates.cpp.o
[ 48%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/crypto/cryptonight_common.cpp.o
[ 51%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/httpd.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/http/webdesign.cpp.o
[ 58%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/console.cpp.o
[ 62%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/executor.cpp.o
[ 65%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/telemetry.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/misc/utility.cpp.o
[ 72%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/jpsock.cpp.o
[ 75%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/net/socket.cpp.o
[ 79%] Linking CXX static library bin/libxmr-stak-backend.a
[ 79%] Built target xmr-stak-backend
Scanning dependencies of target xmrstak_opencl_backend
[ 82%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o
[ 86%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/jconf.cpp.o
[ 89%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/minethd.cpp.o
[ 93%] Linking CXX shared library bin/libxmrstak_opencl_backend.so
[ 93%] Built target xmrstak_opencl_backend
Scanning dependencies of target xmr-stak
[ 96%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[100%] Linking CXX executable bin/xmr-stak
[100%] Built target xmr-stak
Install the project...
-- Install configuration: "Release"
xmr-stak installed to folder 'bin'

  ```
  run `cmake -LA .` in the build folder and add the output here:
```
efischer@Server:~/xmr-stak/build$ cmake -LA
CMake Error: The source directory "/home/efischer/xmr-stak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-7
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-7
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-7
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-7
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/efischer/xmr-stak/build
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
CUDA_ENABLE:BOOL=OFF
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/usr/include
OpenCL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libOpenCL.so
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all
```

# Issue with the execution
  - Do you compiled the miner by our own? yes
  ```
  run `./xmr-stak --version-long` and add the output here:
Version: xmr-stak/2.2.0/2ae7260/master/lin/amd-cpu/aeon-monero/20
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
Number of platforms                               0
  ```

# Stability issue
  - Is the CPU or GPU overclocked? NO
  - Is the Main memory of the CPU or GPU undervolted? NO

**Comment by psychocrypt** [comment]
please post the output of the miner. The reason is written down in the
ouput log.

**Comment by feugen** [comment]
efischer@Server:~/xmr-stak/build$ '/home/efischer/xmr-stak/build/bin/xmr-stak'
[2018-01-03 23:32:24] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:24] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:24] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:24] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:24] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.2.0 2ae7260

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-01-03 23:32:25] : Start mining: MONERO
[2018-01-03 23:32:25] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-01-03 23:32:25] : WARNING: No OpenCL platform found.
[2018-01-03 23:32:25] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-03 23:32:25] : WARNING: backend AMD disabled.
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 0.
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 1.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 2.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 3.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 4.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 5.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 6.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 7.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 8.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : Starting 1x thread, affinity: 9.
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : hwloc: memory pinned
[2018-01-03 23:32:25] : MEMORY ALLOC FAILED: mmap failed
[2018-01-03 23:32:25] : Fast-connecting to fr01.supportxmr.com:80 pool ...
[2018-01-03 23:32:25] : Pool fr01.supportxmr.com:80 connected. Logging in...
[2018-01-03 23:32:25] : Difficulty changed. Now: 2000.
[2018-01-03 23:32:25] : Pool logged in.
[2018-01-03 23:32:27] : Result accepted by the pool.
[2018-01-03 23:32:28] : Result accepted by the pool.
[2018-01-03 23:32:29] : Result accepted by the pool.

**Comment by feugen** [comment]
I dont care about openCL at this stage.

**Comment by psychocrypt** [comment]
You need to install the opencl driver from amd to get your vega running.
Currently you have driver issues.
