### ISSUE TITLE
libxmrstak_cuda_backend.so: undefined symbol

### ISSUE THREAD

**Issue by sheepchen** [fireice-uk/xmr-stak#79]
Heyho,
before I mined Monero with xmr-stak-cpu and xmr-stak-nvidia. Now i tried xmr-stak. The compiling went like a charm (except i have not the AMD sources whats OK because I only use NVIDIA)

System: i5-4 Gen. (4 Core no HT) with 4x GTX 1060 3GB

Then I start the software and this happends:

``` 
Please enter:
- currency: 'monero' or 'aeon'
monero
- pool address: e.g. pool.usxmrpool.com:3333
pool.supportxmr.com:5555
- user name (wallet address or pool login):
[...]BMYCBFbLU52L[...] # shorten
- password (mostly empty or x):
mpm01:<my email>
Configuration stored in file 'config.txt'
-------------------------------------------------------------------
xmr-stak 2.0.0-predev mining software.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
NVIDIA mining code was written by KlausT and psychocrypt.
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 1.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-29 01:01:17] : Start mining: MONERO
[2017-10-29 01:01:17] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2017-10-29 01:01:17] : Starting NVIDIA GPU thread 0, no affinity.
[2017-10-29 01:01:17] : Starting NVIDIA GPU thread 1, no affinity.
[2017-10-29 01:01:17] : Starting NVIDIA GPU thread 2, no affinity.
[2017-10-29 01:01:17] : Starting NVIDIA GPU thread 3, no affinity.
[2017-10-29 01:01:17] : CPU configuration stored in file 'cpu.txt'
[2017-10-29 01:01:17] : Starting single thread, affinity: 0.
[2017-10-29 01:01:17] : hwloc: memory pinned
[2017-10-29 01:01:17] : Starting single thread, affinity: 1.
[2017-10-29 01:01:17] : hwloc: memory pinned
[2017-10-29 01:01:17] : Starting single thread, affinity: 2.
[2017-10-29 01:01:17] : hwloc: memory pinned
[2017-10-29 01:01:17] : Connecting to pool pool.supportxmr.com:5555 ...
[2017-10-29 01:01:17] : Connected. Logging in...
[2017-10-29 01:01:17] : Difficulty changed. Now: 5000.
[2017-10-29 01:01:17] : Pool switched.
./xmr-stak: symbol lookup error: ./libxmrstak_cuda_backend.so: undefined symbol: _Z25cryptonight_core_cpu_hashILm524288ELm2097136ELj19EEvP8nvid_ctx
root@mpm01:/work/Monero/xmr-stak#

```

Annd.. Will the other projects be continued, or is this the leading project?

**Comment by sheepchen** [comment]
to info: 
The error is reproducible (obviously).
The old system (xmr-stak-nvidia and xmr-stak-cpu side by side) works fine.
Ubuntu Server 17.04

**Comment by psychocrypt** [comment]
Thx for reporting the bug should be fixed with #76.
This reposetory is currently beta and the new upcomming xmr-stak.

**Comment by sheepchen** [comment]
Yea, no problem. If you need any more data just say it. At the moment I run the old programs, but I leave the xmr-stack binary (+src) on server. I am an developer by myself (C#) so I now how hard it is to program an program that must run on all different systems (OS and hardware).

So if you need an testsubject I am your man ;P.

Where should I put future feature-requests? In the ‚old‘ (splitted) reposetories or in this new one?

**Comment by psychocrypt** [comment]
If you have time you could test #76.

Please add new feature request to this reposetory.

**Comment by sheepchen** [comment]
I would like to test this version. However, I am not so familiar with GIT. I am only registered at GIT to follow this project. on the main page (https://github.com/fireice-uk/xmr-stak) is only #72 available. How can I get the sources of #76?
Or do I have to download all changed files (https://github.com/fireice-uk/xmr-stak/pull/76) and exchange them manually in the source code? That seems a bit awkward to me. But if that's the only way, I will.

**Comment by psychocrypt** [comment]
You can download the zip of the PR directly e.g.
https://github.com/psychocrypt/xmr-stak/archive/fix-winCompilerAndAeon.zip

**Comment by sheepchen** [comment]
First now the binary works fine. But I get worse results than with the standalone programs.
(look at GPUs)

note for all tests. GPU 0 & 1 are only xmr-stak-*. GPU 2 & 3 run also ffmpeg.

xmr-stak
--------
config:

```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],

```
```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 831/3013 MiB
  { "index" : 0,
    "threads" : 12, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 831/3013 MiB
  { "index" : 1,
    "threads" : 12, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 831/3013 MiB
  { "index" : 2,
    "threads" : 12, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 831/3013 MiB
  { "index" : 3,
    "threads" : 12, "blocks" : 27,
    "bfactor" : 0, "bsleep" :  0,
    "affine_to_cpu" : false,
  },
],
```

Running several hours.

HASHRATE REPORT
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 387.6 | 387.4 | 386.4 |  1 | 307.9 | 307.5 | 306.6 |
|  2 | 203.7 | 196.4 | 200.3 |  3 | 206.1 | 211.0 | 207.7 |
|  4 | 20.4 | 20.3 | 20.5 |  5 | 18.3 | 18.3 | 18.8 |
|  6 | 19.7 | 20.0 | 20.3 |
-----------------------------------------------------
Totals:   1163.6 1160.8 1160.6 H/s
Highest:  1330.0 H/s



xmr-stak-cpu
------------
config:

```
"cpu_threads_conf" :
[
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 }
],
```

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 22.4 | 21.0 | (na) |  1 | 26.6 | 26.2 | (na) |
|  2 | 17.2 | 15.9 | (na) |
-----------------------------------------------------
Totals:   66.1 63.1 (na) H/s
Highest:  69.4 H/s



xmr-stak-nvidia
---------------
config:

```
"gpu_threads_conf" :
 [
     { "index" : 0, "threads" : 16, "blocks" : 64, "bfactor" : 8, "bsleep" : 5, "affine_to_cpu" : true },
     { "index" : 1, "threads" : 16, "blocks" : 64, "bfactor" : 8, "bsleep" : 5, "affine_to_cpu" : true },
     { "index" : 2, "threads" : 16, "blocks" : 64, "bfactor" : 8, "bsleep" : 5, "affine_to_cpu" : true },
     { "index" : 3, "threads" : 16, "blocks" : 64, "bfactor" : 8, "bsleep" : 5, "affine_to_cpu" : true }
 ],
```

HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 426.0 | 425.8 | (na) |  1 | 424.2 | 424.2 | (na) |
|  2 | 317.5 | 327.0 | (na) |  3 | 316.5 | 325.6 | (na) |
-----------------------------------------------------
Totals:   1484.2 1502.5 (na) H/s
Highest:  1537.1 H/s


If I copy config from xmr-stak-cpu and xmr-stak-nvidia into desired xmr-stak-configfiles the following happend:

-------------------------------------------------------------------
xmr-stak 2.0.0-predev mining software.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
NVIDIA mining code was written by KlausT and psychocrypt.
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 2.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-29 14:36:40] : Start mining: MONERO
[2017-10-29 14:36:40] : Starting NVIDIA GPU thread 0, no affinity.
[2017-10-29 14:36:40] : Starting NVIDIA GPU thread 1, no affinity.
[2017-10-29 14:36:40] : Starting NVIDIA GPU thread 2, no affinity.
[2017-10-29 14:36:40] : Starting NVIDIA GPU thread 3, no affinity.
[2017-10-29 14:36:40] : Starting single thread, affinity: 1.
[2017-10-29 14:36:40] : hwloc: memory pinned
[2017-10-29 14:36:40] : Starting single thread, affinity: 2.
[2017-10-29 14:36:40] : hwloc: memory pinned
[2017-10-29 14:36:40] : Starting single thread, affinity: 3.
[2017-10-29 14:36:40] : hwloc: memory pinned
[2017-10-29 14:36:40] : Connecting to pool pool.supportxmr.com:5555 ...
[2017-10-29 14:36:40] : Connected. Logging in...
[2017-10-29 14:36:40] : Difficulty changed. Now: 5000.
[2017-10-29 14:36:40] : Pool switched.
[CUDA] Error gpu 2: </work/Monero/xmr-stak/src/76/xmr-stak-fix-winCompilerAndAeon/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:203
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: out of memory
Abgebrochen (Speicherabzug geschrieben)
root@mpm01:/work/Monero/xmr-stak#

**Comment by sheepchen** [comment]
XMR-GPU
status:        running
GPU 0:         425.8 H/s / 57°C / 57.90 W / 23 Tx MB / 62 Rx MB
GPU 1:         425.5 H/s / 63°C / 62.80 W / 19 Tx MB / 48 Rx MB
GPU 2:         340.5 H/s / 62°C / 60.22 W / 46 Tx MB / 267 Rx MB
GPU 3:         344.7 H/s / 56°C / 54.61 W / 45 Tx MB / 307 Rx MB
GPU Total:     1536.5 H/s
This is standard with my current setup:

XMR-CPU
status:        running
Temp:          58 °C
CPU Total:     53.3 H/s

Total:         1589.8 H/s
1 Monero in €: 75.55 €
€ per day:     2.2293 €

**Comment by psychocrypt** [comment]
Do you edited the 16x64 condig from the nvidia miner by hand? This is not
the autosuggestion or?
Could you test both miner with the same config.
The cpu has maybe a bug, large page allocation is broken.

**Comment by psychocrypt** [comment]
memory: 831/3013 MiB Show that only 831 MiB of the 3 GiB are free.
Please end all prozesses to get the full performance. The miner create
a config to fit into 800MIB memory.

**Comment by sheepchen** [comment]
I edit the GPU-config by hand and it works fine with the xmr-stak-nvidia in linux and windows 10.

This are my GPUs only with the ffmpeg-processes. (I can not stop them because I render many TB of video-material)
![grafik](https://user-images.githubusercontent.com/32341444/32144721-9e53d476-bcbd-11e7-9ffb-c2fd54824f8e.png)

This is the system with ffmpeg at 2&3 and xmr-stak-nvidia above all 4 cards. This works for days without any problem. (The 'systemscreen' in at the internel i5-cpu, so all cards are for workloads)
(see config above for xmr-stak-nvidia)
![grafik](https://user-images.githubusercontent.com/32341444/32144752-09333372-bcbe-11e7-8340-7293c7e76335.png)

If I run the same GPU-config in xmr-stak (nvidia.txt) I get the above mentioned error
```
[CUDA] Error gpu 2: </work/Monero/xmr-stak/src/76/xmr-stak-fix-winCompilerAndAeon/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:203
terminate called after throwing an instance of 'std::runtime_error'
what(): [CUDA] Error: out of memory
```

**Comment by sheepchen** [comment]
forget it. Problem was that i killed the xmr-stak-nvidia but even if the process-ID was invalid the GPU-RAM wasnt freed. after flushing the hole PCI-bus and restarting xmr-stak everything works find. This version (#76) is good.

The results are better, too.

```
HASHRATE REPORT
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 426.4 | 426.5 | (na) |  1 | 425.2 | 425.6 | (na) |
|  2 | 325.4 | 334.5 | (na) |  3 | 329.8 | 337.8 | (na) |
|  4 | 18.8 | 18.8 | (na) |  5 | 19.8 | 20.0 | (na) |
|  6 | 19.3 | 18.8 | (na) |
-----------------------------------------------------
```

The 'autosuggestion' was way off, but with my handwritten config the values are similar.

**Comment by psychocrypt** [comment]
Thx for the feedback. Maybe we should add a cleaner shutdown where we reset
the used gpus.
