### ISSUE TITLE
GPU Not Recognized During Autoconfig

### ISSUE THREAD

**Issue by Dfity2** [fireice-uk/xmr-stak#792]
I compiled from xmr-2.2.0 under Win 10 without problem,  Upon running for the first time, no amd.txt is generated.  Output from miner says no AMD device found.  What is causing the GPU to not be recognized? 

[2018-01-03 17:14:23] : Start mining: MONERO
WARNING: NVIDIA Insufficient driver!
[2018-01-03 17:14:26] : WARNING: backend NVIDIA disabled.
[2018-01-03 17:14:27] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2018-01-03 17:14:27] : WARNING: CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for of devices.
[2018-01-03 17:14:27] : WARNING: No AMD device found.
[2018-01-03 17:14:27] : WARNING: backend AMD disabled.
[2018-01-03 17:14:27] : CPU configuration stored in file 'cpu.txt'
[2018-01-03 17:14:27] : Starting 1x thread, affinity: 0.
[2018-01-03 17:14:27] : hwloc: memory pinned
[2018-01-03 17:14:27] : Starting 1x thread, affinity: 1.
[2018-01-03 17:14:27] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2018-01-03 17:14:27] : hwloc: memory pinned
[2018-01-03 17:14:27] : Starting 1x thread, affinity: 2.
[2018-01-03 17:14:27] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.
[2018-01-03 17:14:27] : hwloc: memory pinned
[2018-01-03 17:14:27] : MEMORY ALLOC FAILED: VirtualAlloc failed. Reboot might help.

# Basic information
  - i5-2500K
  - MSI RX560 AMD

# Compile issues
  - Which OS do you use?
  Win10
 
# Issue with the execution
  - Do you compiled the miner by our own?
 Yes

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by psychocrypt** [comment]
PLease try to run `clinfo.exe` but anyway it looks like an driver issue. Please update you driver!

**Comment by Dfity2** [comment]
Here is the clinfo log.  I currently have the AMD blockchain drivers installed.  I'm not sure where I should look for a problem in the log.

Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2442.9)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     1002h
  Board name:
  Max compute units:                             4
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           1024
  Preferred vector width char:                   16
  Preferred vector width short:                  8
  Preferred vector width int:                    4
  Preferred vector width long:                   2
  Preferred vector width float:                  8
  Preferred vector width double:                 4
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3293Mhz
  Address bits:                                  64
  Max memory allocation:                         3216679936
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            8192
  Max image 2D height:                           8192
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   4096
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    32768
  Global memory size:                            12866719744
  Constant buffer size:                          65536
  Max number of constant args:                   8
  Local memory type:                             Global
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          3216679936
  Max global variable size:                      1879048192
  Max global variable preferred total size:      1879048192
  Max read/write image args:                     64
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     1
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    311
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   00007FFD64E93168
  Name:                                                 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
  Vendor:                                        GenuineIntel
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2442.9 (sse2,avx)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2442.9)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event

**Comment by JerichoJones** [comment]
Did I miss where you gave us the model of your GPU?

**Comment by psychocrypt** [comment]
It is an driver issue clinfo is also not showing your gpu. clinfo only
detects the cpu. Please install the amd gpu driver.
