### ISSUE TITLE
Compile for Windows

### ISSUE THREAD

**Issue by JuDucky** [fireice-uk/xmr-stak#793]
I went through the whole process to configure xmr-stak (cpu and gpu) and it worked until i got to the last step, which is titled "Compile"

When I run the code "for CUDA 9 and/or AMD GPUs, CPU" i get an error saying that the source directory doesnt have CMakeLists.txt

I am super new to this so it might be something super simple. I'm thinking I may be in the wrong directory, but I also tried doing all of this in the "xmr-stak-dep" directory I made under my C:\ drive, and it gave me the same errors.

Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

I am running a i5-6600 with 32GB RAM and 2X GTX 950FTW. 

# Compile issues
  - Which OS do you use?

Windows 10

  add **all** commands you used and the **full** compile output here

C:\Users\Julian\Downloads\xmr-stak-master\build>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
C:\Users\Julian\Downloads\xmr-stak-master\build>set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl

C:\Users\Julian\Downloads\xmr-stak-master\build>mkdir build

C:\Users\Julian\Downloads\xmr-stak-master\build>cd build

C:\Users\Julian\Downloads\xmr-stak-master\build\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64
CMake Error: The source directory "C:/Users/Julian/Downloads/xmr-stak-master/build/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

C:\Users\Julian\Downloads\xmr-stak-master\build\build>

  run `cmake -LA .` in the build folder and add the output here

C:\Users\Julian\Downloads\xmr-stak-master\build\build>cmake-LA
'cmake-LA' is not recognized as an internal or external command,
operable program or batch file.

# Issue with the execution
  - Do you compiled the miner by our own?

Yes

  run `./xmr-stak --version-long` and add the output here

'.' is not recognized as an internal or external command,
operable program or batch file.

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here

'clinfo' is not recognized as an internal or external command,
operable program or batch file.

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

No

**Comment by ChaosMarc** [comment]
>CMake Error: The source directory "C:/Users/Julian/Downloads/xmr-stak-master/build/build" does not appear to contain CMakeLists.txt.

you created a build directory in your already existing build directory "\build\build". delete the bottom level one and execute the "cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64" and all following commands in the top level build directory.

>'.' is not recognized as an internal or external command,

If a command starts with ./ it is written in the linux syntax. just omit the ./ and add ".exe" behind "xmr-stak" -> "xmr-stak.exe --version-long"

**Comment by JuDucky** [comment]
I think I found another problem... I never did the step before which was build the system... I'm guessing that's important, but I don't really understand any of it... Is that something it would be better to ask a friend for?

**Comment by ChaosMarc** [comment]
I will give you the steps for a clean build I execute each time I build. You maybe have to adjust your paths in the first to lines. the rest should work fine.

`set XMR_STAK_PATH=C:\xmr-stak
set XMR_STAK_DEP_PATH=C:\xmr-stak-dep
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
set CMAKE_PREFIX_PATH=%XMR_STAK_DEP_PATH%\hwloc;%XMR_STAK_DEP_PATH%\libmicrohttpd;%XMR_STAK_DEP_PATH%\openssl
rmdir /Q /S %XMR_STAK_PATH%\build
mkdir %XMR_STAK_PATH%\build
cd %XMR_STAK_PATH%\build
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
cmake --build . --config Release --target install`

**Comment by JuDucky** [comment]
i used "xmr-stak-master" for my source code and "xmr-stak-dep" for where the binaries are built and got this error:

CMake Error at CMakeLists.txt:319 (message):
  microhttpd NOT found: use `-DMICROHTTPD_ENABLE=OFF` to build without http
  deamon support

**Comment by ChaosMarc** [comment]
something must be wrong with your dependencies (either path, or the deps themselves) either you find your problem with that, or you do what the error suggests and add

**Comment by langyajiekou** [comment]
I also have the same problem:

My directory tree is like below:
E:\PROJECT\XMR-STAK
├─backend
│  ├─amd
│  │  └─amd_gpu
│  │      └─opencl
│  ├─cpu
│  │  └─crypto
│  └─nvidia
│      └─nvcc_code
├─build
├─cli
├─http
├─misc
├─net
└─rapidjson
    ├─error
    ├─internal
    └─msinttypes
E:\PROJECT\XMR-STAK-DEP
├─hwloc
│  ├─include
│  │  ├─hwloc
│  │  │  └─autogen
│  │  └─private
│  │      └─autogen
│  └─lib
├─libmicrohttpd
│  ├─include
│  └─lib
└─openssl
    ├─bin
    ├─include
    │  └─openssl
    └─lib
E:\Project\xmr-stak\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
CMake Error: The source directory "E:/Project/xmr-stak" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

as I found the master has CMakeLists.txt, so, I tried to copy CMakeLists.txt from master to xmr-stak folder and run again.

I don't want to compile a GPU neither Nvidia nor AMD but just for CPU miner, however, `cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..` would tell me _CMake Error at CMakeLists.txt:209 (message):   CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support_

If i set to OFF for above, it will then tell me another Error, says there's no ADM GPU support. and repeat again. balabala... and it would asked me to append many other parameters, such as disable hwloc, httpd, ssl, etc... so what's wrong with it? any steps I missed?

**Comment by JuDucky** [comment]
I have gotten to the point where it's just giving me an error for OpenSSL dependencies and I feel like I want those... Correct me if I'm wrong on that?

**Comment by JerichoJones** [comment]
As @ChaosMarc said, "something must be wrong with your dependencies (either path, or the deps themselves) either you find your problem with that, or you do what the error suggests and add 
-DMICROHTTPD_ENABLE=OFF to your cmake command"
