### ISSUE TITLE
New patch breaks windows binary

### ISSUE THREAD

**Issue by JiKv** [fireice-uk/xmr-stak#795]
Hello,

I was running xmr-stak 2.2.0 c4400d19 (provided binary i did not try to compile own) with cuda9.1 drivers at Windows 2016 core server at Nvidia 750M 2GB. 
Today I updated Windows with https://support.microsoft.com/en-hk/help/4056890/windows-10-update-kb4056890  

And now I am getting [CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:322

Any idea if this may be related to new Intel CPU fix which is somehow in new patch ?

**Comment by JerichoJones** [comment]
What happens if you set the below registry value to 1 ?

```
Key="HKEY_LOCAL_MACHINE"Subkey="SOFTWARE\Microsoft\Windows\CurrentVersion\QualityCompat"
Value Name="cadca5fe-87d3-4b96-b7fb-a231484277cc"
Type="REG_DWORD”
Data="0x00000000”
```

**Comment by JiKv** [comment]
Hello, 
changing this is not working ( i even rebooted server to be sure that it is applied) I guess it has only to do something with Antivirus as mentioned at Microsoft article.

**Comment by JerichoJones** [comment]
All of my machines (Windows 10) have updated and I am not seeing this problem. Test on Windows 10 to rule out the OS.
  
Then fill out the template properly.

---
# Issue with the execution of STAK
- Which OS do you use?

- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
 
- Did you compile the miner yourself or are you running the release?  
   
   
 - Run  
 
```
    xmr-stak --version-long
```
and add the output here  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---

**Comment by JiKv** [comment]
Hello,

I had to change nvidia.txt and reduce memory usage and it started working. Not sure why patch broke it. Card is 2GB and it was using 130/6 => 1.5GB. I had to reduce it to 100/6 => 1.2GB only to have it working again.
