### ISSUE TITLE
Compiling for AMD on Linux(Ubuntu)

### ISSUE THREAD

**Issue by michael-from-there** [fireice-uk/xmr-stak#796]
EASY-TO-SAY: "download and install the latest version AMD APP SDK" 
easy, but not for windows-donkeys))

This stopped me: 

from AMD installation guide:

3.    Installation succeeds and completes the following:

a.   Sets and exports AMDAPPSDKROOT to the AMD APP SDK installation path via 
/etc/profile.d/AMDAPPSDK.sh.

b.    If Catalyst is is not installed: 
–Registers the OpenCL Installable  Client  Driver  (ICD)  via  
/etc/OpenCL/vendors.
–Sets and exports LD_LIBRARY_PATH  to  the  OpenCL  library  path  via /etc/ld.so.conf.d/amdapp_x86.conf (amdapp_x86_64.conf).

These changes are reflected to all the users.

c.    Installs the Linux AMD APP SDK sample files and binaries by default under 
/opt/AMDAPPSDK-3.0/.

d.    Installs the Linux AMD APP SDK CPU runtime files under /opt/AMDAPPSDK-3.0/lib.

4.   To change or update the environment variables: 
i.   Open /etc/profile.d/AMDAPPSDK.sh, and then verify and update the AMDAPPSDKROOT.
ii.  Verify and update LD_LIBRARY_PATH using the /etc/ld.so.conf.d/amdapp_x86.conf and /etc/ld.so.conf.d/amdapp_x86_64.conf files

This what writing compile terminal:

make[2]: *** No rule to make target «/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so», needed by: «bin/libxmrstak_opencl_backend.so».  Stop.
CMakeFiles/Makefile2:144: recipe for target 'ALL' failed: «CMakeFiles/xmrstak_opencl_backend.dir/all»
make[1]: *** [CMakeFiles/xmrstak_opencl_backend.dir/all] Error 2
Makefile:127:  recipe for target 'ALL' failed:
make: *** [all] Error 2

PLEASE HELP !

**Comment by mvpel** [comment]
I ran into this as well - the problem is the symlink in the AMD installation - a case should be opened with AMD. Changing the symlink to /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 resolves the issue and allows compile. Copy and paste the following:

```
sudo mv /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so.badlink
sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
```

**Comment by michael-from-there** [comment]
Thank you so much, i waste a lot of time to this. Now i try to figure out what you do, cause all works perfectly !

**Comment by mvpel** [comment]
Glad to hear it! Be sure to mark this issue as closed, so we can save some of the developers' valuable time.

**Comment by professorviz** [comment]
i can compile but it will not use or create a gpu.txt file
