### ISSUE TITLE
Higher than 5 cache count?

### ISSUE THREAD

**Issue by dancudds** [fireice-uk/xmr-stak#797]
For CPUs with very high cache - is it possible to increase the thread size past 5?

**Comment by keepotalize** [comment]
Yea, have my ryzen 1700 running 8 threads atm

**Comment by dancudds** [comment]
How do you do this? The max thread count is 5 from what I can see.

**Comment by keepotalize** [comment]
What is your CPU? 

You just paste more threads in the cpu.txt file. 

```
"cpu_threads_conf" :
[
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
        { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
        { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
        { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
	{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
        { "low_power_mode" : false,, "no_prefetch" : true, "affine_to_cpu" : 14 },
],

```

**Comment by dancudds** [comment]
Sorry - I mean running multiple threads on the same CPU core. Using the low_power_mode option

**Comment by JayWalker512** [comment]
@dancudds to be clear, those are not extra threads. Low power mode just alters the algorithm to use additional cache. 5x is the max setting for "low_power_mode" as far as I know.

**Comment by dancudds** [comment]
@JayWalker512 Thanks - I don't know if it's possible to add more into the additional cache. My CPU only has 1 core but lots of cache. I tried adding a different cache algo but it corrupts the shares.

**Comment by dancudds** [comment]
Here's my failed attempts at adding 6 into the cache 
https://github.com/dancudds/xmr-stak/blob/master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h

**Comment by dancudds** [comment]
To be clear - I just get rejected shares when trying to use 6 cache threads on 1 core

**Comment by psychocrypt** [comment]
only up to 5 is supported
