### ISSUE TITLE
backend amd disabled

### ISSUE THREAD

**Issue by diamondeye966** [fireice-uk/xmr-stak#798]
# Basic information

  - Type of the GPU (if you try to miner with the GPU).
amd r9 290 4Gb

# Compile issues
  - Which OS do you use?
  Windows 8.0
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?
 No.


Hello everyone, My problem is whenever i run xmr-stak it works fine on 512 intensity but my GPU is amd r9 290 4gb, it should be accept to give 1024 or atleast 768 intensity but whenever i increase it, it gives warning: amd device not found. And warning:backend amd disabled. 
What can be the problem? 

heres the config.

"gpu_threads_conf" : [
  // gpu: Hawaii memory:896
  // compute units: 40
  { "index" : 0,
    "intensity" : 768, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

**Comment by diamondeye966** [comment]
![amd](https://user-images.githubusercontent.com/35115422/34582950-a0e4141a-f1b7-11e7-9be2-31cb9aa8b20d.gif)

**Comment by Simaex** [comment]
@diamondeye966 The core of your problem is there
// gpu: Hawaii memory:896
For some unclear reason miner fail to recognise full amount of memory of your GPU
I have the same issue with Cayman GPU, only 386M from 2G are recognised by the miner.
@psychocrypt try to figure what's on but obviously our old GPUs are not of high priority for dev's so still patiently waiting.

**Comment by psychocoderHPC** [comment]
you can try to set the following environment variables before you start the miner form ther terminal.
https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md#increase-memory-pool

**Comment by psychocrypt** [comment]
you can try to set the following environment variables before you start the miner form ther terminal.
https://github.com/fireice-uk/xmr-stak/blob/master/doc/tuning.md#increase-memory-pool

**Comment by diamondeye966** [comment]
@Simaex  Do you have any idea how is that done? have no idea what to do with the git psychocrypt sent.

**Comment by diamondeye966** [comment]
where to add 
export GPU_FORCE_64BIT_PTR=1
export GPU_MAX_HEAP_SIZE=99
export GPU_MAX_ALLOC_PERCENT=99
export GPU_SINGLE_ALLOC_PERCENT=99
in amd.txt ?
its giving errors, do we need " in start and end?

**Comment by diamondeye966** [comment]
/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * strided_index - switch memory pattern used for the scratch pad memory
 *                 true  = use 16byte contiguous memory per thread, the next memory block has offset of intensity blocks
 *                 false = use a contiguous block of memory per thread
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false, "strided_index" : true },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Hawaii memory:2944
  // compute units: 40
  { "index" : 0,
    "intensity" : 960, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

set GPU_FORCE_64BIT_PTR=1
set GPU_MAX_HEAP_SIZE=99
set GPU_MAX_ALLOC_PERCENT=99
set GPU_SINGLE_ALLOC_PERCENT=99

**Comment by Simaex** [comment]
@diamondeye966 It is usual practice to set enviromental variables for AMD GPU mining. Just run the next commands from command line before starting miner. I use to start miner with a batch file with this set of commands.
setx GPU_FORCE_64BIT_PTR=1
setx GPU_MAX_HEAP_SIZE=99
setx GPU_MAX_ALLOC_PERCENT=99
setx GPU_SINGLE_ALLOC_PERCENT=99

In my case (W10 Pro 64 ver1709, Cayman GPU) it did not help. Please update when you try.

**Comment by Simaex** [comment]
@diamondeye966 it seem to work for you, to some degree
// gpu: Hawaii memory:2944

**Comment by diamondeye966** [comment]
@Simaex well i didn't run a command, i simply pasted the set values in amd.txt, it gave errors, i deleted the file and now it has increased. I still have to get atleast 3gb right?

**Comment by diamondeye966** [comment]
it still dosent run at 960, works at 900 intensity though, while it should be at 1024.

**Comment by psychocrypt** [comment]
In the first post you wrote you can not run intensity 756. Now you can run
960. This would mean you increased you hashes. I am right?

**Comment by diamondeye966** [comment]
I did.
Now i increased more.

"gpu_threads_conf" : [
  // gpu: Hawaii memory:3672
  // compute units: 40
  { "index" : 0,
    "intensity" : 960, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],

**Comment by diamondeye966** [comment]
Control Panel\System and Security\System\Advanced\Environment Variables.

I set it there, i guess its permanent now, Btw is 3672 the max i can get?

**Comment by diamondeye966** [comment]
i cant get above 900. 
It says Error: CL_MEM_OBJECT_ALLOCATION_FAILURE when calling cLenque-NDrange Kernal for Kernal C

**Comment by diamondeye966** [comment]
890 is the max intensity i can set, which dosent give the above error

**Comment by psychocrypt** [comment]
This is the free memory in MB. For your gpu every over intensity of 1024
will reduce your hash rate. Therr reason is the small tlb.

**Comment by Simaex** [comment]
@diamondeye966 Control Panel\System and Security\System\Advanced\Environment Variables is the right place to set. But it is a hard way.

I set it there, i guess its permanent now, Btw is 3672 the max i can get? - it depends on you card or cards, driver and OS. If you are using several GPU expect smaller amount on one of them cause needed to run GUI

**Comment by Simaex** [comment]
BTW what hashrate do you get?

**Comment by diamondeye966** [comment]
well its not constant, goes from 350 to 430 H/s ...

**Comment by diamondeye966** [comment]
at 890 intensity

**Comment by jch9678** [comment]
Regarding your environment variables, 

setx does not use = signs
setx sets the environment variables permanently
set (with = signs) sets it for the current program, not permanently
if you don't want to set them permanently use set, if you want to do it once for all mining software use setx 

e.g. 

setx GPU_MAX_HEAP_SIZE 100
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_FORCE_64BIT_PTR 1
setx GPU_SINGLE_ALLOC_PERCENT 100

**Comment by basselkhaddour** [comment]
backend AMD (OpenCL) disabled. plz help

**Comment by def670** [comment]
hey guys - I am running xmr-stak 2.7.1 on ubuntu 18.04.  I started getting the error that AMD device was not found.   I had changed the index to 1 at some point last night and this is when the error started....just realized it now and have put the index back to 0 and card working again!
