### ISSUE TITLE
build fails on solaris

### ISSUE THREAD

**Issue by baldpope** [fireice-uk/xmr-stak#800]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
Intel Xeon E5-2690 v2 

# Compile issues
  - Which OS do you use?
Solaris on x86_x64
  add **all** commands you used and the **full** compile output here

/opt/csw/bin/cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF -DOpenSSL_ENABLE=OFF -DHWLOC_ENABLE=OFF

make install 

The following command caused the error:
/opt/csw/bin/c++   -DBACKEND_TYPE=cpu -DCONF_NO_CUDA -DCONF_NO_HTTPD -DCONF_NO_HWLOC -DCONF_NO_OPENCL -DCONF_NO_TLS -I/home/jofficer/xmr/xmr-stak-master/. -march=native -mtune=native  -msse2 -maes -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o -c /home/jofficer/xmr/xmr-stak-master/xmrstak/backend/cpu/minethd.cpp

  run `cmake -LA .` in the build folder and add the output here
 $ cmake -LA
CMake Error: The source directory "/home/jofficer/xmr/xmr-stak-master/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/opt/csw/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/opt/csw/bin/gcc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/home/jofficer/xmr/xmr-stak-master/build
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/gmake
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND
CMAKE_OBJDUMP:FILEPATH=CMAKE_OBJDUMP-NOTFOUND
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC_ENABLE:BOOL=OFF
MICROHTTPD_ENABLE:BOOL=OFF
OpenCL_ENABLE:BOOL=OFF
OpenSSL_ENABLE:BOOL=OFF
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

# Issue with the execution
  - Do you compiled the miner by our own?
trying to

  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by mirix** [comment]
> CMake Error: The source directory "/home/jofficer/xmr/xmr-stak-master/build" does not appear to contain CMakeLists.txt.

Are you calling cmake from the right directory. It would seem to me that you are one level too deep...

**Comment by psychocrypt** [comment]
If I not miss something I would say you did not provide the error message.

**Comment by baldpope** [comment]
@mirix Per the build instructions:

`mkdir xmr-stak/build
    cd xmr-stak/build
    cmake ..
    make install`

@psychocrypt attached is the full output from the build
[putty.log](https://github.com/fireice-uk/xmr-stak/files/1607559/putty.log)

**Comment by psychocrypt** [comment]
Is it a 32bit solaris? The error is that you try to build a 32bit binary
what is not supported.
If you have a 64bit solaris please add -m64 to the c and cpp flags.

**Comment by baldpope** [comment]
@psychocrypt regarding the 64bit, yes - not 32bit host.

would I make the changes in the CMakeCache.txt file, this line

//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-m64

**Comment by psychocrypt** [comment]
please set also the c flags.

Am 05.01.2018 20:33 schrieb "baldpope" <notifications@github.com>:

**Comment by baldpope** [comment]
I don't see another file/location to update, where would I add the -m64 option?

**Comment by fireice-uk** [comment]
I will close this issue since we don't support non-x86 CPUs. It doesn't compile because the miner uses SSE4.1

**Comment by fireice-uk** [comment]
`#error You are trying to do a 32-bit build. This will all end in tears. I know it.` You are somehow doing a 32bit build

**Comment by baldpope** [comment]
Assuming this close was accidental, it is on x86-64bit cpu  The error appears specific to compile time options.  I'm simply asking for guidance on where to pass appropriate flags to ensure it's only building for 64bit arch.

I updated the CMAKE_CXX flags to pass through -m64, but presumably there is another location I should add a similar setting.

**Comment by fireice-uk** [comment]
https://stackoverflow.com/questions/44284275/passing-compiler-options-cmake
