### ISSUE TITLE
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265

### ISSUE THREAD

**Issue by badestgod** [fireice-uk/xmr-stak#801]
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265

what is it meaning?

**Comment by badestgod** [comment]
[2018-01-05 16:10:08] : Start mining: MONERO
[2018-01-05 16:10:08] : Starting NVIDIA GPU thread 0, no affinity.
[2018-01-05 16:10:11] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-05 16:10:11] : WARNING: backend AMD disabled.
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 0.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 2.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 4.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 6.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 8.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 10.
[2018-01-05 16:10:11] : hwloc: memory pinned
[2018-01-05 16:10:11] : Starting 1x thread, affinity: 12.
[2018-01-05 16:10:12] : hwloc: memory pinned
[2018-01-05 16:10:12] : Starting 1x thread, affinity: 14.
[2018-01-05 16:10:12] : hwloc: memory pinned
[2018-01-05 16:10:12] : Fast-connecting to xmr.crypto-pool.fr:8080 pool ...
[2018-01-05 16:10:15] : Pool xmr.crypto-pool.fr:8080 connected. Logging in...
[2018-01-05 16:10:16] : Difficulty changed. Now: 18000.
[2018-01-05 16:10:16] : Pool logged in.
[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265

**Comment by badestgod** [comment]
cpu:amd 1700x
gpu:1080ti

who can help me? my mr-stak can not work…………

**Comment by borzaka** [comment]
Show us your nvidia.txt config. Did you made changes to the default config?

My tip: change `bfactor` from 6 to 8.
If that GPU is your primary graphics card, change `bsleep` to 100, and maybe change `bfactor` to 10 or 12 to make Windows less laggish.

**Comment by rmcc3** [comment]
Same issue.

**Comment by badestgod** [comment]
* A filled out configuration should look like this:
 * "gpu_threads_conf" :
 * [
 *     { "index" : 0, "threads" : 17, "blocks" : 60, "bfactor" : 0, "bsleep" :  0, 
 *       "affine_to_cpu" : false, "sync_mode" : 3,
 *     },
 * ],
 */

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9312/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by badestgod** [comment]
I did not made any changes to the default config

**Comment by jweathington** [comment]
same issue here as well, default config

**Comment by badestgod** [comment]
thank you @borzaka ，i changed the config as you tell me, and ,amazing……its  work!thank you very much!

**Comment by jweathington** [comment]
bsleep to 100 and bfactor to 10 and it started working for me as well, thank you @borzaka

**Comment by borzaka** [comment]
You're welcome guys :) I had the same issue: #805

**Comment by shahramd** [comment]
how can i access bfactor or bsleep?

**Comment by borzaka** [comment]
Edit the nvidia.txt

**Comment by shahramd** [comment]
is Nvidia.txt file in program files folder?

**Comment by borzaka** [comment]
It's in the same place, where the XMR-Stak exe is.

**Comment by Venedictos** [comment]
@borzaka please can you help with this error:
**[CUDA] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu>:322**
I have amended the bfactor and bsleep as advised, but no joy:
`"gpu_threads_conf" :
[
  // gpu: GeForce GT 710 architecture: 35
  //      memory: 1694/2048 MiB
  //      smx: 1
  { "index" : 0,
    "threads" : 258, "blocks" : 3,
    "bfactor" : 12, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],`
Thanks in advance :-)

**Comment by psychocrypt** [comment]
half the number of threads

**Comment by Venedictos** [comment]
@psychocrypt  I halved it to 129 and generated the same error code, screen shot below:
![image](https://user-images.githubusercontent.com/13404635/36628908-e74a2622-1946-11e8-9c23-d83cae2f05b0.png)
Your comments much appreciated!
Thanks

**Comment by psychocrypt** [comment]
Could you additionally set bfactor to 10

**Comment by Venedictos** [comment]
@psychocrypt thanks for your prompt response, same error as before:
"gpu_threads_conf" :
[
  // gpu: GeForce GT 710 architecture: 35
  //      memory: 1694/2048 MiB
  //      smx: 1
  { "index" : 0,
    "threads" : 129, "blocks" : 3,
    "bfactor" : 10, "bsleep" :  100,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by psychocrypt** [comment]
try to half the threads again. I think your gpu is to slow.

**Comment by Venedictos** [comment]
@psychocrypt you are genius, it worked. Thanks. Using an old CPU to understand things before getting something current. Please any link on where i can get information to increase current GPU, clocking etc would be greatly appreciated.
Much love and respect 👍

**Comment by PascalParvex** [comment]
Thank you, the values ten and one hundred solved the issue.

**Comment by phlibby** [comment]
Thanks to Borzaka - 'change bfactor from 6 to 8." did the job for me.
