### ISSUE TITLE
Is it possible to dump GPU memory after shutdown?

### ISSUE THREAD

**Issue by davidpesce** [fireice-uk/xmr-stak#804]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Celeron 9440
  - Vega56 (XFX) x4

# Stability issue
  - Is the CPU or GPU overclocked? Yes
  - Is the Main memory of the CPU or GPU undervolted? Yes

Is it possible to dump the GPU memory after closing xmr-stak? Similar to this: https://github.com/tensorflow/tensorflow/issues/1578

When tweaking settings, it requires quite a few reboots after getting a setting wrong. When you get the BSOD with the memory dump (Thread Stuck in Device Driver), everything works fine after that.

Also, can you add a command option to gracefully shut down xmr-stak? Maybe this will help?

**Comment by psychocrypt** [comment]
I am currently working on that. It will coming soon.
