### ISSUE TITLE
Wrong default config for the GeForce GTX 1080 Ti

### ISSUE THREAD

**Issue by borzaka** [fireice-uk/xmr-stak#805]
# Basic information
  - 3x GeForce GTX 1080 Ti (none of them are connected to a monitor)
  - xmr-stak version: `xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20`
  - Windows 10 Version 1703 (OS Build 15063.850) 64 bit
  - NVIDIA driver 388.71

# Issue with the execution
  - launch options: `--noUAC --noAMD --noCPU`
```
[CUDA] Error gpu 1: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265
[CUDA] Error gpu 2: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265
```
Sometimes there is only one line of error.

# Overclocks
  - +120 Power Limit, +100 Core, +500 Memory
  - no issues

# Config
Default nvidia.txt:
```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9312/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9312/11264 MiB
  //      smx: 28
  { "index" : 1,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9313/11264 MiB
  //      smx: 28
  { "index" : 2,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
],
```

Changing `bfactor` to 8 solves the problem.
(I have three 1070 Ti, and they are working with 6 `bfactor` by default.)

**Comment by psychocrypt** [comment]
The reason is that the gpu can not calculate the hashes fast enough and get
killed by windows for blocking the gpu to long. You can also decrease the
thteafs a little bit. Try 48 tjis can sometimea increase the hash rate.

**Comment by borzaka** [comment]
Yeah, a little bit more hash, but still need the bfactor set to 8, otherwise at 6 crashes with the same error.
Thx.

**Comment by mattiasN78** [comment]
Hi i have a EVGA 1080ti and i get best hash/sec with
"threads" : 128, "blocks" : 28, "bfactor" : 8, "bsleep" :  25

if i know that 1080ti has 28 Streaming Multiprocessors and 3584 cuda cores
then i 3584/28=128 threads

and i use P0 state and i get 860h/s and if i OC Memmory +500 and Power State 65% i get 945h/s

to get P0 state you have to set this  OFF like in the picture and use the same version of Nvidia profile inspector 2.1.3.10

https://user-images.githubusercontent.com/984097/31249041-81436152-a9db-11e7-8ab1-46101b94d077.png

The GeForce GTX 1060 (GP104-400) has 10 x 128 shader processors makes a total of 1,280 shader processors.
The GeForce GTX 1070 (GP104-200) has 15 x 128 shader processors makes a total of 1,920 shader processors.
The GeForce GTX 1080 (GP104-400) has 20 x 128 shader processors makes a total of 2,560 shader processors.
The GeForce GTX 1080 Ti (GP102-350) has 28 x 128 shader processors makes a total of 3,584 shader processors.
The Nvidia Titan X (GP102-400) has 28 x 128 shader processors makes a total of 3,584 shader processors.

**Comment by JerichoJones** [comment]
@mattiasN78 Nice write-up!

**Comment by mattiasN78** [comment]
Thanks :)

i have a EVGA GTX 780ti it does have 2,880 cuda cores and 15 Streaming Multiprocessors

but i did try 2880/15 =192 so "threads" : 192, "blocks" : 15 but that did not work

then i did half cuda cores try 2880/2=1440cores
so 1440cores/15SM =96 so  "threads" : 96, "blocks" : 15 but that did not work

then i did try 2880/3=960 cores
so 960cores/15SM =64 so "threads" : 64, "blocks" : 15 and that did work :) i get 677h/s No overclocking
