### ISSUE TITLE
Excluding modules for performance?

### ISSUE THREAD

**Issue by Beedix** [fireice-uk/xmr-stak#807]
Is there any performance gain when excluding AMD, NVIDIA, or CPU to only what is needed?  The build documentation looks straight forward.

The 2% donation level is reasonable so I just wanted to see if there is it's worth excluding components or if I should just compile everything in.

**Comment by psychocrypt** [comment]
If you disable a backend you will not see any performace increase or
decrease.

**Comment by Beedix** [comment]
Excellent.  Thank you for the clarification.
