### ISSUE TITLE
Auto configuration first start- AMD GPU "intensity" : 0

### ISSUE THREAD

**Issue by deereslv** [fireice-uk/xmr-stak#81]
Running latest xmr-stak-dev, on linux with rx480( not OC), compile without problems, cpu backend i5  works flawlessly , but having problem with GPU.
After first start, and auto configuration, in amd.txt, suggested configuration is: 
"intensity" : 0, "worksize": 8
And if i increase intensity more than 32, get many "AMD invalid result" errors. 
Also tried playing with worksize , but no difference. 
Sometimes most errors are upon miner start, and sometimes start without errors, and after some time starts throwing errors

RESULT REPORT
Difficulty       : 100001
Good results     : 316 / 403 (73.8 %)
Avg result time  : 100.1 sec
Pool-side hashes : 2958631

Top 10 best results found:
|  0 |         17327791 |  1 |          6890190 |
|  2 |          5178865 |  3 |          4649874 |
|  4 |          4548370 |  5 |          3991239 |
|  6 |          3690780 |  7 |          3579746 |
|  8 |          3028025 |  9 |          2505256 |

Error details:
| Count | Error text                       | Last seen           |
|    87 | AMD Invalid Result               | 2017-10-30 07:49:40 |

Note, tried different GPU's, all rx480 and almost new, i took them from my eth rig (works without problems) to test aeon mining. Same configuration both my rig and testing computer,  ubuntu/drivers, so GPU should be fine

**Comment by deereslv** [comment]
CLINFO:

$ clinfo 

Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1800.11)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon (TM) RX 480 Graphics
  Device Topology:				 PCI[ B#2, D#0, F#0 ]
  Max compute units:				 36
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1342Mhz
  Address bits:					 64
  Max memory allocation:			 4248635626
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8451543040
  Constant buffer size:				 4244635648
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 0
  Max pipe active reservations:			 0
  Max pipe packet size:				 0
  Max global variable size:			 0
  Max global variable preferred total size:	 0
  Max read/write image args:			 0
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f918ad76430
  Name:						 Ellesmere
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1800.11
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event

  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 4
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 1600Mhz
  Address bits:					 64
  Max memory allocation:			 2147483648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 32768
  Global memory size:				 4108804096
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2147483648
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f918ad76430
  Name:						 Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz
  Vendor:					 GenuineIntel
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1800.11 (sse2,avx)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1800.11)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 



__________________________________________________________________________________________________

FIRST RUN:

$./xmr-stak
Please enter:
- currency: 'monero' or 'aeon'
aeon
- pool address: e.g. mine.aeon-pool.com:5555
aeon.sumominer.com:3334
- user name (wallet address or pool login):

- password (mostly empty or x):
x
Configuration stored in file 'config.txt'
-------------------------------------------------------------------
xmr-stak 2.0.0-predev mining software.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
AMD mining code was written by wolf9466.
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 2.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-30 11:09:17] : Start mining: AEON
[2017-10-30 11:09:17] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
[2017-10-30 11:09:17] : Found OpenCL GPU Ellesmere.
[2017-10-30 11:09:17] : AMD: GPU configuration stored in file 'amd.txt'
[2017-10-30 11:09:17] : Compiling code and initializing GPUs. This will take a while...
[2017-10-30 11:09:17] : Device 0 work size 8 / 256.
[2017-10-30 11:09:17] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2017-10-30 11:09:17] : WARNING: AMD device not found
[2017-10-30 11:09:17] : WARNING: backend AMD disabled.
[2017-10-30 11:09:17] : CPU configuration stored in file 'cpu.txt'
[2017-10-30 11:09:17] : Starting double thread, affinity: 0.
[2017-10-30 11:09:17] : hwloc: memory pinned
[2017-10-30 11:09:17] : Starting double thread, affinity: 1.
[2017-10-30 11:09:17] : hwloc: memory pinned
[2017-10-30 11:09:17] : Starting single thread, affinity: 2.
[2017-10-30 11:09:17] : hwloc: memory pinned
[2017-10-30 11:09:17] : Starting single thread, affinity: 3.
[2017-10-30 11:09:17] : hwloc: memory pinned
[2017-10-30 11:09:17] : Connecting to pool aeon.sumominer.com:3334 ...
[2017-10-30 11:09:17] : Connected. Logging in...
[2017-10-30 11:09:17] : Difficulty changed. Now: 20000.
[2017-10-30 11:09:17] : Pool switched.


______________________________________________


AMD.TXT


/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:0
  // compute units: 36
  { "index" : 0,
    "intensity" : 0, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,

**Comment by psychocrypt** [comment]
I don't know why but opencl says the miner that 0 MByte memory are
available.
I need to check where it comming from.

**Comment by deereslv** [comment]
Thanks!
Btw. CPU part works really well, my old 4 core i5-2300 2.8 gives me ~674 H/s

**Comment by psychocrypt** [comment]
Which OS do you use? is it an 64bit OS?

**Comment by deereslv** [comment]
Ubuntu 14.04-64bit

**Comment by sheepchen** [comment]
600 H/s with an i5? that cant be. An i5 4Gen give me 120 and an i7 (4790K) 4Gen ~200. 674 H/s is way off.. there must be an GPU inside this calculation..

**Comment by deereslv** [comment]
Tonight when i get home i'll post terminal output  running xmr-stak with --noGPU option.
As i said ~670 H/s .
 Note, that i'm talking about Aeon mining, not Monero which is much lower

**Comment by sheepchen** [comment]
oh, ok. my hault.. I mine Monero. Have no clue aboud Aeon. sorry ;)

**Comment by psychocrypt** [comment]
Which compiler do you used. I think I know the reason why there is zero
memory free but I am searching where it comes from. This is a 32bit
iverflow issue.

**Comment by sheepchen** [comment]
okay. my system is ubuntu linux 17.04 64 bit.

root@mpm01:~# cc --version
cc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
[..]
root@mpm01:~# type cc
cc gehasht ergibt (/usr/bin/cc)
root@mpm01:~# file /usr/bin/cc
/usr/bin/cc: symbolic link to /etc/alternatives/cc
root@mpm01:~# file /etc/alternatives/cc
/etc/alternatives/cc: symbolic link to /usr/bin/gcc
root@mpm01:~# file /usr/bin/gcc
/usr/bin/gcc: symbolic link to gcc-6
root@mpm01:~# file /usr/bin/gcc-6
/usr/bin/gcc-6: symbolic link to x86_64-linux-gnu-gcc-6

**Comment by deereslv** [comment]
I used gcc 6.3.0, installed from ubuntu toolchain ppa

**Comment by psychocrypt** [comment]
@deereslv Could you please download https://github.com/psychocrypt/xmr-stak/archive/topic-checkOpenCLZEroMem.zip copile and runt it.
I need the terminal output of the first start.

I added two debug messages which hopefully help me to detect the issue.

**Comment by deereslv** [comment]
I will do that soon as i come back home.

Just a note, last night i tried mining "Monero" (cryptonight), and despite 0 memory, i was able to make tweaking in amd.txt and there was no "AMD invalid result" errors. 
So it must be something wrong with "Aeon" (cryptonight-lite) part of the miner.

**Comment by deereslv** [comment]
Same problem, amd.txt shows 0 memory upon first start.


_____________________________________________________

FIRST START REPORT

./xmr-stak
-------------------------------------------------------------------
xmr-stak 2.0.0-predev mining software.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
AMD mining code was written by wolf9466.
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 2.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-31 08:20:04] : Start mining: AEON
[2017-10-31 08:20:05] : Found AMD platform index id = 0, name = Advanced Micro Devices, Inc.
CL_DEVICE_MAX_MEM_ALLOC_SIZE = 4248635626 size=8 CL_DEVICE_GLOBAL_MEM_SIZE = 8451543040
[2017-10-31 08:20:05] : Found OpenCL GPU Ellesmere.
[2017-10-31 08:20:05] : AMD: GPU configuration stored in file 'amd.txt'
[2017-10-31 08:20:05] : Compiling code and initializing GPUs. This will take a while...
[2017-10-31 08:20:05] : Device 0 work size 8 / 256.
[2017-10-31 08:20:05] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2017-10-31 08:20:05] : WARNING: AMD device not found
[2017-10-31 08:20:05] : WARNING: backend AMD disabled.
[2017-10-31 08:20:05] : CPU configuration stored in file 'cpu.txt'
[2017-10-31 08:20:05] : Starting double thread, affinity: 0.
[2017-10-31 08:20:05] : hwloc: memory pinned
[2017-10-31 08:20:05] : Starting double thread, affinity: 1.
[2017-10-31 08:20:05] : hwloc: memory pinned
[2017-10-31 08:20:05] : Starting single thread, affinity: 2.
[2017-10-31 08:20:05] : hwloc: memory pinned
[2017-10-31 08:20:05] : Starting single thread, affinity: 3.
[2017-10-31 08:20:05] : hwloc: memory pinned
[2017-10-31 08:20:05] : Connecting to pool aeoon.sumominer.com:3334 ...



_____________________________________________________


AMD.TXT



/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 * "gpu_threads_conf" :
 * [
 *	{ "index" : 0, "intensity" : 1000, "worksize" : 8, "affine_to_cpu" : false },
 * ],
 */

"gpu_threads_conf" : [
  // gpu: Ellesmere memory:0
  // compute units: 36
  { "index" : 0,
    "intensity" : 0, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 0,



____________________________________________________





I made start script, and run xmr-stak like this:

______________________________

#!/bin/bash

export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

./xmr-stak

______________________________


and i'm able to tweak amd.txt to increase "intensity" and "worksize".

But again, with this setup, mining "cryptonight" i can increase "intesity"  and everything  is working fine
, NO "AMD invalid result" errors, 

but mining "cryptonight-lite (Aeon), whatever "intensity" value i use, keeps throwing "AMD invalid result" errors.

**Comment by psychocrypt** [comment]
This run was only to give me some debug values.

**Comment by psychocrypt** [comment]
Could it be that you are using the wrong pool address?
Your pool is:
`Connecting to pool aeoon.sumominer.com:3334 ...` but there is an `o` tom much in the address.

**Comment by psychocrypt** [comment]
Could you please post the output of cmake of a clean build.
I still try to reproduce your error but can't see an error.
Is it possible to get ssh access (not root) to your system? This would give me the possibility to debug the error.

**Comment by deereslv** [comment]
Here is clean cmake:


$ cmake .. -DCUDA_ENABLE=OFF
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Set miner currency to 'monero' and 'aeon'
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "2.0")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f")
-- Configuring done
-- Build files have been written to: /home/ajax/xmr-stak-topic-checkOpenCLZEroMem/build


_____________________________________________________________

Don't know if it's relevant, but here is pthread lib location on my system:

$ find /lib -name "*pthread*"

/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libpthread-2.19.so


As for the pool address, you're right, mistype ....

**Comment by psychocrypt** [comment]
Could you please also run `ldd xmr-stak` and `ldd libxmrstak_opencl_backend.so`

**Comment by deereslv** [comment]
________________________________________

$ ldd xmr-stak
        linux-vdso.so.1 =>  (0x00007fff4d7fe000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8d55b7d000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f8d5591e000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f8d55541000)
        libmicrohttpd.so.10 => /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10 (0x00007f8d5532a000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f8d550ea000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8d54ee5000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8d54bd2000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8d549bb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8d545f1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8d55dc6000)
        libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f8d54332000)
        libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f8d540b2000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f8d53ea6000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f8d53c9c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8d53996000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8d5377c000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f8d53568000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f8d53326000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f8d53120000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f8d52f18000)


__________________________________________


ldd libxmrstak_opencl_backend.so
        linux-vdso.so.1 =>  (0x00007ffffa9fe000)
        libOpenCL.so.1 => /usr/lib/libOpenCL.so.1 (0x00007faa656ea000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faa653d7000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faa651bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faa64df6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faa65b6a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007faa64bee000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faa648e7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faa646e3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faa644c5000)

**Comment by psychocrypt** [comment]
ok last try: could you please remove amd.txt and run `valgrind ./xmr-stak`
After the miner started to mine you can kill the miner with `Ctrl+C`

If I can't see something from valgrind than I need definitively access because I can't reproduce whats happen. All my tests runinng withou issues.

**Comment by psychocrypt** [comment]
I can't see anything in the log but the miner was not at the point where the file `amd.txt` is written. 
Maybe it is an issue with the opencl driver but my debug output say that everything provided from OpenCL looks good.

If you can provide me a few hours access to your system please PM me on reddit (user: psychocrypt).

**Comment by deereslv** [comment]
Don't know if you have read one of my previous posts, but running xmr-stak like this: 

export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
./xmr-stak

fixes 0 memory problem. Memory is detected and writen in amd.txt.


Only remains, "AMD invalid result" errors when mining Aeon no mater what value "intensity" is ,
 while mining Monero has no errors, and i can push GPU increasing intensity. 
 Hope this helps

Have to put my gpu back into my rig, so i'll leave it here.

Thanks for the effort !

**Comment by hishikishi** [comment]
how to Disable CPU mining ? & my PC is Running slow hang after i start the mining ? what to do ?
& how to reduce speed of GPU
