### ISSUE TITLE
Hi, I cannot run latest xmr-stak.exe - many errors

### ISSUE THREAD

**Issue by DaveBG0** [fireice-uk/xmr-stak#810]
Hi, I cannot run latest xmr-stak.exe - many errors

First I tried mining with nicehash and it works.
Then I downloaded latest release  v2.2.0 from here:
https://github.com/fireice-uk/xmr-stak/releases
xmr-stak-win64.zip
and copied standard config.txt file.

[config.txt](https://github.com/fireice-uk/xmr-stak/files/1608511/config.txt)

First when I run the exe i got that it is missing "pool_list" from config even though the nice hash version runs with no such thing in parametters and works fine.
I added it empty:
"pool_list" :
[
],
but when I run again now say is missing "currency" so I put that also as:
"currency" : "monero",

Now it says it is missing "print_motd"
I put : 
"print_motd" : 
[
	{ hi },
],

But now another error appears:
JSON config parse error(offset 6811): Missing a name for object member.

[config2.txt](https://github.com/fireice-uk/xmr-stak/files/1608512/config2.txt)

Can someone say what is going on?

# Basic information
  - Ryzen 7 1700 CPU

# Compile issues
  - win 10
  
# Issue with the execution
  - Do you compiled the miner by our own?
  ``` 
  NO

# Stability issue - no


  - Is the CPU or GPU overclocked? - YES 3,9Ghz
  - Is the Main memory of the CPU or GPU undervolted? - NO

**Comment by JerichoJones** [comment]
Delete the config.txt.
Run the miner and follow the instructions.
