### ISSUE TITLE
Saving mining stats

### ISSUE THREAD

**Issue by CoinLogik** [fireice-uk/xmr-stak#813]
Is it possible to save stats from the miner? e.g. When exiting, it could save how long it mined for and what the avg hashrate was?

**Comment by JerichoJones** [comment]
No

**Comment by deshudiosh** [comment]
I started little utility software which read xmr-stak generated log files and gives some basic info about session start and its duration.

There it is:
https://github.com/deshudiosh/xmr-stak-log-reader
