### ISSUE TITLE
Segmentation fault (core dumped) on FreeBSD 11.1

### ISSUE THREAD

**Issue by klikfroggi** [fireice-uk/xmr-stak#817]
hw.model: Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
hw.machine: amd64
hw.ncpu: 4

I have compiled both branch 
first git clone https://github.com/fireice-uk/xmr-stak.git
second time git clone -b dev https://github.com/fireice-uk/xmr-stak.git

root@aphrodite:~/xmr-stak/bin # ./xmr-stak
[2018-01-07 12:14:26] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
[2018-01-07 12:14:26] : MEMORY ALLOC FAILED: mlock failed
[2018-01-07 12:14:26] : MEMORY ALLOC FAILED: mlock failed
[2018-01-07 12:14:26] : MEMORY ALLOC FAILED: mlock failed
[2018-01-07 12:14:26] : MEMORY ALLOC FAILED: mlock failed
[2018-01-07 12:14:26] : MEMORY ALLOC FAILED: mlock failed
-------------------------------------------------------------------
xmr-stak 2.2.0 4fc621c

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-01-07 12:14:28] : Start mining: MONERO
Segmentation fault (core dumped)

Any hints?

**Comment by chichicuervo** [comment]
I'm getting the same issue on a CPU-only build.  this is what gdb tells me:

Program received signal SIGSEGV, Segmentation fault.
0x000000080148d075 in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5

**Comment by chichicuervo** [comment]
as per your identical question from two weeks ago... adding HWLOC_ENABLE=OFF to cmake fixes it

**Comment by rhavenn** [comment]
At least for me I don't think this is a problem with your code. hwloc-ls segfaults and dumps on me as well. So, I think the problem is whatever call you're making to hwloc, so when that's disabled it works and once you have a cpu.txt it doesn't try to make the hwloc calls anymore.

There is a new hwloc build in ports. I'll update if it works better.

**Comment by bgoglin** [comment]
For the record, clang 4.0 on FreeBSD11.1 generates buggy hwloc code, causing a divide by zero. There will be a workaround in the upcoming 1.11.9 (released in a couple days) but we can't do much about buggy compilers.
