### ISSUE TITLE
Problem with miner-gate

### ISSUE THREAD

**Issue by szogun1987** [fireice-uk/xmr-stak#818]
I have joined to minergate to make mine incomes more repeatable. It worker fine for a couple of days but suddenly 8 hours ago it stopped to respond me.
``SOCKET ERROR - [xmr.pool.minergate.com:45560] CALL error: Timeout while waiting for a reply``

I have tried on 3 machines: 2 in one network (first 1,6KH/s second second 160H/s) and second in other network placed in other district, using other ISP. 
Machines are able to connect to other pools. I wonder if problem is related to mine account or all users of xmr-stak? Pool claims that there are still lot of active miners connected to this pool.

**Comment by JerichoJones** [comment]
Can you connect to minergate from those other machines?

**Comment by szogun1987** [comment]
No, I can't. I have setup all mine machines to use 2 pools (minergate and one other), none of them was able to mine anything on minergate for whole dat. Other pool is OK. I think I will choose other pool.

**Comment by szogun1987** [comment]
I have found old issue from xmr-stak-cpu https://github.com/fireice-uk/xmr-stak-cpu/issues/413
@psychocrypt proposed reporter to use xdn-xmr.pool.minergate.com:45790 I tried and it looks to work. but xmr.pool.minergate.com:45560 worked for a couple of days also.
