### ISSUE TITLE
Cannot mine with more than 4 GTX1070ti

### ISSUE THREAD

**Issue by krampuskats** [fireice-uk/xmr-stak#819]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU Intel G3900
  - Type of the GPU (if you try to miner with the GPU). Palit GTX 1070ti

# Issue with the execution
  - Do you compiled the miner by our own?
no, i used the complied miner from github and I get this error if I try to mine with more than 4 GPU
[CUDA] Error gpu 5: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:232
**suggestion: Try to reduce the value of the attribute 'threads' in the NVIDIA config file.**

**Comment by jonhassall** [comment]
Did you try to reduce the attribute 'threads' in the NVIDIA config file?

**Comment by krampuskats** [comment]
I tried reducing them but to no avail

**Comment by kth5** [comment]
Make sure your virtual memory settings are set high enough if this is on windows. Should be at least combined BE AN + some.

**Comment by psychocrypt** [comment]
Please post the file `nvidia.txt`

**Comment by krampuskats** [comment]
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1628191/nvidia.txt)
Here it is, sorry for taking so long

**Comment by JerichoJones** [comment]
Try bfactor 8 or 10

**Comment by krampuskats** [comment]
no change, still having the same issue

**Comment by JerichoJones** [comment]
Try [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/)
