### ISSUE TITLE
how to download from GIT

### ISSUE THREAD

**Issue by sheepchen** [fireice-uk/xmr-stak#82]
Hey people,

I see that fireice merged a new dev-version (#77). but I do not unterstand GIT. how can I download this new src-bundle?

Sorry, I am new at GIT.

**Comment by psychocrypt** [comment]
If you cloned the reposetory than run

```
git fetch origin
git pull
```
or on the main github page right top green button `clone or download` and
downlod the zip.

**Comment by fireice-uk** [comment]
Hi. Unified xmr-stak is currently in pre-release. As you can see, the source code changes almost daily. Version control tools (git) allow us to keep track of everything. I can give you a link to the current snapshot ( https://github.com/fireice-uk/xmr-stak/archive/dev.zip )  but keep in mind that the code is unlikely to be up to date after a couple days.

We are planning to have a stable release in the second week of November.

**Comment by sheepchen** [comment]
Hey fireice,
i know that this is beta-code (or sometimes alpha). For this reason i have small server (i5+4xGTX1060) for testing this versions.

thanks for the commands. I set up a nightly build for this.
(And read a little bit about GIT)
