### ISSUE TITLE
GPU Slows down when using CPU+GPU

### ISSUE THREAD

**Issue by Chicoree1986** [fireice-uk/xmr-stak#820]
Hi,
i have just bought a used gtx 750ti (cuz of its high H/W ratio). mining with this gpu with xmr stak nvidia release (1.4.0) works just fine (~240 h/s at ~40W consumption). But as soon as i use xmr stak with both cpu and gpu (xmr stak 2.2), the gpu starts with only 140 H/s and even slots down to 80 H/s during usage, even though i use exact same settings (same threads/blocks ratio etc) - but still with ~40W consumption.
my system:
FX-8320E, 8-core 3,2Ghz
16 GB Ram
GTX 750Ti Evga
OS: Windows 10
everything on stock settings, no OC

any suggestions how to use both cpu and gpu without any performance drops? am i missing something?

regards

**Comment by mvpel** [comment]
Try commenting out core 0 in the cpu.txt file (double slash - // - at the beginning of the line), and setting the affinity of the GPU in nvidia.txt to core 0 instead of false.

**Comment by Chicoree1986** [comment]
that solved the problem, thanks mate!
