### ISSUE TITLE
Is it possible to compile for Android?

### ISSUE THREAD

**Issue by SleepingAran** [fireice-uk/xmr-stak#822]
Particularly I wish to compile it for ZenFone 2. 

It has an Intel Atom Z3580 processor, which is a quad-core x86 processor that supports SSE2 instruction set.

**Comment by fireice-uk** [comment]
SSE2 should work, go ahead and try it =).

**Comment by BaconBAWS** [comment]
SleepingAran, did you succeeded? I tried to compile with Termux on my Zenfone 2 but no luck. 

Cmake succeed with the following command "cmake -DMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic . -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF -DOpenSSL_ENABLE=OFF". 

It fails on make install with the errors displayed here (https://drive.google.com/drive/folders/1zer8qK4a7TSK9ukTcGK5xpXH7DhaqcSl?usp=sharing).

If you make it work in any way let me know.
Thanks,
BaconBAWS

**Comment by SleepingAran** [comment]
@BaconBAWS  I've suceeded. I used Linux Deploy instead of Termux. I deploy a Ubuntu (x64) environment on Zenfone and cast it to my PC using VNC Viewer. Then I follow the instruction for building for Linux. Everything need to be run in sudo, otherwise it will have the permission error.

Hash rate is between 15 H/s to 16 H/s when running 3 cores at 2333 Mhz. It's better than my old PC that runs on Pentium Dual-Core (LOL). Temperature is around 60-65. 

Hash rate is not bad for a mobile processor IMO, but the temperature and the battery drain is crazy.

**Comment by BaconBAWS** [comment]
@SleepingAran Thank you for you feedback. I rooted my Zenfone and used Linux Deploy as well and it works fine. My hash rate is between 12H/s and 14H/s though.

As for the temperature and battery, I don't use this phone anymore so why not making useful at something like mining ETN. If he dies, he dies.
![image](https://user-images.githubusercontent.com/14330999/34803899-cb27513e-f643-11e7-8b3a-51b50efe2390.png)
