### ISSUE TITLE
NVIDIA Quadro FX 1800M not detected

### ISSUE THREAD

**Issue by oviwankenobi** [fireice-uk/xmr-stak#823]
hi all
I have windows 7 x64
NVIDIA Quadro FX 1800M latest driver installed
cuda_9.1.85_windows
VS 2017 redistributable package installed (link taken from github readme/doc)
and I get the "WARNING: NVIDIA Insufficient driver!"  error
is there anything I can do to make it work?
how can I troubleshoot farther?
thank you

**Comment by JerichoJones** [comment]
Is the NVIDIA Quadro FX 1800M supported by CUDA 9?

**Comment by mvpel** [comment]
http://www.nvidia.com/object/IO_32667.html
> Legacy GPUs are older-generation NVIDIA GPUs which are no longer supported in the regular NVIDIA Unified UNIX Graphics Driver. Instead, these GPUs will continue to be supported through special "Legacy GPU" drivers that will be updated periodically to add support for new versions of Linux system components (e.g., new Linux kernels, new versions of the X server, etc).

> ...
> GeForce GTS 360M | 0x0CB1
> **Quadro FX 1800M | 0x0CBC**
> GeForce 9300 GS | 0x10C0
> ...

**Comment by oviwankenobi** [comment]
thank you, clear.

**Comment by bizlevel** [comment]
Hm, How about Quadro FX 1800, (Quadro FX 1800 | 0x0638) not Mobile version, support or not?
And which one verion of CUDA ? http://developer.download.nvidia.com/compute/cuda/opensource/
