### ISSUE TITLE
Default configuration not working for NVIDIA

### ISSUE THREAD

**Issue by markwalet** [fireice-uk/xmr-stak#827]
Please provide as much as possible information to reproduce the issue.

I'm running the latest xmr-stak release on a Windows 10 Laptop with the following GPU:

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:08:12_Central_Daylight_Time_2017
Cuda compilation tools, release 9.1, V9.1.85
```

I left everything at the default settings and started for the first time.

My generated gpu configuration looks the following:

```
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 950M architecture: 50
  //      memory: 3427/4096 MiB
  //      smx: 5
  { 
	"index" : 0,
    "threads" : 44, 
	"blocks" : 15,
    "bfactor" : 8, 
	"bsleep" :  25,
    "affine_to_cpu" : false, 
	"sync_mode" : 3,
  },

],
```

Even when I downgrade `threads` to `16` and `bsleep` to `100`, the GPU fails to start up.

```
xmr-stak 2.2.0 c4400d19
-------------------------------------------------------------------
[2018-01-07 19:26:55] : Start mining: MONERO
[2018-01-07 19:26:56] : Starting NVIDIA GPU thread 0, no affinity.
[2018-01-07 19:26:56] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-07 19:26:56] : WARNING: backend AMD disabled.
...
Normal mining stuff.
```

How do I determine which configuration does work for me? Or is something else wrong here?

**Comment by psychocrypt** [comment]
Why do you think that the gpu is not working. The log show no error for
nvidia gpus. Press the key h to get the hash report. The should be an entry
for the nvidia cpu.

**Comment by markwalet** [comment]
I really have no idea.
```
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |   (na) |   (na) |   (na) |
```

**Comment by psychocrypt** [comment]
how long do you wait before you pressed h. please report the hash rate
after 2min waiting. you can press h more often but after 2 min the value
are what we need.

**Comment by markwalet** [comment]
```
[2018-01-07 19:50:48] : Difficulty changed. Now: 9804.
[2018-01-07 19:50:48] : New block detected.
[2018-01-07 19:50:53] : Result accepted by the pool.
[2018-01-07 19:51:05] : Result accepted by the pool.
[2018-01-07 19:51:16] : Difficulty changed. Now: 19608.
[2018-01-07 19:51:16] : New block detected.
[2018-01-07 19:51:58] : New block detected.
[2018-01-07 19:52:37] : New block detected.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   47.4 |   45.9 |   (na) |  1 |   48.7 |   47.2 |   (na) |
|  2 |   49.3 |   47.8 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |   (na) |   39.5 |   (na) |
---------------------------
Totals:     (na)  180.3   (na) H/s
Highest:     0.0 H/s
```

**Comment by psychocrypt** [comment]
please half the number of threads. the gpu is to slow to compute a bunch of
hashes within 10 sec.

**Comment by markwalet** [comment]
Ah, this looks better. Is there any way how I can increase my hashing rate more?
```
[2018-01-07 19:56:05] : Difficulty changed. Now: 20000.
[2018-01-07 19:56:05] : New block detected.
[2018-01-07 19:56:16] : Result accepted by the pool.
[2018-01-07 19:56:34] : New block detected.
[2018-01-07 19:56:35] : Difficulty changed. Now: 40000.
[2018-01-07 19:56:35] : New block detected.
[2018-01-07 19:57:16] : Result accepted by the pool.
[2018-01-07 19:57:35] : Difficulty changed. Now: 66667.
[2018-01-07 19:57:35] : New block detected.
[2018-01-07 19:58:32] : New block detected.
[2018-01-07 19:58:52] : New block detected.
[2018-01-07 19:59:10] : Result accepted by the pool.
[2018-01-07 19:59:17] : New block detected.
[2018-01-07 19:59:23] : Result accepted by the pool.
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   45.8 |   47.3 |   (na) |  1 |   47.4 |   48.8 |   (na) |
|  2 |   47.0 |   48.5 |   (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID |    10s |    60s |    15m |
|  0 |  128.7 |  129.2 |   (na) |
---------------------------
Totals:    268.9  273.9   (na) H/s
Highest:   275.8 H/s
```

**Comment by markwalet** [comment]
<img width="351" alt="screen shot 2018-01-07 at 20 01 04" src="https://user-images.githubusercontent.com/11446771/34652964-8fb364ae-f3e5-11e7-8414-83ebe563bbd5.png">
This looks like I'm not getting everything out of my GPU

**Comment by psychocrypt** [comment]
Not sure if it is possible because nvidia gpus are slowet than amd and this
value lucks good. Maybe try to swt bfactor back to 6 and bsleep ro 25

**Comment by mvpel** [comment]
The Windows Task Manager GPU status is focused on graphics, not compute, operations, so it doesn't show an accurate picture of how it's being used to solve hashes. If you run "nvidia-smi" at a CMD prompt, after going to the C:\"Program Files\NVIDIA Corporation"\NVSMI directory, you'll see the GPU-Util at 100%.

**Comment by markwalet** [comment]
Thanks for the help guys. I'm now around 310 H/s on a Windows laptop. If you have any idea on improving it more just say it. Maybe I can do something special with the CPU

**Comment by JerichoJones** [comment]
Try [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/)

**Comment by zherokhudo** [comment]
what is ur current nvidia configuration now
