### ISSUE TITLE
Command Line options for Rel 2.2

### ISSUE THREAD

**Issue by MohitYadavGitHub** [fireice-uk/xmr-stak#828]
In the xmr-stak-amd.exe miner, i am able to create a batch file to start the miner in the following format.

_timeout /t 10
cd "C:\d_Drive\gcard\Miner\xmr-stak-amd"
"C:\d_Drive\gcard\Miner\xmr-stak-amd\xmr-stak-amd.exe" "C:\d_Drive\gcard\\Miner\xmr-stak-amd\config.txt"_ 

Is there a way to do this with rel 2.2 ? 
What options need to be passed to the exe file?

**Comment by szogun1987** [comment]
Please check `xmr-stak.exe --help`
There are options: --cpu FILE, --amd FILE, --nvidia FILE  you can pass path to config files via those parameters.

**Comment by MohitYadavGitHub** [comment]
thanks
