### ISSUE TITLE
Quadro FX 5600 compatibility

### ISSUE THREAD

**Issue by AmigoPerson** [fireice-uk/xmr-stak#829]
Hi!
Is it possible to use old card Quadro FX 5600 ( http://www.nvidia.com/object/quadro_fx_5600_4600.html ) to mine Monero using XMR-Stak software? I can buy 2 cards in good price and use it in my old computer, but I have no possibility to check if XMR-Stak will work with it.

Thank you.

Best regards
Amigo

**Comment by JerichoJones** [comment]
[NVIDIA LEGACY (TOO OLD)](http://www.nvidia.com/object/IO_32667.html)

**Comment by hilga007** [comment]
Just commenting here - if you install the legacy CUDA 6.5 version and nVidia OpenCL headers and so forth on Ubuntu 16.04, install AMDAPPSDK, and link the libOpenCL.so.1 and the nVidia libOpenCL you can get XMR Stak to compile and use the legacy device as an OpenCL device. 

I magically got a GT 9600M to work... with like 25H/S. I don’t even know how it happened. Was just messing around. However... it does! 

Combined with an older Core 2 Duo I get a whopping 62H/S in this setup. 

It’s not supported by the devs... but if you tinker enough with it you can make it work.
