### ISSUE TITLE
OpenCL not found when compiling on Win10 64bit.

### ISSUE THREAD

**Issue by snapek** [fireice-uk/xmr-stak#83]
I've been trying to get this to compile on Win10 64bit today, and keep running into errors stating the following;

C:\xmr-stak\xmr-stak\build>cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DOpenCL_ENABLE=ON ..
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.16278.
CMake Error at CMakeLists.txt:173 (message):
  OpenCL NOT found: use `-DOpenCL_ENABLE=OFF` to build without OpenCL support
  for AMD gpu's

I'm running the AMD 17.x ReLive series drivers, hoping that's not the issue.  I've also installed the 3.x AMD APP SDK thinking I might be missing OpenCL libraries.

I had the same issue running the prebuilt xmr-stak-amd binary on this machine.  That said, it's got an HD 7950 that runs the Claymore AMD GPU Monero miner just fine... so I'm at a bit of a loss as to what I'm overlooking or missing for the build process.

**Comment by psychocrypt** [comment]
please set the environment variable `OpenCL_ROOT` to the place where OpenCL is installed.

**Comment by MTrab** [comment]
I have tried this:

set OpenCL_ROOT="C:\Users\morte\AMD APP SDK\2.9"

same error as original post.
Have tried the same with 2.9-1 and 3.0 and same results.

-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:259 (message):
  OpenCL NOT found: use `-DOpenCL_ENABLE=OFF` to build without OpenCL support
  for AMD gpu's

**Comment by psychocrypt** [comment]
try to set `AMDAPPSDKROOT="C:\Users\morte\AMD APP SDK\2.9"`

**Comment by MTrab** [comment]
Same result.

**Comment by psychocrypt** [comment]
please check if the path is correct and contains a include and lib
directory somewhere

**Comment by MTrab** [comment]
It does.

https://imgur.com/a/j1bT0

**Comment by psychocrypt** [comment]
please post the folders within lib

**Comment by MTrab** [comment]
Lib: https://imgur.com/a/k358s

**Comment by psychocrypt** [comment]
Ahh sry the last command I send must be added to the cmake line. with
`-DOPTIONNAME=PATH`

**Comment by MTrab** [comment]
Added -DAMDAPPSDKROOT="C:/Users/morte/AMD APP SDK/2.9" to the CMake line - still no effect :(

**Comment by psychocrypt** [comment]
please show you full cmake line. Please provide always the full information.

**Comment by MTrab** [comment]
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DOpenCL_ENABLE=1 -DCUDA_ENABLE=1 -DCPU_ENABLE=1 -DHWLOC_ENABLE=1 -DXMR-STAK_CURRENCY=monero -DOpenSSL_ENABLE=1 -DMICROHTTPD_ENABLE=1 -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR="D:/Programmer/NVIDIA GPU Computing Toolkit/CUDA/v9.0" -DAMDAPPSDKROOT="C:/Users/morte/AMD APP SDK/2.9" ..

**Comment by psychocrypt** [comment]
You can also try to remove the spaces in the folder name and in the option
given to cmake.

**Comment by MTrab** [comment]
Sorry, but that didn't change anything either.

Copied the 2.9 folder to D:\Temp and ran the following command:

cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DOpenCL_ENABLE=1 -DCUDA_ENABLE=1 -DCPU_ENABLE=1 -DHWLOC_ENABLE=1 -DXMR-STAK_CURRENCY=monero -DOpenSSL_ENABLE=1 -DMICROHTTPD_ENABLE=1 -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR="D:/Programmer/NVIDIA GPU Computing Toolkit/CUDA/v9.0" -DAMDAPPSDKROOT="D:/Temp/2.9" ..

**Comment by psychocrypt** [comment]
could you please try a nother version of the app sdk.

**Comment by MTrab** [comment]
I have tried the 3 Windows versions available: 2.9, 2.9-1 and 3.0
All with same result.

**Comment by psychocrypt** [comment]
I need to test it tomorrow on my system.

**Comment by Cr0iX** [comment]
I have the exact same problem. Just with this line:
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DOpenCL_ENABLE=1 -DCPU_ENABLE=1 -DHWLOC_ENABLE=1 -DXMR-STAK_CURRENCY=monero -DOpenSSL_ENABLE=1 -DMICROHTTPD_ENABLE=1 -DCMAKE_BUILD_TYPE=Release -DAMDAPPSDKROOT="C:\Users\USER\AMD APP SDK\3.0" -DCUDA_ENABLE=OFF ..

**Comment by Cr0iX** [comment]
Got it to work by adding:
-DOpenCL_INCLUDE_DIR="C:\Users\USER\AMD APP SDK\3.0\include"
-DOpenCL_LIBRARY="C:\Users\USER\AMD APP SDK\3.0\lib\x86_64"

Total line:
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DOpenCL_ENABLE=1 -DCPU_ENABLE=1 -DHWLOC_ENABLE=1 -DXMR-STAK_CURRENCY=monero -DOpenSSL_ENABLE=1 -DMICROHTTPD_ENABLE=1 -DCMAKE_BUILD_TYPE=Release -DAMDAPPSDKROOT="C:\Users\USER\AMD APP SDK\3.0" -DCUDA_ENABLE=OFF -DOpenCL_INCLUDE_DIR="C:\Users\USER\AMD APP SDK\3.0\include" -DOpenCL_LIBRARY="C:\Users\USER\AMD APP SDK\3.0\lib\x86_64" ..

**Comment by MTrab** [comment]
Me to - but then other errors.

This in the beginning:
-- Found OpenCL: C:/Users/morte/AMD APP SDK/3.0/lib/x86_64
-- Configuring done
WARNING: Target "xmrstak_opencl_backend" requests linking to directory "C:/Users/morte/AMD APP SDK/3.0/lib/x86_64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "xmrstak_opencl_backend" requests linking to directory "C:/Users/morte/AMD APP SDK/3.0/lib/x86_64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "xmrstak_opencl_backend" requests linking to directory "C:/Users/morte/AMD APP SDK/3.0/lib/x86_64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "xmrstak_opencl_backend" requests linking to directory "C:/Users/morte/AMD APP SDK/3.0/lib/x86_64".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done

This when running "cmake --build . --config Release --target install":
"D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\install.vcxproj" (default target) (1) ->
"D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\ALL_BUILD.vcxproj" (default target) (3) ->
"D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj" (default target) (8) ->
(Link target) ->
  gpu.obj : error LNK2001: unresolved external symbol clGetPlatformIDs [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clGetPlatformInfo [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clGetDeviceIDs [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clGetDeviceInfo [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clCreateContext [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clCreateCommandQueue [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clCreateBuffer [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clCreateProgramWithSource [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clBuildProgram [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clGetProgramBuildInfo [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clCreateKernel [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clSetKernelArg [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clFinish [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clEnqueueReadBuffer [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clEnqueueWriteBuffer [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  gpu.obj : error LNK2001: unresolved external symbol clEnqueueNDRangeKernel [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak_opencl_backend.vcxproj]
  D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\bin\Release\xmrstak_opencl_backend.dll : fatal error LNK1120: 16 unresolved externals [D:\CryptoMining\xmr-miner-custom\xmr-stak-master\build\xmrstak
_opencl_backend.vcxproj]

**Comment by Cr0iX** [comment]
My bad. 
It has to be these dirs:
-DOpenCL_INCLUDE_DIR="C:/Program Files (x86)/AMD APP SDK/3.0/include" 
-DOpenCL_LIBRARY="C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib

I compiled it with 38 warnings and 0 errors:
cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DOpenCL_ENABLE=1 -DCPU_ENABLE=1 -DHWLOC_ENABLE=1 -DXMR-STAK_CURRENCY=monero -DOpenSSL_ENABLE=1 -DMICROHTTPD_ENABLE=1 -DCMAKE_BUILD_TYPE=Release -DAMDAPPSDKROOT="C:\Users\USER\AMD APP SDK\3.0" -DCUDA_ENABLE=OFF -DOpenCL_INCLUDE_DIR="C:/Program Files (x86)/AMD APP SDK/3.0/include" -DOpenCL_LIBRARY="C:/Program Files (x86)/AMD APP SDK/3.0/lib/x86_64/OpenCL.lib" ..

**Comment by psychocrypt** [comment]
Thx I will check if I can add the solution somewhere to the documentation

**Comment by MTrab** [comment]
Thank you for the support - now it's working for me too.
Didn't notice the AMD SDK installed anything to Program Files (x86) - my bad :)

**Comment by NmxMilk** [comment]
I had the same problem (see #246).
The solution was to remove double quotes from the set command:
set AMDAPPSDKROOT=C:\Program Files (x86)\AMD APP SDK\3.0

Another workaround is to expilicitly use the defines with the cmake command:
-DOpenCL_INCLUDE_DIR="C:\Program Files (x86)\AMD APP SDK\3.0\include"
-DOpenCL_LIBRARY="C:\Program Files (x86)\AMD APP SDK\3.0\lib"
