### ISSUE TITLE
Only mine CPU mode?

### ISSUE THREAD

**Issue by CMUnreal** [fireice-uk/xmr-stak#833]
Please provide as much as possible information to reproduce the issue.

Could you extend your doc to explain if it is possible to only mine CPU?

How to disable GPU mining?
Alternatively, what settings are recommend to throttle GPU mining? I tried different aloc figures (60-90) with no noticeable performance gains.

Thanks!

**Comment by Shuttleu** [comment]
Delete the two xmrstak DLL's or comment out the GPU text files should disable them, or at least it does on mine

**Comment by borzaka** [comment]
Only CPU mining:
`xmr-stak.exe --noNVIDIA --noAMD`

**Comment by JerichoJones** [comment]
@Shuttleu Please do not tell people to do this.
@borzaka is correct.

**Comment by mvpel** [comment]
With @Shuttleu's approach, xmr-stak still probes the GPU cards, which may disrupt running mining operations being managed by another process on the system.
