### ISSUE TITLE
Slow performance on GTX 680

### ISSUE THREAD

**Issue by Shuttleu** [fireice-uk/xmr-stak#834]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. 
i7-3770k
  - Type of the GPU (if you try to miner with the GPU).
GTX 980
GTX 680

# Issue with the execution
  - Do you compiled the miner by our own?
No, using the version from the release page

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

# Problem
Running the default config I get 
CPU - 65-70 h/s each core, 272 h/s combined
GTX 980 - 515 h/s
GTX 680 - 125 h/s - about 100 h/s lower than average

If I set XMR-Stak to use the CPU and the GTX 980, but CCMiner to use the GTX 680, I get the same performance from the GTX 980 and CPU, but an extra 100 h/s from the GTX 680.

I have tried the suggestion in #820 by disabling cores 0 and 2 then assigning them to GPU 0 and 1. The CPU h/s goes up for the remaining 2 cores (85 h/s each core, 170 h/s combined), but the GTX 980 and GTX 680 remain at their previous h/s

The only of note that I can see is that CCMiner says it's using 512 threads on the GTX 680, but XMR-Stak I think is 256. If I try to increase XMR-Stak to 512 by the way of the threads or blocks, I get the following error

> [CUDA] Error gpu 1: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:232
> **suggestion: Try to reduce the value of the attribute 'threads' in the NVIDIA config file.**

**Comment by psychocrypt** [comment]
CCminer is not using multiple threads to work on one AES scratchpad. I will think about it if it is useful to add a option to allow this.
But currently  I have to many tasks to do this. From my tests it is always better to use the current compute mode from xmr-stak.
Could you please post your nvidia.txt.

IMO the best config for the GTX680 should be `threads=40, blocks=24` or `threads=62, blocks=16`

**Comment by Shuttleu** [comment]
So I had been playing around with the threads and blocks, but they didn't seem to do much last time I played with them.
Changing them as drastically as I have, I am now getting 330 h/s out of the GTX 680
`"gpu_threads_conf" :
[
  // gpu: GeForce GTX 980 architecture: 52
  //      memory: 3375/4096 MiB
  //      smx: 16
  { "index" : 0,
    "threads" : 12, "blocks" : 48,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 680 architecture: 30
  //      memory: 1677/2048 MiB
  //      smx: 8
  { "index" : 1,
    "threads" : 32, "blocks" : 14,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],`

**Comment by psychocrypt** [comment]
Does this mean that the issue is solved? If so could you pease close the
issue.
