### ISSUE TITLE
Connection keeps getting dropped

### ISSUE THREAD

**Issue by lthiery** [fireice-uk/xmr-stak#839]
Pretty much every 2 minutes, it looks like my connection to the pool is getting dropped.

I have one miner that has no issue but another that keeps doing this. From the http client:

Date | Error-- | --
2018-01-09 00:33:01 | [mine.sumo.fairpool.xyz:5555] CALL error: Timeout while waiting for a reply
2018-01-09 00:34:37 | [mine.sumo.fairpool.xyz:5555] CALL error: Timeout while waiting for a reply
2018-01-09 00:36:09 | [mine.sumo.fairpool.xyz:5555] CALL error: Timeout while waiting for a reply

I've tried switching pools but it's the same thing. Perhaps both pools I selected are saturated? How can I debug this?

**Comment by DavidBruchmann** [comment]
In config.txt you can increase timout.
Concerning debugging you just can debug the connection, as its not about xmr-stak itself.
With Wireshark for example.

**Comment by DavidBruchmann** [comment]
might be an issue withh a firewall, to other pools you connet by different ports perhaps.

**Comment by Sandown** [comment]
I also have this problem with hashvault. Fairpool fixed it the other day, something to do with XMR-STAK not responding to difficulty changes fast enough. It was a pool side change that resolved it on fairpool. Hashvault still gives me the error, on multiple coins.
