### ISSUE TITLE
NVIDIA insufficient driver

### ISSUE THREAD

**Issue by shaiinbal** [fireice-uk/xmr-stak#840]
Hi,
My GPU is Palit nVidia GeForce 9500GT 1GB.
I have been trying to use it with xmr-stak but I keep getting the error in the title.
I tried: 1. Updating the nvidia graphics driver to the newest version. 2. Installing the latest CUDA (9.1). 3. Installing CUDA without the display drivers (during the installation it says the current driver may be newer than the CUDA display driver). 3. Installing an Older CUDA (6.0) with and without the display drivers.

I have a Windows 7 64-Bit.
Thanks!

**Comment by JerichoJones** [comment]
[NVIDIA LEGACY (TOO OLD)](http://www.nvidia.com/object/IO_32667.html)
