### ISSUE TITLE
Could not find CUDA near last step of CMAKE build - ensured CUDA requirements installed

### ISSUE THREAD

**Issue by mrrogerswasawesome** [fireice-uk/xmr-stak#842]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.

**Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, 3504 Mhz, 4 Core(s), 4 Logical Processor(s)**

  - Type of the GPU (if you try to miner with the GPU).

**NVIDIA GeForce GTX 970**

# Compile issues
  - Which OS do you use?
**Windows 10 Pro 64bit**

**Commands run:**

C:\xmr-stak\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
-- Set miner currency to 'monero' and 'aeon'
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:209 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support

-- Configuring incomplete, errors occurred!
See also "C:/xmr-stak/build/CMakeFiles/CMakeOutput.log".

  run `cmake -LA .` in the build folder and add the output here
C:\xmr-stak\build>cmake -LA
CMake Error: The source directory "C:/xmr-stak/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_INSTALL_PREFIX:PATH=C:/xmr-stak/build
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/link.exe
CMAKE_LINK_STATIC:BOOL=OFF
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_RC_COMPILER:FILEPATH=rc
CMAKE_RC_FLAGS:STRING=/DWIN32
CMAKE_RC_FLAGS_DEBUG:STRING=/D_DEBUG
CMAKE_RC_FLAGS_MINSIZEREL:STRING=
CMAKE_RC_FLAGS_RELEASE:STRING=
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
CUDA_ENABLE:BOOL=ON
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=$(VCInstallDir)bin
CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

# Issue with the execution
  - Do you compiled the miner by our own?
Trying to compile it on my own, just hitting CUDA error on the final step. Exact errors when running CMAKE for CUDA 9.x: 

**CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
CMake Error at CMakeLists.txt:209 (message):
  CUDA NOT found: use `-DCUDA_ENABLE=OFF` to build without NVIDIA GPU support**

**Comment by psychocrypt** [comment]
Whwre do you installed CUDA?
Set the environment variable CUDA_ROOT or point CMAKE_PREFIX_PATH to the
cuda root folder

**Comment by mrrogerswasawesome** [comment]
It is installed at **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA** and CUDA_PATH was set to that path. I added a new PATH entry for CUDA_TOOLKIT_ROOT with the same directory C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1 and re-tried and that worked. The build finished and upon running the xmr-stak executable and editing the configuration file I'm getting the following error that NVIDIA CUDA GPU mining isn't even enabled...


**Errors:**

[2018-01-09 14:38:00] : MEMORY INIT ERROR: Obtaning SeLockMemoryPrivilege failed.
[2018-01-09 14:38:00] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-01-09 14:38:00] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-01-09 14:38:00] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-01-09 14:38:00] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-01-09 14:38:00] : MEMORY ALLOC FAILED: VirtualAlloc failed.
-------------------------------------------------------------------
xmr-stak 2.2.0 2ae7260b

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-01-09 14:38:01] : Start mining: MONERO
WARNING: NVIDIA cannot load backend library: xmrstak_cuda_backend.dll
WARNING: NVIDIA Backend disabled
[2018-01-09 14:38:01] : WARNING: backend NVIDIA disabled.
[2018-01-09 14:38:01] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-09 14:38:01] : WARNING: backend AMD disabled.
[2018-01-09 14:38:01] : Starting 1x thread, affinity: 0.
[2018-01-09 14:38:01] : hwloc: memory pinned
[2018-01-09 14:38:01] : Starting 1x thread, affinity: 1.
[2018-01-09 14:38:01] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2018-01-09 14:38:01] : hwloc: memory pinned

**Comment by JerichoJones** [comment]
You need admin privilege to enable Large Pages in Windows. This is not a fatal error.
