### ISSUE TITLE
GPU0 underperforming

### ISSUE THREAD

**Issue by Erniastukas** [fireice-uk/xmr-stak#847]
HI, I'm going nuts over this one, so I hope someone will be able to help me :]

I'm running v2.2.0 on Win10 with 5xRX580. They are identical with modified BIOSes. GPU0 is strangely underperfoming, all the other things being equal: config is the same for each card and all are using same PCI risers. If I change the cards - performance dip is still on gpu0, so it's not the card, but the slot/config.

BIOS has all slots set to gen1, 4G enabled. MB is Asus Strix h270f gaming. 

Last thing I suspect - it has two M2 slots with a M2 SSD with OS in one of them, maybe it's interfering with the card somehow. I tried moving it to another slot, same result. I'd like someone to shoot me some other ideas to try out before I have to reinstall the whole damn thing to sata drive.

![image](https://user-images.githubusercontent.com/35274268/34741261-b37aac66-f58a-11e7-8e13-c8192382a1a2.png)

![image](https://user-images.githubusercontent.com/35274268/34741323-e9281128-f58a-11e7-9e85-13be8427bf3b.png)

**Comment by psychocrypt** [comment]
I think this GPU is used from windows for visualization. If you have a IGPU than try to use this GPU for windows.

**Comment by Erniastukas** [comment]
Already tried that, no luck. Also if I disconnect monitor completely (Teamviewer connection for control) - same.

**Comment by JerichoJones** [comment]
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**
