### ISSUE TITLE
CUDA error after 24hr+ mining (causes "xmr-stak.exe" to crash)

### ISSUE THREAD

**Issue by axd1013** [fireice-uk/xmr-stak#855]
After about the 24 hour mark of leaving my rig on and mining it seem to crash giving me an error that you can see in the attached picture. Not sure what the issue is. Any ideas of what steps I should take to fix the problem?

-GPU's nor CPU is overclocked. Both are always running when xmr-stak.exe is running.

![img_5186](https://user-images.githubusercontent.com/34933543/34784461-5014434a-f5fc-11e7-9223-c04d3b422d5f.jpeg)

- Windows 7
- Intel Pentium G4600 Kaby Lake Dual-Core 3.6 GHz LGA
1151 51W BX80677G4600 Desktop Processor Intel HD
Graphics 630
- CORSAIR RMx Series RM850X 850W 80 PLUS GOLD
Haswell Ready Full Modular ATX12V & EPS12V SLI and
Crossfire Ready Power
- ASUS Z170 PRO GAMING LGA 1151 Intel Z170 HDMI SATA
6Gb/s USB 3.1 ATX Intel Motherboard
- G.SKILL Value 4GB 288-Pin DDR4 SDRAM DDR4 2400 (PC4
19200) Intel X299 / Z270 / Z170 / X99 Platform Desktop
Memory Model

- EVGA GeForce GTX 1080 Ti FTW3 GAMING, 11G-P4-6696-KR, 11GB GDDR5X, iCX Technology - 9 Thermal Sensors & RGB LED G/P/M 
 - EVGA GeForce GTX 1080 Ti SC Black Edition GAMING, 11G-P4-6393-KR, 11GB GDDR5X, iCX Cooler & LED 
- MSI GeForce GTX 1080 Ti DirectX 12 GeForce GTX 1080 Ti GAMING X 11G 11GB 352-Bit GDDR5X PCI Express 3.0 x16 HDCP Ready SLI Support Video Card

**Comment by derjohn** [comment]
I suspect _some_ hardware fault. That must not necessarily be the GPU itself, I oberserved similar errors (on linux) with overheating and with low-quality power supplies, cables etc or even RAM (did you already run memtest86 for 24h+ ?).
It's very unlikely that s software bug occurs after 24h doing exactly the same computation.

**Comment by hilga007** [comment]
What about your config files as well? 

Also: is the G.Skill Value RAM certified by your motherboard manufacturer?

**Comment by JerichoJones** [comment]
Hardware issues do not fall under the scope of GitHub support. You may find REDDIT helpful.
