### ISSUE TITLE
Unable to complete make install xmr-stak on ubuntu 17 - error: ‘to_string’ is not a member of ‘std

### ISSUE THREAD

**Issue by majorcarnegie** [fireice-uk/xmr-stak#856]
a similar issue. Ubuntu 17, G++ version appears to be correct. It does not like the syntax of the std:: to_string( xxxxxxx)my cuda 9 installed fine, only using cmake .. -DOpenCL_ENABLE=OFF
the cmake completes fine, however make install cannot get by that library conflict std:: to_string See below for details. ( No changes made whatsoever. to anything.) -- following Ubuntu/Deb or Ubunto r14 instructions provided on the Linux compile page...

mike@mike-HP-Z600-Workstation:~/xmr-stak/build$ g++ --version
g++ (Ubuntu 5.5.0-1ubuntu1) 5.4.1 20171010
Copyright (C) 2015 Free Software Foundation, Inc.

mike@mike-HP-Z600-Workstation:/xmr-stak/build$ sudo cmake .. -DOpenCL_ENABLE=OFF
-- Set miner currency to 'monero' and 'aeon'
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mike/xmr-stak/build
mike@mike-HP-Z600-Workstation:/xmr-stak/build$ sudo make install
Scanning dependencies of target xmr-stak-c
[ 3%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_skein.c.o
[ 6%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_groestl.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_blake256.c.o
[ 13%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_keccak.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-c.dir/xmrstak/backend/cpu/crypto/c_jh.c.o
[ 20%] Linking C static library bin/libxmr-stak-c.a
[ 20%] Built target xmr-stak-c
Scanning dependencies of target xmr-stak-backend
[ 23%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o
In file included from /home/mike/xmr-stak/xmrstak/version.cpp:1:0:
/home/mike/xmr-stak/xmrstak/version.hpp: In function ‘std::__cxx11::string get_version_str()’:
/home/mike/xmr-stak/xmrstak/version.hpp:13:33: error: ‘to_string’ is not a member of ‘std’
return std::string(ver_long) + std::to_string(uint32_t(fDevDonationLevel * 100
^
CMakeFiles/xmr-stak-backend.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o' failed
make[2]: *** [CMakeFiles/xmr-stak-backend.dir/xmrstak/version.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/xmr-stak-backend.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-backend.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error

**Comment by tigs001** [comment]
On Ubuntu 17.10 I successfully compiled using the standard packages for nvidia-384, nvidia-cuda-dev, and nvidia-cuda-toolkit.  I think this is all cuda v8.

I ran cmake without specifying a different compiler.  So that means that I used the standard gcc version 7.2.0.

Before executing make, I edited CMakeCache.txt and set the compiler for nvcc to use gcc-5 (you need to have this installed too of course)

`CUDA_NVCC_FLAGS:STRING=-ccbin gcc-5`

**Comment by cameron2018** [comment]
im still having this issue after making the change to makecache.txt

**Comment by faissaloo** [comment]
Please reopen this issue as hasn't been fixed and the workaround doesn't work.
