### ISSUE TITLE
Desactivate AMD and NVIDIA and let just CPU

### ISSUE THREAD

**Issue by kgblaster** [fireice-uk/xmr-stak#857]
How can I deactivate AMD and NVIDIA on this new version?

**Comment by psychocrypt** [comment]
You can use tne command line option --help to see all options and --noAMD
--noNVIDIA to disable the gpus.

**Comment by kgblaster** [comment]
Where i set this?

**Comment by psychocrypt** [comment]
https://www.computerhope.com/issues/chusedos.htm

But google knows many more tutorials and howto's
