### ISSUE TITLE
Windows 10 with Meltdown Update error

### ISSUE THREAD

**Issue by Bavarianspirit** [fireice-uk/xmr-stak#859]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
I5-4430
  - Type of the GPU (if you try to miner with the GPU).
 gtx660 ti

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

Since the meltdown Update the miner does no more work properly. 
Xmr stak combined miner worked in Version 2.0. 
After the Windows Update miner breaks Short Time After Start with Cuda error. 
I tried ver 2.2. Same Problem.
I tried Chancen in the Nvidia config file to remove workload. No help. 
Two days later there was a NVIDIA driver Update. 
Now the miner Runs again with gpu. But only some minutes. Then it breaks again with Cuda error. 
Windows runs on internal Intel hd grafics. 
CPU only works fine. 
Anything known about this issue?

**Comment by JerichoJones** [comment]
Please fill out the template properly.
# Other Issue with STAK

```
- Which OS do you use?
   
- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.
```
