### ISSUE TITLE
Bad compiler optimizations?

### ISSUE THREAD

**Issue by dolohow** [fireice-uk/xmr-stak#861]
Hello

When I start xmr-stak I am getting
```
Cryptonight hash self-test failed. This might be caused by bad compiler optimizations.
```

It used to work just fine, I stopped the process and later I started it again and this thing is happening all the time.

# Basic information
  - Intel x86_64

Compiled with:
```
-DCUDA_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF  -DHWLOC_ENABLE=OFF -DOpenCL_ENABLE=OFF
```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
 Version: xmr-stak/2.2.0/2ae7260/master/lin/cpu/aeon-monero/0
  ```

# Stability issue
  - Is the CPU or GPU overclocked? :heavy_multiplication_x:
  - Is the Main memory of the CPU or GPU undervolted? :heavy_multiplication_x:

Other:
```
gcc (GCC) 7.2.1 20171224
```

I did recompile.

**Comment by fireice-uk** [comment]
Try unmodified source code, that should work.

**Comment by dolohow** [comment]
Turns out that having only 128 hugepages is not enough.  Raising to 256 solved problem for me.

Thanks
