### ISSUE TITLE
Compiling and running with AMD under OS X

### ISSUE THREAD

**Issue by tpjunkie** [fireice-uk/xmr-stak#862]
Not much of an issue, but I was able to successfully compile XMR-Stak under OS X 10.13.2 using

cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
make install

After ensuring hwloc libmicrohttpd gcc openssl and cmake are up to date, and it seems to happily mine using a Radeon RX570  (Currently an eGPU over TB2), so I think the instructions under compiling for MacOS under AMD GPUs can be updated!

Keep up the great work!

**Comment by BigslimVdub** [comment]
![screen shot 2018-01-10 at 9 34 13 pm](https://user-images.githubusercontent.com/30030687/34807508-cfe797b4-f64e-11e7-9dc3-c0704ba31119.png)

/Users/admin" does not appear to contain CMakeLists.txt.

what am I doing wrong? This is the IDENTICAL issue I had on windows, and to fix I moved xmr stak files to the folder above I was requesting make to run. On osx I can because admin password

**Comment by tpjunkie** [comment]
First, for AMD card use, you're gonna want to drop the -DOpenCL_ENABLE=OFF flag; the AMD cards require OpenCL to be used by the miner. If you want to use any NVIDIA cards with the miner, you're gonna need to get rid of the CUDA_ENABLE=OFF flag, as NVIDIA cards require CUDA (make sure you have version 7.5 or later installed) I am mining on a macbook pro with built in discrete graphics, I left CUDA support on in case I felt like mining on the crappy GeForce 750m (and probably melting my laptop). You're looking to compile a CPU only miner with those flags.

The /Users/admin does not appear to contain CMakeLists.txt indicates that you haven't changed your directory to the one where the XMR STAK source was downloaded. Type cd [path to directory here] to do so, or drag and drop the folder into the terminal window after typing cd, and it will fill it out automatically for you. You should be able to run cmake then.

**Comment by BigslimVdub** [comment]
I have no GPU only CPU mining. I managed to move xmr stak 2.2.0 files to admin/install and it built but the miner.exe and dll are nowhere that I can find.

**Comment by tpjunkie** [comment]
Uh, not sure what files the windows source generates, I've only compiled on OS X, sorry.

**Comment by BigslimVdub** [comment]
this is on OSX i am trying to compile right now. I have tried on windows as well with same result. I type in exactly as requested in "osx compile instructions" and it wont build.

**Comment by tpjunkie** [comment]
Oh, you won't generate .exe or .dll files. The /bin/ folder should contain the xmr-stak binary file. To run it, open terminal, cd to the /bin/ folder, hit return, and on the next line type ./xmr-stak which should make it launch. You'll need to supply your pool info and wallet information as well

**Comment by BigslimVdub** [comment]
on, NM I figured it out, by mad. I wasn't CD to the folder the master was in. All good now
