### ISSUE TITLE
WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.

### ISSUE THREAD

**Issue by JonnyUtah12** [fireice-uk/xmr-stak#863]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Core i7-2675QM.
  - HD 6770
# Compile issues
  - Ubuntu 16.04
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPU_ENABLE:BOOL=ON
CUDA_ENABLE:BOOL=OFF
HWLOC:FILEPATH=/usr/lib/x86_64-linux-gnu/libhwloc.so
HWLOC_ENABLE:BOOL=ON
HWLOC_INCLUDE_DIR:PATH=/usr/include
MHTD:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so
MICROHTTPD_ENABLE:BOOL=ON
MTHD_INCLUDE_DIR:PATH=/usr/include
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/usr/include
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
OpenCL_ENABLE:BOOL=ON
OpenCL_INCLUDE_DIR:PATH=/opt/AMDAPPSDK-3.0/include
OpenCL_LIBRARY:FILEPATH=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so
OpenSSL_ENABLE:BOOL=ON
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
WIN_UAC:BOOL=ON
XMR-STAK_COMPILE:STRING=native
XMR-STAK_CURRENCY:STRING=all

# Issue with the execution
  - Do you compiled the miner by our own?
 Yes compiled myself
  run `./xmr-stak --version-long` and add the output here
  Version: xmr-stak/2.0.0/79154f7/HEAD/lin/amd-cpu/aeon-monero/20

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

# Stability issue
  - Is the CPU or GPU overclocked? -no
  - Is the Main memory of the CPU or GPU undervolted? -no

**Comment by psychocrypt** [comment]
You have driver issues. Maybe your linux is to new. The old gpu is only
supported with the proprietary amd driver.  I used ubuntu 14.04 the last
time to get my old equipment running.

**Comment by avujic** [comment]
@psychocrypt  Can you share with us what OS and what AMD gpu/card you are using for development?

**Comment by JonnyUtah12** [comment]
Ubuntu 16.04 and AMD HD 6770.

I will try Ubuntu 14.04 tonight then to see if that works.

**Comment by avujic** [comment]
@psychocrypt   share with us yours [clinfo] and [uname -a]
I'm using Ubuntu 17.10 and cmd/gpu [lspci -v] with [radeon] kernel driver, output is bellow:
    VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM] (prog-if 00 [VGA controller])

**Comment by JonnyUtah12** [comment]
clinfo

terminate called after throwing an instance of 'cl::Error'
what(): clGetPlatformIDs
Aborted (core dumped)

uname -a 


4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by avujic** [comment]
@JonnyUtah12 I presume that xmr-stak do not work with amd/gpu on yours computer?

**Comment by JonnyUtah12** [comment]
Correct everytime I run ./xmr-stak I get the ( WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver. )

**Comment by psychocrypt** [comment]
I used my AMD HD7870 with ubuntu 14.04. I can not provide the clinfo output
because my gpu is broken and I am currently update my hardware.

**Comment by avujic** [comment]
1) Same situation on my Ubuntu 17.10

2) When I try on Arch linux 
[Linux arch63 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10]

[clinfo] output is:
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.3.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA
..........................
ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

Anyway [ ./xmr_stak ]  gives well knows output

WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
WARNING: backend AMD disabled.

**Comment by geogarden** [comment]
@JonnyUtah12 Try: sudo apt install ocl-icd-opencl-dev.

**Comment by psychocrypt** [comment]
please use the opencl shipped with the amd app sdk. Mesa supports only a
view newer gpus.

**Comment by JonnyUtah12** [comment]
With Ubuntu 14.04. and the amd app sdk 3.0 im still getting the same result. 

[2018-01-11 19:50:39] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-01-11 19:50:39] : WARNING: No OpenCL platform found.
[2018-01-11 19:50:39] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-11 19:50:39] : WARNING: backend AMD disabled.


clinfo still gives me.
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

**Comment by JonnyUtah12** [comment]
also ran this with no luck /opt/AMDAPPSDK-3.0/samples/opencl/bin/x86_64$ ./HelloWorld
Error: Getting platforms!

**Comment by MrCowKing** [comment]
I'm having a similar issue with my ATI M5950 (it's a N. Island card). As far as clinfo not detecting a platform, if you don't have an X server running, you need to run the program as root. So, sudo clinfo. I'm using the mesa opencl driver because amd dropped support for older cards on Ubuntu 16.04 and newer. If you need me to post any info I can.

**Comment by totallyG82** [comment]
xmr-stak only works with OpenCl 2.0 if I am not mistaken?

**Comment by mkg20001** [comment]
I got clinfo to work by running `export LD_PRELOAD="/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libamdocl64.so"` before running `clinfo`
