### ISSUE TITLE
The xmr-stak-nvidia is difference Compile of the GPU hash rate.

### ISSUE THREAD

**Issue by reisaiah** [fireice-uk/xmr-stak#865]
-----------This is https://github.com/fireice-uk/xmr-stak-nvidia/releases/download/v1.1.1-1.4.0/xmr-stak-nvidia.zip
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 305.5 | 310.2 | (na) |  1 | 310.3 | 310.5 | (na) |
|  2 | 301.9 | 304.7 | (na) |  3 | 302.4 | 304.9 | (na) |
|  4 | 300.4 | 303.9 | (na) |  5 | 294.6 | 302.7 | (na) |
|  6 | 304.1 | 304.8 | (na) |
-----------------------------------------------------
Totals:   2119.2 2141.7 (na) H/s
Highest:  2146.0 H/s

-----------The version I compiled.
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 306.0 | 306.0 | (na) |  1 | 299.6 | 299.3 | (na) |
|  2 | 296.6 | 296.2 | (na) |  3 | 296.1 | 295.8 | (na) |
|  4 | 293.8 | 294.6 | (na) |  5 | 293.0 | 291.6 | (na) |
|  6 | 295.1 | 295.1 | (na) |
-----------------------------------------------------
Totals:   2080.1 2078.6 (na) H/s
Highest:  2081.7 H/s

The difference between the two is about 70 H/s.

Next.....
-----------This is https://github.com/fireice-uk/xmr-stak-nvidia/releases/download/v1.1.1-1.4.0/xmr-stak-nvidia.zip
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 303.7 | 305.8 | 306.1 |  1 | 298.0 | 304.8 | 306.1 |
|  2 | 305.4 | 305.5 | 305.5 |  3 | 305.4 | 305.5 | 305.5 |
|  4 | 306.6 | 306.6 | 306.5 |  5 | 306.6 | 306.6 | 306.5 |
|  6 | 290.7 | 302.6 | 304.6 |  7 | 298.0 | 304.8 | 306.1 |
-----------------------------------------------------
Totals:   2414.3 2442.1 2446.9 H/s
Highest:  2448.2 H/s

-----------The version I compiled.
HASHRATE REPORT
| ID |  10s |  60s |  15m | ID |  10s |  60s |  15m |
|  0 | 279.1 | 276.6 | (na) |  1 | 280.9 | 274.3 | (na) |
|  2 | 271.0 | 276.7 | (na) |  3 | 265.5 | 264.9 | (na) |
|  4 | 221.9 | 221.6 | (na) |  5 | 203.2 | 204.1 | (na) |
|  6 | 269.2 | 280.1 | (na) |  7 | 271.1 | 270.5 | (na) |
-----------------------------------------------------
Totals:   2061.9 2068.8 (na) H/s
Highest:  2086.7 H/s

The difference between the two is about 320 H/s.

The config.txt file is the same.
The libeay32.dll, ssleay32.dll, xmrstak_cuda_backend.dll, xmrstak_opencl_backend.dll file is the same.

Compilation environment.
* Windows 10
* Visual studio 2017
* Etc :  The same -> https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/WINCOMPILE.md

Can I get CMake GUI setup information?
used to create xmr-stak-nvidia.exe file

![k-008](https://user-images.githubusercontent.com/16423349/34813398-4557e8ac-f6ed-11e7-8bd6-d9b535f96e38.png)

**Comment by JerichoJones** [comment]
Unsupported.

**Comment by fireice-uk** [comment]
We don't support xmr-stak-nvidia anymore.
