### ISSUE TITLE
Set donate level in config

### ISSUE THREAD

**Issue by iamisti** [fireice-uk/xmr-stak#866]
I'd like to have a parameter where I can specify the donation level, like in this tool:
https://github.com/xmrig/xmrig

I like your project, so I keep supporting it, but if you won't have it in the near future, I must switch to another tool to mine, like xmrig.

Keep up the good work,
Cheers!

**Comment by SplitfingerJoe** [comment]
This parameter exists, but do you really think that this is a justified issue?
Other mining tools let you remove the devfee, but then also reduce your overall hashrate (e.g. Claymore).
If you want to profit from their work but don't support it, you might just switch.

**Comment by iamisti** [comment]
I didnt say i dont but maybe set it to 1% would be better setup for me. Also some may increase this number... u can set a minimum donation level if u wish

**Comment by daysus** [comment]
The author say: By default the miner will donate ..... of the hashpower (.... minute in 100 minutes) to my pool. If you want to change that, ed**it donate-level.hpp before you build the binaries.**

**Comment by fireice-uk** [comment]
The parameter is in the binary and not the config to "gently encourage" bot herders to move on / build their own version and stop creating problems for everybody else. At least that was the theory
