### ISSUE TITLE
Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266

### ISSUE THREAD

**Issue by silentj408** [fireice-uk/xmr-stak#869]
Used to work fine then windows updated and now it crashes randomly, If I open chrome it crashes.
pretty much cant use the PC once its running. I had put off the windows update but it auto updated :( 

# Basic information
  - Type of the CPU.   i7-4700MQ CPU @ 2.40 GHZ
  - Type of the GPU (if you try to miner with the GPU).  Nvidia Geforce GT 750M

# Issue with the execution
  - Do you compiled the miner by our own?
 no
  run `./xmr-stak --version-long` and add the output here
] Error gpu 0: <C:/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:266
  ```

# Stability issue
  - Is the CPU or GPU overclocked? no
  - Is the Main memory of the CPU or GPU undervolted? no

**Comment by psychocrypt** [comment]
set bfactor to 8 or readuce the threads.

**Comment by silentj408** [comment]
What happened these setting used to work for awhile then one day they didn't?

**Comment by psychocrypt** [comment]
You updated your system. I do kot know what your update changed.

**Comment by Bavarianspirit** [comment]
Seems like my issue. #859
Intel bug Update.

**Comment by JerichoJones** [comment]
I have the meltdown patch on Win10 x64. No problems other than the expected slowdown. I don't think this is a STAK issue. I'm running the blockchain driver.
