### ISSUE TITLE
HTTP Daemon Failed to Start

### ISSUE THREAD

**Issue by jwm1969** [fireice-uk/xmr-stak#870]
I keep getting error:  "HTTP Daemon failed to Start" and it is only resolved by rebooting computer...the error is generated by:

MHD_start_daemon(...

returning nullptr

I found online it could be caused by an out of date libmicrohttp library, but i verified the one i compiled with was latest static lib from your dep.  I found another guy who said that not terminating list with MHD_OPTION_END could cause it, but you guys do this fine also.

I am not quite sure how to turn on MHD_USE_DEBUG if that would be helpful and someone could point me in right direction.

Other avenues pursued:  thought port 420 was being held open on a not so graceful shutdown of xmr-stak, so I changed port and it still will not start.

**Comment by jwm1969** [comment]
Update:  I disabled httpd server in config and xmr-stak will start but gives this error:

[2018-01-11 07:53:35] : Fast-connecting to pool.supportxmr.com:7777 pool ...
[2018-01-11 07:53:35] : SOCKET ERROR - [pool.supportxmr.com:7777] CONNECT error: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

**Comment by jwm1969** [comment]
Trying to set MaxUserPort=65534 to see if that helps like it says on technet

**Comment by JerichoJones** [comment]
Any updates?

**Comment by jwm1969** [comment]
I think it may have fixed it, I will close this issue if it does not re-appear for a few days.

To set MaxUserPort (ephemeral port range):

Use the regedit command to access the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\ Services\TCPIP\Parameters registry subkey.

Create a new REG_DWORD value named MaxUserPort.

Set this value to 65534

Stop and restart the system.

**Comment by jwm1969** [comment]
100% fixed this issue in my Rig...going to Close the Issue
