### ISSUE TITLE
Unresponsive/slow PC when start to mine

### ISSUE THREAD

**Issue by Waliers** [fireice-uk/xmr-stak#871]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU: i5-44605 at 2.90 GHz
  - Type of the GPU: GeForce GT 730

# Issue with the execution
  - Do you compiled the miner by our own?
No
  run `./xmr-stak --version-long` and add the output here
Version: xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20
Press any key to exit.

# Stability issue
  - Is the CPU or GPU overclocked?
No
  - Is the Main memory of the CPU or GPU undervolted?
No

MY INFO:
Hi all,

I want to use the software while working on my pc (sending e-mails and browsing websites nothing fancy). 
Is it possible to "tweak" the config files so that I can mine AND work on the pc?

At the moment I can only mine at night since pressing start takes forever, let alone work on it...

I'm using the miner on my laptop as well and here I can run it while working as well but im at a loss to why it doesnt work on my pc...

[CPU.txt](https://github.com/fireice-uk/xmr-stak/files/1623662/CPU.txt)
[NVIDIA.txt](https://github.com/fireice-uk/xmr-stak/files/1623665/NVIDIA.txt)
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1623669/config.txt)

EDIT:
I just used --noAMD --noNVIDIA and I can mine while working. So I probably need to change something for the GPU since mining with just the CPU works great as soon as I add the GPU mining the PC becomes unresponsive.

EDIT2:
I've seen on other issues that it's designed to "eat" everything for high hashrates so I am toying with the settings now. If someone can give me some pointers that would be nice.

**Comment by psychocrypt** [comment]
increase bfactor or reduce the number of threads.

**Comment by Waliers** [comment]
Found the sweet spot :) Thank you!

**Comment by psychocrypt** [comment]
how do you solved the issue?

**Comment by Waliers** [comment]
Followed your advice, made a new NVIDIA file and changed Bfactor to double (16). Now I can work and mine with both CPU and GPU.
