### ISSUE TITLE
[FEATURE REQUEST] per-GPU report for "AMD Invalid Result"

### ISSUE THREAD

**Issue by hairetikos** [fireice-uk/xmr-stak#872]
Several people have reported `AMD Invalid Result` from mining with various GPUs with different settings.

I have also experienced this issue with PowerColor GPUs in particular.

To diagnose, rather than having to run `xmr-stak` for each GPU, can the `AMD Invalid Result` be more verbose and let us know the OpenCL device number on which the error occured and number of errors per device?

I think this would ease diagnosing rigs with many cards and eliminate ones maybe due to "silicon lottery"

**Comment by bruslie** [comment]
i got much problems with AMD Invalid Result, but finaly i got it to 0 fails on my vega 64 8x rig
2 things    
1. riser + card same GPU
2. lower the MHZ on the fail cards from 1100 to 1060

**Comment by psychocrypt** [comment]
This is already included in the current dev branch in will be released with the next stable release

**Comment by nuigru** [comment]
I have the same problem,
rig with 8 GPU and about 1-2 AMD errors every hours.
Would be very useful to have information about which device number created the problem.
Is there a link to this dev branch version that can be checked ?

  thanks

**Comment by psychocrypt** [comment]
This feature is already included in the dev branch and will be in the next
release.
The next release will be before the hard fork (This month)

**Comment by nuigru** [comment]
Is there a way to have early access to the dev branch ?

**Comment by hairetikos** [comment]
@nuigru just clone the dev branch
