### ISSUE TITLE
How donation is working ?

### ISSUE THREAD

**Issue by cryptogrot** [fireice-uk/xmr-stak#873]
I would like to know how process donation works, I configured the donation level to`5.0 / 100.0` but I don't see any connection to the the `dev` pool.

I used `gcc` 6.3.0 and `cmake` 3.9.5 to compile the sources on Debian Stretch 9.3.

Everything works fine, the miner is connected to the Intense (ITNS) pools.

Please find the command I used to compile:
  ```
$ cmake .. -DHWLOC_ENABLE=ON -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DCPU_ENABLE=ON -DOpenSSL_ENABLE=ON
  ```
Version:
  ```
xmr-stak/2.2.0/2ae7260/master/lin/cpu/monero/0
  ```

Thanks for your lights !

**Comment by NmxMilk** [comment]
Every 100 minutes, it will switch working from your pool to the dev pool for x minutes, where is the number you configure for the donation level (5 in your case).

**Comment by cryptogrot** [comment]
@NmxMilk Thanks, I got this part but what I'm wondering more how they get donations, I didn't see anything in the code related to their wallet.

How the miner is able to login in `donate.xmr-stak.net` without the wallet ?

**Comment by JerichoJones** [comment]
Out of scope for support.

**Comment by cryptogrot** [comment]
@JerichoJones but should I not see the line `Dev pool connected. Logging in...` in the log ?
