### ISSUE TITLE
xmr-stak support proxy server?

### ISSUE THREAD

**Issue by bobwang3** [fireice-uk/xmr-stak#875]
I ping mine pool about 5% of the packet loss, which is acceptable. But if the network fluctuations, packet loss rate will rise, the software prompts "All pools are dead, Timeout while waiting for a reply...", mining action will reconnect, interrupt about half a minute. I have a very good proxy server(ssr/v2ray), can I use it in xmr-stak?

**Comment by fireice-uk** [comment]
Not without a proxifier, but you can tune the settings to make the miner reconnect faster ( retry_time ).
