### ISSUE TITLE
ETN restart when dev mining start

### ISSUE THREAD

**Issue by ubbe1** [fireice-uk/xmr-stak#879]
Running v2.10 at Win 10 pro.
No problems mining XMR but when reading http://minecryptonight.net/ i do have to change to ETN instead.

Now, every time Dev mining start the hash counting script tell 0 H/s and restart.
How to manage this?

Best Regards
Ubbe
EDIT:
Strange. Now 3H uptime so possible something on devpool?

**Comment by psychocrypt** [comment]
Which hash counting script do you mean?

**Comment by ubbe1** [comment]
JJ script or what name it get.

**Comment by psychocrypt** [comment]
Could you please open an issue in the reposetory of this script. It looks like it is an bug in the script.

**Comment by JerichoJones** [comment]
Try [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/)
