### ISSUE TITLE
Mining on an old PC containing Radeon HD 8350 

### ISSUE THREAD

**Issue by gershgorin** [fireice-uk/xmr-stak#881]
To put this into context, I'm using a much older desktop I have laying around.  I already have a desktop with this application running and doing well.  Right now I'm having issues building this on Ubuntu 16.04.3 using the AMDGPU-PRO 17.40-492261 driver.  I'm just putting it to use since power costs are not an issue and...well, why the hell not.

My video card is a Radeon HD 8350.  It is apparently supported according to the website.

Where I am getting stuck is the issue below.  I want to test OpenCL before I move any further since prior installation attempts on this machine have failed to detect the GPU.

```
[2018-01-13 15:09:09] : Your CPU doesn't support hardware AES. Don't expect high hashrates.
[2018-01-13 15:09:09] : MEMORY ALLOC FAILED: mmap failed
[2018-01-13 15:09:09] : MEMORY ALLOC FAILED: mmap failed
[2018-01-13 15:09:09] : MEMORY ALLOC FAILED: mmap failed
[2018-01-13 15:09:09] : MEMORY ALLOC FAILED: mmap failed
[2018-01-13 15:09:09] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak 2.2.0 2ae7260

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-01-13 15:09:10] : Start mining: MONERO
Segmentation fault (core dumped)
```

The above happens when I run ./xmr-stak

Also,

```
$ sudo /opt/amdgpu-pro/bin/clinfo 
Segmentation fault (core dumped)
```

Any suggestions.

**Comment by gershgorin** [comment]
Would that be as simple as installing Catalyst?

**Comment by flicksterdoo** [comment]
You need to make sure the OpenCL support is installed.  You need to load the OpenCL support and dev (headers and libs).  You'd do that like this off the install folder for AMDGPU-PRO

`amdgpu-pro-install --opencl=legacy`

If you get a VEGA you'd run this,

`amdgpu-pro-install --opencl=rocm`

and if you have both (lucky me) you do this,

`amdgpu-pro-install --opencl=legacy,rocm`
