### ISSUE TITLE
Application.BitCoinMiner.ZF stealth-miner virus is found on this build 2.2

### ISSUE THREAD

**Issue by gamehauz** [fireice-uk/xmr-stak#883]
All miners are flagged, but this is different, Application.BitCoinMiner is a known virus that stealth-mines.

What's going on with this?
![zzzzzbitcoinminer virus](https://user-images.githubusercontent.com/20614893/34912295-5c2ec278-f8a3-11e7-84dd-33291edabb0b.PNG)

**Comment by flicksterdoo** [comment]
Can you post the download URL?  Did this come from the github release page?  We really need to get a hash up there for releases so at least we can confirm that the download matches the release page version.

**Comment by Morgon** [comment]
Sums are available right on the main page: https://github.com/fireice-uk/xmr-stak/blob/master/README.md#release-checksums

I can confirm that VirusTotal, for instance, are identifying xmr-stak.exe as having malware, but are we sure that "BitcoinMiner" isn't being used as a generic term here? I haven't compiled the latest version to compare, though I will note that 2.0.0 doesn't have the same reports.

**Comment by flicksterdoo** [comment]
can you just hash the executable you've got and see if it's been messed with?

**Comment by JerichoJones** [comment]
Never download the miner from anywhere other than this github.
