### ISSUE TITLE
WARNING: CL_DEVICE_NOT_FOUND when calling clgetdeviceids

### ISSUE THREAD

**Issue by Thecarrothead** [fireice-uk/xmr-stak#885]
Lately the one GPU i've been running has stopped registering to xmr-stak, leaving it as N/A for hashes and showing 'WARNING: CL_DEVICE_NOT_FOUND when calling clgetdeviceids'. Any help in solving this would be great!

CPU: AMD FX 6300
GPU: NVIDIA GTX 670
OS: Windows 10

clinfo:
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Diamond>clinfo
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2117.13)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.2 CUDA 9.1.84
  Platform Name:                                 NVIDIA CUDA
  Platform Vendor:                               NVIDIA Corporation
  Platform Extensions:                           cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer

  Platform Name:                                 AMD Accelerated Parallel Processing
ERROR: clGetDeviceIDs(-1)

**Comment by Thecarrothead** [comment]
My GPU drivers are also all up to date.

**Comment by Thecarrothead** [comment]
nvm, it has been resolved :D

**Comment by Thecarrothead** [comment]
nvm it's back again?

**Comment by Thecarrothead** [comment]
Wow that was strange, I tried lowering the threads for the gpu, which made it work again. I then raised it a bit higher to test it, and it did not work. I lowered it back down and it still doesn't work.

**Comment by Thecarrothead** [comment]
Now the gpu is showing 3000 hashes per second!???

**Comment by flicksterdoo** [comment]
what are your current settings?  You can move the nvidia.txt file aside and let the xmr-stak recreate one to get the defaults back.  I find that my 670s are good for about 325H/s
