### ISSUE TITLE
'Socket Error' after restarting for the first time

### ISSUE THREAD

**Issue by ChAos48** [fireice-uk/xmr-stak#886]
So after running the miner for the first time without an issue and I decide to restart the miner it gives me the following error

> SOCKET ERROR - [stratum+tcp://pool.etn.spacepools.org:5555] 14832: errir 2006A066: BIO 
 routines:BIO_get_host_ip:bad hostname lookup:.\crypto\bio]b_sock.c:146:host=stratum+tcp

I am running it on windows 10 Pro 64-bit
CPU: intel Core i5-3470 @ 3.20GHz (4CPUs), ~3.2GHz
Memory: 8GB
GPU: Nvidia GeForce GTX 560 Ti

I am mining ETN (so curency for config is monero) and I said yes to ssl everything else is no
the pool I am using is spacepools.org

I downloaded the already compiled version for windows

**Comment by psychocrypt** [comment]
it looks like the pool is not available. try to connect to the port via
telnet.

**Comment by flicksterdoo** [comment]
you'll need program that can do telnet, it is no longer installed by default post Windows 7.  This article should work for Windows 10 (you may need to google)
[https://technet.microsoft.com/en-us/library/cc771275(v=ws.10).aspx#bkmk_installcmd](https://technet.microsoft.com/en-us/library/cc771275(v=ws.10).aspx#bkmk_installcmd)

and once that's done you will be telnetting to the port that the pool is looking for, so in this case you will telnet to port 5555.

Don't expect to see much if it's ssl, but in this case your url would indicate that it isn't SSL, rather raw.  You may also want to try turning off SSL and seeing if you can hook up that way.

**Comment by ChAos48** [comment]
I could connect via telnet.
I did forget to mention that if I delete the config.txt and go through the setup again it does connect. After closing the application and reopening it the error occurs unless I delete the config file again and go through the setup again this happens on multiple pc's that we have. All with the same error.  The issue also happens using any of the given ports by the pool. Using other pools also gives the same error.

**Comment by flicksterdoo** [comment]
never seen it.  I'm running 10 myself (not to that pool) but have not seen anything like that.  I'm assuming you've checked the config file to make sure it's not corrupted prior to deleting?

**Comment by ChAos48** [comment]
I found the issue.
I set the miner to use TLS/SSL when the pool does not support it.

thanks for the help, it let me get my thoughts together

**Comment by flicksterdoo** [comment]
glad to be a help

**Comment by jagerman** [comment]
I think this should be reopened: I noticed the same issue.  It seems when `xmr-stak` runs initially and it asks you for configuration values, it generates the config file using your TLS setting, but then ignores it for the initial connection (i.e. connecting without TLS).  On stopping it and starting it again, it now uses the `config.txt` TLS option.  The end result is:

- you can't connect in the first run to a TLS server
- if you enable TLS, but the server doesn't actually support TLS, the initial run works but subsequent runs fail to connect.
