### ISSUE TITLE
Faulty work size? 8/32 instead of 8/256

### ISSUE THREAD

**Issue by PorkyForky** [fireice-uk/xmr-stak#887]
Hi,

I am using Sapphire RX 480 8GB on my Windows 10 and have been using xmr-stak-amd and now I downloaded xmr-stak 2.2.0. 
With the latest xmr-stak the GPU's start with:
Device 0 worksize 8 / 32

and with the old xmr-stak-amd:
Device 0 worksize 8 / 256

How can I make the new xmr-stak run 8 / 256? My old xmr-stak-amd that run 8 / 256 give me a lot more hashrate.

**Comment by JerichoJones** [comment]
Assign a cpu to the gpu via "affine_to_cpu" setting. If that fails for you... use the old version.
