### ISSUE TITLE
Centos7.4 GPU-RIG -- Amd Driver issue

### ISSUE THREAD

**Issue by LordKain001** [fireice-uk/xmr-stak#888]
Hello together 

I am tying to make a Miningrig with 16 gpus, thats why i chose Linux.

followed this "script" after installing centos
yum update
yum install kernel
yum install epel-release
yum install git
yum install centos-release-scl
yum install devtoolset-4-gcc*
scl enable devtoolset-4 bash

./AMD-APP-SDK-v3.0.130.136-GA-linux64.sh
cd $AMDAPPSDKROOT/lib/x86_64
sudo ln -sf sdk/libOpenCL.so.1 libOpenCL.so

    git clone https://github.com/fireice-uk/xmr-stak.git
  mkdir xmr-stak/build	
    cd xmr-stak/build
scl enable devtoolset-4 bash
  
    cmake3 ..  -DCUDA_ENABLE=OFF
    make install
    xmr-stak

# Basic information
CentOs7.4
Installed Packages
Name        : amdgpu
Arch        : x86_64
Version     : 17.50
Release     : 511655.el7
Size        : 0.0  
Repo        : installed
From repo   : amdgpu-pro-local
Summary     : amdgpu driver meta package
URL         : http://www.amd.com/
License     : AMD Proprietary License
Description : Meta package to install amdgpu components
  - Type of the GPU ...ASUS rx550

# Issue with the execution
  - Do you compiled the miner by our own? Yes

xmr-stak 2.2.0 2ae7260

Configurable dev donation level is set to 2.0%

-------------------------------------------------------------------
[2018-01-14 15:08:14] : Start mining: MONERO
[2018-01-14 15:08:14] : WARNING: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms.
[2018-01-14 15:08:14] : WARNING: No OpenCL platform found.
[2018-01-14 15:08:14] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-14 15:08:14] : WARNING: backend AMD disabled.

# AMD OpenCl issue
clinfo
Number of platforms                               0

**Comment by psychocrypt** [comment]
You have driver issues. If clinfo is not finding any gpus than also
xmr-stak can not be used. :-(

**Comment by LordKain001** [comment]
Thanks for the quick response i thought so aswell, do you have any hints or ideas what i can try?

i am struggling like 3 full days now

**Comment by psychocrypt** [comment]
Which amd driver do you use?

**Comment by LordKain001** [comment]
'/root/Downloads/amdgpu-pro-17.50-511655/amdgpu-install' -y

**Comment by LordKain001** [comment]
Update: 
Given up on Centos7.4
Tried Centos7.3
Dont do
`sudo Yum update -y `
...it wil update to 7.4
then i tried with a new installation(amd sdk+17.30 driver)...killed the System

Now i am trying installing CentOs6.8 and doing all the updates then installing the 17.30 for 6.9

anyone else having such troubles with the amd driverset?
