### ISSUE TITLE
Choosing pools based on latency to solve the problem of centralization?

### ISSUE THREAD

**Issue by CheapHoarder** [fireice-uk/xmr-stak#889]
There's still an ongoing discussion on how to solve the problem of certain pools gaining too much of the hash rate.

While installing Antergos and letting Chinchi sort my mirror-list the idea hit me. Why not use the same solution for XMR-Stak?

Using a latency testing script like the ones found here https://wiki.voip.ms/article/Choosing_Server#Latency_Testing_Scripts_.28User_Submitted.29 to automatically ping a list of pools and then choose the pool with the best latency! 

This would make it easy for the user and possibly solve the problem! Would a solution like this be possible? What would be needed to make this work? Could you grep information from existing lists like http://aeonpools.net/ or http://www.moneropools.com/?

**Comment by JerichoJones** [comment]
Sounds good on the surface but it would seem to be impractical as some pools require an account, some payouts are higher/lower, etc, etc.
