### ISSUE TITLE
AMD Platform index found but AMD backend disabled

### ISSUE THREAD

**Issue by dmkrovichmix** [fireice-uk/xmr-stak#890]
![screen shot 2018-01-14 at 10 47 03 pm](https://user-images.githubusercontent.com/19509766/34926402-1ae87c84-f97d-11e7-8084-21fd9df7a88e.png)

**Comment by dmkrovichmix** [comment]
Compiled from source on Windows 10.

clinfo seems to work fine.

**Comment by eliashdezr** [comment]
Out of nowhere I started getting this error, which is similar too.
![teamviewer_2018-01-16_23-50-10](https://user-images.githubusercontent.com/6153607/35027752-04812b52-fb18-11e7-9021-0e3e795f978d.png)

**Comment by dmkrovichmix** [comment]
My config.txt didn't have the platform_index option at all.  Tried setting it to 0,1, and 2.  All yielded the same result.  Will post the output from clinfo next.

**Comment by dmkrovichmix** [comment]
[clinfo.txt](https://github.com/fireice-uk/xmr-stak/files/1638214/clinfo.txt)

**Comment by dmkrovichmix** [comment]
Doing more research perhaps I need to install OpenCL from Intel.....

**Comment by dmkrovichmix** [comment]
Installing OpenCL from Intel didn't seem to help.  Not sure where to try next.

**Comment by Simaex** [comment]
You need OpenCL from AMD. No AMD-specific code in OpenCL from Intel.

**Comment by dmkrovichmix** [comment]
@Simaex 

My initial setup was just OpenCL from AMD.  Built xmr-stak from source on windows.  After that didn't work I tried installing the Intel OpenCL but no change.

**Comment by dmkrovichmix** [comment]
Not going to worry about this much further.  I think this is most likely a driver issue and nothing with xmr-stak.
