### ISSUE TITLE
using env proxy settings 

### ISSUE THREAD

**Issue by Neuromancer2701** [fireice-uk/xmr-stak#892]
Ubuntu 16.04 LTS
I am behind a firewall/proxy.  But I have a login that I export to the terminal environment variables.
When I use ethminer, I can make a connection to dwarfpool without any problems.
But I am unable to connect to monerohash:80 with xmr-stak.  I have gotten around it by vpning into another server and then starting xmr-stak but I would like to get rid of that step.

One of the differences is that ethminer was just an apt-get install and xmr-stak was a locally compiled.
I have tried more than just port 80 for monerohash. And I can get to website just fine.

This could be something as generic as getting locally compile applications to use specific environment variables but I am just not sure.

Any insight would be appreciated.

**Comment by JerichoJones** [comment]
Use a proxifier?

**Comment by noctrex** [comment]
You cloud try to compile proxychains:
```
git clone https://github.com/rofl0r/proxychains-ng.git 
cd proxychains-ng 
./configure
make
make install 
make install-config
```
change the proxychains configuration:

`nano /usr/local/etc/proxychains.conf`

and add at the end of the config your proxy details,
and then use it like this:

`proxychains4 xmr-stak`
