### ISSUE TITLE
Feature Request: Assign threads to groups of CPUs

### ISSUE THREAD

**Issue by TheBulitt** [fireice-uk/xmr-stak#893]
what would be great is if we could assign threads to groups of cores. I have an 8 core AMD Vischera and it uses 8MB of shared L3 cache. Currently I have it set up like this:
"cpu_threads_conf" :

> [
> { "low_power_mode" : 2, "no_prefetch" : false, "affine_to_cpu" : false },
> { "low_power_mode" : 2, "no_prefetch" : false, "affine_to_cpu" : false },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
> 
> ],

but it would be nice if I could set the two low-power threads to use just cores 0+2 and 4+6, something like

> [
> { "low_power_mode" : 2, "no_prefetch" : false, "affine_to_cpu" : 0+2 },
> { "low_power_mode" : 2, "no_prefetch" : false, "affine_to_cpu" : 4+6 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
> { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
> 
> ],

HASHRATE REPORT - CPU
| ID | 10s | 60s | 15m | ID | 10s | 60s | 15m |
| 0 | 62.4 | 66.7 | 55.8 | 1 | 62.0 | 66.9 | 55.8 |
| 2 | 58.0 | 58.8 | 50.2 | 3 | 55.9 | 60.7 | 48.6 |
| 4 | 65.1 | 70.7 | 57.8 | 5 | 36.5 | 37.0 | 40.9 |

As you can see core 7 really suffers because the other threads have starved it of L3 cache.

**Comment by psychocrypt** [comment]
could you please show the config from the auto suggestion. If you have
linux please run hwloc-ls.
If you have 8 mb ram than the optimal thread cound should be 4 for monero
or do you use aeon?

**Comment by TheBulitt** [comment]
when I let it run the autoconfig it fails:

> [2018-01-15 15:01:06] : Start mining: MONERO
> WARNING: NVIDIA Insufficient driver!
> [2018-01-15 15:01:06] : WARNING: backend NVIDIA disabled.
> [2018-01-15 15:01:06] : Compiling code and initializing GPUs. This will take a while...
> 
> [2018-01-15 15:01:06] : Device 0 work size 8 / 32.
> [2018-01-15 15:01:14] : Device 1 work size 8 / 32.
> [2018-01-15 15:01:23] : Starting AMD GPU thread 0, affinity: 0.
> [2018-01-15 15:01:23] : hwloc: memory pinned
> [2018-01-15 15:01:23] : Starting AMD GPU thread 1, affinity: 6.
> [2018-01-15 15:01:23] : hwloc: memory pinned
> [2018-01-15 15:01:23] : Autoconf FAILED: Failed to allocate a PU.. Create config for a
> single thread.
> [2018-01-15 15:01:23] : CPU configuration stored in file 'cpu.txt'
> [2018-01-15 15:01:23] : Starting 1x thread, no affinity.

 HASHRATE REPORT - CPU
 | ID |    10s |    60s |    15m |
 |  0 |   73.0 |   73.0 |   (na) |

this is the autoconfig it generates:

 
> "cpu_threads_conf" :
> [
>     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
> 
> ],

If I manually configure 4 threads on the odd-numbered cores they all use the maximum cache per thread thats possible

> "cpu_threads_conf" :
> [
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
> 
> ],

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   82.3 |   (na) |   (na) |  1 |   82.4 |   (na) |   (na) |
|  2 |   82.4 |   (na) |   (na) |  3 |   77.3 |   (na) |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  638.0 |   (na) |   (na) |  1 |  388.2 |   (na) |   (na) |
-----------------------------------------------------
Totals:   1350.5   (na)   (na) H/s

now this provides the highest per-core hashrate but leaves almost 50h/sec on the table versus when I use 2 extra double threads with no affinity.

HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   71.4 |   (na) |   (na) |  1 |   71.6 |   (na) |   (na) |
|  2 |   69.2 |   (na) |   (na) |  3 |   64.9 |   (na) |   (na) |
|  4 |   58.8 |   (na) |   (na) |  5 |   46.1 |   (na) |   (na) |
-----------------------------------------------------
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  638.7 |   (na) |   (na) |  1 |  388.0 |   (na) |   (na) |
-----------------------------------------------------
Totals:   1408.7   (na)   (na) H/s
Highest:  1410.1 H/s

and lasty as to be expected if I put a thread to each physical core, they end up sharing the cache too much and slowing down their total output as well as slowing down the GPU threads (Ive tried setting affinity to false on the GPU's and it actually further reduces hashrates)

> 
> "cpu_threads_conf" :
> [
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
> 
> ],

 HASHRATE REPORT - CPU
 | ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
 |  0 |   44.8 |   (na) |   (na) |  1 |   44.8 |   (na) |   (na) |
 |  2 |   45.2 |   (na) |   (na) |  3 |   45.4 |   (na) |   (na) |
 |  4 |   45.0 |   (na) |   (na) |  5 |   45.2 |   (na) |   (na) |
 |  6 |   46.7 |   (na) |   (na) |  7 |   42.2 |   (na) |   (na) |
 -----------------------------------------------------
 HASHRATE REPORT - AMD
 | ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
 |  0 |  599.6 |   (na) |   (na) |  1 |  375.5 |   (na) |   (na) |
 -----------------------------------------------------
 Totals:   1334.4   (na)   (na) H/s
 Highest:  1333.3 H/s

so the sweet spot is putting some low power threads with affinity JUST to the "slave" cores that's shared with the GPU's

**Comment by Prev-I** [comment]
I've encountered the same problem on AMD FX 6300, which have 6 core and 6 MB on L3 cache.
Running the some test I've got this results:

**3 fixed threads**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 }
],
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   76.9 |   (na) |   (na) |  1 |   77.4 |   (na) |   (na) |
|  2 |   77.3 |   (na) |   (na) |
-----------------------------------------------------
Totals:    231.6   (na)   (na) H/s

**3 fixed threads + 1 shared thread**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false }
],
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   73.3 |   (na) |   (na) |  1 |   68.9 |   (na) |   (na) |
|  2 |   58.8 |   (na) |   (na) |  3 |   47.7 |   (na) |   (na) |
-----------------------------------------------------
Totals:    248.7   (na)   (na) H/s

**3 fixed threads + 2 shared thread**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false }
],
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   67.4 |   (na) |   (na) |  1 |   49.0 |   (na) |   (na) |
|  2 |   53.5 |   (na) |   (na) |  3 |   47.2 |   (na) |   (na) |
|  4 |   47.2 |   (na) |   (na) |
-----------------------------------------------------
Totals:    264.3   (na)   (na) H/s

**6 fixed threads**
"cpu_threads_conf" :
```
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
],
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   46.1 |   (na) |   (na) |  1 |   46.9 |   (na) |   (na) |
|  2 |   46.7 |   (na) |   (na) |  3 |   46.2 |   (na) |   (na) |
|  4 |   46.1 |   (na) |   (na) |  5 |   46.6 |   (na) |   (na) |
-----------------------------------------------------
Totals:    278.6   (na)   (na) H/s

**6 shared thread**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
],
```
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   45.6 |   (na) |   (na) |  1 |   46.3 |   (na) |   (na) |
|  2 |   45.9 |   (na) |   (na) |  3 |   46.4 |   (na) |   (na) |
|  4 |   45.8 |   (na) |   (na) |  5 |   46.0 |   (na) |   (na) |
-----------------------------------------------------
Totals:    276.0   (na)   (na) H/s
