### ISSUE TITLE
Backend_NVIDIA disabled

### ISSUE THREAD

**Issue by schwiznog** [fireice-uk/xmr-stak#894]
# Basic information
  - 2x L5640.
  - NVIDIA 1080 Ti
  - WIN 7

# Issue
- Error: Backend_NVIDIA disabled
- Error: UNKNOWN_ERROR when calling clGetPlatformIDs For number of platforms

After the above warnings the miner continues and seems to work, but is only mining with the CPU. This is my assumption based on the hash rate  of 170 h/s and the above Warnings. It looks like i have all my .dll files (xmr-stak_cuda, xmrstak_opencl). I have posted the confis that the app made on first run as well.

I have looked through a few different threads with this same issue that were closed, but the answers do not solve my problem. Let me know what you guys think. I would be happy to turn off the CPU mining if I could just get the GPU to mine.

"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },

],

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 10982/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 64, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : true, "sync_mode" : 3,
  },

],

**Comment by psychocrypt** [comment]
Please post the full output.

**Comment by deepenough** [comment]
I'm having the same issue. I was mining fine yesterday on a single 1080 ti but after adding another one today I'm now getting the same error. Yesterday the folder contained Nvidia.txt that had my GPU config in it but thats gone today and I see nothing in the config.txt about GPU's. 
[nvidia backend error.txt](https://github.com/fireice-uk/xmr-stak/files/1632907/nvidia.backend.error.txt)
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1632908/config.txt)

**Comment by psychocrypt** [comment]
gpus are listed in nvidia.txt. Never the less please reinstall the driver!

**Comment by deepenough** [comment]
That's the problem. The folder no longer has the nvidia.txt file in it. I even deleted everything and started with the zip file without success. It was running fine yesterday with a single EVGA but after adding a PNY 1080 ti in died. I even removed the PNY and redid the whole process and still no luck. 

I'll try reinstalling the nvidia driver =)

**Comment by schwiznog** [comment]
Here is my post of the config files. I haven't found that any of the config files disapear, but I am just experiencing the backend warning. 
[config.txt](https://github.com/fireice-uk/xmr-stak/files/1632954/config.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1632955/nvidia.txt)
[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/1632956/cpu.txt)

**Comment by deepenough** [comment]
Fixed!!! I reinstalled my nvidia driver and ran into an error I already new how to fix. Maybe this will help others...

After you reinstall the driver, and run the exe you'll likely get a Cuda Error. Go into your nvidia.txt and change the bfactor from 6 to 8 and bsleep to 100. I'm off to the races and running at 1600h/s with two 1080 ti's. I've attached my nvidia txt. Let me know if I helped anyone. And thank you to psychocrypt for his help!
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/1632979/nvidia.txt)

**Comment by schwiznog** [comment]
I reinstalled drivers and now do not receive the GPU backend warning, but I receive a new error after it starts mining "Error gpu 0: <C/xmr-stak-master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:265" and then the miner crashes

**Comment by schwiznog** [comment]
Just read Deepenough's comment. Worrked for me too! Thanks Deepenough

**Comment by mikezter** [comment]
This worked for me in that casae:
NVIDIA Control Panel -> Manage 3D Settings -> DSR - Factors -> 1.2X
https://github.com/xmrig/xmrig-nvidia/issues/65

**Comment by btcminer2** [comment]
what i do for this massege? "Backend_NVIDIA disabled'

**Comment by Spudz76** [comment]
Pending accept, new docs section [here](https://github.com/Spudz76/xmr-stak/blob/dev-cudaDocs/doc/compile.md#cuda-runtime-versus-cuda-sdk) summarizing what CUDA and what Driver for what GPU family

backend disabled probably means you have too new driver for old GPU (Fermi) or some other CUDA Version vs Driver mismatch.
