### ISSUE TITLE
Android Porting

### ISSUE THREAD

**Issue by ejbnvegiga** [fireice-uk/xmr-stak#897]
Hi I'm new here. Do you have plans porting xmr-stak to ARM/Android platform?

I'm currently mining altcoins using NanobytesInc Miners xmrig emulated into Termux app in my Android phone speeding for around 30 H/s, while I am also currently mining with my desktop with Intel G4560 CPU using xmr-stak, I get 60 to 70 H/s when configured default. If configured properly, I can get up to 100 to 125 H/s by using all cores/threads, but it stutters a lot. It would be awesome if it will be used in android devices!

**Comment by Mogster** [comment]
xmr-stak can be forced to run at a lower priority. What I did was to create a shortcut to xmr-stak.exe on the desktop, then change the target from "<path>\xmr-stak.exe" to "cmd.exe /c start /low <path>\xmr-stak.exe". Not sure how it works on Linux. But yeah, an Android app would be cool.

**Comment by JerichoJones** [comment]
ARM will not be supported. Android on x86 seems unlikely.

**Comment by JerichoJones** [comment]
[If he dies, he dies.](https://github.com/fireice-uk/xmr-stak/issues/822#issuecomment-356793393)
