### ISSUE TITLE
best way to compile for a different architecture

### ISSUE THREAD

**Issue by aleqx** [fireice-uk/xmr-stak#900]
I have a complete build system on an older Xeon running Ubuntu 16.04 and I'd like to build optimized binaries for different architectures, such as Haswell. What would be the best way to do it? I'm not new to Make but am new to CMake. With Make I would change the gcc flags to use `-march=haswell`. Any pointer to how best to do this with CMake (before I delve into CMake docs)?

**Comment by JerichoJones** [comment]
This is beyond the scope of github support. That being said, maybe the lurkers here can help.
