### ISSUE TITLE
Low hashrate on new compile

### ISSUE THREAD

**Issue by flaskvn** [fireice-uk/xmr-stak#901]
- CPU: INTEL XEON E5-2630V3 ( no Overclock, no UnderVolt)
- Distro: CentOS

I was using an old compiled version of xmr-stak-cpu since [commit](https://github.com/fireice-uk/xmr-stak-cpu/commit/135184b57926332eaf0d9538148a0311b901c31a) without problem
I'm recently compiled a new binary based on this repo and notice that my hashrate has been halved. So i tried to compile the old xmr-stak-cpu repo which still give me the same hashrate as low as the new binary.

I tried to run the old binary again and still get higher hashrate than the two new compile. My compile environment has not change since the compile on last September. I'm really puzzled since the xmr-stak-cpu repo has seen no major change since my old compile and i use same CPU config. My old binary is working just fine, i just want to upgrade it to a newer version once in a while.

**Comment by JerichoJones** [comment]
Use whichever version works best for you.
