### ISSUE TITLE
Segfault on FreeBSD 11.1 on EPYC 

### ISSUE THREAD

**Issue by streaml1ne555** [fireice-uk/xmr-stak#902]
I compiled xmr-stak on a new FreeBSD 11.1 EPYC 7351P system but it segfaults immediately after generating the config file. I built the debug version and ran it through GDB and this is the output:

```
(gdb) run
Starting program: /root/xmr-stak/xmr-stak
-------------------------------------------------------------------
xmr-stak 2.2.0 c4400d19

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-01-16 20:38:48] : Start mining: MONERO

Program received signal SIGSEGV, Segmentation fault.
0x000000080168d075 in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5

```
The system is using hwloc-1.11.7. This is a completely fresh system with software compiled from a ports tree updated today using CLANG 4 from the base system.

**Comment by fastworks** [comment]
Same issue here. Completely different CPU.

#0  0x000000080148d075 in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5
(gdb) bt
#0  0x000000080148d075 in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5
#1  0x000000080148cf2d in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5
#2  0x000000080148ca77 in hwloc_topology_set_userdata_import_callback () from /usr/local/lib/libhwloc.so.5
#3  0x000000080147395b in hwloc_topology_load () from /usr/local/lib/libhwloc.so.5
#4  0x000000000043eb69 in xmrstak::cpu::autoAdjust::printConfig ()
#5  0x000000000043d9f0 in xmrstak::cpu::minethd::thread_starter ()
#6  0x00000000004283c4 in xmrstak::BackendConnector::thread_starter ()
#7  0x000000000042bd2b in executor::ex_main ()
#8  0x000000000042209d in _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM8executorFvvEPS7_EEEEEPvSC_ ()
#9  0x00000008008a3bc5 in pthread_create () from /lib/libthr.so.3
#10 0x0000000000000000 in ?? ()

**Comment by JerichoJones** [comment]
Please complete the template.
