### ISSUE TITLE
2 X 7850 (1gb) hashrate down..

### ISSUE THREAD

**Issue by why35** [fireice-uk/xmr-stak#903]
Hello Guys ,

I had 1x7850 - 1x7700 and using xmr-stak , my 7850 was 350h/s , 7700 was 150h/s , both of them with OC

But when i changed my 7700 with another 7850 both of hashrate decreased now both of 7850 giving 250/hs per card.

config is..

"gpu_threads_conf" : [
  // gpu: Pitcairn memory:524
  // compute units: 16
  { "index" : 0,
    "intensity" : 285, "worksize" : 8,
    "affine_to_cpu" : false, 
  },
  // gpu: Pitcairn memory:524
  // compute units: 16
  { "index" : 1,
    "intensity" : 285, "worksize" : 8,
    "affine_to_cpu" : false, 
  },

],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

this is my top intensity when i increase giving buffer error.

whats going on guys ? need help.. my new total hasrate ( 2 x 7850 1gb ) same as previous one ( 1 x 7850 + 1 x 7700 )

**Comment by psychocrypt** [comment]
A workaround is to start the miner twice with two different configs. I am
not sure how well the driver can be used together with diffent gpus.
