### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by SKITZOFRENIX01** [fireice-uk/xmr-stak#904]
Apologies if answer is already listed.

I had same issue as alot people ive seen on site regarding the settings

""gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 64, "blocks" : 45,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],

I found aload of answers from this guy @psychocrypt  which sorted my issue (thanks)

However i just wanted to know how changing these settings effect the outcome if at all?

i changed mine to 

"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 32, "blocks" : 45,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],
/*

And works fine, again apologies if its posted already

**Comment by kyleboddy** [comment]
Only way to know is to test and re-test different variables.

**Comment by JerichoJones** [comment]
_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._
