### ISSUE TITLE
Can you clarify behavior of defining multiple pools?

### ISSUE THREAD

**Issue by RetroLemur** [fireice-uk/xmr-stak#905]
Could you please clarify exactly the behavior of defining multiple pools with different weights?

Does this cause the higher weight pool to be used unless it fails, or does it actually spread the hash power among the pools based on weight so that a "10" weighted pool would get ten times the hash power of a "1" weighted pool, but they are both being used?

In other words, is it really weighted, or is to more like a failover where the highest weight is always used if possible?  What happens if you have 2 pools with the same weight?

Thank you.

**Comment by kim0** [comment]
I have precisely the exact questions .. From some quick testing, I cannot see the miner switching between different pools. It is always using the highest weight pool. Unless it waits many hours before switching or something!! @fireice-uk your input is most appreciated. Thanks for your great work

**Comment by Simaex** [comment]
Some time ago there was info that pool weighth is not for splitting hash power but simply to set failover. No use to set the same value. It have no practical use but can cause problems if such exeption was not foreseen by developer. I do not think that this was changed in the current version.

**Comment by fireice-uk** [comment]
Right now the multipool scheme is a simple fail-over strategy (use the highest weighted pool available). Extending it to round-robin strategy is on the todo. 

`What happens if you have 2 pools with the same weight?` Tie breaker is the internal pool id, hence the recommendation not to do that.

**Comment by ThaumicMekanism** [comment]
@fireice-uk Sorry to bother you as I know, as a developer, you probably get bothered by this question a lot but do you have an eta when you would add that? Is it like something that if you find the time would take a long time? Thanks for your great program. Will definitely donate (other than what I already am doing)!

**Comment by fireice-uk** [comment]
@ThaumicMekanism It should make it into xmr stak v2.4 - as we are aiming for a new stable release every month, this means around April.

**Comment by lmachens** [comment]
@fireice-uk 
Did it make it to v2.4? I can not find it in the release notes.
Thank you
