### ISSUE TITLE
Affinity for all GPUS top core 0?

### ISSUE THREAD

**Issue by vans163** [fireice-uk/xmr-stak#906]
There is an option to enable GPU affinity for the worker thread. But how to lock all the gpu threads to core 0?

**Comment by JerichoJones** [comment]
Please re-phrase. This question, as written, seems like the answer is obvious. Maybe showing how you think the config file would work would be helpful.

**Comment by vans163** [comment]
@JerichoJones The config file has a cpu.txt (assign thread pinning for SPECIFIC CPU core) and a nvidia.txt (assign a true/false value whether to pin the GPU thread).

What I am saying is, for the nvidia.txt I want to pin the GPU thread to a SPECIFIC CPU core.

**Comment by JerichoJones** [comment]
"affine_to_cpu"?

**Comment by vans163** [comment]
@JerichoJones affine_to_cpu can is only true or false? Or can it be an integer >1 as well?

**Comment by JerichoJones** [comment]
Yes. Set it to a particular core.
