### ISSUE TITLE
Windows 10 with CUDA 9 compile errors

### ISSUE THREAD

**Issue by Antreasgr** [fireice-uk/xmr-stak#91]
I tried to compile on Windows 10 with Visual Studio 2017 and Cuda 9.0, and i am getting the following error:

Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cu da_backend_generated_cuda_core.cu.obj CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.obj.Release.cmake:219 (message): Error generating C:/Users/Antreas/xmr-stak/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cuda _backend_generated_cuda_core.cu.obj

The full logs running the CMake generation and compiling is in the attached file.
[log.txt](https://github.com/fireice-uk/xmr-stak/files/1444349/log.txt)

**Comment by psychocrypt** [comment]
You used this `cmake -G "Visual Studio 15 2017 Win64"` CMake command but the [documentation](https://github.com/fireice-uk/xmr-stak/blob/dev/doc/compile_Windows.md#compile) say `cmake -G "Visual Studio 15 2017 Win64" -T v140,host=x64 ..`

Please follow exactly the WINDOWS compile guide https://github.com/fireice-uk/xmr-stak/blob/dev/doc/compile_Windows.md#compile

**Comment by Antreasgr** [comment]
Thank you very much, i downloaded and installed the v140 and you were right, it now compiles correctly. 
Keep in mind that the latest version of Visual Studio 2017 by default ships with the windows toolkit v141. 

I now get some runtime errors related to cuda_extra.cu file. If you want any help trying to build this with the 141 version i am willing to try it out and provide logs. Thank you again

**Comment by psychocrypt** [comment]
Cuda is not supporting v141. But this was cuda8 I have not checked if
nvidia changed it with cuda 9.

**Comment by fireice-uk** [comment]
I also get this error. Fresh install of visual studio (v141) + cuda 9.0 fails.

This is the error message:

`  Building NVCC (Device) object CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cuda_backend_generated_cuda_core.cu.obj
  CMake Error at xmrstak_cuda_backend_generated_cuda_core.cu.obj.Release.cmake:222 (message):
    Error generating
    C:/Users/MAIN/github/xmr-stak/build/CMakeFiles/xmrstak_cuda_backend.dir/xmrstak/backend/nvidia/nvcc_code/Release/xmrstak_cuda_backend_generated_cuda_core.cu.obj`

**Comment by fireice-uk** [comment]
CUDA header says

`#if _MSC_VER < 1600 || _MSC_VER > 1911`

So it isn't CUDA <-> VS incompatibility.

**Comment by Antreasgr** [comment]
I have managed to build this and it seems to be a cmake issue. 
Microsoft changed the default toolkit directory to a different scheme. The cmake variable CUDA_HOST_COMPILER is set to $(VCInstallDir)bin which is no longer correct. I have set this to a absolute path like:

`set(CUDA_HOST_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe")` 
(note the forward slashes)

Finally i have set the --cl-version flag to nvcc compiler but i do not know if this is required:
`list(APPEND CUDA_NVCC_FLAGS --cl-version=2017)`

After those changes i have managed to successfully build this.

**Comment by psychocrypt** [comment]
Thanks for the help I will try to create a workaround in our cmake to fix
it automatically if Cuda9 is enabled.

**Comment by fireice-uk** [comment]
@psychocrypt just noting here that setting it to an absolute path is a bad idea for a general usage - it will change with VS service packs.

**Comment by RussIvan** [comment]
Windows 7 Professional
Visual Studio 2017 (14.12.25827)
Cuda 9.1.85
`cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..` - OK
`cmake --build . --config Release --target install` - BAD
**I did as You wrote above**
**Add CMakeLists.txt:**
- `set(CUDA_HOST_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe")`
-  `list(APPEND CUDA_NVCC_FLAGS --cl-version=2017)`

**I am getting the following error:**
`c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/host_config.h(135): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]`

**I tried to change C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\crt\host_config.h**
`#if _MSC_VER < 1600 || _MSC_VER > 1911` => `#if _MSC_VER < 1600`

**and got even more errors**
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(504): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(505): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(506): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(538): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(1043): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(1558): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2371): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\type_traits(2371): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xutility(543): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xtr1common(58): error : class "std::enable_if<<error-constant>, int>" has no member "type" [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xmemory0(390): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xmemory0(1002): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xmemory0(1322): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xstring(1693): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xtr1common(58): error : class "std::enable_if<<error-constant>, void>" has no member "type" [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\xutility(298): error : expression must have a constant value [C:\xmr-stak\build\xmrstak_cuda_backend.vcxproj]`

**Comment by xschral** [comment]
exactly my problems...

**Comment by untra** [comment]
❗️ The problem is [Visual Studio 2017 15.5 failed to support CUDA 9](https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/1)
Or vice-versa. Either way the CUDA community is pretty pissed.

**Comment by oviwankenobi** [comment]
so is it possible to uninstall 141 toolset and install 140
would this fix this whole mess? did anyone tried?

**Comment by SabahKarim** [comment]
> so is it possible to uninstall 141 toolset and install 140
> would this fix this whole mess? did anyone tried?

I am already using 14.0 but still getting the same error..
