### ISSUE TITLE
-DCMAKE_LINK_STATIC=ON not linked all libraries statically

### ISSUE THREAD

**Issue by belikoviv** [fireice-uk/xmr-stak#911]
xmr-stack was compiled with following options:
  ```
cmake .. -DCMAKE_LINK_STATIC=ON -DXMR-STAK_COMPILE=generic -DMICROHTTPD_ENABLE=ON -DOpenSSL_ENABLE=OFF -DCPU_ENABLE=ON -DOpenCL_ENABLE=OFF -DCUDA_ENABLE=OFF
make install
  ```
But when compiled binary moved to another system, I got the following:
  ```
# ldd xmr-stak
        linux-vdso.so.1 =>  (0x00007ffe813ee000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f53031bb000)
        libmicrohttpd.so.10 => not found
        libhwloc.so.5 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5302df0000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556f1da0b000)
  ```
So libmicrohttpd and libhwloc not linked with binary.

How I may compile portable binary with all libraries linked statically?

**Comment by psychocrypt** [comment]
The libraries are linked but you need to configure your environment
correct. Set LD_LIBRARY_PATH to the folders with the libraries.

**Comment by belikoviv** [comment]
I'm so sorry, but I have little experience in compiling binaries.
As I understand - LD_LIBRARY_PATH is set on system where I run the program to help program to find shared libraries.
But I want to link into binary file all libraries and do not use shared libraries on target system. Is it possible?

**Comment by Hacker-One** [comment]
+1, I have same problem, please tell how to do

**Comment by belikoviv** [comment]
I'm found compromise solution - install needed libraries from repository on target system:

sudo apt install libmicrohttpd-dev libhwloc-dev

But this method don't satisfied me.

**Comment by psychocrypt** [comment]
No a full statix build is not possible because linux is not shipping all
libraries as static libs.
This is only possible if you compile the full dependency tree by hand.
Please do not ask how I never tried that.
You can try to copy all shared libraries from the system where you compiled
the miner into the folder where the vi ary is located and than set the
library path to the current directory. This can be a workaround if the OS
on both systems is equal and you only miss some dependencies.

**Comment by chrisknepper** [comment]
Like others in this thread, I am having the same problem. I would like `libmicrohttpd` and `libhwloc` to be included in a portable way. I am compiling xmr-stak on my macOS machine and when I try to distribute it to other macOS users who don't have these libraries installed, they can't run xmr-stak.

Could you elaborate on what you mentioned regarding "copy shared libraries into the folder where the vi ary is located and then set the library path to the current directory"?

**Comment by JerichoJones** [comment]
>"copy shared libraries into the folder where the binary is located and then set the library path to the current directory"
