### ISSUE TITLE
Result rejected by the pool.

### ISSUE THREAD

**Issue by lucky1688** [fireice-uk/xmr-stak#912]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - 2X E2680V4 CPU.
  - 6* 1060 GTX 6G

# Compile issues
  - WIN10  ```

Result rejected by the pool.
  RESULT REPORT
Difficulty       : 450017
Good results     : 0 / 1 (0.0 %)
Avg result time  : 98.0 sec
Pool-side hashes : 0

Top 10 best results found:
|  0 |                0 |  1 |                0 |
|  2 |                0 |  3 |                0 |
|  4 |                0 |  5 |                0 |
|  6 |                0 |  7 |                0 |
|  8 |                0 |  9 |                0 |

Error details:
| Count | Error text                       | Last seen           |
|     1 | Low difficulty share  ```

**Comment by JerichoJones** [comment]
Please fill out the template properly.

---
# Issue with the execution of STAK
- Which OS do you use?

- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
 
- Did you compile the miner yourself or are you running the release?  
   
   
 - Run  
 
```
    xmr-stak --version-long
```
and add the output here  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---
