### ISSUE TITLE
88 threads - 2x Xeon 4669 v4 config problem

### ISSUE THREAD

**Issue by deshudiosh** [fireice-uk/xmr-stak#918]
I've been trying to make configuration for 2x Xeon 4669 v4 (88 threads) for quite a long time now.
My target is to end up with cpu use at about 90-95%.

Auto configuration works best so far, with the cpu usage at about 65%.
I don't really know how xmr-stak comes up with core ids in the "affine_to_cpu", as they exe exceed 88 by long shot ( 106 is the biggest one).

Yes, I've tried just adding a line for each number in sequence 0, 1, 3, 4, 5, 6.........87
This gave me cpu usage at 50%.

I start thinking that hyperthreading might be a problem.

**Automatically generated cpu.txt:**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 16 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 18 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 20 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 22 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 24 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 26 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 28 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 30 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 32 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 34 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 36 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 38 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 40 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 42 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 64 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 66 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 68 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 70 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 72 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 74 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 76 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 78 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 80 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 82 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 84 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 86 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 88 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 90 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 92 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 94 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 96 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 98 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 100 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 102 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 104 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 106 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 65 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 67 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 69 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 71 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 73 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 75 },
],
```

**Comment by ChromeHearts** [comment]
are you running on Linux?  If yes with hyper threading, you should set the affinity from 0-43 (assuming  you have 44 physical cores, 88 threads).  My experience is that you got more hash rate at 50% CPU usage..  Running two threads in the same HT core will lower the total hash rate.

**Comment by deshudiosh** [comment]
@ChromeHearts I am on windows 7. Gonna try that 0-43 affinity setup in terms of hashrate, but that's not a solution I look for:)

**Comment by deshudiosh** [comment]
I've checked it out, hashrate dropped from 1800 to 500. Autogenerated config works best so far.

**Comment by Slippy369** [comment]
I'm running a a single 2699 (22 cores 44 with HT)  You want to count up from 0-86.  Then add about 3 threads on odd numbered cores per socket i.e (17,27,37,57,67,87)  Spread them out so you get 3 odd threads on each socket.  Also I find you want to avoid running them on the low numbered cores as many of the system apps will run there.  That is how I got over 1000 on mine.  You can play with adding or removing the odd numbered cores 2 at a time (one per socket) to see if the hashrate goes up or down.

**Comment by Slippy369** [comment]
One clarification when I say count up from 0-86 only use even cores.  Should end up with 50 entries, 44 on the even cores and 6 on odd cores.

**Comment by deshudiosh** [comment]
What do you mean by "socket"?

**Comment by deshudiosh** [comment]
I get "Warning: setting affinity failed" on threads 44, 46, 48, 50, 52, 54, 56, 58, 60, 62.

**Comment by Slippy369** [comment]
Ah my apologies second socket (or CPU) on a dual socket(CPU) board starts counting at 64 it would seem so go from 0-42 then 64-106.  Then add the 3 odds on like 17, 27,37,  77. 97, 107

**Comment by Slippy369** [comment]
sorry 6 odds total 3 per CPU

**Comment by deshudiosh** [comment]
Let me fiddle with it for a bit. It seams like auto setup works best. I achieved almost identical results with your approach

**Comment by Slippy369** [comment]
OK do you see a red message about locking memory when it starts?  IF so resolving that will give a big performance bump.  Yeah try adding and removing odd threads and see if it gets better or worse.

**Comment by deshudiosh** [comment]
I don't see red message. I didn't even know that xmr-stak has coloured console output.

**Comment by psychocrypt** [comment]
Note for windows user: the latest version in the dev has a fix that the
uset can see that setting the affinity for cores with a ID greater than 63
is not possible in windows.
This means if you own a windows server whith 88 threads we can only set the
affinity up to thread 63.

**Comment by deshudiosh** [comment]
@psychocrypt Thanks for the info. Any idea when exe will be released? I've never compiled cpp myself.
@Slippy369 Thanks. Luckily I've no memory allocation errors.

**Comment by psychocrypt** [comment]
I think the next release takes more than 3 weeks. I got my amd equipment I
will check all my open pull requests.
In the mean time let the miner generate a config and than change all
affinities greater than 63 to false. This is equal to what the program is
doing.

**Comment by DeeViens** [comment]
Runing xmr-stack v2.0 on Win 10 2x Xeon 2697 v4 (72 threads)
and no problem affinity for cores with a ID greater than 63

I want to try monero7 
will the new v2.6.x version fix this problem?
