### ISSUE TITLE
 I want to know the truth.

### ISSUE THREAD

**Issue by reisaiah** [fireice-uk/xmr-stak#922]
Is there a handicap if I compile with 0% developer fee?
Why does it compare to HASHRATE REPORT when it is 1-2% lower?

I want to know the truth.

I tried about 100 times.
I chose several options.
I have tried CUDA8.0 ~ CUDA9.1.

I would also like to discuss some issues with me.

**Comment by psychocrypt** [comment]
No there is no handycap. You can check the code. Disabling works like we
described it in the documentation.

**Comment by psychocrypt** [comment]
There are no issues described in your oost. Please use the issue template
and profide all information if you have an issue. Please do not mix it
whith this issue if it is something else.

**Comment by reisaiah** [comment]
Thanks for the answer.
if so,
Are there any issues I can check?
I need advice.

**Comment by GoZippy** [comment]
what is the issue? code is open.. look... i dont see anything changing or nerfing ... they even tell you how to screw the devs out of fair fees and set to what you want, even 0.0.... its in the doc and inline as well... theres not that many files to work through or read to understand this. if you feel lesser amt is just, change it, compile and enjoy.

**Comment by fireice-uk** [comment]
`I would also like to discuss some issues with me.`

`Are there any issues I can check?`
`I need advice.`

I will close this as psychocrypt answered the identifiable questions in your post. With regards to the quotes ones, if they are related to xmr-stak, please file a proper report using the template so that we know your hardware and stak version.

**Comment by JerichoJones** [comment]
>Is there a handicap if I compile with 0% developer fee?

Your conscience?

**Comment by reisaiah** [comment]
> Your conscience?
What do you mean?
Your conscience?
It is a problem of poor performance, though the method you proposed.
(Average 8-10 HS is low.)
Don't change anything!
Is my question a problem?
What's the problem?

**Comment by JerichoJones** [comment]
LOL. There is nothing in the code. Read it if you don't believe me.
