### ISSUE TITLE
Make developer fee configurable in config.txt

### ISSUE THREAD

**Issue by andregasser** [fireice-uk/xmr-stak#923]
Hi!

This post is a suggestions. Therefore, I skip all the hardware details.

I was playing around with Docker and xmr-stak. Something I would like to see is being able to set the developer fee withing the config.txt file. 

Use case:
I run multiple containers based off one Docker image. Before I can run containers, I have to build one. I do this in a similar way as you do, by compiling xmr-stak during the image build. But as soon as you would like to run multiple containers with different developer fees, I am forced to compile a version of xmr-stak for every differing value. 

If the developer fee would be configurable within the config.txt, I could simply run containers with bind mounts pointing to different config.txt files. That way, I would be sufficient to build the Docker image once.

Do not get me wrong: Developer fees are totally OK, but I would rather be able to vary them.

Thx!
André

**Comment by GoZippy** [comment]
-1 vote from me

**Comment by psychocrypt** [comment]
If you need this feature you can use 'sed' ro manipulate the files and than
compile it on the fly.

**Comment by andregasser** [comment]
ok, thx for clarifying.
