### ISSUE TITLE
Request for a change in the code of the miner.

### ISSUE THREAD

**Issue by regestro** [fireice-uk/xmr-stak#926]
**Hello! You have an excellent miner (the best of its kind), thank you very much!**
Immediately I say, I am from Russia, and the translation of my message was made using an online translator (sorry!). Also I attach the original in Russian to the end of the message. I also attach a translation from another online translator, for a clearer understanding of me.
I wanted to ask you to change the code of the miner a bit. Personally for me. If it does not complicate you!
So, in the miner you can use several pools. I would like to see the shares go not to one of them, but to all of them. Yes, it's incredibly stupid! After all, it will not be possible to immediately mine several pools. Purely technically. But I have one idea that must be checked. It's even possible that my idea is working. I can not reveal my idea yet.

So, if it does not make it difficult for you to change the code of the miner a little, so that the mining goes simultaneously to several pools, while the hashrate is not divided evenly into all the specified pools, and sent in the same amount for each pool.
I hope, I clearly explained. If not, ask.

I await a response from you, dear developer! And once again, thank you very much.
My e-mail is "regestro@mail.ru".
______________________________________________________________________

Hello! You have an excellent mayner (the best in own way), thanks a lot!
At once I speak, I from Russia, and a transfer of my message was made by means of the online translator (excuse!). Also I attach in the end of the message the original in Russian. I also attach a translation from another online translator, for a clearer understanding of me.
I wanted to ask you to change a code of a miner a little. Personally for me. If it you does not complicate!
So, in a miner it is possible to use several pools. I would like that shares went not to one them them, and on everything specified. Yes, it is incredibly silly! It will not turn out to mining on several pools at once. Purely technically. But I have one idea which needs to be checked. It is very possible that my idea working. I cannot disclose the idea yet.

So, if you does not complicate to change a little a code of a miner that the mining went at the same time on several pools, thus, that hashrate was not divided evenly into all specified pools, and I went in identical quantity to each pool.
I hope, I clear explained. If is not present - ask.

**I wait for the answer from you, reputable developer! And once again many thanks to you.**
My e-mail is "regestro@mail.ru".
______________________________________________________________________

Здравствуйте! У вас отличный майнер (лучший в своем роде), спасибо огромное!
Сразу говорю, я из России, и перевод моего сообщения был осуществлен с помощью онлайн-переводчика (извините!). Также прикрепляю в конец сообщения оригинал на русском.
Я хотел попросить Вас немного изменить код майнера. Лично для меня. Если это Вас не затруднит!
Итак, в майнере можно использовать несколько пулов. Я хотел бы, чтобы шары отправлялись не на один их них, а на все указанные. Да, это невероятно глупо! Ведь не получится майнить сразу на несколько пулов. Чисто технически. Но у меня есть одна идея, которую нужно обязательно проверить. Очень даже возможно, что моя идея рабочая. Пока не могу раскрыть свою идею.

Итак, если Вас не затруднит немного изменить код майнера, чтобы майнинг шел одновременно на несколько пулов, при том, чтобы хэшрейт не делился равномерно на все указанные пулы, а отправлялся в одинаковом количестве на каждый пул.
Надеюсь, я понятно объяснил. Если нет - спрашивайте.

Жду ответа от Вас, уважаемый разработчик! И еще раз большое Вам спасибо.
Моя почта - "regestro@mail.ru".

**Comment by psychocrypt** [comment]
This feature is planed but has currently not the highest priority.
