### ISSUE TITLE
worker name cannot be setted

### ISSUE THREAD

**Issue by cetindogu** [fireice-uk/xmr-stak#929]
no way to set my rig names???? really hurts me

xmr-stak-amd-win64.zip

i m using AMD rx 460,470,480 cards and have 11 RIGS

my config.txt file content:

/* 
 * Number of GPUs that you have in your system. Each GPU will get its own CPU thread.
 */
"gpu_thread_num" : 7,

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 */
"gpu_threads_conf" : [ 
	{ "index" : 0, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 1, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 2, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 3, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 4, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 5, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
	{ "index" : 6, "intensity" : 1536, "worksize" : 32, "affine_to_cpu" : false },
],

/*
 * Platform index. This will be 0 unless you have different OpenCL platform - eg. AMD and Intel.
 */
"platform_index" : 1,

/*
 * TLS Settings
 * If you need real security, make sure tls_secure_algo is enabled (otherwise MITM attack can downgrade encryption
 * to trivially breakable stuff like DES and MD5), and verify the server's fingerprint through a trusted channel. 
 *
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_secure_algo - Use only secure algorithms. This will make us quit with an error if we can't negotiate a secure algo.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 */
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",

/*
 * pool_address	  - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address - Your wallet, or pool login.
 * pool_password  - Can be empty in most cases or "x".
 */
"pool_address" : "uk-etn-pool.hashparty.io:3333",
"wallet_address" : "etnk42mveXmiPbwGyxTCki7k1Xvs2gBx75iBzYJF2oyYGvkMxQixv8PExC4dCYJGtHPBgj6FEWda7DXc98YuyUAn9hdjqxY2sb",
"pool_password" : "",

/*
 * Network timeouts.
 * Because of the way this client is written it doesn't need to constantly talk (keep-alive) to the server to make 
 * sure it is there. We detect a buggy / overloaded server by the call timeout. The default values will be ok for 
 * nearly all cases. If they aren't the pool has most likely overload issues. Low call timeout values are preferable -
 * long timeouts mean that we waste hashes on potentially stale jobs. Connection report will tell you how long the
 * server usually takes to process our calls.
 *
 * call_timeout - How long should we wait for a response from the server before we assume it is dead and drop the connection.
 * retry_time	- How long should we wait before another connection attempt.
 *                Both values are in seconds.
 * giveup_limit - Limit how many times we try to reconnect to the pool. Zero means no limit. Note that stak miners
 *                don't mine while the connection is lost, so your computer's power usage goes down to idle.
 */
"call_timeout" : 10,
"retry_time" : 10,
"giveup_limit" : 0,

/*
 * Output control.
 * Since most people are used to miners printing all the time, that's what we do by default too. This is suboptimal
 * really, since you cannot see errors under pages and pages of text and performance stats. Given that we have internal
 * performance monitors, there is very little reason to spew out pages of text instead of concise reports.
 * Press 'h' (hashrate), 'r' (results) or 'c' (connection) to print reports.
 *
 * verbose_level - 0 - Don't print anything. 
 *                 1 - Print intro, connection event, disconnect event
 *                 2 - All of level 1, and new job (block) event if the difficulty is different from the last job
 *                 3 - All of level 1, and new job (block) event in all cases, result submission event.
 *                 4 - All of level 3, and automatic hashrate report printing 
 */
"verbose_level" : 3,

/*
 * Automatic hashrate report
 *
 * h_print_time - How often, in seconds, should we print a hashrate report if verbose_level is set to 4.
 *                This option has no effect if verbose_level is not 4.
 */
"h_print_time" : 60,

/*
 * Daemon mode
 *
 * If you are running the process in the background and you don't need the keyboard reports, set this to true.
 * This should solve the hashrate problems on some emulated terminals.
 */
"daemon_mode" : false,

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

/*
 * Built-in web server
 * I like checking my hashrate on my phone. Don't you?
 * Keep in mind that you will need to set up port forwarding on your router if you want to access it from
 * outside of your home network. Ports lower than 1024 on Linux systems will require root.
 *
 * httpd_port - Port we should listen on. Default, 0, will switch off the server.
 */
"httpd_port" : 0,

/*
 * prefer_ipv4 - IPv6 preference. If the host is available on both IPv4 and IPv6 net, which one should be choose?
 *               This setting will only be needed in 2020's. No need to worry about it now.
 */
"prefer_ipv4" : true,

**Comment by JerichoJones** [comment]
Where do expect the rig name to be displayed?

**Comment by cetindogu** [comment]
hashpart.io, electroneum mining pool
http://uk-etn-stats.hashparty.io
My wallet address is 

etnk42mveXmiPbwGyxTCki7k1Xvs2gBx75iBzYJF2oyYGvkMxQixv8PExC4dCYJGtHPBgj6FEWda7DXc98YuyUAn9hdjqxY2sb

I just can see total hashrate.

**Comment by JerichoJones** [comment]
The pool has to support it. usually it is part of your password or ID.

**Comment by cetindogu** [comment]
Ok, I got it, I m going to send an email to hashparty.io, thanks for the answer.
