### ISSUE TITLE
Add a line group by thread_id in http report ?

### ISSUE THREAD

**Issue by B3l3tt3** [fireice-uk/xmr-stak#93]
Not really an issue, but a request asking you if it would be possible to add a sum of the hashrate by thread_id in the html report please ?
I tried to do it but I couldn't find how/where I have to calculate the sum to print it in webdesign.

**Comment by fireice-uk** [comment]
Sum by thread_id? Do you mean for Vega cards?

**Comment by B3l3tt3** [comment]
Hi, mainly for Vegas yes but actually I'm using 2 threads for each of my RX580 too and get better results.
