### ISSUE TITLE
how to limited the GPU usage?

### ISSUE THREAD

**Issue by kamisama2333** [fireice-uk/xmr-stak#931]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Intel Xeon E3 1230V2.
  - GTX 750TI × 2.

# Compile issues
  - Windows 7 64bit
  ```
  // gpu: GeForce GTX 750 Ti architecture: 50
  //      memory: 1964/2048 MiB
  //      smx: 5
  { "index" : 0,
    "threads" : 6, "blocks" : 6,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 750 Ti architecture: 50
  //      memory: 1964/2048 MiB
  //      smx: 5
  { "index" : 1,
    "threads" : 6, "blocks" : 6,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

I have two  GTX 750 Ti , I want to make one of them not full loaded, limit its usage, such 90%, so it will no affect normal computer use, but whatever parameter I set, it always cost 100% GPU load, is there any way to do so?

**Comment by JerichoJones** [comment]
* bfactor       - Enables running the Cryptonight kernel in smaller pieces.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 8
 * bsleep        - Insert a delay of X microseconds between kernel launches.
 *                 Increase if you want to reduce GPU lag. Recommended setting on GUI systems - 100

**Comment by kamisama2333** [comment]
Recommended setting on GUI systems - 8
Recommended setting on GUI systems - 100

no work, still 100% load

**Comment by XhmikosR** [comment]
You should try decreasing the number of threads.
