### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SuperOP535** [fireice-uk/xmr-stak#932]
OS: Windows 10 64-bit
GPU: AMD Radeon R7 240
CPU: AMD A6 6400K APU with Radeon(tm) HD Graphics 3.90 GHz
RAM: 8 GB
Currency: monero
Nicehash: no
TLS: no
xmr-stak version: v2.2.0

The miner instantly freezes and the classic "xmr-stack.exe has stopped working" popup appears.

I run xmr-stak with xmr-stak.exe --noNVIDIA --noCPU

If I replace --noCPU with --noAMD it works fine so I don't know why it doesn't want to work with the GPU

**Comment by JerichoJones** [comment]
Please complete the template properly

---
# Issue with the execution of STAK
- Which OS do you use?

- Type of the CPU. Running stock clocks/voltages? If not, provide settings.  
  
- Type of the GPU (if you try to miner with the GPU). Running stock clocks/voltages? If not, provide settings.  
  
- Amount of RAM memory. Running stock clocks/voltages? If not, provide settings.  
 
- Did you compile the miner yourself or are you running the release?  
   
   
 - Run  
 
```
    xmr-stak --version-long
```
and add the output here  
  
  
  
 1. Describe the issue clearly:
 
	a. A short synopsis of what is happening.
    
	b. What you expect should be happening.
    
	c. Exact error message(s), if any.
    
	d. Include screenshots and/or logs of the issue.
    
	e. If useful, edit the screenshot with circles or arrows to highlight the error.
        
 2. Describe what steps you have performed in an attempt to resolve the issue.

---

**Comment by psychocrypt** [comment]
What was the reason for the freez?

**Comment by SuperOP535** [comment]
didn't fix, I made a new issue

**Comment by maliardo1967** [comment]
I have got the same issue when xmr-stak stop work silency when useing R7 240 GPU. I use Win10 too.
Is there anything solution for this issue.
