### ISSUE TITLE
Where is the xmr-stak-portbin-linux.tar.gz in releases?

### ISSUE THREAD

**Issue by eddiejibson** [fireice-uk/xmr-stak#934]
Hi,

I'd like to use xmr-stack for Linux. However, I don't see it in any of the recent releases, must I compile just for use? If so, I don't see any valid instructions for doing so on Linux.

Thanks.

**Comment by hunasdf** [comment]
+1

**Comment by davidcomerford** [comment]
+1 
Thought I was going blind.

**Comment by mibzman** [comment]
@nsummy, @eddiejibson is referring to the instructions at https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md, which refer to the latest releases for a file titled 'xmr-stak-portbin-linux.tar.gz', which does not exist in the releases.

**Comment by callum-p** [comment]
+1

**Comment by nsummy** [comment]
@mibzman Yes, but he also said if he has to compile himself, he can't find the instructions.

The document you reference does state:  "This is an experimental feature we reserve the right to remove the binary if we get too many issues."

**Comment by hunasdf** [comment]
@nsummy  https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md solved my problem :)

**Comment by mibzman** [comment]
@nsummy yeah it totally makes sense that it was removed.  I'd totally do a PR for the documentation, but since I only found this repo this week I don't want to muck with the documentation.
