### ISSUE TITLE
display hashrate at some interval in miner output

### ISSUE THREAD

**Issue by travisstaloch** [fireice-uk/xmr-stak#936]
Is it possible to show the hashrate info in the miner window every X seconds or minutes so that I can see a history of the hashrates?  Forgive me if this is covered elsewhere, but I looked around and couldn't find anything.

**Comment by Steelminer** [comment]
By default it does it every minute, or you can press the h key and that would show it whenever you want to see it.

**Comment by travisstaloch** [comment]
I know you can press 'h' to see it.  I would like to see a history of the hashrate on a remote machine for monitoring purposes and its not showing up.  I just installed the latest release win 64 version today and not seeing any hashrate output, just this over and over: 

...
[2018-01-20 14:50:30] : Result accepted by the pool.
[2018-01-20 14:51:15] : New block detected.
[2018-01-20 14:52:09] : New block detected.
[2018-01-20 14:52:58] : Result accepted by the pool.
...

Is there something in the config.txt I might need to include or change?

**Comment by DrMoropo** [comment]
Go to the config.txt file, there's a setting in there that says "verbose_level". Change that from 3 to 4. That will give you automatic hashrate reports.

The default is to report every 60 seconds, if you want to change that there is another setting below
"h_print_time" : 60,

Change that from the default 60 to whatever you want.

**Comment by travisstaloch** [comment]
Ok thank you!  Exactly what I was looking for.
