### ISSUE TITLE
No Hashrate

### ISSUE THREAD

**Issue by KingCornWallis** [fireice-uk/xmr-stak#939]
Hello,

Upon starting, Windows becomes incredibly laggy, yet absolutely no Hashrate. I can get a solid Hashrate when running XMR-Stak-CPU though, so I know it's a GPU problem. In the beginning I kept getting GPU errors and changed the bfactor from 6 to 10 and the bsleep from 25 to 100 to keep it from crashing. I've also toggled the threads value a bit, but 128 is default.  

Basic information
Xeon x3363
GT 730
Running a display on GPU, no IG on CPU.

Compile issues
Which OS do you use? Windows 10 Pro
Compile output (used precompiled binary)

Please enter:
- Currency: 'monero' or 'aeon'
monero
- Pool address: e.g. pool.usxmrpool.com:3333
pool.supportxmr.com:3333
- Username (wallet address or pool login):
42JoEXKvzipGwjAnvm2deMYotWHS1gU5XaM4u3qkXP7QG2uXgDXKrjTBPPJHDXZ6F7hQ3EUU9F5owJxQJxbjwBQRP4nq6gt
- Password (mostly empty or x):
x
- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
N
- Do you want to use nicehash on this pool? (y/n)
y
- Do you want to use multiple pools? (y/n)
n
Configuration stored in file 'config.txt'
[2018-01-20 16:15:35] : Your CPU doesn't support hardware AES. Don't expect high hashrates.

//etc

Is the CPU or GPU overclocked? No.
Is the Main memory of the CPU or GPU undervolted? No.

**Comment by KingCornWallis** [comment]
My current NVIDIA file settings:
"gpu_threads_conf" :
[
// gpu: GeForce GT 730 architecture: 35
//      memory: 1690/2048 MiB
//      smx: 2 original threads is 128
{ "index" : 0,
  "threads" : 128, "blocks" : 6, 
  "bfactor" : 10, "bsleep" :  100,
  "affine_to_cpu" : false, "sync_mode" : 3,
},

**Comment by JerichoJones** [comment]
Fill out the template please.

**Comment by JerichoJones** [comment]
```
CUDA Cores / Streaming Multiprocessors = Threads
Streaming Multiprocessors = Blocks
```

**Comment by JerichoJones** [comment]
---
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---
