### ISSUE TITLE
how to run as background job and also able to find logs.

### ISSUE THREAD

**Issue by cloudzhong** [fireice-uk/xmr-stak#942]
I use ubuntu 17.

I just tried use nohup ./xmr-stak &
and in nohup.out
there is no logs.

who can tell me  , what is the best way to run as service and also see the log.

**Comment by JerichoJones** [comment]
Turn on text logging in config.txt?

**Comment by cloudzhong** [comment]
Thanks, I saw output_file and daemon_mode in config.txt,
I have the answers now.

**Comment by iskyd** [comment]
If you want to see the logging from nohup you can also use flush_stdout setting it to true.
