### ISSUE TITLE
Color customization - console

### ISSUE THREAD

**Issue by Steelminer** [fireice-uk/xmr-stak#943]
Would it be possible to customize the color of the stats and other messages? 
Examples
Result rejectedwould display red or whatever color I choose from a predetermined list of colors.

Result accepted - green
CPU stats - blue
GPU stats - orange

Hopefully this gives an idea of what I'm referring to.

**Comment by psychocrypt** [comment]
This has currently a low priority. We are focusing our time first to miner
improvements those increase the stability and hash rate.

**Comment by Steelminer** [comment]
Understandable. I wouldn't expect this to be at the top on the roadmap. I appreciate the response :)
