### ISSUE TITLE
Incorrect Autoconfig for 940MX

### ISSUE THREAD

**Issue by hilga007** [fireice-uk/xmr-stak#944]
# Basic information
  - Core i7-2820HQ
  - nVidia 940MX (laptop - 384 CUDA cores) 

# Compile issues
  - Windows 10 / Compiling n/a 
 
# Issue with the execution
n/a

# AMD OpenCl issue
n/a

# Stability issue
  - Is the CPU or GPU overclocked? NO 
  - Is the Main memory of the CPU or GPU undervolted? NO 

# AutoConfig Settings - Results in 0 H/S 

"gpu_threads_conf" :
[
  // gpu: GeForce 940MX architecture: 50
  //      memory: 1697/2048 MiB
  //      smx: 3
  { "index" : 0,
    "threads" : 86, "blocks" : 9,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

# Reducing Blocks Results in 120H/s

[
  // gpu: GeForce 940MX architecture: 50
  //      memory: 1697/2048 MiB
  //      smx: 3
  { "index" : 0,
    "threads" : 86, "blocks" : 4,
    "bfactor" : 8, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by borzaka** [comment]
The blocks must be a multiple of the smx: 3, 6, 9, 12, etc.

Try to lower your threads first in the autoconfig. It is possible, that the 940MX can't produce hash in 10 sec. That is not a problem, it's normal.

**Comment by psychocrypt** [comment]
I added a PR #950 to reduce the number of threads used within a low end device.
