### ISSUE TITLE
Software is used to attack on servers

### ISSUE THREAD

**Issue by kivervinicius** [fireice-uk/xmr-stak#949]
hello, we saw that your software is being used as a form of attack on several of our servers, is there any way to block it?

**Comment by psychocrypt** [comment]
Could you please describe what you mean by attack? Please describe the
attack vector as good as possible.

**Comment by kivervinicius** [comment]
One month ago we are suffering a kind of attack (possibly back-door) on all docker containers on our server, the attacker enters our server and loads the xmr-stak renaming to another known system process. We found this repository after finding the binary. We made some attempts to block but even blocking the ip output the CPU continues with high consumption rates.

**Comment by psychocrypt** [comment]
I am right that someone got access to your systems and installed xmr-stak under a different name. This means not xmr-stak attacks your system.
In that case it not helps to block some ports. You need to remove all docker container. You do not know which back doors the attacker implemented in you system and if he/she still has access.
You can check which process produce the high load and than kill this process and if it gets restarted you can analyse how.

**Comment by kivervinicius** [comment]
Ok, we've done this process a few times, both the process of killing what is using more CPU, I thought there might be some method in preventing this from running. At least until we can identify where we are having the attack.

**Comment by psychocrypt** [comment]
The miner is a normal program and can not be blocked. If you have a clean
system you can compare the checksum of each file on both systems and found
the manilulaten.

**Comment by kivervinicius** [comment]
@psychocrypt thanks for patience!

**Comment by JokerGermany** [comment]
Do you really want to continue running a system which was compromised?
