### ISSUE TITLE
NVidia Quadro P3000 is not supported

### ISSUE THREAD

**Issue by hmageste** [fireice-uk/xmr-stak#951]
I got the following issue trying to configure my NVidia video card:
**********
Start mining: AEON
[2018-01-22 19:37:38] : NVIDIA: GPU configuration stored in file 'nvidia.txt'
[2018-01-22 19:37:38] : Starting NVIDIA GPU thread 0, no affinity.
[2018-01-22 19:37:39] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2018-01-22 19:37:39] : WARNING: backend AMD disabled.
******

I have a Nvidia Quadro P3000 with 6 GB GDDR5 running on Windows 10 and the latest Nvidia drivers installed (version: 385.41).

**Comment by psychocrypt** [comment]
Whete is the issue. From you output I can only see that one nvidia gpu is
started. Please describe the problem.

**Comment by hmageste** [comment]
These warnings seems to be looking for AMD video boards. Is that supposed to happen when I only have nvidia ones installed?

**Comment by DrStein99** [comment]
Hi.  You will get a warning for whatever you DO NOT have installed.  If no AMD boards, then you get AMD warning.  If you do not have NVIDIA installed, then a warning for that too.  If you manually compile your own binary OR download a pre-compiled version for cpu+nvidia only, then the warning goes away.

**Comment by hmageste** [comment]
Ok. Understood.
