### ISSUE TITLE
I have a mixxed rig 8 1070TI and 6 Vega 56 getting error

### ISSUE THREAD

**Issue by BitCoinJedi** [fireice-uk/xmr-stak#955]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Thread Ripper 16/32  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Windblows 10  ```
 My first issues is I'm getting a source error on the Visual c++ 2017 runtime distr. During the installation the setup stopsd and asks for a path for additional runtime.msi blah blah. Ive seen windows do this in the ancient days tbh I forgot why this happens. Any insight would be great! Have a blessed day!

**Comment by psychocrypt** [comment]
You need to provide the full error message. Is this error really a miner
compile error or do you have issues with your terminal?
