### ISSUE TITLE
Miner taking too long to start

### ISSUE THREAD

**Issue by rv-msilva1** [fireice-uk/xmr-stak#956]
I have a 8 GPU rig with 16 GPU threads in AMD.txt
The problem is: miner usually take 5 minutes to start (~20 seconds per thread)

Is there something that I can do to reduce this startup time to make coin switching faster?

# Basic information
  - Pentium G4400.
  - 6x RX 580 XFX GTS 8GB with 2 threads of 1880 intensity each.
  - 2x RX Vega 64 with 2 threads of 1932 intensity.

**Comment by JerichoJones** [comment]
Not really.
