### ISSUE TITLE
Hyperthreading: on or off?

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#957]
If xmr-stak wants to use every OTHER thread, would it be more efficient to disable hyper-threading in the BIOS - and then use the cores, instead of binding to an even -or- odd affinity?

**Comment by psychocrypt** [comment]
In our tests on will give a few hashes more.

**Comment by taisel** [comment]
It's more efficient to use hyperthreading, and pin the threads to two per physical core.

Proper HyperThreading usage  does lower the hashrate, but it improves the performance per watt greatly.

**Comment by DrStein99** [comment]
I just noticed my test computer was PINNED at like 96% CPU utilize.  I restarted, turned hyperthreading back on.  Now is comfortably running at 50%, with same hash power.  Nice work!

Do other bios settings affect? 

"c states": NO
"hardware prefetecher": YES
"adjacent line prefetech": YES
"high io performance": YES

**Comment by jgillich** [comment]
> I just noticed my test computer was PINNED at like 96% CPU utilize. I restarted, turned hyperthreading back on. Now is comfortably running at 50%, with same hash power

With HT on, 50% utilization means your CPU is fully utilized. XMR mining usually doesn't benefit from HT because each thread requires 2MB cache and no CPU has that much.

**Comment by totallyG82** [comment]
Place one thread per Core and leave HT on. CN is limited by cache size and AES throughput.
Usually there is one AES block per core which means using both of SMT/the HT-core (0,1) just would stall the performance.
