### ISSUE TITLE
Testing same pool, different machines and software

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#958]
I have different hardware here sometimes on smaller machines to test before I decide to switch the larger ones to a different company / pool.  Should I use different pool:port for EACH separate machine & xmr-stak task ?

I suspect something goes wrong when 2 of my machines try to connect to same address:port.  I just realized now, there could be issues routing the traffic back into my machines through my WAN router.

**Comment by JerichoJones** [comment]
I run multiple rigs behind a consumer router without issue.
