### ISSUE TITLE
Is there any command to restart the miner itself every 5 minutes? 

### ISSUE THREAD

**Issue by kamisama2333** [fireice-uk/xmr-stak#959]
**Basic information**

Intel Xeon E3 1230V2.
GTX 750TI × 2.

**System**
Windows 7 64bit

**Issue:**
sometimes, it just stop mining, but shows no error, it could make the computer idle all the time until you press "h" or any other keys, then it restore mining. so does this miner have command line to check itself running or  stop, or is there any command to restart the miner itself every 5 minutes?

**Comment by DrStein99** [comment]
I know the socket disconnect works, it will retry and connect. 

I was curious too.  Sometimes it looks like it is mining, but results not accepted by pool.  I check machine 1 hour later, it just reporting hash rates, and I have no idea what work it did - because there were only like 2 results accepted by pool when I press "R"

**Comment by JoKeRz42o** [comment]
@kamisama2333 You should check out TheJericoJones' script. Small tool that monitors hash rate and restarts xmr-stak [if needed]. 

[https://www.reddit.com/r/MoneroMining/comments/7fqqha/jjs_xmrstak_hashrate_monitor_and_restart_tool_v/](url)

I have it setup with all three (3) of my rigs and I swear by it. Don't have to leave the house worrying about my rigs shutting down.  

Only other thing I would suggest doing is to add his script as a "STARTUP" item (and enable power-on after power loss in BIOS). Oh and make sure to enable login screen bypass.  In case of power outtage your computer will power on again and run **"JJ's XMR-STAK HashRate Monitor and Restart Tool"** which in turn fires up xmr-stak and you're all set!

Hope this helps!
-Harry

**Comment by kamisama2333** [comment]
@JoKeRz42o Thanks, this really help!

**Comment by JerichoJones** [comment]
There is a new, more robust and feature rich version named Precious Guardian that can be found on the [subreddit](https://www.reddit.com/r/PreciousGuardian/)
