### ISSUE TITLE
Mining on Ubuntu live USB, getting memory pinned errors as well as system instability

### ISSUE THREAD

**Issue by brody3123** [fireice-uk/xmr-stak#960]
# Basic information
  - 4 x Intel Xeon E7-8867L (2.13Ghz.10Cores.20Threads,30M L3 Cache)
  - 2 x 4GB PC3-8500R Registered ECC memory dimms (8GB total)

# System
  - Ubuntu 16.04 LTS

# Stability
  - Is the CPU or GPU overclocked? **No**
  - Is the Main memory of the CPU or GPU undervolted? **No**

# Issue

I have about 90 of these systems running as we speak, each with 4 of these Xeons in them and 8GB ram. I have a few problems to address:

1. I only get about a 1200H/s mining hashrate. This number is **only** achieved by setting the config to use cpu affinity =0,2,4,6,8,10,12.....78 (i.e. only the 40 physical cores) If I add 5 logical cores to the mix, per processor (so 0,1,2,3,4,5,6,7,8,9,10,12,14,16,18 for the first processor, etc.) my hashrate doesn't increase as it should given the increased number of threads being utilized. I have 30MB cache per CPU, I should be able to at least mine with 14 threads (with 2MB as a little extra buffer) if not 15 threads per CPU. Please advise.

2. I always get a huge list of 'hwloc: memory pinned' errors when I start the miner. Is this considered normal? I have followed the steps to enable largepages to the T but to no avail. The miner still displays the errors and runs anyways. My config has the largepages setting set to 'warn'. --This brings me into my next question--

3. Being that these are live usb drives with a persistent file, and are running LTS 16.04, when they were created there was no swap file or swap partition created (since a live usb creator was used). Is the fact that there is no swap file or partition having an impact on my performance and/or causing largepages to not work properly?

4. Last but not least, after 24-48 hours of mining, the Ubuntu screen freezes. Mouse still works but no input is registered, I have to force power-off the system and reboot to get it to respond again. In my pool reporting software, it still reports that the system is mining and submitting shares, however, I find if I don't reboot every couple days, my hashrate as reported on the pool slowly drops over the course of a week.
On systems that haven't frozen at the 48 hour mark yet but likely would have if left unrestarted, I went into the monitor and the ram usage only shows about 1.5GB out of 8GB used--like when I first boot the system--leaving me to believe that I'm not running out of memory. Likewise the USB activity lights on all systems usually stay solid as they are mining, not much read-write, so they aren't being overworked. As far as my knowledge goes, pagefiles/swapfiles (whatever you want to call them) are normally just used in place of physical memory if it runs low, correct? If I'm not running out of memory and the lack of page/swap file isn't causing this instability and lack of performance, what could it be? Any solution to this freezing and/or any idea as to why my hashrate diminishes over time?

Yes, I know this is a lot of information to drop on you guys, but I also know that the more you know the better you can help me. I appreciate any help you can provide me.

**Comment by JerichoJones** [comment]
#2 is not an error.

---
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably
already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---
