### ISSUE TITLE
How to prevent / stop using CPU

### ISSUE THREAD

**Issue by GrannyCryptomaster** [fireice-uk/xmr-stak#961]
How do I stop the combined miner to mine on CPU?
CPU G3930 on Asus Prime Z270-P, 6x nVidia GPU rig, Windows 10 pro x64, XMR Stak CPU-AMD-nVidia miner, last version.
My CPU is a Celeron and outputs 32H/s on ETN mining, so it's a waste of energy and a great risk to fry it for nothing. How can I make the miner to ignore it and use only the nVidia GPUs (GTX 1060 3GB - 450H/s each)?
I understand that this combined version is more up-to-date than the dedicated nVidia version, so thats why I'm using it... Or am I wrong? Should I use only the nVidia version? Will it be updated as much as the combined version?
I'm not a programmer, just an usual user of computers, but I can edit a .bat or a .txt file if that's the case :)) Thanks!
P.S.: The Ryzen 1600 outputs 420H/s on ETN mining, it's a great cpu for mining (tested on my pc).

**Comment by DrMoropo** [comment]
You have to run it with the option --noCPU

Open a command line, change directory to the folder where you have the miner and do: 

xmr-stak.exe --noCPU

**Comment by endorxmr** [comment]
The old xmr-stak-nvidia will not be supported anymore, so using this new version is what you want.

If you don't want to use the cpu at all, you can also set your cpu.txt config to:
`"cpu_threads_conf" : null,`

That way, the CPU will be disabled regardless of any startup parameters.

**Comment by GrannyCryptomaster** [comment]
Thanks guys!

**Comment by elhigu** [comment]
Even with `"cpu_threads_conf" : null,` set in bootup miner says that, CPU mining is disabled, but still all CPU cores has 100% load. This is with hiveos.
