### ISSUE TITLE
nVidia GeForce GTX 1060 3GB miner settings for Windows

### ISSUE THREAD

**Issue by GrannyCryptomaster** [fireice-uk/xmr-stak#963]
GeForce GTX 1060 3GB - 32x27 8x100 arch:61 SMX:9
I put here the optimal miner settings for mining Monero & co. on GTX 1060 3GB, in Windows, for anyone that just started in the mining business and dosen't has the time to read and test a lot. The max threads (44) and blocks (27) are outputed by the "XMRig miner" and they are good for first start. bsleep and bfactor is what "XMR stak help" recomends for GUI systems (Windows). The optimal "threads" setting is 32 for this GPU, thanks to sergneo. I tested both, and with 6 GPU at 44 threads, I got around 2650 H/s, but with 32 threads, my hashrate jumped to 2863 H/s.
Explanations: 
-smx (multiprocessors) are 9 for this gpu.
-architecture type is 61.
-threads can be increased from the basic settings by +2, untill miner crashes. 44 is maximum for this gpu.
-blocks =SMX x 3=9 x 3=27.
-bfactor - 8 for GUI systems.
-bsleep - 100 for GUI systems.

**Comment by sergneo** [comment]
No no and no. More isn't better. The most optimal parameters for this: // gpu: GeForce GTX 1060 3GB architecture: 61 // memory: 2921/3072 MiB // smx: 9 { "index" : 0, "threads" : 32, "blocks" : 27, "bfactor" : 8, "bsleep" : 100, "affine_to_cpu" : false, "sync_mode" : 3,

**Comment by GrannyCryptomaster** [comment]
Thanks sergneo. Great hashrate jump after your tip! I updated the post.
I can mine for you some ETN or other cryptonights, for 3 days, if you send me your wallet address.

**Comment by sergneo** [comment]
Thank you and I'm glad that helped you.
ETN : etnk7KqFQaxfB4xNKodhdjisZXkkrihgyUZ6zhCbFyUT5Uj8eYs5G7Ei1VEd6VtM5BRs5rBnCDazUbEwZVCDMUYo8cFZ1gvgRk

**Comment by chicken--** [comment]
I'm getting about 50 H/s more with the default settings vs the settings that sergneo posted. I have a PNY GTX 1060 3GB

  // gpu: GeForce GTX 1060 3GB architecture: 61
  //      memory: 2490/3072 MiB
  //      smx: 9
  { "index" : 0,
    "threads" : 26, "blocks" : 27,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,

**Comment by annern55** [comment]
The absolute best I have been able to output with my gtx 1070 3GB is 210 H/S after playing with the settings for hours.. Is that decent?

**Comment by annern55** [comment]
This is with monero mining!

**Comment by GrannyCryptomaster** [comment]
@annern55 
I did't try monero, only EDL and ETN. With 1060 3GB I get 470-490 H/s, with cards from 3 brands, with Hynix memory. The GTX 1070 must have much bigger hashrate, at least 550 on stock I think... that's with ETN mining. 
As OC settings, when mining cryptonights, a super good constant/stable hashrate I got by reducing core -100, power 65, temp 83, and increasing just the mem to +400 or +500. If you get Samsung memory, you can go to +900.

**Comment by chicken--** [comment]
Does it matter what coin we are mining if it's the same algorithm? The hashrate is the same is it not?

**Comment by GrannyCryptomaster** [comment]
@chicken-- 
I tryed 6x25, but Windows becomes laggy, if you have the monitor linked to a GPU. It's more performant, but laggy in operating the computer. So 8x100 is recomended for GUI systems to reduce lag.
The 26x27 setting dosen't give me more h/s, but 32x27 does. But as long as there are not 2 cards identical, not even from the same brand, there are no general perfect settings for everyone. You can tweak the settings as long as you want, if you have the time, untill you get the absolute best for your rig.
Someone sugested blocks 32 works better. I realy don't have the time to test all the combinations, I'm happy with my hashrate output.
The quick setup method I sugested in the guide is for any beginner to get the things working quickly and with near top hashrates.

**Comment by sergneo** [comment]
@chicken-- don't know how you have the default settings give you less H / s

**Comment by annern55** [comment]
No matter  what OC setting I use it doesn't affect hashrate whatsoever!! If anything it becomes worse... And my hashrate is so awful stock too idk why.. I put them in my other computer they perform twice as good :| Very annoying

**Comment by mycoalm** [comment]
1060 3gb
{ "index" : 0,
 "threads" : 8, "blocks" : 142,
 "bfactor" : 8, "bsleep" : 100,
 "affine_to_cpu" : false, "sync_mode" : 3,
},
Getting 458 h/s.  

MSI Afterburner 116 power limit, 92 Temp, 150 core clock, 660 memory, fan 50
539 h/s
Monero

**Comment by sergneo** [comment]
Maximum speed Monero_V8
 // gpu: GeForce GTX 1060 3GB architecture: 61
    "threads" : 8, "blocks" : 144,
    "bfactor" : 8, "bsleep" :  100,

**Comment by Spudz76** [comment]
Similarly, GTX970 seems to enjoy the 16xSMX instead of 8x (latest driver / CUDA10.0)
But at half the threads  - My card has 13 SMX
```
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3795/4096 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 4, "blocks" : 208,
    "bfactor" : 8, "bsleep" : 100,
    "affine_to_cpu" : false, "sync_mode" : 0,
    "mem_mode" : 1,
  },
```
gets around 435H/s which is on par with old v7 perf which IIRC was about 440H/s

Might need to adjust the autoconfig math so it uses the 16x and then scale threads around until it is smooth.  8x is good but 16x is (seems like always?) better

**Comment by Spudz76** [comment]
Oh and above 435H/s is with 100W power limit ("59%") +72 core clock +572 mem clock
![image](https://user-images.githubusercontent.com/2391234/47760567-83ca6380-dc7a-11e8-955e-da56020c8968.png)

**Comment by Simaex** [comment]
@Spudz76 do you notice lower CPU hashrate with the better GTX970 settings? I've got the same rate for GPU but at the same moment CPU i7-3770 decrease rate from 280 to 265.

**Comment by Spudz76** [comment]
@Simaex likely but difficult to tell, I have about 50 open tabs in browser on this daily driver machine so CPU is all over the place anyway.  Hashrate totals match around what I remember from v7 and similar usage-while-mining so I'm pretty happy with it.  i7-2600 (sandybridge) four threads about 17.8H/s each very uneven 13.5-20H spread

Being a never-reboot-warrior, I have not had an opportunity to test with nothing else running.  Uptime 53 days
