### ISSUE TITLE
Set single pool from command line

### ISSUE THREAD

**Issue by belikoviv** [fireice-uk/xmr-stak#965]
I'm try to set pool/user/pass from command line, and other parameters from config file, but miner complains that config parameter `pool_list` must be present in config and must not be empty.

Is it possible to set pool only from command line and other parameters (such as `verbose_level` and `httpd_port`) from config file?

**Comment by fireice-uk** [comment]
Hi. Can you use the template properly? We will need error output, your config.txt, and `xmr-stak -V` output.
