### ISSUE TITLE
AMD Invalid Result - GPU0

### ISSUE THREAD

**Issue by ChartSloth** [fireice-uk/xmr-stak#967]
Please provide as much as possible information to reproduce the issue.

GPU0 finds "AMD Invalid Result." It doesn't seem to be hardware related. As soon as the 1st AMD Invalid Result is found... It gets worse on that GPU. THe % of Invalid Results gets higher the longer it goes. 

# Basic information
  - N/A.
  - 8x XFX RX570 4GB

  - Do you compiled the miner by our own?

Yes, but I had the same issues on public version.

# Stability issue
  - Is the CPU or GPU overclocked?
Yes. I seem to be getting them regardless.

  - Is the Main memory of the CPU or GPU undervolted?
No.

**Comment by JerichoJones** [comment]
Almost certainly overclocked too high or you toasted the card.

**Comment by ChartSloth** [comment]
@JerichoJones card is fine. must be OC issue.

**Comment by bruslie** [comment]
@ChartSloth any news ? you fixt the problem ?
