### ISSUE TITLE
why you dont use openCL (1,2) both for nvidia and amd GPU ?

### ISSUE THREAD

**Issue by aotto1968** [fireice-uk/xmr-stak#968]

**Comment by totallyG82** [comment]
TDLR; nVidia cards may use openCl but performce worse than CUDA.

I would like to see a more "general" opencl 1.2 support for older AMD and Intel GPUs. 
However for nVidia CUDA performance seems to be much better than openCl for some reason.

**Comment by aotto1968** [comment]
this is a open question ist nVidia performs better with CUDA than openCL…
I thought… you can just reuse your AMD code and run it on NVIDIA… this whould be the prrof… or not.

**Comment by psychocrypt** [comment]
You can use the opencl part for nvidia. we added the code that it is fully
compatible. The reason to use CUDA is that it is much easier to use new
features for upcomming gpus with CUDA than with opencl.
In CUDA we have much more options to tweak the miner.
If you like to use your nvidia gpus with OpenCL disable CUDA and set in
amd.txt the platform index to your CUDA OpenCL and configure your gpus by
hand.

**Comment by aotto1968** [comment]
thank you for the information… if I read your answer right… the AMD prefered "openCL" is less competive than the NVIDIA prefered "CUDA"… 

other question… on a grafics chip… there is much mure than the CUDA kernel… does you planing to use the "other parts" of the CPU as well?

**Comment by aotto1968** [comment]
I compiled it vor my "old" nvidia card… but… its TOOO old (GeForce 210)… fails at…

> [2018-01-29 22:06:20] : Start mining: MONERO
> [2018-01-29 22:06:20] : Compiling code and initializing GPUs. This will take a while...
> [2018-01-29 22:06:20] : Device 0 work size 8 / 64.
> [2018-01-29 22:06:20] : Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create 0 hash scratchpads buffer.

what I found out… with openCL you have a lot of hard-wired "AMD" text inside… so… an config option would be nice

→MY TASK: going to buy a REAL Nvidia device for testing "1050 Ti"…

MY GPU
`# /usr/bin/nvidia-smi -q

==============NVSMI LOG==============

Timestamp                           : Mon Jan 29 22:17:31 2018
Driver Version                      : 340.104

Attached GPUs                       : 1
GPU 0000:01:00.0
    Product Name                    : GeForce 210
    Product Brand                   : GeForce
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : Disabled
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-97c3345a-dfa0-0eae-6309-2fe142baa794
    Minor Number                    : 0
    VBIOS Version                   : 70.18.5F.00.00
    MultiGPU Board                  : N/A
    Board ID                        : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x0A6510DE
        Bus Id                      : 0000:01:00.0
        Sub System Id               : 0x00000000
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 511 MiB
        Used                        : 362 MiB
        Free                        : 149 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
        Encoder                     : N/A
        Decoder                     : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 35 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Compute Processes               : N/A
`

**Comment by psychocrypt** [comment]
reduce the intensity to 32 and increase it slowly

**Comment by aotto1968** [comment]
this is the "origonal" amd.txt

```
"gpu_threads_conf" : [
  // gpu: GeForce 210 memory:0
  // compute units: 2
  { "index" : 0,
    "intensity" : 0, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  },

],
```

**Comment by psychocrypt** [comment]
There was no memory detected. But never the less you can try to set
intensity to 32.

**Comment by aotto1968** [comment]
it was doing something… but "eat" all my memory. and I have to reboot… so . itseems… my "card" is not really sufficent… saw a number of "12 H/s"…

I have to wait for my new card.

**Comment by aotto1968** [comment]
have more info:
1. GeForce 210 using the GT218 chip supporting only OpenCL 1.1

> From: https://en.wikipedia.org/wiki/GeForce_200_series

2. uninstall opensuse "openCL" header and instll original from:

>  From: https://github.com/KhronosGroup/OpenCL-Headers

3. set variable:

> -DOpenCL_INCLUDE_DIR=~XXX~/OpenCL-Headers/opencl11

4. cmake…
```
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "1.1") 
```
4. build fails with…

```
Scanning dependencies of target xmrstak_opencl_backend
[ 82%] Building CXX object CMakeFiles/xmr-stak.dir/xmrstak/cli/cli-miner.cpp.o
[ 93%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/jconf.cpp.o
[ 93%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o
[ 93%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/minethd.cpp.o
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp: In function ‘const char* err_to_str(cl_int)’:
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:87:7: error: ‘CL_COMPILE_PROGRAM_FAILURE’ was not declared in this scope
  case CL_COMPILE_PROGRAM_FAILURE:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:89:7: error: ‘CL_LINKER_NOT_AVAILABLE’ was not declared in this scope
  case CL_LINKER_NOT_AVAILABLE:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:91:7: error: ‘CL_LINK_PROGRAM_FAILURE’ was not declared in this scope
  case CL_LINK_PROGRAM_FAILURE:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:93:7: error: ‘CL_DEVICE_PARTITION_FAILED’ was not declared in this scope
  case CL_DEVICE_PARTITION_FAILED:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:95:7: error: ‘CL_KERNEL_ARG_INFO_NOT_AVAILABLE’ was not declared in this scope
  case CL_KERNEL_ARG_INFO_NOT_AVAILABLE:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:167:7: error: ‘CL_INVALID_IMAGE_DESCRIPTOR’ was not declared in this scope
  case CL_INVALID_IMAGE_DESCRIPTOR:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:169:7: error: ‘CL_INVALID_COMPILER_OPTIONS’ was not declared in this scope
  case CL_INVALID_COMPILER_OPTIONS:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:171:7: error: ‘CL_INVALID_LINKER_OPTIONS’ was not declared in this scope
  case CL_INVALID_LINKER_OPTIONS:
       ^
~XXX~/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:173:7: error: ‘CL_INVALID_DEVICE_PARTITION_COUNT’ was not declared in this scope
  case CL_INVALID_DEVICE_PARTITION_COUNT:
       ^
CMakeFiles/xmrstak_opencl_backend.dir/build.make:62: recipe for target 'CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o' failed
make[2]: *** [CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o] Error 1
```

**Comment by aotto1968** [comment]
the compile error above are reletet to missing DEFS in openCL 1.1 → fixed it

the "0" mem problem in amd.txt

```
// keep 128MiB memory free (value is randomly chosen)
size_t availableMem = ctx.freeMem - (128u * byteToMiB);
```
availableMem = 134217728 - 128 * 1024 * 1024 = 0 !!

**Comment by psychocrypt** [comment]
#1112 will add a new flag to enable non AMD OpenCl devices.

**Comment by aotto1968** [comment]
I successful run "nvidia" with the openCL "driver"… and nvidia alone with the "cuda" driver… it seems that cuda has more "fine-tuning" capabilities… but if you have a rack mixed with "nvidia" and "amd" devices… the openCL might be a good choice :-)
