### ISSUE TITLE
inconsistent xmr-stak CPU hashrate

### ISSUE THREAD

**Issue by zanfr** [fireice-uk/xmr-stak#975]
I have noticed an irritating phenomenon on the CPU side of xmr-stak.

The CPU hashrate is inconsistent from one run to the next. One time I may get a total of nearly ~320 with each core (max ~50C), and then next run I can get all cores but a couple on ~30h/s, down to ~260 total (same temperature, same clock speed reached).

I tried right after a fresh boot, right a fresh full power off (PSU off too), after using firefox, with or without other programs open...I disabled realtime protection for windows defender, power management etc... It is still a lottery no matter what.

Once xmr-stak is started and runs at its "cruising speed" little influences it, I can start firefox, thunderbird (what I'd consider near idle loads most of the time), the hashrate and temperature (~50C max) remain stable.

And ideas ?

I run an i7 8700 (without turbo and without MCE, due to spiking up to 90-100C during Turbo...sigh) with 16Gb on Win10 with the following configuration:

```
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 }, 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 }, 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 }, 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 }, 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 }, 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
```

I did try playing with more or less threads, low_power_mode etc... nope... I only manage to reach the ~320h/s once in say 1/10 runs, if I'm lucky.

EDIT:
I suspect this has to do with memory allocation and/or cache use...
Right after posting my initial message, I started xmr-stak again, this time reaching the top rate of ~330, whereas 10mn previous I was around 260.

ADDENDUM:
I have since asked around and found out that 8700K users (with turbo mode on, doesn't seem to matter what frequency the CPU is actually running at) experience similar random hashrate behavior. I have also reenabled Turbo and played around with power settings on my 8700 to rule clock speed management out with similar random behavior. Something that may help is starting xmr-stak two instances then closing both and starting one (which usually reaches it's normal top CPU hashrate).
This is increases my suspicions that this has something to do with the newer Intel chips cache management.

**Comment by Simaex** [comment]
1. Do you have huge pages enabled? 
2. 6 threads are too much for 12M cache that 8700k featured. Each thread is using 2M, so you have all 12M fully utilised and a lot of time wasted while discarding cache for OS tasks. You may get better results with 5 threads.

**Comment by zanfr** [comment]
I have Win10 Home so I can't access gpedit, however, I have "use_slow_memory" : "never" set in config.txt and I do get hwloc: memory pinned when starting.

Using 5 threads instead of 6 gives 300h/s (instead of 320) but indeed I seem to able to hit that rate more reliably.
