### ISSUE TITLE
Slow Performance low_power_mode Ryzen

### ISSUE THREAD

**Issue by maxisvk** [fireice-uk/xmr-stak#976]
I do some test with Ryzen 1300x and found very slow performance with 1 Thread and low_power_mode >= 2 contrary to what happens with Intel where 
1 Thread + low_power_mode 2 gain ~ 50% or more vs 1 Thread + low_power_mode = 1
and
1 Thread +low_power_mode 3 gain ~ 15/20% over 1 Thread + low_power_mode = 2

test with low_power_mode = 1

{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 0 },
75 h/s

{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 1 },
66+67 = 133 h/s

{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 1 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 2 },
63+64+70 = 197 h/s
	
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 1 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 2 },
{ "low_power_mode" : 1, "no_prefetch" : true, "affine_to_cpu" : 3 },
57+63+64+66 = 250 h/s

test with low_power_mode = 2 with 1 Thread ( no change affine_to_cpu 0 or 1 or 2 or 3 or prefetch )

{ "low_power_mode" : 2, "no_prefetch" : true, "affine_to_cpu" : 0 }
90 h/s  ( only 15% gain )

test with low_power_mode = 3 with 1 Thread ( no change affine_to_cpu 0 or 1 or 2 or 3 or prefetch )

{ "low_power_mode" : 3, "no_prefetch" : true, "affine_to_cpu" : 0 },
only 54 h/s 

test with low_power_mode = 3 with 1 Thread ( no change affine_to_cpu 0 or 1 or 2 or 3 or prefetch )

{ "low_power_mode" : 4, "no_prefetch" : true, "affine_to_cpu" : 0 },
only 50 h/s

instead test with low_power_mode = 2 with 2 Thread 
{ "low_power_mode" : 2, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : 2, "no_prefetch" : true, "affine_to_cpu" : 2 },
90+90 = 180 h/s

maybe, optimizations are needed for Ryzen / Intel for low_power_mode > 2 ?
( just for stats same results with new XmrigCC with multi hash > 2 )

**Comment by totallyG82** [comment]
Don't use Low Power mode with Ryzen. This should only be used for Intel Xeon and similar devices with very big cache sizes 25-48MB. My 1700 does 800H/s (8 threads lp:false)

Normal mode: Threads = Cache/2 (MB) = 4 threads on the 1300x (lp false)
Low power mode: Threads = Cache(2*2n) (MB where n is lowpower setting) (if 1300x core 0 and 2 lp:2)
