### ISSUE TITLE
Suspicious compare: (4) Xeon E7 96mb cache: 1350 h/s -vs- (2) Xeon E5 2650 40mb cache: 950 h/s

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#979]
According to my calculations, my setup #2 is not performing to the same speed as #1, considering the hardware is just about double the statistics.  There is a 400 h/s difference, with over 2x as much cache, and 2 cpu's, with over 2x as many threads. 

#1 (2) E5-2670 40MB cache, 20 threads: 930 h/s- 950 h/s (windows 8.1, browser running, other stuff)
#2 (4) E7 4850 96MB cache, 48 threads: 1,366 h/s (linux and nothing else running)

Please help me to troubleshoot, the procedures, advice if possible.
-------
Please provide as much as possible information to reproduce the issue.

# Basic information
Setup #1:
(2) E5 2670 
40mb L3 cache
2.6 GHz - 3.3 ghz  (2.99 GHz report by task manager)
32gb ram, ZERO page size set (disabled in system/advanced hardware)

Setup #2:
(4) E7 4850 
96mb L3 cache
2.0 - 2.4 GHz (unconfirmed official reading report by linux)
32gb ram

# Compile issues
Setup #1: Xmr-Stak-Win64 binary download, windows 8.1
Setup #2: Ubuntu Server 16.04, manual git clone, compile xmr-stak from here

# Issue with the execution
setup #1: no, I download binary.  This setup hashrate is consistant with other tested hash rates from other softwares, used as my control test

Setup #2: git clone, compile with no issues to report.  This is the comparison test to setup #1.  I have not tested other softwares and operating systems yet.

# AMD OpenCl issue
No amd cards on either setup

# Stability issue
 no overclocking or otherwise hacking.

**Comment by psychocrypt** [comment]
The clock speed of setup 2 is slower and therefore also the cashe. You can
not compare two different cpus. Overclock setup 2 to the same clock and
than compare it.

**Comment by nicholasfeigen** [comment]
The e7 processors you're using are built on the Nehalem-C/Westmere Architecture whereas the e5 processors you're trying to compare them to are use the IvyBridge architecture.  I've noticed similar performance discrepancies between my Dual 6-core x5680 rigs (I have two rigs with those processors) and my Dell r320 with a single e5-2448Lv2.  I like to multiply the cores and ghz of a given processor to give it a number I can compare with others, so I was thinking:

2x X5680: 3.3ghz(nonturbo)•12cores= 39.6ghz•cores
and 
1x e5 2448Lv2: 1.8ghz(nonturbo)•10cores=18ghz•cores

You'd expect the performance to be roughly half, but the two setups perform almost the same at ~1450h/s in AEON!!!   

There is a massive performance benefit to the newer archetecture!

**Comment by DrStein99** [comment]
On the windows machine (e5 2670), I just enable speed-step bios setting.  I check task manager and can see it will see the CPU run at 2.9 ghz.  When I set bios setting off, is at 2.4 ghz.  If I recall correctly, this had a 40% improvement in speed, which is a big difference from 680 h/s to 960 h/s.  I did not install any over clocking software or do any modifications.  According to what I have read, the turbo automatically engages and manages itself.  I use this same machine for my 3D cad drawing, and it just runs at 2.9 ghz all day since I bought it about 2 years ago, which puts a more demanding load than xmr-stak.

I do the same procedure in the BIOS. on the LINUX machine (E7 4850).  I have the turbo enabled in BIOS. 
 According to LINUX: "turbostat"- my "bzy_mhz" is only 2133 on a few threads, 2000 on all the rest.  "tsc_mhz" reporting "1995" on all threads.  

I do not know what else I should be configuring to enable that turbo frequency above 2.0 ghz to drive at the 2.4 ghz that the intel-ark site explains, that the cpu's can comfortably run at.  35% of 1350 h/s is another 500 h/s, which is ALL the power of my 2 other lame desktop test machines combined, that I am probably losing right now.

I would like to figure this out, I prefer to run linux on my machines instead of Windows - but if it means a sacrifice in production.

**Comment by mvpel** [comment]
How warm are your processors getting?

**Comment by DrStein99** [comment]
sensors:

```
nouveau-pci-0e00
Adapter: PCI adapter
fan1:           0 RPM
temp1:        +53.0°C  (high = +95.0°C, hyst =  +3.0°C)
                       (crit = +115.0°C, hyst =  +2.0°C)
                       (emerg = +130.0°C, hyst = +10.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +57.0°C  (high = +86.0°C, crit = +94.0°C)
Core 1:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 2:       +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 8:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 9:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 16:      +58.0°C  (high = +86.0°C, crit = +94.0°C)
Core 17:      +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 18:      +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 24:      +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 25:      +53.0°C  (high = +86.0°C, crit = +94.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +51.0°C  (high = +86.0°C, crit = +94.0°C)
Core 1:       +54.0°C  (high = +86.0°C, crit = +94.0°C)
Core 2:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 8:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 9:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 16:      +53.0°C  (high = +86.0°C, crit = +94.0°C)
Core 17:      +54.0°C  (high = +86.0°C, crit = +94.0°C)
Core 18:      +57.0°C  (high = +86.0°C, crit = +94.0°C)
Core 24:      +57.0°C  (high = +86.0°C, crit = +94.0°C)
Core 25:      +55.0°C  (high = +86.0°C, crit = +94.0°C)

coretemp-isa-0002
Adapter: ISA adapter
Core 0:       +44.0°C  (high = +86.0°C, crit = +94.0°C)
Core 1:       +53.0°C  (high = +86.0°C, crit = +94.0°C)
Core 2:       +54.0°C  (high = +86.0°C, crit = +94.0°C)
Core 8:       +52.0°C  (high = +86.0°C, crit = +94.0°C)
Core 9:       +54.0°C  (high = +86.0°C, crit = +94.0°C)
Core 16:      +53.0°C  (high = +86.0°C, crit = +94.0°C)
Core 17:      +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 18:      +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 24:      +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 25:      +53.0°C  (high = +86.0°C, crit = +94.0°C)

coretemp-isa-0003
Adapter: ISA adapter
Core 0:       +60.0°C  (high = +86.0°C, crit = +94.0°C)
Core 1:       +55.0°C  (high = +86.0°C, crit = +94.0°C)
Core 2:       +59.0°C  (high = +86.0°C, crit = +94.0°C)
Core 8:       +59.0°C  (high = +86.0°C, crit = +94.0°C)
Core 9:       +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 16:      +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 17:      +56.0°C  (high = +86.0°C, crit = +94.0°C)
Core 18:      +60.0°C  (high = +86.0°C, crit = +94.0°C)
Core 24:      +57.0°C  (high = +86.0°C, crit = +94.0°C)
Core 25:      +55.0°C  (high = +86.0°C, crit = +94.0°C)


```

**Comment by DrStein99** [comment]
I do not believe the INTEL speed-step (turbo, cpu-frequency governer, or whatever the linux equivilant to windows c-states / turbo stepping) modules are loaded by default.  At least it seems the case with my Ubuntu 16.04 server kernal.  I think these are set to the default safest SLOW possible (since it seems most people want to turn their computers on so they can sit idle and do nothing).

**Comment by OverActiveBladderSystem** [comment]
I know in multi-cpu environment some software has trouble with the numa nodes, have you tried running a separate miner for each cpu, basically run 4 copies one for each CPU to see if you can localize the impact of the program to each specific CPU rather than the system trying to operate the program on one numa node, then crossing over to another node then another node and you're slowing things down simply because its not sticking to a single cpu to run everything? on opterons the problem is amplified even more since individual cpu's can have multiple numa nodes and cross over the fabric to communicate slowing down programs that run faster when you isolate them to a single numa node...

**Comment by DrStein99** [comment]
That is good advice, thank you.  Your right - when I simplify the whole machine down to 1 CPU or 1 thread, and work my way up - is a whole lot easier to troubleshoot 4 cpu's and 80 threads.  

This machine is like dealing with the combined resources of 4 computers.
