### ISSUE TITLE
Share your config for AMD FX 4300/6300/8320e CPUs. How can I improve performance?

### ISSUE THREAD

**Issue by krll-k** [fireice-uk/xmr-stak#980]
I have three processors amd:
- FX 4300;
- FX 6300;
- FX 8320e.

Helpful information:
- Windows 10;
- MSI 970a-g43 motnerboard.

cpu.txt:
<pre>"cpu_threads_conf" :
[
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 }
],
</pre>
![image](https://user-images.githubusercontent.com/2174805/35422088-e680fea6-0257-11e8-96c4-d18431cef0a2.png)

Each stone gives about **50 hashes/sec.** from one core. This is normal?

**Comment by krll-k** [comment]
I found from http://monerobenchmarks.info/:
- 180 h / s to 4300@3.8 in the form of 3 streams;
- 275h / s through 6300@3.5 in the form of 5 threads (without 6);
- 300h / s through 6300@4.4 in the form of 5 flows;
- 470h / s through 8320E@4.5 in the form of 5 flows (core 1 and 0 with low power mode);
- 395h / s through 8320E@4.0 in the form of 5 streams (kernel 0 with low power mode);

**Comment by krll-k** [comment]
Who ever put the experiments?

**Comment by Jaydaar** [comment]
I used an i7-3610QM and got similar results.

**Comment by krll-k** [comment]
I want to continue my experiments, and subsequently share the results. In my view series amd fx is an most profitable stone. Correct me if I'm wrong. Socket Am3+ the most available variant for mining. For example motherboard msi 970a-g43 have 4 pci-e slots, or gigabyte ga-970a-ds3p have 5 slots. Price is about $50-60. First i can connect graphics cards plus a stone with low price. Later replace such as athlon for $5 (which brings nothing) to fx for $30-100 (which will pay for itself after a few months). I from russia, my electric power is cheap, about $0.02-0.01 for 1kW/hour. At the moment i have 33 pieces rx 570, and it seven rigs. My goal $10 000 per one month

**Comment by TheBulitt** [comment]
I have a standard FX-8320 3.5Ghz and this is the config I use:

> "cpu_threads_conf" :
> [
>     { "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
>     { "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 7 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 5 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
>     { "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
> 
> ],

The shared L3/L2 cache system on the FX processor can be slightly more efficient than just putting one thread per 2MB of L3 cache as is the "standard" config.

Eventually hopefully we can set the low-power threads affinity to just the "slave" (even numbered) cores to really free up the single threads to use a full 2MB of L3 cache each as well as sharing the L2 better.

**Comment by krll-k** [comment]
why two identical line? @TheBulitt 
```
{ "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
{ "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
```
and

``` 
"cpu_threads_conf" :
[
	{ "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
],
```
for 4300 such a config?

**Comment by krll-k** [comment]
![image](https://user-images.githubusercontent.com/2174805/35490753-ea1aac3a-04b2-11e8-8b15-ae95ed017521.png)
```
"cpu_threads_conf" :
[
	{ "low_power_mode" : true, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 3 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 1 },
],
```
