### ISSUE TITLE
CUDA_CORE compile error

### ISSUE THREAD

**Issue by eXellenz** [fireice-uk/xmr-stak#984]
i build xmrstak with VC2017
**1. when compile** cuda_core.cu with VC2017 v14.0+CUDA8 nvcc i get:

> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
> cuda_core.cu
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(320): error C2146: syntax error: missing ';' before identifier 'grid'
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(364): note: see reference to function template instantiation 'void cryptonight_core_gpu_hash<524288,2097136,19>(nvid_ctx *)' being compiled
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(320): warning C4551: function call missing argument list
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(320): error C2059: syntax error: '>'
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(329): error C2146: syntax error: missing ';' before identifier 'grid'
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(329): warning C4551: function call missing argument list
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(329): error C2059: syntax error: '>'
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(337): error C2146: syntax error: missing ';' before identifier 'grid'
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(337): warning C4551: function call missing argument list
> xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(337): error C2059: syntax error: '>'

I assume that the error in the syntax <<< grid, block8 >>>
**2. when linking** obj i get error:

> minethd.obj : error LNK2005: xmrstak_start_backend already defined in minethd.obj

I assume that func xmrstak_start_backend defined 2 times in amd\minethd.cpp and nvidia\minethd.cpp

**Comment by psychocrypt** [comment]
CUDA 6 is not supported. Do you mean cuda8?

**Comment by eXellenz** [comment]
sorry. of course 8

**Comment by eXellenz** [comment]
@psychocrypt 
any solve?
mey be any more compatible syntax instead of <<< *,* >>>?
and for func  xmrstak_start_backend may be need define for each gpu of its own func, example amd_xmrstak_start_backend and nv_xmrstak_start_backend?

**Comment by psychocrypt** [comment]
please try the latest dev branch and check the documentation updates for Visual Studio 2017

**Comment by eXellenz** [comment]
i use latest Build Tools for Visual Studio 2017
compile project from commandline. i dont using cmake and vs ide.
i listing documentation updates for Visual Studio 2017 and dont see anything what help me.
i can get help from you? how to enable support for such syntax in the compiler, or get a link to a document that describes this syntax.

**Comment by JerichoJones** [comment]
Out of the scope of Github support.

**Comment by eXellenz** [comment]
test

**Comment by psychocrypt** [comment]
please download the code again and try it again withou changing any lines.
also do not change the donation. The error looks like a changes line
somewhere.
If this not help post all output and commands used for the compile

**Comment by eXellenz** [comment]
cryptonight_core_gpu_hash need set to external "C"

**Comment by psychocrypt** [comment]
why? should it external C

**Comment by eXellenz** [comment]
because <<< *,* >>> its cuda simantic

**Comment by psychocrypt** [comment]
but cuda supports c++ therefore there should be no need. I also compiled
the last release with cuda8 and VisualStudio v140 without any issues. Du
you use the dev or master branch?

**Comment by eXellenz** [comment]
i use src from [release](https://github.com/fireice-uk/xmr-stak/archive/v2.2.0.zip)
use CUDA8 SDK and VC2015v14 build tool.

**Comment by wangheng673** [comment]
i also get this error!

1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.0.targets(707,9): error MSB3722: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" --use-local-env --cl-version 2017 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o x64\Debug\cuda_main.cu.obj "D:\B-WorkSpace\CLionWorkSpace\cuda2017_test\cuda2017_test\cuda_main.cu"”已退出，返回代码为 5。请验证您是否拥有运行此命令的足够权限。
1>已完成生成项目“cuda2017_test.vcxproj”的操作 - 失败。
