### ISSUE TITLE
Very low Ryzen 1700 h/s under ubuntu

### ISSUE THREAD

**Issue by rumham215** [fireice-uk/xmr-stak#986]
I upgraded from a 1300x to a 1700 only for the 1700 to have the same single thread h/s as my 1300x. Now im thinking for some reason my system is limited at this h/s because even the 1300x would be considered slow with 27h/s on a single thread.

My GPU's are doing fine. I have hugepages and proper limits set. What else could it be? Ram is ddr4 8gb 2400. Thanks!

	HASHRATE REPORT - CPU
	| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
	|  0 |   27.5 |   27.4 |   (na) |  1 |   27.6 |   27.6 |   (na) |
	|  2 |   27.6 |   27.6 |   (na) |  3 |   27.6 |   27.6 |   (na) |
	|  4 |   27.8 |   27.7 |   (na) |  5 |   27.8 |   27.8 |   (na) |
	|  6 |   27.8 |   27.8 |   (na) |  7 |   27.8 |   27.7 |   (na) |
	-----------------------------------------------------

    4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

	AnonHugePages:     40960 kB
	HugePages_Total:     128
	HugePages_Free:      118
	HugePages_Rsvd:        0
	HugePages_Surp:        0
	Hugepagesize:       2048 kB

	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 12 },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 14 },

**Comment by android-dep** [comment]
that's a good hash rate for a CPU, given the fact that CPUs aren't the best thing to use to mine with in the first place and that xmr-stak isn't primarily a CPU miner.

**Comment by JerichoJones** [comment]
Set no_prefetch" : true,

I get over 600H/s

**Comment by rumham215** [comment]
@android-dep Plenty of reports of people getting 500+ on the ryzen 1700. I just installed ubuntu 17 and was able to get 516 h/s

**Comment by rumham215** [comment]
@JerichoJones i just did that but it even dipped 2h/s. You have the 1700 or 1700x? any OC?

**Comment by borzaka** [comment]
I have 1700x @3.8GHz, and I'am getting a little more than 600 h/s. Windows 10 64 bit.

`cpu.txt`
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
],
```

**Comment by rumham215** [comment]
just want to post an update.  i couldnt get ubuntu 16 LTS to hash more than 22h/s per thread under any circumstances including updating kernel to 4.13.  so i changed my os to Ubuntu 17 and was able to get 516 and then ~565 with a slight overclock.
