### ISSUE TITLE
Setting Difficulty

### ISSUE THREAD

**Issue by STRATZ-Ken** [fireice-uk/xmr-stak#988]
Is it not possible to set the difficulty with the current miner version?  I tried following the pool suggestions of putting a + in the address, but then I get a JSON Parse error.

**Comment by STRATZ-Ken** [comment]
So normally a user can force a difficulty by putting a period between the address and the difficulty.  One of my Sumo pools requests a + between the address and the difficulty.  xmr-stax cannot support this and a JSON error occurs.

https://sumokoin.hashvault.pro/en/#!/dashboard Is the pool

**Comment by jgillich** [comment]
Works fine for me. Make sure the `+` is inside the quote, like:

    "wallet_address": "wallet+1234",

**Comment by fireice-uk** [comment]
@STRATZ-Ken Nope, xmr stak will support pretty much anything that's valid json for the login. Please use the guided setup.

**Comment by totallyG82** [comment]
It is likely you have introduced a whitespace or similar in your json config.
Or uses any setting not allowed by the pool.
Try to start out with a fresh config and add the diff manually.
I have used + . etc for fixed diff without any problems.

**Comment by DrStein99** [comment]
So far the pools I have used EXCEPT Nicehash all allow me to change my own difficulty by adding it to the wallet parameter.

I think the difficulty is part of the parameter that makes the whole algorithm work.  I've been trying to research and figure out how to break down a higher difficulty between 2 processes, then merge the results back to the pool as a single entity.  This is just a theoretical idea, will take me some time to develop that.  If I understand correctly, this is what happens to the process threads internally when the job comes in, the code splits it between it's threads.  My idea was to split the job between rigs to treat them as threads.

**Comment by JerichoJones** [comment]
@DrStein99 XMR-NODE-PROXY

**Comment by DrStein99** [comment]
does xmr-node-proxy work with nicehash?

**Comment by bobbieltd** [comment]
@DrStein99 No, xmr-node-proxy doesn’t work with NiceHash
