### ISSUE TITLE
Linux prebuild binaries nowhere to be found

### ISSUE THREAD

**Issue by Extarys** [fireice-uk/xmr-stak#990]
According to [this page](https://github.com/fireice-uk/xmr-stak/blob/master/doc/Linux_deployment.md), a file named **xmr-stak-portbin-linux.tar.gz** is suppose to be present in the [latest release](https://github.com/fireice-uk/xmr-stak/releases/tag/v2.2.0) page, but it is nowhere to be found.

Is it because it wasn't precompiled yet from the 2.2.0 version?
I'd like it since I'll put it on my USB stick.

Thanks!

**Comment by minerbird** [comment]
Hey, it says `This is an experimental feature we reserve the right to remove the binary if we get too many issues.`
I guess you can [compile it](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md) and then put it on a stick?

**Comment by Extarys** [comment]
Hey it says there that there is a file - they then should delete it if they had "too many issues".
