### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by flarecurrency** [fireice-uk/xmr-stak#993]
Missing a file and i'm compiling it on ubuntu linux 16.04 and I got all the software needed to compile

make[2]: *** No rule to make target '/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'bin/libxmrstak_opencl_backend.so'.  Stop.
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/xmrstak_opencl_backend.dir/all' failed

**Comment by minerbird** [comment]
Check out this issue https://github.com/fireice-uk/xmr-stak-amd/issues/182 and read post by @csinko.

>Run 
$ cd $AMDAPPSDKROOT/lib/x86_64
$ sudo ln -sf sdk/libOpenCL.so.1 libOpenCL.so
You do not need to reboot

**Comment by flarecurrency** [comment]
Thankyou very much it works
