### ISSUE TITLE
How to set an option similar to 'gpu-threads' in sgminer-gm?

### ISSUE THREAD

**Issue by alextrezvy** [fireice-uk/xmr-stak#994]
# Basic information
  RX550

It gives only 280 H/s, while there are claims (see monerobenchmark.info) the card can give 460 H/s with 2 threads per GPU. I've tried an option 'threads' in 'amd.txt', but it was ignored.

**Comment by JerichoJones** [comment]
LOL... sgminer?
I use two threads on my (FLASHED) 550s and get that 460H/s.
You are doing something wrong (besides the name of the miner).

**Comment by alextrezvy** [comment]
**How** do you activate 2 threads?  My current config 'amd.txt' gives only 280 H/s:
 { "index" : 2,
    "intensity" : 410, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : true
  }

**Comment by psychocrypt** [comment]
JJ could you please post you config for him.

**Comment by JerichoJones** [comment]
@psychocrypt Only for you sir do I expose muh secret sauce. ;)


"gpu_threads_conf" : [
  // gpu: gfx804 memory:1216  
  // compute units: 8  
  { "index" : 0,
    "intensity" : 432, "worksize" : 8,
    "affine_to_cpu" : 3, "strided_index" : true
  },
  // gpu: gfx804 memory:1216
  // compute units: 8
  { "index" : 0,
    "intensity" : 424, "worksize" : 8,
    "affine_to_cpu" : 3, "strided_index" : true
  },
],

**Comment by alextrezvy** [comment]
Thanx, I'll continue to tweak stak.
