### ISSUE TITLE
Question about intensity in AMD backend

### ISSUE THREAD

**Issue by jgillich** [fireice-uk/xmr-stak#998]
While reading through the AMD GPU code, I've noticed the following:

* [Intensity is rounded to a multiple of worksize](https://github.com/fireice-uk/xmr-stak/blob/30888a31368d6d1e2f459e611b634df39cbcc857/xmrstak/backend/amd/amd_gpu/gpu.cpp#L870)
* [Nonce is incremented by the original size of intensity, not the rounded one](https://github.com/fireice-uk/xmr-stak/blob/30888a31368d6d1e2f459e611b634df39cbcc857/xmrstak/backend/amd/amd_gpu/gpu.cpp#L981)

Doesn't this mean that some nonces are calculated twice? For example:

* 140 intensity, 32 worksize
* g_thd = 160
* nonce += 140

So 20 threads are wasted? I don't fully understand most of the cl code, maybe I'm missing something.

**Comment by psychocrypt** [comment]
If we round up than there is no memory for those threads created. The
threads are only started as dummies and will something lime deselected on
the device. This behaviour is nedded to be supported by all opencl
implementations.

**Comment by psychocrypt** [comment]
Nonces will not be calculated twice.

**Comment by jgillich** [comment]
Ok, so working as intended. Thanks!
